### ISSUE TITLE
Inconsistent behavior for model conversions

### ISSUE THREAD

**Issue by Dvogonen** [opentx/opentx#1025]
Scenario:
A model window is open. The model window has the same setting for radio type as the current profile (The normal case).

If the current profile is switched to a profile for another radio the models are automatically converted to the new radio type.

If the radio type in the current profiles is switched, the models are however not converted.

I can not see that either alternative is more logical than the other, but they are inconsistent.

**Comment by mpaperno** [comment]
Definitely fixed in 2.2.
