### ISSUE TITLE
OpenTX 2.0 user manual

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#1077]
There are **a lot** of changes and new features in 2.0. We should start writing a new manual based on r2940 existing manual. 

First step would be to gather in one place a rough note containing all changes/features.

**Comment by powercycle** [comment]
In case anyone reads this, it is now hosted on github at https://github.com/opentx/opentx-taranis-manual

**Comment by ckleanth** [comment]
i have made an update to the old manual based on OpenTx 2.0 (and its better than the old version) but I didnt have the time to finish it (and now we are at OpenTx 2.1..
anyhow here it is
https://docs.google.com/document/d/136JYUcMJwrNM60Pf6cIf274yDoFHzAS6hzt8fWdXN0s/edit

**Comment by powercycle** [comment]
ckleanth, from the looks of it, there is more here than in the newer version.  I'll do what I can to update the 2.0 manual with what works in the newer one.

Would you want to edit the new one as well?
bsongis, how would you like to move forward?
