### ISSUE TITLE
Add RF Module blocking mode switch to model instructions / checklist

### ISSUE THREAD

**Issue by TimGFoley** [opentx/opentx#1098]
We had discussed this in use forums so I thought I'd add it to a later version of firmware as a suggestion.

Could we look at adding a blocking mode switch/setting of some type that when the model notes/checklist is displayed, the selects RF module  is not powered up until the checklist/notes are read/cleared.

This is to remind people to connect external antennas for modules or internal if they have done the antenna mod.   Thereby preventing damage to the RF module should they forget to connect an antenna.

I'm sure there are other instances such as a reminder to plug in a specific module if the user has multiple, etc.

Thanks

**Comment by projectkk2glider** [comment]
Just a reminder that in case of a Watchdog reset this should be skipped

**Comment by kabturek** [comment]
i've added a simple warning on PR #3861 that reminds about plugging an antenna. not perfect but might be a good start.

**Comment by craigywsm** [comment]
Great idea,
Also a great idea if you want to test failsafe without switching radio off. An option to turn RF off and on (With connected warning) would be a great feature

**Comment by 3djc** [comment]
The OP feature has been implemented already, the module stays off while models notes are read
