### ISSUE TITLE
[OpenTx] Impossible to set Switch warning 

### ISSUE THREAD

**Issue by MicheleVilla** [opentx/opentx#1111]
In "Switch Warning"  menu is possible to set only up position of all switch

**Comment by stephendevelop** [comment]
Today, using latest software ( 2.2.1 ) on my Taranis X9D+ it still doesn't work.
Long press enter has no effect, short press enter only switch alarm on and off

**Comment by 3djc** [comment]
It does work, I just tested it. The full line need to be selected, long enter stores actual switchs positions

**Comment by stephendevelop** [comment]
Ok, long press while selecting the full line does work, thanks!
It takes the current state off all switches and stores them correctly
![screenshot_1](https://user-images.githubusercontent.com/34748704/38723162-855c842a-3f00-11e8-819f-751c624adff4.png)

**Comment by 3djc** [comment]
The ones you see without arrows ahev been 'single disabled'. Enter the line and activate one by one

![image](https://user-images.githubusercontent.com/5167938/38723255-c408334a-3f00-11e8-9911-6e005909785e.png)
