### ISSUE TITLE
New Multipos Switch Calibration Settings not handled in Companion 

### ISSUE THREAD

**Issue by borland1** [opentx/opentx#1126]
Recommend that for Multipos Switch(s), calibration settings be shown in OpenTX Companion as editable fields.  This is to support using a pot (S1 or S2) as a 5 or 6 rotary Multipos Switch.

The Multipos Switch calibration procedure only works with a 6-position sequential switch. Attempting to calibrate pots S1 or S2 as a Multipos Switch does not work because it does not prompt user for individual switch positions.

In OpenTX Companion, under General Settings, Calibration Tab, stick calibration settings can be read from the radio, edited, and then written back to the radio.  This is not the case for Multipos Switch which must be calibrated using the radio's firmware Calibration Menu.

**Comment by LapinFou** [comment]
I hope that this feature will be implemented in Companion. All my throttle security are based on the 6-pos switch (S21, S22, etc...) and it is annoying to not be able to test it under Companion.
I also hope this will be implemented in the 2.0.x branch.
:)

**Comment by LapinFou** [comment]
Any chance to implement it for the next 2.1.4 or 2.1.5 version???
It's really missing me.
:-)

**Comment by mpaperno** [comment]
This is all fixed in 2.2, unless I'm very mistaken. Reopen if needed.
