### ISSUE TITLE
Improvement  PPM1- PPM8 at Master  not only  PPM1- PPM4 

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#1132]
While working with Master/Slave at Taranis:

Think its importand to have at least PPM1 to PPM8 at Master settings 
not only PPM1 - PPM4 

Its Importand for calibrating the student's Tx 
at the master to use direct the PPM1 - PPM8 at the Mixer

PPM1 to PPM16 would be fantastic !!

Helle

**Comment by rguptaca** [comment]
For the  Apprentics S15e getting the student practicing to use the oops/recover switch would be usefull. A number of graduates from buddy box training don't use the recover because they have had no practice.  It is om ch6 I believe.

**Comment by kilrah** [comment]
That's already possible, you just have to do it separately in the mixer.
