### ISSUE TITLE
USB Mass storage very slow connect time to windows-XP SP3 swe

### ISSUE THREAD

**Issue by 483917** [opentx/opentx#1152]
Windows-XP SP3 Swedish ,USB 2.0
Taranis: OpenTX 1.99.4 ,haptic,Lua,sqt5font, Swedish
Companion 1.99.4 swedish

1. When i use bootloader USB-mass storage and plug in my usb cable it takes
30-40 sec to connect fully, i can hear the Windows USB connect sound after 1-2 sec  ?? Companion 1.52 was mutch faster 5-8 sec

2. And when i write "Models and settings" to Taranis it takes 1-2 minutes to compleat
sometimes i even get an IO timeout error from Windows

**Comment by 483917** [comment]
Thought an update regarding this issue would be good
//Original issue -------------------------------------------------------------------------------------
1. When i use bootloader USB-mass storage and plug in my usb cable it takes
30-40 sec to connect fully, i can hear the Windows USB connect sound after 1-2 sec ?? Companion       1.52 was much faster 5-8 sec
--------------------------------------------------------------------------------------------------------//
  This is pretty much the same, connect time 30-40sec , But 
//--------------------------------------------------------------------------------------------------------
2. And when i write "Models and settings" to Taranis it takes 1-2 minutes to complete
sometimes i even get an IO timeout error from Windows.
--------------------------------------------------------------------------------------------------------//
  This problem is gone ? I can write "Models and settings" to Taranis fairly quick 10-15sec without any
  "IO timeout errors from Windows" and no Companion crashes :+1: 
 
So this is not an big issue for me anymore

Windows-XP SP3 Swedish ,USB 2.0
Taranis: OpenTX 2.0.15 ,haptic,Lua,sqt5font, Swedish
Companion 2.0.15 swedish

**Comment by projectkk2glider** [comment]
Somehow it seems that this issue was fixed, closing.

**Comment by 483917** [comment]
Yes i confirm issue fixed
