### ISSUE TITLE
RPM Sensor for Multi engine plane

### ISSUE THREAD

**Issue by driver33** [opentx/opentx#1154]
I was thinking about if it is possible to build in many RPM sensors in one multiengine plane.
For HUB sensor its not possible however for future Sport sensor I think it is.
It of course requires some work from FrSky in hardware  (setting RPM sensor "address" and set at least 4 "addresses" for RPM sensor in Sport protocol).

In OpenTx i think its easy to support.

**Comment by projectkk2glider** [comment]
Done in 2.1
