### ISSUE TITLE
Send entire model file over trainer port!

### ISSUE THREAD

**Issue by brandonkal** [opentx/opentx#1159]
Ambitious idea but this should be technically possible.
To send a model setup from one OpenTX radio to another without using a computer.
Say you are in the field and you want to send a model config to your friend. Just connect the trainer ports and tell each radio to initiate either a send or receive function and then the sender would select the model(s) he wishes to send to his friend.

If anyone is interested in this idea I could design graphics and screen layouts.

**Comment by projectkk2glider** [comment]
Related to #2008

**Comment by brandonkal** [comment]
See you next month bot.

**Comment by brandonkal** [comment]
@kilrah has this been added?

**Comment by kilrah** [comment]
No, but since this issue is 5 years old it's just become clutter.

**Comment by brandonkal** [comment]
Still seems like a valid feature idea but okay...

**Comment by bsongis** [comment]
It's an interesting feature but I wonder what could be the speed of this link.
