### ISSUE TITLE
ease in/out function for camera gimbals

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#117]
_From [blastop...@hotmail.com](https://code.google.com/u/107672424216419636021/) on August 21, 2013 22:22:26_

On the taranis will be very useful for the use the Sliders to control the pitch or the roll of a gimbal, to implement a function adding a curve for slow the first movements of the sliders. So you can get from every position a very soft movement at the beginning of the camera travel until the end.

_Original issue: http://code.google.com/p/opentx/issues/detail?id=117_

**Comment by projectkk2glider** [comment]
This one is solved by clever Lua script http://rcsettings.com/index.php/viewdownload/13-lua-scripts/155-smooth-channel
