### ISSUE TITLE
Bootloader doesn't detect USB disconnection

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#1236]
From fourms:

```
Trim Manuever, turn on Taranis
Connect USB
Open Companion
Download models from Taranis to Companion
Make Changes in models
Save back to Taranis
Close companion
Pull out USB
Wait a few seconds
Turn off Taranis

Taranis will not turn off. I have to pull the battery.
```

And also:

> I never get the menu back. It just says 'usb connected' even with the cable pulled out. 

Looks like Bootloader isn't detecting USB cable disconnection.

**Comment by ChristianPloesser** [comment]
I have now the same problem after updated my Taranis plus to 2.1.0 from 2.0.17. It is an older Plus from 2014 and I updated it several times without any problems.
I tried Win7, Win 8.1 and Linux (all different Computer and at least 10 times). Nothing worked. But I can flash firmware with Companion, when the Taranis is turned off (STM 32 Bootloader), so the USB Hardware should be ok?
