### ISSUE TITLE
open tx telemetry accX,accY,accZ units inacurancy, also can we have a vector sum accXYZ and accXYZ+

### ISSUE THREAD

**Issue by ckleanth** [opentx/opentx#1244]
I'm not sure of the benefit of displaying acceleration in local coordinates perhaps a vector sum of the magnitude of the accelerations should also be available? for example parameter accXYZ that measures in G and please also add accXYZ+ accXYZ-
In order to retain the accuracy can the display show the value in G with two or three decimal points?

Also There is a bit of discrepancy when it comes to the measured accX,accY,accZ units 

I was told accX,accY,accZ units is G if you divide the measured value by 100 as mentioned here (https://github.com/opentx/opentx/issues/1138#issuecomment-44157907)

From telemetry comparison data shown below I disagree and initially I thought we should divide by 1000.
http://www.rcgroups.com/forums/showpost.php?p=28441097&postcount=3426

Regarding the data above I have videos of the flights shown in the logs and although I was doing KE spins I don't think I was pulling 4G, and the real G value must definitely be lower.
http://www.rcgroups.com/forums/showpost.php?p=28441122&postcount=2414
How low I don't know as the output data is not calibrated but its not /100 or by /1000 but probably something in between. Can we have this resolved in Opentx firmware or add a configurable calibration value on all axis to scale the values

**Comment by kilrah** [comment]
Lua script could do this.
