### ISSUE TITLE
Rotary Encoder support

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#1260]
According to Mike's guide here:
http://openrcforums.com/forum/viewtopic.php?f=97&t=5603#p79960

We could extend the "S1/2/3 Type" selection list to include "Rotary Encoder", and have RE1/2/3 available as a result in mixers etc.
And an item in General settings to choose which one to use for menu navigation.

**Comment by MikeBland** [comment]
Is this now available in 2.1 for the standard and plus Taranis?
SInce rotary encoder navigation is needed for the X9E, it should be fairly easy to add it to these with my mod.

**Comment by bsongis** [comment]
Still no, no time for everything, but I plan to noze your mods of course!
