### ISSUE TITLE
simulate TR channels

### ISSUE THREAD

**Issue by ChrissDE** [opentx/opentx#1270]
Hello,

it would be nice to simulate trainer/teacher inputs for TR1-16 (maybe with simple sliders or so on) to check the correct programming!

Thank you!

**Comment by ChrissDE** [comment]
Hi,

the first step is perfect, now it is possible to simulate trainer channel 1-4, for a quick test this helps! Thank you for your work! :)

One idea for the feature:
maybe it is possible to simulate all 16 trainer channels and use simple slider (not the stick input simulate), so everyone can simulate the mixes.

Background: i have a glider and wan't to fly it in trainermode, but I am not the teacher. A friend of mine uses a Graupner MX-** and is not able to bind with my glider. So I create mixes, that replace my inputs with the inputs of trainer. But in critical situations I have to switch by my own to the trainer inputs, that maybe result in crash. Now I use a switch on Graupner (CH7) and im my mixes I use TR7 for trigger the trainer mode. At the moment it is not possible to simulate this switch to check the function, I only can use it "online" with booth transmitter.

An other usecase: a cam operatorwants to trigger shutter with a switch. In mixes you define CH6 (for example) as trigger and want to simulate this input.

My idea of a simple input looks like this:
![trainer-sim](https://cloud.githubusercontent.com/assets/7880207/5735879/2a9628a8-9bce-11e4-8967-ff8f02424093.png)

Thank you very much! :)
Regards from Germany!
Christian

**Comment by projectkk2glider** [comment]
@ChrissDE I like your idea with the sliders and will implement it in the future...
