### ISSUE TITLE
Get cannot write destination access is denied

### ISSUE THREAD

**Issue by erieqc** [opentx/opentx#1281]
When I loaded 2.0.2 I can write models and setting to the tx 1 time then it wont let me do it again. Its been the same for all the 2.0 updates. I can read them back from tx no problem then try to write it right back and wont do it.

**Comment by specimenas** [comment]
I am not  sure how much it relates to your issue, but I can tell my case when was not able to write models to EEPROM... 
I am on W10
I have Turnigy 9x transmitter with Smartieparts usb mod. 
Transmitter has Atmega m128 chip, used USBasp driver
Have latest supported Open TX firmware for Turnigy 9x transmitter which is 2.19 
 And I was able to read and write firmware to  device , was able to read models from device, but not write: when writing my transmitter rebooted but still had the same models. 
     Once I tried to write models with box unchecked < Check firmware compatibility > in Write Models and Settings to Radio window popup and I succeeded!!! Simple box tick uncheck saved my nerves, I hope it might help to someone... :)
