### ISSUE TITLE
SH switch warning

### ISSUE THREAD

**Issue by banditpowdercoat** [opentx/opentx#1354]
I don;t know if it has been thought of, but some of us swap SH around for a maintained,  Or, even to just use the feature of having a switch warning upon startup for it.   There is a switch warning for all other switches.  I don;t see any reason not to have it for SH as well.  Would help great for us that use that switch for throttle hold.  I know one can swap wires and the labels.  But then your cutting labels and re gluing etc. As well as the TX simulator in companion now is backwards regarding those switches.  Might seem like a anal nitpicky thing, but you know how some of us hobbyists are.  Thats why were in this hobby LOL

**Comment by rcbebo82** [comment]
This is still a problem if you want the 2 pos switch on the right side with a X9D Plus. So why is this closed?

**Comment by banditpowdercoat** [comment]
I see it actually is fixed.  In 2.1.7 you go to the general edit tab, then hardware and you can change the types of switches there.  So, Swap the switch on the TX, then change the switch type in Companion

**Comment by banditpowdercoat** [comment]
I am mistaken.  There is the selections in Companion, but it does not change the simulator to toggle when I change the settings.  I selected SF to toggle and SH to 2 pos,  still has SH as toggle in Sim

**Comment by rcbebo82** [comment]
So all X9Plus Users have to something like this: http://www.rcgroups.com/forums/showpost.php?p=25722193&postcount=11
Man this is ugly!

**Comment by kilrah** [comment]
Switch assignment is indeed possible on the radio since 2.1.0, so no need for any rewiring and the reason why this has been closed.

The simulator does not take these settings into account but that's a whole other issue that has its own ticket as there are many other things to fix on it.

**Comment by rcbebo82** [comment]
This doesent help because i want warning on SH switch! So the only way is to change the switch from the left to the right side and keep the wiring. But that is not possible because the wires are too short!

**Comment by kilrah** [comment]
Warning on SH is supported.

**Comment by rcbebo82** [comment]
Got it! Switched the type of the switch under hardware then i got SH warning on companion! 
Thx!
