### ISSUE TITLE
a>b opentx 2.0.4

### ISSUE THREAD

**Issue by PieroCo** [opentx/opentx#1361]
a>b and a>x not return same value.

in this example GV1 is 20 but L1 is False and L2 true same with a=b and a<b

![image](https://cloud.githubusercontent.com/assets/7857600/3376082/4c411c1c-fbd1-11e3-9aea-5e007f8abce0.png)

![image](https://cloud.githubusercontent.com/assets/7857600/3376096/7497114e-fbd1-11e3-9ae1-eec53da46f3a.png)

![image](https://cloud.githubusercontent.com/assets/7857600/3376073/2ccb4c2c-fbd1-11e3-908e-ac7cf34ff40b.png)

**Comment by bsongis** [comment]
Refactoring explained in #3185
