### ISSUE TITLE
notification SF

### ISSUE THREAD

**Issue by andras** [opentx/opentx#1431]
How about a special function that pops up a text on the screen?  Maybe just a trigger for the checklist, but it would be nice to have something that displays text on the screen for announcements that you don't want to miss even when sound is off.

As an example, it would be nice if the radio displayed a message while throttle cut is active, so that you know what's wrong when you apply throttle and motor doesn't start and you've long forgotten that spoken throttle hold announcement.

**Comment by projectkk2glider** [comment]
Lets close this one and continue in #2013
