### ISSUE TITLE
documentation: defragment?

### ISSUE THREAD

**Issue by andras** [opentx/opentx#1432]
I've had a hard time gathering all information (as a user) about OpenTX.  There is a manual, but that's not quite up to date, and everything else is scattered around the place: Google code, wiki(s), forums, github, even worse, some users have their own websites with tips, such as Mike Shellim's "clinic".  Strangely enough for open-source software, there appears to be no documentation at all in the github repository itself.

I therefore claim that new users of OpenTX have quite a lot of work to do before they can fully understand the software and get a feel for the best way of achieving what they want in their model set-upts.

May I suggest that we streamline documentation?  My favourite would be a manual kept in the gihub repository in emacs Org format, which could then be rendered into HTML, PDF, etc., and which everyone can contribute to using github pull requests.  A Wiki would do just as well.

Then of course I suggest having a "how to" document of some sort, either in the form of a Wiki or simply another emacs Org file that gets rendered periodically into HTML and PDF.

RFC.

**Comment by andras** [comment]
Sorry for the late reply, I've been busy doing lots of other things in real life recently.

I really appreciate this move to LaTeX.  Having said that, may I seriously suggest that we also consider org-mode?  We don't need many of the features offered by LaTeX, in fact everything we need is already implemented in org-mode.  Org-mode also converts readily to HTML, not just PDF.

Having said that, I'd be more than happy to write LaTeX, but the HTML documentation might be a rather important aspect to consider.

**Comment by projectkk2glider** [comment]
Another option is https://readthedocs.org/ to publish HTML docs and create PDFs. With this we could use Markdown or reStructuredText that are also supported by github.
