### ISSUE TITLE
instant volume control, temporary quiet operation

### ISSUE THREAD

**Issue by andras** [opentx/opentx#1445]
On the Taranis, I find the lack of an easily accessible volume control rather inconvenient.  Therefore I have two suggestions:
1. Introduce a temporary "no-sound" mode.  This mode can be enabled by pushing a momentary switch (one of the trims, or SH) while powering up the radio.  The radio would then disable the volume-control menu in the global settings, and simply not emit any sound until powered off again.  If enabled, the no-sound warning would also appear.
2. Make a certain combination of switches trigger a volume-control popup during radio operation.  This could be, for example, simultaneous operation of two trims (both forward/aft trims up or down at the same time, for which you need both hands off the sticks and therefore being unlikely to be triggered during flight).  The regular +/- keys would set the master volume, "exit" or "ent" would return the display to its previous state.  This would be much quicker than browsing through the global menu.

I'm quite sure 1. would be possible and certainly a great feature for all those who like to do some quick tweaking after they've had an enlightening dream about OpenTX in the middle of the night without waking up your better half (and pocket-money authority).

RFC.

**Comment by fnoopdogg** [comment]
Hi, is there any progress on this, or a workaround for now?  This is a great project, but it seems slightly insane that you can't suppress the extremely loud sound coming out of the tx - it makes it unusable in quieter environments, or for developing at night/while the wife is watching tv etc
Is there any way of doing it through lua?

**Comment by andras** [comment]
I'm waiting for news on this as well.  What about my original idea of introducing a power-up key/trim/etc. combination that mutes sound until the next power-down?

I'm aware that you guys are busy adding other features, and the new telemetry is really superb, but this can't be that hard, and would add so much to the usefulness of OpenTX.

**Comment by weeeFPV** [comment]
what about loading a mute startup-sound and putting your volume control on a side-slider? i know, again, you have to do that for every model...but its kinda simple and you have the slider to be quick on muting if you forgot to turn the volume down in the first place (i installed a musicplayer via luascript and found out that my battery warning will be either too loud on the earphones or too quiet without on the field, so i played a little with programming a slider.. and if you don't mind the startup-sound its good. and what do you need startup-sound for? for knowing that you turned on your radio? downside is, with muting you might loose your inactivity alarm..

**Comment by stefanunz** [comment]
I would love this, too - being able to switch on my taranis without waking up the whole house :-) And I agree that it would be nice to be able to mute everything by some kind of startup keys, without reconfiguring everything in advance ...

**Comment by weeeFPV** [comment]
first possibility is to get rid of the startup-sound and then switch volume control to one of the potentiometers..

thats how i did it - except i still have a startup-sound..

**Comment by schwabe** [comment]
removing the startup sound defenitively helps (tada.wav or hello.wav) depending on the version.

**Comment by kilrah** [comment]
But then it's gone for good, not only for the few occasions where you want the radio to be quiet. 

I'd be favorable for the "hold a key during power up to mute all sounds" approach, could have used it myself a few times actually when quickly checking something at work. On Taranis you can just remove the SD but that doesn't work on Horus...

**Comment by lshems** [comment]
In my opinion it is not all that difficult: why not start the radio at the volume it was when we last shut it down? 

It will be the level corresponding to the active model during shutoff, and it makes sure that I can easily restore it to normal volume after startup, because I used some slider of whatever in this model setup to mute it in the first place.

It will not prevent the absurd loud Tada if you have your model volume on MAX, but who does?

In that way, if I set the volume down on my model, because I am testing stuff on my transmitter laying in bed next to my wife is looking at some horror movie, I don't scare the hell out of her after rebooting the radio.

**Comment by lshems** [comment]
In addition, you could make a menu entry in the bootloader to adjust the volume in bootloader mode,even if no sounds are used there (yet). 

If you then really don't want to have any controls on your model to adjust the volume, just boot it up in the bootloader one time, and adjust the volume there to apply on the next reboot.

**Comment by kilrah** [comment]
The bootloader does not have access to the settings. 

> In my opinion it is not all that difficult: why not start the radio at the volume it was when we last shut it down?

This would only help if last time you used the radio you anticipated that next time you'd pwoer it up you'd want it silent... i.e. never. If you were able to plan that you could already set the master volume down now.

**Comment by lshems** [comment]
What is the normal use case: 

playing around on the radio, set the volume down, do some stuff and then start the radio again for some reason or another.

So yes, I would find it normal that the radio would start in the last used volume level, and if in the meantime I change some slider that is used in the model to set the volume, some few instants after starting it would be at that level.

It would help me, and some of the others here, based on their info.

**Comment by lshems** [comment]
That's not what I am reading, but well, doesn't matter, right?

Merry Xmas and a happy newyear.

**Comment by Toymakr000** [comment]
I created and easy fix for the blaring out of the tada.wav..
I used Audacity and saved the tada file at 25% volume :)

**Comment by MattiParviainen** [comment]
I would LOVE to see this implemented and I must say I was ashtounded that it didn't have this function by deafult! (I just got my first Taranis).

I mean. First figting 1.5hours to get your daughter to sleep, you sit on couch, grab your Taranis for some simulator training/adjusting the modes etc and BLAAAAMM! Whole neighbourhood awake, including your daughter that has high fever and doesn't want to go to sleep. Great, just great!

So yeah, please, please, PLEASE! Add a function that allowes us to power up the darn Tx in silent mode with some switch pattern enabled.

**Comment by fnoop** [comment]
It's obviously never going to happen..

**Comment by lshems** [comment]
I have found the perfect solution: just put the middle wire of one of the pots directly on the gain of the amplifier chip. Did this on the X7, and freed one pot entry, that I used for my self installed slider on the place of the SF, that I moved to a pushbutton on the back in the grip. 
FLying DLG, so I have my 2 sliders available for camber and other stuff, AND a pot for hardware volume control, and a pushbutton on the back :)

Search the X7 forum on mods; Its an easy fix, probably also possible on the Taranis.

**Comment by MattiParviainen** [comment]
I was actually thinking about to do it like that too, or almost.
One extra pot to the top plate for HW control.
Push button would be awesome too!

**Comment by powercycle** [comment]
How about just putting a plug into the audio out?  Wouldn't that cause the sound to no longer be played through the speaker, thus effectively muting it?  
I've turned one of my pots into volume control, and it is set in a global function, but it does not lower the volume for the start up screens.

**Comment by kilrah** [comment]
> I've turned one of my pots into volume control, and it is set in a global function, but it does not lower the volume for the start up screens.

Set the volume down in the menu.
