### ISSUE TITLE
Telemetry "NO DATA" message

### ISSUE THREAD

**Issue by Didier-L** [opentx/opentx#1453]
Hello,

When using Taranis without a receiver performing telemetry function, we have a message "NO DATA" blinking in the lower part of the screen "Telemetry".

It would be fine to have a 3rd option in "Protocol" / telemetry page choice like "no telemetry" (currently D or S port). This 3rd choice would cancel the "NO DATA" blinking message.

And yes, I use telemtry screen even without telemtry (for timers numerical/bargraph view) :-)
Thanks,

Didier

**Comment by jrfoell** [comment]
Bummer that this got closed, I liked the idea.

Several receivers will send battery voltage, RSSI, etc without any bus data. Would be nice to at least make "NO DATA" stop blinking :)

**Comment by kilrah** [comment]
Then this doesn't apply since RSSI counts as data present.

**Comment by jrfoell** [comment]
I should have been more specific. I have a Flysky iA6 Rx that sends TRSS (similar to RSSI?), RQly (link quality?), and voltage. 

All of the telemetry screens blink "NO DATA" even with these values displayed.
