### ISSUE TITLE
read/write file capability for Lua 

### ISSUE THREAD

**Issue by ckleanth** [opentx/opentx#1471]
I was wondering if you can help.

I wanted to create a script/training tool that the user predefine a time history of stick input pattern (for example rolling harrier http://www.rcgroups.com/forums/showpost.php?p=28824025&postcount=10254) and the script will beep within some tolerance from the predefined path. 
 Also I wanted to implement a slow/speedup function

I have had a discussion with projectkk2glider how we would go about to do this using lua and basically (I copy/paste info here) we need read/write file capability to store reference stick movements that is to put them into some kind of log file.
The Lua script would then read this file and compare actual stick positions with recorded ones. You would of course have to have a very good algorithm that would detect if actual stick movements are ahead of behind the recorded stuff. But that is another problem altogether.

I'm an engineer, I can program but I'm no programmer and never came across lua up until it was introduced in OpenTx 2.0.

Can the developers please provide some help on how to implement this?

**Comment by jermoo** [comment]
+1 for io.lua

**Comment by bsongis** [comment]
Tests needed. I will add seek feature after first tests OK

**Comment by projectkk2glider** [comment]
Done
