### ISSUE TITLE
[LUA]  [feature]  "About" script functionality

### ISSUE THREAD

**Issue by davxlw** [opentx/opentx#1483]
Hi,

LUA scripts are incredibly powerful but it can be hard to remember exactly what they are doing and how to use them.

So it would be nice if we could define a special "About " zone in the script file itself, where we could put comments like:

```
-- About --
Who...
When...
What...
How to...
--End--
.
.
.
```

and these infos could be accessed by long pressing ENT or MENU ( like the actual memory display for one-time script ) from within the script running when we need to.

What do you think ?

**Comment by kilrah** [comment]
Script can now be viewed in SD browser so if the first lines include some doc it can be read on the radio.
