### ISSUE TITLE
Companion 2.0.5 - Custom Scripts Tab missing from Edit Model screen

### ISSUE THREAD

**Issue by franknitty69** [opentx/opentx#1488]
Edit a model.

There isn't a tab to edit to Custom Scripts (Lua).

There needs to be a tab to edit Custom Scripts.

**Comment by franknitty69** [comment]
resolved

https://github.com/opentx/opentx/issues/1609
https://github.com/opentx/opentx/issues/1673

**Comment by projectkk2glider** [comment]
@franknitty69 why did  you close this issue?

**Comment by franknitty69** [comment]
@projectkk2glider it was listed as a missing feature and the references 1609 and 1673 appears to have added the functionality. I assumed that this should be closed the .

**Comment by projectkk2glider** [comment]
No, those two issues were closed as being duplicates of this issue. The work was never done!

**Comment by u8mydog** [comment]
Will a Customs Script tab be added to Companion? I'm using Companion 2.1.7 on Windows and I do not see the customs script tab. I am able to add custom scripts within the radio simulation.

**Comment by kilrah** [comment]
Maybe, maybe not. You can add them (although the settings are lost when you close it), but you can also use the standalone firmware simulator that will keep them.

**Comment by RCdiy** [comment]
We need some way to make using mixer scripts more intuitive to the end user. One of the biggest selling points of OpenTx is companion so having to revert back to basically using the Tx interface is a step backwards. Having said that I understand that this is hard work and "someone" has to do it as a volunteer:)

**Comment by RCdiy** [comment]
A custom scripts tab with nothing more that the explanation of why there are no configuration options plus how to access it via the simulator would give a sense of completeness plus make it more intuitive for people using companion.

**Comment by kilrah** [comment]
It is technically not a simple thing to solve. 
The same is required for Horus UI customization, so if that ever makes its way into companion this issue would "solve itself" in the process.
