### ISSUE TITLE
Simulator switch warnings

### ISSUE THREAD

**Issue by mcfudge** [opentx/opentx#1497]
First off, guys, a huge thank you from Canada for making a really awesome programmable radio environment.  This is my first radio and I'm sure it will be my last!  I'm sure you already know this but you guys are doing a top notch job here!

I'm using Windows companion 2.0.5.  When I select Simulate while editing my model, I have to manually set all the simulator switches to my default settings each time.  Can you make the simulator automatically set the switches to my preferred switch warning settings that are on the Setup tab?

Can you make the simulator speak my speech files when the various special functions have been triggered to help me verify what real world operation will be like?

**Comment by mpaperno** [comment]
Setting simu switch positions from radio "check switch" settings seems awkward... how do you tell if this is the "first load" or not?   In my view, the simulator is like a physical radio, and it should remember its switch positions between uses (on my list to do), just like a physical radio would.

The simulator switch settings will be saved with the radio profile, which is now selectable at simulator startup (and of course in Companion).  So you can have different default switch positions per radio profile.

I suggest to close.

**Comment by mpaperno** [comment]
As of 6e2474081f216d255853cbec56a997d4ac8eab64, switch positions now remembered between uses, per radio profile.
