### ISSUE TITLE
companion enhancement drag and drop to open a file

### ISSUE THREAD

**Issue by ckleanth** [opentx/opentx#1519]
in the old companion we used to be able to drag and drop a file in the companion window to open a file. This is not available in OTX2+ (at least in windows version)
Can the feature be added please?

**Comment by kilrah** [comment]
Hmm it has always been there, and still is.

**Comment by ckleanth** [comment]
I don't think that it works with opentx 2.x companion

Date: Thu, 15 Jan 2015 00:57:11 -0800

**Comment by davxlw** [comment]
@ckleanth,
I can confirm it works with Companion 2.0.15 on win XP.

**Comment by ckleanth** [comment]
when we switched to QT it did not used to work. I noticed the issue near the time bernard fixed the mouse wheel changing values in drop down menus issue. I'm not sure when it has been fixed but yes it now works for me as on Windows 7 x64
