### ISSUE TITLE
Easy reorder of Logical Switch and Special Functions in Companion

### ISSUE THREAD

**Issue by shadowjig** [opentx/opentx#1536]
Can a feature be added to allow the user to reorder Logical Switch and Special Functions in Companion?  Maybe a 1,2,3,4,etc order or a drag and drop reorder?

Thanks.

**Comment by elecpower** [comment]
Great idea.

To address the resultant broken/errant LS references raised by @nigelsheffield you could take the spreadsheet approach where the app moves and updates all affected references. A not so small code change especially when it would need to check and update throughout a model's settings but it would at least not require adding other references.
