### ISSUE TITLE
Help user avoid corrupting his eeprom

### ISSUE THREAD

**Issue by Dvogonen** [opentx/opentx#1607]
The following scenario seems to have happened a lot lately:

* A user buys a Taranis and sets up his models using the standard firmware in the radio.
* The user decides to test Companion, connects and reads his models.
* He makes some changes and writes the models back to the Taranis.
* Companion writes the models in OpenTX2 format.
* The FrSky OpenTX version interprets the eeprom as corrupt and erases it automatically.
* All the models are gone and the user is unhappy.
* The user writes an upset post on RCgroups or openRCforum and everyone tells him he is stupid, which does not exactly make him happier.

Naturally the user should have updated the radio  to OpenTX2 first. But he receives no warning or information about this until it is to late.

A warning message in the burn dialog that informs the user that the firmware in the radio MUST be OpenTX2 would be a real improvement.

**Comment by kilrah** [comment]
Fixed in #1876
