### ISSUE TITLE
Special Function: "Range Check" and "Bind" Mode for Taranis

### ISSUE THREAD

**Issue by joshuabardwell** [opentx/opentx#1616]
I would like to be able to put the "range check mode" and "bind" functions for the internal transmitter on a switch on my Taranis, instead of having to navigate through the menus to get to it.

**Comment by kilrah** [comment]
For the record this is now available but requires compiling the firmware yourself with DANGEROUS_MODULE_FUNCTIONS=YES.

**Comment by joshuabardwell** [comment]
Awesome. Thanks for supporting those of us who like to live on the edge ;-)
