### ISSUE TITLE
Temporary hold SH switch down in Companion (Taranis)

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#1627]
In Companion, it would be nice if it were possible to temporary hold SH switch at its down position (maybe in a similar way as the Hold X and Hold Y boxes of the sticks) in order to simulate sequences like: SH-down / do something  / SH-up.

**Comment by fraternl** [comment]
Almost every right-handed DLG pilot that isn't afraid of opening the radio has moved that switch to the left.
It then becomes SF.

**Comment by ckleanth** [comment]
a hardware solution exists, its fairly easy and does not require any modifications to the firmware.
you can read about it here
https://docs.google.com/document/d/136JYUcMJwrNM60Pf6cIf274yDoFHzAS6hzt8fWdXN0s/edit#heading=h.fb7wt415v0jk

**Comment by fraternl** [comment]
What I meant with my comment is that each switch could become momentary. I wasn't satisfied with swapping SF and SH and now have replaced switch SE with a ON-OFF-(ON) switch. 

The brackets mean it's momentary.
This makes it ideal for DLG's if placed at the position of SF.

**Comment by rcbebo82** [comment]
I also swapped the switch SH with SF. I use it on the right side as "Throttle Hold". It's a pain in Companion to simulate with that switch going back to its position.
Companion should read the type of the switch from the general settings hardware tab. 
So then SF would become momentary and SH 2 way and all would be nice.
