### ISSUE TITLE
LUA extentions to enable heli wizard

### ISSUE THREAD

**Issue by ArchmageAU** [opentx/opentx#1647]
In order to create an LUA heli setup wizard, the following API enhancements are required:
- getCurve, setCurve
- insertMix, getMix must include curve data

Heli's require curves as both throttle and collective are controlled by a single stick (throttle).  Creating an LUA wizard for helis is impossible without the above functions.

Optional but desired:
- getHeli, setHeli (CCPM data)
- getInternalRF, setInternalRF
- getExternalRF, setExternalRF
- getTrainerPort, setTrainerPort

Being able to bind to the heli in the wizard enables proper guided setting of CCPM (required for flybarred helis and some flybarless ones).

Other desirable functions:
- getFlightMode, setFlightMode
- getModelSetup, setModelSetup (name, icon, warnings)

These enable creating more advanced functions (like named modes and model personalization).

**Comment by jermoo** [comment]
we need model.addInput() as well.

**Comment by projectkk2glider** [comment]
>we need model.addInput() as well.

Already available by`model.insertInput()`

**Comment by jermoo** [comment]
I can only get this to work for adding a line to an existing input. Perhaps my syntax is incorrect?
 local ivalue={name="test", source=MIXSRC_Thr, weight=55, offset=3}
two lines I've tried
  model.insertInput(4, 0,  ivalue) 
and 
  model.insertInput(4, ivalue)

if I change the line to 

  model.insertInput(0, 1, ivalue) 

it correctly adds the line to the first input as the 2nd entry.

Thanks in advance.

**Comment by projectkk2glider** [comment]
@jermoo you found a new bug, issue #2084 created for it.

**Comment by jermoo** [comment]
yay..

**Comment by u8mydog** [comment]
Also need the additional properties for insertInput.
For example:
inputName (vs line name)
curveType
curveValue
flightModes
carryTrim

**Comment by lshems** [comment]
Not stale as seen by recent demand for lua setflightmode support
