### ISSUE TITLE
Unable to setup release trainer by moving stick on Taranis as master.

### ISSUE THREAD

**Issue by tomkfly** [opentx/opentx#1652]
I used to be able to set up return from trainer by moving a gimbal stick, using the stick as source to release a sticky setup as the slave TX used to bypass the Taranis Sticks but now the slave stick acts as if it is a Taranis Stick. Example: Setting up a channel using ELE would only move the output when the Taranis stick was moved and not when the Slave stick moved. Now the Slave TX Stick changes the output of the channel and immediately returns control to the Master.

Tom

**Comment by nigelsheffield** [comment]
I just ran into this problem , took me a couple of hours of fueling to work it out, what's needed is access to master sticks while trainer is active,
Though this can be achieved on a per model basis it means a lot of work on each model to set it up rather then just getting the setting right once in trainer screen and it working across the models.
Perhaps a simple solution would be a option on the trainer screen for auto switching back to master if sticks are moved, as this is generally what we want to achieve?

**Comment by EmanuelStassar** [comment]
I like to be able to correct the student a bit while teaching. But if I move the sticks too much, I want to take control from the student completely. The only way to do this now is what is described above, by adding lines in each mixer for trainer inputs. If the special function "Trainer" is used, there is no longer a possibility to distinguish between the master or the students stick movement. It would be great if the stick values would still be just the master sticks if SF-Trainer is enabled.
