### ISSUE TITLE
GPS Time Zone

### ISSUE THREAD

**Issue by andytransonic** [opentx/opentx#1653]
Using Taranis Rev B OpenTx 2.0.8.
Can alter GPS Time Zone on Radio Setup in Integer steps only.
I live in Kolkata ( India ) which has UTC offset of +5:30.
Most countries have Integer offsets. But there are a few, which are offset by 30 mins.
Request firmware capability to handle such situations.

**Comment by Gordon65** [comment]
I would also like to see this added.
I live in Adelaide, Au. UTC +9:30
