### ISSUE TITLE
Settable inflexion point of expo curves (especially for throttle)

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#1654]
When you use expo on throttle, you may expect the expo curve not to be symmetrical but beginning at the bottom of the throttle throw.
Surprisingly, the Taranis doesn’t seem to do that (unless it is a well hidden feature!).
Of course you can do the job by yourself.
You can build a curve like this but, unlike built-in expo curves, you can’t call a GVar:
![courbe expogaz](https://cloud.githubusercontent.com/assets/8396899/4080483/10bafc9e-2edf-11e4-8ec6-76c02dac3790.png)

Or you can calculate your own expo with mixers like these if you need to use a GVar (with the advantage of having the same shape as a built-in expo):
![mixers expogaz](https://cloud.githubusercontent.com/assets/8396899/4080488/253ce664-2edf-11e4-9311-4b3728ffb895.png)

Oh my God! Seven lines instead of only one!
Please, somebody tells me there’s an easier way already!
If not, it would be great if the software gave the possibility to offset the center point of an expo curve.

**Comment by fraternl** [comment]
Having an exception whenever the input is based on throttle (which is already designated as a special stick) is IMHO safe.
The curve (on a Taranis) would show that the expo goes over the full length (-100 ~ 100).

I thought of using a little negative expo on an EDF reasoning that it doesn't do much in the beginning anyway. The expo could compensate for that. I have never actually tried this, so I might be wrong here.

The current implementation of expo has no practical use on throttle as far as I can see.
The proposed workaround doesn't result in a clean and transparent setup. I prefer to keep it linear then.

**Comment by fraternl** [comment]
I was wondering how other radios were handling this and checked a Spectrum and a Futaba. The Spektrum handled it like the Taranis does now, but the Futaba handled it like I described in my previous comment. 1 curve from -100 to 100.
On the other inputs it offers 2 expo settings for each side. This way you can have asymmetrical expo.
Never had the need for that, but.....

**Comment by pindeslandes** [comment]
A nice additional feature would be that:
- When you have checked the “Trim Idle Only” box,
- Changing the expo rate wouldn’t affect the idle point (neither the full throttle point, of course),
- And, in the other way, moving the idle point with the trim wouldn’t affect the expo curve’s shape (i.e. you would always have the full half of the expo curve (the 0% – 100% part) from the actual idle point to max throttle, whatever the trim position). I hope I am clear enough.

To illustrate, here’s the way I do that (maybe there's a simpler way but I didn't find):
- Input (use only the positive part of the expo curve and neutralize the bulit in trim function):
![capture1](https://cloud.githubusercontent.com/assets/8396899/11335706/e9d05f2a-91de-11e5-9f0c-5e7076810f38.PNG)

- Mix (rebuilt the "trim Idle Only" and apply expo rate):
![capture2](https://cloud.githubusercontent.com/assets/8396899/11335709/f3df62ea-91de-11e5-9900-cd5edaeeea2a.PNG)
