### ISSUE TITLE
Constant "beep" special function disappeard.

### ISSUE THREAD

**Issue by batzkass** [opentx/opentx#1679]
I'm using 9XR 128m 2.0.8.
Many times ago it was possible to set a constant steady beeping special function. Now it's only possible to get a short beep every 10, 20, 30, 40, 50 or 60 secs. However, it was useful to set for example a model low-voltage alarm, especially for people who don't have "Audio" nor "Voice" nor "Haptic" functions.
Thanks.

**Comment by batzkass** [comment]
Hi, at this time the feature I suggested (constant beep) is not implemented. Why is this issue closed ? I can develop it but I just need a little bit of help please : where may I find the beep special function code ? (the one which can beep every 0, 10, 20, ... 60 secs ?
After that, I plan to develop different beep (monotone) melodies.

**Comment by kilrah** [comment]
It's not closed, another identical issue was closed for being a duplicate.

Would probably be quicker to rewrite appropriate code than to look for how it was done as it's pretty much impossible to find when it became inactive.

**Comment by batzkass** [comment]
Sorry, I misunderstood the "closed" status.
I'm not looking for the old version of this function, but rather at the actual function that only make short beeps. I already tried to find, but the code is huge for someone new.

**Comment by kilrah** [comment]
See buzzer.cpp and the macros in buzzer.h.

**Comment by dkisselev** [comment]
+1, just got telemetry working and the single beeps make it difficult to tell between a voltage dip just from gunning the throttle, and actual low voltage.

**Comment by thatjoshguy** [comment]
Any progress on this at all?  Those of us holding out on the Taranis could really use this functionality.
