### ISSUE TITLE
Would like to add timer1 and timer2 in the log

### ISSUE THREAD

**Issue by deltasigma101** [opentx/opentx#1682]
HI,
Could you add the "timer1" and "timer2" in the log information.

The reason behind that it will permit, when we analyzed the log few days later, to find the duration of the flight and the interval between two "logs". 

This information are important for a pilot log book and for data remediation during an homologation purpose.

Jean-Guy

**Comment by deltasigma101** [comment]
Sorry, I follow the #194 but nothing about adding timer1 or timer2 in the CSV log with the version 2.1.9.

Could you revalidate the possibility do add the TIMERx into the CSV logs like any sensors

thanks

**Comment by 3djc** [comment]
I suggest you read the second message in #194,  timers are in there...

**Comment by deltasigma101** [comment]
I installed the 2.1.9 and start the logs and don't saw the TIMER1 or TIMER2 value
I checked to enable it like a sensor but don't see where we can activate the TIMERx into the logs since it's not a sensor.
The Date and time are there but no the TIMER1, 2 or 3
See the attachment. 
Maybe it's an user issue but didn't found any docs or interface to enable TIMERs into the logs.
Please let us know where to enable that

[H14-Wiris-1-2016-08-21.txt](https://github.com/opentx/opentx/files/548348/H14-Wiris-1-2016-08-21.txt)

**Comment by kilrah** [comment]
It doesn't exist. This issue was closed as the intent was to take care of it together with @194, but apparently it was forgotten when implemented.

**Comment by projectkk2glider** [comment]
Perhaps a more elegant solution would be to allow several more sources to be selected for the calculated sensors. If for example Timer1 was available as a source there, this would already work. User would create a new calculated sensor (add), define one source (tim1) and enable logging. Result would be in the seconds.

**Comment by kilrah** [comment]
To be fair the 4 "special" things (Batt, Tmr1-3) should be selectable everywhere telemetry is available, they're not THAT special...
