### ISSUE TITLE
Sounds on 9XR-Pro not working anymore (Release v2.0.10)

### ISSUE THREAD

**Issue by daJuels** [opentx/opentx#1690]
Tried to erase the eeprom to reset to defaults..
not working..

When browsing thru the explorer in openTX they play very short, and distorted.. after a short time no sounds anymore.

Flashed back to nightly build from 2014-08-30 04:06:33 (v2.0.10/ EEPR:216) -> Working like a charm.

**Comment by BobMarley100** [comment]
In the newest Version 2.1.1 the sound problem with the 9XR Pro is already there.
