### ISSUE TITLE
Improvement:   SF Adjust GVx  increment +/-1, better not only +/-1  increment a free setting value

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#1713]
Hy, 
At SF Adjust GVx Increment +/-1   is a nice funktion
It  works like   x= x+1  or  x= x-1
but only increment +/-1 

Would be much better for setting GVx  not only +/-1 fix    
value should be free, we can count in a free setting increment

We can set GVx   increment +5   or  -20  
and can count in larger steps the GVAR direkt.

Example
SF1  SHv   Adjust GV1  Increment +20
Result
GV1  -100 -80 -60 -40 -20 -0 +20 +40 +60 +80 +100

Helle

**Comment by bsongis** [comment]
Refactoring explained in #3185
