### ISSUE TITLE
Servo test screen in channels menu

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#173]
_From [TilmanBa...@gmail.com](https://code.google.com/u/102604845319663901187/) on October 29, 2013 16:35:45_

I was thinking about implementing this for a while. But I have been busy doing so many other things.

How about a sub screen where you can put the servo into test mode.
Cut off the input from the mixes and run either of three programmes:

1) Sweep left centre right. Stopping for instant at each end and centre 

2) centre mode

3) move by pot or stick.

The same screen should of course also allow you to set all trims and end positions for this channel. Because the purpose is of course to set those up, independently from mixes.

_Original issue: http://code.google.com/p/opentx/issues/detail?id=174_

**Comment by rguptaca** [comment]
Is this in the works?

**Comment by kilrah** [comment]
If you mean "has work started on it", no.

**Comment by rguptaca** [comment]
Just wondered. I just ordered a servo tester for under $10. As I get more experience in the hobby I wonder how you would account for servo binding. With a servo tester one can quickly change the setting or unplug it.

**Comment by kilrah** [comment]
You would set the limits first, then the test would sweep between those.
