### ISSUE TITLE
RSSI as mixer source with 9XR-Pro

### ISSUE THREAD

**Issue by daJuels** [opentx/opentx#1733]
Not sure if this is actually possible somehow.
I want to send the RSSI (from FrSky telemetry) to a defined channel.

In the mixer screen i can't select the RSSI as a source.
Does this need some changes in the source code?

**Comment by hurtz** [comment]
Is it possible to implement? I have a 9x running er9x with FrSky telemetry and would gladly switch to OpenTX if this were possible. Noticed you were involved with another person asking for the same thing here:

http://openrcforums.com/forum/viewtopic.php?f=122&t=6947

**Comment by kilrah** [comment]
This issue and the thread you linked are about the 9XR Pro that has a powerful ARM processor that would make it possible, but no chance on the 9x/9xr.

**Comment by hurtz** [comment]
Excellent, thank you for the response.
