### ISSUE TITLE
Enhancement: Any way to lock the buttons so, they don't get pressed accidently while flying

### ISSUE THREAD

**Issue by pberki** [opentx/opentx#1747]
It would be nice if there is any way to lock the buttons so, they don't get pressed accidently while flying 
Thank you

**Comment by rguptaca** [comment]
Should we not ne carrying the transmitter with our thumb holding the throttle down in which case pressing the keyboard is almost impossible. Even if there is a throttle hold/disable switch get in the habbit of carrying the transmitter this way.
