### ISSUE TITLE
Feature request: failsafe trigger (or disable radio module) in special functions

### ISSUE THREAD

**Issue by R5fan** [opentx/opentx#1761]
Reason Im asking for this is that I crashed a DLG while trying to test my failsafe servo positions in flight; when I turned off the radio, my plane unexpectedly dove straight down and it took too long for me to turn the radio back on and finish the boot sequence (not too mention that throttle or switch warnings might interfere in other cases).

So I thought it would be nice to be able to turn off the transmitter module and/or set failsafe positions (using X series receiver)  with a switch, so you can regain control much faster again.

**Comment by 4n41yz3r** [comment]
This feature would be extremely useful for my use-case as well. I'm developing my own flight controller that acts as a slave redundancy receiver. Unless the master receiver enters the FailSafe mode, the pulses from the slave receiver are ignored and there is no way to test the controller unless I power off the transmitter (bad idea). Further more, a simple FailSafe switch could be used to toggle the autopilot on and off in such configuration.
