### ISSUE TITLE
2.0.12 telemetry problem with 9XR-pro

### ISSUE THREAD

**Issue by mikes49** [opentx/opentx#1772]
I'm using Frsky- hub mode with FVAAS-02H altimeter and D8R-II Plus Rx.  RSSI, A1, and A2 values work perfect. Problem is altitude always reads 0. 

Pretty sure I'm wired correctly because I get correct altitude readings when I run Ersky rom 204, using the same setup.
Any help appreciated,

Mike

**Comment by kilrah** [comment]
Can you check with the current version again?

**Comment by projectkk2glider** [comment]
Closed due to a lack of activity.
