### ISSUE TITLE
Popup with list of options

### ISSUE THREAD

**Issue by andras** [opentx/opentx#1774]
There are many places in OpenTX where one item out of a list of many can be selected.  An example is the source for anything that requires an "on/off" input, for example the enable switch for a mix.  In this particular example, there are many choices and also types of choices (Sx, Lx, FMx, etc., plus their negations), which makes navigating the list rather cumbersome.  This not only applies to the Taranis, but other radios with rotary dials have the same fundamental issue.

Today, when an item to be set is activated by pressing ENT, it simply starts flashing.  I propose that, instead of flashing, a popup list appears that shows the currently selected value plus its immediate neighbours (however many the screen allows).  Here is a screenshot from the HP48 calculator, which does this really well:

![hp48menu](https://cloud.githubusercontent.com/assets/66469/4555300/c826aa08-4ebb-11e4-950a-4f0fc28294d1.png)

Note the little arrow showing that the list continues and can be scrolled down.

In this list, all valid items would immediately appear, and it would be much easier to (a) find your desired setting, and (b) for new users to see what other options can be selected that they haven't yet considered.

It's a matter of debate whether unselectable items (i.e., unassigned Lx) should appear greyed out or simply not at all.  I would probably vote for the latter because the list of unassigned Lx alone would more than fill the popup menu.

RFC.

**Comment by bsongis** [comment]
This one is done in 2.1!
