### ISSUE TITLE
On radio start wrong switch position is annunciated then correct position announced

### ISSUE THREAD

**Issue by JSGordon** [opentx/opentx#1775]
OpenTX 2.0.12 Taranis B with 6 position switch in S1 location.
Special Function Play Track is assigned to each switch position S11-S16
Program is set so S15 is initial required position.
When radio is turned on S11 position is announced even though switch is in S15 position.
Repeatable on 2 different Taranis models with same firmware.

**Comment by bsongis** [comment]
@JSGordon Are you available to test a fix. I don't have this multipos switch installed in my radio.

**Comment by JSGordon** [comment]
Yes I can test the fix.  How do I get the test firmware?

**Comment by bsongis** [comment]
I just manually launched a new nightly build, it should be ready in a couple of minutes

**Comment by bsongis** [comment]
Here:
http://jenkins.open-tx.org/nightly-20/01_09_2015/
