### ISSUE TITLE
Stuttering audio when telemetry screen running

### ISSUE THREAD

**Issue by lvale** [opentx/opentx#1779]
When running this telemetry script 

https://github.com/lvale/MavLink_FrSkySPort/blob/DisplayAPMPosition/Lua_Telemetry/DisplayApmPosition/Model_Name/telem1.lua

with all its associated files from here:

https://github.com/lvale/MavLink_FrSkySPort/tree/DisplayAPMPosition/Lua_Telemetry/DisplayApmPosition

if the telemetry screen is visible the audio prompts are stuttering.

When the script is running in the background the audio is ok.

![screen shot 2014-10-08 at 19 43 00](https://cloud.githubusercontent.com/assets/3130363/4584575/0c5048a6-4ffc-11e4-9c7d-bf89b103f171.png)

**Comment by projectkk2glider** [comment]
Just for the record. I had a stuttering problem today on my new Taranis X9E with the supplied 1G SD card. The stock card had no partition table, FAT32 started at first sector. I created normal MBR partition table and one partition, formatted with FAT32 and copied on files. The SOUNDS dir was copied first, then other dirs.

What I found out that some files would play normally while others would stutter badly. One example was file SOUNDS/en/SYSTEM/0000.wav. In fact all files from 0000.wav up to 0027.wav stuttered. 

When I copied the SOUNDS/en/SYSTEM/0000.wav to a different dir (on the radio) that copy played without any problem!

In the end I concluded that the position of the file on the SD card made a difference. I did some tests of the card speed and access times and they showed that some areas were much slower than others. After some more test the card started to give IO errors. So the reason for the stuttering in this case was a bad SD card.

![screenshot](https://cloud.githubusercontent.com/assets/5950438/11324903/50e36f90-913f-11e5-8e1c-42bf494f6e78.png)

**Comment by bsongis** [comment]
What is the program you used for this benchmark?

**Comment by projectkk2glider** [comment]
It's gnome-disk-utility on Ubuntu, not sure how it is called on Linux Mint

**Comment by bsongis** [comment]
Debian Stretch here anyhow :)

**Comment by bsongis** [comment]
Thanks!
