### ISSUE TITLE
An usefull mod/enhancement - VIRTUAL ADJUSTER SWITCH

### ISSUE THREAD

**Issue by robthomson** [opentx/opentx#1787]
I was pondering the use of the 'trim switches' in opentx, and the way in which with our glider setup we use them as virtual adjusted.

Now the problem I have is that I dont really like using up the trim switches.  It stops you using them as a trim!

So it struck me that there is an alternative.

We could swap any switch with one of these:

http://www.allelectronics.com/make-a-store/item/mts-79/dpdt-on-on-on-momentary-toggle-switch/1.html

Simply a   ON-OFF-ON momentary switch.

This would make the switch always return to center.   The result is similar to the action of a trim switch.

What would now make this really usefull is if we could assign on or more switches in the system to be used as 'ADJUSTERS'.

Then.. just like the trim switch, we can use them to adjust flight mode specfic 'trims'.   While not being used by the trims in any way, they could be used for ANY flight mode specific adjuster. 

So..   differential could be controlled on a flight mode by flight mode adjuster.

I personally would swap at least two switches for this function.

Rob

**Comment by projectkk2glider** [comment]
All that is requested here can be done with existing logical switches, closing.
