### ISSUE TITLE
not able to restore model on 9xr pro with companion on linux

### ISSUE THREAD

**Issue by blairfancy** [opentx/opentx#1793]
hi,
i m not able to restore modele to 9xr pro radio.
backup work properly i can see model on my radio but when i try to restore model radio is not updated.
companion and fw opentx 2.0.12

regards

**Comment by bsongis** [comment]
Did someone try with ersky9x and eePe for sky9x ? I am not sure it's an opentx bug.

**Comment by bsongis** [comment]
Did someone try with ersky9x (just copy the eeprom.bin with a simple cp command) ? I am not sure it's an opentx bug.

**Comment by blairfancy** [comment]
Hi Bertrand,
could you be more precise actualy there are only ersky9x.bin and firmware.bin on radio.

**Comment by bsongis** [comment]
Mike called the EEPROM "ERSKY9X.BIN" in his bootloader

**Comment by bsongis** [comment]
On Linux massstorage driver, the EEPROM starts at offset 11 instead of 3 (Windows)

**Comment by bsongis** [comment]
Ok I just added a dirty fix in Mike's bootloader and it works now on Linux, I will clean it tomorrow and send a patch to Mike

**Comment by powercycle** [comment]
Just to be clear, this IS a problem with linux and opentx with the 9XR running 2.0.10

**Comment by bsongis** [comment]
Since we use Mike's bootloader, yes.

**Comment by bsongis** [comment]
And ersky9x has the same problem obviously.

**Comment by bsongis** [comment]
@projectkk2glider bad news I am almost sure we have a problem with Taranis as well on Linux, but in the latest sectors of EEPROM (the 8 last ones)

**Comment by projectkk2glider** [comment]
@bsongis how are you getting your data? Do you have any usefull command to debug this? I plan to fire up wireshark and sniff usb packtets. I have found this command and with myy 9XE it says:
```
damjan@mambo ~ $ sudo hdparm --fibmap /media/damjan/TARANIS/EEPROM.BIN 

/media/damjan/TARANIS/EEPROM.BIN:
 filesystem blocksize 512, begins at LBA 0; assuming 512 byte sectors.
 byte_offset  begin_LBA    end_LBA    sectors
           0          3         10          8
damjan@mambo ~ $ sudo hdparm --fibmap /media/damjan/TARANIS/FIRMWARE.BIN 

/media/damjan/TARANIS/FIRMWARE.BIN:
 filesystem blocksize 512, begins at LBA 0; assuming 512 byte sectors.
 byte_offset  begin_LBA    end_LBA    sectors
           0         67        194        128
```

**Comment by blairfancy** [comment]
same command with 9xr pro
/media/blairfancy/ERSKY_9X/ERSKY9X.BIN:
 filesystem blocksize 512, begins at LBA 0; assuming 512 byte sectors.
 byte_offset  begin_LBA    end_LBA    sectors
           0          3        130        128

/media/blairfancy/ERSKY_9X/FIRMWARE.BIN:
 filesystem blocksize 512, begins at LBA 0; assuming 512 byte sectors.
 byte_offset  begin_LBA    end_LBA    sectors
           0       1027       1154        128

**Comment by bsongis** [comment]
The sector where the EEPROM start is stored is n°11
And we allow 3+(EESIZE+BLOCKSIZE) as a max. It means we skip the last 8 sectors.
And as a proof, if you dump on the bootloader screen eepromOffset, it won't be reset to 0

**Comment by bsongis** [comment]
My comment above is related to WRITE of course, not READ!

**Comment by bsongis** [comment]
[bertrand@localhost src]$ sudo hdparm --fibmap /run/media/bertrand/TARANIS/EEPROM.BIN 
/run/media/bertrand/TARANIS/EEPROM.BIN:
 filesystem blocksize 512, begins at LBA 0; assuming 512 byte sectors.
 byte_offset  begin_LBA    end_LBA    sectors
           0          3         66         64

[bertrand@localhost src]$ cp /tmp/EEPROM.BIN /run/media/bertrand/TARANIS/

[bertrand@localhost src]$ sudo hdparm --fibmap /run/media/bertrand/TARANIS/EEPROM.BIN 
/run/media/bertrand/TARANIS/EEPROM.BIN:
 filesystem blocksize 512, begins at LBA 0; assuming 512 byte sectors.
 byte_offset  begin_LBA    end_LBA    sectors
           0         11         66         56
       28672          3         10          8

**Comment by bsongis** [comment]
Above command BEFORE and AFTER doing a WRITE!!!

**Comment by bsongis** [comment]
It means that we can't skip the 2 first blocks without analysing them ... Unless there is a solution to avoid this fragmentation?

**Comment by bsongis** [comment]
I will try to give a bigger size to the virtual disk, it should work

**Comment by bsongis** [comment]
I now have to put some space between the 2 files EEPROM.BIN and FIRMWARE.BIN

**Comment by bsongis** [comment]
Now the cp works correctly, but a second cp is wrong

**Comment by bsongis** [comment]
I just found that if we open the EEPROM.BIN file in ReadWrite mode (instead of WriteOnly), it works perfectly on all bootloaders (no fragmentation)

**Comment by projectkk2glider** [comment]
Working here with 9XE and Linux. If I issue `cp eeprom.bin /<taranis mount>/EEPROM.bin && sync` I get:
```
No.     Time                       Source                Destination           Protocol Length Info
    842 2015-01-04 14:23:32.815878 62.1                  host                  USBMS    77     SCSI: Response LUN: 0x00 (Test Unit Ready) (Good)
    845 2015-01-04 14:23:33.685322 host                  62.1                  USBMS    95     SCSI: Write(10) LUN: 0x01 (LBA: 0x00000001, Len: 2)
    846 2015-01-04 14:23:33.685465 62.1                  host                  USB      64     URB_BULK out
    847 2015-01-04 14:23:33.685497 host                  62.1                  USB      1088   URB_BULK out
    848 2015-01-04 14:23:33.686663 62.1                  host                  USB      64     URB_BULK out
    849 2015-01-04 14:23:33.686695 host                  62.1                  USB      64     URB_BULK in
    850 2015-01-04 14:23:33.686846 62.1                  host                  USBMS    77     SCSI: Response LUN: 0x01 (Write(10)) (Good)
    851 2015-01-04 14:23:33.686898 host                  62.1                  USBMS    95     SCSI: Write(10) LUN: 0x01 (LBA: 0x00000003, Len: 64)
    852 2015-01-04 14:23:33.687082 62.1                  host                  USB      64     URB_BULK out
    853 2015-01-04 14:23:33.687146 host                  62.1                  USB      32832  URB_BULK out
    856 2015-01-04 14:23:36.650420 62.1                  host                  USB      64     URB_BULK out
    857 2015-01-04 14:23:36.650504 host                  62.1                  USB      64     URB_BULK in
    858 2015-01-04 14:23:37.138954 62.1                  host                  USBMS    77     SCSI: Response LUN: 0x01 (Write(10)) (Good)
    859 2015-01-04 14:23:37.139132 host                  62.1                  USBMS    95     SCSI: Test Unit Ready LUN: 0x00 
    860 2015-01-04 14:23:37.139353 62.1                  host                  USB      64     URB_BULK out
    861 2015-01-04 14:23:37.139365 host                  62.1                  USB      64     URB_BULK in
```

Which looks perfectly normal:
* update of FAT table SCSI: Write(10) LUN: 0x01 (LBA: 0x00000001, Len: 2)
* write all sectors of EEPROM.BIN starting at sector 3: SCSI: Write(10) LUN: 0x01 (LBA: 0x00000003, Len: 64)

If I then read eeprom from radio (with cp) and then write two more files to EEPROM.BIN I also get good results:
```
No.     Time                       Source                Destination           Protocol Length Info
    193 2015-01-04 14:44:00.896678 host                  63.1                  USBMS    95     SCSI: Write(10) LUN: 0x01 (LBA: 0x00000001, Len: 2)
    198 2015-01-04 14:44:00.898143 63.1                  host                  USBMS    77     SCSI: Response LUN: 0x01 (Write(10)) (Good)
    199 2015-01-04 14:44:00.898225 host                  63.1                  USBMS    95     SCSI: Write(10) LUN: 0x01 (LBA: 0x00000003, Len: 64)
    206 2015-01-04 14:44:04.349486 63.1                  host                  USBMS    77     SCSI: Response LUN: 0x01 (Write(10)) (Good)
    215 2015-01-04 14:44:04.350441 host                  63.1                  USBMS    95     SCSI: Write(10) LUN: 0x01 (LBA: 0x00000001, Len: 2)
    220 2015-01-04 14:44:04.351926 63.1                  host                  USBMS    77     SCSI: Response LUN: 0x01 (Write(10)) (Good)
    247 2015-01-04 14:44:09.168565 host                  63.1                  USBMS    95     SCSI: Write(10) LUN: 0x01 (LBA: 0x00000001, Len: 2)
    252 2015-01-04 14:44:09.169959 63.1                  host                  USBMS    77     SCSI: Response LUN: 0x01 (Write(10)) (Good)
    253 2015-01-04 14:44:09.170043 host                  63.1                  USBMS    95     SCSI: Write(10) LUN: 0x01 (LBA: 0x00000003, Len: 64)
    260 2015-01-04 14:44:12.621734 63.1                  host                  USBMS    77     SCSI: Response LUN: 0x01 (Write(10)) (Good)
    269 2015-01-04 14:44:12.622701 host                  63.1                  USBMS    95     SCSI: Write(10) LUN: 0x01 (LBA: 0x00000001, Len: 2)
    274 2015-01-04 14:44:12.624230 63.1                  host                  USBMS    77     SCSI: Response LUN: 0x01 (Write(10)) (Good)
```

**Comment by bsongis** [comment]
I have exactly the same USB traces here. But what gives hdparm after the copy is done on your computer?

**Comment by projectkk2glider** [comment]
Not so fast!

I've written a small python script to dump FAT12 clusters. When Taranis is read we get (only first relevant clusters shown for brevity):
```
cluster 000: last in this file (0xff8)
cluster 001: last in this file (0xfff)
cluster 002: next 003
cluster 003: next 004
cluster 004: next 005
cluster 005: next 006
cluster 006: next 007
cluster 007: next 008
cluster 008: next 009
cluster 009: last in this file (0xfff)
```
This is exactly how it is programmed in the source. The file starts at cluster 2 (first cluster for files) and continues to cluster 9. 

Now when I do a `cp` on Linux and watch what is then written to the FAT (wireshark) I get:
```
cluster 000: last in this file (0xff8)
cluster 001: last in this file (0xfff)
cluster 002: last in this file (0xfff)
cluster 003: next 004
cluster 004: next 005
cluster 005: next 006
cluster 006: next 007
cluster 007: next 008
cluster 008: next 009
cluster 009: next 002
```
So now Linux decided to start EEPROM.BIN on cluster 3 and end it on cluster 2! The contents are badly fragmented and your fix can not help here at all!.

In reality we can not expect a fs driver to put back the file contents in the same place it has been originally. And that is exactly what is happening here. So we can't rely on simple file copy to write an eeprom file in proper sequence. To do this correctly on every OS platform is even more unrealistic.

**Comment by bsongis** [comment]
My fix doesn't make cp work, but it forces Companion to open the file in ReadWrite mode, it avoids fragmentation. Tested on Taranis and 9XR-PRO.

**Comment by projectkk2glider** [comment]
>My fix doesn't make cp work, but it forces Companion to open the file in ReadWrite mode, it avoids fragmentation. Tested on Taranis and 9XR-PRO.

What about on Windows, Mac? Can you be sure it will work there the same, everytime?

An idea: we remember the new FAT (clusters 2-9) when OS writes it (this happens before the contents are written) and use it to map incoming sectors when they arrive. 

The same problem can happen with FIRMWARE.BIN. I wonder how it worked at all.

**Comment by bsongis** [comment]
Are you sure that the new FAT is written BEFORE the sectors themselves?

**Comment by projectkk2glider** [comment]
Nope. It was on my machine, but you are right it is not something to expect. Bummer.

**Comment by bsongis** [comment]
Then my fix is not too bad, it prevents an EEPROM starting at sector 11 from being written (as the last sectors would be skipped). It ensures it starts at sector 2 (which normally finishes at sector 66)

**Comment by projectkk2glider** [comment]
Yes your fix is good, it is better than before. But as it is some writes to the eeprom wont succeed. And we have no way of knowing that to inform user. Or is it? The bootloader knows. Maybe it could display this on the LCD?

**Comment by blairfancy** [comment]
Thanks for all your effort to make it working on linux ;)

**Comment by bsongis** [comment]
@blairfancy Do you confirm it works on your side?

@projectkk2glider Yes this is possible. We now have a variable 'operation' for the job in progress, if it stays on a non 0 value, there is a problem ...

**Comment by blairfancy** [comment]
unfortunatly i dont have toolchain ready to build new companion.
if you have .deb i can test it.

**Comment by projectkk2glider** [comment]
@blairfancy here is deb 64bit package built from 5c26f16dffcf0d00a232d2aa00c31c976ef95b53 http://jenkins.open-tx.org/downloads-20/test/companion_2.0.99_amd64.deb

**Comment by bsongis** [comment]
I mark it as fixed, feel free to reopen if needed, there is no perfect solution anyhow and I am afraid that a better solution won't fit in the 32k we are allowed for the bootloader

**Comment by blairfancy** [comment]
I have retreived all my seting with ERSKY9X.BIN i have dumped some day ago

**Comment by projectkk2glider** [comment]
Thank god, I was feeling really bad.

**Comment by powercycle** [comment]
Maybe I'm doing something wrong, but using companion 2.0.14 on Linux with 9XR I get this:

![screenshot - 01112015 - 12 43 55 pm](https://cloud.githubusercontent.com/assets/2614846/5696966/a81a73ce-998f-11e4-8e02-98d2ee6be5fb.png)

**Comment by bsongis** [comment]
Why don't you give an extension to your file?

**Comment by powercycle** [comment]
Guess I was doing something wrong...added .hex extension and it now works as I would expect it to.

Why would an extension be required?  It's linux, not normally needed.

Mike B.

**Comment by bsongis** [comment]
Avrdude doesn't like when there is no extension
