### ISSUE TITLE
Support for Ukrainian/Russian voice

### ISSUE THREAD

**Issue by maxsymba** [opentx/opentx#1797]
Hi.
Any estimation with SUBJ?
The matter is that for a correct pronunciation of numerals in these languages, etc., some rules are necessary. 
In current set of supported languages there are no suitable rules.
I am programmer (C#/C++/Delphi and so on...). 
Can I help with this task?
What is necessary for this purpose?
Best regards from Ukraine,
Max

**Comment by projectkk2glider** [comment]
Closed due to a lack of activity.
