### ISSUE TITLE
Individual cell values available for Lua scripts

### ISSUE THREAD

**Issue by lvale** [opentx/opentx#1799]
Currently we have the following values:

cell-min                 LiPo sensor - lowest current cell voltage [volts]
cell-min-min             LiPo sensor - all time lowest cell voltage [volts]
cell-sum                 LiPo sensor - current summ of all cell voltages [volts]
cell-sum-min             LiPo sensor - all time lowest summ of all cell voltages [volts]

Would be nice to expose the individual cell values to the Lua scripts.

brgds

**Comment by projectkk2glider** [comment]
Closed by #2826
