### ISSUE TITLE
Text editor in Companion

### ISSUE THREAD

**Issue by Scott-Page** [opentx/opentx#1809]
There are two levels to this idea.  The first and most simple is simply a text editor for SD card txt files that would constrain the text to the width displayed by the tx.  This may somewhat simplify documenting changes made in the model.txt file as well as keeping track of other notes that are not necessarily needed attached to a specific model.

The other level to this idea is to have an automatically generated change file generated as a .txt file to record changes made to specific model.  It could be names something like model_name_change.txt - with the name auto generated.  It may also be useful to have the model 'display checklist" automatically generated in the MODELS folder so the user can then edit it and be confident that the name will correspond with the model name.  

In general I think that the .txt potential for recording history, aircraft specs, etc is underutilized and these are some ways that this capability could be further enhanced.

**Comment by kilrah** [comment]
Got implemented in the meantime
