### ISSUE TITLE
Add lcd.drawEllipse to LUA function

### ISSUE THREAD

**Issue by Sacre100** [opentx/opentx#1817]
It would be great to have a function to draw an ellipse (or a circle) on LUA screen.

**Comment by Sacre100** [comment]
May I suggest the following code for drawing an ellipse.

    void lcd_ellipse(xcoord_t x, uint8_t y, xcoord_t w, uint8_t h, LcdFlags att)
    {
      int j, k;
      
      // Plot four cardinal points
        lcd_plot(x - w, y, att);
        lcd_plot(x + w, y, att);
        lcd_plot(x, y - h, att);
        lcd_plot(x, y + h, att);
      
      // Plot more horizontal part of the curve
        for (int i=1; i<=w*0.71; i++) {
          j = floor(h * sqrt(1 - pow(i / w, 2)) + 0.5); // check casting & math lib availability
          lcd_plot(x - i, y - j, att);
          lcd_plot(x - i, y + j, att);
          lcd_plot(x + i, y - j, att);
          lcd_plot(x + i, y + j, att);
        }
      
      // Plot more vertical part of the curve
        for (int i=1; i<=j-1; i++) {
          k = floor(w * sqrt(1 - pow(i / h, 2)) + 0.5); // check casting & math lib availability
          lcd_plot(x - k, y - i, att);
          lcd_plot(x - k, y + i, att);
          lcd_plot(x + k, y - i, att);
          lcd_plot(x + k, y + i, att);
        }
      }
    }


Code is NOT tested, casting and math lib availabity MUST be checked.
- x & y are the center of the ellipse.
- w & h are the horizontal & vertical radius.

**Comment by Sacre100** [comment]
For this function, may I suggest to use the Dresenham's code found here : https://sites.google.com/site/ruslancray/lab/projects/bresenhamscircleellipsedrawingalgorithm/bresenham-s-circle-ellipse-drawing-algorithm

I adapted it for OpenTx and tested it into the simulator (i don't have a spare radio to test it on the tx, sorry). Here is the result with lcd.drawEllipse and lcd.drawFilledEllipse : 
![drawfilledellipse](https://cloud.githubusercontent.com/assets/8712977/10564286/5a07b858-75ae-11e5-80f1-1a614bea648f.png)

The code added to lua_api.cpp for drawEllipse

    static int luaLcdDrawEllipse(lua_State *L)
    {
      if (!luaLcdAllowed) return 0;
      int xc = luaL_checkinteger(L, 1);
      int yc = luaL_checkinteger(L, 2);
      int width = luaL_checkinteger(L, 3);
      int height = luaL_checkinteger(L, 4);
      unsigned int flags = luaL_optunsigned(L, 5, 0);
    
    /* Bresenham's procedure to draw an ellipse in two steps */ 
      int a2 = width * width;
      int b2 = height * height;
      int fa2 = 4 * a2, fb2 = 4 * b2;
      int x, y, sigma;
    
    /* Plot more horizontal part */
      for (x = 0, y = height, sigma = 2*b2+a2*(1-2*height); b2*x <= a2*y; x++)
      {
        lcd_plot (xc + x, yc + y, flags);
        lcd_plot (xc + x, yc - y, flags);
        if (x > 0)
        {
          lcd_plot (xc - x, yc - y, flags);
          lcd_plot (xc - x, yc + y, flags);
        }
        if (sigma >= 0)
        {
          sigma += fa2 * (1 - y);
          y--;
        }
        sigma += b2 * ((4 * x) + 6);
      }

    /* Plot more vertical part */
      for (x = width, y = 0, sigma = 2*a2+b2*(1-2*width); a2*y < b2*x; y++)
      {
        lcd_plot (xc + x, yc + y, flags);
        lcd_plot (xc - x, yc + y, flags);
        if (y > 0)
        {
          lcd_plot (xc + x, yc - y, flags);
          lcd_plot (xc - x, yc - y, flags);
        }
        if (sigma >= 0)
        {
          sigma += fb2 * (1 - x);
          x--;
        }
        sigma += a2 * ((4 * y) + 6);
      }
    
      return 0;
    }

and for drawFilledEllipse

    static int luaLcdDrawFilledEllipse(lua_State *L)
    {
      if (!luaLcdAllowed) return 0;
      int xc = luaL_checkinteger(L, 1);
      int yc = luaL_checkinteger(L, 2);
      int width = luaL_checkinteger(L, 3);
      int height = luaL_checkinteger(L, 4);
      unsigned int flags = luaL_optunsigned(L, 5, 0);
    
    /* Bresenham's procedure to draw an ellipse in two steps */ 
      int a2 = width * width;
      int b2 = height * height;
      int fa2 = 4 * a2, fb2 = 4 * b2;
      int x, y, sigma;
    
    /* Plot more horizontal part */
      for (x = 0, y = height, sigma = 2*b2+a2*(1-2*height); b2*x <= a2*y; x++)
      {
        if (sigma >= 0)
        {
          lcd_line(xc - x, yc - y, xc + x, yc - y, SOLID, flags);
          lcd_line(xc - x, yc + y, xc + x, yc + y, SOLID, flags);
          sigma += fa2 * (1 - y);
          y--;
        }
        sigma += b2 * ((4 * x) + 6);
      }
    
    /* Plot more vertical part */
      for (x = width, y = 0, sigma = 2*a2+b2*(1-2*width); a2*y < b2*x; y++)
      {
        lcd_line(xc - x, yc - y, xc + x, yc - y, SOLID, flags);
        if (y > 0)
          lcd_line(xc - x, yc + y, xc + x, yc + y, SOLID, flags);
        if (sigma >= 0)
        {
          sigma += fb2 * (1 - x);
          x--;
        }
        sigma += a2 * ((4 * y) + 6);
      }
    
      return 0;
    }

If this code is OK for you, I will pursue my test.

**Comment by bsongis** [comment]
Good! Will you open a pull request?
If you have code to draw a filled circle with a start angle, and end angle it will be even better as I need it :)

**Comment by Sacre100** [comment]
A pull request !!!

I have to learn how to make it as I'm no more active on software development since more than ten years and things have changed ;-) I will ask help from @fred99

For start and end angle, I didn't find a good one yet. Trigonometry capability seems needed for. Do we have these available in OpenTx (sin, cosin, etc...) ?

**Comment by Sacre100** [comment]
> If you have code to draw a filled circle with a start angle, and end angle it will be even better as I need it :)

I didn't find any algorithm with start-end angles but I thought about and I have an idea how to make it using Bresenham's line and ellipse. 

@bsongis I have few questions before programming it : 
1) the algorithm will use sin and cos to calculate the start and end position, is this OK for you ?
2) do I write this in lua_api.cpp (availabe only for LUA) or do I add this into lcd.cpp (available every where) or somewhere else ?
3) if it's to add in lcd.cpp, do I add it for both version (9X and Taranis) or only for Taranis ?
4) do we need ellispe or only circle ? If we need only circle, I can use Andre algorithm which more simple and without hole when we draw concentric circle, but limited to circle

**Comment by bsongis** [comment]
@Sacre100 I did it in the Horus branch, would you have a look?

**Comment by Sacre100** [comment]
I saw the void lcdDrawCircle(int x0, int y0, int radius) function.

This algorithm has a flaw, though. If you try to draw several circles with an increasing radius (+1 pixel each time), you will notice some “blanks” in the result.

I think that you should consider the Andre’s algorithm which is quite similar to the midpoint version but which doesn't produce any blank hole when drawing concentric circle. You can find it here : https://fr.wikipedia.org/wiki/Algorithme_de_trac%C3%A9_de_cercle_d'Andres

Do you think that we need ellipse ?
And do you think that we need partial draw like this ?
![figure](https://cloud.githubusercontent.com/assets/8712977/10718476/d7aea15c-7b73-11e5-97a2-475f5c7edb34.png)

**Comment by bsongis** [comment]
For the moment I don't really need the lcdDrawCircle, I only use the lcdDrawBitmapPatternPie, which works OK. I am only missing anti-aliasing at start / end angles
