### ISSUE TITLE
settings for logical switches are sometimes changed by itself

### ISSUE THREAD

**Issue by wolkstein** [opentx/opentx#1834]
hi,
i noticed a strange problem with  logical switches. i have defined 6 Logical switches to get six flight-modes at my apm2.6 using switches SG and SD. I defined for each switch an function(and) V1 and V2 depending to switch position.
"And Switch", Duration and delay for all six  Logical switches are unused.

now the problem. if the taranis is powered longer than 30-45 minuts suddenly my LS settings are changed by self.  suddenly i can not switch back to first position(first flightmode LS1) . if i open the Logical Switches tab in model settings there is an And Switch Defined for LS 1. connected to !=SA↑.  what goes wrong. i using opentx 2.0.12

i noticed this bug two times(taranis uptime >30 minutes). but i can not reliably reconstruct the bug. mostly nothing happens although the taranis uptime is >45 minutes.

/g
wolke

**Comment by CaptainSwashplate** [comment]
Wow - quite the thread.
I was one (the only?) person reporting this problem in the forum 
http://openrcforums.com/forum/viewtopic.php?f=92&t=6178
Thanks for tracking it down. I have had my intentions changed externally last year in October but now updating everything and looking forward to trying the new firmware on easter. If everything goes well with the test-plane I'll go forward and convert the next models.
Thanks for your hard work!
