### ISSUE TITLE
LCD screen stays blank after power on

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#1849]
Report from forums, http://www.rcgroups.com/forums/showpost.php?p=29953267&postcount=879

> I have a first generation Taranis. Never had a problem. Today, several time while powering it up I would hear the welcome message, but the screen would stay blank. and nearly as I can tell, the radio would not transmit. Usually turning the power off and on again solved it. Running OpenTx 2.0.12 which so far (2 months) worked fine. Anybody has had issues like this before? The radio is 14 months old. 

Then another user:

> About 4 hours after I received my Taranis I experienced this failure. My supplier gave me an RMA number immediately, I returned the system and I was sent a replacement which has been good for two months now. 

And another:

> Mine which is 16 months old has just started doing the same. It seems to be when the temperature is quite low.

And another:

> Mine did that also in the beginning with the stock FW. Then once or twice recently since updating to 2.0.12. Temperature doesn't seem to be a factor.Turning it off then on again always corrected it. I thought perhaps the FW was not loading properly. Mine is the ver.B, about a year old.

**Comment by mgx0** [comment]
Hello after 4 years :) It's getting colder outside, is anybody having this problem again? I experienced it in temperatures below 15 degrees, repeatedly. I'm on the currently latest stable release of OpenTX, Taranis X9D (No Plus). Maybe something needs replacing, but is there anything I can check please?

I have had a pause in flying for 2 years, so I don't really know whether this problem would occur earlier or not :(

**Comment by raphaelcoeffic** [comment]
@mgx0 could it be that it's outside the specs of the LCD? -15° is quite cold for the poor LCD....

**Comment by mgx0** [comment]
@raphaelcoeffic nope that 15 was above zero 😊 i remember when this issue has been opened, it was around the same temperature.  And also turning off and back on the radio helped. And display never stopped working once started correctly until next shutdown. Same symptoms

Should I open new Issue? How do I find out whether it's an issue with my TX or general? My Taranis is one from the earliest X9D non-plus

**Comment by kilrah** [comment]
In any case it has nothing to do with the software...

**Comment by mgx0** [comment]
@kilrah could you prove your statement?

i can prove mine: this whole thread started with the same problem and has been fixed in the software. If I roll back to openTX 2.0.14, I have no problem, I just have found out

**Comment by bsongis** [comment]
@mgx0 given that on your X9D 2.3 is KO would you tell me if :
- 2.0 is OK / KO
- 2.1 is OK / KO
- 2.2 is OK / KO

**Comment by mgx0** [comment]
@bsongis I'll test it and provide the update. I have to put it into freezer after each upload. Give me a day or two

**Comment by 3djc** [comment]
I see you want to give us cold news ! (sorry, I could not resist)

**Comment by mgx0** [comment]
@3djc yes exactly, cold news :D

**Comment by mgx0** [comment]
Freezing news :P 

2.0.8 - NOK
2.0.13 - OK
2.1.0 - OK


continuing testing

**Comment by 3djc** [comment]
2.2.8 ? Not sure I remember us releasing that !

**Comment by mgx0** [comment]
soooorry, that's the cold 😄 typo, testing in progress. I'll post new reply with all versions tested.

Taranis is in the fridge for 20 minutes now, 2.3.1 is loaded. If it works alright, we're gonna close this thread. But I have experienced exactly same display startup failures like on the beginning of this thread. And I was one of the testers of the fix, so I remember how it looked like.

it might be a hardware failure of course. What then? could replacing display help? or where is the controller which is lazy to init when it's cold outside?

**Comment by mgx0** [comment]
So after 30 minutes in the freezer (Refrigerator, 7deg C) the display has booted up Even on 2.3.1

Like I mentioned,I have experienced display failures in colder (around 15 degrees C) environment, while radio has booted up normally without display. After testing, I'm not sure whether this is the same problem anymore. I suggest not to bother with it until few other people find and reply to this thread. In the meantime I'll continue testing but I don't want distract you people from doing lot more useful things. 

If I can ask for an advice, what can be faulty in my case and what could be the subject to replacement in this case?

Thanks and sorry for summoning this again

**Comment by bsongis** [comment]
If you live near here I would help to repair, I think I have the spare parts available.
Otherwise I would suggest a brand new X9D+ 2019
Better sticks, more RAM. But you will find more information on forums.

**Comment by mgx0** [comment]
Yeah I don't think you live within 1000km range 😊 but thanks for that, I'll see what I can do with it. I appreciate it

**Comment by mgx0** [comment]
If I may ask offtopic please, assuming that my problem with blank screen is faulty LCD controller, what should I try to replace? I don't want to give up D8 protocol, I have too many receivers and I don't want to use external module, to explain why I want to fix my X9D instead of buying a new one.

I know it's off topic of this issue but it's already closed. could anybody give me an advice please?
