### ISSUE TITLE
[OpenTX 2.1][Companion]List containing unwanted field

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#1856]
On Telemetry screen, there is many unwanted field.
See the attached snapshot.
![bug1tel](https://cloud.githubusercontent.com/assets/1685030/5123330/be88c9a2-70aa-11e4-88e8-4759b1fe395e.jpg)

**Comment by projectkk2glider** [comment]
I can't reproduce this issue anymore, looks like it has been fixed.
