### ISSUE TITLE
[OpenTX 2.x][Companion]Smooth curve not working

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#1859]
Well everything is in the title. :)
When editing a curve under Companion, the "Smooth" does not work. I noticed this for Companion 2.0.12, 2.0.13 and 2.1.

**Comment by projectkk2glider** [comment]
Duplicate of #1330

**Comment by LapinFou** [comment]
I probably missed something, but, do you plan to implement this feature in the OpenTX 2.0.x branch?

**Comment by bsongis** [comment]
No, 2.1.1

**Comment by LapinFou** [comment]
OK. Thanks for the update. Anyway, it is just a cosmetic feature.
:]
