### ISSUE TITLE
[OpenTX 2.1][Companion]French translation issue

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#1860]
When language is switches to French, many part are not translated yet. Here is a first list:
"Paramètres généraux":
- Global Functions instead Fonctions Globales
- Configuration/Écolage/Étalonnage tab: everything is displayed in English
- Etalonnage tab should be Étalonnage (capital 'é')
- Timer 3 should appear as Chrono 3
- Télémesure tab (maybe Télémesures ?): Sensors should be Capteurs,  Custom should be Personnalisé, Formula should be Formule. Instance should be "No Capteur", Precision=Précision, Range=Plage, Offset=Décalage, Persistent=Permanent. Then in the scrolling field, Raw=Données brutes, Voltage=Tension, etc...

**Comment by bsongis** [comment]
Ahh I did it for 21 and not 20
