### ISSUE TITLE
Differential not applied the same way in Inputs and Mixers

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#1879]
Taranis.
Since OpenTx 2.0, the offset in a mixer line is applied after weight and curve instead of being the first operation. And so it is for inputs.
Example with differential and offset on an input:

![screenshot-1](https://cloud.githubusercontent.com/assets/8396899/5220688/4d8c7054-7669-11e4-9449-10ff7cf8d639.png)

Easy to see that the offset is applied after the differential: all is right, so far.

Now if you do exactly the same in a mixer (-50 offset and 100 differential in that case), you will see that y stays to 0 when x < 50, meaning offset is applied BEFORE differential.
It seems that differential is the only exception: no such issue with other curves.

**Comment by bsongis** [comment]
We did something wrong here. The differential will be reworked in release 2.2.0
I revert this commit

**Comment by bsongis** [comment]
Part of the mixer rework done by @JivaroFAD
