### ISSUE TITLE
Lost model tracking using the display readout of GPS telemetry

### ISSUE THREAD

**Issue by Excaliburst** [opentx/opentx#1892]
What steps will reproduce the problem?
1. Crash your model softly so the electronics does not break
2. Look at your Tx - wouldn't it be great if you could use the telemetry data from GPS in model to track its location?

Please provide any additional information below.
I think you may be able to display telemetry data on screen that will help in locating a lost model:
1. RSSI signal streangth
2. On top of this feature in later HW implements than Taranis (that does not have built-in GPS) Comparing possible GPS coordinates from Tx (FrSky Horus) and the model GPS should give you a vector directly to the model - with both distance and direction.

**Comment by tedbmoss** [comment]
I have used just the signal strength and a very directional antenna (corner reflector for wi-fi) to find a downed model. This can be used with any tx that can have an external ant. attached. it works with frsky telemetering rx..

**Comment by teckel12** [comment]
I've created a Lua script that will locate a lost model if you're running INAV. It's available on the INAV repo under "LuaTelemetry"
