### ISSUE TITLE
Referencing Curve-names instead of curve#

### ISSUE THREAD

**Issue by Excaliburst** [opentx/opentx#1896]
Companion 2.0.12
Usability
All platforms

In the mixer screen it is not easy to distinguish between curves if you use many of them. This would be much easier if you in all screens in Companion that reference a curve, use the name of curve (if the name has been filled out), instead of the curve-no (which to most of us is gibberish).

This also opens up the possibility to reorder the used curves if needed, as they are referenced not with no, but names...

**Comment by richarddeweerd** [comment]
The curve names should also be visible on the Inputs screen.

**Comment by mpaperno** [comment]
Done in #4888.
