### ISSUE TITLE
Graphic model of the model in SIM-GUI as an addition to the servo outputs now showed

### ISSUE THREAD

**Issue by Excaliburst** [opentx/opentx#1899]
Companion 2.0.12
Usability
All platforms
SIM-GUI

Make a graphical representation like in the Wizard, when using the SIM to test throw direction and weights on mixes.

This GUI should have a simple means (right-Clicking on rudder surface) of reversing the throw direction without affecting the mixer settings, as this depends on the side of the servo-arm.

In the same spirit it should have a possibility to actually change direction of all related mixers (and showing the mixers contributing to this rudder-section), so mistakes in mixers could be avoided.

**Comment by mpaperno** [comment]
Closed as impractical/out of scope (sorry).  This is now talking about a Model (airplane) Simulator, not radio (out of scope).  Those do exist but naturally would take a lot of configuration to properly match an actual model (impractical).
