### ISSUE TITLE
Little display bug on French Firmware

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#1905]
Hi Folks,

For one for my model I need to display the current time on the telemetry screen. It is fine on the English version (Time), but in French the name "Heure" is too long and there is a graphical collision. See the attached picture.
To resolve this little problem, "Heure" should be only 4 characters, not 5.
May be "Heure" can be replaced by "H:M" or "H" or maybe the size font of the time must be reduced.
![issuetime](https://cloud.githubusercontent.com/assets/1685030/5339997/885331d8-7ee7-11e4-8bea-f1741f72cc03.JPG)

**Comment by LapinFou** [comment]
This bug is back on the 2.1.x branch.
Same issue as below on the 2.1.3 version.

**Comment by bsongis** [comment]
Same screen? Not "Heur"?

**Comment by LapinFou** [comment]
Not exactly the same screen. Indeed it is "Heur".
Sorry to have been inaccurate. :sweat:
