### ISSUE TITLE
[Companion] [Wish] Graphical Editor

### ISSUE THREAD

**Issue by teodoryantcheff** [opentx/opentx#1910]
The way OpenTX handles mixing (and all in general) is essentially a graph. Information flows from sources (inputs), via some "modification" and / or "computation" to  ouputs, which in turn can be the inputs of other such "blocks" and so on until ultimately a final "value" (another output) is computed. I've been thinking about it and in my view this is no different than what people do in video editing and compositing -- building [node graphs](http://en.wikipedia.org/wiki/Node_graph_architecture) with "sources" at one end and "result/s" at the other. E.g. :

![image](https://cloud.githubusercontent.com/assets/4791195/5358435/dadcf2ec-7fbc-11e4-9349-76fcd359d3ab.png)

I think it will be very cool of Companion could do this with the building blocks of OpenTX !

**Comment by geekness** [comment]
https://github.com/opentx/opentx/issues/2008
This is related
