### ISSUE TITLE
[Companion] Quick jump to edit curve screen

### ISSUE THREAD

**Issue by teodoryantcheff** [opentx/opentx#1911]
Now in companion, in the mixer edit window this is how using a curve looks like

![image](https://cloud.githubusercontent.com/assets/4791195/5359313/e22b5644-7fc4-11e4-928a-0cdac9d23a42.png)

For one to edit the selected curve, or even just see it, the mixer window needs to be closed, a switch to the curves tab made and the respective curve selected (yet another mouse click).
It'd be nice to have a small button there, in the mixer editor that jumps straight to the selected curve.

**Comment by bsongis** [comment]
Comments needed! I am not really proud of the result and I don't know it can be improved.
http://jenkins.open-tx.org/nightly-21/companionInstall_dock_2.0.99.exe
