### ISSUE TITLE
[Wish] A way to handle telemetry reset event within LUA script

### ISSUE THREAD

**Issue by Sacre100** [opentx/opentx#1913]
It would be great to handle the "telemetry reset" event within telemetry related script.

An idea is to have a "reset" function in addition to the "run" function. 
It's just one idea as there is many way to do this kind of things.

**Comment by RCdiy** [comment]
Yes!

**Comment by servicespringcorp** [comment]
Also, a way to know when the reset telemetry was run so certain values can be reset.

**Comment by teckel12** [comment]
Also, knowing when telemetry was reset within a Lua script so values can be reset in some way.

**Comment by teckel12** [comment]
While stale, I believe this issue should remain open.

**Comment by teckel12** [comment]
Bad bot!
