### ISSUE TITLE
More informative Lua error messages for telemetry scripts

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#1914]
For example in `master` (`next` doesn't even have this error message) user gets "Syntax error" for both true syntax error and out of memory error. At least these two should be separated. Ideally user could also see the actual reason for error (ie line number, etc) for problematic telemetry scripts.

**Comment by projectkk2glider** [comment]
Also separate error for wrong number of returned values would be beneficial.

**Comment by dsbeach** [comment]
I started looking at this today, but have not yet identified the code that implemented this in 2.0.x.

Can anyone point me in the right direction?

David

**Comment by bsongis** [comment]
![snapshot_04](https://cloud.githubusercontent.com/assets/5603504/10106385/a57c2a5a-63b4-11e5-875a-3a29c28d4b10.png)
