### ISSUE TITLE
Companion/SIM Easy way of debugging mixer input - that is clearly wrong

### ISSUE THREAD

**Issue by Excaliburst** [opentx/opentx#1922]
I would like to see in Companion, an easy way of debugging when a mixer/LSwitch is clearly not doing as expected. 

If I had a debug funtion in the SIM, that could show me at any given time, switch pos, LSwitch pos, what is contributing to the servo input. Then the erroneous servo position would be much less to decipher.

An example:
I know my R Ail servo is good and behaves as expected, but when I insert a trigger from a switch that enable a certain mixerline, it behaves badly and its position goes from -50% to +50% (my 2 extremes in this setup).

I would like to have a (dockable) window showing me for any channel that I chose, which mixer lines contribute with what percentages at every flick of any switch in real-time. This way troubleshooting mixers/LS would become faster/easier.

**Comment by projectkk2glider** [comment]
I don't think we can make anything useful here, closing.
