### ISSUE TITLE
New Features (Color touch-screen) support - FrSky Horus?

### ISSUE THREAD

**Issue by Excaliburst** [opentx/opentx#1932]
Proposal for OpenTx 2.2 FW for the FrSky Horus and other HW with these features.
Label: Enhancement

Is color touch-screen support in the pipeline for OpenTx? I know that mhotar is working on something for the colorscreen of the FrSky Horus.

Should we open an issue for this, or will it automagically land in OpenTx eventually!?

Apparantly the FrSky Horus will ship with a proprietary OS from FrSky supporting both touch- and color-screen. But most people will surely want to switch to OpenTx on this Tx right from the get-go. So we should make sure that OpenTx supports the new HW features.

In another thread https://github.com/opentx/opentx/issues/1608#issuecomment-65893984 I read about maybe switching to icons for the settings menu in Taranis. Here are a couple of very nice screen proposals from mhotar.

Other features are 
- Touch-screen. Possibilities are endless. buttons and even rotary programming widgets become obsolete with one stroke. Instead all values could be 'dragged'/swiped to the right value just by pointing on any setting/value and dragging up for increasing value or down for decreasing value. This operation could even have acceleration builtin, so that if you do the swipe fast it would jump 5% at a time. 
Alternatively values could be swipe-adjusted like described above, but for small values, pressing with your thump on the value and turning your finger would slow-adjust the value.
Or you could drag the value op/down for single digit adjust - Left/Right adjusting 10's at a time (faster rate) 
And/or actual volume music admin via part of the large screen real-estate.
![image](https://cloud.githubusercontent.com/assets/10078661/5427339/c51f7170-8398-11e4-9090-093a3bba5e29.png)

- All matter of swipes are possible we just have to determine which should be used for what
![image](https://cloud.githubusercontent.com/assets/10078661/5427360/3ec45bc6-8399-11e4-85b8-31a99dbc89f1.png)

- BT, (exchange models wirelessly with other OpenTx pilots)
          Wireless pupil-flying
- Built-in GPS, for tracking lost model with vector to model

**Comment by geekness** [comment]
This is similar to my open ticket.
https://github.com/opentx/opentx/issues/2008

Im proposing to be able to access the menu with real time send/receive from an external machine with touch interface.

**Comment by Excaliburst** [comment]
As I see it your ticket adresses only a small subset of what this ticket could. I was addressing all new HW opportunities with the touch-screen (UI), GPS (lost-plane-locator using the Tx GPS to track model (Rx) GPS and direct pilot directly to model with indications on screen, vector and distance), Networking (WiFi, Bluetooth), possibly new types of switches (on Horus). 

With this set of HW in the Tx, it is only imagination that limits us. So please chime in, to help create the most attractive Radio on the market.  :+1:

**Comment by kilrah** [comment]
All of these things are on our list indeed... but it's just a bit early. Unless more people join the effort that list would probably represent 2-4 years of development.

**Comment by geekness** [comment]
@Excaliburst you are right, but my ticket suggests adding the required feature of being able to access the menu "remotely". You can't have an external touch screen to manipulate the menu, without first having the ability to send/receive the menu items.

The app you suggest looks great, and I think having the features requested in https://github.com/opentx/opentx/issues/1910 will make it awesome!! I hope it one day becomes a feature.

@kilrah, 2-4 years of development? Far out. I want to help, just not really sure where to start.

**Comment by kilrah** [comment]
@geekness you're talking of using an external computer with all its power and existing libraries to configure things, which using an interface between opentx and said device can be done relatively quickly. 

But this issue is completely different, it is about integrating all said functions into opentx itself, which does not have a full-blown operating system and much smaller resources. I.e. redesign the entire interface (after integrating the relevant functions needed to do so), integrate network stack and drivers, finding ways to do useful things with them and integrate that with the rest of the functions... i.e. a whole lot of things of significantly higher complexity than anything that is in the firmware right now. That's what will have to be done for radios like the Horus, and it will take long.

**Comment by geekness** [comment]
@kilrah, you are correct, thanks for taking the time to expalin it to me.
It certainly does sound like a lot of work.

**Comment by kilrah** [comment]
#2943

**Comment by Excaliburst** [comment]
I am quite certain that this ticket should not be closed at present. As it pertains to all the new HW features available and they should be implemented when the Horus is available to the programmers of OpenTx.

@kilrah Please enlighten. Geekness is not the originator of this ticket. He refers to his ticket and should have replied in that thread. This one is still very much in demand. Please reopen.
And thank you for your efforts.

**Comment by kilrah** [comment]
Makes no sense to have a ticket that basically says nothing but "do cool things" like this one, that's just obvious. 
We'll open separate tickets for each actual feature or concern.

**Comment by bsongis** [comment]
Right I also prefer if we open issues when we have something to show and debate. We are even not sure Horus will have a touch screen!
