### ISSUE TITLE
Taranis  and Taranis Plus   Ext. Modul setting +/- CPPM wrong 

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#1937]
Taranis  and Taranis Plus   both openTx V2.013

Setting of ext Modul  PPM Protokolll
22,5ms 300us   + or -  for rising Edge and falling Edge of CPPM startimpuls ist wrong
 Plus    + must be rising edge  of CPPM-Signal, but its falling
 Minus  - must be falling edge of CPPM-Signal, but its rising 

------------------------
Setting  of Master / Trainer Slave PPM Protokoll is ok
Plus     + is rising Edge
Minus  - is falling Edge

Have both measerd today with a Digital Oszi

HRenz

**Comment by Mow06** [comment]
This doesn't appear to have been changed. Module bay PPM on 2.0.15 is same as previous firmwares.

**Comment by bsongis** [comment]
@projectkk2glider You forgot to modify ppm_arm.cpp!

**Comment by bsongis** [comment]
(my fault, this part in ppm_arm.cpp should be in the driver, not there)

**Comment by projectkk2glider** [comment]
The solution to this issue looked very simple. Unfortunately nobody tested the fix before it was merged. I was counting on @hrenz to do that. 

From the reports on forums it looks like I made change to trainer output and not to the external module. I will do the test myself today in the evening.

**Comment by kilrah** [comment]
No you did right, but apparently only in the next branch, didn't replicate the commit in master

**Comment by projectkk2glider** [comment]
Isn't commit c9e66c950228dcc705f064f2a8140586b5591c3d on the `master` branch?

**Comment by kilrah** [comment]
Yup, see edit.

**Comment by projectkk2glider** [comment]
I see! I missed as spot in `void setupPulsesPPM(unsigned int port) `:
```c
  else if (port == EXTERNAL_MODULE) {
    TIM8->CCR2 = rest - 1000;             // Update time
    TIM8->CCR1 = (g_model.moduleData[port].ppmDelay*50+300)*2;
    if(!g_model.moduleData[EXTERNAL_MODULE].ppmPulsePol)
      TIM8->CCER |= TIM_CCER_CC1NP;
    else
      TIM8->CCER &= ~TIM_CCER_CC1NP;
  }
```

**Comment by projectkk2glider** [comment]
We seem to have some redundancy/error in the code. The `init_pa7_ppm()` calls `setupPulsesPPM()` but after that it messes with the polarity setting on its own. Shouldn't polarity and all other timer parameters be set in one place and called only once (at init and at every mode change) and not like it is now in multiple places?

**Comment by kilrah** [comment]
Yep it's duplicate code. 

Ideally it would be set once in the driver and that's it. If it has to be changed, then stop the PPM, then start the PPM again as we do for a change in "main" protocol (see setupPulses() in pulses_arm.cpp).

As you'll see required_protocol only looks at  g_model.moduleData[].rfProtocol, not the polarity that is stored elsewhere. 

The duplicate code in setupPulsesPPM were just a quick and dirty way to make it work in a hurry at some point. Fixing setupPulses needs a bit more thought than copying a 4-line block if you want to make sure not to break other platforms.

**Comment by projectkk2glider** [comment]
Thanks for confirmation and explanation. I will tackle this carefully and measure the result. Expect to see something in the near future.

**Comment by kilrah** [comment]
:+1:

**Comment by projectkk2glider** [comment]
@kilrah Should I also remove **internal module PPM** related functions in Taranis driver, because as fas as I can see the PPM option is not selectable for internal module anywhere.

**Comment by projectkk2glider** [comment]
On a side note, while I was testing my changed I also scoped the PPX signal to the external module. Here is how it looks:
![figure_1](https://cloud.githubusercontent.com/assets/5950438/5843249/734e39d6-a1ab-11e4-839a-78d8054938fb.png)

As you can see we have quite a long rise time compared to the bit time. I say we are right at the border here. This could potentially cause issues down the road.. What do you think?

**Comment by kilrah** [comment]
> @kilrah Should I also remove internal module PPM related functions in Taranis driver, because as far as I can see the PPM option is not selectable for internal module anywhere.

I think it can be left there, AFAIK some people have been using it in their self-compiles.

> As you can see we have quite a long rise time compared to the bit time. I say we are right at the border here. 

Not much we can do, it's due to the hardware... and it works.

**Comment by projectkk2glider** [comment]
>It might actually look better once you connect an XJT due to the pull-up in it.

You are right, any additional pull-up will improve this.

**Comment by projectkk2glider** [comment]
I will port this to `next` later.

**Comment by bsongis** [comment]
@hrenz would it be possible you do the tests on 'master' before we port it to 'next'?

**Comment by projectkk2glider** [comment]
Just for the record, I tested `master` at https://github.com/opentx/opentx/commit/6975eef35da04afa2cf7626d7f2effe44b8ae0d2 on scope and everything is OK.

Now we wait for @hrenz test.

**Comment by projectkk2glider** [comment]
Code changes for this are done both on master and next branches. What is still missing is a better user notification about this change, the agreed way was described in https://github.com/opentx/opentx/pull/2035#issuecomment-71172758

**Comment by kilrah** [comment]
Done in https://github.com/opentx/opentx/commit/5027eac7b3d7598c107cf175edcaeaa95e5e2a6c
