### ISSUE TITLE
[Companion] [Wish] Double RMB to reset pots to 0

### ISSUE THREAD

**Issue by teodoryantcheff** [opentx/opentx#1939]
Title says it all.. I'd like to be able to reset the virtual pots to the 0 position (where it would beep center on the physical transmitter) the same way trims are reset to 0 -- double right mouse button click.
Along these lines -- is there a particular reason to choose double rmb over the normal double click ?

**Comment by romoloman** [comment]
The reason for right button is that right button is ignored by the normal qslider or qdial control, so  when you release the button the release event is ignored by the parent class.
If we would have implemented doubleClick on left button, then on release the slider will move to the release point vanishing the effect of reset.

**Comment by teodoryantcheff** [comment]
OK,  understood.  Thanks for the explanation.
