### ISSUE TITLE
Batt values omitted from telemetry logs 

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#194]
_From [barry.m....@gmail.com](https://code.google.com/u/114629264712523158321/) on November 30, 2013 07:07:47_

Which board (stock / gruvin9x / sky9x / Taranis) are you using? What is your openTx FW version? r2834 What is your openTx EEPROM version? 215 What steps will reproduce the problem? Telemetry parameter 'Batt' is used to show the transmitters operating voltage (battery level) and can be configured to show on custom telemetry screens.

When logging telemetry data to csv file using the custom function SD Logs, Batt values are not recorded along with other transmitter data(stick, switch, and slider positions). What is the expected output? What do you see instead? Since Batt is configurable on custom telemetry screens, I expected to see Batt values recorded along with other transmitter data on the csv file.  Instead, it is omitted. Please provide any additional information below. none.

_Original issue: http://code.google.com/p/opentx/issues/detail?id=189_

**Comment by projectkk2glider** [comment]
Not relevant anymore, with 2.1 every sensor can be logged.

**Comment by kilrah** [comment]
The radio battery voltage still can't though ;)

**Comment by projectkk2glider** [comment]
Uff, you are right!
