### ISSUE TITLE
[OpenTX] [Taranis] Shortcuts keys don't work correctly in timers switches

### ISSUE THREAD

**Issue by davxlw** [opentx/opentx#1940]
![screenshot-1](https://cloud.githubusercontent.com/assets/7569433/5471051/0181b380-85f1-11e4-9388-0848d46b0fc5.png)

- [MENU] + [PAGE]  -> OFF => Ok

- [PAGE] + [EXIT] -> !FM8 (manually I can't select past !FM0 as I don't have set any Flight Mode) => **wrong**

- [-] + [ENTER] -> FM8 (manually I can't select past FM0 as I don't have set any Flight Mode) => **wrong**

- [+] + [-] -> SF↑ becomes !SG↓ => **wrong**

-OpenTX 2.0.14 (self build)
-Taranis B

**Comment by bsongis** [comment]
As soon as tested on 'master' branch I will port it to 'next' if OK.

**Comment by davxlw** [comment]
:+1:
