### ISSUE TITLE
[OpenTX] [enhancement] Pauses when long press [+] or [-] for selection

### ISSUE THREAD

**Issue by davxlw** [opentx/opentx#1942]
It could be convenient to have pauses between values of different kind when maintaining [+] or [-] keys for scrolling through list. (like those we already have when reaching -100, 0 or 100 for numerical values)

eg. for switches selection:

Physical switches
_\* pause \*_
Trim switches
_\* pause \*_
Logical switches
...

**Comment by bsongis** [comment]
@davxlw If you are programmer, this feature is now really easy to add, have a little search in the code on stops100 (which makes a pause on -100, 0, 100). We now can introduce as many pauses as we need! Would you have a look?

**Comment by davxlw** [comment]
I can't say I'm a programmer but I will have a look for sure...

**Comment by davxlw** [comment]
Ok, I've tried to implement stops in FM switch selection but it's only half working.

With these settings: 
```_stopsModelSwitch[] = { 5, -SWSRC_FIRST_LOGICAL_SWITCH, -SWSRC_FIRST_TRIM, 0, SWSRC_FIRST_TRIM, SWSRC_FIRST_LOGICAL_SWITCH }```

When pressing [+] or [-] from ---, the pause is at the right switch but if we go from the max or min value to ---, the pause is at the same switch as before, which is not what we want.

The value must pause at each switch type change and not at a particular switch. I think the `struct CheckIncDecStops` would have to be modified...

**Comment by bsongis** [comment]
Ah yes, what I implemented are sticky values, we need something else here

**Comment by bsongis** [comment]
@projectkk2glider this one is for me ;)

**Comment by projectkk2glider** [comment]
Ok, ok, I will let you have it. :)
