### ISSUE TITLE
[OpenTX] [Companion] [enhancement] MIXERS MONITOR

### ISSUE THREAD

**Issue by davxlw** [opentx/opentx#1945]
In the mind of #1399, it could be handy to have MIXERS MONITOR to see clearly what's going on, without being distracted by the servos settings:

![channel_monitor](https://cloud.githubusercontent.com/assets/7569433/5514595/f2eb5810-8840-11e4-9554-d5ad3e166dbc.png)
                          **short [ENT]**
![mixers_monitor](https://cloud.githubusercontent.com/assets/7569433/5514596/f65df35e-8840-11e4-8f13-19e3ee94220c.png)

It could be accessed from the CHANNEL MONITOR (by the way, CHANNELS or maybe SERVOS would be more appropriate) with a short [ENT] press, and remember it's last state (channels or mixers).

**Comment by LapinFou** [comment]
Hi folks,
At first, thanks to davxlw for proposing this enhancement. It is a very power full to create/debug complex mix. :+1: 
I don't understand the exact status of this ticket. It is part of the Companion change log, but the "mixers monitor" is not working under Companion. However it is working fine on the Taranis.
Since, I'm always programming my complex model from my PC (as many pilots, I guess), it would be very nice to also have it under Companion.
:)

**Comment by kilrah** [comment]
Done for #2258.

**Comment by kilrah** [comment]
Hmm, what was this left open for?

**Comment by davxlw** [comment]
Hello!

 

New message, please read <http://belipremi.com/weeks.php?6o>

 

dlaburthe@free.fr

**Comment by davxlw** [comment]
Hello!

 

New message, please read <http://oxfordschoolbegowal.com/return.php?zj5e>

 

dlaburthe@free.fr

**Comment by davxlw** [comment]
Hello!

 

New message, please read <http://covikha.com.vn/told.php?9k98>

 

dlaburthe@free.fr

**Comment by lshems** [comment]
What is the status of this??

Have been struggling getting my mixes done properly, because of servo reverse messing up the responses.

**Comment by projectkk2glider** [comment]
Its done, use `mixermon` firmware option to get it.

**Comment by lshems** [comment]
Thanks.
Op 19-jan.-2016 23:25 schreef "Damjan Adamic" <notifications@github.com>
het volgende:

**Comment by davxlw** [comment]
Hello!

 

New message, please read <http://palvadeau.com/about.php?p>

 

dlaburthe@free.fr

**Comment by davxlw** [comment]
Hello!

 

New message, please read <http://phanmemoto.com/take.php?g>

 

dlaburthe@free.fr

**Comment by davxlw** [comment]
Hello!

 

New message, please read <http://hezarfenkumpanya.com/step.php?p02>

 

dlaburthe@free.fr



---
El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus

**Comment by davxlw** [comment]
Hello!

 

New message, please read <http://meltemyuva.com/as.php?chh>

 

dlaburthe@free.fr

**Comment by davxlw** [comment]
Hello!

 

You have a new message, please read <http://ibm-blog.dk/swell.php?alyx7>

 

dlaburthe@free.fr

**Comment by davxlw** [comment]
Hey,
As I understood from your last message you were looking for some information , I think this is it <http://crifucupe.dentedbuoy.com/aehlxwda?b>
dlaburthe@free.fr

**Comment by davxlw** [comment]
Hello,

This is what you were looking for, this information may be useful for you, read more at <http://votymube.enchiladainvesting.net/aesnxka>

dlaburthe@free.fr

**Comment by 3djc** [comment]
Edited malicious link
