### ISSUE TITLE
[OpenTX] [enhancement] [Taranis] [Telemetry] [Log] FrSky telemetry, missing decimal precision from GPS speed data

### ISSUE THREAD

**Issue by sambas** [opentx/opentx#1953]
Looks like AP data is missing from TELEMETRY_GPS_SPEED_FORMAT.

![screenshot 2014-12-25 19 55 53](https://cloud.githubusercontent.com/assets/2865403/5554646/69852c2e-8c71-11e4-8fe7-668e5b63a08a.png)

**Comment by kcaldwel** [comment]
Is this going to be incorporated in some version? I'm not sure what to do with the patch...

It would also be nice to have options for different speed units for the GPS and airspeed in the log, or lacking that, in the Companion Log Viewer.

**Comment by kilrah** [comment]
2.1 has independently configurable units for each value, you can even display and log the same value in 3 units at the same time if you feel like.

**Comment by bsongis** [comment]
I guess it could be included in 2.0.16

**Comment by kcaldwel** [comment]
Thanks!

**Comment by bsongis** [comment]
Not relevant in 2.1

**Comment by bsongis** [comment]
Needs your tests in 2.0 (next nightly builds will include it)

**Comment by sambas** [comment]
Looks good.
![screenshot 2015-04-03 15 01 59](https://cloud.githubusercontent.com/assets/2865403/6982006/3b0da420-da14-11e4-8601-7c882dc14253.png)
