### ISSUE TITLE
[Wish]Companion: tool to generate notes files

### ISSUE THREAD

**Issue by MicheleVilla** [opentx/opentx#1954]
Notes files are very useful options but sometimes is difficult to insert and visualize some font (i.e. arrow  up and down)
A simple tool for generate notes files may be helpful in Companion,in this way could be used custom font

**Comment by WavyDavy1960** [comment]
I would also like a Companion tool for writing/managing Checklist notes. It would be a tab in Companion that shows "Checklist Notes" for selected model and allow writing/editing of notes. This would be very useful when creating/modifying settings in Companion, and would be saved with model settings.
