### ISSUE TITLE
[Taranis] [Bootloader] [enhancement] A little more infos

### ISSUE THREAD

**Issue by davxlw** [opentx/opentx#1956]
First, these are really small details but...
- I would prefer if the name of the file to write (either firmware or EEPROM) was specified all along the process:

![boot_write_start](https://cloud.githubusercontent.com/assets/7569433/5561022/4826917c-8dba-11e4-9c85-a2b4852b2f6e.png)
![boot_write](https://cloud.githubusercontent.com/assets/7569433/5561023/4c94af46-8dba-11e4-93b5-f3f386a84162.png)
- And when finished, I'd like to know what to do (the first time, I was just waiting but nothing happened :smile:) :

![boot_write_end](https://cloud.githubusercontent.com/assets/7569433/5561058/50579476-8dbb-11e4-95a2-7ec1fb2e234a.png)

**Comment by MikeBland** [comment]
I have recently changed the bootloaders I have to dynamically create most of the bootsector, the directory and the FAT. This saves quite a bit of flash space as these three 512 byte areas are no longer using so much flash.
