### ISSUE TITLE
Trainer causing calibratedStick over-value

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#1961]
While playing with Trainer Simulator (commit https://github.com/opentx/opentx/commit/d32a473665ae3d309f805bb1d3c674562c5830ba) I noticed that Trainer can cause the `calibratedStick[]` values to come outside the -1204 to 1024 range resulting in this scree-shot (the stick is in bottom left corner of LCD):

![screenshot-1](https://cloud.githubusercontent.com/assets/5950438/5564666/09d28ade-8ecd-11e4-9f87-ada65de71de6.png)

Now we should:
* either limit calibratedStick[] values when adding trainer input
* or fix display isssue
* or even do nothing, but it looks funny when stick is shown outside the box.

**Comment by bsongis** [comment]
I would vote for limiting calibratedStick[], what does Kilrah say about this one?

**Comment by kilrah** [comment]
I would say limit too. Doubt it really happens in normal use though.
