### ISSUE TITLE
Taranis Plus blocked at startup

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#1963]
It had a little bit cold during the night, 2.0.14 doesn't want to start. I guess it is the LCD initialization which fails. I will have to fly with 2.0.13 to fly this afternoon for the last flight of the year ...

**Comment by projectkk2glider** [comment]
@bsongis  The latest commit should fix the power switch OFF->ON issues. My tests on Taranis and 9XE were successful. Please test and close this issue if you think it is solved.

**Comment by bsongis** [comment]
@unstoppablecarl I mostly fly planes, those ones are not broken http://bsongis.free.fr/ but I recently started playing with quadricopters

@projectkk2glider would you port this one to 'next'? It seems perfectly solved now

**Comment by projectkk2glider** [comment]
>would you port this one to 'next'? It seems perfectly solved now

Already done https://github.com/opentx/opentx/commit/56670fc2120fa7773a3e569f1b2ce98222ec0a53
