### ISSUE TITLE
OpenTX Companion not properly round-tripping Telemetry Type on 9XR-Pro

### ISSUE THREAD

**Issue by StewLG** [opentx/opentx#1965]
OpenTX Companion is not properly round-tripping the Telemetry Type variable when used with the 9XR-Pro.

Steps to reproduce:

- Create new model on radio
- Set Telemetry Type to "FrSky D (cable)"
- Read Models & Setting from Radio using OpenTX Companion
- Telemetry Type will be set to "FrSky S.PORT"

I haven't checked thoroughly for other variables having round-trip issues in this area; might be worth a look.

OpenTX 2.0.13 (2014-11-25)
OpenTX Companion 2.0.13

**Comment by bsongis** [comment]
Just open the ModelEdit window, change the parameter, close and reopen and the value disappears!

**Comment by bsongis** [comment]
May I let you test nightly builds tomorrow once build happened?
http://jenkins.open-tx.org/nightly-20/

**Comment by StewLG** [comment]
On 1/1/2015 12:25 PM, Bertrand Songis wrote:
>
> May I let you test nightly builds tomorrow once build happened?
> http://jenkins.open-tx.org/nightly-20/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentx/opentx/issues/1965#issuecomment-68497088>.
>
Absolutely. Just tell me when to get a copy and I'll let you know right
away - it is easy to test.

Thanks for the fix! This was a contributing factor in my not getting
FrSky telemetry working with several models for literally months.

- Stewart

**Comment by bsongis** [comment]
In 4 hours it will be automatically built!

**Comment by StewLG** [comment]
It looks like we have a failed build for Companion maybe? It's 0 bytes:

companionInstall_2.0.14.exe	02-Jan-2015 03:12 	0

**Comment by bsongis** [comment]
Yes, compilation failed on VC++

**Comment by bsongis** [comment]
It should be ok now, I manually launched a new compilation

**Comment by StewLG** [comment]
I tested this back and forth several times, setting things both on the 9XR-Pro and in OpenTX Companion. All seems well now - thanks!
