### ISSUE TITLE
Build fails with PCB=9X2561 and PWM_BACKLIGHT=YES

### ISSUE THREAD

**Issue by kh90909** [opentx/opentx#1970]
It looks like the PWM_BACKLIGHT code didn't get updated with ATmega2561-specific defines and code, so there are compile errors related to the different timer registers.

Happy to fix this myself and submit a pull request, but I could use some help to determine which timer I should use. The current mega64/128 code uses timer 2. The [2561 migration app note] (http://www.atmel.com/Images/doc2581.pdf) suggests that its timer0 is equivalent to timer2 on the 64/128, but I'm concerned that timer0 might be used elsewhere. Someone familiar with the code will be able to answer this much faster and more reliably than me.

**Comment by bsongis** [comment]
I would say Timer4!

**Comment by bsongis** [comment]
Yes you have to use Timer0 which is unused (on 9X2561) if I am not mistaken

**Comment by bsongis** [comment]
When confirmed it will need to be ported to 'next'

**Comment by kh90909** [comment]
Thank you very much for taking the time to fix this so quickly. I'll test it and report back.

**Comment by kh90909** [comment]
Sorry, it took a while to find the time to get this done.

The original quick fix had a typo in the CS2:0 value and didn't account for the SP22 flag for the inverted backlight with the Smartieparts v2.2 programmer board. The above pull request fixes these issues.

I've tested this on my 9X2561 transmitter and it controls the backlight brightness correctly, but I won't be able to do a flight test for some time. However, I have reviewed the code and confirmed that timer0 is not used elsewhere on 2561 boards (except for the audio/voice modules, which are incompatible with PWM_BACKLIGHT), so the chances of any unintended side effects are very minimal.

**Comment by bsongis** [comment]
Thanks for your tests, and sorry for the typo ;)

**Comment by bsongis** [comment]
Would you open a pull request with this fix ported to 'next' (next release 2.1.0)? Thanks!

**Comment by kh90909** [comment]
Sure, I'll do that this evening.
