### ISSUE TITLE
Add LUA function to get value of multi-pos switches 

### ISSUE THREAD

**Issue by macfly1202** [opentx/opentx#1976]
Hi, 
It seems there is no info yet about LUA getValue number for S11 to S16 (and the other multi switch position instead of basic S1,S2,S3) 
Where to find this info please ?
Perhaps there is a possibility within this ?
Thanks again for works

**Comment by kilrah** [comment]
They are switches like any other switch, on or off. Nothing special.

**Comment by macfly1202** [comment]
Andre, 

I understand they have no number and we call them directly with String name I suppose.
ie.
switch_value = getValue("S13") for example 
exact ?
