### ISSUE TITLE
Edge function V2.0.13 OpenTX Companion bug

### ISSUE THREAD

**Issue by tomkfly** [opentx/opentx#1981]
If you set a value of 3 seconds or more( sometimes occurs at 2.5 seconds) as a start value you do not get the INSTANT release option. Going back to a lower value and selecting INSTANT you can then increase the start value to 3,0 and the INSTANT option remains active.
I discovered this setting up a Jukebox mix for another guy and he had the same problem.

**Comment by bsongis** [comment]
Reproduced, really strange bug. I take it.

**Comment by projectkk2glider** [comment]
I already have a fix!

**Comment by bsongis** [comment]
Oh OK I go to next one :)

**Comment by projectkk2glider** [comment]
I will port this to next later.
