### ISSUE TITLE
Channel monitor limited to +/-125 instead of +/-150 with extended throws

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#1982]
Taranis – Open Tx 2.0.13
The title says all but a picture may help:
![screenshot-1](https://cloud.githubusercontent.com/assets/8396899/5650412/7e343dc2-969e-11e4-8c48-b1ffcc583b65.png)

**Comment by franck76** [comment]
with Taranis - Open TX 2.0.13
Channel monitor can display [-150,+150]
but you have to set up servo menu with Min = -150, Max = +150.
![screenshot-4](https://cloud.githubusercontent.com/assets/6233237/5654511/2b450968-96c4-11e4-99b5-074dfa1c6535.png)

**Comment by kilrah** [comment]
Yeah but the bar reaches the end at 125. As far as I remember it was decided to leave it like that.

**Comment by projectkk2glider** [comment]
We need decision, do we change graph to 150 or leave it as it is? The change (I presume) is minimal and very simple.

**Comment by bsongis** [comment]
Nobody uses 150% is it needed?

**Comment by ckleanth** [comment]
If you got servos with no endstops (dunno robotics or animatronic applications) then it would be useful. Personally I don't/cant use more than 125%

**Comment by kilrah** [comment]
On servos with no endstops it makes even less sense, you never need more than 20% or so, anything beyond that is "full speed".

**Comment by bsongis** [comment]
So what do we decide on this one? For the moment I vote for no change

**Comment by ArchmageAU** [comment]
What makes sense to me is that since the graph changes between extended and normal limits, the graph for extended limits should max at the limits (+/-150) instead of another arbitrary historical figure (+/-125).

**Comment by kilrah** [comment]
But then everybody loses some resolution on the graph when extended limits are on for the 2-3 people who might use the 125-150 range...
I vote for no change too. It can indeed be seen as a discrepancy, but I see it as a good compromise for general use.

**Comment by InRVoice** [comment]
graph resolution doesn't matter. % value is on the left. I use more than 125% and I think it is a benefit to have this degrees of freedom instead of limitations like comercial systems.

**Comment by pindeslandes** [comment]
Agreed! And it would be logical and consistent, as expected.

**Comment by franck76** [comment]
Why not add max value (125 or 150) as an option to extended limits
and allow the bars to reach the end at this maximum?
