### ISSUE TITLE
Companion, telemetering type selection

### ISSUE THREAD

**Issue by tedbmoss** [opentx/opentx#1983]
It seems that companion keeps switching back to Frsky Sport instead of staying on the selected 
Frsky D type , however it seems to set the parameter correctly in the Txmitter until the next time it is loaded? Using Taranis.

**Comment by bsongis** [comment]
Already fixed, it's in the nightly builds (both stable and unstable)

**Comment by tedbmoss** [comment]
Thanks, I have trouble finding things on the list of issues.
