### ISSUE TITLE
lcd.drawLine and lcd.drawPixmap issue

### ISSUE THREAD

**Issue by lakeroe** [opentx/opentx#1987]
Using following small LUA script (in OpenTX 2.0.13)

lcd.drawPixmap (0, 0, "/SCRIPTS/BMP/quad.bmp")	-- Size is 20x20
lcd.drawPoint  (0, 0)
lcd.drawPoint  (19, 0)
lcd.drawPoint  (0, 19)
lcd.drawPoint  (19, 19)
lcd.drawLine   (0, 21, 19, 21, SOLID, FORCE)

gives this output
![ist](https://cloud.githubusercontent.com/assets/6253801/5662119/e59edbe8-9734-11e4-949c-a42f5535ea84.png)

In my optinion this should be right
![soll](https://cloud.githubusercontent.com/assets/6253801/5662120/eb1a543a-9734-11e4-98cb-85672d509846.png)

Am I wrong or can anybody reproduce this issue ?
I think lcd.drawLine doesn't draw the first pixel and lcd.drawPixmap doesn't draw the last colum.

**Comment by projectkk2glider** [comment]
We need your bitmap file to test this.

**Comment by projectkk2glider** [comment]
`lcd.drawLine()` indeed has a bug, first pixel is not drawn. However  I can not reproduce a bug with `lcd.drawPixmap()` with test image https://raw.githubusercontent.com/opentx/opentx/master/radio/src/tests/4b_31x31.bmp

**Comment by lakeroe** [comment]
I also can't reproduce the issue using your test image.
My test image is here:
http://www.adrive.com/public/EsNJgQ/quad.bmp

**Comment by projectkk2glider** [comment]
Whit your image I also reproduced this bug. Will take care of this one to...

**Comment by projectkk2glider** [comment]
All done

**Comment by projectkk2glider** [comment]
Ported to next in b878dc673674c9e4669f77f1f927e14d3a240f78
