### ISSUE TITLE
Enhancement: Set Model timer value from custom functions

### ISSUE THREAD

**Issue by Hwurzburg** [opentx/opentx#1990]
While you can directly set a timers value, you cannot set the model default...in my case, I sense a switch position on power up for different battery or prop configurations and change curves, etc....also set the flight timer(s)....this works well at POR....but using the "reset flight" feature as I put the next battery in the quad to fly, will reset the timers to the model page's default....it would be nice to change that value for a given power up session, so that I could just reset the flight for a new battery, rather than cycle the power switch...

**Comment by kilrah** [comment]
Already there.

![screenshot-1](https://cloud.githubusercontent.com/assets/6065069/5690660/d2452df2-98b2-11e4-8c6a-f53a5da4a3be.png)

**Comment by Hwurzburg** [comment]
You did not understand the request...please read the entire post...
using "Set TImer x" does so only temporarily and is exactly what the first sentence was referring to...." Reset Flight" resets the timers to the default value on the Model setup page....the enhnacement would be to set THAT value from a custom function...so "reset Flights" use it again without having to toggle SA, in your example....

**Comment by projectkk2glider** [comment]
Then use Lua script to set timer to whatever configuration you want.

**Comment by kilrah** [comment]
Or use a switch to trigger both a Reset flight SF, then a Set Timer one when it's released for example.

**Comment by Hwurzburg** [comment]
good idea! thnx...saves having to learn another programming language...
