### ISSUE TITLE
enhancement: logical switch extra function

### ISSUE THREAD

**Issue by petedotnl** [opentx/opentx#1994]
is it possible to make an extra function like this:  x < a > y.   Where x=v1 and y=v2  (sorry looks like algebra)
If there is a function that gives the opportunity to sit between two values , then it gets easy to use every potentiometer as a multiposition switch.  Say: s1 is between -100 and -80 thats  pos 1 (L1) and between -80 and -60 position 2 (L2)  etcetera. easy ,flexible and little programming. You can make as much positions as you like (until it gets to narrow ofcourse)

**Comment by projectkk2glider** [comment]
Logical switches have two parameters that can be set, your example needs three - a, x and y. This would require mayor changes to implement.

I propose alternative with two logical switches:
* L1   a > x
* L2   a < y AND L1

Which already woks current opentx versions.

**Comment by petedotnl** [comment]
thank you

2015-01-12 21:41 GMT+01:00 Damjan Adamic <notifications@github.com>:
