### ISSUE TITLE
Companion 2.0.15 Audio tracks not alphabetically sorted

### ISSUE THREAD

**Issue by frelew** [opentx/opentx#2002]
In companion 2.0.15 audio tracks are not sorted alphabetically. They are however in the transmitter, standard Taranis.
![opentx-2 0 15-nosorttrack](https://cloud.githubusercontent.com/assets/10533669/5742249/f0bc1fbe-9c10-11e4-9e7d-73eee986d6ae.png)

**Comment by projectkk2glider** [comment]
Commit 7f31bde6d08a6306d6e70172cf5ec419daf33040 did this. Now we use set instead of the list. The same problem is probbably with `scriptsSet`.

**Comment by bsongis** [comment]
True. But this set could be converted to a linked list in order to be sorted. I don't remember why I used a set right now, perhaps not the best choice!

**Comment by projectkk2glider** [comment]
I guess you used set to eliminate duplicates.
