### ISSUE TITLE
When SD card overflow Taranis work very slow

### ISSUE THREAD

**Issue by VictorEVolkov** [opentx/opentx#2007]

**Comment by projectkk2glider** [comment]
You need to give us a lot more details, I can not make any sense out of this report.

**Comment by VictorEVolkov** [comment]
When LOG files fill ALL empty space - Taranis work very slow. If SD card removed - Taranis work fine.

**Comment by kilrah** [comment]
Log will try to write but disk is full... pretty normal. Don't fill the disk...

Interface slowness will not affect control.

**Comment by projectkk2glider** [comment]
We could add a check for free space in `openLogs()` using function `f_getfree()`.

**Comment by projectkk2glider** [comment]
I have a solution for this, do we want this in master or only in next?

**Comment by bsongis** [comment]
Yes, 'master' will be fine

2015-01-23 19:21 GMT+01:00 Damjan Adamic <notifications@github.com>:

**Comment by projectkk2glider** [comment]
Reminder to myself: I need to port this to next.
