### ISSUE TITLE
Timer Voice Miniute Call not working on  V2.0.15

### ISSUE THREAD

**Issue by tomkfly** [opentx/opentx#2009]
Checked my TX after seeing this reported on RC Groups and the mins are not being called out.

Tom

**Comment by kilrah** [comment]
Works fine here. More details?

**Comment by tomkfly** [comment]
I have my timer 1 set to  THt, 20 mins , persistant  flight, Minute call  checked and Countdown Voice,
With V2.0.13 it used to call out the mins 19,18, 17 --- down to 1 and at then count seconds down.
Since changing to V2.0.15  I am no longer getting these call outs.
I have checked the sounds are still in the SD Card and will call out if I set up a SF to playe Value off a switch.

**Comment by projectkk2glider** [comment]
Upload the eepe with the model that does this somewhere and post link here.

**Comment by kilrah** [comment]
OK, confirmed on a new model with same settings.

**Comment by projectkk2glider** [comment]
Maybe fixes in #1927 caused this one?

**Comment by projectkk2glider** [comment]
Yep, my commit in #1927 caused this. Damn, you fix one thing and brake another :). Fix coming...
