### ISSUE TITLE
SB middle position not work

### ISSUE THREAD

**Issue by laflaf3d** [opentx/opentx#2010]
Hi,
This morning I tried to use the middle position of SB switch in simulation. It's doesn't work.
In the same hand : The NOT SB in HIGH position is set only when SB is in LOW position.
![sb_middle_marche_pas](https://cloud.githubusercontent.com/assets/9316905/5756473/3af0d184-9cb0-11e4-95bd-37980ea8523e.PNG)
![sb_middle_marche_pas2](https://cloud.githubusercontent.com/assets/9316905/5756480/5ac45ab2-9cb0-11e4-8186-d7ed8dd2d34e.PNG)

**Comment by tomkfly** [comment]
You should have !SB^ and SB^. As your switches

**Comment by projectkk2glider** [comment]
And don't use the same switch for **mixer source** and **mixer switch** unless your really know what you are doing. You might want to use **MAX** for mixer source in your case and perhaps adjust the weight of some mixes to -100%.

Closing as this is user error, not opentx issue.

**Comment by laflaf3d** [comment]
Shame on me !Your great, thanks a lot for your marvellous work !
Stéphane. 

     Le Jeudi 15 janvier 2015 12h35, Damjan Adamic <notifications@github.com> a écrit :
   

 Closed #2010.—
