### ISSUE TITLE
Multiwiis (and forks) MSP protocol support

### ISSUE THREAD

**Issue by w1ndf4k3r** [opentx/opentx#2014]
What are the chances for implementing support for MSP protocol in a similar fashion mavlink and others are.
http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol

**Comment by projectkk2glider** [comment]
Closely related to #2008

**Comment by w1ndf4k3r** [comment]
I do not think is related. What I am talking about is a telemetry protocol implementation.

**Comment by kilrah** [comment]
Will be easy to do by anyone once 2.1 is out. Definitely won't happen before.

**Comment by kilrah** [comment]
Will close that one, the most appropriate way to do that will be through lua scripts. We'll give access to the smart port and serial port to the lua interpreter.
