### ISSUE TITLE
Switch position warning on startup

### ISSUE THREAD

**Issue by ululi1970** [opentx/opentx#2016]
After upgrading to 2.0.15 from 2.0.13, I have an issue with the warning of POT positions. Before the upgrade, the warning windows appeared if a POT was not on the last recorded position, with an arrow to indicate in which direction to rotate the POT to go back to the last recorded position. Once the POT was 
set right, the warning disappeared. Now, it does not seem to work. I can rotate the POT back and fort and the only thing I get is a beep when it goes past center.

**Comment by projectkk2glider** [comment]
I can not reproduce this,  tried every possible case, it always works for me. @ululi1970 any chance you screwed your sticks/pots calibration data?

**Comment by davxlw** [comment]
No problem here either...

@ululi1970,
You could post an eepe.

Taranis B
OpenTX 2.0.15

**Comment by ululi1970** [comment]
MY mistake. It works as intended. Sorry for increasing your work load. BTW, the fix for blank screen on cold starts works without a hitch...
