### ISSUE TITLE
Logging of Logical Switches

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2022]
I have created many logical switches and it's possible to debug this using the simulator. But this isn't always possible as some realworld conditions (like height and vspeed) can't be given as input.

For instance; I have created a logical switch with a duration of 0.2s to reset my telemetry when I enter launch mode, the absolute height is more than 2m and the vertical speed is less than 0.1 m/s.

I would suspect it to work properly, but sometimes it resets telemetry when it's already launched. It says so, at least.

After flying I opened my logs expecting to see the values of the logical switches and found out they weren't logged.Otherwise I would have found out why it resets the telemetry although it already did this before.

It would be nice if this is added. These values are boolean so it would fit in 4 bytes

**Comment by fraternl** [comment]
This never received any attention.
I needed it today to check if the logic was working as intended

**Comment by Spainman** [comment]
Being a switch junky myself I consider it a great idea! It would be a great tool to debug complex sequences.

**Comment by fraternl** [comment]
Sometimes my timer gives me a 0-output after a flight.
It would be great if logging of switches could be made optional so I might find the cause of it.
Or is it already?

**Comment by janekx** [comment]
+1

**Comment by projectkk2glider** [comment]
Two issues with current implementation:
* label `LS` is already used by `Left Slider`, I propose `LogSw`
* I propose to store HEX value in log (faster conversion, fixed width)

**Comment by vian31** [comment]
I was wondering if this function might be possible... Very good to see that has been included in the 2.2 milestone.
Superposing LS status with log charts will be very helpfull.

**Comment by LevYas** [comment]
This issue is very searchable, so I want to add some comments on that.
1. Logging is implemented, but there's no UI to display that. The log viewer can only display these HEX values. Probably, you can open the log in excel and convert the column using formulas to individual logical switches.
2. Here's a clarification on how you can interpret these HEX values https://www.rcgroups.com/forums/showpost.php?p=47996299&postcount=6833
