### ISSUE TITLE
Open TX companion

### ISSUE THREAD

**Issue by ginney54** [opentx/opentx#2030]
Running win 7 Dell OpenTX unable to check for updates. Will not download firmware. Works ok on my work Dell running Win8. Headbanger.

**Comment by kilrah** [comment]
What companion version? 
If the same version works fine on another computer the problem is likely with the computer.

**Comment by ginney54** [comment]
Thanks Andre both have the latest version, must be the computer but can’t get it sorted. I will keep looking. I have flashed the Taranis Plus using the file that downloaded from the working PC. Have looked at firewalls and cleared all cache.
Mystery. I will let you know if I get it fixed.
Greg

**Comment by projectkk2glider** [comment]
No feedback, closing.
