### ISSUE TITLE
lcd.drawLine(...) gives wrong result

### ISSUE THREAD

**Issue by Sacre100** [opentx/opentx#2034]
Tested on OpenTx 2.0.15 Simulator

Since OpenTx 2.0.15, lcd.drawLine(...) gives the following result 
![lcdline](https://cloud.githubusercontent.com/assets/8712977/5834011/6805869e-a159-11e4-9d7d-51fbeb10e085.png)

with the following LUA code : 

    return {
      run = function (event)
        lcd.drawLine( 10, 30, 30, 10, SOLID, FORCE )
        lcd.drawLine( 30, 10, 50, 30, SOLID, FORCE )
        lcd.drawLine( 50, 30, 30, 50, SOLID, FORCE )
        lcd.drawLine( 30, 50, 10, 30, SOLID, FORCE )
    
        lcd.drawLine( 130, 10, 110, 30, SOLID, FORCE )
        lcd.drawLine( 150, 30, 130, 10, SOLID, FORCE )
        lcd.drawLine( 130, 50, 150, 30, SOLID, FORCE )
        lcd.drawLine( 110, 30, 130, 50, SOLID, FORCE )
      end
    }

**Comment by projectkk2glider** [comment]
The changes in #1987 are responsible for this, the slanted lines are not handled properly. The fix in #1987 is only good for vertical or horizontal lines. I will fix this.
