### ISSUE TITLE
Add way to start LUA Telemetry directly after power up

### ISSUE THREAD

**Issue by fzahn** [opentx/opentx#2043]
there is no way to autostart a lua-telemetry-screen after power up. Currently you have to enter the telemetry-screen by long-holding the Page-Button. It would be cool, if there would be a option in each model-setup to tell the Taranis to directly enter the telemetry-screen after power-up

**Comment by mhotar** [comment]
I would prefer to unify all the front pages we have with telemetry ones into one queue and simply make it to remember last used page in selected model. Then we will be able to use Page/LongPage to cycle through them in both directions. With Lua function like drawMainPanel, which will draw top bar and trims, it would be nice to do cool custom pages.

**Comment by bsongis** [comment]
Right this is something I have done in my workspace (one list for all those screens). It will be good to have it on Taranis as well.

**Comment by AndrewFarley** [comment]
+1 +1 +1.   This feature can't be that hard to implement... I'm bumping it, can we get this implemented?  Just implemented my own custom Telemetry / interface to simplify/unify my usage of the handset, and I'd like it to auto-run on selection of a model.  I imagine an implementation such as...

- Upon model selection (which I assume also comes right after it boots and selects the default model) check if /SCRIPTS/*MODELNAME*/auto_telemetry.lua exists.  If it does, run it immediately.

**Comment by lshems** [comment]
not stale, but perhaps covered in another issue?

**Comment by AndrewFarley** [comment]
+1 on not being stale, still desired

**Comment by AndrewFarley** [comment]
+1 on not being stale.  Still relevant.  But clearly no one cares enough to implement it.  :P
