### ISSUE TITLE
Taranis not working anymore

### ISSUE THREAD

**Issue by KevinJaspers** [opentx/opentx#2044]
I've upgrade taranis to the new firmware but doenst start up anymore is shakes by startup.

Please react,

Greats Kevin

**Comment by PieroCo** [comment]
you have not selected the correct firmware for your radio

**Comment by bsongis** [comment]
Please rea ... read the ... manual

**Comment by KevinJaspers** [comment]
On my work i was ready after the problems and i found it was the wrong firmware!
Everythings is fine now.
thanks for reacting
greats kevin
