### ISSUE TITLE
companion, broken link to deb file

### ISSUE THREAD

**Issue by wolkstein** [opentx/opentx#2045]
hi,
on the opentx website download section(http://www.open-tx.org/2015/01/13/opentx-2.0.15) the companion 2.0.15 32 bit deb installer have a broken link.

currently the broken link is
http://downloads-20.open-tx.org/companion/companion_2.0.15.deb.
the right link is
http://downloads-20.open-tx.org/companion/companion_2.0.15_i386.deb

/g
wolke

**Comment by kilrah** [comment]
Fixed.
