### ISSUE TITLE
Menu names in firmware different than those in OpenTX Companion simulator for 9XR-Pro

### ISSUE THREAD

**Issue by StewLG** [opentx/opentx#2046]
Menu 05/12 Reads "DR/EXPO" in firmware, but "STICKS" in OpenTX Companion simulator.
07/12 is "LIMITS" vs. "SERVOS"

I'm not seeing any functional differences; hopefully these are just some strings that didn't get updated during the OpenTX 2.0 work?

**Comment by bsongis** [comment]
It stayed like that for > 2 years because we didn't want to rename OpenTX menus (for novice who don't use the PPM center feature) and confuse people. Now people are confused by this discrepancy, I change :)
