### ISSUE TITLE
Taranis Plus

### ISSUE THREAD

**Issue by KevinJaspers** [opentx/opentx#2052]
Hello Everybody,

when i move my poke my curve goes at ones to 100%.
Its only on the left side.

Is the gimbal broken or is it a software configration?
The radio is just an week old.

Already thanks.
Greats Kevin

**Comment by bsongis** [comment]
Did you calibrate your radio?

**Comment by KevinJaspers** [comment]
Yes, But the problem was that the calibration was wrong
