### ISSUE TITLE
[enhancement] Set RTC when receiving GPS timestamp

### ISSUE THREAD

**Issue by hsteinhaus** [opentx/opentx#2056]
The Taranis RTC has the habit to drift badly (at least mine). Wouldn't it be possible to correct it when receiving GPS timestamps via telemetry?

**Comment by LapinFou** [comment]
Good idea ! :+1: 
It would also be nice to update the RTC, when some models are uploaded in the radio from a PC/Mac.

**Comment by bsongis** [comment]
RTC from GPS is nice with me. But from the USB connection we have to change the protocol, massstorage is not good for that (it's not stored in EEPROM).

I would need some inputs about which USB protocol would be better to our needs. Massstorage showed us some limits for EEPROM and FIRMWARE transfers ...

**Comment by LapinFou** [comment]
OK. It didn't understand than firmware/model update where done through a mass-storage protocol.
Updating RTC from GPS should take care of timezone. I guess this easiest way will be to only update minute/second (with special caution if the minute are closed to a plain hour) .

**Comment by bsongis** [comment]
No, timezone is configured in General Settings.

**Comment by LapinFou** [comment]
Sorry, I did not mean timezone (bad English), I mean Summer TIme/DST (Daylight Saving Time). I'm not at home, but I don't recall such setting in OpenTx.

**Comment by kilrah** [comment]
Just add / remove one to the timezone adjustment...

**Comment by LapinFou** [comment]
Thanks for the tips. Maybe it could be automated?

**Comment by kilrah** [comment]
Nope, no way of knowing for sure when it happens. Devices that do use network access.

**Comment by hsteinhaus** [comment]
I think the best solution would be to run the RTC in UTC (or more precisely GPS time) and a simply adding an adjustable offset before displaying the time somewhere in the menu. 

BTW, telemetry logs should  preferably contain the GPS time (not local time) for easier matching with onboard vehicle logs, e.g. provided by a multicopter/fixed wing autopilot/stabilizer.

**Comment by JoeB99** [comment]
I think the RTC and all logs should be in UTC, then apply the user-specific offset (as set in general settings) to the displayed time only. 
Automatic DST change to the time can be done on the radio. There is a proven formula to calculate when DST occurs. 
The user could set their DST amount (in 15 min increments) in a general settings menu. For most, this would be set to 1hr.

**Comment by jtaylor2** [comment]
>Automatic DST change to the time can be done on the radio. There is a proven formula to >calculate >when DST occurs.
  
OpenTX is used all over the world.  Daylight savings time is used (or not used) differently in different countries and can change at the whim of an administration.  http://en.wikipedia.org/wiki/Daylight_saving_time_by_country 

I think you underestimate the complexity of automatic DST change.  I would be interested in a pointer to "a proven formula to calculate when  DST occurs" because the only way I know how to do it is with the zoneinfo database ( http://en.wikipedia.org/wiki/Tz_database ) which seems like it would be too involved for an embedded system without OS TZ support.

Is it really that much trouble to change the time on the transmitter twice a year?

**Comment by kilrah** [comment]
Even my fancy radio-controlled watch that supports displaying 3 timezones at the same time requires you to set DST manually for each zone because it's impossible to know for sure when it's active. The "rules", when some exist, are regularly changed.

**Comment by JoeB99** [comment]
Yes, you need to know the day and the offset. Companion connects to the internet to get the latest firmware version. It could also get the rule for the users timezone at the same time, and then send the rule to the radio.... Or just let the user change the time 2x a year :)

**Comment by kh4** [comment]
Maybe we can just make GPS correct time for +/- 5 minutes or so? This way it could just guess the timezone?

**Comment by JoeB99** [comment]
That won't work for me, my TX didn't come with a GPS receiver :-P

**Comment by kh4** [comment]
@JoeB99 none of the TX:s have GPS, this feature will update TX time based on GPS data received via telemetry from the aircraft/rover.

**Comment by JoeB99** [comment]
It was a joke, hence this-->      :-P
