### ISSUE TITLE
No Countdown Announcement When Triggered by THt

### ISSUE THREAD

**Issue by hkfanatic** [opentx/opentx#2059]
I read somewhere else that this bug has been reported AND has been acknowledged but couldn't find it in any of the open issues nor in the fixed issues so I opted to post it as a kind reminder of this issue.

I'm using the OpenTX 2.0.15 on the Taranis X9D Plus.  Countdown Announcements work just fine if triggered by something else (e.g. THs, switches, etc.).

Thanks for the fantastic work you guys have done.  Kudos!

**Comment by kilrah** [comment]
#2009, fixed.
