### ISSUE TITLE
A10 and geebee Icons Do Not Show Up Properly

### ISSUE THREAD

**Issue by hkfanatic** [opentx/opentx#2060]
I've been racking my brains trying to figure out why the A10 and the geebee icons are replaced by the Frsky Splash screen.  I re-formatted my MicroSD and re-copied the contents to no avail.  I renamed the A10 file to Z10 to see if it will show up when assigned to a model and it still didn't work.

I decided to look closely at the icon files and noticed that the above-mentioned 2 icons have a size of 6.05kb while the others are 1.11kb.  Could this be the reason?

Using OpenTX 2.0.9, you can't even see the correct image (like what you would see if you viewed them in a PC).  What you'll see instead is the FrSky splash screen.  In OpenTX 2.0.15 on the other hand, you can view the correct image when browsing the contents of the MicroSD card using the Taranis (i.e. long press of MENU button, then PAGE button, etc.) but the correct image will not show up when assigned to a model.  You still see the FrSky spash screen.

I hope you find a fix for this.  Thanks in advance.

**Comment by kilrah** [comment]
1.11k is the correct size. Your images are likely not saved as 4 bits per pixel as required.
