### ISSUE TITLE
[Wish][Companion] enable tick box for "play track"

### ISSUE THREAD

**Issue by jj-uk** [opentx/opentx#2070]
There is no enable tick box for play track. Having this would be useful when testing settings.

At the moment, i'm writing down what the switch is, then setting it to --- to disable it whilst testing something else, which is not ideal. - No audio in the sim is a massive PITA.

**Comment by kilrah** [comment]
The enable tick box is a safety feature and thus only present where required.

Is it such a problem to have the sounds play during testing? Isn't it better to set the volume to 0?

**Comment by JoeB99** [comment]
Not really. If i'm setting up other sounds, then i have announcements which gets confusing if i don't disable them.
