### ISSUE TITLE
DSM2 serial transmission speed out of spec

### ISSUE THREAD

**Issue by zieren** [opentx/opentx#2072]
I noticed that the serial transmission speed to a DIY DSM module is 125000 baud:

#define BITLEN_DSM2          (8*2) //125000 Baud => 8uS per bit

This seems based on PPMtoDSM:

Serial.begin(125000);                     // closest speed for DSM2 module, otherwise it won't work

While I do realize that it typically works, this does sound a little scary to me. I'm pretty sure that the modules are only specced for the standard speed of 115200. The fact that it works for some modules doesn't mean it'll work for all, all the time. What speed do actual Spektrum radios use?

I'm just getting into this topic, but I did read reports of "signal loss" when using DIY modules. Maybe it's not an RF problem but a problem with the serial link?

Would it make sense to set this (closer) to 115200?

**Comment by kilrah** [comment]
No, 115200 will not work. The current speed is based on what a real Spektrum transmitter sends to the module.
