### ISSUE TITLE
Minor tweeks

### ISSUE THREAD

**Issue by jj-uk** [opentx/opentx#2074]
On the radio, we have 'Beep Pitch' which shows a value of +xxxHz
On Companion we have 'Speaker Pitch' with has a value of 1 to 20.
Are these the same setting?

In the radio, in a model, Switch positions on/off is indicated by the presence or not of the switch direction.
Input->Modes and Mix->Modes on/off state are indicated by the presence or not of the mode number.
Center Beep indicates on/off by reverse highlighting the letter.
I think this should be made consistent, and the reverse highlight is the better way to indicate state.

In the radio, 'Mixer' screen says I'm using 4/64 mixes, but i can only see 32 mixes available. Is this an error?

**Comment by projectkk2glider** [comment]
>In the radio, 'Mixer' screen says I'm using 4/64 mixes, but i can only see 32 mixes available. Is this an error?

You have 32 channels which can hold 64 mixes. One channel can have more than one mix line an each mix line counts as one.
