### ISSUE TITLE
Not all values are logged

### ISSUE THREAD

**Issue by Datospel** [opentx/opentx#2077]
Have a question | proposition:

There are values that are aquired by TX from telemetry data and logged to file. But there are some other calculated values that a user can display on telemtry screen (DIST, alt+ or -, etc) but those values are not being logged. It is logical that if a user needs such values in the field, he would also prefer to see all of them in a log file. 

Don't you think that all user-selected telemetry screen values should be logged to file no matter wheather they originate from raw telemetry data or calculated TX data?

Thank you

**Comment by kilrah** [comment]
Will close that one as the new system that is already implemented for 2.1 will allow logging any value based on user choice.
