### ISSUE TITLE
Enhancement: Set "Backup Folder" as part of the Radio Profile instead of Application Settings

### ISSUE THREAD

**Issue by CoyotteDundee** [opentx/opentx#2080]
Hi All,
I wonder if the Companion's "Backup Folder" parameter could be moved from the Application Settings to the Radio Profile, allowing having a backup folder per Radio Profile.
This could allow people having multiple models to not mix backups.

Best regards,

Coyotte

**Comment by LapinFou** [comment]
:+1: Very good idea !

**Comment by LapinFou** [comment]
Can't wait to try the first stable version of 2.1.
:)

**Comment by romoloman** [comment]
I would prefer to have both with profile backup folder overriding the default application one if set.
If this is accepted by all members I will implement it

**Comment by CoyotteDundee** [comment]
Hello,
This 'll allow usual operation mode, as also a specific mode if needed by the user. 
The best of both worlds ;-)
Thanks for the proposal.

Coyotte

**Comment by bsongis** [comment]
Yes of course, thanks @romoloman for this one, I will have more time for other issues!

**Comment by romoloman** [comment]
Done in profilebackupfolder branch, give it a test.

**Comment by romoloman** [comment]
Isn't this issue closed ?
Feedbacks are welcome

**Comment by bsongis** [comment]
You just forgot to write "Fixes #2080" in your commit :)
Thanks for your this one!
