### ISSUE TITLE
Companion: Default channel order

### ISSUE THREAD

**Issue by JoeB99** [opentx/opentx#2089]
Setting the default channel order to RETA, create a new model and both the 'inputs' and 'mixes' are ordered as TAER.
Is this a bug?

**Comment by davxlw** [comment]
You may be referring to the channel order in the radio profile setting.
But if you want to change it after that, do it in the "General Settings" of your eepe document, then it will be taken into account when creating a new model.

**Comment by kilrah** [comment]
That setting applies to new *documents*. The setting in that document's general settings applies to new models
