### ISSUE TITLE
Companion: Minor cosmetic bug with play track

### ISSUE THREAD

**Issue by JoeB99** [opentx/opentx#2090]
Cosmetic bug: If you have 2 play track lines in special functions, and you click the first to play, then click the second before the first has finished playing, the first stop icon does not change back to play.

To reproduce: 
Click play on the first SFx 'play track'
Click play on the 2nd SFx 'play track' BEFORE the first has finished.

This is cosmetic and does not effect the functionality of the software.

**Comment by jtaylor2** [comment]
@projectkk2glider I wanted to do a pull request for a fix for this but messed up and evidently pushed it directly to next.  Should I back it out or leave it?

**Comment by kilrah** [comment]
It's good like that, just try to remember to create a branch in the future :)

You can do the same change on master.

**Comment by projectkk2glider** [comment]
@jtaylor2 slipped a bug into master 730bc8c608529fdd1f6ce6b092c4334c2741538b and next 459837d6f36502ca97cf44e057304f3779eb92d1 . Jim use a pull request next time :wink:
