### ISSUE TITLE
Feature request: Channel lock special function

### ISSUE THREAD

**Issue by TexasFPV** [opentx/opentx#2096]
Using the pots on the Taranis is useful for tuning multirotor gains, but after the gains are set, the pots can be accidentally moved.  It would be useful to "lock in" the current value of the pot by using a toggle.    Whatever channel is using the pot will remain at the value read from the pot when the lock is toggled, regardless of the pot position.  This would be similar to the current channel override special function, without a predetermined channel value.

**Comment by davxlw** [comment]
Just add a mix on the channel you want to lock with itself as source and multiplex to replace.
Here is an example with pot S1 controlling channel 6:
![ch_lock](https://cloud.githubusercontent.com/assets/7569433/6277490/359affa2-b88f-11e4-8f54-dfeb58d2c2fb.png)

**Comment by lepicfoto** [comment]
nice i was looking for something just like that, tnx

**Comment by kilrah** [comment]
Or use trims / global vars to set them.
