### ISSUE TITLE
update D series recievers over serial port 

### ISSUE THREAD

**Issue by pinkywafer** [opentx/opentx#2099]
Feature request :  Would it be possible to flash D series RXs ( ie 27ms D4R-II fw) using the serial port?

**Comment by projectkk2glider** [comment]
Yes it will be when #1599 is done. Duplicate.

**Comment by pinkywafer** [comment]
I may be wrong, but I don't think this is a duplicate issue... I'm talking about the older D-series, non Sport RXs, which require rx, tx and gnd to communicate via serial. Not sure that these D series RXs can be flashed with mike's fw?

**Comment by projectkk2glider** [comment]
You might be right, the D series needs separate TX and RX lines (inverted TTL levels) and X series needs only one line.
