### ISSUE TITLE
Copy flight modes

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#21]
_From [r...@marotori.com](https://code.google.com/u/109472470680444692365/) on April 18, 2013 19:42:58_

One menu press on a flight phase should pop up a menu to allow you to copy the selected flight phase and gvar settings to another flight phase. 

Not a critical option,  but useful when setting up similar phases.

_Original issue: http://code.google.com/p/opentx/issues/detail?id=21_

**Comment by janekx** [comment]
I am for look at this soon :) Useful and after year it would be nice to be added. :)
