### ISSUE TITLE
Feature Request: sbus servo channel changer

### ISSUE THREAD

**Issue by pinkywafer** [opentx/opentx#2100]
Would it be possible to add functionality of servo channel changer using module port (or maybe trainer port)

**Comment by projectkk2glider** [comment]
Maybe this could be also done in #1599.

**Comment by projectkk2glider** [comment]
@bsongis, @kilrah, @MikeBland Do we actually know the protocol for this?

**Comment by kilrah** [comment]
I don't. FrSky do, maybe Mike asked them.

**Comment by MikeBland** [comment]
I have no idea of the protocol, never asked.

**Comment by LapinFou** [comment]
Some news: FrSky released a new product named SD1 → https://www.frsky-rc.com/product/sd1/
When downloading the firmware, you got some included LUA script to change the channel number.
Maybe this can help?
Firmware can be downloaded here: https://www.frsky-rc.com/wp-content/uploads/Downloads/Firmware/SD1/FW-SD1-171114%20and%20lua.zip
