### ISSUE TITLE
Remove the 2x2 switches feature in Taranis

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#2103]
I did it for somebody who asked for it in my club. He decided to switch to the X9E and doesn't need it any more. Now it uses EEPROM and RAM for nothing... until anybody else needs it?

**Comment by kilrah** [comment]
Hmm has that already been released to users or was it about to come in 2.0.16?

**Comment by bsongis** [comment]
No it's only in 'next'. Nobody uses it and I guess nobody will use it.

**Comment by bsongis** [comment]
Done
