### ISSUE TITLE
Unify line endings

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2106]
When remaining pull requests are closed, it would be a good time to finally unify line endings on all source files. I propose this change for `next` branch, we can leave `master` as it is. 

My vote is for Unix style line endings. 

Maybe we should also create _.gitattributes_ file according to https://help.github.com/articles/dealing-with-line-endings/

Our _.gitattributes_  file would be very simple:

```
* text eol=lf
```

**Comment by xmxwx** [comment]
:+1:

**Comment by bsongis** [comment]
I will wait for your feedback before applying the script ...
I am not completely happy with the #ifdef but at least it will be the same everywhere!

**Comment by bsongis** [comment]
Done!
