### ISSUE TITLE
Problem with screen width (Fedora 21)

### ISSUE THREAD

**Issue by martinwh99** [opentx/opentx#2108]
Hello

I have a 10.2' screen on my notebook i'm using for companion. Unfortunately some screens, like Simulate Tx or General Settings,  do not have a maximize or zoom capability. I have installed the Gnome extension but that did not really help.

regards
Martin

**Comment by romoloman** [comment]
Which is the resolution on your notebook ?

**Comment by martinwh99** [comment]
sorry for the late answer. i switched to Ubuntu that is working fine.
