### ISSUE TITLE
BUG: Model compare missing SF differences

### ISSUE THREAD

**Issue by JoeB99** [opentx/opentx#2110]
SF differences are missed in compare model. See attached image.

![untitled](https://cloud.githubusercontent.com/assets/10943625/6368957/916725a6-bcd9-11e4-8ece-52bced347e7f.jpg)

How do i upload an eepe here to show the issue?

**Comment by projectkk2glider** [comment]
>How do i upload an eepe here to show the issue?

No need, the compare has more issues, it needs someone to take time and fix it thoroughly. But there are so many other issues more important...

Related #1862

**Comment by romoloman** [comment]
This one has been fixed, also curve compare is back, but there is still a lot of stuff either in compare and in printmodel to be fixed.

**Comment by JoeB99** [comment]
Great. I use compare all the time when changing settings at the field and then syncing them back to my master file at home, or when helping a friend set up models.

**Comment by bsongis** [comment]
@romoloman thanks for taking care of those issues!
