### ISSUE TITLE
Request help OpenTX

### ISSUE THREAD

**Issue by nino165** [opentx/opentx#2111]
Hello everyone
I installed version 2.0.15 firmware into the radio, and in the PC.
Going into the pc in settings, profile radio and compile options and not selecting anything, FrSky example, telemetrez, the radio does not give me no defect.
Recently I bought the module Telemetry FrSky DJT, and I wanted to add the two settings written FrSky example, telemetrez, just turn on the radio to me by mistake and I realize that the swich TH and AIL are set to 1, as if they were on and not to 0 as it should be.
If not I select in the profile radio and compile options voices FrSky, telemetrez the swich are set to 0.
What do I do?

**Comment by kilrah** [comment]
You need to redownload and reflash the firmware after changing options.

Please use forums for support, this place is strictly for feature requests and bugs.
