### ISSUE TITLE
Bug (?) with minutes voice chrono if trigger is Throttle

### ISSUE THREAD

**Issue by macfly1202** [opentx/opentx#2112]
Hi,
For OpenTX, last master version (2.0.15) 
To have minute voice chrono, we must use 'ON' on 'Chrono1'
If trigger for start chrono is 'Gzt' for start chrono (Throttle), minute voice disapear.
Don't know if it's normal behavior or a minor bug. 

Thanks for all dev's works !

**Comment by projectkk2glider** [comment]
Duplicate of #2094
