### ISSUE TITLE
Missing a Funktion at Log Switches |a|>|b| 

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2115]
I miss the a funktions at log switches, important to compare absolut 2 values 

I miss the Inc Dec x at Spez. Funktions, not only fix +1 -1 
free setting  Inc Dec  
Example +10 -10

**Comment by pindeslandes** [comment]
It looks very complementary to #1678... which nobody seems to be interested in!

**Comment by hrenz** [comment]
But its important to compare 2 abolut values  at a simple way

Same at the Spez Funktions to INC DEC fix values
INC 40
DEC 40
Per puls you can set Values direct up donwn
-100 -60 -20 20 +60 +100
