### ISSUE TITLE
[BUG] Rotary encoder sense

### ISSUE THREAD

**Issue by JivaroFAD** [opentx/opentx#2118]
On M2560 board (should be the same on all 9x boards, to verify on Taranis), create one special function and two mix lines : 
AdjustGV1, source = REa
CHx : source = REa, weight = +100%
CHy : source = MAX, weight = GV1

If we take a look at the outputs, we should expect to have CHx = REa and CHy = REa
But we have : CHx = REa and CHy = - REa

**Comment by projectkk2glider** [comment]
@JivaroFAD which branch has this problem?

**Comment by JivaroFAD** [comment]
"Next" branch, tested on Mega2560 board.
