### ISSUE TITLE
[BUG] after lcd.drawPixmap event EVT_PAGE_BREAK is sometime generated automaticaly

### ISSUE THREAD

**Issue by Sacre100** [opentx/opentx#2123]
This is a funny bug !

Bug found in the simulator V2.0.15 (not tested yet on the Taranis)

I found that when you draw a bitmap too big for the screen, it can in some circumstance generate automaticaly a EVT_PAGE_BREAK event.

Here is a standalone script to reproduce the bug : 

    local col = 149 -- Error will occur at col 152
    local time = getTime()
    local bingo = false -- True when the bug occurs
    
    local function run(event)
      if not bingo then print("Event :", event) end
      lcd.lock()
      if event == nil then
        error("Cannot be run as a model script!")
        return 2
      elseif event == EVT_EXIT_BREAK then
        return 2
      elseif event == 0 then
        if not bingo and (getTime() - time) % 100 == 0 then
          lcd.clear()
          col = col + 1
          lcd.drawPixmap(col, 1, "/SCRIPTS/bugpixmap.bmp") -- height : 65 pixel, width 1 pixel 
          lcd.drawText(1, 11, "At col : ", 0)
          lcd.drawNumber(lcd.getLastPos(), 11, col, LEFT)
        end
      elseif event == 189 then
        lcd.clear()
        col = col + 1
        lcd.drawPixmap(col, 1, "/SCRIPTS/bugpixmap.bmp") -- height : 64 pixel, width 1 pixel 
        lcd.drawText(1, 11, "At col : ", 0)
        lcd.drawNumber(lcd.getLastPos(), 11, col, LEFT)
      elseif event == EVT_PAGE_BREAK then
        bingo = true
        print("Bingo")
        lcd.drawText(1, 1, "Bingo", 0)
        lcd.drawText(1, 11, "At col : ", 0)
        lcd.drawNumber(lcd.getLastPos(), 11, col, LEFT)
        lcd.drawText(1, 21, "Event : ", 0)
        lcd.drawNumber(lcd.getLastPos(), 21, event, LEFT)
      end
      return 0
    end
    --
    return {run=run}

And here is the image used by the script (it's a PNG that must be converted as BMP to test the script) :  ![bugpixmap](https://cloud.githubusercontent.com/assets/8712977/6522844/0c3e63d6-c3ea-11e4-9d1c-9a8e1fca8957.png)

The script trace the event flow in the console.

**Comment by projectkk2glider** [comment]
Confirmed. Bug caused by write outside LCD buffer by https://github.com/opentx/opentx/blob/master/radio/src/lcd_taranis.cpp#L177
