### ISSUE TITLE
Mixer Monitor and Channel Monitor are different at gauge  all is 100%

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2125]
Test next from today 07.03.2015
Mixer monitor and channel Monitor are different at gauge
Input 100%,  Mixer 100%, Servo 100%  (all weights 100%)
Channel gauge ist correct,   Mixer gauge has only 50%
![snapshot_01](https://cloud.githubusercontent.com/assets/6217896/6540618/f8e13002-c4a7-11e4-98e9-2c2594a970a6.png)
![snapshot_02](https://cloud.githubusercontent.com/assets/6217896/6540619/feee0196-c4a7-11e4-8c7a-6aad261db9f7.png)

**Comment by davxlw** [comment]
It's not a bug but a feature ;)
The mixers gauges can show a larger range of value (200%) than the channels ones.
This view is better used with the channels values expressed in %, it allows to see if your mixes exceed your servos ranges.

**Comment by bsongis** [comment]
This should not be the default though, is it?

**Comment by bsongis** [comment]
Ah titles sind auf Deutsch geschrieben, ok!

**Comment by hrenz** [comment]
yes self compiled, makefile with mixermonitor YES
there is no info that mixer Monitor gauge is 200% , because mixer and channel value is standard
