### ISSUE TITLE
Error 404 Not Found : http://voices-20.open-tx.org/opentx-9xrpro/fr/

### ISSUE THREAD

**Issue by panguitou** [opentx/opentx#2126]
Hi everybody,

In OpenTX Companion Version 2.0.15, Jan 14 2015
When clicking on the [Download Voice] button either in french or in english you get this 404 error 

![image](https://cloud.githubusercontent.com/assets/10453190/6546349/c6379c22-c5b0-11e4-8c3b-a2401426ca83.png)

Of course it's quite easy to overcome but just in case it can be fixed up.

Thanks
JM

**Comment by panguitou** [comment]
Precision : I'm using Ubuntu 14.04 LTS
Thks

**Comment by bsongis** [comment]
Fixed

**Comment by panguitou** [comment]
Perfect.. thank you !
