### ISSUE TITLE
No Global Variables Menu : opentx-9xrpro-2.0

### ISSUE THREAD

**Issue by panguitou** [opentx/opentx#2127]
Despite selecting the gvars option I do not get the Global Variables Menu.

![image](https://cloud.githubusercontent.com/assets/10453190/6546392/e0bcac02-c5b2-11e4-90ce-a7cb3e0d0e3b.png)

I tried many configurations but I never get the gvars menu, for the above exemple I have obtained 
only 11 menus 

[MODELES][CONF.MODELES][PHASES DE VOL][MANCHES][MIXEUR][SORTIES][COURBES][INTER LOG.][FONCTIONS SPEC.][TELEMESURE][GABARITS]

Shall I try the english version ?

Thanks in advance !
JM

**Comment by projectkk2glider** [comment]
Gvars are at the bottom of Curves screen.

**Comment by panguitou** [comment]
Thank so much for your very prompt reply...
But sorry to disagree, thanks to you I dig a little more and I finally found them not in the curves screen, but logically in each Flight Mode screen !
Regards

**Comment by projectkk2glider** [comment]
True, GVARS are:
* on Flight mode screen in Companion
* on Curves screen (9X) or Flight mode screen(Taranis) on the radio
