### ISSUE TITLE
question about logical switches for OpenTX 2.0.15

### ISSUE THREAD

**Issue by Ray58** [opentx/opentx#2133]
Hi,
Is it possible with the V2.0.15 for Taranis to do several logical operations in one equation without using LUA?
Example: I would like to do something equivalent to this:

L1= !L2 AND !L3 AND !L4.
Or another example
L2 = C- AND L3 OR L4

Thanks

**Comment by kilrah** [comment]
You can use the AND switch for an extra condition but that's it.

BTW this place is not for user question please, only development-related detailed issue reports and suggestions.

**Comment by Ray58** [comment]
Ok thanks.

Ray
