### ISSUE TITLE
9XR-PRO - wav files of more than 6 letters does not appear in the pick list

### ISSUE THREAD

**Issue by panguitou** [opentx/opentx#2137]
Firmware opentx-9xrpro-2.0
The wav files with a name of more than 6 letters does not appear in the play track picklist and cannot be select : 
![20150312_180245](https://cloud.githubusercontent.com/assets/10453190/6623718/1282bd32-c8e5-11e4-8faa-572def969a52.jpg)

On the opposite all the files even with longer name are accessible in the SD-HC Card screen :
![20150312_180117](https://cloud.githubusercontent.com/assets/10453190/6623791/7c76553c-c8e5-11e4-96c5-2bec8f6791de.jpg)

To overcome this problem the wav files have to be renamed with maximum 6 letters name.

Thanks in advance
JM

**Comment by kilrah** [comment]
It's normal, 6 chars is the max length that can be stored for names in special functions on sky9x/9XR-Pro.

**Comment by panguitou** [comment]
Merci, désolé pour le dérangement.
JM
