### ISSUE TITLE
opentX 2.099  Simulation  TaranisPlus  no SWR selection at Telemetrie possible

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2146]
Date 16.03.2015  openTx 2.099  simu  for Taranis Plus
At Telemetrie screen, can't select SWR

![snapshot_27](https://cloud.githubusercontent.com/assets/6217896/6693126/2adb788e-ccd1-11e4-8d17-62fcb4df3f16.png)

**Comment by kilrah** [comment]
SWR is only enabled if the RF module reports it supports it. Might need to set that to on in the simu...
