### ISSUE TITLE
bug: voltage telemetry should change to zero if sensor disconnect from battery

### ISSUE THREAD

**Issue by offer-shmuely** [opentx/opentx#2148]
Voltage Telemetry does not reset if sensor disconnect from battery

Setup:
OpenTx 2.0.12
Voltage Sensor: FRSKY SP-FLVS - SMART PORT LIPO VOLTAGE SENSOR
Revicer x8R

Expected Behavior:
   In case voltage sensor disconnect from battery, telemetry show 0 volt

Actual behavior:  
   In case voltage sensor disconnect from battery, telemetry show the last voltage

Problem:
   Since one (I am) may use the telemetry of to decide when to land, 
   the low voltage alarm will never operate, and the plane may crash.

**Comment by kilrah** [comment]
As far as I know it's impossible for us to know if the sensor got disconnected form the battery with the data we get from the telemetry.

**Comment by offer-shmuely** [comment]
Does the sensor itself send the same values forever?

How can it be verified if it the sensor or the OpenTX?

**Comment by kilrah** [comment]
I just checked in the 2.1 branch and the sensor does stop sending values if disconnected. So that feature will be supported (and is already implemented) in 2.1, every telemetry value will have a timeout flag.

**Comment by offer-shmuely** [comment]
Thanks!
Is there a milestone for 2.1?

**Comment by kilrah** [comment]
If you mean estimated release time frame... No.

**Comment by bsongis** [comment]
No timeframe, but it's already available in nightly builds
