### ISSUE TITLE
Enhancement: add A2+ to telemetry screen

### ISSUE THREAD

**Issue by offer-shmuely** [opentx/opentx#2149]
Enhancement request

In telemetry screens, I can set to show A1 / A2 / A1- / A2-
Can you add also A1+ A2+

When I connect simple current meter, it will be nice to show the max current used
I believe on other sensor it may be used as well.

(Grate work, love the OpenTX)

**Comment by kilrah** [comment]
Each value will have min/max in 2.1.

**Comment by offer-shmuely** [comment]
Cool, thanks.

**Comment by bsongis** [comment]
Again, we need your tests on the nightly builds, the telemetry system was rewritten almost from scratch

**Comment by offer-shmuely** [comment]
I will test it when it will reach to Beta stage (will it?)
Since I have only one transmitter that I use, it used for 50 size plan for competition as well, so I afraid of issues.
