### ISSUE TITLE
Companion: GVAR names shouldn't be present for 9x

### ISSUE THREAD

**Issue by vian31** [opentx/opentx#2150]
Hi all, I am really impressed by the Opentx software, thanks for that great job.

I would like to report a minor bug in Campanion about the GVAR fields on the FM page: the software is not recording the names of the GVARs when you exit the soft.
At least, as an improvement, it would be very appreciated to have the GVARs' names on the OpenTX GVARs' page (IE the CURVES page).
On the other hand, it would be very usefull to have more than 5 GVARs in OpenTX for 9X devices.
Some complex programs could use 2 or three more.

Thanks !

**Comment by kilrah** [comment]
GVAR names are not available on the 9x, not enough resources.
Same for the 5 GVAR limit, you won't get more on a 9x...

**Comment by kilrah** [comment]
Fixed... not the way you'd like unfortunately :(

**Comment by vian31** [comment]
Thanks for this clear answer kilrah, neverthless could you please fix the recording bug on Companion ? It should be very usefull to have the names of GVARs in the computer's soft as a reminder.
Rgds

**Comment by kilrah** [comment]
It's not a bug, companion does not have a way of recording anything separately from the radio's eeprom.

The bug was that GVAR names shouldn't have been displayed in companion for the 9x, and that's what I corrected.

**Comment by vian31** [comment]
OK thanks.
Have a nice day.
Vianney
