### ISSUE TITLE
minus value not allowed in LS Delta.

### ISSUE THREAD

**Issue by Mow06** [opentx/opentx#2153]
On Companion a d>=x switch function will not allow a negative value in V2.

Can set a negative value on the radio.

OK not quite that simple.

In Companion if you set a LS to |d|>=x you cannot set a negative value V2 as expected.
If you now change the function in that LS to d>=x you still cannot set a negative V2.

If you set a function of d>=x you can set a negative V2. 
If you then change the function to |d|>=x you can still set a negative V2.

**Comment by tomkfly** [comment]
I have no problem in OpenTX Companion v 2.0.15

**Comment by Mow06** [comment]
Read it again. Don't want a negative with ABSOLUTE.
But if you change a switch function from NON-ABSOLUTE to ABSOLUTE delta, you can't set a negative value, unless you clear the switch and reload it.

**Comment by kilrah** [comment]
Change tab then go back to LS tab and it will be OK. The changes are just not taken into account until the tab is reloaded at the moment.
