### ISSUE TITLE
keep data on screen after loss of signal.

### ISSUE THREAD

**Issue by geofrancis** [opentx/opentx#2155]
i noticed when mavlink data cuts off the screens go blank. this is a problem if you crash a plane and it looses power in the distance since you now have no way of finding it. 

if its possible could you get it to keep the last known gps coordinates on the screen.

**Comment by abvgeej** [comment]
Cant reproduce as mine keeps the data till the power cycle.

**Comment by kilrah** [comment]
You don't even say what radio you're using, how you're feeding it with data, what build options you use...

**Comment by geofrancis** [comment]
sorry

im using a turnigy 9xr with latest opentx -mavlink connected to an apm with AC 3.2.1 using gitsly fork of openlrsng v3.5.
