### ISSUE TITLE
At simu Taranis,  how to come into bootloader menu   which char at win simu used?

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2156]
Sorry simply question Taranis V2.099 next
At simu, how to come into Bootloadermenue at simu?
All other kexboard char for Simulation are clear
S = screenshot
F1 to F8 for Trimms
A-H for switches 
up, down, Enter, page up, page down, Bakcspace for the 6 Switches

But no idea how to start Simu in Bootloader menü
I use Linunx for Compile and simu

**Comment by projectkk2glider** [comment]
You can't. The bootloader is not even compiled for simu. Why would you want to use it in simu?

**Comment by hrenz** [comment]
not for running the bootloader, 
only to see the screens and selecting the new things
for screenshots for the manuals
