### ISSUE TITLE
Simu Display trimmvalue Change,  Values at wrong positions

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2157]
At Simu 
Display Trim Value
at Yes (allways on ) all values apperas at right position, its ok
but
with Change  (show short)  
at first start of showing trimm values they appears at wrong positions

Picture Taranis Stick Mode 4
At  trim of  Th,  Ail   (at left side)
Values appears  at Ele  and  Rud Position (right side)

![snapshot_26](https://cloud.githubusercontent.com/assets/6217896/6764508/617239da-cfb2-11e4-8be7-68b943bb40f8.png)

**Comment by kilrah** [comment]
And I'd rather have the vertical numbers displayed "normally". Don't like the vertical digits.
