### ISSUE TITLE
At Companion2.0.99 next  Play value  of TH  AIL  for test Audio at PC 

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2158]
Hy,
Linux,  compiled Companion2.0.99 ,  for test Audio at PC
have set  2 spezial funktions: Play value TH  3s,  Paly Value Ail  3s

Put Sticks in positiv direktion, Play Value:  Audio plays correct value  50 , 34 , 85 and so on
Put Sticks in negativ direction,  Play Value:   Audio plays allways first 500  then the correct value 

checked wav files, are ok in EN and DE both same
0104.wav = 500
0111.wav = negativ

**Comment by kilrah** [comment]
Can't reproduce.
Please list exact settings or send the eeprom file.
