### ISSUE TITLE
'slow' action causes control jump

### ISSUE THREAD

**Issue by JoeB99** [opentx/opentx#2165]
Setting up ailerons:

Mix:
CH6: [I2] Ail 100%
CH6: MAX 50% SW D- Slow(u0:d3)
CH6: MAX 75% SW D Down Slow(u0:d3)

Changing the switch from D- to Ddown causes the output to jump to 100% then ramp down to 75%

Changing the switch from Ddown to D- is the same.

Is this a bug?

**Comment by kilrah** [comment]
No. Slow works on changes of the source, not the enable/disable of a line. You should only have one slow per channel.

You would thus rather create an input with source SD on which you have those 2 lines (without slow), then on CH6 you choose that input, and add the slow.
