### ISSUE TITLE
My taranis v2.05 dont connect to opentx compagnon

### ISSUE THREAD

**Issue by benjamin35** [opentx/opentx#2168]
It was in v1 1.05 and finaly put it in v2.05 but now it dont connect....please HELP!!!!

**Comment by bsongis** [comment]
Perhaps you could ask on the forums. Pretty sure you didn't start it in bootloader mode.

**Comment by benjamin35** [comment]
How do i do that ???

**Comment by bsongis** [comment]
Again it's not the right place for this kind of questions.
Put the 2 horizontal trims towards the middle of the Tx

**Comment by tomkfly** [comment]
Don't plug in until after you have switched on the Tarannis with both trims towards the power switch. 
As has been said by others this is not the place to ask operation questions. Find a Taranis Forum using Google. RC Groups has loads of related forums.

Tom
