### ISSUE TITLE
Logical switches trigger additional voice tracks when shouldn't for Multi-pos S3

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#2185]
Sorry the subject is vague, as this is really hard to explain, but here goes. I have a multi-pos switch installed in Taranis Plus (6 positions, all calibrated to give values -100, -60, -20, 20, 60, 100). Under Logical switches for a model I have:
L1  a~x  S3  -100
L2  a~x  S3  -60
L3  a~x  S3  -20
L4  a~x  S3  20
L5  a~x  S3  60
L6  a~x  S3  100
These are used for playing sound files to vocalise the flight mode selected on the multi-pos switch. I also have another 6 Logical switches, which allows the same sound file to play out when I flick SH(down) - this simply tells me what mode I presently have selected. These are:
L7  AND  L1  SH(down)
L8  AND  L2  SH(down)
L9  AND  L3  SH(down)
L10  AND  L4  SH(down)
L11  AND  L5  SH(down)
L12  AND  L6  SH(down)

Special functions are:
SF1 L1 Play Track  mode1  (plays track 'mode1' when the multi-pos switch is moved to pos1 = -100)
SF2 L7 Play Track  mode1  (plays track 'mode1' when the SH switch is flicked down when multi-pos switch is in pos1 - remaining SF configs do the same for other 5 positions)
SF3 L2 Play Track  mode2
SF4 L8 Play Track  mode2
SF5 L3 Play Track  mode3
SF6 L9 Play Track  mode3
SF7 L4 Play Track  mode4
SF8 L10 Play Track  mode4
SF9 L5 Play Track  mode5
SF10 L11 Play Track  mode5
SF11 L6 Play Track  mode6
SF12 L12 Play Track  mode6

When I change from pos1 to pos2 (-60 on S3), it plays both the mode2 voice file (L2 condition met, so this is correct), plus also the mode6 voice file (but L6 condition is not met so shouldn't play this - this is the issue!). Again switch to pos3 (-20 on S3) - you hear mode6 voice file again (should not be played) plus additionally the correct mode3 voice file, and so on through the modes. 

The issue is that the voice file associated with mode6 (pos6 on S3 = 100) is incorrectly played when no condition is met in the logical switches to trigger this condition.

Running f/w opentx-taranis-plus-2.0.15
Date: 2015-01-14
Time: 01:31:19
EEPR:216

**Comment by kilrah** [comment]
That would be because when you change position of the switch it first breaks the current contact before making the next - and jumps to +100 for a short while in the meantime.

You should just use the built-in multipos switch handling (set the related analog input to multipos switch in the hardware tab, calibrate, then use the Sxy switches that will be added to the switch list).
That is designed to filter out the spike, and will drastically simplify your setup.
