### ISSUE TITLE
Ability to display current time in telemetry screens

### ISSUE THREAD

**Issue by ckleanth** [opentx/opentx#2190]
Not sure if this was addressed/can be done with the new telemetry revamp in OTX 2.1 but currently with OTX2.15, the current time disappears once you enter the telemetry screen menu.

One might say use a watch or your phone to check the time or exit the telemetry menu but hey if it can be added or can be done it will save me an argument of being late going back home…

**Comment by kilrah** [comment]
You can already do so, and even set an alarm.

![screenshot-1](https://cloud.githubusercontent.com/assets/6065069/7047974/0320004c-de21-11e4-81c6-2e3477547e50.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/6065069/7047975/0419ea62-de21-11e4-8df9-b3079f05fb66.png)

**Comment by ckleanth** [comment]
Cool thanks Andre

**Comment by kilrah** [comment]
And that's on 2.0.15 I might add.

**Comment by ckleanth** [comment]
Yes typo, sorry about that
