### ISSUE TITLE
Telemetry Screen Issue.

### ISSUE THREAD

**Issue by BarryCole** [opentx/opentx#2192]
Sorry if this has been mentioned, I did check through and could not see it.

On the telemetry Screen, Timer 1 and Temperature 1 are both shown as T1

Same with Timer 2 and Temperature 2 both shown as T2

Not a big issue, but if you can make it clearer it would help.

I would like to take this opportunity to thank all those involved in Open Tx, for their time and dedication.

Best Regards, Barry Cole  Hampshire UK

**Comment by kilrah** [comment]
Very obvious from the display format which one is which though.

**Comment by bsongis** [comment]
Anyhow in 'next' you will choose yourself a name for your timers and sensors
