### ISSUE TITLE
Critical: "TX Antenna Problem" error on FrSky Taranis Plus

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#2196]
There seems to be an extremely nasty problem being reported with the newer Taranis Plus radios that have the new main board with the XJT on the board that provide the standing wave measurement.  The transmitter will intermittently display popup "TX Antenna Problem"  followed by voice "Signal Loss" and then the aircraft into failsafe crash!  This is a highly intermittent problem. 

Could this just be a glitch in the standing wave calculation, and the most important and critical question, does 2.0.15 shut down the RF on this error.  The current Taranis Plus radios come from the factory with 2.0.9.2 and apparently it does shut down the RF.

There is the known glitch on getting the "TX Antenna Problem" popup when doing a telemetry reset, but on my system running 2.0.15 during the error on reset, the RF is not shut down. 

Help, this could become a significant problem.

Thanks,

Mike

**Comment by bsongis** [comment]
Is there anything new on this topic? The RF is NOT shutdown on Telemetry Reset. It seems to me that the user really had a TX antenna problem which the firmware cannot fix.

**Comment by MIKE-DAILEY** [comment]
Thanks for your very quick response.  So, just to be clear, you are saying that with 2.0.15 the RF is not shut down if there is a "TX Antenna problem" error pop-up during normal flying operations?

Thank,

Mike

**Comment by kilrah** [comment]
At least OpenTX does not stop transmitting on an antenna problem, all it does is display the warning. 
The module however may do what it wants and could stop, but from out tests it is not the case. With current module firmware when causing the antenna problem on purpose control is maintained.

So if there's a problem somewhere there isn't anything we can do about it on our side, it's more likely to be a hardware issue.

**Comment by MIKE-DAILEY** [comment]
Thank you very much for your response.   Looks like FrSky has a problem with radios made in the last few months.    

Mike

**Comment by bsongis** [comment]
How many crashes like this have been reported? There was one report on openrcforums, did anybody else experienced the same issue?

**Comment by tomkfly** [comment]
There are a few reported on RC Groups. Not a lot, but enough to make it worrying.

**Comment by hrenz** [comment]
Same reports at FPV-Community
Antenna problem accours during flight with TaranisPlus Prod-date Dez2014
Or after 5 or 10 times Telemetry Reset an Antenne problem accours too
with 255 and then slow go down to 0 or 1

**Comment by mpjf01** [comment]
A separate thread has now been set up in RCG to collate reported instances of antenna warnings on Taranis in the interests of getting all the reports on that forum in a single place. They are spread between four of five threads at present..

http://www.rcgroups.com/forums/showt...7#post31322989

**Comment by kilrah** [comment]
The warning when telemetry is reset is unrelated and solved.

**Comment by bsongis** [comment]
I was given 2 different information yesterday, not sure both together make sense, and difficult to know today if it is an hardware or a firmware failure. For the moment the problem seems in the module though.
1) flashing the module with the previous firmware version removes the problem
2) only radios "B02" with the IPX connector have this problem

**Comment by bsongis** [comment]
By the way if your radio raises an "Antenna warning" on the bench, I wouldn't fly with it.

**Comment by MIKE-DAILEY** [comment]
The main thing I wanted to find out is if OpenTX 2.0.15 shuts down the RF on the "TX Antenna Problem". I believe the answer to that at this point is NO.  I have a March 11, 2015 B02 system with 2.0.15 and IPX connector from Aloft Hobbies and after 25 hours of operation I have not had any problems at all.  There is a reported single event on a system with a serial number that is about 300 numbers older than mine so I did a lot of bench running before I flew it.  

Aloft Hobbies is working with FrSky to determine what is causing the problem.  When the reports of the problem first started being reported it looked like it could be wide spread because one person had two systems with the problem (one without the IPX and one without) etc., then after about 5 or 6 reports there haven't been any more on RCG. One of the systems did not show any problems, but then had an event after 15 hours of run time.  

So it looks like it is limited to very few systems and the problem is very intermittent.  There is a report of a system with 2.0.13 that had a event without loss of control so that is good news because that was not the case with the factory installed 2.0.9.2. 

Hopefully Aloft Hobbies and FrSly will get this figured  out so we all know the root cause and we can fly without any worries. FrSky will be able to analyze the firmware in the internal XJT RF module and find the root cause.

**Comment by bsongis** [comment]
Latest news ... the problem seems to be related to the IPEX connector. A wrong batch.

**Comment by MIKE-DAILEY** [comment]
Does anyone know the serial numbers or build date of the radios impacted?

**Comment by bsongis** [comment]
This is something to ask to FrSky! By the way I think we can close the issue, it has nothing to do with OpenTX, and we can't fix anything at our level.

**Comment by sandrinio01** [comment]
can someone help me PLS. I have taranis 9xd. when the range is more then 120 the alarm starts at 45 RSSI. how can i increase the range. as I know it should work in more then 2 km range. what can be the  problem reason?

**Comment by projectkk2glider** [comment]
Please use forums for such questions. Just to get you started, try with another receiver, if the range is the same with the new receiver, then the radio has a problem.

**Comment by sandrinio01** [comment]
i dont have another receiver. is there any other way to test it?

**Comment by projectkk2glider** [comment]
>is there any other way to test it?

No, unless you have access to expensive RF measuring instruments.

**Comment by DjLiviuX** [comment]
hi, i am writing this for everyone to know and understand the risk of modding the taranis antenna.
If you mod the taranis tx module with and external antenna be aware not to touch the live wire ! The final IC that does the TX amplification gets ruined by ESD so be cautious !

**Comment by kilrah** [comment]
Yep - between the fine soldering and high sensitivity of the PA to ESD it's really not recommended. Wayne at Alofthobbies says he sells multiple replacement boards per week to people damaging their radios trying to do the mod.
