### ISSUE TITLE
wrong selection when choosing a fly sessions in log viewer

### ISSUE THREAD

**Issue by griebd** [opentx/opentx#2198]
Just (actually many days ago :wink:) noticed that when you select a fly session in log viewer the selected rows doesn't mach the fly session.

The problem is that some variables are declared as int when they should be double.

Will make a pull request soon (my last pull request #2191 to next already included the changes).

**Comment by griebd** [comment]
Fixed on next by #2191!

**Comment by bsongis** [comment]
Would you fix it on 'master' as well? Or it's just too much work and doesn't need to be fixed in 2.0.16?

**Comment by griebd** [comment]
it's already fixed and merged on master, #2200. The issue was still open because of next, but I'm preparing a new related pull request and noticed it's fixed and merged on next too.
The important part is, this is solved and can be closed. :wink:

taking the opportunity, should I leave it open for you guys to close or can I close the issues I solve? (yes, I will try to keep contributing to this project, I use it and find it easier to contribute codding than donating)

**Comment by bsongis** [comment]
Yes you may close the issues you fix! Don't forget to update the milestone if needed. Thanks for your help!

**Comment by kilrah** [comment]
Issues close themselves automatically once the fix is merged on next if you reference them with "fix #xxxx" in the commit or pull request :)
