### ISSUE TITLE
Telemetry graphic bug

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2203]
Hi folks,

There is a graphical bug with the French version of OpenTX v2.0.15 as shown below.
<img  src="http://i19.servimg.com/u/f19/15/93/13/30/barbug10.jpg"/>

By the way, there is a restriction for RPM field. The maximum value which can be displayed in the bar graph is 12750. The propeller of one of my plane can reach 15000rpm. This higher RPM value is correctly record in the LOG and also correctly displayed in the classic telemetry screen. Maybe should I open another ticket?

**Comment by kilrah** [comment]
Wow... did we finally find the first person who uses these bars?

**Comment by bsongis** [comment]
I think we won't fix the RPM problem, it's completely changed in 2.1 and the restriction is not there.
Perhaps you could have a check of the bars in 2.1, it would help us!

**Comment by bsongis** [comment]
I will reduce the bars length a little bit in 'master' before 2.0.16

**Comment by kilrah** [comment]
Where do those strings come from? Could just use the 4-char ones

**Comment by bsongis** [comment]
True, perhaps it's the translation which is wrong

**Comment by LapinFou** [comment]
I think the bars display are very handy for reading remaining fuel, total consumption and RSSI.
No need to read the value, a quick look and the bars gives you the wanted information.
For RPM, it doesn't matter.
As soon as I will have more time, I will try the 2.1 beta version.

Thanks again for your hard work !
:)
