### ISSUE TITLE
plot is wrong when hand picking data in log viewer 

### ISSUE THREAD

**Issue by griebd** [opentx/opentx#2204]
If you select the rows one by one the points are ordered by the order you select them, not by time as expected.

One line fix on the way... :wink:

**Comment by projectkk2glider** [comment]
@griebd Is this fix also needed on the `next` branch? Otherwise we can close this issue.

**Comment by griebd** [comment]
yes, but the fix is already included in griedb/next_log_viewer_performance_2163 branch with some more updates to improve performance! there is more to do, but maybe I should do a pull request with all that is already done, what do you think?

**Comment by projectkk2glider** [comment]
No need to make a separate pull, I just wondered if this can be closed. We will leave it open for now.
