### ISSUE TITLE
LCD contents shifted upwards by 6 pixels (with wraparound) on 9XR

### ISSUE THREAD

**Issue by xmxwx** [opentx/opentx#2221]
'next' branch, 41f78440db2230a20bb980c54640c406a65e36cf

**Comment by bsongis** [comment]
What? Why did you mention this commit, it is related to Companion! Did you compile your firmware yourself? 

We introduced options for LCD, I guess there is either an error in the Makefile or in the compile script

**Comment by bsongis** [comment]
No I don't see any issue in the Makefile. Did you try many nightly builds to help me and find which commit is involved?

**Comment by kilrah** [comment]
And is it on the actual radio or in the simulator?

**Comment by xmxwx** [comment]
When I was working on https://github.com/opentx/opentx/pull/2210 I did everything on the master branch. @bsongis, when you suggested the right thing - to do it on the next branch - I've rebased my changes, compiled and flashed into 9XR and saw this problem. Then I checked out clean next (hence the mentioned commit) and saw that the problem is still there even without any of my changes. Thus, I posted this issue here.

@bsongis 
> Why did you mention this commit, it is related to Companion!

It is just the commit I've compiled and flashed into my 9XR. Not a commit that I think is bad.

> Did you compile your firmware yourself?

Yes.

> Did you try many nightly builds to help me and find which commit is involved?

No, not yet. I hope I'll have some time for this today in the evening. I'll try nightly builds. Or maybe I'll use my favourite git bisect because it will help me to do it logarithmically ;-).

@kilrah 
> And is it on the actual radio or in the simulator?

Actual radio. Frankly, I haven't yet tried the simulator.

**Comment by xmxwx** [comment]
BTW. I firstly marked it with "9X-Stock (m128)" label, but then I'll noticed that it's "9X", not "9XR". Shouldn't we have "9XR" label?

**Comment by bsongis** [comment]
Oh ok, now I understand everything, I didn't see it was the same person who opened this issue and the pull request!

**Comment by bsongis** [comment]
Would you do some dichotomia to see which commit is wrong? 

git reset --hard origin/next~200
=> check

git reset --hard origin/next~500
=> check

etc.

**Comment by xmxwx** [comment]
> Would you do some dichotomia to see which commit is wrong? 

Of course, that's what git bisect does :-)

Now I really gotta go... Till the evening!

**Comment by bsongis** [comment]
I learnt something with git bisect, I was used to do it manually!

**Comment by xmxwx** [comment]
I just finished git-bisecting.

c6cf0f915ec26f418d79afde6b9b4a7dc6bf819d is the first bad commit

**Comment by bsongis** [comment]
I see, would you revert it? I mean MEGA2560 should have its own
lcd_driver.cpp!
Le 25 avr. 2015 3:10 PM, "Michał Wróbel" <notifications@github.com> a
écrit :
