### ISSUE TITLE
PPM modulation opendrive/fulldrive

### ISSUE THREAD

**Issue by djdevil** [opentx/opentx#2239]
Hello i update my new 9xrPro to last version of opentx but tne my module assan v1 not work!! The problem is the protocol of ppm modulation..where i can change modulation ppp fulldrive?there is no menu!! Thx

**Comment by projectkk2glider** [comment]
What do you mean by *fulldrive*? You can change polarity and timings on the first page of model setup.

**Comment by djdevil** [comment]
In the menu of ersky9r firmware  In the Protcol Menu there is an option to Set PPM Drive to FullDrive and opedrive!

Full Drive outputs the PPM signal driving both high and low. OPENDRAIN only drives it low, expecting a pullup resistor, in the module, to pull it high. This was added because at least one module type caused a problem by passing the PPM voltage back through the module power pin preventing correct detection of power being switched off.

**Comment by djdevil** [comment]
any Reply???

**Comment by projectkk2glider** [comment]
It is clear now what you want.

**Comment by djdevil** [comment]
Thx i hope this fuction for the next update

**Comment by projectkk2glider** [comment]
I am not sure we have a spare location in eeprom for this new setting. @bsongis will know more. Maybe we could split `ModuleData::ppmPulsePol`?
```c
PACK(typedef struct t_ModuleData {
  int8_t  rfProtocol;
  uint8_t channelsStart;
  int8_t  channelsCount; // 0=8 channels
  uint8_t failsafeMode;
  int16_t failsafeChannels[NUM_CHNOUT];
  int8_t  ppmDelay;
  int8_t  ppmFrameLength;
  uint8_t ppmPulsePol;
}) ModuleData;
```

**Comment by djdevil** [comment]
Please...i want opentx on my radio

**Comment by bsongis** [comment]
@projectkk2glider Yes we could change the ModuleData structure (but only in 'next'). Perhaps we could even save one or two bytes in the whole structure

**Comment by djdevil** [comment]
Thank you very much😀

**Comment by bsongis** [comment]
@projectkk2glider Will you take care of this issue? At least the EEPROM change should be done before 2.1 is out to avoid problems ...

**Comment by projectkk2glider** [comment]
Ok, I will try.

**Comment by projectkk2glider** [comment]
@djdevil This is now done, but only in the upcoming OpenTX 2.1 version which is not yet airworthy! Use with caution.
