### ISSUE TITLE
Companion log viewer is slow

### ISSUE THREAD

**Issue by zieren** [opentx/opentx#2240]
I have a log file with RSSI, cell voltage and altimeter data. For a 35 minute flight, plotting these three graphs takes 20 seconds (Windows 7, i3 550 3.2GHz, 16GB RAM - all pretty standard). This seems like a bug, maybe some O(n^2) behavior somewhere.

I can't seem to attach the file here; it's at http://zieren.de/tmp/log.zip
The seesion in question is 2015-04-15 17:20:56 (though IIRC the problem also happens for other seesions).

The problem doesn't exist with short sequences, like when I turned on logging by accident and turned it off seconds later.

**Comment by kilrah** [comment]
Was already addressed in https://github.com/opentx/opentx/issues/2163.
