### ISSUE TITLE
Grouping/labelling of logical switch cascades and Special Functions.

### ISSUE THREAD

**Issue by Matty2B** [opentx/opentx#2242]
Complex setups often require "cascades" of logical switches where the output of one is the input of another. If a setup requires more than 1 of these cascades it can be tricky to identify where one stops and where the next begins. This is a particular problem when you get near the 32 switch maximum, and it often isn't possible to leave a gap of 1 switch between cascades; setting up and troubleshooting issues becomes much trickier to do.

To get around this it would be nice to have an indexing number or short free text field for each LS. This would mean for example that all the LS's used to (say) arm landing gear deployment could be labelled "1" or "Gear". As a final nice to have enhancement it would be great if in Companion we could display LS's based on this field i.e. have a search box at the top of the LS screen into which you type the index number or name, and only those LS's that meet this criteria are displayed. Thissearch  functionality could also be added for Special funtions too so that only (say) voice callouts are displayed etc.

**Comment by projectkk2glider** [comment]
This is all true, but we are limited by the available storage space in EEPROM. Maybe in the future we will move to some other kind of storage for models and then something like this will be possible.
