### ISSUE TITLE
mixersmon option in Companion has no effect

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2256]
The downloaded firmware has no mixers monitor. If I compile it myself it works.

**Comment by kilrah** [comment]
Compilation script likely missing the option

**Comment by LapinFou** [comment]
I don't know who got this brilliant idea, but I loved the mixers monitors. So handy to debug complex mixers!!!
:+1:

**Comment by projectkk2glider** [comment]
I've changed complilation script, it should work now.

**Comment by bsongis** [comment]
Did you change on both 'next' and 'master'? I know, this script is really horrible, I plan to rewrite it from scratch

**Comment by projectkk2glider** [comment]
Ups only master, I will fix next now...

**Comment by projectkk2glider** [comment]
Done
