### ISSUE TITLE
Sounds do not play in simulator

### ISSUE THREAD

**Issue by mpjf01** [opentx/opentx#2259]
In a recent upgrade I note that sound files such as system warnings and timer sounds play when the simulator button is activated.

Sounds that are flight mode related, those in the folder titled with the model name and with names such as "Launch-on" do not play.

**Comment by projectkk2glider** [comment]
Provide the output of Debug window (press F6 key while in simulator) after you try to play some model sounds.

**Comment by mpjf01** [comment]
After a lot of messing about I had the idea to make a new clone of my SD card and the sounds now work, Seems the old copy on my desktop got corrupted somehow.

Sorry for the bother, OK to close now.
