### ISSUE TITLE
Be able to reference the values "A1 low" and "A1 critical"

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2269]
I would like to reference the values I enter for "A1 low" and "A1 critical" instead of copying these values. If I'm able to reference these values in logical switches I can use such a switch to trigger a SF that says the value of A1 each 30 seconds and each 10 seconds is the value is equal or lower than the "A1 critical" value (this is just an example)

This could be done for some other variables

**Comment by kilrah** [comment]
Those 2 values are "legacy" and only there for retrocompatibility.

If you want more flexibility don't use them and use an LS instead (a<x A1 xx.x), you can then do anything you want with it.
