### ISSUE TITLE
firmware won't load into transmeter

### ISSUE THREAD

**Issue by Kennyptho** [opentx/opentx#2277]
ok, I just downloaded the newest version of Companion OpenTx ... It installed just fine. Then it asked if I wish to load the firmware into my radio... I click ok then a message popped up saying like always  DFU Util executable not found ....

**Comment by Kennyptho** [comment]
for what its worth the radio I think was a waste of money

**Comment by bsongis** [comment]
Yes if you don't read the manual it will be difficult. Where do you live, here 2 guys are waiting for the Taranis being again in stock, they will be happy to get yours.

**Comment by Kennyptho** [comment]
I not chineese i speak english and read it hell i didn't even get a god damn manual with my radio so blow it out yer ars pall

**Comment by Kennyptho** [comment]
ya they can suck ma nuts chuck over 325.oo dallers and they can fight over it

**Comment by Kennyptho** [comment]
thats not including the taxs and duties  and deliveries i paid... by the time i got it, it cost me over 400.oo dollars

**Comment by Kennyptho** [comment]
fix your fucked up software dickhead

**Comment by tomkfly** [comment]
Great way to ask for help

**Comment by kilrah** [comment]
The software that your radio comes with is perfectly good and is not supported by us. You have absolutely no reason to change it, especially if you can't read or understand instructions.

**Comment by ckleanth** [comment]
Great way to ask for help x2, this is not the radio for you. sell it off, I'm sure someone will be happy to take it off your hands.

**Comment by griebd** [comment]
400 dollars? just send me it and I will gladly take it to use as testing platform for OpenTX, so I can help making it even better than it already is!!!!!!
OpenTX and FrSky just changed the RC world for the better!!!!!!!

**Comment by Kennyptho** [comment]
you may sell a cheep radio but over all Futaba (
18MZ
18-Channel 2.4GHz Computer System) beets Fr Sky hands down and they have a full illastraited manual simplifed

**Comment by Kennyptho** [comment]
SCAM ARTTEST MORE LKE IT

**Comment by griebd** [comment]
I do not sell, I'm offering to buy yours for the price you paid! Anyhow, locked too.... just a spammer!
