### ISSUE TITLE
unable to set negativ values for logical switch conditions

### ISSUE THREAD

**Issue by diablol** [opentx/opentx#2283]
It seems not possible to set negativ values for logical switch conditions. 
You can do it in companion but not in the transmitter. 

by the way is it normal that 2.0.99 companion at current status is showing very different values in some areas compared to the firmware?

**Comment by kilrah** [comment]
Looks like a bug indeed.

> by the way is it normal that 2.0.99 companion at current status is showing very different values in some areas compared to the firmware?

Hmm what exactly? Many things are still broken, of course knowing which will help fix them.

**Comment by diablol** [comment]
> what exactly?
at moment actually everything ;) strange letters and wrong buttons everywhere

![fnct](https://cloud.githubusercontent.com/assets/12254611/7549975/6841e8d8-f64e-11e4-962b-1e6d2e023e2e.png)
![img_20150509_131738](https://cloud.githubusercontent.com/assets/12254611/7549976/68454c9e-f64e-11e4-8656-b5d8c184f08d.jpg)
![input](https://cloud.githubusercontent.com/assets/12254611/7549977/6849c1ca-f64e-11e4-98a1-8f29f0934473.png)
![mixes](https://cloud.githubusercontent.com/assets/12254611/7549979/684e1392-f64e-11e4-9412-55d1158a25a5.png)
![timer](https://cloud.githubusercontent.com/assets/12254611/7549978/684b97d4-f64e-11e4-84b5-cd496fe59056.png)

**Comment by kilrah** [comment]
Are you using firmware and Companion builds from the same day? There have been changes recently.

**Comment by bsongis** [comment]
I am afraid he doesn't use the nightly builds but the "release" builds which are not up to date at all!

**Comment by diablol** [comment]
What do you mean? 2.1 release?
I use the nightlys from here http://jenkins.open-tx.org/nightly-21/
I Install companion and force download over companion and flash it. 

Am I doing something wrong?

**Comment by diablol** [comment]
Ok as I recently asked in openrcforum if the download over companion is the same as the one in the nightly directory it seems they are not the same. I just flashed the one from nightly and it appears with the same issues. So I assume they are not the same. Am I right?

**Comment by kilrah** [comment]
I am the one who answered you on the forum but only learned right now that no they were not the same, the builds available from companion were not the latest state of the next branch, they needed manual update which hasn't been for a long time. 
That should now be fixed for next builds..

**Comment by diablol** [comment]
I know you answered but no problem :) Keep the good work up guys!! Your job is unbelievable. 
As I get used to github I will try to participate more as I do a lot of stuff with opentx.

**Comment by kilrah** [comment]
OK it's now fixed, it will be updated nightly and a build has been run so if you now download from companion you'll get the current status (checking for updates will NOT notify you though, you just have to download manually).

Note that due to the same changes you saw in companion you'll have to discard all your radio settings (do a factory reset on the version screen).

**Comment by diablol** [comment]
even closed I add here a similar problem

unable to set decimal value e.g. for calculated lowest cell value sensor for logical switches


![volt](https://cloud.githubusercontent.com/assets/12254611/7550925/82cfe822-f675-11e4-8052-7ea117b543d4.png)
![tele](https://cloud.githubusercontent.com/assets/12254611/7550927/88d2b6d2-f675-11e4-9a9f-65965d51cab1.png)

**Comment by diablol** [comment]
e.g. for ALT the units for logical switches are always +1 from the telemetrie list
for example meters in telemetrie results in feet for log switches
this all may the same problem

**Comment by kilrah** [comment]
Can you provide an eepe file that shows the problem? Would save quite a bit of time recreating one to reproduce.

Might want to open a new issue, it has nothing to do with the original one, best to separate unrelated things.
