### ISSUE TITLE
Scroll speed

### ISSUE THREAD

**Issue by hillflyer** [opentx/opentx#2294]
I find the scroll speed in menus often too fast to read the entries.
Is it possible to make it adjustable?
Thanks!
Hannes

**Comment by projectkk2glider** [comment]
Maybe we could add a radio setting that would set the scroll speed (maybe just a couple of values, slow, medium and fast (fast would be equal to current speed)).

**Comment by kilrah** [comment]
As we have the source popup as shortcut now I doubt that would be very useful, much less scrolling to do in the first place.

Anyway after a couple of days of use you start to know where things are and can estimate the time to hold the key quite well...
