### ISSUE TITLE
FLVSS voltage display

### ISSUE THREAD

**Issue by Cetros** [opentx/opentx#2296]
I am quite new to Opentx (one week old! :P) and I love it.
I am doing some tests and I don't know if the results work as expected.
I have 2 FLVS-S (Smart Port version) connected to 2 6s batteries. Using Opentx 2.0.17 on my Taranis-Plus, after setting different IDs to FLVSS I am able to see both Cell and Cells values from each Battery switching randomly on the Telemetry screen. Same for each cell value on the voltage cell column (switching randomly).
I have seen there are some threads about this ( #1409 and solution in #1444 , also same thing for FLVS-01 on #158 ) and all of them are closed.
I was expecting to have at least all 12 cells plotted in the column as seen in this photo: 
![](https://cloud.githubusercontent.com/assets/7201728/2648835/e8395222-bf5b-11e3-894f-871a79459b31.jpg)
Also at least showing lowest cell voltage from both batteries as Cell and Cells values (not switching). Having both of them may be also interesting.
I have read that you are reworking telemetry for OpenTX 2.1.0 version so maybe I am just reporting something that will be solved on future versions but as I have seen older posts as "Solved" I was hoping it was already done.

**Comment by kilrah** [comment]
Yes they have been marked as solved as it's all ready for 2.1.

The current support in 2.0 only works for a single >6 cell battery, it's all we could do until the big rework but already catered for a few people's needs.
