### ISSUE TITLE
telemetry screens in companion

### ISSUE THREAD

**Issue by diablol** [opentx/opentx#2299]
unable to setup the telemetry screens in companion. There is no dropdown menu for numbers or bars.
2.0.99

**Comment by kilrah** [comment]
To clarify, the screen type can be selected but the dropdowns used to select items are not populated

**Comment by diablol** [comment]
Not sure I understand.
I mean it is not possible to select sensors to be shown on a screen. The dropdown is always empty. But working in the firmware.

**Comment by kilrah** [comment]
Yes that's what I found out. Your post sounded like the dropdown to select the screen type was missing.

**Comment by diablol** [comment]
your are right it sounds like that :)

**Comment by bsongis** [comment]
Needs a serious test, I had to do a big refactoring ...
