### ISSUE TITLE
SF Bug with the comparison tools 

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2308]
Some difference are not detected in the comparison tool.
Here is an example.
![diffbug](https://cloud.githubusercontent.com/assets/1685030/7652648/f55faac4-fb0e-11e4-8059-9c70ccbdefdd.png)

**Comment by bsongis** [comment]
Which version?

**Comment by LapinFou** [comment]
Sorry !!
Companion 2.0.17

**Comment by projectkk2glider** [comment]
This will be fixed as a part of other changes in a branch https://github.com/opentx/opentx/tree/projectkk2glider/print_and_compare_refactoring
