### ISSUE TITLE
[Bug][OpenTX 2.0.17] Curve not linked with setting in INPUTS menu

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2309]
Hi folks,

I don't know if it is a bug or not, but it was quite confusing for me.
Most of my setting are done through Companion, so I never noticed before.
I was on the field doing some EXPO adjustment on my Yak55.
I got a triple rate, so it means for each input, I got 3 lines with a different ratio and expo.
![triplerate](https://cloud.githubusercontent.com/assets/1685030/7653776/a0e40aa8-fb18-11e4-847a-ec2e45f442b6.png)

Here is what I've done:
1- Go the INPUTS setting.
2- Select and edit the "MOYEN" rate (2nd line)
3- Change the expo parameter.
Then I realized the curve on the right was not changing.
![triplerate2](https://cloud.githubusercontent.com/assets/1685030/7653822/e98c48ec-fb18-11e4-839d-ab2c9221bc86.png)

In fact the curve doesn't reflect the current settings which are modified, but show the current curve which is applied on the input. Very confusing!

After I toggled from SD^ to SD-, then I could finally visualize the modification I was doing.
![triplerate3](https://cloud.githubusercontent.com/assets/1685030/7653912/90bf8264-fb19-11e4-8d51-7822e5eed651.png)

**Comment by kilrah** [comment]
The graph always shows what's currently active, it's a feature that's always been there and is also done that way on several other radios. That way you can toggle your switch and see the difference "live" on the graph as it changes.

**Comment by LapinFou** [comment]
Thanks. Sorry for that. I wasn't aware.
:)
