### ISSUE TITLE
Code duplication between gui/9X/lcd.cpp and gui/Taranis/lcd.cpp

### ISSUE THREAD

**Issue by xmxwx** [opentx/opentx#2315]
I strongly prefer modular code and separate implementations over monolithic code with a lot of #ifdefs. However, what we have right now joins drawbacks of both approaches bringing no advantages in return.

Do you agree that we should extract code common to gui/9X/lcd.cpp and gui/Taranis/lcd.cpp into a separate file (gui/lcd_common.cpp?) and leave in gui/{9X,Taranis}/lcd.cpp pieces really {9X,Taranis}-specific?

**Comment by bsongis** [comment]
Yes, I do agree, don't hesitate to propose something if you can!
