### ISSUE TITLE
Companion - GPX Export for Photo Geotagging

### ISSUE THREAD

**Issue by Lubive** [opentx/opentx#2329]
Hello together,

would it be possible, to integrate an .gpx export to Companion in order to be able to geotag Photos for Photogrammetry purpose (adding Longitude and Latitude to EXIF)?

The data is already there in the .csv and saving to .kml and re-convering to .gpx corrupts the data.

Any other hint to convert the .csv to .gpx is very welcome!

By the Way: I appreciate your great efforts into this project very much!

Regards
Ulrich

**Comment by projectkk2glider** [comment]
I see no data corruption:
* from Companion export to Google Earth
* in Google earth save the track to kml or kmz file
* use http://www.gpsvisualizer.com/ to convert saved file (kml or kmz) to gpx. 

It works for me.
