### ISSUE TITLE
incorrect view on the display of the simulator

### ISSUE THREAD

**Issue by tonimerlot** [opentx/opentx#2331]
incorrect view on the display of the companion simulator 2.0.17 on OSX 10.10.3.
![screenshot_2 0 15](https://cloud.githubusercontent.com/assets/11818855/7787114/ff643124-01f9-11e5-9960-6ce54b095eb1.png)
![screenshot_2 0 17](https://cloud.githubusercontent.com/assets/11818855/7787115/ff6914c8-01f9-11e5-9ba2-3bda2c6a1de3.png)

**Comment by kilrah** [comment]
Yeah it's known, just a build error. I've notified @andyjenkinson to rebuild but he must be unavailable these days.

**Comment by tonimerlot** [comment]
Thanks for the quick response.
