### ISSUE TITLE
FCS-150A

### ISSUE THREAD

**Issue by frobert0** [opentx/opentx#2333]
Hy,

Proposal to measure currents of heavy 150A.

When the supply line consists of two wires and only one is led by as sensor and then multiply this value in the transmitter 2, could be measured up to 300A.

**Comment by kilrah** [comment]
Multiplying by 2 will be possible in 2.1.

**Comment by frobert0** [comment]
Hi
unfortunately
  Curr + Curr
too imprecise

It would be better
  Curr * Number
