### ISSUE TITLE
File selection list broken in Play Track

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2335]
I get a ton of empty lines at the bottom after the list of files in the Play Track file selection

**Comment by bsongis** [comment]
Not on the simu, right?

**Comment by kilrah** [comment]
Hmm yes, if I press the + key to wrap to the bottom of the list I get a crash...

![clipboard01](https://cloud.githubusercontent.com/assets/6065069/7821603/3e9c3236-03f0-11e5-8f17-26c3c86d5408.jpg)
