### ISSUE TITLE
 [9X / MEGA2560] OpenTX doesn't start if HELI option is not selected

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#2337]
http://openrcforums.com/forum/viewtopic.php?f=45&t=7052&p=97568#p97568

**Comment by JivaroFAD** [comment]
Some problem detected on my boards, with 2.0.99, but only with FrSky telemetry connected to the board. Another board without telemetry seems to work well whatever PPM or Heli options.

**Comment by JivaroFAD** [comment]
Make exhaustive tests today on M2560 board and stock LCD (KO is only at flash, with always the some avrdure error : 0x07 != 0xff) with 2.0.99 :
![image](https://cloud.githubusercontent.com/assets/8770878/8147988/60587016-1286-11e5-85f6-c89ed5553350.png)

Very strange...

**Comment by kilrah** [comment]
> we have just a verification mismatch after flashing (with always the same avrdure error : 0x07 != 0xff)

At what address? There have been known problems with the firmware of some AVR programmers that would mess up when programming beyond the first 128K if I remember well.
