### ISSUE TITLE
Companion QCheckBox backupEEprom is enabled by default

### ISSUE THREAD

**Issue by JivaroFAD** [opentx/opentx#2338]
All in the tittle !

This is problematic with Arduino M2560, as initial EEprom is not valid (by default in the wring size : 2048 bytes againts 4096).

This issue can solve be user with selecting a backup folder in radio settings, then he can enable or not the checkbox, but that is not very intuitive. It seems preferable to have the default state of the class at "false".

**Comment by kilrah** [comment]
The default state is enabled because of people not thinking of making backups until it's too late. Shouldn't be a problem for M2560, the first backup would just be unuseable.

What's exactly the problem now? If it can be fixed by people selecting a backup folder it seems the issue is rather that there should be a valid default in there.

**Comment by JivaroFAD** [comment]
The problem is that the checkbox is shown as not checked, although the default state of the class is enabled.

**Comment by JivaroFAD** [comment]
If i'm not wrong, in flashfirmwaredialog.ui, there's an inconsistency between :
widget class="QCheckBox" name="backupEEprom" : property name="enabled", bool = "true"
and 
Backup and restore Models and Settings : property name="tristate", bool = "false"
We should have "true" and not "false" to have the checkbox checked by default ?

**Comment by JivaroFAD** [comment]
New tests today, after this mod : 1dc10122ea637a272f0d9bd0b365a49a792e4937
Not very concluant : checkbox "Backup and restore Models and Settings" in Flash Firmaware panel is not checked by default.

An another strange thing : this checkbox is not linked to the checkbox "Enable automatic backup before flashing firmware" in Settings/Settings/ApplicationSettings, each can be checked or not independantly. They should be linked, or I missed something ?

**Comment by bsongis** [comment]
This is not the same thing:
1) "Enable automatic backup before flashing firmware" in Settings/Settings/ApplicationSettings = we do EEPROM backups in the directory configured
2) "Backup and restore Models and Settings" in Flash Firmaware panel = we read the EEPROM from the radio, flash the firmware, update the EEPROM and write it to the radio in the updated format. This is useful for radios which don't have automatic conversions

**Comment by bsongis** [comment]
This checkbox should be enabled by default.

**Comment by JivaroFAD** [comment]
Thanks for the explanation, I understand now the difference :)

**Comment by bsongis** [comment]
Would you put again the checkbox enabled by default as it was before? So that we can close the issue ...

**Comment by JivaroFAD** [comment]
Done : 88f907abc5b00b36cdf834ad49e66f1d508fe5a6
