### ISSUE TITLE
Function for display differences between transmitter and eepe-file

### ISSUE THREAD

**Issue by dklueh79** [opentx/opentx#2340]
Could a function be added, to display the differences between eepe file and the setup of the taranis?

**Comment by kilrah** [comment]
You can open the eepe, read from radio, then use the compare models feature?

**Comment by projectkk2glider** [comment]
I think that Kilrah's solution is exactly what you want. Some sort of automatic comparison of all models from one eepe and the radio is difficult/cumbersome. Closing.
