### ISSUE TITLE
model get corrupted after upgrading from 2.0.15 to 2.0.99 (from 2015/5/25)

### ISSUE THREAD

**Issue by offer-shmuely** [opentx/opentx#2343]
model get corrupted after upgrading from 2.0.15 to 2.0.99 (from 2015/5/25)
 
Radio: Tranis plus
old version: 2.0.15 
new version: 2.0.99 from 2015/5/25
model backup by companion 2.0.17
model restore by companion 2.0.99   from 2015/5/25
after version upgrading, the Taranis displayed a message of updating eeprom

Note: how can I send you the eepe files?

The following issues found:
setup page:
Throttle source was CH03 --> changed to THR
switch warning: was different settings --> all changed to upper
failsafe mode: was custom --> disabled

flight mode page:
name changed
fade out: was 0 --> 1.0
trim changed

Inputs page: all have bean lost
curves page: all lost
logical switch page: lost

![setup-page](https://cloud.githubusercontent.com/assets/7026911/7802559/074c9c8a-0341-11e5-90e1-0db4cade29c7.png)
![curves](https://cloud.githubusercontent.com/assets/7026911/7802565/102f9dd4-0341-11e5-8f6a-d34fa5fc3281.png)
![flight-modes](https://cloud.githubusercontent.com/assets/7026911/7802566/105ce654-0341-11e5-8cc3-ef5104547eef.png)
![inputs](https://cloud.githubusercontent.com/assets/7026911/7802567/1076f0b2-0341-11e5-96a9-b5a8bcf23da0.png)
![mixes](https://cloud.githubusercontent.com/assets/7026911/7802568/107af324-0341-11e5-9131-c6dce336d39b.png)
![special-functions](https://cloud.githubusercontent.com/assets/7026911/7802569/107cf840-0341-11e5-82d3-089c59b3c818.png)

**Comment by kilrah** [comment]
Those result from recent changes, as there are still more changes to be done the upgrade procedure hasn't been updated yet.

Note that the upgrade from 2.0 to 2.1 WILL require major review of models, notably anything related to telemetry will be lost.

**Comment by bsongis** [comment]
Thanks, I introduced a shift of one byte ...

**Comment by offer-shmuely** [comment]
Is it ready to be tested it again?

**Comment by bsongis** [comment]
I will launch a nightly build right now

**Comment by bsongis** [comment]
Nightly build is now launched:
http://jenkins.open-tx.org:8080/job/OpenTX%20Unstable%20-%20Nightly%20builds/
