### ISSUE TITLE
companion/firmware dismatch logical switch

### ISSUE THREAD

**Issue by diablol** [opentx/opentx#2346]
2.1.0 nightly:
e.g. L1 condition in companion results in L11 in the firmware
L1 in firmware is FM8 in companion

**Comment by bsongis** [comment]
Which version / board?

**Comment by diablol** [comment]
current nightly for Taranis

**Comment by bsongis** [comment]
2.0 or 2.1 ?

**Comment by diablol** [comment]
opentx 2.1 if you mean that ;)?
