### ISSUE TITLE
Simulator volume different in Companion and standalone Simulator

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2351]
The volume level in Simulator is louder than in Companion.

It has been this way probably since the beginning of simulator audio. The recent addition of `simulator volume gain` in #2260  did not change/affect this behavior. 

The same issue is present on Linux and Windows (I can't test on OSX). No idea why this is happening.

**Comment by mpaperno** [comment]
Is this still an issue?  I haven't noticed any volume difference when switching between the two, on all 3 OSs.

**Comment by projectkk2glider** [comment]
Tested with 2.2, all OK.
