### ISSUE TITLE
precision for telemetrie voice

### ISSUE THREAD

**Issue by diablol** [opentx/opentx#2371]
opentx 2.1

e.g. my voice call "play value" for V_min only says "3V". But we need at least prec1 or actually prec2.

**Comment by bsongis** [comment]
Which telemetry field are you playing? Is it the same for field, field- and field+? What is the PREC you choosed for this telemetry value. Here I use Cells, it's ok with PREC1. PREC2 normally won't be accepted.

**Comment by diablol** [comment]
yes cells works.
but most others have wrong voice units. C° is watts mph is watts and a few others are wrong too.

I refered to a custom sensor for  lowest cell voltage. 
field+- is the same

**Comment by bsongis** [comment]
Did you install 2.1 sounds?

**Comment by diablol** [comment]
ehm nop.

where to get?

**Comment by bsongis** [comment]
http://www.open-tx.org/links.html

2015-06-18 18:38 GMT+02:00 Mathias Krapp <notifications@github.com>:

**Comment by diablol** [comment]
ok I didnt knew that.

now she says "3.9" without "volts". Also for "cels" the unit is missing too.

AND all units are shifted one element in the unit list. So if the list is e.g. : volt,amps,mah,mph,knots,celsius,fahrenheit.

amps are called mah and knots fahrenheit etc.

that may also is the reason for voltage having no unit..

**Comment by bsongis** [comment]
It means you don't have the latest nightly builds, I fixed this very recently

**Comment by diablol** [comment]
It means I am quiet now ;)

**Comment by bsongis** [comment]
I start a new 2.1 prerelease now, please confirm we can close this issue

**Comment by diablol** [comment]
installed 2.1 sound and recent nightly, but unfortunately units still are shifted

**Comment by bsongis** [comment]
"volts" are good, right? I only tested volts myself

**Comment by diablol** [comment]
on my taranis not really. for cells unit is missing. amps are volts.
