### ISSUE TITLE
no SWR on my Taranis B01

### ISSUE THREAD

**Issue by diablol** [opentx/opentx#2372]
opentx 2.1

After some openrcforums posts I start a request here.

I have a Taranis B01 and have SWR with any 2.0.x version. But NO SWR values with 2.1 that not seems normal!? 

Is it known? I found no information.

**Comment by bsongis** [comment]
You did well in opening a new issue, I can't read forums as much as I should.

**Comment by diablol** [comment]
Would be interessting someone else to confirm this. There is a minor possibility my board could be broken. I am getting a new one no later than next week.

**Comment by projectkk2glider** [comment]
Confirmed on Taranis B01 with DR8 receiver (hub protocol). I will take a look at this...

**Comment by diablol** [comment]
so, means closed it should work now? because it doesnt.

**Comment by projectkk2glider** [comment]
Yes, it should work. Did you look on telemetry setup page, the SWR will be the last item.

**Comment by tomkfly** [comment]
The early B01 Taranis Plus TXs didn't have the hardware for SWR.

**Comment by diablol** [comment]
I have no Plus and HAVE SWR with 2.0. 
checked again but nothing..:(

**Comment by projectkk2glider** [comment]
Do you have connection with the receiver?

**Comment by diablol** [comment]
Ah ok, I need connection. I see. 
But why? Should SWR not be independet from a reciever signal?

**Comment by projectkk2glider** [comment]
It is sent from XJT internal transmitter to the radio CPU along with other telemetry data. That only happens when connection with the receiver is established.

**Comment by diablol** [comment]
But that changed from opentx 2.0 where SWR worked without connection.
I am not sure if this is the best solution because you get a SWR warning first if your already connected.
If it cannot be changed with the new 2.1. concept it is still well paid.

**Comment by projectkk2glider** [comment]
The swr warning is independent of telemetry settings, it will still  sound as before in 2.0
