### ISSUE TITLE
latest Simu openTx V2.99:  Trim ON shows allways extened trim values, Extendet Trim is OFF

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2374]
latest openTx V2.99 from 19.06.  Simu
At Simu,  Show trim YES
Now allways trim works from +/- 125% possible
Extended Trim is NOT aktivated!

Aktivating, deaktivating Extended Trim, and / or Reset,  no changing 

Some days before it was ok trim from+/-25%

![auswahl_177](https://cloud.githubusercontent.com/assets/6217896/8266104/f3ba638a-171a-11e5-898f-220464516583.jpg)
![auswahl_176](https://cloud.githubusercontent.com/assets/6217896/8266105/f93b243e-171a-11e5-84ba-d8f9154790e0.jpg)

**Comment by kilrah** [comment]
Following https://github.com/opentx/opentx/commit/f4e0518cd929fc0e078f8ea53693fd86e3ae1c06 trims are simply no more displayed in % but in steps.

**Comment by bsongis** [comment]
Right, with percent, it was not possible to read the current trim value, as the precision was lost. It is steps, it could perhaps be percent with precision 1 instead.

**Comment by kilrah** [comment]
> it could perhaps be percent with precision 1 instead

I think I tried that when I previously fixed an issue with that trim display, but it would have required rework of the display routines as the TINSIZE handling of decimals took too much space.
