### ISSUE TITLE
latest simu openTx V2.99 Telemetry screen position of text after Sensor 10:  1 char wrong

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2375]
Sensor Text position after Senser 10:  1 char wrong

![auswahl_178](https://cloud.githubusercontent.com/assets/6217896/8266359/548b3cf6-172b-11e5-9f6e-251fa8e5df98.jpg)

**Comment by kilrah** [comment]
Your EEPROM is likely outdated, throw it away and reconfigure from scratch on current version.
