### ISSUE TITLE
Companion: simulator switch settings don't follow hardware settings 

### ISSUE THREAD

**Issue by ChrisMH** [opentx/opentx#2377]
I have changed SF and SH from the default settings to SF = "2 Position Toggle" and SH = "2 Positions".  These choices aren't reflected in the simulator, which shows SF as "2 Positions" and SH as "2 Position Toggle".

The hardware settings work fine in the radio, this is just in the simulator.

**Comment by kilrah** [comment]
Known limitation, it requires a deep rework of the simulator to take the new switch possibilities into account. 
It will come, but that may take a bit more time.

**Comment by mpaperno** [comment]
Fixed with #4268  and 17a03e6c1888c755642c1f97298b05f2ad84944a.
