### ISSUE TITLE
Companion import of a 216 eeprom is broken

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2378]
Invalid data + crashes

**Comment by bsongis** [comment]
Would you attach an eeprom?

**Comment by kilrah** [comment]
http://www.andrebernet.ch/divers/eeprom-good-2015-06-19-16-42-47.zip

I was looking at P-51, flight modes tab crashes

**Comment by projectkk2glider** [comment]
The switch import is still wrong, the added SF- is causing problems. It probably should be fixed in `class SwitchesConversionTable` but it is hard for me to decipher what to do there.

**Comment by fraternl** [comment]
My EEPE's can't be imported either. I'm assuming it's the same bug...
Should I post something or just wait and test after some fix is made?

**Comment by bsongis** [comment]
Yes please attach your eeprom here and tell us what goes wrong, thanks!

**Comment by projectkk2glider** [comment]
@fraternl be sure to use the latest nightly build before posting new problems.

**Comment by bsongis** [comment]
I will wait for some tests before closing this one.

**Comment by projectkk2glider** [comment]
Still some problems with switches

In Companion 2.0.17:
![switches2 0](https://cloud.githubusercontent.com/assets/5950438/8397116/a1a6b1e6-1dc0-11e5-8521-39233c8bc59b.png)

In latest `next`:
![switches2 1](https://cloud.githubusercontent.com/assets/5950438/8397117/a4aec432-1dc0-11e5-8965-b95ce0c7a7ea.png)

**Comment by bsongis** [comment]
I knew it wouldn't be so simple :)

**Comment by projectkk2glider** [comment]
It is good now!

**Comment by kilrah** [comment]
Discussed via chat, but for the record still module settings broken and input names missing.

**Comment by bsongis** [comment]
Input names are now good, is there anything else missing?

**Comment by kilrah** [comment]
Looks all good now!

**Comment by bsongis** [comment]
Cool!
