### ISSUE TITLE
When V1 is a timer the value in V2 stays decimal

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2381]
When V1 is Timer, the V2 changes in hours, minutes, seconds in Companion 2.0.x  (logical switches)
In Companion 2.0.99 it stays decimal (seconds?)

This may be intended.
I just notice it's different

I'm using nightly build 23-06-2015

**Comment by bsongis** [comment]
@projectkk2glider will you take care of this one?

**Comment by projectkk2glider** [comment]
Ok, but I leave the difficult one to you https://github.com/opentx/opentx/issues/2378#issuecomment-116208211

**Comment by bsongis** [comment]
Ok, thanks for the reminder, I am sure I missed some emails / notifications

2015-06-28 16:31 GMT+02:00 Damjan Adamic <notifications@github.com>:
