### ISSUE TITLE
taranis plus radio  

### ISSUE THREAD

**Issue by antonucci** [opentx/opentx#2384]
I'm looking for  help I having a hard time with my  radio put models on it and they to use open TX and to put models to fly .I use rc settings  and putting them on my radio but it dose not see the radio .I'm using window 8.1 anyone out there that can help me

**Comment by mpjf01** [comment]
This is not a support forum.

Maybe ask here
http://openrcforums.com/forum/viewforum.php?f=96&sid=3907b6de1c4de18444d3cdffb56ab4ed

or here

http://www.rcgroups.com/forums/showthread.php?t=1866206
