### ISSUE TITLE
Taranis only shows up on PC as Bootloader/2.0 wont recognize radio

### ISSUE THREAD

**Issue by ToddPatterson** [opentx/opentx#2394]
I have done something wrong and now the taranis only shows up as "FrSky Taranis Bootloader.
Companion will not recognize taranis
Also...companion version and firmware version are 2.0.17 but bootloader is only 2.0.15

please help

**Comment by tomkfly** [comment]
This is not the correct place to ask this question as it is only for development and bugs in the firmware.
You should ask questions about problems like yours on one of the Forums below.
http://www.rcgroups.com/forums/showthread.php?t=2178865
http://openrcforums.com
