### ISSUE TITLE
FrSky Horus X12D and OpenTX 

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#2395]
Now that the release of the FrSky Horus X12D has been delayed many months because of some hardware changes, there is a rumor that with the extra time it might have OpenTX available as an option when delivered rather than only the preparatory FrSky interface.   Even if it started out with just the basic OpenTX features that are on the Taranis Plus that would be awesome.        

So if there is a possibility that the Horus X12D can run OpenTX wouldn't it be great if the OpenTX Companion for Horus X12D let you open Taranis Plus models and drop the basic model programming into the Horus as a starting point for programming.  

I've noticed that all the switches look like they are labeled with the same name.   It would be a great feature for all of us Taranis Plus users that have spent countless hours building our models in the Taranis. 

I like all the hardware features of the FrSky Horus X12D, but if it does not run OpenTX I'm not a buyer. 

Thanks for all you folks do for us in the OpenTX community.

Mike

**Comment by bsongis** [comment]
FrSky is busy with X9E right now. No doubt we will receive the Horus prototype boards as soon as they are ready.
