### ISSUE TITLE
2015-07-01 - Companion - build option - nohaptic - setup wrong.

### ISSUE THREAD

**Issue by Mow06** [opentx/opentx#2397]
My be related to #2396 
Build option set to haptic yes, setup options OK
![haptic](https://cloud.githubusercontent.com/assets/6369173/8448603/d6b6ccd8-200c-11e5-9873-e6ed6752d9ff.jpg)
Build option haptic no, setup options wrong.
![nohaptic](https://cloud.githubusercontent.com/assets/6369173/8448619/f7dae7a0-200c-11e5-9e46-9249746e885b.jpg)

**Comment by kilrah** [comment]
Seems to be OK with the other fix.
