### ISSUE TITLE
Heli menü in Companion V2.10 and openTX is different

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2401]
At companionV2.10 Heli menü is not complete, 3 Weight missing
different to openTx V2.10

**Comment by kilrah** [comment]
???

![capture_002_02072015_193306](https://cloud.githubusercontent.com/assets/6065069/8483489/3ad0c112-20f1-11e5-9454-6c78310106b2.jpg)

**Comment by bsongis** [comment]
Perhaps he means the order of fields? Which one is the best, this is easy to fix ...

**Comment by kilrah** [comment]
We can at least change the labels so they match the radio... "elevator" and "aileron" sucks for helis :)

**Comment by bsongis** [comment]
So we keep the radio order, ok?

**Comment by hrenz** [comment]
think Radio order is ok and fine to set for Heli

**Comment by bsongis** [comment]
You may download the latest companion installer, it is fixed.

**Comment by hrenz** [comment]
Thanks a lot!
I am just making translations ready for companion and opentx and testing
