### ISSUE TITLE
Differential behaviour changes following migration to 2.1.0

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#2403]
Diff is not working the same way after migrating my F3F setup from 2.0.15 to 2.1.0.  This is both in Companion and on the actual model.

Diff on the right aileron appears to work correctly. However on the left aileron the diff is now affecting the up-going aileron instead of the down-going aileron. 

Reproducable on both the Tx and the Companion 2.1.0 (1st July build). 

Steps to reproduce:

1. Download https://drive.google.com/file/d/0B7eJi6dZb_UkaHRHQ1M0bnZGbE0/view?usp=sharing
2. Load in OTX Companion 2.1.0
3. Open model 01
4. Open sim view in editor
5. move SA to the middle (Normal mode)
6. Hold full left aileron (RH stick), vary diff with rudder trim. Note that neither aileron moves.
7. Hold full right aileron, vary diff with rudder trim. Note that BOTH ailerons move.

Loading the same model def in OpenTx Companion 2.0.15 works as expected.

**Comment by RC-SOAR** [comment]
OK here's a minimal setup, should be easier to work with

https://drive.google.com/open?id=0B7eJi6dZb_UkX0pBZ05SX2Zsek0

Aileron diff value is stored in GV1, which is bound to CH14 (rudder trim)

**Comment by kilrah** [comment]
Hmm not sure why that changed, but from what I remember it's the old way that would likely be "wrong"... I remember when we introduced GVs there that we allowed choosing -GVx as it would be required precisely in that scenario.

**Comment by bsongis** [comment]
Right I thought we didn't change anything, something must be wrong, I will find tomorrow.

**Comment by kilrah** [comment]
This?

![capture_001_02072015_232349](https://cloud.githubusercontent.com/assets/6065069/8488248/8b8f8244-2111-11e5-8f99-00cd073163ba.jpg)

**Comment by bsongis** [comment]
Here:
https://github.com/opentx/opentx/commit/f008e6ad889834b74085dbec6caec09f1ac9258a
So this was intentional, to fix this issue:
https://github.com/opentx/opentx/commit/f008e6ad889834b74085dbec6caec09f1ac9258a

**Comment by bsongis** [comment]
@JivaroFAD I need advice from more gliders experts ;)

**Comment by RC-SOAR** [comment]
Advice is simple: backwards compatibility.

**Comment by bsongis** [comment]
Perhaps I will revert as we have bigger plans on differential with @JivaroFAD

**Comment by RC-SOAR** [comment]
Just to clarify: I am not affected by #1879 as (a) I do not have mixer offsets and diff in the same mix and (b) I always split trim into a separate mix. So maybe I'm the wrong person to ask. All that concerns me is that users should not have to re-adjust their diff settings, or alter program settings for these cases.

**Comment by bsongis** [comment]
I don't agree here, it would mean that if we did something wrong in a release N, we cannot fix in a release N+1?

On the differential topic, our implementation is not the best, I really want to sort it as soon as possible. But introducing a partial change in 2.1.0 doesn't seem good, I want to have things done properly if we do them.

**Comment by kilrah** [comment]
No, what he says is we shouldn't change something if not necessary and if it might change again later, i.e. we all agree.

So yes, revert the commit, "unfix" #1879, and just make sure to take it into account when reworking differential "properly".
BUT, on that topic I believe that differential rework should target a major version, i.e. either delay 2.1 to include it or postpone it to 2.2. We can't change basic model behavior in a minor release, people wouldn't expect something as fundamental to change there.

**Comment by bsongis** [comment]
Ok. Then it will be done in 2.2.0, I mean next major release. We have changed enough things in this release, at least the mixer will stay untouched.
Give me 1/2h it will be ok.

**Comment by bsongis** [comment]
Please download again the 2.1 companion and firmware, this one is reverted:
http://downloads-21.open-tx.org/companion/

**Comment by RC-SOAR** [comment]
Have just installed the latest Companion (3rd July), have tried clicking on 'Check for Updates' but no firmware is shown. Any clues?

**Comment by bsongis** [comment]
Yes, we don't increment the number in this phase, while the release is not official just install again as if you never did it.

**Comment by RC-SOAR** [comment]
Confirmed - diff behaviour in latest build has reverted to as it was in 2.0.15. Many thanks!
