### ISSUE TITLE
OpenTx 2.1 enhancement for model-name.wav

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#2404]
I always have the model name spoken as well as displayed on the tx.  It would be very convenient if a model_name(.wav) could be included on the setup page just as the model image(.bmp) is.

Then a Global function to play model-name or just automatically played or with a paly/no-play checkbox.

**Comment by deaconFlyer** [comment]
I would love to see a file name "model-name.wav" be part of a "aircraft-name" directory in the sounds directory. I have found this to be the quickest way to maintain my setup and switch sounds. If the name was present, the firmware would speak it when selected.

You would not need a global function after that. If it is present, it is spoken,

You could have some combination of both items.

**Comment by kilrah** [comment]
> I would love to see a file name "model-name.wav" be part of a "aircraft-name" directory in the sounds directory.

Doesn't that exist already?

**Comment by projectkk2glider** [comment]
No, after looking at the sources, there is no such function implemented (yet).

**Comment by rdeanchurch** [comment]
As Global Functions appear to be processed prior to the data in Setup of a model, I prefer having a global function have a method define a .wav for a model name.  
As opposed to having the model name being buried ion any global function Play Tracks that might be present.  
 I assume a Sound/Model folder solution is also processed after global functions, but have not tested.

**Comment by kilrah** [comment]
Global functions can not have any model-specific action. The sound in the model folder is pretty much the only valid solution.
