### ISSUE TITLE
Inconsistent 'trim step' values when migrating 216 EEPROM to 217 

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#2405]
There are some inconsistencies with the default values for 'trim step' in 2.1.0, depending on how the EEPROM is migrated and whether it's an existing or new model:

* After migrating v. 216 EEPROM to 217 in situ in the transmitter: 
    * Existing models received a trim step of **Extra Fine**.
    * New models created in the Tx default to **Fine**.

* After opening the old (216) EEPROM in Companion v. 2.1, 
   * Existing models showed trim step of **Medium**
   * New model showed **Fine**

When migrating existing models, IMO the setting should match the old behaviour (medium?).

**Comment by MIKE-DAILEY** [comment]
Unless I'm missing something mine went from Fine to Exponential.
