### ISSUE TITLE
Cannot set Volts Source in Companion

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#2406]
Companion 2.0.1 (July 1), Windows 7

1. Create new model, or open an existing model (from 216 EEPROM)
2. Select Telemetry tab
3. Volts Source defaults to ---, and the drop-down list is empty.

I am able to select Volts Source = 'RxBat' without problem in the Tx. 

Protocol is FrSky XJT - D16

**Comment by kilrah** [comment]
Normal, see this post and the next few:
http://openrcforums.com/forum/viewtopic.php?f=45&t=6887&p=98803&sid=156330a522b2af7ec326a94c71583db6#p98796
