### ISSUE TITLE
Switch spec is incorrect following translation of EEPROM in transmitter

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#2407]
OpenTx 2.1.0 (2015-07-02)

Found an incorrect translation of an Edge switch when checking out my 216 format electric setup.

Steps to reproduce:
1. Do a 'Restore EEPROM' from this BIN file (216 format)
https://drive.google.com/file/d/0B7eJi6dZb_UkSEpSZ01UUU9uM00/view?usp=sharing
2. Logical switch L8 should be 'Edge V1=SH-down' but is translated as 'Edge V1=SH-Up'.

The translation is correct if the EEPROM is opened directly in Companion 2.1

**Comment by bsongis** [comment]
New compilation done, with a new installer here:
http://downloads-21.open-tx.org/companion/

**Comment by RC-SOAR** [comment]
Checked OK with latest build, thanks.
