### ISSUE TITLE
Failsafe mode incorrect, following EEPROM translation 

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#2408]
OpenTx 2.0.1 (3rd July build)

Failsafe mode is incorrect following translation from 216 to 217 format. This problem occurs only when translation is in the transmitter, it displays correctly when the EEPROM is opened directly in Companion.

Steps

1. Using bootloader, restore 216 format EEPROM from SD card. EEPROM is here:
https://drive.google.com/file/d/0B7eJi6dZb_UkaHprdkJxeGNVMFE/view?usp=sharing

2. After translation go to Model 09 'Cullast_03',  Model Setup

Expected: Failsafe mode = 'custom'
Actual: Failsafe mode = 'hold', and testing on actual model confirms 'hold' mode. Changing the mode to 'custom' reveals the previously stored values.

**Comment by kilrah** [comment]
Looks OK :+1:
