### ISSUE TITLE
Taranis 2.1.0 - model image selector possibly broken

### ISSUE THREAD

**Issue by lichtl** [opentx/opentx#2413]
I've updated for testing/review of the new telemetry to 2.1.0 on my Taranis. During model setup I've noticed that the model image selector is not generated properly (I'm uploading a video on YT right now). It looks like the right border is being created but it don't overwrite the other sections.

**Comment by lichtl** [comment]
This is the video. I've just reviewed the play-track selector. This is working as expected.

https://www.youtube.com/watch?v=HLMMLJ34cyg

**Comment by kilrah** [comment]
How many files do you have in there?

I see an issue as well but a different one...

**Comment by lichtl** [comment]
I have 523 files in the BMP folder. This is a copy. On 2.0.17 and below I never experienced any issues here.
https://drive.google.com/file/d/0B3ugUwyDKJageVdtX3NnNnIzT0E/view?usp=sharing

**Comment by bsongis** [comment]
Exactly the same on the simu and your directory
