### ISSUE TITLE
UI error in Special Functions

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#2418]
Taranis, OpenTx 2.1.0 (3 July build)

The new 'source category' dropdown in 2.1.0 is great, but it doesn't appear to work correctly when creating an 'Adjust GV' special function. 

Steps to reproduce on transmitter:

1. Go to Special Functions
2. Create a new function with action 'Adjust GV1'
3. Skip to source field, and [Enter long]  repeatedly until the source category picklist is displayed.
4. Select a group e.g. 'Sticks', and press [Enter]

At this point, the user would expect to see the field value default to the first value in the group, but it always shows 'GV1',

**Comment by kilrah** [comment]
Ah yes there is a conflict here between the ENTER LONG that is used to toggle the source type only for this particular SF, and the ENTER LONG that calls the source popup in all source fields.

Hmm, what's the best way to solve that? Can't think of anything good.

**Comment by bsongis** [comment]
Good catch. I propose to remove the source category in this choice (Adjust GV), ok?

**Comment by RC-SOAR** [comment]
So it'll work the same as before? Sounds fine.

**Comment by bsongis** [comment]
I keep it open, but delayed to 2.1.1 for the nice fix ...

**Comment by kilrah** [comment]
Oh, easy... We also have an issue open for +/-x instead of only 1... can probably see that at the same time.
