### ISSUE TITLE
English Audio Time Call Outs on Taranis

### ISSUE THREAD

**Issue by Waldo-P-Barnstormer** [opentx/opentx#2423]
Using the latest OpenTX English audio pack and the 2.1 nightly builds of July 4th and 5th looks to have fixed all telemetry unit call outs ( volt, amp, watt, etc ).
However the time call outs ( hour, hours, minute, minutes, second and seconds) needed to be shifted by 2 in the file name in order to work properly.  I only checked the English audio pack.

**Comment by bsongis** [comment]
Please download the very last firmware from Companion, it was fixed 2 hours ago!
