### ISSUE TITLE
Switch picker behaviour in Global Functions

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#2426]
OpenTx 2.1.0 (2015-07-02 build)

Just trying out the new Global Functions, and I noticed a couple of inconsistencies with the category picker in the Switch field.

* The picker works correctly only if the switch field is already blinking before you press [Enter long]. Otherwise the switch is not updated. 
* The picker contains a 'Logical switches' category which defaults the switch to 'L1', but logical switches are missing as you cycle using the +/- keys.

**Comment by kilrah** [comment]
Hmm point 2 raises an interesting question... Should LSs be available for selection in GFs? 
It could be useful to have them supposing you remember to configure the same LS in every model... but if you didn't it could be a mess, same when changing model.

I'd be for excluding them, and if Global LS are introduced as per #2409 then those would be available there.
