### ISSUE TITLE
Opentx 2.1 splash screens

### ISSUE THREAD

**Issue by mhotar** [opentx/opentx#2427]
This is not an issue at all. I made some splash screens for 2.1 I would like to offer.
If they are not acceptable, feel free to close this isuue :)

![splash](https://cloud.githubusercontent.com/assets/6114100/8535857/2ebcca72-244a-11e5-80c5-fddb0a09d6b3.png)
![splasht](https://cloud.githubusercontent.com/assets/6114100/8535864/39998836-244a-11e5-94b3-9d6261b948c9.png)

**Comment by projectkk2glider** [comment]
Nice.

**Comment by bsongis** [comment]
Nice!

**Comment by mhotar** [comment]
I finally removed radio frames from splash screens.

![splasht](https://cloud.githubusercontent.com/assets/6114100/8543418/ec845faa-249c-11e5-88c1-4452d35b75d5.png)

**Comment by fraternl** [comment]
I agree they look nice.
I'm sure we will have these in our next Companion...  ;-)

I'm not a dev. though

**Comment by tomkfly** [comment]
But we don't have couloured screens.

**Comment by fraternl** [comment]
Do you still have a monochrome monitor attached to your PC?

**Comment by tomkfly** [comment]
Of course not, but I don't see an point with a nice screen on the sim when it's not available on the TX.

**Comment by kilrah** [comment]
It's got nothing to do with the sim, it's the splash screen when you launch companion.

**Comment by bsongis** [comment]
Thanks, really nice work!

**Comment by bsongis** [comment]
May I ask to work with @romoloman for the X9E simu graphics, I would like it is consistent with your new splashes!

**Comment by mhotar** [comment]
I am happy to help. @romoloman do not hesitate to send more details and instructions what you would like me to do.
