### ISSUE TITLE
Taranis Plus - Play Delay (sw.mid pos)

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#2434]
2.1.0 - Play Delay (sw.mid pos) does not seem to work anymore. I believe it was set at 150ms in 2.0.17 and I ran it all the way to 1000ms and it still plays the mid switch wav sound. 
Mike

**Comment by bsongis** [comment]
At least not reproducible on simu

**Comment by bsongis** [comment]
Which is your custom function line?

**Comment by MIKE-DAILEY** [comment]
The switch is used for triple rates and was working fine on 2.0.17 unless I messed something up on the upgrade to 2.1.0. 
![rates 1](https://cloud.githubusercontent.com/assets/11791852/8556559/d0004262-24c5-11e5-97b0-626a154b8c0d.JPG)
![rates 2](https://cloud.githubusercontent.com/assets/11791852/8556560/d001b1ba-24c5-11e5-83c7-be90835d5baf.JPG)
![rates 3](https://cloud.githubusercontent.com/assets/11791852/8556561/d00599b0-24c5-11e5-92e5-d60aea4e73bd.JPG)

**Comment by bsongis** [comment]
Do we agree it is SF5 and SF7 which should have the delay?

**Comment by bsongis** [comment]
Oh yes you are right, the delay works with SA- but doesn't with SC-

**Comment by MIKE-DAILEY** [comment]
SF5 is the mid position and should be impacted by the "Play Delay" SF7 is another switch used for playing the RSSI value when I want to during flight.

**Comment by MIKE-DAILEY** [comment]
Correct, delay only on SA-.  Could this be related to my conversion problem?

**Comment by bsongis** [comment]
No I have the same problem here with a blank model, and on the simulator

**Comment by MIKE-DAILEY** [comment]
Great Bertrand, my testing effort helped!

**Comment by bsongis** [comment]
Indeed, we need you in the beta user list
