### ISSUE TITLE
A way to select 2 soundpacks within 1 language (male/female?)

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2440]
I am considering to make a soundpack with a (real) female voice in my own language. I just now became aware that someone already made a soundpack in my language.

This soundpack is however with a male voice.

It would be nice if an alternate voice-pack could be used within the language...

**Comment by kilrah** [comment]
Just rename the folders?

**Comment by fraternl** [comment]
I have my radio not here...
The language is not hardlinked to the 2 character language code?

Then it's not necessary...

**Comment by kilrah** [comment]
It is hard-coded, yes.

**Comment by fraternl** [comment]
But when I select "Nederlands". it will play the sounds of the /SOUNDS/nl/ folder.
Maybe only a checkbox for "alternate sounds" and then it will play the sounds out of the /SOUNDS/nla/ folder???
The same for the other languages
This way it would also be able to switch between Amber and Standard.

What I'm proposing has a very minor impact on the code.

(I know there's no "Nederlands"... I'm working on it)

**Comment by kilrah** [comment]
If I want to change sounds I just have an "en" folder and say an "en_male" one... If I want to switch I'll rename "en" to "en_female" and "en_male" to "en". 

But then again I don't see why I'd change packs all the time, I try a few, choose one I like and once I'm done testing it stays there.

**Comment by fraternl** [comment]
true true true....
But like I said.... It could be made with a minimal impact on the code...

Maybe a late milestone or close it....??
I still need to make that good female voicepack.....

**Comment by kilrah** [comment]
> It could be made with a minimal impact on the code...

Go ahead then ;)
But then why only 2, because some people will want to swap between 3 or 4... ;)

**Comment by fraternl** [comment]
That could be easily accomplished by selecting a suffix..
a to a
Default, there's no suffix.

**Comment by bsongis** [comment]
Why do you close this one, I do like the idea, just needs some time to come
with a nice solution...
