### ISSUE TITLE
Telemetry - setting units degree F removes prec field in companion & simulator

### ISSUE THREAD

**Issue by Mow06** [opentx/opentx#2441]
![degreef](https://cloud.githubusercontent.com/assets/6369173/8569701/97b1aba0-25bd-11e5-84ef-03227ed5d5a4.jpg)
![degreefsim](https://cloud.githubusercontent.com/assets/6369173/8569710/a365c47c-25bd-11e5-8d3d-41f4fc0f0f6f.jpg)

Haven't got access to radio to test that.

**Comment by kilrah** [comment]
normal, both are incompatible.

**Comment by Mow06** [comment]
Don't understand. Why is degree F the only one without a prec field?

**Comment by Mow06** [comment]
Don't understand.

What "both" are incompatable.

You create only one sensor with degreeF, prec field disappears. What is that not compatable with

  ----- Original Message -----

**Comment by kilrah** [comment]
With the the way precision is calculated changing it would break the °C to °F conversion.  That's why it's hidden in this case.

**Comment by Mow06** [comment]
OK. Thanks for the explanation.
