### ISSUE TITLE
Adding Nederlands (Dutch) as a selectable language

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2443]
Adding Nederlands (Dutch) as a selectable language

I've been discussing this with Bernard in a closed ticket.
It's more appropriate to have its own ticket

Dutch soundpack
    http://hmvc.eu/SOUNDS_nl.zip

A patched tts.en.cpp to be used for the nl-language
   http://hmvc.eu/tts.nl.cpp

I'm still working on the nl.h.txt file  (it's time consuming)

**Comment by bsongis** [comment]
https://github.com/opentx/opentx/commit/d0bee7d66679b28f4e86ff623b64b751abb75fea

**Comment by fraternl** [comment]
Could you add this for the Dutch translation?
This is probably not the final one.
Is this a problem???

![en h txt](https://cloud.githubusercontent.com/assets/8692856/8647872/25eec758-295c-11e5-9131-52b41aa3493b.jpg)
