### ISSUE TITLE
Wrong scroll direction in simulators for X9E

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2444]
Affected programs: Companion, Standalone simulator, simu.

Steps to reproduce:
* open X9E radio simulation
* scroll trough menus with + an - keys

Bug: the scroll direction is wrong, but not in all cases, for example in name editor the direction is good. The problem is caused by the fact that rotary encoder on X9E works in other direction.

**Comment by bsongis** [comment]
Not exactly. It's because on a standard real Taranis, the - key moves down, while it moves left on the X9E

**Comment by projectkk2glider** [comment]
Exactly. I think it is annoying and feels wrong in Simulator. But on the actual radio it is fine.
