### ISSUE TITLE
Companion 2.1 does not recognize reset altitude nor is it able to set it

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2451]
I just went back to 2.0.17 and did an upgrade with today's (Saturday) nightly.
Of course telemetry values were lost, but I tried to fill these up using Companion.

When I got to "Reset Altitude", I was unable to pick it.
In the already setup I flew with yesterday it is there, but can't be shown

**Comment by kilrah** [comment]
You can of course only pick it after an altitude sensor has been either detected or configured. 

http://openrcforums.com/forum/viewtopic.php?f=45&t=6887&p=98803#p98796

**Comment by kilrah** [comment]
Ah, even then it seems the list indeed lacks the telemetry items, you're right.
