### ISSUE TITLE
   Trims not correct,  showing +/-125%  instead +/-25% at one screen

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2454]
openTX V2.10 latest next
Trim value at channel monitor is ok +/-25%
but  at show trim aktiv, no extendet trimm aktiv, shows +125% / -125%

![snapshot_05](https://cloud.githubusercontent.com/assets/6217896/8634223/fb349892-27f0-11e5-974f-f486dfe04527.png)
![snapshot_06](https://cloud.githubusercontent.com/assets/6217896/8634215/74087672-27f0-11e5-9acb-ee54d3b3c4af.png)
![snapshot_08](https://cloud.githubusercontent.com/assets/6217896/8634218/a09d0b76-27f0-11e5-907e-0e4332b99ebc.png)

**Comment by hrenz** [comment]
sorry thing has cleared, this mean:
At channel monitor is at % or at PPMus
At the other screen is +/-500 steps   with extrafine=1 fine=2  mid=4 steps  and so on.

But:
If a trim is  at 125  (= 25%) and I push the same trim button again
it runs over 125 to max 500
(no extendet trim is aktiv!) can that be ok?

**Comment by kilrah** [comment]
Again please explain PRECISELY what you're doing. I just tested trims and they only go to 500 if extended trims are on.

**Comment by hrenz** [comment]
Hy kilrah,
no extendet trim aktiv!
push a trim button, hold it, runs to 125,  ok its 25%
then push same trim button again, hold it, and its runs from 125 to 500  (=100%)

**Comment by kilrah** [comment]
And I can't reproduce that either on the radio or on the simu. 
So please say exactly what version you're using, whether it's the radio or the simu, and what you're doing coming from a new model to reproduce the problem.

**Comment by hrenz** [comment]
test with openTx V2.10 latest from today 
at Simu with Modell1 at start up
-----------------------------------------------
now I have generated a new Modell3
there I can't reproduce the "bug"
there it works well as it should 
----------------------------------------------
