### ISSUE TITLE
Companion 2.1 Telemetry sensor range incorrect

### ISSUE THREAD

**Issue by pinkywafer** [opentx/opentx#2460]
Running 2.1 on Taranis (not plus).
I set up a quad using NAZE32 and D4r-II. Telemetry sensors were detected on the tx, and all seems fine. I have adjusted a couple of the "range" settings for the sensors (on the TX) : VFAS range 25.5.  RPM range 1279.0.  These give the correct expected readings on the TX.  When imported into companion, while VFAS range shows 25.5, RPM range shows 24.6

**Comment by bsongis** [comment]
Which range do you mean?

**Comment by pinkywafer** [comment]
on the sensors page. Its labelled range in companion, and ratio on the tx. 
![companion sensor](https://cloud.githubusercontent.com/assets/8636233/8640508/20b9a6cc-28f3-11e5-808d-2abb7f579646.jpg)

![tx sensor](https://cloud.githubusercontent.com/assets/8636233/8640520/7d20dbd8-28f3-11e5-8230-84fe702f2731.jpg)
