### ISSUE TITLE
Firmware Simulator 2.1 Pots

### ISSUE THREAD

**Issue by pinkywafer** [opentx/opentx#2461]
If I load firmware simulator 2.1, there are no controls for pots
If I hit simulate from within companion, the controls for pots appear as normal at the top by the switches.

**Comment by projectkk2glider** [comment]
I am not entirely sure I understand you. Do you mean that pots are missing from Standalone Simulator?

**Comment by pinkywafer** [comment]
yes.  See attached
![nopots](https://cloud.githubusercontent.com/assets/8636233/8639286/08c5dc5a-28cd-11e5-9798-054b57ee0771.jpg)

**Comment by MIKE-DAILEY** [comment]
Looks like this for me on build #33.
![pots](https://cloud.githubusercontent.com/assets/11791852/8639505/091d5ba6-28aa-11e5-82eb-cadc9ab8fa53.JPG)

**Comment by bsongis** [comment]
Did you configure your pots in General Settings? If you set type None for all of them you will get no pot in the simulator.

**Comment by pinkywafer** [comment]
Yes, pots are configured as pot with detent. They are there in the simulator within companion, but not on the standalone simulator

**Comment by bsongis** [comment]
Ok understood.
