### ISSUE TITLE
New translation "Nederlands"

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2464]
I created http://hmvc.eu/nl.h.txt from en.h.txt to be used for the translation to Dutch

**Comment by bsongis** [comment]
Please check string lengths, you cannot write this for example:
#define LEN_VBEEPMODE          "\005"
#define TR_VBEEPMODE           "Stil""Alarm""NoKey""Alles\0"

**Comment by fraternl** [comment]
OK, I will

But how should I see this in the original en.h.txt????

#define LEN_VRENAVIG           "\003"
#define TR_VRENAVIG            "No REaREb"

**Comment by mhotar** [comment]
"No REaREb" is the same like "No ""REa""REb", this is something that needs to be changed for better readability.

**Comment by fraternl** [comment]
I have updated the file now.....
http://hmvc.eu/nl.h.txt

**Comment by kilrah** [comment]
Some lengths are still off... the LEN is in octal (base 8), not decimal. So for example TR_VPERSISTENT either has 2 chars too many on each item, or its LEN should be 2 more.

**Comment by kilrah** [comment]
Also you should ideally have a build environment set up so you can build the simulator. With the thing above fixed as well as 3 missing " some strings seem to be too long, some only on small screen platforms and some also on Taranis. You can use the TR() macro to define separate strings for both, but it's hard to do without being able to test in "real life".

![screenshot-1](https://cloud.githubusercontent.com/assets/6065069/8658087/ffcfa10a-29a1-11e5-9673-511d91ef7c2b.png)
 
![screenshot-2](https://cloud.githubusercontent.com/assets/6065069/8658092/0315dd66-29a2-11e5-980e-fbbb7fe9d94c.png)

![screenshot-1](https://cloud.githubusercontent.com/assets/6065069/8658110/1b0de710-29a2-11e5-94fe-f6d515ccf067.png)

![screenshot-2](https://cloud.githubusercontent.com/assets/6065069/8658113/1cf744b8-29a2-11e5-825b-20c6437ac17d.png)

I've committed the last file and the couple of fixes that result in the screenshots above.

**Comment by fraternl** [comment]
I didn't know it was octal (I should have). Did know that \0 is 1 char.
I have a corrected file for download, but I think it's almost impossible to get it right...
English words are generally much shorter than Dutch words

**Comment by kilrah** [comment]
Time to get creative with abbreviations :)

**Comment by fraternl** [comment]
I downloaded the new firmware to my radio and realized I didn't understand how it's implemented now.
It's not in the radio firmware, but only in the simulator....

Could you give me some global directions for making a development environment?
Is it in Windows or Linux?
I assume in Windows as the target is in Windows.
In Linux I don't use the desktop versions
Never developed in Windows. Currently only in Linux and a long time ago for MS-DOS.

If mismatches in the "Dutch part" have no influence on the behaviour of the rest of the system you could just "make it live" for the radio itself. I have the radio now with me and can check everything the next morning.
I am aware that OpenTX is not "Taranis only"
I will also examine and compare the German file.
German has the same "problem" as Dutch using much longer words for the same thing.

Is that OK by you?

**Comment by kilrah** [comment]
The radio firmware will have it too, but something was missing that I fixed in my last commit so for now it wasn't "enabled" neither in the simulator nor on the radio. 
Next 2.1 beta release will have NL present both in the radio and simu, but as these are only made once every few days feedback is kind of slow.

Build instructions are in the project's github wiki.

**Comment by fraternl** [comment]
If it is build could you fetch a fresh one from  http://hmvc.eu/nl.h.txt
I think it should be usable now

**Comment by kilrah** [comment]
It also reverts at least 2 of the fixes we did... Would really be good if you could use the git tools ;)

**Comment by fraternl** [comment]
OpenTX 2.1.0 has come out now and none of the translations are implemented. Is that correct?

**Comment by kilrah** [comment]
I just downloaded an NL firmware from companion and flashed it, and it is in NL.
