### ISSUE TITLE
Feature request: Companion 2.1 Telemetry Script

### ISSUE THREAD

**Issue by pinkywafer** [opentx/opentx#2465]
On the companion, Telemetry tab, for each screen, if Script is selected, is it possible to have a dropdown to select the script to use (assuming SD card is synced)?

**Comment by AndreasAusD** [comment]
on the simulator it is already working right, only in companion there is no way of selecting a script.
also this information is lost whe there is a script assigned on the radio and the models are downloaded from the radio to companion and uploaded back to the radio again

**Comment by bsongis** [comment]
Would someone test this one before the release, I did a small refactoring, I would like to be sure I didn't break anything ...

**Comment by projectkk2glider** [comment]
One bug found, maybe not even related. When I defined bars in Companion like this, I get empty bars screen in simulator (both ranges are 0-0). 
![screenshot](https://cloud.githubusercontent.com/assets/5950438/8762342/ebca10cc-2d76-11e5-93ce-bd5512bc4309.png)

**Comment by bsongis** [comment]
You should use another issue, it's not at all related!

**Comment by projectkk2glider** [comment]
Done, issue #2491

**Comment by AndreasAusD** [comment]
will this go to the nightly builds for testing ? and when ?

**Comment by bsongis** [comment]
Yes, nightly. I will wait befinning of next week for 2.1.1

**Comment by projectkk2glider** [comment]
The new nightly will be build in about 10 hours from now.
