### ISSUE TITLE
In Companion the "Download voice" is fixed for "en"

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2467]
In Companion the "Download voice" is fixed for "en"
Other languages can't be chosen

**Comment by kilrah** [comment]
Uhh... no?

![capture_001_15072015_122322](https://cloud.githubusercontent.com/assets/6065069/8696412/5dfc1542-2aec-11e5-992a-8f624e1fd0cf.jpg)

Again no version info...

**Comment by fraternl** [comment]
Ow...
That's not how it looked on my computer.

I didn't attach a screenshot because I thought it would have been obvious.
It now turns out it's only at my PC at home. The one with the UHD television attached.

Sorry, for this
It's working on other PC's
