### ISSUE TITLE
Global Function Play Track & BGMusic can't select a track on the radio

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2472]
The Global Function BGMusic can't select a track

**Comment by kilrah** [comment]
In companion? On the radio?

Please work a bit on making usable issue reports.

**Comment by fraternl** [comment]
Sorry....
On the radio.

**Comment by bsongis** [comment]
No problem for me, someone else?

**Comment by fraternl** [comment]
Bernard,
Can you select a track?

http://hmvc.eu/2015-07-16 19.58.26.mp4

**Comment by bsongis** [comment]
Bertrand :)

**Comment by fraternl** [comment]
Sorry...   My French butcher is called Bernard  ;-)

**Comment by bsongis** [comment]
Yes I can select a track without problem!

**Comment by fraternl** [comment]
Just did a factory reset and it's still the same.
Can you see me do something wrong in the video?

**Comment by bsongis** [comment]
Which is your language selected?
Or perhaps because your filename begins with a '3'?

**Comment by bsongis** [comment]
Would you put somewhere your eeprom + a zip with your SD contents?

**Comment by fraternl** [comment]
I have yet another problem...
My SF3 changes from time to time to the first track (3dhobbyshop).
I had this before, but thought it was some user error.
Now it changed again.

**Comment by fraternl** [comment]
The firmware and eeprom
http://hmvc.eu/EEPROMS.zip

**Comment by fraternl** [comment]
I thought it might have been the large music files I have in /SOUNDS/en/, but I just formatted the SD-Card in my PC and copied a backup without those music files to it.
I checked Global Functions again and it did the same.

I haven't tested enough to see if SF3 has changed again.

http://hmvc.eu/Taranis_SD.zip

**Comment by fraternl** [comment]
I now tested it and when I select a track in GF3 it will be written to SF3

**Comment by bsongis** [comment]
Sorry I didn't see you were talking about Global functions. Now I reproduced the problem with your firmware.

**Comment by fraternl** [comment]
;-)
I'm so glad these 2 are related.
I was afraid of some memory overwrite like with the LS1

**Comment by bsongis** [comment]
It was just a stupid bug, something that obviously nobody tested. I knew OpenTX 2.1.1 would be quickly needed ...

**Comment by fraternl** [comment]
I started using Global Functions 2 days ago. 
BTW...   None of the translations are implemented. That's intended or not?
