### ISSUE TITLE
Shouldn't people be made aware they lost their A1 monitoring?

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2473]
I realized only today that the battery settings inside the model are gone.
Especially glider pilots could be in for a nasty surprise

You need to make it yourself now.
No access from the SF to the SYSTEM sound files

"A1 low" and "A1 critical" need to move to /SOUNDS/en
I didn't do that in my pack.
I don't know if you did.

**Comment by kilrah** [comment]
A1 and A2 alarms don't exist anymore... pretty obvious. Those files are now obsolete for the same reason.

**Comment by fraternl** [comment]
I have created a new nl.zip to be placed in http://voices-21.open-tx.org/opentx-taranisplus/nl/

http://hmvc.eu/nl.zip
