### ISSUE TITLE
DSM receiver number for external module not converted from 216

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2474]
Found on a forum:
>Just installed 2.1 and all of my external module DSMX receivers have been set to 00 losing the binding on all of 13 models

Don't have more details whether the conversion was done on  radio or in companion.

**Comment by Alexander-C** [comment]
The firmware update was done from within companion. I was able to recover the situation by manually changing the receiver numbers on the radio to match those on my 2.0.15 backup.

**Comment by bsongis** [comment]
In OpenTX 2.1.0 we have now 2 model receiver indexes (one different per module), while in OpenTX 2.0.x the same model index was shared amongst all modules.
