### ISSUE TITLE
Companion 2.1 not saving vario source and centre silent options

### ISSUE THREAD

**Issue by helicop** [opentx/opentx#2476]
Opentx-taranis-plus-2.1.0, 17/07/2015 EEPR:217

Reading taranis memory to companion, then writing back, variometer source is blank (-----) and the centre silent option has changed to "Tone". Very minor problem, just have to remember to change things at next use.

**Comment by bsongis** [comment]
Would you check for me something? I think there is also a problem with volts and current sources

**Comment by helicop** [comment]
The only sensor I have with voltage and current is a Unisens-E. I have tested it, and the voltage and current are working fine

**Comment by kilrah** [comment]
What he means is the selection for "voltage source" and "current source" on the telemetry page. Regardless of the sensors you have.

**Comment by bsongis** [comment]
*posts removed, I read the code too quickly
