### ISSUE TITLE
Can't register individual cells correct in Companion 2.1

### ISSUE THREAD

**Issue by ReneTr** [opentx/opentx#2485]
I have a Taranis X9D plus, an X6R with a FLVSS.

The FLVSS voltage sensor registers fine and cels shows correct values.

When in Companion 2.1 I add a new sensor: lowc Calculated Cell Cells Lowest
I want to use that sensor in a Logical Switch for a lowest cell warning: Like a<x lowc 3.50v
But I can only select integers in the V2 column, it doesn't know it's volts. In the telemetry screen it also shows an integer. Example: 4 instead of 4.12

If I create the lowc sensor on the Taranis it works fine. Also if I then read the settings from the Taranis into Companion, Companion works fine as well. It now knows it's Volts and I can create the Logical switches I want.

**Comment by ReneTr** [comment]
![comp2](https://cloud.githubusercontent.com/assets/13387411/8758696/5462e0a4-2ce7-11e5-9796-2b45c9112882.png)

**Comment by kilrah** [comment]
Was related to #2479
