### ISSUE TITLE
OpenTX 2.1 Telemetry: Date not logged correctly

### ISSUE THREAD

**Issue by Bamfax** [opentx/opentx#2487]
Hi,

the date field has the same issue as the GPS field when being logged (as in issue #2456 ). Its fieldname is logged as "Date(d<)" and the value stays at 0, even though GPS time is received via telemetry and displayed correctly.

Thanks again for fixing,
Olli

**Comment by Bamfax** [comment]
Cels and calculated CelL do not exhibit this behavior, they work fine.

**Comment by Bamfax** [comment]
The closed #2456 caused a little sideeffect, maybe you can revisit that. See comment in #2456. Let me know if you want a separate issue for that.

**Comment by nscch** [comment]
Hello
The voicegenerator didnt response the right units the telemetry data. E.g. the alt (meter) response in "miliampere per hour"

**Comment by kilrah** [comment]
Unrelated, make sure you've updated your voice files.

**Comment by nscch** [comment]
How can I get the weakest cell voltages from FLVSS in the data. I get only the main voltage from the Lipo.

Thank you very much for your answer.
