### ISSUE TITLE
LUA Scripts doesn't work 

### ISSUE THREAD

**Issue by Jamuukah** [opentx/opentx#2489]
Whether I put the telem2.lua as an example to the correct Folder on SD Card  I couldn't use it.  Even if I try to load a script in Taranis itself , I get the error meassage; no scripts on sdcard.  If I try to execute this script directly on Taranis. I get the error message: Script syntax error.
Is it possible that "old" scripts doesn't work on the new 2.1 Version?

**Comment by kilrah** [comment]
Correct, old scripts need to be updated and the whole modelname\telemx.lua is obsolete too. You now select them in the telemetry screens settings.
Please use the forums for usage questions.
