### ISSUE TITLE
GPS Lat/Lon logging with new 2.1 telemetry,logging file first line headers incomplete

### ISSUE THREAD

**Issue by Bamfax** [opentx/opentx#2490]
With fixing #2456, the now new Latitude field in the log file does not have a header field in the first line of the csv file. Which causes all following field names to get left shifted by one and the last field does not have any name.

![gps latitiude logheader](https://cloud.githubusercontent.com/assets/12980986/8762064/167708b0-2d6e-11e5-85c3-4fd73b6959cf.jpg)

**Comment by bsongis** [comment]
Yes in fact I already fixed it earlier today.
