### ISSUE TITLE
Bars ranges not transfered to radio

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2491]
When I defined bars in Companion like this, I get empty bars screen in simulator (both ranges are 0-0). 
![screenshot](https://cloud.githubusercontent.com/assets/5950438/8762342/ebca10cc-2d76-11e5-93ce-bd5512bc4309.png)

**Comment by kilrah** [comment]
Just read about someone wishing that we allow for having start > end and have the bar work the opposite way e.g. to use mAh count to show "remaining" instead of "elapsed", maybe we can take care of that at the same time.

**Comment by bsongis** [comment]
Good idea, but he can open another issue, I prefer doing only fixes right now to have a good start for 2.1 ...

**Comment by projectkk2glider** [comment]
>Good idea, but he can open another issue, I prefer doing only fixes right now to have a good start for 2.1 

Done in #2495
