### ISSUE TITLE
Enable bars to work the opposite way

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2495]
Taken from https://github.com/opentx/opentx/issues/2491#issuecomment-122563162

> Just read about someone wishing that we allow for having start > end to have the bar work the opposite way e.g. to use mAh count to show "remaining" instead of "elapsed", maybe we can take care of that at the same time.

**Comment by kilrah** [comment]
:+1:

**Comment by Eldenroot** [comment]
+1
