### ISSUE TITLE
Global Functions in Companion

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2499]
I might probably be missing it, but is there any way to set the Global Functions in Companion?

**Comment by bsongis** [comment]
In General Settings, or did I forget them?

**Comment by projectkk2glider** [comment]
No you did not miss them, they are there
![screenshot](https://cloud.githubusercontent.com/assets/5950438/8765148/b9fdda80-2e00-11e5-936e-27cf9739c72e.png)

**Comment by fraternl** [comment]
It turns out I've always missed that page (General settings)
