### ISSUE TITLE
Simulators missing from Companion installer on Linux platforms

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2500]
Two problems:
 * The simulator dynamic libraries libpentx-*-simulator.so are missing from RPM and DEB packages. 
 * The Companion looks in current working directory for those files, which is not the standard way on Linux, the libs should be in /usr/local/lib/companion.

Perhaps similar problem is also present on MAC.

This issue is solved in pull #2482, which also includes a change that enables Companion 2.0 and 2.1 install at the same time (both packages can't have the same files).

@bsongis and @kilrah I urge you to consider that pull request before the 2.1.1 is released!

**Comment by bsongis** [comment]
I think this one can be closed, right?

**Comment by bsongis** [comment]
@projectkk2glider wouldn't it be better to use companion21 name instead of companion2.1 ? A little bit like python ...

**Comment by projectkk2glider** [comment]
Sure, the dot was bothering me also. I will change it...

**Comment by bsongis** [comment]
Gah, I will continue working on Linux then :)

**Comment by projectkk2glider** [comment]
@bsongis Please test my work and close the issue.

**Comment by bsongis** [comment]
Yes, it's perfect now, thanks!
