### ISSUE TITLE
Companion 2.1 doesn't show calibration settings for pot 4

### ISSUE THREAD

**Issue by franck76** [opentx/opentx#2502]
my radio : Taranis with Opentx 2.1 official release

Start Companion from nightly-21  18-jul-2015
Read models ans settings from my radio

Calibration settings for pot4 are missing, they are set to 0 for other sticks and pots :
![img01](https://cloud.githubusercontent.com/assets/6233237/8765406/c6633004-2e0a-11e5-8ff4-ba2f43b18b1c.png)

do the same with companion 2.0, yo get this : 
![img2](https://cloud.githubusercontent.com/assets/6233237/8765445/5dc8d0ce-2e0c-11e5-85a8-f879ee2583f4.png)

this may be a bug ?

**Comment by bsongis** [comment]
Someone confirms?

**Comment by kilrah** [comment]
What radio type?

**Comment by franck76** [comment]
Type ?
Taranis 1st version (june 2013)

**Comment by franck76** [comment]
I see, in both companions radio type is Frsky Taranis
My EEPROM was converted from the radio when installing companion 2.1 
I noticed that some models (not all of them) were not properly converted
I shall install a new eeprom and carry out calibration if nobody can reproduce

**Comment by projectkk2glider** [comment]
Maybe @franck76 converted EEPROM in Companion. Because if I convert my 216 eeprom in Companion I also loose calibration settings (all become zero). Should I create a new ticket for this?

 The pot4 is disabled for Taranis and Taranis+, it is only enabled for X9E, which I think is ok.

**Comment by franck76** [comment]
In the first place I am pretty shure I converted my EEPROM from the radio 
Then I also thried and converted the same EEPROM from companion
Anyway, I can do some further tests tonight

By the way I thought that Pot1-4 were S1, S2, LS and RS ?

**Comment by kilrah** [comment]
I can confirm that calibration settings aren't displayed in either case coming from a 216 or 217 eeprom.

![capture_001_19072015_133453](https://cloud.githubusercontent.com/assets/6065069/8765719/4b40ff44-2e1b-11e5-8ede-10364bfe0c30.png)

**Comment by bsongis** [comment]
Someone would check, just one line forgotten?

**Comment by franck76** [comment]
Seems OK with nightly from today :
![cap](https://cloud.githubusercontent.com/assets/6233237/8770333/ca4fc43e-2eaf-11e5-8cde-a8ecf5f7cab8.png)
