### ISSUE TITLE
Standalone simulator radio selection display problem

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2503]
Two problems:
* window width on narrow displays 
* buttons to small to display all text

![screenshot](https://cloud.githubusercontent.com/assets/5950438/8765558/b300dd5c-2e11-11e5-8ab0-29aeffad221f.png)

**Comment by bsongis** [comment]
Yes a combo box would be really better, would you take care of it?

**Comment by projectkk2glider** [comment]
Ok

**Comment by kilrah** [comment]
Argh, 2 more clicks and some scrolling at each opening... some people are already complaining that they have to choose the radio type each time :)

**Comment by projectkk2glider** [comment]
Maybe we should remember the last selection and select it at the next start. Do settings work in standalone Simulator?

**Comment by kilrah** [comment]
That would be good. Settings should work as things like SD card folder work.

**Comment by projectkk2glider** [comment]
@kilrah how about now? Pretty sleek i think :wink:

**Comment by kilrah** [comment]
Perfect! No more problems even with multiple languages and the ton of related simulators :)

![capture_001_19072015_150916](https://cloud.githubusercontent.com/assets/6065069/8766017/ed2ab202-2e28-11e5-8af6-a4a777e895ea.png)

EDIT: seems it works on Windows, but on linux the simu still doesn't remember the last used item ;)

**Comment by projectkk2glider** [comment]
simu is not in the same league. Use `simulator` executable from companion dir.

**Comment by kilrah** [comment]
Yes that's what I meant.

**Comment by kilrah** [comment]
oh no I know, I jsut repeated last command and it launched simulator2.1 that doesn't include that change. My bad.
