### ISSUE TITLE
Clarification for EU Build Option

### ISSUE THREAD

**Issue by twokaff** [opentx/opentx#2504]
May I suggest to change the wording for the eu-checkbox tooltip to say "...on radios sold in the EU after...".

It currently reads as if the D8 and LR12 protocols are illegal to use everywhere.

**Comment by kilrah** [comment]
The "eu" name for the option should be quite self-explanatory, but...

**Comment by twokaff** [comment]
It is to you and me :)

Thanks for entertaining it.

**Comment by fraternl** [comment]
To nit-pick:   It's Jan 15th 2015, not Jan 1st

I still think that statement claims more than is true, but this is not the place...

**Comment by tomkfly** [comment]
The new EU regs came into force on The 1st of Jan 2015, not the 15th.
