### ISSUE TITLE
[Suggestion] Change Telemetry Sensor ID Input Method

### ISSUE THREAD

**Issue by twokaff** [opentx/opentx#2506]
Currently, when adding a sensor manually on the radio, we have to scroll through the ID values until we have the correct one.  That can take a *very* long time depending on the ID value.

Consider changing the input method for the sensor IDs to be the same as used when entering names, i.e. enter each part of the ID by selecting from hex values 0-F.  Perhaps, when no value is entered it defaults to 0.

**Comment by kilrah** [comment]
The system wasn't really meant to be used that way, is there really a need to enter these manually?

**Comment by twokaff** [comment]
There is the option to manually add sensors.  What if the sensor has the ID F3AB?  I'll be sitting there ages waiting for the ID list to scroll to that position.  If, on the other hand, I'm not supposed to add sensors manually, then why is the option there in the first place?

It just struck me as cumbersome to having to scroll through the IDs in increments of 1, when I could just add each digit individually and be done with it in a few seconds.  That was my reasoning behind the suggestion.

I don't fully understand the new telemetry system yet, perhaps my suggestion is moot.  If that's the case feel free to close it.

**Comment by bsongis** [comment]
Fair enough. I don't see why this field is modifiable.

**Comment by kilrah** [comment]
Because it doesn't hurt and even if not convenient it lets you change it should you need it. I've edited the ID and instance a few times during testing.

**Comment by kilrah** [comment]
Because it doesn't hurt and even if not convenient it lets you change it should you need it. I've edited the ID and instance a few times during testing. I don't see a reason to spend time making it easier, but I'm definitely not for removing the possibility either.
