### ISSUE TITLE
Mega 2560 Can't connect to radio after firmware flash

### ISSUE THREAD

**Issue by WillD7545** [opentx/opentx#2511]
After flashing firmware to 2560 SainSmart clone, companion cannot communicate with radio. Receive timeout errors.

**Comment by JivaroFAD** [comment]
You must press the reset button of board just before flash.

Please read : http://jenkins.open-tx.org/MEGA2560/2_Configuration-Flash/MEGA2560_FlashProcedure.pdf

**Comment by WillD7545** [comment]
It writes, but when the radio boots, eeprom data is bad and it reformats.

**Comment by kilrah** [comment]
Could be the usbasp is loaded with the firmware that fails to flash the m2560 eeprom correctly, common problem... Would be stupid on a board that precisely uses an m2560, but then with clones anything is possible.

**Comment by JivaroFAD** [comment]
I assume you talk about usb operation, not usbasp. With usb driver based on A16U2 or A8U, you can not flash firmware and restore eeprom in the same operation.
You need to decompose each operation, with a hard reset at each time.

**Comment by WillD7545** [comment]
Yes, the reset button is pressed before each operation.
