### ISSUE TITLE
"Copy sensor" function on telemetry item popup

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2513]
The system is made so that you can have multiple copies of a sensor with different attributes, but at this point you can only get to it if you enter everything manually. That's all good although cumbersome for things like Alt, but we've got a problem for a few sensor types that have hidden attributes that can't be entered manually.

**Comment by projectkk2glider** [comment]
The received telemetry value is set only for the first sensor that is found, look at https://github.com/opentx/opentx/blob/cd3d473ddcbf245c392fcec744a10749a34cebba/radio/src/telemetry/telemetry.cpp#L489

So your method will not work. What will work is to create a calculated sensor that uses original value and has attributes set to your liking.

**Comment by kilrah** [comment]
Read that again. I precisely changed that piece of code to be a loop (see the for()) so it would allow this use case.

**Comment by projectkk2glider** [comment]
I see a return after the value is set for the first found sensor.

**Comment by kilrah** [comment]
Then I need to go through the log to see who broke my work :(

**Comment by bsongis** [comment]
Perhaps it's me to optimize things :)

**Comment by projectkk2glider** [comment]
34d096e115a940d47509f229383efeef1ad45294

**Comment by bsongis** [comment]
sorry I didn't know it would be needed to continue in the list (aka 2 sensors with the same IDs)!
