### ISSUE TITLE
Compagnon 2.1 not able to flash model

### ISSUE THREAD

**Issue by blairfancy** [opentx/opentx#2517]
Hi,
Companion is not able to flash model on 9XR pro, the app freeze.
Ubuntu and Deb package. Does not work on windows version to.

**Comment by bsongis** [comment]
Reproduced

**Comment by projectkk2glider** [comment]
Is this a same issue as #2402?

**Comment by bsongis** [comment]
Nightly builds are there, would you check the issue is fixed?
http://downloads-21.open-tx.org/nightly/companion/

**Comment by blairfancy** [comment]
Hi,
Bug was not solved with nightly build. I m not able to restore model.

Regards



Date: Fri, 24 Jul 2015 00:36:36 -0700

**Comment by blairfancy** [comment]
It looks like bug on V2.12 with memory allocation problem

**Comment by projectkk2glider** [comment]
>It looks like bug on V2.12 with memory allocation problem 

@blairfancy  can you explain a little more, what allocation problem and which version, the 2.12 is not a valid version number.

**Comment by blairfancy** [comment]
Please see issu #1793 for more information.
