### ISSUE TITLE
VFAS not working when using D series sensors

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2518]
http://openrcforums.com/forum/viewtopic.php?f=45&t=6887&p=99406#p99406

Seems it uses 
#define VOLTS_BP_ID             0x3A
#define VOLTS_AP_ID             0x3B

while we have 

{ VFAS_ID, ZSTR_VFAS, UNIT_VOLTS, 2 },

**Comment by bsongis** [comment]
Right I forgot it, the constants are there and the first part also.

**Comment by bsongis** [comment]
Anyone can test my fix?

**Comment by shadow974** [comment]
Works for me with 2.1.1! 
Had to delete the old sensors and let it re-detect them.

Thanks!
