### ISSUE TITLE
Companion 2.1.99 crashes when I open general settings

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2519]
![companion-crash](https://cloud.githubusercontent.com/assets/8692856/8782607/f16417e8-2f16-11e5-98bf-1e2748e4edb9.PNG)
Companion 2.1.99 crashes when I open general settings.
It doesn't do this when it's empty...

It does so when I open General settings after opening an eepe or reading the settings from my radio.
I just tested it using remote desktop on my machine at work and it does the same.
It seems to be related to my radio's setup, so I will attach the eepe
![20jul2015 eepe](https://cloud.githubusercontent.com/assets/8692856/8782508/3a65e684-2f16-11e5-8109-5428d27535a3.png)

**Comment by projectkk2glider** [comment]
Confirmed, also in 2.1. I will take a look...

**Comment by bsongis** [comment]
Isn't it a compilation problem? Does the problem exist if you start from an empty build dir (not only make clean)

**Comment by projectkk2glider** [comment]
@bsongis the problem is deeper than I thought.

The issue is in available sources for global function `Play Value`. The problematic are telemetry soruces which are picked from current model! On the radio it sort of works, but it might not with other model selected. In Companion it doesnt work, because model is not available when we populate CB sources!

**Comment by projectkk2glider** [comment]
I think telemetry values should not be available for selection for global function `Play Value`. At least not on ARM platforms where we have the new telemetry!

**Comment by bsongis** [comment]
True.

**Comment by bsongis** [comment]
I had the same problem when thinking about Global Switches ...

**Comment by projectkk2glider** [comment]
Will you fix it, or shall I?

**Comment by bsongis** [comment]
I let you work on it, I still have a ton of emails to answer, but let me know if you cannot!

**Comment by projectkk2glider** [comment]
Ok, I will try...

**Comment by fraternl** [comment]
I'm getting bugs that were fixed before.
It seems as if I have an older firmware on my radio all at once.
I flashed it just now using Companion 2.1.99

**Comment by fraternl** [comment]
Is this a quick fix and will it be added later?
It sort of makes it crippled.
I was so glad I could finally make that radio wide

**Comment by projectkk2glider** [comment]
You can't have a global function that plays telemetry value from one of the models. Because the other models might have something else there or worse nothing. Think abut it.

**Comment by fraternl** [comment]
And getting back the radio wide variables Alt and RxBat?
We already have to add 2 switches in each model for that... (I ran out of logical switches)

**Comment by projectkk2glider** [comment]
With the new telemetry system there are no more any radio wide telemetry values. Even RSSI and SWR can be in different positions in different models and can have different names.

Currently I see no other solution for your problem. I agree it is perhaps more cumbersome. Maybe we will come up with some clever idea how to improve this situation.

**Comment by fraternl** [comment]
Link them to radio wide telemetry variables in each model and allow these to be referred to in Global Functions?

**Comment by projectkk2glider** [comment]
Your idea might work. But it needs to be discussed more. Please create a new issue with your requests and ideas, this one is closed and others will miss discussion if we continue here.

**Comment by bsongis** [comment]
Yes this is not a bad idea. Will use more RAM for sure though! But it would also fix the Global Switch issues I foresee.
