### ISSUE TITLE
Companion 2.1.99 imports SF "Reset Alt" as "Reset ---"

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2521]
Companion 2.1.99 imports SF "Reset Alt" as "Reset ---"
I had this in 2.0.99, but then it was impossible to correct it in Companion.
It was then not possible to make a "Reset Alt"

Now, although it's correct in the radio, it will import that setting as "Reset ---"

I believe it worked before, but can't be 100% sure

It is working on my radio. It resets the variometer if it deviates to much.
It should be around 0 metres after entering launch mode....
If it's not, this function will reset the altitude, which it did fine during my flying sessions in the weekend

**Comment by projectkk2glider** [comment]
@fraternl  Just a side note. I recommend you use the `master` branch for your testing, which now contains 2.1.x development. The `next` branch is reserved for 2.2.x.

**Comment by fraternl** [comment]
I'm using nightly builds. Not compiling myself.
How do I get a proper firmware on my radio again?

**Comment by projectkk2glider** [comment]
Use these night-lies http://jenkins.open-tx.org/nightly-stable/ these are 2.1.x

**Comment by bsongis** [comment]
Right, I just renamed the nightly builds. Currently we focus on 2.1.X, I would like we release the 2.1.1 this week.

**Comment by fraternl** [comment]
But isn't this critical enough to be in 2.1.1?

When I write it back to the radio the setting is luckily preserved.

**Comment by bsongis** [comment]
Yes if the bug is in 2.1.0 it must be fixed in 2.1.1 
You lost me with 2.1.99

**Comment by fraternl** [comment]
I am now using the binaries in the nightlies.
Will test again this evening for some stuff...

**Comment by bsongis** [comment]
Anyone reproduces this issue? Here it works ..
I only see an issue with Reset in Global Functions
The same than #2519

**Comment by kilrah** [comment]
Works fine both on 2.1.0 release and current master.

I close it, reopen with precise info if you have some to provide.

**Comment by fraternl** [comment]
Didn't see it was closed without a change.
I will check it again this evening and give some more info.
I'm sure it's still in there "Print model" gave an entry in red as well.....
