### ISSUE TITLE
Simulator 2.1 Windows Radio Type Start/Selection screen

### ISSUE THREAD

**Issue by lvale** [opentx/opentx#2537]
Included screenshot at 1024x768 resolution at normal zoom:

The selection window goes outside the screen laterally and some/most of the button labels are not easy to read. I would suggest a 4 x 3 button layout with enough room on the buttons to clearly read the model type.
<img width="1030" alt="screen shot 2015-07-21 at 23 04 46" src="https://cloud.githubusercontent.com/assets/3130363/8813712/5983f5dc-2ffd-11e5-88b2-cd0c3cd0f164.png">

**Comment by bsongis** [comment]
Already fixed, will be in 2.1.1

**Comment by lvale** [comment]
LoL
The fastest issue report :)
