### ISSUE TITLE
On a 9x pots P1..P3 missing in Companion 2.1.0

### ISSUE THREAD

**Issue by bdowling** [opentx/opentx#2543]
In trying to use 2.1.0 Companion on a 9x, I see that in the UI I am unable to pick the POTs, P1 thru P3 as a Mix source for example.

From the radio itself I can choose this, and it displays correctly when downloaded. But as the Px source isn't in the drop down, you can't edit it without losing the correct source.

fwiw, once configured via the radio, the simulator does show the Px mixes changing the channels, so I know that is working as I expected.

Hopefully I'm not doing something wrong here, but let me know if I am.

**Comment by bsongis** [comment]
Good explanation of the problem, thanks!
