### ISSUE TITLE
CYC Mix 2.1.x

### ISSUE THREAD

**Issue by marcodcribeiro** [opentx/opentx#2553]
Hi,

i upgrade from 2.017 to 2.1.0 but the CYC Mix dont work in Heli CCPM.

**Comment by bsongis** [comment]
It should be fixed in latest nightly builds, would you give it a try?
http://downloads-21.open-tx.org/nightly/companion/

**Comment by griebd** [comment]
have you set the weight? the heli tab has changed a bit...
in my case I needed to set the input for lateral and longitudinal movement and set the weight, it was default to 0.
from what I understood if you set it to 100 you have the same behavior of 2.0. And if you had any reverse set, then -100.
was that your problem?

**Comment by bsongis** [comment]
To download the latest nightly build you follow what I wrote here:
https://github.com/opentx/opentx/issues/2526

**Comment by marcodcribeiro** [comment]
The nightly builds works in taranis Radio? if yes i will try later.

**Comment by bsongis** [comment]
Yes, you will see how to download the firmware nighly built in my post

**Comment by marcodcribeiro** [comment]
Tks,

later i will install companionInstall_2.1.1N390.exe ajnd test

**Comment by kilrah** [comment]
Yes the fix was for the swash ring, the rest should normally be ok.

**Comment by marcodcribeiro** [comment]
griebd, i did the input for lateral and longitudinal its works. tks

bsongis, tks for the help too
