### ISSUE TITLE
Play Value RSSI

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#2557]
Not sure if this was an expected change from 2.0.17 to 2.1.0. or not.  When Play Value RSSI in Special Functions is selected with a switch in 2.0.17 it would play the RSSI value followed with the word "Db".  In 2.1.0 it plays the value only.  I have the July 16, 2015 en American English sound pack installed. Please see attached screen for Play Value programing. 

Taranis Plus system.

![play value rssi](https://cloud.githubusercontent.com/assets/11791852/8881376/4cd07cea-320d-11e5-9df5-0426b4d45eca.png)

**Comment by Swwils** [comment]
This also occurs for any play value - it only says the first value encountered. e.g. a calculated cell value actually being 3.67 volts only says "3 volts".

**Comment by MIKE-DAILEY** [comment]
Play Value works correct for RxBt on my system, e.g. plays 5.1 volts.  One of the sound packs fixed that problem for me a few weeks back.
