### ISSUE TITLE
Companion, Compare models, Curves not working

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2560]
http://downloads-21.open-tx.org/nightly/companion/companionInstall_2.1.1N391.exe

When I do a Compare models of my Cumel, the curves are not shown.
Only Curve22 (which I don't use) is shown.
I believe it's rather a long time already.

**Comment by projectkk2glider** [comment]
Link to Cumel eepe https://cloud.githubusercontent.com/assets/8692856/8888344/0ab7bf10-32aa-11e5-9566-105b92f2ae1f.png

**Comment by projectkk2glider** [comment]
This issue goes way back.

**Comment by fraternl** [comment]
Seems to be fixed in https://github.com/opentx/opentx/issues/2734

**Comment by LapinFou** [comment]
You wrote "partially fixed", what is not fixed yet?

**Comment by fraternl** [comment]
Because this feature never worked I'm already glad I now have the raw data.
The curve graphs however are all placed on each other.
I assume they were meant to be apart, but not sure though....
In "print model" all the graphs overlap as well and a legenda is shown.
Maybe it should be turned into a feature request:
![curves-overlap](https://cloud.githubusercontent.com/assets/8692856/9378917/91ac9be6-4725-11e5-9d61-5a26c981e6e1.PNG)

**Comment by LapinFou** [comment]
OK. Thanks for the feedback.
I'm sure projectkk2glider will fix it one day. :)

**Comment by fraternl** [comment]
He now just had a renewed acquintance with the code   ;-)

I made a new issue for this and this one can be closed
https://github.com/opentx/opentx/issues/2737

**Comment by projectkk2glider** [comment]
Closing this one, the @bsongis is making an extensive refactoring of the code as a part of #2737.
