### ISSUE TITLE
Companion 2.1: SH polatrity wrong in simulator for X9E

### ISSUE THREAD

**Issue by ChrisParish** [opentx/opentx#2561]
When running the simulator for an X9E the SH switch polatrity is wrong. i.e when the switch is in the UP posistion then the sim reads it as being in the down position and vice versa.

**Comment by projectkk2glider** [comment]
Confirmed, in fact both 2 pos switches are wrong (SF and SH).

**Comment by driver33** [comment]
Just a simple question:  is it error in software or error in assembly the radio ?

**Comment by projectkk2glider** [comment]
In Companion simulator only - so software only.
