### ISSUE TITLE
Companion nightly is unable to update itself

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2563]
Companion nightly properly detects there's a new version, but then it is unable to download that version.
![screen shot 07-26-15 at 08 17 am](https://cloud.githubusercontent.com/assets/8692856/8892809/6bceeb96-336f-11e5-9acb-c1f70b2b66eb.PNG)

A subsequent manual download was made successfully

**Comment by bsongis** [comment]
Good catch, it would have been the same with the release!

**Comment by bsongis** [comment]
It should be good now, would you check?

**Comment by fraternl** [comment]
Checked....
:-)
