### ISSUE TITLE
Changes at languages file de.h.txt  from Next  #2488   are not transfered to Master

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2564]
so at latest Master are some strings wrong and for 9XRPro to long

**Comment by bsongis** [comment]
I changed my mind and currently only 'master' is maintained. We have enough work to make it bugfree, then we will start working on 2.2.0 (next)

**Comment by kilrah** [comment]
E.g. do not do anything in next for now, what you want included should be dine in master. When we start working on next we'll base it on master's current state.

**Comment by projectkk2glider** [comment]
>I changed my mind and currently only 'master' is maintained. We have enough work to make it bugfree, then we will start working on 2.2.0

Uff, I strongly agree with this decision. :+1:  The duplicate work was tiresome and error prone.

**Comment by bsongis** [comment]
I forgot to answer to your post, but I followed your advice. In fact I didn't imagine how much work was remaining in 'master', I thought I would quickly dive into mixer rewrite in 'next'
