### ISSUE TITLE
[Heli Settings] add Gvar as source on weight settings

### ISSUE THREAD

**Issue by 483917** [opentx/opentx#2567]
Add Gvar as source on Long.cyc ,Lateral.cyc, Collective, and Swash Ring.
Makes Heli settings even more flexible.
I know this can be done in [Inputs] ,sort of

If its  a bad idea ? Feel free to close this issue

**Comment by bsongis** [comment]
It's a good idea. I plan to add this possibility for many fields (I have slow and delay in mixes in mind)

**Comment by bsongis** [comment]
Perhaps it will be done in 2.2.X if we need an EEPROM change

**Comment by 483917** [comment]
Yes thanks perfect, Gvar:s is extremely versatile i use them very much
