### ISSUE TITLE
Mac OS installer spams /Library, /usr/local/*

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#257]
_From [DrZip...@gmail.com](https://code.google.com/u/103756129429363622233/) on June 04, 2012 07:02:06_

The Mac OS X package overwrites files in /Library (if you already have SDL installed) and /usr/local (avrdude, libusb, etc.).  Many of the files written are not actually used by the application (SDL headers, static libraries, etc.).

This will damage e.g. Homebrew installs, other applications using different versions of SDL, libusb, etc.

Since Companion9x installs an application, the frameworks it requires should be packaged inside the application's Contents/Resources folder.  This will both avoid damaging the user's system, and permit a simple drag-and-drop installation.

_Original issue: http://code.google.com/p/companion9x/issues/detail?id=57_

**Comment by schwabe** [comment]
Should be closed by #3776
