### ISSUE TITLE
Companion 2.1.1, Print model can't handle SF  "Reset Alt"

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2570]
Companion 2.1.1, Print model can't handle SF  "Reset Alt"
Probably it can't handle more telemetry values.....

It was first mentioned in ticket https://github.com/opentx/opentx/issues/2541
I just closed that ticket because it involved another issue which was solved.

![screen shot 07-26-15 at 02 24 pm](https://cloud.githubusercontent.com/assets/8692856/8893877/a5abb1ea-33a2-11e5-9537-21e6ce46e26e.PNG)
![screen shot 07-26-15 at 02 22 pm](https://cloud.githubusercontent.com/assets/8692856/8893878/a8dbc54e-33a2-11e5-9e23-76e248988fb4.PNG)
![eeprom-2015-07-26-14-19-54 bin](https://cloud.githubusercontent.com/assets/8692856/8893879/b153cf1e-33a2-11e5-8a70-aa87ef6282b6.png)

**Comment by bsongis** [comment]
I will take this one, there is code missing and some refactoring to avoid duplicate ...

**Comment by projectkk2glider** [comment]
This might also be fixed in #2590

**Comment by bsongis** [comment]
@fraternl please reopen if needed after nightly builds

**Comment by fraternl** [comment]
It's working fine....in 2.1.1N396
