### ISSUE TITLE
Play Value RSSI

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#2574]
Should https://github.com/opentx/opentx/issues/2557 be fixed in nightly build July 26, 2015?  I'm testing and it is not playing "Db". Are there new sound files that I should be loading other than what I loaded with 2.1.0?

**Comment by bsongis** [comment]
No the 2.1.0 sound files didn't change in 2.1.1 
But if your sensor was created with 2.1.0? If yes it has no unit.
So 2 solutions:
1) you change its unit manually to dB
2) you remove your sensor and it will be created again by 2.1.1 with the right unit
If I am wrong please reopen the issue!

**Comment by MIKE-DAILEY** [comment]
Set it manually and it is working fine.
