### ISSUE TITLE
Companion print model and compare model has receiver number missing

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2576]
When I was comparing 2 models I noticed that it didn't flag the receiver numbers.
In fact, these are completely missing.

Not really a bug, but if it's used for some purposes it could be valuable info.
I wouldn't mind that much if it's not added, but for completeness I think it should (low priority?)

**Comment by kilrah** [comment]
There's a n open issue for pretty much a complete rewrite of compare and print dialogs because they're quite outdated and code is duplicated. Not worth fixing much until then I'd say.
https://github.com/opentx/opentx/issues/1063

**Comment by fraternl** [comment]
Ah, ok....
As long as the "print model" and "compare model" isn't just scratched before a new one is put in place. I find it quite valuable...

**Comment by projectkk2glider** [comment]
Related to #1063
