### ISSUE TITLE
PPM channel ordering

### ISSUE THREAD

**Issue by agnauck** [opentx/opentx#2578]
I am using a Robbe/Futaba HFM12-MX PPM module in my Taranis. The same module is available under other brands as well, eg Ripmax or Hobbico.

The output of the PPM channels 1-3 is wrong/different in the module.

TX 1 -> RX 2
TX 2 -> RX 1
TX 3 -> RX 2

from channel 4 on the ordering is correct.

It would be great if there would be a feature in the future where the PPM order can be configured. Or a Futaba PPM setting where the ordering is hardocoded and corrected in the Firmware.

**Comment by kilrah** [comment]
I have one of those modules too, just order your mixes accordingly, it isn't that hard. The mixer in OpenTX is already so flexible it wouldn't make much sense adding such an option...
