### ISSUE TITLE
Feature Request: Eject the 2 volumes from within Companion

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2583]
I often disconnect the USB-cable without ejecting the media.
This could lead to a corrupt SD-Card.

If this could be done by clicking on an icon in Companion this could be easily added to my routine.

**Comment by kilrah** [comment]
Windows? Last time I ejected a drive on Win was probably 5 years ago or so.

**Comment by fraternl** [comment]
I've had USB-disks become corrupted. Last thing I did was pull the USB without ejecting....
I do agree it is not that often and in your case it never happened....
