### ISSUE TITLE
Play Sound vs Play track or Play Background music

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#2587]
In 2.1.1N395 Special Functions. Windows 8.1.
One can listen to a Track or to Background music with a click of the start arrow, shouldn't Play Sound also be palyable?

![playsound](https://cloud.githubusercontent.com/assets/4843199/8934965/1e23657a-34ff-11e5-9c9b-9af72c7fe993.PNG)

**Comment by bsongis** [comment]
Is this PlaySound function really needed on ARM boards?

**Comment by projectkk2glider** [comment]
I use it for sure. It is a simple way to generate some beeps and warning sounds.

**Comment by projectkk2glider** [comment]
@rdeanchurch you can't play it in Companion, the sound is generated on the fly in radio firmware.
