### ISSUE TITLE
Allow mixes to be switched "OFF".

### ISSUE THREAD

**Issue by Julez1** [opentx/opentx#2591]
Hello,

what I am missing currently is the clean and simple option to switch a mixer off. Do do this now, I would have to delete the mixer, set the weight to 0, create a logic switch which is always "off" and assign the mixer to it, or tie the mixer to a flight phase that is never used.
A clean and simple solution would be either to have a dedicated checkbox switching the mixer off, or being able to choose "OFF" in the switch menu.
Apparently someone had the idea before me, because in er9x it was possible to switch "OFF".
Regards,
Julian

![mixer](https://cloud.githubusercontent.com/assets/13544262/8941534/7014c4c0-3570-11e5-8e3f-34078ce0c984.gif)
![mixer2](https://cloud.githubusercontent.com/assets/13544262/8941533/70131d78-3570-11e5-8919-dcd37cf84248.GIF)

**Comment by borland1** [comment]
Won't someone confuse that switch option?  The power switch is labeled "ON".

**Comment by Julez1** [comment]
I'd be very happy either way. But another advantage of the check box would be that one would not have to reassign a previously preferred switch when reactivating that mixer.

**Comment by fraternl** [comment]
If this is implemented (the checkbox version, I hope) it should be made clear somehow that this mixer-line is turned off in the display...

**Comment by kilrah** [comment]
We can have ot greyed out, I think we even already have code for that in the UI.

**Comment by borland1** [comment]
Greyed out text or strikethrough text would work.
Most Special Functions have a enable check box. A disable check box on the Main Mixer page might allow for easier way to disable/enable.
I wonder how the Multiplex option might work for mixer lines below one set to 'disabled'?  I guess the intent would be like "Multiplex: Bypass".

**Comment by fraternl** [comment]
Either they should be grayed out too as some confirmation and skipped or just left to the responsibility of the user and stay enabled.

It took a long time for someone (julez) to come up with this request. I doubt that many will make use of it. I'd think it should be left to the user. OpenTX is not a system that holds your hand all the time.

The example he gave would have been better off with a logical switch.

**Comment by kilrah** [comment]
From what I can see there is no free bit in the mixer structure that could be reused for a checkbox so that couldn't be done before 2.2, and even then I doubt it's worth "opening" a whole new byte just for it.

Switch set to "OFF" is possible, but then we'd have 2 ONs (nothing and ON). We could remove ON, but then we'd lose quick access to OFF from the shortcut popup.

Multiplex set to OFF should be possible and the easiest/cleanest.
