### ISSUE TITLE
9XR pro resetting when changing from XJT to PPM in setup menu

### ISSUE THREAD

**Issue by eokeeffe** [opentx/opentx#2592]
Noticed a slight bug in the setup menu.
When I go to External RF mode and change from PPM to XJT nothing happens.
But when I try to reset it I notice there is an immediate power off and reset.
The option does not change but remains the same.

**Comment by bsongis** [comment]
Which version?

**Comment by eokeeffe** [comment]
opentx-9xrpro-2.1
EEPR:217


On 28 July 2015 at 22:42, Bertrand Songis <notifications@github.com> wrote:

> Which version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentx/opentx/issues/2592#issuecomment-125762147>.
>



-- 
*Forti Et Fideli , Nihil difficile*

**Comment by bsongis** [comment]
What do you mean by "try to reset it"? Do you mean "change again to PPM as it was before"?

**Comment by eokeeffe** [comment]
trying to change the setting from XJT back to PPM yes

On 29 July 2015 at 19:51, Bertrand Songis <notifications@github.com> wrote:

> What do you mean by "try to reset it"? Do you mean "change again to PPM as
> it was before"?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentx/opentx/issues/2592#issuecomment-126056332>.
>



-- 
*Forti Et Fideli , Nihil difficile*

**Comment by bsongis** [comment]
Not fixed
