### ISSUE TITLE
Feature Request: Like Tada.wav, a sound that's played on shutdown

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2602]
When OpenTX is started it plays tada.wav
Something similar could be done when OpenTX shuts down.

This feature was asked in rcgroups
http://www.rcgroups.com/forums/showpost.php?p=32288521&postcount=19381

Do nothing if the sound is not in the /en/SYSTEM folder

https://archive.org/details/MicrosoftWindowsXPShutdownSound

**Comment by kilrah** [comment]
bye.wav
