### ISSUE TITLE
Writing setting to radio doesn't work -  Companion 2.1 /  9XR PRO  

### ISSUE THREAD

**Issue by procha170** [opentx/opentx#2605]
Hello,
Save setting doesn't work in companion. I can load setting from radio but changes are no written there.  9XR PRO

**Comment by projectkk2glider** [comment]
Same as #2517?

**Comment by procha170** [comment]
Yes It looks the same. Official version 2.1 freeze during saving. Last build doesn’t freeze but saves nothing.

.

**Comment by projectkk2glider** [comment]
@procha170 please check again after the 2.1.1 is released.

**Comment by kilrah** [comment]
Possibly related to #2619...

**Comment by bsongis** [comment]
I am afraid that the bootloader doesnt accept the new eeprom format.
Here is the code in the sky9x bootloader:
'''
// Test for EEPROM file
uint32_t isEepromStart( uint8_t *p )
{
	uint32_t csum ;
	uint32_t size = 7 ;

	csum = 0 ;
	while( size )
	{
		csum += *p++ ;
		size -= 1 ;
	}
	if ( csum == *p )
	{
		return 1 ;
	}
	return 0 ;	
}
'''

Fortunately the result of the test goes into a static boolean which never returns to 0, it should be possible to bypass the test.

'''
if ( isEepromStart( (uint8_t *) buffer ) )
		{
			EepromBlocked = 0 ;
		}
		else
		{
			EepromBlocked = 1 ;
		}
'''

**Comment by kilrah** [comment]
We should port our bootloader at some point...
