### ISSUE TITLE
CZ and SK tts code is not 2.1 ready

### ISSUE THREAD

**Issue by mhotar** [opentx/opentx#2610]

**Comment by mhotar** [comment]
If I am not wrong, there are different telemetry unit numbering in 2.1 tts, CPUARM has new one and !CPUARM is still the same as the 2.0 was. In this case we cannot use 2.1 tts.py to generate tracks for !CPUARM boards? I had to split my CASE switch in tts_cz.cpp unit types to reflect this. Can someone confirm that I am not wrong here please? I cannot test it myself, I do not have any sound capable radio.

**Comment by bsongis** [comment]
Yes you are right, we should have 2 different numbering systems in this tts.py (well, only for units in fact)

**Comment by mhotar** [comment]
OK thanks for confirmation.
