### ISSUE TITLE
Get rid of the "RF signal low" alert before "Telemetry lost" when powering off receiver

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2616]
Seems we currently feed zero RSSI values into the filter when nothing is received - we should probably skip them and have a timeout instead.

**Comment by LapinFou** [comment]
:+1:

**Comment by kilrah** [comment]
All good!

**Comment by bsongis** [comment]
Was it ported to 'master'?

**Comment by kilrah** [comment]
No, but is it really necessary?

**Comment by bsongis** [comment]
No, but today I used 2.2 and it's nice :)

**Comment by bsongis** [comment]
It was only a 2 lines fix, I just ported it to 2.1.8
