### ISSUE TITLE
EEPROM storage problem on sky9x/9xrpro in standalone simu

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2619]
Settings are often not stored, and eeprom is reported as corrupt every few launches.
Trying to open an eeprom from these platforms with companion results in "invalid format".
Hopefully it's only in the simu.

**Comment by Grapaf** [comment]
Unfortunately, not only in the simulator. 9XR Pro radio, firmware OpenTx 2.1.1, master branch from 31.07.15. Yesterday, in the field I found that the the radio reports about eeprom error and formats it. The saved backup from the memory card has not recovered. No errors are issued, it simply creates a new blank model without adjustments, that I made before saving the model.

PS: sorry for my english.
