### ISSUE TITLE
Companion 2.0 opens 2.1 eeproms but obviously with a corrupt result

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2620]
Should give an invalid eeprom error, or even better say it's a 2.1 eeprom.

**Comment by griebd** [comment]
Two points:
1) the way the code is (as far as I understood it) makes it impossible for the GUI to know why the file was not open, so there is no way to tell it's a 2.1 eeprom.
2) haven't even looked at it, but the radio firmware isn't affected by the same issue?

**Comment by griebd** [comment]
Just to let it clear, checked my second question above in simulator and it gives a "bad eeprom"!

It's already done and merged, closing...
