### ISSUE TITLE
Model Wizard Number of Channels

### ISSUE THREAD

**Issue by ianjanflan** [opentx/opentx#2624]
The Model Wizard only gives 8 channels to work with and any plane with flaps and gear requires more than 8 channels if allocating one channel to each surface and function. Can this be upgraded to at least 16 channels please.

**Comment by griebd** [comment]
Has already been discussed before!
Thing is, the wizard is to help newcomers to see how OpenTX works. If you need more than 8 channels you are past the wizard, you need to do things yourself!
You can start from the wizard to see how things are done and add what you you need!
Think about how much possibilities there are, OpenTX gives you the chance to explore then all!!! How could we put all in a wizard? There is no magic here, just freedom!!!!

If you need help, use the forums, people will help you there!!!!

Hope you enjoy OpenTX as much as I do.
