### ISSUE TITLE
Shutdown confirmation

### ISSUE THREAD

**Issue by myckey** [opentx/opentx#2625]
When loading latest version of firmware to 9XE and selecting the shutdownconfirm option this doesn't get loaded in the firmware, i.e. just push and hold down power button shuts down the TX, no request to confirm shutdown by pressing eneter.

**Comment by projectkk2glider** [comment]
Probably just a missing option on the firmware compilation server, the source looks fine.

**Comment by myckey** [comment]
That would make sense as the 9XE with the shipped firmware DID have the confirmation working.

**Comment by kilrah** [comment]
Typo in the compilation script, should be fixed.

**Comment by myckey** [comment]
I can confirm that is now fixed, thank you.
