### ISSUE TITLE
Add haptic option for countdown timer

### ISSUE THREAD

**Issue by Matty2B** [opentx/opentx#2635]
Is it possible to add in haptic options for the countdown timer? Ideally I would like the option to have the option to enable haptic as well as beeps/voice, or instead of them. This would really helpful when flying in a noisy environment. Many thanks!

**Comment by bsongis** [comment]
Why not, I will take care of it once the 2.1.1 rush is over

**Comment by Matty2B** [comment]
Many thanks, much appreciated. No rush though, it is not an important one.
