### ISSUE TITLE
10 m/s limit of vario

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2636]
First off, sorry to use github for asking this question.
I think this is the best place to ask, please tell me if I shouldn't do this in the future.

Adrian (Extremewing) has developed a launch script and I've been contributing with ideas, snippets of code and debugging/testing. He is using an open altimeter (BTOA) and I'm using a Frsky HP vario.
In his version he has the script call out the the highest vertical speed...
I noticed that I was always getting 10 m/s, so it's not that valuable info.....
I've tried to increase these values in the telemetry settings, but that didn't make a difference.

Is there something to be done to increase this value to 20 or maybe even 30 m/s or is this just the limit and I should make myself a BTOA?

http://www.rcgroups.com/forums/showthread.php?t=2467581

**Comment by kilrah** [comment]
AFAIK that is the maximum Vspd the FrSky vario will report.

Those questions are better asked in the forums indeed until you're sure it's a firmware thing we can actually do something about.
