### ISSUE TITLE
Special functions: saying telemetry value istn't available since 2.1

### ISSUE THREAD

**Issue by dklueh79** [opentx/opentx#2640]
Until today I used the chance to set a special function for "say value" for telemetry data.
But since upgrading on 2.1, it isn't available any more.

Could this be readded, please?

**Comment by kilrah** [comment]
It's of course still there. You need to let the radio discover the connected sensors before they can be selected as value to say.

**Comment by dklueh79** [comment]
OK, that works nearly.- But I didn't find any documentation, if the old sensors still work (analog, with sensor hub on an D8R-Receiver)
During switching on the Taranis the old FAS-100 and FLVS-01 aren't shown...but one of the old Temp.Sensor. The screenshots show the new and the old telemetry window.

![2015-08-06 08_51_17-modell 8 bearbeiten _assault-fbl](https://cloud.githubusercontent.com/assets/6195999/9105494/a0cd865c-3c18-11e5-9304-66a64cb3d81c.png)
![2015-08-06 08_51_56-modell 8 bearbeiten _assault-fbl](https://cloud.githubusercontent.com/assets/6195999/9105497/a6fc1a8e-3c18-11e5-8279-b4ac6907df5b.png)

**Comment by kilrah** [comment]
That capture shows all the hub data, but it seems your fas/flvs weren't connected.

**Comment by dklueh79** [comment]
OK, but I haven't cconnected fuel- or apm-sensor- why does the taranis recognize this?

So, the old sensor all should work, too- right?

**Comment by kilrah** [comment]
That's just how the hub works... It sends values for everything even if the sensor is not connected... Except for the fas/flvs that use a slightly different interface.

All sensors are of course supposed to work.

**Comment by dklueh79** [comment]
OK, but I haven't cconnected fuel- or apm-sensor- why does the taranis recognize this?

So, the old sensor all should work, too- right?
