### ISSUE TITLE
Broken link on open-Tx.org

### ISSUE THREAD

**Issue by rguptaca** [opentx/opentx#2641]
http://www.open-tx.org/2015/07/16/opentx-2.1.0/ 
At the top of the page the "here" link is broken

**Comment by kilrah** [comment]
Works here, the "www" wasn't in so maybe your browser throws a fit... now added.

**Comment by rguptaca** [comment]
Thanks. iPad. 

Rav

Have a wonderful day!

Ravi Gupta, PMP
Founder of Hike For Happiness
A Mental Health Fundraiser
http://hikeforhappiness.ca/
(519) 697-0796

On Aug 5, 2015, at 2:05 AM, Andre Bernet <notifications@github.com> wrote:

Closed #2641.
