### ISSUE TITLE
Gspd value in Taranis Telemetry too high

### ISSUE THREAD

**Issue by marcodcribeiro** [opentx/opentx#2644]
hi,

i have taranis 2.1.0 with telemtry but gspd value in display show values like 400 and so.
any update on that?

**Comment by projectkk2glider** [comment]
Sport or hub sensor?

**Comment by marcodcribeiro** [comment]
its a external GPS and the Telemetry is by Naze32.
the unit i try kmh an kts.
the value in naze32 logs its correct

**Comment by kilrah** [comment]
What receiver? What firmware and version on the Naze32?

The problem is most likely in the Naze32 firmware as we've had no reports of issues with the FrSky GPS.

**Comment by marcodcribeiro** [comment]
Sorry,

i'm use Naze32 Cleanflight 1.9.0 and frsky d4r II

**Comment by projectkk2glider** [comment]
Bug in Cleanflight https://github.com/cleanflight/cleanflight/blob/master/src/main/telemetry/frsky.c#L248

The sent gps speed is multipled with 0.1944 instead of 0.01944

**Comment by kilrah** [comment]
I'll send a pull request to cleanflight, already have a fork

**Comment by marcodcribeiro** [comment]
Tks for the help,
So or change to baseflight or wait to any update to cleanflight.

**Comment by kilrah** [comment]
Baseflight doesn't send GPS speed at all.

**Comment by marcodcribeiro** [comment]
Tks,
so for now i'll create a LUA script to do the calculation about GPS

**Comment by projectkk2glider** [comment]
You could also play with the ratio parameter.

**Comment by marcodcribeiro** [comment]
how?

**Comment by projectkk2glider** [comment]
Ah, I was wrong. The Ratio does not support division by 10. You will have to wait for the #2615

**Comment by kilrah** [comment]
It will once #2615 is implemented :\

**Comment by marcodcribeiro** [comment]
Tks guys for the help. I'll wait

**Comment by hydra** [comment]
merged https://github.com/cleanflight/cleanflight/pull/1191 into cleanflight

**Comment by kilrah** [comment]
:+1:
