### ISSUE TITLE
X9E shutdown after exit selection in bootloader

### ISSUE THREAD

**Issue by lichtl** [opentx/opentx#2650]
Hi,

don't know if this is really an issue or working as intended. Compared to my X9D when exit the bootloader menu my old Taranis just boot through while the new X9E just switch of. It would be great if there is a possibility to either shutdown or boot through or by default just reboot (maybe even a flag on the firmware)

Thanks
Carsten

**Comment by kilrah** [comment]
It's just a consequence of the different power control hardware in the x9e.
