### ISSUE TITLE
Easier mixers monitor

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#2655]
In addition to #2258 wouldn’t it be more convenient if Companion could show the mixers monitor in some tabs here, as for outputs?
![onglet](https://cloud.githubusercontent.com/assets/8396899/9117241/3e63f07c-3c69-11e5-997d-df3e1f6921e7.PNG)

**Comment by LapinFou** [comment]
:+1:

**Comment by pindeslandes** [comment]
This issue seems to have been forgotten: the simulator of companion 2.2.1 still can’t show mixers monitor (but still shows channels monitor, which is far less relevant when you are setting a new model, specially a complex one). To see the mixers outputs, one must go through the pages of the radio display, which is not very convenient.
