### ISSUE TITLE
Display issues on X9E?

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2664]
Read about here: http://frskytaranis.forumactif.org/t2455p45-companion-2-1-je-ne-comprends-pas-tout#28397 

Broken splash screen, possibly only when custom

**Comment by bsongis** [comment]
On X9E I just tested the splash screen, with a custom one. No problem.
I flashed it using the bootloader

**Comment by kilrah** [comment]
Bleh :(

**Comment by bsongis** [comment]
Perhaps again the problem with flashing with the bootloader ....
