### ISSUE TITLE
Mac version of Companion 2.1.1 has no sound

### ISSUE THREAD

**Issue by rmcclurg** [opentx/opentx#2667]
The compilation of the OSX version of Companion did not include the correct libraries for sound. The resulting Companion installation does not have the play button on Special Functions that include sound files.

**Comment by projectkk2glider** [comment]
@bsongis this is a packaging problem, could you correct it and upload the new/better/improved package for 2.1.1?

**Comment by bsongis** [comment]
Yes when I have one minute :)

**Comment by floaaaaargh** [comment]
Is this the same problem that causes the complete refuse to launch the app here? I get the same error-text.

**Comment by kilrah** [comment]
Yes.
