### ISSUE TITLE
Feature request: Highlight unreferenced logical switches

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2670]
If a logical switch is unreferenced by either a special function or another logical switch this may indicate an orphaned switch or user error..
When fiddling around with different kind of setups and new ways to achieve something it is of great help if these are highlighted.

In Companion this could be in red and on the radio underscored

I just cleaned my setup and made several changes and it would have been of great help to immediately see that a switch was not refenced. No need to page swap and scroll....

**Comment by projectkk2glider** [comment]
I am not in favor of this kind of check on the radio, too much additional code.

But it could be done in the Companion, I envision a kind of *model checker* function that could be executed from the menu and then a report created that would point out any obvious problems with the setup like unreferenced switches, etc...

**Comment by fraternl** [comment]
On Companion it could be done in realtime, no?

**Comment by projectkk2glider** [comment]
Yes it could be done that way, but I prefer to gather all errors (if we do a more complete check) in one place.

**Comment by kilrah** [comment]
>On Companion it could be done in realtime, no?

It would become way too annoying/intrusive, the moment you set up an LS it would come up in red because it's obviously not used yet...

**Comment by fraternl** [comment]
Who's afraid of red yellow and blue?
