### ISSUE TITLE
special function play value rssi not playing db sound

### ISSUE THREAD

**Issue by driedeker** [opentx/opentx#2675]
In special function play value rssi not playing db sound in firmware and companion 2.1.1 taranus
just plays value with out the db sound.

**Comment by kilrah** [comment]
Set the unit to dB.

**Comment by driedeker** [comment]
sorry where do i do this.

**Comment by kilrah** [comment]
Telemetry setup page, select RSSI, enter to edit settings, set unit to dB.

**Comment by driedeker** [comment]
found it thanks.
