### ISSUE TITLE
Allow LUA model script out as Inputs source

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#2676]
I would like to ba able to use an lua model script out as the source of an input. Currently, you can use quite a few things, but LUA outs are not part of it

**Comment by projectkk2glider** [comment]
True Lua script outputs (from model scripts) can not currently be used as a source for inputs. 

But you can use it already as a source in the mixers. Would that be enough for you?

**Comment by 3djc** [comment]
Sure, I found a different approach to tackle my needs :). I still think it would make some sense to have it there, but I'm more than fine to have it put on the backburner !!!

Thanks for all , jc
