### ISSUE TITLE
Companion 2.1.1: Lua custom script returning 100 is displayed at 0 in telemetry screen

### ISSUE THREAD

**Issue by fred99** [opentx/opentx#2684]
I run this trivial programme under Companion 2.1.1
-- LUA custom script
-- SD\SCRIPTS\MIXES
   
 local outputs = { "out" }
    local function run() 
      return 100 *10.24
    end
    return { run=run, output=outputs }

![capture0](https://cloud.githubusercontent.com/assets/12371235/9156509/ea702ac8-3edc-11e5-86ad-d2a611196d05.JPG)

![capture2](https://cloud.githubusercontent.com/assets/12371235/9156512/fb745f24-3edc-11e5-8182-7432c2badfde.JPG)
Should be 100:
![capture1](https://cloud.githubusercontent.com/assets/12371235/9156511/f31db186-3edc-11e5-806d-114e3d44d5c4.JPG)
This trivial progamme works fine on my Taranis updated in 2.1.1.

**Comment by projectkk2glider** [comment]
Confirmed, fix coming up..

**Comment by projectkk2glider** [comment]
It caused a segmentation fault in Companion actually!

**Comment by fred99** [comment]
Wow!
Companion seemed imperturbable.
