### ISSUE TITLE
SF Play Value Timer without "minutes" an "seconds"

### ISSUE THREAD

**Issue by floaaaaargh** [opentx/opentx#2689]
Hi, 
in 2.1.1 the announcement of the timers says "point two" instead of the right scale "minutes" or "seconds". 
This happens in the simulator and the Taranis.

**Comment by kilrah** [comment]
You forgot to upgrade your sound pack.

**Comment by floaaaaargh** [comment]
Ups. I thought, that would be optional. Thanks.

**Comment by davidlibbyFIT** [comment]
I downloaded the current Amber Sound pack and 145 and 146 are there in the sd/sounds/en/system dir.

Version: 2.1.6
Varient: 217
Date&Time:2015-11-12 03:16:36

**Comment by davidlibbyFIT** [comment]
Update.. I downloaded the wrong sound pack, All is well thanks..
