### ISSUE TITLE
EEPROM OVERFLOW on 9xr

### ISSUE THREAD

**Issue by mrpreciado** [opentx/opentx#2690]
i keep getting this warning EEPROM OVERFLOW ,i just have a couple of models saved and still displays the error
![eeprom](https://cloud.githubusercontent.com/assets/13734310/9176954/dc47b732-3f53-11e5-91ca-9b8f1e1b6ee4.jpg)

**Comment by kilrah** [comment]
This does not look like an OpenTX screen but like the original firmware (er9x). It should tell you how much free space there is on the model selection screen if I remember well.

**Comment by mrpreciado** [comment]
![nomem](https://cloud.githubusercontent.com/assets/13734310/9183194/62d1844e-3f73-11e5-902c-decb363cc484.jpg)
it looks like if it had no memory ,with just 2 models it displays it doesnt have enough  memory and when there are no saved models i get like 160 free,do you have any recomendation to solve this or what sould i try tnhks

**Comment by bsongis** [comment]
This is not OpenTX.
OpenTX would show you 7 models in this last screenshot.

**Comment by bsongis** [comment]
Also it seems to me that the screen index has a display problem (a white column between / and 11)

**Comment by kilrah** [comment]
You should ask your question there: 
http://openrcforums.com/forum/viewforum.php?f=70
