### ISSUE TITLE
Add default logging behaviour to general settings.

### ISSUE THREAD

**Issue by flarssen** [opentx/opentx#2692]
It would be nice to have a single checkbox in general settings that affects the default for new sensors. That way there will be a choice between editing the ones that you want to log, or edit the ones you don't want to log.

**Comment by fraternl** [comment]
Yes....  I second that!!!

**Comment by bsongis** [comment]
General Settings or Model Settings?

**Comment by kilrah** [comment]
I'd say general...

**Comment by flarssen** [comment]
Me too. (Radio setup in Tx)
