### ISSUE TITLE
Auto-offset for Frsky variometer on per default

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2693]
In the telemetry options the Frsky-altimeter needs to have "auto-offset" enabled for proper behaviour. It would be nice if this is set at discovery.

Maybe this is the proper settings for all barometers

**Comment by kilrah** [comment]
It's not a "need", it's personal preference. Was discussed and rejected not even a week ago.

**Comment by fraternl** [comment]
It might be that I'm mistaken, but these variometer can't possibly give any sane value out of the box without this option selected, can they?

**Comment by kilrah** [comment]
Or you may want a manual offset to see variation.

**Comment by griebd** [comment]
@fraternl, I do not disagree with you, most people will set auto-offset and use this way... BUT that doesn't mean you can't use without it...
what @kilrah sad in hist comment is that you need to calibrate it everyday, maybe even every hour.... but you can calibrate it to your local altitude and have a valid ASL (above sea level) value.

**Comment by fraternl** [comment]
I don't believe such a calibration is possible unless he means giving it a manual offset each day... (every 15 minutes)
An impractical way to achieve something that most people are not even interested in.....

A reset to 0 IS something that can be done by using some buttons or like I do using a special function.

Why hinder people that use it for relative height when it's already impractical to use for absolute heights...?

**Comment by bsongis** [comment]
I tend to agree that we should have auto-offset enabled by default on all altitude fields as today all sensors are relative (or wrong if absolute)

**Comment by kilrah** [comment]
OK, fine for me. In the usual philosophy I just always favor having as little "pretreatment" done as possible unless really necessary, and what the sensor gives should be what I see by default, if I then want it processed then I enable that myself.
Also kind of "forces" users to understand what they're doing and why.
