### ISSUE TITLE
Sounds on 9XR-Pro not working anymore (Release v2.1.1)

### ISSUE THREAD

**Issue by BobMarley100** [opentx/opentx#2695]
Same Problem as in Issue #1690.

**Comment by bsongis** [comment]
Duplicate of #2665 which is already fixed. Please give a try at nightly builds!

**Comment by majkkky** [comment]
Same Problem as in Issue #2665

**Comment by rafabene** [comment]
How can I get access to the nightly builds ?

**Comment by kilrah** [comment]
The link is on the "Links" page of open-tx.org. Download a nightly companion build from there, install, check the "get nightly builds" checkboxes in the settings, download firmware with your options.
