### ISSUE TITLE
high resolution current+consumed capacity data

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#27]
_From [Raine...@gmail.com](https://code.google.com/u/107428441397779591739/) on May 11, 2013 21:07:37_

Enhancment request for openTX with telemetry.

Summary:
TelemetryID to write to cnsp field.
or
TelemetryID to transmit the measured current with a mA resolution

The Problem:
currently the current data being transfered from the sensor to openTX uses a resolution of 0.1amps. the consumed capacity gets calculated from this value making it unusable for low capacity batteries/low current planes.

This is ok for big electric planes with huge batteries, but for small e.g. gliders or micro planes/quadrocopters maybe, this does not provide a usable reslotuion that could be used to calculate the consumed power. with batteries smaller than 1000mAh a resolution of .1A does normally not work at all
Additionally for e.g. DLG gliders i reset the telemetry data quite often using the menu key. (in order to reset flight statistics like Alt+,...) whenever i do this, the TX resets the CNSP field as well, which makes it unusable in this situation.

The Idea:
in the openXvario i implemented a current measuring solution that counts all consumed milliampere in a much higher resolution. the used sensors provides good accuracy at a very small weight. If there would be an ID to transfer this mAh count to the CNSP field in openTX, the field could be used to have a precise overview about the consumed power from the (receiver) battery and to trigger alarms based on the consumed capacity.
Alternativly a methjod could be implemented to write transfer the current in a mA resolution in order to have openTX calculate the mAh in a more precise way.

_Original issue: http://code.google.com/p/opentx/issues/detail?id=27_

**Comment by projectkk2glider** [comment]
Pull #2970 will solve this. The Power box has two sensors for consumption, unit is mAh. It could be used to send the precise consumption data.
