### ISSUE TITLE
Playing two background sounds at once causes sound to stop

### ISSUE THREAD

**Issue by powdermnky007** [opentx/opentx#2704]
i have lots of songs on my radio assigned to different switches.   If i accidentally flip two switches at the same time, both of which are set to play bgmusic, all music stops and if i remember correctly display gets laggy.

My tx is a Taranis (non plus) model.  It's done this for a long time, just never got around to reporting it.

**Comment by projectkk2glider** [comment]
I guess this one affects both 2.0 and 2.1
