### ISSUE TITLE
There could be a way to specify a previous fw version

### ISSUE THREAD

**Issue by rafabene** [opentx/opentx#2705]
I moved recently from 2.0.x to 2.1.1 in my 9xrpro and that broke the sound. I wish to be able to use 2.1.0 in companion.

**Comment by kilrah** [comment]
2.1.0 was broken too.

**Comment by projectkk2glider** [comment]
@rafabene explain more what do you want exactly.

**Comment by rafabene** [comment]
I would like that companion be a able to select previous versions (downgrade) a firmware. This is a feature request!

**Comment by projectkk2glider** [comment]
Not sure the whole firmware compilation server thing would be capable of such an arrangement. I guess it would be too many firmware images to keep. The @bsongis will decide.

Still the long standing recommendation is valid: keep a local backup of the old downloaded firmware versions to use in such cases.

**Comment by fraternl** [comment]
Couldn't the system keep all the once requested flavours in some folder nicely arranged?
It's not exactly what he wants, but could be enough.

**Comment by kilrah** [comment]
No, if we do something about that it should be done in a similar way to nightlies. 
But I'm not for it, or would restrict it to only the previous version, nothing further back. But then we need a way to disable that should the previous version have a serious bug etc, more work and maintenance.
