### ISSUE TITLE
Center beep on setup tab missing for third potentiometer - 9XR

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx#2707]
There is a P1 and a P2, but should also have a P3.  P3 appears in source listings as expected.

**Comment by projectkk2glider** [comment]
More data please, which version, on the radio or in Companion?

**Comment by projectkk2glider** [comment]
9XR does not have P2. The 9XR-PRO does have one and I can see the center beep selector in Companion 2.1.1.

**Comment by powercycle** [comment]
Companion, 2.015.

9XR has three potentiometers, in the mixes tab for a SRC you can see all three, P1, P2, and P3.

In Setup tab, only P1 and P2 are shown.

Center Beep on simulator (and Radio) DOES show the third Pot.

So only seems to be missing on the Setup tab.

**Comment by projectkk2glider** [comment]
Ok, I did not know that 9XR has three pots.

**Comment by powercycle** [comment]
From all the pictures I've seen, the 9X has three as well.

Mike B.

**Comment by bsongis** [comment]
I can't see the bug in current 'master', did someone already fix it?

**Comment by kilrah** [comment]
The bug was tagged wrong, it's an issue only in 2.0!

**Comment by bsongis** [comment]
Ok that's different

**Comment by bsongis** [comment]
No issue in 'master', just fixed in 2.0. I close this issue.
