### ISSUE TITLE
Switch that becomes true when going from 1 switch to another

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2709]
I have asked in the forum how to create a switch that becomes true when I go from 1 switch to another. It didn't get answered
I suspect it can be done with edge, but I'm doing too many things at the same time and have some difficult to understand the possibilities with it. I also suspect it needs to be more than a one-liner.

If so, I would like to propose a switch that becomes true when going, for instance to FM0, but only if the previous cycle was in FM2. 

If this can done with another one-liner I would like to know how and you can close this issue.

**Comment by projectkk2glider** [comment]
Dup of #2708
