### ISSUE TITLE
Throttle trim - Companion Simulator Error

### ISSUE THREAD

**Issue by driver33** [opentx/opentx#2715]
Comapanion v 2.1.2N418.
In simulator throttle trim working as normal trim not throttle trim - only for slow rpm position.

**Comment by pindeslandes** [comment]
I believe it has always been like this. There is a check box here to choose the way the throttle trim works: idle only or full range (sorry, it's in french):
![throttle trim](https://cloud.githubusercontent.com/assets/8396899/9292331/63a24b32-43f2-11e5-92c6-9b76c8dd4d4f.PNG)

**Comment by projectkk2glider** [comment]
Can not reproduce. Provide more data, like which radio, maybe even upload eepe. Yo do realize that throttle trim idle only also affects the whole throttle range, just its effect linearly diminishes with the throttle position.

**Comment by driver33** [comment]
Yeah, My mistake I think. Watching only INPUT with works from -125 to 125 (input (-100-+100) + trim(-25+25)) and didn't check channel output.

Closing this issue.
