### ISSUE TITLE
wish : minus / delta in telemetry calculation

### ISSUE THREAD

**Issue by AndreasAusD** [opentx/opentx#2720]
How can i substract values within the telemetry calculation ?
I can see there is a add function, a multiply, but no minus.

Idea behind that : comparing two values like two different FLVSS and have a logical switch that turns on if the difference exceeds a certain value

Thanks
Andreas

**Comment by kilrah** [comment]
You can select "-value" in the fields of the Add function...

**Comment by AndreasAusD** [comment]
ah ok, I didn't see that
