### ISSUE TITLE
Why does Edge have no delay?

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2731]
I noticed that the column "Delay" has N/A when Edge is chosen.
N/A could stand for "Not Available" or "Not Applicable"

Is it left out because it gave problems with implementing it? Maybe not enough room for that option?
Or was it considered not applicable?

I'm not asking for it, really.
I just started to use "Edge" to be honest, merely wondering...

**Comment by pindeslandes** [comment]
I think #1547 answers your question.
