### ISSUE TITLE
[Companion 2.1.1] Companion crashed when using "Compare Models"

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2734]
Step to reproduce the problem:
1- Download the EEPE <a href="http://1drv.ms/1JhF1QV">nano-cpx_LapinFou.eepe</a>
2- Drag and drop the same NANO_CPX model on the right and left side.
3- Companion has crashed.
Environment: Windows 7 Pro 64 bits.

**Comment by projectkk2glider** [comment]
Which radio is selected in the radio profile?

**Comment by LapinFou** [comment]
Taranis Plus
![seeting](https://cloud.githubusercontent.com/assets/1685030/9363700/343657b8-46a8-11e5-8212-efd65023b2d4.jpg)

**Comment by fraternl** [comment]
What I was hoping for came true....
This change now fixed the curves....
They are now showing

**Comment by LapinFou** [comment]
Nice !!
:)

**Comment by fraternl** [comment]
BTW... it's only partially fixed...

**Comment by projectkk2glider** [comment]
>BTW... it's only partially fixed...

What do you mean? Are you still having problems, details please.
