### ISSUE TITLE
Print model gives large integer when "Play value.... not on startup" is chosen

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2736]
In print model I'm now seeing a large integer when I have a "play value... not during startup" chosen in Special Functions.
It does the same on "Play Track" (to be expected)

Must be some recent change as I never saw this before.
I'm on today's nightly 

![print model](https://cloud.githubusercontent.com/assets/8692856/9378527/81afd8f0-4722-11e5-801d-d145e714a19a.PNG)
![sf](https://cloud.githubusercontent.com/assets/8692856/9378532/8a7c91bc-4722-11e5-9649-7f5fbc3c763e.PNG)

**Comment by projectkk2glider** [comment]
Well the  "play value... not during startup" is in really a really big number, but should be shown more user friendly. We will fix it,thanks for reporting.
