### ISSUE TITLE
Wish: Separate curve graphs in "Print Model" and "Compare Models"

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2737]
In "Print model" and "Compare models" all the curve graphs are merged together in 1 image.
These overlapping curves soon become unreadable if more than 2 are shown

It would be nice to have a graph for each curve

![curves-overlap](https://cloud.githubusercontent.com/assets/8692856/9379020/917ec5bc-4726-11e5-9cd1-ac845536b095.PNG)

**Comment by bsongis** [comment]
Please nobody works on Compare and PrintDialog, I am on it

**Comment by projectkk2glider** [comment]
Here are related issues to this one:
*  Companion print model and compare model has receiver number missing #2576 
*  [OpenTX2.1] [Companion] Compare Models #1862 
*  Companion Print model needed enhancements #1063
