### ISSUE TITLE
[Enhancement] Random generator

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2739]
Hi folks,

I saw a nice B17 video, where the guy created a random generator on his Spektrum DX18 using 2 mixes. He is using it, to randomly move the gun turrets on his plane.
Could be a nice feature for people flying with scale models.
Ideally a special input which creates some random number but where the user can choose the boundaries and the refresh rate.
:)

Source: http://www.rcgroups.com/forums/showthread.php?t=2483520

**Comment by fraternl** [comment]
We can't let them have a feature that's not in OpenTX, can we?   ;-)

**Comment by kilrah** [comment]
That would be the perfect job for a Lua script.

**Comment by LapinFou** [comment]
@fraternl : Absolutely ! We can't... ;-)
@kilrah : Yes, but I didn't see a random  function in LUA (I checked before opening a ticket).

**Comment by kilrah** [comment]
Isn't there a math.random()?

**Comment by LapinFou** [comment]
My mistake, I checked the OpenTX doc, but forgot to check the official LUA libs...  :-/
Well, I guess this ticket can be closed.

**Comment by mhotar** [comment]
It could be nice feature to have special function that can set Gvar to random value. I think it is more valuable to have it in the base function set.

**Comment by kilrah** [comment]
I would think any use of this would need a bit more processing to be really useful...

**Comment by mhotar** [comment]
It could be processed through standard mixer path.
