### ISSUE TITLE
Taranis don't say the good unit of value (in french)

### ISSUE THREAD

**Issue by nicolas81** [opentx/opentx#2742]
Hi,
I have a Taranis with 2.1.1 firmware. When i ask the taranis to read a value (like Alt or Vspeed) she don't use the right unit (in french). 
She says "mA" instead of "m".
She says "km/h" instead of "m/s".
etc.

**Comment by projectkk2glider** [comment]
Are you using the new sound pack for 2.1? If not than that is your problem.

**Comment by nicolas81** [comment]
Sorry.
I have solved the issue when i made the update to Sounds Pack for openTX 2.1..

**Comment by nicolas81** [comment]
I have noticed that the sentences in the  file of the french sound pack 2.1 named "french-taranis.csv" don't correspond to the sound but the sound in taranis seems ok.
