### ISSUE TITLE
SetFailsfe action in special functions not in companion.

### ISSUE THREAD

**Issue by Mow06** [opentx/opentx#2753]
the "SetFailsfe" action in special functions is available on the radio but not in companion.

When an is eepe with that function set is read from the radio the function is lost.

**Comment by projectkk2glider** [comment]
Confirmed, all missing functions are:
```
  FUNC_SET_FAILSAFE,
  FUNC_RANGECHECK,
  FUNC_BIND,
  FUNC_PLAY_DIFF
```

What is FUNC_PLAY_DIFF anyway?
