### ISSUE TITLE
Trim to subtrim  not ok at Ch1  the others Ch2, Ch3, Ch4 is ok  openTx V2.1.2 N417    at X9E

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2755]
hy,
Test:
Set all 4 trims to max 125
go to servomenü
then kopie trim to subtrim
you can see subtrim setting  (servomid)
CH1  100  not ok, should 125 too
CH2  125  ok
CH3  125  ok
CH4  125  ok

**Comment by kilrah** [comment]
Can't reproduce, please detail exact starting conditions and settings.

There is no way trim.>subtrim should ever exceed 100% with "normal" settings so the issue as presented makes no sense.
