### ISSUE TITLE
Logical switch with calculated sensor not working properly

### ISSUE THREAD

**Issue by lichtl** [opentx/opentx#2756]
Model: Taranis X9E
Firmware: opentx-taranisx9e-timer3-noheli-lua-mixersmon-ppmus-en-2.1.2N427.bin

I'm using a calculated Sensor to report the lowest cell (coming from my Cleanflight Naze). For reporting I want to use a logical switch using a<x which don't seem to work (L2 active all the time).

I've tried multiple settings and L2 only deactivate once I set x to 0 or into negative. Please let me know if you need any more data

![img_20150823_234303](https://cloud.githubusercontent.com/assets/1228155/9430452/a0b50e38-49f6-11e5-93df-b2bc00e98943.jpg)
![img_20150823_234333](https://cloud.githubusercontent.com/assets/1228155/9430453/a0bd142a-49f6-11e5-9eb5-6d17ea08a70d.jpg)
![img_20150823_234444](https://cloud.githubusercontent.com/assets/1228155/9430454/a0bfadb6-49f6-11e5-8985-c29c7ca0b617.jpg)
![img_20150824_001435](https://cloud.githubusercontent.com/assets/1228155/9430455/a0bfe682-49f6-11e5-8c8f-3e9284bb3593.jpg)

Config file. Please rename to config.eepe
![config eepe](https://cloud.githubusercontent.com/assets/1228155/9430464/e672ad36-49f6-11e5-97b8-d485088b1496.jpg)

**Comment by kilrah** [comment]
Did you create the "Cell" sensor on the radio or in companion? Was it done right now or does it date back some time? At some point there was a bug where a property wasn't set correctly.

**Comment by lichtl** [comment]
I've created the "Cell" sensor at the radio and the testing was done at the time I've created this issue (The picture mention N425 but I've also tested with reflashed N427 )

**Comment by lichtl** [comment]
Just another question. Is there a function to report the number of cells back? I've just rechecked on Companion but it don't seem to report back the number of total cells. (can split this also into a different issue/feature request)

**Comment by AndreasAusD** [comment]
I have a similar problem : two voltage sensors, one FLVSS giving me a total voltage "FLVS" and a JLog 2.6 connected to a Kontronik Jive giving me a total Voltage "Vfas" 

Calculated sensor "diff" which adds "FLVS" and "-Vfas and a logical switch on "|a|>x" which never changes, no matter what value x has

Values differ by -0,07V and 0,03V when both connected and go up to 15V when only the FLVSS is connected to the battery

Tested on a 9xD with the release version of 2.1.1, no nightly build
all configuration done on the radio

**Comment by joehallenbeck** [comment]
That's definitly the same problem I discovered. Try to relocate the telemetry sensor to a slot greater than or equal to 16. It should work properly then.

**Comment by joehallenbeck** [comment]
![telem4](https://cloud.githubusercontent.com/assets/13510399/9526758/886d3038-4ceb-11e5-9b0b-3f9f4d492b5c.png)
This is my current working configuration.

**Comment by kilrah** [comment]
Closing that one, #2787 has more detailed info.

**Comment by AndreasAusD** [comment]
just tested it, diff on sensor 14 works, copied to sensor 25 does not work...
glad you found that bug
