### ISSUE TITLE
Telemetrie column deleted with sensor

### ISSUE THREAD

**Issue by floaaaaargh** [opentx/opentx#2764]
Hi, 
if a telemetrie sensor assingned to a column in the telemetrie screen is deleted, the coulumn isn't acsessable anymore. So you cannot assign annother sensor or a blank field to this particular column. 

I had to restore the deleted sensor and the column was acssessable again and could be assined to another sensor.

**Comment by projectkk2glider** [comment]
Which version, Companion or radio?

**Comment by kilrah** [comment]
It's normal to have "holes" when deleting sensors. The slot will be reused next time a sensor is detected or you create one.
