### ISSUE TITLE
9XR-PRO doesn't shutdown

### ISSUE THREAD

**Issue by MikeBland** [opentx/opentx#2779]
When using th original FLYSKY module in a 9XR-PRO, you cannot shutdown the radio without disconnecting the battery. This is due to the PPM output voltage leaking back through the module power pin and holding the radio power on.
Solution: Allow the PPM output to be configured as Open Drain, then there is no positive voltage sent to the module. This needs to be a model option as some other modules don't work with an open drain output.
This option is in ersky9x so the code is available.

**Comment by kilrah** [comment]
I believe it was added in 2.1.
