### ISSUE TITLE
Lua getValue() not working for special telemetry values

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2780]
The #2773 reminded me that we are missing a way for Lua to get the values of all *special* telemetry sensors. That pull fixes the case for GPS coordinates. But other sensors types like cells and datetime also need this special handling. 

Also related to the request to have all individual cell voltages avalilable in Lua #1799

**Comment by dsbeach** [comment]
I might be in a position to take this on.  Is there a list of 'special'
sensors, or should I just find all the enumeration values for
TelemetrySensor.unit?

**Comment by projectkk2glider** [comment]
>should I just find all the enumeration values for TelemetrySensor.unit?

Yes that is the right path. I would also like to change the flow of `luaGetValueAndPush()`: there is no need to call `getValue(src)` for these special telemetry values. It might as well be done along with this issue.

**Comment by dsbeach** [comment]
Should be closed by #2826
