### ISSUE TITLE
companion - telemetry tab bigger than screen

### ISSUE THREAD

**Issue by dk7xe** [opentx/opentx#2781]
Since companion 2.1.0 i have issues with the telemetry tab having the slider outside the visible screen (EeePC1201N with 1366x768 resolution).
To move the slider on the right hand window side for scrolling i need to move the complete window to the left. This moves the sensor name out of the visible area. Therefore it's hard to predict on which line i'm currently working.

Request is to change the window behavior in case of window size > screen size to a way that the fields outside the visible range are moved to a 2nd line. This enables to have all fields visible on the screen and avoids wrong setting.

Issue is since companion 2.1.0
current version used: companion 2.1.1
system: openSuse 12.3_64 on EeePC1201N - 1366x768 resolution

Thank you, Gerald

![screenshot - 08262015 - 04 48 47 pm](https://cloud.githubusercontent.com/assets/3907200/9512759/13ac7f6a-4c87-11e5-8a1a-09b594906be0.png)
 ![screenshot - 08252015 - 04 55 18 am](https://cloud.githubusercontent.com/assets/3907200/9512758/13ab37a4-4c87-11e5-81eb-a8acdeb3933c.png)

**Comment by projectkk2glider** [comment]
Telemetry items need their own sub dialogs, like mixes.
