### ISSUE TITLE
Companion 2.1.1

### ISSUE THREAD

**Issue by TaranisHarry001** [opentx/opentx#2786]
Hallo,

habe auf meiner Taranis 2.1.1 gespielt und auch die dazugehörige Companion 2.1.1 auf dem PC installiert. Mir ist beim Upload vom Sender zu dem PC aufgefallen, dass das HF-Modul immer deaktiveirt wird. Ändere ich diese Einstellung unter Companion und schreibe dann diese in die Taranis und lese ich diese wieder zurück, dann ist alles ok.

Gruß
Harry

**Comment by projectkk2glider** [comment]
@TaranisHarry001 please use English languge.

Translation (from google):

>have played on my Taranis 2.1.1 and also the accompanying Companion 2.1.1 installed on the PC. I noticed when uploading from the transmitter to the PC that the RF module is always deaktiveirt. I change this setting under Companion and then write them into the Taranis and I read this back, then everything is ok.
