### ISSUE TITLE
Telemetry sensors > #16 not usable as logical switch

### ISSUE THREAD

**Issue by joehallenbeck** [opentx/opentx#2787]
Logical switches do not accept telemetry sensors greater than #16.

I'm developing my own minimOSD firmware, sending back a lot of telemetry data. Currently I'm using 24 of the available 32 telemetry slots. I discovered that only the first 16 telemetry slots are usable as logical switch. After I relocated all important sensors everything works fine.

Steps to reproduce:
1. Assign a sensor to a telemetry slot > 16.
2. Use this sensor as parameter of  a logical switch
3. Upload the config to Taranis
4. Download the config
5. The sensor is shown as something like "[I]Ail"  in logical switch config

**Comment by kilrah** [comment]
Is that only a problem when programming and transferring to the radio from companion? Does it work when set up on the radio only?

**Comment by joehallenbeck** [comment]
No. It makes no difference wether setting it up on Companion or the Taranis itself. I figured out the problem by trial and error. Logical switches using telemetry sensors over slot 16 doesn't work properly.

**Comment by joehallenbeck** [comment]
I'm not a native english speaker, sorry for that. But I can provide screenshots or a video describing the problem. It's not grave, but I thought it might be something you should know.

**Comment by kilrah** [comment]
OK, most likely explains #2756

**Comment by joehallenbeck** [comment]
I forgot: I'm using OpenTX 2.1 on a FrSky Taranis Plus.

**Comment by kilrah** [comment]
Bleh. LS evaluation fails when cs->v1 > 255, I found a place that would definitely cause it, but it still fails after fixing. Can't seem to find another similar mistake in the data path.

**Comment by kilrah** [comment]
Addendum, as described companion also breaks on import/export of values >255.

**Comment by kilrah** [comment]
2nd one was hiding, thanks @bsongis !

**Comment by joehallenbeck** [comment]
Thanks for fixing this so fast.
