### ISSUE TITLE
RF module state from the upload disabled

### ISSUE THREAD

**Issue by TaranisHarry001** [opentx/opentx#2788]
Hello,
have played on my Taranis 2.1.1 and also the accompanying Companion 2.1.1 installed on the PC. I noticed when uploading from the transmitter to the PC that the RF module is always deaktiveirt. I change this setting under Companion and then write them into the Taranis and I read this back, then everything is ok.

Harry

**Comment by bsongis** [comment]
I think you installed a beta OpenTX 2.1.0 and your model were converted there, right?

**Comment by TaranisHarry001** [comment]
Hello,

first, i have installed the beta opentx 2.1.0 and then i have flashed the version opentx 2.1.1 and compansion 2.1.1 on my pc.

Von meinem iPad gesendet

**Comment by bsongis** [comment]
Ok then it's normal, the bug was an import bug in the first opentx 2.1.0 beta versions. Not a huge issue, but you have to fix your module settings on Companion as you do and everything will go fine after.

**Comment by TaranisHarry001** [comment]
perfect. thanks. good night.

Von meinem iPad gesendet

**Comment by kilrah** [comment]
No, it's still a problem right now!

**Comment by bsongis** [comment]
The eeprom was also badly converted in a previous 2.1.0 beta version. I could fix it, but Companion would be unusable for those who have the internal module hack (they have PPM sent on the internal module instead of PXX)
