### ISSUE TITLE
FrSky Horus X12D 

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#2791]
Will it be possible for those of us the follow the development of OpenTX to know when FrSky makes the Horus X12D available to the development team for the OpenTX porting?

Thanks,

Mike

**Comment by kilrah** [comment]
You'll see in the commit descriptions when something happens.

**Comment by bsongis** [comment]
I will find a way to communicate and send screenshots, but not here!

**Comment by MIKE-DAILEY** [comment]
Thanks, I’m hoping to make the X12D my next radio but only if it is running OpenTX.  I have my lunch money saved up to buy it already.
