### ISSUE TITLE
V2.1 telemetry calculated sensors: extend ‘Multiply’ to 4 sources…

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#2795]
…as it is for Add, Average, Min, Max.

**Comment by kilrah** [comment]
Limited on purpose because of the risk of overflow. Numbers can quickly get big with PREC2.

**Comment by pindeslandes** [comment]
Isn’t that limitation just an illusion?
Because if I need to multiply four sources, I will anyway. I will have to use three calculated sensors instead of only one but I will. And nothing will prevent me to get an overflow as well.
