### ISSUE TITLE
V2.1 telemetry: ‘PREC0’, ‘PREC1’, ‘PREC2’ may be more explicit

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#2796]
Like:  **000.**  -  **00.0**  -  **0.00**

Cosmetic, of course, but it would help people to figure out things (and would work for any language).

**Comment by fraternl** [comment]
It is that way in my translation...
Not my idea, though. I adopted it from the German one.

**Comment by griebd** [comment]
+1

**Comment by bsongis** [comment]
I am OK with this idea
Le 28 août 2015 2:57 PM, "Adriano Grieb" <notifications@github.com> a
écrit :

**Comment by kilrah** [comment]
Will do, I still have an editor open with the translations files...
