### ISSUE TITLE
Updated nl.h.txt

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2798]
In special functios the "reset ..." was using text it got from totally somewhere else.
My translation of "Telemetry" into "Telemetrie" messed up the string that was used as an array.

http://hmvc.eu/nl.h.txt

Since this recently discovered issue with jitter was solved I suspect a release of 2.1.2
I hope to get this in on time.

**Comment by projectkk2glider** [comment]
I am on it.

**Comment by projectkk2glider** [comment]
This does not look right to me. The length is 10 characters:
```
#define LEN_VFSWRESET          TR("\004", "\012")
```

But you now you translated it to 9 chars long:
```
  #define TR_FSW_RESET_TELEM   TR("Telm", "Telemetry")
```

The error must be somewhere else.

**Comment by fraternl** [comment]
Sorry... missed that....

But the part where it goes wrong is exactly the same as the english counterpart...
I don't think it's something wrong with the firmware itself.
Must still be something in my nl.h.txt   
I will look at it this evening..  have to work now

**Comment by projectkk2glider** [comment]
I've found it, other strings were too short. Fix coming.

**Comment by fraternl** [comment]
Ah... thanks....
Yours is better...
