### ISSUE TITLE
Von 2.0.17 nach 2.1.1

### ISSUE THREAD

**Issue by frobert0** [opentx/opentx#2800]
Nach Update und EEProm Konvertierung ist der Timer1 Schalter von !SG^ in !FM8 geändert worden.

In Mischer und anderen Teilen wo !SG^ verwendet worden ist hat es funktioniert.

Wieso ist bei der X9D mit 2.1.1 Timer3 im Sender nicht vorhanden und in Companion 2.1.1 schon

**Comment by kilrah** [comment]
Conversion done on the radio or in companion?

To have timer 3 on the radio you need the "timer3" firmware option.

**Comment by frobert0** [comment]
Conversion in Radio von 2.0.15 to 2.1.1

Firmware 2.1.1 in Radio

???? !SG^ to !FM8




Am 28.08.2015 um 10:36 schrieb Andre Bernet:
> Conversion done on the radio or in companion?
> 
> To have timer 3 on the radio you need the "timer3" firmware option.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opentx/opentx/issues/2800#issuecomment-135680432>.
> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by kilrah** [comment]
Hmm for me on a conversion from 2.0.17 to 2.1.1 I get !SG^ -> !SFv. No !FM8.
