### ISSUE TITLE
Logical Functions: Timer - Firmware: 2.1.x

### ISSUE THREAD

**Issue by rafabene** [opentx/opentx#2805]
On Companion I set the values 1 for both V1 and V2 on the Timer for Logical Functions.

But when I open the firmware on the simulator and go to Logical Function screen the value is negative.

If I edit it, it gets automatically corrected to positive values. 

If i set the value 90 for V1 or V2  on Companion it shows as 38 on the firmware execution.

**Comment by kilrah** [comment]
Can't reproduce. What radio type and exact companion/firmware version?

**Comment by rafabene** [comment]
It happens with 9XRPRO. Companion and Firmware 2.1.2N
