### ISSUE TITLE
Telemetry screen: Firmware 2.1.x

### ISSUE THREAD

**Issue by rafabene** [opentx/opentx#2806]
In companion I can set more than one Telemetry screen, but when I'm execution the firmware it shows only one screen.

**Comment by kilrah** [comment]
Can't reproduce. What radio type? What screen type? What exact version? Please detail your issues.

**Comment by rafabene** [comment]
It's a 9xrPRO with 2.1.2N

**Comment by bsongis** [comment]
First there is a problem in menu navigation when there are hidden items!

**Comment by bsongis** [comment]
Would you be able to test my fix tomorrow on the nightly build and tell me if it is better?

**Comment by rafabene** [comment]
@bsongis Who was this question for ?

**Comment by bsongis** [comment]
For you :)

**Comment by rafabene** [comment]
I can test it. I'll will do it today at night.

**Comment by bsongis** [comment]
Thanks!

**Comment by rafabene** [comment]
I should try today again together with #2824​

**Comment by rafabene** [comment]
I tested N440 and 9xrPRO still showing just one telemetry screen

**Comment by bsongis** [comment]
I just tested, no problem on my 9XR-PRO
Do you see your screens in the Telemetry screen (Model menu)?
Do you press [Down] to switch between all those telemetry screens?

**Comment by rafabene** [comment]
In my Telemetry screen (Model menu) I have two screens configured but when I press [Down] to switch between those telemetry screens, I can see just the first one. I tried it with different models

**Comment by bsongis** [comment]
I tested with numbers, perhaps you have bars on one screen? Is it the same if you create your screens on the radio. Just to know if it is a Companion or a firmware bug ...

**Comment by bsongis** [comment]
Would you send me your eeprom (export from Companion). I can't reproduce.

**Comment by kilrah** [comment]
Can't reproduce either.

**Comment by rafabene** [comment]
You can get it here: https://www.dropbox.com/s/6b8xl9jon8f5pkg/Modelos%202.1.bin?dl=0

**Comment by kilrah** [comment]
Your 2nd screen has bars configured with a source but with no range (From 0 to 0). That is equivalent to nothing, so it is skipped.
