### ISSUE TITLE
Companion print model mixes

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2808]
On the radio multiply is presented as *=, add as += and replace as := 

It would be nice if it's the same in Print model

I just used "print model" to post it on rcgroups and it takes a lot of editing to make it easy readable (not only this)
http://www.rcgroups.com/forums/showpost.php?p=32550041&postcount=347

**Comment by projectkk2glider** [comment]
Just a small warning: the same representation is also used in mixes/inputs setup screen. So the change would affect both.

**Comment by projectkk2glider** [comment]
I can't decide if I like the change or not:

![new](https://cloud.githubusercontent.com/assets/5950438/9569071/993ed734-4f5e-11e5-90d0-6d8c1734c012.png)

Lets see what other have to say @bsongis @kilrah.

**Comment by bsongis** [comment]
Yes, it seems good to me!

2015-08-30 21:33 GMT+02:00 Damjan Adamic <notifications@github.com>:

**Comment by projectkk2glider** [comment]
Ok, I will push to master then.
