### ISSUE TITLE
Companion conversion issue

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#2809]
somwhere I found some servo tester epee so I try to test it. 
At Companion 2.0.17 and working

![image](https://cloud.githubusercontent.com/assets/2682800/9566137/332abfb0-4ef7-11e5-860f-fa2f3d93813b.png)

![image](https://cloud.githubusercontent.com/assets/2682800/9566139/419db17e-4ef7-11e5-838d-40a3b0c57888.png)

![image](https://cloud.githubusercontent.com/assets/2682800/9566140/4b153bdc-4ef7-11e5-96ff-a1a045838aea.png)

But opening at 2.1.1N434 

![image](https://cloud.githubusercontent.com/assets/2682800/9566142/72b29ab8-4ef7-11e5-9b81-0a001697b5f4.png)

![image](https://cloud.githubusercontent.com/assets/2682800/9566143/7c8407ac-4ef7-11e5-9c1e-66b6db6e73d1.png)

![image](https://cloud.githubusercontent.com/assets/2682800/9566144/86e07118-4ef7-11e5-9d4e-f82a23609b3b.png)

As you can see the channels change from Ch24 to CH23 ate mixers, from MAX to S1, other chanenels change numbers too and at logical switches GV1 change to CH32. 
Can be the issue from how does loading progress and filling the values some channels or GV are not usable? interesting MAX there should not be any reason to change.

**Comment by kilrah** [comment]
To do together with #2788

**Comment by bsongis** [comment]
Would it be possible to have your eepe file?

**Comment by bsongis** [comment]
This is not related to #2788 as I am almost sure it's a conversion issue from OpenTX eeprom < 2.0

**Comment by janekx** [comment]
Will upload it as soon as will be close to pc

**Comment by bsongis** [comment]
Would you send it by email?

**Comment by janekx** [comment]
Yes will send  it by email to you as will be close to PC if not possible to commit it here.

**Comment by janekx** [comment]
Confirming that now it translate well. Thanks
