### ISSUE TITLE
Anomaly in Dutch Translation

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2811]
Somehow a few (too many) spaces slipped through.
I also needed a lesser translation for "Smooth" because "Afronden" was 1 letter too many and went into the checkbox.

http://hmvc.eu/nl.h.txt

There are no strange characters anymore, BTW???

Dutch is really hard to do with many words that are much longer than English ones
Only our "yes" is shorter

**Comment by projectkk2glider** [comment]
>There are no strange characters anymore, BTW???

The delta character is still not correct in your file, but I am used to it now :wink:
