### ISSUE TITLE
Proposal: Companion sync SD should be two way. 

### ISSUE THREAD

**Issue by rafabene** [opentx/opentx#2824]

**Comment by projectkk2glider** [comment]
Related to #2743

**Comment by projectkk2glider** [comment]
I looked at the sources and looks like it should be two way. What exactly is your problem?

**Comment by rafabene** [comment]
The Backup and logs from my sdcard wasn't copied to my computer.

**Comment by projectkk2glider** [comment]
@bsongis just one comment. The modification time of a file/directory precision and existence depends on the underlying file-system. If I remember correctly some file-systems have only 2 second resolution, other store file time in UTC. This might be the cause of some issues, but probably not this particular one.

**Comment by bsongis** [comment]
If it's true for the backup and logs file, probably no, I will do a check myself later

**Comment by rafabene** [comment]
I checked and it's working.. Sorry!

Closing this issue...
