### ISSUE TITLE
MEGA 2560 audio output not working

### ISSUE THREAD

**Issue by tmrttmrt** [opentx/opentx#2825]
No audio on Arduino pin 6. 

Found some bugs in code. Also, since 16 bit timers behave differently than 8-bit timer configuration has to be updated. 

Proposed solution will be published soon.

**Comment by projectkk2glider** [comment]
Just a reminder, work in `master` branch.

**Comment by kilrah** [comment]
Was merged in https://github.com/opentx/opentx/pull/2829
