### ISSUE TITLE
Improve model selection on compare model dialog

### ISSUE THREAD

**Issue by rafabene** [opentx/opentx#2830]
I tried this feature today for the first time with 2.1.2N440 version and it's not working on Windows. The mouse drag and drop doesn't populate any model on the comparing window.

**Comment by projectkk2glider** [comment]
Are you sure you dragged the model onto the text and not in a window? As soon as model is dragged correctly the text should change to the name of the dropped model.

**Comment by fraternl** [comment]
I'm using this feature quite often.
Just tested if it still works on 2.1.2N440 and it works.
If he never used it before it's quite certain a user error

**Comment by kilrah** [comment]
To be fair that way of dragging has never been very intuitive. Could be worth using a more straightforward UI mechanism, e.g. 2 dropdowns that both have the list of models present in the file...

**Comment by kilrah** [comment]
Confirmed it works as it always has, edited issue title to reflect what the actual problem is...

**Comment by rafabene** [comment]
I can confirm now. It works dragging on the text but it's not intuitive since my first reaction was to send it to the window.

**Comment by mpaperno** [comment]
Fixed with #4769 (can now drop anywhere in the window).
