### ISSUE TITLE
X9E switches numbers in firmware 

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#2833]
Would be nice to change firmware switches and sliders marking same as are on the X9E case.  
X9E have switches marked by nubers and not letters.

**Comment by kilrah** [comment]
They're labelled with letters on the PCB.

**Comment by janekx** [comment]
Yes i know but users see numbers,  its confusing them.

**Comment by kilrah** [comment]
Tell that to FrSky... There's no way we can really solve this. 
Users can rename all controls if they want though.

**Comment by janekx** [comment]
You right, there is many possible combinations. Maybe make some compilation option to show letters or numbers
