### ISSUE TITLE
Edge representation is different in print model / OpenTX University / Companion Setup

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#2837]
When I look at Edge in Companion the setup page, Companion print model, the radio itself and the explanation on http://open-txu.org/home/continuing-education/logical-switch-functions/ 

I will get different terminology for what is called "instant" on OpenTX university.
In "print model" this is -0.1
IMHO this should be "<<"

It is true I'm not that familiar with Edge.
In this case the explanation on OpenTX university becomes confusing.

Where OpenTX-U speaks of "instant" it is "no release)"  without the opening brace in Companion

**Comment by fraternl** [comment]
I made some screenshots giving the 4 representation of the same logical switch
I don't like the "no release)" in Companion 2.1. Maybe it's just me.
It seems to be changed as OpenTX University is giving "instant" for this value.


It would be nice if the "<<" would appear on "print model"
I think it's now giving the value it has internally.


Edge on Print model

![edge_c print model](https://cloud.githubusercontent.com/assets/8692856/9703416/9540508e-5483-11e5-88a2-87f9a8d6f32c.png)

Edge on Companion 2.1   no release)

![edge_c 2 1](https://cloud.githubusercontent.com/assets/8692856/9703418/97c9e7ca-5483-11e5-9f13-8d40034bff7a.png)

Edge on Radio

![edge_t](https://cloud.githubusercontent.com/assets/8692856/9703423/b84ec9d4-5483-11e5-8261-609ac234d599.jpg)


Edge on Companion (OpenTX  University)

![edge_c](https://cloud.githubusercontent.com/assets/8692856/9703424/bb85e150-5483-11e5-9969-044a44890ed2.jpg)

**Comment by vieuxdruide** [comment]
hi :-) i charged this morning the new open tx 2.1.2
and in companion in french langage 
in the mixages screen the ratio is in english "weight"
![capture d ecran 2015-09-08 08 40 09](https://cloud.githubusercontent.com/assets/11027091/9728059/b267bbba-5605-11e5-84ac-29b295a079e4.png)
![capture d ecran 2015-09-08 08 40 53](https://cloud.githubusercontent.com/assets/11027091/9728083/d647a96e-5605-11e5-99d5-c626fdf6be00.png)

**Comment by bsongis** [comment]
What do we choose? instant everywhere in companion, while we keep << in the firmware as "instant" won't fit?

**Comment by kilrah** [comment]
>  instant everywhere in companion, while we keep << in the firmware as "instant" won't fit?

That seems good.

**Comment by fraternl** [comment]
We still have 3 representations of Edge
I prefer to have them all the same.

Companion
L2  Edge   SE↓   [0:0(infinite)]
Print Model:
L2  Edge(SE↓, [0:0])
Radio
L2  Edge [0.0:--]

**Comment by projectkk2glider** [comment]
I agree, the companion will be changed to show the same as the radio (perhaps with the word explanation included for easier usage).

**Comment by bsongis** [comment]
I am not sure it's easy to change this 0 in Qt! It easier to change it in
the radio, but -- is better than 0. Difficult choice...

**Comment by fraternl** [comment]
Replace (infinite) with --- in companion
Print model the same as the radio.

Would that work?

**Comment by bsongis** [comment]
Not sure it's easy to do in Companion!

2016-01-09 19:59 GMT+01:00 fraternl <notifications@github.com>:

**Comment by fraternl** [comment]
I don't mean the zero as that seems to be your problem, but if the word "infinite" with the parentheses is replaced by the 3 dashes it would be almost the same as the radio

Albeit with a 0.0 in front with it....

A simple search and replace....  Not?

**Comment by bsongis** [comment]
Yes 0 --- is OK, but is it easy to understand?

**Comment by jtaylor2** [comment]
No it's not easier to understand.  I'm not sure why there is a request to make them all the same if it means making Companion less understandable.  The radio does not have the resources or screen space to make everything easy to understand, but Companion does so I don't see where dumbing down Companion just to match the radio is an improvement.

**Comment by fraternl** [comment]
It is (almost) the same as in the radio, which IMHO is more important than
an extra word which in itself still doesn't explain the behaviour.

Personally I try a lot of things to find out exactly how it behaves and
after I find out I use this knowledge to solve real-world problems.
Op 10 jan. 2016 12:51 p.m. schreef "Bertrand Songis" <
notifications@github.com>:

**Comment by fraternl** [comment]
In the nightly I downloaded today I can't see the "<<" in companion when I do a "print model"
Nor does the "<<" come back in the editing screen of logical switches.

This is because it's not merged yet????
Sorry, I still have no dev platform

**Comment by projectkk2glider** [comment]
Correct, it is not merged, I have some ideas that still need to be implemented before we merge.
