### ISSUE TITLE
Simulator/Taranis 2.1.1: In Telemetry screen 13/13, the extended list of choice (Long ENT) doesn't work in menu "bars".

### ISSUE THREAD

**Issue by fred99** [opentx/opentx#2843]
![screenshot-1](https://cloud.githubusercontent.com/assets/12371235/9708294/ff064122-5519-11e5-8ea4-cba81e9efe1f.png)

A long ENT on ---- doesn't show the extented list of choice:
![capture2](https://cloud.githubusercontent.com/assets/12371235/9708323/398e6b1c-551a-11e5-8ea2-0ab8510ddf46.JPG)

**Comment by kilrah** [comment]
More details, it's only on "Bars" that it doesn't work.
On Nums it's OK, albeit requires you to be in edit mode before you long press.

**Comment by fred99** [comment]
You are right, it's only on bars in the simulator and in the Taranis V2.1.1, no problem with nums or script.
I was in edit mode (blinking) and able to select the input using + and - buttons so it's a small problem.
Long Ent is so nice so it's immediatly adopted !
My title/qualification is not accurate.
