### ISSUE TITLE
Companion: Translations not working in ModelPrinter::printMixerLine()

### ISSUE THREAD

**Issue by vieuxdruide** [opentx/opentx#2847]
hi i charged the new open tx 2.1.2 this morning
and when i opened companion (in french)in the mixages screen the ratio is in english weight
![capture d ecran 2015-09-08 08 40 09](https://cloud.githubusercontent.com/assets/11027091/9728789/b79d44b0-560a-11e5-8507-8adce44ed3a5.png)
![capture d ecran 2015-09-08 08 40 53](https://cloud.githubusercontent.com/assets/11027091/9728791/be9682d6-560a-11e5-92d6-5a77412f736b.png)
thanks :-)

**Comment by kilrah** [comment]
Actually nearly everything in compare model/print model also comes out untranslated, although translations files are up to date and complete.

**Comment by vieuxdruide** [comment]
salut Kilrah excuses moi mais je n'ai pas bien compris la réponse :-( désolé mais mon anglais est bien pauvre
merci

**Comment by kilrah** [comment]
J'ai simplement complété la description avec quelques infos supplémentaires pour quiconque va s'y atteler.

**Comment by vieuxdruide** [comment]
ok en fait c'est l'ensemble de la page mixage qui est en anglais :-)
je viens de voir ça.
