### ISSUE TITLE
Pots don’t reset inactivity Timer

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#2857]
Taranis – OpenTx 2.0.17

If you touch only pots, the radio seems to interpret that as inactivity and ends up by triggering the inactivity alarm.

**Comment by projectkk2glider** [comment]
True, the inactivity is only reset by the:
* moving sticks
* or moving switches

The pots are not checked. Ti would be a waste of resources to add pot movement check. You do after all fly your model with sticks.

**Comment by pindeslandes** [comment]
Well, as a matter of fact, I do fly one special model without ever touching any stick (it’s a servo tester).
