### ISSUE TITLE
Voice alerts only 0 decimal places accuracy

### ISSUE THREAD

**Issue by ecob81** [opentx/opentx#2860]
I loaded 2.1.3 and the voice alert accuracy has gone down to 0 decimal places and no longer plays "two point one volts" but instead just says 2 volts.

**Comment by kilrah** [comment]
You need to update your voice files to 2.1 too.

**Comment by ecob81** [comment]
Thanks Kilrah, Sorry for not realising that. I really appreciate all the work that you all put in on here it's fantastic and this software is amazing i'm loving it! Can't wait to see where it goes in the future.
