### ISSUE TITLE
Companion: let the LSs’ parameters line always visible

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#2861]
Th parameters line doesn’t stay visible if you have to use the ‘elevator’ to go down in the list of LSs. Personally I tend to have a hesitation about the last two items when I can’t see them (which one is duration, which one is delay?).

Visible:
![parameters line](https://cloud.githubusercontent.com/assets/8396899/9786086/80992642-57b7-11e5-88c9-8b9d1a23ae1b.PNG)

Not visible:
![parameters line 2](https://cloud.githubusercontent.com/assets/8396899/9786095/8a17f248-57b7-11e5-8586-850428872bb9.PNG)

**Comment by projectkk2glider** [comment]
@opentx/commiters An attempt at this issue available in branch https://github.com/opentx/opentx/compare/projectkk2glider/issue_2861_header_always_visible

I am not a Qt guru, so I am stuck with a problem: how to properly re-size table columns width to better show all items? For example `#` column should be narrower, while the `switch` column should be wider, etc...

**Comment by bsongis** [comment]
Ok I take it, I don't promise anything!

**Comment by bsongis** [comment]
Done. At least it's a little bit better :)

**Comment by projectkk2glider** [comment]
How do you like it now?
![screenshot](https://cloud.githubusercontent.com/assets/5950438/10738193/73447856-7c16-11e5-8006-0070c7420e7b.png)

**Comment by bsongis** [comment]
Nice!

**Comment by projectkk2glider** [comment]
I will continue on other pages...
