### ISSUE TITLE
Companion 2.1.3 Print Model

### ISSUE THREAD

**Issue by AndreasAusD** [opentx/opentx#2866]
Hello,

I can select more than one model in the eepe-File, but when I try to print them only the last one clicked is printed.
Examples : 
- Select model 2, shift-click on 5, 2 - 5 are selectet, 5 is printed.
- select model 2, shift click on 5, strg-click on 3 (deselect), so 2, 4 and 5 are selected, but 3 is printed

Copy and paste on multiple selection works as expexted (only selected are copied)...

Andreas

**Comment by projectkk2glider** [comment]
There are workarounds for both issues, so to me it is not high priority to fix this.
