### ISSUE TITLE
Companion - changing any setting on the telemetry panel does not set the file as being modified

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2875]

**Comment by LapinFou** [comment]
This has been partially fixed. Any modifications in the attached snapshot will not set the file as being modified.
![bug](https://cloud.githubusercontent.com/assets/1685030/10995529/cef630f8-847d-11e5-9ae6-98cbe7c52b8a.png)

**Comment by bsongis** [comment]
Would you reopen an issue (for 2.1.6)?

**Comment by LapinFou** [comment]
Hi Bertrand,

Sorry, I did it the wrong way. I opened a new issue: #3029
