### ISSUE TITLE
companion "lastUpdatesDir" apparently needs a trailing slash added for W10

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#2876]
As it is now:

![desktopko](https://cloud.githubusercontent.com/assets/6065069/9849613/b4b85ea6-5aec-11e5-8ffd-8a5c23ade13e.jpg)

With trailing slash added:

![desktop1](https://cloud.githubusercontent.com/assets/6065069/9849618/bcd6a372-5aec-11e5-814e-0c69dee6b503.jpg)

Same problem on different directory:

![tempko](https://cloud.githubusercontent.com/assets/6065069/9849620/c8f7e0da-5aec-11e5-8fba-f6da0ed3d1d3.jpg)

**Comment by bsongis** [comment]
Needs a test on Windows, thanks!

**Comment by bsongis** [comment]
I removed some unreachable code in this commit, someone would double check?

**Comment by projectkk2glider** [comment]
Looks good
