### ISSUE TITLE
OpenTX sound packs

### ISSUE THREAD

**Issue by adrionics** [opentx/opentx#2878]
Hello

I am trying to understand the sound pack structure for all supported radio's and would like some clarification on this.

It seems that the following radios use the same sound packs: 9xrpro = taranis = taranisplus.
Then, the sound packs for these are the same: 9x = 9x128.
On it's own is the sky9x.

Are these assumptions correct? 
Are there any more supported radio's not in this list?

I have been looking at the tts /radio/util/tts.py script. 
Is this the only script for generating sound file lists?

Is there any other recommended source for more information on supported radio's and their sound packs?

Thank you in advance!
Adrian

**Comment by kilrah** [comment]
AFAIK all ARM boards use one, all mega64/128 boards use another, and the Gruvin board uses its own separate one.
So 3 packs. 

tts.py is the only tool, but it's not even guaranteed to be up to date for all platforms. Ideally you'd look at the code that plays the audio to see what it will call when.
Several of the packs were made by 3rd parties without any tool. 

And please don't ask questions in the issue tracker, causes a lot of mess. Use the forum instead: http://openrcforums.com/forum/viewforum.php?f=45
