### ISSUE TITLE
Timer logical switch: allow setting V1 to a minimum of 0 instead of 0,1

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#2892]
Taranis – OpenTx 2.0.17

V1 = 0 would actually mean the LS is true for the minimum possible time (one calculation cycle, I suppose, as for an Edge LS with duration = 0).
That would allow to create a maximum 10 Hz timer instead of 5 Hz (with V1 = 0 and V2 = 0,1 (of course, the minimum V2 would still be 0,1)).

**Comment by projectkk2glider** [comment]
Relying on that much timer precision in unreliable. The LS duration/delay is processed in a 100ms tick handler an is asynchronous from the LS activation. So a setting of 0.1s could result in actual duration of 0 ~ 200ms. 

What I mean to say is that the LS delay/duration precision is not very accurate.
