### ISSUE TITLE
Latest .deb 64-bit package is of bad quality

### ISSUE THREAD

**Issue by green-big-frog** [opentx/opentx#2893]
While upgrading from 2.1.1 to 2.1.3 I got the error that the package is of bad quality:

`Lintian check results for /home/[USER]/Downloads/companion21_2.1.3_amd64.deb:
E: companion21: control-file-has-bad-permissions md5sums 0664 != 0644`

No Idea if this only happens on my system...

I'm running the latest Ubuntu (15.04) with everything up to date.

**Comment by kilrah** [comment]
Ubuntu has always reported that. We don't know how to make it happy, seems it's not possible with the tools we use.

**Comment by green-big-frog** [comment]
Ok... Searching with the github search in this repo didn't deliver any issues so I just opened a new one.
