### ISSUE TITLE
[Companion 2.1.3][Bug] Model comparison issue: curves

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2896]
Hi folks,

The new comparison engine is much better, but there is still one issue with the curves. The data are ok, but not the graphic curves.
See the snapshot below:
![issuecurves](https://cloud.githubusercontent.com/assets/1685030/9959497/cca3c3a4-5e14-11e5-99cf-65bac9f295f8.png)

**Comment by projectkk2glider** [comment]
Please upload an eepe and tell us which models to compare to see this result.

**Comment by LapinFou** [comment]
At first, I wasn't able to reproduce the problem, but I finally discovered the right sequence to reproduce the problem.
http://1drv.ms/1KlNjUS
1- Open the comparison windows.
2- drag & drop the T-Rex500 model on the left side.
3- drag & drop the Stratus model on the right side.
4- drag & drop the same T-Rex500 model on the right side this time.
Curves are not refreshed.

**Comment by fraternl** [comment]
Does it only happen if you are comparing the same models? It should work then as well, but that might also be the reason it now doesn't work.

**Comment by LapinFou** [comment]
To me, it look likes if you drag & drop another model without closing the comparison windows, then the curves plotting is not refreshed.

Ex:
1- Open the comparison windows.
2- drag & drop the T-Rex500 model on the left side.
3- drag & drop the same T-Rex500 model on the right side.
3- drag & drop the Stratus model on the right side.
Curves are not refreshed.
![issuecurves1](https://cloud.githubusercontent.com/assets/1685030/9961758/960afcf0-5e22-11e5-85b5-d8ef9cecc9ce.png)

**Comment by projectkk2glider** [comment]
Can not reproduce in current `master` and official 2.1.3. Perhaps it is only a Windows problem? We use the same file names and generate new contents in them. Maybe the display is generated from the cached image somewhere? Again can not reproduce on Linux.

**Comment by LapinFou** [comment]
When the 2.1.4 will be out, I will try again.
Thanks for your support.
:)

**Comment by projectkk2glider** [comment]
Or you could try the nightly build tomorrow http://downloads-21.open-tx.org/nightly/companion/

**Comment by LapinFou** [comment]
I will !
:)

**Comment by LapinFou** [comment]
I confirm the issue has been resolved in the build 2.1.4N465.
Thanks!!
