### ISSUE TITLE
Compilation Server Down!

### ISSUE THREAD

**Issue by pyr8** [opentx/opentx#2904]
Getting error on download - "Compilation server temporary failure, try later"

**Comment by projectkk2glider** [comment]
Must be something on your side, just checked both 2.0 and 2.1 and both work for me.

**Comment by pyr8** [comment]
See attached screen-shot for version, error & settings.

Thanks.

[image: Inline image 1]

**Comment by projectkk2glider** [comment]
Image does not show, is this the same problem as #2905?

**Comment by pyr8** [comment]
Yes it is, sorry!  :(
