### ISSUE TITLE
No "Mavlink" download from server on 2.1.3

### ISSUE THREAD

**Issue by pyr8** [opentx/opentx#2905]
Unable to download "Mavlink" firmware - getting error from download server on OpenTX 2.1.3

**Comment by projectkk2glider** [comment]
Confirmed, the EXT=MAVLINK option cause compilation failure on many platforms. The server itself is ok, the OpenTX source is broken.

**Comment by projectkk2glider** [comment]
One example of broken compilation:
```
make clean; make PCB=9X EXT=MAVLINK
```

**Comment by pyr8** [comment]
Is there a work around in the meantime, or default back to "OpenTX 2.0.17"?

**Comment by projectkk2glider** [comment]
No work around, sorry.

**Comment by pyr8** [comment]
I'm assuming I will have to wait for the next release for this issue to be resolved?

**Comment by kilrah** [comment]
Correct.

**Comment by pyr8** [comment]
Perfect, thanks for the clarification!  :)
