### ISSUE TITLE
No sound with 2.1.3 using Amber

### ISSUE THREAD

**Issue by MichaelEber** [opentx/opentx#2906]
I have a Taranis X9D Plus and two days ago I installed the latest version of OpenTX on it.
I was in the 2.0.x version prior to this.
I then installed the Amber sound files which failed to make any sound at all.  I then found a 2.1 file for system so I deleted the System folder and copied in the 2.1 Amber System files.  I still have no sound whatsoever.

**Comment by bsongis** [comment]
Is it possible you ask on the forum before opening an issue? Thanks for your comprehension
