### ISSUE TITLE
Compilation warning "FrSky module alarms removed!" necessary?

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#2908]
There was a `#warning` introduced in commit https://github.com/opentx/opentx/commit/88d9691d16fa96691a74595ed8e17d021c868fd5#diff-146f1098a524de4323eff6d3d2817e61R416
which produces anoying compiler warnings:
```
./../radio/src/telemetry/frsky_d.cpp:416:2: warning: #warning "FrSky module alarms removed!" [-Wcpp]
```

Is there still any reason for it, or could that part of the code be cleaned up now?

**Comment by bsongis** [comment]
Yes, nobody complained yet for this part missing, I think we could remove the warning!

**Comment by bsongis** [comment]
And then all warnings should become errors, this would be really nice ...

**Comment by projectkk2glider** [comment]
Let me do this.

**Comment by bsongis** [comment]
Thanks! Also perhaps there will be some eeprom that can be freed in 'next'

**Comment by projectkk2glider** [comment]
I am also looking at splitting frsky_d.cpp code into ARM and nonARM files. The current file is hard to read with so many ifdefs. I will make a PR and you will decide if you like it.

**Comment by bsongis** [comment]
Oh yes, thanks!
