### ISSUE TITLE
[Sound pack FR][OpenTX 2.0 & 2.1 branches]Trim voice announces are missing

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2912]
When upgrading from 2.0.17 to 2.1.13, I discovered the French CSV (french-taranis.csv) files were incomplete for both 2.0 and 2.1 OpenTX versions.
The 2 following announces are missing:
SOUNDS/fr/SYSTEM;midtrim.wav;Trim centré
SOUNDS/fr/SYSTEM;endtrim.wav;Trim maximum atteint

**Comment by projectkk2glider** [comment]
@LapinFou can you provide French translations for:
* "trim center"
* "maximum trim reached"

**Comment by LapinFou** [comment]
I've already done it !
;-)
SOUNDS/fr/SYSTEM;midtrim.wav;    <b>Trim centré</b>
SOUNDS/fr/SYSTEM;endtrim.wav;    <b>Trim maximum atteint</b>

**Comment by projectkk2glider** [comment]
Silly me :blush:

**Comment by LapinFou** [comment]
Nope!! Probably just exhausted with all you work ! :wink:
