### ISSUE TITLE
Add Step and Range to the Adjust GV Function

### ISSUE THREAD

**Issue by voyager9** [opentx/opentx#2917]
Hello,
i would like to have a step range in the Adjust GV Function, with a Max. value.
For Example:
SF1  AileronTrimRight   Adjust GV1   STEP   (+ 1-150)    MAX  (0-150)
SF2  AileronTrimLeft     Adjust GV1   STEP   (- 1-150)    MAX  (- 0-150)

When i can choose a Step to the Adjust GV fuction it would simplify the creation of a Digital Pot. or a variable Multistep Position Switch.
The Steps are between 1-150 and the MAX 0-150 that the value cannot step over it

It would be great when you can add this function.

Best Regards, Andy

You do a great Job with the OpenTx Soft. Thumb Up

**Comment by hrenz** [comment]
Well that would be fine, 
this should be same at SF increment / decrement not only with +/-1steps

free inc/dec steps  example 5 or 10 or 20 or  25

**Comment by projectkk2glider** [comment]
This issue expands on #2862 (where only range was requested). I will close that one.

**Comment by LapinFou** [comment]
Yeah!!
Very good idea. +:100:

**Comment by bsongis** [comment]
I am afraid that we cannot add a max without a min

**Comment by voyager9** [comment]
??? Why ???
The min should always be zero. Isnt it possible? Or Add a min with zero standard..... or positive as max and negative as min....

**Comment by bsongis** [comment]
Refactoring explained in #3185
