### ISSUE TITLE
companion: duplicate tabs

### ISSUE THREAD

**Issue by gbirkus** [opentx/opentx#2918]
In model "General Settings" there are duplicate tabs "Setup, Trainer, Calibration")

**Comment by gbirkus** [comment]
Tested on ubuntu 64, companion 2.1.3

**Comment by projectkk2glider** [comment]
Did you compile it yourself? If yes, then you need to start from the clean build directory and this problem will be fixed.

**Comment by gbirkus** [comment]
no, i downloaded it and do a clean install on new ubuntu.

**Comment by projectkk2glider** [comment]
Then the packages were probably created wrong (they are build by hand). I will take a look later today.

**Comment by projectkk2glider** [comment]
Confirmed the .deb packages on server are incorrect. Clean build produces a good package. I can not fix this now, but will do it in the afternoon.

**Comment by gbirkus** [comment]
thanks
