### ISSUE TITLE
Simulator 2.1.3 - getValue("pilot-latitude") and getValue("pilot-latitude") return always 0

### ISSUE THREAD

**Issue by Sacre100** [opentx/opentx#2921]
In Companion Simulator 2.1.3, getValue("pilot-latitude") and getValue("pilot-latitude") return always 0 even with valid simulated GSP latitude and longitude.

GPS coord 1 : 46.515826, 6.999142 -> converted for : 27909495 -2143284163
GPS coord 2 : 46.510178, 6.992867 -> converted for : 27906106 -2143287928

Distance between point : 790m (OK in simulator).

**Comment by projectkk2glider** [comment]
Not a valid field name in 2.1, see http://downloads-21.open-tx.org/firmware/lua_fields.txt

This is still missing and must be coded in 2.1.

**Comment by Sacre100** [comment]
Current flight mode ("flight-mode") seems also missing.

**Comment by ptsneves** [comment]
Is there a list of the missing fields so could implement them?

**Comment by projectkk2glider** [comment]
Not really. You could compare the list with the 2.0 list http://downloads-20.open-tx.org/firmware/lua_fields.txt and see what is missing. You should forget about all telemetry fields that are handled natively in 2.1 (like Alt, Alt-max, etc..) and then the diff between 2.1 list should produce missing ones.

**Comment by projectkk2glider** [comment]
This could be easily solved by adding additional values to the `getValue()` It currently returns latitude and longitude, we could add: pilot lat, pilot lon and distance.

**Comment by mcshaz** [comment]
getValue("flight-mode") is still missing. should I open another issue?

**Comment by projectkk2glider** [comment]
No, I forgot about that one.
