### ISSUE TITLE
Companion installer 2.1.3 installs into 2.0 folder

### ISSUE THREAD

**Issue by ph-svv** [opentx/opentx#2932]
Companion 2.1.3 installs into C:\Program Files (x86)\OpenTX\Companion 2.0\ instead of C:\Program Files (x86)\OpenTX\Companion 2.1\ 
Also the start menu item is listed as 2.0, not 2.1

**Comment by kilrah** [comment]
The bug was in companion versions <2.1.3 and was fixed, see release notes. You'll have to fix the directory manually once.
