### ISSUE TITLE
Screenshot,  Filenames to long, cant see at SD-Cart at Display

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#2934]
![auswahl_328](https://cloud.githubusercontent.com/assets/6217896/10122067/dc28f9a0-650a-11e5-94c0-8eadcf72a7b3.jpg)
Hy,

the Screenshot Filenames are to long.
I can't see the filenames at the Sd-Card at the Display direct, no file is displayed.
Only if I connect to PC I can see that there are Files of Screenshot at the Sd-Card
Example:  screenshot-2015-07-27-22-44-54.bmp

Possible shorter Filename: 
Screen20150727-224454.bmp
or shorter
20150727-224454.bmp

**Comment by kilrah** [comment]
The radio doesn't have the ability to read those anyway.

**Comment by hrenz** [comment]
I will only see the filenames itself notthe screenshot
now I see nothing

**Comment by projectkk2glider** [comment]
I vote for `Screenshot-20150727-224454.bmp` which is 30 characters (limit is 32). Minimal changes required in the code.

**Comment by bsongis** [comment]
Yes, go on :)

**Comment by projectkk2glider** [comment]
The same date/time generation function is used in:
* model backup (only date part)
* eeprom backup
* telemetry log (only date part)
* screen-shot

I do not want to change behaviour in all of them, so my current recommendation is to leave the date/time alone and shorten the prefix to **scr**: `scr-2015-07-27-22-44-54.bmp`. @bsongis do you agree?

**Comment by bsongis** [comment]
I also think we should keep consistency in these names.
Why not screen-2015-07-27-224454.bmp?

At the beginning I thought about screen-2015-07-27-22:44:54.bmp. But the quick selection in a terminal won't work with usual xterm*charClass settings
