### ISSUE TITLE
Taranis X9E SWF and SWH don't seem to recognise 3 pos on-off-on switch

### ISSUE THREAD

**Issue by cncmodeller** [opentx/opentx#2936]
Hi,
    I've fitted an On-Off-On three position switch to both SWF and SWH on my Taranis X9E and set 3 POS in the hardware menu. The main screen display page only shows a 2 positions when the switch is toggled. I note that the switch port connectors header markings are in bold (like the analogue inputs) SWH rather than SW-H so is this an analogue "switch" port that I need to feed 0v - Vcc/2 -Vcc to get the three positions or is it a firmware bug??

Any thoughts gratefully received.

Barry M

**Comment by projectkk2glider** [comment]
Did you configure the switch type to 3POS in radio setup menu?

**Comment by projectkk2glider** [comment]
@bsongis does commit bcfbc4d04c03278a1347ae7730167c3db5d0ae89 fix this or do we have another problem?

**Comment by bsongis** [comment]
I need to check, I am not sure there are 2 PINS for SF and SH! At least SH cannot be 3POS. Would you double check?

**Comment by bsongis** [comment]
@projectkk2glider No this commit has nothing to do with the physical switches as they are in the beginning of the list

**Comment by cncmodeller** [comment]
Both of the headers for the two switched have 3 pins on the X9E see pic opf SWH below.

Hope that helps,
Ta
BPM

![20151008_225049](https://cloud.githubusercontent.com/assets/14881285/10381044/c0fb8d7e-6e0f-11e5-9090-148cb0589ea8.jpg)

**Comment by bsongis** [comment]
Yes but it doesn't say that the 3 pins are connected to the CPU!

**Comment by kilrah** [comment]
On the X9E ALL switches can be 3POS, they all have 2 pins that are connected all the way! Including SH

**Comment by projectkk2glider** [comment]
Btw my development PCB back board has SW-H connector positioned very differently. In fact many of the connectors are placed in other positions, Did we perhaps missed some CPU pin changes here? Maybe one leg of SW switch is wired wrong in hal.h.

Other possibility is that use has a defective switch. @cncmodeller can you temporarily try to use some other (known to be working) switch in SW-H slot to see if it works.

**Comment by bsongis** [comment]
@kilrah  All the schematics I have don't have 2 pins for SH

**Comment by kilrah** [comment]
They must be outdated?

![clipboard01](https://cloud.githubusercontent.com/assets/6065069/10400380/5d20d6e6-6ec9-11e5-82cd-cdc66bde891d.jpg)

**Comment by projectkk2glider** [comment]
We have a firmware problem, hal.h:
```
#if defined(REV9E)
  #define SWITCHES_GPIO_REG_H           GPIOF->IDR
  #define SWITCHES_GPIO_PIN_H           GPIO_Pin_1  // PF.01
#elif defined(REVPLUS)
  #define SWITCHES_GPIO_REG_H           GPIOD->IDR
  #define SWITCHES_GPIO_PIN_H           GPIO_Pin_14 // PD.14
#else
  #define SWITCHES_GPIO_REG_H           GPIOE->IDR
  #define SWITCHES_GPIO_PIN_H           GPIO_Pin_13 // PE.13
#endif
```
So SH is defined as one input switch!

**Comment by projectkk2glider** [comment]
Actualy there are more errors in hal.h. At least SF, SH and SI have wrong inputs.

**Comment by bsongis** [comment]
No, Adela sent me 3 or 4 versions ... I am almost sure that what we have is good and SF and SH are 2pos only, now I remember. I will try to find the last table (it is not in the schematics)

**Comment by projectkk2glider** [comment]
Then we must limit the choice in hardware setup menu for SF and SH. But first we need to verify this somehow.

**Comment by kilrah** [comment]
Yes, if there are 4 versions floating around we really need to ditch everything we have and ask FrSky to give us a version that 100% matches the production hardware for sure, otherwise we'll just continue to go crazy.

**Comment by bsongis** [comment]
I am lost, I have too many versions sent on Skype or email, some are hand written. I really need to ask Adela to be sure things are right. But yes I remember I was lazy and didn't do what @projectkk2glider explains.

**Comment by cncmodeller** [comment]
Thanks guys, 
                     Both the switches I was using work fine in all 3 positions when connected to other switch headers.

Hope that helps...
Cheers
BPM

**Comment by projectkk2glider** [comment]
@cncmodeller it now looks like the SH and SF are only able to accept (physically) the 2 position switches. So if you want to use the 3 position switch, then move it to some other slot (not to big otherwise you will get another problem).

The OpenTX will have to be fixed to remove a possibility to select 3POS type for SH and SF in radio hardware setup menu.

**Comment by cncmodeller** [comment]
OK thanks guys I've got a couple of two pos switches in the physical switch config I'm using so I'll move them over. I'm guessing it's the top / centre pins (as seen in the pic above) that are connected as from memory the switch registered a different state when closed across them vs open.

Thanks for your help. Great work BTW, loving the functionality. I'm finally getting all of the mode / camera and gimbal controls I've wanted for ages. Operating my quad will be relative child's play after the upgrade to the X9E and OpenTx :-)

Cheers
Barry M

**Comment by projectkk2glider** [comment]
>The OpenTX will have to be fixed to remove a possibility to select 3POS type for SH and SF in radio hardware setup menu.

I will do this...

**Comment by MarenB** [comment]
Hi,

I have similar issue here after I swapped SC and SF on my X9E, so SF is now 3POS, SC is 2POS. 
Adopted the settings on the hardware menue, but that does not change anything at all. I can only use two positions of SF and SC shows all three positions when I do the autodetect-thing in the mixer setting and move the 2POS-switch slowly.

**Comment by kilrah** [comment]
As explaned above SF only supports a 2-pos switch, so your 3-pos obviously won't work there. 
What "3 positions" does SC show? You should have up and down but not middle.

**Comment by MarenB** [comment]
Damn. Sorry. No idea why I didn't hear the bell ring - it must have nearly hit me.

I can set SC to be 2POS, but if I move it slowly, I can see it going from up to center to down. Maybe that's normal, but I just wanted to notice it. Not sure, what electrical-wise causes the center position reading.

**Comment by kilrah** [comment]
Your 2-pos is a single contact that is either open or closed, right? Not closed/closed using 2 contacts?

**Comment by MarenB** [comment]
It's the stock switch from SF that I moved to SC.
