### ISSUE TITLE
Translation: Audio Files differences

### ISSUE THREAD

**Issue by Clooney82** [opentx/opentx#2937]
Hi,

why does some audiofiles have different sayings / meanings some languages?
e.g.
File 0105.wav
EN: 600
DE: Uhr (clock)

Wouldn´t it be better to have one Master Language (e.g. EN) and then translate it to the tagret language, so that e.g. file 0105.wav has in all languages the same meaning ?

**Comment by kilrah** [comment]
Doesn't work as different languages have different "logic" (order and amount of words)
