### ISSUE TITLE
Feature Request - BgMusic Track Selection Dialog

### ISSUE THREAD

**Issue by powdermnky007** [opentx/opentx#2940]
This isn't an Issue, more of a feature request.  I'm Git impared.  Please move if you need to.

My friends and I use our radios as jukeboxes while we fly.  Currently we have bgmusic set up for each of our toggle switches, on each of our models.  To find a particular song, we have to keep going through each switch until we find the right one, or go edit the switch configs to play the song we want because we have more songs than switches.  

It would be amazing to be able to use one three way switch for this.
1st position off
2nd position pick filename out of music folder (save path/filename to variable).
3rd postiton bgmusic play (variable name)

that way we could dedicate one switch to playing all of our songs, instead of all 4 switches to be able to play a total of 8 songs.  My apologies if there is a way of doing this now that I am unaware of.  If so, please enlighten me.  Thank you in advance.

**Comment by projectkk2glider** [comment]
I remember seeing a Lua script that would work like jukebox https://www.youtube.com/watch?v=qvW74wlo0OY or even this https://www.youtube.com/watch?v=s7TU0m4jcSc

I think we can close this one.
