### ISSUE TITLE
S1 slider on X9e has no memory 

### ISSUE THREAD

**Issue by Isoaritfirst** [opentx/opentx#2948]
Using 2.1.3 on X9e

I have tried changing the check position from auto to manual but niether gives me a memory of its last position when re selecting a model.

The F1 pot does have a memory but I cannot achieve the same effect with the sliders.
Any ideas?

Mike

**Comment by projectkk2glider** [comment]
Anybody else can confirm this issue?

**Comment by janekx** [comment]
Hi cant agree I test all together and any of them one by one in N486 all warn well befere are turn back to right  mem position.

**Comment by bsongis** [comment]
It's really possible it was the same bug than the X9E Trainer issue.
@Isoaritfirst  please download the N486 to confirm it's fixed, thanks!
