### ISSUE TITLE
[OpenTX 2.1.3][Bug][9XR-Pro] Battery gauge bar shows only 1/2 battery when 100% full

### ISSUE THREAD

**Issue by biasedlogic** [opentx/opentx#2950]
If using the graphical battery gauge bar option on a 9XR Pro, the same number of bars is displayed for a full battery as on a Taranis, but Taranis has a smaller battery symbol. So the "full" charge does not "fill" the battery icon - it looks half empty.

**Comment by projectkk2glider** [comment]
Image from the other issue: http://fs5.directupload.net/images/151024/zrj4qnjy.png

**Comment by bsongis** [comment]
Done, needs tests

**Comment by biasedlogic** [comment]
Works better, but displays always at minimum one bar of battery - even if the battery voltage is below the lower limit of the voltage range.

I'd prefer the battery symbol to be 1px narrower, so that when the battery is full there's not so much white space to the right of the "bar" - but it's a matter of how it looks like and personal preference

**Comment by bsongis** [comment]
At the right of the bar is the flight mode

**Comment by biasedlogic** [comment]
Sorry, I wasn't precise again ;-) 
The bargraph is displayed within a black rectangle, on a white field that is shaped like a battery. The very first bar is one pixel away from the left edge (the negative pole) of the battery. The bars fill up the battery symbol, but when "full" the rightmost bar is three pixels away from the right edge (the positive pole) of the battery symbol, giving the impression "90%full". It either needs a bar more or a shorter field. 
Regards, 
M.
