### ISSUE TITLE
FAS40A not send current on X9E 2.1.3 

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#2952]
Hallo, 
friend told me that after changing to X9E stop getting values from FAS40A old telemetry sensor. 
Taranis Plus with 2.0.17 works well, the RX is D4R-II and all worked fine after rebind to X9E he can find all sensors by detect all sensor function. It shows sensors and asterisk blinking but value is 0. 

Looks like bad ID value?

**Comment by janekx** [comment]
You have re-release the 2.1.3? Reflasing with other date 2.1.3 looks correct this issue.

**Comment by bsongis** [comment]
No, we would have released a 2.1.4 ...

**Comment by janekx** [comment]
Interestin, reflash helped closin
