### ISSUE TITLE
[Companion] Improve Log Viewer

### ISSUE THREAD

**Issue by MicheleVilla** [opentx/opentx#2959]
In Companion Log Viewer may be useful have some options
-Statistical data like Min Max Average
-Print and export in pdf or image  format of visualized graph
-Display the coordinates (X Y) detected by the mouse on the curve
-Possibility to cut logged data rows 

Thanks

**Comment by PieroCo** [comment]
- Possibility to edit incorrect values. Es altitude value

**Comment by projectkk2glider** [comment]
Altitude improvements done in #3442
