### ISSUE TITLE
[OpenTx] 3 temporary positions switch

### ISSUE THREAD

**Issue by MicheleVilla** [opentx/opentx#2960]
Is not relevant but in Hardware configurations is not present a  3 positions temporary switch (ON-OFF-ON)
Is the same of 3 switch positions but in simulator may be useful to have the right switch type

**Comment by hrenz** [comment]
Hy,
At the distributors 
the 3 Pos Switch are Called
ON - OFF - ON    both side switches
(ON)- OFF - ON  one side switch, other side temporary
(ON) - OFF - (ON) both side temporary

the 2 Pos switches
ON - OFF   2 two pos, normal switch
(ON) - OFF  2 pos, temorary switch

**Comment by kilrah** [comment]
Duplicate of #3189
