### ISSUE TITLE
No arrows on RS, LS2, RS2 warning of the position on X9E N486 

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#2961]
When we use the manual check of the sliders and pots position all have arrows what direction to move to memorised position, the RS, LS2, RS2 siders not have any arrow LS have arrow.  
![2015-10-11 14 39 20](https://cloud.githubusercontent.com/assets/2682800/10416805/f1014136-7025-11e5-95b8-5f732b43502d.jpg)

**Comment by bsongis** [comment]
Would you double check the nightly build? I didn't test myself.

**Comment by janekx** [comment]
N488 OK show arrows and right direction, Thanks
