### ISSUE TITLE
Enhancement: provide means of copying telemetry sensors between models in 2.1

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#2964]
I would like to be able to selectively copy telemetry sensor configurations from one model to another. Maybe a select-all then copy and paste to another model, or drag-drop (whatever way is considered most appropriate).

**Comment by athertop** [comment]
To my knowledge, this has still not been implemented even in the latest release. Having consistency between pages regarding copy/paste options would be really nice.

**Comment by RipperDrone** [comment]
would really be nice feature for users like me who handle a lot of models...
