### ISSUE TITLE
Companion nightly build 488 - prompt to "Save As to backup in old format" can be misleading

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#2967]
Just trying the latest nightly build 488 of Companion.
1. Open .epee in format 216
2. The alert that the EEPROM is being upgraded is great, but is IMO a little misleading. It says "_You should Save As to keep the old file as a backup_" but of course this will only work if the user specifies a different name. Obvious to expert users but maybe not so to naive users. It wouldn't matter so much, but the default in the Save As dialog is to overwrite the original file.

Suggest tighter wording e.g. "About to upgrade your EEPROM to format 217. To keep your original file as a backup, please choose File -> Save As specifying a different name." 

Even better would be if Companion made an auto backup of the source file, say with suffix "_216".

**Comment by SebiTimeWaster** [comment]
thx, the new wording helped me understand whats happening!
so... +1
