### ISSUE TITLE
LUA issue - model.setTimer() minutebeep always enables regardless of 0 or 1

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#2978]
The model.setTimer() function (in 2.1 for Taranis Plus), regardless of the minutebeep value assigned (0 or 1), will always enable the minuteBeep option ('Minute Call' option in the Model Setup page) for the timer to which this is applied. I believe this has been broken for many versions of OpenTX. 

To reproduce, save this LUA script somewhere on SD card:

local function run(event)
	model.setTimer(0,{ mode=1, start=0, value=0, countdownBeep=0, minuteBeep=1, persistent=1 })
	model.setTimer(1,{ mode=1, start=0, value=0, countdownBeep=0, minuteBeep=0, persistent=2 })
end

return {run=run}

Then manually In the model setup page, set the timers to off, minute call to off etc. for both timers. Then run the script. You will see that both timers become configured with the values from the script lines, but where Timer 2 should not have the minute Call option set, this becomes enabled by the execution of the second line in the run function of this script, despite the switch on this line being "minuteBeep = 0"

(My favourite telemetry script which has been migrated for use in 2.1 now has the annoying issue of two seperate minute calls now being enabled because of this issue - one minute call would be great, but because of this bug, we get 2 calls every minute which is annoying!)

Would be grateful if someone would look at this issue given its longevity without resolution. Best regards

**Comment by projectkk2glider** [comment]
The parameter `minuteBeep` is boolean type so the `false` and `nil` values are treated as FALSE, any other value (including 0) is treated as TRUE. That is the way Lua works, we use http://pgl.yoyo.org/luai/i/lua_toboolean function.

The same is true for parameter `carryTrim` in `funciton model.insertMix()`. It also uses boolean type.

So just write `minuteBeep=false`.
