### ISSUE TITLE
Update Lua Reference Guide for OpenTx2.1

### ISSUE THREAD

**Issue by r41065** [opentx/opentx#2985]
changing my Taranis from OpenTx 2.0.17 to 2.1.x found some lines in my Telemetry script which are not longer working correct.
for example:
  local modelinfo = model.getInfo()
  lcd.drawText(10,20,modelinfo.name,MIDSIZE)    --> works correct
  lcd.drawNumber(10,30,modelinfo.id,MIDSIZE)    --> returns Syntax Error

local fm = getValue("flight-mode")  --> returns always "0"

lcd.drawChannel(80, 20,"clock", MIDSIZE) --> returns Minutes from midnight, not "hours:minutes" as in 2.0.17

I wonder that they are not working for the new Version because I copied these Functions from the Reference Guide for OpenTx 2.0 .
I can't find any Documentation to check if there is a new syntax or if this are open points for Lua scripting in OpenTx 2.1

Ralf

**Comment by projectkk2glider** [comment]
https://github.com/dsbeach/lua-reference-guide is I thing the most recent version of documentation.

**Comment by r41065** [comment]
Sorry, but i get only:

Come back later!
This book is still in preparation by its author.

**Comment by projectkk2glider** [comment]
I see, here is a link to the fork https://www.gitbook.com/book/dsbeach/opentx-lua-reference-guide/details by @dsbeach which was not yet merged into the main OpenTX repository.

**Comment by dsbeach** [comment]
I'm here and still working on it.  Should I create a pull request for the current state?

I've been busy putting together a debugging environment for the companion so I can hopefully correct whatever defects are uncovered by bringing the documentation up to date.

**Comment by r41065** [comment]
Thank you for Updated Link, now i can do my Test
and yes, there are some new functions for the scripts..

**Comment by bsongis** [comment]
@dsbeach Yes for the pull request, it would be nice, I hope it will work, it will be the first pull request on the doc

**Comment by dsbeach** [comment]
I'm using the gitbook editor which generates a ton of commits.  I'm new to git and wonder if there is a easy way to consolidate all the commits down to one per file.

Also, should I plaster a 'DRAFT' watermark on the cover page, or are you OK as it is?

**Comment by bsongis** [comment]
I think it is already OK!
