### ISSUE TITLE
Timer as input not possible at 2.1.3 and Nightly

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#2991]
On 2.0 was possible to set timers to inputs. On 2.1.3 and nightlyes is not possible to select it in the input. 
I tried to set timer, give it name but there in the selectons of inputs no longer appear.

**Comment by projectkk2glider** [comment]
On the radio or in Companion?

**Comment by janekx** [comment]
Sorry i tried it on radio

**Comment by kilrah** [comment]
Inputs have never been a possible choice for throttle source.

**Comment by janekx** [comment]
Talking about that is possible to use timer as progress to the any channel. 
https://www.youtube.com/watch?v=rEs3y2xj7xE

**Comment by kilrah** [comment]
Ah, makes more sense. Not sure if it's a bug or intended.

**Comment by janekx** [comment]
It is unususal function but for some like tanks or other it is useful, that is what makes the OpenTX that OpenTX where can be done anythink :)

**Comment by kilrah** [comment]
I had a look and it was apparently removed because some code it needed to work is no more part of the new telemetry system.
I.e. quite a bit of work to put back in, so unless there are "real" scenarios where it's useful it will likely stay as it is.

**Comment by projectkk2glider** [comment]
@janekx  I suggest to use a Lua script as an alternative. I should be fairly simple and could also do much more if needed.
