### ISSUE TITLE
Companion Mixes Tab Suggestion

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#2996]
On the Model Mixes tab the Name of an component where entered is not always displayed. eg Curve names are not, just their ordinal number eg Curve (1) whereas Flight Mode is displayed eg Flight modes (Launch, FM2). 
I know you can click on the Curves and other tabs but would make easier reading and diagnosing errant relationships for more complex models.

I cannot find another request for this however apologies if already asked.

**Comment by elecpower** [comment]
Should have mentioned Taranis X9D Plus Companion & Firmware 2.1.3 on Windows 10.

Just new to OpenTX and appreciate the amount of effort you guys put in.

**Comment by mpaperno** [comment]
Done in #4888
