### ISSUE TITLE
[Feature Request] Trainer port connect/disconnect indicator

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#2997]
Hi folks,

Since some people are doing some complex training setup (the most common one is: the master radio will regain the control by moving its sticks), it would be very nice to have a "trainer port connect/disconnect" information.
The built-in trainer mechanism will switch back to the master controls if the trainer port is detected as disconnected. This is nice and safe.
If you create a complex setup using the TR1-TR16, this is not the case. The easy solution would be to create a logical switch to detect if the trainer port is present or not. Unfortunately this information is not available.
Is it possible to add in the list a **"Trainer is present"** parameter?

This should work with DSC port, S.Bus/CPPM in the JR bay and S.Bus in the battery compartment.

**Comment by kilrah** [comment]
Any TRxx mixer line gets disabled automatically when trainer is disconnected.

**Comment by LapinFou** [comment]
Well, this is not the case in my current setup (X8R in the JR bay/S.Bus wired). If I switched off the student radio, I got a voice announcement for the trainer KO, but TRx takes a value depending of the failsafe configuration of the X8R.
I will do more testing at home to be more accurate, but your statement doesn't match my observations.

**Comment by kilrah** [comment]
Then that would be a bug that needs solving, not something that needs a new feature.

**Comment by LapinFou** [comment]
OK. I will do more testing ASAP.
However, having a trainer state indicator would be nice.
:smiley:

**Comment by LapinFou** [comment]
I was thinking about something: without a "trainer mode active" indicator, how can we use more than 4 channels? To me, this indicator is really missing. I must think about more arguments to convince the team that it would be a good idea to add it.
:smiling_imp:
