### ISSUE TITLE
[Taranis] Problem with SBUS Trainer mode

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#2999]
Reported by Wayne: **we had a few reports from people. We did most all of our testing with the D4R-II in CPPM mode. Only ground checks with Sbus, so we failed to fully test it. Sorry!! The issues take a little time to show up, but sure enough it seems to do it every time. 
We also wired in an X8R just to make sure it was not an RF thing, and it had the same results.
from an observation emailed to me this morning:
But the worst part was that after several minutes with the
Student flying, the plane would go crazy, and returning control
to the Instructor it started working OK.**

But it means ... who has the RSSI warning?

**I think the master radio does. I was out sick this weekend, so was not present for this round of testing.**

would you double check if you can reproduce?
I just read again the code, I really see nothing, I hope it's not just interferences between the 2 modules

**I just asked Bruce a few more details from his weekend testing. He was doing the additional testing as we had heard from a few people about issues when using Sbus with the Linker. It may be a while before I have an answer for you.**

**Comment by kilrah** [comment]
Another report:
http://www.rcgroups.com/forums/showpost.php?p=33039291&postcount=14

And in French:
http://frskytaranis.forumactif.org/t2828-rx-sans-telemetrie-avec-sortir-cppm#33090

**Comment by kilrah** [comment]
If we could have details on what firmware the receivers are using (EU/non-EU) it would be nice too to see if that can play a role.

**Comment by bsongis** [comment]
Here is an update from Bruce:
**I could never get the bad RSSI Critical/Telemetry Lost/Recovered messages
on the ground.
Maybe the model receiver needs to be quite a ways away before it happens?

But I had some success seeing the the XR4-SB Trainer channels misbehave.

I used a D4R-II as the model receiver and used channels 1-4 for the Trainer.

With the Trainer Radio, Student Radio, and Model receiver all about 20 feet apart
I switched a few times between Student and Trainer, then kept it
with Student in control.

After a few minutes, looking at the Channels Monitor, every now and then
I could see the 4 channel values jump around.

Sometimes you had to wait several minutes for it to happen, then it would
happen for maybe 5 seconds.
**

**Comment by kilrah** [comment]
> I could never get the bad RSSI Critical/Telemetry Lost/Recovered messages
on the ground.
Maybe the model receiver needs to be quite a ways away before it happens?

This would be "normal", the X receiver having its antennas right next to the radio's module it can swamp it and prevent it form receiving the telemetry from the model when it is far. Moving the antennas further away, even a few cm will help.

> After a few minutes, looking at the Channels Monitor, every now and then
I could see the 4 channel values jump around.
Sometimes you had to wait several minutes for it to happen, then it would
happen for maybe 5 seconds.

For this the only thing I can imagine is the opposite, with the master radio's module preventing the X8R from receiving control data from the slave and causing it to enter/exit failsafe mode and cause the jumps.

Both systems send RF at a 9ms interval, but with imprecisions both timings will slowly "slide" with regards for each other, and sometimes timing might be "just right" to block the trainer RX.

If I'm right then nothing but physical separation can solve it.

**Comment by AloftHobbies** [comment]
This would be with the "normal" X based stuff.

We can give Kilrah's separation idea a quick test. I think I heard of someone having the same issue when using Sbus into the trainer port (DSC). I think they may have been running a different brand RF system. I may be wrong on that.. I speed read a lot of different stuff for the FrSky world.

CPPM does not seem to have an issue. Also, we will have the X4R-SB-CPPM receivers in very soon, should be interesting to give one of those a try in CPPM mode and see if they still have the same issue, as the RF stays the same that way.

**Comment by kilrah** [comment]
> I think I heard of someone having the same issue when using Sbus into the trainer port (DSC). I 

I doubt since that doesn't work! SBUS can only come in either on module pin 2 or on the battery bay serial port.

**Comment by AloftHobbies** [comment]
LOL - See, my memory...

**Comment by Ze-baloo** [comment]
I will add my observation, sorry in advance for my lack of electronical knowledge ;-)

I have binded a X8R to my Turnigy 9X under OpenTX-9X 2.1.3 with a stock frsky DHT module.
The X8R has been connected in the external module bay of my Taranis X9D A01 model under OpenTX 2.1.3 (see photo)
![20151012](https://cloud.githubusercontent.com/assets/15279917/10782154/13e539b6-7d4e-11e5-9835-b49cc6f120ca.jpg)
All are on non-Eu firmware.

While observing the Chanel monitor on my Taranis once the trainer activated, i have noticed some "phantom" slave commands. The problem is that it happens all the tims independantly of the model used, more annoying, it will happen, but no clue when, i mean that it's not clearly reproductible.

if you want more information, please ask, it'll be a pleasure to help you to find out.

**Comment by LapinFou** [comment]
I have the same setup as Ze-baloo. I also got some troubles.
In my setup the X8R is binded in mode 2 (D16 / 16ch / telemetry off).

**Comment by banderson546** [comment]
I'm testing a Linker equipped with an X4R-SB on 2.1.3 with 4 channels set for the Trainer function activated by a switch.

I did an experiment and separated it from the Taranis by 3 feet using an extension cable.

It still got the occasional channel glitching coming over the link from the Student receiver.
There were no announcements of Trainer signal loss.
It was very intermittent, sometimes it would take a while to happen. It usually would last for 3 or 4
seconds and then stop.

**Comment by KIrill-ka** [comment]
@kilrah, do you confirm that issues mentioned here are caused by uart interrupt latency (overrun errors) as in #3252?

**Comment by kilrah** [comment]
I can't confirm it as it wasn't investigated yet. If you did and can affirm it then great!

**Comment by KIrill-ka** [comment]
I was a bit worried that my "investigation" was put aside :)
It's not absolutely clear to me that this is an exact duplicate of #3252.
By the way, as a temporary solution I shortened sbus frame which is sent to taranis to 23 bytes. Now there's no glitches. That's because OREs make frame too short to be accepted.

**Comment by kilrah** [comment]
@bsongis Did we change to DMA on master in the end (worth restesting this)?

**Comment by banderson546** [comment]
I've retested this on 2.1.7 and I still see see channels glitching over the trainer link.  It takes
a minute or two before it happens and it lasts for several seconds.

**Comment by kilrah** [comment]
2.1.7 doesn't include any fix for that, it would be on the 2.1.8 nightly. But I jsut had a look and it doesn't seem anything was done on 2.1 yet.

**Comment by LapinFou** [comment]
OTX 2.1.8 is out, but this bug has not been fixed.
Are you planning to fix it for the milestone 2.1.9?

**Comment by banderson546** [comment]
On the same Taranis that generated glitches with OpenTX, I flashed ErSky9X and configured it as an SBUS Trainer.

I did not get any channel  glitching with ErSky9X.

**Comment by bsongis** [comment]
Would you check 2.2? 
Here:
http://downloads-22.open-tx.org/nightly/companion/
And you enable the firmware nightly builds in the Settings to download the latest firmware

**Comment by banderson546** [comment]
I've tried with 2.2.0N300 and SBUS Trainer appears to be broken.  I activate Trainer in Special Functions and control just stays with the Trainer, there is no control from the Student Radio.

**Comment by AloftHobbies** [comment]
Bertrand thanks for digging into this. Would be great to have a fix with the next release as we are looking to expand on the Sbus functions. :)

**Comment by bsongis** [comment]
Yes but this is fixed in 2.2, I just need somebody gives a test, if it works, I will port it to 2.1 (next stable release)

**Comment by projectkk2glider** [comment]
@banderson546 says that 2.2 does not work!

**Comment by bsongis** [comment]
Sorry you are right, I will check later tonight

**Comment by projectkk2glider** [comment]
The cause for this could be:
* we get UART overrun in the middle of SBUS frame (confirmed by #3252)
* we still process such SBUS frame even if it is only 24 bytes long (normal SBUS frame is 25 bytes)
* this frame will have all channels from the missing byte and up pretty well corrupted.

Now, the reason for the buffer overrun:
* on `master`: #3252 says that disabling internal module cures the problem, so this interrupt is taking too much time (occasionally). Remember SBUS speed is 100kBps, character time is 100us.
* on `next` we receive trough DMA so there should be no overrun. Must be some other reason, one could be the issue of `DMAFifo.isEmpty()` in relation to DMA NDTR register. 

Question for @bsongis why do we allow SBUS frames with a length different from 25 bytes?

**Comment by bsongis** [comment]
It should work the same way than the serial port UART3 or S.PORT on Horus!
I am afraid of a collision with external module pulses, as it also uses DMA2_Stream2

**Comment by bsongis** [comment]
Instead I am afraid we never detect the end of the frame with the pop() done in the mixer task, the SBUS fifo is perhaps never empty with the mixer running once every 20ms!

**Comment by KIrill-ka** [comment]
@bsonis, As a temporary fix I changed s.bus source to send truncated 23 byte frames. It did help with channel glitch - bad frames were ignored.

**Comment by bsongis** [comment]
On 2.1?

**Comment by bsongis** [comment]
I need to discuss with @projectkk2glider about the best way to fix it in 2.2

**Comment by projectkk2glider** [comment]
My proposals:
* use DMA2_Stream1 for heartbeat input, this will prevent collision with  DMA2_Stream2.
* call `processSbusInput()` directly in mixers thread every time it is run (every 2ms)
* change the SBUS fame synchronization in `processSbusInput()`, wait for start character, data bytes and valid end byte. Then parse SBUS frame and have more strict checks (especially the length which should always be 25 bytes).

**Comment by KIrill-ka** [comment]
> On 2.1? 
Yes. 2.1.7

**Comment by bsongis** [comment]
I just moved the call to processSbusInput so that it is called every 2ms and it seems to work perfectly now

**Comment by bsongis** [comment]
![sbus](https://cloud.githubusercontent.com/assets/5603504/15251551/439ab0aa-192a-11e6-837b-ee6ec9e01374.png)

**Comment by bsongis** [comment]
The delay is far greater than 2ms, so it's normal it works. I will wait for more tests in 2.2 then I will port the DMA thing to 2.1

**Comment by projectkk2glider** [comment]
I am not completely satisfied. Two more things to do:
* use DMA2_Stream1 for heartbeat input, this will prevent collision with DMA2_Stream2.
* have more strict checks (especially the length which should always be 25 bytes).

**Comment by bsongis** [comment]
Who wants to give some tests before we merge it into 'master'?

**Comment by projectkk2glider** [comment]
We could still have glitches, I think we should only accept SBUS frames with 25 bytes, not 23 bytes as it is now. This is what actually produced weird channel errors when one byte was missing from the SBUS frame. Why do we allow 23 bytes anyway?

**Comment by banderson546** [comment]
I'll give it a test. I don't see it yet though in the 2.2 nightly's.

**Comment by raphaelcoeffic** [comment]
@projectkk2glider I remember wondering about the same as I looked at the code last year. I double checked just now in librepilot & cleanflight. Librepilot checks for the same things you proposed, whereby cleanflight does not check the end-byte.

**Comment by banderson546** [comment]
Thanks Bertrand!
I tested 2.2.0N317 and it is working perfectly on the ground now :)
I will do more testing in the air this weekend.

**Comment by AloftHobbies** [comment]
Yay!! Great to hear, especially if we want to do some more cool things with Sbus. :)

**Comment by LapinFou** [comment]
2 questions:
1. I assume the port in the battery compartment is also impacted by this bug and the fix will also applied to it. Correct?
2. I'm planning to setup a wireless body box on my T+ using the (UART?) port in the battery compartment. Is it possible to achieve the S.Bus trainer mode **AND** used the Spektrum hack module in the JR bay module at the same time?

**Comment by bsongis** [comment]
1. Yes the serial port in the battery compartment is also impacted, it now uses DMA in 2.2 as well.
2. Yes it should work until you open a new issue

**Comment by LapinFou** [comment]
@bsongis 
Thanks !! :smile:

**Comment by banderson546** [comment]
I've tested 2.2.0N317 in the air and it does not
have issues with channels glitching now.

It still has a problem though with the Telemetry
link between the Trainer Radio and the model.

Several times a minute the Trainer Radio announces Telemetry 
Lost-Telemetry Recovered and the Telemetry display
disappears and then comes back.
It only happens when the SBUS channel is up.
If the Student Radio is turned off Telemetry
returns to normal.

**Comment by bsongis** [comment]
Are you sure this alarm comes from the Trainer radio? Are the 2 radios close each other? Is the model close to the Trainer radio?

**Comment by kilrah** [comment]
Try disconnecting only the SBUS wire between the receiver and the master radio, i.e. leaving the receiver powered.
The telemetry lost/recovered is most likely due to the receiver swamping the telemetry reception when it sends its own back, i.e. nothing to do with software, but something that would be solved by physically putting the receiver further away.

**Comment by LapinFou** [comment]
I'm using the same setup of @Ze-baloo with a SBus to CPPM converter (until the issue is fixed).
I was getting lots of telemetry lost/recovered voice message. So I bind the RX in mode 2 (D16 without telemetry). This solved the problem. As Kilrah said, I'm pretty sure the TX part of the receiver is much too close of the internal XJT antenna and create some kind of saturation.

**Comment by AloftHobbies** [comment]
That is odd. If it was swamping, it would be the student's radio that would have the telemetry lost errors, not the instructors. I have never found a second radio or receiver being close to my radio would cause telemetry lost, but I will go test that right now...

Yep just tested and confirmed. It would appear that only the bound receiver being too close causes the swamping issue.. This makes no sense to me, but I thought that might be the case. **Begs the question if something else is going on with the swamping issue.**

**Comment by banderson546** [comment]
I used an extension cable to move the Linker 3 feet away from the Trainer Radio and the 
Telemetry Lost problem with the model does go away. 

I don't see a way to disable telemetry on an X4RSB receiver though.

**Comment by kilrah** [comment]
> That is odd. If it was swamping, it would be the student's radio that would have the telemetry lost errors, not the instructors. 

Nope, the instructor's is the one that has 2 transceivers basically an inch away from each other which is the whole problem. The student radio only has one.

The same problem also sometimes happens when you use both internal and external module together.

**Comment by LapinFou** [comment]
@AloftHobbies 
Hi Wayne,
It would be very nice if you could request to FrSky a firmware for the X4R where the telemetry can be disabled. Otherwise, you will get some issues with your "Linker" product when using a XR4-SB.

**Comment by AloftHobbies** [comment]
Limited testing here (with dead batteries) did not cause this telemetry lost issue.

I would like to test using Mike's firmware and see if we have the same issue then. I am not convinced we have pinned this down yet.

**Comment by ledvinap** [comment]
There is possible problem with some sbus receivers - heartbeat line is connected both to internal and external module. Internal module on Taranis X9D has open-drain output + small resistor in heartbeat signal.
With X8R this works fine, receiver drive strength is large enough to fight heartbeat from internal module (signal is pulled down by about 0.5V).
But with R9D SBUS signal is pulled down considerably(to ~1.5V), at least under threshold of saleae logic analyzer.
This problem is more pronounced in D8 mode, heartbeat is pulled low much longer than in D16 / LR12.

**Comment by ledvinap** [comment]
Another problem with Radiolink X9D (after cutting internal module heartbeat):
Trainer signal returns to zero(low value) for short time (probably one tick, almost always visible on channel display, usually registered by servo).
The pattern is very stable, is is 3 glitches about 1s apart, repeating every 8 seconds.
X9D is in failsafe mode, data are stable (all packets are identical). SBUS packets are send every 13.44ms, delay between packets is 10.48ms, with jitter less than 0.2ms
The frames (failsafe) are:
F0 37 D8 F9 EE 2B E3 36 66 C8 F6 04 0B E0 00 D0 9A 10 02 00 40 08 01 08 00
The glitch happens both with and without failsafe bit set. This is a bit strange, failsafe SBUS packets should be ignored ..

This does not happen when I connect FrSky X8R .. 

Any idea what can be causing this?

Using version 2.1.8

**Comment by ledvinap** [comment]
Ok, the failsafe not triggering is probably caused by X9D sending wrong bit.

**Comment by ledvinap** [comment]
Bisected problem to  #3178. SBUS overrun + ignoring serial port errors is probably causing my problem ...

sbus trainer works fine with https://github.com/opentx/opentx/pull/3410 applied

**Comment by AloftHobbies** [comment]
So the trainer feature works for you now? Regardless of receiver?

**Comment by ledvinap** [comment]
@AloftHobbies : 
It does work with #3410 applied and heartbeat from internal module disconnected.
It may work with heartbeat in original state, I did not test that.

Radiolink X9D receiver failsafe/flag byte is reversed, so 'trainer signal lost' is not reported, but that is not OpenTx problem (I modified it to accept both bits as failsafe, but that's only hack)

**Comment by projectkk2glider** [comment]
Good news, so this issue should be fixed once the 2.1.9 is released.

**Comment by ledvinap** [comment]
I modified my X9R to disable PA (rewiring PA enable signal), so I have no issue with 'Telemetry Lost problem' that is also mentioned in this issue..

It may be better to  catch parity/overrun errors and ignore corrupted SBUS frames..

**Comment by toomanytoys** [comment]
I just setup a Linker, Taranis+ Master, original Taranis trainer, D4R-II, CPPM (27ms). 1 meter apart got low/critical RSSI warnings. I assume it was the Trainer~Linker as the wing was flying OK. Just wondering if swamping may be an issue, has anyone tried to set the Trainer to range check mode to lower the RF output. Anyway my first test (delta wing, D4R-II, 27ms, also) didn't really work, I don't think the Elevon Mix was transposed correctly, if at all. I'll try a Bixler next test. Early days yet amyway.

**Comment by LapinFou** [comment]
Here is a tip concerning the 'trainer signal lost. Indeed with a wireless buddy box you don't get such information.
Here is my solution (salve radio is also a Taranis+):
1. First, the RX's failsafe in the master radio is set to 0% for all channels.
2. I'm sending **MAX -100% on the channel 8**
3. Then on the master radio, I added LS to detect
L1: a<x TR8 -80%
L2: AND L1 SH↓
4. Then I'm using L2 to play audio announcement and enable the trainer special function.

In fact, I'm using more complex LS to detect if the slave signal is present or not (play audio announcement) + detecting a lost of signal or recovering signal during the training session (another audio announcements). But the example below is just to explain the idea.

**Comment by ledvinap** [comment]
@LapinFou : SBUS protocol frame has bit that is set when RX is in failsafe mode and OpenTX handles this correctly (at least that works for me)

**Comment by kilrah** [comment]
Loss of PPM also would be detected if you set the receiver's failsafe to "no pulses".

**Comment by LapinFou** [comment]
Thanks to both of you. :+1: 
In my case, I used this: http://www.rcgroups.com/forums/showpost.php?p=33036059&postcount=9
In others words, I don't use the special function trainer and there is no way to detect a 'trainer signal lost'. So, this is my solution combined with "Updated Trainer Quick Takeback".
I should have be more precise. :smile:

**Comment by kilrah** [comment]
Same, all the TRx mixes should deactivate themselves when trainer signal loss is detected

**Comment by ledvinap** [comment]
@LapinFou : Trainer mode icon and connection/disconnection messages are unrelated to trainer special function. It should be superset of trainer enabled/disabled

Also when used as input, TRx will keep it's last value after trainer disconnect (it is set to 0% when used directly in mixer or trainer special function)

**Comment by LapinFou** [comment]
OK. I didn't notice this point. Thank to both of you. I will do some more testing on the bench.

**Comment by LapinFou** [comment]
OK. I don't want to be too much off topic, however the post mentioned below explain how to enable a pseudo trainer mode by hitting once SH↓, then the instructor will take back the control by moving any gimbals (excepted the throttle). So, the Ail, Rud, Elev must be monitored, which mean your proposed solution will not work. Indeed in the classic trainer mode Ail, Rud, Elev are replaced with the associate TRx channels.
Anyway, thanks a lot for your clarification.

**Comment by bsongis** [comment]
I realize that I still didn't port this fix to 2.1
We are releasing 2.1 right now, it will be there in the next release. I will backport the fix.

**Comment by LapinFou** [comment]
FYI, this bug is declared as fixed in the "Firmware changes...". However if I understand well it is not. Correct?

**Comment by bsongis** [comment]
Well true. I prefer the correction we did in 2.2 (we use the DMA, far less interrupts), but if it works like this I won't change anything in 2.1

**Comment by LapinFou** [comment]
Sorry but I'm lost. SBus issue bas been fixed or not in 2.1.9 ?

**Comment by bsongis** [comment]
Yes it should be fixed. But in 2.2 the fix is even better :)

**Comment by LapinFou** [comment]
Arf !! :smile: Can't wait for the 2.2.
Thanks for answering.

**Comment by LapinFou** [comment]
Hi folks,
I tried the S.Bus through the serial port in the battery compartment. When I was doing some testing on the bench, the same problem occurred again when the training mode was active. It was difficult to reproduce it during the training mode, however I found a sequence to create the problem easily. 
I'm using a X8R (non-EU) binded in mode 2 (no telemetry).
On the student radio, I'm using this setup:
- Internal XJT
- D16 mode
- CH.1-8
- Rx number 1
- Failsafe is set to "No pulse". It seems the bug will happen faster with "no pulse" than with a setup with all channels to 0%.

On the master radio, I used the wiring shown on the attached picture.
![img_1482](https://cloud.githubusercontent.com/assets/1685030/18678016/ff889f16-7f5a-11e6-9310-c63b763a2c27.JPG)

Both radios are running OTX2.1.9 (opentx-taranisplus-timer3-lua-mixersmon-nooverridech-fr-2.1.9.bin)

I've also been able to make a video of the master radio: https://youtu.be/BkQ3tlWOakA
Check the channel 10. The setup is:
CH10: TR8 ratio(+100%)
 
On the student radio the channel 8 setup is:
MAX Ratio(-100%) [Active]

To create the bug, I'm moving the gimbal of the student radio, then switch it off. Then switch it ON and moving the gimbals and switch OFF again... and so on.

This will create the condition visible in the video. Once again, this is a procedure to create the problem, but keep in mind that the issue happen during a classic training session (on the bench).

I had no chance yet to test the same thing using the JR bay. But, I guess the same thing will happen.

**Comment by kilrah** [comment]
That suggests once again that the issue is not with OpenTX, but RF swamping. Can you put an extension cable so you can locate the X8R a good 50cm-1m away from both radios?

**Comment by ledvinap** [comment]
Do you have version with  #3410  applied?

**Comment by LapinFou** [comment]
I can test this, but did you noticed that the X8R is in mode 2 (**no telemetry**)? So, no power should come out of the X8R. Or, did I missed something?

**Comment by LapinFou** [comment]
@ledvinap: As far I understand, the #3410 has not been ported yet on the OTX2.1 branch.

**Comment by ledvinap** [comment]
@LapinFou : Then it's most probably causing glitch you noticed ... (usually pair of invalid reading about 1 second apart)

**Comment by kilrah** [comment]
@LapinFou Yes but it could be the opposite, the X8R losing reception because of the master radio blaring just next to it.

Or the (different) fix that was done in 2.1 than in 2.2 does not work... if it still fails with a bigger distance we'll know it's the latter.

**Comment by LapinFou** [comment]
@kilrah: OK but, in the video, you can hear a lot of "disconnect/disconnect" and you can see that the CH10 is glitching during several seconds. This is not an expected behavior since the X8R, at this moment, is in failsafe mode. So, I really doubt the RF is anything to do. To me, it looks like the S.Bus frame is not correctly interpreted or synchronized for some reason. I know I'm not helpful, but this is my gut feeling.
Anyway, I will test with a 1m wire ASAP.
I hope when thing will calm down after the OTX2.2 release, you will have the time to implement #2498 :smile:

**Comment by LapinFou** [comment]
OK. I have been able to test with a 1.20 meter cable. I still got the same problem.
Again I used the serial port in the battery compartment.

Here is a pic of the setup (I can upload a video if required):
![img_1494](https://cloud.githubusercontent.com/assets/1685030/18833153/9bfc0d4a-83ef-11e6-924e-971a7ec72fa7.JPG)

**Comment by ledvinap** [comment]
@LapinFou: Just try firmware with #3410, you will see it solves your problem ...

**Comment by kilrah** [comment]
Well it doesn't seem so since that's what he's doing... i.e the fix used in 2.1 (which is different from the one in 2.2) isn't efficient.

**Comment by ledvinap** [comment]
Sorry, missed that 2.1.9 is out. I'll test it, but I don't have AT9 now, will take some time
