### ISSUE TITLE
io.read example please?

### ISSUE THREAD

**Issue by sbright33** [opentx/opentx#3005]
I've tried everything I can think of.  Got either an error or no results.  The file looks like this:
0 1 2 3 
3 4 5 6
3.1 4.5 5.6 7.8

Tried
a=io.read(fh,b)
a=io.read(b,"xall")
a=io.read(fh,"xall")
a=io.read("xall")
a=io.read(b)
a=io.read(fh)

Had to type x instead of * for Github

I guess it's not a bug, I just need a good example to test on PC Companion Sim?
Has anyone used this function even 1x in Companion?
io.write works nice.

**Comment by projectkk2glider** [comment]
Only the form `read(fd, n)` is supported in OpenTX, see https://github.com/opentx/lua-reference-guide/issues/3
