### ISSUE TITLE
REQ- ability to calibrate FLVSS individual cell readings

### ISSUE THREAD

**Issue by virtual812** [opentx/opentx#3007]
I have recently purchased 3 FLVSS sensors intending to use 1 in a 4s model and 2 in a 12s model.
I have found the individual cell readings to be inaccurate by almost as much as 100mV.
Can an option be added in OpenTX to apply a calibration value to each cell like it is available for A1 & A2?

Thanks.

**Comment by projectkk2glider** [comment]
I give very little chance to this request for several reasons:
* extensive rework of existing EEPROM structure
* more usage of EEPROM per model
* there really should be no need for this, the sensors should be calibrated by the factory (looks like they are not)
* is the resolution of the received voltage enough to apply any kind of correction and get useful result?
* there is also a workaround available: custom Lua script that fixes each cell value.
