### ISSUE TITLE
9xr128 - mavlink build (.hex) missing

### ISSUE THREAD

**Issue by flegmatoid** [opentx/opentx#3009]
OpenTX Companion 2.1.3 fails to download opentx-9xr128-mavlink-en.hex
I can confirm its missing in http://downloads-21.open-tx.org/firmware/binaries/
Is Mavlink build option not supported anymore? If So, that has to be reflected in Companion.

**Comment by projectkk2glider** [comment]
We fixed 9X in #2905, perhaps there is similar issue for 9xr128

**Comment by bsongis** [comment]
It seems fixed, right?
