### ISSUE TITLE
global variable doesnt work in OUTPUTS

### ISSUE THREAD

**Issue by martinkindl83** [opentx/opentx#3010]
Using Global variables in OUTPUTS doesnt work. It uses -100,100 value instead.

**Comment by kilrah** [comment]
In what field(s) of the outputs page??

**Comment by martinkindl83** [comment]
In fields for min and max. Fields that are by default - 100 and 100.
M.

**Comment by kilrah** [comment]
Can't reproduce in the simulator, it works as it should.
Please upload your settings somewhere and post a link.

**Comment by projectkk2glider** [comment]
We also don't know which version of OpenTX he uses.

**Comment by martinkindl83** [comment]
sorry guys,
i did test it on different PC and it works.

Reinstalled companion on the original (with the non working global
variable) and it works now.
