### ISSUE TITLE
Taranis timer

### ISSUE THREAD

**Issue by GadgetMart** [opentx/opentx#3014]
I have tried numerous different firmware versions on my Taranis Plus.
Currently 2.1.3

The timer has never worked as I imagined it to.

> Set countdown to 'voice' - everything OK
> Set countdown to 'Beeps' - I get 10 seconds, 10 seconds repeated every second for the last 10 secs.
> Set countdown to Haptic - I get 30 secs, 20 secs and then no buzz?

Thanks.

**Comment by GadgetMart** [comment]
Just changed haptic from 'alarm' to 'no key'
It now works during haptic countdown, but I still get '30 seconds' '20 seconds' announced verbally.

**Comment by hrenz** [comment]
Hy,

and only  call  the  min voice without sec
