### ISSUE TITLE
[Bug][Companion 2.1.3] Changing the trainer port doesn't trigger the "need save" flag

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#3016]
Hi folks,

If you change the trainer mode, Companion doesn't detect that the EEPE has been modified.
![trainer](https://cloud.githubusercontent.com/assets/1685030/10857099/5b38bf40-7f4c-11e5-87f7-595fc75a09d0.png)

**Comment by projectkk2glider** [comment]
Thanks for reporting.
