### ISSUE TITLE
Model Setup Failsafe FrSky XJT (D16) and (LR12) Channel Names

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#3021]
Would be helpful is the Channel Names from Outputs tab are displayed (if entered) in place of channel numbers especially when Mode is Custom in Companion.
Taranis X9d Plus and Companion 2.1.3

**Comment by kilrah** [comment]
Good idea. That actually pointed out a little ommission in a recent fix too.

**Comment by elecpower** [comment]
@kilrah Just downloaded 2.1.5. Thanks for you and the team's efforts on continuing to improve a great product.
