### ISSUE TITLE
Companion Flight Modes, Logical Switches and Special Function Delete Action

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#3026]
Just a time saving feature with the addition of right mouse menu item to Delete/Reset the highlighted item to its defaults.

For Flight Mode it is the open FM tab and for LSs and SFs it is the highlighed row.

With us sharing model files or even repurposing our own there are times where there are many elements which are not required for the new model. Some will have no effect if old artefacts exist but others no so. Also results in cleaner model settings as we tweak over time. 

With ongoing development entries may become redundant as they are more easily handled by new features so you would like a quick tidy method.

Keep up the good work.

Taranis X9D Plus with v2.1.3

**Comment by projectkk2glider** [comment]
I suggest we wait for #2861 to be finished before tackling this.

**Comment by fraternl** [comment]
A great time saviour...
I had to completely redo a setup lately. I wish I had it then.

**Comment by elecpower** [comment]
Also please add Telemetry Senors. When changing from Calculated to Custom and back to Calculated the Calculated row displays the old values.

**Comment by projectkk2glider** [comment]
Well, the LS and SF already have a right click context menu (right click on `LS` label for example) where you can select Delete. So that is already done.

We need similar for:
* Flight mode
* Telemetry sensor (might be sensible to wait until #2781)
* Output

**Comment by elecpower** [comment]
Appologies on not identying the existing context menus on LS and SF. I was over the first data field of each when right clicked rather than the labels. Great to see progress on the others.
