### ISSUE TITLE
Changing play track to Override CH1 only hides the "enable field", it doesn't clear it

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3027]
When I want to clear a special function I'm changing it to "Override CH1"  with a value of 0 and a "----" switch. 
If I do this with a "Play track" that has its "Enable" set to 60s this value is not shown anymore, but it's still there. 
I was doing a "model compare" and there this field showed up.

When I change it back to "Play track" this value appears again.
I don't know how far this hidden unused propery carries, but if it survives a back and forth from the radio this behaviour is unwanted.

It's a minor issue, but I think it would be better if that value is really cleared although it's not applicable for "Override CH"

Keeping values is probably happening in other things too.

**Comment by kilrah** [comment]
Version? On companion or on the radio?

**Comment by fraternl** [comment]
Today's nightly.... On Companion.

**Comment by fraternl** [comment]
I just changed an LS from "a<x" to "Edge"
The behaviour is not the same.
"delay" is not applicable for Edge, but here this value is not hidden but greyed out.

I believe it's better to clear it.
Do you agree?

**Comment by fraternl** [comment]
![ax](https://cloud.githubusercontent.com/assets/8692856/12306155/ad460d48-ba38-11e5-9d79-866a44a17367.PNG)
![edge](https://cloud.githubusercontent.com/assets/8692856/12306168/b637b19a-ba38-11e5-991a-e0992341948f.PNG)
