### ISSUE TITLE
EU / none-EU Firmware

### ISSUE THREAD

**Issue by lolu971** [opentx/opentx#3030]
Hi,
I had a Taranis and just received my new Taranis-plus with the pre-installed firmware 2.0.12-EU identified easily under the software version page.
I've upgraded to 2.1.15 by sellecting EU build options under Open-TX companion 2.1. Load file came with opentx-taranisplus-eu-fr-2.1.5 BIN-file, everything great!
Once implemented into the radio, the version noted is 2.1.15 instead of 2.1.15-EU which is important to have in order to insure compatibility with RX.
Thanks for fixing this small but sensitive missing information.
Best regards and congratulations Guys for your amazing job

**Comment by kilrah** [comment]
If you have "eu" in your filename then you have the EU version.
Anyway the only thing it does is hide 2 settings from you in the menu, nothing actually behaves differently, the distinction is in the RF module, not in opentx.
