### ISSUE TITLE
[opentx] [2.1.5] Set date and time not working

### ISSUE THREAD

**Issue by glini** [opentx/opentx#3031]
Radio 9RX Pro, opentx build 2.1.5;I can not set date and time. Display says 'Set menu long', but long press doesn't change anything. Time stays 00:00:00, date 01-Jan-2000. I have no tx-modul inserted, maybe it's because of this?

**Comment by bsongis** [comment]
Was it ok in 2.1.4?

**Comment by bsongis** [comment]
"Set menu long"? Are you in the radio setup page?

**Comment by kilrah** [comment]
> Display says 'Set menu long'

Then you're on the wrong screen. Probably the VERSION screen, which is telling you the date/time the firmware was built and obviously can't be changed.

**Comment by glini** [comment]
Radio setup page.  Right Column, Date-Time. In next page (Date-Time) I can change Sec., Min., Hour, Date, Month, Year. New settings reset when I leave page, long pressing Menu does not work.

**Comment by kilrah** [comment]
Can you check with the original ersky9x firmware if it works well? Some have already had defective chips.

**Comment by glini** [comment]
Checked with original ersky9x; working without problem.

**Comment by glini** [comment]
Did a complete reinstall with companion. Seems this fixed the problem. Don't know what went wrong before, but now it works.

**Comment by bsongis** [comment]
Ok, this is strange!
