### ISSUE TITLE
[Companion]installation fails on Ubuntu 14.04.3

### ISSUE THREAD

**Issue by MicheleVilla** [opentx/opentx#3033]
XUbuntu 14.04.3 64 bit
during installation by .deb show error messagge:
needed libstdc++6 >=4.9
available 4.8.4

**Comment by bsongis** [comment]
I take it

**Comment by bsongis** [comment]
Is it better now? I compiled on Mint17

**Comment by MicheleVilla** [comment]
Download link 
http://www.open-tx.org/2015/11/05/opentx-2.1.5/ ?

from this same error
Try also on other PC with Kubuntu 14.04.3

**Comment by projectkk2glider** [comment]
@MicheleVilla  Try it now, I have just uploaded a new package (under the same name).

**Comment by MicheleVilla** [comment]
Very well
works fine!

Thank you

**Comment by hrenz** [comment]
Hy,
yes deb packet at ubuntu 14.04  works well now!

Is it possible to get it at nightly builds too?
