### ISSUE TITLE
 Discovery new sensor with D4r II

### ISSUE THREAD

**Issue by PieroCo** [opentx/opentx#3038]
Taranis X9D opentx 2.1.5
Why the function "discovery new sensor" finds the sensors A1 and A2, but I have only one battery connected directly to the receiver?
is it normal?
![screenshot-2](https://cloud.githubusercontent.com/assets/7857600/11021027/3900f49e-8634-11e5-9ea4-413572a81a42.png)

**Comment by hrenz** [comment]
A1 is internal Rx Voltage
A2 is your RxBatt

**Comment by PieroCo** [comment]
I connected the battery directly to the receiver. The internal voltage is  equal to external. I should have only A1

**Comment by projectkk2glider** [comment]
Please use forums for such questions. The A1 and A2 are sent no matter if you connect anything to it or not. If you do not need it, just ignore it.
