### ISSUE TITLE
model memo text space

### ISSUE THREAD

**Issue by Nihonski** [opentx/opentx#3048]
When programming modells in the companion, the length of names is quite limited. Thats ok, I think its the best choice for the small transmitter displays.
However it would be convenient to have some text space in the companion for each model, where I can leave my own memos, what I have done, what I changed, etc. for every specific model. 
This text space does not need to be downloaded into the transmitter, but if so, could be just one additonal screen to be accessed from the model menu. Maybe enough to be seen on the transmitter, but editing only by companion.
Would be " nice to have feature".

**Comment by kilrah** [comment]
Impossible with the current file format. There is already an open issue about improving that.

**Comment by projectkk2glider** [comment]
It's #2339
