### ISSUE TITLE
[Feature Request][OpenTX 2.1.5] COM port in battery compartment: CPPM trainer mode

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#3049]
Hi folks,

The new Sbus/CPPM trainer modes are fantastic. Being able to do some wireless trainer is nice.
I discovered this tiny 8 channels receiver: [MicroFrX](http://www.fisselrc.com/microfrx/)
With some small extra electronic parts (to adapt the power supply), it will perfectly fit in the battery compartment. However, the COM port currently supports only the SBus protocol. Would it be possible to add the CPPM mode?

Thanks,
Seb

**Comment by kilrah** [comment]
Duplicate of #2498

**Comment by LapinFou** [comment]
Sorry. I did a search, but found no relevant results. I'm very bad choosing the good keyword :sweat_smile:
