### ISSUE TITLE
Add the warning message to CLI option

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#3050]
As per https://github.com/opentx/opentx/issues/3000#issuecomment-152249468 we should add some kind of warning to the `cli` firmware option in Companion to notify/warn users of potential risk.

**Comment by bsongis** [comment]
I think we should split the CLI option from the DEBUG option.
In the future the CLI could be used for EEPROM transfer, commands from Companion, switch to bootloader mode etc.

**Comment by bsongis** [comment]
Side note: this is what I did in the Horus branch if I am not mistaken

**Comment by projectkk2glider** [comment]
>I think we should split the CLI option from the DEBUG option.

Good idea!

**Comment by Sacre100** [comment]
> I think we should split the CLI option from the DEBUG option.

Yes ! For (some) end user, CLI is useful to debug LUA script directly on the radio using print(...) , however, if CLI doesn't reduce too much the available memory for LUA.

**Comment by projectkk2glider** [comment]
The Lua print() is currently dependent on DEBUG option, so we have to split that one too!

**Comment by mpaperno** [comment]
CLI can now be enabled w/out DEBUG (and all associated tracing).
