### ISSUE TITLE
Companion Simulator replace generic identifiers with user defined names

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#3057]
To take advantage of the features of the model configuration how about bringing the user defined names, where defined, to the Simulator.

Outputs tabs substitue CHn
GVars tab substitute GVn and FMn
Switches - though likely not to be practical due to layout crowding

(Tarnanis X9D Plus - Companion 2.1.5 - Win 10)

**Comment by kilrah** [comment]
Don't understand, on the outputs the name is on the same line as the rest, on the GVARs tab the GVAR name is also on the line right there... FM no room to replace them.

**Comment by elecpower** [comment]
Sorry if not making myself clear so if pictures speak louder than words then...
![sim fmodes](https://cloud.githubusercontent.com/assets/15316949/11448137/6f5346c4-95a6-11e5-9c27-52f9ef867864.jpg)
![sim gvars](https://cloud.githubusercontent.com/assets/15316949/11448138/78edf01c-95a6-11e5-848b-e333848a771a.jpg)
![sim outputs](https://cloud.githubusercontent.com/assets/15316949/11448139/78eddbf4-95a6-11e5-9b8a-d21870307ad1.jpg)

**Comment by elecpower** [comment]
There would be less need for this if #3056 were implemented though I still feel it worthwhile in that it brings all information into the sim.
