### ISSUE TITLE
Wizard for plane, and probably others does not draw dotted lines.

### ISSUE THREAD

**Issue by u8mydog** [opentx/opentx#3061]
In wizard\plane.lua, every:
lcd.drawLine(xx,xx,xx, LCD_H, DOTTED, xx) 

should be changed to:
lcd.drawLine(xx,xx,xx, LCD_H-1, DOTTED, xx)

Otherwise, the dotted line is not drawn. Something changed between 2.0.x and 2.1.x because the dotted line is drawn in the older version.

**Comment by projectkk2glider** [comment]
True, drawing a line with either starting or end point outside the lcd dimensions will not draw anything #2929
