### ISSUE TITLE
Close any Lua open files when radio powers off

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#3062]
A script might have a file open (by using io library). That file should be closed before the radio powers off.

**Comment by projectkk2glider** [comment]
@bsongis I think you *optimized* io library a bit too much :grin:  The metatable for file objects `flib[]` should be registered with at least one method `__gc` which will close the open file in such cases.

**Comment by bsongis** [comment]
That's very possible I forgot it!

**Comment by indavis** [comment]
Just wanted to say Thanks for looking at this. The file io is a game changer as we can write our own log files. Until this is fixed, my workaround is open file, write data, close file. Probably more file io than necessary, but seems to be keeping my files safe and I haven't seen any speed issues (at least with my sd card).
