### ISSUE TITLE
Joystick Switches with 3 States

### ISSUE THREAD

**Issue by Muenze** [opentx/opentx#3064]
Hi, most of my switches on my Taranis X9D have 3 states, -100, 0, 100, but the joystick emulation maps the channels 9-18 to buttons with 2 states, is it possible to map switches to 3state buttons or switches?
I use the Taranis als Joystick with Aerofly RC7, so I need a lot more 3 state switches than simple buttons

**Comment by kilrah** [comment]
3-state buttons don't exist in the joystick spec.

You must either use a proportional channel or combine 2 switch channels.
