### ISSUE TITLE
ar9x, play val A2 problem

### ISSUE THREAD

**Issue by hildan76** [opentx/opentx#3069]
i use ar9x board.
and i set,

  SPECIAL FUNCTION
   TRN Play Val A2 -

result,
if A2 is 7.0v, sound is "seven"
if A2 is 7.1v, sound is "seven point six"
if A2 is 7.2v, sound is "seven point seven"

i think, playing sound is real value +0.5
check please.

**Comment by projectkk2glider** [comment]
If you are on 2.1 then you need to install a sound pack for 2.1!

**Comment by hildan76** [comment]
yes, i use 2.1 sound pack.
firm ware version 2.1.6
and sound pack is "http://voices-21.open-tx.org/opentx-ar9x/en/english.zip" <== that.
ar9x is no sound pack for 2.1 version.

**Comment by kilrah** [comment]
That link had a 2.0 pack. Download again.

**Comment by hildan76** [comment]
thank you kilrah.
have nice day.
