### ISSUE TITLE
ar9x, companion sam-ba configuration problem

### ISSUE THREAD

**Issue by hildan76** [opentx/opentx#3070]
no "at91sam2xxx-ar9x" in "ARM mcu"
check please.

**Comment by projectkk2glider** [comment]
I have no idea what you are writing about. @hildan76 please elaborate.

**Comment by kilrah** [comment]
Probably refers to flashing an AR9X baord using sam-ba.
In which case it's irrelevant, it uses the same 3s8 as the 9XR so just choose that. 
Only labelling could maybe be improved.

**Comment by hildan76** [comment]
kilrah.
that is right.
can you add "s38 ar9x"?
this is not important issue.
just be confused.
thanks.
