### ISSUE TITLE
ar9x, LOGICAL SWITCH, V2,  impossible decimal value.

### ISSUE THREAD

**Issue by hildan76** [opentx/opentx#3071]
firmware version 2.1.6

i set

LOGICAL SWITCH L1
Func a<x
V1 A2
V2 7
AND Switch ---
Duration ---
Delay ---

i can't input decial value for V2
A2 set is below

SENSOR4 8.2V
Name A2
Type Custom
ID F103 25
Unit V
Precision 0.0
Ratio 24.9
Offse 0.0
Auto Offset □
Positive □
Filter ▣
 Persist. □
Logs ■

check please.

**Comment by kilrah** [comment]
Can't reproduce. You probably forgot to set precision. 

![screenshot-2](https://cloud.githubusercontent.com/assets/6065069/11169167/62019246-8bc9-11e5-8076-0a9d81825316.png)
![screenshot-3](https://cloud.githubusercontent.com/assets/6065069/11169168/637397be-8bc9-11e5-92a8-31ed901f7ebd.png)

**Comment by hildan76** [comment]
precision is 0.0

i was wrote
↓

A2 set is below

SENSOR4 8.2V
 Name A2
 Type Custom
 ID F103 25
 Unit V
 Precision 0.0
 Ratio 24.9
 Offse 0.0
 Auto Offset □
 Positive □
 Filter ▣
 Persist. □
 Logs ■

**Comment by hildan76** [comment]
my simulator had same problem.

![screenshot-1](https://cloud.githubusercontent.com/assets/15857394/11169300/f4d842cc-8bf6-11e5-9cf4-0ba9cf135773.png)
![screenshot-2](https://cloud.githubusercontent.com/assets/15857394/11169301/f4dc5574-8bf6-11e5-9c14-e71a955a5e3e.png)

and, real video is below.

**Comment by projectkk2glider** [comment]
@hildan76 Any chance you have two (or more) sensors named "A2"?

**Comment by kilrah** [comment]
I know that is what you wrote... but here it works, both on the simulator and on the radio, and the problem would match with Precision being set to 0.--.

Also, the LS doesn't show the "V" unit, so my guess is you have 2 sensors named "A2" and you chose the wrong one.

**Comment by hildan76** [comment]
plese check this video.

https://youtu.be/j0rOGSzUBoY

**Comment by projectkk2glider** [comment]
@hildan76 please upload your EEPE somewhere and paste a link here.

**Comment by hildan76** [comment]
![ar9x_v2problem bin](https://cloud.githubusercontent.com/assets/15857394/11169628/f750ce08-8bff-11e5-8c04-825d7d04762e.jpg)
fds

**Comment by projectkk2glider** [comment]
Confirmed in Companion simulator. There is some kind of problem with the units lookup in the logical switch setup page.

**Comment by projectkk2glider** [comment]
The lookup does not take in account that every telemetry value has three values (current, min, max) and just goes to the next value's unit.
