### ISSUE TITLE
Taranis x9d plus not recognized by Companion21

### ISSUE THREAD

**Issue by ice00** [opentx/opentx#3075]
If I plug my Taranis X9D plus radio into Linux (Fedora 21) I get those from kernel:

Nov 15 21:14:43 host-7826-93-122 kernel: [41135.703091] usb 6-2: USB disconnect, device number 2
Nov 15 21:15:02 host-7826-93-122 kernel: [41154.874016] usb 6-2: new full-speed USB device number 3 using uhci_hcd
Nov 15 21:15:03 host-7826-93-122 kernel: [41155.248066] usb 6-2: New USB device found, idVendor=0483, idProduct=5710
Nov 15 21:15:03 host-7826-93-122 kernel: [41155.248073] usb 6-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Nov 15 21:15:03 host-7826-93-122 kernel: [41155.248077] usb 6-2: Product: FrSky Taranis Joystick
Nov 15 21:15:03 host-7826-93-122 kernel: [41155.248080] usb 6-2: Manufacturer: FrSky
Nov 15 21:15:03 host-7826-93-122 kernel: [41155.248083] usb 6-2: SerialNumber: 00000000001B
Nov 15 21:15:03 host-7826-93-122 kernel: [41155.258162] input: FrSky FrSky Taranis Joystick as /devices/pci0000:00/0000:00:1d.0/usb6/6-2/6-2:1.0/0003:0483:5710.0003/input/input14
Nov 15 21:15:03 host-7826-93-122 kernel: [41155.258569] hid-generic 0003:0483:5710.0003: input,hidraw1: USB HID v1.11 Gamepad [FrSky FrSky Taranis Joystick] on usb-0000:00:1d.0-2/input0
Nov 15 21:15:03 host-7826-93-122 mtp-probe: checking bus 6, device 3: "/sys/devices/pci0000:00/0000:00:1d.0/usb6/6-2"
Nov 15 21:15:03 host-7826-93-122 mtp-probe: bus: 6, device: 3 was not an MTP device

It seems that the device is not the one that Compaion use for Taranis.
I use Companion compiled in 64 bit from source.

The radion is equipted with:
opentx-x9dp-v2.0.9.2

Thanks

**Comment by projectkk2glider** [comment]
Learn how to use the Bootloder mode, http://open-txu.org
