### ISSUE TITLE
we made the Korean soundfiles. upload please.

### ISSUE THREAD

**Issue by hildan76** [opentx/opentx#3082]
we made the Korean sound files for opentx 2.1.

can you upload at open-tx.org?

if it is possible,
Mail addresses for sending the files?

**Comment by bsongis** [comment]
I downloaded it thanks, now I have to add the glue to allow the users to download it from Companion and select it on the radio.

**Comment by bsongis** [comment]
Unless somebody wants to take it before me?

**Comment by bsongis** [comment]
Does the korean grammar look like english grammar? It would mean we don't need a tts_ko.cpp ?

**Comment by hildan76** [comment]
i don't know about tts_ko.cpp
i am not programmer.
i am mechanical engineer and rc mania.  ^^
we made just wav files.
copy to sounds/en and sounds/en/system on sd memory.
really need a tts_ko.cpp???

**Comment by projectkk2glider** [comment]
What Bertrand meant is this: a number 75.6 is played differently in different languages. For example in English: seventy five point six, in other languages the order can be different. 

If numbers are played well with your language pack and English language settings that means that we don't need to add a special grammar file for Korean.

**Comment by hildan76** [comment]
sorry.
i was think that just need sound files.
but, now i think it is difficulty.
so we more think about it.
i want close now  this issue.
but, we try again later as soon as.
thanks.
