### ISSUE TITLE
ar9x, no works navigation encoder switch.

### ISSUE THREAD

**Issue by hildan76** [opentx/opentx#3086]
no option "encoder switch" in companion for arm board.
but, simulator have option "RotEncNavig" in RADIO SETUP.
transmitter no have this option.
finally, no work navigation encoder switch.
check please.

**Comment by bsongis** [comment]
Who has the board? I don't!

**Comment by kilrah** [comment]
I do, but no encoder.

**Comment by pierrotm777** [comment]
See here please !
http://www.rcgroups.com/forums/showthread.php?t=2479552

**Comment by hildan76** [comment]
i know about ar9x and encoder.
http://www.thingiverse.com/thing:1021368 <== this thing is my design.

just, opentx not support encoder.
i am talk about that.

**Comment by kilrah** [comment]
And what I mean is that I do not have an encoder to do any testing with if we want to try and add it ;)

**Comment by hildan76** [comment]
buy it!!! haha
another method,
er9x and sky9x is support encoder.
please, check opened source code of er9x, sky9x.
and apply opentx code.
i think, you already have an code.
you need only check option for compile.
really is it impossible?
