### ISSUE TITLE
Horus Test Next Date 21.11. No internal HF-Modul

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#3088]
Hy,

Horus Development improvement is fine!

Testing latest Horus Next from 21.11.
Only External RF-Modul, No Internal RF-Modul  at UI-screen
![snapshot_06](https://cloud.githubusercontent.com/assets/6217896/11317160/27b7ffe0-9023-11e5-8f8c-ee8b9121bca3.png)

**Comment by kilrah** [comment]
Irrelevant. 
Internal RF will work differently from past systems.

**Comment by hrenz** [comment]
ok
