### ISSUE TITLE
[OpenTX 2.1.6] "No Impulse" on X8R seems to be not working

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#3099]
Hi folks,

In order to create a wireless buddybox (same goal as the "Linker" sold by Aloft), I have done this setup inside the JR module bay of the master radio:
![img_1285](https://cloud.githubusercontent.com/assets/1685030/11362334/32d39462-9293-11e5-96d6-0e1fef6f7827.JPG)
A X8R binded in D16 & Mode 2 (= no telemetry) → S.Bus to CPPM converter → heartbeat pin
The **master/teacher radio** is configured as followed:
![tmp](https://cloud.githubusercontent.com/assets/1685030/11362788/1c8ad118-9296-11e5-9ada-a3db42c5e13c.png)
The **slave/student radio**  is configured as followed:
![tmp](https://cloud.githubusercontent.com/assets/1685030/11362386/8152de86-9293-11e5-8b56-bcd35235ce3b.png)

This setup is working perfectly. FYI, the master RF is not perturbed anymore by the telemetry feedback of the X8R (binded in mode 2). I had some RSSI warnings with the flying model on the master radio when using a X4R/CPPM setup (probably the telemetry feedback of the X4R was too close of the internal RF).

If I switched off the slave radio, I'm expecting the X8R going to **no pulses** failsafe mode. Thus, the master radio will play the "trainer link lost" voice announcement.
Unfortunately it is not the case. Looks like the X8R is going in **receiver** failsafe mode. Indeed if I chose **receiver** in the slave radio, I will get the same result as **no pulses**.
The XJT and X8R have been flashed with the latest non-EU firmwares.
I'm not sure where the problem is coming from, it can be:
* S.Bus to CPPM converter which doesn't translate correctly the failsafe flag
* The X8R which got a problem (I will try with another one in the incoming days)
* Can be an OpenTX bug, since choosing **no pulses** or **receiver** failsafe mode on the **slave/student** radio generates the same result on the **master/teacher** radio.

**Comment by kilrah** [comment]
"No Pulses" only works for the servo outputs, it's irrelevant for the SBUS output. 

It's the SBUS to PPM converter that AFAIK has no other option than to hold positions on failsafe.

**Comment by LapinFou** [comment]
OK. Fine. :smile: 
However there is something weird:
* Changing the failsafe settings will change the behavior when the slave TX is switched off.
* With **No Pulses**, the SBUS to PPM converter doesn't hold the value. Something else is happening.
* When I used the X4R setup (with CPPM software), the **No Pulses** was working fine and I was also getting the voice announcement when losing the link.

So according yours explanations, the SBUS protocol doesn't support the **No Pulse** failsafe mode?

**Comment by kilrah** [comment]
> the SBUS protocol doesn't support the No Pulse failsafe mode?

Correct.

**Comment by LapinFou** [comment]
Thanks for answering.
It is perfectly clear now.
:smile:
