### ISSUE TITLE
More swedish translation issues

### ISSUE THREAD

**Issue by HakanBastedt** [opentx/opentx#3113]
We have found some cosmetic issues with the swedish translation in se.h.txt
and also an issue with the labelling in telemetry screen setup which has to be fixed.TR_VTELEMSCREENTYPE for CPU_ARM has four fields, but not in the swedish version, there are only two.

If it is okay with you I can fix this and give it a try with the github branch and all that.

**Comment by kilrah** [comment]
Sure!

**Comment by projectkk2glider** [comment]
@HakanBastedt any progress?

**Comment by HakanBastedt** [comment]
Yes, fur sure. I am ready and even made a pull request.
I messed up the endlines -  maybe you remember this?
I think the changes are in the next branch.
Maybe I should close this issue?

**Comment by projectkk2glider** [comment]
I see now, the pull request was missing reference back to this issue. Does the master (aka 2.1) also need this fix or not?

**Comment by HakanBastedt** [comment]
Yes, current and next need this.
I see I was targetting "next", but it is an update for the current version as well.

**Comment by projectkk2glider** [comment]
Can you make another pull request with your changes against master? Thanks.

**Comment by projectkk2glider** [comment]
@HakanBastedt any progress on pull against `master`?

**Comment by HakanBastedt** [comment]
Oh, I missed you previous message. I'll do a pull request in a day or two.
