### ISSUE TITLE
OpenTx companion OSX libraries for 10.8.5 Mountain Lion

### ISSUE THREAD

**Issue by maoyin** [opentx/opentx#3116]
OpenTx Companion crashes when choosing the simulate button in models.  The crash report contains

Dyld Error Message:
Symbol not found: ___sincos_stret
Referenced from: /Applications/companion 2.1.6.app/Contents/MacOS/../Frameworks/QtGui.framework/Versions/4/QtGui
Expected in: /usr/lib/libSystem.B.dylib

It appears that when 2.1.6 Mac version of 2.1.6 companion was compiled it possibly did not take into account the older libraries in OSX 10.8.5 Mountain Lion i.e. this file libSystem.B.dylib is not compatible with 2.1.6 at that older revision of OSX.

I have verified this as per post in the RCGroup thread for OpenTx 2.1 by replacing libSystem.B.dylib file with the one from El Capitan.  The simulator does not crash then.

http://www.rcgroups.com/forums/showpost.php?p=33311990&postcount=1942

http://www.rcgroups.com/forums/showpost.php?p=33307841&postcount=1938

If at a next revision compile using Mountain Lion for these older libraries please.

**Comment by projectkk2glider** [comment]
Possible related issue #1482
