### ISSUE TITLE
Timer - Voice reading time with decimal places

### ISSUE THREAD

**Issue by Blindtuna** [opentx/opentx#3119]
Using:
Companion 2.1.6 
Taranis Plus Bootloader 2.1.6
Firmware 2.1.31

When using the Play Value "Timer2" function, the time is spoken out incorrectly.

Example - 
Time: 5 minutes and 32 seconds
Voice: 5 point zero and 32 point 5

**Comment by kilrah** [comment]
You didn't update your voice files when you went from 2.0 to 2.1.

**Comment by Blindtuna** [comment]
Thanks and apologies for wasting your time!

Quoting Andre Bernet <notifications@github.com>:
