### ISSUE TITLE
Add descriptions for known telemetry sensors

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#3120]
We should have a const table of strings that would explain every known telemetry sensor. Sort of like a description for each item (like it is done for lua fields).

So for "Rx2C" sensor the explanation would be "Power box bla bla bla". These descriptions would be shown in sensor setup menu and available to Lua by getFieldInfo().

**Comment by lshems** [comment]
Not stale, even a pore valid request with 2.2 and 2.3 telemetry framework
