### ISSUE TITLE
Companion telemetry sensors ratio and offset value increment and decrement ignores precision

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#3121]
Companion 2.1.6 - Field up/down steps whole number irrespective of precision. Other fields eg altimeter do inc/dec by decimals.

**Comment by projectkk2glider** [comment]
Probbably best to fix this when doing #2781

**Comment by projectkk2glider** [comment]
Ratio fixed in 10d29e93b5a9af24008efd634f9e62ba865467a1
