### ISSUE TITLE
FCS-150A  Measurement greater 150A

### ISSUE THREAD

**Issue by frobert0** [opentx/opentx#3129]
#2333 

Approach: 

Two cables to share power
One by sensor

unfortunately
Curr + Curr
too imprecise

It would be better
Curr * Number

**Comment by kilrah** [comment]
https://github.com/opentx/opentx/issues/2615

**Comment by frobert0** [comment]
sehr schwer einzustellen, es sollte ein kalibrier Möglichkeit ähnlich Akkuspannung geben

very difficult to adjust, it should be a calibration option similar type battery voltage

**Comment by kilrah** [comment]
That's what it will be when #2615 is implemented.
