### ISSUE TITLE
OpenTX 2.1.6 / 9XR pro USB serial does not work

### ISSUE THREAD

**Issue by mikeller** [opentx/opentx#3132]
I noticed that after updating OpenTX on my 9XR pro, the USB serial connection when connecting while the TX is on and running normally has stopped working.

Plugging in USB while off / in bootloader mode still gets the TX recognised as USB drive.

Unfortunately this also means I can not write model configs from companion21 to my TX.

Operating system: ubuntu 15.10

Expected behaviour: TX recognised as /dev/ttyACM0 when plugged in while running

Experienced behaviour: TX not recognised at all (in 'dmesg' output) when plugged in while running

**Comment by kilrah** [comment]
There has never been a USB serial port on the 9XR Pro, and there wouldn't be anything to do with it. You need to be in bootloader mode to read/write models.
