### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by puppetx** [opentx/opentx#3137]
03:40:53.587649 IP 192.168.42.17.14861 > 93.51.182.154.80: Flags [S], seq 2302745599, win 8192, options [mss 1460,nop,nop,sackOK], length 0

Please bring the hosting server back up?

**Comment by kilrah** [comment]
No issue here.

Companion or firmware? Release or nightly? What version? Actual relevant details would be appreciated.

**Comment by puppetx** [comment]
Sorry, I downloaded an old companion on accident, latest version works fine.  Sorry for the false alarm
