### ISSUE TITLE
CELL - telemetry option for 2.1.6 & X9E

### ISSUE THREAD

**Issue by aussiepilot** [opentx/opentx#3140]
Hi I can not see the telemetry Option CELL (to indicate the batteries lowest cell voltage) is there any way to have this option displayed Regards Barry

**Comment by kilrah** [comment]
Please do not use the issue tracker to ask usage questions.
Lots of info and help on forums:
http://openrcforums.com/forum/viewtopic.php?f=45&t=6887
http://www.rcgroups.com/forums/showthread.php?t=2451551
