### ISSUE TITLE
Simulator 2.1.6 adding a Fx key for reloading it

### ISSUE THREAD

**Issue by pointu** [opentx/opentx#3141]
For a faster testing when making scrips could it be possible to add a Fx key for reloading simulator in place of quiting cliquing retying testing values .... ?

**Comment by projectkk2glider** [comment]
Do you mean Standalone Simulator or the radio simulator inside Companion? 

In Companion to "reload" one has to:
* click close button and then simulate button
* or press Alt+F4 and then Enter key

Is that too much? Does it warrant a special key combination?

**Comment by pointu** [comment]
I'm not explaining it correctly
I mean simulator inside Companion, but it's the same for standalone, and the goal is to "Restart/Reload" it without quiting it, retyping test values etc etc...
when you are modifiying à script for example, you do that externaly from simulator, and you have to quit, re-enter, re-type values, quit re-enter, re-type values...
Is there a way ?

**Comment by kilrah** [comment]
I think what he really wants is a way to reset only the lua environment in the simu.
Someone has already suggested him to use a Special Function with a dummy script linked to the momentary switch as that should do what he wants.

**Comment by pointu** [comment]
Thanks kilrah, only yhe lua environment, i haven't think that's possible, but where is that suggestion your talking about ?

**Comment by kilrah** [comment]
On the French forum

**Comment by pointu** [comment]
it's some workaround and questioning not an answer and again an Fx to reload lua environment should be a great idea for not good developer like me who cycle a hight number of time between sim and script editor...
