### ISSUE TITLE
OpenTX 2.1 - Fahrenheit temperature conversion error

### ISSUE THREAD

**Issue by dsbeach** [opentx/opentx#3146]
Configure a telemetry sensor (Tmp1 or Tmp2) to display Fahrenheit values. Using the telemetry simulator a value of 100C will show as 180.32.  If you use the transmitter to select Celsius it will show 100C - then switch back to Fahrenheit and the correct value of 212F is shown.

Similarly using 1C you get 2.12F initially, but switching back and forth results as 33F as expected.

**Comment by projectkk2glider** [comment]
Another thing I can not reproduce today! :confused:  @dsbeach can you check again with some recent build. The factor 1.8032 also does not appear anywhere in the code.

**Comment by dsbeach** [comment]
Will do.

**Comment by kilrah** [comment]
Could be a problem with PREC. Using anything else than PREC0 with °F will break the conversion (because of the offset). The radio will force it to 0 when selecting °F, but it seems companion doesn't, it hides the prec field but omits setting it to 0.

**Comment by dsbeach** [comment]
Yes, it looks like an issue with PREC.  When editing the model in companion I changed the unit to 'raw' and the precision showed '2'.  Change the precision to '0', change the unit to degrees F and the problem is gone.

The radio (both physical and in the sim) allows the setting of PREC when the unit is degrees C.  Changing to F then hides the field.

I'm not sure if this needs a fix, but regardless it is a low priority.
