### ISSUE TITLE
Symbols for drawsource not shown correct on companion (and radio??)

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3151]
I get some weird symbols using LUA lcd.drawSource:
![2015-12-14 1](https://cloud.githubusercontent.com/assets/12395806/11792871/ab39814e-a2a8-11e5-9cf7-fa01fc5efebf.png)

**Comment by projectkk2glider** [comment]
Don't use small fonts, they don't have required symbols! It works with normal sized font.

**Comment by lshems** [comment]
funny, the Taranis native menu is in small fonts and has the symbols.

??

**Comment by kilrah** [comment]
Yep, the menus are in standard font.

**Comment by lshems** [comment]
OK. Pity ;) :(
