### ISSUE TITLE
Potentiometer conversion ratios are not valid.

### ISSUE THREAD

**Issue by AndreyRakhmanov** [opentx/opentx#3164]
I just installed 2.1.6 on my Turnigy 9x, and started the model configuration. What I found that all potentiometers on my model don't work. When I go to ANALS screen and start to rotate PIT TRIM potentiometer in the range (0-100%), looking on digital and analog columns I see next changement in A7 row:
Angle 0:       A7: 0000     0
Angle 2%:    A7: 0032   51
Angle 5%:    A7: 0052   81
Angle 7%:    A7: 0070  100
Angle 25%:  A7: 0276  100
Angle 50%:  A7: 03D4  100
Angle 100%:A7: 07FE  100

Looks like it is pure conversion problem, ADC supplies reasonable values. 
I loaded same firmware into simulator and see noting like this  behavior -  the potentiometer was mapped into (-100 - +100) range. Any ideas how to fix it?

**Comment by kilrah** [comment]
Calibrate your sticks/pots.
