### ISSUE TITLE
USB Joystick with 9XR Pro

### ISSUE THREAD

**Issue by AlexDaniel** [opentx/opentx#3168]
[It seems like](https://github.com/opentx/opentx/wiki/OpenTX-USB-Joystick) this feature is supported on Taranis but not on 9XR Pro.

**Comment by LeoDJ** [comment]
push?

**Comment by schwabe** [comment]
@leodj someone need to implement that feature. And as in every OpenSource project most people do what they like to do.

**Comment by buzztiaan** [comment]
+1 

anyone have a idea whats needed for this?

**Comment by kilrah** [comment]
Someone needs to write the USB driver and application code for the 9XR-Pro's processor (or find an example to modify).

**Comment by dandruff39** [comment]
Are these reasonable references for what's required (supplemental to the Taranis joystick code)? 
http://www.atmel.com/products/microcontrollers/ARM/SAM3S.aspx?tab=documents
http://www.atmel.com/Images/Atmel-42339-USB-Device-Interface-UDI-for-Human-Interface-Device-Generic_ApplicationNote_AT09334.pdf

**Comment by mayanez** [comment]
Any update on this?

**Comment by schwabe** [comment]
@dandruff39 yes. @mayanez no.

**Comment by AlexDaniel** [comment]
It is not stale, there's actually a PR fixing this: https://github.com/opentx/opentx/pull/5776
