### ISSUE TITLE
Global Variable

### ISSUE THREAD

**Issue by frobert0** [opentx/opentx#3173]
Spezial Funktion
SF2   Adjust GV1  Wert   85
Logische Schalter
L 1  a>b  [i3Gas]   GV1

>> bei ~ 8% Throttle aktive L1

---------------------------------------------------------------

Logische Schalter
L1 a>x  [i3Gas]  85

>> bei ~85% Throttle aktive L1

?????????????????????????????????????????????

**Comment by kilrah** [comment]
https://github.com/opentx/opentx/issues/1361

**Comment by frobert0** [comment]
für Programmierer und Mathematiker, nicht für Normale, es solte immer der selbe wert sein nicht einmal so und einmal anders, wenn Funktion benötigtig dann sollte sie anders benannt sein

**Comment by kilrah** [comment]
Again #1361 explains why it is that way and that it will eventually be changed for what you want.
