### ISSUE TITLE
OpenTX (Taranis) Firmware 2.1.6 - Timer not reading value correct!

### ISSUE THREAD

**Issue by wot4** [opentx/opentx#3182]
I recently updated my FrSKY Taranis+ from 2.0.13 to 2.1.6.

I have noticed that all of the Telemetry 'logical switches' and 'Special Functions' have stopped working.  

For example I had (2.0.13):
a<x   Cells   10.5v

Now the transmitter displays it as (2.1.6):
a<x   ---   105

Also I had a switch to read the remaining time on the timer1, now this doesn't get read properly.

For it to read the time 12.50, it says "12.0 and 50.2". Its also doesn't include the "mins" word at the end of the speech.

Any suggestions ?

**Comment by kilrah** [comment]
>I recently updated my FrSKY Taranis+ from 2.0.13 to 2.1.6.

...aaand like many you forgot to update the sound pack along with it.

**Comment by projectkk2glider** [comment]
Read http://www.rcgroups.com/forums/showthread.php?t=2451551

**Comment by wot4** [comment]
Thanks for the feedback.

Sound files working correctly now....
