### ISSUE TITLE
No Haptic - 2.1.6 - Taranis X9D Plus

### ISSUE THREAD

**Issue by dWoolridge** [opentx/opentx#3183]
I just upgraded to 2.1.6 and just noticed that my transmitter no longer produces haptic vibrations.  It does make a very faint electronic sound when I would expect the haptic to be active.  Please note this is not a mechanical sound I am hearing.

I'm somewhat new to Open TX, so hopefully I'm not missing something simple.  I created a special function on a switch to test the Haptic.  The transmitter produces the sound described above when the switch is active, and the sound pulses 3 times as I set the Haptic pulse in the special function.

General Settings:
----------------------
Haptic mode:  ALL  (also tried No Keys)
Haptic length:  normal
Haptic Strength:  I've tried all Haptic Strengths

Thanks,

Doug

**Comment by projectkk2glider** [comment]
Can anybody verify this. I suspect it is a user setting problem somewhere.

@dWoolridge you upgraded from which version? Or to put it differently, which was the last version that worked for you?

**Comment by dWoolridge** [comment]
I know it worked with the firmware that was on the transmitter when I bought it new.  I can't say if it ever worked since updating the firmware.  I just discovered how the haptic would be nice to use, and realized that it wasn't working.  The firmware currently reported by the transmitter is "opentx-taranis-plus" version 2.1.6 (2015-11-12 01:10:06)  EEPR 217.

In addition to the "General settings" I noted above, I've been using Special Function 8 (shown below) to test.  If I hold the transmitter right to my ear, I can hear 3, faint, electrical "pulses" when I flip SA to the up position.

![image](https://cloud.githubusercontent.com/assets/16481972/12055952/a10d14dc-aef7-11e5-9896-b284d374b140.png)

**Comment by dWoolridge** [comment]
One other thing I noticed... but I'm not sure it would help.

I don't see "Haptic" as a build option when I go to Edit Settings.  Based on something I read somewhere, it sounded like that may have been an option in previous versions.  (see below)

![image](https://cloud.githubusercontent.com/assets/16481972/12056213/b96f9aca-aef9-11e5-8ec4-a9a73ef3e449.png)

**Comment by kilrah** [comment]
Normal because Taranis plus always has haptic, so no option needed. The menu options wouldn't appear if it wasn't enabled.

**Comment by projectkk2glider** [comment]
Any chance you have your Haptic strength setting on minimum?

**Comment by dWoolridge** [comment]
I've tried all 5 haptic strength settings.

**Comment by dsbeach** [comment]
I can test tomorrow.

**Comment by dsbeach** [comment]
Tested today on 2.0.15 and then on released 2.1.6 and an up-to-date self built master.  No issues found.  At lowest strength the haptic barely noticeable over the sound from the speaker (coming from my 'play track'). I did not use a LS but otherwise I think the test is valid.

**Comment by dWoolridge** [comment]
Thanks for testing that.  2 quick questions...

1)  Where can I get just the .BIN files  for previous versions of the firmware?  I'd prefer to try a previous version by doing that rather than installing another version of Companion to get the firmware.

2) Does the companion simulator simulate the haptic vibration in any way?

**Comment by dsbeach** [comment]
Sorry - I don't know if the older .bin files are available.  Also, it appears that there is no haptic feedback in Companion.

**Comment by powercycle** [comment]
Haptic works for me on 2.1.6, eepr v 217.  Are you positive that you are using the Taranis Plus profile?

If not, it could cause issues similar to this.

**Comment by dWoolridge** [comment]
I believe so...  under settings it says "Radio Type->FrSky Taranis Plus".  Is there anywhere else I need to confirm this?

Also, I just popped the radio apart and applied 1.5V directly to the haptic motor solder points.  No result.  I then tried 4.8V and still nothing.  Do you know if that voltage should have spun the haptic motor?

**Comment by powercycle** [comment]
Guess it could just be a hardware issue.

**Comment by kilrah** [comment]
Sounds like your haptic motor is simply dead.
