### ISSUE TITLE
2.1.6  and new Telemetry  setup

### ISSUE THREAD

**Issue by Kfegley** [opentx/opentx#3184]
When I tell my radio to find  "New Sensors" it does it just fine but I am unable to find CELL....It shows CELLS but for some reason I am unable to monitor individual cell voltages like I could before with the earlier firmwares.

Kyle

**Comment by kilrah** [comment]
http://openrcforums.com/forum/viewtopic.php?f=45&t=6887

Please don't use the issue tracker for usage questions.
