### ISSUE TITLE
Error reading switch label from X9E

### ISSUE THREAD

**Issue by jvmatern** [opentx/opentx#3187]
When downloading radio settings to companion is switchK "SK-" given the wrong name "!FM8".
Companion 2.1.6
open-tx-taranis-x9e 2.1.5

![pc](https://cloud.githubusercontent.com/assets/16493370/12056910/51ef00a0-af3c-11e5-8449-ef444a0578fe.gif)
![x9e](https://cloud.githubusercontent.com/assets/16493370/12056958/b295ea72-af3c-11e5-9630-51788c5186a9.gif)

**Comment by mpaperno** [comment]
This is actually a radio firmware bug.  When a switch in a 3-way "slot" is configured as two-way, the wrong value is registered when auto-detecting switch position on the radio.  

Two-way switches should register as UP/DOWN (arrows).  That is how it acts in eg. slot SF.  But if you configure any 3-way slot as 2-way, then the auto-detection shows only `-`/DOWN (no UP arrow).

If you manually scroll through the available switch positions on the radio, then only the UP/DOWN options are shown, there is no `-` middle position option at all.  Which seems correct.  So only auto-detection seems broken in this case.

This is not limited to the LS screen, but seems to be throughout the X9E radio UI.   Nor can I recreate this on any other radio/UI.

**Comment by 3djc** [comment]
I have a bug registered for this, but this won't get looked at before 2.2.0 I think

**Comment by mpaperno** [comment]
OK, perhaps close this one then if it's a dupe.

**Comment by 3djc** [comment]
Yeap and the real issue is with the radio
