### ISSUE TITLE
Not possible to manually add GPS sensor

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#3188]
If you manually add a GPS sensor (configured with say ID 0800 Instance: 4) then it will display only 5-6 digit numeric, and not the RAW GPS value. The only way to add it successfully is to have the radio discover the sensor, which seems to then configure it with a completely custom layout when you go to edit it - but this works fine, displaying the coordinates as expected. It would be good if it were possible to add this manually, maybe choosing a GPS format for the Unit of measure option.

**Comment by axyspg** [comment]
Confirmed. Furthermore if you edit an already "special" sensor like GPS or Date from Custom to Calculated and then modify the Units to something (Raw for example), setting again to custom value loses original unit format. I've found no way to make it work again. Sensor must be deleted and redetected (also can't be manual added, as this issue describes).

Date is also affected. I suppose all "special" fields have the same problem.
