### ISSUE TITLE
More type of switches in harware settings

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3189]
I have replaced 2 of my switches by different types that I can't choose in hardware settings.

I have replaced a standard 3-position switch with a 3-position switch that's only on 1 side latching. The other side is momentary. They are sometimes referred to as (ON)-OFF-ON
The other switch I replaced is of type (ON)-OFF-(ON) which means it will always goes into neatral (OFF).

AFAIK the simulator follows these settings (I can't really test as Companion started to become extremely slow in the latest nightlies) and it would be nice if it would follow that changed behaviour.

**Comment by kilrah** [comment]
Not really a fan of adding settings to the firmware that do absolutely nothing in it...
And no, the companion simu corrently doesn't take any of the switch settings into account.

**Comment by MicheleVilla** [comment]
There is another open issue about that
#2960

**Comment by hrenz** [comment]
Hy.

we will need a   2 side Toggel Switch  (ON)-OFF-(ON) option with autorepeat
Because at Horus there are 2 free trimm switches  in the middle 
this is the same as Toggel Switch  (ON)-OFF-(ON) option with autorepeat

think this functions are ready for trimm switches

**Comment by fraternl** [comment]
>> And no, the companion simu corrently doesn't take any of the switch settings into account.
I don't believe there's a request for that.
Would I need to do that or can I use this ticket for it?

**Comment by hrenz** [comment]
Hy 
the tree pos switch it self are integrated, thats ok, and enough for  (ON)-OFF-(ON) too
I think what realy would be interesting is a autorepeat funktion like the trimm switches has.

**Comment by mhotar** [comment]
I would see the SF AdjustGV +x/-x with autorepeat function (once, repeat every x second), similar to like PlayValue has, sufficient to create this type of switch. There is opened issue for this already somewhere.

**Comment by hrenz** [comment]
Hy,

think autorepeat funktion like the trimmswitches we have would be right way for  (ON)-OFF-(ON)

**Comment by projectkk2glider** [comment]
I have this idea for Companion simulator:

Add new tab to the radio profile (for all Taranis variants) where user can define for each switch (that the radio supports):
 * switch physical position (important especially for X9E)
 * switch type (more precise than in the radio settings, like three pos momentary), can also be none if the switch is not installed.

This new setting will then be used to populate the switches in the simulator window. 

The related issues is: #2377

**Comment by kilrah** [comment]
Yep why not, maybe with a way to "import current radio settings" so that you don't have to set up everything twice completely, only once on the radio, then import and edit the differences.

**Comment by lshems** [comment]
Made a small screen mockup. The idea would then be to assign the physical switch positions PA, PB ... to the named positions SA, SB, SC, and have the physical possibilites follow the physical switch positions.

All functions in the rest of the programming would refer only to the named positions.

This would also allow for an often asked feture to interchange switches easily,without looking at all possible places.

![switches mockup](https://cloud.githubusercontent.com/assets/12395806/12186005/34a3f7d0-b59f-11e5-9481-6e63128d46cf.png)
