### ISSUE TITLE
Models not read in correctly from Taranis Plus

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx#3194]
Companion 2.1.6
Taranis Plus

Models write correctly to radio, but when read back from radio, they no longer have input.

Before writing to radio:

![screenshot - 01012016 - 03 15 09 pm](https://cloud.githubusercontent.com/assets/2614846/12072704/9b0e99a8-b09a-11e5-9b5f-99d0bd8bab47.png)

After reading from radio:
![screenshot - 01012016 - 03 14 24 pm](https://cloud.githubusercontent.com/assets/2614846/12072707/a8958cee-b09a-11e5-8701-89eb41898133.png)

Logical switches have a similar fate.

After writing the initial file, the radio goes through an eprom conversion (v216).

What files would you need to help troubleshoot this?

**Comment by kilrah** [comment]
You must be using the wrong companion version. 

> After writing the initial file, the radio goes through an eprom conversion (v216).

This means you're actually running companion 2.0, not 2.1. Openting a 2.1 eeprom in 2.0 does just what you see.
