### ISSUE TITLE
TRx not working on 9XR pro

### ISSUE THREAD

**Issue by estechnical** [opentx/opentx#3203]
Hi, I'm using OpenTX 2.1.6 on Turnigy 9XR pro and I am having trouble getting the PPM in working as I wish...

I have 16ch radio module (XJT) and I'm using some channels to control a gimbal and camera, I'd like the trainer port to allow me to have a second TX for these tasks.

I have so far found that only the first 4 channels of the incoming PPM are read correctly, coming from my 6ch second TX. All the other TRx inputs all give mid-point values.

Having looked at some of the other issues related to the trainer port I changed to PPM out instead of XJT and the PPM inputs all started working as expected - but of course now I can't use my radio to it's full potential...

Is this something that's not possible for my case?

Thanks,
Ed

**Comment by estechnical** [comment]
Further to my observations above, if I start up the radio having previously set it to XJT mode the PPM in doesn't work (as per above) but then if I switch to PPM mode and back to XJT mode the PPM (TRx) inputs all remain working, including those above ch4. This leads me to think I found a bug and I'm not doing something wrong... Any ideas?

Thanks,
Ed

**Comment by projectkk2glider** [comment]
Definitely looks like a bug.

**Comment by projectkk2glider** [comment]
@estechnical Did it work in any previous 2.1.x version?

**Comment by estechnical** [comment]
How would I get earlier firmwares?

**Comment by estechnical** [comment]
Well I tried to grab an older firmware but it appears to be hard to get old firmwares (probably deliberately?) - I can't comment on older firmwares as I can't test and don't know.

Sorry... if there is anything you need me to test please let me know.

**Comment by estechnical** [comment]
The issue persists in 2.1.7, I just tested and the behaviour is the same...

**Comment by projectkk2glider** [comment]
>How would I get earlier firmwares?

You can't unless you have the old firmware stored on your computer. Anyway I just wondered if any of previous versions worked (which would then mean that we messed up something) or it was newer actually implemented.

**Comment by estechnical** [comment]
Hi, has there been any progress on this issue? I'm happy to test if needed. I need this issue fixed as soon as possible because it's really hampering my use of the radio...

**Comment by projectkk2glider** [comment]
I will take a quick look at the code if something obvious is missing. I don't have this radio, so it is impossible for me to test...

**Comment by projectkk2glider** [comment]
Sorry, I have found nothing obviously wrong. This must be tackled by some other developer.

**Comment by bsongis** [comment]
I take it

**Comment by estechnical** [comment]
:) Thanks Bertrand

**Comment by bsongis** [comment]
Do you know if it worked in 2.0?

**Comment by estechnical** [comment]
Sorry but I never used this version. Is it possible for me to get this firmware to test for you?

**Comment by projectkk2glider** [comment]
Download Companion 2.0.19 http://www.open-tx.org/2016/01/15/opentx-2.0.19 and with it the 2.0.19 firmware for your radio. Be sure to make a backup of your current setup as the radio/model settings will be wiped after you install 2.0.x OpenTX on the radio!

**Comment by bsongis** [comment]
@estechnical Would you send me an email so that you can test for me?

**Comment by bsongis** [comment]
I am testing on mine first, it was taking dust ...

**Comment by bsongis** [comment]
It works here

**Comment by estechnical** [comment]
Many thanks Bertrand, i think the reason was partly because of a dodgy contact in one of my plugs. Sometimes I was able to get the radio to vibrate when moving the cable... i have now pulled out a few contacts from the affected plug and swapped in another pin. This has helped with the issue, i no longer have to switch modes for the radio module to get trainer ppm in working. Perhaps your changes will make it more robust than before when incoming ppm signal is intermittent during plugging in the cable or in use. :-)
