### ISSUE TITLE
SF for new model

### ISSUE THREAD

**Issue by PieroCo** [opentx/opentx#3204]
The SF window for  a new model is not formatted correctly

ver 2.1.7
![sf](https://cloud.githubusercontent.com/assets/7857600/12117758/17de6b22-b3c3-11e5-9232-0608de2bad40.jpg)

**Comment by projectkk2glider** [comment]
Hmm, probably my fault (remember QTableWidget layout and #3091 and #3131). But on Linux the window looks ok, this is official 2.1.7:
![screenshot](https://cloud.githubusercontent.com/assets/5950438/12121817/9f60a146-b3d7-11e5-87f7-66bd0bcbfd11.png)
