### ISSUE TITLE
Telemetry Simulator

### ISSUE THREAD

**Issue by PieroCo** [opentx/opentx#3207]
the altitude is not populated  opentx 2.1.7
![untitled-2](https://cloud.githubusercontent.com/assets/7857600/12146517/3f5f4050-b494-11e5-8caa-838c4246cf55.jpg)

**Comment by axyspg** [comment]
Not sure what's happening with instances with this version, but setting it to 32 fixes the problem.
I've read somewhere that 28 is the max instance in SmartPort, is that true? if yes, why works when setting instace to 32?
Let me congratulate all of you for this feature, it's really nice for LUA scripts development.

**Comment by axyspg** [comment]
By the way, telemetry simulator doesn't send data when values are at 0. Is it the intended behaviour?

**Comment by jtaylor2** [comment]
@axyspg 
>By the way, telemetry simulator doesn't send data when values are at 0. Is it the intended behaviour?

Yes, it is intended behavior.

**Comment by kilrah** [comment]
I haven't followed the simulator enhancements closely, but before that the Instance number was the "encoded" one, not the "user" one i.e. not 1, 2, 3, 4 but 0x00, 0xA1, 0x22, 0x83.

I'd expect that would have been changed in the refactoring, but maybe not. And yes it sends only with the chosen instance, that's the whole point of it.

**Comment by pointu** [comment]
The VSpd value is not populated too,
Can u save the last used values ?

**Comment by projectkk2glider** [comment]
>The VSpd value is not populated too,

My pull #3207 should cover this

**Comment by dsbeach** [comment]
The best way to save values is via the "Load" function of "Replay SD Log File".  There are currently no provisions for just retaining the last used values.  Note that if you are using the telemetry sim to develop Lua scripts you can just change your script source and press 'PF7' to test the changes without exiting the sim.
