### ISSUE TITLE
9xr issues with usbasp

### ISSUE THREAD

**Issue by mrpreciado** [opentx/opentx#3227]
![c](https://cloud.githubusercontent.com/assets/13734310/12276986/952e6264-b93e-11e5-8cbb-8ebb8f3d30d5.png)

i am not able to upload opentx firmware to my 9xr it keeps giving the problem on the image,the driver is installed and my cable works(turns on the controller,once i connect to the computer),any ideas on how to do it

**Comment by projectkk2glider** [comment]
Please user forums for such questions.
