### ISSUE TITLE
Directory listing error in SD card browser

### ISSUE THREAD

**Issue by urbans90** [opentx/opentx#3230]
Hello. When the 2.0.19? And who can make a firmware fix for 2.0.18? A bug in the folder when scrolling up. Flashing when the backlight. Or tell me how to fix it all by hand. Thank you.

**Comment by projectkk2glider** [comment]
Please describe your issue more clearly, I cannot make anything from your post.

**Comment by urbans90** [comment]
Here's a video like when paging up all is lost. And there's also a flash of blue when turned on. https://goo.gl/photos/mYo5zr5Awh6uDpKZ7

**Comment by projectkk2glider** [comment]
Did it work in 2.1.7? Does it happen only in directories with a lot of files or in all directories?

**Comment by urbans90** [comment]
I did not set 2.1.7. This firmware 2.0.18. This occurs when flipping have not depending on the quantity. And only when paging up from any position.

**Comment by kilrah** [comment]
How many files do you have in that "en" folder? Looks like way too many.

**Comment by urbans90** [comment]
If you put the firmware 2.0.9.2 is no such. And it's not a lot of files.

**Comment by projectkk2glider** [comment]
Confirmed on simu, and 2.1 is not affected.

**Comment by urbans90** [comment]
How to fix it? What program? How to rebuild the firmware?

**Comment by projectkk2glider** [comment]
@urbans90 wait for 2.0.19 release...

**Comment by projectkk2glider** [comment]
A one character bug :relaxed:

**Comment by projectkk2glider** [comment]
Tested on my Taranis, it works.

**Comment by urbans90** [comment]
Thank you.

**Comment by projectkk2glider** [comment]
@urbans90 did you test  2.0.19, is it OK for you now?

**Comment by urbans90** [comment]
Yes, everything is great.

**Comment by urbans90** [comment]
And you can somehow swap adjust the illumination color. To the right was the blue and white on the left? And then when when you turn if you choose something white is a flash blue, then lights white lights. On my video which is higher than it should be seen. The firmware 2.0.9.2 was white lights on the left in the settings. I apologize for my bad English.

**Comment by projectkk2glider** [comment]
The backlight gets turned on before the radio settings are read, therefore the user backlight setting is unknown at that time. 

So a default preset is used for a moment, which I think it is better than to leave it off and turn it on after the settings are known.

**Comment by urbans90** [comment]
Good. Let then so be it.
