### ISSUE TITLE
No contact to the server for Firmwareupdate

### ISSUE THREAD

**Issue by Torstenscopter** [opentx/opentx#3238]
Hello!
I have the software installed Companion9x. Now I want to download this software a new company goods for my FrSky Taranis. I can not reach the server. No connection to the server open TX.
What's going on there?
Please help me. greeting

**Comment by kilrah** [comment]
Companion9x is old, deprecated and the matching 1.x firmware is no more available. 
Use OpenTX 2.0 or 2.1 instead.

http://www.open-tx.org/downloads.html
