### ISSUE TITLE
real time clock time zone  adjustment on companion not correct

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3241]
In Brussels time zone, my PC shwos 16:00, companion shows 15:00.

setting the offset in the general settings are not reflected.

In this way I cannot prepare all in companion and be sure the radio will be correct when uploading settings.

**Comment by kilrah** [comment]
The time zone setting is only used to display GPS time received from a telemetry sensor.

**Comment by lshems** [comment]
OK. Option to sync radio when making connection with companion??

**Comment by kilrah** [comment]
There is no communication method that allows for it at this point
