### ISSUE TITLE
Improve telemetry layout

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3242]
In the current screen layout, all settings are in the top half screen, and all sensors ar in a big table below.

The settings for the 4 telemetry screens then "dangle" a bit lost below the sensor settings.

It would be cleaner to put them just above the sensor settings.

Just my opinion, and taste is debatable.

**Comment by bsongis** [comment]
In the firmware (which radio)? Or in Companion?

**Comment by lshems** [comment]
Companion.
Op 20-jan.-2016 10:01 schreef "Bertrand Songis" <notifications@github.com>
het volgende:

**Comment by kilrah** [comment]
On companion I agree that the sensor panel and telemetry screen panel could be swapped. 
Not on the radio though, as the sensor list allows for a quick glance to sensor values.

**Comment by lshems** [comment]
Sounds great
Op 20-jan.-2016 15:20 schreef "Andre Bernet" <notifications@github.com> het
volgende:

**Comment by fraternl** [comment]
Have you considered 2 tabs/screens for telemetry?

A telemetry input and a telemetry output page

**Comment by elecpower** [comment]
Agree with @fraternl on the separation of purpose. The form is becoming a bit unwieldy.

**Comment by projectkk2glider** [comment]
Should be done together with https://github.com/opentx/opentx/issues/2781#issuecomment-158743482
