### ISSUE TITLE
Flying Wing problem with model wizard using 2.1

### ISSUE THREAD

**Issue by Oldgibber** [opentx/opentx#3245]
If you create a new flying wing model using the wizard, and assign channels 2 and 3 to the elevons, and select no rudder, the wizard produces 4 channels on the Inputs page (thr, elev rudd and ail), and mixes channels 2 and 4 for the elevons on the Mixes page.

**Comment by tomkfly** [comment]
What channels are the mixes on?  Could it be Inputs 2 and 4 on channels 2 and 3?

**Comment by Oldgibber** [comment]
Yes it does exactly that. Ah yes I finally see what is going on. I'm going brain dead. Thanks.
