### ISSUE TITLE
2.1.7 language problem

### ISSUE THREAD

**Issue by tomkfly** [opentx/opentx#3247]
I downloaded 2.1.7 with  en selected in preferences and initially had no problems, but today Companion is in another language (looks like French to me). I have tried re downloading again making sure "en" is selected, but it won't download.

**Comment by kilrah** [comment]
Companion language selection is independent from firmware language. Settings -> Menu language.

**Comment by tomkfly** [comment]
Just realised I was trying to download firmware, when it was Companion  I needed to re-load. However, I still don't understand why the language changed.
