### ISSUE TITLE
Offset missing in line text on Inputs page when present

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#3248]

**Comment by projectkk2glider** [comment]
@bsongis what is `scale` member in:
```c
class ExpoData {
  public:
    ExpoData() { clear(); }
    RawSource srcRaw;
    unsigned int scale;
```

**Comment by kilrah** [comment]
> what is scale member

When the source is a telemetry value this defines how much of that value should be considered as 100% in the mixer domain.
