### ISSUE TITLE
Unable to download polish firmware variant for Taranis/Taranis Plus in Companion 2.1.7

### ISSUE THREAD

**Issue by pawelsky** [opentx/opentx#3253]
I'm unable to download polish firmware variant for Taranis/Taranis Plus in Companion 2.1.7. Dowload always finishes with error. All other language variants download correctly.

**Comment by projectkk2glider** [comment]
I have also changed source on compilation server (manually) in order for user to be able to download 2.1.7 PL variant. @pawelsky try it now.

**Comment by projectkk2glider** [comment]
Uff, it wasn't so simple, but now it works. :smile:

**Comment by pawelsky** [comment]
2.1.7 PL works now for both Taranis and Taranis Plus, thanks a lot! :)
