### ISSUE TITLE
Companion telemetry field edits not triggering save changes on closing model file

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#3254]
For Custom type, only changes to the name, type, units and precision fields flag changes with asterisk and prompt to save changes on closing file.

Steps to reproduce
1. Open existing model file
2. Edit model which had telemetry auto discovered plus some manual entries for lipo battery cells. 
3. Click telemetry tab
4. Change a field
5. Close model edit
6. Close model file. Prompt or not?
Repeat

Started to look at Calculated but way too many variations to test unless necessary. Checking the code maybe quicker and more reliable.

Using Companion v2.1.7 Win 10

**Comment by projectkk2glider** [comment]
This https://github.com/opentx/opentx/issues/2781#issuecomment-158743482 should also fix this problem.
