### ISSUE TITLE
Problem when playing VALUES in SPANISH with TARANIS PLUS 2.1.6.

### ISSUE THREAD

**Issue by bji2010** [opentx/opentx#3256]
There is a problem when playing VALUES in SPANISH with TARANIS PLUS 2.1.6.
Numbers from 0 to 99 are OK
Number 100 (CIEN) is not played
Number 101 and greater are played with an adition of 100 (101 is played as 201...)

I think that the problem is at the translation file tts_es.cpp when playing hundreds
 
 
 ```
ES_PROMPT_NUMBERS_BASE = 0,
  ES_PROMPT_ZERO = ES_PROMPT_NUMBERS_BASE+0,
  ES_PROMPT_CIEN = ES_PROMPT_NUMBERS_BASE+100,
  ES_PROMPT_CIENTO = ES_PROMPT_NUMBERS_BASE+101,
  ES_PROMPT_DOSCIENTOS = ES_PROMPT_NUMBERS_BASE+102,
  ES_PROMPT_TRESCIENTOS,
  ES_PROMPT_CUATROCIENTOS, 
```

```
 if (number >= 100) {
    PUSH_NUMBER_PROMPT(ES_PROMPT_CIENTO + number/100);
    number %= 100;
    if (number == 0)
      number = -1;
```
 
If we take as example value "105" ("CIENTO CINCO"), the expression  
	PUSH_NUMBER_PROMPT(ES_PROMPT_CIENTO + number/100) will be
	PUSH_NUMBER_PROMPT([ES_PROMPT_CIENTO =] **101** **+** [number/100=]**1** ) so we are
prompting to **102** (**ES_PROMPT_DOSCIENTOS** / two hundred).

I am not a programmer but i think that is necessary to some new code for (number **=** 100) ("CIEN") and modify the code for (number  **>** 100). Something like this:

	}
  	if (number = 100) {
    	  PUSH_NUMBER_PROMPT(ES_PROMPT_CIEN);
          number %= 100;
          if (number == 0)
          number = -1;
	}
	}
  	if (number > 100) {
    	  PUSH_NUMBER_PROMPT(ES_PROMPT_CIENTO + (number/100)-1);
    	  number %= 100;
    	  if (number == 0)
      	  number = -1
         }

Thanks a lot!!
Inaki

**Comment by projectkk2glider** [comment]
@bji2010 Can you test my changes with the nightly builds. Thanks.
