### ISSUE TITLE
[Companion][Taranis][2.1.7N630] Input->InputName  

### ISSUE THREAD

**Issue by 483917** [opentx/opentx#3267]
Windows 10 pro Swedish
Companion 2.1.7N630 Eng
Taranis B ,with firmware:
opentx-taranis-haptic-timer3-lua-mixersmon-sqt5font-en-2.1.7N630.bin

When moving a input-line with InputName , up or down
the InputName do not move.
It is the same behavior in Companion and Taranis
Is this intended or some bug ??

Look at picture below
![input report](https://cloud.githubusercontent.com/assets/6617907/12698793/da642618-c7a6-11e5-9d3a-0176dbecf8a9.png)

If this is intended behavior feel free to close this issue

**Comment by kilrah** [comment]
Intended, there is no other way to correctly handle moves between inputs that have multiple lines.
