### ISSUE TITLE
Taranis as transmitter, but used by student

### ISSUE THREAD

**Issue by stefa168** [opentx/opentx#3270]
Hi everyone.
Recently I bought the Taranis X9D Plus radio and I had some time to get used to it.

Now, I have to use it with another transmitter (which can't transmit with OpenTX' protocol) but the Taranis has to be used as the student radio.
Is it possible to have the Teacher to use the non-trasmitting radio, while the Student to use the transmitter? In this case, the Teacher should always be able to override thecontrols, like in normal buddyboxing.

Any idea?
Thanks!

**Comment by projectkk2glider** [comment]
It is possible, but please use the forums for such questions.
