### ISSUE TITLE
'Play Value' RSSI says 'XX Minutes' not 'XX dB'

### ISSUE THREAD

**Issue by chillware** [opentx/opentx#3272]
Just noticed this bug in OpenTX 2.1.7 on My Taranis Plus. I setup a switch to call the RSSI every few seconds, and it says 'XX minutes' not 'xx dB' as it did on my OEM taranis plus firmware.

**Comment by projectkk2glider** [comment]
You need 2.1 sound pack, look in download section on open-tx.org

**Comment by chillware** [comment]
I installed "http://voices-21.open-tx.org/opentx-taranisplus/en/english-amber.zip" and still have the same issue..

**Comment by tomkfly** [comment]
You have probably loaded them in the wrong folder.

**Comment by chillware** [comment]
ok, I will double check and let you know.. thx for the reply.
