### ISSUE TITLE
Can not change the field "Cell sensor" on taranis plus telemetry screen

### ISSUE THREAD

**Issue by DanielG63** [opentx/opentx#3277]
When you add "cell" sensor in telemetry screen, you can not change the field "Cell sensor" on the remote control. The display shows " --- " without the possibility of changing. This change can be done through "OpenTX Companion" and after saving the changes on the remote control.

Firmware version 2.1.6 / 2.1.7 (I have not checked in earlier versions)
Hardware: taranis plus ver B, X8R, FLVSS LiPo Voltage Sensor.

**Comment by kilrah** [comment]
You likely added the Cells sensor mnaually instead of having it discovered. That won't work.

**Comment by DanielG63** [comment]
Thanks!
I deleted the settings and I made a new scan with "Discover New sensor" and it all worked out.
