### ISSUE TITLE
[OpenTx] switchs visualization on Taranis

### ISSUE THREAD

**Issue by MicheleVilla** [opentx/opentx#3278]
![display_err](https://cloud.githubusercontent.com/assets/6508436/12871840/182cd62a-cd8d-11e5-8ad1-bb13c5f7ec91.jpg)

Taranis X9E
OpenTx 2.1.7
Switchs names and arrows visualization  too close sticks box on display page

**Comment by kilrah** [comment]
What are those labels? did you define custom names?

**Comment by MicheleVilla** [comment]
Yes
in Hardware page I have assigned a name for each switch
For examples number 6 switch on left position is 6Sx

**Comment by kilrah** [comment]
OK. That page was designed for 2 characters only.

**Comment by kilrah** [comment]
There.

![screenshot-3](https://cloud.githubusercontent.com/assets/6065069/12872105/c39948bc-cdb1-11e5-9d4f-441a6d4b1e77.png)
![screenshot-4](https://cloud.githubusercontent.com/assets/6065069/12872108/c5bcc038-cdb1-11e5-8bcc-3a9b752bd796.png)
