### ISSUE TITLE
[Frsky Taranis X9E] latest firmware for TBS Crossfire

### ISSUE THREAD

**Issue by sleekgrid** [opentx/opentx#3281]
Hi....
Anybody can help me provide the latest firmware (to support CRSF Crossfire) for Taranis X9E....

here is the video for Taranis X9D Plus : 
[https://vimeo.com/148148151](url)

Best Regards,
SleekGrid Syndicat

**Comment by kilrah** [comment]
Just use the latest OpenTX version (2.1.7).
