### ISSUE TITLE
Seperate debug output from PRINT command output or increase debug window buffer

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3284]
when debugging, you get a lot of info, for instance about files being loaded.

This blocks viewing the content of the variables you want to check by using the PRINT command. It has already scrolled away, so you cannot analyse it.

2 options perhaps:
make the buffer on the debug screen bigger (easy one perhaps)
make 2 screens, on for debug info, and the other for results of the PRINT command

Thanks

**Comment by lshems** [comment]
Found the CLI option. Will check that out.
#3000

**Comment by projectkk2glider** [comment]
>make the buffer on the debug screen bigger (easy one perhaps)

The scroll back buffer should already be unlimited. Are you sure you have missing lines?

**Comment by lshems** [comment]
In 2.0 sure. I'll check 2.1
Op 11-feb.-2016 09:36 schreef "Damjan Adamic" <notifications@github.com>
het volgende:

**Comment by lshems** [comment]
2.1 as well.

My main problem is file loading being reported. That completely fills my debug window.

**Comment by mpaperno** [comment]
A filter as suggested in #3685 would solve it?

**Comment by mpaperno** [comment]
Closed via #4385 (and lack of further input).
