### ISSUE TITLE
inputs lines limited to 32 in LUA call, but available in radio

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3285]
When having more than 32 lines in inputs (subs counted as a line) the lines above 32 total count cause LUA to crash when using model.getinput()

both 2.0.19 and 2.1.7 NB

**Comment by projectkk2glider** [comment]
There is a bug in Lua interface. We have two numbers:
 * MAX_EXPOS which defines max total lines on inputs page (current value is 64)
 * MAX_INPUTS which defines max number of inputs defined (current value is 32)

The mistake is that we use MAX_INPUTS constant when searching of input. When you request input bigger than 32, you get back a **nil** value. That is why your script crashes. 

The **nil** return will stay, so you have to check it anyway, but the Lua interface should be fixed to enable manipulation of all 64 input placeholders.

**Comment by lshems** [comment]
It crashed even if I ask for name of input 2,line 0, if there are already
32 lines used before that on input 1.
Op 11-feb.-2016 09:21 schreef "Damjan Adamic" <notifications@github.com>
het volgende:

**Comment by projectkk2glider** [comment]
@lshems please test with the next nightly build. Thanks.

**Comment by lshems** [comment]
Ok.
Op 15 feb. 2016 21:50 schreef "Damjan Adamic" <notifications@github.com>:

**Comment by lshems** [comment]
Companion 2.1 is OK. Radio not checked yet.
