### ISSUE TITLE
Telemetry screen corruption Companion v2.1.7

### ISSUE THREAD

**Issue by EtiennePhillips** [opentx/opentx#3287]
Hi

On the Taranis Simulator on Companion v2.1.7, I tried to run the Telemetry Screen 2 Example script (from [here](https://www.google.com/url?q=http://lua-20.open-tx.org/telem2.zip&sa=D&ust=1454880632525000&usg=AFQjCNGwVUbUfP3WKXIymkcu2oYSpIvfJA)) , and it corrupts the screen and all buttons stop responding. I've attached a screenshot...

Thanks
Etienne

![screen shot 2016-02-11 at 9 56 44 pm](https://cloud.githubusercontent.com/assets/1217523/12992098/64334c04-d10a-11e5-9eef-d4375d443ad3.png)

**Comment by kilrah** [comment]
The lua script is for 2.0, there have been changes in 2.1 and it needs to be updated. I believe the only thing needed is an lcd.clear() at the start of the run function.

**Comment by projectkk2glider** [comment]
Exactly as Kilrah wrote. And you can use long press on EXIT key to go back to the other menus.

**Comment by EtiennePhillips** [comment]
Yep, that solved it... I had tried a long Exit press, and that wasn't working either. Everything's 100% now though :)

Thanks!
