### ISSUE TITLE
Special function reads RSSI value in minutes instead in db

### ISSUE THREAD

**Issue by pippos44** [opentx/opentx#3288]
When setting up a logical switch so i can read the RSSI value i get the value correct but the unit is wrong. I have set the correct unit in telemetry page as db. When the value is below the threshold ive set it, it reads i.e. 65 minutes. Can this be a wrong callout audio sound from the "Amber" sound pack that i'm using?

**Comment by kilrah** [comment]
You're using the sound pack for 2.0 with OpenTX 2.1.

**Comment by pippos44** [comment]
Well that is the latest sound pack version, isnt it?

**Comment by tomkfly** [comment]
For 2.0, but there is a modified version for 2.1 with a few extra sounds and some of the locations moved.
