### ISSUE TITLE
Model ID already used

### ISSUE THREAD

**Issue by fnjlong** [opentx/opentx#3290]
When a number of models are configured and bound to receivers, but a gap is left in the list.  If I attempt to create a new model (in the gap), the model wizard is overlaid with the message "Model ID already used".

My workaround is to move an existing model into the gap and create the new one at the bottom of the list.

Not critical, but a bug nonetheless. Opentx v2.1.7 running on Taranis+

Cheers,
Frank

**Comment by kilrah** [comment]
It's not a bug, but a warning that the Receiver number that is set by default to the model slot number when creating a new model is already in use by another model (you likely moved models around).
The Receiver lock feature would thus not prevent this model from being flown when the other one that has the same number is selected, and so you might want to check those numbers and maybe make them unique again.

**Comment by fnjlong** [comment]
An empty slot that cannot be used with the wizard.  I think most users would call this a bug.

**Comment by griebd** [comment]
If I remember correctly EXIT will just close the warning and things continue as there were no warnings, but I did not check this recently (and not in every single situation possible)...
About the "black art", I do agree and I am/was working to solve this, there is a open issue (#2187) related to that! BUT as things are build right now there is no visible solution for that yet...

**Comment by kilrah** [comment]
The EXIT key is processed by the script and as such the popup can't be dismissed without also closing the wizard.

But you can always relaunch the wizard afterwards.

So yes everything in it this ticket is already part of #2187.

**Comment by fnjlong** [comment]
You can only relaunch the wizard later on that model location after 
1) deleting the model just created after exit from the error
2) fixing the model ID issue that caused the problem to start with

If you use a lot of D8 receivers you will need to visit each model changing receiver type to D16 to see which model ID it uses.  Proceed through each one until you find the one with the model ID of the empty slot.  You could then 
a) move the model back into the matching empty slot or 
b) change the model ID so they reflect the model numbers as you go.

I am wondering if users are aware of the model ID not changing when moving models around.  

Hopefully these concerns are addressed in #2187.

**Comment by kilrah** [comment]
No you can launch it at any time from the SD card browser.

**Comment by fnjlong** [comment]
WOW, so you can.  I never knew that.  Thanks I have learnt something new.
