### ISSUE TITLE
OpenTX 2.1.7 says the wrong value

### ISSUE THREAD

**Issue by BergshamraFraggel** [opentx/opentx#3291]
Hi
When I use the Special Functions Play Value to read out the value of A2 (battery voltage) voice says 11.7 volts, but the telemetry screen displayed 11,2V.
The voice adds 0.5V to value.
I tested two models, one with 3S and 6S with battery and get the same error on both.
Best regards
Jonas Walther

**Comment by kilrah** [comment]
Please read the info threads when upgrading to OpenTX 2.1, you need to also upgrade your voice pack to one made for 2.1.
