### ISSUE TITLE
RxBt shows all the time zero volt in telemetry simulation

### ISSUE THREAD

**Issue by rcbebo82** [opentx/opentx#3293]
Im using Companion Version 2.1.7 and simulate telemetry with a csv file.
The csv file contains a colum named "RxBt(V)", if i play the file i can see the voltage changes in the "PF4 Telemetry Simulator". But the Radio Simulator Shows all the time zero volt.

**Comment by kilrah** [comment]
You need to match the Instance number in the sim to what your model telemetry settings are set to expect.
