### ISSUE TITLE
Burnconfigdialog add /dev/ttyAMC0

### ISSUE THREAD

**Issue by cmeldas** [opentx/opentx#3302]
When you are using DIY Arduino MEGA2560 linux see it as /dev/ttyACM0. But in the dialog there is no option like that.  Please add this option, or enable writing to the line Port.

Solution:
Edit burnconfigdialog.ui and rename /dev/ttyUSB0 to /dev/ttyACM0 and than compile it.

**Comment by kilrah** [comment]
Note you can use the "extra arguments" option and just put it in there.

**Comment by projectkk2glider** [comment]
@cmeldas Is Kilrah's solution satisfactory to you? Can we close this issue?
