### ISSUE TITLE
[Enhancement] Timer beeps multiple times to indicate which minute it is

### ISSUE THREAD

**Issue by GilDev** [opentx/opentx#3303]
Hi,
When I'm flying (mostly quadcopters, sometimes FPV), I have a timer counting up on my screen to know approximately when I should land (when I don't have OSD). I use the option “Beep every minute”, but it would be a lot more useful if it could beep a number of time relative to the current minute. For example if it counted up one minute, it beeps once. Two minutes, beeps twice. And when it comes to the sixth minute, it just resets to one beep so that you can keep up tracking the number of beeps, then two, etc.
I hope I was clear, it would be an incredibly useful feature to have. Hope it gets implemented.
Thanks!

**Comment by kilrah** [comment]
What radio are you using? All platforms that support it have that spoken

**Comment by GilDev** [comment]
Turnigy 9X, it just beeps once every minute

**Comment by kilrah** [comment]
Good idea. Not sure of how much interest it will generate among the developers though, I believe the last time anything was done for the stock 9x platform was a couple of years ago... having to optimize every single byte of memory has kind of grown old...

**Comment by GilDev** [comment]
Too bad, it's still a pretty great radio for a very low price…

**Comment by kilrah** [comment]
A 9XR-Pro is miles above in capability, doesn't require modding to install a programmer, and only costs $10 more!

Anyway I see you have some programming experience, if you want to have a go you might learn something :)

**Comment by GilDev** [comment]
Yeah I guess I need to update my equipment… 9XR-Pro or Taranis? That's the question! I didn't found clear informations on this: is the 9XR-Pro usable as a joystick with the mini-USB port like the Taranis? I'm on Mac and I'm tired of using CRRCSim for it's audio input capability. I want some FPV!
Anyway, multiple beeps sometimes is more discrete than some woman speaking out loud. Maybe I'll try to implement the feature, I took a look at the code already but it looks pretty messy, I'm not sure where to look. ^^ And I'm no Git expert. If I need to publish my code I will not know what to do: branches, testing…

**Comment by kilrah** [comment]
The 9XR-Pro could technically been used as joystick but nobody has written code for it yet.

**Comment by GilDev** [comment]
Well again, too bad, but I think I will go with a Taranis+ next, and I will look at the code to see what I can do about those timer beeps. Thanks for your answers!
