### ISSUE TITLE
[Enhancement, Usage][Companion ,OpenTx] Inputs and Mixer, add Clear/Set all Flightmodes

### ISSUE THREAD

**Issue by 483917** [opentx/opentx#3305]
I use Flightmodes in all my models 
And when i make new input or mixer, all flightmodes are selected as default and that is good.
But often i only need an input or mix to be active in 1-3 flightmodes
In Companion it would bee nice to have a Clear/Set-all flightmode Button,
then if i want to have a mix active in FM1 only, I click  the "Clear flightmode Button" and
click FM1 checkbox Done. 
Look at pictures below
![companion-input-mixer-clear fm](https://cloud.githubusercontent.com/assets/6617907/13172746/ff3aaab8-d6f9-11e5-8306-50d300fc40dc.PNG)

And on Radio when input or mixer flightmode is selected, Long press enter could clear/Set-all flightmodes.
Then i select the FMx i want as usual.
![radio-input-mixer-clear fm](https://cloud.githubusercontent.com/assets/6617907/13172842/9163fe80-d6fa-11e5-88cf-ec2dfa061d5f.PNG)

If this is a useless idea just close this issue

**Comment by kilrah** [comment]
Maybe an "Invert"...

**Comment by 483917** [comment]
Yes that would work too i guess

**Comment by elecpower** [comment]
plus one supporting request
