### ISSUE TITLE
playNumber says the wrong number

### ISSUE THREAD

**Issue by Mrono** [opentx/opentx#3306]
playNumber(123, 0, PREC1) plays 12.8 instead of 12.3
11(0-9) will play 11 no matter what
101 = 10.6

All numbers are screwed up unless it ends with a 0

Occurs in both companion sim and taranis

Taranis x9d plus running 2.1.7
Companion 2.1.7

**Comment by kilrah** [comment]
You likely have a 2.0 voice pack.
