### ISSUE TITLE
[Companion 2.1.7N653-Simu, Taranis B] FM-screen corrupt graphics

### ISSUE THREAD

**Issue by 483917** [opentx/opentx#3307]
Windows 10 pro swedish
Companion 2.1.7N653 eng
Taranis B ,Fw : opentx-taranis-haptic-timer3-lua-mixersmon-sqt5font-en-2.1.7N653.bin

In Companion-simulator and on Taranis Flightmode screens the switch arrows don't look so good
See picture below.

![fm-swt-grafic-bug0](https://cloud.githubusercontent.com/assets/6617907/13199458/fd519cfc-d825-11e5-9d2f-89d54c186c0b.png)

If this issue is reported alredy, just close this issue

**Comment by bsongis** [comment]
The switch name is covered by the +0, I will move it a little bit to the left, there is some space left

**Comment by 483917** [comment]
Thank you ,you guys do an amazing job :+1:
