### ISSUE TITLE
bad permision on 2.1.7 in debian 32 bit

### ISSUE THREAD

**Issue by nigelsheffield** [opentx/opentx#3309]
got this result when i installed in ubuntu

Lintian check results for /home/nigel/Downloads/companion21_2.1.7_i386.deb:
E: companion21: control-file-has-bad-permissions md5sums 0664 != 0644

**Comment by kilrah** [comment]
Yup known packaging issue, no apparent solution with the tools used.

https://github.com/opentx/opentx/issues/2893
