### ISSUE TITLE
Hungarian Sound Pack V2.1

### ISSUE THREAD

**Issue by hori64** [opentx/opentx#3319]
The Hungarian Sound Pack is missing from the V2.1.
We have prepared one of the Hungarian RC Forum:
https://drive.google.com/file/d/0B5pTbINRksqSNEtLZ3hpckRHYnM/view

But this package can only work perfectly when it is in the SOUNDS\en directory.
(I tried to create one based on the opentx-2.1.7\radio\src\translations\tts_hu.cpp, but it did not work properly)

I think the solution would be to tts_hu.cpp the same work as the tts_en.cpp.

Please, somebody help us!

**Comment by projectkk2glider** [comment]
Are you sure that the grammar for numbers is the same in Hungarian and English. That is the purpose of separate tts files.

**Comment by projectkk2glider** [comment]
I've just checked both tts files. They are basically the same, grammar is the same. Only the HU file has different constants which could be corrected to work with the new sound pack. 

But this will then brake the old Hungarian sound packs. Do you think this will be a problem?

**Comment by projectkk2glider** [comment]
I see that no official 2.1 sound pack was made for Hungarian. So I think there is no problem changing this. Agreed?

**Comment by hori64** [comment]
Yes. We want to use this pack.

**Comment by hori64** [comment]
I built a development environment and modified the tts_hu.cpp.
I checked in the simulator. It works perfectly.
I'm not sure how well I uploaded this on Github.
I did it well?

**Comment by hori64** [comment]
I do not have permission to add a new branch.
Here is the new tts_hu.cpp:
https://drive.google.com/file/d/0B5pTbINRksqSTVpOTEpEWWhyUGM/view?usp=sharing

**Comment by kilrah** [comment]
Thanks, committed and pack uploaded!
