### ISSUE TITLE
Translation from 2.0 to 2.1 result in bad values.  

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#3320]
Hi, 
is posible to correct this version migration issues? 

![image](https://cloud.githubusercontent.com/assets/2682800/13358024/821ab334-dcad-11e5-899a-b2348772da0b.png)

![image](https://cloud.githubusercontent.com/assets/2682800/13358029/886097e0-dcad-11e5-8d57-e4aa4593683d.png)

Thanks
Jan

**Comment by kilrah** [comment]
No.
All telemetry-related settings are lost when upgrading.
