### ISSUE TITLE
enhancement: bind emergency replacement transmitter to the same receiver

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3321]
When having contests, in the stress and hurry, you are bound to drop a transmitter some day. (I did).

when switches break off, typically launch switches, you would like to be able to grab the spare transmitter, and not have to worry about binding it again.

No idea if this is possible, but it woud be a BIGGGG plus.

**Comment by kilrah** [comment]
Impossible by definition, the whole purpose of binding being to make sure one and only one transmitter can control a receiver.

You can use an external module and move that from one radio to the other...

**Comment by lshems** [comment]
Well, your solution is genial nonetheless. Thanks
