### ISSUE TITLE
make unit optional in LUA playNumber(value, unit [, attributes])

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3328]
If omitting unit, have playNumber just play the number without unit.

playNumber(value [, unit [, attributes]])

unit 0 is missing in the list for 2.1 in the documentation.

suggestion: 0 for no unit play; nil or omitting no unit play.

**Comment by kilrah** [comment]
UNIT_RAW?

**Comment by projectkk2glider** [comment]
Using 0 for `unit` will do what you want - play a value without a unit.

**Comment by lshems** [comment]
https://opentx.gitbooks.io/opentx-lua-reference-guide/content/general/playNumber.html

doesn't reflect this yet. 

I would be happy to do the update, but ...??

**Comment by projectkk2glider** [comment]
Done now.

**Comment by lshems** [comment]
Thanks. Just a detail, but nonetheless :)
