### ISSUE TITLE
9XR models/ settings not read by Companion 2.0

### ISSUE THREAD

**Issue by obguy99** [opentx/opentx#3333]
1)No problem writing models to radio but can't read model settings to companion.
See below. m128 running with 2.019 with EEPR 217.
Is this radio not supported? (see 2nd image)

If I write a model on companion and save it onto my computer I can not later open that file (to modify) and then rewrite to radio. (see first image) below
![capture](https://cloud.githubusercontent.com/assets/17563000/13419845/78e656b8-df3e-11e5-899d-572aa78ebdf2.JPG)

Started AVRDUDE
C:/Program Files (x86)/OpenTX/Companion 2.0/avrdude.exe -c usbasp -p m128 -P usb -U eeprom:r:C:/Users/POPROX~1/AppData/Local/Temp/4272-temp.hex:i
=================================================================================

avrdude.exe: error: programm enable: target doesn't answer. 1 
avrdude.exe: initialization failed, rc=-1
             Double check connections and try again, or use -F to override
             this check.

**Comment by kilrah** [comment]
Do you have the correct radio type selected? How are you saving that model?

**Comment by obguy99** [comment]
I download the firmware for 9XR m128 (it is a stock unmodified radio). I'm almost sure that is correct. I 1)write a model into the companion then 2) click save as (name on my desktop) then 3) click write models/settings to radio. That part works.
What I can't do is 1)Read models /settings from radio or 2) open the file that I had "saved as". Therefore each time I want to write a model I am starting from the beginning.
:) 
It's still better than the stock firmware!
Are there some specifics for the m128 stock 9XR that I am missing?

**Comment by obguy99** [comment]
forgot to mention that I can only write firmware to radio if I uncheck (check firmware) and uncheck backup. Works well if I uncheck those.

![capture](https://cloud.githubusercontent.com/assets/17563000/13429132/ece56a26-df7b-11e5-928a-22bb9c09324c.JPG)

**Comment by kilrah** [comment]
Looks like it might be a problem with your programmer. Please continue this discussion on forums, you'll likely get better help there and this issue tracker is meant for OpenTX development discussions, not user support.

**Comment by obguy99** [comment]
Understood, thanks! What about the issue of writing the model on companion and saving it to my computer and then later trying to open it? Shouldn't companion be able to open that file, regardless of the programmer or even the radio? I'm going to try an Arduino uno programmer. Thank you!

**Comment by kilrah** [comment]
Ah yes, that is an issue indeed.

**Comment by obguy99** [comment]
Ok. So 2.1 differently saves the models in "save as" and then opens them later without difficulty? That would help a ton since for my simple needs I can write to but not read with the companion to 9XR. At least I can then modify previous work and not start over each time.

**Comment by obguy99** [comment]
Confirmed - saving to computer and can reopen that file for future editing works in 2.1.
 :) 
Happy guy since that creates a long term work flow with 9xr
