### ISSUE TITLE
io.open(file,"r") crashes companion on non-existing file instead of returning nil

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3342]
When trying to open a non-existing file for read only, companion crashes, instead of returning nil

**Comment by projectkk2glider** [comment]
Do you know if it works on a radio?

**Comment by projectkk2glider** [comment]
@bsongis I guess this should be ported to master.

**Comment by bsongis** [comment]
Yes!

**Comment by athertop** [comment]
I have just been testing new script I have written in Companion 2.1.9 and this issue  still appears to exist. Trying to open a file which does not exist results in a LUA disabled! [EXIT] message screen. This issue does not affect  2.1.9 running on a Taranis plus radio, only in simulator 2.1.9. Works fine in sim 2.2 also.

local f = io.open(cfgFile, "r")

**Comment by projectkk2glider** [comment]
Confirmed.
