### ISSUE TITLE
io.open(file,"r") crashes companion on filenames starting with a dot instead of returning nil

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3343]
Io.open('/directory/.lua','a') crashes companion.

So when constructing filenames to load from file="somefile" and io.open("/directory/" .. file .. ".lua"," a")
Make sure file is not "".

**Comment by projectkk2glider** [comment]
Most likely related to #3342

**Comment by projectkk2glider** [comment]
Do you know if it works on a radio?

**Comment by bsongis** [comment]
Duplicate of #3342
