### ISSUE TITLE
Add lua function getLanguage() to be able to make script texts match transmitter language.

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3344]
There are two places for language definition:

In compile options for user interface. Covered in earlier request to make used compile options accessable from lua.

In language for sound files.

Please make those available for proper localisation of scripts.

**Comment by lshems** [comment]
Language,voiceLanguage=getLanguage()
?

**Comment by lshems** [comment]
And 
language=getlanguage("text")
VoiceLanguage=getLanguage("voice")

**Comment by bsongis** [comment]
Will be only present in 2.2.0

**Comment by projectkk2glider** [comment]
My mistake, I did not see the commit and thought that issue was closed by mistake.

**Comment by bsongis** [comment]
It's completely untested

**Comment by projectkk2glider** [comment]
I will reopen and close it after I test it.

**Comment by projectkk2glider** [comment]
I do not like this implementation for two reasons:
* it defines two new functions, but the values could be returned in existing function `getGeneralSettings()`
* the `getTTSLanguage()` is too complicated and does not work, the `g_eeGeneral.ttsLanguage` is not set until user select the language for the first time. I would be better to use `currentLanguagePack->id` directly.

I will prepare a pull...

**Comment by lshems** [comment]
Wow, nice solution!

**Comment by projectkk2glider** [comment]
Thanks, my goal is to not introduce new Lua functions unless absolutely necessary.

**Comment by lshems** [comment]
Well, mine is to be able to write scripts using the transmitters GUI settings for voice and text. Now I can.

This solves the other issue as well. Close it down?

And there is one for getting the compile parameter known in LUA, Sort of same reason. Cant see of another compile option useful to know? NoGVARS and NoOverridechannel perhaps can be tricky, as well as noheli. MMM, better leave that one open.

**Comment by lshems** [comment]
Update Milestone 2.1.8 ??

**Comment by projectkk2glider** [comment]
No, this will be in 2.2.0

**Comment by lshems** [comment]
Pity, but thanks anyway. Looking forward ;)
