### ISSUE TITLE
Bootloader problems 2.1.7

### ISSUE THREAD

**Issue by WSWhitby** [opentx/opentx#3345]
Help Please.
PC with Win 10,
I have downloaded and installed Companion TX Ver2.1.7. I have downloaded ,with Taranis off, Firmware V2.1.7 I have then uploaded that firmware to the radio and all works OK I get a message at the end of the firmware download ".........Device returned transfer size 2048
DfuSe interface name: "Internal Flash  "
Downloading to address = 0x08000000, size = 369216
.....................................................................................................................................................................................
File downloaded successfully
No valid DFU suffix signature
Warning: File has no DFU suffix  "
I then reboot the taranis in Bootloader mode ..Trims together etc. Taranis reports Bootloader -2.1.7 and when I connect USB it reports USB connected I then try and "Read Models and Settings" and get the message "No Radio found" I have tried uninstalling and reinstalling at least 3 times all to no avail. Any suggestions would be very welcome

**Comment by kilrah** [comment]
Please use forums for support, this is not a software issue.

Most likely you overwrote the mass storage driver with Zadig (used it with radio ON instead of OFF). You need to restore it by deleting the device and driver in the device manager while connected in bootloader mode.
