### ISSUE TITLE
Companion Sync SD card no syncing

### ISSUE THREAD

**Issue by pointu** [opentx/opentx#3351]
Hi,
Using (nice idea) SD card sync, but there is no syncing from a changed file on pc to old one one SD card (old old, lot of days).

W7 / OTX 2.1.7 / Companion 2.1.7

**Comment by projectkk2glider** [comment]
Please provide more data, like the dates for affected file both on SD card and on computer.

**Comment by pointu** [comment]
![capture3](https://cloud.githubusercontent.com/assets/2773940/13730277/5a7711ec-e94b-11e5-99e9-826456543c09.JPG)
File test1.lua not synced
The opposite don't work also
![capture4](https://cloud.githubusercontent.com/assets/2773940/13730297/d6ecfcd2-e94b-11e5-98bd-3a31cbd8df14.JPG)

But it work in both sens when file is missing on the other side.

**Comment by projectkk2glider** [comment]
Thanks for additional info. This one is strange...

**Comment by projectkk2glider** [comment]
@pointu if the file contents are the same, the files will not be copied, even if their date differs. Please confirm that your `test1.lua` files have different contents.

**Comment by pointu** [comment]
I confirm there is a different contents, i add a comment

**Comment by projectkk2glider** [comment]
I can't find any reason (in the source code) why it is not working for you. Can you provide additional information like: 
 * does the name of the files matter
 * does the position of file matter 
 * does only happen for particular dates
 * try the same thing with English language selected
 * are more files affected or just this one.

**Comment by pointu** [comment]
i change the language for english > nothing more
I change the system date/time to utc > nothing more
I update a lot of files  > nothing more
i try for a long time, it never work  > nothing more
all files are affected and in other directory too

**Comment by pointu** [comment]
Verifying with syntoy :
![capture5](https://cloud.githubusercontent.com/assets/2773940/13760186/1c90bd96-ea32-11e5-96be-4930a7b5c0c4.JPG)
With Companion:
![capture6](https://cloud.githubusercontent.com/assets/2773940/13760218/4a978d82-ea32-11e5-8397-e72a84d5ae78.JPG)

**Comment by pointu** [comment]
No more to say
Test again and again in different ways, nothing more.
Is there a way to obtain the list of files with there attributes Companion get to go forward ?
(i'm not a dev so it's impossible for me to modify obtain and use the code)

W7 / OTX 2.1.8 / Companion 2.1.8

**Comment by pointu** [comment]
Does someone can give me a test version that give me a log of sync to analyze like files in both sides like companion see them ?

**Comment by projectkk2glider** [comment]
I will prepare something for you, hold on...

**Comment by pointu** [comment]
Thanks for all
The goal is to go forward or close !

**Comment by projectkk2glider** [comment]
While implementing a debug logging of sync process, I discovered a bug. It is now fixed. @pointu please check with the next nightly build (which I will start now).

**Comment by pointu** [comment]
Will test that

**Comment by pointu** [comment]
N771 or N711  ?

**Comment by projectkk2glider** [comment]
Ups, 711 which is now ready.

**Comment by pointu** [comment]
Think u do a loop, look > 
![pass 1](https://cloud.githubusercontent.com/assets/2773940/14563990/d58dde5e-0324-11e6-88d2-5e1eaa90100b.JPG)
U write first in the correct way, but u write again in opposite way

That's why u have to test if the size have change, because the date/time have are few second different but the size are equal and i think it's not a good idea because u can have same weight for a file with different contents.

**Comment by pointu** [comment]
More
It arrived only with the first file when there is more than one file not with the  other

**Comment by pointu** [comment]
The result is 
![pass 2](https://cloud.githubusercontent.com/assets/2773940/14564475/f5f2cd92-0326-11e6-8d3d-0614d57d1d70.JPG)
Because the date/time are not equal

**Comment by projectkk2glider** [comment]
I see another issue. Reopening

**Comment by projectkk2glider** [comment]
Please try with N712. It will be ready in about 15 minutes.

**Comment by pointu** [comment]
Better,
But the last... The modified date of the copied file is the date of the copy, not the date of the original file file, so they're always a different between the source and the target and that's not correct to verify who's the last
![pass 3](https://cloud.githubusercontent.com/assets/2773940/14573408/2c9e7ca0-0355-11e6-941d-c542d674e4ce.JPG)
This is the result of sd sync, the file is the same but the last modified timestamp is not good.

**Comment by projectkk2glider** [comment]
>The modified date of the copied file is the date of the copy, not the date of the original file file

This is how the current algorithm is supposed to work. Not sure it is the best/correct way. I will try setting the modified date.

**Comment by kilrah** [comment]
The date of the copy should be the date of the original, otherwise every copied file will always be detected as modified on the next sync.

**Comment by projectkk2glider** [comment]
Perhaps the current algorithm to detect change is flawed. It first checks for the modified date difference and proceeds only if they are different. So now we can have two files with the same name and modified date, but different contents and they won't be synced.

**Comment by projectkk2glider** [comment]
One must also be careful, not all file-systems have the same modified date/time resolution.

**Comment by pointu** [comment]
How could you have "two files with the same name and modified date" with different contents ? the last date/time is the good date/time thats how sync programs like synctoy work, otherwise you have to do a contents check

**Comment by pointu** [comment]
what did i do close ?

**Comment by elecpower** [comment]
> One must also be careful, not all file-systems have the same modified date/time resolution
Not ideal but assuming there is no way to solve and @kilrah point on flip-flop syncing what about a small time tolerance eg 1 sec?
The files being synced are highly ulikely to be changing within the date/time resolution variance on both the source and destination and remain the same size.

**Comment by projectkk2glider** [comment]
I think the current state of the sync algorithm is OK. If two files have different date, but have the same contents, their dates won't be updated. This is how @bsongis originally wrote the algorithm.
