### ISSUE TITLE
2.1.7 Telemetry Precision syntax very different on Taranis and in Companion. Confusing.

### ISSUE THREAD

**Issue by BurtPR** [opentx/opentx#3352]
I am adjusting parameters for a current sensor. On the Taranis I adjust Precision to 0.00 and it improves behavior of the sensor/Taranis. I am pleased. 

In Companion it show Precision 2, not Precision 0.00. I get the relationship (2 decimals) but it is jarring to the aged brain. Might want to clean it up in version 2.2.24? Might not?

Thanks for all your great work.

**Comment by projectkk2glider** [comment]
Should be done together with https://github.com/opentx/opentx/issues/2781#issuecomment-158743482
