### ISSUE TITLE
Taranis Telemtry won't work

### ISSUE THREAD

**Issue by sniperxnl** [opentx/opentx#3355]
Hello,

I fly almost erveryday with my X9D Taranis.
On a day my Telemtry for the voltage stopt.

I buy a new X4r-SB and a D4R-II, but same problem

My version is:  Bootloader 2.0.19

**Comment by projectkk2glider** [comment]
This is either a hardware problem specific to your radio or a configuration problem. I advise you to seek help on related forums. This page is for actual OpenTX issues/bugs/feature requests.
