### ISSUE TITLE
Date and time resets after off x9e

### ISSUE THREAD

**Issue by free6k** [opentx/opentx#3361]
Date and time resets always after off x9e

This happens after some time after switching off, if you just turn the time is not reset

I have taranis x9e EU 2015
OpenTX 2.1.7 non-eu version

I read about this problem fixed in 2.1.2 version?

Thanks for answers!

**Comment by kilrah** [comment]
Some early X9Es were delivered with a dead clock battery, check that first.

**Comment by free6k** [comment]
Thanks for you answer! Where i can see taranis x9e scheme for check battery? Do you have manuals or photo? )

**Comment by hrenz** [comment]
Its under the Batterie
 think its a CD2032 RTC Batterie

**Comment by free6k** [comment]
@hrenz thanks you!! Great answer! I will try tomorrow replace battery... I have CR2032 at home. CR2032 and CD2032 different batteries? If yes, i will give answer tomorrow.

**Comment by kilrah** [comment]
AFAIK it's a 1220, not 2032.

**Comment by projectkk2glider** [comment]
Also check that you have a capacitor (circled in below photo) installed, this one is vital to the clock preservation.
![cap](https://cloud.githubusercontent.com/assets/5950438/13771407/e5cdf1dc-ea8d-11e5-9429-74de77665fe2.png)

**Comment by hrenz** [comment]
Yes,  of course .
I have  changed this condensator too, becaue RTC Batterie was ok
470µF/16V or so

the original Cap was to short

**Comment by free6k** [comment]
I today buy battery cr1220. I will change tomorrow. the capacitor is available. Thanks for good support!

**Comment by free6k** [comment]
Thank you all for answers. I changed battery. In during all day i checked the time in x9e. Work very well! The problem can be closed
