### ISSUE TITLE
google earth not opening in 2.1.7

### ISSUE THREAD

**Issue by nigelsheffield** [opentx/opentx#3365]
I cant get get anything to happen when I try to link to google earth, I have set the path as I did in 2.0 which worked but now nothing happens when I press the google earth button.
I have not changed any names of any sensors.
windows 7 taranis none plus.

**Comment by projectkk2glider** [comment]
Do you get any dialog message with an error?

**Comment by projectkk2glider** [comment]
Please upload a log file example somewhere and post link here, so I can do a test here.

**Comment by nigelsheffield** [comment]
http://www.rcgroups.com/forums/showpost.php?p=34290206&postcount=34

a link to the file which I cant get to open to google earth. No error message just nothing happens, if I select an old file from 2.0 it gives an error message about gps wrong labels.

**Comment by kilrah** [comment]
No issue here.

![ge](https://cloud.githubusercontent.com/assets/6065069/13877289/32d31e98-ed23-11e5-8582-9f4d532fced6.jpg)

**Comment by nigelsheffield** [comment]
I must have done something wrong then, because i still get no response from this file, i still have 2.0 installed and that also does nothing also with this file but does work with old files from 2.0 
but 2.1 reports a problem with old files and just does nothing with this file...

**Comment by nigelsheffield** [comment]
ok i got it linking now , i had wrong executable selected sorry.
I dont see any data on screen though, I think i have setting wrong for altitude or something in google earth?

**Comment by nigelsheffield** [comment]
I can get to see the path by adjusting height but altitude tracking looks wrong, all the same level to look  at though when clicking on parts of path it says different altitudes.

**Comment by projectkk2glider** [comment]
Try different altitude setting in Google Earth track properties, like clamp to ground, etc...

Did you close ths by accident?

**Comment by nigelsheffield** [comment]
I tried different setting  under edit , properties and tried every track option for altitude , maybe I need to enable GPS altitude logging for it to work but I did have baro altitude logged.
To be honest I don't know what to expect as this is the first time I've had GPS and don't know whether the map tracking graph tracks the altitude or if it is just displayed in a graph.
I closed it because it's obviously nothing wrong with companion and just my lack of knowledge ...

**Comment by kilrah** [comment]
> maybe I need to enable GPS altitude logging for it to work but I did have baro altitude logged.

Yes at this point the Google Earth export only looks at the "GAlt" column. 

Making the GPS/Alt/Speed fields selectable is a possible improvement listed in #2569.
