### ISSUE TITLE
RSSI is read as minutes instead of DBs

### ISSUE THREAD

**Issue by carloss66** [opentx/opentx#3367]
I configured the controller to speak the RSSI level.  The RSSI unit is spoken in minutes instead of decibels.  To get the remote to say decibels, I had to change the RSSI unit to Fahrenheit.  This is on version 2.1.7.

**Comment by kilrah** [comment]
You've got an old 2.0 voice pack on your card.

**Comment by fraternl** [comment]
Can't you write an autoresponder for this?

**Comment by kilrah** [comment]
If only... but people always manage to find a different way of referring to it!

**Comment by projectkk2glider** [comment]
We should have FAQ wiki page.
