### ISSUE TITLE
companion 2.1.7 missing telemetry protocol choice

### ISSUE THREAD

**Issue by nostromo123** [opentx/opentx#3372]
Just found an issue in companion 2.1.7
Telemetry screen in companion only offers 2 choices. See attached screen shot. 
FrSky D (cable) is missing in companion. Needed for our MPX FrSky telemetry converter to get the data into Taranis ...
![screenshot_15](https://cloud.githubusercontent.com/assets/17964433/13904871/458410f0-eeaf-11e5-9308-b4970c7604ce.jpeg)

**Comment by kilrah** [comment]
Indeed. You can set it on the radio itself in the meantime.

**Comment by nostromo123** [comment]
Took me half an hour to find out ;-)
Was looking for any issues with our converter
br KH

**Comment by nostromo123** [comment]
Sorry, not used to the buttons here. Was my #1 at github ...

**Comment by projectkk2glider** [comment]
Don't worry, it often happens. :smile:
