### ISSUE TITLE
companion 2.1.7 - German text showing up in English GUI

### ISSUE THREAD

**Issue by nostromo123** [opentx/opentx#3376]
Only a minor issue, but stumbled over those German words showing up in English companion GUI?
Have both opentx and companion set to English language ....
![screenshot_19](https://cloud.githubusercontent.com/assets/17964433/13919603/c24b610a-ef6e-11e5-838a-4cc2bd9d56e5.jpeg)

**Comment by kilrah** [comment]
Looks like your system language is set to German, and automatically replaces some standard strings?

Can't reproduce here.
Are you running the officially distributed package or a self-compile?

**Comment by nostromo123** [comment]
Official package, system is Debian Jessie KDE 64 bit.
Linux system language is set to German.

**Comment by nostromo123** [comment]
Strange.
Have a backup Debian Jessie KDE 64 bit in a vbox. Set that system to "system language" English.
Installed companion ... No issue there .... Don't understand, what causes that language mixture????

![screenshot_20](https://cloud.githubusercontent.com/assets/17964433/13922459/b5e0a5d4-ef7c-11e5-93dd-6d4c313e1cef.jpeg)

**Comment by kilrah** [comment]
It must be something on your system, given that nowhere in the OpenTX code do either of the 2 words appear, not even in the German translation files!
