### ISSUE TITLE
9X pot 3 problem

### ISSUE THREAD

**Issue by MikeBland** [opentx/opentx#3379]
A problem has been identified on the (original) 9X, mainly with the M128 processor. The JTAG port is enabled on the processor. This shares signal lines with 4 of the analog inputs. Certain movements of pot P1 and pot P2 can cause the JTAG TDO signal to become active, causing pot P3 to be read incorrectly.
The solution is to disable the JTAG port. The code I've used on er9x is below:

#ifdef CPUM2561
  uint8_t mcusr = MCUSR; // save the WDT (etc) flags
   SaveMcusr = mcusr ;
  MCUSR = 0; // must be zeroed before disabling the WDT
  MCUCR = 0x80 ;
  MCUCR = 0x80 ;   // Must be done twice
#else
  uint8_t mcusr = MCUCSR;
  MCUCSR = 0x80 ;
  MCUCSR = 0x80;   // Must be done twice
#endif

Note that the MCUCSR (and MCUCR on the '2561) have protection and bit 7 is only modified if is written twice within 4 clock cycles, so these must be written twice with interrupts disabled.

The JTAG port may also be disabled by setting bit 6 in the High fuses ('64/'128/'2561).
It is worth modifying Companion so that if it updates the fuses then this bit is set.

**Comment by kilrah** [comment]
Already included in https://github.com/opentx/opentx/commit/e1bcbfa013cc061b152c65a8e520dfef864c3626, thanks!
