### ISSUE TITLE
Lua: bitlib not working

### ISSUE THREAD

**Issue by hsteinhaus** [opentx/opentx#3381]
When calling a `bit.lshift(x,8)` from Lua script, I get an interpreter error: Attempt to index global "bit", a nil value. `bitlib.lshift()` doesn't work either. Constructions like `require "bit"` or `require "bitlib"` also don't work.

The bitlib seems to be part of the interpreter on OpenTx 2.1.7. I double-checked that the bitlib gets compiled into the image (that happens).

**Comment by lshems** [comment]
Use bit32

**Comment by projectkk2glider** [comment]
see #1626
