### ISSUE TITLE
Symbols not displaying properly in MIDSIZE

### ISSUE THREAD

**Issue by Daemonentreiber** [opentx/opentx#3386]
Hi.
When using "MIDSIZE", symbols are not displayed properly.
Only happens on "MIDSIZE", all other fonts are working.

![screenshot-3](https://cloud.githubusercontent.com/assets/7510243/14059684/25fa542a-f34a-11e5-880a-e00291ffdfbf.png)

**Comment by kilrah** [comment]
The "extra" characters are only implemented in SMLSIZE, normal and DBLSIZE.

**Comment by Daemonentreiber** [comment]
Seems i forgot to test it in "XXLSIZE".

Whats the reason they not implemented in MID and XXL?
MIDSIZE is the perfect size for most lua telemetry screens.

**Comment by kilrah** [comment]
That simply predates lua. Whoever added the new fonts probably didnt want to bother doing the extra work for those...
