### ISSUE TITLE
Distorted slow audio on 1 model

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3392]
When I started using a model again it suddenly has distorted slow audio as if the device is too busy doing something else

![eeprom-2016-03-30-055231 bin](https://cloud.githubusercontent.com/assets/8692856/14132386/95b05a8c-f645-11e5-9b65-494fc555d95c.jpg)
![end-march-2016 bin](https://cloud.githubusercontent.com/assets/8692856/14132392/a8e577ae-f645-11e5-8bf5-6e77147d079a.jpg)

http://hmvc.eu/2016-03-30.04.55.29.mp4

**Comment by fraternl** [comment]
I had no time to investigate this. Will do later, but wanted to save everything that might be needed to reproduce this.

**Comment by projectkk2glider** [comment]
It's an old problem that shows it self once in a while. Some related issues are #2020,  #1779, #894 and #894.

**Comment by lshems** [comment]
Same here. I've come to live with it, as I just run very extensive lua scripts, and they ALWAYS have my radio stutter.

I've recently found the debug statistics screen on the transmitter, by getting into statistics and pressing up.

Could anybody explain what these LUA parameters are, and what normal values should be??

Thanks.

**Comment by bsongis** [comment]
@lshems Do you mean you have one script which always reproduces this sound problem? This is VERY interesting is this is the case. Would it be possible you share this script? Lua scripts are executed in the main task which has a lower priority than the audio. That's said if your script uses a lot the SD card, it will take the mutex on DISKIO and will block the AUDIO task!

**Comment by lshems** [comment]
Any explanation on the debug Screen?

Ill see if i can make a Nice example to reproduce.

**Comment by projectkk2glider** [comment]
**Lua duration**: the maximum time it took to execute one *loop* of all Lua scripts.
**Lua interval**: the maximum time between calls to the Lua *loop*.  Bacically a measure how ofter the scrip `run()` function is called.

Both of these can be reset any time by pressing ENT on that screen. The numbers will rise with the script complexity.

**Comment by lshems** [comment]
Ok,

I got timings of 900-1300 for both duration and interval at the critical parts where stuttering is audible.
When stuttering has passed, due to finish of loading the script, it lowers to 30-140 for both.

I am almost sure it is not only file loading, but also calculation time.

**Comment by lshems** [comment]
I thought that every call to run() or background() needed to be finished in 20 ms??

So I do not understand the results and explanation. 

What is a loop ?? I have only 1 lua telemetry script running at the same time ?? It cannot take 900-1300 ms to finish, can it?

**Comment by projectkk2glider** [comment]
A loop is one iteration of calls to all active Lua scripts `run()` or `background()` functions.

> It cannot take 900-1300 ms to finish, can it?

Apparently it does take such a long time (remember this is max, so at least one loop took that long). The script execution time can be prolonged if Lua is waiting for free SD card mutex. That can for example happen when other threads (Audio or Telemetry logs) are using the card. The time spent in OpenTX Lua functions does not count against the script allowed instruction count. Only the true Lua instructions are counted. All opentx API functions are in fact C functions and they are not counted in Lua.
