### ISSUE TITLE
Potential model corruption

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#3413]
http://openrcforums.com/forum/viewtopic.php?f=96&t=8714&p=114036#p114036

2.0, but might warrant some investigation. No idea as is.

**Comment by pointu** [comment]
Hi Kilrah,

Why do u put this in 2.1.8 and not the next release, it will be a great idea for us, i suppose doing this stop the production of 2.1.8

Thanks

**Comment by kilrah** [comment]
2.1.8 IS the next release.

But this really seems like an individual random glitch, doubt we can do much about it apart from the existing planned improvement to include CRC checking of all data to detect it.

**Comment by pointu** [comment]
2.1.8 IS the next release.
I know and we wait for it for a long time !!!
That's why i propose for this 2.1.9

**Comment by kilrah** [comment]
If it is a problem it is very serious and would need fixing ASAP. 
But unless he can reproduce we will move it away.

**Comment by pointu** [comment]
ok i understand

**Comment by bsongis** [comment]
We need more data about this one.

**Comment by pointu** [comment]
that's why i said it can't be affected to a milestone
thanks

**Comment by kilrah** [comment]
But putting it to a milestone got the attention of everybody, which was the goal :)

**Comment by pointu** [comment]
for sure @kilrah but the first attention we need is the attention of the one who got the problem isn't it ?

**Comment by kilrah** [comment]
I meant among the devs.

**Comment by mpjf01** [comment]
I'm the "one who got the problem" and you have my attention as well. Despite spending a lot of time trying in the last couple of days I have not been able to make the issue happen again. I am flying blind a bit as I have no real evidence, just a guess really, of the event that caused the problem in the first place. If there's anything else that anyone can suggest that I should do, please let me know and I will do it.
