### ISSUE TITLE
Telemetry units

### ISSUE THREAD

**Issue by Oldgibber** [opentx/opentx#3414]
On the telemetry screen (2.1.8), the units can be changed to any other units visible, even though they might not be acceptable. e.g. changing mph to volts. I realise that obviously the program will not do a conversion and the reading will still be in mph. 
However, as an enhancement, would it be possible to only display appropriate units. 
Would this cause difficulties with some third party sensors? If so, how does the actual conversion cope with this problem.

**Comment by hrenz** [comment]
Well, what will you do ?

you read  3,56V  this represets a RPM of 12500 /min  or a fuel level  of 85% or other things

its importend to change units as you like
