### ISSUE TITLE
get an "404"... download links on open-tx.org for compainion 2.1.8 linux debian packages are wrong

### ISSUE THREAD

**Issue by wolkstein** [opentx/opentx#3418]
http://downloads-21.open-tx.org/companion/companion21_2.1.8_i386.deb

http://downloads-21.open-tx.org/companion/companion21_2.1.8_amd64.deb

**Comment by kilrah** [comment]
They aren't up yet.

**Comment by bsongis** [comment]
Give me 5 minutes, I am mounting up my VM
