### ISSUE TITLE
Companion Windows Build Instructions

### ISSUE THREAD

**Issue by pointu** [opentx/opentx#3419]
Not able to follow this instructions because of not up to date link and untesting version as @bsongis said ..
VS 2010 (unavailable on Microsoft site now) > 2015
QT link unavailable
CMake give this
![fishing](https://cloud.githubusercontent.com/assets/2773940/14541478/75e343da-028a-11e6-9652-f63a9a9ce2fb.JPG)
...
Can you verify that and giving us a new stable development environment.

**Comment by kilrah** [comment]
A new guide will be provided for 2.2.
