### ISSUE TITLE
Companion 2.1.8 on opentx.org is missing 64-bit deb version

### ISSUE THREAD

**Issue by zendes** [opentx/opentx#3420]
The 64-bit DEB link on http://www.open-tx.org/2016/04/14/opentx-2.1.8 is pointing to a non-existent file.

**Comment by kilrah** [comment]
#3418

A bit of patience, these aren't part of the automated build process and have to be made manually, they always come a couple of days later.
Should be up now.

**Comment by zendes** [comment]
ah, ok. i just came back from a holiday & saw that a new version got released. didn't realize it was released today.

thnx!
