### ISSUE TITLE
GPS Coordinates Compressed/Incorrect on Telemetry Screen - LUA

### ISSUE THREAD

**Issue by jmxp69** [opentx/opentx#3424]
GPS coordinates displayed using lcd.drawChannel(80,55,"GPS",0) results in truncated/compressed coordinates on the screen. It shows up the same with the telemetry simulator and with live data.

![gps](https://cloud.githubusercontent.com/assets/378637/14579909/3dec8d56-0370-11e6-8866-35cacf548eeb.jpg)

**Comment by kilrah** [comment]
The GPS display function is meant to display the appropriate 2-line format for the telemtry screens, it's not surprising it doesn't bode well with lua.

You might need to display lat and lon yourself separately the way you want them.

**Comment by jmxp69** [comment]
How would one go about parsing lat/lon from the gps sensor?

**Comment by projectkk2glider** [comment]
https://opentx.gitbooks.io/opentx-lua-reference-guide/content/handling_gps_sensor_data.html

**Comment by jmxp69** [comment]
PERFECT! Looks good so far. Thanks guys. Is there any reason the value can't be displayed correctly without going through all of that?

**Comment by projectkk2glider** [comment]
Looks like that function is meant to be used with `LEFT` attribute. Working example (notice that horizontal position will change):

```lua
local function run(event)
  lcd.clear()
  lcd.drawChannel(80,55,"GPS",LEFT)
  return 0
end

return { run=run }
```
![screenshot-1](https://cloud.githubusercontent.com/assets/5950438/14749797/d580663c-08c1-11e6-8e78-b5257ced556b.png)
