### ISSUE TITLE
Switch Positions Missing '<]'

### ISSUE THREAD

**Issue by firstof3** [opentx/opentx#3429]
Taranis X9D Plus, v2.1.8
Previously, I was able to setup default switch positions for each model so that OpenTx would warn me that a switch was not in the recommended starting position.  In the general settings of each plane (page 1), there was a line with each switch labeled with either an up arrow or nothing.  In prior versions, I could toggle up to blank and then save by long pressing '<]'.  And after that, toggling the switch would change it from blank to down and then I could save it by long pressing '<]' again.  
However, in v2.1.8, the '<]' is missing.  
In OpenTx University, ( http://open-txu.org/basic-airplane-class-2-7-preflight-checks/ ), it mentions that the direction of the arrow does not matter.  In v2.0.17, I was able to choose the direction of the arrow.  However, in v2.1.8, it seems to only be up or blank (except on models I ported over from v2.0.17 where I was able to set down.  on those channels, in v2.1.8, I can only set blank and down; there is no way to get that particular switch to up.  the actual position of the switch doesn't seem to matter).
It would be nice if the directions/instructions for setting the Switch Position remained the same from version to version so that the instructions don't have to be continually updated for small changes.

**Comment by kilrah** [comment]
> I could toggle up to blank and then save by long pressing '<]'.

You still do just the same, simply while the whole line is selected. There is no more room for the '<]' because now SH may have a switch warning too unlike before.
