### ISSUE TITLE
Centring precision 2.1.8

### ISSUE THREAD

**Issue by PieroCo** [opentx/opentx#3432]
see this video https://youtu.be/ymvEtfYWABY

**Comment by lichtl** [comment]
I have noticed this as well on my Taranis Plus when updating from 2.1.7 to 2.1.8

**Comment by kilrah** [comment]
That is a side effect of the filter that was implemented for people who complained of too much jitter at rest.

**Comment by projectkk2glider** [comment]
We have two options:
* disable jitter filter
* or merge #3250

**Comment by bsongis** [comment]
What about merging #3250 but with an option in Companion (or inside the UI, using a spare bit in the EEPROM, but it would use RAM even for those who don't need it)

**Comment by projectkk2glider** [comment]
I am for the option. The jitter filter itself should not use any more RAM. The jitter measurement does, but it can be disabled.
