### ISSUE TITLE
Suggestion: make companion output failsafe settings when telemetry RSSI is set to 0

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3433]
Currently there is no way to easily check if the failsafe settings correspond to desired outputs in companion.

This would enable to change just the RSSI value on the telemetry fake input from 75 to 0 and see how the outputs respond.

**Comment by kilrah** [comment]
> Currently there is no way to easily check if the failsafe settings correspond to desired outputs in companion.

Umm the percentages are the same?

**Comment by lshems** [comment]
I'll close it.

The concept of easy is subject to interpretation, and I don't have the time for posing argiments.

Thanks anyway.
