### ISSUE TITLE
Throttle inverse not acting on selected throttle source (companion and radio?)

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3435]
2.0.19, perhaps also 2.1 since it is not noticed yet??. 

When selecting LS as throttle source in the general screen, and selecting throttleinverse checkbox, it is the stick input from Throttle which is reversed.

If this is intended, why can you select a throttle source?

Confused or bug.

**Comment by projectkk2glider** [comment]
`Throttle source` an `throttle inverse` are two separate settings. 

>why can you select a throttle source?

It is used for:
* throttle trace
* THt and TH% timers

I see no problem, please elaborate or close the issue.

**Comment by lshems** [comment]
Thanks
 The screen is confusing to me, but understood

**Comment by kilrah** [comment]
Actually the throttle warning also follows the Throttle source setting, it probably shouldn't.
