### ISSUE TITLE
open V2.20  Missing at Horus the info lines we have a Taranis 

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#3441]
We have no Info lines at Horus 

at Taranis we have at 
Inputs, Mixers, Servos, log Switches, ....
![auswahl_437](https://cloud.githubusercontent.com/assets/6217896/14767919/83440550-0a32-11e6-9b31-1840d15e7f49.jpg)
![auswahl_436](https://cloud.githubusercontent.com/assets/6217896/14767920/87369a24-0a32-11e6-9991-bdebe3c2af02.jpg)
![auswahl_435](https://cloud.githubusercontent.com/assets/6217896/14767923/8b80ae3a-0a32-11e6-9101-49c27f8f6c7b.jpg)
![auswahl_434](https://cloud.githubusercontent.com/assets/6217896/14767933/e5890a76-0a32-11e6-8109-74f16a8927fc.jpg)

**Comment by kilrah** [comment]
#3393
