### ISSUE TITLE
Support other languages?

### ISSUE THREAD

**Issue by rebelboy** [opentx/opentx#3449]
why not Support other languages?

like German Chinese .

Thanks.

**Comment by kilrah** [comment]
German has always been supported.

Anything else can be if someone does the translation, but anything with completely new fonts or different orientations would be a lot of work.

**Comment by rebelboy** [comment]
Thanks
I'm a chinese user。
can support chinese language？

**Comment by bsongis** [comment]
It could be, but the problem will be the font, would you be able to build an image such as this one (with all chinese chars): 
https://github.com/opentx/opentx/blob/master/radio/src/fonts/std/font_05x07.png

**Comment by rebelboy** [comment]
Thanks  . I will try it ！  

I am working hard on my English .
