### ISSUE TITLE
Trims to Subtrims problem on Taranis Plus 2.1.8

### ISSUE THREAD

**Issue by Dfrazier1965** [opentx/opentx#3457]
I have a Taranis Plus on 2.1.8 and I have a small issue. It was brought to my attention by my brother-in-law and I verified it on mine also.
 Using trims to subtrims at the bottom of the outputs page, applies the subtrims necessary and centers all trims as expected. When on a single channel, long pressing on Enter brings up a choice to apply trim to subtrim for that channel, but using this method does not center the trim. Is this how it is intended to work or is it a bug?

**Comment by projectkk2glider** [comment]
I would say it is done like this on purpose. Imagine situation where one trim affects two or more channels.

**Comment by fraternl** [comment]
Ah... I didn't think of that... (I encouraged him to create the ticket).

**Comment by bsongis** [comment]
Yes exactly, @projectkk2glider is right and this is done on purpose!

**Comment by Dfrazier1965** [comment]
Didn't think of that. Makes perfect sense.
