### ISSUE TITLE
Simulator crashes with lua script

### ISSUE THREAD

**Issue by Spainman** [opentx/opentx#3462]
- create a lua script with playTone(2000, 1000, 20, 0, 100)
- companion and stand-alone simulator crash after running the playback 
- tested on Windows in Companion 2.1.8 running a function script and also as a one time script 
- emulated radio is taranis plus
- not tested on the actual hardware yet

In the meantime I would appreciate if somebody could help on how to use playTone. Reference guide lacks useful information on the _pause_ argument. Actually I was testing around with values to discover what pause might mean... Thanks.

Edit:
- _pause_ argument is clarified now - appends silence after the tone
- _freqIncr_ still is a complete mistery. Certain values generate a crash, others do not. None produces a sound I would expect. I would have assumed that it is the increase of the frequency over the specified duration of the sound either in Hz or as a factor of the initial frequency but it isn't. From the sound the frequency even overflows to the initial value depending on the value passed to freqIncr.

**Comment by Spainman** [comment]
Thank you for the bugfix. Still I would appreciate if you could comment on the parameter _freqIncr_. What are non-abnormal parameter values?

**Comment by projectkk2glider** [comment]
Perhaps you can help me formulate the text for *freqIncr* for Lua docs. Here is how it works:
* tone starts playing with the frequency that was set by the first parameter *frequency* (unit is Hz)
* every 10ms frequency is changed with a formula:
  * newFrequency = oldFrequency + 10 * freqIncr

Couple of examples:
 * `playTone(1000, 1000, 0, 1)` starts with 1000Hz, increase by 10Hz every 10ms, at the end (1s play time) the frequency reaches 10Hz * (1000ms/10ms) + 1000Hz = 2kHz
 * `playTone(1000, 100, 0, -5)` starts with 1000Hz, decrease by 50Hz every 10ms, at the end (0.1s play time) the frequency reaches -50Hz * (100ms/10ms) + 1000Hz = 500Hz

The valid range for *freqIncr* is from -127 to 127. Even small number has big effect.

**Comment by Spainman** [comment]
>Perhaps you can help me formulate the text for freqIncr for Lua docs

Thank you for explaining!!! See my post in the issue where we are discussing lua mix script failsafes. I will try to help with the guide. For now I would suggest you just add the description you just wrote here. I will then try to improve on it right in the guide. Ok?
