### ISSUE TITLE
Taranis won't bind.

### ISSUE THREAD

**Issue by 3000gt** [opentx/opentx#3466]
I am having a big problem getting my Taranis to bind after I updated my firmware. It started when I bought a X4Rsb receiver and could not get it to bind because it had new EU LBT programing. Someone told me I had to go update the firm ware. I did that, and still could not get it to work. I still could fly my other models at the time but just could not get the X4Rsb to bind. i tried various other things, and now my Taranis won't bind to anything. I even did a factory reset and can't get it to bind. When I look on the SD card, there is no firmware to be seen? I have version 2.1.8 opentx-taranis-plus on my radio Any help would be great, I think I just need to put the firmware back on the SD card, but can't find the .hex files.

**Comment by kilrah** [comment]
Not an OpenTX issue, what the person was telling you is that you need to match the firmware of the RF module and receivers. Tons of info about that on forums.

**Comment by 3000gt** [comment]
I've tried all that. I need to find the files that go on the SDcard. I've updated ALL my firmware, but there is no file on SD card.

**Comment by 3000gt** [comment]
Yeah, that's what everyone says,"Oh, just read a forum? They have tons of info" then they pass me on to the next guy without helping.
Thanks, I already know about all the forums and how useless they are to most people. 
Thanks anyway. I'll find someone who can, or wants to help.

**Comment by kilrah** [comment]
A quick Google search brings up a good enough tutorial for what I assume to be your need as per your incomplete description, i.e. the need for flashing an X4R-SB to non EU firmware:
http://www.dronetrest.com/t/how-to-upgrade-your-frsky-receiver-firmware-x8r-x4r-x4r-sb/1667

The firmwares for the modules and receivers (.frk files) are at the obvious place - the appropriate product's page in the "Downloads" section of FrSky's website.

**Comment by schwabe** [comment]
the rar files are archives, just a program like winrar to extract them.

**Comment by 3000gt** [comment]
Yeah, I finally figured that out. It still won't work. It says not a valid firmware file.

**Comment by kilrah** [comment]
WHERE does it say this? Please describe exactly what you're doing. Can't help you without that.
