### ISSUE TITLE
Inconsistent new model global variables initialisation by Companion and radio

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#3473]
The model created on the radio intialises the linked field for each GVar in FM 1-8 to "Flight mode 0 value" whereas Companion initialises to "Own value".

(Taranis X9D, Companion 2.1.8, Bootloader 2.1.7, Eeprom 217, Ubuntu 14.04, Windows 10)

**Comment by projectkk2glider** [comment]
We need to decide which one is correct - radio or Companion and adapt other one to do the same.

**Comment by elecpower** [comment]
Both default trims to "Use Trim from Flight Mode 0" so it would make sense from consistency to do the same for Gvars. 
There is some logic in FM0 being the default for all values and the starting point for all other FMs and you tweak each FM for its purpose.
If Companion is to change to the radio default the fix for #3214 will need to be revisited.

On a related point there is an an interface inconsistency in Companion when fields are linked to other FMs. For GVars the value field is disabled forcing you to go to the referenced FM to make a change (I agree with)  whereas trims are fully enabled and changes are pushed back to the referenced FM which has an element of risk especially if the default is FM0 (this is what happened in the first iteration of FM clear). The user may change the trim values and then set the linked field to Own Value not realising the changes have also been made to the previously linked FM. I would favour disabling the trims when linked to avoid the risk.

**Comment by projectkk2glider** [comment]
I agree with @elecpower on both points the gvar initialization and trim disabling.

**Comment by kilrah** [comment]
+1

**Comment by projectkk2glider** [comment]
@elecpower commit ce68f364255b4d878fe90581ce57872b122135fc needs to be ported to the `next` branch

**Comment by elecpower** [comment]
master and next fixed so closing
