### ISSUE TITLE
Companion UI bug: Mix line drag'n drop before CH1

### ISSUE THREAD

**Issue by Spainman** [opentx/opentx#3474]
Reproduction steps:
- edit model
- enter Mixes tab
- shift-drag a line of CH1 before CH01

       -> line appears before CH01
- shift-drag a line that does not belong to CH1 and is the only line in the corresponding channel

       -> line 'donor' channel moves completely before CH1

-> leaving and re-entering the mixes tab reestablishes a valid view
-> simulator radio menus show valid entries too when pressing Simulate from within the scrambled Mixes tab
==>> Perception-wise just an UI irregularity
Companion 2.1.8, Windows

**Comment by projectkk2glider** [comment]
>shift-drag a line of CH1 before CH01

I can not do this on Linux

But yes, the shift-drag to any position is broken.

**Comment by elecpower** [comment]
I can replicate on Ubuntu 14.04
