### ISSUE TITLE
[Edit Mix screen] Range indicator widget does not take into account weight sign

### ISSUE THREAD

**Issue by Spainman** [opentx/opentx#3476]
Title + screenshots below pretty much describe the whole problem

![screenshot-2](https://cloud.githubusercontent.com/assets/8582669/15100849/e64dacfc-157f-11e6-948d-79e2a6028be9.png)
- positive weight -> indicated range correct

![screenshot-3](https://cloud.githubusercontent.com/assets/8582669/15100847/e3709cec-157f-11e6-9f65-a8bfbe2802af.png)
- negative weight -> indicated range inverted

**Comment by tomkfly** [comment]
Surely that is correct. Range stays the same but stick/ switch works in the opposite direction.

**Comment by kilrah** [comment]
+1, the point of this thing is to show the movement range, the direction is irrelevant.

**Comment by Spainman** [comment]
I wasn't implying that the two numbers alone are the wrong way around, but the whole widget. Taking your comments into account, I assumed information embedded in the representation that isn't there. 

Let's leave sticks and switches aside and thing in terms of the resulting x/y-graph, that obviously isn't visible in the mix line screen.
Let's ignore what may have been specified for the widget behavior in the past and assume that
-  the widget serves as a **condensed representation of the graph**

Wouldn't the visualization as illustrated in the following
- make **sense**,
- transport **more useful information** than representing both graphs with the same widget,
generally **help to visualize the graph mentally** much better than representing both graphs with the same widget ?

![untitled](https://cloud.githubusercontent.com/assets/8582669/15113534/29285214-15f5-11e6-8064-ecc5bbf4afa4.png)

**Comment by tomkfly** [comment]
To me It's the same range,but you are travelling in the opposite direction, that makes more sense.

**Comment by projectkk2glider** [comment]
I went ahead and did this, @kilrah or @bsongis you decide if  you like it :wink: #3476

**Comment by mhotar** [comment]
I do not think it is right to merge. When the graph is swapped it will not match the one in the channel monitor. The range does not change with negative weight, from the channel point of view. We can add some graphics to the input line instead, to reliably indicete input is inverted.

**Comment by Spainman** [comment]
I have never seen the widget as a static representation of the channel monitor indicators. Anyway - I brought it up so it's clear that I prefer functionality and a representation that is intuitively understandable over conformance with something that is on an entirely different screen.

**Comment by projectkk2glider** [comment]
Reopening until we port the #3476 to the `next` branch.
