### ISSUE TITLE
Verfy the actual delay of delay_01us() function

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#3492]
Some test suggest that it is not right. Test environment in 2020807473d468fbf13db5798610d87d1c7e7c0e

**Comment by projectkk2glider** [comment]
With commit https://github.com/opentx/opentx/commit/4fe6122141552ae4abd08868ba3cde5fb7f221c7

On Horus:
```
delay 1ms  : 0.119ms - 0.120ms
delay 2ms  : 0.239ms - 0.239ms
```

Looks very wrong, now I am not sure if it is the delay or the measurement problem -ie debug timers. I will try the same on Taranis....

**Comment by projectkk2glider** [comment]
Similar *problem* on Taranis (tested with 87229ed4119840077c4e0364c812ab28dc14038b):
```
delay 1ms  : 0.167ms - 0.167ms
delay 2ms  : 0.334ms - 0.334ms
```
:fearful:

**Comment by bsongis** [comment]
It seems we have a *10 factor!

**Comment by projectkk2glider** [comment]
New method - same results (on Taranis):
```
delay 1ms  : 0.168ms - 0.168ms
delay 2ms  : 0.334ms - 0.334ms
```

**Comment by projectkk2glider** [comment]
Something fishy going on, with the timer prescaller multiplied by 2, I get the same times:
```
delay 1ms  : 0.168ms - 0.168ms
delay 2ms  : 0.334ms - 0.334ms
>p tim 13
TIM13
 CR1    0x2
 CR2    0x0
 DIER   0x0
 SR     0x2
 EGR    0x0
 CCMR1  0x0
 CCMR2  0x0
 CNT    0x2724
 ARR    0xffff
 PSC    0xb
 CCER   0x0
 CCR1   0x2710
 CCR2   0x0
 CCR3   0x0
 CCR4   0x0
```

**Comment by projectkk2glider** [comment]
Delay fixed, on Taranis:
```
delay 1ms  : 1.001ms - 1.001ms
delay 2ms  : 2.001ms - 2.001ms
```

and on Horus:
```
delay 1ms  : 0.953ms - 0.953ms
delay 2ms  : 1.905ms - 1.905ms
```

**Comment by bsongis** [comment]
Cool, thanks for fighting it!

**Comment by kilrah** [comment]
Cool!
Is it normal to be that off on Horus?

**Comment by projectkk2glider** [comment]
Yes it is normal, the timer clock is 84Mhz, so ideal prescaler would be 8.4-1. I will make adjustment for delay_ms() function.

**Comment by projectkk2glider** [comment]
@bsongis While the same problem exists in the `master` branch I am reluctant to make this change there. Do we agree and close this issue?

**Comment by bsongis** [comment]
Yes, it would bring problems
