### ISSUE TITLE
Companion 2.1.8 GERMAN version - path google earth

### ISSUE THREAD

**Issue by nostromo123** [opentx/opentx#3500]
Could someone please change the text in next GERMAN version companion settings from 

> Google Earth *.EXE Datei

to something maybe like 

> Pfad Google Earth

*.EXE make you think, it only works under windows. Which is not true.
Just tested google earth under Debian. Working fine.
And we usually don't have EXE files in Linux ;-)
Thank you for your good work - br
![screenshot 1](https://cloud.githubusercontent.com/assets/17964433/15294751/ccffe166-1b8d-11e6-99eb-f59b5f5f0f4e.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/17964433/15294754/d0121bee-1b8d-11e6-952b-039066890684.png)

**Comment by projectkk2glider** [comment]
@schwabe Thanks :+1:
