### ISSUE TITLE
Horus Special Functions

### ISSUE THREAD

**Issue by Plumbrr** [opentx/opentx#3503]
Timer delay does not seem to work in the special functions

A>X assigned to a L1 with timer delay switch. Time delay doesn't work. 
Also you can not select any other position of a three pos switch other than 1

**Comment by kilrah** [comment]
Don't understand what you're trying to set up, what do you mean by "timer delay"? Please give the actual values you put in and the results you get.

**Comment by projectkk2glider** [comment]
No response from @Plumbrr. Since the LS code is shared with the Taranis I guess it is just a user misunderstanding problem, therefore I am closing this. If issues is real, then please explain in more detail and reopen.
