### ISSUE TITLE
Backlight voltage

### ISSUE THREAD

**Issue by bbbenji** [opentx/opentx#3504]
Recently I replaced the blue led's in my Taranis Plus with green ones. Not paying attention and following a  guide written for the regular Taranis, I purchased smd led's which require slightly higher voltage which resulted in a dim backlight. Is it possible via FW to change the max V output to the LCD backlight? If so, please point me in the right direction. I will compile my own version of OpenTX with the changes.

**Comment by kilrah** [comment]
Is it possible via FW to change the max V output to the LCD backlight?

No. You might need to change the current limiting resistors.
