### ISSUE TITLE
[Telemetry simulator] Fuel quantity (ml) not implemented

### ISSUE THREAD

**Issue by raphaelcoeffic** [opentx/opentx#3505]
The fuel quantity sensor (in ml; id=0x0A10) does not seem to be implemented in the telemetry simulator. I have a patch ready for which I will make a pull request linked to this issue.

**Comment by bsongis** [comment]
That's nice!

**Comment by raphaelcoeffic** [comment]
By the way, I added this new value at the bottom end of the screen. Was it the right place, or should it be placed just bellow the other Fuel sensor? (thus shifting everything else one level down)

**Comment by projectkk2glider** [comment]
Done in #3506
