### ISSUE TITLE
Heli setup not properly backuped

### ISSUE THREAD

**Issue by blairfancy** [opentx/opentx#3510]
Hi,
I ve noticed that on companion 2.1.8 heli setup is not properly saved/restored especialy inversion on dir/ail/pitch.

Regards
Thierry

**Comment by projectkk2glider** [comment]
Please describe the issue in more detail, we are really illiterate about helis :wink:  

I tried setting all values in Heli tab, saving to eepe and the reopening the file. All values were there. Do you see a problem when transferring from/to radio?

**Comment by blairfancy** [comment]
Ok here are the step to reproduce issue:
-first setup model and in heli setup invert channel Pitch
-with companion load models from radio
--finally check heli setup in companion you can see that pitch channel is no more inverted (no check in the box)

hope it help...

**Comment by schwabe** [comment]
@blairfancy OpenTX multiple ways to invert a channels. In which screen did you invert the pitch channel? (Mixers/Outputs/Heli...etc)

It would also help if you can make a backup of your eeprom from the remote and attach the eepe file so we can load it ourselves in Companion

**Comment by blairfancy** [comment]
as explained invert channel in "Heli Setup" screen
ok i ll try to backup model with radio itself

**Comment by schwabe** [comment]
That screen has no invert option?! (I am also not a heli user)

![image](https://cloud.githubusercontent.com/assets/1038539/15440765/8f348ea2-1ed7-11e6-8565-4177938248c4.png)

**Comment by blairfancy** [comment]
In the radio there are 
![heli_setup](https://cloud.githubusercontent.com/assets/7937229/15440895/41bbe12e-1ed8-11e6-8713-ce2ee70a9d67.jpg)

[fbl100.txt](https://github.com/opentx/opentx/files/275359/fbl100.txt)

**Comment by griebd** [comment]
my guess is he is importing from an old version... this setup has changed!
there is a upgrade note saying about it!!! before we had the invert option, now we have weight! there is no automatic conversion though...
@blairfancy, is my guess correct? are you importing a eeprom from an old version of openTx in a newer one?

**Comment by blairfancy** [comment]
@griebd, no and bug can be reproduced with companion only (radio simulator). bug is only on model setup of companion on radio no issue.

**Comment by projectkk2glider** [comment]
I see now, the inversion parameter is present on platforms that don't support *virtual inputs* like 9X and 9XR, etc..

**Comment by schwabe** [comment]
Yes. I Taranis encodes the paramter in the weight, negative weight is inversion. When reading the eeprom for 9x we do not store the value in the SwashRingData (opentxeeprom.cpp function, class HeliField). Writing back that config should work. But that flag cannot not be modified via companion

**Comment by schwabe** [comment]
@projectkk2glider are you already coding a fix? Otherwise I would take this.
