### ISSUE TITLE
[Companion 2.2]  Windows-Nightly: Missing dll

### ISSUE THREAD

**Issue by dklueh79** [opentx/opentx#3525]
companion-windows-2.2.0N317.exe:
Missing Lib ( Win 7) api-ms-win-crt-runtime-l1-1-0.dll

**Comment by kilrah** [comment]
AFAIK this should not need to be distributed by companion.

See here about reinstalling VC++ 2015 redistributables:
http://blog.spreendigital.de/2015/09/01/how-to-fix-the-api-ms-win-crt-runtime-l1-1-0-dll-is-missing-error-for-delphi-10-seattle/

**Comment by projectkk2glider** [comment]
Did this issue emerge in 2.2 or (most likely) is also present in previous versions? If later, then we can close this.

**Comment by kilrah** [comment]
Only 2.2 since previous versions used the 2010 redist

**Comment by dklueh79** [comment]
Everything fine, could be closed
