### ISSUE TITLE
Missing units in telemetry for the quantity of energy

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3528]
Although almost all quantities are adopted in the OpenTX telemetry system, Energy is missing.
We have no Ws, Joule and/or Wh.
I haven't thought of which unit should be appropriate.

I thought of measuring the amount of energy produced by each cell.

http://www.rcgroups.com/forums/showpost.php?p=34845699&postcount=4045

**Comment by LapinFou** [comment]
It is also somehow linked to the tiket #2914

**Comment by fraternl** [comment]
@projectkk2glider   Hi Damjan.... I think this one also needs the label "EEprom change"
