### ISSUE TITLE
Horus GUI Theme design

### ISSUE THREAD

**Issue by JimMchugh** [opentx/opentx#3535]
Just loaded up OpenTX v2.2.0N317 on my beta Horus.

Fantastic!

One question: What is required to create your own theme design?

I'd like a very plain / stark / monochrome design...

**Comment by 3djc** [comment]
Please join https://gitter.im/opentx/OpenTX22 . I'm closing this as it is not an issue per say :)

**Comment by bsongis** [comment]
I started a TBS theme here:
https://github.com/opentx/opentx/blob/next/radio/sdcard/horus/THEMES/TBS/main.lua
And yes please use the gitter for that, we will try to help (and add more functions to the Lua interface if needed)

**Comment by dk7xe** [comment]
When i click the gitter link i get "404. This is not the chat you're looking for. Sorry. :(" any idea?
Just flashed my Horus with OTX and did the painful manual transfer of my models. ;)
but now i'm stuck at creation of own theme.
BTW: if there is an explanation available in a closed group on gitter. Why can't the solution be posted here as well? If you like i can volunteer but first the gitter access issue needs to be solved ;)

**Comment by 3djc** [comment]
We are not using gitter anymore, we moved to rocket.chat (https://opentx.rocket.chat/). And no, no instructions exist on theme creation
