### ISSUE TITLE
How do I get added to the OpenTX Horus Beta Tester

### ISSUE THREAD

**Issue by Joetrin** [opentx/opentx#3538]
I received my Horus Test TX, and would like to assist.  Oh, i can't seem to add a label to this to specify Horus.

I'm new to Github and frankly it's a bit confusing to me, so apologies potentially not posting in the correct area.

**Comment by projectkk2glider** [comment]
Check out  https://gitter.im/opentx/OpenTX22, introduce yourself and you will get help from other testers in no time.
