### ISSUE TITLE
HORUS - Mix weights default to GV1 rather than 100%

### ISSUE THREAD

**Issue by DaddyBigas** [opentx/opentx#3539]
HORUS
opentx-horus-2.2.0N317

After creating a new model and going to the mix tab, empty mixes have a default weight=GV1 rather than 100%.

**Comment by DaddyBigas** [comment]
But the question is should it be defaulting to GV1 rather than 100%?

**Comment by kilrah** [comment]
No, it was a bug we previously had on other platforms but the fix didn't get ported to Horus. When you created a mix with enter long instead of enter short the key event would get carried into the new page, and a long enter on the source field toggles GV mode.

**Comment by DaddyBigas** [comment]
Makes sense...thanks kilrah.
