### ISSUE TITLE
HORUS Multipos Switch not calibrating...

### ISSUE THREAD

**Issue by JimMchugh** [opentx/opentx#3542]
I have set the centre knob as a 6 way multipos switch in the hardware config page.

Whenever I do calibration, I cannot get any more than 1 - 4 positions.

Switch physically in Position 1 = Value 1
Switch physically in Position 2 = Value 1
Switch physically in Position 3 = Value 2(?)
Switch physically in Position 4 = Value 2(?)
Switch physically in Position 5 = Value 3(?)
Switch physically in Position 6 = Value 4

Thanks!

**Comment by 3djc** [comment]
Please do it very slowly, allowing a couple of seconds for each position, it will work :)
