### ISSUE TITLE
HORUS External RF module selection causes EMERGENCY MODE

### ISSUE THREAD

**Issue by JimMchugh** [opentx/opentx#3543]
On the radio section of a Model, if I select the "External RF" (default OFF) and start to scroll down the list, the OS will crash and go to "EMERGENCY MODE".

Every time without fail...

**Comment by kilrah** [comment]
Known, "XJT" mode is not implemented yet and thus selecting it causes a crash.

**Comment by JimMchugh** [comment]
@kilrah: I was hoping to use an external Spektrum DSM2 / DSMX module. Will that be an option?

**Comment by kilrah** [comment]
It will eventually, again there's still a lot of work to be done.
