### ISSUE TITLE
HORUS SD Card not appearing in Windows

### ISSUE THREAD

**Issue by JimMchugh** [opentx/opentx#3545]
With the radio ON, running latest OpenTX firmware, when I connect to a Windows computer (that works fine with Companion v2.2.0) no SD Card shows up in the drive list.

All drivers loaded. Put the SD Card directly into computer and all is fine.

If I connect USB with radio OFF, I get the STM32 Bootloader connected.

Am I missing something obvious?

**Comment by 3djc** [comment]
The bootloader does not work yet like a Taranis to allow you to access the sd through usb

**Comment by JimMchugh** [comment]
But my understanding is that with Horus switched ON, connecting the USB should show the SD Card as a drive.

The radio knows that it's connected via USB as it displays the USB icon in the top right corner...

**Comment by kilrah** [comment]
USB storage isn't implemented yet.

Please use the chat for simple questions instead of opening issues.

**Comment by JimMchugh** [comment]
@kilrah: Sorry! Where is the chat at?

**Comment by 3djc** [comment]
https://gitter.im/opentx/OpenTX22
