### ISSUE TITLE
OpenTX Companion 2.2.0N317

### ISSUE THREAD

**Issue by breakcore01** [opentx/opentx#3552]
I have a problem with the programm, when i start the programm come this error " Unable to check for updates"

Why is it?

**Comment by 3djc** [comment]
Please unselect : Automatic check for companion updates, in settings/settings/application settings

**Comment by breakcore01** [comment]
but then i can not download the new firmware for Horus

**Comment by 3djc** [comment]
yes yyou can, the firmware is another settings, this one is only for companion

**Comment by breakcore01** [comment]
how can i download the new firmware for opentx horus? have you a link?

**Comment by 3djc** [comment]
you need at the same place:
- use OpenTX nightly builds
- Automatic check for OpenTx firmware updates

**Comment by breakcore01** [comment]
yes i have make it, but how can i write the firmware in horus?
i have start the horus and then conect to the usb and then when i write the new firmware in horus comes this error , see the photo
![imag1454](https://cloud.githubusercontent.com/assets/19343290/15650241/68fae39c-2677-11e6-8375-1757caba1f7b.jpg)

**Comment by 3djc** [comment]
The drivers have for horus have not been installed on your pc
