### ISSUE TITLE
FRSKY telemetry for STD 9X buld options broken

### ISSUE THREAD

**Issue by aergid** [opentx/opentx#3559]
I have a standart 9x with external XJT module and telemetry-mod done and x4rsb as receiver. 
I have tried to build different versions of openTX, enabling FRSKY, FRSKY_SPORT together and separately from different tags and branches. In any combination there are a lot of broken code, e.g. missing fields in enums, undefined types, disabled conditional constants. Removing some code, mainly GPS, formats conversions, filtering sensors so that FW finaly compiles,  is of little help. I either get flashing 'NO DATA' on telemetry screen or zero values. At the same time, if I flash er9x-frsky, then at least RSSI levels are working. But I like openTx more :)
So, here is my question: Is there a 'right combination' for std 9x build to get FRSKY S.PORT telemetry and which values can it show?

**Comment by kilrah** [comment]
S.port telemetry support was never added for the 9x platform. 

https://github.com/opentx/opentx/issues/498
