### ISSUE TITLE
No !SF in Companion logical switch selection

### ISSUE THREAD

**Issue by timdonovanuk** [opentx/opentx#3563]
Someone forgot their alphabet, as you can select "not" values for every switch except F

<img width="270" alt="2016-06-03 13_17_31-2016-06-03 13_12_08-greenshot png - photos" src="https://cloud.githubusercontent.com/assets/8156439/15778384/d1df1f9a-298d-11e6-8be3-48c1112addd3.png">

**Comment by schwabe** [comment]
That might be indented since SF is not a switch but a toggle

**Comment by kilrah** [comment]
You forgot your logic - SF is 2-position, so !SFup == SFdown. Duplicates are unnecessary.

**Comment by tomkfly** [comment]
Methinks someone doesn't understand logic

**Comment by timdonovanuk** [comment]
Spent too long staring at 20 sticky logical switches states, apologies, I'm an idiot.
