### ISSUE TITLE
TGY 9XR PRO - Timer 3

### ISSUE THREAD

**Issue by JASSoft1** [opentx/opentx#3567]
Investigators "OpenTx 2.1. x" introduced for the "TGY 9XR PRO" very useful quantity "Timer 3" (Tmr3). In the "Companion (Simulator)" is the value of Tmr3 processed and displayed correctly.
For real 9XR PRO is Tmr3 broken - displays the value of the 83:47 hours, reset goes to 00:00, after a reset returns to 83:47. Verified on three TX with the same result (only the value of time is different).
Please authors delete in FW This error.
Sorry for the bad English.

**Comment by kilrah** [comment]
What firmware version??

**Comment by JASSoft1** [comment]
2.1.8
