### ISSUE TITLE
9X companion 2.0.19 :Gvar as subtrim in the Servos screen 

### ISSUE THREAD

**Issue by Roland38** [opentx/opentx#3580]
II think that it's not for the 9X radio (it doesnt work)
![servos2](https://cloud.githubusercontent.com/assets/19773517/15896201/89c0af66-2d8f-11e6-8c19-b326f19b78b8.JPG)

**Comment by projectkk2glider** [comment]
That checkbox should be visible only for Taranis and Horus.
