### ISSUE TITLE
Logical Switches: a>x etc.: x limited to le. 150 if a is the output of a lua script

### ISSUE THREAD

**Issue by pau33** [opentx/opentx#3581]
For me, this is an interesting behaviour. I tried to set up a logical switch, which is triggered, if the calculated distance from a LUA-Script output is larger then 250(m). But 150 is the biggest number I can fill in for x. With other parameters for a (for ex. SWR and others) higher values for x are possible.
Would it be possible to increase the x-values for lua-scripts to higher values as well?

Best Regards Paul

**Comment by projectkk2glider** [comment]
Similar problem on the radio, where the biggest value is 100. The limit could be much bigger.

**Comment by kilrah** [comment]
Just noticed something related now, in companion offset for telemtry sensor is limited to 300 for no good reason, radio allows much higher values.

**Comment by pointu** [comment]
We have the same problem with the GV, limited to 1024, so when u use for exemple Alt (vario altitude, it's à prec1 number) and do something like alt limitation (if Alt >GVx do something) u are limited to 102,4 m.
A work around is to do a calculated sensor to retrieve it in prec0 (m) and the limit is 1024.
