### ISSUE TITLE
Taranis x9d plus time format

### ISSUE THREAD

**Issue by BIGEMANN1** [opentx/opentx#3585]
I would like the option to display the time shown on the Taranis from the "24 hour" to the "12 hour" format . If this is possible it would be greatly appreciated !

**Comment by 3djc** [comment]
If we where to that, we could not display AM/PM without going throught  a major UI revamp, and LUA scripts would be affected too, so does it make sense to do ?

**Comment by schwabe** [comment]
Also 24h is universally understood at least in Europe. Even in UK where am/pm is still used, you will find a lot of times given in 24h.
