### ISSUE TITLE
Persistent not always persistent

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3595]
I'm using the persistent flag for consumption in the telemetry settings.
This works great, but sometimes, after charging the battery I want to check how the consumption relates to the amount I just charged.
When I turn on the radio this value is not displayed.

It will only display if I turn my receiver on.

I need to be quick then, because I have an SF that resets the consumption if it detects a full battery.

It would be nice if persistent values (or maybe all values?) continue to be displayed.

**Comment by projectkk2glider** [comment]
There is a workaround (I believe):  Telemetry model setup page will show persistent value even if telemetry is not being received.

**Comment by fraternl** [comment]
No, 
I was already looking there in the first place.

**Comment by bsongis** [comment]
@projectkk2glider do you take it?

**Comment by projectkk2glider** [comment]
ok

**Comment by bsongis** [comment]
Thanks!

**Comment by fraternl** [comment]
Works!!!
