### ISSUE TITLE
9xr radio thr and ail switch always armed

### ISSUE THREAD

**Issue by Goofieshot** [opentx/opentx#3598]
Ver 2.1.8 - Finally got this ver somewhat figured out except for these two switches. Had this issue in  a earlier ver and all i did is deselect the frsky build option to get back to business. This time I had no success even with frsky deselected. Do i have any other options? thanks for your help.

**Comment by Goofieshot** [comment]
when are the radio settings and build options written to the radio? with firmware write or model write?

**Comment by mhotar** [comment]
You should select your build options in companion, then re-download firmware file, and re-flash it.

**Comment by Goofieshot** [comment]
didn't work but thanks - set up the radio in options and re-downed firmware, installed it and still am in telemetry mode with switches set. This build option is getting loaded because in the radio all models show telemetry setting page (page 10).

**Comment by Goofieshot** [comment]
btw i did reload all models after the new firmware load

**Comment by Goofieshot** [comment]
i generated default firmware with no build and default splash and for some reason the radio did not take it because upon completion i had the same old splash screen. Companion did say that it completed it successfully. The only error i get in the beginning of write points to the usbasp

![error](https://cloud.githubusercontent.com/assets/19889607/16066123/bb7995d8-327e-11e6-9611-a0b67e11b61c.jpg)

but it seems to write models and models and model changes in fine - now I'm really confused

**Comment by Goofieshot** [comment]
in the end i loaded the same ver of companion on another win7 machine and it did everything fine - imagine that. Wrote the firmware and models without any issue - i apologize for the confusion, and would like to thank for the support. In conclusion at least I have acquired some knowledge on the companion soft.
