### ISSUE TITLE
[Bug][Companion]Incorrect tooltip comment for EU compilation option

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#3608]
Hi folks,

The comment is incorrect for the EU compilation option. With the latest EU-LBT version, the LR12 mode is available.
![tmp](https://cloud.githubusercontent.com/assets/1685030/16170382/09f3b156-3551-11e6-9728-9eb48a8df06e.png)

**Comment by bsongis** [comment]
+ faute d'orthographe au passage - utilisable**s**

**Comment by LapinFou** [comment]
Il manque aussi un espace entre "[...]utilisables légalement" et "en Europe [...]"
Ceci dit après correction, il n'y a plus de **s** à utilisable... :wink:
