### ISSUE TITLE
Request: add Function Script "background" function

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3609]
It would be nice if the Function Script would allow to have a background function as in a telemetry script, if the switch condition is not true.

This would also solve the problem of knowing if the function has been deactivated and activated again by moving the associated switch

I have a custom countdown function, that is activated on Adown. it needs to pause on A-, and needs to reset on Aup. 

the pause is already difficult to achieve, but possible with some time checks to see if the function has not been called and then not update the countdown counter

the reset is now impossible to implement without a background function, since the script is not active as soon as Adown is moved up !

It would also allow telemetry scripts to be run under a function script, and use the switch to toggle functions. (there is no display function available in function scripts, but for voice commands that is not neccesary)

**Comment by bsongis** [comment]
Yes agree

**Comment by projectkk2glider** [comment]
Isn't the Function script called only once each time when the LS changes from 0 to 1? That I think is the point of Functions script, to be executed exactly once on LS trigger.

You might be better of using a Mixer script, which runs continuously, You can monitor unlimited number of switches is such script and react accordingly. The script runs non-stop.

**Comment by bsongis** [comment]
the ```run()``` function is called when the function is active
the ```background()``` *could be* called when the function is in the list, but inactive

**Comment by projectkk2glider** [comment]
You are right about the `run()` and you proposal is good.
