### ISSUE TITLE
Improvement: allow negative timer start to allow "Count-in"

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3619]
On competition tasks, we ususally get a countdown until start of working or flying time.

Using LUA it is very easy to accomplish this with one model timer, or even a custom build timer.

Allowing a negative start time would allow to achieve the same without LUA coding, making it an accessable feature for all.

so, start time  -10 would make a countdown from 10 to zero, and then count up.
start times >0 would count down to zero, and then continue in negative.

Voice call's would work on negative side as on positive sides, so alert on -30, -20, -10, -9, -8, -7, .. ,0 , and doing minute calls if activated.

Pure functionally, the same could be achieved by activating minute calls on negative timer minute values as well, but it is not a nice implementation that way.

**Comment by projectkk2glider** [comment]
I think using Lua in this case is only viable solution. 

Here is an example that will not work with only *negative start*: 10 minute count down timer with a 10 seconds count-in. This would require another new parameter to be added to the timer - a count-in value.

In any case a solution in Lua would be much more powerful and flexible. The Lua solution itself is fairly simple:
* mixer script
* one parameter defines count-in duration in seconds
* other parameter is used to start count-in
* third parameter defines which timer is started
* after the count-in is finished a timer is started.
