### ISSUE TITLE
request: add LUA function to set custom scripts and adjust the values

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#3621]
It is usefull to have the custom scripts to be added using a lua function. 

Custom scripts have the nice feature that they store the input settings applied, so they are perfect to use as a "settings" functionality for other scripts or functions, sharing a global variable.

It would be nice if those "permanent" settings could be set or adjusted using LUA as well.

Important note to all users using LUA and thinking of using files to store settings: 

All LUA scripts should follow the design rule that they don't interfere with radio operation, but are allowed to change radio settings that are permanent (that is, stored in EEPROM as part of the EPEE). So they only act as a seperate way to change settings, to work in cooperation with the standard GUI, and/or present non crititcal settings, flight or telemetry info.

Using a file to save settings could be dangerous, since if there is an SDCard corruption or any other glitch, settings are not loaded. If the proper functioning of the EPEE relies on these (personal, for instance calibration or trim) settings, things could go badly wrong. A custom script is the way to do this safely, since settings are stored with the model when adjusted, and do not rely on SDCard access.

**Comment by projectkk2glider** [comment]
>Custom scripts have the nice feature that they store the input settings applied, so they are perfect to use as a "settings" functionality for other scripts or functions, sharing a global variable.

This to me looks like a bad practice.

>Using a file to save settings could be dangerous, since if there is an SDCard corruption or any other glitch, settings are not loaded.

If you have SD card problems, then your Lua script will also not run at all.
