### ISSUE TITLE
short circuit external receiver

### ISSUE THREAD

**Issue by free6k** [opentx/opentx#3625]
Hello, accidentally locked the power to the external receiver on x9e, when flash x4r receiver :( there was little smoke :( Taranis and internal receiver work is fine. But external receiver not working... What i can doing?

Thanks for all answers!

**Comment by 3djc** [comment]
I'm afraid this is not at all an OpenTX issue.

**Comment by free6k** [comment]
There are people here who understands this

**Comment by kilrah** [comment]
Please post this kind of questions on the forums, you'll have more chances there.
