### ISSUE TITLE
Taranis x9d+: Cannot bind in + polarity to Spektrum receiver.

### ISSUE THREAD

**Issue by zombiediesel** [opentx/opentx#3627]

**Comment by kilrah** [comment]
Doesn't mean a thing. What module?

**Comment by zombiediesel** [comment]
Spektrum dm9 trying to use ar7010 receiver. The thing is, my friend has the
stock taranis firmware on his and it works. I don't want to downgrade
though, because I have frsky telemetry setup on several other models.
On Jun 24, 2016 4:22 PM, "Andre Bernet" <notifications@github.com> wrote:

Doesn't mean a thing. What module?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/opentx/opentx/issues/3627#issuecomment-228465189>, or mute
the thread
<https://github.com/notifications/unsubscribe/ATM2oiNohPPavU1gexoRtRMOYt2vQ34Eks5qPEqZgaJpZM4I-G_L>
.

**Comment by schwabe** [comment]
What is your version of OpenTX and what version does your friend use? Do you use the same settings for the ppm output as your friend?

**Comment by jtaylor2** [comment]
Does it work with - polarity?  If so use minus.  There was a change to the ppm output polarity in version 2.0.16.  Below is from the release notes:
 
Version 2.0.16 / 2015-05-03
[Taranis] 
Fixed reverse polarity on external PPM output. Users with external module in PPM mode should check and update PPM polarity setting.

**Comment by zombiediesel** [comment]
I'm using 2.1.8 and he never upgraded firmware from when he bought his a
couple years ago. Ppm settings are identical. His works, mine doesn't.

**Comment by zombiediesel** [comment]
The receiver will not work with - polarity. The manual specifically calls
for +

**Comment by jtaylor2** [comment]
Try these settings for 2.1.8.  I don't have one, but this is what has been reported to work.  Firmware below 2.0 16 needed + polarity.  And verify that this is an actual DM9 and not a hack module in a DM9 case.

External RF Module in the Model Setup menu:
PPM
CH1-8
22.5ms
400u (not the default 300)
- polarity

**Comment by zombiediesel** [comment]
That is what mine has been setup as all along. Does not work. Again, the
only difference between mine and my buddies is the polarity setting.

**Comment by schwabe** [comment]
Did you swap the modules to check if both modules show the same behaviour (your works in his, his does not work in yours?)

**Comment by zombiediesel** [comment]
Yes I did. The only variable I havent tested was to flash his radio to
current firmware, but he wouldnt let me do that. I have seen this issue
reported about previous versions of the firmware as well.

**Comment by kilrah** [comment]
As mentioned your discrepancy is that the polarity display has been changed form one "convention" to the other in 2.0.16, and whatever instructions you're reading might have been written before that or use what was used before.

Just use the polarity that works.

**Comment by zombiediesel** [comment]
The problem is, neither one do...
