### ISSUE TITLE
DSM protocol not working on 9Xr pro and nigthly build

### ISSUE THREAD

**Issue by blairfancy** [opentx/opentx#3628]
Hi,
I m not able to bind my DSM2 heli with 2.1.8N786 on 9xr pro radio
PPM signal is coming out PPM pin.
With 2.0.19 no issue bind every time.

**Comment by schwabe** [comment]
What module are you using?

**Comment by blairfancy** [comment]
I use module made as follow
http://openrcforums.com/wiki/index.php/9x_Full_Mod_DSM2/X

**Comment by schwabe** [comment]
Then you need to select the DSM2 protocol instead of PPM.

**Comment by blairfancy** [comment]
Sure I did it, module is working properly on 2.0.19. It is only a regression. I see signal on ppm pin

**Comment by blairfancy** [comment]
Signal scoped on pin ppm of module 

![img_25062016_151909](https://cloud.githubusercontent.com/assets/7937229/16361159/310b1e1a-3b86-11e6-89f1-b5c290c90e77.jpg)

**Comment by schwabe** [comment]
Sorry. Your first report sound like you were using ppm instead of dsm2 serial protocol.

**Comment by projectkk2glider** [comment]
That signal looks very strange, perhaps it has something to do with the **output type** setting not being visible in 2.1.8 (was fixed in 2479aebde54744463f94642c000d4cd1412b39e9 and will be available in 2.1.9).

**Comment by projectkk2glider** [comment]
Scratch that, I see that you are using nightly build. Have you tried changing *output type* setting?

**Comment by schwabe** [comment]
That looks the resolution of the osciloskope does not get the fast 100000 baud

**Comment by projectkk2glider** [comment]
I meant the three logical levels of the signal, where one would expect only two levels.

**Comment by blairfancy** [comment]
Same capture but with 2.0.19 version

![img_27062016_205254](https://cloud.githubusercontent.com/assets/7937229/16391924/a43345f6-3ca9-11e6-9bb9-a48fb2d8f64b.jpg)

**Comment by schwabe** [comment]
The second one looks like 3,3V logic level while the first one is 1,8V? Is the wrong logic level only a problem with dsm2 or also with ppm/ppx/etc?

**Comment by blairfancy** [comment]
As shown on peak bellow problem occurred only on DSM mode. PPM and XJT mode looks correct

![img_04072016_182936](https://cloud.githubusercontent.com/assets/7937229/16566519/878d9304-4215-11e6-94c5-52a32142f813.jpg)

**Comment by blairfancy** [comment]
Hi guys,
just to confirm that bug is still present on latest 2.1 branch. What can i do to help solving this issue?

**Comment by blairfancy** [comment]
is it possible to enable OUTPUT_TYPE_ROWS for dsm protocol for next release? This is probably root cause of issue. By default output type is set to push-pull output except for ppm module because g_model.moduleData[EXTERNAL_MODULE].ppmOutputType is set to 0 (open draint output type)

**Comment by blairfancy** [comment]
Ok bug is solved just need to comment line 176 to 180 on file radio/src/targets/sky9x.pulses_driver.cpp
[pulses_driver.cpp.zip](https://github.com/opentx/opentx/files/560719/pulses_driver.cpp.zip)

**Comment by bsongis** [comment]
@blairfancy would you open a pull request for those changes? Thanks!

**Comment by blairfancy** [comment]
Sorry i m noob on git if you explain process i can do it

**Comment by blairfancy** [comment]
hi i m trying to push my branch for opentx but i got access forbiden

**Comment by 3djc** [comment]
You need to go through a pull request

**Comment by projectkk2glider** [comment]
You must make your fork this repository, push the changes there in some branch, then you create a pull request against the master branch here. Se github help for more details.

**Comment by blairfancy** [comment]
ok thank Github issue workflow guide was not clear about that

**Comment by kilrah** [comment]
Translator's guide has more info about the process
https://github.com/opentx/opentx/wiki/Translators-Github-Guide

Note that it can be done much more "visibly" with a GUI git client .
