### ISSUE TITLE
 models.txt and radio.bin can be deleted from within the SD card brower

### ISSUE THREAD

**Issue by Robomort** [opentx/opentx#3633]
It is possible to delete /RADIO/radio.bin and /RADIO/models.txt when browsing the SD card from the radio. These files should be hidden / locked out from the user or have a warning message display when trying to delete them. Deleting models.txt will break model selection from the categories/model select page

**Comment by 3djc** [comment]
Well, your PC also allows you to delete key elements, most of the time without warning. And when you move the sdcard to a PC, same exists. Better to learn not to delete things unless you know what you do (because their might be exceptional cases when you want to be able to do that)

**Comment by Robomort** [comment]
I agree with the direct editing of the card on a PC is not something that can not be avoided but that would an extreme willful course of action and of course users will use Companion for everyday tasks when it become available. Editing these files on the radio should not be required and a simple incorrect menu selection could cause the model files to be de synced with the selection process.

**Comment by kilrah** [comment]
This is irrelevant since the model storage system is going to change completely anyway.
