### ISSUE TITLE
How can I join translation companion to simple chinese & tradtional Chinese?

### ISSUE THREAD

**Issue by Jasonsiu** [opentx/opentx#3639]
OpenTX Companion is a gerat open souce software for RC fans. But most of Chinese Rc fans can't read english. I hope OpenTX Companion support Chinese for this fans, How can I join translation OpenTX Companion to simple Chinese & tradtional Chinese?

**Comment by schwabe** [comment]
Translating companion is probably not that difficult since it uses the QT framework. But that still leaves you with an English only RC. (See also #3449)

**Comment by projectkk2glider** [comment]
Done in #4196.
