### ISSUE TITLE
Model audio files not played

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#3642]
Model audio files (for example flight mode on/off) are not played when the radio is powered up. If the model is reloaded, then the audio files start playing. The problem is only on the radio (X9E), `simu` works just fine.

This was not a problem on 2.1.

**Comment by bsongis** [comment]
Do you want I take it?

**Comment by projectkk2glider** [comment]
Not today. This will be easiest to solve with a hardware serial port for debug traces.

**Comment by bsongis** [comment]
Who wants to test in my branch?

**Comment by 3djc** [comment]
Just tested on my X9E : tt does works correctly as far as I can tell with your branch bsongis

**Comment by bsongis** [comment]
I think this one is fixed now. The model was loaded BEFORE the SD card was initialized
