### ISSUE TITLE
Companion with proxy

### ISSUE THREAD

**Issue by francisbesset** [opentx/opentx#3648]
Hello,
I use companion behind a proxy and it is impossible to download a firmware.
I have this error: **Unable to check for updates.**

I tried to add http_proxy and https_proxy (too with caps lock) in environment variables of Windows and same error.

I don't see a parameter interface to specify the proxy in Companion.

**Comment by kilrah** [comment]
What companion version?

You likely need to set the proxy in your system's network preferences (in Internet settings).

**Comment by francisbesset** [comment]
I use the v2.1.8.
The proxy server is set in Internet settings but a login and password are required for proxy.

**Comment by francisbesset** [comment]
Can you give me the urls called by Companion?
Maybe that proxy block theses urls.

**Comment by kilrah** [comment]
http://downloads-21.open-tx.org/firmware/stamp-opentx.txt
http://downloads-21.open-tx.org/companion/companion-windows.stamp

**Comment by francisbesset** [comment]
No problem to load theses urls from IE or an other browser.
