### ISSUE TITLE
[ Companion 2.2] Crashes on clicking Release-notes within popup "new firmware available"

### ISSUE THREAD

**Issue by dklueh79** [opentx/opentx#3650]
The whole companion crashes if clicking on rel-notes
Have to kill via Task-Manager

![2016-07-05 13_07_09-opentx companion 2 2 0n332 - radio_ frsky horus - profile_ horus](https://cloud.githubusercontent.com/assets/6195999/16582784/72e71eb0-42b1-11e6-85ac-6be6037d7190.png)

**Comment by kilrah** [comment]
It's not crashed, but the close button is disabled. You can close the window with alt-F4
