### ISSUE TITLE
AR9X board with T9X: vario setup [2]

### ISSUE THREAD

**Issue by vian31** [opentx/opentx#3651]
Opentx 2.8.1/T9X + AR9X board:
Still about the vario setup. The selected option "Neutral silent" on Companion does not do anything  once in the radio. I should enslave the Vario sound to a logical switch, like with 2.0 versions to not have sound at neutral values.
Thanks

[Edit] The selection is also not recorded when the setup is transferred to the radio AND then read again after into Companion.
![image](https://cloud.githubusercontent.com/assets/11540573/16610905/9a3b4ab0-435e-11e6-8d42-d320a991aa79.png)

Question: why there is not the same checkbox in the radio firmware ? Would make this setup easier.

**Comment by DaveKraft** [comment]
I can confirm that this issue persists in opentx2.2, I can't set "silent middle" for vario at my ar9x, I have the option in companion 2.2, but it can't be uploaded to the radio.

**Comment by 3djc** [comment]
Fixed in https://github.com/opentx/opentx/pull/4923, will be available in 2.2.1
