### ISSUE TITLE
x9e 2.1.8

### ISSUE THREAD

**Issue by olimis83** [opentx/opentx#3654]
swr and alarm antenna not working in this version

**Comment by tomkfly** [comment]
I replied to this on RC Groups.

**Comment by projectkk2glider** [comment]
It should work. What is the actual value of SWR when you expect to see the bad antenna warning? The warning will be triggered by SWR > 51.

The things preventing SWR alarm would be:
*  a specific version of XJT module which does not report valid SWR value
* a sub-standard SWR detection circuit on your particular XJT module that does not measure SWR accurately enough.

**Comment by tomkfly** [comment]
It could be he hasn't done the telemetry discovery.

**Comment by kilrah** [comment]
The "antenna defective" alert works independently of any telemetry display and discovery.

**Comment by tomkfly** [comment]
He said "in this version",  which made me think Thais is why he isn't getting the SWR display and he is not getting the warning because there isn't a problem.

**Comment by schwabe** [comment]
Has 2.1.8 already SWR removed as telemetry only shows it under Analog inputs, or is that next only?

**Comment by kilrah** [comment]
Next only.

> He said "in this version", which made me think Thais is why he isn't getting the SWR display and he is not getting the warning because there isn't a problem.

But as I said that can't be, the alarm is always active in all versions without the need for any user intervention, so if he doesn't get it there is a problem somewhere indeed.

He could help by saying whether the warning did ever work on his radio with another version or not.

**Comment by free6k** [comment]
i too have this problem, on 2.1.8 i don't have alarm "antenna".
Maybe problem in my antenna?

**Comment by projectkk2glider** [comment]
Most likely not an OpenTX issue.
