### ISSUE TITLE
DCR.  PRI-LOW.  Show/Hide menu tabs

### ISSUE THREAD

**Issue by StevenSeim** [opentx/opentx#3667]
Hello.  With permission, I would like to submit a low priority design change request. (DCR)

Within Companion, on opening a model, grant the option to show/hide the menu tabs through a settings icon (say, a gear) on the far right of the master frame.  The Setup tab would remain fixed.

Result:  

1. Users that do not fly helicopters will have the ability to hide that tab from view if wanted.
2. Users with models not complex can hide what they don't leverage from the application.
3. Streamlining and more rapid accessibility. 

Many thanks to you.
Steven

**Comment by 3djc** [comment]
Does this duplicate https://github.com/opentx/opentx/issues/3491 ?

**Comment by kilrah** [comment]
Yep

**Comment by StevenSeim** [comment]
It may.  

 

I had not seen 3941.  On reading, it sort of defines the symptoms and problem, but does not clearly define the solution.

 

If it makes the same point, please roll my issue into 3491 and close it out.

 

Many thanks for responding quickly.

 

 

Steven

 <https://www.facebook.com/steven.j.seim> Facebook

 <http://www.cybermodelle.com/> Web

**Comment by kilrah** [comment]
The solution is pretty clearly defined and would take care of your issue, but the current state of the discussion has objections to implementing that altogether.

**Comment by StevenSeim** [comment]
Understood.

 

It is a DCR, and low priority at that.  Usability is not adversely affected nor adversely hindered.

 

I would suggest though that it would be an aid for folks that do not leverage all the menu tabs, given the option to reveal/hide all tabs at will.

 

Having the ability to show only the menu tabs most commonly used might aid in porting the application to a mobile platform perhaps?

 

Again, many thanks for responding promptly.

 

 

Steven

 <https://www.facebook.com/steven.j.seim> Facebook

 <http://www.cybermodelle.com/> Web

**Comment by kilrah** [comment]
Please read the other issue for details about why that couild be a bad idea.
