### ISSUE TITLE
Assigning IDs for FrSky S.Port telemetry (ATTITUDE)

### ISSUE THREAD

**Issue by jelinj8** [opentx/opentx#3700]
Would it be possible to get "officially" assigned IDs for FrSky virtual sensors for attitude?
Their puprpose would be sending angles back to Taranis to build artificial horizon as a telemetry screen.
I have proposed to Cleanflight devs to optionally send angles in place of ACC values, but this would be cleaner solution, maybe usable for other FlightControllers devs.
(Cleanflight ticket: https://github.com/cleanflight/cleanflight/issues/2344 )

**Comment by projectkk2glider** [comment]
FrSky already reserved IDs from  0x5100 - 0x52FF for DIY sensors (see #4232). If you need anything else then you should contact FrSky directly.
