### ISSUE TITLE
Cannot Get Taranis To Appear as DFU Device With 2.2 Installed

### ISSUE THREAD

**Issue by davidbitton** [opentx/opentx#3702]
I have 2.2 firmware on my Taranis and when I attach it to my Mac, only the drive with the EEPROM and FIRMWARE files appear, no SD card files and also Companion says no DFU found. Any ideas?

**Comment by kilrah** [comment]
dfu is only used for flashing with the radio powered off. Please use forums or chat for matters not related to development .

**Comment by davidbitton** [comment]
Just a quick follow-up. The radio isn't reading the SD card however the SD card mounts fine on the laptop
