### ISSUE TITLE
[Companion 2.1.8N836 Simulator][OpenTx 2.1.8N836] Inputs->Edit->Stick side->NEG, Bug?

### ISSUE THREAD

**Issue by 483917** [opentx/opentx#3703]
Windows 10 pro swedish
Companion 2.1.8N836
Taranis B, Firmware: 
"opentx-taranis-haptic-timer3-lua-mixersmon-sqt5font-en-2.1.8N836.bin"

In ModelEdit->Inputs->Edit->Stick side->NEG, do not behave like StickSide->POS does
Open my demo file: "Neg-switch-bug.eepe/.Zip" 
[Neg-Switch-bug.zip](https://github.com/opentx/opentx/files/422322/Neg-Switch-bug.zip)
 and start Companion Simulator,
in sim-outputs look at Channel 6 = "StickSide POS" , And Channel 7 = "StickSide NEG"
and move switch SA-up , SA-mid , SA-down

Channel 5 is StickSide ALL for referens only, goes from -100 ,0 ,100 as it should
Channel 6 moves from 0 to 100 as it should
Channel 7 do not move from 0 to -100 as it should ?? it dont move at all

This only happens when a "Switch is assigned as Source"
Tested on Companion-sim and on Taranis B ,same behavior

If this is intended behavior ?,then feel free to close this issue
But feels confusing.

**Comment by 3djc** [comment]
Well there might be a logic flaw in what you are trying to achieve. Since you use a switch, it can have only 3 values, and in your setup, you kinda assume 0 will be both LEFT and RIGHT

**Comment by schwabe** [comment]
I looked at the setup. The bug narrows down to SA with stick negative is a constant -100 while for positive it is 0 or 100. 

My bet is that the stick side condition was never meant for switches and somewhere a < 0, <=0 ... condition lurks that is true for pos but not for negative. While stick side is a strange thing for switches, it should be consistant or removed.

**Comment by 483917** [comment]
Yes i think it should be consistant, StickSide POS 0 to 100 and StickSide NEG -100 to 0
But you decide

**Comment by kilrah** [comment]
0 is considered positive, so when your switch goes from -100 to 0 the value is never updated.

<= 0 would make most sense but there's likely a reason for it to be that way, needs careful investigation.

**Comment by schwabe** [comment]
What I noticed is that the preview (the curve graph) actually shows values of -100 and 0.
