### ISSUE TITLE
Companion 2.2.0N347_amd64.deb

### ISSUE THREAD

**Issue by dwheeld** [opentx/opentx#3704]
[Companion 2.2 Downloaded companion-linux-2.2.0N347_amd64.deb nightly and also latest next compiled on Linux Ubuntu 16.04 LTS.]  [May be related to #3691]

Steps to reproduce:
1. Run Companion 2.2 - Radio type Taranis
2. Attempt to open simulator window either from Model List screen or Edit Model screen
3. Message box pops up with message:
                 Simulator for this firmware is not yet available

**Comment by kilrah** [comment]
The 2.2 linux nightlies do not come with any simulators yet. Might want to build yourself.

**Comment by bsongis** [comment]
I reopen the issue as the simulators *should* be embedded in the package!
