### ISSUE TITLE
Companion Telemetry "Multiplier" Field

### ISSUE THREAD

**Issue by rmcclurg** [opentx/opentx#3711]
An RCGroups member asked me to report this issue. 

There is a problem with the OpenTX 2.1.8 Companion Telemetry "Multiplier" Field. 

This field can be set to a value of up to 30,000 on the radio, but any value above 300 that is set into it is lost when the model is stored back into the radio after editing any model with the companion software. If the field is set to a value greater than 300, the field gets reset to 300. That wipes out the setting that you have, and your actual setting has to be re-entered again on the radio.

**Comment by bsongis** [comment]
Fixed by https://github.com/opentx/opentx/commit/76ce186bd4a9e42ee8e336ae7ad601bbda6011c1
Already available in 2.2.2 nightlies
