### ISSUE TITLE
   model.setLogicalSwitch in LUA make an Error

### ISSUE THREAD

**Issue by StefanKie** [opentx/opentx#3719]
Hello,
My Hardware is Taranis and SW 2.1.8
I made a savety Switch for THR 
this LUA Line shows an Error at the "and" function 

   model.setLogicalSwitch(30, {func=4,v1=1,v2=-99, and=24})

**Comment by projectkk2glider** [comment]
Looks like `and` is treated as Lua reserved keyword - use following syntax:
```
model.setLogicalSwitch(30, {func=4,v1=1,v2=-99, ["and"]=24})
```
