### ISSUE TITLE
Companion V2.18N846  F4, RS not working,  LS wrong Channel reaction at Simulator

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#3721]
Companion V2.18N846  Profil X9E
Hardware setting F1,F2,F3,F4 as Poti,  RS, LS as Slider
Set to simple source at mixers Ch6 to Ch11

Start Simulator, Test reaction
F1=Ch8, F2=Ch9=, F3=C10 works fine, ok and at the right Ch
F4=Ch12, RS=Ch7, no reaction 
LS=Ch6  no reaction at Ch6, but reaction at Ch11

Pictures added
![2016-08-25_183230](https://cloud.githubusercontent.com/assets/6217896/17977784/589cada8-6af3-11e6-82c5-5c423be81241.jpg)
![2016-08-24_183949](https://cloud.githubusercontent.com/assets/6217896/17977802/69cd55f0-6af3-11e6-903a-14733a7a2e9f.jpg)
![2016-08-25_184351](https://cloud.githubusercontent.com/assets/6217896/17978077/b873fad2-6af4-11e6-8107-abde84271505.jpg)

**Comment by kilrah** [comment]
Duplicate of #2377
