### ISSUE TITLE
Companion V2.18N846  F4, RS not working,  LS wrong Channel reaction at Simulator

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#3722]
Transmitter Profil X9E
Hardware setting  F1,F2,F3,F4 as Potis  LS, RS as Sliders
source setting for test at mixer
LS=Ch6, RS= Ch7, F1=Ch8, F2=C9, F3=Ch10, F4=Ch11
Stimulator to Test
F1=Ch8, F2=Ch9,  F3=Ch10  works correct, ok
F4= Ch11,  RS= Ch7 no reaction
LS=CH6 no reaction, but wrong movement at C11 insteed

![2016-08-24_183949](https://cloud.githubusercontent.com/assets/6217896/17981769/56d28fa8-6b05-11e6-8ad5-383f705fb05b.jpg)
![2016-08-25_183230](https://cloud.githubusercontent.com/assets/6217896/17981782/611a1bc0-6b05-11e6-8c3a-ff3588219b9f.jpg)
![2016-08-25_184351](https://cloud.githubusercontent.com/assets/6217896/17981797/713e85ea-6b05-11e6-8efb-244915776fee.jpg)

**Comment by kilrah** [comment]
Please stop opening these. The simulator does not support the X9E at this point and all aspects of that are considered on #2377.

**Comment by hrenz** [comment]
ok, sorry was surrpriced that same things go, others not 

sorr
