### ISSUE TITLE
Horus telemetry - Consumption reading incorrectly.

### ISSUE THREAD

**Issue by HorusChris** [opentx/opentx#3723]
Horus. OpenTx 2.2.ON350.
Using a FCS-150A Current sensor with X8R receiver.

Current readings match my Wattmeter within 1%.
Consumption readings however read at about 1/4 of the wattmeter reading.
This is then confirmed by recharging my battery.

So When Horus reads 20A. Wattmeter reads 20A.
When Horus shows consumption of 700mAh. Wattmeter shows just under 3000mAh
Recharging the lipo puts back Just over 3000mAh.

**Comment by bsongis** [comment]
Strange I use myself the consumption with the Taranis and it is right.

**Comment by HorusChris** [comment]
Yes It's right on my Taranis too.

**Comment by kilrah** [comment]
> Yes It's right on my Taranis too.

With 2.2?

**Comment by HorusChris** [comment]
No my Taranis is 2.1.0.

I'll try to get a telemetry log from Horus tomorrow. Current and Consumptione were not logging before.

**Comment by bsongis** [comment]
Yes, excellent idea

**Comment by crazynight78** [comment]
I have a similar problem with a frsky fcs-40a using 2.1.8, flight was over 50% out second was more like 25% seems to not display very low amp usage. I was flying a bixler with a lot of low throttle the first flight the second was more powered.

**Comment by bsongis** [comment]
@crazynight78 Horus ? Taranis ?

**Comment by bsongis** [comment]
I don't see any obvious issue in the code, I will wait for your logs

**Comment by kilrah** [comment]
I've just set up a little test bench, need to charge a battery and I can run a test

**Comment by bsongis** [comment]
:+1:

**Comment by HorusChris** [comment]
I may be some time with my results. Today is planned for family thing, not modelling. I got up to do this test and found no bind between Horus and my model. I've assumed this has been caused by flashing to FrTx and then back to OpenTx. During the flash to FrTx it did an IXJT upgrade.

**Comment by HorusChris** [comment]
[Wots_Wot-2016-09-27.xlsx](https://github.com/opentx/opentx/files/440572/Wots_Wot-2016-09-27.xlsx)

**Comment by HorusChris** [comment]
OK - seems that choosing the wrong FrTx file will switch the IXJT from FCC to LBT. So, having flashed to FrTx and back to fix that:

This mornings test is posted above. 
That shows a 1:20 run being held at around 20A with throttle (badly). 
Test stopped when Wattmeter was reading 400mAh.

**Comment by HorusChris** [comment]
During the 20A period of my test, consumption should be increasing at about 5.55 mAh each second.

20*1000 = 20000mA and 20000/3600 = 5.55 mA/S

Log results show an increase of either 1 or 2 mA/s

**Comment by kilrah** [comment]
I have just run a test discharging about 530mAh from a pack with 2 current sensors and 2 receivers, one bound to my X9E on 2.1.8 and the other to my Horus on current next branch, both matched, and my charger put about 540mAh back in.

So I'd presume you've got something configured wrong in your calculated sensor.

![clipboard02](https://cloud.githubusercontent.com/assets/6065069/18026817/6b59067a-6c52-11e6-8643-9772fb17df01.jpg)

**Comment by HorusChris** [comment]
OK thanks, that's good news. Now to work out what.
I assume my Current sensor must be set up correctly?

What is there that I can get wrong in my calculated one?
Set up like this:

Name = Cons
Type = Calculated
Formula = Consumpt
Sensor = Curr
Auto offset = blank
Positive = blank
Filter = checked
Persistent = blank
Logs = checked

**Comment by kilrah** [comment]
Don't enable Filter.

**Comment by HorusChris** [comment]
I'll give that a go when family allows, later today.
