### ISSUE TITLE
OpenTX 2.2 nightlies

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3730]
I think I will be receiving one of the first production Horuses this week.
It will probably be loaded with the Frsky-OS.

I would like to load it with OpenTX and do some testing and hopefully I can soon give feedback.
Can a nightly system be setup like there is on currently for the 2.1.x branch?

**Comment by kilrah** [comment]
It's been there for half a year... http://www.open-tx.org/links

It's not "nightly", we run a build when we feel is needed.

**Comment by kilrah** [comment]
Note that the production version of the Horus will not work until the next build is made. You might want to join the chat at http://opentx.rocket.chat for news.
