### ISSUE TITLE
Companion 2.2.0N350, when I set it to language nl (Dutch) I get a compilation error

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3731]
Companion 2.2.0N350, when I set it to language nl (Dutch) I get a compilation error when "downloading" the firmware.

In the past I did the translation for 2.1.x
I may be of help providing the necessary files.

**Comment by kilrah** [comment]
It was disabled for some reason, next version should have it enabled again.

Translation file is here: https://github.com/opentx/opentx/blob/next/radio/src/translations/nl.h.txt
It looks pretty OK, but might be a bit outdated vs the English one: https://github.com/opentx/opentx/blob/next/radio/src/translations/en.h.txt

**Comment by fraternl** [comment]
I will work on it...
Will wait with uploading until I tested it on the Horus.....
