### ISSUE TITLE
Sensor Lost. Horus Open TX 2.2.0N350

### ISSUE THREAD

**Issue by KevinFairgrieve** [opentx/opentx#3733]
Beta Horus running Open TX 2.2.0N350.
FrSky X6R RX
FrSky GPS V2 Sensor

Flying with a rock solid link, but occasionally getting a "sensor lost" vocal alert.

Worked fine in this configuration using a Taranis running Open TX 2.1.8

I did video the flight on a hat cam and as soon as it is loaded to YouTube I will add the link so you can hear.

**Comment by 3djc** [comment]
Was it not telemetry lost ? (or are you running another language than english ?)

**Comment by KevinFairgrieve** [comment]
No. Definitely "sensor lost".

English language used.

**Comment by kilrah** [comment]
What sensors are connected?

**Comment by KevinFairgrieve** [comment]
FrSky GPS V2 only

**Comment by KevinFairgrieve** [comment]
I will check the connections and report back. Strange that it has worked on my Taranis for the last 18 months without issue.

**Comment by kilrah** [comment]
That's because there was no such warning feature on 2.1.

**Comment by KevinFairgrieve** [comment]
From about 1min 20sec in.

https://www.youtube.com/watch?v=Xse8yoLXgiw&feature=youtu.be

**Comment by kilrah** [comment]
Got any logs?

**Comment by bsongis** [comment]
It would be nice to see in the logs what is the refresh rate

**Comment by bsongis** [comment]
And perhaps 15s is not optimized for GPS ...

**Comment by KevinFairgrieve** [comment]
Sorry no logs.

Forgot to activate them during the days flights.

**Comment by kilrah** [comment]
From the blinking '*' on the telemetry page refresh rate is 3Hz for speed and 1Hz for position/altitude.

I've tried simulating loss of GPS signal and that doesn't trigger the "sensor lost" alarm, info comes in regardless of validity. I can only simulate it by physically disconnecting the GPS, so that connection would still be the main suspect. Would be good to look at the telemetry setup page while checking the connection.

**Comment by KevinFairgrieve** [comment]
Not sure this is going to help.

https://youtu.be/txKp8QBLpOU

Even changed to a different GPS Sensor.

When wiggling wires I saw no change to the telemetry settings.

May need to turn your volume up.

**Comment by kilrah** [comment]
Can barely see a thing on the flickering screen... you should see a sensor go red when it happens. 
It looks like you might have 2 "GPS" sensors, that doesn't seem normal. Delete one (or both , and rediscover).

**Comment by KevinFairgrieve** [comment]
The "*" do not stop on any sensor for any length of time.

Rediscovered, sometimes get 1 GPS others 2.

Hopefully better shorter video.

https://youtu.be/94ZNjoCenpg

**Comment by projectkk2glider** [comment]
Looks like **Date** sensor gets no updates.

**Comment by kilrah** [comment]
GPS sensor handling is just completely broken right now. Will be fixed after next test build.

**Comment by KevinFairgrieve** [comment]
Thank you I shall wait the next rellease. Who knows I may even have a production radio......

**Comment by bsongis** [comment]
Fixed

**Comment by rondofpv** [comment]
Having the same issue after upgrading to the latest 2.2
