### ISSUE TITLE
en.h.txt for 2.2

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3737]
I'm busy doing the translation from en.h.txt so I can produce a better nl.h.txt
I noticed these 2 lines in en.h.txt....

Can you have a look at them?

`#define TR_LSW_DESCRIPTIONS    { "Comparison type or function", "First variable", "Second variable or constant", "Second variable or constant", "Additional condition for line to be enabled", "Minimum ON duration of the logical switch", "Minimum TRUE duration for the switch to become ON" }`

The "Second variable or constant" is stated twice

In this line the month February is not translated from French

`#define TR_MONTHS              { "Jan", "Fev", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }`

**Comment by kilrah** [comment]
Month fixed. The other is normal, there is a special case where there are 2 navigation positions for the same column and that was the easiest way to go about it.
