### ISSUE TITLE
nl.h.txt

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3738]
Here's the updated translation file I made:

http://hmvc.eu/nl.h.22.txt

@projectkk2glider
Can you check the file I made?
In the past you needed to change something. I still don't know why.

**Comment by schwabe** [comment]
I took a quick look and it looks good. 

Some issues I noticed during a quick simu test:

(These I are just things I noticed. Not sure if they are intendend or not:)

String too long:

![image](https://cloud.githubusercontent.com/assets/1038539/18087308/d5926a36-6eb4-11e6-9516-18647aeaa63f.png)

heli screen not translated: 

![image](https://cloud.githubusercontent.com/assets/1038539/18087340/f4862a36-6eb4-11e6-9564-b8acb64137f2.png)

Dutch/English mix:

![image](https://cloud.githubusercontent.com/assets/1038539/18087345/07702c8c-6eb5-11e6-9fd0-2fd538b9fcd6.png)

Not all special functions are translated:

![image](https://cloud.githubusercontent.com/assets/1038539/18087401/6170f8ec-6eb5-11e6-8826-8d1b942276a7.png)

Translation missing: 

![image](https://cloud.githubusercontent.com/assets/1038539/18087453/9788fbdc-6eb5-11e6-97a1-a1d0cdd6e3bb.png)

I also added the modified file to the commit 75b74da2bd651414ca73bd6581ae1dd010f6dca6

**Comment by fraternl** [comment]
Hi Schwabe,

Some of it is intended, but I agree it does look messy.
Our languages (Dutch, German) are very descriptive and take more words and letters than English.

The Dutch are mixing English words and expressions into their language much longer than Germans and therefore I chose to keep many things in English.

I did in fact a comparison with the German de.h.txt to check what was done there.

I will make some more corrections to the file...
Thanks

**Comment by schwabe** [comment]
@fraternl No problem, I was just wondering.

The German translations is also a bit special since it translates almost everything and even changes the headings (e.g. from External Module to ======== Externes Modul ======). I don't use that one :)

**Comment by fraternl** [comment]
The things you see are not in the nl.h.txt 
somehow the simulator uses something else or you are using an old copy....

I just wanted to correct some things, but these don't correspond with the screens you posted.

**Comment by kilrah** [comment]
Merged without checking much, no time... but that way you can have a look once the next build is out.
