### ISSUE TITLE
Companion 2.2.0N350 installs by default as Companion 2.2, version 2.20N351 has my 2.1 overwritten

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3748]
A few days ago I installed Companion 2.2.0N350 and it installed as Companion 2.2

Today I installed Companion 2.2.0N351 and it installs in the folder for Companion 2.1 and has now overwritten my 2.1 installation

**Comment by fraternl** [comment]
It might be that I paid more intention the previous time....

**Comment by kilrah** [comment]
That's listed in the warnings on the download page.
