### ISSUE TITLE
More room in OpenTX 2.2 for the Dutch word for "warning"

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3755]
When the radio starts it can give several warnings.
The Dutch word for "warning" is "Waarschuwing".
I can't really think of another word in this context.

The last letter (G) is not able to fit on the screen.
Can some extra room be made for this word???

**Comment by bsongis** [comment]
And how would you see that?
I propose to finish the word directly on the case :)

**Comment by mrpraline** [comment]
What is you use "Pas op!" instead of "Waarschuwing" ?

**Comment by fraternl** [comment]
@bsongis funny man....
The font could be slightly smaller and it could move some pixels to the left...

But I didn't think of "Pas op!"
I like it even more.....
Thanks @mrpraline

**Comment by fraternl** [comment]
A new file can be downloaden here:

http://hmvc.eu/nl.h.22.txt

**Comment by fraternl** [comment]
On second thought "Pas op!" is not correct...
In Dutch you can say "Schakelaar Waarschuwing" like "Switch Warning" but "Schakelaar Pas op!" sounds awkward.  "Pas op! Schakelaar" is alright, but this would mean that it would change for other languages as well....

Please advice???
What changes are you willing to do?

**Comment by kilrah** [comment]
Can't you just abbreviate it? We have to do it commonly in most other languages for some things, not a big issue...

**Comment by lshems** [comment]
Why not use 'melding', as it actually isnt a warning, just a notification.

**Comment by fraternl** [comment]
@kilrah  an abbreviaton for the word "warning" defeats its purpose and is very ugly. I don't want be the one to ruin @mhotar 's  work.
@lshems Given all the options I have it's the best way out I think. I will change it to that.

**Comment by mhotar** [comment]
I do not use "Warning" word at all, I think the image says it already. So you have two lines to describe the problem. In Cz i have
"THROTTLE
CHECK
Throttle stick is not at zero"

**Comment by fraternl** [comment]
en.h.txt
#define TR_WARNING             "WARNING"
#define TR_MIXWARNING          "Warning"

nl.h.txt
#define TR_WARNING             "MELDING"
#define TR_MIXWARNING          "Melding"

The #TR_WARNING is used together with another word on the opening screen of the model
There is insufficient room to place "WAARSCHUWING" there, the counterpart of "WARNING"


#TR_EEPROMWARN              "EEPROM"
#TR_STORAGE_WARNING    "STORAGE"
#TR_THROTTLEWARN          "THROTTLE"
#TR_SWITCHWARN              TR("SWITCH", "CONTROL")

SWITCH
WARNING

THROTTLE
WARNING

But it's OK now.... I will use the word "MELDING"
