### ISSUE TITLE
Request: Music folder

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3760]
Can the function BGMusic also mount the folder /Music if it exists?
This way one can keep separate folders for bigger sound files of that type and they don't clutter the ones that show up on "Play Track".

**Comment by RCdiy** [comment]
Working on a list of changes for 2.2, was this implemented? I created a MUSIC folder with one file but it was not picked. MAC companion RC10.

**Comment by kilrah** [comment]
No, he jsut closed his requests.
If you don't see a commit or reference it's most likely not been addressed.
