### ISSUE TITLE
Taranis Plus - OpenTX 2.2 - Crossfire module not working in CRSF mode

### ISSUE THREAD

**Issue by lichtl** [opentx/opentx#3762]
Using Open-TX 2.2.0N354 (lua-mixersmon-multimode-ppmus-en) the Cross-fire module report "No Signal" when CRSF mode is selected. Downgrading on 2.1.8N857 it is working again an reporting "Digital" signal on.

**Comment by kilrah** [comment]
The protocol for Crossfire has changed, and will need an update on the XF module too.
