### ISSUE TITLE
SD card file rename under Horus 2.2.ON.356

### ISSUE THREAD

**Issue by Scott-Page** [opentx/opentx#3763]
When using OpenTX-Horus-2.2.ON356   
This is the procedure:
From main screen:
 - Press SYS to get into Radio Setup 
 - Press PgDn once to get to SD-HC Card
 - Wheel down to [SOUNDS] Directory
 - Wheel down to the directory you want to try to rename a sound.
 - Wheel down or up to the sound to rename
 - Long press the rotary encoder to get menu with four options - Play - Copy - Rename - Delete
 - Wheel down to Rename   

File name will select - however not able to rename.  Asked several other Horus users to confirm this - and got three confirmations.

**Comment by kilrah** [comment]
It's in the misc issues list

https://github.com/opentx/opentx/issues/3393
