### ISSUE TITLE
Timer 3 Edit When using OpenTX-Horus-2.2.ON356

### ISSUE THREAD

**Issue by Scott-Page** [opentx/opentx#3764]
In When using OpenTX-Horus-2.2.ON356 

Can't find Timer3 editing lines in model setup.  Timer1 and Timer2 are fine.

 Maybe missing, maybe I'm blind.

**Comment by bsongis** [comment]
Did you select the TIMER3 option in Companion?

**Comment by 3djc** [comment]
Currently, timer3 cannot be selected in companion, actual bug

**Comment by 3djc** [comment]
We have now defaulted all ARM radio to have timer3 by default, wich will solve this in next nightly.
