### ISSUE TITLE
Prevent (sometimes) the execution of LUA-script from SD-Card manager

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3766]
The SD-Card manager can execute LUA-scripts.
When I was playing with it trying to discover the new features of OpenTX 2.2 I was able to execute a widget LUA-script after which the radio went in some loop that I only was able to stop by turning off the radio. Maybe something else works too.....

Maybe this feature (of executing a LUA-script) should be disabled on certain folders or only enabled on some folders...

**Comment by bsongis** [comment]
Which script? There is a check to write at the beginning of the script to exit gracefully

**Comment by projectkk2glider** [comment]
@fraternl please upload the script that freezes the radio. This should not happen.

**Comment by kilrah** [comment]
Both lua widgets we distribute in the SD card image do it. It doesn't actually freeze the radio, but corrupts the display until reboot.

**Comment by bsongis** [comment]
OK I will take care of this

**Comment by fraternl** [comment]
Sorry for not reading this before.
I did make several model images in photoshop for the community
