### ISSUE TITLE
Open TX Horus 2.2 ON352  GVAR setting delay when set by pot, slider or trim

### ISSUE THREAD

**Issue by clivemartin** [opentx/opentx#3770]
When using a pot slider or trim to set a GVAR there is a delay from setting control (pot, slider, trim) to GVAR responding. Noticeable both in real time (model servo response) and in channel monitor.

**Comment by kilrah** [comment]
Can confirm, the Adjust GVAR SF seems to only execute once a second when continually active.

**Comment by clivemartin** [comment]
Many thanks for quick response

**Comment by projectkk2glider** [comment]
Last commit breaks the play sound: if repeat 1x is selected, the sound repeats forever.
