### ISSUE TITLE
Open TX Horus 2.2 ON352 On Input setting dialogue box, trim assignment missing.

### ISSUE THREAD

**Issue by clivemartin** [opentx/opentx#3773]
Input dialogue box, ability to assign any trim lever/switch to an input is most useful (cross trims for one) this function is missing in this version of open tx.

**Comment by kilrah** [comment]
It's a display scroll issue, it's there and the cursor goes on it but it ends up outside of the screen. Surprising nobody reported yet.

**Comment by bsongis** [comment]
Fixed by https://github.com/opentx/opentx/commit/3156dd304000c2a2392746295bffc0afe0bc177e
