### ISSUE TITLE
Open TX Horus 2.2 ON352 - Model notes not shown when switching models

### ISSUE THREAD

**Issue by clivemartin** [opentx/opentx#3777]
When a new model selection is made from model select menu and activated, the 'text notes' are not shown on screen, however notes can be selected from long press on enter key for that newly selected model.  When transmitter is powered 'on' then notes are displayed for the last model selected.

**Comment by clivemartin** [comment]
To be clear, it is the 'display checklist' (user generated text file) that is not displayed when a new model is selected from the model select menu. However with a model selected and the transmitter is powered OFF and then ON then the 'display checklist' is shown as first screen exactly the same as Taranis.

**Comment by 3djc** [comment]
Fixed in next nightly
