### ISSUE TITLE
OpenTX 2.2.0N356 Horus: Only four lua widgets supported

### ISSUE THREAD

**Issue by Noircogi** [opentx/opentx#3781]
This limit seems very low.
I believe this is due to the following definition in widget.h
#define MAX_REGISTERED_WIDGETS 10
There are 6 built-in widgets, so that only leaves 4 for lua and two of those are included in the base.
The fifth lua widget will not show up on the radio, but works in the simulator.

**Comment by kilrah** [comment]
Fixed for next build
