### ISSUE TITLE
Patched nl.h.txt

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3782]
I made a few new corrections to nl.h.txt for OpenTX 2.2

http://hmvc.eu/nl.h.22.txt

**Comment by kilrah** [comment]
This file reverts several changes that have been introduced recently.

Would be nice if you could actually use the source control tools to take care of those things...

**Comment by fraternl** [comment]
Hi Kilrah,

Sorry about that. I will take better care in the future.
Please merge this
http://hmvc.eu/nl.h.22.txt

**Comment by projectkk2glider** [comment]
Looks OK, I will merge it...
