### ISSUE TITLE
Weightfactor of mixing effecting trim

### ISSUE THREAD

**Issue by magmeinenseat** [opentx/opentx#3794]
When I am switching between 2 Flightmodes differnt lines in mixchart are active with differnt weightfactors. The confunsing thing for me is, that by toggling between the modes the elevator is hopping a few millimeters. I investigated this issue and found the connection to the trim of elevator. If trim is centered switching the modes has no influence, but teh bigger the trim is, the bigger the flipping on elevator is.
Maybe I missunderstood the strategie and way of programming models, but it seems to be an issue to be investigated.
Thanks and best regrads, 
Joerg

**Comment by kilrah** [comment]
That is perfectly normal, you'd typically implement your rates in INPUTS.
