### ISSUE TITLE
Logical switch option to Global, (6 position + 2-3pos = 24 songs for background all aircraft)

### ISSUE THREAD

**Issue by smartbird34** [opentx/opentx#3798]
Logical switch option to Global, (6 position + 2-3pos = 24 songs for background all aircraft).  This is what I would like the six songs on the position switch in global is getting repetitious.  I would like to have a larger library at my finger tips without loading all the individual modules with the logical switches and matching special functions.

**Comment by kilrah** [comment]
Can't understand anything. What radio? What version? What are you actually missing?

**Comment by projectkk2glider** [comment]
No response from OP, closing.
