### ISSUE TITLE
Bad telemetry Values

### ISSUE THREAD

**Issue by pointu** [opentx/opentx#3804]
hi,

Some bad telemetry values give us a wrong calculated values like +/- 

Exemples are joined in a telemetry log for, wrong values in Vspd/Gps(false dst calculation)

W10 / OTX 2.1.8 / Companion 2.1.8 / Taranis +

[Erreur.zip](https://github.com/opentx/opentx/files/473370/Erreur.zip)

**Comment by projectkk2glider** [comment]
At one point the Vspd is `20399769.6` which is obviously wrong, but that data came from the sensor.

The GPS positon also has some weird values like `152.0063E 000.9789N` but again that comes from a sensor.

Not sure we can do much about it.
