### ISSUE TITLE
No multi module for option for 9X transmitters (multimodule on AVR)

### ISSUE THREAD

**Issue by hactiv8** [opentx/opentx#3812]
This is possible as its done with er9x I've tried building from source with this option on and it will not compile is there some other line needing to be changed to allow 9X boards to be built with Multi-module support?

**Comment by kilrah** [comment]
The code and drivers for that hardware platform would have to actually be written or ported, yes...

**Comment by schwabe** [comment]
Multi is only implemented for ARM boards. AVR is missing multi pulses and the menu implementation might need fixing.
