### ISSUE TITLE
Enhancement: Show small preview image on model image selector

### ISSUE THREAD

**Issue by rcbebo82** [opentx/opentx#3814]
It would be nice if there could be a small preview image of the selected model image in the model image selector.

**Comment by 3djc** [comment]
Are you talking Horus ?

**Comment by kilrah** [comment]
There is a preview in the SD card browser, Taranis has an "Assign image" command that can be used from there but that has yet to be ported to Horus.

**Comment by rcbebo82** [comment]
Primarly Horus yes but this would be mayby also fine on X9E or X9D.

> There is a preview in the SD card browser, Taranis has an "Assign image" command that can be used from there but that has yet to be ported to Horus.

Ok but this means i have to look at the sd card browser and choose every image and open it.

It would be nice if i select the properly Image in model image selector wait a second and a preview would be displayed.

**Comment by kilrah** [comment]
> Ok but this means i have to look at the sd card browser and choose every image and open it.

Precisely not, you see the preview straight while scrolling. Just go try it...

**Comment by rcbebo82** [comment]
Got it, when this would be also in model image selector it would be very nice!

**Comment by bsongis** [comment]
Yes, agree for this one, I will do it when things will calm down

**Comment by kilrah** [comment]
I have a quick patch for the SD browser, but the whole thing would warrant further improvements (on all platforms, e.g. check we can only assign from the IMAGES folder). Do we wait and do it right, or shall I commit the patch?

**Comment by bsongis** [comment]
Perhaps you open a branch, we are not forced to merge quickly, this is not a major issue

**Comment by kilrah** [comment]
Reference didn't work... #3817
