### ISSUE TITLE
Horus X12S N357 - Curves resetting to random points

### ISSUE THREAD

**Issue by MyRCode** [opentx/opentx#3822]
I have had this issue happen on 3 different models.  

I have curves set for throttle hold, idle up, etc. for each of my 3 heli models.  I've been adjusting several curve points and and servo end points then exiting to the main screen and turning off the Horus.

When I turn the Horus back on, all the curves have been changed.  My 2 point flat-line curves have become 5 point diagonal curves, all of the untouched curves have become 5 point curves with random points.  No other sections of the model have changed.

This has happened on all 3 of my heli models and all after making multiple changes to multiple curves.

**Comment by bsongis** [comment]
Is it *always* reproductible?

**Comment by MyRCode** [comment]
It has happened on each of the 3 models after making changes to my setup.  I'm not sure what it is specifically that is causing the curves to randomize.  I can try to go through the same changes again in a few minutes...currently formatting my SD card.

**Comment by MyRCode** [comment]
I'm not sure if this was also occurring on any of the previous firmwares.

**Comment by MyRCode** [comment]
I just tried to reproduce it on N357 and could not.  I was going to flash back to N356 but I'll keep N357 for now and see if it happens again.  I've backed up my SD card onto my computer so should be able to go back to the old curves without having to enter everything manually.  Is there a way to take a screenshot on the Horus?

**Comment by bsongis** [comment]
Still no, but I do believe you! It would be interesting to know if it is really fixed in N357, it's the first time we have such a report. Perhaps your models come from an older Horus alpha release and they were corrupted?

**Comment by MyRCode** [comment]
I programmed the models from scratch on this Horus.   I was getting a windows error that the SD card had errors when I plugged in the Horus and windows chkdsk was unable to correct the error.   I swapped out the SD card for a new one and re-formatted so maybe that was related to this issue.

**Comment by EricFPV** [comment]
I have same issue , flash to N358 , problem solved.

**Comment by 3djc** [comment]
If we can get another confirmation that it is fixed, it would be great

**Comment by kilrah** [comment]
Yep, are you really sure? No way to consistently reproduce has been posted so far...

**Comment by MyRCode** [comment]
Just had the curves reset again on N358.  The last thing that I did was change CV 1 from an 8 point curve with values of -93, -93, -93, -93, -93, 40, 70, 100 to -100 to 100.  

When I powered back on, all my curves were reset again.

**Comment by bsongis** [comment]
Are you able to reproduce this problem? Only one curve was resetted, nothing else?

**Comment by MyRCode** [comment]
I haven't been able to reproduce it so still not sure if that was exactly what did it. 

All the curves were reset again....I can't tell if they were reset to the same points again.  

I've reset everything back to the way it was before and backed up the SD card to my computer.

If it happens again, I'll copy the SD card to my computer before I make corrections and see if I can compare the two versions.

**Comment by projectkk2glider** [comment]
Closing for now, reopen if problem re-appears in new versions.

**Comment by sloper-lloyd** [comment]
I have this issue on 2.2.2 and 2.2.4
X10S
Curves when edited affect other curves. Also when turn off and on 'some' curves have changed.
