### ISSUE TITLE
Request:  Write protect on categories or models

### ISSUE THREAD

**Issue by MyRCode** [opentx/opentx#3823]
When selecting a new category using long press, delete category is one rotation away from select category.  It is very easy to accidentally delete a category.

**Comment by iflymlnm** [comment]
+1 
I've created a few models and deleting the category wiped all my models, very very easy to accidentally delete potentially lots of models.

**Comment by 3djc** [comment]
The solution might be to have a confirmation box for deletion

**Comment by MyRCode** [comment]
I believe there is a confirmation already,  but there is also a confirmation to select a different model so I was used to just hitting the short press twice.   

I've just had to take a mental pause in between the two passes just to verify I haven't accidentally scrolled the wheel.
