### ISSUE TITLE
Turnigy 9xr pro - frozen splash screen after converting from er9sky to OpenTX 2.x

### ISSUE THREAD

**Issue by Heartsbane** [opentx/opentx#3824]
I've been struggling for several days to install OpenTX on a new Turnigy 9xr pro. The transmitter works fine with the er9sky firmware, but after flashing OpenTX it hangs on the LCD splash screen (dimmer than normal). Every minute or so, the unit "clicks" and the LCD screen flashes, but returns immediately to the same state. The transmitter functions normally after re-flashing back to er9sky (from backup). 

At first it sounded similar to Issue [#2852](https://github.com/opentx/opentx/issues/2852) which mentions a few different possibilities, including: corrupt SD card, sound/voice files not properly installed on SD card, and switches not fully releasing. After trying to boot without SD card, trying another SD card from a Turnigy 9xr pro with OpenTX working, and running a full switch test (from er9sky), it seems like none of these are the underlying problem. 

We then found a "workaround" to get past the frozen splash screen. If we unplug the battery to cut power (the on/off switch does not respond), leave the power switch set to ON, and then plug the battery back in, the transmitter boots up with OpenTX and seems to be working.

Any ideas why this might be happening and is it somehow related to what happens when the power switch is slid from OFF to ON?

**Comment by kilrah** [comment]
I think this is the same as #2852. There must be an issue in how OpenTX starts after being launched by the bootloader.
