### ISSUE TITLE
Mix Script Output Return Issue

### ISSUE THREAD

**Issue by RCBrust** [opentx/opentx#3826]
There seems to be a discrepancy in the way that numbers are returned from Mix Scripts in Companion 2.1.9 and OpenTX 2.1.9.  For example (return 3 * 10.24) will return 3.0 in Companion and 2.9 in OpenTX.  If 0.5 is added to adjust for truncation, then (return 1 *10.24 + 0.5) will return 1.0 in OpenTX but 1.1 in Companion.

It seems like Companion is rounding and OpenTX is truncating during the type conversion.  It wouldn't matter which way it is done as long as Companion and OpenTX are consistent.

**Comment by projectkk2glider** [comment]
The problem originates from the Lua internal function `lua_number2integer()` which uses different code depending on the platform. The solution is to define *LUA_ANSI* which will use the same code on all platforms.
