### ISSUE TITLE
Total Flight Time Horus

### ISSUE THREAD

**Issue by Bumblebee78** [opentx/opentx#3828]
Enhancement: I would like a timer, which run from a preset time up. For total flight time. Now you can set it only to 1:00:00 and the timer runs down.

**Comment by MyRCode** [comment]
If you set the timer to 0:00:00 it will count up.  I use one timer for Total flight time per model.

**Comment by 3djc** [comment]
You also need to set it persistant

**Comment by Bumblebee78** [comment]
I know, if the timer start by 0:0:0 it count up.   I have a yak on the taranis whit total time 21:33:00.  i would like start the count by this time.

Bug:
over 00:60:00 the next time is not 01:01:00 its 00:61:00.

**Comment by 3djc** [comment]
That bug will be added to the list to fix

**Comment by 3djc** [comment]
![image](https://cloud.githubusercontent.com/assets/5167938/18625906/efc14740-7e51-11e6-947d-9443f017801b.png)

I do not seem to get you issue

**Comment by Bumblebee78** [comment]
![img_0545](https://cloud.githubusercontent.com/assets/22217563/18627001/c3028f00-7e58-11e6-8b4f-09d43021fc76.JPG)



![img_0544](https://cloud.githubusercontent.com/assets/22217563/18627047/152c7200-7e59-11e6-8643-348206fa6658.JPG)

so it looks at the Horus

**Comment by 3djc** [comment]
What nightly are you running ?

**Comment by 3djc** [comment]
You are not using the timer widget, that's why

**Comment by Bumblebee78** [comment]
OpenTX 2.2.0 RC5 (N357)

**Comment by 3djc** [comment]
![image](https://cloud.githubusercontent.com/assets/5167938/18627257/5737867a-7e5a-11e6-9359-0abeb5210be4.png)

**Comment by Bumblebee78** [comment]
Oh..with the Timer widget works.

**Comment by kilrah** [comment]
Then.. where did it not work? How should we guess?

**Comment by 3djc** [comment]
And the timer limits to 1 hour should be extended in N358

Closing this if you don't mind
