### ISSUE TITLE
N358 - SD Card Warning after Flashing Firmware

### ISSUE THREAD

**Issue by MyRCode** [opentx/opentx#3834]
I now get an SD Card Warning that says "Wrong Files Version - Press any key" on boot up.  

I'm able to bypass the warning and all models appear to respond correctly.

**Comment by 3djc** [comment]
Not an issue : You need to update your Sd card files, as this version did bring changes to audio and S6R files.

**Comment by MyRCode** [comment]
Where can I find the updated SD card files?
