### ISSUE TITLE
Companion 2.2N358 Simulator crash

### ISSUE THREAD

**Issue by lichtl** [opentx/opentx#3841]
The Simulator for Taranis+ hangs straight after start. I've tried several installation under Windows 7 + Windows 10.

Uploading a Video at the moment.

**Comment by kilrah** [comment]
No need for a video, we're aware of it.

**Comment by projectkk2glider** [comment]
Can't reproduce with 29e618146c673f605234a19210157c244c7d9cd4 on Linux.

**Comment by lichtl** [comment]
Just tested 7e8bebfaaccaa89f86890717df681a25d4f164e3 under Linux (Ubuntu) and noticed the same behaviour. Simulator got stuck at the start-screen

**Comment by lichtl** [comment]
Just some more testing. It seems the simulator only works if started directly. Start the simulator via companion22 will cause it to hang/crash.

**Comment by Heliobteixeira** [comment]
Even starting simulator alone wont solve the issue for me on Windows 7 crashing after wrong eeprom data message.

**Comment by projectkk2glider** [comment]
Ok, reproduced on Linux with *Release* build. And it is not a crash, but unresponsive and stuck simulator window.

**Comment by projectkk2glider** [comment]
Ha ha, nice bug, this is how eeprom thread is started:
```c
  assert(!pthread_create(&eeprom_thread_pid, NULL, &eeprom_thread_function, NULL));
```
In release build this line does nothing. :roll_eyes:

**Comment by projectkk2glider** [comment]
@lichtl can you test and confirm my fix?

**Comment by lichtl** [comment]
@projectkk2glider looking good at a fresh compiled linux companion. Is there somewhere a windows binary available to test as well?

**Comment by bsongis** [comment]
Funny bug, could be mine :)

**Comment by bsongis** [comment]
I suppose you git pruned?

**Comment by fred99** [comment]
I have recompiled with your fix under W10/MVS14 with the Release build and now the simulator works like a charm in the 2 modes, direct and from Companion : no more hang

**Comment by lichtl** [comment]
Sweet. 👍
