### ISSUE TITLE
Timers with ThS and ThS should look on throttle input, not throttle stick

### ISSUE THREAD

**Issue by hsteinhaus** [opentx/opentx#3845]
Currently the timers are controlled by the throttle stick, but not by the throttle input as defined in menu "inputs" hen selecting Tht, ThS or Th%. This seems to be illogical, especially when moving the throttle control to other switches/sliders/knobs.

Use case: consider a powered glider, equipped with both motor and air brakes. Usually the brakes are placed on the throttle stick, while the motor is put on a switch. You don't need anything between on and off for the motor in a glider. Sometimes, intermediate throttle settings are even forbidden and would instantly kill the ESC, e.g. with ultra-high power drives used in F5B.

**Comment by kilrah** [comment]
It looks at the configurable "throttle source", and common practice is to set the output channel used for throttle.

**Comment by hsteinhaus** [comment]
Cannot confirm this. At least with 2.1.8 and a throttle source set to "SF" the timer is definetely following the stick, not the switch configured as trottle source.
