### ISSUE TITLE
Taranis+ - opentx-2.2.0N358 SWR sensor no longer available

### ISSUE THREAD

**Issue by lichtl** [opentx/opentx#3851]
Hi,

just noticed that under opentx 2.2.0 on my Taranis Plus the SWR sensors are no longer available.

**Comment by kilrah** [comment]
That is intentional. You can find the "RAS" value in the Statistics screens.

**Comment by athertop** [comment]
There does not appear to be a RAS value displayed in the Taranis 2.2RC10 version on the Stats screen.

**Comment by 3djc** [comment]
It is in analogs test on x9

**Comment by athertop** [comment]
Perfect, Cheers

**Comment by si618** [comment]
fwiw, analog test is on page 7 of radio setup.
