### ISSUE TITLE
Bluetooth not advertising on Horus

### ISSUE THREAD

**Issue by stytom** [opentx/opentx#3852]
On Horus, BLE Module is enabled and named but does not advertise any data and is thus not visible.
In addition when trying to set serial port to S-port mirror the radio falls into Emergency Mode

**Comment by kilrah** [comment]
Serial hasn't been taken care of yet indeed.

BT is unused on both X9E and Horus at this point. No time could be found for that so far.

**Comment by dk7xe** [comment]
Would be nice to get BT working since 
- a cable might not be available always.
- there are still issues with files going corrupt when USB cable is pulled out while Horus is still on.

**Comment by 1Sven** [comment]
Yes it will be nice. Filetranfer and Trainer...

**Comment by xtrmtrk** [comment]
And sending out telemetry data over BT to Tower or similar ground station apps.  Hopefully we'll be able to get to it from Lua.

**Comment by MarenB** [comment]
Hi!

I am pretty sure, BT was working on my X9E in version OpenTX 2.0.x 
After I updated to 2.2.1 I have two issues:
1. BT cannot be enabled from the radio, only via Companion
2. if I enable it, there's no telemtry data send on BT anymore

Unfortunately, my antenna tracker is based on the BT data stream. The BLE module of the tracker connects, but there's no usable data received,

EDIT: quickly updated to 2.2.2 - let's see, if it is fixed, there (didn't find any notice in the release notes)

**Comment by MarenB** [comment]
Hi Guys,

I can now confirm: something happened to the BT datastream between OTX 2.1.9 and 2.2.x

My BT master receives the smartport telemetry without any issues from my X9E with 2.1.9, after updating to 2.2.x it seems to receive empty or no data.
