### ISSUE TITLE
Website RSS

### ISSUE THREAD

**Issue by alexisju** [opentx/opentx#3857]
The [News page](http://www.open-tx.org/news.html) entries order is a bit weird, and the RSS feed give not the right order of entries.

It is not a very big issue but i love RSS and use it to have latest news...

In the same kind of thing, maybe you could update the [OpenTX facebook page](https://www.facebook.com/opentx) when you add news on the website too (even about RC)?

**Comment by schwabe** [comment]
I think we solved this via our OpenTX chat. Closing this for now
