### ISSUE TITLE
2.2nightly: wrong inputline conversion in case of channel source

### ISSUE THREAD

**Issue by strgaltdel** [opentx/opentx#3865]
After model upgrade-conversion from 2.1.8 to 2.2 n358 by Tx firmware, some input lines are referenced to the wrong source.
In case the input line was sourced from a channel, it will be converted into a trim source.
Error occurs only by firmware conversion, not by upload an 2.1.8 eepe file into companion 2.2

2.1.8
![conv21](https://cloud.githubusercontent.com/assets/20392683/19013551/4f76b23e-87d4-11e6-82ae-496ca8d26e1d.jpg)

2.2

![conv22](https://cloud.githubusercontent.com/assets/20392683/19013555/58c4e27a-87d4-11e6-9abf-959659899623.jpg)

**Comment by kilrah** [comment]
Radio type?

**Comment by strgaltdel** [comment]
X9e
