### ISSUE TITLE
D Series Sensors not showing up on Horus N258

### ISSUE THREAD

**Issue by flyingdreamz** [opentx/opentx#3867]
The voltage sensor worked in 2.1 but in 2.2 on the horus, the horus is not finding them. This is the case on my D8R-XP with the FBVS-01 and FAS-40. As well as my X6R using the FBVS-01.

**Comment by kilrah** [comment]
You need to "discover" them. Definitely works, I'm using some.

**Comment by flyingdreamz** [comment]
I have been unable to get the discover function to find them. So far I am at 8 Sensors that the Horus is not seeing.

**Comment by 3djc** [comment]
It clearly works, there must be something wrong on your side:
![image](https://cloud.githubusercontent.com/assets/5167938/19028174/922a94f4-8939-11e6-9b7a-2c0f25eef9e2.png)
![image](https://cloud.githubusercontent.com/assets/5167938/19028177/9c595e92-8939-11e6-9f41-51f7844d6bc2.png)

**Comment by projectkk2glider** [comment]
I think OP has a problem with sensors that connect trough the telemetry connector (via HUB). I would not be surprised if IXJT does not handle external HUB sensors somehow. 

@flyingdreamz do you get at least RSSI, A1 and A2 sensors discovered and working?

**Comment by flyingdreamz** [comment]
I get RSSI but I do not get A1 or A2.
I have literally changed nothing between my Opentx 2.1 on the T+ to my Horus. In fact on the X6R using the Analog port with https://alofthobbies.com/frsky-battery-voltage-sensor-fbvs-01.html it has been direct soldered for a year. When I rebind with my T+ the sensor shows up, when I bind to the Horus I just get RSSI and RX Voltage. On my D8R-XP I get no telemetry other then RSSI.

**Comment by 3djc** [comment]
Wait, I'm unsure of what you are expecting, but an X6R will report RSSI and Rxbt. Extract of X6R docs:
"When pins of A1 and X (Middle Pin) are connected by the jumper, A1 will change from External Analog
Telemetry Port to Internal Built-in battery voltage sensor."

Here is a X6R with FVBS:
![image](https://cloud.githubusercontent.com/assets/5167938/19063605/a4a3418c-8a04-11e6-8d80-798cb577b6e2.png)
![image](https://cloud.githubusercontent.com/assets/5167938/19063609/aca16620-8a04-11e6-91e4-90b966e8fec2.png)

Remove it and place the jumper:
![image](https://cloud.githubusercontent.com/assets/5167938/19063616/bb794a0a-8a04-11e6-9c9e-66029d10267c.png)
![image](https://cloud.githubusercontent.com/assets/5167938/19063620/c39ef1a8-8a04-11e6-949a-c96b4c55472c.png)

I'm unsure of what else you are expecting

**Comment by projectkk2glider** [comment]
Example of D series receiver with a lot of sensors - working:
![img_20161005_103845](https://cloud.githubusercontent.com/assets/5950438/19106603/86e7a2f2-8ae8-11e6-9754-068a7a73877b.jpg)
