### ISSUE TITLE
Horus OpenTX Special Functions Incremental and Source

### ISSUE THREAD

**Issue by tomkfly** [opentx/opentx#3884]
I have been trying to assist someone else set up a Jukebox on his Horus, but the only  Function seems to be "Value" , "Increment" and "Source" don't show for selection.

**Comment by projectkk2glider** [comment]
Are you trying to adjust (increment/decrement) GVARS? If so, the compile option -DGVARS=YES should be used (not sure if it is in nightly builds).

**Comment by 3djc** [comment]
Gvar is an ondemand compilation option on companion :)

**Comment by tomkfly** [comment]
Thanks Projectkk2glider, the problem now is +=1 is making the GVAR increase 10.
3dcj GVARS are the default. You need to check the " nogvars" box to deselect them.

**Comment by projectkk2glider** [comment]
I see the problem that increase never stops as long as condition is true. In my mind it should only do one increase or decrease when the condition becomes true.

**Comment by projectkk2glider** [comment]
Even if you use EDGE LS, that switch is ON for 100ms which is enough to do 10 increments instead of one.

**Comment by tomkfly** [comment]
It makes more sense to only increase by the value selected once per event. Inthe setup I am using the condition is true for 0.1 seconds, but that was put in just so the switch could be seen when monitoring in Companion Sim. I will test it with the duration at zero and see if that fixes it.
Thanks

**Comment by projectkk2glider** [comment]
Exactly, this needs to be fixed. Can you type in a new issue for this, this one is too contaminated.

**Comment by tomkfly** [comment]
Done
