### ISSUE TITLE
Open TX 2.2 N358 Pots S1 & S2 not working on Taranis+

### ISSUE THREAD

**Issue by Heliobteixeira** [opentx/opentx#3890]
Potenciometers S1 and S2 are not being recognized even on Analog Test page.
They are not even displayed on "Source" list of any page.

**Comment by kilrah** [comment]
They're probably disable on the Hardware page, reenable them there.

**Comment by Heliobteixeira** [comment]
You are right. This is the first time that I needed to do that after loading new firmware.
Should I select pot or pot with deternt?

**Comment by schwabe** [comment]
S1 and S2 are pots. LS, RS have a deterent

**Comment by kilrah** [comment]
Depends whether your S1/S2s have a center detent or not...
