### ISSUE TITLE
OpenTX 2.1.9: 3 Point Switch in Stick not supported?

### ISSUE THREAD

**Issue by dklueh79** [opentx/opentx#3904]
I don't know, if it is an hardware or software problem - I think it's OpenTX.
The Problem is, that a  3-pos-switch (from http://rctechnik.de/Knueppelschalter-Spektrum/10003.html) doesn't work correctly. The switch works well, it has been measured. But if I activate it in OpenTX under switches, the main-screen shows an urgly screen, the picture attached. Surely it's the Version for Taranis X9E

The 3-pos switch only works for one postion. Do you have any solutions?

![img_1863](https://cloud.githubusercontent.com/assets/6195999/19361257/3f27177c-9182-11e6-83da-d445a6017fb7.JPG)

![connection](https://cloud.githubusercontent.com/assets/6195999/19361371/aef5ad34-9182-11e6-85d7-9beea42abf76.png)

**Comment by 3djc** [comment]
The screen is normal when you start adding more switches on X9E. (you probably declared it to be connected on SR. The radio does not care (or know) where the stick is , or what it does look like

**Comment by dklueh79** [comment]
I configured the stick in main menue. But the strange is, that the 3-pos switch only supports middle off, down -100% and up postion nothing. I've check the second delivered stick- it behave the same way.
It's connected to sw-l

![img_20161013_204809](https://cloud.githubusercontent.com/assets/6195999/19362592/882a40fc-9187-11e6-8950-89a4ae3cd00c.jpg)

**Comment by 3djc** [comment]
Strange your first screen show R, not L. You need to compare with existing switch to ensure the are the same

**Comment by dklueh79** [comment]
Yes, really strange. so I switched to sw-q. Installed as 3-pos switch. But the same. It works in upper pos with 100%, middle zero and down is nothing. Could it be a mistake in wiring? but i think the wiring is the same like the switches build in.

![img_20161013_211824](https://cloud.githubusercontent.com/assets/6195999/19363548/3e444ace-918b-11e6-93c4-439124725e70.jpg)

**Comment by kilrah** [comment]
They a "smaller" letter, e.g. I or J... I know there was an issue with some higher ones that can't be fixed in 2.1, will have to move to 2.2 for them to work.

**Comment by dklueh79** [comment]
You mean, if I use a slot that exists like SA (sw-a) it should work?

**Comment by kilrah** [comment]
I said SI or SJ...

**Comment by dklueh79** [comment]
Ok, the strange is, that if I connect the Stick-switch to SB where the 9E has an original 3-pos, too, the new stick only works as 2-pos....I think it could be a problem of the switches, not OpenTX....if I connect the original SB to sw-i it works as an 3-pos....

**Comment by kilrah** [comment]
Then 

> The switch works well, it has been measured.

Isn't correct :)
