### ISSUE TITLE
S6R lua on Horus has calibration left/right and front/back text swapped

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx#3905]
S6R lua on Horus has calibration left/right and front/back text swapped. The images are correct. Calibration works if you follow the images.

**Comment by 3djc** [comment]
I'll modify text to say follow the pictures, or something along those lines

**Comment by RealTadango** [comment]
local calibrationPositions = { "up", "down", "forward", "back", "left", "right" }

should match the images. The images forward and left, back and right should be swapped.

**Comment by 3djc** [comment]
Fixed by https://github.com/opentx/opentx/pull/3906
