### ISSUE TITLE
Deleting file in SD manager updates the list wrongly

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#3912]
![before](https://cloud.githubusercontent.com/assets/6065069/19408732/bf6fe79a-92c4-11e6-96bd-50f107b3744c.jpg)

Deleting "P51Mus.png" results in this:

![after](https://cloud.githubusercontent.com/assets/6065069/19408737/d1dc2fe2-92c4-11e6-81d4-f55e96e56e5e.jpg)

The correct file has actually been deleted, it's a display problem

**Comment by projectkk2glider** [comment]
Can't reproduce on `simu` (Horus and Taranis) with ae47b1a4d1b2dc5470e427d010aa844f4e365bdf

**Comment by kilrah** [comment]
It seems to depend where the cursor is in the list. You might need to scroll down a bit , then go back up above the point that causes scrolling if you get what I mean

**Comment by projectkk2glider** [comment]
Confirmed, the item must not be on first page (scroll needed), Taranis is not affected, there the whole list is refreshed after the delete and cursor is moved to the first line.

**Comment by projectkk2glider** [comment]
I chosen the simplest solution, the cursor is moved to the top (like Taranis).
