### ISSUE TITLE
Behaviour change of SF reset to only act upon becoming true 

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3918]
Today I had a lock-up of my radio because I used the SF "reset flight" in a wrong way.
I wrongfully assumed it would act the same as "Play Track" in that it only acts upon the condition "becoming true".

This isn't so.
It does a "reset flight" continuously while the switch is true.
If this is done the radio will go into a race condition and locks up.

I'm proposing to change its behaviour so it acts the same as "Play Track".
I can't see any downsides to that. Maybe others can.

**Comment by kilrah** [comment]
Same as #3858

**Comment by fraternl** [comment]
fixed in https://github.com/opentx/opentx/pull/3920
