### ISSUE TITLE
N358 pots don't appear in calibration menu

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx#3919]
When doing a calibration on 2.2.0 N358, pots don't appear for Taranis Plus, sliders do appear.

**Comment by 3djc** [comment]
Are they declared in hardware section ?

**Comment by powercycle** [comment]
No, they weren't.  I guess my expectation is that the firmware would know what hardware was available.

**Comment by kilrah** [comment]
It does, but since this was only recently added/fixed if you upgraded from an older nightly that got broken.
