### ISSUE TITLE
Open TX Horus 2.2 ON352 - Flight mode trim assignments not working

### ISSUE THREAD

**Issue by clivemartin** [opentx/opentx#3927]
Example, selecting trim from another flight mode + own trim as offset. This function does not appear to work.

**Comment by kilrah** [comment]
I have a model set up that uses this config and have no issue.

You should update your firmware to the current build before reporting issues, especially as it's still pre-release there are many bugs that get solved everytime, you're 4 builds behind.

**Comment by clivemartin** [comment]
Sorry, will update to 358

**Comment by clivemartin** [comment]
Still have an issue despite updating to 358.  If cross trims are selected in Input menu (elev trim on Thr trim) then the fault as detailed above holds.

**Comment by kilrah** [comment]
Please post a non-working setup (ideally the .bin file of that model on the SD card).

**Comment by projectkk2glider** [comment]
Could this #170 be related?

**Comment by projectkk2glider** [comment]
Duplicate of #170
