### ISSUE TITLE
Cosmetic: In LS's Edge. the closing bracket is not displayed (fully)

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#3935]
Horus, current trunk

When Edge  [0.1:<<] needs to be displayed the closing bracket is almost gone

**Comment by projectkk2glider** [comment]
Result
![snapshot_02](https://cloud.githubusercontent.com/assets/5950438/19837761/0dbaba62-9ec1-11e6-8fc2-6c3d61f9dc72.png)
