### ISSUE TITLE
Companion simulator has Hold X and Hold Y, needs Hold SH. 

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#3944]
I originally wrote SF but I meant SH. Thanks kilrah.

I programmed my Taranis to enable certain switch functions while I hold switch SH, but I can't test it with Companion because there's no way to hold SH like you can with the sticks. My only workaround was to temporarily change it to another switch.

**Comment by kilrah** [comment]
I guess you mean SH...

But what about setting all other things as they should be first, and actuate SH last?

**Comment by Miami-Mike** [comment]
What I'm working on is a special "Set Failsafe Trims" flight mode for adjusting trims to the best-flying failsafe positions while I'm actually in flight. In order to properly test this in Companion I need to secure SH↓ and then actuate all of the trims to make sure they do what they're meant to do without affecting the other flight modes. 

It  works great, by the way.

**Comment by kilrah** [comment]
Can be taken into account whenever we finally do that full simulator revamp.

**Comment by pindeslandes** [comment]
Please, see #1627

**Comment by mpaperno** [comment]
Duplicate of #1627, closing.
