### ISSUE TITLE
No option for Haptic on Taranis X9D Non-Plus

### ISSUE THREAD

**Issue by hactiv8** [opentx/opentx#3946]
Ive ticked the box in companion 2.20N359 and i still can't get the haptic option to appear on my taranis I've even compiled from source and still not getting this as an option is there something I'm doing wrong or a bug somewhere?

**Comment by kilrah** [comment]
You must re-download firmware and flash it after ticking the box.

**Comment by hactiv8** [comment]
Im flashing it with opentx-x9d-haptic-noheli-lua-multimodule-sqt5font-en-2.2.0N359.bin so its downloaded it with the haptic option but it's still not working

**Comment by schwabe** [comment]
I think he is right, that is a bug in the Cmake script.

For X9D we do
```  set(HAPTIC NO)```

instead of using an option that could be changed

**Comment by kilrah** [comment]
Yep, correct

**Comment by projectkk2glider** [comment]
Fixed in #3949
