### ISSUE TITLE
Companion 2.2 OS X "Download Voice" link broken?

### ISSUE THREAD

**Issue by GWCTas** [opentx/opentx#3951]
After I download the firmware, I then select "Download Voice" and it takes me to this link http://voices-21.open-tx.org/opentx-horus/en/ and I get a 404 error. Maybe the Voice download is not implemented yet?

**Comment by 3djc** [comment]
Indeed, since no 'release' firmware have been released yet on the 2.2 branch.
You can get them here for nightlies: http://downloads.open-tx.org/2.2/nightly/sdcard/
