### ISSUE TITLE
Horus 2.2.0 NB 358 Problem - Reset Fly data ... Switch problem Warning

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#3952]
If you have for example Dual Rate on Switch SA and switch is pos. on, and you want to try to do a reset for timer, Flight, Telemetry (Reset Flightdata) than arrive a warning: Switch wrong position please proof! Than you have to touch a button, but nothing happen! 
YOU CANNOT SWITCH OFF THE HORUS UNTIL 4 Minutes are over!
That is a very big bug I think?

**Comment by kilrah** [comment]
That was fixed in the current version that was released 2 days ago.
