### ISSUE TITLE
"Redundancy Bus" telemetry values are copied between sensors after simple read/write cycle within companion

### ISSUE THREAD

**Issue by strgaltdel** [opentx/opentx#3953]
After a simple Read from Tx into Companion and Write back into Tx without changes,
Voltage values are duplicated into Current values.
No current data are available
(RB1V copied into RB1A, RB2V copied into RB1A)

You have to delete the sensors and perform a new search on the Tx.

Per definition, sensors for voltage and current have the same id and instance.
They only differs in their unit
eg:

RB1V  
ID 0B00 
Instance 26
unit    V

RB1A  
ID 0B00 
Instance 26
unit    A

maybe companion doesn't write all data needed back into Tx?

tested on X9e & oTx 2.2 RC7

**Comment by schwabe** [comment]
@kilrah that sounds more like a companion bug than TX bug.
