### ISSUE TITLE
[Horus] SBUS/PPM input on Heartbeat pin for external modules

### ISSUE THREAD

**Issue by raleighcopter** [opentx/opentx#3954]
can support for the linker be added for the Horus?

**Comment by schwabe** [comment]
What do you mean with "linker"?

**Comment by raleighcopter** [comment]
https://alofthobbies.com/linker.html

takes the sbus or cppm stream from a receiver (d4r-ii or x4r-sb and pipes it in through the module bay as a trainer port to wirelessly link to another transmitter as a master or slave.

**Comment by kilrah** [comment]
The hardware of the Horus is different and that pin is unfortunately not a serial port like it is on the Taranis, so at least SBUS is likely to be out unless someone feels like decoding serial from timer captures.

**Comment by raleighcopter** [comment]
If cppm will work, it would be very nice to have.

**Comment by agibson2** [comment]
If that is possible for CCPM to work, Is that something time consuming to implement or would most of the code come from the previous implementation on the Taranis?  I would love to be able to use the Wireless Trainer from alofthobbies in CCPM mode.

**Comment by 3djc** [comment]
We understand the need, but as mentioned earlier, it will be a time consuming exercise, so it is unlikely for 2.0

**Comment by robustini** [comment]
With the SBUS there is little to do, but with the CPPM you can do it, but not via software:

https://www.rcgroups.com/forums/showpost.php?p=42694565&postcount=16448

**Comment by raphaelcoeffic** [comment]
see #5518

**Comment by robustini** [comment]
> 
> 
> see #5518

Excellent alternative @raphaelcoeffic , but perhaps it is more complex to weld those two resistances rather than inject the CPPM signal where the radio expects to have it natively.
However good to know.
The soft serial for SBUS would be more interesting, as long as it does not involve an excessive load on the CPU with possibile cpu-lockup.

**Comment by raphaelcoeffic** [comment]
@robustini I had to do it on X10 as the pin is otherwise not connected at all to anything. Meanwhile I have a simple solder  bridge in place. How is the X12S here?

**Comment by robustini** [comment]
The next time I open the tx I try to check.

**Comment by brainbubblersbest** [comment]
Here is your x12s ixjt mainboard
![IMG_20200502_121735](https://user-images.githubusercontent.com/48190425/80915043-c7aa9700-8d4f-11ea-9510-924a94274dfb.jpg)
![IMG_20200502_120701](https://user-images.githubusercontent.com/48190425/80915048-cc6f4b00-8d4f-11ea-8093-974d50fd2e34.jpg)
