### ISSUE TITLE
lua: lcd.drawNumber() standard-alignment changed from "RIGHT" to "LEFT"

### ISSUE THREAD

**Issue by strgaltdel** [opentx/opentx#3956]
oTx RC7 (&prevous revisions) changed luascript standard alignment for numbers from RIGHT to LEFT
This will cause some redesign of most scripts which uses the "lcd.drawNumber" function

simple test with following statements:

	lcd.drawNumber(50,25,123)
	lcd.drawText(lcd.getLastPos(),25,"  lcd.getLastPos() : ", SMLSIZE)
	lcd.drawNumber(lcd.getLastPos(),25, lcd.getLastPos(),LEFT + SMLSIZE)

2.1.8

![align218](https://cloud.githubusercontent.com/assets/20392683/19732185/43543820-9ba0-11e6-9493-87468250c962.jpg)

2.2 rc7

![align359](https://cloud.githubusercontent.com/assets/20392683/19732197/4d561ca8-9ba0-11e6-9453-63bc43ed7ecd.jpg)

tested on Taranis X9e,
Companion screenshot represent firmware behavior

issue was discussed some weeks ago on rocketchat

**Comment by 3djc** [comment]
Yes,  all text functions,  including drawn number,  now default left.  We realize it is a change and some scripts are going to need rework (adding RIGHT for example).

**Comment by strgaltdel** [comment]
OK, so if this is final state i can start to adopt existings scripts, no problem

Thanks
Udo

**Comment by 3djc** [comment]
Thx for your understanding.  We did investigate reverting that,  but that change was made so early in 2.2 dev that there was a lot of implications.
