### ISSUE TITLE
Horus Production Unit - O/S Model menu interface hangs on Pg down (random) 

### ISSUE THREAD

**Issue by Webbsolution** [opentx/opentx#3961]
On random attempts to access the Model menu immediately followed by pge down  - the interface hangs... 

One other pilot has experienced this as well. The link is in tact and sounds function... switches function... but the software menu interface hangs. I hard power off ( hold power button for 10 seconds) is required.

**Comment by projectkk2glider** [comment]
Can't seem to be able to replicate on beta Horus with self debug build (CLI and DEBUG and bunch of other stuff enabled). Will keep an eye out for this.

**Comment by Webbsolution** [comment]
Try binding...then model then page down is fast succession...

**Comment by projectkk2glider** [comment]
Binded to D8 receiver on a model with 16 sensors - can't reproduce. Strange. I might try with the official N359 firmware next. @Webbsolution what firmware options did you check in the Companion?

**Comment by projectkk2glider** [comment]
Closing for now, reopen if it is reproducible.
