### ISSUE TITLE
Lua custom scripts have a 6 inputs limit in 2.2?

### ISSUE THREAD

**Issue by floaledm** [opentx/opentx#3963]
Looks like in 2.2, the number of inputs to lua custom scripts islimited to 6, whereas more inputs were possible before. Could someone please confirm whether that is by design?

**Comment by projectkk2glider** [comment]
Jep, designed that way:
```c
#define MAX_SCRIPT_INPUTS              6
#define MAX_SCRIPT_OUTPUTS             6
```
