### ISSUE TITLE
OpenTX N359 Trim Does not center

### ISSUE THREAD

**Issue by Joetrin** [opentx/opentx#3965]
Development unit 5 HORUS, N359
Frsky Firmware 1.2.20
Mode 2 using Non Eu version

Seems to happen on "Course" trim settings.
Extended trims on

Repeatable:
Adjust your elevator trim to full down
Then using the same trim button, adjust back to center.

2 Symptoms show up.
Maximum trim reached only shows up on the screen as 1/3 of the way up the trim bar
When going extended, it goes to about 2/3rd up the trim bar
When centering the trim, it does not stop at "Trim Center" and it's missing the "=" which indicates trim center.

**Comment by 3djc** [comment]
Fixed in next nightly
