### ISSUE TITLE
Request: Adjust brightness per model / trhough lua / ??

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx#3987]
I am adjusting the brightness every time i use the Horus indoor (50%) or outdoor (90-100%). With so many features there must be a better solution. It would like an option to set the (on) brightness per model (indoor vs outdoor models) or set it through lua (for even more intelligent options). The perfect way for me would be through a light sensor, but that might be not an option without a modification (not for everyone that is). 

So, is there something possible in the model data or a setting adjustable through lua?

**Comment by schwabe** [comment]
I think handling that like volume should be fine (e.g. new special function for that). Haven't looked if adding SF without eeprom is possibly.

**Comment by 3djc** [comment]
Beside the potential eeprom issue, I think we need to set a minimum so that you do not end up with a black screen .. forever :D

**Comment by RealTadango** [comment]
Well... that might be a good idea ;) setting SF ON brightness 0 would make most people unhappy :)

**Comment by kilrah** [comment]
Minimum is handled in the driver, it won't accept anything below 5

**Comment by projectkk2glider** [comment]
Related to #3408 where the original intent of Backlight SF was to change color.

**Comment by nmaggioni** [comment]
Pinging this back to life, having per-model brightness override would be very handy: when flying wings having the screen always on (even on reduced brightness) lets me peek at telemetry widgets anytime, but with FPV quads or simulators there's no need to waste precious battery life.

**Comment by RealTadango** [comment]
This would still be usefull for those indoor or night flying sessions ;) Using a pot or per model setting is still very welcome.

**Comment by RealTadango** [comment]
Still a welcome feature :)

**Comment by HermanKruisman** [comment]
Still a welcome feature :)

**Comment by 3djc** [comment]
If only ! Oh wait it has been added already ! You have a special function to adjust brightness now

**Comment by RealTadango** [comment]
Ow.... Awesome :)

**Comment by RealTadango** [comment]
> If only ! Oh wait it has been added already ! You have a special function to adjust brightness now

Will be in 2.3.10? When was this added?

**Comment by 3djc** [comment]
https://github.com/opentx/opentx/pull/7680
