### ISSUE TITLE
Telemetry log messed up

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#3995]
2.2.0RC7@X9E
Telemetry works fine, but the log is messed up. GPS and LSW possibly in a wrong format? Source is an openXsensor, which worked flawlessly with prior OpenTX versions. No changes made since.
[new  1.zip](https://github.com/opentx/opentx/files/573114/new.1.zip)

Companion hardcopies added:
2.2.0RC7:
![tellog](https://cloud.githubusercontent.com/assets/23188713/20258141/6b214318-aa4e-11e6-8e17-38d5507b910b.png)
2.1.8 identical sensor:
![tellog1](https://cloud.githubusercontent.com/assets/23188713/20258590/a8c25e3a-aa50-11e6-9222-db8746ff1e72.png)
Although the decimals look weird, I get a GE-Track, started from Companion 2.1.9
![ge-2 1 8](https://cloud.githubusercontent.com/assets/23188713/20261476/3ccffd82-aa5e-11e6-919e-1af76cd379c8.png)
2.2.0 FrSky GPS
![gps](https://cloud.githubusercontent.com/assets/23188713/20261271/561b46a8-aa5d-11e6-8c86-a2ccfc886ae9.jpg)

**Comment by Allerhopp** [comment]
When i deleted the sensors and discovered them again, GPS did work as expected, but the LSW field still has the wrong format. Is there a recommendation, to update the sensors, when updating to 2.2?
![log_new](https://cloud.githubusercontent.com/assets/23188713/20268501/b8fd3f52-aa7f-11e6-88d0-7926a44dc05c.png)

**Comment by projectkk2glider** [comment]
Nice, a while ago some other user had the same problem with GPS, same wrong logging contents for location. Since 2.2. is not stable yet, there were a couple of internal storage changes that probably caused this. 

What do  you expect to see in LSW field. That is a hex representation of 64 hex number, each bit is one LSW. Decoding in Companion still needs to be implemented.

**Comment by Allerhopp** [comment]
Thx, i did not realize, that the LSW field represents the logic switches. It is sometimes hard to know, which findings are helpful and which are not ;)
