### ISSUE TITLE
Add support for TX Side mode selection (Telemetry, CH 1-8, 9-16)

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx#4002]
FrOS has an option during bind to select the operation mode of the receiver. This would be nice to have in OpenTX of course :) There are 4 modes with the combinations of Telemetry on/off and channel 1-8 of 9-16. This would probably need some info from FrSky for the commands send during bind....

**Comment by schwabe** [comment]
We have no information how to communicate that to the IXJT. Sniffing FrOS to IXJT serial protocol with a logic analyser is probably the fastest way to get information at the moment.

**Comment by kilrah** [comment]
My contact at FrSky repeatedly insisted it was an S-Port command, but I believe I did find the responsible flags in the PXX stream as expected in below capture for future reference.

Receivers actually don't support that yet, so not putting any priority on it.

![pxx_bind_modes](https://cloud.githubusercontent.com/assets/6065069/21466722/a9d33134-c9d4-11e6-9676-a04a3e8e0f81.png)
