### ISSUE TITLE
Turnigy 9x update on Green" Chip (not Atmega)...

### ISSUE THREAD

**Issue by gstudio74** [opentx/opentx#4003]
I read about the warning on latest Turnigy 9X sold by HobbyKing from summer 2016. I look my PCB and I discover the chip is the "Green", not genuine Atmega. Your warning is about ED040501-H16D, on my PCB there is ED040502-H16D.

Is there the same warning for this version also?

![20161106_093411](https://cloud.githubusercontent.com/assets/23333839/20109089/dd407294-a5de-11e6-9122-b23ae9207318.jpg)

**Comment by kilrah** [comment]
Anything not being a genuine atmega is not supported.
