### ISSUE TITLE
SF "reset timers" to prevent the need to do this with 3 lines

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#4008]
A SF "reset timers" would make it easier to reset all timers instead of creating 3 lines to do that for each timer individially

I was told it needs an "eeprom change"
There's a label for that (I don't know how to attach that)

**Comment by projectkk2glider** [comment]
>I was told it needs an "eeprom change"

Perhaps not, let me see...

**Comment by projectkk2glider** [comment]
Indeed, if we add "reset all timers" we will mess up the existing 2.2 setups. Users will not be happy. The place is there, the problem will be a shift of existing parameters of reset SF.
