### ISSUE TITLE
Companion 2.2 Setup still using sd card BMP directory instead of IMAGES

### ISSUE THREAD

**Issue by jtaylor2** [opentx/opentx#4026]
Companion 2.2 Model Setup still using sd card BMP directory instead of IMAGES for model images.

**Comment by jtaylor2** [comment]
Problem reported and discussed in openrcforums thread: http://openrcforums.com/forum/viewtopic.php?f=45&t=9399&p=121206#p121206

I have submitted a two line pull request to fix this issue.

**Comment by projectkk2glider** [comment]
PR was #4026
