### ISSUE TITLE
Vibrate function in lua code

### ISSUE THREAD

**Issue by pau33** [opentx/opentx#4030]
In LUA code you have several acustic output functions. A  vibrate function triggerd from LUA, for example as an alert would be a good enhancement for the radios with a build in vibration system.

**Comment by projectkk2glider** [comment]
Already done in OpenTX 2.2. https://github.com/opentx/opentx/pull/3740 Could be ported back to 2.1 but we are busy with more important stuff right now.

**Comment by pau33** [comment]
Thank You, OpenTX2.2 is ok. I searched for "vibrate" and not for "haptic", thats why I didn't find it. Sorry.
