### ISSUE TITLE
Telemetry Sensor : german languages shows wrong units

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4031]
@ Kilrah OPENTX 2.2.359 NB
Hallo If you want to hear the Dezibel from RSSI you have to choose "rmp" in the editor for DEZIBEL.
If you choose dB you hear milliwatt, for W is ok come Watt, for mAh come only Zero, for g you hear rpm, for ° you hear g, for ml you hear degree °, for fOz you hear Zero, for I--I you hear milliliter, for -Gl you hear UNZE.
Rest of UNITS for EDIT UNITS are right connected to audiofile.

![20161117_145346](https://cloud.githubusercontent.com/assets/22581690/20392537/8f02db48-acd8-11e6-8d44-310cd4cf552c.jpg)
![20161117_145429](https://cloud.githubusercontent.com/assets/22581690/20392538/8f055e4a-acd8-11e6-898f-f76821e06469.jpg)
![20161117_145457](https://cloud.githubusercontent.com/assets/22581690/20392539/8f066218-acd8-11e6-9733-67880dfc0931.jpg)
![20161117_145555](https://cloud.githubusercontent.com/assets/22581690/20392540/8f0a931a-acd8-11e6-9f2f-5e68274d88fc.jpg)

**Comment by 3djc** [comment]
what audio files are you using ?

**Comment by Githubbachelor** [comment]
I use the audiofiles for DE System

**Comment by 3djc** [comment]
From http://downloads.open-tx.org/2.2/nightly/sdcard/ ?

**Comment by Githubbachelor** [comment]
yes

**Comment by Githubbachelor** [comment]
can you open it I make a mistake in Compouter

**Comment by Githubbachelor** [comment]
I mean reopen it

**Comment by Githubbachelor** [comment]
Thanks

**Comment by 3djc** [comment]
I cannot reproduce, works fine on my radio

**Comment by 3djc** [comment]
it plays file /SOUNDS/de/SYSTEM/db0.wav, from sdcard. Can you check on your computer that this says db ?

**Comment by Githubbachelor** [comment]
What can be the problem?

**Comment by Githubbachelor** [comment]
All in Sounds/de System is 100% OK. All Files are working with exactly names

**Comment by Githubbachelor** [comment]
If you go in Telemetry and say find all sensors start, it find all. For example RSSI - but show RPM. But tell DB for rpm. If you change in editor to Db it tells milliwatt

**Comment by 3djc** [comment]
wait, that's a completely different issue

**Comment by Githubbachelor** [comment]
later in display you see RSSI 91rpm and tell DB

**Comment by Githubbachelor** [comment]
if you take db for RSSI you see in Display later RSSI 91dB and it tell milliwatt

**Comment by Githubbachelor** [comment]
But the soundfile dB0, rpm0, aso is ok

**Comment by Githubbachelor** [comment]
must be a route mistake to the files or wrong DESIGNATION, I think so

**Comment by Githubbachelor** [comment]
Where can I give my idea? To you? For example to make the possibility for Moving/copy lines in the Sensor menu. For example to move RSSI line under the A1 line....

**Comment by 3djc** [comment]
German is missing mW unit, which shifts db, rpm, g, ...

**Comment by Githubbachelor** [comment]
Why do you close that? That was a confirmed bug!
Greetings Michael

**Comment by schwabe** [comment]
Because he commited a fix.

**Comment by 3djc** [comment]
This will be fixed in next available nightly

**Comment by kilrah** [comment]
> Where can I give my idea? To you?  

You create a new issue with the suggestion.
