### ISSUE TITLE
 FrSky Taranis Plus - writing on SD card.

### ISSUE THREAD

**Issue by Georgi65** [opentx/opentx#4039]
Hi I have problem and I have run out of ideas.
I have OpenTX 2.1.9 (2016-09-15) I updayted also bootloader. to the same ver.
I start Taranis in Bootloader and connect cable USB. 
I tried 4 cables on 3 Computers. 2 laptops - usb 3.0 and one PC usb 2.0 All have windows 10 
Windows see Taranis as 2 things and one of this is Memory storage. 
I Can copy from the storage. But I can't Copy to CD Card. 
When I want to do this my taranis it freezing. 
I updayted firmware by Companion 2.1.9 with 0 problems. The only one problem is when I want copy something to card. Can someone help me ? What should I check, change ? 
Is this Taranis problem ? or my cables/PC drivers ? :(

**Comment by 3djc** [comment]
If not cable, I would test the sdcard, a likely candidate for failure too

**Comment by Georgi65** [comment]
Ok will try that but when I take out card and put to card reader then I can copy files with no problem.

**Comment by 3djc** [comment]
We need more data then to confirm. You say you cannot copy to, but can you copy from ?

**Comment by Georgi65** [comment]
Yes when I connect from bootloader taranis I can copy FROM the SD but not to SD. 
When I connect the same SD to card reader then I can copy to SD.

**Comment by Georgi65** [comment]
THANKS ! I changed SD card to 4GB and FAT32 Format. And it works !!!!
