### ISSUE TITLE
Taranis 19-11-2016   Mixer screen cut off on left

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#4043]
The mixer screen is cut off at the left
![mixer](https://cloud.githubusercontent.com/assets/8692856/20454870/5c92e91c-ae4c-11e6-82f6-48e8a293a243.PNG)

**Comment by 3djc** [comment]
I reopened because it looks there are more issues on this screen than just this one

**Comment by fraternl** [comment]
[19-11-2016-all-models.eepe.txt](https://github.com/opentx/opentx/files/601399/19-11-2016-all-models.eepe.txt)

**Comment by fraternl** [comment]
On today's compile (20-11) the mixer screen is still garbled.
The global variable is now gone, but much stuff is being partially overwritten by other...
Taking the mixer screen of one of my DLG's as an example should cover most of those.

@bsongis made a change yesterday afternoon, but it wasn't attributed to this ticket.

![mixer2](https://cloud.githubusercontent.com/assets/8692856/20462067/2b91e8ce-af12-11e6-9d79-ccaa8939d2a5.PNG)

**Comment by bsongis** [comment]
The changers were pushed on a dedicated branch to allow somebody else than me to test it before it's ported to 'next'. Now this has been done and everything should be back

**Comment by bsongis** [comment]
I will be glad to have another report and be sure everything is nice ;)

**Comment by fraternl** [comment]
yes....   I can't see anything wrong now.
Will inspect some more...
