### ISSUE TITLE
Taking screenshot does not work using ENT - EXIT

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#4044]
Taking screenshot does not work using ENT - EXIT
I don't know if it ever worked, but it seems it did as I could find several references to it.
http://rc-soar.blogspot.nl/2015/07/opentx-21-preview.html

I needed it to file the previous github issue.
Now I used a global function.

**Comment by bsongis** [comment]
Would we remove the special function "Screenshot" then? it wouldn't be needed anymore

**Comment by kilrah** [comment]
No, it is still useful in flight! I tend to screenshot my telemetry page at the same time I trigger voice announcements with SH, gives status snapshots to have references

**Comment by bsongis** [comment]
Ok. The [ENT] + [EXIT] remains a good idea, do you agree?

**Comment by kilrah** [comment]
Yes!

**Comment by projectkk2glider** [comment]
On Horus pgup+ent would work better I think.
