### ISSUE TITLE
Bug? HORUS OPEN TX 2.2.0 359 PROBLEM Missing Channel 11 in Screen

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4060]
In the Mixer Screen channel 11 is missing. See picture. That is a bug I think. Channel 1-12 is used in my configuration. 11 is not shown.

![20161121_191702](https://cloud.githubusercontent.com/assets/22581690/20495100/024f8a7a-b020-11e6-9416-740a20873111.jpg)

**Comment by 3djc** [comment]
You have to choose the first chan in the widget settings

**Comment by Githubbachelor** [comment]
I have set the first Channel

**Comment by 3djc** [comment]
I may fix it, but this widget is not designed to be used on this screen

**Comment by 3djc** [comment]
![image](https://cloud.githubusercontent.com/assets/5167938/20495481/953b6e34-b021-11e6-8da0-247ad33786d5.png)

**Comment by 3djc** [comment]
I may also remind that you have a much more evolved chan monitor with long push on the wheel and monitor

**Comment by Githubbachelor** [comment]
Can I take your screen? I do not understand?

**Comment by 3djc** [comment]
you have put the chan mon on a layout not adapted for that, you need for example to take the layout on two collums like I have done.

**Comment by Githubbachelor** [comment]
OK let me test

**Comment by Githubbachelor** [comment]
Ok I try this in 2 Windows I can set the second Window from Channel 13 upwards.

But If you take 1 big screen, it has to check automatic from channel 1 to 20

**Comment by 3djc** [comment]
This will be fixed in the RC
