### ISSUE TITLE
IDEA! WANTED HORUS- IN THE MAIN MENU ROUTE VOLUME TO A POTI OR SLIDER-Maybe in NB360

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4062]
PLEASE PLEASE PLEASE Guys

Is it possible to build a point in the Main Menu where you can ROUTE THE MAIN VOLUME to a prefered:

Switch, Slider or Poti???  That is a very big help to save the nerves.

Also to build in the next Genaration HORUS B directly a poti into the SpeakerCable.

**Comment by kilrah** [comment]
The Volume special function has been there since day 1 of the Taranis.

Please validate your requests before posting.

**Comment by Githubbachelor** [comment]
I know that, but you did not understand me. I do not mean to program that in every Model. I mean a one time done for future. I did not find that in the main menu!

**Comment by kilrah** [comment]
Global functions.

**Comment by bsongis** [comment]
Also please stop using the private rooms of our chat to explain your idea. As stated above IT'S ALREADY IMPLEMENTED.
