### ISSUE TITLE
Horus Beta sd card warning expected version 2.2v0003

### ISSUE THREAD

**Issue by sniperxnl** [opentx/opentx#4065]
I got this message after update the latest version off opentx to my horus. 

Settings 
PCBdev

sd card warning expected version 2.2v0003

**Comment by 3djc** [comment]
Yes, it just means you have not updated, or properly updated your sd card content with the one here: http://downloads.open-tx.org/2.2/nightly/sdcard/

**Comment by bsongis** [comment]
And it would be nice to ask on a forum rather than opening issues here, thanks
