### ISSUE TITLE
Missing the MODE_Q2X2

### ISSUE THREAD

**Issue by Dutchy-79** [opentx/opentx#4068]
Hi,

I'm working on adding the WLToys Q222 to Pascal's Multiprotocol tho It's not in the Taranis software yet so hard to try in MULTI mode.

>  	MODE_Q2X2
> 		Q222
> 		Q242
> 		Q282

Best regards,

Jasper

**Comment by kilrah** [comment]
Until a protocol is fully implemented and released in multi code you should use custom and enter the numbers

**Comment by Dutchy-79** [comment]
Thanks, Pascal just gave me the numbers and i forgot to edit this post.
