### ISSUE TITLE
At loading another model happen NOTFALLMODUS / EMERGENCYMODUS

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4069]
Hallo since an h iam preparing my new models. 5 minutes ago I want to load another model and the system was going into NOTFALLMODUS with a short loud crack. must be a Bug. Please tell me what you need to find out. See picture
![20161124_225922](https://cloud.githubusercontent.com/assets/22581690/20610472/8781af30-b29a-11e6-909e-21a15ff230e9.jpg)

**Comment by bsongis** [comment]
Is it reproductible? I mean if you go to the other model and reload this one, do you reproduce it?

**Comment by Githubbachelor** [comment]
No sorry not reproduc. I must switch off. Than Switch on and all is working again. Sporadically

**Comment by Githubbachelor** [comment]
Now I go on installing my models. Maybe come anothertime??? Hopefully not. I think it has to do with storing. At the moment if I hold the button to load came the crash. What happen at this moment in the firmware? Maybe to find there.

**Comment by Githubbachelor** [comment]
button to load a MODEL

**Comment by projectkk2glider** [comment]
Closing for now, reopen if you can reproduce this issue.
