### ISSUE TITLE
2.2N359 Assign Brightness to any available pot or switch

### ISSUE THREAD

**Issue by Joetrin** [opentx/opentx#4071]
Not really an issue, but I'd like the ability to adjust screen color using any assignable knob or switch.  I guess this can be considered an enhancement.

Thank You

**Comment by SimonJux** [comment]
This would be great to adjust screen brightness and volume on the knob

**Comment by schwabe** [comment]
See also https://github.com/opentx/opentx/pull/3988
but that pull request is not yet fully ready.

**Comment by Viruswelt** [comment]
Maybe it would be possible to adjust screen brightness for each model separately?
When I fly simultor I need a different brightness than in the hall (gym) or on the airfield
especially for the Horus

**Comment by Joetrin** [comment]
Adding to @Viruswelt , if it can be applied in Global Function and Special Function, then we could have both options.

Thank You

**Comment by poge-st** [comment]
Could be solved like the Volume feature with an Special Function/Global Function "ON" - "Brightness" - Input (Switch, Knob, .... )

**Comment by der-ray** [comment]
Having a global function for brightness adjustment via poti would be great for radios with a big color screen like the horus. FPV users for example dont need the screen brightness to be up all the time but only in bright sunlight when looking at it.

**Comment by ikcalB** [comment]
would also love to see that implemented!
same as Volume, like @poge-st mentioned?
