### ISSUE TITLE
Discussion:  Shouldn't the logical switch "One" become true after "Reset Flight"?

### ISSUE THREAD

**Issue by fraternl** [opentx/opentx#4073]
I was looking for a way to act upon a flight reset, but that switch is not available.
A reset flight should, as I believe, act the same as a newly selected model (with some exceptions).
The switch "One", a switch that I never used before doesn't become true.
Is that an oversight, a bug or was it always considered but chosen not to become true?

**Comment by bsongis** [comment]
Needs to be discussed and documented if we don't change how it works now

**Comment by kilrah** [comment]
Yes it should become true IMO at least if the behavior of other things steays as it is.

**Comment by bsongis** [comment]
I just tested it and it seems it already works perfectly (2.3.3 nightlies)
