### ISSUE TITLE
Horus simulator rotary control very hard to use with a Macbook trackpad

### ISSUE THREAD

**Issue by joaquins** [opentx/opentx#4085]
Hi,
The Horus simulator rotary control, is emulated using the mouse scroll function (center wheel).

When using a Macbook without a mouse connected (very common), the mouse scroll function is done using the trackpad, moving 2 fingers up/down.

This cause several movements in the Horus simulation menus (very fast scrolling). Also, is very hard to stop in any menu option, because lifting the fingers from the trackpad cause one more menu movement, resulting in a very poor user experience.

It would be nice to solve this by either:
 - Reduce menu movement response when using the trackpad.
 - Provide alternate mechanism for the rotary control (keyboard/ui based)

Thanks,
Joaquin

**Comment by projectkk2glider** [comment]
Fixed
