### ISSUE TITLE
OpenTX 2.2.0-RC7

### ISSUE THREAD

**Issue by Noltari** [opentx/opentx#4091]
It's unable to check for updates/download firmware.
Any alternative way to download the 2.2 firmware?

**Comment by 3djc** [comment]
You need to supply more details,  because it does work.  Have you enabled nightly?

**Comment by Noltari** [comment]
Nope it doesn't: 
![opentx_2 2 0-rc7](https://cloud.githubusercontent.com/assets/264346/20859389/5c883b26-b95e-11e6-8360-3ec14b5e33d2.png)
Where should I enable nightly?

**Comment by 3djc** [comment]
Please read :http://www.open-tx.org/2016/10/16/opentx-2.2.0RC7
