### ISSUE TITLE
Horus OpenTX 2.2.360 RC8 Problem with Model Name?

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4098]
Hallo
A few minites ago I make a new model and it got the name "model.5" automatically. After I opened an other ready made model. And than I want delete model.5 and I go to delete. The screen ask me to delete model.125? Than I delete it and "model.5" was gone. What is about the difference Model.5 =model125?

Please look pictures.

![20161205_003415](https://cloud.githubusercontent.com/assets/22581690/20870463/dc9ef112-ba88-11e6-9187-6b08a1f6d930.jpg)
![20161205_003432](https://cloud.githubusercontent.com/assets/22581690/20870464/dca01db2-ba88-11e6-8a81-9c31f0cd4da9.jpg)
![20161205_003449](https://cloud.githubusercontent.com/assets/22581690/20870465/dca16172-ba88-11e6-923c-3a93dc04c6d6.jpg)

**Comment by 3djc** [comment]
One is the name of the model (Model 5), the other one is the name of the file holding the model data. I leave this open until we decide if we should display model name on your last screen

**Comment by bsongis** [comment]
We should perhaps display the model name + the model filename, no?

**Comment by 3djc** [comment]
Yeap, will do that today

**Comment by 3djc** [comment]
Fixed in next nightly

**Comment by Githubbachelor** [comment]
Thanks a lot!
