### ISSUE TITLE
Taranis X9E OpenTX 2.2 RC8 New Model Wizard "Hangs"

### ISSUE THREAD

**Issue by OldGazer** [opentx/opentx#4102]
The New Model Wizard "hangs" at the airplane icon and will not allow navigation to a different model type.
Only the setup for a new airplane can be completed using the wizard.

**Comment by 3djc** [comment]
Currently, only airplane is available.. If you don't want to create a plane, just use RTN

**Comment by projectkk2glider** [comment]
I will reopen this to remind us to fix the wizard.

**Comment by OldGazer** [comment]
Thank you.

**Comment by 3djc** [comment]
Fixed, can be dl here : downloads.open-tx.org/2.2/nightly/sdcard/

**Comment by OldGazer** [comment]
I'm confused.  This issue has been closed.  However, the files in the TARANIS archive have not been changed since 12/3/2016 and the wizard still "hangs."

**Comment by 3djc** [comment]
Give it another try. Also, as a general comment, when we close issues, it may not necessarily be accessible to you, it just mean that is done and approved, ready to ship in next version

**Comment by OldGazer** [comment]
Thanks for the feedback.  I will keep this in mind...

I just tried the new script and it works.

Well Done

Thank you for taking the time to fix this..
