### ISSUE TITLE
A Minor Companion Bug in Special Functions

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#4103]
Go to **Special Functions** and enter a **Play Sound, Play Track,** or **Play Value** function.

Change the setting in the **Enable** column to something other than **No repeat**, i.e. a number of seconds, or **Play once, not during startup**. 

Bring up that model in **Print** or **Compare Models** and you'll see the **Special Function** with those settings, properly displayed.

Now change the function setting to something other than **Play Sound, Play Track,** or **Play Value**.

Bring up that model in **Print** or **Compare Models** and you'll see the **Enable** settings that belonged to the function previously entered, inappropriately attached to the new function. Example:

`SF1    SA↓ - Override CH1(0) played once, not during startup`

Workaround: If you set that function back to any one of the **Play** functions, set **Enable** to **No repeat**, and then set the function back to the new setting, the incorrectly displayed **Enable** text will no longer show up in **Print** or **Compare Models**.

**Comment by kilrah** [comment]
Actual issue is that function settigns should be reset when changing function type
