### ISSUE TITLE
GV1 inverse isn't calculated correctly

### ISSUE THREAD

**Issue by ubiquitoususer2** [opentx/opentx#4107]
Not sure about all the protocols here but I'll try my best

GV1 calculates the inverse incorrectly.
example:
 GV1 assigned _valve_100 own value

under mixes:
Channel 6
weight GV1

Channel 7
weight -GV1

results from channel 6 & 7 on simulator or mixmon:
 GV1=100
-GV1=10

this is confirmed and repeatable on  2.2.RC359

**Comment by kilrah** [comment]
Can't reproduce, either not enough details or not clear enough.

Firstly, what radio?

Secondly, what does this mean?

>GV1 assigned _valve_100 own value

Maybe supply your settings file for best results.

**Comment by kilrah** [comment]
Closed due to no reply. Will reopen if requested info is supplied
