### ISSUE TITLE
Horus RC8 Wizard 2.2.0.N360

### ISSUE THREAD

**Issue by Casichispea** [opentx/opentx#4111]
when  the option V tail is selected immediatly the wizard stops running and the error : "250 attempt to index global 'TailCfgBg'" appears.

**Comment by 3djc** [comment]
My bad, a typo in the script. You do not have to wait the next RC, you can can re-download the files in http://downloads.open-tx.org/2.2/nightly/sdcard/, it should fix the issue

**Comment by Casichispea** [comment]
Hi

I was sure it was a writting  error.
The wizard looks really good
Thank you
Regards


El 8 dic. 2016 22:30, "3djc" <notifications@github.com> escribió:

My bad, a typo in the script. You do not have to wait the next RC, you can
can re-download the files in http://downloads.open-tx.org/
2.2/nightly/sdcard/, it should fix the issue

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/opentx/opentx/issues/4111#issuecomment-265861241>, or mute
the thread
