### ISSUE TITLE
wrong-freeze opentx 2.1.9 turnigy9x m128 (no green processor)

### ISSUE THREAD

**Issue by 19alex86** [opentx/opentx#4114]
Hi everyone!!!! :)
I have a problem with my turnigy9x M128 processor "NO GREEN" ..
when I push the exit button repeatedly and not, not always, i have a reboot the system  or I have a freeze of the battery voltage. example. the voltage is 9.7 volts happens that suddenly drops to 8,6volt without the possibility of ricorreggerla from the menu and the only solution is to restart the radio.
What can you think? I done also this mod: "9x upgrade to ATmega128A3-AU + Reboot With Horiz Trims"  and indeed from right trim i haven't more the reboot problem
thanks to all in advance and sorry for my bad English!

**Comment by schwabe** [comment]
Duplicate #3694. See also http://www.open-tx.org/2016/10/29/hk-9x-announcement

**Comment by kilrah** [comment]
He said he did NOT have that processor.

But anyway this looks like a hardware problem, not our thing.

**Comment by schwabe** [comment]
Oh sorry, I interpreted that as "No Green" m128 and for some reason thought no green was the chinese manufactor

**Comment by 19alex86** [comment]
i solved!!!!! :)
![9x 20board_remove 20exit 20cap](https://cloud.githubusercontent.com/assets/24466487/21054247/14ffe5aa-be2d-11e6-938f-b1dec8d41509.jpg)

**Comment by 19alex86** [comment]
However, i want to signal a bug in the firmware 2.1.9 for turning 9x m128, in the section "channels" voice trim.. the issue is also in the simulator!

**Comment by bsongis** [comment]
voice trim? would you explain more?

**Comment by mhotar** [comment]
I had similar problem with my M128 chip i placed to the 9XR. I had this issue with Up,Down,Left,Right buttons. I placed a resistor in series with the switches. I sold this radio later, but I know new owner had the same problems with Menu/Exit buttons in some rare cases as well. It worked Ok with M64 but was strange with M128 http://openrcforums.com/forum/viewtopic.php?f=73&t=628&start=420#p37236
