### ISSUE TITLE
Simulator only allows 6char lua filenames

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#4117]
On Companion 2.2 rc8 with Taranis+ model selected in profile, when a model has a telemetry script selected for one of its screens, if the filename is >6+3 chars, then running the script (long press on 'page') the simulator returns: Script syntax error. Cannot open /SCRIPTS/TELEMETRY/telemp.lua no such file or direc

the actual file selected is telempc.lua, but the simulator truncates the name to 6+3 chars max.

Additionally, the DISPLAY screen and the CUSTOM SCRIPTS screen will both only list scripts which are <=6+3 chars

I have no idea if these issues exist on the Taranis itself as haven't tested the firmware for 2.2 yet.

**Comment by 3djc** [comment]
Due to tight resource allocation, many filenames in 2.2 are indeed limited to 6 chars. Not a bug, something we all have to leave with until the next major eeprom change
