### ISSUE TITLE
Horus N360 RC8 Play Value doesn´t work with telemetry

### ISSUE THREAD

**Issue by Casichispea** [opentx/opentx#4126]
Play value works with Batt, GPS etc but not with telemetry RSSI, ALT etc.  Nothing happens.

**Comment by kilrah** [comment]
No issue reported nor reproduced.
Please add more details and specific configuration if you want to reopen.

**Comment by Casichispea** [comment]
Special funtion "Play Value"  doesnot read the telemetry values but works
with transmitters one like Bat, GPS, etc.
It is a serial Horus and it has worked under N359.

**Comment by Casichispea** [comment]
Everything OK. Option FAI in companion was activated. now w/o FAI play
value works
