### ISSUE TITLE
Single expo curve in input option

### ISSUE THREAD

**Issue by OpenMik** [opentx/opentx#4127]
On radio in input window, expo option is a symmetrical regulation of curve
Is possible to add a asymmetrical regulation similar to SINGLE EXPO option in companion curve page?
For example Is very useful for adjust gas response

**Comment by projectkk2glider** [comment]
Use two input lines and `Side` option set like this:
![snapshot_01](https://cloud.githubusercontent.com/assets/5950438/21082706/5c4d980c-bfe1-11e6-9dd9-8d9effbdd32f.png)

**Comment by OpenMik** [comment]
Single Expo is like this
![curve](https://cloud.githubusercontent.com/assets/24204587/21082794/046b6d7e-bfe3-11e6-90eb-1f49603eb65a.png)
Is possible to obtain it by a curve, but  is more useful changing only a parameter in Input form 
![curve 1](https://cloud.githubusercontent.com/assets/24204587/21082814/864446cc-bfe3-11e6-8be8-f04590fb47db.png)
Expo is already present in Input form, but with a symmetrical response

**Comment by OpenMik** [comment]
![input](https://cloud.githubusercontent.com/assets/24204587/21083152/8f76b73c-bfea-11e6-82a4-4542c9873877.png)

**Comment by OpenMik** [comment]
@projectkk2glider 
my request is different from how you get it
Other radio have this function and is very useful
currently to change the response of the engine need to edit more points individually on a curve
I suppose no more change on EEPROM is needed

Thank you

**Comment by kilrah** [comment]
The function was actually added in companion as a workaround becasue it would have been too big a change in the firmware. Only 4 curve modes are possible using the current structure and they're all used, allowing for more would be a huge change for little audience.

**Comment by projectkk2glider** [comment]
@OpenMik Try this workaround CH0
![screenshot](https://cloud.githubusercontent.com/assets/5950438/21153178/a82225f2-c169-11e6-8ad0-95c6e38f4e5c.png)
3 gives you the throttle response you want, expo amount is adjusted with GV1.

**Comment by OpenMik** [comment]
@projectkk2glider 
Thank you for your Suggestion
I'll try it
