### ISSUE TITLE
Little error in lua documentation of model.setGlobalVariable

### ISSUE THREAD

**Issue by pau33** [opentx/opentx#4129]
Actual lua docu:
model.setGlobalVariable(index, phase, value)
 -phase zero based phase index, use 0 for Phase 1, 5 for Phase 6

In my simulation it looks, as if:
 -phase phase index, use 0 for Phase 0, 5 for Phase5

should be correct way. phase is not zero based, index is zero based.

opentx 2.1.9, Taranis Plus

**Comment by pau33** [comment]
I have not tested it, but I assume it will be probably the same at model.getGlobalVariable

**Comment by projectkk2glider** [comment]
You are right, Flight modes start at zero!
