### ISSUE TITLE
X7 misc issues

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#4143]
- [x] Using source popup doesn't work and caused reboot on certain commits (when pressing enter, or when scrolling past displayed items)

- [x] Missing unexpectedShutdown flag on main view 

- [x] Screenshot SF outputs valid image but with garbage

- [x] ~Can't scroll up in text view,~ exit back to SD browser shows the [..] at the bottom

- [x] Can't seem to be able to exit a lua screen with RTN long

- [x] SH not defined as momentary

- [x] S1/S2 center position not calibrated

- [ ] ~TMR3 not displayed in stats (maybe not necessary, didn't think of the custom telemetry screens when I wrote that...)~

- [ ] ~NOT URGENT - Custom scripts page missing~

- [x] Reset function broken on telemetry items

- [x] LS V2 not switching format when comparing a Timer

**Comment by bsongis** [comment]
For SH, would you do a fresh erase of your EEPROM to be sure?

**Comment by bsongis** [comment]
What do we do with TRM3 then?

**Comment by kilrah** [comment]
Let's forget about TMR3 for now.

I confirm SH even after a reset, selecting it as a switch som a field and using autoswitch does not work as toggle. Also it seems S1/S2 are set as "pot without detent" as the center position is not being calibrated

**Comment by bsongis** [comment]
Which script did you try? Is it reproducible with the snake script?

**Comment by kilrah** [comment]
I don't remember which script it was - I now can't seem to get any standalone script to run including snake (and existing Taranis telemetry scripts like BattCheck cause a reboot)

**Comment by 3djc** [comment]
They would be drawing outside screen given X7 size, no ?

**Comment by kilrah** [comment]
Yes but shouldn't we have protection for that?

**Comment by 3djc** [comment]
I think it would be very wise yes :)

**Comment by bsongis** [comment]
@kilrah would you only try the scripts from the official SD? Here the snake is perfectly OK and exits properly with [EXIT Long]

**Comment by kilrah** [comment]
OK the X7 snake is OK indeed!

**Comment by bsongis** [comment]
Sure, which script would be a good candidate for those tests (and crashes now)?

**Comment by kilrah** [comment]
For example this, run as telemetry script causes a reboot when the screen is displayed

```
local function run_func(event)

  lcd.clear()

  lcd.drawText(10,10,"Hello World \128 \129", MIDSIZE)

end

return { run=run_func }

```
