### ISSUE TITLE
Horus outputs widget: display channel name when available

### ISSUE THREAD

**Issue by joaquins** [opentx/opentx#4145]
The "outputs" widget in the Horus displays the channel number.

When a channel is assigned a name in the model output settings, this name should be displayed instead.

Rationale for this request: Specially useful when having lots of models with different channel assignment (TAER, AETR...), and labeling the channel output helps when checking the outputs widget.

NOTE: A pull request with this change will be provided by me following this issue request.

**Comment by projectkk2glider** [comment]
Done
