### ISSUE TITLE
Little error when using lua string.format and lcd.drawText

### ISSUE THREAD

**Issue by pau33** [opentx/opentx#4156]
I try to show the preceeding +- on the telemetry screen.
It works only for the smaler fonts:

    lcd.drawText(0,0,string.format("%+04i",23),SMLSIZE)
    lcd.drawText(0,10,string.format("%+04i",23))
    lcd.drawText(0,20,string.format("%+04i",23),MIDSIZE)
    lcd.drawText(0,40,string.format("%+04i",23),DBLSIZE)
    lcd.drawText(50,20,string.format("%+04i",23),XXLSIZE)

Result:
![image](https://cloud.githubusercontent.com/assets/19154380/21419387/94ef52ba-c827-11e6-9964-b56bcf0d3925.png)

It is the same result, if I use %i or %d
Taranis Plus  OTX2.1.9

Thank you in advance.

**Comment by projectkk2glider** [comment]
Both DBLSIZE and XXLSIZE fonts don't have `+` character at all (except on Horus). Should we add them or not?

**Comment by kilrah** [comment]
No reason not to I guess

**Comment by 3djc** [comment]
Just let me finish the drawNumber PR before changing it on next please (or at least please start from DBLSIZE in my branch)

**Comment by pau33** [comment]
Thank you for the fast response.

There are more characters missing in the large fonts, for example < or > and some more. Others appear differnet on the panel than on the keybord.

May be not all characters must be implemented, but the implemented ones should be described in the documentation.

**Comment by pau33** [comment]
May be an appropriate subset of characters could be:
"=+-_.:,;<>|^*#()!?"

Some work already.

**Comment by kilrah** [comment]
You need to look at the standard size font file - that's what can be implemented.
DBLSIZE should have all supported chars, XXLSIZE has only numbers (storing the whole font is starting to become ridiculously huge in memory requirements).

**Comment by pau33** [comment]
Are you shure?
With     lcd.drawText(0,20,"=+-_.:,;<>|^*#()!?",DBLSIZE)  I get:

![image](https://cloud.githubusercontent.com/assets/19154380/21452255/069e493c-c906-11e6-9600-1854c50ad40b.png)

For the XXLSIZE I agree, only number an +- should be sufficient.

**Comment by kilrah** [comment]
Well it is in the font file, but something else could be broken. 

https://github.com/opentx/opentx/blob/next/radio/src/fonts/std/font_10x14.png

**Comment by projectkk2glider** [comment]
That font file si never used, the used font is https://github.com/opentx/opentx/blob/next/radio/src/fonts/std/font_10x14_compressed.png

**Comment by lshems** [comment]
Would it be logical to stick to  the characters used in the string.byte and string.char functions?

**Comment by pau33** [comment]
In my opinion that is a good idea and logical. That would show the ASCII characters from 32-126 correctly on the screen (string.char).
If memory size is a problem at the big fonts, it could be less (XXLSize numbers and +-).
