### ISSUE TITLE
Horus 6 position switch hysteresis/debouncing OpenTX N360

### ISSUE THREAD

**Issue by joel-1** [opentx/opentx#4161]
Please add hysteresis/debouncing to the Horus 6 position switch. As it is, it is easily glitched. Say for example you are switching from position 5 to position 6, the switch will go to the position 1 state as it passes through the no contact area between 5 an 6. This occurs between any switch positions as you go through the no connect region. The no connect state defaults to position 1. This can be minimized by adding some multi sampling for the switch. A bonus would be to make the sampling period adjustable by the user..

Thanks

Joel

**Comment by kilrah** [comment]
It's been there forever when you use the 6posX switches. Delay is configurable in radio settings.
