### ISSUE TITLE
Negative GV's as Input Weights no longer works in 2.2.0N360

### ISSUE THREAD

**Issue by roycegb** [opentx/opentx#4163]
I can no longer use negative Global Values for input weights as of R360. The resulting weights pass only very small or no stimuli.  Positive GV's work correctly.  Negative GV's may have worked in the September releases of 2.2 but certainly work in 2.1.9.

**Comment by kilrah** [comment]
What about some useful details, like on what radio?

**Comment by roycegb** [comment]
Andre,

Sorry, Taranis X9D Plus.  The failure shows up on the Tx or on the Companion 2.2 simulations.  If you look at the resulting Curve, it is squashed, probably a math error.

The inputs are shown in the image, (-GV1) weights causes the problem only in 2.2.0.  (GV1) weights work fine in 2.2.0.  

The receiver screen shots show that the inverse Curve seems to be calculated wrong. It should be the same basic extent but opposite slope.   Thw (throw) is GV1 on the two screen shots.

Thanks,

Royce

**Comment by projectkk2glider** [comment]
I can't reproduce
![screenshot-1](https://cloud.githubusercontent.com/assets/5950438/21470368/ff9ca6c0-ca85-11e6-8835-0adccea712ee.png)

@roycegb your pictures are not showing.

**Comment by kilrah** [comment]
Maybe he means when you select -GV1 as weight?

**Comment by bsongis** [comment]
-GV1 as mixer weight works perfectly
testing -GV1 as input weight now ...

**Comment by bsongis** [comment]
![snapshot_01](https://cloud.githubusercontent.com/assets/5603504/21472719/380e37ca-cae6-11e6-97b3-af5314fa7fab.png)

**Comment by roycegb** [comment]
Bernard,

I had built my original model files in version 2.1.  I brought those over into version 2.2.  Apparently the format translator makes some sort of error.  If I generate totally new versions of each model within 2.2 they seem to work correctly.  

I think i read something about translator problems in the OpenTX discussion under the S6R topic.

Thanks for your help.

Royce

**Comment by schwabe** [comment]
do you still have a backup of your 2.1 files? Reproducing the error would allow us to fix it.

**Comment by bsongis** [comment]
this is very possible I forgot something in model translations, I need a backup to reproduce!

**Comment by roycegb** [comment]
Bertrand,

Here are the .eepe files for version 2.1 (works) and then version 2.2 (doesn’t work).  You can see the problem in Companion 2.2 with the version 2.2 file or replicate the conversion error by opening the version 2.1 file with Companion 2.2.

I am using Companion Version 2.2.0N360, Dec 4 2016 on a MacBook Pro running OSX version 10.11.6.  I have not tried running on Windows or Linux.

Royce

**Comment by schwabe** [comment]
The attachments you probably made to your email did not get through to github. And just to be clear you made the conversion with Companion and not with the radio itself?

**Comment by kilrah** [comment]
Attachements are not supported when replying via e-mail. Need to use the web interface.

**Comment by roycegb** [comment]
Arne,

Yes, I made the conversions in the latest Companion and not the radio.

Royce

**Comment by bsongis** [comment]
Conversion tested on Companion. Again everything fine. Please reopen with the attachments if needed.
