### ISSUE TITLE
X12S New Model wizard - disable

### ISSUE THREAD

**Issue by robthomson** [opentx/opentx#4170]
I am not a huge fan of the wizard method on opentx.   Prefer the manual creation of models.

In the past - simply renaming the 'WIZARD' folder to something like 'WIZARDX' would disable the functionality.

On the X12S, doing this only breaks the functionality.  You get a wizard prompt - but no content in the wizard.  

Is there a magic way to turn off the wizard?  or is it intentional for it to now be mandatory?

**Comment by 3djc** [comment]
When the wizard selectors shows (right now only with Planes if you are using the default sd card content), you just push RTN and you are done (your model is created without running the wizard)

**Comment by robthomson** [comment]
Yup.  I know that.

But seems to me that if you dont want the wizard - you should not even be prompted for it?

**Comment by schwabe** [comment]
That is one of the software design problems. And in this the decision is to show the wizard to everyone since it not a major annoyance. You just have press one more button and it goes away.

**Comment by kilrah** [comment]
I also would like not to appear at all, I was also renaming the wizard on the card so it didn't pop up.

If this can't work anymore becasue the loader stays then an option should be added to enable/disable the wizard - if only for consistency with companion where the exact same thing has been done.

**Comment by bsongis** [comment]
I also don't use the wizard here, I will have a look now

**Comment by bsongis** [comment]
```
#if defined(LUA)
    chainMenu(menuModelWizard);
#endif
```

we could insert a test if the WIZARD directory is there, am I wrong?

**Comment by 3djc** [comment]
This will be available in next nightly
