### ISSUE TITLE
Cannot change startup switch warning positions in the radio

### ISSUE THREAD

**Issue by JoeB99** [opentx/opentx#4171]
It does not seem possible to change the expected position of a switch in the radio.

I have mine set to all up except SF which is expected to be down. I need to change SF to be up at startup.

I can turn on/off the "check" for SF, but cannot change the expected state. Companion works as expected.

OpenTX 2.1.9 taranis plus.

**Comment by kilrah** [comment]
Set switches as desired, long press enter to store current positions.

**Comment by tomkfly** [comment]
Model setup scroll down to "Switch  Positionns. Press ENT and then move the corporate across to SF, using the "-" button and press ENT again this should change SF to SF^. Then press EXIT

**Comment by JoeB99** [comment]
Yes, thank you.
