### ISSUE TITLE
Range Pot´s S1, S2 and L1, L2 to small

### ISSUE THREAD

**Issue by SDX50** [opentx/opentx#4172]
Hallo together,
i think i´ve found an issue at the range of the Pot´s above.
discription: i have done the calibration, then i cheked the range´s of all pot´s and i saw that the Pot´s S1 S2 L1 L2 dont work at the moving of the slider and the pot correct.
Example: Start slow moving slider L1 from the lowest position, the Gauge don´t change.
The Gauge start changing at about 10-15% of moving and stop´s at about 85-90% of all the way moving to the highest position.
Result: loosing of about 20-30% of the conplete way/sensibility.

**Comment by kilrah** [comment]
That's mechanical. Can't do anything about it.
