### ISSUE TITLE
translate companion to chinese, need a companion_zh_CN.ts file

### ISSUE THREAD

**Issue by Kongse** [opentx/opentx#4179]
Hi i'm trying to  to translate companion to chinese. 

At #712 I've seen some guide to do this, but seems  a companion_zh_CN.ts file should be created first. 

I'm new about github, so what should I do next as a translator, should I follow the guide in "OpenTX Git Development Workflow" exactly?

thanks a lot.

**Comment by projectkk2glider** [comment]
Is it possible to display Chinese texts using western charactes? If not (which I think is true), then this will be almost impossible. Current OpenTX code only has western fonts defined. Current characters can be seen here:

https://raw.githubusercontent.com/opentx/opentx/next/radio/src/fonts/480x272/font_midsize.png

**Comment by kilrah** [comment]
He seems to be interested in translating Companion only, and posted on the forum that it works (he inserted Chinese translations in the italian file and they seem to display).

**Comment by projectkk2glider** [comment]
:blush: Missed that.

**Comment by Kongse** [comment]
Yes the companion can display Chinese but firmware seems impossible. 

It  comes a problem that when Chinsese users use a translated companion software to edit models, they may feel unsure what items on Radio corresponding to the items on companion. 

It can be partly solved by while translating the companion to Chinese, showing English words in brackets beside the translation words. I've tested it before (as kilrah mentioned above using italian ts file) and seems working well. 

So when they edit one item on companion, they know what's the item exactly corresponding to on the radio. And by cross reference, a chinese user unknown about English would learn to user Opentx radios faster.

**Comment by kilrah** [comment]
There you go:
https://github.com/opentx/opentx/tree/next/companion/src/translations

**Comment by Kongse** [comment]
Thank you all too :), I'm working on the file.

**Comment by kilrah** [comment]
Translation included but somehow not working, still need to fix

**Comment by kilrah** [comment]
Fixed
