### ISSUE TITLE
Pseudo Diversity

### ISSUE THREAD

**Issue by robthomson** [opentx/opentx#4184]
Hypothetically....

It seems it should be possible to have a pseudo rf diversity setup on the horus.

There is an internal and external antenna.  So what would be needed is something as follows:

- read rssi on internal module.
- if ok.  keep using antenna currently in use.
- if rssi low -> switch antenna - read rssi - compare to last..  then choose best antenna.

The risk.. a possible 'blip'.  But then you where already nearly up sh!t creak with a low rssi anyway!

To do this would need an additional option on the module antenna page.

INTERNAL|EXTERNAL|BOTH

And then a sub routine that kicks in when rssi is low?  or I guess even at a regular interval?

**Comment by kilrah** [comment]
The module does that already, when you select External it uses both internal and external. That was added a couple of RF firmwares ago. 

Besides, doing that in the radio OS would have WAY too much latency to be any useful, that's something that must be (and is) handled frame by frame by the module firmware.
