### ISSUE TITLE
Horus main thread freeze if Instant trim causes trim overflow

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#4191]
Reported by @horuschris in chat

https://opentx.rocket.chat/group/OpenTX_Horus_Testing?msg=RfFGjjdM98CAoqme6

**Comment by projectkk2glider** [comment]
Original report in case chat links stops working:

>My screen and buttons lockup is reproducible. It doesn't need the Rx switched on. It seems to happen after a number of instant trim operations and is easiest to reproduce if instant trim takes the amount of trim beyond what would be available with the trim switch. It happens on any screen . (I don't believe that I need to take trim that far in my flight today, but can't be absolutely sure).

**Comment by 3djc** [comment]
Fixed in next nightly
