### ISSUE TITLE
GPS sensor config corrupt after opening 2.1 eepe in 2.2 companion

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#4193]
In 2.1.9 companion, I have a bunch of sensors configured including the GPS, all of which were created by discovery method (on Taranis Plus radio). (In fact, it is known that GPS sensor will only format correctly if using the discovery method to create it in 2.1 as a manually configured GPS sensor just displays 5 digit numeric formatted as volts) In 2.1 Companion, the GPS sensor displays correctly: lat, long etc.
If I open that same 2.1 eepe file in 2.2 Companion, then the GPS sensor gets screwed up - it behaves as if it were added manually (as mentioned above), so shows as 5 digit numeric (with volts format). Following the 'save as' option to convert the eepe to 2.2 format does not resolve this. I can only presume that the sensors will require a fresh discovery to correct this once upgraded to 2.2.

**Comment by kilrah** [comment]
Would have been the same problem as https://github.com/opentx/opentx/issues/4174
