### ISSUE TITLE
Horus 2.2 N360: SPORT packets sent by LUA are sent to random sensor IDs

### ISSUE THREAD

**Issue by raphaelcoeffic** [opentx/opentx#4205]
I traced the SPORT signal at the back of the Horus, and it seems that SPORT packets sent by LUA scripts (here S6R.lua) are sent to random sensor IDs. However, the S6R.lua sends its READ requests to sensor 0x1B:
```
local function telemetryRead(field)
  return sportTelemetryPush(0x1B, 0x30, 0x0C30, field)
end
```

First one is sent to 0x00:
<img width="691" alt="screen shot 2017-01-06 at 21 55 45" src="https://cloud.githubusercontent.com/assets/1050031/21732688/f5c7a59e-d45a-11e6-9314-fdb329d0375e.png">

and then 0xCB:
<img width="722" alt="screen shot 2017-01-06 at 21 59 00" src="https://cloud.githubusercontent.com/assets/1050031/21732771/65ffbe64-d45b-11e6-9ef3-75ca0c3c5aca.png">

and on and on.... each time another ID (0x00 is there a couple of times).

**Comment by raphaelcoeffic** [comment]
Same behaviour with "next" -> random IDs are used to send the values out.

<img width="684" alt="screen shot 2017-01-06 at 22 45 21" src="https://cloud.githubusercontent.com/assets/1050031/21734074/dca8c5d2-d461-11e6-9b25-996f348bacf3.png">

**Comment by RealTadango** [comment]
I confirm the issue and have the same issue on my Horus

**Comment by raphaelcoeffic** [comment]
Was trying to make a list of the sequence used, and then I see this:
<img width="715" alt="screen shot 2017-01-07 at 15 53 37" src="https://cloud.githubusercontent.com/assets/1050031/21742552/88973b50-d4f1-11e6-8ef3-4e687de2b1a7.png">

**Comment by raphaelcoeffic** [comment]
And here another strange thing. Here is the global picture:
<img width="615" alt="screen shot 2017-01-07 at 15 57 02" src="https://cloud.githubusercontent.com/assets/1050031/21742581/2ebeaa0e-d4f2-11e6-9934-866719c4fbc0.png">

And now a little closer, the poll request:
<img width="223" alt="screen shot 2017-01-07 at 15 57 25" src="https://cloud.githubusercontent.com/assets/1050031/21742587/3d6d9bb4-d4f2-11e6-8bbc-0d86c5610490.png">

and the reply from OTX almost 9ms later:
<img width="710" alt="screen shot 2017-01-07 at 15 58 12" src="https://cloud.githubusercontent.com/assets/1050031/21742589/4afd4c66-d4f2-11e6-807a-ccf87e2773b1.png">

**Comment by raphaelcoeffic** [comment]
If you ask me, there is something seriously broken here...

**Comment by schwabe** [comment]
Where are these captured. On the sport pin of the TX or the sport PIN on a RX?

**Comment by raphaelcoeffic** [comment]
@schwabe on the TX

**Comment by RealTadango** [comment]
All S.Port push issues are solved if you use the Taranis telemetry driver.

**Comment by RealTadango** [comment]
Confirmed to work. ID's are correct, speed is good. Works as expected :)

**Comment by raphaelcoeffic** [comment]
Works on my side with Horus as well. I'll test with Taranis right away.

**Comment by raphaelcoeffic** [comment]
Looks good on Taranis as well. Tested with S6R.lua and both scripts from Betaflight (SpMsp.lua & BFSetup.lua).

**Comment by 3djc** [comment]
Fixed in next nightly
