### ISSUE TITLE
Timer main screen doesn't work

### ISSUE THREAD

**Issue by emics** [opentx/opentx#4207]
from release 2.0.18 [opentx-9x-frsky-battgraph-thrtrace-en-2.0.18] and after, in my radio Turnigy 9X, the THs Timer in main screen doesn't walk if I increase the throttle, it is always at 0:00

i attach my conf
[configTurnigyRadio.txt](https://github.com/opentx/opentx/files/691655/configTurnigyRadio.txt)

if I use the 2.0.17 the timer work successufully.

**Comment by hrenz** [comment]
Please update at least to V2.1x
