### ISSUE TITLE
Simulator Open TX 2.2 (hello.wav)

### ISSUE THREAD

**Issue by rcbebo82** [opentx/opentx#4213]
In the simulator the greetings sound "hello.wav" is not played. It makes no difference if voice language is english or german it is not played. 
On the Transmitter (Horus) it works.

**Comment by kilrah** [comment]
That's intended, annoying to hear it everytime and you don't really need to brag when you're in front of your PC

**Comment by rcbebo82** [comment]
Ok, i understand makes sense 8-)
