### ISSUE TITLE
Small bug - custom 2 point curve overshoots values to select.

### ISSUE THREAD

**Issue by JapieG** [opentx/opentx#4222]
When i create a custom curve on Horus n360:

Type: Custom
Count: 2pts

When i want to select a value for the Y axis it overshoots the values when i try to select it with the rotary encoder.  I know it is unwanted to change x value on 2 point curve. But the way it works now is a bug i think :-)

Video:
https://www.youtube.com/watch?v=UVnQeREYf-0

**Comment by projectkk2glider** [comment]
True, two point custom curve should not even exist. I wonder if the same bug is also on 2.1?

**Comment by kellybyrd** [comment]
Is this something a new-to-the-project dev could pick up as his first bug? Or is there a bunch of history and context required here?

**Comment by projectkk2glider** [comment]
Should be fairly easy. If you are luycky you just need to adjust the min value based on curve type here https://github.com/opentx/opentx/blob/next/radio/src/gui/480x272/model_curves.cpp#L135

**Comment by kellybyrd** [comment]
Ok, I can repro this and I finally underatand @projectkk2glider's comment that "two point custom curve should not even exist." because you would solve that problem with a standard two point curve, like I do for a curve applied for volume control on a slider. Thanks for being patient, I'll dig in now.

**Comment by projectkk2glider** [comment]
Go ahead with your idea.

**Comment by kilrah** [comment]
Can be solved at editing time, when you change number of points to 2 type gets set to standard, when you change type to custom if number of points is set to 2 set it to 3. Ideally... do the same in companion :)

**Comment by kellybyrd** [comment]
I've got a PR out for just skipping the X editing. This is what the current Taranis code does in the simulator, so I followed that example.
