### ISSUE TITLE
Taranis X9D+ won't bootload

### ISSUE THREAD

**Issue by Dutchy-79** [opentx/opentx#4226]
Hi Guys,

My Taranis X9D+ won't start in bootloader mode when i push the bottom trims in and then turn on the TX
This way I can't connect to Companion to import a model file a friend gave me.

Any suggestions?

Companion 2.2.0.N360
OpenTX opentx22-5e00436-multi-2016-12-28-x9d+.bin  from http://plaisthos.de/opentx/

Thanks,

Jasper

**Comment by kilrah** [comment]
That file indeed has a broken bootloader.
