### ISSUE TITLE
Companion 2.2 simulator too big for 1280x800  screen.

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx#4229]
When trying to use the Horus simulator on 2.2 RC8, the screen does not completely fit on a 1280x800 screen.  I've included a picture of the screen so you can see how much is missing.

This is on Ubuntu 16.04 32 bit.
![screenshot_2017-01-13_21-04-27](https://cloud.githubusercontent.com/assets/2614846/21952884/57481f46-d9d4-11e6-87ac-0df45523dfcc.png)

**Comment by mpaperno** [comment]
Fixed by #4154 (will be included in next release).
