### ISSUE TITLE
Suggestion - Change app name on Mac from "companion" to "OpenTX Companion"

### ISSUE THREAD

**Issue by DIYglenn** [opentx/opentx#4279]
It's confusing when it's been a while, and I want to open OpenTX companion, so I search for "open" on my Mac, but nothing. The app is just called "companion".

Also, it doesn't have the version attribute set, so you cannot see which version you have installed.

**Comment by schwabe** [comment]
![image](https://cloud.githubusercontent.com/assets/1038539/22242333/3ca7a8e4-e223-11e6-900b-6989b3639c94.png)

In OpenTX 2.2 this already done. I am not touching the cmake 2.1 build script

**Comment by schwabe** [comment]
Renaming of 2.1 binary will probably not happen (I suggest to rename it locally) and for 2.2 it is already fixed, so I will close this as fixed in 2.2 and wontfix in 2.1

**Comment by DIYglenn** [comment]
Hey, that looks great! 
Thanks, I did not know.
