### ISSUE TITLE
Prevent Lua from allocating all heap memory

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#4284]
We need to limit the amount of heap memory that Lua allocates on Horus. 

Currently there is no limit other than the amount of the actual physical memory size. So when bogus Lua script uses up all memory, the rest of the firmware that also uses heap (like model images) will have problems working. The user interface will be affected.

The Taranis is not affected, because it doesn't use heap in other parts of firmware.

Proposed solution:
 * keep track of all heap memory used up by Lua and limit that number to something less (lets call it **system reserve**) than the actual max heap size. 
 * do not forget to count all memory allocations done by Lua scripts that are not counted by the Lua, like bitmaps.

Open questions:
 * how big should system reserve be?
 * what to do to Lua when our calculation shows excessive memory usage. We have two independent Lua states one for widgets/themes other for mix/function/standalone scripts. How to decide which script to kill or even which Lua state. Tracking of Lua memory usage per script is not possible (I think), we can only get the memory usage of the whole Lua state.

**Comment by kellybyrd** [comment]
Which to kill? Fun/Hard problem. The OOM-Killer on Linux has a similar problem. It tries to kill things in order of freeing up the most memory and which are least important to the system, to do this it scores each process. If OpenTX doesn't have per-process metrics, can we make some guesses which state is least least important or which state is more likely to use more RAM? 

Just guessing, but widget/themes seem like they would fit both of these criteria. They're supposed to be just drawing things on the screen, and it feels to me like they're more likely to contain bitmaps.
