### ISSUE TITLE
OpenTX Companion 2.2.0 RC9 (N361) Keyboard functions don't correspond to keymap

### ISSUE THREAD

**Issue by floaledm** [opentx/opentx#4289]
F3 brings up the joystick configuration and F4 the telemetry simulator. The rest works as it is supposed to...
![image](https://cloud.githubusercontent.com/assets/9093438/22313934/b353b51c-e324-11e6-8fb4-b3bce6a92cd7.png)

**Comment by mpaperno** [comment]
Fixed the help text, thanks for report.  The correct shortcuts can be seen in the RC version in the tooltip of each individual button.
