### ISSUE TITLE
HORUS - add MP3 Player

### ISSUE THREAD

**Issue by dk7xe** [opentx/opentx#4294]
FrSkyOS on Horus is having a MP3 Player.
Please add this functionality to OpenTX as well.
This is useful if you fly a coreography and like to keep tricks in sync with a certain background music.
Or just for having some fun at the field ;)

**Comment by kilrah** [comment]
We use the sound chip differently from FrSky OS, so can not implement MP3 decoding. 

Just convert your files to WAV.

**Comment by dk7xe** [comment]
Ok, if it is not possible at all to use MP3 i'd like to reduce the scope to:

Audio files to be stored as WAV on separate folder independent from language e.g. SD card /MUSIC folder.

Functions should be made available to

    start certain audio file.
    stop audio file.
    pause audio file / and restart from same point again.
    jump to next file.
    jump to previous file.

Thank you!
