### ISSUE TITLE
Companion 2.2-RC9 Saving in .otx removes unused models and renumbers following models

### ISSUE THREAD

**Issue by jtaylor2** [opentx/opentx#4295]
Companion 2.2-RC9 Radio X9D
I don't know if this is a bug or "working as designed" but if there are any unused models (gaps), saving in .otx format removes the unused models and moves all models after that up to fill those slots (changing the model numbers accordingly).  Saving in EEPE maintains the model numbers as they are on the transmitter as it always has.
![capture](https://cloud.githubusercontent.com/assets/6879281/22331905/ffa24916-e39b-11e6-9f67-aec87b44b714.JPG)

**Comment by projectkk2glider** [comment]
This behavior is  needed for Horus, but should not be used for other radios.
