### ISSUE TITLE
VS15 Debug builds of Companion RC9 Assert and Crash on save as a eepe to a new otx file

### ISSUE THREAD

**Issue by jtaylor2** [opentx/opentx#4300]
RC9 VS15 QT5.7.0 Companion debug build for X9D
This failure only occurs on debug builds, it does not occur on local release builds or downloaded RC9

I am getting a Companion "vector subscript out of range" assert and Companion crash doing a save as .otx of a .eepe. This only happens on debug builds, not release builds or downloaded RC9.

Steps to reproduce:
1.  Open an eepe in Companion.  It can be as simple as only one basic 4 channel model
2.  Select File-Save As and change type to .otx and a new file.
3.  Asset window will pop up and when dismissed Companion will crash

This appears to be caused by Categorized.cpp line 108 not checking that radioData.categories[model.category].name exists before trying to use it.
```
modelsList.append(QString().sprintf("[%s]\n", radioData.categories[model.category].name));
```
Adding a check to make sure it exists such as:
```
c:\temp>cat categorized.cpp.diff
diff --git a/companion/src/storage/categorized.cpp b/companion/src/storage/categorized.cpp
index 4b62db2..6ebb782 100644
--- a/companion/src/storage/categorized.cpp
+++ b/companion/src/storage/categorized.cpp
@@ -105,7 +105,9 @@ bool CategorizedStorageFormat::write(const RadioData & radioData)
       }
       int categoryIndex = model.category;
       if (currentCategoryIndex != categoryIndex) {
-        modelsList.append(QString().sprintf("[%s]\n", radioData.categories[model.category].name));
+        if (radioData.categories[model.category].name) {
+           modelsList.append(QString().sprintf("[%s]\n", radioData.categories[model.category].name));
+        }
         currentCategoryIndex = categoryIndex;
       }
       modelsList.append(QString(model.filename) + "\n");
```
corrects the problem, but I don't know enough about the code to know if this is the proper way to fix it.

[assert.eepe.zip](https://github.com/opentx/opentx/files/733269/assert.eepe.zip)
![capture1](https://cloud.githubusercontent.com/assets/6879281/22345966/474b9270-e3d0-11e6-81e9-227c27291c3a.JPG)

**Comment by projectkk2glider** [comment]
Should be fixed by #4308, no categories on Taranis.
