### ISSUE TITLE
2.2RC9 Taranis lcd.getLastPos() issue

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#4310]
in lua, if you display a number using RIGHT alignment then do a getLastPos() - this does not return the right hand position of the written number but the left. So here's some code to demo this:

lcd.drawNumber(61,10,getValue("Cmin")*100,MIDSIZE+PREC2+RIGHT)
xposCons=lcd.getLastPos()
lcd.drawText(xposCons,9,"c-",SMLSIZE)
lcd.drawText(xposCons,15,"min",SMLSIZE)

in RC8 this displayed the same as in 2.1 with the c- and min aligned after the displayed number, but in RC9 it displays c- and min on top of the number left aligned with the number

**Comment by mpaperno** [comment]
I see the same thing in my Lua scripts here.  @3djc  I think it started happening after your updates to the fonts/display (since RC8).  Also the `MIDSIZE` period is now quite large  :)  (larger than `DBLSIZE`)

**Comment by mpaperno** [comment]
Before:
![screenshot-1](https://cloud.githubusercontent.com/assets/1366615/22383322/45d6f2f0-e497-11e6-9eb6-f51620c6cfcf.png)
After:
![screenshot_17-01-27_13-47-13](https://cloud.githubusercontent.com/assets/1366615/22383407/a4bb9d98-e497-11e6-8ad6-68fbdd1f82fb.png)

**Comment by projectkk2glider** [comment]
Might be caused by fixes in #4157 and is probably intentional. @3djc will explain.

**Comment by 3djc** [comment]
There two different aspects to this.

YES, numbers and text drawing routine have been streamlined and will not produce the exact same results as RC8. There where bugs  and issues when unusual combination of attributes where used. All of that has been fixed, and the result is that you screens might look different, sometime by a pixel or two, but in several case, the difference can be significant (XXL+RIGHT for example).

The other one is lcd.getLastPos(). If you write RIGHT, the position you give to drawNumber is what you call your right hand position (61 in your example). It is logical that lcd.getLastPos() gives you the side you don't already know, the left one.

@Max, raise a good point about MIDSIZE dot, I'll have a look

**Comment by mpaperno** [comment]
Are you saying `getLastPos()` returns different results based on how you aligned the last draw call?  Or it will now always return NOT the last position (the left/top-most one where it started drawing?) ?  😕  Seems like a major "feature" of getLastPos() was that it was consistent...

**Comment by 3djc** [comment]
Well, my understanding is that getLastPos() is there to give you an information you don't already have: where did your writing end, because depending on the fonts,.. a string pixel size will be different. If you align RIGHT, what is the leftmost position you reached ?

If you want to  do : ! speed : 500 you draw speed, then lcdgetpos and draw 500
If you want to do  : speed : 500 ! you draw 500 (right) then lcdgetpos and draw speed (right)

**Comment by mpaperno** [comment]
I see your point about how it may be useful in some cases to know the leftmost position, but then it should be a new function, `getStartingDrawPos()` or whatever.  Changing behavior of an established API function that has been around for several years, and is undoubtedly used in hundreds of scripts, is a bad call IMHO.  And above all a function like that needs to return consistent results.

Imagine I just called a drawing function from inside run().  I don't know where it drew what it drew or how it was aligned, and don't care.  I need to know getLastPos(), period.

**Comment by 3djc** [comment]
Btw, it was not a purpose full decision or even known change, just the consequence of rewriting the code cleaner.

**Comment by mpaperno** [comment]
Didn't realize that, sorry, thought it was intentional.  Can we change it back then?  :)

**Comment by projectkk2glider** [comment]
Well technically if you are aligning RIGHT then the left most (first) character is the last one. 

@mpaperno are you sure that current behavior is **different** from the 2.1, because every 2.2 release prior to this fix was broken - the default alignment for certain LCD functions changed in 2.2 and this made a  mess we are trying to solve here. @3djc worked hard to fix it, but there might still be some fixed needed.

**Comment by mpaperno** [comment]
Actually those screens are from 2.1, and right now I'm not sure if 2.2 RC8 had the same alignment problem, but I think it did.  I may have to install a fresh a fresh Windows RC8 to be sure (no LUA in Launchpad RC8 which works on my Mint).

This is from what I'm pretty sure is "stock" RC8:
![screenshot-2](https://cloud.githubusercontent.com/assets/1366615/22395474/b40e1192-e50d-11e6-9282-242e0378d496.png)

I could install some older RC versions to test, if that would help.

**Comment by 3djc** [comment]
In 2.1, you could not drawText RIGHT, number where right aligned, text left. You could left align numbers but that wasn't quite right.

I think getLastPos() is very misleading or imprecise, but as Max mentioned, as been there long enough to stay (a bit more). I'm proposing:
- create two new functions, returning respectively left and right of last written string/number
- alias getLastPos() to the one returning right
- phase out getLastPos()

**Comment by mpaperno** [comment]
That's true, the alignment attributes were a bit confusing/quirky in the older versions.  But I guess we learned to live with them.  :)

I like your proposal.  I think it's a good way to transition to a newer API, even though it's annoying keeping old stuff around.

**Comment by athertop** [comment]
@3djc - totally agree with your suggestion. Will certainly help my scripts moving forward. Many thanks.
