### ISSUE TITLE
RC9 361 on X12S beta - Backup Radio to File

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#4312]
RC9 361 on the X12S beta "Backup Radio to File" just displays progress bar with no progress.

**Comment by projectkk2glider** [comment]
This was not yet implemented

**Comment by MIKE-DAILEY** [comment]
Would it be a good idea to add it to the change log so folks know it is not implemented yet in Companion support for the X12S.

**Comment by kilrah** [comment]
They'll see when they click it, a message box has been added.

**Comment by MIKE-DAILEY** [comment]
Good idea!  Thanks.

**Comment by raphaelcoeffic** [comment]
How is this feature actually different from the normal "read models"? Should it save the firmware used as well? Or anything else?

**Comment by kilrah** [comment]
It does not go through the companion import/export layers so makes a true backup without the risk for a potential bug in companion to modify/corrupt the data.

**Comment by raphaelcoeffic** [comment]
@kilrah ok, makes sense from a technical point of view, but as a user, I never really understood that feature. Considering what you've just explained, is there any point at all implementing that feature for the Horus? For my part, if I want to be sure, I just backup the relevant SD card directories.

**Comment by kilrah** [comment]
No user knows what "the relevant directories" are... 
It's not a main feature but a convenient troubleshooting tool that's been used many times to get people to send us unmodified data to catch companion bugs.

**Comment by raphaelcoeffic** [comment]
@kilrah ok, thanks for the explanations. So basically, this is about copying the correct files (`RADIO/*` and `MODELS/*`) and zipping them together into an OTX file? Or some other format?

**Comment by kilrah** [comment]
Exact
