### ISSUE TITLE
2.2 RC9: Accessing X7 thru companion possible?

### ISSUE THREAD

**Issue by dklueh79** [opentx/opentx#4314]
In the changelog of RC9 it's mentioned, that you could use companion again in order to write and get models, etc from the X7.
But: pressing the lower trims together during switching on, doesn't work any more. (White Screen)

What to do in oder to get a connection to companion? Same question for my horus

**Comment by 3djc** [comment]
This is not a support system, but a bug tracking one.If you have usage questions, please direct them to relevant forums, like http://openrcforums.com/forum/viewforum.php?f=45 or rcgroups.com

**Comment by dklueh79** [comment]
Thanx, I know. It's a bug. Connecting a X7 isn't possible

**Comment by dklueh79** [comment]
Thanx, I know. It's a bug. Connecting a X7 isn't possible . Flashing is possible, but during read out model data companion freezes

**Comment by 3djc** [comment]
Then you need to bring much more detailed evidence. (because it is possible)

**Comment by dklueh79** [comment]
Fw  update: no problems.
Connecting X7 after that and trying to download models: the status hangs up during 0 %. After about 5 min windows 7 ( 10, too)  wants to close companion during no reaction. 
I didn't try Horus.

**Comment by dklueh79** [comment]
Ah, no data within windows logs

**Comment by kilrah** [comment]
Do you get something on the X7 screen' Do you see drives on the PC? can you access them?

**Comment by dklueh79** [comment]
Yes, mass storage works.
But the X7 screen is blank white

**Comment by dklueh79** [comment]
OK; reflashing twice- one without, the next again with massstorage. Works, But companion shows, no connection- in the background you coudl see, that it was transfered....

OS in Win 7 SP1 fully patched
![2017-01-28 10_37_13-opentx companion 2 2 0n361 - radio_ frsky taranis x7 - profile_ taranis x7](https://cloud.githubusercontent.com/assets/6195999/22395712/054e52f0-e546-11e6-97a8-2942eaba8b8e.png)

**Comment by projectkk2glider** [comment]
See #4318 for explanation.
