### ISSUE TITLE
2.2 RC9 Horus. Old model (2.1 eepe) converted LS to L1

### ISSUE THREAD

**Issue by BurtPR** [opentx/opentx#4315]
The conversion of a model from OpenTX 2.1 format to to 2.2 format for the Horus seems to have a minor glitch. I was using LS as input to a mixer. In the converted file it became L1 as input to the mixer. 

**Edit by projectkk2glider**: see also description of another similar issue https://github.com/opentx/opentx/issues/4315#issuecomment-275899641

**Comment by BurtPR** [comment]
[EEPE etc.zip](https://github.com/opentx/opentx/files/736476/EEPE.etc.zip)

**Comment by BurtPR** [comment]
eepe to make it obvious.

**Comment by kilrah** [comment]
What source radio?

**Comment by BurtPR** [comment]
Taranis Plus

**Comment by projectkk2glider** [comment]
Similar to #4329 (conversion problems between Taranis 2.1 -> Horus 2.2 )

This is the text from there:
```
1. Launch Companion 2.1, type = Taranis
2. Create a model with potwarnings = MAN, all check boxes **dis**abled
3. Save file
4. Launch Companion 2.2, type = Horus
5. Open .eepe from step (3), note value of pot warnings:

Expected: all pot warnings disabled
Actual: LS and RS warnings enabled
```

**Comment by bsongis** [comment]
If imported using a Taranis profile, the import is good, it means it's the Taranis => Horus conversion which is bad
