### ISSUE TITLE
RC9 361 QX7 Switch settings for !Sx missing except for !SAup

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#4316]
QX7 361 on Ubuntu 64 in Companion.  I haven't tried nWIndows.
Only !SAup is shown as options in Special Functions, Logic Switches, Inputs and Mixes.

This means many conversions are made incorrectly also.

**Comment by kellybyrd** [comment]
This looks like a duplicate of #4288

**Comment by rdeanchurch** [comment]
You are correct, I missed that one.
Please delete or close as necessary.
