### ISSUE TITLE
RC 361 Horus. SF Reset Flight causes Control Warning dialog to check switch positions. Intended?   

### ISSUE THREAD

**Issue by BurtPR** [opentx/opentx#4317]
Special Function which Resets Flight causes Control Warning dialog to check switch positions. Change the SF to Reset Timer 1, no dialog appears.

Is this the intended behavior?

**Comment by kilrah** [comment]
Yes.

**Comment by projectkk2glider** [comment]
See https://github.com/opentx/opentx/issues/3422#issuecomment-275835263
