### ISSUE TITLE
companion 2.2 RC9 Taranis 9xd error message

### ISSUE THREAD

**Issue by benoit35690** [opentx/opentx#4318]
**Edit by projectkk2glider**: The issue is in models write to the radio, see last comments.

Hello with companion 2.2 RC9
Menu "Read/Write"
"Read models and settings from radio"
the models and settings are properly read but an error message is displayed

![copyecran](https://cloud.githubusercontent.com/assets/9080382/22395219/4f23cc0c-e537-11e6-8b3e-dba45564a15e.jpg)

**Comment by fred99** [comment]
I have also this trouble on RC9 but not on personnal compilations based on Next source of yesterday and days before

**Comment by projectkk2glider** [comment]
Should be fixed by #4291, please reopen if it still happens in RC10 (when it is released).

**Comment by dklueh79** [comment]
Update: Only a few writes are successful! Reading  works always. But 7 of 10 write-tries failed!

**Comment by projectkk2glider** [comment]
>But 7 of 10 write-tries failed!

Do you mean:
 * the radio actually did not get new changes
 * OR you got error in Companion only, but changes actually made it to the radio.

**Comment by dklueh79** [comment]
The X7 doesn't get the data. Companion says 100% ok. Like my screenshot

**Comment by projectkk2glider** [comment]
Our test show that it is working (at least now close to RC10), so wait until RC10 is out and reopen if issue remains.
