### ISSUE TITLE
dont allow taranis to power off if receiver is still connected.

### ISSUE THREAD

**Issue by geofrancis** [opentx/opentx#4324]
if you go to turn off the handset and its still connected to a receiver ie it still has rssi coming in,  it should warn that a receiver is still connected and prompt for a confirmation and make you confirm by holding a button for 5 seconds before turning its self off.

**Comment by mpjf01** [comment]
A sound added safety feature. I'm not sure that the five second delay is needed though, a prompt that needs to be responded to before the radio turns off ought to be enough. There are legitimate reasons for switching off with Rx still powered such as testing FS and that should not be made too difficult.

**Comment by kilrah** [comment]
Should be optional with a radio setting.

**Comment by geofrancis** [comment]
Make it optional but should be on by default.

**Comment by tubeme** [comment]
I think this should be well thought. Definitely optional. I might want to fly the take off and landing of my mission with the Horus but then once in the mission I might want to safe battery power of the RC and switch it off. The battery power of Horus seems like the one on X9E and we are in a big trouble with this bat pack inside.

Another issue here is how do we shut down the RC if opentx hangs and we have only soft button for power down? How do we reset the Horus in this situation?

**Comment by kilrah** [comment]
> Another issue here is how do we shut down the RC if opentx hangs and we have only soft button for power down? How do we reset the Horus in this situation?

Press for >10secs and release.

**Comment by geofrancis** [comment]
The percentage of people running auto missions and turning of the handset will be less than 1% so having it on would help the majority of people by making sure models are not left on.

**Comment by mpaperno** [comment]
The point of this would be what? Prevent accidental use of the power button?  Remind the pilot they're still flying?  Remind the pilot to shut down the model first?

Are any of these actual problems for people now?  Just asking...

Personally I'm not a big fan of soft-power switches.  Maybe I'm just biased because they never worked right for years and years, often have to go pull the battery in the end (or find that paper clip to reach the tiny little recessed Reset button).

I'm also wary of imposing changes on people in the interest of "safety."  We have quite a bit of that in the US...  ;-)

Most definitely optional please, perhaps compile-time option even (esp. if it's going to affect power circuit handling in the hardware), disabled by default.

**Comment by geofrancis** [comment]
Can you honestly say you have never left an aircraft on after switching of your handset?

**Comment by mpaperno** [comment]
Only on purpose.  Model goes off first, then radio (opposite of startup procedure).  Always.

**Comment by kilrah** [comment]
> Can you honestly say you have never left an aircraft on after switching of your handset?

Yes, even intentionally but it's not a problem because I make sure to configure my failsafes properly.

**Comment by geofrancis** [comment]
I heard that argument from a uav sales company, they disabled battery warnings, low battery failsafe, rc failsafe, everything apart from the main flight battery voltage on the handset. 

According to them it was up to the pilot not to get into trouble and none of the failsafes were needed because they had the voltage on the screen in front of them.

Surprise surprise the machine crashed 3 times, 3 times basic alarms or warnings would have saved it.

Not everyone has been doing this for years. I run multi rotor clubs so I see the beginners and all the mistakes they make.

What about just a beep before the handset switches off if rx is connected? So there is some indication that rx is connected without delaying shutdown?

**Comment by mpaperno** [comment]
That's a bit of a stretch between a low battery warning and the radio deciding when you're allowed to turn it off.  IMHO.

At the club I used to go to "back in the day" there was a simple rule that if you couldn't follow basic safety procedures after they were explained to you, you couldn't fly there.  Times change I guess.

> What about just a beep before the handset switches off if rx is connected?

That I like.  Perhaps even a special function that could be executed on shutdown if RSSI > 0 (or something like that).  Not sure if that's possible now w/out re-engineering the whole shutdown procedure, but perhaps.

**Comment by geofrancis** [comment]
Hmm that could be interesting, if you could use the handset shutting down as an input to trigger a special function . Then you could get it to do whatever you want before shutdown?

**Comment by bsongis** [comment]
I will take this one once 2.2 is released

**Comment by 3djc** [comment]
Proposing a way of operation;

Radio with bistable on/off (x9d):
1) Off switch 
2) Audio alarm + warning screen
3) model is turned off : immediate shutdown
4) ignore warning pushed : immediate shutdown

Radio with temporary POWER (Horus,x7, x9d,..)
1) start pushing POWER
2) audio alarm + display alarm
3) end of power off delay: warning screen with exit or enter
4) model turned off : off
    exit : back to normal operation
    enter  : off

**Comment by geofrancis** [comment]
Sounds good

**Comment by mpjf01** [comment]
So is it proposed that this still be optional - if so a compile time option or a SF or ?

**Comment by geofrancis** [comment]
why dont you put it in the handset menu as an option.

**Comment by 3djc** [comment]
If it gets in, it will be optional as some have voiced that  they do not want it. Currently, it's been prototyped as a radio setting

**Comment by geofrancis** [comment]
expanding this to changing models as well as powering off is a good idea.

**Comment by Bravedan** [comment]
If you change model leaving old model on, how it this going to be dangerous as with different Rx numbers the "old" model is incapable of running.  I'm confused!?

**Comment by schwabe** [comment]
@Bravedan  RX goes to failsafe which may have throttle on a non zero position.

**Comment by Bravedan** [comment]
Ah, right, thanks.  Personally I always set zero throttle so would not have that situation.

**Comment by 3djc** [comment]
Dealt with in #5126

**Comment by LapinFou** [comment]
So nice enhancement!!! I nearly lost a plane by inadvertently switching off my X9D+ (despite the button difference I confused the power switch with the elevator trim). I think it is a very good security feature.
Well done. 👍
