### ISSUE TITLE
N361 - Horus unstable after transferring data from Companion 

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#4326]
Horus, OTX & OTX Companion 2.2 N361

Steps

- Connect tx to PC in mass storage mode (tx on)
- Create or open a model in Companion
- Choose "Write models and settings to radio"

After the transfer, the screen goes blank. Tx still responds to key presses (throttle, switch warnings). No option but to switch off. Same after powering off and powering on, responds to key presses but can't see anything.

Tried it with two setups so far, same outcome. 
Deleting the Models and Radio folders (via card reader) restores normal operation. 
If I just set a model up on the transmitter then all is fine.

**Comment by kilrah** [comment]
Backlight is simply off, you can see the screen worls if you shine a light at it. That shouldn't happen...

**Comment by projectkk2glider** [comment]
I can trace this, remember I have hw serial :smile:

**Comment by kilrah** [comment]
No need, jsut missing default in companion and some backlight driver value in prod version

**Comment by projectkk2glider** [comment]
Cool, I tested reading existing setup and writing back with latest `next` and everything was OK (on first glance).

**Comment by tubeme** [comment]
I must add once I write the Presets from Companion to the Horus, everything gets very messy in the OpenTX. Once it changed the default color. The other time it just renamed the Presets. All weird things happen.

I even tried the following scenario. I reset the Horus with deleting the folders mentioned aboveby @RC-SOAR . Then I created 3 models in 3 different categories in the Horus. Then I read the presets with the Companion. Then I just write them back, nothing changed. Again Horus is messed up heavily.

**Comment by RC-SOAR** [comment]
Wow that was quick - thank you!
