### ISSUE TITLE
RC10: Multiprotocol status is not displayed in X9D simulator

### ISSUE THREAD

**Issue by dev-fred** [opentx/opentx#4332]
If I compile NEXT under MSVC, I got all informations under  External RF when Multiprotocol is selected:

![capture1](https://cloud.githubusercontent.com/assets/12371235/22403944/50e0359a-e626-11e6-879c-d77307e4a241.JPG)

This is not the case with RC10 and RC9:

![capture](https://cloud.githubusercontent.com/assets/12371235/22403938/2fe31024-e626-11e6-84f8-e703bb1e4aff.JPG)
:

**Comment by kilrah** [comment]
You compiled without enabling multimodule.

**Comment by dev-fred** [comment]
Sorry, but I am not sure to understand: 
I have compiled with -DTRANSLATIONS=FR -DHELI=NO -DGVARS=YES -DLUA=YES -DMIXERS_MONITOR=YES -DTIMERS=2 -DMULTIMODULE=YES -DHAPTIC=YES
and that works: 1st screenshot.
The simulator uses opentx-x9d-simulator.dll  which is installed by companion-windows-2.2.0N362, and that doesn't work correctly-> 2nd screenshot.

**Comment by kilrah** [comment]
That's because the simulators that we currently distribute as nightlies don't have the MULTIMODULE option enabled.

**Comment by dev-fred** [comment]
Ok," You compiled" is not me ; )

**Comment by kilrah** [comment]
Yep, given you mentioned you compiled next I understood "with RC9 and RC10" as you compiling those tags instead of next.

**Comment by 3djc** [comment]
And I'm unsure what would be the value of having it in the simulator. We need to have a middlepoint choice for simu

**Comment by schwabe** [comment]
well the simulator does not simulate the multimodule telemetry so it is indeed missing. We could replace that string with something that says "Multi module not emulated in simulator"  (too long but you get the idea) but it is a status only.

**Comment by dev-fred** [comment]
All other fieds, like in Companion, are accurate, it's a very good job:
![capture](https://cloud.githubusercontent.com/assets/12371235/22405110/a5cdd622-e63d-11e6-980c-e3a7b1c09c1b.JPG)

One days, when we will have options for the simu like the firmware, everybody will be happy, specially with local language.

**Comment by kilrah** [comment]
That will be solved the day simulators are compiled and downloaded on demand, and will thus match your profile settigns like the radio.
