### ISSUE TITLE
OTX2.2 RC10, Taranis X9D+: UAV image not loaded on very first start

### ISSUE THREAD

**Issue by RipperDrone** [opentx/opentx#4334]
Switching on the Taranis X9D+, I am getting the opentx splash screen, and then get a small openTX logo as a UAV image in place of the chosen copter image. When selecting another model and then re-selecting the former UAV, the image shows ok. Seems a problem of first boot/image loading...

**Comment by projectkk2glider** [comment]
Which OpenTX version?

**Comment by RipperDrone** [comment]
2.2 RC10. Sorry, will modify the title accordingly.

**Comment by ryphon** [comment]
I found this as well, however it only takes a couple seconds for me until it pops up with the correct photo.

**Comment by RipperDrone** [comment]
Funny, mine stays wrong image. I have to explicitly select a model manually to get the correct image.

**Comment by ryphon** [comment]
I notice that once it loads correctly, it never fails again. It only displays the wrong image on startup.

**Comment by RipperDrone** [comment]
Correct, but every time you hard switch the Taranis off and back on again, same error occurs.

**Comment by bsongis** [comment]
SD was initialized AFTER model load, which is bad
