### ISSUE TITLE
 Joystick values ​​invisible in companion, joystick immovable in simulator HORUS

### ISSUE THREAD

**Issue by 1Sven** [opentx/opentx#4336]
The nice future, a Joystick, usefull for special functions like a cam or  switches and so on is not supported. In mixers the values mean: " ??? " .  No values, are assignable, no inputs is definable.  The knob for Joystick is not movable.
I think a importand funktion for many users. How about, to aktivate this futures of the HORUS in companion and simulator?  
![image](https://cloud.githubusercontent.com/assets/25420478/22407359/5a5de4e8-e665-11e6-893c-54392337acf9.png)

**Comment by projectkk2glider** [comment]
The `???` is a bug, while the movable joystick in  simulator  is an enhancement.
