### ISSUE TITLE
In Companion 2.2.0 RC10, can't move a model to a new category 

### ISSUE THREAD

**Issue by kellybyrd** [opentx/opentx#4338]
In Companion on OSX, I 
-- Read models from my Horus.
-- Created a new Category called "Simulators"
-- Tried to either move or copy/paste a simple model called "USB" from the "All" category to the new "Simulators" category. In the "move" case, I saw no menu option and Drag-n-Drop didn't work. In the copy/paste case, copy seemed to work, but "paste" pasted a duplicate back in the "All" category even though I had selected a "New Model" to paste on top of in "Simulators

**Comment by projectkk2glider** [comment]
Already reported in #4224

**Comment by kellybyrd** [comment]
My bad. I was in a rush and forgot to check existing tickets. Thanks!
