### ISSUE TITLE
In Companion 2.2.0 RC10 on OSX, can't rename a Category

### ISSUE THREAD

**Issue by kellybyrd** [opentx/opentx#4339]
I couldn't find a way to rename a category in Companion 2.2.0 RC10 on OSX.

**Comment by projectkk2glider** [comment]
Added to #4224

**Comment by kilrah** [comment]
Just double-click on the category label.

**Comment by kellybyrd** [comment]
I can't check that right now, but I expected the context menu it show a rename function alongside the other options. Dbl-clicking isn't that discoverable. But, this is nitpick.

**Comment by bsongis** [comment]
You are right, it should be easy to add an entry in the menu

**Comment by kellybyrd** [comment]
I can maybe give it a shot, this would be part of the multi-bug #4224?
