### ISSUE TITLE
Poor display of Input and Mixer lines

### ISSUE THREAD

**Issue by projectkk2glider** [opentx/opentx#4341]
Using Qt 5.2.1 on Linux the display of Inputs and Mixer lines is truncated on the bottom (notice missing bottom part of `g` character).
![screenshot](https://cloud.githubusercontent.com/assets/5950438/22416269/ccf2662e-e6cd-11e6-99ea-5532537e6c59.png)

I will verfy later if the same problem exist with Qt 5.7.

**Comment by 3djc** [comment]
Doesn't seem to exist on Debian Jessie compile (qt5.3)
![image](https://cloud.githubusercontent.com/assets/5167938/22416564/967429aa-e6cf-11e6-84af-ac51cb24f0c2.png)

**Comment by projectkk2glider** [comment]
Nice, this means it will be difficult to solve...

**Comment by projectkk2glider** [comment]
Using Qt5.7 on the same base system is good( but notice different window colors because of non-native Qt installation)
![screenshot](https://cloud.githubusercontent.com/assets/5950438/22440216/d867f086-e732-11e6-8368-9400f199c416.png)

I also do not understand why icons on the buttons are **different** I am using the same theme - Yerico.

**Comment by mpaperno** [comment]
https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications

http://askubuntu.com/a/775519

**Comment by mpaperno** [comment]
Found this Qt5 "configuration tool" for setting/editing Qt app styles. 
http://www.webupd8.org/2015/11/configure-qt5-application-style-icons.html

Better to install from:
https://launchpad.net/~hda-me/+archive/ubuntu/qt5ct/+packages
or http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu/pool/main/q/qt5ct/

Or an easy build from source: https://sourceforge.net/projects/qt5ct/files/?source=typ_redirect

Qt5.7 does not support GTK3 themes (but 5.8 supposedly does). However the tool can also be used to configure a completely custom style for the default Qt Fusion theme, so any/all Qt apps can be affected at once.

> I also do not understand why icons on the buttons are different I am using the same theme - Yerico.

I still don't get that either, but I see the same thing.  Some icons or actions/shortcut icons are being matched/replaced by the GTK style, but only for some themes (eg. with monoblue they don't get replaced).  I'm sure there are some heuristics involved...
