### ISSUE TITLE
n362 Companion: shortcut Alt-S malfunction

### ISSUE THREAD

**Issue by strgaltdel** [opentx/opentx#4349]
Hello,

shortcut "ALT-S" seems to have some problems even in n362 / Windows.
Directly after starting companion, open an eepe (or .otx) and highlighting a model, ALT-S is without functionality.

Tested with Win10 & Vista, Horus and X9e Profile.

After some editing and simulating by right mouseclick, ALT-S starts operating.
Unfortunately, couldn't find any systematic "root cause" which brings this shortcut into live.

btw
"RELOAD LUA" not suported in horus Sim but in X9e?

regards
Udo

**Comment by projectkk2glider** [comment]
The current code only enables `Alt+s` shortcut when model is selected. This should be changed, since simulation can be run even without any model selected or even present.

**Comment by strgaltdel** [comment]
Just for clarification:
even if a model is selected, Alt-S isn't enabled.
![grafik](https://cloud.githubusercontent.com/assets/20392683/22454702/14809ba4-e788-11e6-9cdc-8d6525451dc8.png)
.. in this situation shortcut is without action.

As well i'm editing this model it wouldn't work directly.

Some minutes later, after some editing and simulation, it starts to run.....

**Comment by kilrah** [comment]
The print/cut/copy/paste buttons also stay greyed until after the window has lost/gained focus a few times.
