### ISSUE TITLE
RC10 N362 - User Interface Color - Enhancement    

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#4353]
The User Interface Color Enhancement was discussed many months ago.  Are you still planning sometime in the future to change the "User Interface" "Main Color" options we can change the secondary color that is automatically calculated now from the main color?  Right now as I adjust the main color near what I want the secondary becomes something I do not want.

**Comment by kilrah** [comment]
There's currently a bug with the automatically calculated colors.

Beyond that, themes were created so they could be modified or created by users, so we likely won't spend extra time on such details.

**Comment by projectkk2glider** [comment]
Before my commit:
![screenshot at 2017-02-01 09 47 42](https://cloud.githubusercontent.com/assets/5950438/22500460/cfc8fd16-e864-11e6-885b-4af5afa829ef.png)

After commit, default colors and some variants that now work properly:
![snapshot_06](https://cloud.githubusercontent.com/assets/5950438/22500486/efecc726-e864-11e6-9f82-ac235808033f.png)
![snapshot_05](https://cloud.githubusercontent.com/assets/5950438/22500492/f23265b8-e864-11e6-85c5-a48335a887bc.png)
![snapshot_04](https://cloud.githubusercontent.com/assets/5950438/22500495/f4b2515e-e864-11e6-8ec4-fb8dd7e11d35.png)

**Comment by bsongis** [comment]
Yes really better, thanks!

**Comment by MIKE-DAILEY** [comment]
Thanks!
