### ISSUE TITLE
Companion v362 saving model file to transmitter issue

### ISSUE THREAD

**Issue by Tbolt65** [opentx/opentx#4357]
When saving an *.otx file to transmitter from Companion 2.2 v362 some models have had the Internal Radio System is turned off.  Seems to occur when the RX is D16.  Models with D8 don't seem to be affected.   It doesn't appear to occur with all D16 models.  This has happened twice but the number of models affected is different.

**Comment by kilrah** [comment]
Radio type...?

**Comment by Tbolt65** [comment]
Horus.  Do you want my otx file to try it?

Sent from Yahoo Mail on Android 
 
  On Tue, Jan 31, 2017 at 2:06 PM, Andre Bernet<notifications@github.com> wrote:   
Radio type...?

**Comment by Tbolt65** [comment]
Tried to duplicate problem with a corrected file in Companion sent to Horus then copied back to Companion, but was unable.

**Comment by Tbolt65** [comment]
Could not duplicate
