### ISSUE TITLE
Q X7 - LUA drawScreenTitle error

### ISSUE THREAD

**Issue by gsimpson2g** [opentx/opentx#4362]
It appears the drawScreenTitle function is not working on OpenTX 2.2 for the Q X7.

Using the function returns the error:
"attempt to call field 'drawScreenTitle' (a nil value)"

**Comment by 3djc** [comment]
This function, along quite a few others, does not work with X7 reduced LCD size. I'll go through the list of functions before 2.2.0 and make sure they either work or the documentation mentiàon they do not

**Comment by gsimpson2g** [comment]
Thanks!!!!

**Comment by putimir** [comment]
@3djc Same error on 2.2.0 nightly on Horus X10S

**Comment by schwabe** [comment]
Well the docs say " Only available on Taranis X9 series". Horus X10 is not a Taranis X9
