### ISSUE TITLE
Q X7 LUA Rotary Left and Right events not working in telemetry scripts

### ISSUE THREAD

**Issue by gsimpson2g** [opentx/opentx#4366]
Playing around with the LUA scripting, I can't seem to get the EVT_ROT_LEFT or EVT_ROT_RIGHT events to work properly on the Q X7. All other events work, including the EVT_ENTER_BREAK when pressing the rotary down.

**Comment by 3djc** [comment]
I'll have a look tomorrow :)

**Comment by 3djc** [comment]
ok, did find some time. Those event are working perfectly both on simu and a real radio. Here is a small script you can test to demonstrate it . I'm closing this issue, please reopen if you fin contradicting evidence.
```
`x=0

local function run(event)
  lcd.clear()
	lcd.drawNumber(50,10,x)
  if event == EVT_ROT_RIGHT then
		x=x+1;
	end
	if event == EVT_ROT_LEFT then
		x=x-1;
	end
	return 0
end
return {run=run}`
```

**Comment by gsimpson2g** [comment]
That's really strange. I have the latest RC10 (N362) companion software/firmware, and even the simple script didn't work in the Simu or the Radio. It remains at 0.

**Comment by 3djc** [comment]
I flashed again to be sure I was on N362, but yes, the script works fine here

**Comment by kilrah** [comment]
What firmware options have you selected?

**Comment by gsimpson2g** [comment]
I have noheli checked. Trying the script as a telemetry screen. Currently editing up a script made for the X9D+ that allows BetaFlight settings to be changed via the telemetry page with the script running on it, but can't get the rotary working.

**Comment by gsimpson2g** [comment]
Ok, if I execute the script directly from the SD card, then it works 100% fine. When running the script as a Display Page, the rotary doesn't work.

**Comment by raphaelcoeffic** [comment]
That's a pity, as it rules it out as a telemetry script.

**Comment by kilrah** [comment]
Simply a bug.

**Comment by 3djc** [comment]
i checked on my X9E, it does not seem that we have those event either in that context

**Comment by raphaelcoeffic** [comment]
@3djc thx!

**Comment by Datospel** [comment]
"Ok, if I execute the script directly from the SD card, then it works 100% fine. When running the script as a Display Page, the rotary doesn't work."

Same for me on Q X7

**Comment by 3djc** [comment]
It has been fixed and will be available in next RC

**Comment by janekx** [comment]
Looks 2.2 final again not work !
