### ISSUE TITLE
 Add MULTI protocol for 9X radio

### ISSUE THREAD

**Issue by JFingerle** [opentx/opentx#4378]
OpenTX 2.2 RC10

With issue #2894 the new MULTI protocol was implemented. Sadly the new protocol is not available on 9X  radios.

Would it be possible to add this to the 9X OpenTX version? Maybe a compilation option can be added for this feature.

**Comment by kilrah** [comment]
Leaving it there and labeling as enhancement, but it's already been mentioned that none of the current developers were feeling like doing it so don't hope too much.

**Comment by schwabe** [comment]
Closing it as duplicate of #3812
