### ISSUE TITLE
Lua in Companion 2.1.9: lcd.drawPixmap() won't draw a 212 x 64 image.

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#4384]
lcd.drawPixmap will draw a 212 x 64 bitmap image if it's broken into two 106 x 64 images, but won't draw it as a single 212 x 64 image.

This produces a blank screen:
`lcd.drawPixmap(0, 0, "complete.bmp") -- a 212 x 64 monochrome bitmap`

This is a successful workaround to display a 212 x 64 bitmap:
`lcd.drawPixmap(0 ,0 ,"left.bmp") -- a 106 x 64 monochrome bitmap`
`lcd.drawPixmap(106 ,0 ,"right.bmp") -- a 106 x 64 monochrome bitmap`

This issue occurs in the 2.1.9 Companion simulator and in a Taranis radio.

**Comment by kilrah** [comment]
Yep, 106x64 is the biggest image you can load, memory limitation.
