### ISSUE TITLE
X7 N362 at Display trim values somtimes hidden at the corners

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#4394]
at Q X7 display only 
sometimes  trim values hidden at the corners

![2017-02-04_165643](https://cloud.githubusercontent.com/assets/6217896/22619726/5bc597aa-eafb-11e6-9d0a-c625dd8ee0f8.jpg)

**Comment by mpaperno** [comment]
I mistakenly referenced this issue (typo)... sorry! I fixed the commit comment so hopefully this issue will not actually be closed when that PR is merged.
