### ISSUE TITLE
Telemetry ratio for BtRx, A1, A2 

### ISSUE THREAD

**Issue by dev-fred** [opentx/opentx#4395]
I create A1 in entering 5V, but I have no way to enter directly the ratio 13.2 in the grey area: 
![capture](https://cloud.githubusercontent.com/assets/12371235/22619656/d378d5fc-eaf9-11e6-83f3-3589492dfe70.JPG)
But magically, if I kill the simulator window and run it again, the ratio appears:
![capture1](https://cloud.githubusercontent.com/assets/12371235/22619658/dc1de6fc-eaf9-11e6-9a7b-5f8e11164277.JPG)

What is the expected way to simulate BtRx, A1, A2 ?

Tested on NEXT of today but seen on 2.2.0N362

**Comment by dev-fred** [comment]
Add: If I edit A1, the value ratio is already 13.20 but it's not taken in account

**Comment by kilrah** [comment]
The ratio field is simply displayed for information, read form the sensor configured in the radio.

**Comment by dev-fred** [comment]
The sequence to get all sensors working is :
1-Open telemetry simu
2-Activate Discover new sensors in radio
3-Enter a value in simu
That's all, the sensor is created and the value is displayed in the radio

For A1, A2 and BtRx we have this sequence:
1-Open telemetry simu
2-Activate Discover new sensors
3-Enter a value in simu
Here the sensor is created and the value displayed in the radio is always = 0
3-Kill the telemetry simu window
4-Open telemetry simu
And this time we have the correct value

This sequence is a workaround to simulate A1 but I am surprise that you think it's a normal sequence.

**Comment by kilrah** [comment]
You're supposed to have telemetry already configured in your model, the simulator isn't really meant to create/discover sensors.

**Comment by dev-fred** [comment]
It's your assumption but there is no technical reason todo that way.
I have really appreciated to build LUA scripts based on Cels without any HW and this way works fine.
This way can be apply to all sensors excepted for A1, A2.
You have decided to grey the ratio and not to get the default configuration already there.
This workaround (kill/re-run simu) shows simply that we can work with A1/A2 also this way but it's not your choice .
Sorry but it's not very coherent.

**Comment by kilrah** [comment]
> there is no technical reason todo that way.

Sure there is - The telemetry simulator does not have the ability to adjust the ratio in the radio.
Then within companion any changes that are done in the simulator are lost, so detecting sensors there makes no sense.

**Comment by dev-fred** [comment]
However, I can adjust the ratio in the radio (after the famous kill/re-run) 
![capture](https://cloud.githubusercontent.com/assets/12371235/22621224/d6d49630-eb1e-11e6-906c-1cb2b2cf1468.JPG)
I imagine that ratio variable can be accessed by both side. 

Companion can't help for LUA, it's natural to remain in the simu

**Comment by dev-fred** [comment]
In fact, the real problem is not to be able to adjust the ratio, it's already configured at 13.2.
In order to use the telemetry simulator, we are supposed just to enter the voltage and get the same value in the radio (and the grey ratio should be at 13.2 like the radio and not at 0).
At the moment, to have this simple behaviour, we need to kill and re-run the telemetry simulator (which becomes complicated with the new docking system).
There is nothing to save in Companion which is unable to deal with LUA script, and creating sensors is so easy.
I can survive with the workaround I have found, and may be the way I use the simu is a corner case but I don't like your conclusion "so detecting sensors there makes no sense." 
This non sense works very well when dealing with LUA script and sensors from scratch without HW.

**Comment by kilrah** [comment]
>At the moment, to have this simple behaviour, we need to kill and re-run the telemetry simulator

Only the very first time when the sensor doesn't exist yet, or if you change the ratio while it runs... Once your sensor is there you don't need to restart.

> (which becomes complicated with the new docking system).

What? It's simpler than ever, just click twice on the telemetry simulator icon.

**Comment by dev-fred** [comment]
> What? It's simpler than ever, just click twice on the telemetry simulator icon.

Thanks for this tip, the double-click is much better than kill+re-run. 
My comment was just linked to the way I used the docking system and the visual effect produced  with the automatic resize when you have 3 windows docked and you kill one.
I like very much this new improvment 🥇 

In conclusion the workaround is easier to use with the new docking system and the double-click but idealy, A1,A2 should not behaves differently from other sensors when we enter a value.

**Comment by kilrah** [comment]
The problem is they actually DO behave differently technically from all different sensors, and the "reading ratio from the radio" is already a workaround to make it more convenient, otherwise you'd have to enter a raw 0-255 number.

**Comment by dev-fred** [comment]
I have also tested the case with a telemetry already configured. 
I enter 5V and 6V and nothing happens in the radio: 
![capture2](https://cloud.githubusercontent.com/assets/12371235/22624835/ab8831c6-eb87-11e6-8a8c-8137bd7fde3e.JPG)

I need to double-click on the icon telemetry to get value:
![capture3](https://cloud.githubusercontent.com/assets/12371235/22624841/e513ff24-eb87-11e6-8e60-ca16aa2326a4.JPG)

It seems that something is not iniatlized in A1,A2 when we check Simulation:
![capture5](https://cloud.githubusercontent.com/assets/12371235/22624874/8ab0a716-eb88-11e6-8c01-6219787696ed.JPG)

**Comment by kilrah** [comment]
Can't reproduce, for me if a sensor exists the greyed ratio fields always get populated when the simulator is opened. Please give exact way to reproduce.

**Comment by dev-fred** [comment]
OK, I can reproduce: there are 2 ways to enter in simulator.
1- From Edition of the model with the button: 
![capture](https://cloud.githubusercontent.com/assets/12371235/22625121/de9deb22-eb8d-11e6-911a-b92948dac1d9.JPG)
in this case, the simulator is directly openned on the model you are editing and the greyed ratio field is populated if  A1 is defined.
2- From this window:
![capture2](https://cloud.githubusercontent.com/assets/12371235/22625155/8baa51ac-eb8e-11e6-9cbe-e09446e669d2.JPG)
In this case, if the default model has no sensor and if you navigate with the radio to a model with sensors the greyed ratio field is populated after a double-click.
In the previous post, I have clicked on a model with sensors A1 and A2 defined but I have started the simulation using the way 2. This was not volonteer but this view is not coherent.

**Comment by kilrah** [comment]
All normal then. The ratio field is only populated when the window is opened, so if you change model you need to close/reopen to reload the value from the new model.

**Comment by dev-fred** [comment]
Yes, all normal.
Finally to avoid the double click, I can simply fill the values in Model Edit/Telemetry
![capture3](https://cloud.githubusercontent.com/assets/12371235/22625407/e3e0fa86-eb95-11e6-9e56-15ee77ca4e28.JPG)
This time the ratio field is populated when the window is opened without create/discover sensors.
