### ISSUE TITLE
Companion bug in activate fligh mode in Gvars tab

### ISSUE THREAD

**Issue by Pascal-m** [opentx/opentx#4408]
Hello,
I find a bug in companion V2.2N362
The flight phases displayed in the Companion Gvars tab are false.
In flight mode 0 it indicates the flight mode 1 and in flight mode 1 it indicates the flight mode 0.

Thank you
![fm1](https://cloud.githubusercontent.com/assets/5825739/22630429/517f6712-ebfa-11e6-8d3a-e9951a35283d.JPG)
![fm2](https://cloud.githubusercontent.com/assets/5825739/22630431/5782918e-ebfa-11e6-9e24-1ca4d7ecb3a1.JPG)

**Comment by mpaperno** [comment]
Confirmed, also in latest version.  Thanks for reporting, a fix is forthcoming.
