### ISSUE TITLE
Idea for timer - TH%

### ISSUE THREAD

**Issue by frobert0** [opentx/opentx#4413]
Timer function TH% for stick center position

Timer starts Stick <> 0, ???? (<-5%, >+ 5%)

For car or thrust reversal

**Comment by kilrah** [comment]
Apply a custom curve to an unused channel and set that as throttle source.

**Comment by frobert0** [comment]
Oh Sorry.
Thanks for the quick reply.
Works perfect

Robert

Am 06.02.2017 19:06 schrieb "Andre Bernet" <notifications@github.com>:
