### ISSUE TITLE
RC10 N362: It does not accept any file with more than 6 letters in the name.

### ISSUE THREAD

**Issue by tubeme** [opentx/opentx#4415]
I put my custom WAV files. If larger than 6 letter name than it does not appear in the track list.

With the JPG's if the file is with larger than 6 letters in the name, it is visible you can select it as model icon but then it does not load and the model stays with no image. 

Once I renamed the files to 6 letter names then no problem. Sounds load, jpgs are visible.

**Comment by kilrah** [comment]
The 6-letter limit is normal.


>With the JPG's if the file is with larger than 6 letters in the name, it is visible you can select it as model icon 

Where? In companion? On the radio? in the model setup page or in the SD manager?

**Comment by dk7xe** [comment]
I guess in companion at the model image file selection he means.
![model](https://cloud.githubusercontent.com/assets/3907200/22749095/773d746a-ee2c-11e6-94ca-04189db6bef0.JPG)
But in fact if the file name is longer than 6 char then the extension is cut off. 
in my Example "monster.jpg" was becoming "monster.jp"

**Comment by tubeme** [comment]
The JPG files are visible in the radio in the model setup page drop down. But then once selected nothing appears on the model screen.

**Comment by 3djc** [comment]
There is at least an issue on Horus firmware:
![image](https://cloud.githubusercontent.com/assets/5167938/22771747/205c67d8-ee99-11e6-951f-877f73fb6156.png)
