### ISSUE TITLE
RC10 N362 on Taranis Q X7: not possible to set a logical switch using telemetry value 'cells' as V1

### ISSUE THREAD

**Issue by JR63** [opentx/opentx#4416]
First of all: Many thanks for openTX on the brand new Taranis Q X7!

I found that it is not possible to set the telemetry value 'cells' (and maybe others) as V1 for a logical switch.

'Tmp1+' is the last telemetry value that could be choosen, after that the entry wraps around to '---'

![screenshot](https://cloud.githubusercontent.com/assets/8395202/22661553/0f71b260-eca6-11e6-828c-87a24ac2df25.jpg)

**Comment by 3djc** [comment]
Have you discovered Cells sensor, because I think it does work.

**Comment by JR63** [comment]
wow, fast response, thanks.

Yes I discovered it:

![cells_discovered](https://cloud.githubusercontent.com/assets/8395202/22661942/854af3f6-eca7-11e6-9f37-b2134f0eb8a9.jpg)

**Comment by 3djc** [comment]
Then I'll need your model file, I cannot reproduce it here

**Comment by kilrah** [comment]
Meh ;)

**Comment by JR63** [comment]
Many thanks, so my model file is not needed anymore?

**Comment by 3djc** [comment]
Nop, next RC will fix it

**Comment by JR63** [comment]
Cool, many thanks, good work!
