### ISSUE TITLE
Taranis X9D Plus vario issue on 2.1.6

### ISSUE THREAD

**Issue by SoaringJim1951** [opentx/opentx#4421]
I have a X9D Plus Tx and X4r receiver with a high precision vario. On V 2.0.9 the vario worked fine. Now I get no tone response to rising and falling. After finding the sensor The VSpd variable displays a sensible response and the Altitude readout also works fine. I have used the Variometer Special Function as usual and the tone settings are OK..
Is there a bug or is 2.1.6 incompatible with my Tx?

**Comment by 3djc** [comment]
Have you set your Vspd as a source for Vario in telem page ?

**Comment by SoaringJim1951** [comment]
Ah!

Thankyou. All fixed now.

Flexibility comes with a price!

All the best

Jim
