### ISSUE TITLE
RC10 (N362) Companion(HORUS)　:　SH strange behavior on logic switch

### ISSUE THREAD

**Issue by mizuta1951** [opentx/opentx#4426]
Only on Companion, dose not happen on HORUS.
Example : L1　SA↑ AND SH↓
If SA is ↑  and SH is ↑, when you start the simulator L1 is OFF (correct).
Once you move SH to ↓, L! is still OFF (wrong).
Then release SH to ↑, L1 becomes to ON (wrong).
After this L1 behave as SH is reversed.

**Comment by mpaperno** [comment]
I'm pretty sure this is fixed by cab26a6 .  But just to confirm, do I have it set up right?  This is after several restarts and multiple SH toggles, still shows correct.

![image](https://cloud.githubusercontent.com/assets/1366615/22722735/1682ee70-ed87-11e6-84c5-a4fd38b80865.png)

**Comment by mizuta1951** [comment]
Strange,,,
Different behavior.
I'm using Win-10, is that　cause something ?

![sh_down](https://cloud.githubusercontent.com/assets/6777468/22725002/2b9991aa-ee05-11e6-8658-f8b1cb3d0b33.jpg)
![sh_up](https://cloud.githubusercontent.com/assets/6777468/22725003/2fad6014-ee05-11e6-8220-c466d5655bf1.jpg)

**Comment by projectkk2glider** [comment]
The inverted SH problem is fixed by #4351

**Comment by mpaperno** [comment]
Ah right, I knew it was fixed somewhere along the line.  Anyway, confirmed works in latest version with same setup as @mizuta1951, so fix will be in next RC.
