### ISSUE TITLE
CANNOT READ TELEMETRY FOR CELL OR CELLS

### ISSUE THREAD

**Issue by miah9303** [opentx/opentx#4433]
The option to select CELL or CELLS can no longer be found in the Special Functions screen under Parameters. I am trying to get my Taranis to play the value of my cell/cells in my model by using a switch on the tx but this option no longer appears to be there. I can see Batt under the drop down menu but not Cell or Cells. I have also noticed that the drop down menu for Parameters is now very short. Under the Special Functions screen i have selected a switch, and action of 'Play Value' but cannot see Cell or Cells under Parameters. I am running version 2.1.9.

**Comment by kilrah** [comment]
Please read documentation about 2.1 telemetry, you need to discover sensors before you can use them.
