### ISSUE TITLE
Mixer script source selector only has a few telemetry values

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx#4438]
Mixer script source selector only has a few telemetry values. I only see 3 while i have about 20 sensors....

**Comment by kilrah** [comment]
Companion? Radio? What radio type? What version?

Please....

**Comment by RealTadango** [comment]
Horus, on the radio. Code from 03-02-2017

**Comment by 3djc** [comment]
Having a list of what values are available, and which not could also help debuging

**Comment by RealTadango** [comment]
I saw RSSI, RxBT, Tmp1
I missed RPM, ASpd, RB1/2 V/C, other custom sensors

Will test with latest next but did not see any changes related.

**Comment by RealTadango** [comment]
Same result with latest NEXT built

**Comment by projectkk2glider** [comment]
This is in fact not a bug. Any telemetry source can not be selected as a source for a mixer. You have to go trough inputs where you can use telemetry value as a source. This is how the system is supposed to work. Not sure how you saw RSSI, RxBT, Tmp1, none of them should be present in mixer source selection.

In any case I just verified Taranis and Hours in current (ee43d3fb971aef5295ea70a50dac9e94b74b0bdf) Companion and I see no problems.

**Comment by projectkk2glider** [comment]
Reopening, I misread, the issue is about `Lua mixer scripts`.

**Comment by projectkk2glider** [comment]
Confirmed in Companion Horus simlator

**Comment by RealTadango** [comment]
I just noticed it jumps to --- after the 3th sensor but with only rxbatt and rssi it remains at the last (as it should) so the bug is not missing sensors in the selection but an error in the selector itself now allowing to select a sensor....

**Comment by kilrah** [comment]
Just wrong type since there are now >256 possibilities in the source list. Being fixed.

**Comment by RealTadango** [comment]
Solution works fine :)
