### ISSUE TITLE
Issue with battery-bars and percent with 2.2.0N362 (3e00d016) on Horus

### ISSUE THREAD

**Issue by firstlily** [opentx/opentx#4441]
With fully charged transmitter battery, the meter in the upper-right corner only shows three out of five bars. I know I can change the battery-range showing on that meter to make it more full, but felt it was odd.  So I added the charge-percent meter and voltage to the top of the screen.  It only goes to 55% on a full charge.  Why is this, and can this be adjusted with a battery re-calibration?  Also, it shows more than a volt over the 9.6 volts that the stock battery pack is supposed to hole; is this a hardware issue or OpenTX?

**Comment by projectkk2glider** [comment]
Please ask this on forums, this looks like the setup problem. For example full pack voltage is over 11 volts!
