### ISSUE TITLE
Lua getModule() function should also return module mode.

### ISSUE THREAD

**Issue by mrpraline** [opentx/opentx#4444]
Currently the getModule() function returns only the RF protocol, not the RF mode. The value that is currently returned for rfProtocol is 0, regardless if the RF mode is OFF or any other value. In companion getModule(x).rfProtocol always returns 0,  I don't know what happens in a real transmitter without an external module.

As a consequence, it is currently impossible to determine if a module is actually transmitting and thus what channels  are physically being transmitted to the model. Adding the mode to the result table would solve this. 

Background:
I want to create a one time script to reorder the physical outputs on the receiver. For that only the channels that are actually being transmitted are of interest. The user should not be able to choose other channels and also limiting the amount of channels will greatly save screen space in most circumstances.

**Comment by 0815Creeper** [comment]
The RF protocol has apparently been renamed to subType but still does not match the documentation of model.get/setModule(): It reads 1 for D8, 2 for L12 and 0 for anything else (including OFF, which should be -1 according to doc...)

**Comment by kilrah** [comment]
There are now so many possible combinations and values for module settings including things that are not known until a receiver is connected and queried, so it's almost impossible to keep such a function at all.
