### ISSUE TITLE
lcd.drawLine(...) gives wrong result

### ISSUE THREAD

**Issue by floaledm** [opentx/opentx#4449]
For the 212x64 resolution, that was corrected: https://github.com/opentx/opentx/issues/2034

But it's not for the 128x64 and 480x272 resolutions.

**Comment by floaledm** [comment]
Awesome. Looks good. Thanks guys!

**Comment by projectkk2glider** [comment]
Just for reference, on 128x64 lcd before the fix:

![lcddrawline_128x64](https://cloud.githubusercontent.com/assets/5950438/23013589/957285ec-f42b-11e6-9422-619baba47302.png)

after:
![lcddrawline_128x64](https://cloud.githubusercontent.com/assets/5950438/23013596/99d77e1c-f42b-11e6-8ece-44e50ccd1c0d.png)
