### ISSUE TITLE
Companion 2.2 won't run on Windows Vista

### ISSUE THREAD

**Issue by rgs2010** [opentx/opentx#4465]
Companion 2.1.9 runs on my Windows Vista laptop just fine but 2.2 give some type of runtime error and won't load.

**Comment by mpaperno** [comment]
You likely need the MSVC 2015 runtimes DLLs if you don't have them installed yet:  https://www.microsoft.com/en-us/download/details.aspx?id=48145  (SP2 required)

If that's not it, please post the actual error you're getting.

**Comment by mpaperno** [comment]
Closing for now, please reopen if still an issue.
