### ISSUE TITLE
Supplementary (stick-)switch not supported

### ISSUE THREAD

**Issue by 1Sven** [opentx/opentx#4472]
Inside the Horus are 2 ports for stick-switches. For the time they are not supportet in openTX. A switch on the sticks is a very useful thing! I think, it’s more than an nice future...

**Comment by kilrah** [comment]
Additional inputs for X7 and Horus will have to wait for next eeprom change (2.3?) to be supported.

**Comment by 1Sven** [comment]
This will take a long time, I think... , isn't it a lttle milestone?

**Comment by kilrah** [comment]
Inserting items in the list would shift all existing setups, so can only be done when a conversion is implemented, which is on major versions.
