### ISSUE TITLE
LUA Script syntax error on RC10 (works fine on RC9)

### ISSUE THREAD

**Issue by slawek89** [opentx/opentx#4473]
It is some kind of bug that Betaflight LUA script dont work on OTX 2.2 RC10? Everytime show syntax error.
On RC9 everything works fine.

**Comment by 1Sven** [comment]
The script works on Horus. I had today tested.

**Comment by kilrah** [comment]
What radio?...

**Comment by slawek89** [comment]
Sorry, it is for taranis.

16.02.2017 8:41 PM "Andre Bernet" <notifications@github.com> napisał(a):

**Comment by mpaperno** [comment]
More details?  Or can this be closed?  

Personally I have no idea what "that Betaflight LUA script" entails or why anyone would assume otherwise.

**Comment by kilrah** [comment]
Especially since there are several variants of the script floating around.

**Comment by slawek89** [comment]
Sorry for long time reply. This issue can be closed.
It turns out that Betaflight LUA script was divided to two files and they has to be in proper localisation.

**Comment by 3djc** [comment]
Thanks for the update !
