### ISSUE TITLE
Bluetooth as simulator-connection, because BT not available

### ISSUE THREAD

**Issue by 1Sven** [opentx/opentx#4476]
At every time it is necessary connecting a USB-cable to the computer. In Horus is a simple BT-module. With this enabled, a wireless connection may be possible. Of course there is a lot and complicate work for does it. Isn’t it a funny thing?

**Comment by 1Sven** [comment]
Please, do not close. This may be a funny thing... !!!

**Comment by kilrah** [comment]
There is no standard for Bluetooth joysticks, so it would need a load of driver development on the PC side to make it happen which is completely out of scope for OpenTX. 
If someone made that, then we could do our side.
