### ISSUE TITLE
USB joystick lag since upgrading to 2.2 firmware on Taranis X9Dplus

### ISSUE THREAD

**Issue by Enlightx** [opentx/opentx#4479]
Iv been using a lot of emulators and had no issues all input was smooth.
Since updating to 2.2 firmware iv found that USB joystick input is not smooth.
when moving throttle quickly you can hear input it sharp stepped and not smooth.
Smooth if you throttle slowley but sharp movements as its as its skipped steps and throttle is not smooth because of not getting the data quick enough to the pc?

is it a known issue or can someone test see if they have the same?

**Comment by projectkk2glider** [comment]
I would like to have a confirmation from another user before going into this.

**Comment by Mistale** [comment]
I'm having similar issues. Ive been using my X9d with Velocidrone simulator without a hitch, but after updating to 2.2, input seems to be stepped / unfiltered resulting in untunable copter in the sim.

**Comment by projectkk2glider** [comment]
I don't see any problem on Linux, please provide an example of the good and bad performance. Here is an example how it works on my system: https://www.youtube.com/watch?v=rNaxqF5JQUY

**Comment by Enlightx** [comment]
Is it possible to downgrade the flash? Then I could try on 2.1 and 2.2



Sent from my iPhone

On 6 Mar 2017, at 16:59, Damjan Adamic <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see any problem on Linux, please provide an example of the good and bad performance. Here is an example how it works on my system: https://www.youtube.com/watch?v=rNaxqF5JQUY

**Comment by projectkk2glider** [comment]
Only if you stored both the 2.1 firmware and radio/models settings. When flashing back 2.1 your 2.2 models will get lost since OpenTX only supports model conversion when going from old to newer version and not when going in opposite direction.

**Comment by projectkk2glider** [comment]
This might be Windows specific problem and that might explain why I don't see the problem.

**Comment by Enlightx** [comment]
Let me get it tested on a few other computers and older windows version

Problem seems to be rapid movements of sticks created lag. Think I might have a screen recording before I upgraded to 2.2 I'll have a look

Sent from my iPhone

On 6 Mar 2017, at 17:06, Damjan Adamic <notifications@github.com<mailto:notifications@github.com>> wrote:


Only if you stored both the 2.1 firmware and radio/models settings. When flashing back 2.1 your 2.2 models will get lost since OpenTX only supports model conversion when going from old to newer version and not when going in opposite direction.

**Comment by projectkk2glider** [comment]
Do you see the same lag in Windows Joystick calibration app?

**Comment by Enlightx** [comment]
Yeah same in calibration app . Tried recalibration but same effect also

Windows 10 64 bit

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by kilrah** [comment]
Can't seem to see an issue here on Win... feels no slower than another controller.

**Comment by projectkk2glider** [comment]
The only issue I see so far here is that actual USB joystick packets get send out every 50 - 60ms. Investigating why...

**Comment by projectkk2glider** [comment]
Test firmwares (English language, USB Joystick, 3 Timers, Lua):
 * Taranis http://downloads.open-tx.org/2.2//tests/opentx-x9d-lua-double-fix.bin
 * Taranis Plus http://downloads.open-tx.org/2.2//tests/opentx-x9dplus-lua-double-fix.bin

**Comment by projectkk2glider** [comment]
Test firmwares (USB packets sent every  10ms):
 * Taranis http://downloads.open-tx.org/2.2/tests/opentx-x9d-joystick-fix.bin
 * Taranis Plus http://downloads.open-tx.org/2.2/tests/opentx-x9dplus-joystick-fix.bin

@Enlightx Try one of these firmwares (depending which Taranis you own) and tell me if it is any better.

**Comment by Enlightx** [comment]
Hi
Tested on the X9 Plus

Completely fixed! thank you

Throttle is now super smooth when rapid movements occur.

I did take videos to show difference if they are any use to you.

Thanks again
Luke

**Comment by projectkk2glider** [comment]
Thanks for the report, videos are not needed.
