### ISSUE TITLE
T5 / T6 Horus => Companion transfers that sources as "Lua1a" 

### ISSUE THREAD

**Issue by Casichispea** [opentx/opentx#4480]
if you have created a model in the Horus using  T5 as source, when you copy it with companion 2.2 into the computer, the process changes the source "T5" and appears  "LUA1a".

**Comment by Red-Devil74** [comment]
As T5 and T6 are not present in Companion, I assume it defaults to the first entry in the list "LUA1a". I have the same issue. After transfer from Horus to Companion it shows 3 question marks in the mixes tab. Only after opening said mix is appears as "LUA1a". (hope this info helps a bit...)
![image](https://cloud.githubusercontent.com/assets/23432540/23231635/cc56e4dc-f948-11e6-8d31-548809394068.png)
![image](https://cloud.githubusercontent.com/assets/23432540/23231654/e446cd5a-f948-11e6-8de6-72c98044d84b.png)

**Comment by Red-Devil74** [comment]
Is this not fixed as per remark in buglist "Horus misc issues #3393"?

**Comment by kilrah** [comment]
No that referred to radio firmware only, still missing in companion
