### ISSUE TITLE
GPS displayed on Taranis is  concatenated

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#4481]
Just received my first FrSky GPS sensor and hooked it up. Discovered this on telemetry sensors screen on OpenTx2.2rc10 X9D+ and then added GPS to a ('Nums') telemetry screen. This is what it looks like:
![](https://dl.dropboxusercontent.com/u/12131631/forum-links%28do%20not%20delete%29/22rc10GPSissue.jpg)

Note degrees are chopped off both lat/long

**Comment by 3djc** [comment]
Already fixed in next rc
