### ISSUE TITLE
Companion Horus : the jumping cat

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#4482]
Reproduce steps:

New window, new category, another ne w categry, create a model in the second category, run the wizard against this model, when finishing, the model jumps to the previous category

**Comment by LapinFou** [comment]
Jumping cat??
![JumpingCat](http://www.assisianimalhealth.com/files/cache/075d7e1b9e4f873045bce197705bd164_f184.jpg)

😄

**Comment by LapinFou** [comment]
Jumping cat??
![JumpingCat](http://www.somepets.com/wp-content/uploads/2014/07/Jumping-cats22.jpg)

😄
