### ISSUE TITLE
can't change channel order on X7 2.2.0N362

### ISSUE THREAD

**Issue by nathantsoi** [opentx/opentx#4490]
Just updated my Taranis Q X7 to rc9 and I can't set the channel order under radio setup... It is possible this is due to operator error...

Here's what I see: https://goo.gl/photos/uSSh7ZzybMdf5B167

**Comment by projectkk2glider** [comment]
Please try with RC10 it might already be fixed.

**Comment by 3djc** [comment]
Why do you update to RC9 when RC10 as been out for a month or so (and does fix the issue you are reporting)

**Comment by nathantsoi** [comment]
Ha. Thx guys. I'll update to RC10. Google fail :(

![screen shot 2017-02-20 at 11 13 31 pm](https://cloud.githubusercontent.com/assets/399770/23154358/3e4b491c-f7c2-11e6-86cc-45c35659ae56.png)

**Comment by nathantsoi** [comment]
Ok, just double checked and this was actually with, 2.2.0N362

(md5) efef1be8600f65cfff6b6cefc51b8c33  opentx-x7-lua-sqt5font-en.bin

so I think this could be a real bug?

**Comment by projectkk2glider** [comment]
Just checked in `simu`, appears fixed, @nathantsoi fix will be in RC11:
![snapshot_01](https://cloud.githubusercontent.com/assets/5950438/23155299/54d562b2-f812-11e6-9f68-4fd0ee2df188.png)

**Comment by nathantsoi** [comment]
awesome. thx @projectkk2glider!
