### ISSUE TITLE
Companion Inputs with assci symbols like Hearts or Smiles bellow line 30

### ISSUE THREAD

**Issue by Casichispea** [opentx/opentx#4495]
If you click on these inputs with the symbols, all your inputs will be deleted or modified.

![screenshot 2017-02-22 12 19 04](https://cloud.githubusercontent.com/assets/24463388/23209437/820067b8-f8f9-11e6-8dea-66dd80117096.png)

**Comment by kilrah** [comment]
Already fixed for next release.
