### ISSUE TITLE
X7 missing telemetry sensors in logical switch setup

### ISSUE THREAD

**Issue by SPlissken** [opentx/opentx#4496]
When selecting V1 or V2 inputs for logical switches on an X7 with OpenTX 2.2.0 RC10 (N362) there are no further sensors listed after 'Tmp1' when scrolling all the way through or going via context menu.
I was looking for 'RPM' and it just wasn't there.

Logical switches can be set from Companion with these missing sensors, and they work, but the name does not show on the TX when viewing the logical switch configuration.

I found this whilst trying to setup an RPM alarm and this is using FrSky D8 telemetry.

**Comment by 3djc** [comment]
Fixed in next RC
