### ISSUE TITLE
companion read model doesn´t work any more

### ISSUE THREAD

**Issue by Casichispea** [opentx/opentx#4500]
everything has been working well and suddenly 
![screenshot 2017-02-23 19 31 30](https://cloud.githubusercontent.com/assets/24463388/23273373/117570f4-f9ff-11e6-8478-88c5e56c34e1.png)

**Comment by 3djc** [comment]
Well if it worked ok, it means likely that the error is not in the code. Have you been removing the SDCard ?

**Comment by Casichispea** [comment]
Windows could read the SDCard w/o problems. I have restart computer, Horus, with SDCard in, out....nothing help. At the end I have written an old version of an otx file in the horus and that has worked after that companion can read the models in Horus normally again.   I have lost all the changes made directly in the field yesterday in the flyfield.... Horus has been working normally during the problem with companion.

**Comment by kilrah** [comment]
Did you save the card contents before restoring the old file? The only waywe could investigate is if you supplied a copy of the problematic data.

**Comment by Casichispea** [comment]
I have synchroninized the SD Card and it worked. Could you find anything in the SD images on computer?

**Comment by kilrah** [comment]
Only if what you have is still in the "broken" state.

**Comment by Casichispea** [comment]
yes it is

**Comment by kilrah** [comment]
Then you can zip the whole content and upload to a service like www.filedropper.com, and post the link here, we'll have a look.

**Comment by Casichispea** [comment]
http://www.filedropper.com/n362-kopie

**Comment by Casichispea** [comment]
The error can be reproduced. It occurs when I writte some wav files directly in the SD Cart in Horus using the file explorer and I did in this way because if I writte the sound files in the SD image in the computer and this files are used by a modell, when they are synchronized the are corrupted and transformed in a file with 1K size.

**Comment by kilrah** [comment]
That would suggest a card problem. Did you try another one?

**Comment by Casichispea** [comment]
the same again with another card and this is the order what I do:
1. I write some wav file in the Horus SD Card which are used by some models.
2. Synchronize the SD Card with companion.
3. Error comes when I try to read the models.
4 then I write and old otx file in the Tx SD Card and everything works fine again.

and the oposite direction

1. I write a wav file in the computer SD Card images.
2. Synchronize => in Horus SD are written a file with 1K size corruted

**Comment by Casichispea** [comment]
Before I had taken the new card and copied the old one in the new => same result
Now I had copy the SD Card content from Internet V2017-01-25 19:14	29M	 and started from cero. Everything seems to be Ok now.
