### ISSUE TITLE
Logging the flight mode

### ISSUE THREAD

**Issue by jfrickmann** [opentx/opentx#4501]
It would be really nice if we could record the flight mode in the log file.
Please, and thank you for OpenTX - it is awesome :-)

**Comment by projectkk2glider** [comment]
This can be solved with Lua mixer scritpt that reads current flight mode (`getFlightMode()`) and writes it to custom sensor (`setTelemetryValue()`) that is then logged.

**Comment by jfrickmann** [comment]
Thanks - looks like it is coming in 2.2, but not in 2.1?

**Comment by 3djc** [comment]
You have been given a way to do it in 2.2 without needing firmware change,

**Comment by powercycle** [comment]
jfrickmann,

Additionally 2.1.x seems a little dated.
What makes you need to stay with 2.1.x?

**Comment by jfrickmann** [comment]
As far as I know, 2.1 is the current version?

**Comment by kilrah** [comment]
Would be handled in #4166, FM could be a useful thing to add to a group indeed.
