### ISSUE TITLE
OpenTX 2.2.0N362 Multi Modul protocol 32 not work

### ISSUE THREAD

**Issue by profdrdenis** [opentx/opentx#4505]
OpenTX 2.2.0N362

Multi Modul protocol 32 (GW0008) cant selected. Work only to 31

**Comment by schwabe** [comment]
What remote, do you mean selecting in custom protocol? I am not sure I can follow.

**Comment by profdrdenis** [comment]
Hello,
the protocoll 32 (GW0008) is new maybe 1-2 days young. The complete list you see here:
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/Multi.txt
have a look than you understand what I mean.

Thanks

**Comment by kilrah** [comment]
Please detail whether you're referring to companion or radio. Current "next" status the radio do allow Custom subprotocols up to 63, but Custom doesn't even exist in companion.

**Comment by profdrdenis** [comment]
Hello,
before we talk wrong I talk from protocol not from Subprotocol. In Companion I count and have 29 last is "???" 

I start my topic about radio.

**Comment by schwabe** [comment]
@profdrdenis that "???" will be fixed by https://github.com/opentx/opentx/pull/4459

**Comment by kilrah** [comment]
> I start my topic about radio.

Then that's already fixed for next release.
