### ISSUE TITLE
Companion 2.2 N362 read models from Radio

### ISSUE THREAD

**Issue by profdrdenis** [opentx/opentx#4506]
When I read the models from my Frsky X7 the Multi Radio Modul protocol "Flysky AFHDS2A" is lost. All the other are there

**Comment by profdrdenis** [comment]
Me again
the same when you write and save it in Companion, leave models open again than protocol "Flysky AFHDS2A" lost.

**Comment by kilrah** [comment]
Already (hopefully) fixed for next version.
