### ISSUE TITLE
[MULTI] had support for more than 31 protocols

### ISSUE THREAD

**Issue by pascallanger** [opentx/opentx#4514]
Hi,
I got report that opentx only supports 31 rf protocols where the serial protocol supports 63. Er9x and ersky9x already supports this for some time.
Basically, the custom entry does not go over 31. I've published a new RF protocol gw008 number 32 a few days ago and opentx users can't access it.
Pascal

**Comment by schwabe** [comment]
Hm, 

it should support it. Maybe the users are using very old 2.1.x versions?

![image](https://cloud.githubusercontent.com/assets/1038539/23341373/8080de72-fc46-11e6-9abe-0581e4d1e3de.png)

**Comment by pascallanger** [comment]
OK so feel free to close this false issue.
Thanks for checking, Pascal

**Comment by pascallanger** [comment]
By the way have you tried to load the latest multi code and load the protocol gw008 32? It should blink forever if no quad is around. I think it's a good test to see if it works as it should.
Pascal

**Comment by powercycle** [comment]
I can confirm that custom choice goes to 63, and at protocol 32 for multi 1.1.6 using RC10, shows Protocol Invalid. 
As of today, the latest precompiled release is 1.1.6, so folks may not be recompiling from master.
