### ISSUE TITLE
Visual Studio 15 build broken by commit 4382e9fa2b for issue 3305

### ISSUE THREAD

**Issue by jtaylor2** [opentx/opentx#4522]
Companion (next) will no longer compile in Visual Studio 2015 after commit https://github.com/opentx/opentx/commit/3b149a22d16a4b9184f466fc7f12ea4382e9fa2b because of the use of the text "not" operator instead of ! in mixerdialog.cpp line 242 and  expodialog.cpp line 243
```
+    cb_fp[i]->setChecked(not cb_fp[i]->checkState());
```
Per https://msdn.microsoft.com/en-us/library/1k6w8551.aspx

"The not operator is the text equivalent of !. There are two ways to access the not operator in your programs: include the header file iso646.h, or compile with the /Za (Disable language extensions) compiler option."

I will generate a pull request to replace the text "not" operators with ! to correct the VS15 build.

**Comment by mpaperno** [comment]
Actually it should be 
```
cb_fp[i]->setChecked(!cb_fp[i]->isChecked());
```
