### ISSUE TITLE
Opentx RC10 Logical Switches on QX7 Missing Telemetry Items

### ISSUE THREAD

**Issue by dkuenzi1** [opentx/opentx#4532]
When trying to set up a logical switch using VFas and or Cell items these items will not appear as options in the V1 field even though all the other telemetry fields do show up in V1. Note that Vfas and cell are the 11th and 12th items in the list of 'discovered' telemetry items. Also, Vfas and cell ARE available to display on screens and seem to work properly there. 
Also, Vfas and cell are options for logical switches (V1 parameter) in Companion 2.2 but they disappear when uploaded to the X7. Hope this description makes sense

**Comment by kilrah** [comment]
Fixed already.
