### ISSUE TITLE
Heli TS - Mischer CYC1-3 Horus N362

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4545]
Hallo I cannot set in the Helipage under Collective Pitch a channel . If you scroll you end at TR16. But I miss setting CH1-16. To setup a CCPM Heli you need for example to set Pitch to CH11 to work with curves later.

Look the pictures and see what I mean
![pict3540](https://cloud.githubusercontent.com/assets/22581690/23529605/806773aa-ff9e-11e6-9c39-79eab4d84d2c.JPG)
![pict3542](https://cloud.githubusercontent.com/assets/22581690/23529603/8065b84e-ff9e-11e6-9ef8-80d6da8a7e64.JPG)
![pict3543](https://cloud.githubusercontent.com/assets/22581690/23529607/8079fb38-ff9e-11e6-8dca-b68e35ccf4d3.JPG)
![pict3544](https://cloud.githubusercontent.com/assets/22581690/23529604/8067533e-ff9e-11e6-8838-52ebcf098dba.JPG)
![pict3541](https://cloud.githubusercontent.com/assets/22581690/23529625/911ad7b4-ff9e-11e6-87b3-9528eb540149.JPG)

**Comment by projectkk2glider** [comment]
Looks like it works in Companion.

On the radio only the mixer channels that actually have something defined are selectable. So first create some mixes on CH11, then you will be able to select CH11 there.

![snapshot_07](https://cloud.githubusercontent.com/assets/5950438/23543044/9d16fe56-fff0-11e6-84c0-3498001f40a7.png)
