### ISSUE TITLE
Telemetry for the new Scorpion ESC Tribunus

### ISSUE THREAD

**Issue by Storchy1** [opentx/opentx#4546]
Is it possible to integrate the new Scorpion ESC Tribunus Telemetry?
I have asked Scorpion for the Telemetry Data Sheet and i got it.
Thanks a lot
[Tribunus ESC protocol description.pdf](https://github.com/opentx/opentx/files/815916/Tribunus.ESC.protocol.description.pdf)

**Comment by 3djc** [comment]
Well, you can't simply connect your esc to the receiver smartport. If you want your ESC telemetry, an interface (I mean a real physical board with a small cpu) will need to be build to connected to you 4,6,.. ESC on your craft, speaking their language, and to a single smartport to receiver speaking FRSky language.  Such an interface to a single ESC can probably be done at the flight controller level, but their developer would be better suited to respond to that question There is not much we can do at our end to replace that.

**Comment by Storchy1** [comment]
Thank you very much, 
i think i have found the little interface you are talking about.
[http://j-log.eu/s32/s32-de/scorpion-tribunus/](url)
This interface can understand Tribunus and can translate to Frsky SmartPort.
This can be closed
