### ISSUE TITLE
Spacing issue for DBLSIZE number on 128x64

### ISSUE THREAD

**Issue by floaledm** [opentx/opentx#4547]
Kind of a followup on #4540 

Looks like lcdDrawNumber() in lcd.cpp for the 128x64 display hasn't been updated to match the updates made for the 212x64 display (see #4157).

This results in display inconsistencies (shown using Companion 2.2RC10):
![untitled](https://cloud.githubusercontent.com/assets/9093438/23540546/8233aeac-ffa7-11e6-8087-fba745d8e1ee.png)
![untitled2](https://cloud.githubusercontent.com/assets/9093438/23540547/83508ca6-ffa7-11e6-8e1f-8fa38ccbb4e0.png)

The code I used to display this is:
`lcd.drawLine(0, 0, 0, 16, SOLID, 0)`
`lcd.drawNumber(32, 0, 332, DBLSIZE+PREC1+RIGHT)`
`lcd.drawLine(32, 0, 32, 16, SOLID, 0)`
`lcd.drawNumber(61, 0, 333, DBLSIZE+RIGHT)`
`lcd.drawLine(61, 0, 61, 16, SOLID, 0)`
`lcd.drawTimer(63, 0, model.getTimer(1).value, DBLSIZE)`
`lcd.drawLine(105, 0, 105, 16, SOLID, 0)`

**Comment by 3djc** [comment]
It is already fixed for RC11

**Comment by floaledm** [comment]
Thanks! Can I get the reference to the PR to take a look on how that was done?

**Comment by 3djc** [comment]
This PR is scheduled to go live before rc11, we are just debating some details about it

**Comment by floaledm** [comment]
Sounds good... I wasn't finding the changes on the branch so I was wondering where they were... Many thanks!
