### ISSUE TITLE
N362/Horus/Companion: Copy/paste of models using Ctrl+C/Ctrl+V works incorrectly

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#4549]
Steps to reproduce:

- Copy/paste a model from source eeprom to non-default category in target eeprom

The model gets copied, but to the default category.

[Test   ]
model7.bin
![2017-03-03_113919](https://cloud.githubusercontent.com/assets/6317479/23550067/12fbce92-0007-11e7-8c10-6bbe3b96141f.png)

[Test   ]
model7.bin
![2017-03-03_113935](https://cloud.githubusercontent.com/assets/6317479/23550076/1c0f7376-0007-11e7-9209-bd1f5bc39496.png)

**Comment by kilrah** [comment]
All fixed, copy/paste isn't even supposed to be possible yet in N362, pasting on an existing model wasn't even a proper way of operating but jsut a workaround someone found (which is broken as you can see).
