### ISSUE TITLE
Working joystick in Horus simulator.

### ISSUE THREAD

**Issue by mpaperno** [opentx/opentx#4551]
Currently the Horus joystick controller is not functional in Simulator. Enhancement request carried over from #4336 .

**Comment by hursto75** [comment]
Would like to add the ability to use the Joystick function through bluetooth. Not sure if that goes on this Issue or should be a seperate enhancement.

**Comment by 3djc** [comment]
#5234

**Comment by kilrah** [comment]
Nope, this issue is about the little 2-axis stick on the radio, not joystick functionality. @3djc pointed you to the right place, we can reopen if you think you're able to figure out the PC side.

**Comment by hursto75** [comment]
Looking at the PC side now.

Brad
