### ISSUE TITLE
Remove MIXERS_MONITOR option, make MM always available.

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#4557]
Hy,
Profil X9D+

No Mixermonitor at Simulator with ENTER
At Option Mixermonitor is selceted

Same with  X9E

**Comment by kilrah** [comment]
Simulators don't use options.

**Comment by hrenz** [comment]
Mixermonitor at simulator is importend 
 for programming and testing before got to Tx an Modell ans set Servo directions

**Comment by kilrah** [comment]
We'll spend time figuring out what options to use by default but that will be only in final release, not RCs.

**Comment by hrenz** [comment]
ok I see

**Comment by mpaperno** [comment]
I think there was actually consensus for removing the option altogether and just having the MM always available in every build, but the changes slipped for RC11.   (Literally the only difference at this point is if the "enter" key/action in channels monitor has any effect or not (there is no extra memory or resources used, etc.).  Seems like even if someone DID get confused by that, it should be fairly obvious that repeating the key action gets you back to the default channels view.)

**Comment by kilrah** [comment]
Ah yes, forgot about it

**Comment by mpaperno** [comment]
Me too :)   I'll reopen this issue to remind us.
