### ISSUE TITLE
OPENTX 2.2 RC11  XJT  D8 No selection menu

### ISSUE THREAD

**Issue by wolflonezx11** [opentx/opentx#4563]
HI 

TARANIS Q X7  or TARANIS  X9E 

MODEL SETUP->INTERNAL   RF -> MODE  ( D16 /  L12 ) ?? D8  No selection menu

Can not use D4R-ii.
Please take immediate action
please

**Comment by schwabe** [comment]
Are you using a EU firmware?

**Comment by kilrah** [comment]
Flash firmware without the EU lock.

**Comment by wolflonezx11** [comment]
non EU firmware

**Comment by schwabe** [comment]
as @kilrah said the only firmware we have that do not allow selecting D8 are eu firmwares.

**Comment by kilrah** [comment]
You're likely confusing rf firmware version with the openTx eu option.

**Comment by wolflonezx11** [comment]
In the past, I have used the opentx 2.2 rc10 without any problems.
Then what firmware should I put ???

**Comment by 3djc** [comment]
One **without** EU option choosen

**Comment by wolflonezx11** [comment]
Eu became the choice
It was my fault.
sorry
Troubleshooting
