### ISSUE TITLE
RC11 N363 on Taranis Q X7

### ISSUE THREAD

**Issue by JR63** [opentx/opentx#4568]
Nice effort with the RC11 N323, I like it very much!

I found a minor issue:

I can set a Logical Switch with e.g. Cells 3.25V:

![logicalswitch001](https://cloud.githubusercontent.com/assets/8395202/23628521/d0213c28-02b4-11e7-90fa-0eba619ca2a9.jpg)

But in the Logical Switches overview it looks like this:

![logicalswitch002](https://cloud.githubusercontent.com/assets/8395202/23628534/d8824524-02b4-11e7-8b6c-94ac1ffbdeb6.jpg)

I think it should be:
Cels 3,25V

Tested with real Q X7 and Companion.

Bye
JR

**Comment by 3djc** [comment]
I need more details, as I cannot reproduce it:
- is it coming for a earlier verison ?
- how was it created ?

![image](https://cloud.githubusercontent.com/assets/5167938/23644273/cc69b13a-0306-11e7-86c9-e7bffe153202.png)

![image](https://cloud.githubusercontent.com/assets/5167938/23644278/d51f23f0-0306-11e7-914f-d983097319ac.png)

**Comment by JR63** [comment]
Hi,

I think it's one line in the following method:


void menuModelLogicalSwitches(event_t event)
{
     ...

      else {
        uint8_t v1 = cs->v1;
        drawSource(CSW_2ND_COLUMN, y, v1, 0);
        if (v1 >= MIXSRC_FIRST_TELEM) {
          drawSourceCustomValue(CSW_3RD_COLUMN, y, v1, convertLswTelemValue(cs), LEFT);
        }
        else {
          if (v1 <= MIXSRC_LAST_CH) {
            drawSourceCustomValue(CSW_3RD_COLUMN, y, v1, calc100toRESX(cs->v2), LEFT);
          }
          else {
            drawSourceCustomValue(CSW_3RD_COLUMN, y, v1, cs->v2, LEFT);
          }
        }
      }

     ...
}


The line:
        uint8_t v1 = cs->v1;

maybe shall be:
        int v1 = cs->v1;


It's the same problem as the fix of #4416

v1_val = (uint8_t)cs->v1;
->
v1_val = cs->v1;

Bye
JR

**Comment by 3djc** [comment]
I still would like the otx to confirm a fix if possible. Thx

**Comment by JR63** [comment]
No problem, here is my ziped otx:

[document1.zip](https://github.com/opentx/opentx/files/823790/document1.zip)

**Comment by 3djc** [comment]
Thx, I have succeeded reproducing it, will make my fix much easier to check :)

**Comment by JR63** [comment]
cool

**Comment by 3djc** [comment]
Your fix would work, but we have type defined for this scenario :)

**Comment by JR63** [comment]
ok, source_t is also a good choice ;-)

#if defined(PCBTARANIS) || defined(PCBHORUS)
typedef uint16_t source_t;
#else
typedef uint8_t source_t;
#endif

perfect, thanks.

**Comment by tonythetiger95** [comment]
How can I get this fixed exactly. Pretty new to the whole opentx platform and so far I'm having a good experience with the sound editing and so on but not really sure how to fix this issue thanks.

**Comment by 3djc** [comment]
When RC12 gets released, it will have the fix

**Comment by tonythetiger95** [comment]
Thank you. I'll be sure to check back in when that gets put out. Good day
