### ISSUE TITLE
Character alignment issue?

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#4571]
![characteralignmentquestiontiled](https://cloud.githubusercontent.com/assets/4843199/23638632/a839ca26-0297-11e7-9a63-cf64fb64771d.jpg)
[QX7.zip](https://github.com/opentx/opentx/files/823167/QX7.zip)

On n363 (and n362), QX7 the character alignment is not what I would have expected.  Notice the Mid and DBL size appear to be at least one pixel too low.  This is true in both the simulator in Companion and on the tx as shown in the attached picture.
Data written from a telemetry script, QX7, also attached.

**Comment by 3djc** [comment]
It is not X7 specific, X9 is exhibiting the same behaviour, still investigating

![image](https://cloud.githubusercontent.com/assets/5167938/23645127/d81a9b12-030a-11e7-8050-45ae81ef9cc7.png)

**Comment by 3djc** [comment]
ok, what happens is that the font itself has a blink pixel line in MID and DBL size;
![image](https://cloud.githubusercontent.com/assets/5167938/23646269/64982492-0310-11e7-93a4-67b9e6ac8725.png)

It can be fixed, but will have impact, so needs to be assessed carefully
