### ISSUE TITLE
[X7] Telemetry bars screen has some display problems

### ISSUE THREAD

**Issue by lthole** [opentx/opentx#4576]

**Comment by 3djc** [comment]
We will probably one if we can make a nice despite the low response, but not before 2.2.0

**Comment by bsongis** [comment]
Are we talking about this screen?

![snapshot_01](https://cloud.githubusercontent.com/assets/5603504/23679734/24f75bea-0389-11e7-8c49-e813d7bc6904.png)

**Comment by 3djc** [comment]
Erf misread, was thinking about chan mon

**Comment by lthole** [comment]
I am unable to get that screen. I am on 2.20N363 RC11 and Win7SP1. I can get the NUMS screen, but no BARS screen.
I have just created a new model, and bound it to an X6R receiver with an SP-FLVS S.Port Lipo sensor. I ran 'Discover new sensors', and it found my sensors. I then set up a BARS screen with RxBt and Cels. From the main view, I pressed [Page_long] and got a screen saying 'No Telemetry Screens' and 'NO DATA'. I then added a NUMS screen with RxBt and Cels, and that screen comes up fine, but the NUMS still does not come up.

**Comment by bsongis** [comment]
True. I will change the bug title

**Comment by bsongis** [comment]
- [ ] Standard bottom bar for RSSI is too far to the right, so not displaying the value
- [ ] We have no TX RSSI, we could write "RSSI"
- [ ] Labels should be written in SMLSIZE?

**Comment by 3djc** [comment]
I'll take that

**Comment by 3djc** [comment]
![image](https://cloud.githubusercontent.com/assets/5167938/23698192/e73ec902-03ea-11e7-9fc7-9cc65138c1e7.png)

With SMLSIZE:
![image](https://cloud.githubusercontent.com/assets/5167938/23698227/0c5e64a4-03eb-11e7-9c95-e9d480ccacde.png)

**Comment by 3djc** [comment]
I prefer SMLSIZE

**Comment by bsongis** [comment]
Indeed!
Would you try also the SMLSIZE for the bar label (Thr)?

**Comment by 3djc** [comment]
![image](https://cloud.githubusercontent.com/assets/5167938/23700001/b00650fc-03f1-11e7-9de3-0fc928c4bc9c.png)

**Comment by 3djc** [comment]
or thi sthat I prefer:
![image](https://cloud.githubusercontent.com/assets/5167938/23700099/1a0c6216-03f2-11e7-9124-d40279430820.png)

**Comment by bsongis** [comment]
:+1
