### ISSUE TITLE
using gVar as offset wrong scaling (x7 radio)

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#4582]
When using a Gvar as offset on a mixer line, the actual effect is only 10 % of the Gvar setting.

So on a mixer line, source max, weight 0, offset gVar1 with gVar set to -100, the output is -10.

**Comment by lshems** [comment]
Sorry, only when using -gVar as offset this is not working correct.

gVar as offset with a negative value of gVar is working correct.

So must be in the - part of the gVar thing.

**Comment by lshems** [comment]
It was late yesterday. Correct issue:

Gvar 100

Source Max, weight 0, offset -gvar
Result -10 instead if -100

Source Max, weight 0, offset gvar
Result 100, as expected.

**Comment by 3djc** [comment]
![image](https://cloud.githubusercontent.com/assets/5167938/23787445/6699ef1e-0572-11e7-919f-a5cb9fb67726.png)

![image](https://cloud.githubusercontent.com/assets/5167938/23787462/7a2e99b2-0572-11e7-8cbd-7d2cfceab7e6.png)

I don't seem to be able to replicate, could you let me have your otx ?

**Comment by lshems** [comment]
Ah, you'r on RC11, I had returned to RC10, because the RC11 had some other issues bothering me. Forgot to test on RC11 as well.

So, it seems that it is fixed on RC11. 

Thanks.

**Comment by lshems** [comment]
Could we reopen: tested on RC11, and got a similar result.

test otx attached.

just change the offset from -gv1 to gv1 and see the difference
![2017-03-10 1](https://cloud.githubusercontent.com/assets/12395806/23810546/529c6e50-05d2-11e7-818d-399713ef584d.png)
![2017-03-10](https://cloud.githubusercontent.com/assets/12395806/23810547/529fdd10-05d2-11e7-94f6-b1d90a19e767.png)



[testerror.zip](https://github.com/opentx/opentx/files/834958/testerror.zip)

**Comment by lshems** [comment]
tested on taranis 2.2RC11, same issue. I have no clue what happens, since a new model with the same settings doesn't exhibit this behaviour; Only the attached OTX does this.

**Comment by kilrah** [comment]
Weirdo

**Comment by lshems** [comment]
Indeed.

**Comment by lshems** [comment]
remark that the gvar screen is showing only zero's !?

**Comment by kilrah** [comment]
Hmm not here?

**Comment by lshems** [comment]
![2017-03-10 2](https://cloud.githubusercontent.com/assets/12395806/23812778/3e305436-05dc-11e7-9dc2-ac11cd3ad7f1.png)

**Comment by lshems** [comment]
![2017-03-10 3](https://cloud.githubusercontent.com/assets/12395806/23812845/76f691e0-05dc-11e7-9f59-88f5f59bff0b.png)

**Comment by lshems** [comment]
perhaps that screen is not functional yet, I don't know.

**Comment by kilrah** [comment]
Indeed, didn't see it...

Open companion, open file, click simulate (on document) - values are shown correctly (but output is bad). Close simu, click simulate again, the<y're all 0.

@mpaperno, help? haven't followed storage evoltion close enough, but seems like it could be related?

**Comment by mpaperno** [comment]
Indeed, the Simulator Radio Outputs gvars not updating was a bug (fixed @ 0a5732b953e1a87763a6ae06ea946c843f6ecbf1).  Thanks for noticing  :)

No clue on the problem of the actual gvars calculations in firmware...  I can't keep track of the import/conversion routines either, if that's what you mean Andre.  I guess first step is consistent repro case.  Maybe @bsongis has some clues for us.

**Comment by kilrah** [comment]
No I just meant the bug you fixed :)

**Comment by lshems** [comment]
Ok, found a reproducable action triggering the issue. It doesn't make sense at all:

in the attached file, there are two models, both having input1 with SA as source, gVAR1 having a value of 50, and mixer line 1 having source Max, weight 0 and offset GVAR1. mixer line 2 having source Max, weight 0 and offset -GVAR1.

When no switch warnings are active, the second mixer line produces -5, where it should have produced -50.
When activating switch warning for SB, the second mixer line is correctly showing -50.

Tell me whats happening ???

[testerror (2).zip](https://github.com/opentx/opentx/files/842922/testerror.2.zip)
![2017-03-14 1](https://cloud.githubusercontent.com/assets/12395806/23925078/f135ee90-090d-11e7-8309-8591169def61.png)
![2017-03-14](https://cloud.githubusercontent.com/assets/12395806/23925079/f1360e16-090d-11e7-966d-a7641bb92853.png)

**Comment by 3djc** [comment]
I can reproduce that, will be looking at that today

**Comment by lshems** [comment]
Thanks. It is a plane crashing one for my models after conversion from X9, if I wouldn't test properly before using it :).
