### ISSUE TITLE
Minor sound pack issue in v6 SD Card for 2.2-rc11

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#4584]
The file /SOUNDS/en/SYSTEM/en-US-taranis.csv contains a typo on line 177. Reads:

SOUNDS/en/SYSTEM;mintrim.wav;minium trim reached

should read:

SOUNDS/en/SYSTEM;mintrim.wav;mini**m**um trim reached

Just minor but required if generating your own sound files using this as the source data and you want it to sound right :-)

**Comment by 3djc** [comment]
Fixed
