### ISSUE TITLE
ENTER/MOUSE-MID defined in the simulator help is not correct

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#4585]
When doing the French translation (and testing the RC11 at the same time), I discovered that the help in the simualtor is wrong.
**ENTER/MOUSE-MID** should be **ENTER/MOUSE-LEFT**

**Comment by mpaperno** [comment]
Mouse left button?  That doesn't change normal meaning.  Mouse MID will (or should) activate the radio "action" (ENT/MENU/Rotary click) while anywhere over the Simulator window.  So I'm not sure what you mean.

That said, I did find some issues in the help text and the controls themselves, which I have changed already in my working copy. I'm also centralizing all the strings in one file to make it simpler to maintain/translate.  So don't spend much time translating the keyboard help text right now.

E.g. from X9E:
![image](https://cloud.githubusercontent.com/assets/1366615/23820215/f3617344-05e1-11e7-94f6-ea7b57e27d15.png)

What do you think of the icons?

**Comment by kilrah** [comment]
> ENTER/MOUSE-MID should be ENTER/MOUSE-LEFT

Umm no, it's correct... :\

> What do you think of the icons?

Yep why not!

**Comment by LapinFou** [comment]
Well I guess I didn't understand what this **ENTER/MOUSE-MID** is for.
With the X9D+ simulator, the middle click doesn't work on the 6 buttons (PAGE, MENU, etc...). But, the left click does.
However with the LUA script (for example the Wizard), I can scroll with the mouse to select, then use the middle button to confirm the action.

**Comment by kilrah** [comment]
Left-click on the buttons activate them, including the rotary encoder "enter" push.
Mid mouse activates the rotary encoder push regardless of where the cursor is.

**Comment by mpaperno** [comment]
Ah, I see... ironically, mid-clicking anywhere BUT in the button areas works correctly.  But while cursor is over the control areas on the left/right, mid-click doesn't actually work at all.  I think I also know why... yes, much better now (fixed... porting... testing... committing...).

**Comment by mpaperno** [comment]
Now if mid-clicking on a radio key, that key is activated.  Otherwise default mid-click action is triggered (enter/rotary click/etc).  I tried it so the default action is always triggered, but it was awkward and counter-intuitive when mid-clicking on a different key and instead "enter" was being pressed.

**Comment by LapinFou** [comment]
Thanks!
😄
