### ISSUE TITLE
Calculated sensor with no name is still saved

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx#4586]
(On the Horus discovered, might apply to others)
Add a calculated sensor, choose totalize as function, exit without entering a name. Now there is a new sensor without a name, that is not shown in the sensor list. The sensor can be selected as a source on the Horus. Companion does list it also
![image](https://cloud.githubusercontent.com/assets/5653676/23812777/3cb924e8-05dc-11e7-981a-7b4c5fad7b28.png)

**Comment by projectkk2glider** [comment]
@kilrah are you sure this issue is fixed? I think you can still create a sensor without the name on the radio. Such sensor will not be shown in the sensors list, but its values will be set in the memory.
