### ISSUE TITLE
Can't connect my Taranis x9d plus with my PC

### ISSUE THREAD

**Issue by Rockefella95** [opentx/opentx#4594]
Hello,

i've got a big problem. I had to rebuild my PC with windows 10 and from this time on i can't use my taranis anylonger with my pc. 

I've tried all usb 2.0 / 3.0 and 3.1 slots to connect the taranis to my pc. 
I installed the newest zadig driver and the STM32 driver. 
When i plug in my Taranis it shows me up in the Devicemanager but i cant use her. I cant flash any Firmware using the companion software and i can't use the Taranis with any of the Simulators. 

Before i rebuild my PC it worked fine and i got no problems. 
I've got no more ideas where maybe the problem is. Hopefully some of you can help me please. 
I hope i dont forgot some needed information for you, if so please just write me what you need.

Sorry for the bad english (i'm from germany)

Best regards Rockefella

**Comment by projectkk2glider** [comment]
Please use forums for this kind of problems. This site is meant for actual bugs.
