### ISSUE TITLE
BUG System Sound Problem ONLY with Folder DE/ System mamps0.wav Horus Taranis!

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#4595]
Hallo Bernard, Kylrah, Djc

Firmware opentx 2.2.363
BUG System Sound Problem ONLY with Folder DE/ System mamps0.wav Horus Taranis!

Please change mamps0.wav into mamph0.wav    Otherwise there is no speaker information for "Verbrauch"

Language EN is OK!!!! Only German DE/System

**Comment by 3djc** [comment]
fixed
