### ISSUE TITLE
[Companion 2.2.RC12] no separation between the mixes lines

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#4599]
Since the release 2.2.RC11 (Win10 env), there is no more separation between mixes lines.
I don't know if it's a small cosmetic bug, or if it's done in purpose. However, it was better before 😉 
Moreover it is inconsistent with the **Inputs** tab.

See the picture
![tmp](https://cloud.githubusercontent.com/assets/1685030/23855607/925a7552-07f6-11e7-9e4b-dab6d9e9789a.png)

**Comment by projectkk2glider** [comment]
Just for additional info, different QT version will produce different result, here is QT 5.2.1 on Linux.

Here the separation is OK, but lines are truncated at the bottom!
![screenshot](https://cloud.githubusercontent.com/assets/5950438/23867859/8fb31382-081d-11e7-9205-57e447e51cee.png)

The QT 5.7 (non-native for me) produces this:
![screenshot](https://cloud.githubusercontent.com/assets/5950438/23868064/4e2451d2-081e-11e7-9080-2bf66aa93ac7.png)

**Comment by mpaperno** [comment]
I've looked briefly at this a couple times but so far can't even understand why the fonts are different on Inputs vs. Mixes screens.  Some day....

**Comment by LapinFou** [comment]
The font doesn't look much different between OTX 2.1 and OTX 2.2.
I thought the only difference was a different interline parameter (or similar).

See on the screenshot below, on the top there is a EOL (or similar) between each mixer line, but not on the bottom screenshot.

![tmp](https://cloud.githubusercontent.com/assets/1685030/25563654/c3fc0e66-2da0-11e7-8e89-99ae7a2cdc5e.png)

**Comment by mpaperno** [comment]
Sure, the document formatting is "quite" different.  The font difference is either the reason or a symptom, not sure which.  The 2.1 version of Mixes looks like the same as 2.2 Inputs format.
