### ISSUE TITLE
QX7 - display dark after update to 2.2.0 RC12 (N364)

### ISSUE THREAD

**Issue by franz4949** [opentx/opentx#4604]
After update to nightly 2..2.0 RC12 (N364) and pressing "Exit" the display remains dark and also switch off button does not work, battery must be disconnected and reconnected. After that display remains dark but Tx starts up and can then also be switched off via button hold pressed. Start in boot mode does work normal and can be connected to companion. I read the Tx settings with companion, changes values of contrast and brightness, wrote settings back into Tx, however no success. After "Exit" of bootmenu display remains dark and power button again without function. Only way left is disconnect/reconnect battery.

**Comment by 3djc** [comment]
What is the name of the firmware you flashed ?

**Comment by franz4949** [comment]
Version is as written in heading, thus nightly build 2.2.0 RC12 (N264).
And Tx display remains dark when started in normal operation mode, however possible to shut off by pressing and holding power button. Display only illuminates normal when started in bootloader mode.

**Comment by 3djc** [comment]
What we need is something like opentx-x7-lua-massstorage-en.bin

**Comment by franz4949** [comment]
Ok => opentx-x7-noheli-lua-massstorage-de-2.2.0N364.bin

**Comment by 3djc** [comment]
That's interesting, since that specific firmware has not been compiled on our server yet

**Comment by franz4949** [comment]
I took the windows installer (companion) from here => http://www.open-tx.org/2017/03/13/opentx-2.2.0RC12#

**Comment by 3djc** [comment]
OK, I found it, sorry. All seems fine on our side, I'll try flashing it on my radio

**Comment by 3djc** [comment]
Works fine here (just a strange language :D)
Have you tried working your way to lcd settings just in case ?

**Comment by franz4949** [comment]
Sorry for the strange language :D 
Only way to do this is start in bootloader mode, connect to companion, read models and setup from Tx (Q7), do some setup changes for contrast and brightness and write thenchanges back into Tx. This way worked for the previous nightly build but does not work with actual version. Also i should mention that none of the two display criteria were down with its values. Brightness was/is at 100%, contrast at 35%.

**Comment by projectkk2glider** [comment]
@franz4949 is your radio really hot or cold? Try starting without the SD card. Flash the radio again.

**Comment by franz4949** [comment]
Have taken out SD card and then flashed again, no change in result. After leaving bootloader mode, display remains dark, no function of switch on/off power button. After dis/reconnection of battery I can start Tx but display remains dark. Power button works to switch off and I can start bootloader mode normally.

**Comment by franz4949** [comment]
Radio has normal temperature, thus not hot not cold.

**Comment by projectkk2glider** [comment]
Can you flash back the RC11 just to confirm that it works - ie that your radio has not suffered a hardware problem.

**Comment by franz4949** [comment]
I flashed 362 (must be RC10 I think) and it works normal. With RC11 I I had same problem as with RC12, only difference was, that after reading of Tx setup via companion and writing back again the display worked. With RC12 it does not work this way.

**Comment by projectkk2glider** [comment]
This would suggest that the issues is indeed the contrast setting.

**Comment by franz4949** [comment]
But what about the frozen status after leaving the bootloader mode? Power button without function, only thing I can do is disconnect battery.

**Comment by projectkk2glider** [comment]
Previously you wrote:

>And Tx display remains dark when started in normal operation mode, however possible to shut off by pressing and holding power button. 

Do you hear any trim beeps when your use trims?

**Comment by franz4949** [comment]
And if the contrast is down, should I not see this then when I read the Tx setup with companion?

When I start Tx normal, yes then display is dark but power button does work, means I can switch Tx off. However when Exit bootloader mode Tx is frozen and does not start,

**Comment by projectkk2glider** [comment]
Try setting the radio language to English (in Companion), then download the new firmware and flash the radio.

**Comment by franz4949** [comment]
I did but no change in result.

**Comment by franz4949** [comment]
Again after Exit bootloader mode only way is disconnect and reconnect battery. After then normal start display dark, no sound when switching trims, however can switch off with power button.

**Comment by franz4949** [comment]
What can I do to give you more data/information?

**Comment by projectkk2glider** [comment]
I would like to have a confirmation of the same issue from at least one another user. So far it looks like your specific radio problem.

**Comment by franz4949** [comment]
I understand what you say, but I do not understand how this might be specific for just for my radio. The radio I received from Banggood some 3 weeks ago. I am not using it for flying yet, I also have two X9D radios. I only flashed german OTx nightly RC10 which worked normal. Then some days ago I flashed RC11 and run first time into this problem, which I could resolve by Companion reading Tx setup and writing it back again. And now with RC12 also this does not work. That is all what I did up to date with this radio, no use for flying no mods. nothing.

**Comment by franz4949** [comment]
Strange. Anyway I'd like to thank you for your efforts to resolve this matter.

**Comment by franz4949** [comment]
Additional information: Bootloader on my QX7 is =>  X7   -  2.2.0N362

**Comment by 3djc** [comment]
While it sounds logical, you are the only one experiencing it, which in return points to a problem on your side.  Could you try the following : put RC (or whatever works), make 100% sure you have backups of your radio, long press menu, go to page 5/9, enter long for a factory reset, then try to flash RC12.

**Comment by franz4949** [comment]
Problem solved by installing the update **not via companion** but **direct from SD card**. This proposal I got from a guy in RCG who reported that he was facing the same problem as I had and he solved it in the proposed way by direct update from SD card.

So for me I am fine and for me I can close this issue. If there is something not so perfect with companion, I cannot say, maybe you might have a closer look there.

Many thanks again for your prompt support and effort to help me.

**Comment by 3djc** [comment]
Happy to see it solved  !
