### ISSUE TITLE
Curves not displayed in the "print" output

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#4612]
Hi Folks,

I'm running the N364 on a Win10 64bits. When I do print a model, the curves are not displayed.
Here is what I got, instead the graphical views:
![tmp](https://cloud.githubusercontent.com/assets/1685030/23893503/ff0abbd2-089e-11e7-8464-58d41729ee2c.png)

**Comment by projectkk2glider** [comment]
Same problem on Linux.

**Comment by mpaperno** [comment]
Yep, saw that while making the model printer (and the rest of Companion) show user-configured control names.  Wasn't sure if it ever worked, but I guess so?   Looks like the image isn't being properly embedded in the resulting HTML doc...  will check into it more.

**Comment by LapinFou** [comment]
Never checked on previous Companion 2.2 version, but it is working on Companion 2.1.9

**Comment by mpaperno** [comment]
Maybe it was a Qt 4 -> 5 migration glitch.  Confirmed working now in all 3 OSs.  Though I still need to check Damjan's favorite Qt 5.2...   😛

**Comment by mpaperno** [comment]
Yes, even there  :)

![image](https://cloud.githubusercontent.com/assets/1366615/23909518/552b4dd4-08ad-11e7-9bf3-977bcb484be6.png)

**Comment by LapinFou** [comment]
That was a very fast fix!
Thanks 👍

**Comment by mpaperno** [comment]
We aim to please.  Especially translators.   :-)

**Comment by LapinFou** [comment]
Thanks! ^_^
