### ISSUE TITLE
French sound pack

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#4615]
Hi folks,

When checking the SD card version 0007, I saw a small mistake in the fr-FR-taranis.csv file.

SOUNDS/fr/SYSTEM;knot0.wav;knots
should be
SOUNDS/fr/SYSTEM;knot0.wav;noeud

**and**

SOUNDS/fr/SYSTEM;degf0.wav;degrés fahr
should be 
SOUNDS/fr/SYSTEM;degf0.wav;degrés fahrenheit

**Comment by 3djc** [comment]
Fixed

**Comment by LapinFou** [comment]
Wahouuu, ça c'est du rapide !!
