### ISSUE TITLE
Companion channel window displays 79% for an 80% value

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#4619]
![2017-03-14 3](https://cloud.githubusercontent.com/assets/12395806/23925238/7fa7c95a-090e-11e7-928a-3b28a642014d.png)
![2017-03-14 2](https://cloud.githubusercontent.com/assets/12395806/23925237/7fa555a8-090e-11e7-9d90-050bb5179fe4.png)

see screenshots

**Comment by mpaperno** [comment]
Looks like a rounding error/difference.  I suppose the outputs could be shown out to 1 decimal place in Simulator, though it would take more horizontal space...
