### ISSUE TITLE
RC12 (N364) Horus Emergency Mode on max year

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#4627]
RC12 (N364) pcbdev Horus.  On SYS/Radio Setup/Date if the year is accidently turned to the maximum year the system goes into emergency mode.

**Comment by bsongis** [comment]
ouch, really?

**Comment by MIKE-DAILEY** [comment]
Yes, on pcbdev.  It is easy to scroll past the year you want and hit the end year and zap!  Haven't tried it on production though.

**Comment by bsongis** [comment]
it should be the same on production

**Comment by MIKE-DAILEY** [comment]
I'm sure that this is not a priority for a fix, but it still exists in RC16.

**Comment by bsongis** [comment]
This one should be fixed asap, @3djc let me know if you have any problem, I will take it

**Comment by 3djc** [comment]
I plan to work on it tomorrow, but I'll let you know if I encounter any problems
