### ISSUE TITLE
[X9D] GPS coordinates are sometimes badly displayed

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#4631]
![](https://cloud.githubusercontent.com/assets/5603504/24055256/a7cc8f32-0b3f-11e7-855a-65a9d8463d48.jpeg)

![](https://cloud.githubusercontent.com/assets/5603504/24055260/a9892c0e-0b3f-11e7-85ac-03c5f04d8509.jpeg)

![img_5949](https://cloud.githubusercontent.com/assets/5603504/24055338/e69f03ac-0b3f-11e7-8f61-dc40a5e19a19.jpeg)

**Comment by sirPerna** [comment]
only values <1.0 affected.

**Comment by 3djc** [comment]
Could you post bigger pictures, can't see with those :)

**Comment by bsongis** [comment]
ah yes

**Comment by bsongis** [comment]
![img_5947](https://cloud.githubusercontent.com/assets/5603504/24055256/a7cc8f32-0b3f-11e7-855a-65a9d8463d48.jpeg)
![img_5948](https://cloud.githubusercontent.com/assets/5603504/24055260/a9892c0e-0b3f-11e7-85ac-03c5f04d8509.jpeg)
![Uploading IMG_5949.jpeg…]()

**Comment by 3djc** [comment]
With the coordinates taken from the fpv screenshot
N364 DMS:
![image](https://cloud.githubusercontent.com/assets/5167938/24056411/dc0fdae8-0b43-11e7-9fdc-c899b2167236.png)

N364 NMEA
![image](https://cloud.githubusercontent.com/assets/5167938/24056445/feb50aaa-0b43-11e7-97d4-f9b0bea2107f.png)

**Comment by sirPerna** [comment]
@3djc Did you fix anything becase it's still not working here. The CRSF sends Latitude first. 

![image](https://cloud.githubusercontent.com/assets/7645907/24070228/6c385490-0bb9-11e7-9bc4-52bc3d3863ee.png)

**Comment by 3djc** [comment]
What version are you using ?

**Comment by sirPerna** [comment]
2.2.0N364 the latest it downloaded yesterday.

**Comment by kilrah** [comment]
Well we didn't even know you were using CRSF telemetry... We thus checked with FrSky obviously.

**Comment by sirPerna** [comment]
Sorry for the bad report in this case. Setup is TBS CORE PRO - Crossfire - Taranis. I can share a test firmware for Crossfire so no additional hardware required then a Crossfire TX and a OpenTX remote.

**Comment by 3djc** [comment]
If I input your values with 364, i get the screens above (mine) that are correct.
If I used N362, I get your screen :
![image](https://cloud.githubusercontent.com/assets/5167938/24070334/c7046db2-0bbb-11e7-8ead-8fdbaa617f60.png)

Can you confirm on the radio you are running N364, because it doesn't look like it

**Comment by kilrah** [comment]
> 2.2.0N364 the latest it downloaded yesterday.

Then you probably downloaded **companion** N364, but didn't download / flash N364 **firmware**.

**Comment by bsongis** [comment]
@sirPerna would you tell us which firmware version you see in the VERSION screen on the radio?

**Comment by sirPerna** [comment]
![2017-03-18 09 41 27](https://cloud.githubusercontent.com/assets/7645907/24070511/2f481e34-0bbf-11e7-87d1-ecde7e4a3c1e.jpg)

**Comment by bsongis** [comment]
ok, we have a bug for sure

**Comment by bsongis** [comment]
bug confirmed even in our current 'next' branch

**Comment by bsongis** [comment]
the GPS parsing code is here:
https://github.com/opentx/opentx/blob/next/radio/src/telemetry/crossfire.cpp

```
if (getCrossfireTelemetryValue<4>(3, value))
        processCrossfireTelemetryValue(GPS_LATITUDE_INDEX, value/10);
```

**Comment by bsongis** [comment]
it returns an uint32_t which is not good here

**Comment by bsongis** [comment]
@3djc I take it, testing in progress with @sirPerna

**Comment by sirPerna** [comment]
Tested. Thank you!
