### ISSUE TITLE
Companion 2.2.0N364 Model list default model font size (cosmetic)

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4632]
![screenshot from 2017-03-19 06-52-17](https://cloud.githubusercontent.com/assets/15316949/24075525/53503372-0c71-11e7-84e4-8e000ceb562a.png)

Ubuntu 16.04

**Comment by elecpower** [comment]
#4769 Fixes

**Comment by mpaperno** [comment]
Cool!  Not sure why it got fixed, but I'm not complaining.  :)
