### ISSUE TITLE
No new Firmware available thru companion N365

### ISSUE THREAD

**Issue by dklueh79** [opentx/opentx#4636]
Neither for X7 nor Horus you could download the new firmware. The last is the 364 - check for nightly is set in setting.
![otx](https://cloud.githubusercontent.com/assets/6195999/24080316/929d36a8-0c9c-11e7-8dd4-9f0effe061b9.png)

**Comment by dklueh79** [comment]
![2017-03-19 12_08_14-opentx companion 2 2 0n365 - radio_ frsky taranis x7 - profile_ taranis x7](https://cloud.githubusercontent.com/assets/6195999/24080321/c65d9a82-0c9c-11e7-8f2e-9fcea79488d4.png)
![2017-03-19 12_08_51-edit settings](https://cloud.githubusercontent.com/assets/6195999/24080324/dc47b2a6-0c9c-11e7-95b9-bde500b1cb60.png)

**Comment by 3djc** [comment]
Fixed

**Comment by dklueh79** [comment]
Very fast! Thx!!!!

**Comment by kilrah** [comment]
Things get built one after the other, so become ready one after the other, normal.

We'll be changing to hold off the notification until everything's ready for the future.
