### ISSUE TITLE
Missing Qt translation

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#4637]
Hi folks,

When closing Companion without saving the modifications, the popup windows got some fields in English.
I didn't see them with Qt Linguist. A guess there is a Qt "tr(xx)" missing somewhere.
![tmp](https://cloud.githubusercontent.com/assets/1685030/24081805/d4338fea-0cba-11e7-96ed-7a4f583657a0.png)

**Comment by 3djc** [comment]
They are qt built in messages linked to your system language, cannot be changed.

**Comment by kilrah** [comment]
Tey can, reference:
http://stackoverflow.com/questions/31533019/title-qt-how-to-translate-the-buttons-in-qmessagebox

**Comment by LapinFou** [comment]
But, I'm running a "French Window 10 famille" version?
So, something is not right.My "préférences inguistique" is setup to "français(France)".

**Comment by 3djc** [comment]
That's really odd! There is a magic trick you can do in case like that. Let me try it : @mpaperno!

**Comment by kilrah** [comment]
See my post above!

**Comment by LapinFou** [comment]
Same thing in the Wizard.
![tmp](https://cloud.githubusercontent.com/assets/1685030/24082382/092c2c7a-0cc5-11e7-9b0b-4afa4b9401f0.png)

On the French forum, somebody reported on MAC than the "close, minimize, et maximize" buttons (top left of the windows) are not translated either.

**Comment by 3djc** [comment]
for the same reasons

**Comment by LapinFou** [comment]
Yep, probably. 😄 

Here is the link, just in case: http://frskytaranis.forumactif.org/t5037-opentx-2-2-0-rc13-n365#58134

**Comment by 3djc** [comment]
It is the case on windows too btw ;)

**Comment by LapinFou** [comment]
In fact same issue on Windows. It is not only Mac OS dependent.
![tmp](https://cloud.githubusercontent.com/assets/1685030/24082442/0c4fddec-0cc6-11e7-94bc-c6d4fb316a2a.png)

**Comment by 3djc** [comment]
You will find it in many many places, where system dialogs are used

**Comment by LapinFou** [comment]
OK. So, I will wait @mpaperno feedback.

**Comment by LapinFou** [comment]
This one is a missing Qt translation:
![tmp](https://cloud.githubusercontent.com/assets/1685030/24083942/375509fc-0ce1-11e7-9da5-eb5454d188ae.png)

**Comment by kilrah** [comment]
The one on the pots does have the tr(). Did you update the .ts file?

**Comment by LapinFou** [comment]
I didn't see it in the .ts file generated by @3djc . Could you (or @3djc) generate a branch with the latest up-to-date French .ts file? I don't have the flow installed on my computer (just Qt Linguist).

**Comment by kilrah** [comment]
Weird, it's actually already there and translated :\

![clipboard01](https://cloud.githubusercontent.com/assets/6065069/24085341/8fb05e76-0cfa-11e7-841b-febbffbb723f.png)

**Comment by LapinFou** [comment]
Badly translated, it should be "Double-clic **droit** pour recentrer."

**Comment by mpaperno** [comment]
> There is a magic trick you can do in case like that.  

LOL...  obviously I should ignore you more often!  :)

Well Andre gave the link (2nd answer there is correct), but essentially Qt comes with a bunch of `.qm` files for its internal strings like buttons and other UI elements.  In a downloaded Qt SDK they're in the `Qt/<x.y>/<toolchain>/translations` folder, broken up somewhat by module (most/all stuff we need should be in `qtbase` and maybe `qt`).  They can be packaged with an app same way as custom translations (either qm files in a folder with the app, or embedded into a resource file like we do now.)  Multiple translation files can be used in an app at once: http://doc.qt.io/qt-5/qcoreapplication.html#installTranslator

The minimize/maximize buttons (as in one of the screens above) are controlled/drawn by the OS.  However we already learned recently that Windows hasn't updated the MDI sub-window design in several iterations, so that could be the reason why the main window min/max buttons are translated, but not the sub-window ones.  I'm not sure if installing the Qt translations will help in this particular case, but I'm guessing not.

**Comment by 3djc** [comment]
Well, I was calling on the most knowledgeable person I know around Qt :) I did read the link on how you can replace those default translations by your own, what I did not understand it why on a common language like french, there not there 'by default'. Maybe we should try packaging those default translation, it surely make more sense than try to redo all those ?

**Comment by 3djc** [comment]
@LapinFou , here is an up to date file
[companion_fr.zip](https://github.com/opentx/opentx/files/854112/companion_fr.zip)

**Comment by LapinFou** [comment]
@3djc : thanks for the file. I will have a look.

**Comment by LapinFou** [comment]
@3djc 
I push the latest translation #4657 according your .zip archive.

**Comment by LapinFou** [comment]
Hi folks,

In order to track the progress between the RC13 and the RC14 (N366) none of the previously issues named in this ticket have been fixed.
In the RC14 (wahouuuu, the Companion simulator is getting better and better. You are greats!!! 💯 ), I discovered few more missing tr():
![tmp](https://cloud.githubusercontent.com/assets/1685030/24240601/85225f26-0fb2-11e7-9552-38a587c85487.png)

**Comment by mpaperno** [comment]
The top 2 are brand new as of yesterday... what's taking you so long to translate them?   😛 

The last one (file type name) is actually hidden in a macro (in constants.h) and right now is not translatable... will put that on the "to be fixed" list.

I'm taking care of getting the Qt translations included and also make it easier to preview new translations within Companion/Simulator while working on them (w/out re-compiling).

**Comment by LapinFou** [comment]
OMG!!! I'm one day late!! 😓 
Understood for the file extension.

Being able to test Qt translation would be very very handy for translators (helpful to get the context where the text is used). 👍 

Since, I don't have any dev environment (don't want for now, only got a standalone Qt Linguist), could you kindly send me the latest french .ts file?

**Comment by mpaperno** [comment]
"Latest" is relative  😄   We should probably just regen/commit all the .ts files in `next` 

BTW you do not need Qt or any compiler installed to generate .ts files -- Linguist comes with the `lupdate` utility which is what is used to generate .ts from code.  (You also use the included `lrelease` utility to generate the final binary `.qm` file from `.ts` file.)  You do need the full OTx source code available, but I imagine you have that anyway (if not, you should because it is much nicer for translating to see source code reference).

I think you can run both utilities from a menu in Linguist, but also simple from a command line.  E.g:

`lupdate </path/to/code> -no-obsolete -ts </path/to/file.ts>`

`lupdate c:\OTx\  -no-obsolete -ts c:\OTx\companion\src\translations\companion_fr.ts`

You will see some warnings but that is OK.  The final output should be something like:

```
Updating 'c:/OTx/companion/src/translations/companion_fr.ts'...
    Found 2263 source text(s) (176 new and 2087 already existing)
    Removed 153 obsolete entries
    Same-text heuristic provided 22 translation(s)
```

**Comment by LapinFou** [comment]
Thanks for those nice information. Unfortunately, I installed Qt 5.8.0 on a machine, create an archive with only required .exe/.dll, then uninstall it.
So, in my handmade Qt Linguist v5.8.0, I got only the **lrelease.exe** CLI.
It would be so nice, if you could send me the missing .exe through a ZIP archive.

**Comment by schwabe** [comment]
@mpaperno you add a short "How to translate OpenTX page" in the wiki based on that information? I will then play dummy user and test it for German ;)

**Comment by kilrah** [comment]
I think there's already a page, could be added to it

**Comment by LapinFou** [comment]
@schwabe 
Too easy for you, most of the missing tr() have been found... 😉

**Comment by schwabe** [comment]
@LapinFou I was more thinking about a five to ten step tutorial for using seeking to translate Companion into their language.

**Comment by mpaperno** [comment]
> I think there's already a page, could be added to it

I thought so too but couldn't find it on the GH Wiki.  Is it in some other docs?

**Comment by LapinFou** [comment]
@schwabe I understood. I was just joking. 😃 
Concerning the wiki, it could be nice to have a standalone Qt Linguist archive. Here is my handmade version (as explained previously, some executable are missing).
[Qt_Linguistv5.8.0.zip](https://github.com/opentx/opentx/files/865505/Qt_Linguistv5.8.0.zip)

**Comment by kilrah** [comment]
Possible it was removed becasue so outdated it had to be rewritten from scratch anyway

**Comment by mpaperno** [comment]
I can't believe there's still no easy way to d-load Linguist separately.  Though it is included with each Qt SDK install (using their [online/offline installers](https://www.qt.io/download-open-source/#section-2) ) 

In the installer component selector, choose any desktop OS version (eg. on Windows `MinGW*` or `msvc*`).  After install Linguist will be available in the usual [Start|Applications|Programming] [menu|folder] (depending on OS).

![image](https://cloud.githubusercontent.com/assets/1366615/24260973/cbd62f10-0fcb-11e7-8819-231bff5837b2.png)

It also forces you to install Qt Creator as part of the package.  If disk space is an issue, after install you could delete everything except the `Qt\<x.y>` folder (where "x.y" is Qt version) and still keep using Linguist & tools (it is also possible to "extract" just the few bits actually needed for Linguist to run, like @LapinFou did).

@LapinFou Which compiler (MSVC? Versions?) did you build your Linguist with?  Whatever I send you would need to match.  One way to get the missing bits would be to install the matching SDK (as above) and just get what you need before uninstalling (lots of download though...).

**Comment by kilrah** [comment]
Can find some old releases: https://www.linux-apps.com/content/show.php/Qt+Linguist+Download?content=89360

**Comment by LapinFou** [comment]
@kilrah I tried the old release, but few things was not working well with the generated .ts file.

@mpaperno I don't remember which MSVC version was installed. 2 solutions:
1. You have a look in my .zip file → [Qt_Linguistv5.8.0.zip](https://github.com/opentx/opentx/files/865505/Qt_Linguistv5.8.0.zip). Then, you make the "full" handmade version. This version (if this is legal), could be downloaded somewhere int the Wiki. Thus, others translators can be "up and running" in no time.
2. I will install again Qt on my PC and make myself a 5.8.0 standalone version.
Since, I can easily guess than you are very very busy, I'm not sure you will have sometime for the 1st solution.

**Comment by mpaperno** [comment]
Qt translations DO handle the MDI subwindow controls  :)

![image](https://cloud.githubusercontent.com/assets/1366615/24268275/93130122-0fe3-11e7-8e94-b20bad81d3d0.png)

**Comment by mpaperno** [comment]
@LapinFou I packaged up a version of Linguist from my local Qt SDK install.  You could see if this works for you.  Just unzip somewhere and run `linguist.exe`.  If it works we could make this available somewhere from the OTx site/wiki (this one is Windows-only, obviously).

http://max.wdg.us/OpenTX/QtLinguist-5.7.1-msvc2015.zip

I see `lupdate` does not have a menu option in Linuguist so indeed it must be run from a command line.

**Comment by LapinFou** [comment]
Just tried. Qt Linguist doesn't work, I got this error message:
![tmp](https://cloud.githubusercontent.com/assets/1685030/24271966/844d191a-101b-11e7-8377-8487590f1f20.png)
I think the sub-folder **platforms** is missing. In this sub-folder, the file **qwindows.dll** should be present.

I tried the CLI. It works!! 👍
```
D:\GitHub\Qt Linguist>lupdate.exe D:\GitHub\OpenTX -no-obsolete -ts  D:\GitHub\OpenTX\companion\src\translations\companion_fr.ts
Scanning directory 'D:\GitHub\OpenTX'...
D:/GitHub/OpenTX/companion/src/firmwares/opentx/opentxinterface.cpp:732: Qualifying with unknown namespace/class ::OpenTxFirmware
[...]
D:/GitHub/OpenTX/radio/src/switches.cpp:936: Parenthesis/brace mismatch between #if and #else branches; using #if branch
D:/GitHub/OpenTX/radio/src/switches.cpp:724: Unbalanced opening brace in C++ code (or abuse of the C++ preprocessor)
Updating '../OpenTX/companion/src/translations/companion_fr.ts'...
    Found 2317 source text(s) (0 new and 2317 already existing) 
```

**Comment by mpaperno** [comment]
> I think the sub-folder platforms is missing. In this sub-folder, the file qwindows.dll should be present.

You're right... and it is present I just put it in the wrong place... d'oh!  Drag the 3 folders inside the `plugins` folder up one level (same directory as `translations`).   LMK if that works.

> I tried the CLI. It works!

👍

**Comment by LapinFou** [comment]
@mpaperno I just tried. Moving the folder **printsupport**, **platforms** and **imageformats** from the __plugins__ directory to the root one di solved the problem.
This standalone version is working perfectly on my Win10 64bits PC.
Thanks! 👍

**Comment by mpaperno** [comment]
Thanks for letting us know!  It now has an official home:  http://www.open-tx.org/2017/03/24/QtLinguist-download   😹 

Still need that translators instructions page for the Wiki though...  which also got a reorganization BTW (so it's all ready for new content 😉 ).

**Comment by LapinFou** [comment]
I'm quite busy right now, but I will try to create an up-to-date "Translation tutorial".

I generated the latest french .ts file. I got one question:
In the section **Multiprotocols**, the translations in the file _opentx\companion\src\multiprotocols.cpp_ are only for Companion? Or are they also used for the OTX firmware itself? Just to know if a can or not use some foreign characters.

**Comment by schwabe** [comment]
Only companion. Radio has its own translation mechanism that is not compatible with companion.

**Comment by LapinFou** [comment]
Thanks. Good to know.
