### ISSUE TITLE
Design N364 Radio Output Channel Pointers  should be coloured like V2.19 was

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#4638]
Hy,
to see the channel pointer position better at Radio Output Simulator 
they should be coloured like V2.19 was, blue or green or red.

Or can I set it somewere?
Win7 prof openTx V2.20N364

**Comment by hrenz** [comment]
Channel  Position Pointer not coloured, bad to see.
![2017-03-20_183054](https://cloud.githubusercontent.com/assets/6217896/24113038/b60daa82-0d9b-11e7-843b-82fb0b12e6c9.jpg)

**Comment by mpaperno** [comment]
Would this be better?  

![image](https://cloud.githubusercontent.com/assets/1366615/24165887/0b7a1fc6-0e48-11e7-8b7d-c18d14be3d18.png)

**Comment by mpaperno** [comment]
Or actually darker color on bottom, I think... ?

![screenshot](https://cloud.githubusercontent.com/assets/1366615/24175800/a3eba452-0e6e-11e7-9e41-2be65d0dfb50.png)

**Comment by kilrah** [comment]
Prefer the 2nd :)

**Comment by hrenz** [comment]
2nd looks fine 
thanks
