### ISSUE TITLE
Multi subtype broken on ar9x

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#4641]
Subtype name not even appearing
Example: DSM

**Comment by schwabe** [comment]
It works fine on my AR9X simulator and current next: 

![image](https://cloud.githubusercontent.com/assets/1038539/24104636/019e5668-0d83-11e7-9c60-e5bd9a6830f9.png)

is that just on the radio itself?

**Comment by kilrah** [comment]
Possibly then, someone reported it dodn't work on their radio, I checked and it doesn't work on mine either

![20170320_161507](https://cloud.githubusercontent.com/assets/6065069/24106598/a553a5a6-0d88-11e7-9a0a-c181b5908985.jpg)

**Comment by schwabe** [comment]
that might be because of the way how I store the strings. Are String on Atmels arm somehow special (like AVR's strings)?

**Comment by kilrah** [comment]
Yep I do have the 2 0's in Custom mode!

**Comment by bsongis** [comment]
I don't think this commit will fix the issue though!

**Comment by kilrah** [comment]
It did!

**Comment by bsongis** [comment]
cool then :)

**Comment by schwabe** [comment]
I don't really understand why that commit fixes it. But at least it is fixed now.
