### ISSUE TITLE
Companion export to AR9X (and co?) potentially broken

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#4651]
Needs verification

https://www.rcgroups.com/forums/showpost.php?p=37145225&postcount=110

**Comment by mpaperno** [comment]
I just experienced the last part of that post -- inputs (and maybe other stuff) are being exported wrong from Companion.  Reproducible in the simulator...

![image](https://cloud.githubusercontent.com/assets/1366615/24137764/9fa32c18-0deb-11e7-8f39-5677d8a4ed4e.png)

Models created on the simulator and existing/known-good files run fine directly in standalone Simulator.

**Comment by bsongis** [comment]
This one should be fixed, feel free to reopen if needed
