### ISSUE TITLE
RC13 N365: LUA panic / not enough memory with BF lua script

### ISSUE THREAD

**Issue by RipperDrone** [opentx/opentx#4659]
RC13 throws memory error when installing BF lua script: 

https://github.com/betaflight/betaflight-tx-lua-scripts/tree/c51d80d24e7a2f53f0bfc72d1d64c48a06031514

HAve asked the BF dev team for analysis, too: https://github.com/betaflight/betaflight-tx-lua-scripts/issues/24

**Comment by kilrah** [comment]
Try both versions on RC12, if you've got the same result it's not on our side.

**Comment by RipperDrone** [comment]
Hmm, radio shows some 19k free memory, doesn't indicate low memory actually...

**Comment by RipperDrone** [comment]
@kilrah has been fixed:

- I had non-lua firmware version installed (for some reason, BF lua scripts have been working without the lua / luac check boxes ticked throughout v0.3, though).
- PID values were lost due to a bug in the script. Has been fixed now.

**Comment by kilrah** [comment]
Standalone and telemetry scripts don't need lua ticked.

**Comment by RipperDrone** [comment]
I see, this explains it 👍 Thank you so much.

**Comment by kilrah** [comment]
Well it precisely doesn't!

**Comment by RipperDrone** [comment]
rev 0.3 of the script was a standalone version. Splitting it into multiple files came post v0.3, so this might have rendered the script into "non-standalone"?

**Comment by kilrah** [comment]
No. The option refers only to mixer scripts.

**Comment by RipperDrone** [comment]
ok - well, then you are leaving me partly puzzled. Still happy it's working now...
