### ISSUE TITLE
RSSI and Rx Battery voltage not actual values

### ISSUE THREAD

**Issue by mpjf01** [opentx/opentx#4663]
At present it seems that if telemetry is lost the RSSI and RxBatt telemetry values being displayed on the screen and being logged are maintained at whatever they were when the last valid value was received. (If the radio is in RT mode the RSSI value shown in the RT window is the actual value (zero) in this situation.)

Clearly there are reasons for not displaying and logging the actual values being received as OpenTx was changed from displaying actual values to displaying last good values. 

There are also reasons why it is desirable to be displaying and logging the actual values.

Would it be possible to give the user the option over which situation was to apply? Maybe as a different compile option or a setup option in the radio or model setups.

**Comment by RealTadango** [comment]
Same issue as https://github.com/opentx/opentx/issues/4629

**Comment by RealTadango** [comment]
#4629

**Comment by 3djc** [comment]
I guess it can be debated if 0 is a more actual value than last one, since there is no new value. The fact that you do not received telem anymore doesn't mean the receiver is receiving 0 volts, or the rssi is 0 (actually, you might very well  still be in control of the craft).
Don't think a per model or compile option would work very well with scripts.
Maybe we can have more info on the situation where you find it been an issue ?

**Comment by kilrah** [comment]
I believe the display shouldn't be changed (it already should signal the lack of data either by flashing the numbers or displaying NO DATA), but it would be good to have a "No data" or "invalid" indicator in the logs, which could be 0.

**Comment by 3djc** [comment]
or not logging it at all ?

**Comment by RealTadango** [comment]
Mmh, making the value missing is a very common solution.... the graphing tools could show them by a different colors / dotted line to indiate no data was receivers for that sensor value.

**Comment by kilrah** [comment]
> or not logging it at all ?

Yes why not, might need siginificant changes in companion though, need to also make sure that works with other way to graph (e.g. excel)

**Comment by RealTadango** [comment]
After what time do you consider it missing? The same timeout as for the sensor lost warning?

**Comment by kilrah** [comment]
no much shorter, about 1 sec I believe.

**Comment by kajsilander78** [comment]
Why not add a variable that zeroes out on telemetry lost, that would give the option to reset any telemetry you like with "Reset" under "special functions"?

**Comment by teckel12** [comment]
When telemetry is lost, we know that it's lost, and I think it makes the most sense to see the last value.  An individual telemetry sensor can be lost, not all.  So in all cases, it makes sense the way it is now.  We know telemetry is lost, and we get the last good value.

**Comment by mythreeleggedcat** [comment]
Since there is now an implicit Tele "switch" in OpenTX 2.2.X  which has states Tele and !Tele,  why not log that along with the other intrinsic switches?  This would explicitly indicate in the log when telemetry is being received.
