### ISSUE TITLE
[Horus] Serial port options not implemented / Emergancy mode

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx#4664]
The serial port options under the Hardware section is not working / implemented. When set to SBUS trainer the internal serial port header does not accept any S.Bus input. When set to Telemetry the Horus goes into Emergancy mode.

This might be related to https://github.com/opentx/opentx/issues/3954 if the internal UART header RX pin is the same as the heartbeat pin.

**Comment by 3djc** [comment]
This option will be made unavailable for 2.2.0 release. We will come back to it and make it work at a later point in time

**Comment by kilrah** [comment]
Temp fix in 9ff1dab6b83b15e30aafda03b70732c20b91b54d

**Comment by raphaelcoeffic** [comment]
@3djc @kilrah has anything been done here? if it is hidden, there is no "bug" anymore. The feature request is still in #3954.

**Comment by 3djc** [comment]
there is nothing hidden ...unless I  misundersdant what you mean by that

**Comment by raphaelcoeffic** [comment]
> there is nothing hidden ...unless I misundersdant what you mean by that

Unless you have `DEBUG` defined, it seems to be hidden when looking at the code. Did I miss something?

**Comment by 3djc** [comment]
well it has a serail debug purpose when DEBUG is enabled, but when not, it is hidden since it does not 'do' anything, so I guess we can close that if that was the bottom of your question

**Comment by kilrah** [comment]
#3954 is different, it's about the heartbeat pin. This is about the serial port. On other radios we have several functions available on the serial port, on Horus it was broken hence this issue. To avoid people having their radios crash when selecting a function the whole thing was hidden by adding the DEBUG condition (so whoever wanted to fix it could access them for testing), but the correct thing is to fix those functions and then make them available again. If not, to remove the choices completely
