### ISSUE TITLE
Opentx RC12 play on FPV Simulators

### ISSUE THREAD

**Issue by Dutchy-79** [opentx/opentx#4665]
Hi,

I haven't played with FPV Freerider and Lift-Off for a while now but when I just tried the Taranis won't connect as joystick anymore, With the TX ON I plug in the USB cable and it shows the 2 drives instead off joystick.

I think I must have missed something during setup I do have CLI unchecked and flashed firmware 2.2.0N365 (b443d4b6)

Any suggestions?

Jasper
![settings opentx 2 2 0n365](https://cloud.githubusercontent.com/assets/22749572/24189610/f8497b42-0ee5-11e7-8865-115f37a5c965.jpg)

**Comment by schwabe** [comment]
disable massstorage. If you enable massstorage it disables joystick functionality.
