### ISSUE TITLE
Radio.bin not consistent to model number Horus

### ISSUE THREAD

**Issue by 1Sven** [opentx/opentx#4674]
I was build 15 models in Horus TX. Then I've deleted 5. If  I create a new model, it becomes a
model 11 with a model.bin 16?
Ok, I was deleting  this model. Even when I make a new model, the model.bin is +1 up.
When I'm using the companion for a new model, everything is conform. But the Horus
remember permanent the highest radio.bin and creates a new radio.bin +1 when make a new
model.

**Comment by kilrah** [comment]
Normal and intended. There is no "model number" on Horus.
