### ISSUE TITLE
Companion Simulator for X7 on Win10, RC14n366

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#4678]
Am I missing a setting somewhere?  
The simulator for X7 has no switches showing.

and in Companion, the model settings has no Switches showing  position for checking on model selection.
Oops, The switch settings for model selection does not show on the transmitter either.

![n366 simulator](https://cloud.githubusercontent.com/assets/4843199/24276764/2dede11e-0ff6-11e7-90f2-446ff28a6350.PNG)
either

**Comment by 3djc** [comment]
![image](https://cloud.githubusercontent.com/assets/5167938/24282194/4bcabd48-105e-11e7-8c33-1ef67df1f0e4.png)

The simu reads the actual radio settings (in hardware section); so for some reason you do not have the switches declreed there I would think.

![image](https://cloud.githubusercontent.com/assets/5167938/24282246/90a1ebd0-105e-11e7-8620-df617dadd4a1.png)

**Comment by rdeanchurch** [comment]
You are correct.  
I don't see how those went away on my computer, but they were gone.
Thank you.
