### ISSUE TITLE
Mixer Scripts is paused N366 Horus

### ISSUE THREAD

**Issue by 1Sven** [opentx/opentx#4680]
If on a model a mixer script runs and you start a script like LogGra, BFSetup and so on,
the mixer script still is pausing. May be that is not so important, but it is god to now.
If you think you can change the power of the VTX (like trump) in flight, don’t do that if you have a running mixer script.

**Comment by RealTadango** [comment]
That is by design. The one time lua environment replaces all other, like mixer and widgets.

**Comment by 3djc** [comment]
On top of that, you should never have mixer scripts (or other scripts for that matter) that perform critical operations, as in case of emergency reboot of the radio, you do not have Lua at all for example
