### ISSUE TITLE
Different channels behaviour in simulator

### ISSUE THREAD

**Issue by OpenMik** [opentx/opentx#4681]
Channels visualizations have different behaviour in simulator
Companion 2.2.0N366

![optx](https://cloud.githubusercontent.com/assets/24204587/24315416/2e5f78c8-10e7-11e7-8afb-ddd37ac4cd3c.png)

**Comment by 3djc** [comment]
Duplicate : #4619
Display rouinding error that has been fixed

**Comment by OpenMik** [comment]
Companion was downloaded by PPA
I'm on Xubuntu 14.04
today it was compiled from source
![optx1](https://cloud.githubusercontent.com/assets/24204587/24320608/049b74cc-1139-11e7-92dc-3c70c2672065.png)
but the behaviour is the same
I suppose that I do something wrong, but I don't know what

**Comment by 3djc** [comment]
Indeed, I get the same results,  it was marked as fixed, but apparently not

**Comment by projectkk2glider** [comment]
I bet rounding is not working correct for negative numbers only.

**Comment by 3djc** [comment]
Yes, I'm on it
