### ISSUE TITLE
Mixer screen channel names misplaced on Q X7

### ISSUE THREAD

**Issue by cprinos** [opentx/opentx#4690]
On the mixer screen, if the selected channel has a name, the name appears at the top (overwriting the mixer count display) and disappears from it's normal position on the right

Ch1 ("a") selected:
<img width="488" alt="mix-cha" src="https://cloud.githubusercontent.com/assets/671656/24324635/61e585a6-1160-11e7-85a0-3b80b037632c.png">

Ch2 ("b") selected
<img width="527" alt="mix-chb" src="https://cloud.githubusercontent.com/assets/671656/24324636/650ab7d8-1160-11e7-8918-34c8c74921c1.png">

Ch3 (no name) selected
<img width="485" alt="mix-ch3" src="https://cloud.githubusercontent.com/assets/671656/24324643/944c80e4-1160-11e7-97f9-0c198945a1d2.png">

**Comment by 3djc** [comment]
It is purposefully done like this (the space is used to display more mix info) , but it should not conflict with the count
