### ISSUE TITLE
Companion (N366) does not keep Vario source when I import models from Horus

### ISSUE THREAD

**Issue by Red-Devil74** [opentx/opentx#4696]
When I Import the models from the Horus with Companion (N366, Mac OS X), The Telemetry tab shows three dashes at "Vario Source" while it is set as Vspd (and working) in the Horus.

![image](https://cloud.githubusercontent.com/assets/23432540/24334767/c478f4b2-1270-11e7-808a-993eee9ea49a.png)

**Comment by 3djc** [comment]
When you simulate this model, is it ok on the simulated radio?

**Comment by Red-Devil74** [comment]
That is funny. It shows in the sim but if I enable th telemetry vario, I do not hear the sounds when I raise or lower the altitude. I do not know if it ever worked (like this) in the sim, however...
![image](https://cloud.githubusercontent.com/assets/23432540/24347110/846075b4-12d7-11e7-97f9-12bc1cf2783e.png)
