### ISSUE TITLE
Taranis Q X7 flash X8R problem

### ISSUE THREAD

**Issue by yoann217** [opentx/opentx#4701]
I can't flash an X8R with the file from frsky (X8R_150115).
QX7 running on 2.2.0 RC14 (N366), x8r is correctly powering on, but when trying to flash the file on the x8r I have an error : "fw update error not responding".

I success to flash the same X8R with the same file on x9d plus with 2.1.9.

**Comment by 3djc** [comment]
I have no issue here doing that.

1) does your x7 have a connector at the bottom ?
3) how are you connected when you trie that ?

**Comment by yoann217** [comment]
1) yes
2) in the external module bay like the x9d

**Comment by 3djc** [comment]
You cannot do that, if you have the bottom connector on x7, you have to use it to flash external
