### ISSUE TITLE
Missing FR translation on the Horus

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#4702]
Hi folks,

When using Companion (French version), the default created category with a Horus profile is always in English.
I guess this one is a special one (common with the radio firmware).
![tmp](https://cloud.githubusercontent.com/assets/1685030/24348524/4b19e0ce-12dc-11e7-8bf5-7a6f2885aa5c.png)

**Comment by LapinFou** [comment]
Similar issue: when importing models (_Mod**è**les_ in French) from a X series radio to the Horus, the foreign character is not converted.
![tmp](https://cloud.githubusercontent.com/assets/1685030/24348644/b2ac7918-12dc-11e7-9888-ee37d657e4a0.png)

**Comment by 3djc** [comment]
There should not be an accent there since radio can't display it. I guess a translation has an accent where it should not

**Comment by LapinFou** [comment]
I guess so, but when the Companion translation is done, it is hard to know if it is a special case or not. Unless there is a way with Qt to display a programmer comment in the .ts file in order to warn the translators.

**Comment by 3djc** [comment]
I've just pushed a change with a warning for translators, you should be able to see it, let me know if this is not the case (this instance of models is modellist.cpp line 281 (280 before the change)

**Comment by LapinFou** [comment]
I tried on the **next** branch, but it didn't work. See the generated .ts file
![tmp](https://cloud.githubusercontent.com/assets/1685030/24415313/5b967fe2-13e1-11e7-8371-7b03551b9c02.png)

**Comment by kilrah** [comment]
It probably won't work if you don't have the full environment setup. It needs to be able to find the source files and display the contents on the "Sources" panel..

![capt](https://cloud.githubusercontent.com/assets/6065069/24415426/ba92f7f0-13e1-11e7-9ac9-069feb5e09f1.png)

**Comment by 3djc** [comment]
Wrong one:

![image](https://cloud.githubusercontent.com/assets/5167938/24415580/3193a69c-13e2-11e7-84f2-fd4266e6dd48.png)

**Comment by mpaperno** [comment]
Those `QObject::tr`s should really be qualified with a namespace... but there are 438 of them...  😮

**Comment by mpaperno** [comment]
Actually... `TreeModel` inherits from QObject so the `QObject::` qualifier should just be removed in this case... not sure why it's there.

**Comment by LapinFou** [comment]
Indeed it was the wrong one (didn't realized at the same time you added the **Developer comments**, you fixed the issue 😓 )
![tmp](https://cloud.githubusercontent.com/assets/1685030/24417244/f1d47b7a-13e7-11e7-8560-b10ec4525619.png)
