### ISSUE TITLE
PL 2.2 Compilation error.

### ISSUE THREAD

**Issue by driver33** [opentx/opentx#4703]
I have faced following error when trying to pull firmware via CompanionTX 2.2:
"Compilation Error"
Options of firmware I made on : 
Taranis X9D
ppmus
eu
lua
massstorage
sqt5font

**Comment by schwabe** [comment]
```cmake -DPCB=X9D -DPPM_UNIT=US -DLUA=YES -DUSB=MASSSTORAGE -DFONT=SQ5 -DSUPPORT_D16_EU_ONLY=YES ~/oss/opentx``` runs fine here on the 2.2RC14 tag.

**Comment by driver33** [comment]
try Language=pl.

**Comment by schwabe** [comment]
``` cmake -DPCB=X9D -DPPM_UNIT=US -DLUA=YES -DUSB=MASSSTORAGE -DFONT=SQ5 -DSUPPORT_D16_EU_ONLY=YES TRANSLATIONS=PL -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5  ~/oss/opentx``` still works fine for me. Might be something to do with toolchain versions or someone who has access to the compilation server has to check the logs.

**Comment by driver33** [comment]
Still unable to pull firmware night-builds PL version - setup of the firmware : all OFF; Language PL.

**Comment by 3djc** [comment]
And it will remain like that until next nightly

**Comment by driver33** [comment]
Isn't it go directly from NEXT ?

**Comment by 3djc** [comment]
No, it will only when we reach release

**Comment by driver33** [comment]
OK closing it then.
