### ISSUE TITLE
Acceleration while button pressed (Otx 2.2)

### ISSUE THREAD

**Issue by flarssen** [opentx/opentx#4713]
Things like setting boarders for telemetry bars, like -/+ 10.000, or selecting an audio track starting with 'M' is currently a slow process. It would be useful to speed up these things if a button is pressed for a certain time.

**Comment by kilrah** [comment]
Radio type?

**Comment by flarssen** [comment]
Taranis X9D.

**Comment by projectkk2glider** [comment]
Some numeric selectors already have the acceleration so we just need to enable this in more places. But file list selectors are in a different category and would require a separate solution.
