### ISSUE TITLE
MULTI protocol not showing in External RF protocol 2.2.0N366 build

### ISSUE THREAD

**Issue by asmeureanu** [opentx/opentx#4725]
I have upgraded the Taranis X9D+ to opentx-x9d+ with appropriate SD card data however the
MULTI protocol not showing in External RF protocol list.

**Comment by 3djc** [comment]
Have you selected  multiprotocol in the options ?

**Comment by asmeureanu** [comment]
Is there an extra option excluding the External RF protocol slot that is missing?

**Comment by 3djc** [comment]
![image](https://cloud.githubusercontent.com/assets/5167938/24546755/0644a856-160d-11e7-9836-bfe6c5dab246.png)

**Comment by asmeureanu** [comment]
this is in the companion, let me check and confirm

**Comment by asmeureanu** [comment]
non issue had wrong non multi module fw flashed

**Comment by lauchablanca** [comment]
Hola gente. Mi QX7 tenía la versión 2.3.0, pero no veía la opción MULTI Módulo.
Tuve que hacer un DOWNGRADE, a la versión 2.2.4, para poder elegir la opción MULTIMÓDULO en el Companion.
Por qué desapareción esa opción desde la versión 2.2.4 en adelante?
No se puede agregar a versiones posteriores a 2.3.0?

**Comment by 3djc** [comment]
English only please
