### ISSUE TITLE
taranis x9E trainer output menu missing

### ISSUE THREAD

**Issue by bosshog99** [opentx/opentx#4730]
this is an update to the previous message.  i have found the problem to be with the menu of the taranis X9E transmitter.  the option that is missing is the setting for the trainer port in the model menu.  this does not allow for setting the trainer port mode from the transmitter.  i discovered this when i opened companion software, which this option is shown.  when i changed the trainer port to CPPM and downloaded it back to the transmitter it worked. 

please fix this so that you can select the trainer port mode from the transmitter like ver. 2.1.8, as most of us don't take computers with us to the flying field.

great work!

hello,

i've been using the X9E with a futaba (slave) with a DFT module installed.  the master (X9E) is using the aloft hobbies linker which has a D4R-II.  this setup worked perfectly with version 2.1.8.  after upgrading to 2.2.0N367 i can no longer use my trainer radio.  i have tried to rebind, create new models and nothing seems to work.  setting are on PPM as before.  it seems that the transmitters are binding fine but when i flip the momentary switch none of the values are passed between the two transmitters.  yes the switch is setup in the special functions menu, the protocol is PPM (timing set as before, default) in the master radio the trainer menu has been configured and the slave radio nothing has been changed and is configured correctly.

is anyone else having this issue?  # #

**Comment by 3djc** [comment]
You mean this :
![image](https://cloud.githubusercontent.com/assets/5167938/24848710/4ebf8912-1dc8-11e7-8fbb-f4e28103ae4f.png)

**Comment by bosshog99** [comment]
yes, correct!  in the X9E the last option that shows on that screen from External RF is:
External RF
>MODE
>Bind on powerup
>Low power mode
>> then it scrolls back to the top <<  to Model name
there is no way to use the trainer function from the radio.

**Comment by 3djc** [comment]
Well that's taken from X9E. Here is one taken from a real radio, so it is there ....
![image](https://cloud.githubusercontent.com/assets/5167938/24893640/3560408e-1e85-11e7-8276-d0f725ce0e50.png)

**Comment by kilrah** [comment]
> Bind on powerup
Low power mode

These are multiprotocol options that do not exist in official 2.1 OpenTX.  You're probably using the unofficial builds that include it and it's broken in those. Nothing we can do about it. Use OpenTX 2.2 instead, either now or after waiting for official release.

**Comment by schwabe** [comment]
As a sidenote, even in newer 2.1.9 inofficial builds the problem should be fixed but as @kilrah said, if you want multiprotocol support use OpenTX 2.2

**Comment by bosshog99** [comment]
guys, i am using 2.2.  ver. 2.2.0N367 exactly.  do you mean that i need to downgrade to ver. 2.2?  is the 0N367 part an unofficial build of 2.2?

sorry for my lack of understanding.

**Comment by 3djc** [comment]
As shown in the photo above, on N367 the option IS present. Please give us you OTX or more info
