### ISSUE TITLE
First use of companion suggestion.

### ISSUE THREAD

**Issue by Engineereric** [opentx/opentx#4731]
When you install companion and run it for the first time it tells you that the firmware has not been downloaded and asks you to do so. Unfortunately it is some unknown version for an unknown radio.
I couldn't find any quick start guide (and I don't think it needs it because it is an excellent simple to use program) but rather than ask you to down load the firmware.
It would be far far better to ask you to select your required configuration first.
Some thing simple like a message "no radio configuration selected would you like to select your preferences now?"
If I knew what IDE was used I could probably do it.
Any way just a suggestion and good work every one.

**Comment by kilrah** [comment]
Yup, one of my pet peeves as well... Might be a bit complicated technically but would be great to find a solution.
