### ISSUE TITLE
Companion Simulator N266,  at Horus settings of Mainscreens are not stored

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#4745]
At Companion Simulator N266 
I can set the Hours mainscreens and user interface with theme and widgets 
thats all fine, works fine, but my settings are not stored.

close simualtorscreen, open again, all my settings are back to start

Modell files are stored and reopened

at older V2.20 the mainscreen settings are stored, I am shure

Is it only may Problem or a real Issue?

**Comment by 3djc** [comment]
Simu launched from within companion do not store anything. Are you talking about the standalone simu or companion one?

**Comment by 1Sven** [comment]
I have the same thing, it is on the standalone simu.

**Comment by kilrah** [comment]
Are you sure you're then reading the proper location into companion? Horus standalone simu can raccess data from multiple different locations, what you select is obviously where the changes will be applied, need to read from the right place to see them.

**Comment by hrenz** [comment]
I have tested Companion N366
from there started the Simulator the and set the Horus Mainscreens

**Comment by mpaperno** [comment]
There are 3 options for Horus data (radio & model settings) when starting the standalone Simulator.
1. A .otx file (or zip archive containing RADIO and MODELS).
1. A folder containing RADIO and MODELS folders.
1. Using RADIO and MODELS in the usual SD card path (this is how an actual radio would start).

So, which way(s) are you using when the issue occurs?  Have you tried using the other methods to see if the problem persists?

**Comment by kilrah** [comment]
> I have tested Companion N366
from there started the Simulator the and set the Horus Mainscreens

When launched from Companion the simulator never saves any change, it has been that way forever.

Use the standalone "Firmware simulator" with an appropriate data source if you want changes saved.

**Comment by mpaperno** [comment]
Well, @1Sven did specifically mention the standalone simulator, so I'm still wondering if there's an issue here or not.

**Comment by kilrah** [comment]
Ah yeah, missed that... might be some confusion there :\

**Comment by 1Sven** [comment]
I have changed to "Folder" then it works. I think, it is a issue of me...
