### ISSUE TITLE
2.2 flash extern device not work

### ISSUE THREAD

**Issue by frobert0** [opentx/opentx#4746]
X9E after update to 2.2, flashing external device not work
At 2.1.9 comes bars
At 2.2 no bar and after some time error message

X9E back to 2.1.9 and flashen the external devices works

sorry for my English, and translated by google

![20170403_211045](https://cloud.githubusercontent.com/assets/12582649/24626851/f074fcee-18b2-11e7-9e8e-e930c3201e67.jpg)
![20170403_211113](https://cloud.githubusercontent.com/assets/12582649/24626850/f072895a-18b2-11e7-88d1-5744c839408f.jpg)

**Comment by 3djc** [comment]
Just tested it, works fine

**Comment by frobert0** [comment]
At 2.1.9 waits longer for boot
And the option goes as in the picture attachment
![github](https://cloud.githubusercontent.com/assets/12582649/24721157/aeafa17c-1a3f-11e7-861a-d1d7d3f9767e.JPG)

bei 2.2. nur durch Vmain
![github](https://cloud.githubusercontent.com/assets/12582649/24721216/e1da4c64-1a3f-11e7-8b69-67c10b7fb9c5.JPG)

**Comment by 3djc** [comment]
You don't need anything special since frsky receiver accept a wide voltage range. A simple cable with 2 wires crossed. Did flash x6r, x8r and s8. So it definitely works

**Comment by projectkk2glider** [comment]
Not really both d8r and x8r have `Operating Voltage Range: 4.0~10V`. X9E has 8 cell battery.

But I looked at the differences between 2.1 and 2.2 code and could not find any - the power on delay is the same in both versions.

**Comment by 1Sven** [comment]
I use a simple 25 Ohm resistor in the + wire. For the scary users...
Testet with many receivers, vario and the redundacy bus.

**Comment by schwabe** [comment]
check that you really use the smartport and not the sbus port
