### ISSUE TITLE
Q X7 Switches are Missing in Menus

### ISSUE THREAD

**Issue by redbeardfpv** [opentx/opentx#4748]
I am new to OpenTX so if this isn't a bug please let me know, but I have looked for days for a solution.  
I am on 2.2.0 N366 and since flashing away from the 2.2 build that ships with the Q X7 I can't get any switches to work, The sticks, pots and trims are available but not the switches. 

On the Inputs or Mixer  screen when I try to select a source only the sticks, pots and trims are available.  If i long hold and scroll down to switches I can assign SA but the switch doesn't function (the value in the graph never changes), and if I scroll away from SA in the source after using the long hold to get there it is not in the list anymore.  

I am not sure what other information to provide but if there is someone available to help troubleshoot please let me know. 

Thanks, 

RedbeardFPV

**Comment by 3djc** [comment]
I'm not sure of what you do exactly, but It seems to be working here.

In INPUTS screen,, use rot wheel to get to source, push rot wheel, field is blinking, move the switch you want, it is selected

![image](https://cloud.githubusercontent.com/assets/5167938/24643816/719928c4-1910-11e7-9753-6598d94028c6.png)

If I then move the switch you see the vallue change (low, mdedium, up)

![image](https://cloud.githubusercontent.com/assets/5167938/24643865/a518ec3e-1910-11e7-9478-979dcfd40471.png)

![image](https://cloud.githubusercontent.com/assets/5167938/24643881/b5fd0f1c-1910-11e7-9f50-2117171cd8d5.png)

![image](https://cloud.githubusercontent.com/assets/5167938/24643886/bfdc4674-1910-11e7-99e5-7a8cb5ae49f6.png)

**Comment by kilrah** [comment]
Check the switches are set to the correct types on the "Hardware" page, you probably wiped them through some improper Companion manipulation.
