### ISSUE TITLE
Add setting to reduce the range of "throttle trim only"

### ISSUE THREAD

**Issue by MikeBland** [opentx/opentx#4752]
See this thread for details of why this is useful: http://openrcforums.com/forum/viewtopic.php?f=96&t=10056
Currently "throttle trim only" applies full trim range at -100% throttle and reduces the applied trim range linearly up to +100% throttle. For helis, this can cause a problem if the throttle uses a curve. It appears the ideal would be to have the throttle trim just adjust the first point of a curve, but using a setting as I describe achieves the same result.
I have already implemented this in ersky9x, only took a few minutes.

**Comment by projectkk2glider** [comment]
My thoughts: the "throttle trim only" is kind of pre-progammed function which is not really in the spirit of OpenTX. It also has some existing problems like #170. The functionality can (easily) be completely replaced by the existing generic OpenTX primitives (like you detailed in forum posts), which also provide more flexibility and also can support cases like this one. 

So my first idea is to remove this. I know this would be hard and would create a lot of problems with existing setups.
