### ISSUE TITLE
Companion 2.2 Duplicate model sometimes launches Model Wizard

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4773]
Post PR #4769 the model is duplicated but then the Model Edit Wizard is launched. Behaviour traced to the Application setting for Action on New Model.
Does not make sense to follow duplication with action based on setting.

Ubuntu 16.04 Taranis X9D+

**Comment by mpaperno** [comment]
Good point.  Do you think it should still launch the model editor instead?  Perhaps only if the "action on new model" preference is set to Model Editor?

**Comment by elecpower** [comment]
Can see a case to always launch Model Edit as unless making a backup one would expect to make some changes to the duplicate.
Leaning towards take 'action on new model' if not Model Wizard set ie Model Editor or do nothing so it leaves the behaviour to the user

**Comment by mpaperno** [comment]
Sounds good to me (if nothing else user probably "should" rename the model anyway).  Now it is so.
