### ISSUE TITLE
X7: Edge LS allows setting a delay on the radio, shouldn't be possible

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#4776]
Companion N368 QX7 
At log switches function edge  has no delay 
All others TX have delay 
![2017-04-11_201215](https://cloud.githubusercontent.com/assets/6217896/24923911/523463f2-1ef3-11e7-8ddd-4b4480109d26.jpg)

**Comment by kilrah** [comment]
Edge cannot have a delay on any radio.
