### ISSUE TITLE
Theme- Screensettings are global

### ISSUE THREAD

**Issue by 1Sven** [opentx/opentx#4778]
If in the modelsettings for one model the theme is defined, it’s for every model the same. It’s like a systemconfiguration, it works global. So it is not possible to make for every model a new theme.
May be it is not a really bug, but then it is not the right structure.

**Comment by kilrah** [comment]
That's how it's intended. Theme is meant to be for the whole radio UI.

**Comment by Enggmaug** [comment]
"having different looks per model has never been considered"
I would like it to be considered. 
I mean, with color LCDs, I believe it makes more sense now than there was back in 2017.

I'm not asking for you guys to change the entire code structure, so as an alternate method, Is it possible to change the theme with a lua script, when the model is changed ?
