### ISSUE TITLE
Companion N368 - Managing Categories

### ISSUE THREAD

**Issue by Alex00101** [opentx/opentx#4780]
Since I have upgraded to N368 there are various side effects when managing categories. The most serious one is when I read models from radio all models get moved to an unknown category. In addition, the only way to rename the category is to double click on a very particular  spot on its name, menu and toolbar do not work. Also there seem to be an issues when writing categories back to the radio. Windows 10.
Reinstalled fresh on a different PC - same results. 

Thanks

**Comment by mpaperno** [comment]
Fixed by 111bcad .

**Comment by Viruswelt** [comment]
When I create a new category under Companion, the program crashes.
OSX 10.12.5

**Comment by kilrah** [comment]
Yep, known and fixed as can be seen above, wait for next version.

**Comment by Viruswelt** [comment]
ok !
thx
