### ISSUE TITLE
[Horus N366] Please put Version Number in About OTX or somwhere

### ISSUE THREAD

**Issue by Joetrin** [opentx/opentx#4782]
Would it be possible to write the version number in the "About OpenTX" section?

That way it's easy to identify which version of OpenTX you're on, and if somehow the IXJT Firmware were possible to be extracted and a version number shown, it would make it easier to diagnose issues.

Thank you

**Comment by 3djc** [comment]
Already in there

![image](https://cloud.githubusercontent.com/assets/5167938/24974926/26ee2224-1fc4-11e7-9127-e50a5a6f9620.png)

**Comment by Joetrin** [comment]
Merci
