### ISSUE TITLE
Taranis becomes mass storage after 2.2 update

### ISSUE THREAD

**Issue by iglogix** [opentx/opentx#4786]
After update to OpenTx 2.2 version, when I connect USB to transmitter it immediately becomes mass storage device instead of joystick, as was the case before the update. As a result I cannot use it with simulators etc.

**Comment by 3djc** [comment]
Masstorage is an option, and still is with 2.2, please make sure you have the right firmware option.

**Comment by atheimer** [comment]
The Mass Storage "build option" has been removed in 2.2.1... See: http://www.open-tx.org/2017/12/16/opentx-2.2.1

There is no a USB option in the main radio menu.  From any model "home screen" press Menu to go to Radio Setup, scroll down until you see USB... change to joystick..
