### ISSUE TITLE
Windows on a 4k display

### ISSUE THREAD

**Issue by austrianglider** [opentx/opentx#4788]
Since version N366, the individual windows, both in Companion and Simulator, are no longer optimally displayed on a screen with 4k resolution (laptop 15 ", 3.840 x 2.160px) and partly too small.
Some windows are too small, so not all fields are available.
In the Simulator the display of the remote control is far too small in the main window. Unfortunately, this window can't be enlarged by mouse.
The operating system is Windows 10.

I added several screenshots in the appendix.
[comp368.pdf](https://github.com/opentx/opentx/files/918772/comp368.pdf)

**Comment by kilrah** [comment]
Fixed in https://github.com/opentx/opentx/commit/78c5bf1ec2cee1dc1145a7c211483fd037d81941
