### ISSUE TITLE
timer - time change

### ISSUE THREAD

**Issue by faphog** [opentx/opentx#4791]
Hello opentx team-
Noticed on my X7 (N368) that when I update the countdown time on e.g. Timer1, it only updates the actual timer after a power-cycle.
Not sure but recall that with earlier builds this was not the case.
Minor issue obviously.
Pls keep up the great work!

Regards,
Floris

**Comment by 3djc** [comment]
That's normal behavior, similar to X9, you can also reload it using long enter, reset flight or reset specific timer
