### ISSUE TITLE
bf lua out memory

### ISSUE THREAD

**Issue by ndalisay** [opentx/opentx#4792]
Not sure if this is opentx issue but after upgrading from rc14 to rc15 I encountered out of memory multiple times.

**Comment by kilrah** [comment]
We can't guess what radio you have.

**Comment by ndalisay** [comment]
Sorry i'm using taranis x9d plus.

**Comment by schwabe** [comment]
I don't have the problem with the current BF script on my X9D+.

**Comment by kilrah** [comment]
Could depend on the options. @ndalisay what's your firmware filename?

**Comment by ndalisay** [comment]
@kilrah I shorten the name so i opened it from the radio. anyway the issue seems to be fixed now in rc18..
