### ISSUE TITLE
RC16 - Q X7

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#4795]
On Q X7 cannot clear a line in Special Functions.  Click clear and the line is still there.  Works OK on the Horus though.

**Comment by 3djc** [comment]
What version are you using ? Works here, both on simu and real radio

**Comment by kilrah** [comment]
Yup, can't reproduce at all.

**Comment by MIKE-DAILEY** [comment]
I think we had this problem way back on one of the early builds.  Can't remember if there was a fix or we had to rebuild all the Special Functions.  If I start with a new model the clear works.  Note in the images below from an exiting model there are extra stuff in the pop-up window. 

View of the Special Functions Screen: 

![screen-1](https://cloud.githubusercontent.com/assets/11791852/25063474/1a40010a-21b3-11e7-9a25-1560d439f57e.jpg)

**Comment by MIKE-DAILEY** [comment]
Long Press:

![screen-2](https://cloud.githubusercontent.com/assets/11791852/25063479/411bc12e-21b3-11e7-8ac3-3feaeabe2cb7.jpg)

**Comment by MIKE-DAILEY** [comment]
Select an click clear and note the other stuff on the screen:

![screen-3](https://cloud.githubusercontent.com/assets/11791852/25063486/4fe5b5f2-21b3-11e7-889e-ed15d60244bf.jpg)

**Comment by MIKE-DAILEY** [comment]
After click pop-up goes away and line is not cleared:

![screen-4](https://cloud.githubusercontent.com/assets/11791852/25063494/6e2864ce-21b3-11e7-853e-853a0774c933.jpg)

**Comment by kilrah** [comment]
Are you sure you're actually running RC16?!

**Comment by MIKE-DAILEY** [comment]
Shoot!  Forgot that screen. 

![screen-5](https://cloud.githubusercontent.com/assets/11791852/25063524/7b45f9b8-21b4-11e7-8190-4757c68ece86.jpg)

**Comment by 3djc** [comment]
Could you post your model? You have a combined menu that I don't understand

**Comment by MIKE-DAILEY** [comment]
Sure. 

[QX7Models.zip](https://github.com/opentx/opentx/files/923596/QX7Models.zip)

**Comment by kilrah** [comment]
Aha, it only breaks when you scroll down, i.e. anytime the first line isn't visible on screen.

**Comment by MIKE-DAILEY** [comment]
So I can just wait until there is a fix and not need to rebuild my Special Functions?

**Comment by kilrah** [comment]
Rebuild would change nothing at all

**Comment by MIKE-DAILEY** [comment]
Oh! Of course not.
