### ISSUE TITLE
Companion 2.2.0N369 Special Functions hiding non-default lines

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4799]
Lines with no switch are now hidden however the values remain which is not necessarily a bad thing.

Setting a SF to no switch is a way to temporarily disable when there is no Enable option but in this case you do not want it hidden. To relocate you may have to use trial and error and even more confusing if sharing models with 'hidden' SFs.

IMHO lines should only be hidden when all values are defaults.

To reproduce create a SF, change switch to none and add back a switch.

Ubtuntu 16.04 Taranis X9D+

**Comment by mpaperno** [comment]
I do agree that being able to disable any LS/SF w/out deleting it can be quite handy.

> ... lines should only be hidden when all values are defaults.

This is really the crux of the matter, I think.  There is no foolproof way to determine if values are at defaults or not.  The default action is "Override Ch. 1" (vs. "none" for example).  A parameter of `0` could mean default or be an actual setting. Etc.  Only way to be sure a function slot is used is by checking the switch config.

Another (better?) way to temporarily disable a function is to assign it to an unused [logical] switch.  This also works on the radio side.  I think this would also work for logical switches (by assigning an unused "AND Switch").

Hiding the unused LS/SF slots significantly reduces the time needed to open the model editor window (even on a fast computer).  This was primary reason for change.  It also looks cleaner and matches the radio UI.
