### ISSUE TITLE
Load log screen (Horus)

### ISSUE THREAD

**Issue by fjodor84** [opentx/opentx#4806]
Hello,

on the Companion of version 2.2.0 (N369) is not possible to load and change a log screen for a Horus radio. 
![x12_logscreen](https://cloud.githubusercontent.com/assets/27646246/25074572/d28ecf06-22fe-11e7-8095-3070771ae174.png)

**Comment by kilrah** [comment]
Splash screen replacement isn't supported on Horus. Need to disable that menu item.

**Comment by fjodor84** [comment]
And it will be possible in the future?

**Comment by kilrah** [comment]
Maybe, if/when someone feels like adapting the code.
