### ISSUE TITLE
X9D+ N369 - Simulator - Helicopter wizard doesn't launch

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx#4809]
To create, start with a fresh OTX file, then click simulate radio.
Press any key to bypass Failsafe warning.
Use - sign to choose helicopter and press enter.
Nothing happens.
Hit + sign to move to plane icon and press enter.
Wizard starts as expected.

I did notice that someone maybe working on something, so wondered if this had been temporarily disabled.

I currently don't fly helicopters from this radio, so not urgent, but someone might want it! :)

**Comment by 3djc** [comment]
There is no heli wizard anymore. If you see one, it is because you are not using the right sdcard content
