### ISSUE TITLE
Companion ON369 - Global Variables - Tele and other telemetry values not selectable as switch source.

### ISSUE THREAD

**Issue by clivemartin** [opentx/opentx#4810]
Companion ON369. radio profiles for Horus and Taranis Plus.  Global values, Tele and other telemetry inputs not selectable as switch source when Edit Radio is selected.  However they are available within the simulator.

**Comment by kilrah** [comment]
Global variables or global functions?

**Comment by clivemartin** [comment]
Sorry, Global Functions.

**Comment by kilrah** [comment]
It's normal, nothing from the model settings can be used in global functions, that includes telemetry.

If it's available for selection in the radio that's what's wrong.
