### ISSUE TITLE
Taranis 2.2 does not connect as gamepad anymore

### ISSUE THREAD

**Issue by TempleClause** [opentx/opentx#4815]
After updating to 2.2, the USB gamepad thingy does not work anymore. 
I power on my Taranis, clear all the warnings and connect the USB cable. But now it gets connected like it's in the bootloader mode (SD card is accessible and I can read and write with the companion app). 

After I unplug the USB cable the Taranis restarts. 

Any ideas?

I'm on Windows 10 by the way.

**Comment by kilrah** [comment]
You selected the "massstorage" option. Don't.

**Comment by TempleClause** [comment]
Where is that option?

**Comment by kilrah** [comment]
In the radio profile in compamnion preferences, that you set before downloading firmware.

**Comment by TempleClause** [comment]
gotcha! Thanks for instant help! No idea why oscarliang recommends having this option selected...

**Comment by kilrah** [comment]
No good reason for recommending it indeed...

**Comment by kurtc021914** [comment]
On companion 2.2.1 i don't have the massstorage option... :(

**Comment by kilrah** [comment]
Read the 2.2.1 release post on the website, it's explained how it works now.

**Comment by kurtc021914** [comment]
@kilrah Thx, i read it twice but too fast..

- Turn ON the taranis
- Open RADIO setting menu
- Choose "USB MODE : "Joystick" or "storage"
