### ISSUE TITLE
X7 sport update external issues

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#4816]
A few people have reported sport update of external accessories not to work.
Found that `sportUpdatePowerOn()` calls `SPORT_UPDATE_POWER_ON();`, which for X7 is defined as...  `sportUpdatePowerOn()`.

Guess we've got a loop there.

At the same time we should set the power to the bottom connector to always be on in normal use since people would like to connect things there.

**Comment by bsongis** [comment]
I don't see the same code:

```
void sportUpdatePowerOn()
{
  if (IS_PCBREV_40())
    GPIO_SetBits(SPORT_UPDATE_PWR_GPIO, SPORT_UPDATE_PWR_GPIO_PIN);
  else
    EXTERNAL_MODULE_ON();
}
```

**Comment by bsongis** [comment]
Who can give a test at this function? I don't have this connector on my prototype

**Comment by 3djc** [comment]
First batch, so no connector either

**Comment by bsongis** [comment]
I will ask to FrSky to do another test before we can close this issue

**Comment by bsongis** [comment]
Test done by FrSky today
