### ISSUE TITLE
Taranis Q X7 Firmware update problem

### ISSUE THREAD

**Issue by GregB3** [opentx/opentx#4821]
Hi Guys,

I'm stupid. 

wanted to update my new Taranis but forget to change my radio type from X9D.

So I have downloaded version for X9D uncheck box for checking hardware compatibility and loaded firmware od X9D for X7.

how I able to enter bootloader and connect USB cable and even load X7 firmware but after restart radio just flash screen backlight and got empty. Just power button lights green.

If i hit trim buttos - any - hear very loud beep

PLEASE HELP!

**Comment by kilrah** [comment]
This place is for bug reports and development discussions, not user questions, please use forums for support. 

If you load X7 firmware correctly either through bootloader or DFU it should just work fine again.
