### ISSUE TITLE
Companion2.20N369 Behaviour of Delete in Special Functions

### ISSUE THREAD

**Issue by bryan39-2** [opentx/opentx#4825]
Running the latest DEB version on Linux Mint 18.x (all up to date).
Right clicking on a line in Special Functions and selecting Delete garbles the listings. See the before and after attachments when I deleted SF6
![before](https://cloud.githubusercontent.com/assets/22890760/25169647/a4145dfc-24df-11e7-96e8-4c40a76783bc.png)
![after](https://cloud.githubusercontent.com/assets/22890760/25169648/a7f0bdc6-24df-11e7-99e6-57895f21cd6c.png)
If I close the window and re-open it, all appears to be well. I have not tried saving the garbled display to see what happens.

**Comment by Oldgibber** [comment]
Copy and paste does the same. (Windows 10)

**Comment by mpaperno** [comment]
Until next release, workaround is to close and re-open the model editor.  The actual actions are not being modified, the problem is display-only.
