### ISSUE TITLE
Companion2.20N369 Simulator crash with a multidimensional array

### ISSUE THREAD

**Issue by austrianglider** [opentx/opentx#4827]
When using a multidimensional array in a lua-script, the simulator crashes when the script is called. 
When the script is called at TX Horus, the Horus goes into the emergency mode.

Q: Is the array to big? If I restrict the array to 2 value series, then the script doesn't crash.

Example Array:
local freqLookup = {}
    freqLookup[1] = { 5865, 5845, 5825, 5805, 5785, 5765, 5745, 5725 }
    freqLookup[2] = { 5733, 5752, 5771, 5790, 5809, 5828, 5847, 5866 }
    freqLookup[3] = { 5705, 5685, 5665, 5645, 5885, 5905, 5925, 5945 }
    freqLookup[4] = { 5740, 5760, 5780, 5800, 5820, 5840, 5860, 5880 }
    freqLookup[5] = { 5658, 5695, 5732, 5769, 5806, 5843, 5880, 5917 }

**Comment by projectkk2glider** [comment]
What kind of script? Widget or stand-alone or something else?

**Comment by kilrah** [comment]
What are you doing with this array?
Could be unrelated, say creating the array works fine but then the length causes you try to display it out of screen bounds...

I.e. might want to post the script.

**Comment by 3djc** [comment]
As a side comment, you are initializing the array, but not the rows : https://www.lua.org/pil/11.2.html

**Comment by austrianglider** [comment]
It's a stand-alone script.
With the script you can make settings on the VTX Tramp HV.
After selecting the band and the channel, I would like to display the corresponding frequency.

![screenshot_x12s_17-04-19_17-15-49](https://cloud.githubusercontent.com/assets/26895027/25188066/1aa67e56-2525-11e7-96a9-625172de83b4.png)

The affected code starts at line 305.
[KissTest.txt](https://github.com/opentx/opentx/files/935610/KissTest.txt)

**Comment by projectkk2glider** [comment]
This runs OK in simu:

```lua
local freq = {
    { 5865, 5845, 5825, 5805, 5785, 5765, 5745, 5725 }, -- Boscam A
    { 5733, 5752, 5771, 5790, 5809, 5828, 5847, 5866 }, -- Boscam B
    { 5705, 5685, 5665, 5645, 5885, 5905, 5925, 5945 }, -- Boscam E
    { 5740, 5760, 5780, 5800, 5820, 5840, 5860, 5880 }, -- FatShark
    { 5658, 5695, 5732, 5769, 5806, 5843, 5880, 5917 }, -- RaceBand
}


local function run(event)
  print("test")
  return 1
end
return { run=run }
```

So the problem must be somewhere else.

**Comment by projectkk2glider** [comment]
The whole posted script does indeed crash simu. I will investigate...

**Comment by projectkk2glider** [comment]
Looks like Lua has a hard limit on a number of local varibles https://github.com/tessel/t1-runtime/issues/163#issuecomment-55960052 :

>Hmm, this is actually a limitation of the Lua interpreter, and must be less than 250. It won't be easy to increase, either: local variables are mapped to Lua VM "registers", which are stack indexes within the current function frame. These must fit in a single byte because they are encoded in most of the Lua opcodes as 8-bit fields.

>The default 200 allows some space for temporary registers, needed to compile expressions and function calls. There is also a limit of 60 upvalues - variables captured in the function closure from the enclosing function. I'm not sure why this one is so small.

>Note that the 200 locals limit applies only to active locals within one function - since Lua has proper lexical scoping, a local used inside a loop or 'do' block only exists during that block. Outside the block, the register is freed up for a different local (e.g. in a following loop or block.)

>**Also, the top level of a Lua source file is compiled as a function body, so the same limit applies to locals at the file level. This is usually where the limit is hit ;) Named local functions are also included in the total.**

**Comment by projectkk2glider** [comment]
Ha ha, @bsongis disabled this check https://github.com/opentx/opentx/commit/f94b4c743d6720641f985790d71d99d976b831c9#diff-be907d08fbafc22e254d337202fef3ceR289, in this issue the `setnodevector()` gets called with size >255

**Comment by projectkk2glider** [comment]
Maybe that is not a problem since max size is much bigger. the issue happens when  `luaH_resize()` is called with `nhsize = 256` (and current size is 255).

**Comment by projectkk2glider** [comment]
The commit f94b4c743d6720641f985790d71d99d976b831c9 did this. The size of hash is now stored as straight number (8 bit) while it was a number of bits before. So any hash bigger than 255 can't fit. @bsongis any idea how to fix it?

**Comment by bsongis** [comment]
I can't remember anything of this commit!

**Comment by bsongis** [comment]
@projectkk2glider will you do a PR with your change? Or is there any problem hidden behind my original change and I cannot remember?

**Comment by projectkk2glider** [comment]
I need to study this change a little more to see what is behind the scenes. Then I will do a PR.
