### ISSUE TITLE
Improvement: Possibility to move the rules (SF1,Sf2...SFn) in "Spezial Funktionen"

### ISSUE THREAD

**Issue by Wesie** [opentx/opentx#4828]
Seen and recreated to 100%
Vers 2.2.0N369
Tab: Spezial Funktionen

The transmitter and also the simulation works in spezial funktionen from up to down. 
This means, that the last valid entry is the master.
In depent, that new rules be should added, (uncomfortable in front) all other rules which are behind must be rewriten one or x row deeper, so that the new rule can be added in between. 

It will be a nice improvement, if the rules SF1, SF2, SF3...SFn could be moved up and down, so that another rule can be added in between.

Thanks for your help

**Comment by kilrah** [comment]
FYI you can copy/paste them already.
