### ISSUE TITLE
2.2.0N369 checkbox in Tab curves unclear 

### ISSUE THREAD

**Issue by Wesie** [opentx/opentx#4829]
In the tab curves, there is a checkbox between the curve No an the curve by herself. 
It's unclear, for what the checkbox is. No mouse over text, no description in the German manual, no info in the Internet. 
I've found one old picture, where is the possibility to delete ( tagged???) Kurven, but I'm not sure if it is or not. 
Enable/disabled isn't.. local or global?

**Comment by kilrah** [comment]
Just trying should be obvious enough? It's whether it's to be shown on the graph additionally to the currently selected one.

**Comment by Wesie** [comment]
Oh, thanks for clarification.
