### ISSUE TITLE
"Unable to check for updates" error when checking for firmware updates

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#483]
_From [m.shel...@gmail.com](https://code.google.com/u/105357959046023476003/) on December 04, 2013 10:21:28_

Can't check for firmware updates, or get the firmware changelog. What steps will reproduce the problem? 1. Help -> Check for Updates 

A progress dialog appears with title "Checking for updates". Times out after about a minute with "Unable to check for updates".

Help->Firmware Changelog also fails, displays empty list.

What version of the product are you using? happens on both 1.48 and 1.51
On what operating system? Win 7
Which firmware have you selected ? 2768 Please provide any additional information below. Previous versions of C9X worked fine.

_Original issue: http://code.google.com/p/companion9x/issues/detail?id=283_

**Comment by benoit35690** [comment]
Hello,
I have the same message when I try to upgrade my Taranis (x9d) with firmware opentx 2.2 from the Companion 2.2.0 RC8. I have checked the "Use OpenTX firmware nightly builds" box.
Is the server issue still open ?
Thanks

**Comment by 3djc** [comment]
you need to enable nightly both for companion and the firmware

**Comment by SaintS3** [comment]
I keep getting unable to check for updates on startup and it won't download firmwares :( 
Ta

**Comment by kilrah** [comment]
Read the post just above yours. And the release page on the website.

**Comment by SaintS3** [comment]
Yes and i keep getting unable to update, i do know how to read.

**Comment by kilrah** [comment]
You don't know how to give useful debugging information though. Like which version of companion you're using, which radio you've got selected, what computer OS you're running on,...

**Comment by benoit35690** [comment]
The problem is solved for me, Yes indeed I only checked 1 "Use OpenTX firmware nightly builds" box. Now with the 2 boxes checked it is OK. Thank you and sorry for a so stupid question.

**Comment by SaintS3** [comment]
Bud you know with a attitude like this, I'll rather just scrap this idea and buy a Dx9 or what ever just works, i came here for help, have absolutely no idea what debugging even means, im a plumber not a IT wizz, i was following a few youtube vids, anyway all the best.

**Comment by kilrah** [comment]
Firstly this place is for managing software development, not for end-user help. Then understand that 

> I keep getting unable to check for updates on startup and it won't download firmwares :(

is the IT equivalent of me telling you "water's leaking :(" with no more info. 

You'd certainly be annoyed at me not even telling you if it's a pipe in the bathroom, the washing machine, or the roof drain that's got nothing to even do with you...
Same here, we support multiple systems and "products", if you want help then help us help you by a least giving relevant infomation.
