### ISSUE TITLE
Menu freeze when USB plugged in (2.2.0N369)

### ISSUE THREAD

**Issue by KD9FNA** [opentx/opentx#4830]
When the USB cable is plugged in to use Liftoff or any other software, the Taranis X9D+ will not allow access of the menu functions appear to freeze.  The radio also fails to be recognized as a controller from the computer.  When the cable is unplugged, the Taranis restarts and the cycle repeats.  This function worked on 2.1.9 with everything else the same.

**Comment by 3djc** [comment]
You have selected a firmware with massstorage ?

**Comment by KD9FNA** [comment]
Yes.  Is that what might be causing this?

**Comment by 3djc** [comment]
of course, you can't be both a joystick and a 'virtual usb key' at the same time

**Comment by KD9FNA** [comment]
Thank you for the help.  I was not aware of this.
