### ISSUE TITLE
Czech display issue 2.2.0N369

### ISSUE THREAD

**Issue by xrom4n** [opentx/opentx#4832]
The display Taranis Q7 contains errors. Page 1/9 radio settings - the text "center transition" and "mode" exceeds the edge of the display, the text "introductory logo" is written without a space. Page 5/9 version - lower texts go beyond the edge of the screen.

**Comment by xrom4n** [comment]
Taranis X7

**Comment by 3djc** [comment]
For screen 5/9 I can do that (not sure if the means anything at all:
![image](https://cloud.githubusercontent.com/assets/5167938/25268287/7da69c58-2678-11e7-8c53-e9ecc0c48734.png)

For 1/9 I'll need screenshot and alternative traductions

**Comment by xrom4n** [comment]
It looks good. "zálohuje" could replace "Záloha"
I'm sending the current version of my version on the radio.

![20170419_182242](https://cloud.githubusercontent.com/assets/27809444/25270506/3dbdd422-2681-11e7-812c-bdd89bd96277.jpg)
