### ISSUE TITLE
GPS coordinates on GPS sensor display issue N369 Taranis

### ISSUE THREAD

**Issue by athertop** [opentx/opentx#4834]
In the Telemetry sensors screen, click on the GPS sensor and the coordinates for lat/long are too close together and clash with each other. Just a cosmetic issue - no biggie :-)

**Comment by 3djc** [comment]
In cases like that, it really helps us a lot if you could duplicate your issue on simu and screenshot it,  because it might be related to your radio type, GPS coord type (DMS or NMEA)  or actual coordiantes themselves.

Help us help you  :)

**Comment by bsongis** [comment]
Taranis X7 or X9?

**Comment by athertop** [comment]
Sorry, I didn't post an image yet. Here it is:
![](https://dl.dropbox.com/s/gvdn6dpt1w59ijy/gps-bug.jpg?dl=0)
Its on Taranis X9.

**Comment by 3djc** [comment]
Ok, It was fixed then
