### ISSUE TITLE
Screen OFF brightness can't go below 5

### ISSUE THREAD

**Issue by Red-Devil74** [opentx/opentx#4836]
When setting the OFF-Screen brightness (OTX N369) the minimum setting is 5. apperently in previous version(s) it could be switched off completely.
Request to enable OFF-screenbrightness to 0 (zero/nill/null) so to actualy switch the screen off completely.
![image](https://cloud.githubusercontent.com/assets/23432540/25297903/1633c568-26f1-11e7-95a2-41ff51be168f.png)

**Comment by kilrah** [comment]
Intentional.

**Comment by Red-Devil74** [comment]
Thought so much. Thanx. Do you have any prediction on power consumption when screen is at 5%? That is the only reason "someone" would like to have it on 0%, to reduce power. I would assume it can be neglected?

**Comment by 3djc** [comment]
It does consume more power than at 0% but it's the only way to get out of a stupid settings, so not a choice really

**Comment by Red-Devil74** [comment]
Could it be a feature enhancement to check wether Mode is not set to OFF and On brightness is above 65% and THEN allow 0% OFF Brightness?

**Comment by kilrah** [comment]
Consumption at 5% is completely negligible.
