### ISSUE TITLE
Crash when syncronizing SD card

### ISSUE THREAD

**Issue by Freddan-67** [opentx/opentx#4837]
First time use on a new computer.
Go to settings->settings and set up a writable directory for sd card backup (in my case %userprofile\opentx\sd-backup\ )
Go to file->syncronize SD
left-click outside of the checkbox called "show details" 
The application crash.
Update: This seems to happen during backup of directory Of (sd card drive)\Info\Video, and the file explorer also crashes in this directory. The explorer screenshot was added after having disconnected the taranis and re-connected it to the computer.
![skarmklipp 2017-04-22 08 56 22](https://cloud.githubusercontent.com/assets/7888909/25302227/b91bea74-2739-11e7-9918-534b63fb4af4.png)

![screenshot2017-04-22 08 40 04](https://cloud.githubusercontent.com/assets/7888909/25302133/7e1825f2-2737-11e7-95f9-045fbf6ddaf8.png)
![skarmklipp 2017-04-22 08 43 43](https://cloud.githubusercontent.com/assets/7888909/25302146/dc9e5c2c-2737-11e7-8bd7-98ca36ae2f6d.png)

**Comment by projectkk2glider** [comment]
@Freddan-67  Which version of Companion?

**Comment by Freddan-67** [comment]
As can be seen on top of the 3:rd image I am using 2.1.9 (windows 10), Lenovo X1 Carbon (2016) with Intel USB 3 host.
