### ISSUE TITLE
Number of Widgets Crash Companion Latest release

### ISSUE THREAD

**Issue by aviat40** [opentx/opentx#4839]
Around round 10 widgets crash the companion
Thierry71

**Comment by projectkk2glider** [comment]
Could be the same reason as #4827

**Comment by bsongis** [comment]
Any example of such widget? You don't provide much information!

**Comment by aviat40** [comment]
I will try to be more precise. To understand the Widget, I create around 10 folders with all widgets i can found on internet with the Horus. I use the Simulator openTX lastest version using Folder option to simulate. 
After selected, when you want to start the simulator, the App crash. OS W10

**Comment by kilrah** [comment]
Please zip your WIDGETS folder and post it.

**Comment by aviat40** [comment]
[Widgets.zip](https://github.com/opentx/opentx/files/965925/Widgets.zip)

I hope it will help you

**Comment by kilrah** [comment]
Nothing to do with the number, it's the "BrainFlightMode" widget that causes the crash.
