### ISSUE TITLE
[Companion n369] SF Conversion from older releases & between tx profiles "buggy"

### ISSUE THREAD

**Issue by strgaltdel** [opentx/opentx#4840]
Hi,
just updated my X9e from n366 to n369 and wanted to write a model into my horus.

Following Problem:

in n366 a SF is defined to control speaker volume:
By flashing n369 on X9e everything seems to be fine within TX model configuration.
![x9e366](https://cloud.githubusercontent.com/assets/20392683/25303658/fb9d384e-2757-11e7-87fe-c7a9ae1e83a5.png)

After that i loaded the "pre saved" n366 otx file into companion n369, still "X9e" in profile settings.
There i recognized, that the SF config changed from input "RS" into "LS", which didn't occur by firmware conversion.
![x9e369](https://cloud.githubusercontent.com/assets/20392683/25303663/07b4ee4c-2758-11e7-9c52-18fab6d005f6.png)

Without changing this config i switched to my horus profile and could see, that the input ended up in the "rubber stick" / x level:
![horus369](https://cloud.githubusercontent.com/assets/20392683/25303665/18a151fa-2758-11e7-9f08-ee4d1222f9f5.png)

Didn't search for more changes, but would expect them
Could find a similar issue
Don't know if it has something to do with my X9e setting: this tx is "expanded" with 2 more switches and the 6Pos pod

regards
Udo

**Comment by 3djc** [comment]
X9E had (and still has until next nightly) invalid handling of two pos additional switches. If you had one or more of those switches, they would very likely be wrong (ie your display position is middle and up/down instead of the correct up/down (no middle)).

In addition, it is nealy impossible to go from X9E (specially expended) to anything else, since X9E has more inputs than any other Otx radio

**Comment by strgaltdel** [comment]
Extension switches are 3-Pos types, so it doesn't perfectly match your failure criteria !
Never saw this kind of "Input shift" by any other Companion upgrade
![x9ext](https://cloud.githubusercontent.com/assets/20392683/25307127/0b4bb1c8-279c-11e7-9f6a-c54a13da6449.png)


I'm fully aware that there is no option to copy a model "one by one" from X9e to horus, but i feel comfortable, 'cause a lot of switches are used by scripts.
Nevertheless there is some work to rearrange switches & functions within oTx due to the "other ergonomic paradigm" of a horus, of course.
So I'd build a systematic "migration paper" which switch definitions in which area had to be changed from a X9e (source) to a horus(target) design.
I would have expected that an Input like "LS", which does exist on both TX's, wouldn't have changed by companion.
By now I've to adopt my paper to these "new" source inputs after companion X9e>>horus conversions, 
NO BIG DEAL !

Of course, it's beta software, and every user has to check all kind of migrations for plausibility.
In case there is "internal definition" that there is no must of a 1 by 1 mapping between X9e and horus inputs (cause it would exceed development work... or so on..) it's an understandable decision.
But if so (suggesting same behaviour by a standard X9e), a hint that there are expectable changes by selecting between Tx profiles would be useful (my guess)

**Comment by 3djc** [comment]
If your additional switches are 3pos to then yes, that data corruption should not happen. Having your 366 would be nice. 

Yes basic switches should go through and what you are experiencing should be resolved. At some point in time, we would like to have user defined transfer maps, but that's for 2.2.x

**Comment by strgaltdel** [comment]
maybe a issue with my firewall, can't attach zip files here, any preferred source for filesharing withou need of registration ?

**Comment by strgaltdel** [comment]
OK,try
http://www53.zippyshare.com/v/d24mEI2l/file.html

two files,
the "366" was uploaded within companion 366 (backup purpose),
the other one is an upload from companion 369 after FW 369 conversion.
Look at Radio setting, global functions...

**Comment by kilrah** [comment]
www.filedropper.com

Even if both are "LS" they are still different things becasue the other controls make it so that they aren't in the same position in the list so the mapping isn't 1:1. 

Ideally all these cases would be handled but it takes motivation for someone to code that, with so many different platforms it starts to create a whole lot of individual cases.

**Comment by strgaltdel** [comment]
Hi Kilrah, thanks again for explanation,
i was afraid of something like this.

as mentioned before, my suggestion would be to add one more line in the window which occurs by changing TX profile, in order to sensitize the user 
(obvisouly at least i wasn't aware of this, maybe the majority is)

Thanks and bye !

**Comment by kilrah** [comment]
If a more complete conversion doesn't make its way in by the time we get to final release we'll put an additional warning. For now there's still hope some work is done on that.

**Comment by strgaltdel** [comment]
it seems that the remaining "issue" is more a question of a consistant value presentation between Firmware and companion.

Cause the input "RS" controlled the loudspeaker volume, i named it "LS" in the config.
(OK, should 've been aware that "Vol" would've been better and would have avoid irritations)
![inpconfig](https://cloud.githubusercontent.com/assets/20392683/25312294/3c4b4296-2816-11e7-8f3c-434feb5039c1.png)

By now, Tx firmware shows the "Input Hardware", 
![1_366_before upgradeviatx](https://cloud.githubusercontent.com/assets/20392683/25312300/53f5ff3a-2816-11e7-958d-7b3bd6fef961.png)

and Companion shows the "Input label"
![x9e369](https://cloud.githubusercontent.com/assets/20392683/25312303/64ef1a06-2816-11e7-8fec-615683647ad2.png)

.. which is a change in behavior between companion 366 to 369.
personally i would prefer same results between firmware & companion.

**Comment by 3djc** [comment]
Oh, that's a nice bug :) Name should be displayed, but are not JUST for RS (LS works as it should)

**Comment by strgaltdel** [comment]
Yes, all is running fine, just a "display feature" (-;

**Comment by 3djc** [comment]
and the same exist for S2 on x7, at least we are consistent !
