### ISSUE TITLE
Companion 2.2(n369) logical switch V1 name changes from Tx to companion 

### ISSUE THREAD

**Issue by calril312** [opentx/opentx#4841]
LS30 & LS32 V1 were set to "JSy" on production Horus-X12S Tx but changed to "L1" when models and settings were loaded into companion. It appears to be mostly cosmetic but as "L1" is more often associated with Logical Switch 1, it could be somewhat confusing. It does however show up correctly in Simulator.
![screenshot n369](https://cloud.githubusercontent.com/assets/27895043/25305822/a94a50bc-273f-11e7-91f2-e0d8a470c9c2.jpg)
![screenshot n369 sim](https://cloud.githubusercontent.com/assets/27895043/25305895/de1a8928-2740-11e7-9be6-f7eede7336b8.jpg)

**Comment by 1Sven** [comment]
I see this also as a problem. And you can not simulate the JSy/x on Companion becorse the stick is not mouveble. For test I'm using L1 or L2 that maks the confusion much bigger...
I hope of a probatly solution to!

**Comment by bsongis** [comment]
Is this issue still there in the last RC?

**Comment by kilrah** [comment]
Can't reproduce on n369 with setting done on a Horus also running on N369 and read into companion.

**Comment by calril312** [comment]
I believe the model was created on n368 but the LS was created on n369. It was created on the radio, not companion or the simulator. Here is the "print model" file. What else can I provide that might help?
[DemonS8R 540.pdf](https://github.com/opentx/opentx/files/953486/DemonS8R.540.pdf)

**Comment by kilrah** [comment]
zip the MODELS and RADIO folders ftom your radio's SD card and send us a link to that.

**Comment by calril312** [comment]
[MODELS.zip](https://github.com/opentx/opentx/files/954922/MODELS.zip)
[RADIO.zip](https://github.com/opentx/opentx/files/954923/RADIO.zip)

**Comment by kilrah** [comment]
OK, must be something with @mpaperno's source names - JSy takes the name set for L1 in the hardware page if there's one

**Comment by bsongis** [comment]
I take it

**Comment by kilrah** [comment]
i think it's in eeprominterface.cpp:555, should test for sticks only

**Comment by calril312** [comment]
Cool, well let me know if there's any other info you need. Thank you guys for all that you do for the RC & OpenTX communities. Seriously, your time and efforts are greatly appreciated!
