### ISSUE TITLE
6 poz switch Horus 2.2N369 switching signals

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#4853]
We have got info, that when is asigned 6poz switch to imput and directly to channel there is some moments that during changing position result in 0 on channel. It is not visible in case of F.modes where is probably some filter but for chanels it happend and can disturb some drones controlers.

Should be considered to add some filter too as switching from 5th pos to 6poz looks 1850ms - 1500ms - 2000ms

**Comment by kilrah** [comment]
That's due to how the FrSky switch is wired... but there is already a "switch delay" setting to take care of it in the radio settings.
