### ISSUE TITLE
Companion 2.2N369 external flash issue

### ISSUE THREAD

**Issue by xrom4n** [opentx/opentx#4858]
Non-functioning external flash (X8R) via transmitter Q7
Version 2.2.0N369 (f197268c)

**Comment by RealTadango** [comment]
Do you have the bottom connector pins? And if so, did you use them?

Btw, has nothing to do with companion ;)

**Comment by schwabe** [comment]
Probably duplicate of #4846 (wrong connector used). If your error is different, reopen and provide more details
