### ISSUE TITLE
LUA Script Sound Stuttering

### ISSUE THREAD

**Issue by thatsnailguy** [opentx/opentx#4863]
Hello, 

I am running a FlightDeck telemetry script created by Craft and Theory LLC. I have contacted them trying to troubleshoot this problem, they have been unable to help me.

Does anyone know what is going on here? I have tried several SD Cards with varying speeds and capacity.

I am running the latest release and have attached my models and setting otx file.

[![FlightDeck Sound Problem](https://img.youtube.com/vi/jtxTRtV1Oq8/hqdefault.jpg)](https://www.youtube.com/watch?v=jtxTRtV1Oq8)

https://www.youtube.com/watch?v=jtxTRtV1Oq8

[Condor.zip](https://github.com/opentx/opentx/files/961736/Condor.zip)

**Comment by schwabe** [comment]
While this points to a problem somewhere in OpenTX, I think your first line of support here is Craft and Theory LLC as this is a commercial product.

To get this bug fixed, we also need a (simple) script that can reproduce the error. Most of us are very reluctant to debug complex to debug lua scripts that are only distributed in compiled form and we have to buy first.
