### ISSUE TITLE
6 character limit in voice file selection

### ISSUE THREAD

**Issue by boTy635** [opentx/opentx#4867]
I made a voice pack for my Taranis Q X7 with OpenTX Speaker, and all the files with more than 6 characters in the file name are not visible in the list at special functions>play track. They are also not visible in the global functions list. However, they are visible in the SDcard explorer menu.

**Comment by kilrah** [comment]
Normal, keep length to 6 chars max.

**Comment by boTy635** [comment]
Tried that, but the problem with that is that it doesn't recognize system sounds like the trim center sound.

Or should I only rename my custom files to 6 characters and not the system files?

**Comment by kilrah** [comment]
Only custom, system filenames must not be touched.

**Comment by boTy635** [comment]
@kilrah Okay, I will do that, thank you!
