### ISSUE TITLE
Missing error code documentation

### ISSUE THREAD

**Issue by DeanChurch** [opentx/opentx#487]
I've seen to messages that I do not understand.
1.  When I'm reading and writing Models on the PC, ocasionally a rectangle will show on the screen

[. 
    no SD card
    EXIT to continue 
                                 ]

I can still read or write models or access the SD card from 
Windows Computer to add replace Sounds or move Log files to disk...
So obviously there is an SD card and it is available.
I have not figured out how to produce this on demand.

When starting one of my models on the Tx, I will see a message rectangle that says 

[.  
   PathToo Long  
                            ]

I do not see anywhere that error or information messages are documented.

What do these messages mean?

**Comment by lostintheglide** [comment]
I also have an issue with trying to play audio files on my Qx7 on 2.2 , I downloaded Amber files for 2.2 and copied them into sounds folder on Sd card using a Mac , sounds do not play when starting radio and when I find the files and press play I get an error saying "path to long , exit to continue " 
What should I do to get sounds working ?
