### ISSUE TITLE
Cosmetic of LS

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#4877]
Hi Folks,

I see that a `Sw` prefix has been added in the logical switch of the simulator.
Personally, I think it is useless and less readable. Do you think it would be possible to revert as before?

![tmp](https://cloud.githubusercontent.com/assets/1685030/25558016/5c104cf4-2d1e-11e7-81a4-055fa3365844.png)

**Comment by mpaperno** [comment]
I guess I should pay more attention...  This was a side-effect of renaming the LSs in Companion selector lists ( #4874).  Reverted back to numbers-only.

**Comment by LapinFou** [comment]
Thanks Max ! 👍 
Since we are talking about cosmetics issues on Companions, FYI, I opened 2 issues: #4599 and #4879 

Seb.
