### ISSUE TITLE
QX7: Slow menus and voices. Channels don't respond.

### ISSUE THREAD

**Issue by miginv** [opentx/opentx#4893]
Since I updated to 2.2.0N369 with Spanish menus, after some normal operation, Taranis Q X7 started to show a very odd behavior:
- Voices seem to be played very slow so it is impossible to understand them.
- Menus are slow.
- Radio transmitter and receiver are binded since receiver led becomes green when on and transmitter vibrates when receiver is off. However, channels updates are not displayed in the Cleanflight configurator. They have fixed values besides I move all sticks and switches.

I have done this troubleshooting:
- Uploading different firmwares (both Opentx and bootloader): 2.2.0N364, 2.2.0N370, 2.2.0N371 and from Frsky website (http://www.frsky-rc.com/download/files/Firmware/FIRMWARE-X7_170213.zip)
- Removing SD card and using different sdcards.

These are some videos that shows the behavior: 
https://www.youtube.com/watch?v=DoTi1rIMcv4
https://www.youtube.com/watch?v=UvzA9gl8svg

Thanks in advance.

**Comment by kilrah** [comment]
> Uploading different firmwares (both Opentx and bootloader): 2.2.0N364, 2.2.0N370, 2.2.0N371 and from Frsky website (http://www.frsky-rc.com/download/files/Firmware/FIRMWARE-X7_170213.zip)
Removing SD card and using different sdcards.

And, did it change anything?

Looks like a hardware problem with the main crystal/oscillator.

**Comment by 3djc** [comment]
Yeah looks like your radio needs to be returned for warranty.

**Comment by miginv** [comment]
Thanks for the answers. Changing firmwares and removing the SD card didn't change anything. So it seems that the mainboard (with the sd card reader, usb, sticks connectors, etc) has something wrong, doesn't it?

**Comment by kilrah** [comment]
Correct.

**Comment by projectkk2glider** [comment]
Unless you think you changed firmware, but you actually did not. You should verify the actual flashed version from the radio setup menu to see if you actually succeeded to flash another firmware.

**Comment by miginv** [comment]
Perhaps I am missing something. I uploaded the bootloaders versions from Opentx and the Opentxs versions from the bootloader. What I couldn't is to enter into the DFU mode besides I followed the Zadig manual (I tried in Windows 10 and 7). I also tried dfu-util from Mac and Linux, but I never get the stm32 recognized. Before the issue the DRL simulator recognized the radio but now it doesn't, so the problems also affects the USB. Anyway, if the DFU is not modified by upgrading the opentx itself or opentx bootloader, it shouldn't matter.
According to these pictures I think I actually changed the firmware, but please, can you confirm?

![qx7fws1](https://cloud.githubusercontent.com/assets/8844425/25725134/08dd7b74-311f-11e7-980e-d017b498dc89.jpg)
![qx7fws2](https://cloud.githubusercontent.com/assets/8844425/25725138/08e40886-311f-11e7-8bc8-496d3c365946.jpg)
![qx7fws3](https://cloud.githubusercontent.com/assets/8844425/25725137/08e23362-311f-11e7-8f38-6a37d5974176.jpg)
![qx7fws4](https://cloud.githubusercontent.com/assets/8844425/25725136/08deb3e0-311f-11e7-81cd-d4746aa0c097.jpg)
![qx7fws5](https://cloud.githubusercontent.com/assets/8844425/25725135/08de0670-311f-11e7-81e2-23300dd792b5.jpg)

**Comment by kilrah** [comment]
Yes all good. 

A wrong system clock would cause everthing you see (USB can't work if clock is incorrect, internal module won't recognise the input signal that's highly timing-dependent explaining the lack of response from the receiver, etc...)

**Comment by miginv** [comment]
It makes sense, but then is a SW or HW issue?

**Comment by kilrah** [comment]
Hardware, if it was software nobody would have an X7 that works.
