### ISSUE TITLE
Flightmode switch changed from SF to SD when upgrading from 2.1 to 2.2

### ISSUE THREAD

**Issue by jfrickmann** [opentx/opentx#4900]
I downloaded the latest Companion 2.2 and loaded an .EEPE file from 2.1.9. My models have flight mode 1 on SF down, and this was changed to SD down in the upgraded file. I assume that it is a bug; not a feature :-)

Thanks! /Jesper

**Comment by 3djc** [comment]
Please post your 2.1.9 eepe file

**Comment by jfrickmann** [comment]
I tried to reproduce the problem and could not do so. Then I realized that when I first loaded the file, I had mistakenly set the transmitter type to X7 instead of X9D+, and that was probably why the switch was moved around. My bad, sorry! Please consider the issue resolved.

/Jesper
