### ISSUE TITLE
The timer in the top menu

### ISSUE THREAD

**Issue by fjodor84** [opentx/opentx#4901]
The Timer (Tmr1, 2, 3) on the top menu is bad showed. Another values seem to be fine. It's only for a models created on Horus with RC18. In models from previously RC versions it is fine.

![img_0639](https://cloud.githubusercontent.com/assets/27646246/25780019/68b172b8-3321-11e7-8e29-0d7149852d65.JPG)

**Comment by kilrah** [comment]
Do you have correct SD card contents?
