### ISSUE TITLE
Companion 2.2 can't set custom failsafe to Hold or No Pulse

### ISSUE THREAD

**Issue by jarhart** [opentx/opentx#4904]
Companion 2.2 RC18 (N371), Custom failsafe mode setup: the dropdowns for setting the positions to `Hold` or `No Pulse` don't seem to change the model and it always gets reset back to `Value`.

To reproduce:
1. Open a "models and settings" file or import from a TX.
2. Open one of the models.
3. Set the failsafe mode to `Custom`.
4. Set one of the Failsafe Positions to `Hold` or `No Pulse`.
5. Close and re-open the model.
6. The Failsafe Position is `Value` instead of whatever it was set to in step 4.

Workaround:
Set failsafe in the TX after writing Models and Settings from Companion.

**Comment by kilrah** [comment]
Radio type?

**Comment by jarhart** [comment]
Tarans and Horus

**Comment by mpaperno** [comment]
Confirmed.
