### ISSUE TITLE
Download firmware

### ISSUE THREAD

**Issue by rcabuser** [opentx/opentx#4915]
I've tried several times to download firmware/software, but when trying the download link for the given firmware/software i get the message "site can't be reached" I tried on a windows 10 computer with all the different browser's, and i tried with a Mac but no luck.

**Comment by 3djc** [comment]
What exactly are you trying to download ??

**Comment by rcabuser** [comment]
I tried to download the wizard lua script

**Comment by 3djc** [comment]
What script are you refering to ???

**Comment by rcabuser** [comment]
model wizard

**Comment by 3djc** [comment]
what model wizard ? what link are you following ? what instructions are you followinig ?

**Comment by rcabuser** [comment]
<img width="729" alt="screen shot 2017-05-11 at 14 17 24" src="https://cloud.githubusercontent.com/assets/16747210/25948653/cf4b1a20-3654-11e7-926d-dde82088d07d.png">

**Comment by 3djc** [comment]
ok, that starts helping

**Comment by 3djc** [comment]
Fixed

**Comment by rcabuser** [comment]
Ahh great, thx man:-)



On Thursday, May 11, 2017 14:33 CEST, 3djc <notifications@github.com> wrote:
 
Closed #4915.
