### ISSUE TITLE
Companion 2.2 Model edit changed names not immediately updating across drop downs

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4917]
gvars, curves, etc name updates not immediately reflected in the new style type:name drop downs. Need to close and reopen the edit dialogue for the refresh to occur.

Updates okay for Inputs and Mixes sub dialogues.

Latest local Ubuntu 16.4 compile for Taranis X9D+

**Comment by mpaperno** [comment]
That's correct, in some cases there's caching going on right now to improve overall performance.  I have new code with better updates already working here, but it will most likely need to wait for 2.2.1 (to avoid risk of breaking anything else for 2.2 release).

**Comment by elecpower** [comment]
@mpaperno yeah 2.2 from what I have see has been full on for the dev team and needs to get stability to release. The issue is just an annoyance but thought I would raise. Not surprised you have already been working on it.

**Comment by kilrah** [comment]
RC4 still (or again?) doesn't update the source dropdowns on the LS page when an LS is added.
AKA if you set L01, you won't be able to use it in L02 before closing/reopening the window.

**Comment by kilrah** [comment]
Actually it depends on the function. If you select OR in L02 the resulting source list does update and contain it. If you select a>b it doesn't. 
Having LS's available in an a>b function is actually debatable, but they were available before so might not want to remove it altogether...

**Comment by mpaperno** [comment]
Yes, I see.... the Sources lists aren't updating, just the Switches lists are.  Investigating...

**Comment by mpaperno** [comment]
Well I don't love the workaround (works but inefficient), but I think a proper refactoring should wait for 2.3.
