### ISSUE TITLE
Companion 2.2.0 N371 Special functions audio play button icon does not always reset

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4929]
It is possible to stop the audio play button icon from resetting to triangle after playing. Clicking another play button before the first has finished appears to be the cause. This does not prevent the button playing the audio file.

![screenshot from 2017-05-15 22-24-32](https://cloud.githubusercontent.com/assets/15316949/26057753/40d540f0-39be-11e7-8a02-b51acaa5e24d.png)

Ubuntu 16.04 Taranis X9D+

**Comment by mpaperno** [comment]
Noticed this a while ago and have it already fixed in new code (once 2.2.0 is released).
