### ISSUE TITLE
Taranis x7 upgrade receiver error

### ISSUE THREAD

**Issue by nontas1986** [opentx/opentx#4931]
On receiver upgrade I get this error.

FW update error.
 Bottom pin no resp

I have the last 318N version.

**Comment by 3djc** [comment]
How and where did you connect your receiver ?

**Comment by nontas1986** [comment]
The receiver is x4rsb and I connect to module 
  + - s on 3 bottom pins

**Comment by kilrah** [comment]
You need to use the connector at the bottom of the radio with a straight cable.
