### ISSUE TITLE
Companion 2.2: rotenc firmware option missing in companion for Mega2560 radio

### ISSUE THREAD

**Issue by hjuergensteinhoff** [opentx/opentx#4935]
The checkbox for rotenc option seems to be missing for DIY Mega2560 radio.

**Comment by bsongis** [comment]
shouldn't it be always enabled?

**Comment by hjuergensteinhoff** [comment]
should be fine to always enable rotencs. Looked in opentxinterface and did not find any nav_options for Mega2560 board. Thus I concluded rotencs are not enabled. However, I am ignorant in programming, so I might be wrong and instead am facing a hardware problem that rotencs don't work in my setup.

**Comment by bsongis** [comment]
![snapshot_01](https://cloud.githubusercontent.com/assets/5603504/26327939/6e2da24e-3f41-11e7-9710-ad5439cf2322.png)

**Comment by bsongis** [comment]
Don't you have those 2 rotary encoders REa and REb?

**Comment by hjuergensteinhoff** [comment]
Your snapshot helped: in switches menue I see REa and REb, I could invert zeros by pushing rotary encoders, but no change in numbers by rotating. Finally found hardware issue (crossed cables). After enabling rotary encoders for navigation in radio setup menu I can now use encoders for navigation (sometimes however with jumping over one or two lines). Thanks again. Please close this issue.

**Comment by 3djc** [comment]
Thx for the feedback!
