### ISSUE TITLE
Model sound plays before hello sound

### ISSUE THREAD

**Issue by jackwilsdon** [opentx/opentx#4942]
I'm on the latest nightly for my Taranis X9D+ (OpenTX 2.2.0 RC18) and the `name.wav` from the model folder plays before `hello.wav` from `SOUNDS/en/SYSTEM`. I assume this is not the intended behaviour? 

I followed the function calls and it looks like it works like this;

    opentxInit → storageReadAll → storageReadCurrentModel → eeLoadModel → postModelLoad → PLAY_MODEL_NAME
               → opentxStart    → AUDIO_HELLO

Where `opentxStart` is called after `storageReadAll`.

**Comment by 3djc** [comment]
I guess we could prevent hello been played when model audio is available
