### ISSUE TITLE
Companion model edit corrupt mixes list when adding mix to line 1 of a channel

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4943]
Adding a mix line to line 1 of a channel temporarily corrupts the Mixes list. Adding to a line 2 onwards does not exhibit the issue. Exiting the mix edit dialogue refreshes mixes list correctly.

![mixes w add dialog](https://cloud.githubusercontent.com/assets/15316949/26344026/84c9688a-3fe1-11e7-93e4-f58c5d62467b.JPG)

Companion 2.1.9 Win 10 64bit Taranis X9D+

**Comment by mpaperno** [comment]
This is fixed in #4919.  (I noticed it while working on that PR but thought it was something I had caused in the new code, so wasn't aware it was an issue to begin with.   Not entirely sure I remember the actual fix, eg. for back-porting to 2.1.10.)

**Comment by elecpower** [comment]
confirm fixed at 2.2
