### ISSUE TITLE
Companion model edit cancelling add of input line leaves skeleton

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4944]
Highlight an input line, from context menu select Add, click Cancel from edit dialogue.

![inputs](https://cloud.githubusercontent.com/assets/15316949/26344353/a98f34d2-3fe2-11e7-9bff-b40cc08fbdc8.JPG)

Companion 2.1.9 Win 10 64bit Taranis X9D+

**Comment by mpaperno** [comment]
Perhaps more an enhancement than bug... When you use Add it properly adds a line.  Then, for the user's convenience the edit dialog is automatically opened on that line.  To "fix" this we'd need to determine that Cancel was pressed on a brand new line which was just added, and only then delete that line.  I'm sure it's possible and probably even logical, but it has to be coded properly to work w/out unwanted side-effects.

**Comment by mpaperno** [comment]
NVM, does seem like a bug... should have looked at the code first.  There's code in `modeledit/inputs.cpp` which should already delete a new input if dialog was cancelled, but it doesn't work for some reason.  Does work in mixers list.
