### ISSUE TITLE
Companion 2.2.0 inability to edit new global variable parameters

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#4947]
Can be edited on radio and Companion Simulator but cannot find in Companion model edit.

Ubuntu 16.04 Taranis X9D+

**Comment by kilrah** [comment]
Flight modes tab as always.

**Comment by elecpower** [comment]
Sorry @kilrah my bad description. As you state the values can be changed as previously but what I really meant was the added ability to edit the new parameters for each gvar.
![screenshot from 2017-05-24 06-29-52](https://cloud.githubusercontent.com/assets/15316949/26375084/e3c8fdfa-404a-11e7-809f-58dbc6c7063c.png)
