### ISSUE TITLE
Global Persistent Timer

### ISSUE THREAD

**Issue by CraigHB** [opentx/opentx#4950]
There's no simple way I can find to create a persistent global timer that runs whenever the transmitter is on.  Would like to be able to keep track of how long the radio runs on a charge.  Any persistent timers created using a model revert to the last time recorded with that model active so it can't be done there.  Running Companion on Windows OS, OpenTX version 2.2.0 N371.

**Comment by kilrah** [comment]
Radio type?

**Comment by CraigHB** [comment]
Taranis Q X7

**Comment by rdeanchurch** [comment]
A nice feature.  It could also be used for the total time the Tx has been used.
If there was an EVENT for power off button depressed and maybe a Function script could write this data to the SD....given some processing time after EVENT _POWER_OFF button detected.  The delay for power off seems like more than enough time would be available.  
This could also be expanded to include a log for each models selected time.  
(the model log could be implemented now, I believe, for all except the last model, before the supposed EVENT _POWER_OFF.)

**Comment by jj604** [comment]
Kilrah, can I just comment that IMO it would be good to have a "simple" option exactly as CraigHB requested however in addition to any more powerful functionality. Not many users will be into scripting while all might find a "Time since last charge" useful. Both my original DX8 and my 10 year old Cockpit SX have such a manually resettable timer.  Thanks.  John

**Comment by mpjf01** [comment]
There presumably is a reason why only the QX7 is indicated as the enhancement target? From the discussion on RCG that prompted the request it would seem that it is desired on all platforms.

**Comment by kilrah** [comment]
All platforms already have a global running timer. It's simply not displayed anywhere on the X7 (and other 128x64 ARM platforms) and this is about adding it in the UI. Nothing to do with Lua or anything advanced, please open separate issues for that (there might even already be one).

**Comment by 3djc** [comment]
There is a timer responding to requirement of : " keep track of how long the radio runs on a charge.". On x9 for example, it is shown in statistics, and can be reset on demand by long menu press.

There is no UI for it (yet) on x7, that's what we will be adding

**Comment by mpjf01** [comment]
Thanks. What is SES - is it Session? My TOT showed a value of 15C9:26 or something before I reset it, what is the upper limit of this timer?

**Comment by 3djc** [comment]
It is a manual triggered thing, so you can use it to track whatever you want

**Comment by CraigHB** [comment]
Excellent, is there a way to find out when this will be added so I can make use of it?

**Comment by 3djc** [comment]
Not before 2.2.1, as can been seen in the milestone setting

**Comment by CraigHB** [comment]
So do I check a change log on 2.2.1 to find out if it's there?

**Comment by kilrah** [comment]
This issue will be closed when it's added.
