### ISSUE TITLE
Italian time sounds "rendering" is broken

### ISSUE THREAD

**Issue by mdenadal** [opentx/opentx#4952]
I'm used to set a button to play TH% Timer during flight (special functions->play value->Timer x).
Voice reading is fine in English but broken in Italian. 
The bug is really easy to reproduce but I'm not able to find a pattern to describe how the time to text conversion fails in Italian.

OpenTX version: 2.2.0N371 
Radio Tested: Taranis and Taranis+
SD Card version: 2.2V0009
Problem appears both in radios and simulator

**Comment by 3djc** [comment]
We do not speak italian, so we will not be able to fix it unless somebody explains how it works in Italian. Here is an exemple of what was done for Cz : https://github.com/opentx/opentx/blob/2.2/radio/util/tts_doc_cz.md

We will not be able to fix it unless someones details how things should be said in a way we can translate into code.

**Comment by mdenadal** [comment]
Well, I think the problem is not related on syntax or grammar issue.  
It should be more trivial. 
On OpenTX 2.1.x was working correctly.
In example: when timer is 00'30" the "play value" functions says: "Zero seconds", on 01'10" says "and 1 second", on 02'00" says "2 minutes",  on 02'30" says "2 minutes and 2 seconds" and so on.
Anyway I'll try to setup a dev environment and fix the bug myself.

Is 2.2 much different from 2.1 TTS wise?

**Comment by 3djc** [comment]
Yes, 2.2 units are different, but I would not rate that as too different. I won't have access to my dev env before monday, but given what you describe above, I should be able to work on that on monday

**Comment by mdenadal** [comment]
Ok, thank you very much! 
Let me know if I can help testing or writing some specs about italian syntax/grammar.

**Comment by 3djc** [comment]
Are you running next or N371? Already did a bunch of fixes in #4889 that are not in last rc

**Comment by mdenadal** [comment]
As stated in first comment I'm using N371.  Should I compile OpenTX myself to try next or can I find a build to download?

**Comment by 3djc** [comment]
If you give me a radio type and the option you use, I can compile one for you

**Comment by mdenadal** [comment]
Ok, compiling PyQt4 is driving me crazy so I accept you offer:  Taranis+, ppmus, noheli, lua, bindopt. Thank you very much. Btw, it would be interesting to try Companion as well, mainly for the simulator.

**Comment by 3djc** [comment]
http://downloads.open-tx.org/2.2/tests/opentx-x9d+-fix-italian.bin

Not meant to be flown, just for language testing

**Comment by mdenadal** [comment]
Tested right now. Seems to work fine! Time values are perfect, tomorrow I'll try other value types.

**Comment by 3djc** [comment]
I'm closing it, but feel free to report here issues if you find one
