### ISSUE TITLE
Allow a display off brightness of 0 when the mode is not set to off

### ISSUE THREAD

**Issue by RealTadango** [opentx/opentx#4954]
This should be save and allowes for a perfect dark screen during nightflying and maximum battery saving.

**Comment by kilrah** [comment]
Saving is insignificant.

**Comment by RealTadango** [comment]
But a setting of 5 is still bright when flying in pitch black, that is the main reason....

**Comment by chiefspecialk** [comment]
I agree some type of setting needs to be implemented for us night flyers. 5% is too bright in pure darkness.
