### ISSUE TITLE
companion 2.2 N371 crash

### ISSUE THREAD

**Issue by benoit35690** [opentx/opentx#4959]
Systematic crash trying to open this file.
[9XR-28052017.zip](https://github.com/opentx/opentx/files/1034016/9XR-28052017.zip)

I have a X9D profile, I tryed to convert a model to a 9XR PRO profile. It gaves errors.

**Comment by schwabe** [comment]
I cannot reproduce the crash on OS X. Does it crash when just opening the file?

**Comment by benoit35690** [comment]
Yes, Companion has crashed 3 times with same file, now it does not crash anymore...

**Comment by benoit35690** [comment]
Actually it crashes when trying to open the model "Claire"

**Comment by schwabe** [comment]
should be closed by #4963
