### ISSUE TITLE
companion 2.2 and 9XR-PRO

### ISSUE THREAD

**Issue by benoit35690** [opentx/opentx#4961]
I edit a model using companion and write it to the radio.
The copy to the radio is corrupted.

[9XR-symaX5.zip](https://github.com/opentx/opentx/files/1034082/9XR-symaX5.zip)
![dsc_0544](https://cloud.githubusercontent.com/assets/9080382/26527768/0b0670e8-439b-11e7-8a99-b9a0584a2cec.JPG)

**Comment by schwabe** [comment]
Is your attached file before or after the corruption?

**Comment by benoit35690** [comment]
before.
You can reproduce the problem starting from an empty model and writting it.

**Comment by schwabe** [comment]
with current 2.2 and the fix for your other issue I cannot reproduce this. Probably fixed in current code.

**Comment by schwabe** [comment]
Should be closed by #4963
