### ISSUE TITLE
Mac junk files break popup on Horus

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#4962]
No popups at all appear anymore until they're deleted and the radio rebooted, not sure which of the junk files cause it and at what time them being listed causes it.

**Comment by AJ-Acevedo** [comment]
Which mac "junk" files? The hidden macOS .DS_Store file?

**Comment by kilrah** [comment]
Either that or the individual ._xxx files that there is one for each other file in a folder. As said I didn't try removing them one by one to see which causes the problem, needs to be done.

**Comment by raphaelcoeffic** [comment]
@kilrah I think nothing is going to happen here until 2.3, right? Do we even know how to reproduce / fix?

**Comment by kilrah** [comment]
I could clearly reproduce at the time, but it's been a while since I did anything with radios on a mac and nobody else complained, so I guess if if it's still there it's not bothering many...
