### ISSUE TITLE
PXX and SPORT telemetry support for all boards

### ISSUE THREAD

**Issue by Dvogonen** [opentx/opentx#498]
The user backman8571 on openrcforums has  been trying to get 16 channels out of a 9xr with a XJR module and a X8R receiver. He uses two sbus converters connected to the receiver. 

As far as I understand, the combination should work.  According to the user's report he is able to get 16 channels by using stock er9x on his 9xr.

I have basically none of the hardware needed to replicate the problem,  so I am merely reporting what I have read. Here is one of the users posts on the issue from openrcforums (he has made several) 

---

I have found an openTX firware issue

If you have the XJT and using stock firmware on the 9XR and you have it set to support D16 when all 16 channels will be output and if you use the sbus for ch 9-16 all is well

If you now flash the 9XR with opentx, when i see this

1 no option to chose D8 or D16 with XJT selected.

2 if you have it set for PXX or PPM16 with 16ch selected, when you can see alloutput on the monitoring screen, but a big but you can only use 12 channels.

The programing for the sbus is correct since it worked with stock 9XR feirware and also with Taranis radio

Somwhow you can only use channel 1-12

13-16 will not work, only if you flash it back to 9XR stock, we even reflashed the module's and receiver's with the XJT firmware on frSky web site no difference.

So OpenTX software peoplewhat do you need from me so we can have a fix.

I also like to see the option like you have on the 9XR with selecting XJT and D8/D16 or long range mode and receiver number.

Regards

Per

**Comment by rhyde** [comment]
I was trying to figure out why this stopped working, I should have looked here first and saved my a lot of time.

**Comment by m1anh** [comment]
Is there any progress or an ETA on OpexTX supporting 16 Channels using the 9XR and XJT.
I have the hardware, Can I help with any testing?

**Comment by kilrah** [comment]
Not applicable anymore due to AVR support removal.
