### ISSUE TITLE
SDCard Changes Needed

### ISSUE THREAD

**Issue by Johnex** [opentx/opentx#4980]
I just noticed that the latest sdcard zip has lots of stray "output.mp3" files in all the sound folders.
The generator script is leaving them in it seems.

Also, i see that some script names like Crossfile.lua are longer than the max 6 characters for LUA names in OpenTX2.2

**Comment by 3djc** [comment]
Standalone scripts are not bound to the 6 chars rule

**Comment by Johnex** [comment]
And all the stray output files?

**Comment by kilrah** [comment]
See above, he fixed it for next version.

**Comment by Johnex** [comment]
Yeah sorry i didnt see the commit, removed my message but you got the email.

**Comment by kilrah** [comment]
Files on server now also updated.
