### ISSUE TITLE
X7 SD Card Contents S6 Calibration Images For Reference

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#4989]
It would be beneficial to add these images to the S6 folder or sub folder.
1 Label Up.png
![1 label up](https://cloud.githubusercontent.com/assets/20209851/26684281/810fecf8-46b4-11e7-9a32-9ea3134cbbfc.png)
2 Label Down.png
![2 lable down](https://cloud.githubusercontent.com/assets/20209851/26684286/81ad50c4-46b4-11e7-973c-17bc86f17fb1.png)
3 Pins Up.png
![3 pins up](https://cloud.githubusercontent.com/assets/20209851/26684283/8116521e-46b4-11e7-9b4d-940e28478e5c.png)
4 Pins Down.png
![4 pins down](https://cloud.githubusercontent.com/assets/20209851/26684285/811f4914-46b4-11e7-9096-5fa801840c33.png)
5 Label Facing You Pins Right.png
![5 lable facing you pins right](https://cloud.githubusercontent.com/assets/20209851/26684282/81121ece-46b4-11e7-9746-21d8c5fd4d35.png)
6 Label Facing You Pins Left.png
![6 lable facing you pins left](https://cloud.githubusercontent.com/assets/20209851/26684284/8119ae82-46b4-11e7-89fb-3848af8b8452.png)

[Archive.zip](https://github.com/opentx/opentx/files/1045058/Archive.zip)

**Comment by schwabe** [comment]
Could you eloborate? We already have pictures in X9 and Horus. For the X7 the images were to difficult to view on the remote iirc. @3djc can probably eloborate why we don't have pictures there.

**Comment by 3djc** [comment]
Given the very limited screen capability of x7, we do not handle pictures from Lua. They might seem to look OK on a pc screen, they would less so on the real lcd screen. That's why we went to the least ambiguous text we could think of
