### ISSUE TITLE
FAI Choice not available in 2.2.0 released version on Horus

### ISSUE THREAD

**Issue by jonlowe** [opentx/opentx#4991]
Compiled released Version 2.2.0 with FAI Choice option selected in Companion settings.  Choice is not available anywhere on Horus menus. This was the case in previous beta version RC16, but I just found it today. Not fixed in released version.  

My complier options are ppmus, lua, faichoice, noheli, and massstorage

In Taranis, this was a typo in the compiler setup, according to Kilrah. Don't know if that is the case here or not.

**Comment by 3djc** [comment]
It is indeed not implemented yet
