### ISSUE TITLE
Companion: RS & LS Inputs Missing

### ISSUE THREAD

**Issue by AustinSaintAubin** [opentx/opentx#4992]
Right & Left Sliders (RS & LS) inputs missing from Companion 2.2.0 for Taranis Plus (any maybe others). RS & LS can be added as inputs from the radio interface, but not through companion.

<img width="579" alt="screen shot 2017-06-01 at 8 10 03 pm" src="https://cloud.githubusercontent.com/assets/969780/26706899/78388778-4706-11e7-92eb-1de00bf84af2.png">

<img width="333" alt="screen shot 2017-06-01 at 8 17 00 pm" src="https://cloud.githubusercontent.com/assets/969780/26707006/4fe31508-4707-11e7-8990-3897b02a465b.png">

**Comment by powercycle** [comment]
Check in the hardware settings to ensure they are enabled.
![screenshot_2017-06-01_18-11-32](https://cloud.githubusercontent.com/assets/2614846/26708061/cf588b90-46f5-11e7-86f3-ba07d225b109.png)

**Comment by AustinSaintAubin** [comment]
You are correct Sir. The Hardware LS & RS was set to none. Which is odd because on the radio I was still able to assign RS & LS for use. Not sure how this was disabled. Thanks for your help.
 
<img width="764" alt="screen shot 2017-06-01 at 9 36 24 pm" src="https://cloud.githubusercontent.com/assets/969780/26708603/63a3adcc-4712-11e7-9e50-1b3bd9b02d08.png">

**Comment by SkyRaccoon** [comment]
Where is the Hardware menu ? I can't find it. Thanks.

**Comment by powercycle** [comment]
![screenshot_2017-08-04_18-01-37](https://user-images.githubusercontent.com/2614846/28992048-045247fc-793f-11e7-8553-b8b5b2760d6c.png)

After clicking on Edit radio settings, choose the hardware tab

**Comment by pghern** [comment]
I have changed these settings to access LS/RS in Companion but the settings do not save.... each time I start Companion I have to reset LS/RS in the Radio Settings - Painfull.
