### ISSUE TITLE
Model copy issue

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#50]
_From [bernet.a...@gmail.com](https://code.google.com/u/114409629465115275680/) on June 23, 2013 22:48:43_

Starting from a fresh eeprom, create:

Model 1
Model 2
Model 4

(model 3 slot is free)

Select model 1, then press down once to copy it. The first press puts it in the empry model 3 slot. Press down again, it moves model 4 to slot 3, and places the pending copy on model 4. Press down again, the pending copy goes to slot 5.

Issue is obvious, the second press should NOT move model 4.

_Original issue: http://code.google.com/p/opentx/issues/detail?id=50_

**Comment by kilrah** [comment]
Hehe this is still valid, got caught by it the other day...
