### ISSUE TITLE
Copy/Pasting Logical switches and Special Functions do not update dynamically

### ISSUE THREAD

**Issue by Excaliburst** [opentx/opentx#5001]
In Companion 2.2.0 (May 30th 2017) I have updated my locations of my logical switches and special functions via Cut/Paste of lines in these screens. And have discovered that they do not update their destination. The result is that my special functions where FUBAR... And I had to manually update them to get proper operation.

This must be a bug in Companion.

**Comment by kilrah** [comment]
It's normal, there is no automatic propagation of anything.

**Comment by Excaliburst** [comment]
That should be noted in the screens in Companion. Anyone using the Cut/Paste feature should expect this.

But thanks for the feedback.
