### ISSUE TITLE
[Companion] load Radio Profile when opening OTX

### ISSUE THREAD

**Issue by powercycle** [opentx/opentx#5002]
Sometimes I'm playing with X7 or Horus sim.   Quit for the night.

Come back sometime later (a couple of days), load the otx file for Taranis X9D+.   

The good news is, now it gives you a warning that things have been converted and it renames the file (that is great!)

Isn't too hard to close, select correct profile, re-open.

It seems to know that it needs to be converted, but not sure if it knows what the original radio was.

Since the otx file is likely a facimile of what is on the transitter, maybe storing some bits about radio and settings is possible.

No big deal if not.

Companion certainly is improved with the 2.2 release!

**Comment by kilrah** [comment]
Companion knows the radio type but since you could have multiple profiles with same radio type it still doesn't know what to select.
