### ISSUE TITLE
companion 2.2 and 9XR-PRO

### ISSUE THREAD

**Issue by benoit35690** [opentx/opentx#5006]
issue  #4961 was not fixed

try to write the "phoenixRC" model
[issue4961.zip](https://github.com/opentx/opentx/files/1052429/issue4961.zip)

in radio
model page "INPUTS" 4/11
- channels are now in order "Rud, Ele Thr Ail"
- look at inputs : there are now random offsets

**Comment by schwabe** [comment]
I created a pull to fix the problem. Note that the otx file already is "broken", i.e. the wrong offset are already in the otx file. The commit fixes Companion to correctly read and write those
![image](https://cloud.githubusercontent.com/assets/1038539/26824714/be4b7dc4-4ab2-11e7-9128-250fea11ce79.png)
