### ISSUE TITLE
trim as button (momentary or on/off switches)

### ISSUE THREAD

**Issue by booguiseb** [opentx/opentx#501]
it could be usefull,  if it was possible to use the trim button as momentary or on/off switch. May be they can appear as any of the other switches.
regards

**Comment by expipiplus1** [comment]
@bsongis Could you elaborate on how #592 fixes this, please?

One way I've found to do this is to:

* Disable the trim in the flight mode(s) you will be using
* Create two special functions for `<trim symbol><trim number>u` and `<trim symbol><trim number>d` which override a channel to the desired values for trim up and trim down
* Be careful not to override any channel you are using elsewhere

**Comment by kilrah** [comment]
The Txy switches can be used as a switch to enable a mixer line or any other thing a switch can be selected for.

**Comment by expipiplus1** [comment]
Thanks for the tip!
