### ISSUE TITLE
Unable to download firmwares

### ISSUE THREAD

**Issue by brunmorten** [opentx/opentx#5010]
Hi, not able to download firmwares or check for updates today. Is the server down for some reason?

**Comment by 3djc** [comment]
Hum, there seems to be an issue yes

**Comment by brunmorten** [comment]
Tried from the website (open-tx.org) and through the 2.2 Companion. Takes a while and then it says that it cannot access it.

**Comment by 3djc** [comment]
It was up a while ago, but there seems to be an issue currently, investigating

**Comment by brunmorten** [comment]
Thanks :)

**Comment by brunmorten** [comment]
Any eta on when I can try again?

**Comment by brunmorten** [comment]
It is up again :) Thanks alot :)
