### ISSUE TITLE
[9x] Cant access Radio Menu with a long menu press 9x-Stock (m128)

### ISSUE THREAD

**Issue by wdoler** [opentx/opentx#5014]
OpenTx Version: 2.2.0
Build: opentx-9x128-frsky-autoswitch-battgraph-en.hex

A short press does nothing and a long press (~2 seconds) goes to Model Menu. If I hold menu down longer (>30 seconds), it still goes to Model Menu.

**Comment by kilrah** [comment]
On the 9x the menus are accessed by long left and long right.
