### ISSUE TITLE
OpenTX 2.2.0 RC7 (N359): Aerofly RC 7 does not correctly read channel values

### ISSUE THREAD

**Issue by zkhalapyan** [opentx/opentx#5017]
Upgraded to the latest version from OpenTX 2.1, and after the upgrade, Aerofly RC 7 doesn't recognize the channel values. Using Taranis X9D+ transmitter, on MacBook Air running macOS Sierra 10. 

![screen shot 2017-06-07 at 8 33 07 pm](https://user-images.githubusercontent.com/796815/26911291-278aff1c-4bc1-11e7-893c-fe451f602b0c.png)
![screen shot 2017-06-07 at 8 32 51 pm](https://user-images.githubusercontent.com/796815/26911290-27893c7c-4bc1-11e7-873f-25d20f20d704.png)

**Comment by 3djc** [comment]
Why are you updating to a several month old beta version when 2.2.0 is available : http://www.open-tx.org/2017/05/30/opentx-2.2.0 ?

**Comment by projectkk2glider** [comment]
He is not using OpenTX RC7, but Aerofly RC 7.

@zkhalapyan do the channels move on the radio LCD screen when you move the sticks? Looks like the USB joystick is recognized.

**Comment by 3djc** [comment]
Well it says also n359...

**Comment by kilrah** [comment]
> He is not using OpenTX RC7, but Aerofly RC 7. 

In the title...

**Comment by Westone64** [comment]
zkhalapyan, was this issue able to be resolved? I am experiencing exactly this issue with a Taranis Q X7S running the stock openTX-x7s 2.2.0, with AeroFly RC7 on a Mac running High Sierra. So far unable to find a fix.

Thanks.

ETA: I updated to OpenTX 2.2.1 released in December, which unfortunately did not resolve the issue. I considered downgrading to 2.1, but the X7 does not support 2.1.
