### ISSUE TITLE
GLOBAL Custom Switches and Custom Functions needed

### ISSUE THREAD

**Issue by PeterVRC** [opentx/opentx#502]
Because the Taranis (or other OpenTX sytems with speech etc) can do SO MUCH, it means you can easily use a TON of Custom Functions in no time, per model.
Firstly, 32 is not enough....
Secondly, you have to cut and paste them across every model, which is slow and tedious - whether done in the TX, or in Companion9X.

This brings about several needs..... 
1) 
More Custom Switches and Custom Functions.  It may as well jump to "2x" and be 64 of each. Just add an extra screen for each of those.
OR
Have 32 Global Custom Functions and 32 Global Custom Switches - which is probably a better solution, because it removes a TON of copying/pasting need!

2) Better 'editing' ability in the  and in Companion9X - to make the setting up massively easier.  Quite simple stuff like "Page copying" where a whole page can be copied in one hit.

---

I hear there was a 'reason' NOT to have Global Custom Switches/Functions.... I think it was "Not all models will need the Globals you might add". eg a Throttle Cut Global, not wanted in a glider setup.....

Easily fixed...
The LOCAL screen, of the TX wide Global page,also shows tick boxes per line and a user can "Disable" a Global on a per model basis. So in a Glider you disable the Global Throttle Cut.
Now you might think that 'wastes' a CF in that local model. But it doesn't... because Globals, which are an EXTRA 32 CF's, never existed before anyway!  So they actually got 31 more than they ever had before if they disabled one. LOL

---

Having Globals saves a TON of replication across every model!!
And gives the solution to "needing more CS's and CF's" at that same time.

The FR Sky Taranis can EASILY eat up all 32 Custom Functions for a model!
It has SPEECH capability, and to use that to it full potential you can add a ton of Speech events.... even if they are 'luxury' and wasteful.  It is your radio and if you want to have it sing and dance 50 things, then good for you!  LOL
The Firmware is limiting the full capabilities.  Not in specific items - it can do the all.... but in MULTIPLES of those items.

**Comment by rguptaca** [comment]
Curious why global functions can't do everything special functions can? For example special functions have the option to replace a channel"s value. Useful for throttle disable. Can't do it through global functions.

**Comment by kilrah** [comment]
Global functions can't access anything model-specific, would cause a lot of edge cases and could be dangerous.

**Comment by griebd** [comment]
Well, you can get to a model already build where the throttle channel is 4, then, thinking you are safe be your global override, you turn your radio on, bind that electrical model and have a half powered engine running (channel 4 is normally your rudder and is in the mid pos)...
Channel override are model specific in my opinion....

**Comment by griebd** [comment]
but again, if available, it will be the user problem how to use and be safe!!!!

**Comment by rguptaca** [comment]
Open Tx is not for someone with limited knowledge. It already has features that "could be dangerous" :)

So as it stands now we could set a switch to play a track "throttle disable" but in reality it is not. 

Channel 1 is assigned throttle (TAER). What if throttle on the plane is on channel 3 (RETA) ? Or throttle is reversed. Or plugged into the wrong channel. Same problem as a global functioning overriding a channel to negative MAX.  

All my planes will have throttle cut on SA and CH1.

 I read the thread that prompted this feature and throttle cut was specifically mentioned as a benefit. 

We / I have picked throttle as a discussion point. My point is not only about throttle. Pro's and cons could be listed about feature.

I hope this discussion is helpful.  
Thank you to volunteers involved in this project.  

Rav

Have a wonderful day!

Ravi Gupta, PMP
Founder of Hike For Happiness
A Mental Health Fundraiser
http://hikeforhappiness.ca/
(519) 697-0796

On Aug 5, 2015, at 8:43 AM, Adriano Grieb <notifications@github.com> wrote:

Well, you can get to a model already build where the throttle channel is 4, then, thinking you are safe be your global override, you turn your radio on, bind that electrical model and have a half powered engine running (channel 4 is normally your rudder and is in the mid pos)...
Channel override are model specific in my opinion....

**Comment by rguptaca** [comment]
How about 
if global function  exists
  If is model specific
    Copy to model
else
    do nothing

Just a thought. Maybe too much work. 
Thanks for the response :)

Rav

Have a wonderful day!

Ravi Gupta, PMP
Founder of Hike For Happiness
A Mental Health Fundraiser
http://hikeforhappiness.ca/
(519) 697-0796

On Aug 5, 2015, at 2:03 AM, Andre Bernet <notifications@github.com> wrote:

Global functions can't access anything model-specific, would cause a lot of edge cases and could be dangerous.
