### ISSUE TITLE
Telemetry loop taranis QX7 CRSF protocol

### ISSUE THREAD

**Issue by stevef1966** [opentx/opentx#5021]
Hi seem to have an issue using CRSF on a taranis QX7 with the TBS crossfire, all devices on the latest recommend firmware, CRSF works but the QX7 keeps reporting telemetry lost/recovered.

If I switch top PPM to talk to the crossfire the warnings from the qx7 stop

Have checked the pins in the module bay and checked the soldered connection of the pins to the qx7
Have even jumpered the pins from the qx7 to the crossfire thx but still the same

**Comment by 3djc** [comment]
Duplicate #4922

**Comment by stevef1966** [comment]
apologies, didn't realise it had been included as an issue, thought id have to open a new issue, will know for next time - keep up the great work
