### ISSUE TITLE
OpenTX 2.2.0 telemetry FrSky DJT Turnigy 9X does not work "NO DATA"

### ISSUE THREAD

**Issue by wikmas** [opentx/opentx#5022]
As in title. In 2.1.9 it is OK.

**Comment by frizzy** [comment]
I have the same issue. Used to work fine in 2.1.x

**Comment by nitzo** [comment]
+1 I have the same issue. Will not work on 2.2.0. After downgrading to 2.1.x works fine

**Comment by voltlog** [comment]
same here, not working.

**Comment by goahead0** [comment]
The same here. 2.0.19 and 2.1.x working. 2.2.x no telemetry - no-data.
Config: turnigy 9x with FrSky DHT module, modified bypassing the MAX3232 (or whatever RS232 interface chip it was). After downgrading it works again.

**Comment by kilrah** [comment]
Don't use 2.2 on a 9X, we actually pulled it away and will stop offering it for AVR platforms. Stay at 2.1 which will become the last version supporting those.
