### ISSUE TITLE
Center Beep For the Right Slider5 RS

### ISSUE THREAD

**Issue by ictea-rc** [opentx/opentx#5024]
In the Setup Page of the model if checking the box for the Center Beep for the Right Slider RS only, instead of playing the "beep" track when RS is centered, the following is played: "Timer 1 elapsed".  The LS box is working fine.

I think it's a firmware issue, because it happens in the Companion as well as programing the radio directly.

**Comment by powercycle** [comment]
I can't reproduce this on the transmitter and simulator (X9D+) using May-31-2017 2.2 release.  
You don't mention radio type.

**Comment by powercycle** [comment]
I tried to use the simulator for the X7 and Horus, but don't know how to make the item go up and down (like +\- on X9D+)

**Comment by ictea-rc** [comment]
The radio is X9E w/ 2.2.0

**Comment by 3djc** [comment]
This is a bug indeed
