### ISSUE TITLE
openTx V2.20  X9D X9E  no Template at SD-Card, fix integrated at openTx now?

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5025]
Hy,
I miss the Templates at SD-Card.

Is it now fix integrated  at openTx?
Because I want rewrite it for other  Languages, other picuters, for Q7 only as selection Texts,

Can change the lua files at PC and at Tx, but allways only the original Temp appears.

Same at Companion, Simulator, Tx,  only original Template

**Comment by schwabe** [comment]
There is to be multiple issues here mixed in one:

- translation of lua files (probably wizard)
- templates directory on sdcard (planned but never implemented #5027)
- I don't understand the last sentenc, can you provide a bit more details? What are you modifying and what do you expect and what is happening instead?
