### ISSUE TITLE
Enhancement new special function action copy trims to subtrims

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#5030]
The request for this action was mentioned in a Painless360 video on Plane Maiden - Tips and Tricks.
Easier to perform the action with a switch when trim adjustment limit reached in flight.

**Comment by powercycle** [comment]
Try Instant Trim special function.  I think that will do what you want.
Also, you can do something on the radio, but it doesn't seem to exist on companion.
At the bottom of the Output screen.
![screenshot_2017-06-13_06-06-34](https://user-images.githubusercontent.com/2614846/27086384-7f43b7bc-4ffe-11e7-8499-4379aeeb22db.png)

**Comment by kilrah** [comment]
And much easier to make your model unflyable by a single button press too.
There is already Instant trim for that as mentioned, with limited authority. You can use extended trims if you expect such deviation though.

**Comment by elecpower** [comment]
Yes Instant Trim does to a degree but up until you run out of trim. Yes Extended Trim can further assist. Yes if you have an extra pair of hands on the flight line you can perform the copy.

"And much easier to make your model unflyable by a single button press too"

There are many places not just special functions in a model config to make a model unflyable. The use of this requested action like any of those methods even if used erroneously should be up to the pilot. This is the beauty of OpenTX and why it is so popular. If you want out of box limited functionality you buy a name brand radio with proprietry software.
Please consider reopening.

**Comment by kilrah** [comment]
Again Instant trim with Extended trims enabled does exactly that, so no.
