### ISSUE TITLE
Feature Request: "horussticks" build option for Taranis X7

### ISSUE THREAD

**Issue by auric1** [opentx/opentx#5031]
Hello,
  this mod is well documented, and supported by various 3d model projects, and as of late, has become quite popular. Please consider this addition as it would save enthusiasts a significant amount of time and confusion for newer pilots alike.

Re: Install M9 Gimbals in Taranis QX7
https://oscarliang.com/install-m9-gimbals-taranis-qx7/

**Comment by 3djc** [comment]
M7 are becoming available, aren't they?

**Comment by schwabe** [comment]
We are currently implementing a version that detects sticks direction calibration so no build option will be needed anymore.
