### ISSUE TITLE
Horus openTx V2.20 Screenshot function missing

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5032]
Hy,

realy missing the screenshot function at Horus openTx V2.20
importend for helping people at starting with frsky
writing manual, settings and so on

**Comment by 3djc** [comment]
You can screenshot from the simulator, but anyway, duplicate #3393

**Comment by hrenz** [comment]
At simulator I have  only english as Language
At Horus I have  the setting language, and I can make a screenshot on the field
