### ISSUE TITLE
opentx 2.2 logical switches chrono

### ISSUE THREAD

**Issue by FlipAirboost** [opentx/opentx#5036]
Logical switch panel,
 chrono function,
 the time programmed in the duration column is no longer taken into account **at the right time** with opentx 2.2.0
Same parameters worked fine with opentx 2.0.20.
![inter logique](https://user-images.githubusercontent.com/29504813/27263220-48591c36-5465-11e7-8cbe-9f7ba0b2b6dc.JPG)
![fonctionspecialetimer](https://user-images.githubusercontent.com/29504813/27510114-bb339aca-590a-11e7-881d-fd6f5d280b4b.JPG)
 **Corrective solution**
![reset vs define](https://user-images.githubusercontent.com/29504813/27517788-65815446-59d2-11e7-8ca3-f42f3130d609.JPG)
With opentx 2.2
L01 and L02 are activated at the same time.
L01 for10 s and L02 for 25s

With open tx 2.0 L01 is activated 10s then L02 is activated 25s.

**Comment by FlipAirboost** [comment]
Version 2.2 _speaks_ (I will say **read**)more slowly and is only able to announce time every 2 seconds with the same sound pack "amber as version 2.0.
Open tx 2.0 can announce time almost every second.

**Comment by projectkk2glider** [comment]
Your first problem is not understandable. Your picture does not correspond with the description provided for L2. 

Your second problem: you can use another sound pack that has shorter (ie faster) sounds. This is not a bug.

**Comment by FlipAirboost** [comment]
Hi projectkk2glider,
First problem: I have updated my first post and here are two videos.
I edit the timer to shorten the videos but you can see Lxx highlight it.
https://drive.google.com/file/d/0BzFhb9hmRA8Pb2NSTEFSNzRudEk/view?usp=sharing
https://drive.google.com/file/d/0BzFhb9hmRA8PNnFqbHJuM0gxbDA/view?usp=sharing

Secondly, same sound files need same start up playing time to be read simultaneously , in my opinion.
Why opentx 2.2.0 can't handle it?

**Comment by kilrah** [comment]
> Version 2.2 speaks (I will say read)more slowly and is only able to announce time every 2 seconds with the same sound pack "amber as version 2.0.

There should not be any change there, it isn't even possible for a speed difference to happen.
You DO need different sound packs for both so the difference is most likely there.

**Comment by FlipAirboost** [comment]
Wat a pity, I love Amber voice!
![soundpack](https://user-images.githubusercontent.com/29504813/27511040-2a08fae6-591d-11e7-9285-ec2b241546a8.JPG)
Amber Sound files are lighter yet.So there is more than a difference in name length and filename?
Here are my renamed system sound files.
https://drive.google.com/drive/folders/0BzFhb9hmRA8POXZJVFlSTFJDdkk?usp=sharing
You watched and listened to the videos?
Regards Philippe

**Comment by FlipAirboost** [comment]
Kilrah says
> There should not be any change there, it isn't even possible for a speed difference to happen.
>  You DO need different sound packs for both so the difference is most likely there.

O.K. I tried it with the official sound packsdcard-taranis-x9-2.2V0010 , same problem, there is a restriction in the pipeline,similarly, on the simulator and TX
video here:
https://drive.google.com/file/d/0BzFhb9hmRA8PVmNUYzVaam1yMm8/view?usp=sharing
Regards Philippe

**Comment by kilrah** [comment]
> https://drive.google.com/file/d/0BzFhb9hmRA8Pb2NSTEFSNzRudEk/view?usp=sharing
https://drive.google.com/file/d/0BzFhb9hmRA8PNnFqbHJuM0gxbDA/view?usp=sharing

There seems to be a difference in behavior between 2.1 and 2.2 indeed, but 2.2 is more correct.
If you check well, the announcement on 2.1 does announce every second but it gets late becasue the files take too long to play, so much that at 8 seconds it's actually one second late and skips straight from 8 to 10. That's kinda useless.
2.2 doesn't do that and if it's too tight it doesn't play.
My personal sound pack has shorter files and they do play each second on 2.2 (until it gets to longer files like 23).

All normal then.

**Comment by FlipAirboost** [comment]
> >but 2.2 is more correct.

 
I agree with that.

> > All normal then

No, the logic switches do not work as expected, as you can clearly see on video.

**Comment by kilrah** [comment]
I only referred to the speech.

Still not understanding your point about the LSs. You say 

>the time programmed in the duration column is no longer taken into account at the right time with opentx 2.2.0

That doesn't really mean anything.... what do you mean by "at the right time"??

Please do a **complete** description of what you're actually talking about, what's the **end result** that you're looking for and why it isn't working as expected. Avoid talking of what you think is leading to it not working, or we will fall in an [XY Problem](http://xyproblem.info/) situation.

Videos aren't much help when you have no idea of what you should be looking at, and ideally provide both your 2.0 and 2.2 settings files so we can easily reproduce once we understand it.

**Comment by kilrah** [comment]
As expected, XY Problem.

Your actual issue is "Timer 1 doesn't stay at 0 during the time the logical switch that triggers the Reset Timer 1 is active".

This has nothing to do with logical switches, they work perfectly fine. The Reset special function was however changed from being active as long as the switch is on to only be triggered once when the switch is turned on. 
This was an undesired side effect of a fix for another problem and will be reverted in 2.2.1. 

In the meantime you can use "Set Timer1 00:00:00" instead.

**Comment by projectkk2glider** [comment]
I will reference issue #3858 here, if we ever need to find it, because its solution caused this issue.

**Comment by FlipAirboost** [comment]
Thank you all,
It can remain as it is once you know that.
I updated the first post.
Regards 
Philippe
