### ISSUE TITLE
TARANIS X9E - menu wheel (encoder) trouble

### ISSUE THREAD

**Issue by bandurat** [opentx/opentx#5037]
Hi, I have a trouble with menu wheel (encoder).
On bootloader mode everything is OK, the menu wheel works good, but on "normal mode" sometimes the menu wheel is frozen, or it works strange.
I tried a firmware change and factory reset, but it did not solve the problem.
What should I do with this?
Thank You very much.

Here are the videos:
https://www.youtube.com/watch?v=9BbKqx2vFww
https://www.youtube.com/watch?v=h5Sbo8DU6Gg

**Comment by 3djc** [comment]
I'm using an x9e daily, never experienced anything like that. Any lua scripts running? If not I would suspect hardware

**Comment by bandurat** [comment]
No, I have no lua script.
It is a new radio I bought it one month ago. But I think it is not a hardware problem, because on bootloader mode everithing is OK. :/

**Comment by kilrah** [comment]
Maybe mention your firmware versions....?

**Comment by bandurat** [comment]
Of course, now I have 2.2.0. But with 2.1.6 or 2.1.9 I had a same problem. On videos You see 2.2.0 FW with 2.1.6 bootloader, but I also upgraded bootloader to 2.2.0 with no result.

**Comment by kilrah** [comment]
Can't think of anything but flaky hardware since no one else has that problem.

**Comment by bandurat** [comment]
Likely yes, but I don't understand why it is OK all the time in bootloader mode... :/

**Comment by kilrah** [comment]
The bootloader might read the keys at a different speed or in different order, and that doesn't reveal the issue...

**Comment by schwabe** [comment]
Might be something simple like a loose ground connection. That would also explain that behaviour but I agree, there is something fishy with your hardware.

**Comment by projectkk2glider** [comment]
Closing since this appears to be a hw issue. I have two radios with encoder, none of them has this issue.
