### ISSUE TITLE
Can't download FW

### ISSUE THREAD

**Issue by diggit** [opentx/opentx#5040]
Companion22 reports "Invalid firmware" when it attempts to download FW for my X7.
I can read download link from stdout [`http://downloads-22.open-tx.org/nightly/firmware/getfw.php?fw=opentx-x7-eu-noheli-lua-bindopt-massstorage-sqt5font-en.bin`](http://downloads-22.open-tx.org/nightly/firmware/getfw.php?fw=opentx-x7-eu-noheli-lua-bindopt-massstorage-sqt5font-en.bin)

When I try to visit this link in browser, I get `ERROR:5` response.

Is FW building service down?

**Comment by kilrah** [comment]
You're probably still using a companion RC and trying to download firmware nightly builds, you must update to 2.2.0 release.

**Comment by diggit** [comment]
Thanks for fast reply!
Updated companion to version 2.2.0 and everything works well.
