### ISSUE TITLE
X7 poweroff on USB unplug (massstorage)

### ISSUE THREAD

**Issue by diggit** [opentx/opentx#5041]
I am using openTX 2.2.0 release with enabled massstorage option on my X7. When I connect USB to transmitter, massstorage works well, but when I try to unplug USB cable, transmitter powers off (instantly). Doesn't matter if I mount storage or not. It does not happen with massstorage disabled FW.
Running archlinux on PC.

Is this behavior intentional?

**Comment by kilrah** [comment]
Yes. After accessing the card/eeprom from the PC a reboot is needed before further use, that forces it.

**Comment by Hartinger** [comment]
Understood, but why is the reboot not initiated automatically as for the X9E?

**Comment by 3djc** [comment]
This is currently different on x9e  but this is likely to get harmonized
