### ISSUE TITLE
Sudden power off on opentx 2.2.0 ?

### ISSUE THREAD

**Issue by skorzo** [opentx/opentx#5043]
I have been flying my Taranis 9XD+ without issues on opentx 2.1.9

Yesterday, after some days on 2.2.0, my device suddenly powered off while the switch was in the ON position.

I had to switch back to off and then  to on in order to recover the Taranis, but by the way my multirrotor had already crashed.

Any power issues on your side?   Thanks!!

**Comment by 3djc** [comment]
I do not think we have had any similar reports

**Comment by bsongis** [comment]
First report like this!

**Comment by schwabe** [comment]
I once had that when my battery was completely empty but I screwed up my warning levels for TX battery.
