### ISSUE TITLE
Cant Select Sensor in the calculated sensor menu

### ISSUE THREAD

**Issue by merinkumar** [opentx/opentx#5048]
Hi, Am using opentx 2.2 on both the simulator and qx7 radio, am not able to add an calculated current sensor, please find the attached screen shot. The sensor just displays --- but cant select " curr. " Please help

![qx7_2 2_sensor](https://user-images.githubusercontent.com/3846152/27352537-b292649e-561e-11e7-9419-fbb68a93d06e.JPG)

**Comment by kilrah** [comment]
This only shows actual current sensors, that have been detected properly so the unit is set right.

This is not a place for usage questions.

**Comment by olyrhc** [comment]
I've also had this issue with OpenTX 2.2.

I can create a new calculated sensor in Companion and set the source-sensor to "Cells" (for example) and it works fine. If I try to duplicate it in OpenTX 2.2, it refuses to let me select the "Cells" sensor, even though it's been detected properly.
