### ISSUE TITLE
Taranis Q X7 switches itself off after disconnection of USB cable

### ISSUE THREAD

**Issue by Hartinger** [opentx/opentx#5052]
Taranis Q X7 + OpenTx v2.2.0
Windows 10

With #3840 a problem regarding the Taranis X9E USB connection (v2.1.9 with 'mass storage' option enabled) was reported. The problem was fixed in v2.2.0 and my X9E now works fine when connected and disconnected to/from the USB during normal operation.

With my new Taranis Q X7 (v2.2.0 and 'mass storage' enabled) a new problem has appeared.
When I connect the Radio to the USB during normal operation, it works fine (no termination of the USB link). However, when I then disconnect the USB cable, the Radio switches itself off. This happens regardless of whether I eject the drives before disconnecting or not.

There are no issues when the USB is connected/disconnected during bootloader operation.

**Comment by 3djc** [comment]
https://github.com/opentx/opentx/issues/5041
