### ISSUE TITLE
Throttle warning on different switch

### ISSUE THREAD

**Issue by Kennlicht** [opentx/opentx#5053]
Because I'm now convinced that this is a bug or at least a source of improvement, I would like to reopen issue #5042.

Here is a screenshot of what I'm doing:
![opentx-throttle-bug](https://user-images.githubusercontent.com/29534157/27467330-e9f70d9e-57e1-11e7-8779-fa63f7a10d52.png)

I've configured the "Throttle Source" to CH04, which is mixed from switch SA and not from the throttle stick. Timer 2 reacts on that source as expected. All ok up to this point.

Additionally I turned the option "Throttle Warning" on. Now I get this warning every time when turning my radio on with the throttle stick not in its lowest position. But this warning is not related to my switch SA respectively to CH04. I think it should!

OpenTX still warns me with a switch warning, but it's likely to overlook the throttle position (SA in my case) and ignore the warning by pressing a button. A second warning like the throttle warning would be really nice.

**Comment by powercycle** [comment]
What if a dialog box was displayed based on a special function?  

Could this currently be accomplished with a lua script maybe?

**Comment by jtaylor2** [comment]
>What if a dialog box was displayed based on a special function?
>Could this currently be accomplished with a lua script maybe?

A throttle warning needs to be displayed before the rf is turned on or the throttle channel enabled.  I don't know LUA, but doubt it is available that early in the startup.

**Comment by 3djc** [comment]
It's not, and LUA cannot 'jump' at your screen either, it needs to be called manually

**Comment by Kennlicht** [comment]
Seems to be fixed in 2.2.1 RC3. Perfect!
