### ISSUE TITLE
Alert on model change if telemetry being received from current model.

### ISSUE THREAD

**Issue by hymanroth** [opentx/opentx#5059]
We've had a few issues at our flying club recently when people have changed models without disconnecting the battery from the current model. Depending on the receiver's fail-safe settings, this situation has the potential to be quite dangerous.

This got me thinking that it would be quite easy to show an alert on model change if the transmitter knew it was currently communicating with another receiver.

**Comment by projectkk2glider** [comment]
Loosely related to #4324

**Comment by RCdiy** [comment]
On the Q X7 maybe have a shutdown warning since it is a soft switch? 
"Rx Connected. Are you sure you want to shut down?"

**Comment by 3djc** [comment]
This has nothing to do with shutdown ...
