### ISSUE TITLE
Companion 2.2.0 GVARs not simulated

### ISSUE THREAD

**Issue by jrobsonchase** [opentx/opentx#5065]
OS: Arch Linux
Version: 2.2.0-2

Issue: GVARs never seem to update in the simulator. They're always 0.

Steps to reproduce: Create a new model, then add a special function as such:
![2017-06-27-170356_1297x51_scrot](https://user-images.githubusercontent.com/1553581/27609975-a8f8a448-5b5a-11e7-86f8-d083bb7ba8c7.png)

Then go to the simulator, click View -> Radio Outputs (to get the gvar display), and then slide RS around.

![2017-06-27-170622_1102x549_scrot](https://user-images.githubusercontent.com/1553581/27610071-f5785020-5b5a-11e7-93ca-47c7113d34e6.png)
![2017-06-27-170646_944x525_scrot](https://user-images.githubusercontent.com/1553581/27610092-0507e050-5b5b-11e7-8f9b-8d2109987502.png)

Expectation: The gvar moves with RS
What I'm seeing: It's just 0.

I noticed this when I updated from 2.1 and my models suddenly stopped behaving as expected. When written to my x9d+, everything looks fine. It's just the simulator that's being weird.

Edit:
Uploading my model for easier repro (rename to demo.otx if the extension is a problem - github didn't like it before)
[demo.zip](https://github.com/opentx/opentx/files/1106826/demo.zip)

**Comment by 3djc** [comment]
What was the installer you used ? Because it does work fine.

**Comment by jrobsonchase** [comment]
It was built using this AUR package: [opentx-companion.tar.gz](https://github.com/opentx/opentx/files/1109899/opentx-companion.tar.gz)

Actually, looking at [the comments on the package](https://aur.archlinux.org/packages/opentx-companion/), the maintainer mentions getting the simulator to work "soon." Is there something incorrect about the build method in the PKGBUILD?

**Comment by 3djc** [comment]
It is not built by us, and this unofficial version is not built correctly . We already raise awareness about that, and recommended for the maintainer to look at our build scripts

**Comment by bsongis** [comment]
@3djc wait, I am on Manjaro, I can have a look, I didn't know there was already something done in the AUR!

**Comment by jrobsonchase** [comment]
Just looking through the wiki, I might have found the issue. Is the missing `-DGVARS=YES` flag the culprit?

I'm almost done recompiling now - will report back with the results when it finishes.

**Comment by 3djc** [comment]
Here is how we build : https://github.com/opentx/opentx/blob/2.2/tools/build-companion-release.sh

**Comment by jrobsonchase** [comment]
@3djc Thanks, I'll see how hard it is to adapt that to an arch-friendly package
