### ISSUE TITLE
"convenient mode" missing from S6R Lua script

### ISSUE THREAD

**Issue by Jmelz** [opentx/opentx#5067]
On June 5th, FRSKY introduced a new firmware with a "simple" or "convenient" mode that only allows for 2 flight modes and "off".

https://www.rcgroups.com/forums/showpost.php?p=37669372&postcount=3106

The Lua script appears to be missing the checkbox to enable this functionality. The PC app has a checkbox called "convenient mode" while FRSKY referred to the feature as "simple mode".

In other words, if a user updates the firmware on an s6r with this firmware file, they are still unable to select convenient mode by using the lua script.

**Comment by 3djc** [comment]
There is no such official firmware : http://www.frsky-rc.com/download/view.php?sort=&down=393&file=Firmware-%20S6R

**Comment by Jmelz** [comment]
hi 3djc,

correct, is not official, but it was released by FrSky and communicated from their official account on rcgroups.

I'm not sure what they wish to do with this file, but I am just pointing out that the functionality does not yet exist in the lua script.

**Comment by kilrah** [comment]
And it can't exist if we're told nothing about how to make it work and it's not even available to reverse-engineer...

**Comment by Jmelz** [comment]
Completely understand - I've contacted FrSky and asked them to commit the fw as official so that the lua script can be updated.

**Comment by Jmelz** [comment]
FrSky said they will be reaching out soon. They have now placed the firmware on the website at least:

http://www.frsky-rc.com/download/view.php?sort=&down=394&file=Beta Firmware-S6R

**Comment by Jmelz** [comment]
https://github.com/opentx/opentx/pull/5099#issuecomment-320323349

Not sure if this was tested on a q x7, but seems to not be working as planned :(

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/28983379-c771e728-7959-11e7-9dcb-00eef12c553e.png)

![image](https://user-images.githubusercontent.com/5167938/28983390-d07185ae-7959-11e7-8a06-f77adc5fed54.png)

**Comment by Jmelz** [comment]
Very interesting... I reflashed my receiver with the zip file I pasted. What version are you using?

**Comment by 3djc** [comment]
S6R_FCC_170615.frk

**Comment by Jmelz** [comment]
Very strange indeed. I confirmed I'm using the SxR.lua for the x7... I reflashed fw again, and no dice. I'll test some more. Thanks for your quick reply and photos 👍 

EDIT: Looks like I had the script copied incorrectly. I grabbed raw text and recreated - all is good (even on my other receivers that I had, so I didn't have to reflash anything). Thanks again for your patience.
