### ISSUE TITLE
QX7 drawPixmap enable ?

### ISSUE THREAD

**Issue by aurelx03** [opentx/opentx#5069]
Hi,
I would like know if its possible to enable drawPixmap for the QX7, i know resolution of qx7 screen is small but need to upload small image for custom screen script or other. It is a pity to disable a function between 2 radios.

Kiss friends <3

**Comment by 3djc** [comment]
Not only is the resolution lower, but it does not do greyscale either, it is pure 1 bit bitmaps, not helpful at all

**Comment by aurelx03** [comment]
yeah but for example you would draw an icon or a splash screen for your script u must draw the picture pixel by pixel its annoying

**Comment by rdeanchurch** [comment]
One bit on the low res screen is not perfect, 
but it beats nothing by a country mile.
Please consider putting drawbitmap for Qx7.
![deansplashscreen](https://user-images.githubusercontent.com/4843199/28174154-8be8e9a6-67a5-11e7-89b3-c6d7d17bffd2.PNG)

**Comment by RCdiy** [comment]
Better than nothing. At least it gives us a choice to live with the image or not.

**Comment by 3djc** [comment]
Done in https://github.com/opentx/opentx/commit/541aa459cf5e368dbff916553e4124abc43e2fb9
