### ISSUE TITLE
Unable to flash XM+ version request failed

### ISSUE THREAD

**Issue by sensei28** [opentx/opentx#5072]
Look at https://www.rcgroups.com/forums/showthread.php?2870872-Unable-to-flash-XM-version-request-failed

same problem

**Comment by 3djc** [comment]
We just confirmed it working on a 2.2.0 X9D+ and XM+,, as well as Horus and XM+. In both cases, flashing did not produce and error and went fine. It must be something with your setup.

**Comment by sensei28** [comment]
my setup is not wrong. i received "firmware update error: version request failed"

**Comment by kilrah** [comment]
We did try it with an XM+ and our radios and it works, so it's not an OpenTX problem. Either you've done something wrong or your receiver is defective.
You did not include any details like what radio and firmware version you're using so even if we wanted we can't help further.

**Comment by sensei28** [comment]
i am using taranis x9d+ and open tx 2.2.0. Receiver is a brand new receiver. After getting this error, i cant bind receiver. But before flashing i did.

**Comment by sensei28** [comment]
i can record a video if you want

**Comment by kilrah** [comment]
No point - as said it's nothing we can do anything about.

**Comment by sensei28** [comment]
i tried 2 brand new receivers and same error. Is it possible that receivers are fake. i bought from banggood.

**Comment by kilrah** [comment]
Why are you trying to flash them in the first place?

**Comment by sensei28** [comment]
i want to get rssi on channel 16 at betaflight.

**Comment by kilrah** [comment]
Well, the only thing we can advise is to contact your seller and get help or a replacement from them.

**Comment by sensei28** [comment]
ok ty so much for your help
