### ISSUE TITLE
cant use sd card in taranis x9d plus

### ISSUE THREAD

**Issue by jasonp1976** [opentx/opentx#5075]
i recently updated my x9d+ with the 2.2 firmware. after installing the firmware i lost all sound. after looking into it further my transmitter dosent find the sd card what so ever, says "SD card is missing". i have formatted the sd card (fat32 not the quick format), i bought two new sd cards. i have confirmed i have the correct drivers installed (winbus and masstroage). i even re flashed to the older 2.1.9 firmware with no luck. i do have the new SD card contents installed and it works fine on my sons transmitter. the transmitter works fine as it is,  but flying fpv i like the extra sounds and noises. any help would be greatly appreciated

**Comment by 3djc** [comment]
This is not a place to ask for help, only to log bugs. Please consult forums like rcgroups, or openrcforums.com
