### ISSUE TITLE
Can't download any version on site

### ISSUE THREAD

**Issue by Arti3DPlayer** [opentx/opentx#5077]
http://www.open-tx.org/2017/05/30/opentx-2.2.0

http://downloads.open-tx.org/2.2/companion/macosx/opentx-companion-2.2.0.dmg

`Unable to connect`

**Comment by aelen71** [comment]
Yea i try to download the windows version for about 2 hrs already. 
Tried other versions as well and contacted a friend from different country to check if it's my local problem or not. No luck.

**Comment by kilrah** [comment]
Server's down, waiting on hoster.

**Comment by aelen71** [comment]
Ok it's back. :)

**Comment by gibbster** [comment]
looks like http://downloads.open-tx.org/ is down again :-( Is there a cache available somewhere? In particular I'm looking for http://downloads.open-tx.org/2.2/sdcard/opentx-x9d+/sdcard-taranis-x9-2.2V0010.zip

Much appreciated!
