### ISSUE TITLE
RX8R sbus issue 

### ISSUE THREAD

**Issue by Aris2024** [opentx/opentx#5082]
Sorry for the off topic

**Comment by kilrah** [comment]
You must ask this to FrSky or other users of the setup on forums, we do not control anything that happens receiver-side nor do we know about all the workings of that.

 The only thing we can recommend is you update firmware of the receivers and module (flash FrSky OS, boot once, see module being flashed, flash OpenTX again).

**Comment by Aris2024** [comment]
ok thank you very much!
