### ISSUE TITLE
can't download sd file zip files from site

### ISSUE THREAD

**Issue by gibbster** [opentx/opentx#5084]
Hello! 

It looks like http://downloads.open-tx.org/ is down. Is there a cache available somewhere? In particular I'm looking for http://downloads.open-tx.org/2.2/sdcard/opentx-x9d+/sdcard-taranis-x9-2.2V0010.zip

Much appreciated!

**Comment by 3djc** [comment]
It will be available when the server is back up

**Comment by kilrah** [comment]
Back up now.
