### ISSUE TITLE
OpenTX 2.2 range issues. 

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#5086]
Hello,

I have recently updated my Taranias x9d to the 2.2 branch (lua, noheli, non eu) from the 2.1.7. The update itself was easy, but I now experience a extreme range problem with my XSR.

The transmitter acts as it would be in a constant range check mode if not worse. I get a low warning at 20m, critical at 30m and a few failsafe switches in this range. The exact same receiver was working fine before the update (at least few hundred meters range).

I will try to switch the receiver, but could it be related to the update?

**Comment by 3djc** [comment]
Opentx does not deal with the radio link itself, so no reason for it to be related

**Comment by ghost** [comment]
Is it not? The radio link (its protocol) is configured from within OpenTX, the range check is configured from within OpenTX. 
So it's easy to say.. hardware issue not my problem. So the update broke my hardware as it was perfectly working before the update.
Case closed. Thank you for your help.

**Comment by kilrah** [comment]
Of course OpenTX tells the module what to do... but if it was telling the module to be in range check mode don't you think everyone would have the same problem?
