### ISSUE TITLE
Stickrev broken again

### ISSUE THREAD

**Issue by zmoothrc** [opentx/opentx#5087]
Just updated my 9X to 2.2.0 from 2.0 and stickrev stopped working. Missing from compile or bug?

**Comment by projectkk2glider** [comment]
'FRSKY_STICKS' option is missing from the cmake files! 

It is present in the compilation script.

**Comment by projectkk2glider** [comment]
Another thing to check. The `"stickrev": ("FRSKY_STICKS", "YES", "NO")` is present in the `fwoptions.py` for the 9X, but not for the 9XR, while the source suggests that 9XR also supports this option.

**Comment by kilrah** [comment]
I believe that was intentional becasue FrSky sticks don't physically fit in the 9XR.

**Comment by kilrah** [comment]
Hmm, it is available for selection in companion, so maybe not

**Comment by 3djc** [comment]
```
elif options[optcount] == "9xr":
    command_options["PCB"] = "9XR"
    firmware_options = options_9x
```
So I'm guessing 9XR is covered as well
