### ISSUE TITLE
Add RX number to the model list in Companion

### ISSUE THREAD

**Issue by pointu** [opentx/opentx#5088]
Can u add the rx number in the model list ?

**Comment by agibson2** [comment]
That would be a nice feature to quickly see what is available.  Another idea might be to somehow indicate which numbers are in use by models with a * next to them or something when changing a rx number for a model.

**Comment by pointu** [comment]
Bonjour,

En congès jusqu'au 28 aout 2017, Laissez votre message en cas d'urgence extrême je vous joindrais.

Jean-Jacques Pointel
Directeur
Phone : +33 (0)1.79.97.24.00
