### ISSUE TITLE
opentx 9x128 green ed040502-h16d invalid eprom filesystem

### ISSUE THREAD

**Issue by s3melle** [opentx/opentx#5092]
Hi,

I have an invalid eeprom when flashing with opentx.
The remote is warning after a flash and it's formating the eeprom.

Same probleme with companinon 2.1 and 2.2, he can't read the eeprom data is invalid, can't open radio.bin

Thanks

**Comment by kilrah** [comment]
Please be clear on what you're actually trying to do - it seems you try to read the eeprom from the stock firmware before flashing OpenTX, and it's normal for that not to be readable.

**Comment by s3melle** [comment]
I'm telling that after every flashing with opentx the rom is formatting because it's invalid and if i create some profile i can't export it with companion because it's not readable.

**Comment by projectkk2glider** [comment]
I think you have problems with `usbasp` same as #5093

**Comment by s3melle** [comment]
For the #5092 - invalid eeprom, i'm not sure it's the same issue with the #5093 how only add an udev rules, i have the probleme under windows too.

**Comment by drepou** [comment]
same issue for me impossible to writte the eeprom only compagnion 2.0 is working
after that issue with eeprom version.

I dont understand the uploaded version of FW 2.2.0 use a 216-2 eeprom version ( fw is named with 216-2 ) at the end

I try to force the epprom erase with avrdude it 's ok i get FF every where in epprom.
Then reflash the FW with compagnion get the invalid eeprom message on the radio and "erasing" message then the old eeprom is back again !! and error eeprom upgrade when reading.

I try to create a empty profile and save into the radio same error after ...

**Comment by kilrah** [comment]
Likely mismatched companion and firmware options.

**Comment by s3melle** [comment]
Still have bad eeprom while updating and can't save (read/write) radio parameters.

semelle@dobian:~$ companion22 
[D] Translations::installTranslators():101 - Locale name: "fr_FR" language: "français" country: "France"
[D] Translations::tryLoadTranslator():158 - Installed translation file "qt" from "/usr/share/qt5/translations" for "fr_FR"
[D] Translations::tryLoadTranslator():158 - Installed translation file "qtbase" from "/usr/share/qt5/translations" for "fr_FR"
[D] Translations::tryLoadTranslator():158 - Installed translation file "companion" from ":/translations" for "fr_FR"
[D] registerStorageFactory():54 - register storage "bin"
[D] registerStorageFactory():54 - register storage "eepe"
[D] registerStorageFactory():54 - register storage "hex"
[D] registerStorageFactory():54 - register storage "otx"
[D] registerStorageFactory():54 - register storage "sdcard"
[D] SimulatorLoader::registerSimulators():55 - [simulator.interface.loader] Searching for simulators in "." matching pattern ("*-simulator.so")
[D] SimulatorLoader::registerSimulators():83 - [simulator.interface.loader] Found libraries: ("none")
[D] SimulatorLoader::registerSimulators():55 - [simulator.interface.loader] Searching for simulators in "/usr/local/lib/companion22" matching pattern ("*-simulator.so")
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-9x-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-9x" simulator in  "/usr/local/lib/companion22/libopentx-9x-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-9x128-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-9x128" simulator in  "/usr/local/lib/companion22/libopentx-9x128-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-9xr-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-9xr" simulator in  "/usr/local/lib/companion22/libopentx-9xr-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-9xr128-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-9xr128" simulator in  "/usr/local/lib/companion22/libopentx-9xr128-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-9xrpro-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-9xrpro" simulator in  "/usr/local/lib/companion22/libopentx-9xrpro-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-ar9x-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-ar9x" simulator in  "/usr/local/lib/companion22/libopentx-ar9x-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-gruvin9x-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-gruvin9x" simulator in  "/usr/local/lib/companion22/libopentx-gruvin9x-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-mega2560-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-mega2560" simulator in  "/usr/local/lib/companion22/libopentx-mega2560-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-sky9x-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-sky9x" simulator in  "/usr/local/lib/companion22/libopentx-sky9x-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-x10-simulator.so"
register theme Default
register theme Darkblue
register layout Layout2x2
register layout Layout1x1
register layout Layout2x1
register layout Layout2P1
register layout Layout2x4
register widget Text
register widget Timer
register widget ModelBmp
register widget Outputs
register widget Value
register widget Gauge
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-x10" simulator in  "/usr/local/lib/companion22/libopentx-x10-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-x12s-simulator.so"
register theme Default
register theme Darkblue
register layout Layout2x2
register layout Layout1x1
register layout Layout2x1
register layout Layout2P1
register layout Layout2x4
register widget Text
register widget Timer
register widget ModelBmp
register widget Outputs
register widget Value
register widget Gauge
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-x12s" simulator in  "/usr/local/lib/companion22/libopentx-x12s-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-x7-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-x7" simulator in  "/usr/local/lib/companion22/libopentx-x7-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-x9d+-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-x9d+" simulator in  "/usr/local/lib/companion22/libopentx-x9d+-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-x9d-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-x9d+" simulator in  "/usr/local/lib/companion22/libopentx-x9d-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():60 - [simulator.interface.loader] Trying to register simulator in  "libopentx-x9e-simulator.so"
[D] SimulatorLoader::registerSimulators():75 - [simulator.interface.loader] Registered "opentx-x9e" simulator in  "/usr/local/lib/companion22/libopentx-x9e-simulator.so" and unloaded: true
[D] SimulatorLoader::registerSimulators():83 - [simulator.interface.loader] Found libraries: ("opentx-9x", "opentx-9x128", "opentx-9xr", "opentx-9xr128", "opentx-9xrpro", "opentx-ar9x", "opentx-gruvin9x", "opentx-mega2560", "opentx-sky9x", "opentx-x10", "opentx-x12s", "opentx-x7", "opentx-x9d", "opentx-x9d+", "opentx-x9e")
[D] MainWindow::checkForUpdates():264 - Checking for Companion update  "https://downloads.open-tx.org/2.2/rc/companion/companion-linux.stamp"
[D] MainWindow::checkForUpdates():276 - Checking for firmware update  "https://downloads.open-tx.org/2.2/rc/firmware/stamp-opentx.txt"
[D] MainWindow::readEeprom():1065 - MainWindow::readEeprom(): using temp file:  "/tmp/18723-temp.hex"
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D+ import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9E import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X7 import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky X10 import... wrong size (9740/0)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Horus import... wrong size (9740/0)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9XR-PRO import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... wrong size (9740/2048)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... wrong size (9740/2048)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for ar9x board / 9X import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for Sky9x board / 9X import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for Gruvin9x board / 9X import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for MEGA2560 board import... wrong size (9740/4096)
[D] StorageFormat::setError():109 - [bin] error: Fichier EEPROM invalide /tmp/18723-temp.hex
[D] EepeFormat::load():38 - [eepe] No EEPE header
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D+ import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9E import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X7 import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky X10 import... no
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Horus import... no
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9XR-PRO import... no
[W] OpenTxEepromInterface::checkVariant():976 -  wrong variant ( 0 )
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... version 216 ko
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... version 216 variant 0 ok
[D] FlashFirmwareDialog::on_burnButton_clicked():227 - FlashFirmwareDialog: flashing "/home/semelle/Bureau/opentx-9x128-autosource-autoswitch-en.hex"
[D] writeFirmware():297 - writeFirmware: writing "/home/semelle/Bureau/opentx-9x128-autosource-autoswitch-en.hex" with "/usr/bin/avrdude" ("-c", "usbtiny", "-p", "m128", "-b", "19200", "-P", "usb", "-U", "flash:w:/home/semelle/Bureau/opentx-9x128-autosource-autoswitch-en.hex:i")
[D] MainWindow::readEeprom():1065 - MainWindow::readEeprom(): using temp file:  "/tmp/18723-temp.hex"
[D] MainWindow::readEeprom():1065 - MainWindow::readEeprom(): using temp file:  "/tmp/18723-temp.hex"
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D+ import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9E import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X7 import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky X10 import... wrong size (9740/0)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Horus import... wrong size (9740/0)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9XR-PRO import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... wrong size (9740/2048)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... wrong size (9740/2048)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for ar9x board / 9X import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for Sky9x board / 9X import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for Gruvin9x board / 9X import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for MEGA2560 board import... wrong size (9740/4096)
[D] StorageFormat::setError():109 - [bin] error: Fichier EEPROM invalide /tmp/18723-temp.hex
[D] EepeFormat::load():38 - [eepe] No EEPE header
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D+ import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9E import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X7 import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky X10 import... no
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Horus import... no
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9XR-PRO import... no
[W] OpenTxEepromInterface::checkVariant():976 -  wrong variant ( 0 )
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... version 216 ko
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... version 216 variant 0 ok
[D] MainWindow::checkForUpdates():276 - Checking for firmware update  "https://downloads.open-tx.org/2.2/rc/firmware/stamp-opentx.txt"
[D] MainWindow::startFirmwareDownload():541 - Downloading firmware "https://downloads.open-tx.org/2.2/rc/firmware/getfw.php?fw=opentx-9x128-autosource-autoswitch-en.hex"
[W] unknown():0 - QXcbConnection: XCB error: 3 (BadWindow), sequence: 11413, resource id: 4194995, major code: 40 (TranslateCoords), minor code: 0
[W] unknown():0 - QXcbConnection: XCB error: 3 (BadWindow), sequence: 11424, resource id: 4194982, major code: 40 (TranslateCoords), minor code: 0
[D] MainWindow::checkForUpdates():276 - Checking for firmware update  "https://downloads.open-tx.org/2.2/rc/firmware/stamp-opentx.txt"
[D] FlashFirmwareDialog::on_burnButton_clicked():227 - FlashFirmwareDialog: flashing "/home/semelle/Bureau/opentx-9x128-autosource-autoswitch-en.hex"
[D] writeFirmware():297 - writeFirmware: writing "/home/semelle/Bureau/opentx-9x128-autosource-autoswitch-en.hex" with "/usr/bin/avrdude" ("-c", "usbtiny", "-p", "m128", "-b", "19200", "-P", "usb", "-U", "flash:w:/home/semelle/Bureau/opentx-9x128-autosource-autoswitch-en.hex:i")
[W] unknown():0 - QXcbConnection: XCB error: 3 (BadWindow), sequence: 12957, resource id: 4195044, major code: 40 (TranslateCoords), minor code: 0
[D] MainWindow::readEeprom():1065 - MainWindow::readEeprom(): using temp file:  "/tmp/18723-temp.hex"
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D+ import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9E import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X7 import... wrong size (9740/32768)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky X10 import... wrong size (9740/0)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Horus import... wrong size (9740/0)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9XR-PRO import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... wrong size (9740/2048)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... wrong size (9740/2048)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for ar9x board / 9X import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for Sky9x board / 9X import... wrong size (9740/524288)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for Gruvin9x board / 9X import... wrong size (9740/4096)
[D] OpenTxEepromInterface::load():186 - trying OpenTX for MEGA2560 board import... wrong size (9740/4096)
[D] StorageFormat::setError():109 - [bin] error: Fichier EEPROM invalide /tmp/18723-temp.hex
[D] EepeFormat::load():38 - [eepe] No EEPE header
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D+ import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9D import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X9E import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Taranis X7 import... wrong file system
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky X10 import... no
[D] OpenTxEepromInterface::load():186 - trying OpenTX for FrSky Horus import... no
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9XR-PRO import... no
[W] OpenTxEepromInterface::checkVariant():976 -  wrong variant ( 0 )
[D] OpenTxEepromInterface::load():186 - trying OpenTX for M128 / 9X board import... version 216 ko
[W] unknown():0 - QXcbConnection: XCB error: 3 (BadWindow), sequence: 14909, resource id: 4195086, major code: 40 (TranslateCoords), minor code: 0
[D] OpenTxEepromInterface::load():186 - trying OpenTX for 9X board import... version 216 variant 0 ok
[W] unknown():0 - QXcbConnection: XCB error: 3 (BadWindow), sequence: 15025, resource id: 4195095, major code: 40 (TranslateCoords), minor code: 0
[D] main():165 - COMPANION EXIT 0
