### ISSUE TITLE
no device /dev/ttyACM0

### ISSUE THREAD

**Issue by s3melle** [opentx/opentx#5093]
Hi

I put my arduino in isp mode and the device /dev/ttyACM0 is not seen under Linux.
Anywhere I can put it in the .config file and it work fine but can you add it to the GUI.

Thanks

**Comment by projectkk2glider** [comment]
Bummer. Looks like we forgot to install `45-usbasp.rules` file (in cmake)!

@s3melle try adding a file `/etc/udev/rules.d/45-usbasp.rules`  (as sudo) with this contents ``, then re/plug your radio:
```
SUBSYSTEM=="usb", ENV{DEVTYPE}=="usb_device", ATTR{idVendor}=="16c0", ATTR{idProduct}=="05dc", MODE="0666"
```

**Comment by s3melle** [comment]
For the #5092 - invalid eeprom, i'm not sure it's the same issue with the #5093 how only add an udev rules, i have the probleme under windows too.
