### ISSUE TITLE
PXX low CRC byte is always zero

### ISSUE THREAD

**Issue by krzysztofkuczek** [opentx/opentx#5096]
Hi,
I just wonder if you have everything ok with CRC calculation. I wrote my PXX decoder, and channels values are ok, but when i look into pxx frame, i can see that low byte of CRC sum is always ZERO.
Sample frames:
126,11,64,0,253,51,63,0,161,63,153,4,112,100,34,17,0,170,126,
126,11,64,0,253,35,63,0,161,63,153,4,112,100,34,17,0,59,126,

On the face of it, the signal also repentants zero at this position
![image](https://user-images.githubusercontent.com/1246883/28260157-076f1956-6ada-11e7-8bf1-fca4f75d1d6d.png)

According to limited documentation, and source code, there should be LO and HIGH byte of CRC sum..
Or maybe i do something wrong.
Krzysiek

**Comment by projectkk2glider** [comment]
Before looking into this, I think we would not get anything over to the RX side if the data sent is wrong or something that XJT module does not expect.
