### ISSUE TITLE
[Horus] Reading internal GPS via LUA Script

### ISSUE THREAD

**Issue by labeh** [opentx/opentx#5112]
I like to read the internal GPS from the Horus via LUA Script to implement a Widget which can show me the distance between model (is also equipped with a GPS) and pilot. 

For this widget I need access to the internal GPS from the Horus via LUA. Currently I did much research including reading much opentx code but did not find any suggestion how the internal gps is available. Could anybody help me please?

**Comment by schwabe** [comment]
Currently the internal GPS is not supported very well. You cannot it from lua or other telemetry. Search for ```INTERNAL_GPS``` and ```gpsData``` to see what is implemented so far. 

Making this available via lua should be easy but the question is rather if the internal GPS should available as normal telemetry source.

**Comment by labeh** [comment]
I have done that already. But I sadly don't know enough about the rest of the code to do a quick fix and provide it by a pull request. It is not obvious for me how the data comes to the Lua Scripts. Maybe there should be a `LUA_EXPORT(...)` expression added in https://github.com/opentx/opentx/blob/cd23fedb56e85945455474d4e52d709740c0a114/radio/src/dataconstants.h ? But this can't be enough?

**Comment by schwabe** [comment]
probably not.

As a quick hack, this might work, after the internal GPS position should available as telemetry value:

```diff
diff --git a/radio/src/gps.cpp b/radio/src/gps.cpp
index 5a62fb5ac..9b10694a5 100644
--- a/radio/src/gps.cpp
+++ b/radio/src/gps.cpp
@@ -265,6 +265,8 @@ bool gpsNewFrameNMEA(char c)
                 gpsData.altitude = gps_Msg.altitude;
                 __enable_irq();
               }
+              setTelemetryValue(TELEM_PROTO_FRSKY_SPORT, GPS_ID, 1, 0, gpsData.latitude, UNIT_GPS_LATITUDE, 0);
+              setTelemetryValue(TELEM_PROTO_FRSKY_SPORT, GPS_ID, 1, 0, gpsData.longitude, UNIT_GPS_LONGITUDE, 0);
               break;
             case FRAME_RMC:
               gpsData.speed = gps_Msg.speed;
```

**Comment by 3djc** [comment]
Yeah, GPS and lua need some love, I had a few things ready (like disatnce computation for lua), need to do some code archeology :D

**Comment by projectkk2glider** [comment]
Should be easy:
 * export `MIXSRC_TX_GPS` to lua with `LUA_EXPORT()` macro
 * write custom handler in `luaGetValueAndPush()` for that source.

**Comment by 1Sven** [comment]
Perfect idea, the position and acceleration sensors are also essential. Then you can finally create a follow me mode.

**Comment by WimSanders** [comment]
I would be already very happy if I can display the internal GPS.
So if the can make  as an selectable sensor in the telemetry menu it would be great.
If it’s only to find back a lost model

**Comment by 3djc** [comment]
All that is available

Was done in #5610

**Comment by WimSanders** [comment]
Dear Open TX,


Thank you for replay.

I both my Horus 12s a half year ago, I’m very happy with it, but I still have to learn a lot.

I see that I have to do this by a Lua script, never used lua scripts before, but internet has all the answers. I gone try to find out how to do.

During this winter I have setup a sensor system based on Pawelsky libraries in RC-Groeps.

Now I have the GPS working. And want use the internal GPS as well.


With kind regards,

Wim Sanders



________________________________
Van: 3djc <notifications@github.com>
Verzonden: woensdag 7 maart 2018 15:44
Aan: opentx/opentx
CC: WimSanders; Comment
Onderwerp: Re: [opentx/opentx] [Horus] Reading internal GPS via LUA Script (#5112)


All that is available

Was done in #5610<https://github.com/opentx/opentx/pull/5610>

**Comment by 3djc** [comment]
You do not. You have been able to display internal sensor on widgets since 2.2.0 without any lua knowledge.

Create a sensor display widget and select the internal GPS, it is available as a source

**Comment by WimSanders** [comment]
Thank you for replay.


I did but is say only Sats:0.

I waited for 30 minutes outside.

With kind regards.

Wim Sanders



________________________________
Van: 3djc <notifications@github.com>
Verzonden: woensdag 7 maart 2018 16:26
Aan: opentx/opentx
CC: WimSanders; Comment
Onderwerp: Re: [opentx/opentx] [Horus] Reading internal GPS via LUA Script (#5112)


You do not. You have been able to display internal sensor on widgets since 2.2.0 without any lua knowledge.

Create a sensor display widget and select the internal GPS, it is available as a source

**Comment by 3djc** [comment]
Either the radio could not get a fix (very cloudy, obstacles,...) or your internal gps is defective, because it does work

**Comment by WimSanders** [comment]
Sorry did not wait not long enough, now I have a fix

THNX


________________________________
Van: 3djc <notifications@github.com>
Verzonden: woensdag 7 maart 2018 17:29
Aan: opentx/opentx
CC: WimSanders; Comment
Onderwerp: Re: [opentx/opentx] [Horus] Reading internal GPS via LUA Script (#5112)


Either the radio could not get a fix (very cloudy, obstacles,...) or your internal gps is defective, because it does work
