### ISSUE TITLE
QX-7 Vibration Alerts Constantly

### ISSUE THREAD

**Issue by lookitsnam** [opentx/opentx#5113]
Hello, first time posting in here.

I just bought a QX-7, and when I turn it on I keep getting vibration alerts with no alert on the menu. I constantly get the alerts randomly. I thought it was an issue with just my crossfire unit, but I found that I get it when flying using the internal module as well.

I'm running firmware 2.20. I have a video up on facebook, not sure if the link will work here. 

Thanks in advance for any help! It is greatly appreciated!

**Comment by 3djc** [comment]
Sorry, I'm closing this because this is a bug tracker for Opentx, and this is obviously not an OpenTx bug ,since it only affect your transmiter. Please seek help on forums like openrcforums or rcgroup
