### ISSUE TITLE
HORUS - Variometer height display is Metres only?

### ISSUE THREAD

**Issue by Bravedan** [opentx/opentx#5114]
Setting the Horus to England, English Language, and Imperial measurements (or all to USA), the widget box in telemetry shows the height in metres.

Widget settings does not allow measurement system to be set.

Don't appear to be able to change it??  Bug or me please??

**Comment by Bravedan** [comment]
Further to above, I have had someone check their system and they get the same result, no apparent way to obtain height telemetry display in FEET on a Horus under OpenTX. (but can do under FrOS)

**Comment by schwabe** [comment]
@Bravedan  You just got your answer in chat from @kilrah: just change the unit in the sensor settings on the telemetry page.
