### ISSUE TITLE
invalid epprom version for tgy 9X version FW 2.2.0

### ISSUE THREAD

**Issue by drepou** [opentx/opentx#5117]
I upgraded my radio to 2.2.0 FW i use compagnion 2.2.0

I cant download model from compagnion to radio i get the famous error invalid eeprom format ( old ) even from scracht ( after formating eeprom, reading empty from radio and import again into radio )

i think there is an issue with the FW because the epprom version is 216-2 on radio after 2.2.0 flash
so i i m right i cant work with compagnion 2.2 who deal with 217 version.

How can i "flash" the eeprom to 217 ???? thanks

**Comment by 3djc** [comment]
Duplicate #5092
