### ISSUE TITLE
opentx 2.2.0 repurposing trim with extended limit

### ISSUE THREAD

**Issue by FlipAirboost** [opentx/opentx#5119]
Hi All,
Instead of increasing the adjustment range, the extended trim moves the neutral.
Example here with snapflaps.
First, we have more snapflaps as expected and then for the extended trim it becomes an offset.
[repurposing trim extended limit.zip](https://github.com/opentx/opentx/files/1182442/repurposing.trim.extended.limit.zip)

**Comment by kilrah** [comment]
Please explain what radio type this is for, and what to do exactly with the switches, pots and stick to observe the problem. Not going to spend hours doing random things to try and understand what you're talking about.

**Comment by FlipAirboost** [comment]
Ok , I'm trying
Companion 2.2, opentx 2.2.0, taranis x9d  Mike Shellim philosophy in mind.
![extended trim](https://user-images.githubusercontent.com/29504813/28709311-1333f280-7380-11e7-9e93-24c59f1d454e.JPG)

First check trim extended
![trim etendu](https://user-images.githubusercontent.com/29504813/28709163-60e93630-737f-11e7-8691-e6a676042c5f.JPG)
I use gas trim to adjust in flight snapflaps volume .
![trim gauche volume snapflaps](https://user-images.githubusercontent.com/29504813/28710341-db906e22-7383-11e7-984e-8acad43e6a5c.JPG)
![throtle trim snap volume](https://user-images.githubusercontent.com/29504813/28710348-e39bcbf2-7383-11e7-9f30-cf0eaa5635c4.JPG)
Volume trim minimum with full down elevator = zero snapflaps as expected.
![trim mini snap 0](https://user-images.githubusercontent.com/29504813/28710459-446b4570-7384-11e7-9e8c-346647b3dfe2.JPG)
Volume trim maximum with full down elevator = full snapflaps as expected
![trim full up snapmax](https://user-images.githubusercontent.com/29504813/28710521-8c65df2a-7384-11e7-88d3-31ed70cbd43f.JPG)
Volume trim maximum with centered elevator control = zero snapflaps as expected
![trim full up o ele](https://user-images.githubusercontent.com/29504813/28710608-f3843904-7384-11e7-9ab9-a410383560fd.JPG)
Volume trim maximum + extended = more snapflaps as expected with full down elevator but also flaps with centered elevator control.
![full up extended trim o ele](https://user-images.githubusercontent.com/29504813/28710750-8da5d70e-7385-11e7-93b5-61e0d25c00c0.JPG)

**Comment by projectkk2glider** [comment]
Use multiply for the second line of the CH11 mixer.
