### ISSUE TITLE
Companion Firmware Build Options Lua clarification

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#5120]
My intent is to provide clarity regarding the Lua build option in Companion. Please suggest options.

**Current mouse over text "Support for Lua model scripts"**
**Suggest changing it to "CUSTOM SCRIPTS & MIXES scripts support" or  "Additional Lua features"** This mirrors the no heli mouse over.

This would clarify what that option does. We then update the 2.2 User manual to explain the option.

If from the point of view as a user if the only apparent change is the addition of the CUSTOM SCRIPTS screen then similar to "no heli" where the HELI SETUP screen is removed maybe change "Lua" to "Custom scripts" where the CUSTOM SCRIPTS screen is shown

**Current check box text "Lua"**
**Suggest changing it to "Custom scripts"** This mirrors the no heli check box wording.

Suggestion based on
https://www.rcgroups.com/forums/showpost.php?p=37914641&postcount=1102
The lua option is ONLY for mixer scripts. The lua engine is ALWAYS included and will run all other script types regardless of the option.

**There are no "model scripts"**
There are:
- Mix Scripts
- Telemetry Scripts
- One-Time Scripts
- Wizard Scripts
- Widget Scripts
- Theme Scripts

(Taken from https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/ Part 1 Script Type Overview)

**Comment by schwabe** [comment]
That is only true on the horus, on other platform it really lua

**Comment by RCdiy** [comment]
The post was in a discussion involving the X7.

**Comment by RCdiy** [comment]
From the Lua manual 

If you intend to use mixer scripts, when updating the firmware on your transmitter you need to make sure the lua option is checked in the settings for your radio profile (Main menu -> Settings ->Settings...) as shown below. This is not required if you only intend to run telemetry, one-time and function scripts, support for those is included by default.

**Comment by RCdiy** [comment]
https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/getting_started.html

**Comment by 3djc** [comment]
And actually choosing that option gives access to "custom scripts" screen, and most people use it for many thing BUT mixer script, per say, so I'm not in favor of that change

**Comment by RCdiy** [comment]
What change do we do then?
There is no "model scripts"
There are:
- Mix Scripts
- Telemetry Scripts
- One-Time Scripts
- Wizard Scripts
- Widget Scripts
- Theme Scripts

(Taken from https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/ 
Part 1 Script Type Overview)

No model scripts.

**Comment by RCdiy** [comment]
Apologies for all the repeated edits of the first post and title. Just trying to take feedback into account.
