### ISSUE TITLE
Firmware simulator 2.2 bugs

### ISSUE THREAD

**Issue by dadantsou** [opentx/opentx#5131]
Firmware simulator 2.2.0 bugs, so when I open Companion 2.2, edit my model then Simulate the model, **_servo outputs are not correct_**. It is a random bugs so **sometimes everything is ok, but if I restart Simulator the bug reappear**.

**Comment by 3djc** [comment]
Radio ? Os ? What should the output be ? What do you see as a result ? With the info you give, there is absolutely 0 chance that we can reproduce, and even less fix, the issue (if there is really one)

**Comment by dadantsou** [comment]
9XR PRO with opentx 2.2. Look for eg at these attached files, all my stick except throttle are centered but there are differents servo outputs when i start firmware simulator. i've made no changes to my model settings, just restart the simulator and watch the results. I doesn't understant why.
![capture](https://user-images.githubusercontent.com/30746201/28994340-3e2db8c2-79d4-11e7-9720-3583f7a24533.JPG)
![capture2](https://user-images.githubusercontent.com/30746201/28994350-8ec4b84e-79d4-11e7-8318-f0712c8e6092.JPG)

**Comment by dadantsou** [comment]
**FOUND THE ISSUE!**

My old Companion was not properly uninstalled so it creates conficts between OpenTX 2.2 and the older version. After correcting that, everything seems to be OK!
