### ISSUE TITLE
LUA playNumber plays only first decimal with PREC2

### ISSUE THREAD

**Issue by mkrle** [opentx/opentx#5132]
LUA reference guide for [playNumber](https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/general/playNumber.html) states:

> PREC2 plays a number with two decimal places (for a number 123 it plays 1.23)

However, it actually plays 1.2 and not 1.23 in OpenTX 2.2.0

Test script:

```lua
local function run()
  playNumber(123,0,PREC2)
  return -1
end
return { run = run }
```

**Comment by kilrah** [comment]
All values play with 1 decimal, it is not related to PREC. PREC "only" gets it to play the right value and not 10x more. Doc must be incorrect.
