### ISSUE TITLE
LS/RS Mixer/Source issue

### ISSUE THREAD

**Issue by PeterVRC** [opentx/opentx#5134]
Since changing to OpenTX2.2 I had never seen that in the Radio Settings you need to set the LS/RS to a value of "Slider". Mine were blank.
I had pre-existing models that use LS/RS as a Source in the Mixer lines. These continued to work fine after upgrading OTX2.1 to 2.2.
Today I loaded the models into OpenTX Companion to edit some things, and one thing was to CHANGE some values in a mixer line - this had LS as the Source.
I found that if I EDIT that entry, when I exit out of it the main Companion Mixer window loses all mixers from that edited one onwards! eg 8 mixer lines gone.
So there is some bug in there - which does not like you editing a mixer that has LS or RS if they were not actually enabled as Sliders int he Radio Settings.

Once I changed the Taranis to have the Sliders enabled, and reloaded the models into Companion, then it all edits as you would expect.

**Comment by RipperDrone** [comment]
Similar problem here: When I load existing channel mapping including sliders, they show as an empty box in OpenTX 2.2. When I open the drop-down list, no sliders like LS, RS, ... are available for selection anymore.

Looks like the sliders are missing in the enum list to pick from. I hope that I have not messed up all my slider settings by saving from latest OpenTX back to the radio :-/

**Comment by kilrah** [comment]
Needing to have the sliders defined correctly is necessary and intended, the issue seems to be that old settings are not imported correctly. As said above if you set them correctly you'll be fine.

**Comment by RipperDrone** [comment]
How can I set them if the drop-down menu does not list any sliders at all? Confused... :-(

**Comment by RipperDrone** [comment]
this is what the inputs page tab shows: RS (= Right Slider) is still there from an existing model defined in a previous OTX version...
![image](https://user-images.githubusercontent.com/12601105/31120518-fa10ff84-a834-11e7-8de0-d8232867ea70.png)

**Comment by RipperDrone** [comment]
Once I edit, it looks like this (empty source! No slider ID shown anymore): 
![image](https://user-images.githubusercontent.com/12601105/31120553-29a1d340-a835-11e7-96c2-748e33b9b9c4.png)

**Comment by RipperDrone** [comment]
...and in the drop-down select box, there is no more RS, LS, ... (sliders) available anymore :-( Just sticks, trims & switches...
![image](https://user-images.githubusercontent.com/12601105/31120607-522a0508-a835-11e7-83c1-9a9461df11df.png)

**Comment by RipperDrone** [comment]
Tried the same by setting up a NEW model - same behaviour, no sliders shown for selection...

**Comment by 3djc** [comment]
There are missing in your RADIO settings

**Comment by RipperDrone** [comment]
Ok - how can I fix this then?

**Comment by 3djc** [comment]
By going to your radio settings and ensure they are properly defined ?

**Comment by RipperDrone** [comment]
You mean changing these settings to "slider with ratchet?"
![image](https://user-images.githubusercontent.com/12601105/31120851-4298e00e-a836-11e7-9372-62605a858217.png)

**Comment by RipperDrone** [comment]
I have not changed the radio profile whatsoever, seems it has been reset in OTX 2.2 latest version by default?

**Comment by 3djc** [comment]
Kilrah answered a while back. On a limited set of configs (we don't know precisely which ones), those disapear during to move to 2.2.0. Just add them back and its done

**Comment by RipperDrone** [comment]
ok, great. It worked - thanks a lot!

**Comment by pghern** [comment]
I'm able to change the radio setting for the Sliders and then Store settings and save. but the next time I start Companion, the previous LS/RS setting are lost. I have to reset each time I open Companion.

Has this been fixed with the new 2.2.1 release??- I haven't updated yet, still on 2.2.0
Thanks,

**Comment by kilrah** [comment]
> the next time I start Companion

What does that mean? With a new blank file? After reloading form the radio or a file?

**Comment by pghern** [comment]
After reloading Models and Settings from Radio

**Comment by kilrah** [comment]
...and with what radio type?
Anyway update first.

**Comment by pghern** [comment]
Taranis X9D+

Will update to see if that helps.
Thanks

**Comment by mpaperno** [comment]
Was there ever a final determination on this?  Is there an import/conversion problem?

**Comment by raphaelcoeffic** [comment]
@PeterVRC @RipperDrone could you please confirm or infirm this is still happening for you with the 2.3 nightlies (in case you have a supported radio)?

**Comment by PeterVRC** [comment]
I am using OTX 2.2.3, but on a Horus X10S now, and I tried the above and it was all ok.
I will change to 2.2.4 soon. (I have not tried pre-release versions before.)
I can get out my Taranis and upgrade that and see what that does. In a day or two.

**Comment by raphaelcoeffic** [comment]
@PeterVRC thx, trying out again with the new version (2.2.4) on your Taranis would be nice.

**Comment by raphaelcoeffic** [comment]
> Was there ever a final determination on this? Is there an import/conversion problem?

Yes. We have unit tests for that now in 2.3 (incl. companion).
