### ISSUE TITLE
outputs reset does not stick on reboot

### ISSUE THREAD

**Issue by leeharr** [opentx/opentx#5137]
I am using OpenTx 2.1.9 (also had same issue on 2.1.8 but updated to see if it had been fixed)

On transmitter, page OUTPUTS

Have a channel with some applied subtrim/ min/ max

Highlight channel, choose long-press -> RESET

As expected, all subtrim/ min/ max are reset to 0

Shut down/ restart transmitter

All subtrim/ min/ max values on OUTPUT channel have been restored to previous values.

Seems like a bug to me, though I may be misunderstanding what this feature is supposed to do. Thanks for looking in to it!

**Comment by bsongis** [comment]
And on 2.2.0?

**Comment by 3djc** [comment]
Info on radio type would help too

**Comment by kilrah** [comment]
Closing for lack of details and nothing missing in 2.2 code.
