### ISSUE TITLE
OpenTX Companion inputs offsets not present!

### ISSUE THREAD

**Issue by dadantsou** [opentx/opentx#5138]
While editing model on radio, there is offset option onto the inputs parameters, but when I try to edit model with Companion there in no offset option  onto the inputs parameters.

Mixer offset is always avalaible on the radio and on Companion, but inputs offset is only present on the radio, but not on Companion. 

However, the values ​​of these offsets are calculated by Companion but not editable with!

-------------------------------------------------------------------------------------------------------------------
9XR PRO - OpenTX 2.2 - Companion 2.2 - Windows 7

**Comment by kilrah** [comment]
#5098
