### ISSUE TITLE
Cannot download new firmware for FrSky-X9D

### ISSUE THREAD

**Issue by Fojtik** [opentx/opentx#5139]
When I attempt to download a new firmware I obtain totally confusing message:
![cannotdownloadfirmware](https://user-images.githubusercontent.com/2893993/29061678-20a6236e-7c1f-11e7-8de3-43ac7edf3bb1.png)

**Comment by 3djc** [comment]
Set your language in radio settings

**Comment by Fojtik** [comment]
There is no option to set a language. I have everything in English.
http://open-txu.org/home/undergraduate-courses/radio-setup/beginning-radio-setup/

There is only option "Voice language" and the firmware does not allow me to change it.

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/29063022-684006f4-7c24-11e7-8f1a-a77d9febec04.png)

BTW, you say you have an X9D, but your radio settings are for X9D+, they are not the same

**Comment by kilrah** [comment]
Set the correct radio type and it will be good again.

**Comment by Fojtik** [comment]
Thank you very much for this support. Anyway, before taking snapshot I already have English as actual language set.

After setting "Voice language" to English in transmitter, it suddenly downloaded firmware correctly. 

But I suspect that there is something very unclean. The message box should at least write me which language it is guessing and which language should be set for proper functionality. Non english speakers might be confused by this anyway.
