### ISSUE TITLE
SD card problem

### ISSUE THREAD

**Issue by philpow** [opentx/opentx#5140]
Hi earlier this year I bought a Taranis Plus to replace my old pre-Plus version for various reasons I was unable to access the TX till recently and when I turned it on I found it was mute other than that it worked fine bound with receivers etc no problem, it also didn't have the much vaunted wizard or any graphics.
I removed the SD card and found that it had nothing on it in fact it was useless for purpose.
I have had no help from the retailer T9 at all.
I had of course a spare sd card and copied the files from my old Taranis to it and I now have sound and graphics but no wizard I have tried to create a file on it for the wizard but the tx still doesn't show it when creating a new model.
I would like of course a copy of the original SD contents but this has eluded me and T9 refuse to help, any assistance would be appreciated.

**Comment by 3djc** [comment]
Sorry, but this is a bug tracking system, not a support forum. Please go to rcgroup or openrcforums for support forums
