### ISSUE TITLE
sqt5font

### ISSUE THREAD

**Issue by mixMugz** [opentx/opentx#5142]
No font in 2.2.0 release. Flashed FW with font, but used default

**Comment by 3djc** [comment]
Maybe radio model would help diagnose ...

**Comment by RCdiy** [comment]
Using Tananis Q X7
opentx-x7-ppmus-lua-sqt5font-en-2.2.0
Images from Tx before sqt5 and after

![screen-2017-08-13-151206](https://user-images.githubusercontent.com/20209851/29252840-8d566638-803c-11e7-86a5-e78595071172.png)
![screen-2017-08-13-151904](https://user-images.githubusercontent.com/20209851/29252841-8d6557f6-803c-11e7-87e4-c105b88fef6c.png)

**Comment by RCdiy** [comment]
@3djc need anything else?
