### ISSUE TITLE
Bootloader 2.2.0 bricked X9Dplus

### ISSUE THREAD

**Issue by pascalnl** [opentx/opentx#5143]
After installing the firmware 2.2.0. I updated the bootloader from the tx. The bootloader screen stays black. Tried to reflash original bootloader from Frsky, same result. I tried to flash it over with dfu-util from the first bootloader, same result.

After the initial flash to 2.2.0 it corrupted my sd-card. I formatted it on linux to fat32, copied 2.2.0 sd-card contents, lua scripts, sounds and firmware files to the sd. Everything works fine.

When flashing the bootloader sometimes it gives me a sd-card error and fails to flash. The next time it flashes.

But the bootloader is bricked, so effectively the X9Dplus. I'm out of options, I couldn't find much more on google.

**Comment by kilrah** [comment]
Reflash the correct firmware using DFU, and probably change your SD card since it seems defective. 

Please note this is a bug tracker and not a support page. Use forums for community support.
