### ISSUE TITLE
Cels reads seconds from timer

### ISSUE THREAD

**Issue by Hotwire-** [opentx/opentx#5145]
Battery alert gets the timer for some reason and not battery voltage. 
See image:
![cels-sec](https://user-images.githubusercontent.com/8826288/29149943-b5e732c8-7dba-11e7-8543-08113abe1cc9.png)

**Comment by ghost** [comment]
You Probbably have the wrong version of the SD Card.

**Comment by kilrah** [comment]
Radio type? Other relevant details?

**Comment by Hotwire-** [comment]
The gear is : Taranis X9D and X8R receiver and FrSky battery voltage telemetry module, OpenTx v2.2.0.

So the battery value (Cels) reports the timer, which is weird. This worked fine in OpenTx V2.0 and 2.1.

After deleting sensors and searching again the FrSky battery telemetry module, doesn't detect.  This was not due to any other changes, just the version of the firmware.

**Comment by kilrah** [comment]
Cannot reproduce, your sensor probably has the wrong unit selected. Might want to post your file. 
You need a battery connected to the sensor for it to be discovered.

**Comment by Hotwire-** [comment]
Apologies, the telemetry sensor had a broken track. No fault of V2.2
