### ISSUE TITLE
AFHDS2A failsafe for multi-module

### ISSUE THREAD

**Issue by akosfonod** [opentx/opentx#5149]
Te multi module option is working fine on 2.2.0, but when I select the AFHDS2A protocol ther is no option for seting up the failsafe values.
On the other AFHDS2A nativel supporting radios it is an option to set the values eg: Turnigy evolution.
I have checked the multi module code and it is prepared to send out the failsafe settings.

**Comment by schwabe** [comment]
There is a issue for that on the multi gitbub https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/94 let's keep the discussion in one place
