### ISSUE TITLE
Can't bind Taranis with XSR

### ISSUE THREAD

**Issue by DaxoM** [opentx/opentx#5150]
Internal XJT flashed with XJT_LBT_build151223.frk
XSR flashed with XSR_LBT-build151118.frk

When I power the xsr in bind mode all i get is solid red and green leds, no bind.

I've opened up taranis to check ribbon cables, all good, tried different bec rx power and all sorts of xjt/xsr fw combos with the same results.

Please help, Appreciated.

**Comment by 3djc** [comment]
We are sorry but this is not a support area, but a bug tracking system. Please go to support forums for assistance
