### ISSUE TITLE
Companion 2.2.0 Build Options Simulator ppmus

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#5154]
The Outputs screen always showx -100 to 100 regardless of ppmus being selected... would be nice if in the simulator it changes with selection of ppmus...

Tested in X7 and X9D+ profiles.
![screenshot_x7_17-08-13_14-26-01](https://user-images.githubusercontent.com/20209851/29252427-16945886-8035-11e7-9707-65daff7f2ca9.png)
![screenshot_x9d _17-08-13_14-29-28](https://user-images.githubusercontent.com/20209851/29252431-245db886-8035-11e7-9597-05095f6d8a03.png)

**Comment by RCdiy** [comment]
This image taken from taken from Tx


![screen-2017-08-13-142152](https://user-images.githubusercontent.com/20209851/29252445-73191d12-8035-11e7-95c0-a9bfe0068f15.png)

**Comment by 3djc** [comment]
The simulator is currently precompiled with mainstream options. We have discussed already a build on demand simulator, but we aren't ready for that

**Comment by RCdiy** [comment]
Ah... I see...

Can't put an if statement in the simulator? Show depending on ppus selected? It seems to work for the noheli screen build option....

Just trying to understand...

**Comment by kilrah** [comment]
The simulator is compiled once and for good with default options during the release process. It has no idea of what's selected in companion.

**Comment by RCdiy** [comment]
oops deleted

**Comment by 3djc** [comment]
We want and maybe will do something like that at some point in time, to handle very critical things, like language for exemple. Once/if this is done, all options will be handled, but the complexity of this cannot be underestimated

**Comment by sande005** [comment]
Another vote for this enhancement to have simulator follow profile build options, if ever possible some day....
