### ISSUE TITLE
OpenTX 2.1.9

### ISSUE THREAD

**Issue by sly1231** [opentx/opentx#5169]
I have several models that have voice files in Special Functions that could be simulated. I recently opened a eepe file from a friend and now I am unable to simulate the sound files in 'Special Functions'
How can I resolve this issue?
Thanks.

**Comment by bsongis** [comment]
Why not switch to OpenTX 2.2.0?

**Comment by kilrah** [comment]
Make sure your SD card copy with the voice files is where you told companion it is, and has those voice files.

**Comment by sly1231** [comment]
Thanks, I thought of that late last night - almost asleep and fixed it.

**Comment by sly1231** [comment]
Problem solved.  Will switch later.
