### ISSUE TITLE
flysky TH9x wont flash (m128 with tinyasp)

### ISSUE THREAD

**Issue by ITSIK1231995** [opentx/opentx#5175]
im using companion 2.1.9
the transmiter is a flysky th9x with a m128 bored
and im flashing it using a tinyasp
and i get this:

C:/Program Files (x86)/OpenTX/Companion 2.1/avrdude.exe -c usbtiny -p m128 -P usb -U eeprom:r:/backup-2017-08-21-222857.bin:r
=================================================================================

avrdude.exe: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.01s

avrdude.exe: Device signature = 0x1e9702
avrdude.exe: reading eeprom memory:

Reading | ################################################## | 100% 6.78s

avrdude.exe: writing output file "/backup-2017-08-21-222857.bin"

avrdude.exe done.  Thank you.

=================================================================================

after 2 seconds of work
the trasmiters screen goes off and when its done back on again, but i still have the origenal softwere ... as if i did nothing

tryed swaping drivers with zadig but it changed nothing

i used this guid : 
https://www.youtube.com/watch?v=7sdB1wb6NIM

did anyone solve this problom?

**Comment by kilrah** [comment]
This is a bug tracker for OpenTX, not a support system. Please use forums such as Openrcforums.com or rcgroups.com, both have OpenTX sections.
