### ISSUE TITLE
Switch warning state incorrect Q X7

### ISSUE THREAD

**Issue by kreidler** [opentx/opentx#5181]
On companion 2.2.0 final simulation of the s-warning works fine. In the transmitter the letters are not fully accessible when switches are deactivated or dismounted.
See vid: [https://www.youtube.com/watch?v=9Mx_PZisAbI](url)
Probably remaining issue from #4401

**Comment by hrenz** [comment]
Yes,  its only at X7D, 

X9D+ works fine with deaktivated or dismounted switches
