### ISSUE TITLE
[MULTI] Number of Receivers

### ISSUE THREAD

**Issue by Bravedan** [opentx/opentx#5195]
Quickly, can I just say how much I appreciate the Serial Multi-Module inclusion into OpenTX.  Great Work!

Query/Issue - In Serial Mode, I appear to be able to only have receiver numbers up to 15 (I assume 16 with "0"). Is this so or am I doing something wrong?   (Horus Tx)

**Comment by kilrah** [comment]
Only supporting 16 different receiver numbers is a limitation/choice done by the multimodule team.
