### ISSUE TITLE
Fewer sensors using Copter 3.5.2 than 3.4.6

### ISSUE THREAD

**Issue by pmshopUSMC** [opentx/opentx#5196]
After upgrading to Copter 3.5.1, fewer sensors show up on Taranis X9D + with Open TX 2.2 loaded.
Example: Copter 3.4.6 produced RSSI, RxBt, VSpd, GPS, Alt, and VFAS.
Copter 3.5.1 produces RSSI, RxBt and GPS only.
Same for 3.5.2

**Comment by 3djc** [comment]
Did you change opentx version as well? Because it sounds like a Copter issue, not opentx

**Comment by schwabe** [comment]
I have no idea what Copter is but the problem seem to be Copter related since its version change sees to have triggered the problem.

**Comment by pmshopUSMC** [comment]
@schwabe - Ardupilot Copter firmware 3.5.2 and yes, 3.5.x does seem to have triggered it. That is why i am reporting it for development.

@3djc opentx version 2.2 is loaded

**Comment by schwabe** [comment]
@pmshopUSMC You realise that is the OpenTX issue tracker and not the Ardupilot bug tracker?

**Comment by pmshopUSMC** [comment]
Yes, I do realize this.
If Ardupilot made a change, doesn't Open TX need to follow suit to keep the previous operations, correct?
I mean Craft and Theory does the same with their Flight Deck .lua

**Comment by 3djc** [comment]
No, it is their task to send the sensors in the right format

**Comment by kilrah** [comment]
Most likely you now simply need to manually enable what you want to send in your arducopter configuration...

**Comment by pmshopUSMC** [comment]
So it appears that the mavlink protocol was tweaked a bit and appears open tx hasn't caught up yet...so my guess Ardupilot wont comment...it will be up to Open TX to adjust

**Comment by schwabe** [comment]
@pmshopUSMC we don't even support mavlink telemetry, so telemetry is probably in sport format.

**Comment by pmshopUSMC** [comment]
Then what delivers the sensor data in OpenTX2.2?

**Comment by schwabe** [comment]
if you use frsky receivers as I said sport (smart.port). But this is not a support forum.

**Comment by pmshopUSMC** [comment]
Right...not a support forum...I am reporting to the OpenTX team that the telemetry now sent by copter 3.5.x does not trigger the "Discover Sensors" as it used to. Used to pick up 6 sensors and now only picks up 3 

Using FrSky X8R Sport

**Comment by schwabe** [comment]
And I am telling you that smart port format is unchanged and if OpenTX does not discover the sensors anymore something is wrong what Copter is sending as sport.
