### ISSUE TITLE
Horus V2.20 Trim-Steps allways fix at 4us   at X9D,  X9E  I can set it and works 1, 2, 4, 8us

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5201]
Hy,
after testing setting trim steps at Horus  I was surpriced
Trimsteps are allways only 4us  independend of setting at modell

At X9D, X9E  I can set trim steps ultrafine, fine, mid, .... and so on  
and I get Steps wth 1us, 2us, 4us, 8us  and expo thats ok since years

I have tested with an Impuls wide measering counter

Picture: +WIDE:  Is the RX Servo-Impuls

Please chek it yourself

![cimg2414](https://user-images.githubusercontent.com/6217896/30241732-81f7c996-9589-11e7-941f-f6ed4929524d.JPG)

**Comment by 3djc** [comment]
You are doing something wrong. The 4 settings exists on Horus, and they are workling as expected,

**Comment by 3djc** [comment]
1 step coarse (so 8)

![image](https://user-images.githubusercontent.com/5167938/30242076-04787a72-9590-11e7-8c68-e6869254b7e6.png)

![image](https://user-images.githubusercontent.com/5167938/30242079-1d32e8ae-9590-11e7-86d4-347f6972f7a9.png)

![image](https://user-images.githubusercontent.com/5167938/30242070-eb223aea-958f-11e7-8a52-bfca7b5072d8.png)

**Comment by 3djc** [comment]
1 step fine (so 2) 

![image](https://user-images.githubusercontent.com/5167938/30242097-6bf25312-9590-11e7-92f3-ca5a6d3c2c84.png)

![image](https://user-images.githubusercontent.com/5167938/30242103-7d590f42-9590-11e7-80e1-bc4829dc0864.png)

![image](https://user-images.githubusercontent.com/5167938/30242115-bc6783d0-9590-11e7-9739-e21dd54ba0ab.png)

My center is at 1.501ms

**Comment by hrenz** [comment]
ok I see,
have tested again with Horus and X9D+ 

This 4us steps are only at throttle  trim and only when "Trim idle only" is set.
At the other trims I can set it 1, 2 ,4, 8 as expected

Yesterday at my tests I had tested only the throttle  (ch1)
at Horus the trim idle only was set random
at X9D+ the trim idel only was not set random

so my error, thanks for testing
