### ISSUE TITLE
Inputs in a Lua Script

### ISSUE THREAD

**Issue by Storchy1** [opentx/opentx#5215]
i have tried to make 6 input values in a lua script OpenTx 2.2
local options = {
  { "Pitch" , VALUE,  2,-100,100 },
  { "Head"  , VALUE, 70,   0,100 },
  { "NRExpo", VALUE, 25,   0,100 },
  { "HExpo" , VALUE, 25,   0,100 },
  { "NRDuRa", VALUE, 75,  25,100 },
  { "HDuRa" , VALUE, 75,  25,100 }
}
i cannot get the last value HDuRa, it is always nil.
I thought it is possible to use 6 input values.
Please help

**Comment by projectkk2glider** [comment]
Should work with 6 inputs. Can you post a minimalist Lua code that exhibits your problem.

**Comment by kilrah** [comment]
Max number of Horus widget options is 5.
Assuming you're talking of that since no more detail on script type/platform/intent was given.

**Comment by Storchy1** [comment]
Thanks for your help!.
@kilrah : You write 5 options for Horus, please can you tell me where i can read this, because i have read that the options in 2.2 are 6. I there an extra documentation for Horus. I have another problem that i have tried to set the BLINK option in lcd.drawText(...)  and nothing happend!

I have a Horus with OpenTX 2.2
I try to add the lua script.
[main.zip](https://github.com/opentx/opentx/files/1308468/main.zip)

Thanks a lot, you all make a really good job.

**Comment by Storchy1** [comment]
I have tried the widget in the simulator.
I can only see the first 5 inputs, perhaps that helps.
<img width="826" alt="simulator" src="https://user-images.githubusercontent.com/26022422/30514182-78aa0ee4-9b10-11e7-9c26-d403fc652a55.PNG">

**Comment by 3djc** [comment]
As Kilrah said, max for horus widgets is 5. There is not much horus widget documentation yet

**Comment by projectkk2glider** [comment]
Widgets have **options** - max 5 of them. Mixer scripts have **inputs** - max 6 of them. The docs for Widgets and Themes are still missing https://github.com/opentx/lua-reference-guide/issues/30.
