### ISSUE TITLE
Companion 2.2 sound file not closed by edit special functions module?

### ISSUE THREAD

**Issue by Smoothead** [opentx/opentx#5222]
Companion 2.2 
After adding a 'play track' sound in special functions
Press the test play button.  Sound is played.
Now simulate. Sound is not played in response to triggering switch.
Log says file access denied.
I suspect this is because the file is not closed after doing a test play in the special functions window.
If Companion is closed and restarted, model opened, simulate, sound is played.
If sound is played again in the special functions window, once again, the simulator fails to play sound.
Screen grab to illustrate
![billerror](https://user-images.githubusercontent.com/32037568/30524961-759fdf36-9bf5-11e7-836c-879643d67b4d.JPG)

The error was reported to me by a member of our club who uses Windows 7 - 
I am seeing the same results using Windows 10.  Both of us using May 30th 2.2
I wonder if other can confirm that there is a bug or offer a solution?

**Comment by mpaperno** [comment]
Related: #4929

**Comment by Smoothead** [comment]
Thank you, I look forward to the new version with the correction applied.
