### ISSUE TITLE
X7 Splash Screen Duration checkbox on radio vs time in companion

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#5227]
rcdiy 11:56 AM 
X7 vs. X9D, Splash Screen Settings under Radio Setup on the Tx
On the X7 splash screen just has a tick box
on the X9d it has the seconds
To set the seconds on the X7 we can use companion
will the X7 firmware be updated to have seconds instead on the tick box like x9d has?

schwabe Admin 12:34 PM
did you test if setting with companion actually works?

rcdiy 12:42 PM
No, just saw the setting was available....

schwabe Admin 12:44 PM
okay, then can you just report the issue that it does not get lost?

**Comment by 3djc** [comment]
Done already, will be in 2.2.1
