### ISSUE TITLE
Sd card vr11

### ISSUE THREAD

**Issue by smokeintheeye** [opentx/opentx#5228]
Hello can anyone let me know the link to get the sd card files for the nightly builds please. My taranis qx7 keeps asking for vr11 but all I have at the min is vr10. Loving some of the new setting on the nightly tho. Keeps up the amazing work. Ps sorry if posted in the wrong place.

**Comment by 3djc** [comment]
That shouln't be much of an issue since you should not use it to fly, but here you go : http://downloads.open-tx.org/2.2/nightlies/sdcard/

**Comment by schwabe** [comment]
Will be published with the next release. Nightlies are not meant for normal use

**Comment by smokeintheeye** [comment]
#3djc #schwabe thank yous so much.
