### ISSUE TITLE
Errors on write model to radio 

### ISSUE THREAD

**Issue by smokeintheeye** [opentx/opentx#5229]
hello all, im getting a bit stuck on writing my models back on to my taranis qx7. i have a screen shot on what open tx comes back to me with but im lost on how to fix it. 
![error1](https://user-images.githubusercontent.com/13908744/30713248-a6067068-9f06-11e7-8e71-ad1561b995ed.PNG)
![error2](https://user-images.githubusercontent.com/13908744/30713252-a8a1f112-9f06-11e7-83ef-5919f43fbc41.PNG)

**Comment by 3djc** [comment]
This is not a support site, but a bug tracking system. Please seek help in forum like rcgroups or openrc, they are better place to seek usage help

**Comment by smokeintheeye** [comment]
Ok no bother just i was thinking it might have bean a bug with it happening in the nightly build. can read all the models off the radio but just cant seen to write out back on.

**Comment by 3djc** [comment]
You mean those model s where read from x7 ?

**Comment by smokeintheeye** [comment]
yes i can read all setting and models off the radio but if i got to edit any of them and then go to write the models back to the x7 i get the errors show above. just a bit lost on how to fix it. looking it up now but cant seem to fine out that helps yet. iv run as admin backed everything up reformatted the mem card still the same. any help will be amazing. thanks

**Comment by 3djc** [comment]
Then could you please post your otx ? Looked liked it was coming from a different radio type

**Comment by smokeintheeye** [comment]
the open tx im using is companion-windows-2.2.1N384. same for firmware and x7 bootloader -2.2.1n384. will go back to stock 2.2 see if that fixs it. but i like the new 2.2.1 the holding the power on the turn on is loads better. shutdown logo is a nice touch as well.
![settings](https://user-images.githubusercontent.com/13908744/30716419-e261a6ee-9f11-11e7-9dfe-0c42281b85e1.PNG)
![settings2](https://user-images.githubusercontent.com/13908744/30716424-e411ea58-9f11-11e7-89c0-50613a408faa.PNG)

**Comment by schwabe** [comment]
We need the actual otx file to debug this.

**Comment by smokeintheeye** [comment]
ar right you will have to point me in the right direction to what one you want and its location. i can send you the models or eeprom or back up. but im not 100% on the right OTX file to send

**Comment by kilrah** [comment]
Use "Backup radio to file" and send the resulting file.
Looks like the data comes from another radio type, and the conversion needs manual intervention.

**Comment by smokeintheeye** [comment]
hope this helps. after updating to the nightly build i reset the full radio to stock reformatted to sd card and copied the vr11 sd content over. all models have bean made new on the x7 its self. thanks for all your help on this.
[x7 Backup.zip](https://github.com/opentx/opentx/files/1322745/x7.Backup.zip)

**Comment by smokeintheeye** [comment]
just updated to the new build of opx still getting the same error? any news on what i can do to fix this?

**Comment by kilrah** [comment]
Something apparently got broken. Use companion 2.2.0 instead of nightlies.

**Comment by schwabe** [comment]
![image](https://user-images.githubusercontent.com/1038539/30773873-0499f0ae-a07a-11e7-842b-53f683abd662.png)
![image](https://user-images.githubusercontent.com/1038539/30773877-0f6379e2-a07a-11e7-8490-3f0608f3e615.png)
Something gone terrible wrong here

**Comment by schwabe** [comment]
Git bisect tells me that I broke this in 87295776ff923314e0de699bc151d2ee3deb9360. But I am not seeing any change that affects the X7.

**Comment by smokeintheeye** [comment]
I still get the same errors even after updating to the last 2 nightlys.is it something I'm doing wrong or is it a bug in open tx? Thanks for all your help on this.

**Comment by kilrah** [comment]
Please read what we told you... It was a bug, and @schwabe fixed it yesterday, so today's nightly should be OK. Please also give actual build number of what you test instead of "the last".
