### ISSUE TITLE
Update for QX7S

### ISSUE THREAD

**Issue by reptil1990** [opentx/opentx#5230]
I got the new QX7S and wanted to flash a different configuration. When is support coming or did I miss something?
Thank you!

**Comment by 3djc** [comment]
Full support of X7S will be coming in 2.2.1 (including BT), but most things should work

**Comment by kilrah** [comment]
Just flash X7... they're the same at this point.

**Comment by reptil1990** [comment]
> Just flash X7... they're the same at this point.

I am a little bit concerned because the QX7 has no trainer function

**Comment by reptil1990** [comment]
@3djc what is the timeline for the 2.2.1 release? Would be happy to test and give feedback!

**Comment by kilrah** [comment]
There is no timeline. 

X7 firmware has trainer function, just not over bluetooth. 
Bluetooth trainer is currently not an OpenTX feature on any platform anyway. It will be added soonish, but not sure it will make it in 2.2.1. 

You can test the nightly builds if you wish.

**Comment by schwabe** [comment]
@reptil1990 btw. what build information does your released firmware on your X7s has?

**Comment by reptil1990** [comment]
i can send you the dump i made before i flashed the current 2.2

**Comment by reptil1990** [comment]
[origFirmarQX7S.bin.zip](https://github.com/opentx/opentx/files/1325582/origFirmarQX7S.bin.zip)

that was on the radio

**Comment by schwabe** [comment]
Thanks!

2.2.0 (63baa76c)
2017-09-05 19:54:14

**Comment by reptil1990** [comment]
@schwabe your welcome hope it will help
