### ISSUE TITLE
Irangex IRX4 missing option when using Taranis QX7s when using spektrum RX

### ISSUE THREAD

**Issue by WodiFPV** [opentx/opentx#5231]
I have the taranis QX7 with the IRangeX IRX4 4-1 module. With Spektrum rx you had to go to Multi then pick DSMX and the speed 11 or 22ms. I put the module in my new QX7s and that Multi option doesnt show up at all. So now I can not bind to my Spektrum stuff when needed. the QX7s uses a different vertion of opentx aparently that is not fully functional with the IrangeX IRX4 4-1 module.

**Comment by schwabe** [comment]
You can flash the standard X7 firmware with multimodule option.
