### ISSUE TITLE
its not possible to decrease number of chanels in PPM mode

### ISSUE THREAD

**Issue by Tiefflieger68** [opentx/opentx#5233]
Companion 2.2.0 and 2.2.1N386
Test:
- activate PPM protocol for external module
- find the default settings of 8 channel and frame length of 22.5 ms
- increase eg. nbr of channels to 11 - everything is fine, frame length will modified automaticly (need to switch to an other tab and back to config tab to see the result)
- try to decrease back to 8 ch. everything seems ok from first view. But after switch to an other tab and back to config the old value of 11 channels is set

tested with Radio Type 9XR Pro and X9D Plus
everything is fine at companion 2.1.9

**Comment by Tiefflieger68** [comment]
tested with Radio Type 9XR Pro and X9D Plus

**Comment by kilrah** [comment]
Cannot reproduce. Please give more detail if confirmed.
