### ISSUE TITLE
Companion 2.2.1 Higher Input Sources Disappear

### ISSUE THREAD

**Issue by r41065** [opentx/opentx#5235]
![screenshot002](https://user-images.githubusercontent.com/15220072/30798795-1c415c8a-a1db-11e7-83db-d8955f9bae7d.jpg)
![screenshot003](https://user-images.githubusercontent.com/15220072/30798800-204ffa20-a1db-11e7-9d1f-fff433732054.jpg)

First Time Import Models from OTX 2.2 I wonder that Simulator didnt start
Using Higher Input Numbers all are shown with ??? as Source.
Write all Source manual in again and save them but next time i start this Model the sources are dissappeared again

looks that only the first 4 Inputs-Lines  are saved to OTX-File

Radio Type is Taranis X9d

[Jan221.otx.zip](https://github.com/opentx/opentx/files/1328746/Jan221.otx.zip)

Ralf

**Comment by r41065** [comment]
Operating System from Computer is Win 7/8

**Comment by kilrah** [comment]
What nightly? Probably fixed on today's one.

**Comment by r41065** [comment]
N380..N387  the other i have not tested

**Comment by kilrah** [comment]
Yes looks OK. Please always check on the very latest before reporting an issue.

![clipboard01](https://user-images.githubusercontent.com/6065069/30800011-efaaa9a2-a1de-11e7-8c30-dbdad124448a.png)

**Comment by r41065** [comment]
Sorry but since Yesterday i get only a network Time Out Error if i try to connect 
to http://downloads-22.open-tx.org/nightlies/companion/windows/

N387 was the last version i got...

**Comment by kilrah** [comment]
Ah yep, server went down, and also didn't build a nightly as it broke before the scheduled time... you're forgiven ;)

**Comment by kilrah** [comment]
Today's nightly is now up if you want to test.

**Comment by r41065** [comment]
N388 looks like it works correct:
Thank You
Ralf
