### ISSUE TITLE
Taranis Q X7: elevator trim does not follow input inversion

### ISSUE THREAD

**Issue by twistedwings** [opentx/opentx#5238]
if elevator input is inverted (weight -100), the trim is not inverted.
Applies to elevator only, other inputs are ok.

Taranis Q X7
opentx 2.2.0

**Comment by 3djc** [comment]
Cannot replicate (and btw, -100 weight on input does not invert trim, on any channel, it only does in mixer)

Evidence:
![image](https://user-images.githubusercontent.com/5167938/30858605-a9347c86-a2c0-11e7-819e-82a87ccf1817.png)

![image](https://user-images.githubusercontent.com/5167938/30858902-dd0b7d92-a2c1-11e7-85b7-90b9f6c3d47c.png)
