### ISSUE TITLE
Crossfire protocol implmented from OpenTX 2.2

### ISSUE THREAD

**Issue by krzysztofkuczek** [opentx/opentx#5239]
Hi,
Can you share any documentation regarding crsf protocol you are implementing from version 2.2.
I took a loot at source code, and it's quite different to the implementation i found in betaflight... event bitrate is different  420000 vs 400000 ?

I'm going to force my lrs to work with taranis ;)
Thank you in advance
Krzysiek

**Comment by 3djc** [comment]
No sure what you are asking:  our code is open to have a look at, and crsf is a product of TBS, they are the ones you should be asking for specs and documentation if I understood you correctly

**Comment by krzysztofkuczek** [comment]
Ok,
I just thought that, there is free available crsf protocol documentation...

**Comment by schwabe** [comment]
@krzysztofkuczek for olrs there is already an implementation of the multi protocol that OpenTX also supports. 

And also it might be entirely possible that rxs use a different buad rate and protocol than the tx

**Comment by krzysztofkuczek** [comment]
Thx, 
But there seems to be no mult protocol documentation neither ;)
Except source code :) or maybe i can't find such a basic information like frame format, bound rate on it's doc page https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/tree/master/docs

Regards
Krzysiek

**Comment by schwabe** [comment]
OpenTX has a pointer to the docu and DIY has the douc in the header

https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Multiprotocol/Multiprotocol.h#L437

If you have additional questions etc. feel free to ask or drop by in our chat. There is also a pull request open from that implements sbus output if you looking for a simple standard protocol.

**Comment by krzysztofkuczek** [comment]
Schwabe, Thank you very much :)
