### ISSUE TITLE
LUA lcd.drawBitmap on X7 doesn't work

### ISSUE THREAD

**Issue by NiklasVoigt** [opentx/opentx#5240]
Hi, i've checked out commit 541aa459cf5e368dbff916553e4124abc43e2fb9 for testing drawBitmap for the X7, but this doesn't work.

LUA:
lcd.drawBitmap(0, 0, "plane.bmp")

CLI:
Script error: wizard.lua:40: attempt to call field 'drawBitmap' (a nil value)

Thanks!

**Comment by 3djc** [comment]
It does

```
-- Main
local function run(event)
  lcd.clear()
  lcd.drawPixmap(1, 1, "plane.bmp")
  return 0
end

return { init=init, run=run }
```

![image](https://user-images.githubusercontent.com/5167938/30857751-3b53bce8-a2bd-11e7-9552-237e7c72c665.png)

**Comment by schwabe** [comment]
you need a nightly build. 2.2.0 does not have the feature

**Comment by NiklasVoigt** [comment]
now i am on 2.2.1 but the image does not displayed..
the graphic i used is an 1bit bmp file, maybe you can add yours..

Screenshot of the X7
![screenshot_x7_17-10-03_12-52-51](https://user-images.githubusercontent.com/18678779/31121853-154c4c04-a83a-11e7-945c-6297c5b5538e.png)

Lua
```
-- Main
local function run(event)
  lcd.clear()
  lcd.drawPixmap(1, 1, "/plane.bmp")
  return 0
end

return { init=init, run=run }
```

CLI
```
findTrueFileName(/home/niklas/Desktop/sdcard-taranis-x7-2.2V0011/plane.bmp)
	found in map: /home/niklas/Desktop/sdcard-taranis-x7-2.2V0011/plane.bmp
f_open(/home/niklas/Desktop/sdcard-taranis-x7-2.2V0011/plane.bmp, 1) = 0x7f4fd4002270 (FIL 0x7f4ffccafdc0)
f_size(0x7f4fd4002270) 544
f_close(0x7f4fd4002270) (FIL:0x7f4ffccafdc0)
```

**Comment by 3djc** [comment]
I tested with one from here: http://www.open-tx.org/screens-9x.html

**Comment by NiklasVoigt** [comment]
same behaviour in CLI with a png file from the link

**Comment by 3djc** [comment]
```
convertToSimuPath(): plane.bmp -> plane.bmp
findTrueFileName(plane.bmp)
	found in map: plane.bmp
f_open(plane.bmp, 1) = 03EEEAC8 (FIL 085BF024)
f_size(03EEEAC8) 318
f_close(03EEEAC8) (FIL:085BF024)
```

**Comment by 3djc** [comment]
[plane.zip](https://github.com/opentx/opentx/files/1352472/plane.zip)

**Comment by 3djc** [comment]
I guess you did not see the footprint on max pict size

**Comment by NiklasVoigt** [comment]
Thank you, now it works! How much is the max size

**Comment by 3djc** [comment]
Maybe it would be wise to look for that info on opentx lua manual ?

**Comment by floaledm** [comment]
Have any of you tried drawPixmap() on the X7 with images narrower than 25 pixels? I can't seem to get any image of 24 pixels wide or less to draw correctly... No problem on the height (as long as it is 64 pixels or less).
Here's the code, the files I used, and a screenshot of the result. test1.bmp is 25 pixels wide. test2.bmp is the same image cropped by one pixel on the right, so it is 24 pixels wide.
```
lcd.drawPixmap(1, 1, "/test1.bmp")
lcd.drawPixmap(30, 1, "/test2.bmp")
```

[test.zip](https://github.com/opentx/opentx/files/1577519/test.zip)

![result](https://user-images.githubusercontent.com/9093438/34235856-ff5fc1ce-e5b9-11e7-8459-c783d682385c.png)

Pardon my ignorance, but what is the max image size on the X7? 64x64?
