### ISSUE TITLE
[BUG] Downloads on open-tx.org won't work!

### ISSUE THREAD

**Issue by YloXx** [opentx/opentx#5241]
All the downloads on the website www.open-tx.org won't work at all!

**Comment by 3djc** [comment]
Indeed, the server is currently down, not ETA for having it back up

**Comment by YloXx** [comment]
please send me the files, I will create a temp download dir link!

**Comment by schwabe** [comment]
@Meetbaar Thanks for the offer but we are okay

**Comment by YloXx** [comment]
Then please send me the installer for windows so i can move on with my taranis :+1:
