### ISSUE TITLE
[Q X7] Can't view free memory

### ISSUE THREAD

**Issue by teckel12** [opentx/opentx#5242]
From the main page, long pressing enter and stats brings up a timer and throttle graph, but on other Taranis transmitters you press the + key to see the free memory. No + key on the Q X7 and the dial doesn't change the view. I'm trying to diagnose a Lua script that's out of memory but I can't see the memory used without this working (unless there's another way I'm not aware of).

**Comment by 3djc** [comment]
Fixed in#5199, will be in 2.2.1
