### ISSUE TITLE
Nightly Companion 2.2.1N391 are "Unable to check for updates".

### ISSUE THREAD

**Issue by KrickeH** [opentx/opentx#5252]
After installing Companion 2.2.1N391 I get: "Unable to check for updates".
If I uninstall and install 2.2.1N390 instead, it works and I could download 2.2.1N391 firmware.

OS = Windows 10 - 64
TX = X9D+ SE

**Comment by kilrah** [comment]
Yup, depends on #5217.
Until done that will only work if you already have OpenSSL libraries somewhere on your system.
