### ISSUE TITLE
Taranis X9D simulator issues on mac

### ISSUE THREAD

**Issue by mcvd02** [opentx/opentx#5257]
Updated radio to 2.2.0 and now my radio does not work on simulator. Mac recognizes radio but not sensing any of the inputs.Radio worked perfectly prior to updating.

**Comment by schwabe** [comment]
I cannot reproduce this. Did you check in setting if your remote is displayed there?

**Comment by mcvd02** [comment]
On my computer? If thats what your asking yes it is displayed there.

**Comment by schwabe** [comment]
Is it displayed in finder? Can you make a screen of the system information screen with the Taranis selected? Like this

![image](https://user-images.githubusercontent.com/1038539/31055567-f96366ec-a6c4-11e7-9ca3-ef97a397f471.png)

**Comment by mcvd02** [comment]
Yes mine shows up

**Comment by mcvd02** [comment]
![img_3905](https://user-images.githubusercontent.com/32434314/31055854-aa65a296-a686-11e7-9550-f6656a76dcd5.JPG)

**Comment by schwabe** [comment]
Also selected as the joystick in Companion's preferences? (Btw. you make a screen with CMD+Shift+4)

**Comment by mcvd02** [comment]
Can you send screenshot? Only setting I thought you had to uncheck was the mass storage option

**Comment by schwabe** [comment]
![image](https://user-images.githubusercontent.com/1038539/31056038-02735524-a6cc-11e7-849e-9fda2b994a93.png)

But for the future is rather a bug tracker than a help support forum

**Comment by mcvd02** [comment]
This is potentially a bug and it is enabled. Like I said had no issue prior to updating.

**Comment by kilrah** [comment]
Did you also update your mac? Joystick on mac is messy. Never managed to have it work without an utility here, don't have the name at hand.

**Comment by schwabe** [comment]
also please provide as much information as possible. It is annoying to ask you every little detail. Do the sticks work in the calibration box on the companion screen? Does the joystick feature work in other apps, etc.

**Comment by kilrah** [comment]
Like when you say "simulator" @schwabe takes it to be companion's radio simulator. I suspect you might be talking of a third party flight simulator instead, but since you didn't give details we have no idea.

**Comment by mcvd02** [comment]
Update-Mac recognized FrSky Taranis joystick but companion does not. Say joystick not found in companion simulator settings.

**Comment by schwabe** [comment]
@mcvd02 You are contradicting yourself. In https://github.com/opentx/opentx/issues/5257#issuecomment-333383512 I asked you if your Taranis is recognized there in Companion and you said you have it enabled. And now you say that the Joystick is not found by Companion? 

Sorry, what you are writing so far is to imprecise and vague to get a picture what is really happing on your side and what you are actually doing.

**Comment by mcvd02** [comment]
It was enabled before I updated in companion. I just plugged in controller to double check and it is not being recognized in companion. This is the current condition. My mac recognizes and companion does not. Sorry for the confusion.

**Comment by mcvd02** [comment]
3rd party flight simulators recognize joystick but none of the inputs/channels working.

**Comment by schwabe** [comment]
Taranis might need to connected before starting companion. Not 100% if we update that list dynamically

**Comment by mcvd02** [comment]
Connected Taranis prior to opening companion, still does not recognize.

**Comment by mcvd02** [comment]
Any recommendations??? Why would stock Taranis X9D Plus SE work stock and after updating not work?

**Comment by schwabe** [comment]
All I know is that it works fine with macOS sierra and High Sierra. And your bug report has not given enough information to even try to reproduce your problem, sorry!

**Comment by mcvd02** [comment]
OS X Yosemite 
version 10.10.5
What other information do you need?

**Comment by mcvd02** [comment]
Companion recognizes taranis joystick now but going through calibration, none of the channels are being recognized. I was in boot loader mode earlier trying to get simulator on companion to recognize it.

**Comment by powercycle** [comment]
To be clear, for the mac (and I think for the others as well) you just plug it in to the computer and it recognizes the transmitter as a joystick, right?  No special configuration or anything needed.

**Comment by kilrah** [comment]
You do need to set up appropriate mixes on the radio though of course.

**Comment by powercycle** [comment]
Would not having mixes explain the output issue that @mcvd02 is experiencing?

**Comment by schwabe** [comment]
@powercycle yes channels 1-8 are mapped to joystick axis 1-8 and channels 9-32 are mapped to the joystick button. If every channel is just always 1500 nothing happens on the PC side.

**Comment by powercycle** [comment]
Thanks.

**Comment by mcvd02** [comment]
Can you point me in the right direction to set these up? Like I said it was working perfect prior to update. Thanks

**Comment by mcvd02** [comment]
I have set weight and offset to 50, still nothing

**Comment by schwabe** [comment]
Can you try to test your Taranis on a different PC/Mac to check what part of your system broke? Or backup your eeprom and flash back to the old version and see if it changes anything?

**Comment by schwabe** [comment]
The Taranis HID just implements a standard HID joystick. There hasn't been much changes from 2.1 to 2.2 (other than 24 instead of 8 buttons)
