### ISSUE TITLE
Updated OPENtx to 2.2.0- Now have Companion simulator issues

### ISSUE THREAD

**Issue by mcvd02** [opentx/opentx#5259]
Companion simulator and mac are recognizing taranis X9D but none of the channels are working after upgrading to Opentx 2.2.0. All 3rd party simulators are recognizing usb taranis joystick but none of them are recognizing ay inputs/channels. 

Macbook Pro 
OS X Yosemite 10.10.5

Companion and SDCard content updated to 2.2.0

**Comment by schwabe** [comment]
You already reported this as #5257. Please don't open duplicate issues.
