### ISSUE TITLE
companion: no D8 mode

### ISSUE THREAD

**Issue by twistedwings** [opentx/opentx#5262]
I cannot select D8 mode in companion, in the radio I can.

Taranis Q X7
opentx 2.2.0

![no d8 companion](https://user-images.githubusercontent.com/562809/31135241-b193eb60-a864-11e7-9f3e-a893596f49eb.jpg)

![no d8 x7](https://user-images.githubusercontent.com/562809/31135285-cefc4fe4-a864-11e7-9b0e-5e87e3d4aae4.jpg)

**Comment by schwabe** [comment]
probably your companion is to eu. The simulator is always non EU, your radio might also have a non EU firmware

**Comment by twistedwings** [comment]
"probably your companion is to eu"

What does that mean ?
Is there a eu and non eu companion ?

**Comment by schwabe** [comment]
options of your radio in settings.

**Comment by twistedwings** [comment]
there is no eu option in the radio settings.
Firmware is non eu.

**Comment by schwabe** [comment]
There sure is one. See screenshot
![image](https://user-images.githubusercontent.com/1038539/31139086-c2d6ef6a-a870-11e7-8bcc-598a698ba67b.png)

**Comment by twistedwings** [comment]
I was assuming that as a firmware option only.
Anyway the "eu" is not checked in companion.

**Comment by schwabe** [comment]
The eu option is the only things that controls if D8 shows up or not.

**Comment by twistedwings** [comment]
and why does it not show up ?

**Comment by schwabe** [comment]
please double check that you have not selected the eu option.

**Comment by twistedwings** [comment]
eu is unchecked believe me

**Comment by schwabe** [comment]
Try close/reopen companion. I have nothing I can anymore on my end. I cannot reproduce it and I looked through code and the code really only checks if eu is selected.

**Comment by twistedwings** [comment]
restart does not change anything.
The problem occurs on my notebook only.
On my desktop I cannot reproduce it either.

**Comment by kilrah** [comment]
Try creating a new radio profile.

**Comment by twistedwings** [comment]
creating a new profile solved the problem
