### ISSUE TITLE
Horus: widget registration

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#5265]
even though a widget name in the return specification of the script may be mroe then 10 characters, and the widget will run normally, it doesn't get registered in that case.

Same restrictions on the options specification.

Is it possible to create a warning? I've added it to this reworked version of the counter script:

`---- #########################################################################
---- #                                                                       #
---- # Copyright (C) OpenTX                                                  #
-----#                                                                       #
---- # License GPLv2: http://www.gnu.org/licenses/gpl-2.0.html               #
---- #                                                                       #
---- # This program is free software; you can redistribute it and/or modify  #
---- # it under the terms of the GNU General Public License version 2 as     #
---- # published by the Free Software Foundation.                            #
---- #                                                                       #
---- # This program is distributed in the hope that it will be useful        #
---- # but WITHOUT ANY WARRANTY; without even the implied warranty of        #
---- # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
---- # GNU General Public License for more details.                          #
---- #                                                                       #
---- #########################################################################
---- #########################################################################
---- #                                                                       #
---- # Redifined the variables and added comments to clarify useage          #
---- # Local variable names are never reused                                 #
---- # This is to prevent people thinking they need to be the same           #
---- #                                                                       #
---- # Guido ter Horst, l Shems on rc.groups                                 #
---- #                                                                       #
---- #########################################################################

--define the options to be transferred to OpenTX
--they are not called within this code, they are only transferred to the OpenTX API
--they are used as defaults in the openTX widget settings page to change them according to user preferences
--maximum five options are allowed, 10 character names max, no spaces!
local defaultOptions = {
  { "ControlX", SOURCE, 1 },
  { "ScrollZ", BOOL, 0 }, -- BOOL is actually not a boolean, but toggles between 0 and 1
  { "StepZ", VALUE, 1, 0, 10},
--  { "Text_Color", COLOR, RED }
--  colors are linked to 'areas', like text, lines, etc. 
--  Changing them through a widget is perhaps not a good idea, as it impacts the radio style settings
  { "Shadow", BOOL, 1 }, -- BOOL is actually not a boolean, but toggles between 0 and 1
}

--define the function that wil be called by Open TX on startup of this widget
--OpenTX will transfer the coordinates of the zone that the user chose for the widget in the OpenTX UI widget setup.
--OpenTX will transfer the defaultOptions that have been passed to OpenTX in the options array as an initial setting
--OpenTX will pass the return array to the 'update', 'background' and 'refresh' function
--a convenient way to define widget data is to define/declare local variables within the createWidget function
--then pass them to the other functions through the return array
--make sure you do any initial preparation, as in an 'init' function in another type of script
local function createWidget(zone, options)
--  lcd.setColor( TEXT_COLOR, options.Text_Color )
--  colors are linked to 'areas', like text, lines, etc. 
--  Changing them through a widget is perhaps not a good idea, as it impacts the radio style settings
  local someVariable = 0
  local anotherVariable = {xOffset=0, yOffset = 0}
  return { zone=zone, options=options , someVariable = someVariable, anotherVariable=anotherVariable }
end

--The user can change the options of the widget in the UI of OpenTX. Define here how to update them.
--Normally, you never have to change this.
local function updateWidget(widgetToUpdate, newOptions)
  widgetToUpdate.options = newOptions
--  lcd.setColor( TEXT_COLOR, widget.options.Text_Color )
--  colors are linked to 'areas', like text, lines, etc. 
--  Changing them through a widget is perhaps not a good idea, as it impacts the radio style settings
end

--this function is always called every xx miliseconds as a background task
--here you should do all your logging and calculations that need to go on even f the widget is not shown

local function backgroundProcessWidget(widgetToProcessInBackground)
  local function process(...)
          return ... + 1
        end
  widgetToProcessInBackground.someVariable = process (widgetToProcessInBackground.someVariable)
end

--this function is only called every xx miliseconds when the widget is shown
--here you typically create the screen output, and do any calculations to support that (scaling, sizing etc.)

local function refreshWidget(widgetToRefresh)
  local counterLength = 50
  local counterHeight = 30
  
  backgroundProcessWidget(widgetToRefresh) --background is not called automatically in display mode
  local function anotherProcess(parameter,step,maxParameter)
          return (parameter + step) % maxParameter
        end
  widgetToRefresh.anotherVariable.xOffset 
    = anotherProcess ( widgetToRefresh.anotherVariable.xOffset,getValue(widgetToRefresh.options.ControlX)/10.24/20,widgetToRefresh.zone.w-counterLength)
    
  widgetToRefresh.anotherVariable.yOffset 
    = anotherProcess ( widgetToRefresh.anotherVariable.yOffset,(widgetToRefresh.options.ScrollZ==1) and widgetToRefresh.options.StepZ or 0
      ,widgetToRefresh.zone.h-counterHeight)
  lcd.drawNumber(widgetToRefresh.zone.x + widgetToRefresh.anotherVariable.xOffset, widgetToRefresh.zone.y + widgetToRefresh.anotherVariable.yOffset
    , widgetToRefresh.someVariable, LEFT + DBLSIZE + TEXT_COLOR + ((widgetToRefresh.options.Shadow == 1) and SHADOWED or 0));
end

--now you want to inform OpenTX about your widget by returning its definition
--make sure you use no more then 10 characters for the name!
--Otherwise you can use it, but it doesn't remain registered.

return { name="MovingCntr", options=defaultOptions, create=createWidget, update=updateWidget, refresh=refreshWidget, background=backgroundProcessWidget }
`

**Comment by T3chDad** [comment]
This bug cost me hours and hours working on a custom widget. Thanks for posting it to provide a reason.
