### ISSUE TITLE
getVersion updated? ambiguous documentation and improvement suggestion

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#5266]
The documentation is confusing:

in the code example it is said the second argument contains the radio type:
output example given:
--radio: taranis-simu

in the description it says possible types are:
radio version: x9e, x9d+ or x9d. If running in simulator the "-simu" is added

the horus gives x12s in the simulator
the taranis plus gives x9d+ in simulator.

If it is updated it should state from what version.
I'm happy to change the documentation, but need to know when it was changed?

I suggest an improvement to make the Horus or Taranis type of GUI part of the versioning. Otherwise it has to be derived in indirect ways.

**Comment by projectkk2glider** [comment]
>I suggest an improvement to make the Horus or Taranis type of GUI part of the versioning. Otherwise it has to be derived in indirect ways.

You can use constants `LCD_W`  and `LCD_H` (LCD width and height) to determine if you are on Horus or not.
