### ISSUE TITLE
Data Logging

### ISSUE THREAD

**Issue by AloftHobbies** [opentx/opentx#5269]
I just ran into something I had not noticed and wanted to make a quick suggestion that should help users. 

I did not know that the RSSI was not logged automatically when logging is turned on, yet the radio is monitoring the RSSI. Failure to discover sensors and no voltage and no RSSI are logged. Someone not using any extra sensors may not be in the habit of discovering sensors when setting up a new plane.

My simply suggestion - When binding a new receiver, after the binding, open a popup window asking the user if they would like to discover sensors. Heck, I would love to see an option in the wizard to add logging to a model. :) It can be a very useful tool.

How come SWR is not logged anymore? Or have I failed to turn it on? We find this a useful tool, especially when looking at a log file from a flight that resulted in a crash.

Thanks!

**Comment by KevinFairgrieve** [comment]
Absolutely yes.

I was looking for some GPS info in Open TX 2.2 and had forgotten to select the Logs option. All this time I thought I was recording GPS to import into google earth....
