### ISSUE TITLE
X10s default style background color change slow

### ISSUE THREAD

**Issue by meoster** [opentx/opentx#5271]
Color change for default style background color changing is very slow. 

Tested with 403 nightly.  SD card v11 on a X10s final production unit.

**Comment by meoster** [comment]
I found out why it is slow.. for the background color change in user interface.  A rambackupwrite is done for ever dial change.  this likely added lots of write lag into the menu.  For a similar control in the channel widget.  The rambackupwrite is down after the dial has been selected and returned.  

>trace on
>RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
RamBackupWrite sdsize=10227 backupsize=4531 rlcsize=452
eeprom write general

**Comment by meoster** [comment]
Disabled the rambackupwrite to test, got a little faster; but something else is still causing the lag.

**Comment by rcbebo82** [comment]
Same as #3799

**Comment by kilrah** [comment]
Closing as duplicate.
The reason it's slow is having to render the entire screen again (instead of just using the cache).
