### ISSUE TITLE
2 free switch socket at X7, X10, X12 how can I use it

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5273]
At X7, X10, X12 are 2 free 2way switch socket at the main board

Can I use it at openTx now?
Can I select it at harware setting?
would be good for stick switches

**Comment by 3djc** [comment]
Since those where not in the drawings nor hardware sample provided to us, nothing has been planned. Adding those would require an Eeprom change, so unlikely to happen in minor revisions
