### ISSUE TITLE
radio menu SWITCHES

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#5274]
The X7 has swicthes SA to SH that can be tested
![screenshot_x7_17-10-14_13-59-16](https://user-images.githubusercontent.com/20209851/31578109-954f3c2a-b0e8-11e7-93e8-f6fadefb6a59.png)

The X9D series does not... add them?
![screenshot_x9d _17-10-14_14-03-03](https://user-images.githubusercontent.com/20209851/31578113-a4401a92-b0e8-11e7-81a1-3a472405ba04.png)

**Comment by geofrancis** [comment]
it has them on the main screen

http://open-txu.org/wp-content/uploads/2014/09/taranis_screen_labled.png

**Comment by 3djc** [comment]
Yes, and they can't be on x7 main screen given the lack of available space.
