### ISSUE TITLE
V2.2.0 GRange from GPS gives incorrect value.

### ISSUE THREAD

**Issue by duartecabral** [opentx/opentx#5280]
GRange from GPS gives incorrect value. The value returned is much greater then the hypotenuse of the right angle triangle formed by horizontal and vertical distances. The value returned value appears to be the sum of the 2 right angled sides of the triangle formed by the base (Horizontal distance) and height of the triangle.

**Comment by schwabe** [comment]
You are talking about dist telemetry calucated funtion, right?
