### ISSUE TITLE
V2.2.0 Manual Setting of Pots does not work. 

### ISSUE THREAD

**Issue by duartecabral** [opentx/opentx#5282]
Manual Setting of Pots does not work (Screen 2 of 13) 
The work around was to set it to "Auto Set" and then cycle the power on the radio which caused the radio to remember the Pot Settings and then go to Screen 2 of 13 and change the "Auto Set" of Pots to "Manual Set" of Pots so that it would (could not) not be changed.

Nice feature if it worked properly!!!!!

**Comment by kilrah** [comment]
Tested and working. That said, you didn't even mention the radio type.
