### ISSUE TITLE
V2.2.0 Setting of Servo end Points Does Not Work in Servo Output Window in Some Cases!

### ISSUE THREAD

**Issue by duartecabral** [opentx/opentx#5283]
If one uses S1 for a input and a curve to modify the servos response to it, then in the "Servo Output" window, only the centering of the servo works. Setting of the servo end points does not work! This limits the servo's to 100% movement and not the capable 125% movement. It also makes it more difficult to switch out a bad servo.

The work around for this is to use the curve to control the end points but the servo end movement is limited as described earlier.

**Comment by schwabe** [comment]
YOu need to enable extending limits (or similar) to enable outputs with more than 100%
