### ISSUE TITLE
V2.2.0 Expontetional Selection for single side curve not available for Throttle.

### ISSUE THREAD

**Issue by duartecabral** [opentx/opentx#5284]
With respect to the throttle function, a single sided exponential curve is not available for selection. Only 2 sided symmetrical curves about "0" are available which is not what is needed for the throttle.

Work around was to define a multi point curve to simulate an exponential which is much more tedious.
Interesting a single sided exponential curve is available for selection in Companion.

**Comment by kilrah** [comment]
#3478
#1654
