### ISSUE TITLE
Taranis X7 "FW update error bottom pin no resp"

### ISSUE THREAD

**Issue by rrlarenas** [opentx/opentx#5287]
Hello guys, well I got a newer taranis X7, but i'm uneable to flash my rx using the bottom s-port in the tx.. I've got this message "FW  bottom pin no resp" the RX turn on just  a fraction of sec then,it turn off and i've got the message on the radio..

I'm Ussing O-TX 2.2.0

Any help?

**Comment by schwabe** [comment]
Double check everything. Note this is a bug tracker. Not a help forum. Use rcgroups or openrc forums to seek help.

**Comment by sk-design** [comment]
> Hello guys, well I got a newer taranis X7, but i'm uneable to flash my rx using the bottom s-port in the tx.. I've got this message "FW bottom pin no resp" the RX turn on just a fraction of sec then,it turn off and i've got the message on the radio..
> 
> I'm Ussing O-TX 2.2.0
> 
> Any help?

Hi rrlarenas,
Were you able to find a solution to this problem? I have the exact same problem.
Look forward to your help and reply.

Thanks

**Comment by rrlarenas** [comment]
Hello there 

Just update O-Tx to last versión and it works

Get luck!!

Atte.

Rodrigo Larenas

**Comment by sk-design** [comment]
Hi Rodrigo,

I am running the latest version firmware on OpenTX (2.2.3)
Still no luck.

Thanks

**Comment by 3djc** [comment]
It does work, You are either using the wrong cable (you need a simple straight one) or have it reversed

**Comment by kilrah** [comment]
Ot the receiver is faulty, we heard a few times of receivers that refused to be flashed.
