### ISSUE TITLE
SWR not working on Taranis Plus version B01

### ISSUE THREAD

**Issue by lcdvt** [opentx/opentx#5288]
The SWR reading stays blank. 

FW: opentx-x9d+
VERS: 2.2.0 (85863358)
DATE: 2017-05-30 23:50:52

**Comment by 3djc** [comment]
https://github.com/opentx/opentx/issues/4801 ?

**Comment by lcdvt** [comment]
Thanks 3djc I guess it's called RAS now. Menu long press Page 7/9 ANALOGS TEST screen.
