### ISSUE TITLE
Q x7s bricked

### ISSUE THREAD

**Issue by ivv72** [opentx/opentx#5290]
Hello,

I wanted to upgrade my taranis x7s with open tx firmware and I only found firmware for the Q X7, andnot for the Q X7S.
So I was stupid enough to take the Q X7 firmware and flash my Q X7S with it.
The consequence was that I bricked my taranis.
It turns on and shows the splasch screen and when the throttle warnig goes the screen goes blank.
Can any body help me, onthe frsky site there is only firmware forthe Q X7 and also not for the Q X7S.
Thank you

greetings

Igor

**Comment by andreab3** [comment]
Odd, when I tried that it recognized that it was a Q X7 and didn't let me flash it.  Anyways, if you email me at temp123@audasys.ca I can send you the backup I made _before_ I tried to flash it.. :)

**Comment by geofrancis** [comment]
you should be able to start in bootloader mode and reflash the firmware

**Comment by 3djc** [comment]
Not an OpenTx bug, closing it
