### ISSUE TITLE
Failure to start if RTC 32kHz oscillator is not working

### ISSUE THREAD

**Issue by MikeBland** [opentx/opentx#5294]
If the LSE oscillator fails to start (e.g. faulty 32kHz crystal) then the RTC Init code hangs causing a continuous watchdog reset.
This is particularly bad if the LSE fails during operation and then a watchdog reset occurs for some other reason, the radio does NOT restart.
The solution is to add a (software) timeout while waiting for the LSE to start (in rtc_driver.cpp):
```
  uint32_t i ;
  i = 0 ;
  while(RCC_GetFlagStatus(RCC_FLAG_LSERDY) == RESET)
  {
    if ( ++i > 1000000 )
    {
      return ;
    }
  }
  RCC_RTCCLKConfig(RCC_RTCCLKSource_LSE);

```

**Comment by kilrah** [comment]
Thanks 👍
