### ISSUE TITLE
trainer port setup for turnigy 9x

### ISSUE THREAD

**Issue by turborocket** [opentx/opentx#5296]
Hi all, i would like to connect an headtracker over the training porto of my turnigy 9x with opentx fw. I mapped in the mixer page the channel 7 with trn7(pan) and channel 9 with trn8(tilt). but nothing is working....there is some other option to enable the input from trainer port?

**Comment by 3djc** [comment]
Sorry, this is not a place to seek support, but one to track bugs. Please go to support forums like rcgroups or openrcforum
