### ISSUE TITLE
Support for FLVS-01

### ISSUE THREAD

**Issue by CaptDen** [opentx/opentx#5297]
I have a D8R-xp receiver connected to a FSH-01 Sensor Hub to a FAS-40 40Amp Sensor to a Flvs-01 Lipo V Sensor. Using the opentx 2.2 software I don’t see a cels or Cells or Cell sensor call out. Is this configuration supported? If it is can someone help me configure it either on the radio or in Conpanion?

**Comment by 3djc** [comment]
Sorry, this is not a place to seek support, but one to track bugs. Please go to support forums like rcgroups or openrcforum
