### ISSUE TITLE
Increase "delay" and "slow" times

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#53]
_From [joaoalve...@googlemail.com](https://code.google.com/u/107758819364615868605/) on June 27, 2013 14:25:10_

Which board (stock / gruvin9x / sky9x / Taranis) are you using? What is your openTx FW version? All boards I suppose.

It would be nice to have longer delay and slow times but also keep The small steps. maybe something like you did for the Custom switches Timer?

Thanks

By the way, I can't post this as enhancement. The option doesn't show up.. only defect :(

_Original issue: http://code.google.com/p/opentx/issues/detail?id=53_

**Comment by kilrah** [comment]
This was certainly for 9x where the choices were up to 7.5s with 0.5s steps, we can now do 25 secs with 0.1s steps, pretty sure that's enough.
