### ISSUE TITLE
PPAs don't support latest Ubuntu versions; 17.04 or 17.10

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#5302]
The PPAs in question;

https://launchpad.net/~opentx-test/+archive/ubuntu/rel
https://launchpad.net/~opentx-test/+archive/ubuntu/ppa

They only support 14.04, 16.04 (the two LTS, which makes sense) and 16.10 (which is no longer supported). Can the PPAs be updated with the latest 17.04 and 17.10? Or at least 17.10 since thats the latest? 

I contacted the maintainers of the PPA via launchpad and they said to open an issue on github to add the newer releases.

Thanks

**Comment by projectkk2glider** [comment]
@jw323 new releases are available in nightly PPA https://launchpad.net/~opentx-test/+archive/ubuntu/ppa/+packages Can you test them?

**Comment by ghost** [comment]
I was able to install the nightly with the PPA. Thanks!

Could the stable release be updated as well?

Thank you
