### ISSUE TITLE
QX7 bind to a D8 mode receiver - all 8 channels go crazy 

### ISSUE THREAD

**Issue by gipaq1950** [opentx/opentx#5303]
Hi,
I have a Taranis Q-X7 with opentx 2.2.0 and after I bind to receiver that is integrated into flight controller like Eachine Turbine QX70 Based F3 EVO Brushed Flight Controller Frsky 8CH sbus compatible receiver(D8 mode), the binding process is completed successfully and I go to cleanflight/ betaflight on receiver menu and check if I get connected to transmitter and it's connected moving the sticks' transmitter will move the right channel. But after few seconds without touching the sticks' transmitter all the channel are moving randomly from minimum to maximum and stops for few seconds and moving again randomly like crazy. At first, I thought is the receiver-flight controller board problem but I have replaced with a brand new one and it's doing the same and also I have tried different receiver -flight controller board like Aurora RC JHF3 V1.0 F3 Brushed Flight Controller with Integrated FrSky 8CH Receiver and I get the same crazy channels behavior. 
The strange part is I have other D8 receivers that work fine with the transmitter like Tiny Frsky 8CH Receiver. Also, the transmitter works fine with all D16 receivers.
Please help me to solve this strange problem. Thank you!

**Comment by 3djc** [comment]
Strange indeed, but quite unlikely to be an opentx bug, given the data you supplied (and this tool is only to track bugs) Please raise this in forums like rcgroups or openrc forum.
