### ISSUE TITLE
"Sensor Lost" Raceflight 2.2.0

### ISSUE THREAD

**Issue by GenCodeInc** [opentx/opentx#5306]
In raceflight the voltage is not sent every 15 seconds so "Sensor Lost" keeps repeating.
I renamed the wav so the voice is gone, but the taranis is still vibrating.
I know this is a new feature in 2.2.0 but it would be nice if we could set the timeout or disable this message altogether as I dont care in a race if a sensor fails.

Thanks, Ed

**Comment by schwabe** [comment]
Sending a voltage less than every 15s is a raceflight bug to me. If they want to be compatible with OpenTX/sport they have to send the voltage more often than that to not trigger the warning. Also what voltage is stable enough on a racing quad to be updated only every 15s?
