### ISSUE TITLE
Min/Max settings of GVs seem to have no effect

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#5311]
Companion 2.2.0 simulator, Taranis X9D

1. In the pop up menu of GV1 settings, I set MAX to 50.
2. I set a special function: adjust GV1 with S1 as source.
3. When I move S1 from -100 to 100, GV1 moves accordingly from -100 to 100. Shouldn’t it be clipped to 50 or even scaled to 50 in the positive part?

**Comment by kilrah** [comment]
Needs checking but I believe that only affects the increment / decrement function.

**Comment by elecpower** [comment]
GV Precision also not applied

**Comment by bsongis** [comment]
Testing the whole function now ...
- works correctly with Incr/Decr

**Comment by bsongis** [comment]
- with a constant the precision could perhaps be displayed (it is used) and min / max taken into account (it's not)

**Comment by bsongis** [comment]
- with a mixer source, min / max are not taken into account
