### ISSUE TITLE
Horus x10 + night building  N421 : Statistics go to rescue mode

### ISSUE THREAD

**Issue by nicolas81** [opentx/opentx#5312]
When i select "Statistics"  ( after a long press on enter)   my X10 go to rescue mode.

**Comment by kilrah** [comment]
Any more details? Can't reproduce.

**Comment by nicolas81** [comment]
I'm testing opentx-X10-2.2.1N421 fr
I don't know what kind of details can help you more. I can reproduce this bug everytime. You can see my video :
https://youtu.be/8M65tKr0_78
Thanks for your really good work.

**Comment by kilrah** [comment]
Well for a start that you're using the French version, now we can reproduce...

**Comment by Barbaryann** [comment]
Hello, The same for me, french version and Statistics mode go to rescue mode...

**Comment by Barbaryann** [comment]
Works in the English firmwar version... 
Bug to fix in the french version :D

**Comment by nicolas81** [comment]
The bug still remain in version N426 fr

**Comment by 3djc** [comment]
Which is why it is still opened !

**Comment by bsongis** [comment]
I can't reproduce with EN version. Testing now with FR ...

**Comment by bsongis** [comment]
Reproduced with FR

**Comment by bsongis** [comment]
I think I have it

**Comment by nicolas81** [comment]
Well done and thanks! You're the best.
(I try to understand this code. I installed Qt creator and I managed to compile companion but I don't find a lot of information to understand this code. Have you got some advises to give me?)
