### ISSUE TITLE
X10: LCD brightness bug

### ISSUE THREAD

**Issue by x10user** [opentx/opentx#5314]
Bug: Screen backlight
Category: Firmware
Transmitter: tested on X10 (EU) (affected is most likely also Horus 12s)
Tested with: opentx-x10-multimodule-eu-lua-luac-bindopt-en-2.2.1N421
found by: Danny Koch, homo.faber@gmx.de

Description: It is not possible to set the brightness off value so the screen dims completely. It seems the minimum value is about half dimmed. With the FrOS Firmware I was able to dim it completely.
A possible root cause might be the minimum value expexted from the hardware is -100 (instead of 0). This corresponds to the pot input values (possible to assign in FrOS).
The bug is not critical but increases power consumption and reduces operation time on a battery charge.

![image](https://user-images.githubusercontent.com/33264007/32240728-5efad4e8-be6e-11e7-9322-704353d45c0e.png)

**Comment by kilrah** [comment]
Intentional, backlight lower than 46% causes display corruption due to hardware design.

**Comment by x10user** [comment]
Hello Andre,

After a couple of years of absence from RC planes (mostly sailplanes) I want to restart this hobby and bought a FrSky X10 to replace my outdated 35 MHz radio gear. I selected this TX with OpenTX in mind. I already flashed it with the available nightly builds and  I'm amazed about it.  I really appreciate the work has been done!

Is there something I can contribute?
I'm an mechanical engineer without deeper experience in programming. But from my work and smaller projects I have still some understanding about it. So maybe I can do some testing (i.e. user interface on the X10 or Companion implementation) or provide drawings, sketches (also 3D) for documentation or do some translation to German language.
Please let me know if such kind of help is needed.

best regards
Danny

-----Ursprüngliche Nachricht-----
Von: "Andre Bernet" <notifications@github.com>
Gesendet: Dienstag, 31. Oktober 2017 20:45
An: opentx/opentx <opentx@noreply.github.com>
Cc: x10user <homo.faber@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [opentx/opentx] X10: LCD brightness bug (#5314)

Closed #5314.

-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/opentx/opentx/issues/5314#event-1319586763
