### ISSUE TITLE
X10S ans crossfire : some telemetry lost but no failsafe

### ISSUE THREAD

**Issue by Barbaryann** [opentx/opentx#5315]
Hello,
I have some telemetry lost with my X10S and crossfire :
- Crossfire FW 2.11
- OpenTX N417

BF Lua and Kiss Lua works. Slow but works

Thanks

**Comment by schwabe** [comment]
Can you check the telemetry RX error counter under statistics?

**Comment by Barbaryann** [comment]
I have issue with the statistics mode : https://www.youtube.com/watch?v=Wzt4upfiRhs&list=PLmUct0I1--liC4f3-cGAO_j6Lwbq-y0Ai&index=3
My X10S reboot in HELP MODE :/

**Comment by schwabe** [comment]
Can you flash an English version and check if you get the telmetry RX error counter on that?

**Comment by Barbaryann** [comment]
Okay, I try...

**Comment by Barbaryann** [comment]
Now statistics mode working.
I have More than 10000 on Tlm RX Errs. And it go up and up and up... Now 32789 after 2 minutes...
:/

**Comment by schwabe** [comment]
The X10S seems to have the same "feature"as the X7  of not working at high baud rates then.

**Comment by Barbaryann** [comment]
Shit !
Sorry.
Now we have to wait somebody who can help to explain the hardware mod to fix this bad FrSky idea... :/

**Comment by Barbaryann** [comment]
Thanks for your help

**Comment by Barbaryann** [comment]
Somebody can work on the same software resolve issue than with the Q X7 :  in the Main/hardware menu tu select lower bitrate ?

**Comment by Barbaryann** [comment]
Hi,
Now it is working when i select lower baudrate (100k).
Somebody can expain what are consequences to be in lower baudrate.
I think latency ?
Does it affect the rc command latency or just the telemetry ?
In which time the latency is bigger ? Four time bigger ?

**Comment by kilrah** [comment]
It takes a little more time to get the data to and from the module both for control and telemetry, what the actual impact is would have to be measured with a test setup, likely difficult to predict.
