### ISSUE TITLE
Getting Global Logical Switches in Radio menu

### ISSUE THREAD

**Issue by Tonnie78** [opentx/opentx#5317]
I am very pleased with the new function of Global Functions.

I do have a lot of models which all have the same Special Functions and I would like to replace them all by one single Global Function.

The problem I am facing at the moment is that a large number of my Special Functions are activated by a Logical Switch.  So my request is can we have Global Logical Switches. I would prefer to have 32 Logical Switches in the Models menu and the other 32 in the Radio menu.

**Comment by 3djc** [comment]
Sorry, but this is not possible. Global fonctions cannot refer to  things that might not exist in some models

**Comment by Tonnie78** [comment]
To bad. But thinking about my motor safety switch relies on switch SF and
the Throttle stick which are present in all my models.

I would like to make a global switch L1 a~x  IThr -100 and !Sf^
L2 sticky SF^ L1

I am using this on all my models


Op 1 nov. 2017 09:07 schreef "3djc" <notifications@github.com>:

**Comment by Tonnie78** [comment]
My Request is to have a Radio menu Global Logical Switches. Just like Global Functions. Where I can set Logical Switches that are the same on all models.

I do understand that in order to use them, you need to use data that is available on all models, but isn't that the same for the recently added Global Functions. There also I can activate a function that will not work of the model is not exuipped with the needed hardware. Like take Vario as an example.

**Comment by schwabe** [comment]
The global functions don't allow you do use model specific things.

**Comment by 3djc** [comment]
There is a vario internal function that 1) is always there, 2) does not care if a vario sensor exist or not. that's why you can access this function, not a vario itself (they are two very different thing, albeit they might be looking similar)

**Comment by Tonnie78** [comment]
Oké clear. Just thought it would be a good additional feature to make to Global Functions more usefull

**Comment by kilrah** [comment]
#2409
