### ISSUE TITLE
HORUS (Opentx), negative temperature telemetry values are displayed incorrectly

### ISSUE THREAD

**Issue by vspeak** [opentx/opentx#5320]
In my HORUS (Opentx), negative temperature telemetry values are displayed incorrectly, e.g. -1 ° C is displayed as 64535 ° C. In my opinion, this is due to a faulty data interpretation, instead of an int16 value, a uint16 value is displayed:
0xFFFF -> int16=-1     but uint16= 65535
Is the problem known?

**Comment by 3djc** [comment]
Instead of speculating on causes, maybe you could give us actual usefull  details, such as where you are reading this value ? (widget ? telem screen ? script ?), and also OpenTx version

**Comment by 3djc** [comment]
Seem to work here:

![image](https://user-images.githubusercontent.com/5167938/32268165-2ec90aee-beee-11e7-9cfd-bf2426885fe2.png)

![image](https://user-images.githubusercontent.com/5167938/32268175-3d6524ca-beee-11e7-9ebc-85c50ff778c1.png)

**Comment by vspeak** [comment]
exactly there.
VERS: opentx-x12s-2.2.0 (85863358)
DATE: 2017-06-22

**Comment by schwabe** [comment]
What do you mean with exactly there? IN the telemetry screen or in the main screen?

**Comment by 3djc** [comment]
Then clearly it works. What is you actual sensor ?

**Comment by 3djc** [comment]
I just tested with 2.2.0, works ok too, must be your sensor. Please re-open if you have hard evidence that the isue is with OpenTx

**Comment by vspeak** [comment]
[http://www.vspeak-modell.de/en/ecu-converter](url)
[https://www.youtube.com/watch?v=QuNdJVKccws](url)

**Comment by vspeak** [comment]
we build own sensors.

**Comment by vspeak** [comment]
we use temp2 for lua Status messages

**Comment by 3djc** [comment]
Then you should have a look at what you are sending, because as far as I can tell, it is ok on Opentx  side, as shown above

**Comment by schwabe** [comment]
If that is an sport sensor and not an emulated frsky hub sensor using int16 is wrong anyway. The sensor reports an int32, so s -1 as int16 is correctly displayed as 65535

**Comment by vspeak** [comment]
ok, I'll do. next week I an test also with taranis. with taranis it woks well.

**Comment by 3djc** [comment]
Here with tmp2:

![image](https://user-images.githubusercontent.com/5167938/32268917-24d54d88-bef1-11e7-8992-127ef7853ff4.png)

**Comment by vspeak** [comment]
"The sensor reports an int32, so s -1 as int16 is correctly displayed as 65535"  -->> this can be my issue !! Thank you!

**Comment by vspeak** [comment]
I have checked the SPort data. Now I'm transmitting the correct int32 values -> and **my** problem is solved -> negative temperature values are correct displayed-> **there was no problem on opentx side**.

**Comment by 3djc** [comment]
Good news 👍
