### ISSUE TITLE
N427 X10S Menu icons disappeared, Gimbal read out chaotic. 

### ISSUE THREAD

**Issue by buzzzsam** [opentx/opentx#5324]
Icon disappear.  Gimbal not working.  (values jumping everywhere)

**Comment by kilrah** [comment]
Check your SD card and contents. Post more info. Screenshot, video.,...

**Comment by buzzzsam** [comment]
Formatted 32G FAT32 card with v11 content. 

https://www.youtube.com/watch?v=wwRtg7lkCN0&feature=youtu.be

Same with my friend's unit. 
https://www.facebook.com/groups/rotorriot/permalink/917666715054968/?comment_id=917674201720886&notif_id=1509853034624969&notif_t=group_comment_reply

**Comment by buzzzsam** [comment]
will record more video on youtube later.

**Comment by 3djc** [comment]
Have you run stick calibration ? ,Does it look crazy there too ? Is it always ? Triggered by something ?

**Comment by schwabe** [comment]
that looks like pwm gimbals misdetected as normal analog ones or completely broken calibration

**Comment by buzzzsam** [comment]
I reformated once again, and placed in amber sound file this time.. seems working..  My friend is testing now.. Will see if it works for him with the sound files.

**Comment by buzzzsam** [comment]
I am still getting the shutdown -> emergency error.. I am really suspecting the x10s not liking my 32g sandisk extreme card.

**Comment by 3djc** [comment]
You video has nothing to do with sd cards (content or support),  you should not get jupping channels like that, no matter SD card status

**Comment by schwabe** [comment]
can you make a video of the analogs debug screen? (To see which kind of gimbals you have detected)

**Comment by buzzzsam** [comment]
My tx is now in working state(except the shutdown bug which is extremely annoying).  Will ask my friend to post if it is still happening to him.

**Comment by meoster** [comment]
He still has the problem, can you let him know where the analog debug screen is?

**Comment by meoster** [comment]
By the way, I have a different account on my phone.  Sorry for the confusion.

**Comment by 3djc** [comment]
The shutdown issue is known, so in this thread, let’s focus on the stick issue, if it can be duplicated

**Comment by aiyakim** [comment]
I dont find analog debug screen on my x10s

**Comment by kilrah** [comment]
long press enter on home screen->statistics->3rd page

**Comment by bsongis** [comment]
anybody else has this issue? I can't reproduce

**Comment by meoster** [comment]
My friend and myself seems to have gotten it working after. Don’t know the
reason..

**Comment by kilrah** [comment]
Probably was SD card issue.
