### ISSUE TITLE
LCD type and stick Gain values lost after transfering data to Sky9x board

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5326]
Hi,

i have an T9X+sky9x board+Optrex LCD+Aurora gimbals (OpenTX 2.2.0)

It's OK when i manually set up the screen type and the gain values from the radio, but every time i transfer data from Companion to my TX : those settings are lost.

It may be useless to access those settings from Companion, but keeping them after a transfer would be nice.

![bug_hardware_sky9x](https://user-images.githubusercontent.com/985702/32488025-939adbb6-c3ab-11e7-83a9-ee3a4820f57c.png)

**Comment by schwabe** [comment]
Are you using OpenTX or ersky9x? Your bug title and description are mismatching. 

Note that ersky9x on the radio and OpenTX companion is not going to work.

**Comment by capitaineflam25** [comment]
Sorry for the wrong title, i've changed it.

I confirm i'm using OpenTx firmware : 
![img_1917](https://user-images.githubusercontent.com/985702/32488693-d54321d4-c3ad-11e7-8537-852831d24525.jpg)
