### ISSUE TITLE
Fix simulator switches to match TX

### ISSUE THREAD

**Issue by banditpowdercoat** [opentx/opentx#5331]
The switches are nowhere near what they are on the TX in the Simulator on 2.2  It makes it tough to test edits and just looks plane sloppy to have the switches not the same.

**Comment by 3djc** [comment]
The new system is dynamic and reads your radio data to display the switch actually declared, but cannot know the physical layout of those

**Comment by banditpowdercoat** [comment]
Then how about place the switches in the Sim atleast to how the switches came on the TX from factory.  Both 2 pos switches are not on the right side of TX  One is on each side.

**Comment by kilrah** [comment]
That would bring back the rigidity that prevented custom setups.
Refer to them by name.
