### ISSUE TITLE
Space in a model name and checklist

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5332]
I notices that testing "Companion 2.2.1N430 / 2017-11-08" :

One of my model is named "Quad X"

For the checklist Companion is looking for "Quad X.txt", but firmware is looking for "Quad_X.txt" (With a "_" )

**Comment by kilrah** [comment]
As designed.

EDIT: on firmware, but companion should probably do the same then.

**Comment by capitaineflam25** [comment]
Sorry my description was not very clear but you get it :
the issue maybe on Companion which should replace the " " by a "_" before opening the file.
