### ISSUE TITLE
Allow checklist edit even if not enabled at startup

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5333]
I like the checklist feature but i prefer to display them when i need too, not at startup.

So when i uncheck the "Display checklist" option, i'm not able to use the checklist editor which is sad :yum: : 

![image](https://user-images.githubusercontent.com/985702/32563852-9b0a5a22-c4b2-11e7-9d80-c39fe71b29ca.png)

**Comment by elecpower** [comment]
You can always check the option, edit the checklist and uncheck the option as a workaround

**Comment by kilrah** [comment]
Fixed in https://github.com/opentx/opentx/commit/baa3938f0693c16b4b1eee4a6c6496f75e1dbd15
