### ISSUE TITLE
Limit checklist editor to available caracters

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5334]
I'm a french OpenTx user and accentuated caracters are common.
I don't need to display them on the radio but i regularly forget that they won't display well on it.

Maybe the checklist editor caracters could be limited to a caracter "whitelist" ?

![image](https://user-images.githubusercontent.com/985702/32563964-f1a7bd84-c4b2-11e7-96dc-84ffab3aaa41.png)

![image](https://user-images.githubusercontent.com/985702/32563953-ea249dfc-c4b2-11e7-8088-37faead672bc.png)

**Comment by kilrah** [comment]
You can actually write accented characters through their code (\200, \201 etc) but it' would be a mess to handle it in there.

**Comment by capitaineflam25** [comment]
Thanks for the tip, i didn't know that.
