### ISSUE TITLE
Recent files may be duplicated in Companion

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5336]
This capture has been made with 2017-11-08 nightly build : 

![image](https://user-images.githubusercontent.com/985702/32592124-a8fa8e0c-c522-11e7-826f-cfd8d0829338.png)

**Comment by kilrah** [comment]
Can't reproduce. Aren't those files in different folders?

**Comment by capitaineflam25** [comment]
I found a method to reproduce it (Companion 2.2.1N431) :

- Create a new File
- Save it as "document1.otx"
- Create a model
- Save again
- Close Companion
- Open Companion : "document1.otx" should be duplicate in the recent menu

**Comment by kilrah** [comment]
Nope no issue here with that procedure. Must be something related to your system...

**Comment by capitaineflam25** [comment]
OK

For information here is what i found in my Windows 10 registry : 

![image](https://user-images.githubusercontent.com/985702/32654346-2b007b44-c60b-11e7-9f2c-b95d76bdfbf3.png)

**Comment by capitaineflam25** [comment]
I've installed QT to help on another issue and now i can see what's happening here : 

This is due to QFileInfo that will uppercase drive letters (Source : http://doc.qt.io/qt-5/qfileinfo.html#canonicalFilePath)

If i replace **filename** with **curfile** on the 2 following lines, the issue disappear.

> files.removeAll(curFile);
> files.prepend(curFile);

@kilrah, can you reopen the issue or integrate the patch if you think it's safe ?

![image](https://user-images.githubusercontent.com/985702/33729465-083d0180-db7e-11e7-88ca-f0b7788d1e71.png)
