### ISSUE TITLE
LCD type not saved on Companion (sky9x board)

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5337]
The value doesn't reflect the one on the radio.
You can change it on companion then reopen the dialog immediately, the value is lost.

(It is not crucial to have it on Companion, so if there is two few people using sky9x+optrex, you may remove it from Companion)

![image](https://user-images.githubusercontent.com/985702/32595117-d905ec66-c52e-11e7-9e5a-be1c586ec733.png)

**Comment by kilrah** [comment]
Went with #5326.

**Comment by capitaineflam25** [comment]
I'm not sure it's gone : the screen capture is from this nightly build (i confirm #5326 is fixed with this build)
