### ISSUE TITLE
Some sources mismatch in Mixer screen

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5338]
Using Companion+firmware version 2.2.1N431 (Night build of today : 09-nov-2018) for sky9x board.

THR on radio = RUD on companion (some other sources are OK, maybe there is a value missing in the code resulting in a shift)

![image](https://user-images.githubusercontent.com/985702/32606345-48db799a-c555-11e7-8366-df399d2c4ebc.png)

**Comment by bsongis** [comment]
reproduced

**Comment by capitaineflam25** [comment]
Thanks !
