### ISSUE TITLE
X10S and Crossfire, reciever stay on, but it's not.

### ISSUE THREAD

**Issue by Barbaryann** [opentx/opentx#5340]
Hello guys.

First you all do an amezing job.
Really thank you for all !!!!!

When i use a quad with crossfire, when i unplugged the battery on the quad. My X10S say it is already connected, and if i want to turn off my X10S, it say that the reciever is turn on. But it's not !

It works good with D16 protocol and X4RSB.

If think there is an issue with the crsf protocol on that.

**Comment by schwabe** [comment]
Probablysome telmetry sensors are still sending even if rx is off. Do you get a telemetry lost message when you switch off the RX? You should get at least "Sensor lost"

If not what sensors are still shown as having telemetry (blinkiing * next to them) when the RX is off.

**Comment by 3djc** [comment]
It is checking specificaly for rssi to be 0, which it should be without receivers

**Comment by schwabe** [comment]
might be this
```
--- a/radio/src/telemetry/crossfire.cpp
+++ b/radio/src/telemetry/crossfire.cpp
@@ -153,7 +153,6 @@ void processCrossfireTelemetryFrame()
       break;
 
     case LINK_ID:
-      telemetryStreaming = TELEMETRY_TIMEOUT10ms;
       for (unsigned int i=0; i<=TX_SNR_INDEX; i++) {
         if (getCrossfireTelemetryValue<1>(3+i, value)) {
           if (i == TX_POWER_INDEX) {
@@ -163,6 +162,7 @@ void processCrossfireTelemetryFrame()
           processCrossfireTelemetryValue(i, value);
           if (i == RX_QUALITY_INDEX) {
             telemetryData.rssi.set(value);
+            telemetryStreaming = TELEMETRY_TIMEOUT10ms;
           }
         }
       }
```

**Comment by schwabe** [comment]
I commited this als fix for this. Can you please retest in the next nightly if the problem is fixed?

**Comment by Barbaryann** [comment]
Here a video on this issue :
https://www.youtube.com/watch?v=uOmmxwUaLhI

**Comment by Barbaryann** [comment]
I test next day ;)
Fixed 40mn after the issue is posted.
Woooooo guy you rock !

**Comment by schwabe** [comment]
Btw. while you are at it can you check the telemetry RX error counter under, long press menu on main screen -> statistics -> debug? (with 400k and 100k baud rate)

**Comment by Barbaryann** [comment]
I check it, and confirm it is the same issue than the Q X7 (Shitty frsky !!!!!)
Works great in 100k and Many error in 400k

**Comment by Barbaryann** [comment]
I can confirm you that this is this one we have to replace.
I am waiting the component to try this
![img_0534](https://user-images.githubusercontent.com/17281942/32653980-f1aab6e4-c609-11e7-8974-9b6a8079bc79.JPG)

**Comment by Barbaryann** [comment]
Works well now.
Thanks you very much !
