### ISSUE TITLE
X10s N433  Emergency mode on Power off 

### ISSUE THREAD

**Issue by RoninMedia12** [opentx/opentx#5348]
When I do the long press to power off  it jumps in to emergency mode , If I hode down button again just cycles and powers off for a second then goes back into emergency mode, I must plug it into usb then hold down power so when it is off for that 1/2 sec it connects into stm32bootloader then it will stay off.   On frsky x10s

**Comment by RoninMedia12** [comment]
So after doing some testing  i switched over to darkblue theme and issue went away.  But when i switch back to defualt it returns. I noticed the shutdown squence on the defualt theme is different the. The dark blue not sure if that matters.  I also reflashed n433 and it seemed to go away until i would change something on a model and would start again until i would go to dark blue theme hope this helps

**Comment by 3djc** [comment]
Duplicate #5270
