### ISSUE TITLE
N433 x10s usb joy stick and sd mass storage reversed

### ISSUE THREAD

**Issue by RoninMedia12** [opentx/opentx#5349]
When i flashed the first time seemed to be normal when connecting usb i would select jotstick to play vdrone after reflashing it seems now i have to select sd mass storage to get usb joystick to work. Also to get sd card to appear in windows have to select joystick.  Using dark blue theme.  Tried to read models in companion when selecting sd card  and it fails but if i select joystick can read models.

**Comment by kilrah** [comment]
In that theme the "selected" line is dark, so you're just confusing which one you've selected.
