### ISSUE TITLE
Global Defines not working for UNITS_

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#5352]
I do not believe the UNITS_ are being correctly included in Companion 2.2.0 or 2.2.1N433 for the QX7.
The following script fails with message
-E- luaLoad(/SCRIPTS/TELEMETRY/UnitTs.lua): Error parsing script (2): /SCRIPTS/TELEMETRY/UnitTs.lua:16: bad argument #2 to 'playNumber' (number expected, got nil)
local TITLE = "UNIT_HOURS.lua"	--UnitTs.lua
local function init()
	print (" ****  UnitTs.lua   init()")
end --[[ function init() ]]
local function back()
end --[[ function back() ]]
local function run() 
	lcd.drawText(1,1, TITLE, 0)
	playNumber(2, UNIT_HOURS )
	--print (" **** UNIT_HOURS="..UNIT_HOURS)
	end --[[ function run() ]]
return { init=init, back=back, run=run }

**Comment by 3djc** [comment]
No, those constants are not available to x7, nor x9. They are only for colorscreen, as it takes about 1k of flash to have the telemetry units
