### ISSUE TITLE
Option to mirror CRSF telemetry to the Serial port in the battery tray on Taranis X9D

### ISSUE THREAD

**Issue by oranzs** [opentx/opentx#5357]
Smartport telemetry can be mirrored without a problem. Is it possible to implement the mirroring of CRSF protocol? I might be able to implement the functionality. Where should I start?

**Comment by Amigache** [comment]
It would be interesting for those of us who use antenna tracker, and we use inav, for example.

**Comment by ropalet** [comment]
I have a micro crossfire TX and I can see the telemetry from INAV in my taranis x9d, but it can't mirrored on Smartport telemetry port (serial). Can you implement this functinality?.

**Comment by raul-ortega** [comment]
Hi, I'm also very interested on this implementation. I have realized that for FrSky telemetry is used this block of code to redirect the telemetry (mirrowing):

#if defined(SERIAL2)
  if (g_eeGeneral.serial2Mode == UART_MODE_TELEMETRY_MIRROR) {
    serial2Putc(data);
  }
#endif

Would this block of code solve the problem if it is included in src/telemetry/crossfire.cpp file?

Thanks.

**Comment by fggy-x2** [comment]
I'm in the same situation with the X9D and the crossfire that I can't take the telemetry out,  to use it in the antenna tracker.

**Comment by jgilbertfpv** [comment]
I'm having to forward my crossfire telemetry over bluetooth through a pc connection to my tracker right now, having crossfire support to do away with a pc in the mix would be great.

**Comment by pixelscript** [comment]
For those with a crossfire micro that don't have the option of bluetooth this would be very useful.

**Comment by pixelscript** [comment]
FYI 3djc has put up a build here. I've can verify it's sending data on the TX line of the IO port but not been able to process it to confirm it's working 100%. https://github.com/opentx/opentx/commit/fcd8900cb33bfaff5b14da675dce519831865e93

**Comment by 3djc** [comment]
What you crsf speed ? I suggest trying set to 115k, that build could go further, but I have changed that later on

**Comment by pixelscript** [comment]
Yeah I noticed I had got best results at 115.2k baud. Decoding the signal proved to be beyond my skill set though, looks just like a stream of characters to me. Guessing it needs to be processed in a similar manner to `src/telemetry/crossfire.cpp`.

**Comment by kilrah** [comment]
Yes of course

**Comment by pixelscript** [comment]
FYI I've been using the changes from [here](https://github.com/opentx/opentx/compare/3djc/crossfire-telem-mirror), with it working well.

**Comment by RomanFoltyn** [comment]
Hallo
I am very interested in the possibility of using CROSSFIRE CRSF to receive GPS Position and Altitude via the serial output x9D plus. I am just starting construction of u360 Tracker and it is extremely important to me.
Thanks. (Maybe there is a beta version with this feature?)
Roman
PS Greetings to Raul Ortega!

**Comment by 3djc** [comment]
I have merged the changes into 2.2 branch, which means that tomorows nightly will have that change. We are usually strongly advising against use of  nightlies. It this particular case, all change work is happening on 2.3 branch, so 2.2.4 nightlies should be safe to fly, but please make thourought test on the ground first

**Comment by RomanFoltyn** [comment]
yesterday evening I uploaded 2.2.4 to my x9D Plus but this version does not send the signal through the port:
when the CRSF Telemetry works correctly in the S-Port Mittor Position, the port is constantly Low, Telemetry is constantly High, and the S-Bus position is always High.

But that was yesterday. Please enter what versions I should load

.I will wait until tomorrow and carry out the test again!
Thank you very much

**Comment by RomanFoltyn** [comment]
Hallo 3jdc!

Unfortunately, the size of the compiled file is 0 Byte. 
I can not convince the computer to open it. ;)
best regards!
Roman DL6NBF

**Comment by RomanFoltyn** [comment]
companion-windows-2.2.4N695.exe                    16-Apr-2019 05:30            13816876
companion-windows-2.2.4N696.exe                    16-May-2019 05:25                   0

**Comment by 3djc** [comment]
You can use yesterday companion to downloads todays firmware

**Comment by shannonbaker** [comment]
What's needed to update taranis x9d+ to 2.2.4 to get crsf mirror available? I can't find a compiled 2.2.4. Do I need to figure out how to compile on my own or is there something pre-made?

**Comment by 3djc** [comment]
You need to get 2.2.4 nightlies. Get companion from here  https://downloads.open-tx.org/2.2/nightlies/companion/ and then the firmware relevant to your radio (obvisouly with crossfire enabled)

**Comment by shannonbaker** [comment]
When you say 'and then the firmware relevant to your radio', is it that the companion software creates the firmware to install or do I need to get firmware from somewhere else?

**Comment by 3djc** [comment]
Your need in companion nightly linked above to select nightly firmwares (settings/settings/Application setting/Use nightly builds). You then need to setup you radio profile according to your radio and liking. You can then a firmware using file/download

**Comment by shannonbaker** [comment]
Thanks. I' can't see anything related to CrossFire in the hardware serial screen on taranis after writing the new firmware and the 2.2 SD contents. I confirm that the nightly build splash screen Cobbs up when powering on the taranis. Is there something I'm missing?

**Comment by 3djc** [comment]
Have you set your serial port to 'S.Port mirror' ? (We need to change that name)

**Comment by Saxin** [comment]
Everything is set (N2.2.4) and wired correctly - checked with R9 module, I'm wired to battery bay uart via inverter, set BT module to 115200,0,0 ...
Tried SmartPort telemetry viewer app nothing shows sadly - I'm not sure if it's the app or something else 
Any advise how this can be validated working ?

**Comment by kilrah** [comment]
What app is it?

**Comment by Saxin** [comment]
@kilrah 
This one - https://github.com/CrazyDude1994/android-taranis-smartport-telemetry, 
If you know some other way to validate it's working I would be very happy to hear, thanks.

**Comment by kilrah** [comment]
Several things:
- This issue is about crossfire
- The S. Port mirror is used for internal, and may not be enabled with an external R9 since that's got its own plug you can connect to already.

**Comment by Saxin** [comment]
@kilrah  

**" This issue is about crossfire"**
I'm using CF micro (R9 was used just to validate hardware is ok, inverter, BEC and BT module)


**"The S. Port mirror is used for internal, and may not be enabled with an external R9 since that's got its own plug you can connect to already"** 
I know I've connected to internal / battery bay UART and it works nicely with R9, I prefer the BT hidden inside battery bay.

Hope to somehow validate that crossfire sensors  / telemetry is being sent out ?

**Comment by 3djc** [comment]
This app looks like it is expecting smart port telem, does it know how to decode crossfire streams ?

**Comment by kilrah** [comment]
What are you expecting to do with the crossfire stream? Just like for S-Port the crossfire stream is passed along as received from the module without any processing or conversion, so you need an app that decodes crossfire stream. I don't know of any. If you want to validate you'd want to connect a suitable serial adapter and check that you receive something and that it matches the crossfire telemetry format.

**Comment by Saxin** [comment]
@3djc - I guess it doesn't, I was mistakenly under impression that internally in openTX all sensors are "converted" to smart port type and hence can be mirrored.

@kilrah  - I have x2 use cases, one is ground station display using some app able to decode CF tel. stream; second one is sending mostly GPS sensor to x2 trackers for video and control antennas.

**Comment by putimir** [comment]
Hello all, I don't know where exactly to ask so: is this mirror possible to be directed to the "internal" BT module of the Horus family?

**Comment by skaman82** [comment]
I am interested in this as well. I am using crossfire an would like to connect to an app via BT by mirroring Taranis telemetry via Serial Port @ 57600 baud. No app I have tried is working. Any tipps?

**Comment by kilrah** [comment]
AFAIK there is no app that supports Crossfire telemetry.

**Comment by pixelscript** [comment]
Thought I'd just leave this here. This is the web app I had started building a while back, it's no where near finished and might be in a broken state but if the code is of use to anyone have at it.

https://github.com/pixelscript/telemetry-reader

**Comment by avsaase** [comment]
Was this option removed? I cannot find it anywhere on my X9D Plus 2019 (non-SE) on 2.3.3. As far as I can tell no telemetry is output on the S-port pin in the battery bay.

**Comment by 3djc** [comment]
If I remember correctly, it is using a uart output, and none is available on 2019 version of x9d

**Comment by avsaase** [comment]
Ah, that would be a bummer. Was hoping to get crossfire telemetry into the Telemetry Viewer Android app.

**Comment by avsaase** [comment]
I may buy another transmitter to get this to work. Does the TX16S support this feature already?

**Comment by 3djc** [comment]
Yes, you can output this on one of the two bottom uarts

**Comment by avsaase** [comment]
Could I make a feature request to to support mirroring the telemetry to the Smartport on the 2019 edition? Or is this a hardware limitation?

**Comment by 3djc** [comment]
hardware limitation

**Comment by avsaase** [comment]
Okay. Thank for your help.
