### ISSUE TITLE
[LUA/X10] drawing text with y>LCD_H crashes the TX

### ISSUE THREAD

**Issue by raphaelcoeffic** [opentx/opentx#5359]
Executing this script on the X10 will crash (emergency mode) the TX:
```
local function run_func()
  lcd.drawText(1,260,"Hello")
end

return { run=run_func }
```

**Comment by raphaelcoeffic** [comment]
sorry gentlemen, I'm just too sleepy to fix that today...

**Comment by raphaelcoeffic** [comment]
Forgot to tell: I'm using 2.2.1N433.

**Comment by 3djc** [comment]
Yes, we are aware of that. We have a plan to better protect the screen buffer from overwrite (not only using lua), but it is a significant task to do it properly;. @projectkk2glider is working on that

**Comment by raphaelcoeffic** [comment]
@3djc great, thx! I'll just have to be careful then.

**Comment by projectkk2glider** [comment]
Duplicate of #5056
