### ISSUE TITLE
Timer value limited to 1275 on Companion telemetry screen configure tab

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5362]
Companion/Firmware 2.2.1N434 / Taranis X7 

Timer value limited to 1275 (1 unit = 20 ms so it is 4:15) whereas on the radio we can set it to 10:00 or 20:00

![image](https://user-images.githubusercontent.com/985702/32798523-41356092-c975-11e7-8062-1c6fd15612e0.png)

**Comment by kilrah** [comment]
Radio type maybe? Version?

Can't reproduce.

**Comment by capitaineflam25** [comment]
Companion 2.2.1N434 / Taranis X7

How i get the issue : 
- Create a new model
- Edit it
- Go to Telemetry tab
- Telemetry Screen 1 / Bars
- Select "Timer1
- Try to enter "6000" with the keyboard -> you should not be allowed to
- You can enter 999 and press "+" to enter something higher than 1275

**Comment by kilrah** [comment]
Works here up to the allowed 1275.

![clipboard01](https://user-images.githubusercontent.com/6065069/32795050-ecf149ce-c96a-11e7-94b8-55177f0ad4d6.jpg)

**Comment by capitaineflam25** [comment]
You're right, my mistake.

The "problem" (maybe it's not one) is elsewhere : 

On my radio i can setup a higher limit for the timer bar of "20:00" (which should be 6000 in raw value, as 1 unit (on Companion) is 20 ms of the timer)

So when reading back my radio settings to Companion, the value is truncated to 1275

**Comment by capitaineflam25** [comment]
Should i open a new issue/enhancement for that ?

**Comment by kilrah** [comment]
Just rename this one and clarify the first post.

**Comment by capitaineflam25** [comment]
Thanks
