### ISSUE TITLE
Bars upper limit maybe aligned right (or shifted one caracter left)

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5363]
Using 2.2.1N434 for Taranis X7

On the DISPLAY tab of a model, when the right value exceed 4 caracters (Voltage > 10V or timer) the last caracter is out of the screen.

For the voltage losing the unit is no big deal of course, for the timer you don't know what is the last seconds digit.

![image](https://user-images.githubusercontent.com/985702/32797073-e6aef0c4-c970-11e7-8e90-293c2723ee53.png)

**Comment by 3djc** [comment]
A PR for that as already been submitted
