### ISSUE TITLE
Model name not played when simulator launched from "Simulate model" menu

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5370]
Companion 2.2.1N435 Taranis X7

When clicking "Simulate Radio", the default model name is played if exists -> OK

When lauching a non default model from the contextual menu : "Simulate model", the wav is not played.
(If i do a "Set as default" + "Simulate radio", the wav is played)

![image](https://user-images.githubusercontent.com/985702/32829470-7e694c76-c9f2-11e7-971a-749a9b9f84b3.png)

**Comment by kilrah** [comment]
Intentional, all startup checks are skipped when launched this way to avoid obnoxious calls and warnings when launching it repeatedly while adjusting stuff.
