### ISSUE TITLE
Flexible storage model

### ISSUE THREAD

**Issue by raphaelcoeffic** [opentx/opentx#5372]
The idea here is to make the config storage flexible, so that new options can be added without having to convert everything.

Some requirements out of the top of my head:
 - should stay binary as the storage space is tight.
 - should allow new features without eeprom format change

Anything else?

Some folks think that JSON would be good, @bsongis even has a draft prototype. Some other think that we should stick to binary to be able to support all the TXs. Maybe we could have something that can be serialized in different ways, depending on the TX (different codes for the same thing makes it harder to maintain however).

**Comment by raphaelcoeffic** [comment]
@tadango @kilrah @bsongis @3djc  please feel free to comment and add your ideas. The sooner we have a consensus, the sooner I/we can start implementing it.

**Comment by RealTadango** [comment]
What is the difference between binary and JSON? It's all just a bunch of bits. A small size is important so don't store values matching default. JSON is great for that but long and repeated variable names take up a lot of space. I don't see a simple solution for that right away.....

**Comment by bsongis** [comment]
I already have 2 branches with this work in mind, one with JSON, the other with YAML
All the libs I found use too many malloc and I would like to find time to rewrite something from scratch, without one malloc. This would allow us to use this storage method on Taranis as well.
Do you want to give me an hand with this work?

**Comment by raphaelcoeffic** [comment]
@bsongis I can try to! To do it properly without malloc will basically mean calling some functions while parsing that will deal with the objects, so that you do not need to store anything. So basically some kind of streaming parser? I happen to use JSON a lot for my work, but the other one would be fine as well.

**Comment by schwabe** [comment]
Or just generate a generate a parser that does not need memory since it directly sotres the information inside the structs.

**Comment by raphaelcoeffic** [comment]
@schwabe you mean inside the memory structs for settings? Well, basically means the parser only streams the payload and calls function pointers instead of storing any data itself and passing them for later analysis.

**Comment by 3djc** [comment]
Unless most of the code is rewritten, the data needs to be written in the current data structs, have a look in https://github.com/opentx/opentx/blob/2.2/radio/src/datastructs.h.

So in essence, data need to be read from JSON/YAML and put in the struct for model loading, and the other way arround for saving. But all the radio are different, so the receipees will be complex

**Comment by raphaelcoeffic** [comment]
Ok, YAML is being worked on currently, please stay tuned for more.

**Comment by raphaelcoeffic** [comment]
I meant dices, of course ;-)

**Comment by raphaelcoeffic** [comment]
I'd prefer JSON to be able to get rid of all these spaces and mandatory new lines. And I think json is easier to parse.

**Comment by RealTadango** [comment]
Reply to keep it active ;)

**Comment by raphaelcoeffic** [comment]
@RealTadango coming in 2.4 :-) Radio code for Horus already works, have a look at the PR.

**Comment by RealTadango** [comment]
Keeping the issue alive :)

**Comment by lshems** [comment]
Yep

**Comment by RealTadango** [comment]
Keeping the issue alive :)

**Comment by raphaelcoeffic** [comment]
This is already merged into 2.4, and will be finished in EdgeTx.
