### ISSUE TITLE
Decimal entry is difficult in V2 / Logical Switches

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5375]
Companion 2.2.1N436 / Taranis X7

Language of the test computer is French (decimal separator is ",")

- Add a Volt telemetry sensor, name it A1, with precision 1
- Go to logical Switches and add a line
- Select "a<x", then "TELE1:A1"
- Select v2 content so you can replace it
- Type 12,1 with the keyboard you should get "12,0 V"

There is no issue with other decimal fields, it may be linked to the presence of the unit ? (The unit is refreshed after each keypress)

(This is a cosmetic issue, you can then select the value after the coma and replace it)

![image](https://user-images.githubusercontent.com/985702/32894837-5ca20af0-cade-11e7-9b0d-53da39849303.png)

**Comment by kilrah** [comment]
That's just the way the doublespinbox works in Qt.

**Comment by capitaineflam25** [comment]
I don't know if the "Duration" field is based on the same doublespin box.
The issue is not reproduced on it.
I was wondering if the "bad" behaviour was due to the unit append at the end of the value.

![image](https://user-images.githubusercontent.com/985702/32990139-4dadca96-cd24-11e7-8aca-653de5c0a5ad.png)

**Comment by kilrah** [comment]
Ah no, it's much more complex than that - since the values and steps that may be stored in an LS may not match what can be entered in the V2 box everytime that's edited we have to convert the value to what can be stored, then set the box back to the actual value. That overwrites what you just typed and cancels editing.

I don't see a way to improve that with reasonable complexity.

**Comment by capitaineflam25** [comment]
Ok thanks for the explanation.
It maybe better to leave it as is.
I let you decide if you prefer leaving the suggestion open or closed.

**Comment by capitaineflam25** [comment]
Thanks a lot, the new editor is way better !
