### ISSUE TITLE
9X - OpenTX compiles but will not run after power cycling

### ISSUE THREAD

**Issue by danyocom** [opentx/opentx#5380]
I have tried building Open TX for the Turnigy 9x using both OSX and Linux (and various versions of avrgcc). I am able to compile successfully and after flashing everything appears to be ok until I perform a power cycle (turn switch off/on). Instead of turning on, the backlight flashes for a second and nothing happens. 

What OS/gcc version/settings are used to compile the firmware that is distributed for the 9x via the companion app?

Is the power cycling issue an know problem?

**Comment by 3djc** [comment]
Please refer to the wiki : https://github.com/opentx/opentx/wiki/OpenTX-2.2-OSX-Build-Instructions.

You can probably get some support on you rocket.chat channel too

Closing this as this is not a OpenTx bug per say
