### ISSUE TITLE
X10 and crossfire mod, statistics error again

### ISSUE THREAD

**Issue by Barbaryann** [opentx/opentx#5381]
Hello
I make the mod of my X10 like the Q X7.
It works better now, crossfire lua works great in 400k...
But in statistics mod, i have some error. Something like 1 every 4 or 5 seconds...
It is much better than the thousands every minute before but !
Is it wrong ? What type of error is it ?
Thanks

**Comment by 3djc** [comment]
Do you get error at 100k ?

**Comment by Barbaryann** [comment]
No

**Comment by 3djc** [comment]
Then it means that even with your mod, your connection is not perfect at 400k

**Comment by Barbaryann** [comment]
Not good 😕
