### ISSUE TITLE
Horus X10 - Telemtry page for Lua script

### ISSUE THREAD

**Issue by Barbaryann** [opentx/opentx#5383]
Hello,
I don't find any thing to open a lua script in a telemetry screen like on the X9D+ for exemple.
The only way i find is to go into the SD card and execute manualy the Lua Script.
I am wrong  or not ?
And is it possible to make something for that ?
Thanks a lot for all your job to OpenTX team

**Comment by kilrah** [comment]
There are no telemetry scripts on Horus, you have widgets instead.

Please keep usage questions on forums or in the chat, not in the bug tracker.

**Comment by Barbaryann** [comment]
I ask why there is not he same way than on the tarais, Because widget don't do PID for Betaflight...

**Comment by kilrah** [comment]
Becasue the whole interface system is different. Someone can port the telemetry script as a widget.

**Comment by Barbaryann** [comment]
Is it possible ? It would be awesome.
where to ask this ?

**Comment by kilrah** [comment]
You can try whoever wrote the script you'd like ported.

**Comment by lshems** [comment]
Check my blog on rcgroups. Its shows the porting of an existing telemetry script to a widget. Not saying it is thé solution, but at least it gives an idea on a possible approach.

L shems
