### ISSUE TITLE
telemetry looses connection

### ISSUE THREAD

**Issue by patman13** [opentx/opentx#5399]
Horus X10 with 2.2.1N438
when using internal antennas then telemetry looses connection every two seconds and the reestablishes connection.
When switching to external antenna and back to internal antenna it works fine.

**Comment by kilrah** [comment]
Do you have an external module installed?

**Comment by patman13** [comment]
No. Internal module only.

**Comment by kilrah** [comment]
No idea how it could have anything to do with us then.

**Comment by trojanGoat** [comment]
If you're too close to your model this can happen.  Try standing a few meters away and see if the telemetry still cuts in and out.

**Comment by 3djc** [comment]
How does it behave with frtx ?

**Comment by patman13** [comment]
Tried with Taranis. Same effect. Seems to be a faulty receiver.
Sorry!
