### ISSUE TITLE
Feature request: easy servo setup

### ISSUE THREAD

**Issue by patman13** [opentx/opentx#5400]
I'm coming from Multiplex. Maybe you could put this on the feature wish list.

When modifing Servo values (min, max, center) the values are sent to the receiver. So no extra input at the sticks are necessary to set up the servos. Hands free for set up the mechanic (e.g. plane: rudder linkage).

**Comment by patman13** [comment]
one more detail:
the value you are editing (the blinking one) shall be written to output

**Comment by kilrah** [comment]
There needs a way to enable that, like holding the MENU key during editing or something for safety... but yes the idea is nice.

**Comment by RCdiy** [comment]
Example to consider. 
At 1000us the servo is well past the binding point. 
Moving sticks we can see the problem and stop. 
If we edit lower limit which defaults to -512 then we have severe binding immediately on editing that value. 

Good idea but make it optional with default off.

**Comment by kilrah** [comment]
That's why I said what I said. 
Set limit back to like 50% first, and only then hold the "enable" button and increase value to find the right one.
