### ISSUE TITLE
Companion 2.2.1 build 440: UI bug during eeprom translation from X9D to QX7

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#5402]
The problem arises in Companion 2.2.1 (latest nightly build) after translating a model to QX7 format. If the model contains a mix with a source which is not supported by the QX7 (e.g. 'LS') then opening the mixer editor may cause subsequent mixers to dissappear.

Minimalist .otx file for the X9D is available [here](https://www.dropbox.com/s/3rj7bhe9um4jdgw/UI_Bug.otx?dl=0).

To reproduce the problem

1. Set the Companion profile to QX7
2. Open the X9D .otx. Data is translated in situ
3. Locate the 'LS' mixer line, and open the mixer editor

- If you change the source from 'LS' to a valid control for the QX7, there's no problem.
- However, if you press OK without changing to a valid source, all subsequent mixers are deleted.

**Comment by bsongis** [comment]
I will take it.

**Comment by bsongis** [comment]
Reproduced. Thanks for the good explanation + the minimalist .otx, half work is already done!

**Comment by RC-SOAR** [comment]
Many thanks :-)
