### ISSUE TITLE
Feature Request:  Turn off screen on Horus X10

### ISSUE THREAD

**Issue by trojanGoat** [opentx/opentx#5403]
The original frOS was able to turn off the screen.  Can we get a feature to completely turn off the screen.

Thanks.

**Comment by raphaelcoeffic** [comment]
As far as I've been explained, this is a matter of letting the backlight go dark. At the moment, the "off brightness" goes only as low as around 46%. For that, it would have to go all the way down to zero. Please look at #5422 for some more details.

**Comment by lindongy** [comment]
see my repo.
