### ISSUE TITLE
SH switch is not corrected converted in Companion from X9D+ to QX7

### ISSUE THREAD

**Issue by pacogalvan** [opentx/opentx#5410]
SH is the same switch in X9D+ and QX7 transmiter.
 Any eepe or otx file in X9D+ file with SH switches is not converter to QX7 correctly in Companion un Mixed or Logical Switchs.
This switch always appears as --- in the line.

**Comment by kilrah** [comment]
Duplicate

**Comment by pacogalvan** [comment]
You are right, I have a problem with my browser.
