### ISSUE TITLE
X9E Operation Time Reset

### ISSUE THREAD

**Issue by bosshog99** [opentx/opentx#5412]
Hello,

I'm running version 2.2.0 on a Taranis X9E and no longer have the option to reset the timer on the color display.  I like to reset this timer each time my transmitter battery is recharged to track it's performance.

thanks,

**Comment by 3djc** [comment]
X9E ? Color display ?

**Comment by kilrah** [comment]
The top display. Long MENU on statistics page, still there.

**Comment by bosshog99** [comment]
Yes, the color display.  it is there but, what i was asking, I cannot reset the operation time.  this is the timer on the color display. before 2.2.0 this timer was reset in the status menu.  now the timer shows up in the status menu but the timer cannot be reset.

**Comment by kilrah** [comment]
Don't know about 2.2.0 but tested working on the soon to be released 2.2.1 so update to that once it's out.

**Comment by 3djc** [comment]
Yes, I fixed that a while back
