### ISSUE TITLE
x10 N443 6 position switch does change on bottom of screen stays on position 1 after transfering models

### ISSUE THREAD

**Issue by Crunch69** [opentx/opentx#5413]
x10 N443 N441 and N442 English  6 position switch does change on bottom of screen stays on position 1 in both default and blue theme.   6 position sw does show movement in widget

If sd is loaded stock and radio is reflashed 6 position works when I load models from x7 convert into radio 6 position pot no longer shows position on the main screen but shows movement if I put it on the top bar widget

**Comment by 3djc** [comment]
Would you mind giving the basic information : radio type, opentx version,...

**Comment by Crunch69** [comment]
...
