### ISSUE TITLE
name.wav played on startup not played on model change.

### ISSUE THREAD

**Issue by Mow06** [opentx/opentx#5414]
X9D 2.2.1N441
Turn on tx - name wave of currently selected file plays.
Select different model - name.wav for that model doesn't play. Turn off TX and turn on - that name.wav then plays.

**Comment by 3djc** [comment]
Likely a consequence of #5350

**Comment by capitaineflam25** [comment]
Will it fix issue #5370 ?

**Comment by kilrah** [comment]
#5370 behavior is intentional as you were told.
