### ISSUE TITLE
Off brightness slider has no effect on Frsky X10S

### ISSUE THREAD

**Issue by putimir** [opentx/opentx#5422]
I noticed this issue quite some builds ago, but didn't put much thought into it, I thought it was may a temporary "glitch", but it persists, and since the 2.2.1 milestone is around the corner, I thought I should report this.

So as the subject states, the "off brightness" seems to have no effect on the actual brightness; I remember that in the versions around 40x, if I set the slider all the way to the left, the display had almost zero backlight, but now I think there is no difference between on and off brightness... also I think that the brightness range is much smaller for the on brightness (in a way you could say that brightness cannot be lowered to zero in either mode)...

Does anyone else have this problem?

**Comment by raphaelcoeffic** [comment]
@putimir I think that's more or less engineered this way. I've been told that there were display glitches when the brightness would go bellow a certain value, which has now been deemed as the minimum allowed.

**Comment by putimir** [comment]
Ok, but the fact is, that the setting was working beautifully on earlier versions - it did dim out almost completely, at least on my X10s; my question is why was this removed...

**Comment by raphaelcoeffic** [comment]
@putimir it wasn't me ;-) no clue what's behind that decision, really. I heard there were some gliches on the screen or something like that....

**Comment by putimir** [comment]
👍 

Ok, too bad, since it's most waste of battery juice hehe. Thanks and sorry for opening this, I could have researched more beforehand...

**Comment by trojanGoat** [comment]
@putimir,  let me know if you end up finding a solution for this.  I was also inquiring about the same issue.  The frOS seems to be able to do it.

**Comment by s700ky** [comment]
You cannot set brightness levels in GV for backlight to a pot on X10
