### ISSUE TITLE
Feature Request: Custom Splash Screen for Horus X10

### ISSUE THREAD

**Issue by trojanGoat** [opentx/opentx#5434]
I don't see options for using custom splash screens for Horus X10 when powering up the radio.

https://imgur.com/a/vJYeH

**Comment by raphaelcoeffic** [comment]
Yep, I'd really prefer to have custom splash images being just stored on the SD card, so the process is way easier:
- no need to patch the firmware on the fly
- automatically there when flashing a new version.

**Comment by commonspace** [comment]
Bump. 
Is this feature going to be added?

**Comment by 3djc** [comment]
Will be in 2.2.2

**Comment by R3M1X972** [comment]
Hi guys, anyone got news on this feature ? I still can see the "edit splash screen" button when connecting my Horus X12S to Companion 2.2.2 freshly updated, but the button is grey and can't be used, any ideas ?

**Comment by 3djc** [comment]
maybe you could read 2.2.2 release notes

**Comment by raphaelcoeffic** [comment]
@R3M1X972 you can now select a splash screen directly in the SD explorer. Just click on a PNG image, and it will appear in the context menu.

**Comment by R3M1X972** [comment]
@raphaelcoeffic & @3djc : thanks guys. However I did created a splash.png and placed it in the SD as suggested in release notes (/IMAGES/splash.png). I can see the file displaying when navigating through the menu but for some reason it doesn't shows up on Horus start (OpenTx screen is still showing up instead)... did I miss something again ?

**Comment by raphaelcoeffic** [comment]
@R3M1X972 you are using 2.2.2, right?

**Comment by R3M1X972** [comment]
@raphaelcoeffic yes, indeed, I'm on 2.2.2. could png image size be the solution?

**Comment by kilrah** [comment]
It must be the the right size for the screen or smaller.

**Comment by raphaelcoeffic** [comment]
@kilrah in fact no, it will work with bigger images, will just get cropped.

**Comment by R3M1X972** [comment]
Dammit, I'm sure i'm missing something but can't figure what it is. Created the splash.png in 3 different sizes and placed it subsequently in the above mentionned folder, but still I'm getting the "opentx" logo when powering up the Horus :-/ 
Should you have any idea it'll be really appreciated ! 👍

**Comment by raphaelcoeffic** [comment]
@R3M1X972 could you please come to our chat (chat.open-tx.org) and post me your image?

**Comment by R3M1X972** [comment]
Hi all - my issue is now solved thanks to the help received from @raphaelcoeffic & @kilrah ! thanks guys.

**Comment by splenkingforth** [comment]
Hi 
Could you please share the solution that you found?
Many thanks

**Comment by R3M1X972** [comment]
Hi @splenkingforth
Solution found was to create a png named "splash.png" into the "image" folder of the SD card and redo the update of firmware. However for some reason on my Horus, the custom splash only works with a 480 × 272 file, meaning mine seems unable to resize a bigger image.
