### ISSUE TITLE
[Feature request] Option to boot directly to certain default model

### ISSUE THREAD

**Issue by emski0** [opentx/opentx#5452]
Hi,
 the reason for this feature:
i have my main model working with Tbs crossfire tx module in the taranis.
And i have different other quads on SBUS using the internal XJT.

Since we should not power the TX without antenna, i need each time to screw the tbs antenna, power on, change to an internal module.
Is it possible to choose a model as default boot model(1 model working with internal XJT), so that i can power the taranis without having to screw the antenna for the external module each time when powering.
Thanks

**Comment by geofrancis** [comment]
Perhaps this should be called "confirm antenna connected before powering external module"

**Comment by geofrancis** [comment]
Perhaps this should be called "confirm antenna connected before powering external module"

Graupner radios do something similar where they won't transmit untill you hit ok on the screen.
