### ISSUE TITLE
Horus and X12 (n452)  Companion display no data in Inputs & Mixer screens

### ISSUE THREAD

**Issue by coaster007** [opentx/opentx#5460]
Hi
Companion 2.2.1 (452), no data displayed in the Input and Mixer Screens, the other screens are o.k.
No problems with Companion 2.2.0

![companion_2 2 0](https://user-images.githubusercontent.com/34204590/33523426-9b63fc4a-d807-11e7-9e56-8895407e64ec.png)
![companion_2 2 1_452](https://user-images.githubusercontent.com/34204590/33523427-a12a4ddc-d807-11e7-84b7-2bb3a5af77c9.png)

OS: Linux Mint 18.1
QT-Version 5.6.1

**Comment by 3djc** [comment]
Could you please supply the otx file ?

**Comment by coaster007** [comment]
[x10.otx.zip](https://github.com/opentx/opentx/files/1524579/x10.otx.zip)

**Comment by 3djc** [comment]
Just tested on Debian and official N452:

![image](https://user-images.githubusercontent.com/5167938/33523905-28776946-d812-11e7-800a-7bcd05a8bcbe.png)

Your compilation chain must have issues (please note that we are buildong with Qt  5.7.1)

**Comment by coaster007** [comment]
o.k., but i have not compiled the app, just downloaded and installed the deb package form Linux nightly builds.

**Comment by 3djc** [comment]
I did the same for this test. There seems to be something on your end creating the issue, I would update your QT install to 5.7.1

**Comment by coaster007** [comment]
Hi,
i don't now how to update the runtime qt version. after some searches with google i came to the conclusion it's to complicated for me (i am a simple user ;-) ).
Nevermind i can use my mac there is no problem with N452.

tnx and greetings
Graziano

**Comment by 3djc** [comment]
OK, closing then :)
