### ISSUE TITLE
[Companion] Print model enhancements

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#5462]
There are many fields that are currently not included in the model report. Most notably for general settings and telemetry.

**Comment by kilrah** [comment]
Maybe do a little search and add the references, as far as I know there is quite a number of issues open related to this...

**Comment by elecpower** [comment]
@kilrah yep that was my intention as I addressed with the PR(s). Previous searches found them going back years and part of other Issues. First priority was to flag I was taking up the challenge.

**Comment by 3djc** [comment]
👍
