### ISSUE TITLE
Shouldn't the 2.2.1 Companion be showing the 2.2.1 firmware?

### ISSUE THREAD

**Issue by ftherrmann** [opentx/opentx#5464]
![24799602_2409752009249157_5035057964631991057_o](https://user-images.githubusercontent.com/9029569/33564015-18d95198-d8df-11e7-8a14-a6373b30fdab.jpg)

Here's my win companion screen for the 2.2.1 companion I just downloaded.  Does not look correct.

**Comment by 3djc** [comment]
Please review the release notes, specialy the very first point highlighted in Warnings.

http://www.open-tx.org/2017/12/04/opentx-2.2.1RC1

**Comment by kilrah** [comment]
Release notes won't be put in here until final 2.2.1. Still RC at this point.
