### ISSUE TITLE
Timer display in telemetry screen on a X9D+

### ISSUE THREAD

**Issue by Kennlicht** [opentx/opentx#5467]
Using the new RC1 of OpenTX 2.2.1, I've defined two timers an they are displayed on the main screen as they should:
![screenshot_x9d _17-12-05_12-00-42](https://user-images.githubusercontent.com/29534157/33603834-2e5a67c0-d9b4-11e7-983c-d82153ee82b8.png)

But please have a look at the telemetry screen:
![screenshot_x9d _17-12-05_12-01-02](https://user-images.githubusercontent.com/29534157/33603876-51170fa2-d9b4-11e7-917b-03139acae8be.png)

I'm not able to see the minutes of both timers, The text is too long. Even if I shorten the text, the numbers aren't shown correctly. That is the case in the simulator an on my radio.

**Comment by mpaperno** [comment]
There's no way to fit two custom-named timers in that line and still keep model name and volts the same size.  It's frustratingly close, but just doesn't look good... I tried.  Some options:
* Show up to 3 timers with generic names (`T#` or `Tmr#`).
* If the first one has custom name, then only show that one.
* Reduce font size on model name (would be same size as the timer names). Would still be a bit tight, but should work.
* ....?

**Comment by Kennlicht** [comment]
I would prefer option 1.

The full name of all timers is already displayed on the main screen. The telemetry screen should display Tht, Ths or Th% or T1, T2, T3, ... Or whatever fits.
