### ISSUE TITLE
 No option for setting failsafe for Multi AFDS2A on 2.2.1 rc1

### ISSUE THREAD

**Issue by fabioeh** [opentx/opentx#5470]
On Companion and QX7 there is no option to set failsafe values on Multi AFDS2A. The settings only show on the internal module.

![multi](https://user-images.githubusercontent.com/34279049/33673506-c375e7a0-da61-11e7-8460-50f6627c1bbe.jpeg)

2.1.1 rc1 Feature

Multi: allow syncing multi output with Multimodule radio frames (reduces latency) and allow setting failsafe for AFDS2A, requires experimental Multi code

**Comment by 3djc** [comment]
Likely only from radio

**Comment by fabioeh** [comment]
Not on the radio as well.
The Q7 has no failsafe option under external multi

**Comment by 3djc** [comment]
That is an issue indeed
