### ISSUE TITLE
Add the ability to see Logical Switches (LS) 33-64 from the main view screen. XD9+

### ISSUE THREAD

**Issue by Kennamer** [opentx/opentx#5476]
Taranis X9D+

On the 3rd page of the main view screen (the Logical Switches screen), only switches 1-32 are visible (LS 1-32).

It seems intuitive that by pressing the + key, you would then see 'page 2' of the logical switches: LS 33-64, just like how the Channel Monitor screen operates.

Can this be made to happen?

Thank you.

**Comment by Kennamer** [comment]
Hello mpaperno,

This was my first experience posting on here and I have to say I am impressed! Addressed and fixed in less than 24 hours! Thank you.

I just have a small additional request: Can you make the first page read LS 01-32 (adding the zero to the one). It will make the characters stay in the same place on the screen when switching pages and also corresponds with the actual numbering of the Logical Switches (01, 02, etc.). It is just for aesthetics, but thought I'd ask since all you (probably) have to do is add a zero. ;-)

Thanks again for the quick fix!

**Comment by Kennamer** [comment]
Looks great! Really blown away at how fast it was all handled.

Thank you! 

I suppose I close this thread now, so here it goes...

**Comment by 3djc** [comment]
Thread will be automaticaly closed if/when the correction gets into OpenTx
