### ISSUE TITLE
[X10] LS & RS controls mismatch between Companion and firmware

### ISSUE THREAD

**Issue by x10user** [opentx/opentx#5488]
On my X10 I assigned the RS for volume control. After reading the TX settings to Companion the parameter for volume control was not transferred.
![image](https://user-images.githubusercontent.com/33264007/33795196-61412238-dcdd-11e7-88df-c4ec1d79ec28.png)

I tested it also the other way. If the parameter is set to RS in companion volume control works on the TX (after writing settings to the TX), but in reverse (down make it louder).
Nevertheless, the Parameter-field for volume on the TX is empty. After re-assign RS the volume control works as expected (RS up for volume up).

OTX-file for reference:
[FrSky X10.zip](https://github.com/opentx/opentx/files/1544627/FrSky.X10.zip)

**Comment by x10user** [comment]
The issue was observed for a while, latest build tested: N457 (both on Companion and TX)

**Comment by mpaperno** [comment]
Turns out the X10 LS and RS analogs are being handled differently in firmware vs. Companion, so this is the underlying issue.  Companion thinks X10 has L1/L2 sliders.  Under further investigation now.
