### ISSUE TITLE
Add "View notes" on telemetry screens menu

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5489]
Would you see an interest in showing the "View notes" from the telemetry screen menu ? 
So you don't have to exit Telemetry with an [EXIT] long, and get back in it with [PAGE] long

I do not use often the others main menu option ("Statistics", "About"), i don't know if it make sense to add them too for homogeneity purpose.

![image](https://user-images.githubusercontent.com/985702/33796726-d46f64fa-dcfa-11e7-9e06-4aaf366df5a5.png)

**Comment by capitaineflam25** [comment]
The complete "Reset" menu would be usefull here too.

When you need to reset your timer to prepare a new flight, you need to exit telemetry screen, do the reset and go back to the telemetry screen.

**Comment by kilrah** [comment]
> When you need to reset your timer to prepare a new flight, you need to exit telemetry screen, do the reset and go back to the telemetry screen.

The "reset flight" entry is supposed to be used in this case...

**Comment by capitaineflam25** [comment]
The reset flight is more complete.
I tried a « Reset flight » after a battery change and it also launch the « switch warning ».

I was wondering if the classic home screen and the telemetry screen should have the same menus since more pilots like to have custom LUA telemetry screen.

This could take more sense if #5156 is developed.
