### ISSUE TITLE
Telemetry DSM - modification sensitivity

### ISSUE THREAD

**Issue by romko1** [opentx/opentx#5494]
Hello,
My DSM telemetry on Taranis X9D+ (OpenTX 2.2) shows 0 (RSSI) -> the telemetry OFF - already halfway to the range of the model X-VERT VTOL.
Is it possible to change it?
Thanks.

**Comment by schwabe** [comment]
You probably talking about Multi module here. Telemetry on BNF models is pretty short, only a few meters. Just disable telemetry alarms for the models.
