### ISSUE TITLE
RSSI Shutdown timeout on X9D+/SHUTDOWN_CONFIRMATION on other platforms

### ISSUE THREAD

**Issue by schwabe** [opentx/opentx#5500]
SHUTDOWN_CONFIRMATION disables RSSI check on shutdown via #idef, this seem wrong and counter intuative.

On the X9D+ if you don't switch power back on and just let the screen sit there, the TX turn off after almost exactly 10s. If you compile the X9D+ with PWR_BUTTON_PRESS the timeout disappear.

**Comment by bsongis** [comment]
1st problem: not implemented right now

2nd problem: I think it comes from this `isForcePowerOffRequested`
