### ISSUE TITLE
Update from RC1 to RC2 didn't work

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#5501]
Hi folks,

I realized something. Despite the correct settings, Companion didn't prompt me to announce the RC2 availability.
Here is the settings:
![tmp](https://user-images.githubusercontent.com/1685030/33850217-6f20abe4-deb3-11e7-9cbc-3b48f12c4f8d.png)

**Comment by 3djc** [comment]
We had to pull back rc2 because because of a small, but potentially nasty bug for x10 users. RC3 will fix that

**Comment by LapinFou** [comment]
Thanks 3djc !!
👍
