### ISSUE TITLE
2.2.1RC2 - SD Card Warning Expected version: 2.2V0012

### ISSUE THREAD

**Issue by chiron7000** [opentx/opentx#5504]
I have upgraded to version 2.2.1RC2 on my X10S and also the SD Card content to 2.2V0013 but I get the SD Card Warning message that the expected SD Card version is 2.2V0012. There is also an issue when restoring my models from the backup, see last picture where it says invalid model. Will go back to RC1 now and wondering if others have the same exerience.

![foto 11 12 17 21 58 33](https://user-images.githubusercontent.com/34266910/33854091-b73bcd16-dec0-11e7-9936-9440eec6c1d0.jpg)
![foto 11 12 17 21 58 53](https://user-images.githubusercontent.com/34266910/33854111-c644e8b0-dec0-11e7-9d61-b2d81180d5d6.jpg)
![2017-12-11 22_00_07-l__opentx sdcard version - notepad](https://user-images.githubusercontent.com/34266910/33854120-cdf1d3de-dec0-11e7-924b-252c8f67a75a.png)
![foto 11 12 17 22 08 12](https://user-images.githubusercontent.com/34266910/33854124-d4d6f896-dec0-11e7-8547-f589f6d8e9b3.jpg)

**Comment by kilrah** [comment]
It's actually RC1 since we pulled RC2. version seems to still be displayed wrong.
