### ISSUE TITLE
[Feature request] playBgMusic() function

### ISSUE THREAD

**Issue by JyeSmith** [opentx/opentx#5515]
Hi Everyone,

Would it possible to have a play background music function that is similar to playFile() e.g. something like below.

**playBgMusic(path, [, flags])**

Play background music

**Parameters**

- `path` (string) full path to wav file (i.e. “/SOUNDS/en/system/tada.wav”).  If you use a relative path, the current language is appended to the path (example: for English language: /SOUNDS/en is appended)

- `flags`  Default is to play
    - `PLAY`
    - `PAUSE`
    - `STOP`

**Comment by lshems** [comment]
Yes, for adding title music to asteroids!
