### ISSUE TITLE
TGY 9XR PRO-OpenTx 2.2. – the value of the RAS is not displayed.

### ISSUE THREAD

**Issue by JASSoft1** [opentx/opentx#5520]
The value of the RAS is not displayed (indicated). To be on the side of the 7/9 "Analogs"??
The value of the SWR was already sorted. For the correct setting of the antenna TX is the value of the RAS (SWR) important.

**Comment by kilrah** [comment]
What module?

**Comment by JASSoft1** [comment]
XJT

**Comment by JASSoft1** [comment]
I'm sorry I accidentally closed the #5520.

**Comment by AKA00TG** [comment]
My Qx7 also has no RAS in the analogs  (orSWR in the parameter select) and I do need to see it, if only just once. Is there an ID number or some other way to see this value?
open tx 2.2.1      Taranis Qx7

**Comment by schwabe** [comment]
For the QX7 that is by design since the X7 XJT has no SWR/RAS measurement.

**Comment by JASSoft1** [comment]
I'm sorry, but at my 9XR Pro with OpenTx 2.2.1 the problem persists ..
I add the configuration: 9XR Pro + XJT (version 2015) - D8 mode, D6FR receiver, or D8R-II PLUS, or F801 .... Telemetry works normally. On screen 7/9, RAS is not displayed.
In version FW OpenTx 2.1.9 (in the same configuration). the SWR value is displayed normally

**Comment by 3djc** [comment]
It is not in 2.2.1 It will be available in next version
