### ISSUE TITLE
RC3 compilation error for X9E

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5522]
Download at companion for X9E
got an Compilation error for V2.2.1 RC3
options: opentx-x9e-shutdownconfirm-ppmus-multimodule-lua-de-2.2.1RC3.bin

X9D+ is ok
X10 is ok
X12 is ok

**Comment by 3djc** [comment]
Known issue, will be fixed in release. Remove shutdownconfirm and it will work
