### ISSUE TITLE
stickrev option missing from 'settings' for '9x with m128' in Companion 2.2 

### ISSUE THREAD

**Issue by csurf** [opentx/opentx#5525]
I'm trying to upgrade my 9x w/ m128 chip and taranis gimbals to 2.2.*, but the 'stickrev' option is missing from the build options within Companion. Therefore, I can't download the correct build (if it's even available). Can someone please take a look at this?

![screenshot 10](https://user-images.githubusercontent.com/627526/34078268-83d11a30-e2cb-11e7-8503-2c0137b5c2d7.png)

**Comment by kilrah** [comment]
I believe stickrev is only an option for m64, it's always built in for m128.

**Comment by csurf** [comment]
I must be missing something then, because the openTX build that I downloaded & flashed through Companion doesn't allow me access the 'stick direction icons' within the main radio configuration menu. It simply skips over the 'channel order' option and jumps to the 'mode' option.

Is this simply a case of user error? How am I supposed to highlight and access the stick direction icons? There doesn't appear to be another 'hardware' screen to do the stick reversals either...

**Comment by kilrah** [comment]
I have checked the code and it's indeed how it should be, enabled by default for m128. 
Unfortunately I don't think anyone in the team still has a 9x to test.

**Comment by csurf** [comment]
Can you provide me with a direct link to a 9x-m128 build that should work so that I can test?

**Comment by kilrah** [comment]
I don't even have a working build environment for AVR radios anymore... And since the problem is likely in the server's build process it wouldn't help fixing anything.

Any potential fix will have to be tested through the nightly builds.

**Comment by csurf** [comment]
@kilrah 
how/where can i access the nightly builds for testing?

EDIT:
nevermind, I used the following link:
http://downloads-22.open-tx.org/nightlies/companion/windows/

I installed 'companion-windows-2.2.2N469.exe', flashed the associated firmware, and the problem appears to be fixed. Will this fix be automatically incorporated into a future update for Companion?

**Comment by kilrah** [comment]
Nothing at all has been done with regard to this, so 2.2.1 release should be fine too...
