### ISSUE TITLE
V2.2.1  Companion progamming log Switch Errors, shows not all log Switches defined 

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5527]
programming at Companion a new modell for X9E
look at example L1, L2, L3, 
then will make a L4
look at L4 AND   only the L01 is there, 
after close and open modell again then there are all on

At TX its ok

![fehler log schalter rc3](https://user-images.githubusercontent.com/6217896/34082728-c871820e-e363-11e7-9986-6a7b947f5050.jpg)

**Comment by kilrah** [comment]
Close window and reopen

**Comment by mpaperno** [comment]
(Will be) Fixed by #5437
