### ISSUE TITLE
Horus X10 startup costs more then 30 seconds

### ISSUE THREAD

**Issue by sniperxnl** [opentx/opentx#5528]
Sometimes it start directly but mostly 30 a 40 seconds for that the transmitter is booted. It hanged in the OPENTX logo

**Comment by bsongis** [comment]
interesting as this is a bug we are hunting since long, but only on 9XR-PRO
would you try with another SD card?

**Comment by raphaelcoeffic** [comment]
@sniperxnl any news on that issue??? Did you try another SD? Did it solve the issue?

**Comment by rjelbert** [comment]
I had this problem when I used an older 8GB SD card. As soon as I changed it to a class 10 32GB card, it went away and the radio boots in a few seconds now. (Horus X10 OpenTX 2.2.1)

**Comment by kilrah** [comment]
Closing since no other report and no data from OP.
