### ISSUE TITLE
No joystick connection on windows 10 Taranis x9d+ 2.2.1

### ISSUE THREAD

**Issue by Toastwaffles** [opentx/opentx#5529]
So I went and updated my taranis x9d+ to the latest 2.2.1 firmware, and have no joystick connection. I was reading that people have to disable massstorage and cli, but i have neither of those checkboxes to uncheck. My buddy has been using his as a joystick for along time, but when he updated to the 2.2.1 from 2.1.9 his didnt work either. Anything that I could be missing. My brain is out of ideas.

Thanks. 

![settings](https://user-images.githubusercontent.com/34639058/34090009-aef93874-e379-11e7-82ef-204f39ef07e0.png)

**Comment by 3djc** [comment]
Now a dynamic choice. Plug your cable in your radio and make a choice  (or store the choice in radio setup)

**Comment by Toastwaffles** [comment]
Thank you so much
