### ISSUE TITLE
openTX 2.2.1 - Horus12s - BT is not working

### ISSUE THREAD

**Issue by dk7xe** [opentx/opentx#5532]
Radio - Horus 12s
openTX - 2.2.1
Companion - 2.2.1

BT is not working on the Horus 12s. Have set BT to Telemetry and gave it a name.
According @3djc a hardware adresse should show up. But that's not present.
I have scanned BT with my SGS7 but the Horus is not seen.
![20171218_084324](https://user-images.githubusercontent.com/3907200/34095736-e135641c-e3d2-11e7-83c9-85a4a871cab1.jpg)

**Comment by 3djc** [comment]
My bad. This has changed and on x10/12, that info is bellow master/BT in model setup. And BT is working according to our tests

**Comment by kilrah** [comment]
Works, you might need to reboot the radio after changing the setting to telemetry.

**Comment by dk7xe** [comment]
After reboot it showed up as available device but my android phone can not connect to the Horus. Saying no connection possible.
My windows computer is not recognizing the Horus at all  while it recognizes the Android mobile.

**Comment by 3djc** [comment]
Be aware that this is not a full BT module, only BLE. I likely requires a special app to deal with it

**Comment by dk7xe** [comment]
Even BLE terminal https://play.google.com/store/search?q=BLE&c=apps&hl=de could not find it. But i give up now. ;)

**Comment by kilrah** [comment]
The Free Link FrSky iOS app recognises it fine. 
This one on android sees it too: https://play.google.com/store/apps/details?id=uk.co.alt236.btlescan&hl=de

There is no app on android or Windows that can make use of it anyway at this point.

**Comment by dk7xe** [comment]
ok, thank you!
