### ISSUE TITLE
Timer Countdown Option "Voice and Haptic" possible?

### ISSUE THREAD

**Issue by ParkerEde** [opentx/opentx#5537]
Hi together,
My actual version 2.2.1 Taranis X9d+
is it possible, to add a new parameter for "countdown" "voice and haptic".
This would be very great. Thx.
Regards
Ralf

**Comment by ParkerEde** [comment]
Hi together,
My actual version 2.2.1 Taranis X9d+
is it possible, to add a new parameter for "countdown" "voice and haptic".
This would be very great. Thx.
Regards
Ralf

**Comment by ParkerEde** [comment]
It would be nice if this request could be reconsidered.

**Comment by Luznatural** [comment]
I am also interested in having this possibility for my Horus.
Thanks in advance

**Comment by lshems** [comment]
Create to similar counters.

**Comment by Eldenroot** [comment]
+1

**Comment by ParkerEde** [comment]
It would be nice if this request could be reconsidered.

**Comment by Eldenroot** [comment]
+1

**Comment by ParkerEde** [comment]
unstale

**Comment by ParkerEde** [comment]
unstale
