### ISSUE TITLE
AM / PM

### ISSUE THREAD

**Issue by darkfreelife** [opentx/opentx#5539]
just installed latest version of OpenTX and i noticed changes said i can now change time from 24 hours to 12 hours? how can i do that please help cant see it nowhere

**Comment by 3djc** [comment]
Then you miss read release notes. Here is what they say:
- LUA: getDateTime now additionnaly returns time in AM/PM format

It only applies to this LUA function and is available to script/widget/plugins writers. Doing it accross the radio is something planed in the future, but requires a lot of work to accomodate the extra space used
