### ISSUE TITLE
Horus X10S / 2.2.1 Release "Mass Storage" and "Joy Stick" are reversed...

### ISSUE THREAD

**Issue by jasonbrent** [opentx/opentx#5540]
OpenTX 2.2.1 / X10S - When USB is plugged in with the Tx on, a popup appears on the Tx asking if I want to present the USB as mass storage, or joystick. The options presented are reversed; selecting joystick shows as mass storage to MacOS, and selecting mass storage shows as joystick.

**Comment by kilrah** [comment]
You're just misinterpreting what the "selected" highlight is (hint: same as any other popup).
