### ISSUE TITLE
Companion software icon on windows 10??

### ISSUE THREAD

**Issue by danieljmild** [opentx/opentx#5541]
does anyone else have the some problem with the icon all screwed up on the desktop??

**Comment by 3djc** [comment]
Screenshot ? details ?

**Comment by danieljmild** [comment]
![capture](https://user-images.githubusercontent.com/24760122/34171581-8aa98cea-e53a-11e7-9d6d-47b9a98223cc.PNG)

**Comment by danieljmild** [comment]
Anyone got any ideas?

**Comment by kilrah** [comment]
Yeah, there's no small version so it scales down and badly so if you have medium or small icons set.
