### ISSUE TITLE
OTX 2.2.1 R9M How to enable telemetry on TX

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#5543]
2.2.1, X9D, R9M LBT (EU)
With checkbox telemetry enabled in companion telemtry works. The radio itself has no chance to enable telemetry. It is offered in bind-options, but does not work, if one selects it.
You have to use companion first, to enable telemetry there, then it works on the radio. Why not enable  as default? You can always disable with bind option (i hope ;)).

**Comment by 3djc** [comment]
Telemetry on R9M only works if internal module is disabled,  have you checked it is ? Are you usiing EU or FCC version ?

**Comment by Allerhopp** [comment]
Sure, internal disabled, using LBT (EU) version. As i wrote, telemetry works. But only if the checkbox is enabled using Companion. Bind option in TX offers telemetry mode, but it does not work, without the Companion workaround. TX has no access to the checkbox, Companion has.

**Comment by 3djc** [comment]
OK, understood

**Comment by 3djc** [comment]
As a side note, you can workaround with radio only : select fcc module, activate module telem, choose EU again, the settings should still be 'active'

**Comment by kilrah** [comment]
> Why not enable as default? You can always disable with bind option (i hope ;)).

Module telemetry and receiver telemetry are not the same thing

**Comment by Allerhopp** [comment]
Leniency please dev´s, i was in a deep depression because of the R9 performance ;)

**Comment by LeeHudsonDLS** [comment]
> 2.2.1, X9D, R9M LBT (EU)
With checkbox telemetry enabled in companion telemtry works. The radio itself has no chance to enable telemetry. It is offered in bind-options, but does not work, if one selects it.
You have to use companion first, to enable telemetry there, then it works on the radio. Why not enable as default? You can always disable with bind option (i hope ;)).

@Allerhopp Hi, i'm having no lucjk getting telemetry working with an R9M. Where is this checkbox in companion that you speak of? I can't see it anywhere.
Thanks
Lee

**Comment by Allerhopp** [comment]
Are you using 2.2.2? It is working different now. SPort link is enabled, if internal module is disabled and vice versa.

![r9m_tele](https://user-images.githubusercontent.com/23188713/44040751-5564a8a2-9f1c-11e8-967d-0e2cdf2a7bf8.png)
