### ISSUE TITLE
2.2.1 Mix Scripts Custom Screen X7 Not showing all outputs

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#5546]
2.2.1 Companion
Mix Scripts
Simulator
Custom Scripts
Scripts selected "Sqnc"
Problem
X7 Outputs shows only 1 of 2
X9D Outputs shows both
Anone reported this?
Not all outputs showing for mix scripts on X7
![screenshot_x9d_17-12-19_11-04-24](https://user-images.githubusercontent.com/20209851/34166229-682d1a08-e4ac-11e7-87bf-078a2b6e2423.png)

![screenshot_x7_17-12-19_11-05-50](https://user-images.githubusercontent.com/20209851/34166339-a1f6d6de-e4ac-11e7-9564-a263bbeefacf.png)

**Comment by RCdiy** [comment]
Same behaviour on the tx

**Comment by kilrah** [comment]
No scrolling down?

**Comment by RCdiy** [comment]
Correct... Scrolloing down wraps back to the top...

**Comment by RCdiy** [comment]
Sample file 
[Sqnc.lua.zip](https://github.com/opentx/opentx/files/1572445/Sqnc.lua.zip)
[Sqnc-Sounds.zip](https://github.com/opentx/opentx/files/1572447/Sqnc-Sounds.zip)

**Comment by twistedwings** [comment]
Confirm this.
Custom script screen shows always 1 output less than the script has.
For a script with 6 outputs, only 5 will be shown,

**Comment by RCdiy** [comment]
Yes. In sample I believe 2 outputs exist. 1 is seen.
