### ISSUE TITLE
Taranis SD Card Screen Does Not See Firmware with Multimodule Build Option 

### ISSUE THREAD

**Issue by helinv** [opentx/opentx#5547]
Opentx 2.2.1 Released Version
Taranis X9D+
Build Options: Lua, Multimodule

The SD Card screen (after Radio Setup screen) does not show firmware files with Multimodule build option.

**Comment by 3djc** [comment]
Name of the firmware is too long, needs to be renamed on the PC/Mac

**Comment by helinv** [comment]
I had already tried that.  It does not help.  If firmware Build option contains Multimodule the radio does not see the file.

**Comment by helinv** [comment]
As an example, the radio sees this file
opentx-x9d+-multimodule-lua-en-2.2.0.bin
,but not this file with the exact same character count.
opentx-x9d+-multimodule-lua-en-2.2.1.bin

Any combination of multimodule build option causes the file to not be seen in the radio regardless of filename length.

**Comment by 3djc** [comment]
In that screen the content of the file is not analyzed at all, just names are displayed. There is something wrong somewhere , but hard to tell  exactly what. Could you upload your sd folder content ? Or try something much shorter : test.bin

**Comment by 3djc** [comment]
Yes it is size, remove 2 or 3 chars and it works

Actually opentx-x9d+-multimodule-lua-en-2.2.0.bin does not work either

**Comment by helinv** [comment]
Some issues never cease to amaze me.  My radio would see the file 
opentx-x9d+-multimodule-lua-en-2.2.0.bin with no problem.  I could even select it to flash my bootloader.

I deleted all files under FIRMWARE, and added them back.  Now my radio sees the shorter filenames, even with multimodule, but now doesn't see opentx-x9d+-multimodule-lua-en-2.2.0.bin.

Issue fixed but not solved (SD card problem).

Thanks for your time.  It is most definitely appreciated.

**Comment by 3djc** [comment]
I think you saw one with a similar but shorter name. You cannot see that file name (you can try with simu as well)

**Comment by helinv** [comment]
I actually copied the name right from the SD card.  Who knows?

Thanks again.
