### ISSUE TITLE
Companion Nightlies missing

### ISSUE THREAD

**Issue by capitaineflam25** [opentx/opentx#5550]
The night builds for Companion Windows are no more generated since the 15th.

![image](https://user-images.githubusercontent.com/985702/34196685-7a88596c-e563-11e7-97b1-52bd07bf980a.png)

![image](https://user-images.githubusercontent.com/985702/34196688-7d030b4c-e563-11e7-9e25-05838c505ceb.png)

**Comment by 3djc** [comment]
We are aware about it, there are a lot of changes incomming that broke the compilation chain

Reminder : DO NOT FLY WITH NIGHTLIES

**Comment by capitaineflam25** [comment]
OK thanks
