### ISSUE TITLE
2.2.1 Logical Switches

### ISSUE THREAD

**Issue by Roitellet** [opentx/opentx#5556]
When programming logical switches, other logical switches are not selectable
![grafik](https://user-images.githubusercontent.com/34753844/34276217-b8e8bde4-e6a0-11e7-843d-70b4aa0a1367.png)
Here, L05 can not be selected in the pulldown menue as a condition despite it is configured. 
Could it be a Win 10 Fall creator issue? The Notebook was just upgraded.

**Comment by 3djc** [comment]
It is a list refresh issue, try changing screen and coming back

**Comment by mpaperno** [comment]
Fixed in 2.2.2 (nightly).  Correct about the current workaround.
