### ISSUE TITLE
X10S opentx v2.2.1 very loud noise at speaker, but no noise with FrOS

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5561]
Its at a serie of the latest new X10S with openTx V2.2.1 
very very loud noise  at speaker with opentX V2.2.1
But no noise to hear with FrOS

Mybe FrOS switch the amplifer to Mute (off) if not in use
and opentx not?

could anyone test it, please
with an Oszi at the speaker, and  with an Sinus-Signal of 4kHz as wav-file

**Comment by 3djc** [comment]
Are you comparing with the same modules transmitting at the same power ?

**Comment by hrenz** [comment]
yes, all same, 3 new X10S with this effect 
Fa. Engel has same problem with new X10s and opentx
Muting the X10S  with FrOS is only speculation of me

**Comment by ChristiaanVis** [comment]
I can confirm this issue. No remedy found so far; I tried the following:
- turned off RF
- switching internal or external antenna
- rerouted bluetooth antenna cable
- replaced hello and welcome chimes
- reduced background image size to 4kb
- flashed using both windows 10 and macOS using latest firmware (17 dec 2017)
- also noise through headphones

Possibly issue relates to wav (OpenTx) versus mp3 (fros)?

Available to any further ideas to find the issue.

**Comment by raphaelcoeffic** [comment]
Turning the internal module off does it for me. I guess the speaker wires are not shielded, as usual....

**Comment by 1Sven** [comment]
I think that's not new. The built-in mp3 player was killed with opentx. The audio output is affected. - It certainly can not change without serious hardware change. May be, this is perhaps the price for the simplified audio treatment. You should not be bothered by it, or have to take fros for certain applications.

**Comment by schwabe** [comment]
@1Sven the mp3 player was not killed. It was never implemented.

**Comment by kilrah** [comment]
It's possible it could be improved by muting the audio amp when nothing is playing on radios that have supporting hardware.

**Comment by raphaelcoeffic** [comment]
@kilrah I'd be glad to test it ;-)

**Comment by 3djc** [comment]
Didn’t @projectkk2glider try something like this already ?

**Comment by RoninMedia12** [comment]
I can Confirm my x10s does this same thing my x12s and Taranis x9d plus do not all on 2.2.1,  But my Taranis did it before  I remember a while back I think that was on 2.1 or previous though  then one update just went away and has not returned on the x9d plus

**Comment by voyn238** [comment]
Same issue here on new X10S. I put a sticker over the speaker which reduces the hiss to near inaudibility and reduces volume of audio cues, but it's still there. I didn't hear this hiss during the brief time the radio still had FrOS installed. It's most annoying at home when background noise is low, but you can still hear it in the field, even with the sticker.

**Comment by bajamo** [comment]
Dear all, I have the same issue after put open tx on FRSKY HOrus x10s. What is the fix for this issue ?

**Comment by 3djc** [comment]
I'm afraid at this point in time there is none

**Comment by bajamo** [comment]
on opentx 2.2 it is the same issue ?
thanks for your help

**Comment by sw3Dp** [comment]
this is a bigger issue than just rf noise in the speaker as my day old x10s flashed to 2.2.1 has the speaker noise, rf crazy interference with pc, cell phone, all devices in my pc room.  to top it off it corrupts hal gimbal output making my radio completely non-functional, (that isn't just rf noise.)  FrOS is fine but damb it took me 4 years just to learn the basics of opentx, and i was really happy with the x9d ... mostly.

**Comment by 3djc** [comment]
That seems like a completely diffrent issue altogether, and not one that we have heard off

**Comment by sw3Dp** [comment]
3djc seems different but i remember in 2015 my taranis with one of the intermediate builds had the exact same "noise" glitches that were quickly updated by the crew.  not a stretch to assume corrupted module function affecting hal, but that's just Dirk Gently speaking.

**Comment by svsc99** [comment]
I get the same problem with my Horus x12s, OpenTX 2.2.1 . The error (noise) appears only with the external module **TBS Crossfire micro TX** version 1.25. With the orange module for DSM2 doesn't appear the problem. Are there any new fixes for the problem?
