### ISSUE TITLE
Opentx Stick input reverse

### ISSUE THREAD

**Issue by ThomasH3** [opentx/opentx#5562]
After changing the gimbals on my rc sender throttle and elevator input are now reversed. Is it possible to revervse the stick input in opentx.

**Comment by 3djc** [comment]
What radio ?

**Comment by ThomasH3** [comment]
FrSky X9e

**Comment by 3djc** [comment]
Then you need firmware option horustick

**Comment by ThomasH3** [comment]
great, it's working ...... thank you !
