### ISSUE TITLE
X10S openTx V2.2.1  antenna selection intern extern  both  FrOs only intern or extern

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5564]
at FrOS I can select intern OR extern antenna, but not both
at openTx I can select intern, extern, AND both

Mybe only an error at selection gui at openTx?, comming from the X12 gui selection

**Comment by kilrah** [comment]
We don't know what the module does and assumed same as X12.

**Comment by 3djc** [comment]
I have received confirmation that unlike x12, x10 uses one or the other. Will do the necessary changes
