### ISSUE TITLE
OPENTX 2.2.1 R-XSR "NO TELEMETRY" 

### ISSUE THREAD

**Issue by HotwiresFPV** [opentx/opentx#5565]
I just flashed OpentTX 2.2.1 and I'm getting "NO TELEMETRY". however if I revert to OpenTX 2.2.0 I get telemetry data. using R-XSR using the uninverted S.port pad on top of the receiver. BETAFLIGHT shows telemetry channel 12 going in and out.

**Comment by schwabe** [comment]
We need more details though. What remote. No telemetry data at all or just some missing?

**Comment by HotwiresFPV** [comment]
Taranis QX7. No sensor will populate data.

**Comment by HotwiresFPV** [comment]
Taranis QX7 and r-xsr using the uninverted smartport pads on top of the
receiver. No sensor will populate data. Lua script does work.

**Comment by schwabe** [comment]
Doyou get rssi from the rx?

**Comment by trojanGoat** [comment]
Do you need to possibly update the firmware?  I just installed an r-xsr on my babyhawk and I got telemetry working.
http://rotorgeeks.com/index.php?route=product/product&product_id=877

**Comment by HotwiresFPV** [comment]
Let me try that. Thanks

**Comment by HotwiresFPV** [comment]
I got telemetry working now but I keep getting "telemetry lost" and "telemetry recovered" sometimes "sensor lost" warning. these are happening to  4 drones with rxsr with latest firmware with PID support.

**Comment by rollysing** [comment]
@HotwiresFPV Your Tx is swamping the Rx. Move it a little farther away and it would stop the constant telemetry drops.

Good luck.

**Comment by djdazzy** [comment]
I have had the same issue on my x9d with a d6fr since upgrading to 2.2.1. Intermittent telemetry losing everything including RSSI and A2. I have flashed the internal XJT module with various INT(FCC) FW but it is still the same. I can bind the receiver to my X7 (on 2.2.1) or Devo 7E with no issue.

**Comment by goodnerdboy** [comment]
Hi there.
HotwiresFPV did you solve your issue?
I have a r-xsr and qx7 doing the telemetry lost/telemetry recovered loop and can’t find a way to solve it...
I am using uninverted s.port. Tried both with a SBUS/S.port setup and with F.port, but both have the same result...

**Comment by BombowaKuna** [comment]
I have the same problem. I'm getting telemetry and signal lost sometimes when i fly max 100 meters away. Got the 2.2.1 Open TX update for my Q X7S and 2017-11-09 171103 for R-XSR (all EU ver.).

Any ideas what's going on?

**Comment by kilrah** [comment]
This doesn't seem like the same problem at all, but rather faulty hardware.

**Comment by BombowaKuna** [comment]
so, you telemetry lost does not combine with signal/control lost? If not that im sorry, i misunderstood

**Comment by kilrah** [comment]
No. 

IF you get a control loss then you also get a telemetry loss. Not the opposite. If you lose control at 100m then something is wrong, either faulty hardware or strong interference.
