### ISSUE TITLE
404 on mac download

### ISSUE THREAD

**Issue by spuder** [opentx/opentx#5569]
Not sure if this is the correct place to report this. The mac download link for 2.2.1RC3 returns a 404

http://www.open-tx.org/2017/12/13/opentx-2.2.1RC3

<img width="582" alt="screenshot 2017-12-26 14 41 10" src="https://user-images.githubusercontent.com/242382/34365199-d9a27eb4-ea4a-11e7-9e68-c3b1ec541dd0.png">
<img width="752" alt="screenshot 2017-12-26 14 41 36" src="https://user-images.githubusercontent.com/242382/34365203-e45529e2-ea4a-11e7-9829-42e5caea240c.png">

**Comment by 3djc** [comment]
You should not be using rc3 anymore since 2.2.1 has been released
