### ISSUE TITLE
[Horus X12s] Lua Command for switch the screens

### ISSUE THREAD

**Issue by Storchy1** [opentx/opentx#5573]
Is there a possibility to switch between the screens with a lua conmand.
Something like the pressing from PgUp/PgDn Key.
I have a background routine in a widget script, there happens an event that i would like to visualize.
Thanks

**Comment by 3djc** [comment]
No there is nothing like that. We do not tend to allow lua to take over control of the radio.

**Comment by Storchy1** [comment]
Thank you for your answer
