### ISSUE TITLE
FrSky or SmartPort telemetry - how to get single cell voltage?

### ISSUE THREAD

**Issue by RipperDrone** [opentx/opentx#5578]
Sorry, not sure whether this is an 'issue' or not, but in earlier versions of OTX and BetaFlight, there used to be a single LiPo cell variable (cels, or cells) in SmartPort or FrSky telemetry set of variables. Currently, I can only get VFAS as total LiPo voltage. Unfortunately, I need single cell (lowest or average, I don't care) voltage for copters which I fly on 4S and 6S alternatively and where I would like to implement low voltage alarm on my Taranis over telemetry.

How can I get single cell voltage over to the Taranis, is the old 'cels' variable not active anymore?

**Comment by schwabe** [comment]
Cels still exists. If you don't have it, Betaflight probably does not send it.
