### ISSUE TITLE
X9E+ firmware crashes after startup when built with arm-none-eabi-gcc  7.1

### ISSUE THREAD

**Issue by hsteinhaus** [opentx/opentx#5584]
I just tried to build OpenTX (branch 2.2) on Fedora 27. F27 brings a quite fresh arm-none-eabi-gcc by default (version 7.1). The build for Taranis X9E+ succeeds and the resulting firmware boots up fine till the throttle/switch warnings. But once these stop conditions have been resolved, the TX immediately reboots again. With switches and throttle now in the correct positions, this results in a rapid reboot loop of about one restart per second. The loop can be stopped by switching of the TX (EEPROM save screen becomes visible for a split second). The problem does not depend on a certain TX/model configuration.

After downgrading arm-none-eabi-gcc to the pre-built binaries of gcc-arm-none-eabi-4_9-2015q3 from launchpad, the problem is resolved. A fresh rebuild from the exact same source works fine after a "make flash".

**Comment by 3djc** [comment]
This is what production firmware should be built with gcc-arm-none-eabi-4_7-2013q3-20130916

**Comment by hsteinhaus** [comment]
Unfortunately this information is not present in the "OpenTX 2.2 Linux Build Instructions" in the wiki. This document recommends to install arm-none-eabi-gcc by DNF package manager, which results in gcc 7.1 getting installed. 

BTW, behavior of this kind is very often a strong indication for some nasty sort of bug (initialization, race condition, DMA etc.). Covering it up by downgrading the compiler usually doesn't resolve that.

**Comment by hsteinhaus** [comment]
@3djc May I kindly ask to repoen this issue - at least the documentation should get a fix.

**Comment by 3djc** [comment]
done
