### ISSUE TITLE
OpenTX 9xr128 2.2.1 stuck at variant/eeprom 216

### ISSUE THREAD

**Issue by twids** [opentx/opentx#5586]
No idea if I am totally off here (please close this one asap then.. :-)), but it seems to me like opentx-9xr128-xx-2.2.1 is broken. (I've tried en and se)

If I flash the firmware and load settings from the radio in companion it complains about the settings being outdated and that it needs to be upgraded. 

Seeing the information when I write firmware to radio... well, I was under the impression that, in the attached picture, "variant" should read 218 for 2.2.x+? Which would explain why companion is bitching about it being outdated..
![image](https://user-images.githubusercontent.com/16303454/34501863-1e06e1be-f011-11e7-99a9-81a157ab5c53.png)
![image](https://user-images.githubusercontent.com/16303454/34501531-9d900674-f00f-11e7-8bb9-e55ffd05feba.png)

Update: Installing 2.1.9 firmware works fine, gives me eeprom 217-32768 and works with both reading and writing to radio.

Update: http://openrcforums.com/forum/viewtopic.php?t=10218 discussion regarding the same matter

**Comment by phantomm72** [comment]
Hi Twids, I ve exactly the same pb, i m not alone ... lol same error msgs & pbs .... no Solution found meantime ... worksfine until v 2.1.9, unable to do after this version ....

**Comment by phantomm72** [comment]
If you find any solution, please answer me, if i find, i answer you ....
