### ISSUE TITLE
Flight modes in companion do not support S1 or S2 six position pot mod for Taranis X9D

### ISSUE THREAD

**Issue by kalikraven** [opentx/opentx#5587]
It would be nice if companion supported flight mode changes by use of a six position switch in S1, S2 or in the 9+ S3 positions. If there is a way to do this then I am blind and apologize!

Thank you.

**Comment by kilrah** [comment]
It does as long as your 6pos is configured correctly. 

![clipboard01](https://user-images.githubusercontent.com/6065069/34504753-ce02ba7a-f020-11e7-9495-4908efcf0071.png)

**Comment by kalikraven** [comment]
That will work on the X9D Plus but what about the regular X9 non plus version?

**Comment by mpaperno** [comment]
Sure, just make sure it is set up properly in Radio Settings.

![image](https://user-images.githubusercontent.com/1366615/34507478-56828424-f004-11e7-889c-d134c79f5734.png)
