### ISSUE TITLE
S.Bus on PPM pin is SERIAL_8N2 while it should be SERIAL_8E2

### ISSUE THREAD

**Issue by DzikuVx** [opentx/opentx#5590]
### Should be:
According to specification, S.Bus output should be **SERIAL_8E2**. 

## Is:
In OpenTX 2.2.1, Taranis X9D+, S.Bus output in transmitter bay on PPM pin is **SERIAL_8N2**.

**Comment by schwabe** [comment]
Is that something you tested? Because I am pretty sure that it is 8E2. Also since multi and sbus share the `sbusSendByte` function that sends it and multi expects 8E2 too, I am pretty sure it is really 8E2

**Comment by DzikuVx** [comment]
Yes, I tested. Did not connected to logic analyzer tho. But was able to correctly read S.Bus packets only with `Serial1.begin(100000, SERIAL_8N2);` on Arduino.

On electrical level:
Taranis -> S.Bus normal (inverted) -> single MOSFET inverter -> ATmega32u4 Serial1 RX

Perhaps I'm missing something, but this is what I'm observing

**Comment by kilrah** [comment]
Logic analyzer confirms 8E2.

![odd](https://user-images.githubusercontent.com/6065069/34557695-6cb47314-f13b-11e7-99aa-ce130a2a2f99.png)
![even](https://user-images.githubusercontent.com/6065069/34557696-6ccd5adc-f13b-11e7-8504-337798824459.png)

**Comment by schwabe** [comment]
@DzikuVx try 8E1, that should also work. the 10 bit options are often broken. Also you can test without the inverter if you use non-inverterted output from OpenTX.
