### ISSUE TITLE
X10 uppdates

### ISSUE THREAD

**Issue by seilfly** [opentx/opentx#5594]
Hi, when I updated from 2.2.2N478 to 479, the screen became very dark so I did not see settings. Adding N478 again but there was no change. Despairing!

**Comment by kilrah** [comment]
There is no difference at all between those 2 builds. Check your settings/hardware.

**Comment by 3djc** [comment]
There is also reason why we suggest to  avoid as much as possible nightlies, and only use them for testing something specific !
