### ISSUE TITLE
Screenshot funktion for X10 X12  missing at openTx V2.2.1

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5596]
openTx V2.2.1
We miss the screenshot funktion for X10 X12 at TX´s
------------------------
companion
How does the screenshot funktion work under Companion for X10 X12
Symbol is there, but how to trigger?, but no info

**Comment by 3djc** [comment]
Duplicate #3393

**Comment by kilrah** [comment]
Click on the button, same thing as always...
