### ISSUE TITLE
Wrong enumeration of Logic Switches im Companion

### ISSUE THREAD

**Issue by Gewe99** [opentx/opentx#5597]
OpenTX2.2.2  NB467
Hello together,
the enumeration of the Logic Switches seems to be wrong in Companion!

Till OpenTX 2.2.2-466 Logic Switches count  from L01 to L64.
Since  OpenTX 2.2.2-467 from L02 to L65.

The Radio (HorusX12) Software is correct!

**Comment by mpaperno** [comment]
Thanks!
