### ISSUE TITLE
[Feature request] Open Fileviewer on .lua extension

### ISSUE THREAD

**Issue by Gewe99** [opentx/opentx#5598]
While browsing the SD Card it is possible to view any .TXT file on a Horus radio.
It would be great if it is possible to open the viewer on .LUA Files

**Comment by 3djc** [comment]
What is the intended purpose ? Viewing code on such a small screen doesn’t seem very useful

**Comment by Gewe99** [comment]
I have several short mixer scripts where I sometimes  change some values .
So I could look easy without a PC which values are  actually in this script...
As the textviever is already implemented it should hopefully not be too much work to implement this feature....

**Comment by kilrah** [comment]
The text viewer is limited to a length that would be too short for a script. Best thing should be to name or locate the script appropriately or implement mixer script options for these values that change.

**Comment by RealTadango** [comment]
You could add a text file with values... but then it is double work.

**Comment by raphaelcoeffic** [comment]
Read that text file from your mixer script ;-) or even better, add a display function so your script can be executed standalone to display and possibly change these value.

**Comment by lshems** [comment]
Create a text file editor in Lua. I did for the notes.
