### ISSUE TITLE
[Feature request] Make  Horus X12 GPS position available via getValue () function

### ISSUE THREAD

**Issue by Gewe99** [opentx/opentx#5599]
As discusssed in the rocket forum 2 weeks ago, the Horus X12S GPS radio position is only available  when a telelemety link to the modelgps exists. 
An idea from an developer was to handle the radios gps position like a timer...
I am writing this to keep this issue tracked...

Would it be possible to make the inclination information of the radio accessible as well?
Best solution would be a new value like Joystick Jx Jy

**Comment by Magic-Paul49** [comment]
Yes, that would be great!

**Comment by 3djc** [comment]
So great that it has been available throught the value widget from day one. Will make it available to lua too

**Comment by Gewe99** [comment]
Super!!!!!
What is the value widget? Where can I find that?

**Comment by 3djc** [comment]
Erf, the widget that allow you do display all values !

![image](https://user-images.githubusercontent.com/5167938/34653150-0c74560e-f3e8-11e7-9cba-7b5efba8a712.png)

**Comment by Gewe99** [comment]
![20180107_204823-2](https://user-images.githubusercontent.com/27633575/34653559-d074bab2-f3ed-11e7-9e92-e9e12705684e.jpg)

After carrying the radio into the garden it works....
It's nice that the nr. of sats are displayed until  the gps has a fix.
Surprising what is already implemented...
