### ISSUE TITLE
Logging support for reboot into safe mode?

### ISSUE THREAD

**Issue by dallinbriggs** [opentx/opentx#5612]
I was unable to find any information about this in the documentation or other issues. Is there any logging support when your transmitter crashes and reboots into safe mode? I have a taranis x9d plus that randomly reboots into safe mode and I cannot seem to find the cause of the problem. Battery terminal looks good, all hardware connections seem to be secure. Is there any way I can view what set the flag?

**Comment by kilrah** [comment]
Nope

**Comment by 3djc** [comment]
If you do not use lua scripts , then it is likely a hardware issue. If you do, try without

**Comment by dallinbriggs** [comment]
Okay. Thanks for the input. I'll go ahead and close this issue.
