### ISSUE TITLE
Website - Broken links for Companion Nightly builds

### ISSUE THREAD

**Issue by richard-scott** [opentx/opentx#5615]
I've looked on [here](http://www.open-tx.org/downloads) and noticed that the download links for the Nightly builds of the Companion don't work.

![2018-01-10 15_10_26-downloads](https://user-images.githubusercontent.com/5149834/34780479-2c4a5552-f61b-11e7-8a27-f4b6baee53b2.png)

They reference a host such as http://downloads-22.open-tx.org/nightlies/companion/macosx/

**Comment by 3djc** [comment]
Links fixed (but do not use nightlies for flying)

(we are in the process of changing servers, hence the current issues, sorry about that)
