### ISSUE TITLE
downloads-22.open-tx.org DNS record not found

### ISSUE THREAD

**Issue by MartijnKruissen** [opentx/opentx#5617]
Symptom: "Unable to check for updates"
Reason: downloads-22.open-tx.org DNS record not found

Checked with multiple DNSs.

Version OpenTX 2.2.0

**Comment by 3djc** [comment]
Short term fix: you can upgrade to 2.2.1 which does not rely on this domain while we fix this

**Comment by MartijnKruissen** [comment]
Confirmed. 2.2.1 does not have this issue.

**Comment by bsongis** [comment]
Done
