### ISSUE TITLE
X7 switch warning for H switch

### ISSUE THREAD

**Issue by pierrem** [opentx/opentx#5619]
We can activate H switch warning using companion (2.2.1), but there is no way to desactivate it directly on the X7 radio, only A, B, C and D are accessible, not H

**Comment by kilrah** [comment]
What type is your H switch configured as?

**Comment by 3djc** [comment]
Even if remplace by a 2 pos switch (you cannot 3 on this one) the ui doesn't show it. Not sure how it could either give the available space

**Comment by 3djc** [comment]
That should be reviewed anyway, because the nav isn't right there on the radio

**Comment by pierrem** [comment]
SH switch is a temporary switch on my radio (and probably on all unmodified ones ?)
So It may not be a problem if it never trigger a warning. My problem was that it was active and I didn't see why on the radio, until check what was happening using Companion.

**Comment by 3djc** [comment]
Since it can be made a 2 pos, it needs to be managed on the radio too (companion is right there)
