### ISSUE TITLE
Unable to create new models!

### ISSUE THREAD

**Issue by aviator92** [opentx/opentx#5620]
My Taranis X9D has an issue. When I try to create a new model, I just get an error message that says: "Script syntax error, wizard.lua:72, attempt to call field "lock" (a nil value)."

Does anyone know how to fix this problem.

I have upgraded to the latest firmware (version 2.2v0013)

Thank you.

**Comment by 3djc** [comment]
The version of the wizard on your sd card does not match your radio version

**Comment by kilrah** [comment]
And the model is actually created, just EXIT and that will skip the non-working wizard.
