### ISSUE TITLE
QX7S sd card warning

### ISSUE THREAD

**Issue by ludahchris** [opentx/opentx#5622]
I used companion to update to the newest firmware and even downloaded the sd card contents.  I tried 2.2v0010 and 2.20013 and both give me a sd card warning.  What should I try now? I have tried other versions of companion and tried the sd card contents as well but nothing works still get an error no matter what

**Comment by 3djc** [comment]
You need to make sure all the files in the sd card file are copied properly

**Comment by ludahchris** [comment]
what does that mean?  I copied everything over not including the rar file
