### ISSUE TITLE
X9E: Switch Alarms do not store selected positions

### ISSUE THREAD

**Issue by knabby** [opentx/opentx#5623]
Hi 
2.2.1:
In modell settings it is not possible to select a position other than switch to front.
Due to manual it should be possible to store the desired switch position (front / middle/ rear) ^-v with a long press to the wheel selector. This will then be checked at powering on the TX. But it is not working.

**Comment by 3djc** [comment]
It does work. you need to select the full line, put all your switches in desired position and long press wheel. This will store all switch position. You can the selectct into the list wich switch you want to enable/disable check

**Comment by knabby** [comment]
Thanks a lot!
Now I am happy.
