### ISSUE TITLE
X9E: Poti Warning not working for LS, RS

### ISSUE THREAD

**Issue by knabby** [opentx/opentx#5624]
Hi,
X9E  OTX 2.2.1
Model settings: Potentiometer warning is not working for both side potentiometers L and R (LS and RS).
Thanks,
Knabby

**Comment by mpjf01** [comment]
Check that they are configured correctly in RADIO SETUP/HARDWARE

**Comment by 3djc** [comment]
Just checked on mine, it does work, so there must be something wrong with your setup

**Comment by knabby** [comment]
Thanks a lot.
The Pots LS and RS are not set up per default in the X9E. You have to asign it to "slider". Then it is working.
