### ISSUE TITLE
Redundancy Bus

### ISSUE THREAD

**Issue by drummaker** [opentx/opentx#5629]
2 things
Why does the transmitter automatically giving me voice announcements when redundancy bus is plugged in and providing Telemetry info  Maybe I would like to shut it off... If I did what would I do besides find the wave it is playing and erasing it that is.

Why is the Telemetry info NOT giving me values for current draw and MAH  used?

**Comment by 3djc** [comment]
- Because if you use RB, it means safety is of high priority to you, so very much like RSSI alarms are part of OpenTx, basic RB alarm is too

- Probably because you use RB-16 which does NOT include current telemetry

**Comment by drummaker** [comment]
I am using RB 10

Yet Maybe I would like change the recordings... Their seems to be no documentation on this.. or am I wrong?

**Comment by drummaker** [comment]
under the heading of Values.   It says Over-L - indication of servo status good or overloaded and then below It shows nothing to indicate what value that means...ie Rx2F ?
can you shine any light on this for me?


![capture](https://user-images.githubusercontent.com/35455350/34945104-14538c6c-f9d0-11e7-96ed-9f16bebc3f78.PNG)

**Comment by 3djc** [comment]
This is not a place for end user support, this is just for Otx bug tracking. Best place for end users support are forums like rcgroup for example. Also this is not quite OpenTx , but more FrSky things, I believe they have a forum too
