### ISSUE TITLE
Taranis becomes mass storage after 2.2.1 update

### ISSUE THREAD

**Issue by NTTDNV** [opentx/opentx#5631]
After updating my Taranis X9D+ to 2.2.1 my radio will only function as mass storage when connected to my computer.  Was working fine before the upgrade. The machine would recognize it and Liftoff would work with the transmitter as input.
Also there is no "masstorage" option to deselect in the radio profile:
![taranis_mass_storage](https://user-images.githubusercontent.com/35473783/34967397-42a7350e-fa17-11e7-812c-05a04dfa226e.PNG)

**Comment by 3djc** [comment]
As mentionned in the release notes : 
"FrSky Radio: massstorage option has been removed. When plugin the radio to USB, you have a choice between accessing SDcard or using the radio as a joystick (choice can also be setup in radio settings)"

**Comment by giddy92** [comment]
How do i choose joystick in through the radiosettings?

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/35043615-8b8f7584-fb8d-11e7-9ff6-e8265d3c2310.png)

**Comment by giddy92** [comment]
Yea i found it, thanks for the help anyway :)

2018-01-17 13:51 GMT+01:00 3djc <notifications@github.com>:

**Comment by NTTDNV** [comment]
Hello

I wasn't getting a choice upon plugging in my TX, it would just go straight
to mass storage mode after my 2.2.1 upgrade.

Turns out I had some issues which have been sorted, now it works as it is
meant to.


Thanks for the reply!
