### ISSUE TITLE
2.2.1 companion firmware does not match SD card FW - 9XRPRO

### ISSUE THREAD

**Issue by MPS2199** [opentx/opentx#5637]
Hi OTX Team,

After loading the downloaded FW (via the companion software) and the correlating SD card structure with SD card fw. Upon reboot I get an SD card error Expected Version : 2.2V0013. To note Version 2.2V0010 is what is I was directed to after following the link on the OpenTX 2.2.1 (2017-12-16). Any way this can be fixed?

Thanks

Michael

**Comment by 3djc** [comment]
We currently do not have a 2.2.1 SD card pack for 9xrpro, will make one

**Comment by 3djc** [comment]
Done
