### ISSUE TITLE
Bootloader 2.2.1 do not work on X7 - Photo added [SOLVED]

### ISSUE THREAD

**Issue by 500mania** [opentx/opentx#5639]
after upgrade the firmware to 2.2.1 on Q X7 the bootloader do not start properly
![img_3533](https://user-images.githubusercontent.com/35607970/35175723-5091c2fe-fd75-11e7-9f9f-dade1597ae73.JPG)

**Comment by 3djc** [comment]
You need to put much, much more details, as obviouly thousand and thousands of installations have been done without issues on x7. So be very specific of what you did, and what is happening

**Comment by 500mania** [comment]
I upgraded my X7 with companion 2.2.1 latest stable version
I upgrade the bootloader via sdcard
than...
when I hold both the horizontal trim and switch on the radio the bootloader menu do not start. the display indicate only the version of the bootloader

**Comment by 500mania** [comment]
now it does not start anymore!!!!

**Comment by 500mania** [comment]
option are.... multimode, eu, lua, luac, noheli

**Comment by 3djc** [comment]
works fine here with those options

**Comment by 500mania** [comment]
how can I to come back to 2.2.0?

**Comment by 500mania** [comment]
[SOLVED] reflashing the original firmware downloaded from FrSky with Dfuse Demo and then reflashing the bootloader via SD and then reflashing latest firmware with Companion.
