### ISSUE TITLE
Open TX Speaker

### ISSUE THREAD

**Issue by CrashAndBash** [opentx/opentx#5641]
When I try and download from http://www.open-tx.org/2014/03/15/opentx-speaker via the download link the web page cannot be found.

Can you please fix the
![broken_link](https://user-images.githubusercontent.com/34261028/35189551-6d0cdab6-fe44-11e7-97f7-de42cd98f51f.JPG)
 link?

**Comment by 3djc** [comment]
Should be ok now

**Comment by CrashAndBash** [comment]
Thank you
