### ISSUE TITLE
x10s issue in Companion programing SG and SH switches 

### ISSUE THREAD

**Issue by Crunch69** [opentx/opentx#5644]
x10s issue in Companion with SG and SH switches appear to be reversed.  Programing assigned to SH switch operates on the SG switch
In companion edit radio settings >hardware does not allow you to correct the switch settings ie:the SH drop down does not provide 3 position as a setting.

Are the SG and SH switches physically installed incorrectly on the radio?  ( should the switches be swapped from their current positions)

**Comment by 3djc** [comment]
I'm not sure I understand clearly. On x10s, SH is the two pos momentatry switch, and SG is a short lever 3 pos switch.

I just tested companion 2.2.1, and it is accurate, as can be seen bellow:
![image](https://user-images.githubusercontent.com/5167938/35260711-2b382a80-000d-11e8-903d-71a55c2d2e3b.png)

On the radio itself, SG is next to the right slider (RS) and SH is next to the  radio 'handling bar'

**Comment by kilrah** [comment]
As you were answered in the chat the hardware for the SH switch on X10 does not support 3 positions.

**Comment by Crunch69** [comment]
Shouldn't the SG be next to the slider according to how the rest of the radios switches are laid out?
All the other switches are laid out left to right 
Top Row SF SE SG SH are we saying the top row is SF SE SH SG?
Bottom Row SA SB SC SD

**Comment by 3djc** [comment]
Yes it is according to frsky descriptions. But opentx also says it, create a function or whatever needing a switch, move it to get it recognised, and you shall see...
