### ISSUE TITLE
Taranis QX 7 Outputs Page Issue

### ISSUE THREAD

**Issue by yellowsol122** [opentx/opentx#5647]
I recently bought a Taranis QX7 and after setting it up I’m having an issue I hope you can help me with. I fly quadcopters and went to set up a model profile and in bthe outputs page I went to set my endpoints so that Min Throttle is 1000us-1500us mid point-2000us Max Throttle, and typical on ALL the taranis qx7 I’ve seen in the past start at -100 min and 100 max and when you calibrate using betaflight you end up around -97 and 97. My QX7 came stock with a setting of -512 min and 512 max. It’s on every single channel, and I end up around -500 min and 500 max after I calibrate my end points. These high numbers can’t be right, and I can’t for the life of me figure out why it’s doing this. Please help? I’ve included a picture of the page in the Taranis menu I’m taking about. Thank you so much in advance! 

By the way, I got my Taranis with an old version of OpenTx so I've flashed the latest firmware, setup two models, one for Freerider and the other for my quad, calibrated the remote, and went to setup end points when I noticed it. I set my points but then my quad wouldn't arm. Put it back stock and it arms, its killing me.
![img_1178](https://user-images.githubusercontent.com/35757224/35317807-7edf0ee4-00a6-11e8-8760-6b6ccfe20fd4.JPG)

**Comment by 3djc** [comment]
You are simply running a firmware with option PPMUS, which instead of displaying in % (the 100 you are used to), displays in µS
