### ISSUE TITLE
X7 missing Trainer mode SBUS CPPM

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#5649]
rcdiy 1:35 PM   
Q X7
SETUP
TRainer Mode
Only has Master and Slave Jack
Not the other modes such as SBUS and CPPM missing
2.2.1
On companion the model editing window has SBUS and CPPM
Simulator does not
TX does not

rcdiy 2:08 PM
is this by design?

Kilrah Admin Owner 2:19 PM   
probably broke with bluetooth autodetection

**Comment by Fi156** [comment]
Can confirm, SBUS option is missing too...
