### ISSUE TITLE
Taranis becomes mass storage after 2.2.1 update

### ISSUE THREAD

**Issue by kubais** [opentx/opentx#5651]
After update to 2,2,1 (lua and sqt5font selected only), Taranis goes directly into mass storage mode instead of joystick, as it normally should. There is even no "mass storage" option to select anymore in OpenTx, which would result into such behavior. Bootloader updated as well to 2.2.1.
![screenshot 2018-01-25 19 53 46](https://user-images.githubusercontent.com/30256909/35408269-cca7d4b2-020e-11e8-9666-a0b9451151df.png)

**Comment by 3djc** [comment]
Please read the release notes
