### ISSUE TITLE
Companion 2.2 trying to open a .bin eeprom file directly fails

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#5653]
Get "can't extractt RADIO/radio.bin" regardless of selected profile. Also while it fails and no window appears there is a document "stub" left open since it asks to convert or save when changing profile/closing

**Comment by mpaperno** [comment]
Need a more specific example I think... Just tried a fresh `2.2` build with a few radio types and .bin files and didn't get any errors.  I did get the same error for a while on `2.2` (with any radio/.bin), but that was before 323b30a14b4619861d0bae2add6c3cd1efe46106.

Especially curious to recreate the leftover "stub" issue -- I addressed a lot of that in 0dbad182e8ec0ab3e067aca57b132e416ef8093c but I guess there are still conditions which can cause the MdiChild to not destruct.  The whole situation is a bit awkward really, might be better to only create the MdiChild once the radio data actually exists.

**Comment by kilrah** [comment]
Will have to retry on current 2.2 branch... already forgotten, but all the bins I tried at that point failed indeed.

**Comment by mpaperno** [comment]
Doesn't seem like an issue anymore.

**Comment by raphaelcoeffic** [comment]
@kilrah that happens to me with horus module files, but nothing is left open or the like. Was it the same for you? I think for horus it is just not supported to open just the model file (or radio file only, it's just the same).

**Comment by kilrah** [comment]
It was giving the Horus error when dropping a Taranis bin. Likely not a problem anymore, and tons of stuff was reworked since
