### ISSUE TITLE
Welcome to OpenTX - cannot be suppressed anymore?

### ISSUE THREAD

**Issue by RipperDrone** [opentx/opentx#5656]
Whatever I try to do on the tada.wav sound file, Taranis X9D+ will always play 'Welcome to OpenTX'. All manuals / WiKis say I need to change the tada.wav file to change the startup sound. This has obviously changed. Or am I doing something wrong here?

**Comment by 3djc** [comment]
Changed to hello.wav in 2.2.0 if I remember correctly

**Comment by RipperDrone** [comment]
I see - thanks, found it :-)
