### ISSUE TITLE
Open tx 2.2.1

### ISSUE THREAD

**Issue by piocarlos** [opentx/opentx#5671]
Have no start up welcome to open tx , even though the wav file exists on the sd card sounds.

**Comment by kilrah** [comment]
Not an OpenTX issue. Wav file changed name between 2.1 and 2.2 by the way.

**Comment by piocarlos** [comment]
ok how do I get the welcome like I used to then please.

**Comment by piocarlos** [comment]
Hi, how do I get the open tx welcome back like I used to have in 2.0.
please?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by 3djc** [comment]
Maybe reading the release notes would be a good first step.

**Comment by piocarlos** [comment]
nothing in the release notes about this issue!

**Comment by kilrah** [comment]
No?

> MISCELLANEOUS
> [...]
> tada.wav has been renamed to hello.wav

**Comment by piocarlos** [comment]
Same question how do I set it to play at switch on ?

**Comment by piocarlos** [comment]
Same question how do I make it play that at start up?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kilrah** [comment]
You don't do anything, if it's there it plays. Just like before apart from the name.

**Comment by piocarlos** [comment]
Ok thanks buddy

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
