### ISSUE TITLE
X10 Lua Scripts

### ISSUE THREAD

**Issue by s700ky** [opentx/opentx#5673]
None of them run in 2.2.1 Kiss, BF, Crossfire?

**Comment by 3djc** [comment]
I'm sorry but this tool is to register and track OpenTx bugs. For end user support, please go to forums like rcgroups.com or http://openrcforums.com

**Comment by s700ky** [comment]
I'm sorry. But is this not a bug? They run on my 9Xd+ and QX7?

**Comment by 3djc** [comment]
If you think there is an issue with the Horus version of those scripts, then you need to take it to those scripts authors
