### ISSUE TITLE
[companion] Unable to check updates and download firmware

### ISSUE THREAD

**Issue by OpenMik** [opentx/opentx#5676]
Companion 2.2.1 on Ubuntu 14.04 and 16.04
(from ppa and deb from opentx web site)
When start a message "unable to check updates" is showed 
is impossible also to download firmware
SD card immage is available

**Comment by 3djc** [comment]
Sorry, I just installed it on a brand new uibuntu install and cannot replicate the problem, more details maybe ?

**Comment by OpenMik** [comment]
This morning is back to work
This night I tried to download from different PC without success (around 23:00 in Italy)
(Xubuntu 14.04 from ppa and ubuntu 16.04 from .deb)
Other download were worked
I will make other test
For the moment I think the issue can be closed
Thank you

**Comment by 3djc** [comment]
The server has been up for the last 29 days, so must have been a network issue somewhere
