### ISSUE TITLE
SxR LUA - S8R calibration value

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#5677]
When calibrating S8R and using the SxR script, displays incorrect values XYZ that do not match the values when connecting the receiver to the PC ( here displays correct ) ). At S6R is not a problem. Also, when using FrSkyOS on the transmitter there is no problem. Have any suggestions for solutions please?
![sxrconfig_different_value](https://user-images.githubusercontent.com/36260516/35968245-988781ae-0cc3-11e8-9b96-927c2e409232.jpg)

**Comment by 3djc** [comment]
According to FrSky site, there is an S8R firmware that "solve the issue about lua script", but I have not tested it myself

**Comment by ghost** [comment]
I tried more S8R with the last available FW ver.171018 and  also  ver.171213  and unfortunately still the same :-(
The problem is on FW as you confirm.

**Comment by ghost** [comment]
can you test it myself and give me the information please?

**Comment by 3djc** [comment]
Sorry I do not have a colorscreen radio, but I tested latest firmware with latests FrSky supplied S8R calib script (170925) on X9E and it does not work either.

You need to take that to FrSky I guess

**Comment by ghost** [comment]
Thank you for your quick consultation and recommendations. I'll hand it directly to FrSky. BR

**Comment by 3djc** [comment]
Please copy the new script file from our repository: https://github.com/opentx/opentx/blob/2.2/radio/sdcard/horus/SxR/SxR_Calibrate.lua

**Comment by ghost** [comment]
Very thanks,
