### ISSUE TITLE
Simulator typo X12S

### ISSUE THREAD

**Issue by Oldgibber** [opentx/opentx#5678]
On the Horus X12S simulator the button which should be labelled "MDL" is actually labelled "MOL". The X10 is correctly worded. (version 2.2.2 nightly)
![image](https://user-images.githubusercontent.com/9936596/35988479-63eddae6-0cf6-11e8-9832-496452456e82.png)

**Comment by schwabe** [comment]
The image reproduces the real hw. The real x12s has mol on that button.

**Comment by Oldgibber** [comment]
Nooo! I have my 12S in front of me and it says MDL.
![image](https://user-images.githubusercontent.com/9936596/35990029-b45f454c-0cfa-11e8-9559-845e6a9ad1ed.png)
I also have a spare encoder bought recently and that says MDL too, as does my new X10

It would appear from some of the photos on the internet, that some do say MOL. I wonder if this was an early FrSky typo. 
MOL makes no sense.

**Comment by schwabe** [comment]
Google images disagrees with you. Might be that FrSky changed that on later models. But what the simulator shows is not wrong.

**Comment by Oldgibber** [comment]
Might be right for earlier models, but not so now. I'm trying to update 200 pages of documentation, and typos like this make it difficult both for me and the inexperienced user.

**Comment by Oldgibber** [comment]
At least leave this open so that others can discuss.

**Comment by kilrah** [comment]
My production Horus says MDL, I think MOL was on the beta ones (and we complained...)

**Comment by Oldgibber** [comment]
Replacement rotary encoder. £3.60 in the UK. Having heard of many breaking I bought a spare.

**Comment by kilrah** [comment]
We don't have the source files, @mhotar can you have a look?
