### ISSUE TITLE
Bug??? Frsky Horus X12S Stuck Button error and data reset

### ISSUE THREAD

**Issue by bbc25185** [opentx/opentx#5690]
Today, switching on my radio (Frsky Horus X12S), he showed an alarm of stuck button and, at the home screen, the right menu buttons work poorly and PgUp and PgDown did not work at all.
Opened the radio (removed the main battery) and checked all the buttons, I have verified that they work perfectly.
I tried again to turn on the radio ... same error... but I noticed that the date was reset to 1970
I checked the battery charge of the CR1220 (good) and reinserted in its place.
At this point, the problem of the button disappeared and the date was reset to 2000. 
BUG?????
OpenTx version 2.2.1 (latest stable 2017-12-16)
Frsky Horus X12S
Build Options: ppmus, multimodule, lua, luac
Language: en

**Comment by kilrah** [comment]
Sounds more like a hardware / wiring problem on your radio since nobody ever reported something like that...
