### ISSUE TITLE
When lost student signal at trainer mode  I hear a voice alarm but cant react with a log switch 

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5694]
Improvement:
In Trainer mode  and student signal
I hear  a voice alarm for "lost student signal"  thats ok

But I have not a possibility to react then with a Log switch  and/or a spezial funktion

Think we  need  therefore  a kind of: 
If Errorbyte value  is  XXX then set log switch  on
or lost student signal set log switch 

Problem was with a the Bluetooth lost signal

**Comment by kilrah** [comment]
Any TRx mixer line should be deactivated when trainer signal is absent so you can use that.
