### ISSUE TITLE
2.2.1 does't work for simulators NOT DRL or LIFT OFF

### ISSUE THREAD

**Issue by S-T-A** [opentx/opentx#5703]
i have my radio properly configured it worked before this update. Also once the USB is plugged in, I can't change or select a diffrent model it use to work on DRL and i was tring to get it to work on lift off now i stooged my self:(

**Comment by 3djc** [comment]
What are we supposed to do with your post ? No details on platform, radio type, if there was an issue we would have absolutely no way to diagnose it. But the more likely is that you either did not read the release notes, or you have an issue with your computer. I’m closing this, will reopen it if you supply documented evidence that there is actually a firmware bug
