### ISSUE TITLE
OpenTX 2.2.1 Horus 10 Simulate

### ISSUE THREAD

**Issue by flaviomartins8** [opentx/opentx#5706]
Hi 
In radio simulator X10/X10S, I cannot access the click wheel.

**Comment by 3djc** [comment]
On Windows PC, the wheel click is done by clicking with your mouse on the wheel, rotating the wheel is done with mouse scroll wheel when mousing over the wheel

**Comment by flaviomartins8** [comment]
I use MAC opentx . and could not make it work. 
I Test windows with parallels desktop and cannot make work too.
I use macbookPro 2016.
Tks

**Comment by kilrah** [comment]
Scroll with 2 fingers works on Mac AFAIK. Check help text for alternate key combinations.
