### ISSUE TITLE
Open TX 2.2.1 import from Taranis 9

### ISSUE THREAD

**Issue by flaviomartins8** [opentx/opentx#5707]
Hi 
when I import the data from Taranis to the X Horus and  after ZERO use "0"to everything in OUTPUT and in Input and Mixes, the system do not Zero the sub trim. It appears zero in OUTPUT page, but in ch main screen, stay different that MIDLE point

**Comment by 3djc** [comment]
Could you include screenshots or something, I'm having some difficulties understanding every details.

**Comment by flaviomartins8** [comment]
I will try to take my backups and simulate the problem, to better understanding.
I have  a card backup.
Does I need to put in the radio and read from radio or 
Do we have another way to read the models direct from sd card without the controller?
I cannot open .bin in opentx. in scard\models
