### ISSUE TITLE
LS not properly udpated in the AND switch field

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#5709]
When editing a model, the available LS in the "AND switch" list is not dynamical updated.
It will work once, then we must close the editing windows and reopened it in order the list to update.
Here is a snapshot of the issue:
![tmp](https://user-images.githubusercontent.com/1685030/36488640-45d7a1a8-1724-11e8-8d51-3f24b4d2ba4b.png)

The LS01 has been added, but not LS02.

**Comment by LapinFou** [comment]
![tmp](https://user-images.githubusercontent.com/1685030/36488786-9f09e718-1724-11e8-8138-740e049213a4.png)

**Comment by mpaperno** [comment]
Which version are you testing,  2.2.1?  Should be fixed in `2.2` branch already, which would also make this something like a "quintuplicate" issue on this subject...  (also please don't assign things to me.)

**Comment by LapinFou** [comment]
Oups!! I forgot to mention the version → Companion 2.2.1, Dec 17 2017 Windows version.
I will try on the latest nightly build.
(And sorry for the "assign". I won't do it again).

**Comment by LapinFou** [comment]
I checked the 2.2.1 MacOS → same issue.
I checked the 2.2.2N526 → issue is gone.
So, everything is OK.
Sorry for opening this ticket.

**Comment by mpaperno** [comment]
No worries, & thanks for confirming the fix.

**Comment by LapinFou** [comment]
You're welcome. 😄
