### ISSUE TITLE
USB

### ISSUE THREAD

**Issue by Ibiscanes** [opentx/opentx#5712]
I have upgraded my Taranis to the latest firmware. I turn on the transmitter by holding in the trim tabs. It starts up fine, I plug in the USB cable. I turn on Companion 2.2 and try to download my models. I get and error message I  need to upgrade to 2.0 for the USB cable to work
![p1](https://user-images.githubusercontent.com/36718065/36572153-34fef540-1808-11e8-95e4-66d85ec7cfac.jpg)
![p2](https://user-images.githubusercontent.com/36718065/36572154-350e9b80-1808-11e8-9053-63606f66a700.jpg)
![p3](https://user-images.githubusercontent.com/36718065/36572156-3522678c-1808-11e8-96db-68e69c200931.jpg)
![p4](https://user-images.githubusercontent.com/36718065/36572157-3531364a-1808-11e8-9ba0-95ecbfeee055.jpg)
![p5](https://user-images.githubusercontent.com/36718065/36572158-3541b588-1808-11e8-969d-0df70f39b812.jpg)
![p6](https://user-images.githubusercontent.com/36718065/36572159-3550fd0e-1808-11e8-8f9a-92f5f56dd58d.jpg)
![p7](https://user-images.githubusercontent.com/36718065/36572160-355bd76a-1808-11e8-9243-5258ae1e6a9f.jpg)

**Comment by 3djc** [comment]
Could you include a screenshot of the message, because I do not understand what you are refering to.

**Comment by Ibiscanes** [comment]
My Taranis  X9D 

Version 2.2.1(CCA71801)

EEPR 218

FW opentx-X9D

**Comment by Ibiscanes** [comment]
I also receive this message when I open 2.2 Companion

 

Firmware opentx-x9d+ does not seem to have been downloaded Release 2.2.1(2018-01-09) is available. Do you want to download. 

I responded No. It then asked Do I want to ignore this release I responded No

**Comment by kilrah** [comment]
Attachments don't work when you answer via email.

**Comment by Ibiscanes** [comment]
Pictures attached to issue

**Comment by kilrah** [comment]
Reread the main message a bit more correctly, not jsut the fine print...

Anyway you probably have a bad or charge-only USB cable, try others.

Also this place is for bug tracking , not support. Please use forums for support.

**Comment by Ibiscanes** [comment]
I should have left my system alone. Not worth the trouble of upgrading
