### ISSUE TITLE
NO  Fly wing Delta wing in create model widget

### ISSUE THREAD

**Issue by flaviomartins8** [opentx/opentx#5713]
Hi, can you create a  Fly wing Delta wing in radio create model widget for X10/s.
Please
Tks

**Comment by 3djc** [comment]
We have made radio wizard in LUA so that the community can create those. If not available for your radio, then companion ones are also available

**Comment by flaviomartins8** [comment]
Yes, but the taranis 9 had one and now we do not have on companion wizard, can you check please
We only have T and V til.
First page we do not have nothing, tks

**Comment by flaviomartins8** [comment]
Tks 3djc.
How I can contact or open a request for community?
Here or other place, Thank you

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/36537684-3b2d5ccc-17d1-11e8-893f-b88540092892.png)

As i said, companion has those

**Comment by flaviomartins8** [comment]
Thank you, but we have only in computer, from the radio, looks like we have a bug in first page 
<img width="678" alt="captura de tela 2018-02-22 as 16 33 20" src="https://user-images.githubusercontent.com/12039141/36559995-5767f59c-17ee-11e8-8a4e-c531488d7cd9.png">
<img width="580" alt="captura de tela 2018-02-22 as 16 33 43" src="https://user-images.githubusercontent.com/12039141/36559997-57896308-17ee-11e8-95be-0971c1a7edc0.png">
<img width="549" alt="captura de tela 2018-02-22 as 16 33 49" src="https://user-images.githubusercontent.com/12039141/36560001-57c065b0-17ee-11e8-89fa-b72ee6dfb721.png">
<img width="566" alt="captura de tela 2018-02-22 as 16 33 57" src="https://user-images.githubusercontent.com/12039141/36560004-57f17dd0-17ee-11e8-9f8b-6c5b5bb5a65d.png">
<img width="552" alt="captura de tela 2018-02-22 as 16 34 04" src="https://user-images.githubusercontent.com/12039141/36560006-582367d2-17ee-11e8-8f30-566c870bc794.png">
<img width="519" alt="captura de tela 2018-02-22 as 16 34 09" src="https://user-images.githubusercontent.com/12039141/36560008-58414e96-17ee-11e8-80bd-7ac467e94211.png">

**Comment by kilrah** [comment]
As mentioned it is not a bug, nobody wrote a delta wizard for Horus so far. So either find someone who wants to write it, or use the one on the computer. Or learn to use OpenTX yourself...
