### ISSUE TITLE
Improved FLVSS for Horus 10

### ISSUE THREAD

**Issue by flaviomartins8** [opentx/opentx#5714]
Hi, Can you improve the FLVSS widget in Opentx2.2.1 with other parameters like 
average:
delta:
balance:
Like this one:
http://www.craftandtheoryllc.com/lipo-battery-checker-script-for-taranis-x9d-x9d-and-x9e/

**Comment by 3djc** [comment]
Again, we do supply widgets to get the community stared and as exemple, and so that individuals can do their own tailored version
