### ISSUE TITLE
bulid opentx code

### ISSUE THREAD

**Issue by skyyuzhang** [opentx/opentx#5716]
I'm buliding opentx with a problem . I do install python3.6.4 but it not work . so   how do I fix it? thankyou

-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) 
CMake Warning at radio/src/CMakeLists.txt:55 (message):
  Python not found! Most firmware and simu flavors not buildable.

**Comment by 3djc** [comment]
I'm sorry, but this place is not an support place, this should be used only to track bugs in OpenTX firmware. Please use community support forums like rcgroups or openrcforum
