### ISSUE TITLE
buliding code probled

### ISSUE THREAD

**Issue by skyyuzhang** [opentx/opentx#5717]
16:37:00: Running steps for project OpenTX...
16:37:00: Starting: "C:\Program Files\CMake\bin\cmake.exe" --build . --target all
Scanning dependencies of target firmware_translations
[  0%] Generating cz.h
[  1%] Generating de.h
[  1%] Generating en.h
[  1%] Generating es.h
[  1%] Generating fi.h
[  1%] Generating fr.h
[  1%] Generating it.h
[  1%] Generating nl.h
[  2%] Generating pl.h
[  2%] Generating pt.h
[  2%] Generating se.h
[  2%] Built target firmware_translations
Scanning dependencies of target 9x_xbm_1bit
[  2%] Generating sticks.lbm
Traceback (most recent call last):
  File "D:/opentx/radio/util/img2lbm.py", line 7, in <module>
    from PyQt5 import Qt, QtGui
ImportError: DLL load failed: %1 is not a valid Win32 application.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/opentx/radio/util/img2lbm.py", line 9, in <module>
    from PyQt4 import Qt, QtGui
ImportError: No module named 'PyQt4'
radio\src\bitmaps\128x64\CMakeFiles\9x_xbm_1bit.dir\build.make:59: recipe for target 'radio/src/bitmaps/128x64/sticks.lbm' failed
CMakeFiles\Makefile2:332: recipe for target 'radio/src/bitmaps/128x64/CMakeFiles/9x_xbm_1bit.dir/all' failed
mingw32-make.exe[2]: *** [radio/src/bitmaps/128x64/sticks.lbm] Error 1
mingw32-make.exe[1]: *** [radio/src/bitmaps/128x64/CMakeFiles/9x_xbm_1bit.dir/all] Error 2
Makefile:150: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
16:37:07: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project OpenTX (kit: Desktop Qt 5.8.0 MinGW 32bit)
When executing step "Make"
16:37:07: Elapsed time: 00:07.

# WHY?

**Comment by 3djc** [comment]
This place is for bug tracking, not end user support. Please go to community support places like rcgroup or openrtcforums
