### ISSUE TITLE
Radio : Deleting only discovered sensors (not the manualy/calculated sensors)

### ISSUE THREAD

**Issue by pointu** [opentx/opentx#5719]
An option to delete all or only discovered ?

**Comment by kilrah** [comment]
There is no way to differentiate them.

Also please disable your autoreply for the github notification address...

**Comment by pointu** [comment]
Bonjour,

Je serais absent lundi 26 février 2018, Laissez votre message en cas d'urgence extrême je vous joindrais.

Jean-Jacques Pointel
Directeur
Phone : +33 (0)1.79.97.24.00

**Comment by pointu** [comment]
And only the calculated ?

**Comment by kilrah** [comment]
Not sure it makes any sense if it's only that.

**Comment by pointu** [comment]
When u have 2/3 calculated sensor and dozen of discovered, it should be a start.

**Comment by 3djc** [comment]
Well, if you delete the discovered sensors, your calculated would likely be affected too, usulay they are based on 'discovered 'sensors anyway, no ?

**Comment by pointu** [comment]
yes but when you work on the radio it would be simpler than reenter those calculated sensors, my example is because a have a lot of duplicate sensors in a plane for experimentation, and during the work it can be tedious.

**Comment by 3djc** [comment]
Not sure about that, given all the reference issues (sensor are almost never detected in the same order), it would be very error prone to not recreate those

**Comment by pointu** [comment]
ok, understanding more about detected sensors.

**Comment by kilrah** [comment]
It takes what, a minute to delete the unwanted sensors?

**Comment by pointu** [comment]
it depend about quantity and on the radio u use...
Also they are not unwanted, it's when u are working with a long chain of sensors, and a lot of duplicate like 3 FLVSS, 3 FAS40, 2 RPM, GPS, Vario, PITOT, on term certainly 1 RB....add to this a few calculated...
I also understand i'm not the basic case, i just give some ideas to improve when i think it's interesting.
