### ISSUE TITLE
X7 Power On Delay (Make it configurable)

### ISSUE THREAD

**Issue by RCdiy** [opentx/opentx#5722]
Could the X7 power on delay be made configurable like the splash screen is?
Splash Screen x Seconds. If x is zero splash screen is disabled.
Power On x Seconds. If x is zero power on would be immediate.

**Comment by 3djc** [comment]
X7 is aligned with existing and comparable x9e

**Comment by RCdiy** [comment]
Okay, so make both configurable?

**Comment by kilrah** [comment]
#4639

**Comment by RCdiy** [comment]
For those who find this thread... #4639 will make off configurable...
