### ISSUE TITLE
No telemetry or pids when upgraded to Open_tx 2.2.1

### ISSUE THREAD

**Issue by Mont-ster57** [opentx/opentx#5725]
No telemetry or pids when upgraded to Open_tx 2.2.1 . Everything worked fine in 2.2.0 . Now no telemetry and no pids because of no telemetry. Using a Turanis QX-7

**Comment by kilrah** [comment]
Telemetry works fine on 2.2.1, you must have a configuration error and this is not the place to ask about that.

**Comment by Mont-ster57** [comment]
OK so where can I get some help on configuring it properly .

**Comment by kilrah** [comment]
See community forums like rcgroups or openrcforums.
