### ISSUE TITLE
stickrev - mega2560

### ISSUE THREAD

**Issue by ALFicek84** [opentx/opentx#5730]
Hi,

can stickrev option be enabled for mega2560 board? Im rebuilding old Futaba FX-18 and both my vertical sticks are reversed (horizontal ones goes right way, vertical inv - original FX-18 gimbals). No option in companion. 
I can select/set it when i run simulation in companion, but not on real HW.

in SIM

![inv_sticks](https://user-images.githubusercontent.com/35648852/36686778-c8740d16-1b27-11e8-8b51-0126752f7834.jpg)

and simply no way to select with real HW, jumps directly to mode select

thanx

**Comment by kilrah** [comment]
Given you have to do custom wiring why don't you jsut swap the pot wires?

**Comment by ALFicek84** [comment]
As its not "clean" solution. INV STICK feature is already implemented for other boards. 
https://github.com/opentx/opentx/issues/660
Maybe according to fact it is working in simulator it should be working at live mega2560 board too??

Swapping pots is my last solution, as pots V+H are soldered to small PCB with common GND and VCC, which is clean in my oppinion. Resoldering will just add wire garbagge.

**Comment by kilrah** [comment]
As we will be removing AVR support from 2.2 no more changes will happen there. 
We will try to make 2.1 fully functional for AVR boards and will consider enabling stickrev there.
