### ISSUE TITLE
QX7S Wireless Trainer

### ISSUE THREAD

**Issue by N3tW0rk418** [opentx/opentx#5732]
Slave/BT mode not available to enable wireless trainer in 2.2.1 on QX7S

**Comment by 3djc** [comment]
Then you haven't set your BT to trainer in radio hardware

**Comment by N3tW0rk418** [comment]
I'm saying the option is not there to enable it...unless I'm over looking it.

**Comment by 3djc** [comment]
Which one ? Slave/BT or trainer in radio hardware ?

**Comment by N3tW0rk418** [comment]
I have neither option in both radio itself and companion.

**Comment by 3djc** [comment]
What is the exact 2.2.1 version displayed on the radio (yes, companion does not know about BT)

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/36737202-cfefc040-1bda-11e8-9cbd-a89613a78e8e.png)

![image](https://user-images.githubusercontent.com/5167938/36737226-e03d7ce4-1bda-11e8-9a23-e2ae95dde068.png)
