### ISSUE TITLE
R9M has no bind button in current build

### ISSUE THREAD

**Issue by x4FF3** [opentx/opentx#5734]
Hi, 

yesterday i tried to bind R9 with 2.2.1(build from 23.02.18) on x9d. but no bind button was shown. i reflashed the build from 18.02.18 and the bind button was shown again.

KR
David

**Comment by 3djc** [comment]
Please include photo, because it seems ok here, and there as been absolutely not change in the area between the two

**Comment by 3djc** [comment]
Simu does not show an issue either
![image](https://user-images.githubusercontent.com/5167938/36787483-9396a388-1c8a-11e8-9246-53c2913d0c19.png)

**Comment by kilrah** [comment]
Not only *in the area", not a single line of code was changed in the firmware between the 14th and the 24th.

**Comment by x4FF3** [comment]
18-02-18
![img_20180301_234908](https://user-images.githubusercontent.com/19995842/36874596-c7f2cc38-1dac-11e8-94f2-3e46be7fae09.jpg)
![img_20180301_234921](https://user-images.githubusercontent.com/19995842/36874597-c81b5900-1dac-11e8-9b72-9c8c8fee1cba.jpg)

18-02-23
![img_20180301_235120](https://user-images.githubusercontent.com/19995842/36874636-f56b098c-1dac-11e8-8588-ebba1e9881ca.jpg)
![img_20180301_235141](https://user-images.githubusercontent.com/19995842/36874637-f58fc45c-1dac-11e8-879f-d0a768d96134.jpg)

**Comment by 3djc** [comment]
Those are not our compilations, right ? You can see from the code stamp (cca718008, thats 2.2.1 release code) that you are using the same source code, if it does not produce the same result, it means something is wrong with your compilation

**Comment by x4FF3** [comment]
both versions were downloaded via companionTX. 
options of the version with bind button: opentx-x9d-ppmus-multimodule-noheli-lua-luac-en
options of the version without bind button: opentx-x9d-multimodule-noheli-lua-luac-internalppm-en

**Comment by kilrah** [comment]
Aha, it helps when we actually know what you're doing. 

Then yes, external module lines seem to be broken when internalppm option is selected. 
Since you likely have no reason at all for enabling it in the first place you can use firmware without it in the meantime.

**Comment by 3djc** [comment]
As a reminder, internalppm is for people who have removed the x9 internal module to remplace it with something else

**Comment by x4FF3** [comment]
glad i could point out a bug.

**Comment by 3djc** [comment]
Yes, thx, sorry, I was thinking nightly based on your report title, glad we sorted that out. Will be fixed shortly
