### ISSUE TITLE
X10S sync overwrites model files

### ISSUE THREAD

**Issue by ufoDziner** [opentx/opentx#5735]
Hello,
  I normally make model changes in the field on the radio, and in companion when at home.  If I make changes at the field, I import the models, then save them to the local .otx file.  If I make them in the companion, I save to the .otx file, then write the models and settings to the radio.  Both of these work well.  The problem comes with sync.  It seems that no matter which way I have the SD card sync, the model files on the radio are overwritten by old files.  So, after a sync, I have to write the models and settings to the radio again.  If I want to have the current files that I just wrote to the radio synced with my local SD mirror, I have to copy them manually.

It seems like there needs to be a way to separate/specify which set of model files to use in the sync vs. the rest of the files.  This way, it would be easy to use the model.bin files off of the radio to sync with the local SD, but send the new local SD files to the radio.

Thanks

**Comment by raphaelcoeffic** [comment]
@schwabe could this be related to the file time stamps not being updated properly on FAT?

**Comment by raphaelcoeffic** [comment]
@ufoDziner could you please tell me which options you use for the SD card sync?

**Comment by ufoDziner** [comment]
@raphaelcoeffic I'm attaching some screenshots to show the settings and results.  The otx1.png shows the settings and and my saved .otx file.  Just before taking that screenshot, I imported the model settings from the radio and saved them to my .otx file to ensure my local file is the most current.  I then imported them again (which shows as "document2.otx" in the third image).  Next Icompleted a sync using the sittings in the first image.  The second image shows the summary after I completed the sync.  Finally I imported the model settings from the radio after the sync ("document3.otx" in the last image).  As you can see, my radio settings are now different than what I had before.  I had made no recent changes locally, only on the radio.  It seems that no matter what I do on the radio, it will always get overwritten with the local settings during a sync.  

![otx1](https://user-images.githubusercontent.com/7434287/38698570-609ea872-3e4a-11e8-9e35-24f55a6e79cd.png)
![otx2](https://user-images.githubusercontent.com/7434287/38698576-652b4efe-3e4a-11e8-8d05-41aa507fb022.png)
![otx3](https://user-images.githubusercontent.com/7434287/38698586-6aaac99a-3e4a-11e8-8512-7fc52925ba1a.png)

**Comment by raphaelcoeffic** [comment]
@ufoDziner there must be an issue with the timestamps. Could you please check the timestamps for the files on the SD card and in your local directory after each of the steps you took? At some place, something must be screwed there.

**Comment by mpaperno** [comment]
For 2-way sync to work, the timestamps must be correct/match on both file systems.  The fact that it has something to sync right after running a sync suggests they're not.  (Unless the prior run was also in test mode, of course.)

It might be useful to add a file/folder name filter to the sync settings.  Can't remember if I only thought about it at the time, or if I left a hook in place already (just no UI).

**Comment by ufoDziner** [comment]
Okay.  I did another test today.  **Beware of all the screenshots.**  The sequence of events is as follows:

Deleted a unwanted model from the radio.
Start opentx.
Open my current .otx file.
Connect radio.
Import model settings.
![otxss2](https://user-images.githubusercontent.com/7434287/38761893-84fbc226-3f3b-11e8-96c6-1b5f63d41580.png)

(files before any sync)
![otxss1](https://user-images.githubusercontent.com/7434287/38761932-d2aa3e8a-3f3b-11e8-951b-6ff2b0718176.png)

Save new imported model settings as current.
![otxss3](https://user-images.githubusercontent.com/7434287/38761906-95f4be52-3f3b-11e8-90a6-785cefb05fe0.png)


Copy a new sound file to the Radio's SD card (Drive D:).
Sync files with radio as the master.
![otxss4](https://user-images.githubusercontent.com/7434287/38761922-bb9465e0-3f3b-11e8-9993-bf239c5c55e8.png)

![otxss5](https://user-images.githubusercontent.com/7434287/38761939-e0526968-3f3b-11e8-9523-a662823f962f.png)


Make some changes to the models in companion to use the new sound file I copied to the SD card.
Save the .otx file.
Write models and settings to radio using the appropriately named button.
![otxss7](https://user-images.githubusercontent.com/7434287/38762336-a36b8a1c-3f3f-11e8-9e6d-bbfc5e565112.png)


Sync again to get my local SD backup files updated with the model settings that I just wrote to the radio.
![otxss6](https://user-images.githubusercontent.com/7434287/38762065-fe1e79fe-3f3c-11e8-8bee-bba8152b40d3.png)

![otxss8](https://user-images.githubusercontent.com/7434287/38762084-2b7a7ff6-3f3d-11e8-8b7e-8bac853c1f7b.png)


As you can see here, it reverted some of the files back to some other form.
![otxss9](https://user-images.githubusercontent.com/7434287/38762328-906e94c2-3f3f-11e8-8d81-bb9a1c02cbbc.png)


I then had to use the write models and settings button again to get the files on the radio correct.
![otxss10](https://user-images.githubusercontent.com/7434287/38762324-806c4204-3f3f-11e8-99ec-bbdece974d9c.png)

So, I'm not sure what the sync is doing.  As I understand, when I make a change to my .otx file, and write that to the radio, it changes the model files on the radio.  Nothing changes the local SD card backup except for sync.  Which means if I make a change in companion I need to accomplish the following steps:

Make change in companion.
Save updated .otx file.
Write model and settings to radio.
Sync SD card with radio as the master to update the local files to match my new radio files.

Please let me know if what I'm doing is wrong, but I'm pretty sure something is broken.

Thanks

**Comment by kilrah** [comment]
Can you post your 3 companion settings tabs?

**Comment by mpaperno** [comment]
Why are some of the files timestamped 2019?  Either the computer or radio seem to be living in the future... ;-)

**Comment by raphaelcoeffic** [comment]
@ufoDziner you should basically delete your local SD backup, and re-sync. If your PC and radio are using the same time, it should then work. The old files on your PC with timestamps in 2019 are the issue: they will get never get overwritten, and the issue will first be solved in 2019 ;-) The question is: how did they land on your PC?

@mpaperno probably not directly related to this issue, but wouldn't it be a good idea to be able to sync the time from PC with companion? Or at least detecting a timestamp issue before synchronising?

**Comment by mpaperno** [comment]
@raphaelcoeffic Uh, sure, that would be nice...  :smiley:   We'd need some kinda API for that!  (Or do we have that somehow?  Besides the "devs-only" CLI.)  When we're syncing with SD card the radio is most likely off anyway.  But... yet another option to add to sync would be a maximum time difference.  (And make it ignore system files somehow!)

**Comment by raphaelcoeffic** [comment]
@mpaperno I just opened #5829 for that purpose.

**Comment by raphaelcoeffic** [comment]
@mpaperno ignoring sys files is a good idea anyway ;-)

**Comment by raphaelcoeffic** [comment]
@mpaperno by the way: what about correcting time stamps situated in the future while scanning / synth the SD card (with some acceptable delta).

**Comment by mpaperno** [comment]
Correcting to what date/time?  I don't really like the idea of messing with the timestamp, even if it looks wrong.

However it should probably skip files with future timestamps altogether.  Probably doesn't even need to be an option... future dates are illogical, captain!  :vulcan_salute: 

As a reminder, sync never deletes any files "missing" from source but present in the destination.  Unwanted files need to be deleted manually.

**Comment by ufoDziner** [comment]
@raphaelcoeffic Okay.  I created a blank local SD directory and told companion to sync from the radio to the local folder only.  Here are the results.

![otxfresh1](https://user-images.githubusercontent.com/7434287/38779671-637c24a6-4080-11e8-9df3-658d24e6b37b.png)

![otxfresh2](https://user-images.githubusercontent.com/7434287/38779673-67576180-4080-11e8-92e9-68d6c27651ec.png)

![otxfresh3](https://user-images.githubusercontent.com/7434287/38779675-6adaac18-4080-11e8-8caf-c23da0a80968.png)

The 2019 files are coming from the radio.  Do I need to delete them there first?

**Comment by raphaelcoeffic** [comment]
@ufoDziner you probably don't want to kill these models by deleting the files. But you could try to localise to which model they are tied, make some modifications to these models so the date gets written properly, and then sync to blank directory on your PC. Please control that all files on SD have a correct timestamp (NOT in the future), before doing the sync to your PC.
