### ISSUE TITLE
Possibilty for logbook/total time?

### ISSUE THREAD

**Issue by marcogpw** [opentx/opentx#5738]
Is there a possibilty to have a logbook of sorts? After every flight you either reset the timer or after every transmitter shutdown the previous flight times are lost, would be nice to see you total time per model. Just a question if at all possible or a nice thing to have for the future ? Maybe there is something already, tried the search function, but did not find anything.
Marco

**Comment by 3djc** [comment]
This is not a support site, but a bug tracking system. Please use support groups like rcgroups or openrcforum. Maybe you can also have a look at the ‘persistant’ property for timers
