### ISSUE TITLE
Companion 2.2.x Model Edit Inputs Name Corruption

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#5740]
Steps to reproduce for move up and down:
1. Add a new line or use existing line with an input name
2. Highlight the line
3. Move it up or down
4. Name remains and is not copied to the new location with the other details
5. Open the moved line - moved details except missing name
6. Cancel dialog
7. Open the old position (with the name only displayed) - old name displayed with default values
8. Cancel dialog
9. Name removed from list
10. Close model edit
11. Edit model
12. Corruption remains for the moved line

Duplicate and Paste drop the name from the copied line.
Cut removes the name as expected.

Tested on Win 10 and Ubuntu Linux 10.04

**Comment by kilrah** [comment]
What radio type selected?

**Comment by elecpower** [comment]
Taranis X9D+
