### ISSUE TITLE
incorrect GPS display

### ISSUE THREAD

**Issue by hobby1946** [opentx/opentx#5741]
Transmitter Horus X10 OTX V2.2.1
The GPS data is only partially displayed.
The N position is always 0!
In telemetry and in the display
This is sometimes the case with the original FRSKY GPS

**Comment by kilrah** [comment]
Displayed where, using what widget/page,...

**Comment by 3djc** [comment]
We need exemples, like simu or photo. It might depend from your position and/or setting (nmea, dms)

**Comment by hobby1946** [comment]
Hello,

Both GPS displays have worked until X9D + and OTX V2.1.8.
With X10 and V2.2.1 it looks like this:

![gps01](https://user-images.githubusercontent.com/19935070/36985030-843d087c-2096-11e8-8ae3-8da17d6b1b95.jpg)

![gps02](https://user-images.githubusercontent.com/19935070/36985055-8e50676e-2096-11e8-99c6-103caa899d06.jpg)

![gps03](https://user-images.githubusercontent.com/19935070/36985067-95a32f74-2096-11e8-9c80-db2027f09da6.jpg)

Transmission protocol GPS1

![zaggo log](https://user-images.githubusercontent.com/19935070/36985126-bb2ce8fc-2096-11e8-8451-ed83f5979615.jpg)

The error with GPS1 ( 0x800-15) is always - also with other ID
At GPS2 ( 0x800)-4) sometimes (rarely)

**Comment by hobby1946** [comment]
It might depend from your position and/or setting (nmea, dms):
 the error is the same for both settings

**Comment by 3djc** [comment]
From your issue title, I thought you had a display issue, but from what you present here, you gps data is not read correctly. Could you try logging it and see if value are 0 too ?

**Comment by hobby1946** [comment]
ll try that.
Where can you check that?

The display works with X9D + and V2.1.8
With X9E and V2.1.9 no more.

**Comment by hobby1946** [comment]
The value GPS1 is not logged although ticked
The field GPS1 can not be found in the LOG

**Comment by hobby1946** [comment]
![gps05](https://user-images.githubusercontent.com/19935070/37018720-ad78639c-2115-11e8-9d3b-f9c20b387696.JPG)

![gps06](https://user-images.githubusercontent.com/19935070/37018733-ba427f22-2115-11e8-8730-b389f5f095f2.JPG)

**Comment by 3djc** [comment]
All the info here make me think there is an issue with the telemetry sent to OpenTx, not in OpenTx itself.
On X10, in statistics/debug screen, the last field is Tlm RX Errs, what is the value ?

**Comment by hobby1946** [comment]
Sorry, where is the debug screen?
What do I have to dial?

**Comment by 3djc** [comment]
Long enter, statitstics, pgdn

**Comment by hobby1946** [comment]
OK.
Now while trying (but not always)

Display after switching on transmitter and receiver

![gps 09](https://user-images.githubusercontent.com/19935070/37021767-04ddeb92-2121-11e8-887c-3189de6bf70f.jpg)

![gps 11](https://user-images.githubusercontent.com/19935070/37021785-142d1c80-2121-11e8-8f44-6a71fddcc785.jpg)

Display after reset flight data

![gps 10](https://user-images.githubusercontent.com/19935070/37021822-336b7e7a-2121-11e8-9424-51d129295486.jpg)

![gps12](https://user-images.githubusercontent.com/19935070/37021923-8f3da534-2121-11e8-92fc-80208f630783.jpg)

**Comment by kilrah** [comment]
Can you say which GPS sensors they are and where they're connected?

**Comment by hobby1946** [comment]
GPS1
von Naza Lite über Zaggometry  (0x800/15)

GPS2
Frsky GPS (0x800/4)

**Comment by kilrah** [comment]
And what happens if you connect only one of them at a time?

**Comment by hobby1946** [comment]
Nothing changes when I connect the GPS individually.

GPS1 almost always works

GPS2 almost never (not even at 0x800 / 4)
but all other values are correct
only GPS-N is 0

**Comment by kilrah** [comment]
And if you create a new model and only connect/discover the frsky GPS?

**Comment by hobby1946** [comment]
the Frsky GPS is displayed to 99% correct.
this is also the case with a new model with only GPS

the other GPS shows 99% no N position
even with a new model with only GPS
All other data is ok

The same model (copter) attached to a X9D + with V2.1.8
displays both GPS position correctly

**Comment by hobby1946** [comment]
I tied the copter to an X9E.

at otx V2.1.8 / 9
no GPS1 value appears here (only GPS1)

![gpsv218](https://user-images.githubusercontent.com/19935070/37044451-c90ea0fa-2163-11e8-8849-c7b7743eca36.JPG)

![gps v219](https://user-images.githubusercontent.com/19935070/37044464-d01e77e4-2163-11e8-8e93-43ca194ec4c6.JPG)

with otx V2.2.1 only the N-Pos does not appear

![gpsv2 2 1](https://user-images.githubusercontent.com/19935070/37044481-dbe98bae-2163-11e8-84a5-fffe0e98a121.JPG)

**Comment by hobby1946** [comment]
Hello

I got a X9D +  (Non-Eu) and the same copter was bound.
with OTX V2.2.xxx also the N-position was missing

But with OTX V2.1.8 all GPS data was available!
Also the N position!

![gps ok1](https://user-images.githubusercontent.com/19935070/37112324-5adc9f94-2242-11e8-841f-8412ac01a7c6.JPG)

![gps ok2](https://user-images.githubusercontent.com/19935070/37112338-6390054a-2242-11e8-8863-0f150ef8547b.JPG)


The Zaggometry sends all data properly

what I noticed is :
Normally, first the N-Pos, then the E Pos is displayed, then the position is OK
in the faulty display, first the N-Pos and then the E-Pos are displayed ????

What was changed in V2.2.x ?
With the transmitters X9E and x10 also V2.1.8 does not work .

**Comment by hobby1946** [comment]
here the log file of my X10 with v2.2.1
only the E position is displayed
the N position is 000 ..

![gps](https://user-images.githubusercontent.com/19935070/37213859-9066f002-23b3-11e8-8c36-4d66d5b898b1.JPG)

**Comment by hobby1946** [comment]
Here is a data protocol from the S-Bus at the receiver
GPS ID 0x800 - SubID 15
The transmitter does not indicate an N position


[GPS1-0x8E-15 Zaggo.zip](https://github.com/opentx/opentx/files/1800776/GPS1-0x8E-15.Zaggo.zip)

**Comment by hobby1946** [comment]
Hello
the error is localized.
In the telemetry sensor falsely no byte stuffing is performed!

The transmitter determines for the north position (in my place) an incorrect checksum and therefore North is then displayed with 0.
