### ISSUE TITLE
Add a volume parameter to lua playTone() function

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#5745]
Taranis X9D+ - OpenTx 2.2.1.

You use this function when you have some specific need so you certainly need to set its volume too.
For instance, I have designed my own vario sound in a script using playTone but I find it too loud compared to the other sounds: I would like to lower it (the same way as for the original vario sound).

**Comment by kilrah** [comment]
These will play using the "beeps" volume. 
It is not really possible to give lua control of that without some potentially undesirable implications.

**Comment by pindeslandes** [comment]
Good to know, thank you. And good news for me as I don’t use beeps!

**Comment by kilrah** [comment]
Well you use them a bit without realizing (button presses, trim key beeps etc)
