### ISSUE TITLE
Confirm antenna is connected before powering external module. 

### ISSUE THREAD

**Issue by geofrancis** [opentx/opentx#5747]
Pretty much any uhf system will be destroyed if the handset powers on without an antenna connected. So if there was a warning that makes you confirm the antenna is connected before it powers on the external module. Would stop a lot of modules being damaged.

Ideally it should be a configurable option since 2.4 modules generally have short antennas and can be left in place.

Graupner radios do something similar where they won't transmit untill you hit ok on the screen.

**Comment by 3djc** [comment]
Maybe it does not require yet another model setting. We are considering reviewing model powerup / change sequence so that model notes are displayed before turning on module. That would be a simple way to achieve this (and much more) without making the UI more complex

**Comment by geofrancis** [comment]
Just a confirmation like the switch or throttle warning would be enough when an external module is active. Just something to say check the antenna is connected.

**Comment by 3djc** [comment]
Not quite, because many will complain that their external module does not require such a check (like multimodule for example)

**Comment by geofrancis** [comment]
Yes that's why I said that it would have to be an optional check. Since 2.4 modules usually keep the antenna on all the time. But uhf do not.

**Comment by geofrancis** [comment]
In not really bothered how it is done but it's something that needs to be done especially now tbs and frsky are pushing modules to racers who generally stuff equipment into small bags that require removing antennas.

**Comment by geo502** [comment]
I agree with @geofrancis ,  A lot of the Crossfire users haven't completely changed over all of their models to use crossfire so they have a mixed bag of models using internal and external TX modules.  I keep my transmitter in a bag and have to take of the external antenna when I pack away and  have flown away 1 too many times now with no antenna on and ended up with failsafe 50 yards and crashing to the ground. I am looking into options to help myself remember this now, like a preflight-checklist or safety switch with custom functions but  an actual warning that is optional like the switch or throttle warnings during startup would be a very nice feature.
