### ISSUE TITLE
Translate ‘telemetry’ in French by ‘télémesure’, not ‘télémétrie’

### ISSUE THREAD

**Issue by pindeslandes** [opentx/opentx#5749]
Taranis X9D+ - OpenTx 2.2.1.

Here (and maybe elsewhere):
- In the telemetry setting page, ‘Désactiver alarme télémétrie’ isn’t correct.
- In category picklists of sources, ‘Télémétrie’ is displayed instead of ‘Télémesure’.

**Comment by kilrah** [comment]
It is a word that is abused so much in common language that people were complaining when it was correct.

**Comment by pindeslandes** [comment]
Quoi ? Il vaut mieux satisfaire ceux qui ont tort que faire les choses correctement ?
Dans ce cas, allons jusqu'au bout : traduisons"transmitter" par "transmetteur", "receiver" par "receveur", "trainer" par "traineur", "minus" par "minus"...
