### ISSUE TITLE
Ocassional problem with SD Card not beeing detected by Taranis QX7S on OpenTX 2.2.1

### ISSUE THREAD

**Issue by GordonFPV** [opentx/opentx#5752]
Hi,
I currently have the problem, that the SD card ocassionaly does not get detected by the radio - most noticeable through the missing Audio in this case.
It happens approximately every 20th time I power on the radio, but I did not find a way to reproduce the problem at the moment. Repowering the radio solves the problem in most cases, however sometimes followed by Audio stuttering.
Formatting the SD Card and trying a second one didnt help. I am not running any LUA scripts.
Is ther any known issue regarding this topic?
Thanks!

**Comment by 3djc** [comment]
No issue known, likely a hardware issue

**Comment by GordonFPV** [comment]
All right, thank you.
