### ISSUE TITLE
Companion bug with creating and then using Edge logical switches

### ISSUE THREAD

**Issue by timrowledge** [opentx/opentx#5753]
Companion 2.2.1 on OS X

Trying to make and then reference an Edge LS is a bit of a problem.

As an example
make a new file
make a new model
make L01 (I used a=x/S1/Ch31)
make L02 (Edge/AilTrimRIght/0.0/infinte)
Now when I try to make L03 and attempt to set V1 to refer to L02 - the Edge - it is not in the menu!

*sometimes* if you close the model edit and reopen it you can get the L02 in the menu. 
Very confusing and awkward.

**Comment by 3djc** [comment]
Known issue, fixed already, will be in next release

**Comment by timrowledge** [comment]
Excellent news. I did try to find a prior report covering this but failed.
