### ISSUE TITLE
Horus missing telemetry packets

### ISSUE THREAD

**Issue by rimb05** [opentx/opentx#5757]
When running a widget lua script on an x10, the telemetry seems to miss some packets.  The same script ported to an X7 works fine with no missing data.

This is especially noticeable when using Passthrough mode connected to an Ardupilot.  9000 packets (Mavlink messages) are often missing characters for example.

Packets that do come through pass the CRC in checkSportPacket(), so this isn't an issue with corruption.

The same problem happens with both internal and external RF modules (I tested both).

**Comment by 3djc** [comment]
Could you give us more details to try to replicate ?

**Comment by rimb05** [comment]
Sorry, this was caused by an unrelated issue on my end.
