### ISSUE TITLE
OpenTX Companion: New Logical Switches not appearing in drop down lists

### ISSUE THREAD

**Issue by MrD-RC** [opentx/opentx#5759]
If I double click on a model and enter the editor, go to the Logical Switches tab and create a new Logical Switch, it will not appear in drop down lists until I exit the editor and re-enter it.

Example 1:
I create 
`L01 - a<x | Thr | -98`
then go to add L02 below which uses L01 in V1. L01 will not appear in the drop down list, neither will L02 appear. The switch I'm trying to create should read.
`L02 - OR | L01 | L02 | SF^ | 0.0 | 0.5`
This would create an arm switch that cannot arm until the throttle is below -98.

Example 2:
After creating L01 in the first example, I head over to the Special Functions tab, wanting to create one based on L01. L01 will not appear in the list.

I have noticed that the drop down lists seem to be cached as I had 2 logical switches, closed and re-opened the editor, and they appeared in the list on the Special Functions page drop downs. I proceeded to delete the Logical Switches, but they still appeared in the drop down lists on the Special Functions page. 

I've not noticed this issue on older versions of Companion, I'm currently using version 2.2.1, Dec 2017

**Comment by 3djc** [comment]
Known issue, fixed already, will be available in 2.2.2
