### ISSUE TITLE
X9E duplicate in companion menu selection, X9D missing.

### ISSUE THREAD

**Issue by Freddan-67** [opentx/opentx#5760]
I Just installed OpenTX 2.2.1. I can not select Taranis 9D, only Taranis 9D+ as transmitter.
![skarmklipp 2018-03-12 14 16 00](https://user-images.githubusercontent.com/7888909/37299574-fd0a0506-2623-11e8-819f-3caaeaefddd4.png)
Sorry for the Swedish in the menu but I hope you get the picture. It is the same in English language.

**Comment by Freddan-67** [comment]
Some more tinkering, and it seems like if I select "Taranis X9E {9D?}" I get a firmware named 9D. So the real problem is just the name in the menu.

**Comment by schwabe** [comment]
There is no Taranis 9D. See https://www.open-tx.org/radios. 

Sorry, reread the issue.

**Comment by kilrah** [comment]
Probably a translation issue.
