### ISSUE TITLE
OpenTX 2.2.1 Crash if I download firmware before ever entering the firmware menu.

### ISSUE THREAD

**Issue by Freddan-67** [opentx/opentx#5761]
Now I cannot reproduce the problem. 
On first run of OpenTX 2.2.1 It suggests to download new firmware just after start. When the download window is show, but just before download starts I get a "compilation error" and OpenTX crash.
![skarmklipp 2018-03-12 11 17 47](https://user-images.githubusercontent.com/7888909/37299725-5bba7518-2624-11e8-8924-c0cdf6edfc95.png).
If I go into the settings menu and for instance select lua and sqt5font OpenTX does not crash, and I cannot re-create the error.

**Comment by kilrah** [comment]
What radio type selected?

**Comment by mpaperno** [comment]
The whole startup sequence has been reworked and this issue fixed in 2.2.2.
