### ISSUE TITLE
OPEN TX RESET ALL MY RADIO

### ISSUE THREAD

**Issue by cbsbedoya93** [opentx/opentx#5763]
ive been havinf this problem since i got the horus 10, intall opentx everything works perfect but suddenly any day i turn off the radio and when it comes back on again is a new radio. no configurations, no models, everything is gone. it happen 4 times now, and its driving me crazy. im starting to think that there is a problem with open tx or this radio is just crap. any one know what could be happening this?

**Comment by kilrah** [comment]
MicroSD card probably defective, everything is stored in there. Try replacing it.

**Comment by cbsbedoya93** [comment]
i tried 3 different sd cards. same thing

**Comment by kilrah** [comment]
Then probably a hardware defect on the radio, see your dealer for warranty.
