### ISSUE TITLE
Issue with powering up and down Horus x10

### ISSUE THREAD

**Issue by rimb05** [opentx/opentx#5765]
If you try powering down an x10 while a receiver is still connected it will freeze upon booting up again if you try to power up right away.

In other words:

- Make sure a receiver is connected
- Hold down the power button for a few seconds until you see the message asking you to confirm
- Press Enter to confirm the message
- After it shuts down, immediately press the power button again to try and power up
- The OpenTX logo displays but the unit is locked up and never starts

To work around the problem, you need to hold down the power button for 10 seconds until it force quits, then wait 20 seconds before trying to power up again

This same issue sometimes happens even without a receiver connected, but it's easy to reproduce with one connected.

**Comment by Oldgibber** [comment]
I've been playing with this. OpenTX2.2.1, Horus X10S. I cannot reproduce it. My tx works fine every time.
