### ISSUE TITLE
V2.2.2N549 Setting GVAR Min , Max and adjust with F1,F2,F3 

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5770]
I am testing GVAR Range settings  Min / Max  and adjusting this Range with F1,F2, F3 turning

When I set the GVAR Min/Max Range  and want to set this range with a analogpoti F1,F2,...
I can there not use the full turning range  of 0 to 270° of the Poti
think Poti is not recalculated to the New Range of the GVAR

Is this correct?
![2018-03-18_080837](https://user-images.githubusercontent.com/6217896/37563679-952f0fc8-2a86-11e8-9bc8-fe4251cd52a3.jpg)

Before V2.2.1  I use a free mixer, to calculate the Min/ Max range  of a GVAR 
adjusting with a Poti´s full turning range

**Comment by kilrah** [comment]
> think Poti is not recalculated to the New Range of the GVAR

That has never been the intention.
