### ISSUE TITLE
9x (stock)- Invalid Board - 2.2.1

### ISSUE THREAD

**Issue by csorrows** [opentx/opentx#5775]
When trying to download the firmware for 9x (stock board) I get an "Invalid Board" error. It seems the files are not there?

Using OpenTx Companion 2.2.1

**Comment by 3djc** [comment]
Yes, support for AVR board has been removed from 2.2.1. Please see more info here : http://www.open-tx.org/2018/02/26/avr-pull

**Comment by csorrows** [comment]
My EEPROM was wiped updating to 2.0 even though I selected to backup and restore.. It seems EEPROM issues have been around longer. I just reconfigured everything. I hope you guys figure out the issue. Have a great week!
