### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by cperedamas** [opentx/opentx#5777]
I am using Companion 2.2.1 on Windows 10 with a Horus X10S.  I have followed all the steps but not matter what program settings I choose, I get "unable to check for updates" both when the program boots up and when I try to download the firmware.

I am using Windows defender and Companion has access through the firewall.  Running companion as admin changes nothing.  I can read the firmware to back it up, so there is communication with the radio.

Below is how the software is configured.

![image](https://user-images.githubusercontent.com/37580711/37652553-47e9d832-2c12-11e8-8835-72a8023b0c42.png)
![image](https://user-images.githubusercontent.com/37580711/37652575-59c525b6-2c12-11e8-8646-c3c52cd51feb.png)

**Comment by 3djc** [comment]
You seem to have an issue that is preventing companion to access the OpenTX servers. The servers are running fine, so it is likely local to your PC, network or ISP, difficult to say from here.

You can start with a ping on our servers : ping downloads.open-tx.org

**Comment by cperedamas** [comment]
Thanks for the fast reply.  I'll try it when I get home.  I am using FIOS.  Have there been any complaints about them blocking your server?

**Comment by 3djc** [comment]
No, we are not aware of any difficulties getting to our servers, but it is the nature of Internet to sometimes have interconnections that go down for short periods. It could be something like that among other things of similar probabilities

**Comment by cperedamas** [comment]
It was my FIOS router firewall setting.  Had to be lowered to minimum security.  In case someone else has a similar problem.
