### ISSUE TITLE
Q X7 - Expected ver 2.2V0013 error

### ISSUE THREAD

**Issue by Skallatorc** [opentx/opentx#5783]
Taranis Q X7
Firmware: opentx-x7-lua-en-2.2.1
SD Contents: sdcard-taranis-x7-2.2V0013

Error: Expected ver: 2.2V0013

I purchased this tx a few days ago, updated the firmware and bootloader, downloaded the proper SD Contents file.

I have copied and extracted the zip directly into the SD card, I have deleted, formated, and copied the extracted files from my PC. It has not corrected the alert.

I have verified that the version is correct via the .version file.

**Comment by 3djc** [comment]
You did something wrong somewhere. The process you describe is the right one, but somewhere in its execution, there is an issue. Difficult for us to say where

**Comment by Skallatorc** [comment]
Wow, it's that simple?

No questions? No did you restart the computer, are you sure the tx is in?
Not in India in a tech support where house by chance?

I have followed the OpenTX website directions, multiple YouTube videos by
skilled people who did the very same steps that fixed theirs, etc

How about some suggestions instead of "sorry but you screwed up and not
worth helping"

**Comment by 3djc** [comment]
Since this is not a end support site, but a bug tracker, yes, "that simple". For support, you should try user support forum like rcgroups or openrcforum.

**Comment by Skallatorc** [comment]
Thank you for the recommendations.

**Comment by Skallatorc** [comment]
Just an update, potential bug.

Turns out it wasn't the execution that was the issue. I installed
sdcard-taranis-x7-2.2V0010
and the SDCard folders are listing as they should when editing the
settings, sounds are working but the error still comes up.

The bug seems to be in relation to the OS version and the recommended CD
contents file.
