### ISSUE TITLE
Feature request: Companion GV print out

### ISSUE THREAD

**Issue by Roitellet** [opentx/opentx#5792]
A small but quite helpful improvement can be done to the print out of the settings:
Pivot the table with the GV versus the flight modes in the output so the x,y match the arrangement in Taranis. 
I take the printout to the field and when I need to update a GV I have to search the right one in the transmitter by counting. If the print out is aligned, then there are less errors possible.

**Comment by elecpower** [comment]
See your need.
However the screen layout can vary between radios and the print format tries to be radio agnostic. In 2.2, for ARM radios, extra parameters were added to GVs and subsequently to the print out which makes swapping axis not really practical from a formatting perspective. Also the same layout is used for model comparison.
A possible option could be to save the print to a html file then slice, dice and print with a script.
