### ISSUE TITLE
 two connections labelled p400 and P401 

### ISSUE THREAD

**Issue by sukru1968** [opentx/opentx#5802]
inside the taranis qx7 there are two connections labelled p400 and P401 
is it posible to use for extra switches??

**Comment by schwabe** [comment]
there are already open issues about extra switches in x7

**Comment by schwabe** [comment]
https://github.com/opentx/opentx/issues/5330

**Comment by sukru1968** [comment]
i m a newbee can you explain for x7

**Comment by sukru1968** [comment]
i have qx7 and opentx2.2

**Comment by schwabe** [comment]
Read #5330. In short, wait for OpenTX 2.3
