### ISSUE TITLE
Bug in BattCheck Widget

### ISSUE THREAD

**Issue by Gewe99** [opentx/opentx#5804]
local function getCellPercent(cellValue)
 --## Data gathered from commercial lipo sensors
 local myArrayPercentList = ...
 {{3, 0}, {3.093......
 local result = 100 -- -> Add this line! Otherwise error when starting the Widget while one cellvoltage is greater than 4,2V  (returning a Nil value...)
 for i, v in ipairs( myArrayPercentList ) do
 if v[ 1 ] >= cellValue then
 result = v[ 2 ]
break
 end
 end
 return result
 end

[main.zip](https://github.com/opentx/opentx/files/1879609/main.zip)

Please place the code in the sdcard-horus-2.2V00xx.zip

Regards Dirk

**Comment by 3djc** [comment]
Are you using high voltage lipo ?  if not you should not have more than 4.2, if yes, then the table values are likely wrong

**Comment by Gewe99** [comment]
This happen sometimes if I connect a lipo very fast after charging to the model.

The initialisation of the result prevents that error...

**Comment by 3djc** [comment]
Yes, but it makes me think that I also need to check for highers values to prevent display of incorrect stats for HV lipo

**Comment by offer-shmuely** [comment]
fixed as pert of batt-check updates on pull request #6412
can close this issue after accepting the pull request

**Comment by offer-shmuely** [comment]
fixed as pert of batt-check updates on pull request #6412
can close this issue after accepting the pull request

**Comment by offer-shmuely** [comment]
please closed this bug (fixed in #6412)
