### ISSUE TITLE
Bug in GPS log data - position string doesn't include minus signs where required

### ISSUE THREAD

**Issue by Bill-Glover** [opentx/opentx#5807]
OTX 2.2.1 on X9D. Flying at a location west of the Greenwich meridian, the single "GPS" position data column in the logfile is missing the negative sign on the longitude value. This causes the position to flip to the east side of the meridian. The solution would be to add "N" and "W" labels to the text string to qualify the lat and long figures, or include minus signs where appropriate. The data displayed on a telemetry screen on the Tx is correct with "N" and "W" specified against the lat and long. The issue is just with the value written to the logfile, but it means the wrong location is shown if viewed in Google Earth via Companion.

**Comment by 3djc** [comment]
I will need more details, I just tried and I have negative values:

```
Date,Time,AltG(m),RxBt(V),RSSI(dB),Alt(m),RPM(rpm),GPS,Rud,Ele,Thr,Ail,F1,F2,F3,F4,S1,S2,LS,RS,SA,SB,SC,SD,SE,SF,SG,SH,LSW,TxBat(V)
2018-04-08,09:12:51.120,0,5.2,75,0.0,0,53.381523 -6.765141,0,0,-1024,0,-126,-56,0,0,-1024,-262,0,0,-1,-1,-1,-1,-1,-1,-1,1,0x0000000000000000,10.4
```

**Comment by jtaylor2** [comment]
He posted this problem on RC Groups https://www.rcgroups.com/forums/showpost.php?p=39470678&postcount=53595 .  He is less than a full number west of the prime maridian at "51.492451 N 0.733206 W".  I haven't had much chance to look but I suspect the abs remainder in log.cpp  has something to do with it.
```
if (telemetryItem.gps.longitude && telemetryItem.gps.latitude) {
                div_t qr = div((int)telemetryItem.gps.latitude, 1000000);
                f_printf(&g_oLogFile, "%d.%06d ", qr.quot, abs(qr.rem));
                qr = div((int)telemetryItem.gps.longitude, 1000000);
                f_printf(&g_oLogFile, "%d.%06d,", qr.quot, abs(qr.rem));
```

**Comment by Bill-Glover** [comment]
Thanks folks. I have attached a zip containing the logfile and an OTX of the model. The longitude values in the GPS column of the logfile should be negative for this location (e.g. -0.733206).

[Vulcan Y6 data.zip](https://github.com/opentx/opentx/files/1887374/Vulcan.Y6.data.zip)
