### ISSUE TITLE
Can't read model/settings w/Ubuntu

### ISSUE THREAD

**Issue by jimpriest** [opentx/opentx#5808]
Ubuntu 16.04
Turnigy 9xr-Pro (latest bootloader 2.6)
OpenTX 2.2.1 (lastest firmware)

I updated all this on Windows but now can't connect on Linux.  

I start my radio, plug in USB - it goes into bootloader mode.  The two drives (SD card) are displayed.  So I have a connection.

I start Companion. But I cannot read a model.  It displays loading indicator, I hit close, but nothing is displayed.  I can create a new model - write it to the radio with no errors.  But it will not read anything back?? 

I tuned on debug but nothing is written anywhere. And if I unplug radio and turn it off/on, the Model IS saved to the radio. I just can read it again in Companion.

**Comment by kilrah** [comment]
Bootloader for the 9XR-Pro isn't made by us, and if it works on Windows the issue is likely the configuration of your Linux system.
