### ISSUE TITLE
Negative expo in mixes errors

### ISSUE THREAD

**Issue by stephendevelop** [opentx/opentx#5816]
For example, you take the Aileron on input 1
You define a mix for channel 1, putting input 1 as input and giving it a negative expo.
When you don't use the trims, all is working great.
When you for example trim to the right and you move the stick to the outer right position, it jumps back all the way to the other extreme,  so to the max output for the left position.

I'm using OpenTX 2.2.1 (cca71808)

**Comment by elecpower** [comment]
What radio?
Do you get the same affect if you reverse the directions?
There is a known bug that very large values cause this 'inversion' result.

**Comment by stephendevelop** [comment]
Hi,

I have a taranis X9D Plus.
But the simulator on the companion software shows the same issue, just put
a negative expo in a mix and use trim on that channel.

Just tested it with small values, same result

My input:

My Mix:

My Result, with a little bit of trim to the right, just before the end of
the stick throw,



At the end of the stick throw,




So the value jumps from 19% to -60 at the end when you put stick to the
right ( side to where it was trimmed )


Regards
