### ISSUE TITLE
Horus Lua Widget strange behaviour: options, vars, function memory

### ISSUE THREAD

**Issue by n9rai** [opentx/opentx#5818]
have a strange behavior of my Lua widgets. At first I used the same widget in different models but with different options. This had the consequence that in model 1 the options of model 2 showed effect. I rewrote the widgets and also used different names for the options. Now the Horus can not remember which widgets is set on the model and I get after switching on a blank screen. I put the widgets back in the telemetry menu and they work. I turn off and on the Horus and again they are gone ...

I tried the following:
Widgets rewritten (all variables and functions local) -> no change
Models deleted and recreated -> no change
FrOS and again OpenTX geflsht -> no change

You can find my widget here:
https://github.com/zenuavsolutions/Horus-Mavlink-Telemetry

**Comment by lshems** [comment]
Hi,

Make sure the folder name of the widget is not to long, otherwise settings are not saved. I think that is part of your problem.

Settings between models is strange, but could result from having the code not seperating environments properly. 

Widgets are tricky, because the code is  loaded once, and run as instance for each defined widget

**Comment by lshems** [comment]
If you want, you can upload your widget on the repository I'm setting up.

I'll check it and make suggestions if neccesary.

Repository.justfly.solutions.

You can create a login to upload.

**Comment by lshems** [comment]
Jochen, I think you used an incorrect email. Please pm me at rcgroups. L shems

**Comment by n9rai** [comment]
oh, maybe a typo, can't find you at RCGroup, i'm there as "webmotions" or delete the user "joa" and i try again...

**Comment by raphaelcoeffic** [comment]
The issue is that you use variable local to the script, which does not work when you have multiple instances. Please recheck the doc (https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/widget_scripts.html), especially the last two paragraphs.

**Comment by raphaelcoeffic** [comment]
> Settings between models is strange, but could result from having the code not seperating environments properly.

Proper variable scoping is very important!

**Comment by n9rai** [comment]
ok, i have a lot of variables, so i have to define them all in the create function?
But does this also explain that widgets and there settings are no longer saved?

**Comment by raphaelcoeffic** [comment]
I did not look at your code very intensively, but yes, that could happen.

**Comment by lshems** [comment]
Ok, I have no good internet right now. 
Only on my phone. 

But I've posted some questions on your github. Let's discuss there. 

I don't think you need to rewrite a lot. And no, not all variables need to go into the create part.

**Comment by n9rai** [comment]
Thanks to some valuable tips, the script now works again. You never stop learning :-)
1. Widgets names can have a maximum of 10 characters
2. Variables and functions should not be global in the Lua environment
3. It is best to pass all variables via the create () object

Thanks @all !

**Comment by raphaelcoeffic** [comment]
Could you please add your findings to the documentation?

**Comment by lshems** [comment]
I think they where already there in the Widgets part of LUA 2.2 guide

'Widgets are located on the SD card, each in their specific folder /WIDGETS/<name>/main.lua (name must be in 8 characters or less).'
'widget name (name must be a string of 10 characters or less)'

'in the example given, you can see that no global variables or functions are needed to operate the widget.'
'variables that are used throughout the widget, can best be declared inside the create function as local variables'
'those local variablkes can then be passed through to the other functions as an element of the widget array that is returned'

**Comment by raphaelcoeffic** [comment]
Right, but there is a fine line between CAN and SHOULD ;-)

**Comment by ghost** [comment]
Question about global variables.

I have a widget that I have running on multiple pages in a model. in other sizes.
I want this widget to set a Gvar.

Do all the "same"  widgets in the model set the Gvar in the background? or only the one that is visible?

**Comment by kilrah** [comment]
It depends whether you put the code in the background function or the "refresh" one...

**Comment by lshems** [comment]
Unless you call background from refresh

**Comment by lshems** [comment]
Post the script here or on my rcgroups blog with a short description of the intended workings and I'll look at it

**Comment by ghost** [comment]
> Post the script here or on my rcgroups blog with a short description of the intended workings and I'll look at it

Will do later on, tnx

**Comment by PD5DJ** [comment]
Changed account.
