### ISSUE TITLE
Companion: the Logical switch list does not self refresh properly

### ISSUE THREAD

**Issue by vian31** [opentx/opentx#5821]
Just starting programming with 2.2.1 version and I found that in Companion, while setting up severals LS, the list on parameter V1/V2 and AND sup does not self refresh with the whole list of already EXISTING logical switches. Then not able to select them. To do it we must save the file, close and re-open it, which is boring indeed. See example attached. My profile is for QX7s but it looks the same with X9D (not tried all...)
In the radio the whole list from LS1 to LS64 is available, then no pb. It seems to me that the hidden of not used LS in Companion is new from this version. Am I right ? In anther hand this is a good improvement.

![il_simu](https://user-images.githubusercontent.com/11540573/38666304-da1acac0-3e3e-11e8-9362-57f03069cba5.png)
Vianney

**Comment by 3djc** [comment]
Known and fixed a while ago, will be in 2.2.2

**Comment by vian31** [comment]
Yep, very good. I was also a bit suprised to be the first hilighting that.
Thanks
Vianney

2018-04-12 10:55 GMT+02:00 3djc <notifications@github.com>:
