### ISSUE TITLE
Horus x10s, when applying throttle, pitch is affected.

### ISSUE THREAD

**Issue by ChefMagnum** [opentx/opentx#5827]
On all models from wing to quads, when I apply throttle input, the pitch is affected.  

On a quad it is noticeable in flight and black-box logs as a gyro change but no input change

on a wing, the servos are visibly and audibly moving with only throttle channel input

verified there are no mixes setup, and channel map, there is no movement  of the pitch channel when throttle channel is changed, but the servos connected to only to the pitch and roll channels

**Comment by 3djc** [comment]
If pitch channel is unaffected in the channel monitor, it is clear that it as nothing to do with OpenTx
