### ISSUE TITLE
Sync TX time with Companion

### ISSUE THREAD

**Issue by raphaelcoeffic** [opentx/opentx#5829]
As we have a new mass storage device displaying certain properties of the bootloader, we could use that to read and possibly write the TX timestamp. Background is basically #5735. It has been shown that SD card sync requires the timestamps to be synched.

However, this needs to be deactivated when GPS time sync is preferred (X12S setting).

**Comment by raphaelcoeffic** [comment]
@schwabe Hey! Do you think that would possible? Do you know if operating systems do somehow cache the timestamp seen on mass storage? Or could we always read the current TX timestamp by just checking the file date? When writing to the file, I guess it will automatically take the timestamp from the computer, right?

**Comment by mpaperno** [comment]
Most storage devices have no concept of (real) time. I don't think USB MSD has any API for time sync.  Of course you could always check timestamp on some file, but what does that really tell you?  

If you write a file via USB/MSD then the timestamp will come from the computer.  And radio doesn't have access to SD card while MSD is active.

**Comment by raphaelcoeffic** [comment]
@mpaperno that's not really true, please have a look at the implementation for the "Taranis" drive. We do generate every single bit there on the fly.

Look here: https://github.com/opentx/opentx/blob/2.2/radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp#L381
and here: https://github.com/opentx/opentx/blob/2.2/radio/src/targets/common/arm/stm32/usbd_storage_msd.cpp#L478

**Comment by raphaelcoeffic** [comment]
The only thing I'm not quite sure about is the opsys caching...

**Comment by bsongis** [comment]
Why not use USB CDC for that?

**Comment by raphaelcoeffic** [comment]
@bsongis is that ON at the same time as mass storage? Did I miss something?

**Comment by raphaelcoeffic** [comment]
@bsongis ok, mass storage does not really work for that purpose, as the OS is caching the file, no way around that. Is that somehow possible to enable USB CDC together with mass storage / joystick?

**Comment by naiba4** [comment]
sync-tx:6de804e2f2a096272123b21b7856367d177c9d754ec844b6fae39b29915133b6

**Comment by naiba4** [comment]
Lütfen yardımcı olun
