### ISSUE TITLE
Feature request: SSD1306 for Mega2560

### ISSUE THREAD

**Issue by insidecircuits** [opentx/opentx#5833]
It would be very useful to include the driver for this popular OLED display in the main branch.
This exists in the NextStep-RC development firmware.
https://github.com/Ingwie/NextStepRc-2.18

**Comment by 3djc** [comment]
Well, given we are dropping avr support, it is rather unlikely

**Comment by Tanmax-Payne** [comment]
Would be heartily appreciated, if that could've been  supported as this OLED is extremely small and sharp enough for most use cases, like this. I still believe a handful of people do take on Mega2560 project as not only as a Challenge or Project but sheer Necessity, And i'm sure this would've helped them for sure!
Grateful for all the code still working and Openly available for mega2560 builds! Cheers

**Comment by kilrah** [comment]
As mentioned we have deprecated support for all AVR-based radios and pruned all relevant code so it's not going to happen here.
