### ISSUE TITLE
Horus X10s Module Bay Issue 

### ISSUE THREAD

**Issue by Manoo430** [opentx/opentx#5835]
Hi;

Recently I bought Horus X10S, I flashed it to OpenTx 2.2.1. When I tried to use my EzUHF external module I realized that the module is not powering up. 

Looking at attached photo which is showing the JR module connectors of the Horus, I did below tests on both FrOS and OpenTx operating systems on Horus X10S:

![horus jr module](https://user-images.githubusercontent.com/38488473/38981251-fde42cda-43cf-11e8-9f08-abd12e94eb17.jpeg)

1. In FrOS, the module powers up and everything works normal. The voltage between Vmain and GND measured 6V.
2. In OpenTx, the module doesn't power up! The voltage between VMAIN and GND is almost Zero, the Voltage between VMAIN and S.P is 6V. I switched my negative wire from GND to S.P but when I connect the module voltage drops to 3V from 6V and it cannot power up the module.
3. I used an external battery and it worked good, I had signal too.

I have no programing skills, but I feel OpenTx messes up with the voltage regulators at module bay and also at trainer port ( I had similar issue with trainer port when I was trying to use head tracker - the negative wire was switched to other pin when on OpenTx, I fixed it by shorting 2nd and 3rd rings of my cable connector).

Need assist for this issue.

Cheers

Manoo

**Comment by 3djc** [comment]
Vmain is turned on when you declare a ext module in the model settings

**Comment by Manoo430** [comment]
Of course! this is a very basic thing! during all the tests, my external module setting was on PPM, means ON.

**Comment by Manoo430** [comment]
Plus, as I said ...everything works normal when the operating system is FrOS....problem happens when I flash it to OpenTx.

**Comment by Manoo430** [comment]
This shows OpenTx is not fully compatible with Horus X10 hardware.

**Comment by kilrah** [comment]
First time we have a report of that, and it would be surprising for you to be the first person to try and use an external module on an X10...

**Comment by Manoo430** [comment]
I guess so, couldn't find any report abt it! Hope OpenTx can fix the bug.

**Comment by Massild** [comment]
I have 3 external modules that all work with openTX.  I am running 2.2.1 on
a Horus X10S.  Maybe the S makes a difference?

**Comment by raphaelcoeffic** [comment]
Works on my side as well (X10). Voltage is exactly the same as the battery (7.50V here).

**Comment by raphaelcoeffic** [comment]
Just looked it up: EzUHF states 9-12v as input voltage. Could that be the issue?

**Comment by 3djc** [comment]
Maybe he tried FrOS when battery was more charged and by luck it worked there ?

**Comment by Manoo430** [comment]
No I tried it 2 times...on FrOS it is ok but on OpenTx not!! very confusing! same wiring, same hardware!

**Comment by raphaelcoeffic** [comment]
@Manoo430 could you please upload your model file?

**Comment by raphaelcoeffic** [comment]
And try with a brand new model having only the PPM module enabled?

**Comment by Manoo430** [comment]
Hi, Even with a brand new model with PPM enabled on external module I have same issue. will upload the model file when I'm home. Tnx

**Comment by raphaelcoeffic** [comment]
Just to be 100% sure:
- PPM output works
- but power output is OFF (~0V)
- exact same configuration works without hardware changes with FrOS

Is that correct?

**Comment by Manoo430** [comment]
Hi, yes PPM works, as you remember i mentioned that when I use an external battery, system works.
Also on FrOS i have exact hardware with no changes and it works. Are these two operations systems using different power regulator configurations?

**Comment by Manoo430** [comment]
it has become a riddle to me!!!!

**Comment by raphaelcoeffic** [comment]
@Manoo430 no, there is only a MOSFET to be switched ON or OFF, so basically nothing CAN be different here between FrOS and OpenTX. Do you have the X10S with the battery charger integrated? The only thing I could possibly think of is that something has changed here as well (hard to believe, but well).

**Comment by Manoo430** [comment]
its the latest version with built in charger (integrated).

**Comment by Manoo430** [comment]
the question is, if its a hardware issue, why does it work on FrOS??!!

**Comment by Manoo430** [comment]
it has warranty, but i don't like to return it...its a unique case! ;) ;)

**Comment by raphaelcoeffic** [comment]
I was just thinking, maybe something has changed on the PCB, probably nothing defect.

**Comment by raphaelcoeffic** [comment]
@Manoo430 is this is issue still the same for you?
