### ISSUE TITLE
PC game joystick  control RC car or Drone via companion??

### ISSUE THREAD

**Issue by igaoger** [opentx/opentx#5839]
Hi  I am new here. 

I am new to OpenTX and have some experience with Mission Planner. There is a very interesting function in Mission Planner is using PC game Joystick to control the drones or RC cars with Transmitter.

So I am thinking is it possible to use Game joystick to control a rc car or done via OpenTX Companion and Transmitter??  Like this, PC joystick connects to PC, send signal via Transmitter and control RC cars or drones with Receiver. Of course some setting needed.

Any ideas?

**Comment by kilrah** [comment]
There is no such feature in Open TX but I believe there are arduino-based projects that genrate a trainer signal you can connect to a radio.
