### ISSUE TITLE
Transmitter should ignore messages not listed on telemetry tab.

### ISSUE THREAD

**Issue by marbalon** [opentx/opentx#5842]
I'm using FrSky receivers just to retransmit RC signal to my tracker. RC data is transmitted using SBUS but my tracker transmit back telemetry using SPORT - information from done like battery, GPS, etc. but also with RSSI, and here is a problem. When I have a connection to my plane I receive telemetry and everything is ok, but when I lost telemetry send RSSI = 0 from tracker to SPORT receiver and this generates me "Telemetry lost" but FrSky receiver send it own telemetry with RSSI and Taranis report "Telemetry received".

My tracker generates SPORT frames with ID other than FrSky receiver, and I remove all sensors from telemetry tab but with ID 0x25 but the problem still exists.

So IHMO software should ignore sensors not listed on telemetry TAB and if you have two RSSI sources or two battery information you can select what to ignore.

**Comment by raphaelcoeffic** [comment]
Do I understand it correctly that you have 2 receivers bound to the same module, and each of them is sending telemetry?

**Comment by marbalon** [comment]
No,
I have one LRS transmitter on my tracker connected to taranis using FrSky receiver (SBUS + Sport). So telemetry received in LRS is transmitted to FrSky receiver via S.Port. So taranis receive telemetry generated by FrSky module and telemetry generated but LRS.

PLANE(LRS)   <air>   TX(LRS)  <SBUS + S.Port> FrSky  receiver   <air> Taranis.

So when I select discover sensors in my Taranis I have a lot of sensors from LRS and three sensors from FrSky receiver (of course with a different ID). I delete all sensors with FrSky ID, but still, Taranis receive it internally and mix information about telemetry lost/recover.

**Comment by raphaelcoeffic** [comment]
ok, so basically you have some sensor (your LRS module) connected to your Frsky receiver that sends the same type of packets as the receiver (RSSI), only differing by the Sensor ID, right? Do you happen to have a trace of this? It would be interesting to see what is seen by your Taranis.

**Comment by marbalon** [comment]
Yes, correct. So what you need to analyze this ? Is there any method to log smart port frames ? In my logs I see only RSSI from my LRS system, but this is normal because only this RSSI field is selected for logging.

**Comment by kilrah** [comment]
Basically the RSSI your LRS is sending should not be using FrSky's ID but another custom one.

**Comment by marbalon** [comment]
Of course, all sensors from LRS use different ID than FrSky.

**Comment by kilrah** [comment]
Then there should be no problem. More detail is needed then. Do you have one or 2 FrSky receivers?

**Comment by marbalon** [comment]
I tested on two different FrSky receivers with the same results X4R and XSR.

**Comment by kilrah** [comment]
I mean, more than one powered simultaneously.
If only one FrSky receiver is powered and your LRS uses other IDs then there is nothing that would casue this apart from an actual loss of telemetry feed.

That can happen if the radio is too close to the receiver which is very common knowledge, you didn't mention how far you spaced your stuff out.

**Comment by raphaelcoeffic** [comment]
I think that LRS is using a different sensor ID, but the same value ID, is that correct?

**Comment by marbalon** [comment]
@raphaelcoeffic 
Maybe now it will be more clear, please see attached foto. LRS use different ID (4), than FrSky (25). and like you see Taranis have two RSSI sources. Then I delete sensors with ID 25, so Taranis should wait only for ID=4.

And now scenario looks like here:
- when plane is ON,  LRS generate telemetry and it goes to taranis and everything is working
- when I turn OFF model, LRS lost telemetry and generate only RSSI frame with value 0
- Taranis receive this frame and recognize it as telemetry lost, but still, FrSky receiver sends RSSI with ID=25 and Taranis generate the message "telemetry received", and again LRS send RSSI=0, and telemetry lost, and again, again...
Now it is more clear ?

![taranis](https://user-images.githubusercontent.com/16336451/39230466-de9465f2-4866-11e8-81b3-432f6ad72c5f.jpg)

**Comment by kilrah** [comment]
Yes, it confirms the issue is your LRS using the same Data ID as FrSky as I first suggested.

**Comment by marbalon** [comment]
Yes LRS transmit RSSI as 0xf101 just like FrSky, so you suggest use different to send RSSI ? But how openTx recognize RSSI source ? using Data ID ? 

But when I change Data ID openTx will not know that it is RSSI and will not inform me when telemetry from LRS is lost. IHMO better option is ignore sensors not listed on telemetry TAB.

**Comment by kilrah** [comment]
Yes, use a different ID. You can discover that, select the proper unit, then set up your own alarms on it using logical switches and special functions. You get the benefit of being able to select different alarms/voices to distinguish both then.

Everything that isn't in the list is already ignored... EXCEPT RSSI which is a special case becasue it's used to signal telemetry presence and to feed the RSSI gauge and built-in warnings even if the user hasn't discovered sensors.

**Comment by marbalon** [comment]
But maybe it is a good idea to select RSSI source also like voltage source?

Edit.
And this is a little complicated for user, setup extra allarms, functions etc.

Edit2.
Briliant solution will be: If there is no sensors discovered with RSSI, analyze all RSSI messages, but if user configure RSSI sensor use only this one.

**Comment by raphaelcoeffic** [comment]
Seems reasonable to me. But what happens if more than one sends RSSI, just like in your initial case? Which one should be chosen? All of them?

**Comment by marbalon** [comment]
Yes, all of them. If user configure 2 sources, he probably know what is he doing ;-)

I've just browsed the code and the simplest way is define function in telemetry_sensors.cpp like

isValidRssiInstance(uint8_t instance) with results:
true - if sensor not found or founded with the same instance
false - if there is a sensor with different instance only

And then use it in sportProcessTelemetryPacket(). I can even code it but just let me know if this is correct solution.

**Comment by raphaelcoeffic** [comment]
Cool, just create a pull request and we can have a look at it!

**Comment by marbalon** [comment]
OK, pool request created. Tested and working as expected ;-)
