### ISSUE TITLE
Horus: add SD card benchmark on the debug page

### ISSUE THREAD

**Issue by raphaelcoeffic** [opentx/opentx#5843]
That might help to understand some strange issues with slow boot, or slow "model select" page. Maybe adding some warnings if the speed is really too slow (would need some data from users having working setups).

**Comment by raphaelcoeffic** [comment]
It seems that already exists on X7/X9: press <page> long while in the SD explorer:
![clipboard - april 24 2018 10_31 am](https://user-images.githubusercontent.com/1050031/39175791-7f801ab8-47ab-11e8-9405-90a51340a7d4.png)

**Comment by kilrah** [comment]
Umm, what provides this value is...

```
uint32_t sdGetSpeed()
{
  return 330000;
}
```
