### ISSUE TITLE
getFieldInfo() for undefined sensor name returns 1 when it should return 0

### ISSUE THREAD

**Issue by teckel12** [opentx/opentx#5850]
## OpenTX 2.2.1

The Lua command `getTelemetryUnit()` returns a value of `1` which is `V` (volts) instead of `0` which is `-` 
(undefined).  I'm not sure, but I believe it returned `0` in OpenTX 2.2.0 but I'm not entirely sure.

In any case, the unit for `1` is `V`, which is wrong if the sensor isn't defined.  It should return `0` as that's already defined in Lua as an undefined unit, designated as a `-`.

**Comment by 3djc** [comment]
Do you mean getFieldInfo() ? Because I do not belive we have a getTelemetryUnit() function.

**Comment by teckel12** [comment]
Sorry, I had a major brain-fart.  I believe all is good, closing...
