### ISSUE TITLE
Fading between Flight phases will not happen

### ISSUE THREAD

**Issue by Billy60300** [opentx/opentx#5853]
I report that when switching between flight phases no fading will happen. All positions are switched to abruptly.
Taranis QX7, OpenTX 221.

**Comment by 3djc** [comment]
You need to supply your otx file with instructions for us to reproduce the issue.

**Comment by Billy60300** [comment]
[OTX file April 29.zip](https://github.com/opentx/opentx/files/1958551/OTX.file.April.29.zip)
Sorry, I thought this was only to report some issues for further development in OpenTX.
There is the otx file, latest version.
You will see the 'No Fading' issue, and maybe also the 'missing models' one. In the QX7 two more models are present and used. The SD card has been 'saved' and those two should appear in it. As you see, they don't.
Thanks for your help.
Billy

**Comment by 3djc** [comment]
QX7 does not use SDcard to save models...

**Comment by Billy60300** [comment]
Are you sure ? Mine has a SD-HC card indeed.
I uploaded the OTX file there is on it.
Best regards

**Comment by kilrah** [comment]
There is an SD card but it is not used for model storage. Unless you use the "backup" feature in the model selection page which makes a copy on the card, but then those are "archived" and no longer part of the OTX as designed.

This OTX has 2 models. If you see more on your radio's model select screen then please conenct the radio to USB like you would to use companion, but send us the EEPROM.BIN file you will find it the "Taranis" drive that appears on your computer.

**Comment by kilrah** [comment]
Your "no fading" is becasue you're using your flight mode switch in the mixes' Switch field. You must leave that blank and use the "Flight Mode" checkboxes.

**Comment by Billy60300** [comment]
Sorry Kilrah, I am afraid I don't get the point.
The Flight Modes depend on SC.
The Mixes which are to happen according to the chosen FMode, should be linked in some way to the FM. If not, how will the program know what mix to activate ? I supposed this link between FM and proper Mix was to be done using the same Switch. Now, I  understand how there is no fading in my case: the SC position will trigger the mixes before the fading has occured.
If I leave the Mix Switches box blank, how will they be triggered ?
Thanks again.

**Comment by kilrah** [comment]
I just told you. The Flight modes checkboxes define in what modes the line is enabled.

![clipboard01](https://user-images.githubusercontent.com/6065069/39405218-96eb34fe-4ba1-11e8-82d9-75fe1fc31d93.png)

**Comment by Billy60300** [comment]
Yes indeed ! Got it ! understood !
Everlasting thanks for your help !
