### ISSUE TITLE
How to get logical switch state using lua script?

### ISSUE THREAD

**Issue by BRoy98** [opentx/opentx#5857]
Is it possible to get a **Logical Switch** state from lua script? 

I tried all these but value is always `0`
```
getvalue(LO1)
getvalue(lo1)
getvalue(L01)
getvalue(l01)
getvalue(l1)
getvalue(L1)
```

**Comment by 3djc** [comment]
I'm sorry but this place is a bug tracker, not an end user support place. For question like this, please refer to places like rcgroups or openrcforum. Alternatively, you can consult the opentx lua documentation at getValue() page where links to valid fixed sources is provided ....

**Comment by lshems** [comment]
Post your question on rcgroups in the opentx Lua thread. It will get picked up there.https://www.rcgroups.com/forums/showthread.php?t=2180477
