### ISSUE TITLE
since V2.2.2Nxxx some part are not in setting Languages at V2.2.1 all was ok

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5860]
V2.2.2Nxxx some parts are in setting Languages some not now
V2.2.1 complett setting languages was ok

![opentx v222 fehler001](https://user-images.githubusercontent.com/6217896/39464340-f5ebafc0-4d1c-11e8-8ae1-75680a3b4336.jpg)
![opentx v222 fehler002](https://user-images.githubusercontent.com/6217896/39464348-0190fba0-4d1d-11e8-99da-cd9cc9631309.jpg)

**Comment by schwabe** [comment]
Yes. Someone needs to update the translation. The German tranlsationn is missing many strings in Companion and when code changes the old translation become invalid and need to validated to become active again.

**Comment by hrenz** [comment]
ok, will see what I can do
