### ISSUE TITLE
Missing screenshot for X10, X12  at TX for writing different languages manuals

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#5862]
Hy,
sorry,  but my most missing funktion at X10, X12  are the missing screenshot funktion at the Tx 
its for writing manulas at different lnaguages   De, Es, It

Because at companion  simulator we habe only EN menüs

Will this function come  same as at X7 X9?

**Comment by 3djc** [comment]
There is no point in opening new issues about that since it is already in the main Horus issue list. This will possibly come one day, but will not be part of 2.2.2

**Comment by hrenz** [comment]
ok sorry and thank you for this info
