### ISSUE TITLE
Sky9X target always boot in SAM-BA mode after flashing

### ISSUE THREAD

**Issue by The00** [opentx/opentx#5864]
Hello,

I'm developing a custom hardware based on the AR9X board.  I work with an eval board of the ATMEL SAM3S8 µC. After few successful test with Atmel studio generated binary , I'm trying to flash OpenTX to it. But after writing the .bin file successfully, the board always boot in SAM-BA mode, despite having set the GPNVM bit to boot from the flash.  I'm using the SAM-BA embedded bootloader through USB for flashing.

I tried several binary, official 2.2 and 2.0 version, and  also customized versions (builded with the Qt framework).
I know the AR9X/Sky9X target isn't really supported anymore, but if anyone has an idea of what I am missing, I'll take it.

**Comment by raphaelcoeffic** [comment]
@The00 your best bet is probably to ask your question on openrcforums.com.
