### ISSUE TITLE
Wrong current and consumption reading from FrSky ESC-80A sensors

### ISSUE THREAD

**Issue by RiMr71** [opentx/opentx#5878]
Tested ESC80A in FrSky Vantac AR+ on OpenTx 2.2.2N597.
Wrong data from current sensor, wrong data from consumption sensor - compared with standard 40A sensor. 
Missing data in log file.

**Comment by 3djc** [comment]
Given the amount of details submitted, we have very little chances to understand, let alone fix the issue !

**Comment by RiMr71** [comment]
FrSky speed controller with in-build sensors FrESC32_80A. Horus X12s with OpenTx 2.2.2N597. In telemetry windows are detected right sensors from this ESC (rpm, current, power consumption, temperature), but values from sensors current and power consumption are not valid (numbers are with values which are not true). If is it still hard to understand (sorry for that), I will make a video.

**Comment by 3djc** [comment]
Any details on the value measured vs expected ?

**Comment by RiMr71** [comment]
Screenshots from Companion (2.2.2N597). Look not only on curves, but on different "scale" of value on left and right side. VOltage is acceptable, but current and consumption not. Values from 40A sensor are right, values from ESC80A are wrong.

![voltage](https://user-images.githubusercontent.com/16500983/39777888-24fb07be-5305-11e8-9ced-eb17b16aa015.JPG)
![current](https://user-images.githubusercontent.com/16500983/39777890-25165ec4-5305-11e8-87b0-3fdb0706b4ff.JPG)
![consumpion](https://user-images.githubusercontent.com/16500983/39777891-25303678-5305-11e8-9432-bdda687c4758.JPG)

I can´t attach here directly log file. You can download it here:
https://drive.google.com/open?id=1ZYyO38nuq_oWQ_gLN5PuoKAfk24FfeMd
.

**Comment by kilrah** [comment]
As long as you have your offset and Range set to 0 what OpenTX displays is what the sensor sends. If the value is wrong then the sensor sends a wrong value. Not much we can do.

Please send your otx file as well.

**Comment by RiMr71** [comment]
Thanks Kilrah. Sensors from ESC are as was detected by OpenTx/X12s. 
Link for OTX file is here:
https://drive.google.com/open?id=1uGHTkIXvQhe8VwvMx8glYYgQI7hZUPrr

**Comment by 3djc** [comment]
We are currently talking to FrSky to better understand what could be happening

**Comment by 3djc** [comment]
I am leaving this open until final confirmation by FrSky, but it looks like the issue is not with OpenTx

**Comment by notlebowski** [comment]
After insisting there was a problem with the ESC it was confirmed by Frsky some time ago.
https://www.rcgroups.com/forums/showpost.php?p=39849336&postcount=80

Allerhopp tested this new firmware and saw that although values are now decent, they still are not correct.
https://www.rcgroups.com/forums/showpost.php?p=39894448&postcount=88

Frsky will offer a new firmware soon.
https://www.rcgroups.com/forums/showpost.php?p=39898924&postcount=97

Problem is obviously not in OpenTX
I think the ticket can be closed.

**Comment by 3djc** [comment]
thx for the update 👍
