### ISSUE TITLE
Companion - Mac Download link doesn't work.

### ISSUE THREAD

**Issue by PackyFPV** [opentx/opentx#5880]
Hi... I'm writing here because yesterday i tried to download the latest version of Companion on my Mac (2.2.1 RC3) but after clicking the link i obtained alway "404not found" error. I tried also with older version but for Mac i obtained always the same result.
Please, can you help me with that or suggest me some other links where i can download the program?
Thank you in advance

**Comment by 3djc** [comment]
That's an old RC version. Get the right version from this page : http://www.open-tx.org/2017/12/16/opentx-2.2.1
