### ISSUE TITLE
update doc on branches

### ISSUE THREAD

**Issue by dhardy** [opentx/opentx#5885]
The [wiki](https://github.com/opentx/opentx/wiki/OpenTX-Git-Development-Workflow) mentions `master` and `next` branches which don't appear to exist any more, so I guess this needs updating.

My primary question which I can't find an answer for is: is the 2.2 branch stable?

**Comment by 3djc** [comment]
No, we do not have a stable branch. The closest equivalent is to use a version branch (like 2.2) and a release tag, like 2.2.1

**Comment by kilrah** [comment]
Updated
