### ISSUE TITLE
Polish characters in Horus - OpenTX 2.2.1 (bug)

### ISSUE THREAD

**Issue by oizic** [opentx/opentx#5889]
I have uploaded OpenTX 2.2.1 to my Horus x10
There is a problem with Polish characters.
Instead of Polish characters, there are various inappropriate symbols.
![dsc_0588](https://user-images.githubusercontent.com/39268911/40001433-79513ea4-578e-11e8-8df2-733602ed62a1.JPG)

**Comment by 3djc** [comment]
The complete list of available characters on Horus is here : https://github.com/opentx/opentx/blob/2.2/radio/src/fonts/480x272/font_stdsize.png

Are polish chars missing from this ?

**Comment by oizic** [comment]
That's how Polish signs are missing
There are no Polish characters on this list.
When will they be introduced?

**Comment by raphaelcoeffic** [comment]
Probably when some polish fellow starts working on it? Or at least helping? That‘s how open source works ;-)

**Comment by 3djc** [comment]
We probably need to review the fonts and display routine to deal with polish display ourselves, but yes; polish translations have not been reviewed in a loooonng time, so likely need quite a bit of work !

**Comment by oizic** [comment]
I do not know how to program, so I temporarily use the English menu.
Only I wanted to report a problem in the Polish menu.

**Comment by raphaelcoeffic** [comment]
Fixed by #5891
