### ISSUE TITLE
Crossfire & X9E: Missing wheel events EVT_ROT_[LEFT|RIGHT]

### ISSUE THREAD

**Issue by aguindehi** [opentx/opentx#5893]
**Failure Description:** 
The Crossfire menu can not be used on the Taranis X9E which only has a selection wheel and no plus/minus buttons like the X9D 

**Details:**
I just installed my first Crossfire Micro TX in my Taranis X9E. Even after upgrading to OpenTX 2.2.1 and the SD-Card Content 2.2V0013 I could not get the crossfire.lua menu to work for me. It showed the correct information "XF Micro TX" and I was able to choose it by pressing the selection wheel but I could not move the selection in the menu showing up.

**Bug Description:**
After some investigation I found out that **the two lua scripts were missing the needed events** to handle the selection wheel events generated by the selection wheel on the Taranis X9E.

**Fix:**
I patched the crossfire.lua and device.lua scripts on the SD card to include the needed wheel events EVT_ROT_[LEFT|RIGHT] and to handle them similar to the plus/minus events generated by the buttons on the Taranis X9D. The menu now seems to correctly work and I'm able to scroll down and change options.

**Patch:**
crossfire.lua + device.lua: [crossfire.zip](https://github.com/opentx/opentx/files/2013485/crossfire.zip)

**Comment by raphaelcoeffic** [comment]
@aguindehi thanks for contributing! I just created a PR for your changes. This issue will be closed as soon as the PR gets merged.
