### ISSUE TITLE
Taranis X9D Plus will not bind with receivers

### ISSUE THREAD

**Issue by mace04** [opentx/opentx#5894]
I have been happily using my brand new Taranis X9D+ receiver for a few months now until last weekend when I tried t change the battery back on my drone for the second flight of the day. My drone is equipped with an XSR receiver and had quite a few flights under its belt with no issues.  When I usually finish with a flight i disconnect the flight battery and then switch off the transmitter. I then change the battery, switch on my Taranis and let it boot up (no issues there), and then connect the second battery in my drone. 

What I noticed however last weekend was then when I connected the battry for the second flight my XSR both LEDs where flashing, and will no longer connect to Taranis. Not sure why, but since then I am no longer able to bind any receiver. Thinking that there is something wrong with the XSR I have since bought a brand new X6R and X4R, and cannot bind them either. The weird thing however is that I tried one other model (binded a few months back) and still connects and works as expected so I cannot say that there is a problem with RF.

Below is a list of what I have tried so far with no luck:

- Tried flashing both EU and non-EU firmwares in my Taranis with no luck
- Disconnected the battery from my Taranis and connected back in again in order to make sure that the receiver is started afresh
- Tried to reflush the XSR but was unable to do so for some reason. This indicates to me that something has gone wrong with the XSR. I have not flashed the new receivers as they should work out of the box
- Tried to bind any receiver to a new model slot in Taranis with no luck

Just one final note, when i am trying to bind the new receivers,I switch on the Taranis and set it to bind, I then press the button on the receivers, then power it up, and both LEDs light up (no flashing) after that nothing happens. Also I am afraid to try to re-bind the receivers on my other planes as they may never bind again.

As I am running of ideas, I was wondering if any of you have any ideas or insight on what the problem is here.

Many thanks 

Michael

**Comment by 3djc** [comment]
Sorry, but this not an end user support arrea, but an opentx bug tracking system, which your situation clearly doesn't apply. Please go to support forums like rcgrousp or openrcforums, where you can have a dialog to resolve your issues, so I'll be closing this.
