### ISSUE TITLE
X-Lite N605 Center Beep

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#5896]
On the model screen "Center Beep" the curser will not move over to slider 2.  The function works OK with slider 1.

**Comment by 3djc** [comment]
Actually this one is much trieckier than it sounds. If you move to model setup page and start from the top, you have the bug, until you display external module, where is disapears

**Comment by MIKE-DAILEY** [comment]
Right you are and interesting bug.
