### ISSUE TITLE
2.2.1 X10 not show RAS well 

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#5900]
X10 Frsky OS 
internal antenna SWR 0 external 6-19 based on cover 
flashed same radio to OpenTX 2.2.1 
internal RAS 0, ext+int RAS 0 and not change, no cover change numbers. 

Any change in RAS monitoring by OpenTX?

**Comment by 3djc** [comment]
We haven't made any changes to that I think, we just get the value from the module (btw x10 doesn't have int+ext, it is int OR ext)

**Comment by 3djc** [comment]
We are able to replicate that, so we have an issue that we will be investigating

**Comment by janekx** [comment]
OpenTX says Ext+Int on setting to be clear.  I remeber that X12S if switch to external start to work both, I thing X10 will act same 1+2 switching.

**Comment by 3djc** [comment]
Yes, that was wrong, but we fixed it since

**Comment by 3djc** [comment]
https://github.com/opentx/opentx/issues/5564

**Comment by janekx** [comment]
I see clear, was not informed by FrSky about this changes LOL
