### ISSUE TITLE
Function request: Adjust GV in global function is missing on the remoter.

### ISSUE THREAD

**Issue by StreakingJerry** [opentx/opentx#5905]
The Adjust GV function works fine in companion 2.2.0 but missing in  companion 2.2.1. And on the remoter no matter with which firmware there is no "adjust GV" in global function. But if you set it in companion 2.2.0 then it works good in the remoter.

I think this is pretty useful especially to define a switcher as a maximum range selector for all models.

**Comment by raphaelcoeffic** [comment]
Do you mean that one? this is on Companion 2.2.1:

<img width="1188" alt="screen shot 2018-05-21 at 22 20 18" src="https://user-images.githubusercontent.com/1050031/40328021-312dd850-5d45-11e8-80e1-1c52527878ab.png">

EDIT: sorry, you meant in the global functions, so basically for the complete radio, not just one model?

**Comment by StreakingJerry** [comment]
yes, what I meant is in the global functions. So it works for all models.

**Comment by raphaelcoeffic** [comment]
@wuhao19920619 I'm afraid it has been removed on purpose, but I don't know exactly why.

**Comment by StreakingJerry** [comment]
Yeah I guess so but I don't know the reason. 
One interesting thing is that in 2.2.0 this is only adjustable in companion. In the remotor you cannot find it either......

**Comment by StreakingJerry** [comment]
global variable is "global" functional......So I think logically it should be adjusted also globally.

**Comment by raphaelcoeffic** [comment]
@wuhao19920619 that's basically the issue, GV are anything but global ;-) They have a different value per flight mode, and thus per model. As it seems, it was never intended to be possible to edit GVs from these gobal functions: https://github.com/opentx/opentx/commit/1c1624b8a6e220896401442e750940d230dcde2b
