### ISSUE TITLE
French Name # English Name for Sensor

### ISSUE THREAD

**Issue by aviat40** [opentx/opentx#5907]
Hello,
I am developping a Widget and noticed that the name of the sensor for the Battery RX is not the same according to the language of the radio.

It is "BtRx" in French and "RxBt" in English.

I think all sensors should have the same default names in all languages because when you want to use it to display on a widget, you need to write a special function to detect which language is used.

Thank you
Thierry

**Comment by raphaelcoeffic** [comment]
@aviat40 Whereby I think you're right with the default names being the same with all languages, you should consider make the sensor name a config parameter of your widget, so that people can use renamed / other sensors as well.

@LapinFou is that something you could fix, while you're busy with translations?

**Comment by 3djc** [comment]
As I replied in the French forum, you need to allow user selection, as sensor are designed to be renamed.

If Lapinfou wants to change the French translation, why not, but that won’t change the fact that you shouldn’t assume names

**Comment by lshems** [comment]
Could we increase the amount of parameters to pass through to a widget.

It's becoming troublesome if we have more then one sensor to define e in a widget setup.

**Comment by LapinFou** [comment]
@raphaelcoeffic I may change the translation but, as mentioned @3djc , it would a better (and more reliable) solution to update the widget.

**Comment by aviat40** [comment]
Ok, May be change the translation initially to have the same name sensors and I will also update the widget as 3djc advises ;-)

**Comment by 3djc** [comment]
If that french name has been used for a long time, then I would advise against changing it (since I don't ise the french version, I can't tell)

**Comment by kilrah** [comment]
I am against changing the translations.
Even if we did it would not solve your problem, you'd still need to handle French names becasue the change would only affect new users/newly configured models.

**Comment by aviat40** [comment]
@kilrah : ok, I already start to manage with the French. It seems that was not a good idea. So please for LapinFou who  translate, change also within companion simulator sensors. 
Any case, thank you for all of your answer

**Comment by LapinFou** [comment]
@aviat40 
Je vais écrire en Français afin d'éviter toute ambiguïté. Comme @3djc l'a dit je suis **contre** l'idée de changer la traduction. Toutes les versions OTX supérieure à la 2.1 permette de nommer/renommer les capteurs comme on veut. Donc, c'est au widget de faire en conséquence.
Maintenant si cela te bloque complètement dans le développement de ton widget et que tu n'as pas d'autre solution, alors dans ce cas je peux mettre à jour la traduction. Cependant, je ne gère que la traduction Française de **Companion** !! Pour le firmware radio, il faut convaincre @3djc /@kilrah /@bsongis ...
😉

**Comment by 3djc** [comment]
The issue was raised rightfully as he saw that as an issue. It as become clear that it is not quite the case, I think he understands that clearly and will adapt his widget as a result of those discussion, therefore, closing this. thx to all :)
