### ISSUE TITLE
X-Lite firmware and SD card contents

### ISSUE THREAD

**Issue by teckel12** [opentx/opentx#5908]
Trying to test my INAV telemetry script on the X-Lite but can't find the SD card contents for the X-Lite transmitter.  As 2.2.1 support doesn't seem to be included, I'm running the nightly build, but https://downloads.open-tx.org/2.2/nightlies/sdcard/ doesn't include the X-Lite.

Could someone point me in the right direction?  I tried searching this repo, open-tx.org site, Google search, etc.  The configurator points me to: https://downloads.open-tx.org/2.2/rc/sdcard/opentx-xlite/ which is empty.  When I try to download the firmware from the configurator I get a "Compilation error".

Thanks!

**Comment by teckel12** [comment]
It seems there isn't special SD card contents for the X-Lite?  Not sure why the firmware won't download.

**Comment by 3djc** [comment]
currently, you should use : https://downloads.open-tx.org/2.2/nightlies/sdcard/sdcard-taranis-x7-2.2V0016.zip

**Comment by kilrah** [comment]
And you must set companion to use nightly, no RC. There is no RC yet.

**Comment by teckel12** [comment]
@kilrah Bingo! That's what I forgot I believe, thanks!
