### ISSUE TITLE
Cross trims in Global functions

### ISSUE THREAD

**Issue by kelkarakshay** [opentx/opentx#5910]
Hi friends how mtwomey add cross trim in global function. Is it any other versions of opentx. I have installed latest opene tx 2.2.1. And I m unable to find it. Let me know if there is another versions. I want to install it.
https://youtu.be/JKQgAdqzfmY

**Comment by kilrah** [comment]
There is no crosstrim function in OpenTX. You manually select the trims you want in the inputs.

**Comment by kelkarakshay** [comment]
But in this video https://youtu.be/JKQgAdqzfmY 
How to do that

**Comment by kilrah** [comment]
https://github.com/opentx/opentx/pull/5078
