### ISSUE TITLE
[Companion] Add Mixer view in Simulation

### ISSUE THREAD

**Issue by Roitellet** [opentx/opentx#5913]
In simulation mode, only the Channel Output Signals are displayed (mixers + channel settings, like INV and applied curve). The Mixer output view is not available, or I have not found out how to activate it.

In the Taranis display, the Mixer view can be activated by pressing ENTER long.
Please add this view also to the Companion view in simulation.

Reason: Programming of mixers for an aircraft setup follows some conventions. E.g., rudder up or right is for positive input (Elev must be inverted). Like that, a additional signals added to a channel are acting with the correct sign. The channel output panel is purely for limiting or linearizing the servo travel and its rotation action. 

Thanks!

**Comment by mpaperno** [comment]
Already done in #5811, currently available in nightly builds and will be released with v2.2.2.
