### ISSUE TITLE
Polish characters in 2.2.1 - Horus, possibly Taranis

### ISSUE THREAD

**Issue by makcorner** [opentx/opentx#5915]
Seems like Polish characters are not encoded / displayed properly. Whenever Polish character is expected (ąęćńłśóżź) some other sign is displayed. Pictures visible here:

https://forum.77hobby.pl/topic/117-frsky-horus-polskie-znaki-w-menu-opentx/

Is it known issue?

I can test it also on Taranis if needed, just let me know.

**Comment by kilrah** [comment]
Duplicate of fixed #5889
