### ISSUE TITLE
X-Lite can't switch between custom screens

### ISSUE THREAD

**Issue by teckel12** [opentx/opentx#5917]
**How to duplicate**
1. On X-Lite transmitter create more than one custom screen
1. Exit model configuration and long-press down arrow to bring up first custom screen
1. No button short or long press will ever take you to the second screen

**Suggested solution**
As with the model configuration, left and right arrow keys should page through the custom screens

**Comment by 3djc** [comment]
I think it is fixed and should work with shift long left/right

**Comment by teckel12** [comment]
@3djc Perfect!  Thought it may have been missed as I could't figure out the key combination.  Thanks!
