### ISSUE TITLE
OpenTX 2.2.2 Taranis Q X7 and R9M LBT: no telemetry for 200mW

### ISSUE THREAD

**Issue by xkriton** [opentx/opentx#5919]
Taranis Q X7 on FW FrSky 180525 or 2.2.2N616
R9M EU LBT with FW 180428
Missing 200mW telemetry option. Only available for 25mW options

Martin
![image](https://user-images.githubusercontent.com/39747060/40686622-375bec18-6398-11e8-99a2-d757a2e15c87.png)

**Comment by schwabe** [comment]
That is by design, the EU module does only telemetry with 25 mW.

**Comment by xkriton** [comment]
R9M LBT FW version 180428 says:
Add 16 channels with telemetry and 16 channels without telemetry (200mw power) modes.

**Comment by schwabe** [comment]
Yes, it added 16 channel with telemetry [25mW] and without telemetry  [200mW].
