### ISSUE TITLE
firmware bin error

### ISSUE THREAD

**Issue by georgecang** [opentx/opentx#5921]
hi need help on this error when i am in "write firmware to radio" i encounter this error : CANNOT WRITE VOLUMES/TARANIS/FIRMWARE.BIN (REASON UNKNOWN ERROR)

this is when i was updating to v2.2.1 taranis q7

**Comment by raphaelcoeffic** [comment]
@georgecang I believe you should go to a user support forum like rcgroups:
https://www.rcgroups.com/forums/showthread.php?2818003-FrSKY-Taranis-Q-X7-FAQ-discussion-info-the-younger-full-featured-radio/page534
