### ISSUE TITLE
Unable to Simulate Telemetry for Cels/LowC/CelD

### ISSUE THREAD

**Issue by jquigley3** [opentx/opentx#5923]
Using OpenTx 2.2.1, simulating Taranis QX7. On the physical radio, it is set up and correctly receives battery telemetry, using the Cels/LowC/CelD sensors. These are configured like [Name: Cels, Type: Custom, ID: 0300 2, Precision: 0.00, Logs: No]. When reading this model into OpenTx companion, this configuration is copied across successfully.

When simulating the radio, and simulating the telemetry, the values for Cels/LowC/CelD to not appear to simulate at all. The RxBt and RSSI do simulate. The screenshot show the behaviour (I have also tried varying all the cell volatages with no success).

I am only trying to type the values, not replay a log file. The exact use case is testing a low volatage alarm based on the LowC value (ie lowest cell volatage). This works fine on the physical radio, but I can't reproduce in the simulated radio.

![image](https://user-images.githubusercontent.com/8716660/40763761-687b3b58-64e9-11e8-9aa9-0fa944a97667.png)

**Comment by 3djc** [comment]
There is no 2.2.2 yet, so it is unclear what version you are using

**Comment by jquigley3** [comment]
Typo, it's 2.2.1

Anyway - I started from scratch reloading the models from the radio, and this time it worked. Play with the values, it seems that the simulated values on load intermittently. So, even when I change values, it stays stuck on the old value forever. I can't figure out how to update it, but I'll close this issue because its not a good description of the root cause.

**Comment by kilrah** [comment]
The firmware filters values because of a faulty FLVSS firmware back in the day, so if you type in unrealistic values that don't match a lipo cell (don't remember the criteria anymore) the firmware will ignore them.
