### ISSUE TITLE
Telemetry simulator doesn't reliably pick up changes to Cels and cell volatages

### ISSUE THREAD

**Issue by jquigley3** [opentx/opentx#5924]
Using OpenTx companion 2.2.1, simulating the Taranis QX7 radio, I am unable to reliably set the cell voltage telemetry. As shown in the screenshot, the total volatage and LowC value is incorrect. It has picked up _one_ of my changes, as I managed to change it from zero (I don't know how).

I've tried using the widget up/down tickers, typing, hitting enter, hitting tab, ticking/unticking Simulate and a bunch of other random clicking around without any luck. It feels like a bug in UI: since other changes like RxBt immediately detect the changes, maybe there are some missing listeners or handlers needed to detected changes to the cell voltage input fields.

![image](https://user-images.githubusercontent.com/8716660/40764149-36c0eb06-64eb-11e8-9bc1-2e92b61e12e6.png)

**Comment by kilrah** [comment]
See my comment on #5923.

In your screenshot most of your values are not valid lipo cell voltages.

**Comment by jquigley3** [comment]
Thanks for that tip. I think the actual reason was matching the telemetry channel number. In the screenshot it is '6' for Cels, and it needs to match what is set in the radio. Because I had been randomly changing numbers, I hit the lucky working number and saw an update without realizing why. I'm not sure why leaving it at the default didn't work for me in the beginning, but most likely some sort of user error.
