### ISSUE TITLE
OpenTX 2.2.0 Timer controlled by logical variable L01-L64 has a strange behavior

### ISSUE THREAD

**Issue by WillyZehnder** [opentx/opentx#5927]
The controlling of a Timer (I just checked Timer 1) by a Logical Variable has a different behavior depending on the Logical Variable you use:
L01 - L37 : correct function
L38 - L39 : no function
L40 - L46 : inverted function!
L47 - L64 : no function

![2018-05-31 17_46_59-modell 3 bearbeiten _omega_rx8r](https://user-images.githubusercontent.com/39805388/40794966-ead802e0-6500-11e8-8d7d-fc77ebf02800.jpg)

**Comment by 3djc** [comment]
Please test with latest version in this branch, 2.2.1 for now

**Comment by WillyZehnder** [comment]
Yes, I thought about that, but I decided not to change my running system because of the challenging situation in private and on the job in the moment. I'm sorry.
If somebody has 2.2.1 on his system it would be nice to make that little test for us.

**Comment by kilrah** [comment]
You also don't say what radio you have.

**Comment by WillyZehnder** [comment]
Oops, sorry - I use an X9E
But in the meantime I recognized that you can simulate that effect in Companion, too.

**Comment by kilrah** [comment]
In what companion version?...

**Comment by WillyZehnder** [comment]
It's Companion Version 2.2.0 May 30 2017 (that is fitting to my OTX Version 2.2.0).
Thank you for you patience - I should have known all the questions before you asked me. I developed software for 16 years but I'm a newbie in that GitHub-forum.
