### ISSUE TITLE
X-Lite switches displayed symetrically.

### ISSUE THREAD

**Issue by KC748** [opentx/opentx#5928]
It would nice to see SB and SC swap positions on the main screen so that they are displayed corresponding to their actual positions on the Tx, which is SA and SC on the left and SB and SD on the right.

On the main screen, the switches are listed (alphabetically) with SA and SB on the left and SC and SD on the right. 

Switching the positions of SB and SC,  they will be displayed symmetrically, same way as the graphical sticks, sliders and trims.

Similar changes in the Simulator would be nice as well, so that the switch order appears as SC SA on the left, and SB SD on the right.

X-Lite main screen.
![57d466e0-3f85-4980-b22a-c575795afc49](https://user-images.githubusercontent.com/39738927/40817196-1929db8c-651f-11e8-85ed-1c500ea39570.jpeg)

Switch layout from the manual.
![82d6ce1d-b3ae-4198-83a5-e7ed04d2ab65](https://user-images.githubusercontent.com/39738927/40817194-18d938d0-651f-11e8-9e66-f1558e500749.jpeg)

Simulator with switches listed in alphabetical order and does not reflect physical layout. 
(There are only 4 switches).
![e4a4a4e9-4ebe-4cfe-8729-a4577d1a139f](https://user-images.githubusercontent.com/39738927/40817195-18fe1a42-651f-11e8-980b-09f02bfd3935.png)

**Comment by mpaperno** [comment]
Simulator part duplicate of #4419  (ability to have custom layouts per radio).
