### ISSUE TITLE
Horus x12s with open-tx 2.2.1 no sounds on memorycard!

### ISSUE THREAD

**Issue by weca58** [opentx/opentx#5935]
Hi, i resently installed open-tx 2.2.1 and it works fine, already been flying my twine engine "sea duck"
When i try to add sounds, the radio says no sounds in memorycard? there is all sounds you ever could need there.
Now im not so good with the tecnical side, im good at flying...lol...atleast i think so!
Need help!!!

Thanks for open-tx.

**Comment by 3djc** [comment]
This tools is for bug traking, which your issue isn,'t. Please to a support forum like rcgroups or openrc

**Comment by weca58** [comment]
Ok, thank you. Will try that!
