### ISSUE TITLE
Feature request: Separate RSSI values for each antenna

### ISSUE THREAD

**Issue by Voltbiter** [opentx/opentx#5938]
I don't know if the hardware design permits this, but it would be helpful to have separate readings for the RSSI values from the two antennas on, for instance, an X8R receiver. This would help with resolving signal strength problems, particularly in sailplanes where range in important and where carbon fiber reinforcement is frequently used in the fuselage.

**Comment by kilrah** [comment]
No way we can know that.

**Comment by Voltbiter** [comment]
Ok Andre – thanks for considering it anyway.
