### ISSUE TITLE
Update open tx and companion

### ISSUE THREAD

**Issue by WimSanders** [opentx/opentx#5945]
I have 2 problems with companion 2.2.0
When I want to upgrade companion to version 2.2.1 I get the error message “downloading failed error transferring http://dounlooad-22.opentx.org/companion-windows-2.2.1exe - server replied: Not Found

When I want to update my Horus to open TX to version 2.2.2 The file is downloaded and next companion give the error “Wrong board !” 

How to solve?

**Comment by 3djc** [comment]
Companion should be downloaded in with the link mentionned here : http://www.open-tx.org/2017/12/16/opentx-2.2.1

OpenTx 2.2.2 has not been released yet

Usage question should be directed to support places like rcgroup or openrc forums
