### ISSUE TITLE
Lag of stottering bluetooth teacher function

### ISSUE THREAD

**Issue by andreasstamm** [opentx/opentx#5952]
Hi have found an issue between  the x7s and X10s in teacher bluetooth mode. Sw is 2.2.1 on both. The X10s ist Master . When teacher on Stick the movement is Fine. On pupil the ist Seele like an lag or that only every 300ms the is a movement. Slave Settings are 22,5 300 -. Greetings Andreas

**Comment by kilrah** [comment]
Yes that is unfotrtunately how poorly the Bluetooth trainer hardware works. Nothing we can do about.
