### ISSUE TITLE
X-lite stick PWM driver

### ISSUE THREAD

**Issue by MikeBland** [opentx/opentx#5953]
I'm porting ersky9x to the X-lite. I notice the openTx PWM driver code for the sticks uses a low interrupt priority of 10. I think this is too low. On my X-lite, I see a short pulse of just 52uS with a stick fully one way.
It is therefore necessary to ensure the stick interrupt is not delayed by this much time or a rising edge capture is lost. If, for example, per10ms() takes longer than this, and occurs at the "wrong" time a rising edge will be lost.
I also note that the period of the PWM signal is not constant. This means that a cetain pulse high time does not always correspond to the same stick position.
I'm using a high priority level (1) and measuring both the duty cycle and the period, and storing them from the interrupt.
I then calculate, when reading the analog values:
Stick position = (duty cycle) * 4095 / period.
This gives stick position values with a range of 0-4095, the same as the analog reading.

I'm doing NO averaging and get a VERY stable result, no noticeable jitter.

Mike

**Comment by schwabe** [comment]
I am still waiting on my X-lite that I orderded online. When it arrives I can take a look at this. I think the rest of the OpenTX has preproduction x-lites which have analog sticks.

**Comment by kilrah** [comment]
Preprod has PWM already, there is (currently...) no Xlite with analog gimbals.

I believe the code actually comes from FrSky and was just included without much questioning beyond checking it worked.

**Comment by schwabe** [comment]
![figure_1](https://user-images.githubusercontent.com/1038539/41863484-40495328-78a7-11e8-8c4b-838cb5b667f1.png)

PWM periods from my preprod x-lite when moving sticks. Maximum difference is 14µs. Ignoring this would cause a 0,4% error. That doesn't sound like much but is actually 15 on the 4096 scale.

With stick centred and not moving (all diagram are compared to average):

Low to low:
![low_to_low](https://user-images.githubusercontent.com/1038539/41864537-a78f9d1e-78aa-11e8-9ee7-e683bc2ed594.png)

High to high:
![high_to_high](https://user-images.githubusercontent.com/1038539/41864547-af29fdb2-78aa-11e8-8141-ed30ca5fdc68.png)

low to high:
![low_to_high](https://user-images.githubusercontent.com/1038539/41864550-b29f076c-78aa-11e8-8f18-e77de8560a65.png)

high to low:
![high_to_low](https://user-images.githubusercontent.com/1038539/41865220-b9330e46-78ac-11e8-84c6-055bc85eb80b.png)


Proposed by Mike:
`4095*(lasthigh-lastnull) /( time -lastnull)` 

![mikes_way](https://user-images.githubusercontent.com/1038539/41864552-b510cde6-78aa-11e8-8a93-78d685c092e2.png)

(unit is wrong in the last one). Interstingly, even though the last one is calculated as floating point it falls into 6 distinctive bins.

Conclusion, Mike is right. Although on my unit I would still see a jitter of -2/+2.

When using the low to high time:
`4095 * (time - lastnull)/3820` 

![low_tohigh_asval](https://user-images.githubusercontent.com/1038539/41865058-4748000c-78ac-11e8-9763-b9898f0d11de.png)

Same using high to next low this time:
![val_highlow](https://user-images.githubusercontent.com/1038539/41865356-11067ae0-78ad-11e8-9280-83018a5e372f.png)

Standard deviations:1.113  1.1819  1.161
For min stick position: 1.236 1.240 1.290
For max stick position: 0.789 0.812 0.794

So yes mikes a approach is a bit better for reading the gimbal.

**Comment by schwabe** [comment]
@MikeBland although I agree with you in principle on the time spent in per10ms and not being able to capture all rising edges, I implemented a simple counter that checks if rising edge to rising edge is more than 6000. I can mange to increase this counter if I throw my left stick into the lower left corner, during which the readout of A1 actually shows 0000 but other than that my counter does not increase and everything stays the same wether I use priority 2 or 20 for the interrupt. Did I make some mistake in my thinking?

**Comment by schwabe** [comment]
I am closing this for now as 968e7233e50a7ba48884896306dbe3fae570a951 should be good enough.
