### ISSUE TITLE
Unable to discover GPS sensors on my Taranis

### ISSUE THREAD

**Issue by OZamirO** [opentx/opentx#5958]
After installing a UBLOX GPS on my quad, and verified it is working (It shows info on the OSD), my X9D fails to discover the GPS sensors.

BF version is 3.3.3
XSR FW is 170619 (using S.Port)
X9D FW is 2.2.1

Am I missing something?

**Comment by 3djc** [comment]
I’m sorry but this place is for tracking bugs, not for support. Please go to forums like regroups or openrcforums

**Comment by OZamirO** [comment]
Sorry for that.
