### ISSUE TITLE
After Installing openTx op Horus X10s I got SD card Content Error

### ISSUE THREAD

**Issue by C64HexCoder** [opentx/opentx#5960]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

After installing OpenTx 2.2.1 on Horus X10S and SD card content : sdcard-horus-2.2V0013, I got SD card Content corrupt error. I've tried to flash over again and reinstalling a new downloaded SD card content and the error apeared again. But after choosing FIX SD CARD CONTENT on first boot, everything seems to be working properly. IS IT?

**Comment by raphaelcoeffic** [comment]
The SD content that you downloaded and installed does not contain the model and radio settings, which is what the error is about. This created on first boot and is absolutely normal.

**Comment by C64HexCoder** [comment]
Thank you. This should be written down on the instructions.

בתאריך יום ב׳, 11 ביוני 2018, 19:04, מאת Raphael Coeffic ‏<
notifications@github.com>:
