### ISSUE TITLE
openTx 2.2.2RC1 R9M latest firmware no 200mw telemetry

### ISSUE THREAD

**Issue by SalterFernandes** [opentx/opentx#5971]
Im using openTx 2.2.2RC1
R9M with 180428 LBT firmware 
R9 Slim with 180425 LBT firmware

Cant get 200mw with telemetry option, just on the 25mw.

**Comment by 3djc** [comment]
Radio type ?

As per Frsky release notes:
Add 16 channels with telemetry and 16 channels **without** telemetry (200mw power) modes.

Their wording is not awfully clear, but means 25mW with telem, 200mW without as far as we know

**Comment by 3djc** [comment]
I just confirmed with frsky, it is : Add 16 channels with telemetry(25mw) and 16 channels without telemetry (200mw power) modes.

**Comment by SalterFernandes** [comment]
Sorry, forgot the radio... its an QX7

Well sorry then for the false report, but they should be clear on the info, i was reading 200mw with and without Telemetry.

**Comment by 3djc** [comment]
Indeed, I have suggested they update their wordiing
