### ISSUE TITLE
Companion not downloading stable release when set to, but only latest RC

### ISSUE THREAD

**Issue by HighPeakRob** [opentx/opentx#5978]
*Before submitting,  search the open issue if there is already a report of the bug*
Couldn't see anything which appeared to be the same issue.

**Describe the bug**
I downloaded OpenTx Companion for version 2.2.1. to an HP laptop running Windows 10.

I set radio to Taranis X7/X7s

I set the application to use only stable releases.

I clicked download firmware and got an RC version.

There appears to be no way to get  the (earlier) stable version of 2.2.1.

So, I uninstalled Companion 2.2.1, downloaded TX companion for 2.2.0, settings already show X7 and stable releases, so uninstall didn't get rid of a log file from somewhere.
Download firmware gave me a 2.2.1 RC release again.

Uninstalled both versions downloaded Companion 2.2.1 again, settings already show X7 and stable releases, so uninstall didn't get rid of a log file from somewhere, firmware download got an even later RC version of 2.2.1.

**To Reproduce**
Behgaviour reproduced on my pc as described above.

**Expected behavior**

Download the stable, non RC version of 2.2.1 from Companion 2.2.1 when the application settings are set to require that. There appears to be no way, unless you have saved a previous version of firmware yourself, to revert to an earlier version.

No screenshots, behaviour was replicated on a Mac, but just once as I had wasted enough time on what seems to be a feature which the software claims to support (Use only stable releases) and also what seems to me to be an essential safety feature (the ability to load a known stable, earlier version)

**Comment by 3djc** [comment]
Are you getting 2.2.1rc99 as shown version ? Please be more precise than just rc, because current rc are 2.2.2rc1, not 2.2.1, so whatever you seem to be getting, they are not current rc

**Comment by HighPeakRob** [comment]
The small 'download' screen shows 
'Firmware opentx-x7-en' and 
'Latest download 2.2.1RC99'

The saved bin file is named opentx-x7-2.2.1 dated 20/06/2018 09:12

Does this mean that companion has downloaded the latest stable release, but the information screen is showing the details of the latest available version, which is an RC? 

If so, I may have a different issue, as my first try at loading Opentx firmware to replace the Frsky initial installed version failed with a message 'firmware incompatible', which I didn't note as I thought it was that I was trying to load an RC version with the 'stable releases' option set.

**Comment by HighPeakRob** [comment]
Sorry, new to GitHub, should just have used 'Comment'

**Comment by 3djc** [comment]
It is a well known version computation display error, it is 2.2.1 stable, as it will show when flashed onto radio.

When replacing FrSky firmware, you will get 'incompatibel firmware' because their firmware is not receognized as 'genuine' OpenTX, this is to be expected
