### ISSUE TITLE
Model Image Preview request (in Model Setup menu -> Model Image file list)

### ISSUE THREAD

**Issue by rjelbert** [opentx/opentx#5981]
When customising a new model in the model setup menu, it would be great to see a small preview thumbnail of the Model Image file as you scroll through the list of available ones available on the SD card. Currently you have to choose the image and then drop out of the model setup screen to see which model image you have selected.

For me, I added the full list of over 1000 mode images to my SD card but could not find the correct one using the X10s OpenTx menus (not helped because of the short file names). Having a preview appear next to the currently selected filename would be very helpful. I use a Horus X10S.

**Comment by kilrah** [comment]
You can go in the SD card browser for a preview and select the image from there.
