### ISSUE TITLE
2.2.2RC2 EEPROM: low memory error

### ISSUE THREAD

**Issue by RipperDrone** [opentx/opentx#5983]
2.2.1 was running ok, getting this error message now. Lua scripts then don't load/execute anymore (BF.lua)

**Comment by RipperDrone** [comment]
deleted all .lua files in betaflight lua script, kept the pre-compiled .luac only in all script folders. Now it seems to fit into memory...

**Comment by kilrah** [comment]
EEPROM low mem is unrelated to lua scripts, it's your model memory that is full.

**Comment by RipperDrone** [comment]
ack - reduced model size and it's gone... thanks!
