### ISSUE TITLE
the function "SetFailsafe" is resetting GV1 to "0" in activated flight mode

### ISSUE THREAD

**Issue by ParkerEde** [opentx/opentx#5984]
Hi,
I've found the following issue with my Horus X10S and OpenTX 2.2.1:
Global function: switch "SA (up)" -> SetFailsafe internal
In the modelsetup I use GV1 in three flight modes for the weight for the input of ailerons.
If I set the switch "SA" to (up) position the failsafe values will set correctly to the failsafesetup, but the value (e.g.65%) in GV1 will also set to "0%" in the activated flight mode.

I've also reproduced it with OpenTx 2.2.2RC2 in Companion.

regards
Ralf

**Comment by 3djc** [comment]
Please post your otx

**Comment by ParkerEde** [comment]
[X10S_2.2.2RC2-GV1-resetting-issue.zip](https://github.com/opentx/opentx/files/2126376/X10S_2.2.2RC2-GV1-resetting-issue.zip)

**Comment by ParkerEde** [comment]
![image](https://user-images.githubusercontent.com/15068446/41759030-7d15e356-75ec-11e8-8b93-4beb21252670.png)

![image](https://user-images.githubusercontent.com/15068446/41759039-8dbf2794-75ec-11e8-95d6-f579da54dd12.png)

**Comment by ParkerEde** [comment]
recheck in 2.2.2N641 -> okay
Thank you
