### ISSUE TITLE
Companion 2.2.2 RC2. error while saving Xlite Firmware: Invalid Board

### ISSUE THREAD

**Issue by Toogo** [opentx/opentx#5987]
Companion 2.2.2 RC2. error while saving Xlite Firmware: Invalid Board.
No error if I download Taranis 9+ firmware.

windows 10/64bit

//Frank

**Comment by 3djc** [comment]
You are trying to download a 2.2.1' firmware for xlite which does not exist. You need to set companion to "Use release and release candidate"

**Comment by Toogo** [comment]
Why can I select xlite than in the fw selection?

**Comment by skaman82** [comment]
having the same error (RC5), cant update my x-lite configuration
