### ISSUE TITLE
Expected behavior.Volume freezes transmitter

### ISSUE THREAD

**Issue by donweihs** [opentx/opentx#5988]
I setup my X-lite for background music  with S2 as a volume control. Everytime I go to minimum volume the transmitter freezes.  I have to cycles turn off and on two times or take out the battery  batteries.

**Comment by 3djc** [comment]
I cannot reproduce. Did you properly calibrate your Sx ?
Please post your otx

**Comment by donweihs** [comment]
Did the calibration again, same result. I did find that if I reset the background music the radio will come back to life. Here is my otx

[Xlite.zip](https://github.com/opentx/opentx/files/2131535/Xlite.zip)

**Comment by 3djc** [comment]
I cannot see any volume settings using S2 in your OTX. Also what is you backgroup music ? Is that thrmlmod/cruise/speed ?

**Comment by 3djc** [comment]
OK, no need for more data, I have been able to reproduce
