### ISSUE TITLE
Companion display error for global functions

### ISSUE THREAD

**Issue by Storchy1** [opentx/opentx#5990]
OpenTX 2.2.2 RC2.

I Have made a Global Function to set GV9 to zero see GF4 
![screenshot_x12s_18-06-25_08-44-52](https://user-images.githubusercontent.com/26022422/41834548-f648558c-7854-11e8-9309-ce21d8f78563.png)

in the companion this function is not displayed correct
<img width="793" alt="companion" src="https://user-images.githubusercontent.com/26022422/41834573-0f16f910-7855-11e8-8b29-6cdeb63a8f43.PNG">

Please have a look

**Comment by kilrah** [comment]
How did you do that? Adjsut GVAR is not available in global functions. Current OpenTX does not let you select it.

**Comment by Storchy1** [comment]
I don't how i have made this, perhaps in former version it was allowed. I have now deleted GF4 and i am not able to create the function once more. You are right, Adjust is not available.
If i find a way to create the function once more i will write you
Thank you very much

**Comment by kilrah** [comment]
Yeah it's possible the check was missing in a previous version. Or I found out you could cheat by setting up an Adjust GVAR model special function then copy/paste it into global functions. That's now no longer possible.
