### ISSUE TITLE
Companion use Jsx and Jsy

### ISSUE THREAD

**Issue by Storchy1** [opentx/opentx#5993]
OpenTx 2.2.2 RC2
Horus X12s
I have a LUA Script to increase / decrease the volume using the Joystick Jsx
How can i use the Joystick Jsy and Jsy in the companion so simulate/check  the volume control of my LUA script
Thanks a lot for your help

**Comment by kilrah** [comment]
There is currently no way to simulate them.

**Comment by Storchy1** [comment]
Thanks a lot
