### ISSUE TITLE
External module in Horus X10S switched on with warning present

### ISSUE THREAD

**Issue by Hartinger** [opentx/opentx#5994]
With OpenTx 2.2.1 I have found that my external M-Link module in the X10S is switched on after changing the model, even if a throttle or switch warning is present. (The internal module is off and the external module set to PPM with the default settings for all models that are currently stored in the radio.)

When the radio is powered up, and a warning is generated, due to the throttle or a switch being in the wrong position, then the radio correctly waits until the warnings are cleared before it switches the external module on.

With my other FrSky radios I have never observed this phenomenon.

**Comment by 3djc** [comment]
Indeed, and it is true for x12s too
