### ISSUE TITLE
[Companion] Issue with Play Track

### ISSUE THREAD

**Issue by pinkywafer** [opentx/opentx#5997]
I am uncertain as to what is causing this issue, but...
I am having issues with "Play track" Special Function on Companion.
Certain tracks work fine, and others do not work at all.

In my case, I am using the Joanne soundpack and can reliably recreate this issue by creating a new model, then using any switch for the SF, set "play Track" "thrdis" (throttle disabled) and simulate...
The track is never played.
if I change to a different track, again some work, some do not.
BUT On the TX, ALL tracks are played fine

**Comment by pinkywafer** [comment]
Using Companion 2.2.2RC2
In both X9D and X7
Note also that the sound CAN be played by clicking the play button on the Special Functions screen, it just isn't played when simulating

**Comment by mpaperno** [comment]
Operating system?

Do the "bad" tracks (files) **always** have this issue (vs. being intermittent)? And just switching to a different track makes it work?

**Comment by pinkywafer** [comment]
Windows 10

It was consistent this evening. I didn't try every track, but some did work and some didn't  (the ones that didn't, consistently didn't and the ones that did, consistently did.)
I was unable to find any common feature between the ones that didn't work 
I also copied the files that didn't work to the sd card to be sure I had the same version on the TX, and still they consistently all worked on tx.

One thought which has just occurred... can sync software cause problems with companion?  I have my sd card structure in a folder which is continuously synchronised with cloud storage. Could this be causing the issue?
I'll test further tomorrow evening

**Comment by notlebowski** [comment]
I think it has something to do with other software having a lock on the file.
Maybe companion wants exclusive access to the file if it wants to play it and other software has also access to it. That other software may even be the OS wanting to preview it.

I experienced it once (but repeatedly). It was solved by closing all windows and starting Companion again. It was only 1 file. 
BTW, I'm also running sync software (in my case it's syncthing  https://syncthing.net/)

Not only have I been using the WAV that had this problem for ages. Thousands of others are using that same file as it's part of the Amber sound set which I'm distributing.

**Comment by mpaperno** [comment]
> It was consistent this evening. I didn't try every track, but some did work and some didn't (the ones that didn't, consistently didn't and the ones that did, consistently did.)

That's what I was looking for, thanks.

> can sync software cause problems with companion?

Possibly, but I would expect such issues to be intermittent.  Plus the timing of file locks would have to be "perfect" and any file system is already built to handle such contention.

There is nothing in the simulator debug output when it can't play a file?

> I think it has something to do with other software having a lock on the file.

Right, there an issue open for that problem already (#5222).  But this sounds different since it's consistent and only in Simulator.

In the simulator (specifically in the simulated firmware), audio is played using a somewhat-dated software library (SDL).  When played from the Companion SFs setup screen a different player library is used (QtMultiMedia).  (Playing on the radio itself is a whole other method entirely.)  My guess is that SDL can't handle something about those specific files.

**Comment by pinkywafer** [comment]
Okay, I have now done more testing, and think that this is #5222 again.
When I first loaded companion today, and tried playing tracks which would not play previously in the simulator, they all worked perfectly.
However, Press the play button on one track in the SF page, then simulate and that sound will now not be played in the simulator `Error 13 (Permission denied)`

However, I do have more details to add to my findings.
I have had a good session testing now and have found that the issue can be Cumulative:
Last night, I did not completely close companion, only the individual models.
Tonight I have had a fresh look:
To recreate:
Open Companion
File-> New
Create a new model
open model for editing
on SF page assign any switch you like to play track for any track you like: Track1
Simulate - Activate chosen switch - Track1 will be played
Exit simulator and press the play button on the SF screen - Track 1 will be played
Simulate - Activate chosen switch - Nothing played - `Error 13 (Permission denied)`
exit simulator
Choose a different track for the SF (Track 2)
Simulate - Activate chosen switch - Track2 will be played
Exit simulator and press the play button on the SF screen - Track 2 will be played
Simulate - Activate chosen switch - Nothing played - `Error 13 (Permission denied)`
exit simulator
Choose the first track again for the SF (Track 1)
Simulate - Activate chosen switch - Track1 **will** be played _(Has now been unlocked! - presumably by playing Track 2)_
Exit simulator and press the play button on the SF screen - Track 1 will be played
Simulate - Activate chosen switch - Nothing played - `Error 13 (Permission denied)` _this is now locked again_
Exit simulator
Exit model
Create new model
open Model 2 for editing
on SF page assign any switch you like to play **Track 1**
Simulate - Activate chosen switch - Nothing played - `Error 13 (Permission denied)` _(Still locked by model 1)_
exit simulator
Choose a different track for the SF (Track 2)
Simulate - Activate chosen switch - Track2 will be played
Exit simulator and press the play button on the SF screen - Track 2 will be played
Simulate - Activate chosen switch - Nothing played - `Error 13 (Permission denied)` _(This now seems to be locked by model 2)_
exit simulator
At this point, if you exit the model, and look at a third model, both Track1 AND Track2 are locked.

It seems that the last track played on the SF page for every model examined is locked and not available for the simulator.
So if you had 5 models, and went to the SF page and pressed the play button for a different track on each one, all 5 of those tracks will be locked for as long as companion is open and will only become unlocked if either a different track is played on one of the 5 models (locking that track instead) or companion is closed completely.
Hope that helps!

**Comment by pinkywafer** [comment]
Additional : Closing the .otx will also unlock the files:
New otx (1.otx)
Create model
SF1 SHdown Play Track Track 1
play button on SF page - Track played
Simulate - activate switch - permission denied
close simulator + model
KEEP 1.otx open
NEW otx (2.otx)
new model
SF1 SHdown Play Track Track 1
Simulate - activate switch - Permission denied
Close simulator
close 1.otx
simulate model in 2.otx again - activate switch - Track played

**Comment by pinkywafer** [comment]
I've just been having a look at the code for this and the documentation of the QMediaPlayer.
It seems that "Stopping", does not terminate I/O with the file allocated by setMedia

so, in custonfunctions.cpp line 273:
```
void CustomFunctionsPanel::onMediaPlayerStateChanged(QMediaPlayer::State state)
{
  if (!lock) {
    lock = true;
    if (state==QMediaPlayer::StoppedState || state==QMediaPlayer::PausedState) {
      mediaPlayer->stop();
      if (mediaPlayerCurrent >= 0) {
        playBT[mediaPlayerCurrent]->setIcon(CompanionIcon("play.png"));
        mediaPlayerCurrent = -1;
      }
    }
    lock = false;
  }
}
```
This function I believe simply needs to release the file by using setMedia to a null QMediaContent:
```
void CustomFunctionsPanel::onMediaPlayerStateChanged(QMediaPlayer::State state)
{
  if (!lock) {
    lock = true;
    if (state==QMediaPlayer::StoppedState || state==QMediaPlayer::PausedState) {
      mediaPlayer->stop();
      mediaPlayer->setMedia(QMediaContent());
      if (mediaPlayerCurrent >= 0) {
        playBT[mediaPlayerCurrent]->setIcon(CompanionIcon("play.png"));
        mediaPlayerCurrent = -1;
      }
    }
    lock = false;
  }
}
```

**Comment by mpaperno** [comment]
Wow... thorough!   :+1: 

I think you're right about QMediaPlayer.  I also think we should use QSound instead... much simpler and to the point.

**Comment by mpaperno** [comment]
Well QSound wouldn't work because no "finished" signal. The trick with null QMediaContent() did work, but turned out setting the `QMediaPlayer::LowLatency` flag did also and works better.  But due to other caching behavior, best course of action was to create/destroy a QMediaPlayer for every play/stop event.  :roll_eyes: 

And found another bug, this time on simulated firmware side, with Play Background Music... described in #6000.
