### ISSUE TITLE
Cheap Current Sensors - Allowing for negative reading on A1 and A2

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#6]
_From [joaoalve...@googlemail.com](https://code.google.com/u/107758819364615868605/) on March 24, 2013 15:31:11_

Which board (stock / gruvin9x / sky9x / Taranis) are you using? Atmega128 on Stock Board

Ok, let's see if I can explain this idea.
I've been following a thread on 9xforums.com about those cheap current sensors that you get from China. They are quite cheap.
The problem is that some of them read negative and positive current with zero amps at 2.5V
So from 2.5V to aprox 0V they read from 0A to -100A
from 2,5V to aprox 5V they read from 0A to 100A

There was someone trying to make it work with open9x and he was using the negative side of the measurement because apparentlly can get more resolution. 
so then we have 0 Amps at 2.5V and -100 in theory at 0V
the reading of the analog ports would as far as I understand have to be inverted?

well, you get the idea. It would be nice if we could use those sensors because they are so cheap and we never know, maybe the possibility to read negative values would be a good addition to open9x..

I do apologise if I'm not able to explain it properly..

JHSA

_Original issue: http://code.google.com/p/opentx/issues/detail?id=6_

**Comment by projectkk2glider** [comment]
Solved with the new telemetry system in 2.1
