### ISSUE TITLE
Turnigy 9x stock firmware download retrive "Invalid Board"

### ISSUE THREAD

**Issue by Ubishiro** [opentx/opentx#6012]
I have a Turnigy 9x v2 (with IBUS/SBUS) with m64 chip. 

When Companion tries to download the firmware it can because says "Invalid Board".  

I only can do the upgrade with 2.0 version of companion but no IBUS type in the protocols. I trie companion 2.1 also but same error.

**To Reproduce**
1. Choose Radio Type 9X with stock board
2. Download It
3. Prompt "Invalid Board"

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX Companion (2.2.2RC2 on Win10)

Thanks

**Comment by kilrah** [comment]
Support for the 9x was removed in 2.2. 2.1.9 is the last OpenTX version that will run on it.
http://www.open-tx.org/2018/02/26/avr-pull
