### ISSUE TITLE
In simulation - missing sliders

### ISSUE THREAD

**Issue by Hudla** [opentx/opentx#6024]
hello,

The Companion 2.2.1 for FrSky X9D + radio is not a side slider display in the simulation.
Thank you in advance

Robert

**General information**
 - OpenTX version 2.2.1
 - Hardware Frsky X9D+ 
 - OpenTX Companion 2.2.1

![image](https://user-images.githubusercontent.com/40960844/42422261-e8f28766-82e2-11e8-820e-51a7a5a2de93.png)

**Comment by mpaperno** [comment]
Do you have the sliders configured in Radio Settings for this file? 

![image](https://user-images.githubusercontent.com/1366615/42422415-68ccc4ea-82b3-11e8-8752-d4d4625c525d.png)
 (Image is of X9E, there would only be two slots with that option on an X9D)

**Comment by Hudla** [comment]
Thank you very much for your advice.
I'm a little shy that I did not get it.
Next time I will be smarter ... 
:-)

**Comment by mpaperno** [comment]
No problem, you/re not the first!
