### ISSUE TITLE
Store Telemetry Simulator sensor settings & values

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#6025]
V2.2.2 RC4
After programming and testing a model  at companion
I set the telemetrie simulation with some sensors for testing,  thats ok, works.
after closing  simulationscreen, modell programm changing and reopen the simulation, 
my telemetrie settings are zero
How can I store my settings for Telemetrie settings

**Comment by mpaperno** [comment]
This is not possible at the moment.  It is on the "wish list."

If you use the standalone version of Simulator (not through Companion) with the same data file (.otx), then you can make changes on the simulated radio, so you don't need to close the simulator.  The changes will be saved to the .otx file, which you can then open in Companion again.   If needed, you can restart the simulated radio, or reload Lua scripts, w/out closing the sim.

Related: #5003, #4434, #4256
