### ISSUE TITLE
X-Lite: No way to get to second telemetry screen

### ISSUE THREAD

**Issue by ArchmageAU** [opentx/opentx#6027]
For the X-Lite controller there seems to be no way to get to the second (or subsequent) telemetry screens.

To Reproduce
1. Create new model
2. Configure 2 telemetry screens (numbers, any values)
3. Go out of configuration into model.
4. Long down on configuration joystick goes to first telemetry screen. (equivalent of long press "page" on X9D)
5. Long down on configuration joystick again DOES NOT go to second telemetry screen.

No other combination of long and short pushes on any button seem to be able to get to the second telemetry screen.

 - OpenTX 2.2.2RC4 for X-Lite.
 - Hardware: X-Lite
 - Reproducible on Companion 2.2.2RC4 or X-Lite controller

**Comment by kilrah** [comment]
Shift + long left/right.

**Comment by ArchmageAU** [comment]
Thank you.  Could not find it documented anywhere.  Tried everything I could think of.
