### ISSUE TITLE
Scripts called by Global Functions run for all models whether or not Global Functions is checked.

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#6029]
Observed in Companion, nightly build 2.2.2N655, set for X9D+ and again set for X-Lite. Not confirmed in any radio.

Set any function script to be activated as a Global Function and it will work with any model selected, no matter whether or not the Global Functions box is checked on that model's Setup page. 

Example:

Name this simple script "99mph.lua", store it in SCRIPTS/FUNCTIONS, and set it to run as a Global Function with switch set to "ON".

local function run_func()
playNumber(99, 8)
end
return {run=run_func}
 
Simulate any model in memory and it will repeat "99 miles per hour" whether or not the Global Functions box is checked.

**Comment by Miami-Mike** [comment]
Now, as of 2.2.2RC5, there are at least some cases where a script called by a special function won't load unless global functions are enabled.

**Comment by kilrah** [comment]
Example and way to reproduce?
Note you have to reboot the radio/change model whenever things are changed around Play script functions or now the Enable Global functions checkbox if you have global function scripts. Function scripts are loaded once at model load and then kept in memory, I've noticed very weird things can happen if you remove them after they were loaded (also before my commit).

**Comment by Miami-Mike** [comment]
I learned a little more about why the problem doesn't always show up. Here's an example script named _test.lua_:

    local n = 1
    local function run_func()
        n = n + 1
        print(n)
    end
    return {run=run_func}

Set up two special functions to run it:

SF1 SA↑ Play Script test
SF2 SA↓ Play Script test

Watch Debug Output. If Global Functions is checked then it'll work with either SA↑ or SA↓, but with Global Functions not checked, it'll only work with SA↑, not SA↓.

**Comment by kilrah** [comment]
It breaks something indeed. Can't understand what so I have to revert the fix and someone else will hopefully look at it.

**Comment by lshems** [comment]
dangerous??
