### ISSUE TITLE
Companion Edit Radio Settings issue

### ISSUE THREAD

**Issue by marcogpw** [opentx/opentx#6030]
In the Edit Radio Settings tab of Companion (RC4 version on PC) at the GPS Coordinates, there are 2 options, like on the radio setup menu on the radio. In Companion the options are hh° (N/S) mm' ss".dd this is not correct for coordinate systems ... in the radio it states DMS for Degrees, Minutes and Seconds, somehow in Companion it is stated as Hours, Minutes and Seconds. 
I was setting up my XLite and saw it in the edit radio settings tab.
Minor flaw ...

**Comment by raphaelcoeffic** [comment]
@elecpower Hey! It seems the necessary changes have already been implemented and merged. Can you please confirm that we can close this issue?

**Comment by kilrah** [comment]
Yeah it was just not auto-closed becasue the ref was missing in the PR
