### ISSUE TITLE
OpenTx 2.2.2 RC4 - "Trim Idle Only" affects Elevator channel instead of Throttle channel

### ISSUE THREAD

**Issue by mcddd** [opentx/opentx#6032]
Tested 2.2.2 RC4 in Companion and on a X9D with the same results.

When the Trim Idle Only function is activated, it is affecting the operation of the assigned Elevator trim on the Elevator channel instead of the operation of the assigned Throttle trim on the Throttle channel.  Crossing the elevator and throttle trims still results in the Trim Idle Only function affecting only the operation of the assigned Elevator trim (TrmT) on the Elevator channel instead of the throttle trim and channel.

**Comment by 3djc** [comment]
It got fixed a while ago, then rebroken. Looking at it

**Comment by 3djc** [comment]
Well, no, I cannot replicate it

![image](https://user-images.githubusercontent.com/5167938/42556373-ad1c1cec-84eb-11e8-8dfb-dd57a984cc7e.png)


[6032.zip](https://github.com/opentx/opentx/files/2183378/6032.zip)

Please include OTX if you want us to have a look

**Comment by mcddd** [comment]
Note:  Setup is Mode 2 with TAER channel order.  Trim Idle Only is turned on.  Trims are not crossed.

Elevator trim has no effect at full down elevator stick, but has full effect at full up elevator stick, just like Trim Idle Only is supposed to work with the throttle channel.

Throttle trim affects the throttle channel regardless of throttle stick position, as if the Trim Idle Only was turned off.

[071118.zip](https://github.com/opentx/opentx/files/2185173/071118.zip)
