### ISSUE TITLE
Request: Please make the trim switches available to Lua.

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#6040]
Lua can read trim-ail, trim-ele, trim-rud, and trim-thr via the getValue() function, but it would be nice to have a way to directly read the states of those switches even when they're disabled. I don't want to read the trim values, I want to disable a trim on the Flight Modes tab and use the trim switches for something else.

**Comment by StefanKellerAC** [comment]
yes, that would be helpful.
additionally it would be good to be able to set individual trims with the special functions and with Lua...

**Comment by Miami-Mike** [comment]
I think the developers want us to keep each individual request or issue in its own separate thread because of the way they're managed here.

**Comment by StefanKellerAC** [comment]
done. #6098
in addition to your request: 
when a trim is disabled the announcements "maximum trim reached" and "trim centered"  should not be spoken.

**Comment by Miami-Mike** [comment]
I can't figure out what you're talking about. When a trim is disabled those announcements ****aren't**** spoken. In fact, nothing visible or audible happens when a disabled trim switch is actuated, unless a special function is set up to be activated by it. I tried it in Companion 2.1.9 and 2.2.2.

At any rate, if you really think the issue exists then you should start another thread about it like you did before.

**Comment by StefanKellerAC** [comment]
ok, I had to disable the trim in the flight mode not in the Input, to disable the announcements.

**Comment by RC-SOAR** [comment]
I'd like to add further weight to MiamiMike's request (which seems to have got lost in the fog): a Lua function please, to return the raw state of a trim lever:

**getRawtrim ([name|id])**
returns -100 (down), 0(centre) or 100(up)

Yes there's a workaround (define 3 SF's to update a GV, and query the GV in Lua), but it's messy and it uses up a precious GV. Having a dedicated function would make it much easier to use the trim levers as general purpose 3-pos switches, very useful for applications which need to repurpose trims (with the trim disabled in the flight modes menu). No need to handle repeats and callouts, this can be done more flexibly in the Lua script.

**Comment by kilrah** [comment]
Um the trim keys are switches, so you should be able to get them as that?

**Comment by RC-SOAR** [comment]
That's what I hoped, but **getValue("trim-ele")** returns a non-zero value only if the trim is enabled in the FM menu. 

If the trim is disabled, then **getValue ("trim-ele")** returns zero regardless of the state (up/down/middle). Companion 2.2.3, X9D sim.

**Comment by kilrah** [comment]
OK, this returns the trim register, seems there's indeed no way to access just the keys.

**Comment by lshems** [comment]
Yes please.

**Comment by RC-SOAR** [comment]
Shame if it can't be done, it would turn OpenTx into the complete Jeti killer for glider applications. Users could easily retrofit stuff like dynamic trims, not possible with any current radio AFAIK. Currently, the workaround method (1 GV + 3SF's) isn't possible without extra work and compromise.
