### ISSUE TITLE
OTX 2.2.2RC4, RAS/SWR

### ISSUE THREAD

**Issue by Nihonski** [opentx/opentx#6042]
I still would like to indicate SWR as a telemetry value, so I tried to a create a sensor input manually with ID F105 and instance 25, however there is no value indicated.
When check the S.Port mirror on my X9D+, the data string for SWR is still there, but why I cannot set it up for indication on the screen?

**Comment by schwabe** [comment]
Read the news of OpenTX 2.2. SWR is not available as telemetry anymore, only as RAS under HW.

**Comment by Nihonski** [comment]
Hi,
I know the change notes of OTX and I understand that you don’t want anymore SWR or RAS accessible to common users for the reason of misunderstanding.
I don’t mind, if the SWR/RAS is not indicated anymore when sensor search is initiated.
However would it be possible to access SWR/RAS by manual setup only, which, lets say, only technically interested users bother to set up?
best regards
Ewald
 
Von: Arne Schwabe [mailto:notifications@github.com] 
Gesendet: Freitag, 13. Juli 2018 19:15
An: opentx/opentx
Cc: Nihonski; Author
Betreff: Re: [opentx/opentx] OTX 2.2.2RC4, RAS/SWR (#6042)
 
Read the news of OpenTX 2.2. SWR is not available as telemetry anymore, only as RAS under HW.

**Comment by schwabe** [comment]
you can still see the SWR/RAS under the hw analogs.

**Comment by 3djc** [comment]
And obviously, should RAS get into error level, the radio will tell you also.

**Comment by schwabe** [comment]
But too many users thought RAS good means no problem. But it is only RAS bad means that you have a problem.

**Comment by Nihonski** [comment]
I know, but its very troublesome to check the value by this way before every flight.
Moreover there is no way to set the threshold of the warning.
If I cant see, I would at least decide by myself, when I get a warning.
Pitty, the SWR HW is there, but cant be used easily.
 
 
Von: Arne Schwabe [mailto:notifications@github.com] 
Gesendet: Dienstag, 17. Juli 2018 12:34
An: opentx/opentx
Cc: Nihonski; Author
Betreff: Re: [opentx/opentx] OTX 2.2.2RC4, RAS/SWR (#6042)
 
you can still see the SWR/RAS under the hw analogs.

**Comment by schwabe** [comment]
@Nihonski that would describe is exactly what is the problematic behaviour. If you are checking RAS before every flight, you are trusting the RAS value. Experience shows that it cannot be trusted unless it is high.

**Comment by 3djc** [comment]
Thats the whole point ! It is NOT by any mean an analog read of swr. It is a strange pass/fail logic with analog output. If they had know from start the mess it would make, they probably would have put just an additional transistor to properly switch 0/1, but they wanted to save one I guess

**Comment by kilrah** [comment]
It's accessible to lua scripts I believe.

**Comment by Nihonski** [comment]
I think the problem is, that the analog signals of the forward and return RF-detetectors are not properly filtered, neither by HW, nor by SW. The detetcor signal has quite some ripple, and sporadic drop outs because of LBT. Any SW filtering needs to by synchronised with the tx/rx cycle.
I could fix that, but would like to adjust the warning threshold.

**Comment by schwabe** [comment]
@Nihonski You are free to do so. And as @kilrah said the value is accessible via LUA. If you do your modifcations to OpenTX itself you can also modify the settings there. 

But I would suggest not spending to much time on it.

**Comment by kilrah** [comment]
There is also no calibration at all nor any effort to keep tolerances of the detector. It was never designed to provide more than hopefully a pass/fail information.

**Comment by Nihonski** [comment]
Ok, thank your feedback and spending your time. Closing the issue is fine with me.
