### ISSUE TITLE
Bluetooth Init not working on X-Lite

### ISSUE THREAD

**Issue by alex-vg** [opentx/opentx#6048]
*Before submitting,  search the open issue if there is already a report of the bug*
Seems to be discarded in #5828?

**Describe the bug**
Bluetooth Module not working in X-Lite

**To Reproduce**
1. Solder Horus X12 BLE Module into X-Lite
2. See the now visible Trainer Menu
3. Select Trainer Mode: Trainer Master
4. Error

**Expected behavior**
Enabling Trainer Master should initialize Bluetooth Module successfully and search/list devices

**General information**
 - OpenTX 2.2.2 (xlitefccM2_20180622, e3ea8595)
 - Hardware: X-Lite

**Comment by kilrah** [comment]
What "error"?

Works on our preprod Xlites with a module. Horus module may or may not be different/compatible.

**Comment by alex-vg** [comment]
> Horus module may or may not be different/compatible.

Well, then that is probably the problem. Any clue which module was used and where we can get it?

**Comment by alex-vg** [comment]
Got it working. My first module was faulty. If anyone is interested: It's the FrSky Horus X10S/X12S module. There seems to be only one module for all TX. You also need a bt antenna, obviously. After enabling telemetry or trainer for bt, a restart is required. The module should also work in a QX7.

**Comment by 3djc** [comment]
This is not quite true, X9E uses a different BT chip

**Comment by alex-vg** [comment]
What is different? RF BM S02I looks exactly the same, just unbranded.

**Comment by 3djc** [comment]
The X9E BT doesn't have bootloader and uses a different protocol
