### ISSUE TITLE
missing REPT event on x-lite

### ISSUE THREAD

**Issue by hsuq510** [opentx/opentx#6052]
Please add  event key EVT_PLUS_REPT and EVT_MINUS_REPT support for  x-lite.

**Comment by kilrah** [comment]
Where, for what??

**Comment by hsuq510** [comment]
thats maybe my missunderstanding but MINUS and PLUS are not present in the x-lite code,  that because RIGHT and LEFT ? in that case RIGHT and LEFT have REPT and you can close this.

**Comment by schwabe** [comment]
yeah, there are no physical +/- keys like on the X9D+.
