### ISSUE TITLE
Horus: LUA: degree sign in strings causes widget crash

### ISSUE THREAD

**Issue by n9rai** [opentx/opentx#6055]
when using the degree sign "°" in widgets the script crashes. But there is a degree sign in the font files before the "A". How can i use this?

**Comment by 3djc** [comment]
Given the radio type and OpenTx version are not specified, thats not an easy one to answer...

**Comment by mpaperno** [comment]
To get a degree symbol printed to the LCD you need to use the "at" character `@` in the actual script. Using literal `°` will likely cause a crash.
