### ISSUE TITLE
Companion 2.2.2 RC5. error while saving Xlite Firmware: Invalid Board

### ISSUE THREAD

**Issue by skaman82** [opentx/opentx#6056]
I can select the X-Lite in the menu but can't change any configuration for my TX (LUA/FAIMODE a.s.o).
If I want download the new build I get "Invalid Board" Message. How it is possible to change the firmware?

**Comment by kilrah** [comment]
You must configure companion to download release candidates.

**Comment by skaman82** [comment]
Thanks @kilrah, where can I find this setting? EDIT. found it!
