### ISSUE TITLE
2.2.2 RC5 X7 flashing options sorting

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#6058]
I have found that in 2.2.2 is diferent flashing sorting then 2.2.1. 
In 2.2.2 when i eleft file from SD hold the enter see flash internal module and then flash external device
in 2.2.1 is external device flash on first line 

I recommend to change like in 2.2.1 to have first external device flash, firstly it is known sorting from 2.2.1 and we this way prevent flashing bad FW to internal module by accidentally pressing enter more time.

**Comment by 3djc** [comment]
?

![image](https://user-images.githubusercontent.com/5167938/43093222-c31acc32-8eaf-11e8-80d8-a3a5c69ff217.png)

**Comment by kilrah** [comment]
He probably has a first batch X7 without bottom connector. Issue would only apply to those few, aka not very important.

**Comment by janekx** [comment]
Yes first ones batch have diferent sorting, any way in newer should be as well  S.Port, External, Internal.

**Comment by 3djc** [comment]
After discussion with @bsongis , we have made that change, it will be in release version

**Comment by janekx** [comment]
In fact I meet many bad flashed radios even the option flash internal module is on second or third place, maybe will be good to add warning like, "Warning flashing internal module with incorrect firmware can make internal module inoperate." Yes Enter or other key to cancel.
