### ISSUE TITLE
Cannot set correct GPS Time-Zone X9D+ 

### ISSUE THREAD

**Issue by arnabraha** [opentx/opentx#6062]
Unable to set +5:30 GPS time zone. Can set +5 or +4, but not +5:30 Hrs.

This is a very useful feature with "Adjust RTC" function. I believe its about time to fix this years old problem.

In Radio Settings
![unable to set correct time zone](https://user-images.githubusercontent.com/22033050/43358866-48a3872c-92b6-11e8-8d8c-22b3b21c9e5a.png)

**General information**
 - OpenTX version 2.2.2
 - Hardware Frsky X9D+
 - OpenTX Companion 2.2.2

**Comment by arnabraha** [comment]
I would like to clarify more - The time zone in 30min steps cannot be done with the Radio and the companion software both; since this feature does not exist. It is very important to address this issue - with OpenTX being adopted at so many countries with various time zones.

**Comment by 3djc** [comment]
Duplicate #1653

As it requires an eeprom change, it wont be done before next major version
