### ISSUE TITLE
Modelselection does not remember the actual model / modelcategory

### ISSUE THREAD

**Issue by ParkerEde** [opentx/opentx#6063]
Hi,
since 2.2.2:
while open modelselectionscreen, the Horus X10 marks always the first model in the first modelcategory.
This is not good.
In 2.2.1 the modelslectionscreen is coming up with the last selected model in the last modelcategory. This is much more better than the behavior in 2.2.2. 
Can you please fix it?

Kind regards
Ralf

**Comment by ParkerEde** [comment]
I've to specify the behavior in 2.2.2.

new information:
while open modelselectionscreen, the  Horus X10 marks always the first model in the last active modelcategory which was selected at PowerOn. 2.2.2 does not store the model/modelcategory while the radio is powered on and you change to a model from another modelcategory.

**Comment by tueddelclick** [comment]
It's the same for me:
I switch on the HorusX10 (openTX 2.2.2) and open the model selection. It displays the models from the category "Trainer". Now I am switching to the category "Glider" and choose a model. Opening the model selection screen again the Horus is again displaying the category "Trainer" (the category that was active at the transmitter start). In version 2.2.1 it behaves not like this. This version noticed the category of the last chosen model correctly.

**Comment by ParkerEde** [comment]
It would be nice if this request could be reconsidered.

**Comment by tueddelclick** [comment]
Because it is working in 2.2.1 I hope there‘s a chance to solve it.

**Comment by ParkerEde** [comment]
It would be nice if this request could be reconsidered.

**Comment by pascallanger** [comment]
This weird behavior is still in the current 2.3.5.

**Comment by 3djc** [comment]
Obviously, if not, this would be closed !

**Comment by pascallanger** [comment]
Just preventing the bot to close it ;-)
