### ISSUE TITLE
Mixer outputs display clipping at about +-100%

### ISSUE THREAD

**Issue by Gewe99** [opentx/opentx#6064]
Companion 2.2.2
Displaying  Mixer values in the new Mixerwindow is buggy...
eg. Output from the ElevMixer: +-200%
Moving the stick slow, the Mixer does not show  values more than about +- 102%.
Moving the stick very fast, you can see bigger values up to the expected +-200%
The values in the radios display are  correct...

**Comment by kilrah** [comment]
No idea what you're talking about... What radio? what screen? Any screenshot?

**Comment by Gewe99** [comment]
![mixer](https://user-images.githubusercontent.com/27633575/43393993-a3401e4c-93e8-11e8-8413-ea2ef8522290.JPG)
Look at CH2 (Elevator) in the Mixer Window on the right side...
On all Radios...
