### ISSUE TITLE
Taranis QX7 dead after 2.2.2

### ISSUE THREAD

**Issue by abramose** [opentx/opentx#6065]
Hi, upgrade my QX7 from 2.2.1 to 2.2.2.

All worked for me and after i charged my 2 x 18650 Cells, i bind a new R XSR.

After this the Taranis reboot and start with a "!" in the right corner.
Hmmm, ok...
So battery in and out, since this time i will not start and can not conncet to the PC.

Searching for help!

**Comment by 3djc** [comment]
Sorry, but this is not a support area, only one for managing opentx bugs, which yours isn’t. Please go to places like regroups ou openrc forum.
