### ISSUE TITLE
2.2.2 X9E always shows "Model still powered" in last screen

### ISSUE THREAD

**Issue by FS4000** [opentx/opentx#6068]
After updating from 2.2.1 to 2.2.2, I turn off my X9E (confirmation selected)
and in the last screen there is always the message "Model still powered"
without any receiver is in the near.
If a model is still powered, the right message in **bold letters** is shown before.

Greets and thanks for your hard work, Uwe

**Comment by 3djc** [comment]
I cannot reproduce. Please give more details

**Comment by FS4000** [comment]
I selected the German language for my Opentx. Maybe its only in the German translation.

Greets, Uwe

**Comment by OpenMik** [comment]
Also for my radio 9XE with OpenTx 2.2.4 message
"model still powered" is showed every time during shutdown
Italian language

**Comment by kilrah** [comment]
Have you selected the "shutdownconfirm" option?

**Comment by OpenMik** [comment]
yes

**Comment by kilrah** [comment]
Then it's jsut the wrong message but the requirement for always having to confirm is what you asked for.

**Comment by OpenMik** [comment]
Yes is only a wrong message
At shutdown appears together the the "Model still powered" message and the shutdown confirmation but  pressing  enter the radio shutdown correctly
