### ISSUE TITLE
2.2.2 X9E left and right slider not shown in calibration screen

### ISSUE THREAD

**Issue by FS4000** [opentx/opentx#6069]
After udating from 2.2.1 to 2.2.2, my X9E do not show the left and right slider
in the calibration screen.
Both sliders also missing in companion.
If i opened a file from _rc-soar.com_ "E-Soar Plus", companion shows the
two sliders.

Greets, Uwe

**Comment by 3djc** [comment]
They are present. If you do not see them, it is probaly that those are not properly declared in radio Hardware page
