### ISSUE TITLE
Horus X12S - momentary switch F

### ISSUE THREAD

**Issue by Stuntman2** [opentx/opentx#6070]
I have replaced the one way switch F with a momentary switch and using the sticky function in Logical Switches it acts as a pull on pull off switch. Up to the final release (2.2.2) companion simulator mimicked the transmitter ie when TX first switched on SW-F was off both on the TX and in Companion simulator, after upgrading to 2.2.2 the simulator outputs screen showed SW-F as on, but on the transmitter at switch on it is off.

**Comment by kilrah** [comment]
You should set the correct switch type in the Hardware settings instead of the sticky function...

**Comment by expipiplus1** [comment]
@kilrah Would you be able to post a link to one of these tutorials, please?
