### ISSUE TITLE
GIF as Splash Screen for Horus X10(S)

### ISSUE THREAD

**Issue by IsmaFPV** [opentx/opentx#6071]
In addition to what was implemented in OpenTX 2.2.2, it would be nice to being able to use also gifs as custom splash screens.

The boot animation in FrOS looks neat! :)

**Comment by OpenUAS** [comment]
As an optional setting, fine, feel free to implement. It will keep puzzling... don't you just want you TX to switch on as fast as possible to be used without delay? But then again everyone is different :grinning:
