### ISSUE TITLE
9x turnigy radio update does not display the telemetry screen

### ISSUE THREAD

**Issue by bazizabr** [opentx/opentx#6075]
I choose the frsky option, even then the telemetry screen does not appear.
Neither pressing dowm nor the settings.

**Comment by kilrah** [comment]
Version? Flashed correctly?

**Comment by bazizabr** [comment]
2.0.2
Yes, normally.
Only the telemetry that does not appear.
Even by choosing the FRSKY option

**Comment by bazizabr** [comment]
Where can I find firmware FRSKY version 2.0.2?
I could not find it.

**Comment by bazizabr** [comment]
Sorry, I wanted to say 2.0.1 FRSKY firmware.

**Comment by kilrah** [comment]
2.0.1 and 2.0.2 are many years old and deprecated. You can get 2.0.20 or 2.1.9 from the respective companion versions.

Please note this is a bug tracker and not a user support system.

**Comment by bazizabr** [comment]
Really, thank you.
