### ISSUE TITLE
incorrect altitude reported

### ISSUE THREAD

**Issue by peteoz** [opentx/opentx#6077]
OpenTX 2.2.2
Taranis XD9+

running micro UBlox unit on my BF quad, shows correct altitude on BF OSD but Taranis reports totally irrelevant numbers.
Taranis set to metric system.

example : my real altitude is 1440m (also showing correctly on my BF OSD) however Taranis is reporting around 12000. even when converted to feet that would still be way off.

not sure if this is a bug in OpenTX

thx

**Comment by 3djc** [comment]
Using frsky sensor, it does work properly. It is up to your FC software to properly send the data, it does not seem like an OpenTX issue

**Comment by peteoz** [comment]
thx. looks like there was a bug in BF 3.4 causing this, it should be fixed in next release
https://github.com/betaflight/betaflight/issues/6505
