### ISSUE TITLE
Horus x12S display freeze/firmware crash on channels monitor

### ISSUE THREAD

**Issue by PatrizioPasquali** [opentx/opentx#6078]
Hi
When i use the monitor function, after few seconds, the Horus display stop working;  freezing the image and i can't switch off the tx; to do this i must unplug the battery.
I loaded the last relased version of Opentx 2.2.2 on my Horus X12S .
I choosed LUA and LUAC options
Take into account that i am very new with Horus, and presently I am traying to set up some display widgets, so some my wrong can be.

thanks
Patrizio

**Comment by mpaperno** [comment]
The "monitor function" is the channels monitor screen?

Does this happen without touching any controls on the radio? Specifically the scroll wheel?

You should probably post your .otx file.

**Comment by PatrizioPasquali** [comment]
Yes: channel monitor screen
Exactly,  This happen when i touch the scroll wheel, immediatly after have choosed this function.
Sorry, now i have to unplug the battery.
After this I can load and send the .otx file

**Comment by PatrizioPasquali** [comment]
With the  monitor freezed the TX continue to work properly on the servos

**Comment by PatrizioPasquali** [comment]
[document 2 aug 2018.zip](https://github.com/opentx/opentx/files/2253147/document.2.aug.2018.zip)

**Comment by antgeebee** [comment]
Im having the same issues except if I hold the off button down for around 10 sec or so it switches off...until 
the next time the monitor function is selected and the rotary wheel rotated
nothing but the servos and the sound works

**Comment by bsongis** [comment]
Anybody succeeds to reproduce it?
