### ISSUE TITLE
Clock on home screen

### ISSUE THREAD

**Issue by salem83** [opentx/opentx#6080]
Hi 
I've recently changed from a  Taranis X9D to a X-Lite. But i'm missing the clock in the top right corner
I know its hard to put all information needed on a 128×64 display. But, would the be any possibility to accomplish this?

e.g. Putting the clock on the top right corner? If the model name full size, then tho clock should be shown in front of the model name
This should also be configurable in the Radio setup to show the clock or not. 

Thanks in advance

**Comment by 3djc** [comment]
No, the screen is absolutely, absolutely full. There is simply half of the pixel that X9 has.

You can very easly make a telem screen with clock on it, or a special function to give you time periodicaly or on demand
