### ISSUE TITLE
[FrSky X-LITE] Can't switch between configured display screens.

### ISSUE THREAD

**Issue by fOmey** [opentx/opentx#6085]
Holding down on the joystick on the homescreen opens up SCREEN 1, although you are unable to switch to any other configured screens.

**Comment by 3djc** [comment]
This place is not for usage support, please submit usage question to support places like rcgroups or openrc forum.

(Shift + long left/right.)

**Comment by skylupop** [comment]
> Holding down on the joystick on the homescreen opens up SCREEN 1, although you are unable to switch to any other configured screens.

I found the solution here: https://www.youtube.com/watch?v=lXCcg2S3_RE
