### ISSUE TITLE
OpenTx Companion 2.2.2 Bug in model print and compare switch warnings for Horus X10 & X12

### ISSUE THREAD

**Issue by Hartinger** [opentx/opentx#6086]
The model compare feature in Companion 2.2.2 (Horus X10 profile) seems to have a bug with regards to the switch warnings. See attached screen shot showing actual settings in model editor vs. report from model compare facility (German language).

![comp_issue](https://user-images.githubusercontent.com/22352021/43683863-46d66128-9895-11e8-8f5e-c7a3782e0eea.PNG)

I could not observe this phenomenon when the Taranis QX7 profile was used.
I can't remember having seen this with 2.2.1 but cannot rule it out either.

**Comment by elecpower** [comment]
Confirmed issue for Horus X10 and X12 profiles. X9D+, X9E, X7 and X-Lite profiles tested okay. All tests were performed on a new model file for each profile.
Repeatedly running the print function results in the switch values changing and duplicating switches.
![screenshot from 2018-08-06 07-24-53](https://user-images.githubusercontent.com/15316949/43690387-5878acd0-994c-11e8-81f1-5749df8d5e1d.png)

**Comment by elecpower** [comment]
So I performed some more tests on using Horus 10 profile and discovered the model print is affecting the model settings.

Steps to reproduce:
1. New Horus 10 profile
2. New model file
3. New model using wizard accepting all defaults
4. Open model edit  and select settings tab - noting all switches displaying in up positions
5. Close model edit
6. Click print model - noting different switch settings printed to step 4
7. Close print
8. Open model edit settings tab - noting switch settings changed.

I haven't been able to reproduce this behaviour for Taranis profile. A couple of screen shots for evidence.

![new model 1](https://user-images.githubusercontent.com/15316949/43692770-865ccc6e-996d-11e8-9c17-75a805b69290.JPG)
![new model 2](https://user-images.githubusercontent.com/15316949/43692771-8a017b9e-996d-11e8-95f6-4cbca8ccf2f2.JPG)
![new model 3](https://user-images.githubusercontent.com/15316949/43692775-8fb767c4-996d-11e8-8ca3-072e7c54ef04.JPG)
