### ISSUE TITLE
"Invalid Card" error message trying to download 2.2.2 firmware in Companion 2.2.2

### ISSUE THREAD

**Issue by Chris-Cook-16** [opentx/opentx#6088]
When I'm trying to download the new firmware 2.2.2, opentx-9xr-heli-nofp-autoswitch-nowshh-novario-nogps-nogauges-fr-2.2.2, for Turnigy 9XR (basic one), Companion 2.2.2 displays a "Erreur: Carte non valide" (error: invalid card).
I know it's stated to stay in 2.0 or 2.1 branch for 9XR like radio due to a potential AVR issue; but I have used 2.2.0 and now I'm actually using 2.2.1 on my turnigy 9XR without any issue for flashing or flying.
I have migrated all my model configurations to 2.2 and don't want to downgrade to 2.1 or 2.0.
Could you please allows the download of 2.2.2 firmware for that radio.
Thanks a lot.

**Comment by kilrah** [comment]
No. Too many things broken, upgrading would likely actually cause all your model data to be corrupted. AVR support is now over and all related code is being purged out.

There is nothing you would gain from 2.2.2 over 2.2.1 anyway, you can continue to use that but remember to never use companion to edit models.
