### ISSUE TITLE
Taranis QX7s - VFAS Telemetry Appearing and Disappearing

### ISSUE THREAD

**Issue by cluc** [opentx/opentx#6091]
Currently my Taranis QX7s is on OpenTX 2.2.2.

The quad I'm using is a BetaFPV 75 Pro, which uses an all in one F4 Brushless Flight Controller and running the default factory firmware betaflight_matekf411rx_3.4.0.

When first connected (Taranis and the quad), I go to discover sensors on my Taranis and I can see a lot of different sensors, which is great. Now I'm only interested in RSSI and VFAS.

When I pull out the battery on the quad and replug the battery again, I can see that the RSSI reconnects, but the VFAS disappears or cannot be detected, even if I try to discover sensors.

However, when I turn off my Taranis and then turn it back on, both the RSSI and the VFAS gets connected again. (Similarly, if I switch to another model and switch back, it reconnects the telemetry)

At this point, it looks like a Taranis firmware issue.

To help narrow it down, I also have a Happymodel Snapper 7, this quad uses an all in one F3 Brushless Flight Controller, running Betaflight_3.4.0_Crazybee firmware.

When I perform the same steps, in call cases both RSSI and VFAS always show and connect.

So at this point I'm thinking it's either the F4 Flight Controller firmware needs to be fixed or the the Taranis firmware needs to be updated to support the F4 flight controller.

The worst case scenario is that the F4 flight controller or my Taranis is faulty.

**Comment by kilrah** [comment]
If you have another one working it shows there is no issue in OpenTX.  There is no "Taranis firmware needs to be updated to support the F4 flight controller", the smart port telemetry spec is an FrSky spec and other devices need to comply to it for it to work, we're not doing special cases.
