### ISSUE TITLE
Horus X12S None timers  can be started by throttle channel ...

### ISSUE THREAD

**Issue by ixopa** [opentx/opentx#6092]
Horus X12S - hardware X12SEU14 . Latest firmware "opentx-x12s-fr-2.2.2.bin" installed 2 days ago. 

Would like to start timer 1 count down when throttle stick is activated . 

Way used : 

MDL button, CONFIGURATION, Timer 1  set to GZ%     00:05:00    normal (name given)    PERSISTENT OFF   Minutes announcement  ON    Count Down    VOICE   5s 

Is this wrong ? Timer does'nt not start in any case.

**Comment by 3djc** [comment]
The functionnality works, so there is an issue with your setup (radio mode ? how you look at the time ?). Anyhow, this place is not for support, but used for tracking OpenTx bugs, which this one is not. Please go to support places like rcgroups or openrc forums for usage support.
