### ISSUE TITLE
Ubuntu PPA is stale and does not contain x-lite model.

### ISSUE THREAD

**Issue by njdro** [opentx/opentx#6093]
Using both Debian and Ubuntu, the provided packages do not contain the FrSky x-Lite model. (the packages themselves are 2017)

**Comment by 3djc** [comment]
Not sure where you are  downloading from but the .deb link on the official page is 2.2.2 : http://www.open-tx.org/2018/07/28/opentx-2.2.2

deb : https://downloads.open-tx.org/2.2/release/companion/linux/companion22_2.2.2_amd64.deb

The PPA need to be updated yes

**Comment by njdro** [comment]
**yes, the link to the PPA is definitely outdated:
https://launchpad.net/~opentx-test/+archive/ubuntu/rel/+packages
`2.2.1` is the latest listed with date `2017-12-17`**

and indeed the .deb is up-to-date, i suppose it did not replace the ppa version properly when i tried it the first time.

**Comment by OpenUAS** [comment]
PPA update would be really appreciated. Also to avoid having a new PPA for a new release.

**Comment by 3djc** [comment]
It will come, but we have only two maintaineers with access to it, and it is holliday period ....

**Comment by OpenUAS** [comment]
@3djc No sweat, already appreciate that there is a PPA :+1:

**Comment by benderl** [comment]
Any News about the PPA?

**Comment by WuerfelDev** [comment]
Would be nice if there's a notice if on the downloads page as long as this is not up-to-date :)

(And also how do i even run this? After installing -the old version- i wasn't able to run it by command)

**Comment by njdro** [comment]
@WuerfelDev ,
`companion22` is the executable name, from the `.deb`
