### ISSUE TITLE
Full release version Firmware OpenTx 2.2.2 not available, loads RC5 version

### ISSUE THREAD

**Issue by Roitellet** [opentx/opentx#6096]
The download of the full release version of the 2.2.2 Firmware is not possible:
https://www.open-tx.org/2018/07/28/opentx-2.2.2

The OpenTX Companion 2.2.2 - Windows Installer downloads the July 28th version of the Companion but when one downloads the corresponding Firmware, one receives the RC5 Version file:
opentx-x9d+-noheli-lua-de-2.2.2RC5.bin

Can you please check that the correct Firmware is linked to the full release Companion.
Thanks!

**Comment by 3djc** [comment]
Make sure your settings are set to use release only

**Comment by Roitellet** [comment]
Excellent! Thanks, that was the issue.

**Comment by Roitellet** [comment]
An observation:
After downloading the stable 2.2.2 Firmware, the Release notes in the Help Register start with the 2.1 (no 2.2.2):

Version 2.2.1 / 2017-12-16
Please see this page for details. 
Version 2.2.0 / 2017-05-30
