### ISSUE TITLE
Feature request: pls. make individual trims accessible by special functions and Lua

### ISSUE THREAD

**Issue by StefanKellerAC** [opentx/opentx#6098]
It would be fine to be able to set individual trims with the special functions and/or with Lua...

**Comment by 3djc** [comment]
Could you detail a bit what you have in mind (why, how, scenarios,...) ?

**Comment by StefanKellerAC** [comment]
- instant trim could be explicit for only one channel
- presets could be set by events or switches or ...

- we could use it more flexible as a control
- I tried to make a cruise control for a car:
    trim on the channel is disabled. 
    with trim +/- a global Var is modified. which controls gas in the respective mIxer
    when I touch the stick the cruise control is disabled by a logical switch
    until here it is fine, 
    but then trim should be set to zero, 
    otherwise I have to start next time at the last speed which may be to high
    or when I use the trim button to increment the global var I will stuck at the end of the trim range

**Comment by 3djc** [comment]
I'm not sure I'm following you. You need to disable the trim in the current flight mode, and set 2 special function to inc / dec the Gvar, and one to reset it on a switch

![image](https://user-images.githubusercontent.com/5167938/44000781-32cfc43a-9e26-11e8-8988-1d5ba18f00fa.png)

![image](https://user-images.githubusercontent.com/5167938/44000785-424cd5c4-9e26-11e8-8b1a-86fba394e07e.png)

I have used trim6 on Horus, but the very same is douable on any trim in any radio

**Comment by StefanKellerAC** [comment]
yes, but then you will end using this in one direction when maximum trim is reached ( I have a X7)
... ok, I tried it again. Yes it works but I am confused by the permanent announcement "maximum trim reached "
if you go up and down you may never reach that point

-> setting the trim to a value would be much more flexible and elegant :-)

**Comment by StefanKellerAC** [comment]
another advantage: using the trim value you could read/see it on the display on the main pages.

**Comment by 3djc** [comment]
There is not message about max or min trim reached if done as I said, (you probably did not set trim to '--' in your fight mode

**Comment by kilrah** [comment]
You can already see trim values on the main page.

**Comment by StefanKellerAC** [comment]
@3djc thx! setting it to -- in the flight mode(s) is the point
@kilrah not when they are disabled

so for my scenario it is ok as it is now (2.2.2)

But I guess it would be an improvement for other scenarios (eg single instant trim) and not difficult to implement, because instant trim for all channels is an already implemented mechanism and access with special functions would be straight forward to implement.

**Comment by kilrah** [comment]
There are not shown by default but you can display them on a telemetry screen.
