### ISSUE TITLE
X-Lite Switch Direction

### ISSUE THREAD

**Issue by macsleep** [opentx/opentx#6101]
I am using OpenTX 2.2.2 on an X-Lite. I have seen that Bertrand worked on the switch direction for the X-Lite in issue #5828. I still have to push e.g. switch A down (literally) to get a SA^ in OpenTX. Is this the correct behaviour or shouldn't this be the other way around?

**Comment by 3djc** [comment]
NO, it is right. There is a OpenTx rule that applies to all radio we do support, that come in all king of shapes and forms.
The closest to your head is **down**, the farthest **up**

**Comment by macsleep** [comment]
Thanks for explaining :-) . I can live with that rule (no issue). But to be honest I use the switches the other way around. For example I arm my quad using an OpenTx down on SC. It would be interesting to know how most people use the switches on an X-Lite in that respect...

**Comment by 3djc** [comment]
We understand it feels strange if you look at xlite only, given it's physical setup, but we also want to ensure it is consistent between radios (so you don't have one down on your x9d, while the same on xlite is up (or vice versa))
