### ISSUE TITLE
I am using Qt Creator and working with OTX 2.2 downloaded clean file But when attempting to compile firmware I get the following message.  boot.cpp.obj [ 8%] Building CXX object radio/src/targets/common/arm/stm32/bootloader/CMakeFiles/bootloader.dir/bin_files.cpp.obj [ 8%] Linking CXX executable bootloader.elf arm-none-eabi-g++: error: code: No such file or directory arm-none-eabi-g++: error: files/opentx-2.2/radio/src/targets/taranis/stm32_ramboot.ld: No such file or directory  Does anyone have any experience with this error?  What am I missing? 

### ISSUE THREAD

**Issue by racermark** [opentx/opentx#6105]
The issue tracker here is for devlopment of OpenTX. This is not a
support site, only a bug tracking system. Please use support groups
like [rcgroups](https://rcgroups.com/) or
[openrcforum](https://www.openrcforums.com/forum/). See also our
[manual](https://opentx.gitbooks.io/manual-for-opentx-2-2/).

For quick questions you can also join our general chat.

Issues that fall into the category of asking for help, will be
generally closed as invalid without an answer.

**Comment by 3djc** [comment]
As you state it yourself : ". This is not a support site, only a bug tracking system. Please use support groups like rcgroups or openrcforum.".

BTW your are obviously missing the right arm compiler in your path
