### ISSUE TITLE
Language "nl" is missing in radio menu. It is present in Companion

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6108]
Most Dutchmen are quite comfortable with devices in English, so that's the reason why this is such a late report.
Last week I created a Dutch soundpack which I today wanted to test on my radio.
After setting the language to "Dutch" (which is the English word for "Nederlands") in Companion and writing the setup to my X-Lite I noticed I was still having my English soundpack.
I thought there was something wrong with writing the radio-settings from Companion to the radio, so I checked my X-Lite. I then noticed that "Dutch" was omitted from the list.

I'm running 2.2.2N665 on both Companion as X-Lite.

In Companion English is used and in the radio the languages are represented in their own languages.

"German" in Companion appears as "Deutsch" on the radio.
That's probably why "Dutch" (Nederlands) is missing on the radio.

I propose "nl" as the name for the directory.

As a workaround I will rename the "nl" folder to "de" and select "German/Deutsch"

![companion_dutch](https://user-images.githubusercontent.com/39838998/44297362-59e6df00-a2d0-11e8-81de-fd7a6160c99e.PNG)
![xlite-no-dutch](https://user-images.githubusercontent.com/39838998/44297365-5f442980-a2d0-11e8-869a-1653da374ac8.PNG)

**Comment by 3djc** [comment]
The list on the radio is generated based on effectively available TTS  language, and visibly, no dutch person did volunteer to develop and maintain one, therefore it won't be available in the radio menu.

We probably need to review how to populate that list in companion

**Comment by notlebowski** [comment]
What is this?
I came back here to report that setting it to German is not a valid workaround as they have a different soundsat and I find that after hours of work this ticket has been closed before I can comment on it using more words to dismiss it than is needed for a change in the firmware. 

Apparently my efforts for improving the OpenTX experience is worth less than yours

My Dutch translation is however identical to the English one and the only thing that's needed is to add an option to the list and refer to nl instead of en.

This isn't the first time that hours of work in my side has been dismissed in 30 seconds

**Comment by kilrah** [comment]
@3djc explained to you that code needs to be written for the wording logic of the Dutch language, the reason there is no Dutch choice in the radio is that this is lacking. There used to be one but we were notified it was broken/not suitable.

When a Dutch programmer joins and writes it / maintains it it will be added...

**Comment by notlebowski** [comment]
The language for the voices and the menus are separate.
After I translated OpenTX to Dutch I continued to use English for the voices as for absence of a Dutch soundpack.
As I explained just now it is not like French or German that would need a lot of work, but exactly the same as English.

The only workaround I have left now is renaming "nl" to "en" in my soundpack and let those that want to use it overwrite their /SOUNDS/en/ folder.

It took many hours to create this soundpack because I don't want to use the sound engines that work with the TTS software for this.
I'm saying this as an explanation for my reaction.

**Comment by kilrah** [comment]
So what you're saying is that an exact copy of the en TTS logic could be used for nl? Then that's a possibility.

**Comment by notlebowski** [comment]
In other words... There is no difference in wording logic between English and Dutch and there never will be

**Comment by notlebowski** [comment]
Yes

**Comment by notlebowski** [comment]
Thanks for understanding my initial reaction (or at least partly).
I know that sometimes "silly tickets" are created that are promptly closed, but give at least some time to those tickets that are created with apparent thoroughness so the op can react before it's closed

**Comment by kilrah** [comment]
Just your usual problem of not being actually able to describe an issue - You never mentioned that EN logic was an appropriate replacement until after my commit, you only said you were using German and that wasn't good. 

Less whining and more thinking would be more efficient and avoid all that.

**Comment by 3djc** [comment]
Not acccording to this page that describes the differences:
https://en.wikibooks.org/wiki/Dutch/Vocabulary/The_numbers#1000_to_100,000
https://en.wikibooks.org/wiki/Dutch/Vocabulary/What_time_is_it%3F

Thats why you need a specific tts

**Comment by notlebowski** [comment]
Both are solved in the soundpack.
And no it's not "een duizend"
Please state your native language before further discussing this

**Comment by notlebowski** [comment]
And no the list doesn't go on.

**Comment by notlebowski** [comment]
Although I knew that my pack was exactly the same as the English one I used the German folder to preserve my English folder as workaround.

As I normally never use German as soundpack I wrongly assumed it used the same logic. The moment I started flying I was reminded.

**Comment by notlebowski** [comment]
What is your native language?

**Comment by kilrah** [comment]
Try next nightly and report back whether that works as intended.

**Comment by notlebowski** [comment]
I loaded the N666 and everything seems fine.
I have not flown with it like yesterday.
I have also played the settings back to Companion and settings there was "Dutch" as well.

Thank you very much Andre.

This ticket can be closed ;-)
