### ISSUE TITLE
Comapnion Store/Retreive does not save and restore Global Functions

### ISSUE THREAD

**Issue by rdeanchurch** [opentx/opentx#6109]
On Windows10, Companion 2.2.2 and OpenTX 2.2.2 for a X7

Open and existing .otx with calib, trainer, hardware and Global Functions
Click
'Store calib. and hardware settings in selected profile'

Under File, NEW create a new .otx
 in the  new .otx click 
'Restore  calib. and hardware settings in from selected profile'
Look at the Global Functions tab
Notice 'Restor..."' does not replicate Global Functions of the original.

Is this deliberate or and oversight?

**Screenshots**
![image](https://user-images.githubusercontent.com/4843199/44303140-f4095000-a2ed-11e8-96cf-9cc5b7fd64c9.png)

**Comment by kilrah** [comment]
Global functions have nothing to do with hardware, they are user configuration. 
Hardware = stick calibration, battery type and settings, stick mode, volume, what switches are installed, what mods are done... things that may vary between 2 radios of the same type.

**Comment by mpaperno** [comment]
Related: #4583
