### ISSUE TITLE
check list /notes not displayed on taranis x9e

### ISSUE THREAD

**Issue by utoedter** [opentx/opentx#6110]
Companion 2.2.2 on Windows 7 /  firmware 2.2.2 (a5de713b) 

Tried to display the checklist on my taranis x9e but after long pressing the wheel there are only the following menu items:

- reset timer and telemetry
- throttle statistics
- about

Menu entries are translated from german to english, they may differ from the english firmware.

But if i press the wheel button long in the X9E Simulator it shows a additional line "show notes", which displays the check list.

Bug priority minor

**Comment by 3djc** [comment]
Show notes choice appears only show if valid notes are found on SD
