### ISSUE TITLE
Frsky Horus X12S problem with influence from throttle to rudder

### ISSUE THREAD

**Issue by jszewczyk** [opentx/opentx#6111]
Hi. When I change position of throttle stick, level of rudder changed. What's the matter? When I have fros everything was okey. I don't have any mixer activated. I attached video. Could you help me?
[2018-08-19 12.53.43_1.zip](https://github.com/opentx/opentx/files/2300263/2018-08-19.12.53.43_1.zip)

**Comment by 3djc** [comment]
Sorry but this site is not for usage question, but to track OpenTX software bug. Please go to community support places like rcgroups or openrcforums
