### ISSUE TITLE
Feature request: add Virtual Ram

### ISSUE THREAD

**Issue by david-ng-hk** [opentx/opentx#6112]
some radio like, X9D plus, does not have a lot of RAM.
so some LUA script (like the betaflight vtx lua) can not run, always say something like OUT OF RAM

there is a SD Card Slot in the X9D, and some of the SD Card are very fast right now. like 100MB/S write
Is it possible add the virtual ram function to the OpenTX, so the lua script can use the SD CARD free space as a Virtual RAM.

BTW, is there a hardware mod that I can add RAM? (like change the RAM chip?)

**Comment by bsongis** [comment]
Latest X9D+ has twice RAM
