### ISSUE TITLE
Emergency mode (Notfallmodus) Horus X10S after normal flight (about 25 min)

### ISSUE THREAD

**Issue by Squirlier** [opentx/opentx#6113]
Open TX 2.2.2  (a5de713b) 2018-07-28
Horus X10S  LBT version
Non Eu option for D8 Mode possibility.
sd card is class10 16 gig intenso.

What happened:
After normal Flight with lots of speech sounds...
while still logging to sd card every 2 seconds...
Horus jumped in Emergencymode (or how it is called).
Receiver got wired and outputs started to shake a little... 
luck: landed already and motor didn´t selfstart while carrying plane. (good)

The weather was not too hot. 
I don´t know what happened.
Horus could be switched off and switched on. Emergency Mode was away.

If there are logs/files that can help i will provide them.

**Comment by alex-vg** [comment]
Sounds and logging? Looks like a new occurance of #3771

**Comment by 3djc** [comment]
It could be that, it could be a rogue LUA script, it could be ESD, could be a random hardware fault, the list is long and unfortunatly hard to narrow down

**Comment by Squirlier** [comment]
I have tested same logging every 0.2 Seconds 
but speech was disabled.
over 1 hour no problem. Test stoped without issue.
maybe it is when speech is activated by a switch > talking every x seconds.
Maybe the sd card is not good enough. now i am using a different one. (u1)
No problem since then. Maybe it was a very rare error.
I cant remember if there was a lua script running or not.
But if one did run it was Yaapu telemetry display as widget for ardupilot. that is the the one i use for this plane.
I am not sure that it was running on that day. maybe i´ve installed it later.

**Comment by kilrah** [comment]
As long as it is not repeatable and only occurring in rare occasions it's not a reason for concern. That's why emergency mode was developed in the first place.

**Comment by scott-adamson1975** [comment]
This has just happend to me while in flight, lost control in a roll, running lua inav telemetry script, will try to retrieve logs, if any

Happened while doing a roll, what could cause emergency mode? Is a receiver brownout a possibility?

**Comment by 3djc** [comment]
Hard too say, if we knew we would just prevent it. It has nothing to do with receiver, it's on the radio itself. Likely suspect are LUA stuff, but it could be other things too. Logs are useless in this case

**Comment by scott-adamson1975** [comment]
teh lua script may have just been about to warn me about low satelites and low voltage at teh same time, playing wavs
