### ISSUE TITLE
Outputs screen values, Horus X10S

### ISSUE THREAD

**Issue by keith-wd** [opentx/opentx#6114]
When I started using Version 2.2.2 a few weeks ago the values displayed on the Outputs screen were as a% now both the TX and Companion are showing values in microseconds except for the simulator which is still showing in %. Attached is an image showing the problem on Companion, if required I can also take a photo of the TX and send it.

![outputs problem](https://user-images.githubusercontent.com/42552685/44360545-0ed8f180-a4b3-11e8-9f0b-d35c00975a68.jpg)

**Comment by kilrah** [comment]
This is a bug tracking system, not a user support platform.

You have selected the "ppmus" firmware option.

**Comment by keith-wd** [comment]
Apologies.


________________________________
