### ISSUE TITLE
Taranis X9d+ no binding or no firmware updates possible

### ISSUE THREAD

**Issue by ashish1982** [opentx/opentx#6116]
I upgraded Taranis X9d+ from 2.1.6 to latest 2.2 3 days back from mac. All went well. Needed to install it twice to make it work. Upgraded bootloader as well successfully. Worked well for 1 day I flew couple of packs no problem. 
Didnt work on simulator so changed it to JOYSTICK under USB Mode. Post then it does not work with any of my models. Neither I can bind with Frsky receivers. Seems like no Signal from Taranis.
 I tried reflashing the firmware but it gives ERROR,, File is not valid. 
Any suggestions please!!!

**Comment by 3djc** [comment]
We are sorry but this tool is not for end user support, but for actual bug tracking. For support, please go to community places like rcforums or openrc forums. Alternatively, you could try our chat
