### ISSUE TITLE
Crossfire Telemetry - Missing remaining Bat % in sensor list

### ISSUE THREAD

**Issue by ZinhoRacing** [opentx/opentx#6120]
In INAV, the telemetry over crossfire send V, A, mAh and remaining % for the battery.

/*
0x08 Battery sensor
Payload:
uint16_t    Voltage ( mV * 100 )
uint16_t    Current ( mA * 100 )
uint24_t    Capacity ( mAh )
uint8_t     Battery remaining ( percent )
*/

In the CrossfireSensor list (crossfire.cpp file), there is only V, A and Capacity drawn.
{LINK_ID,        9, ZSTR_TX_SNR,      UNIT_DB,            0},
  {BATTERY_ID,     0, ZSTR_BATT,        UNIT_VOLTS,         1},
  {BATTERY_ID,     1, ZSTR_CURR,        UNIT_AMPS,          1},
  {BATTERY_ID,     2, ZSTR_CAPACITY,    UNIT_MAH,           0},
{GPS_ID, 0, ZSTR_GPS, UNIT_GPS_LATITUDE, 0},

Is it possible to add the remaining % of the battery in sensor list ?

I'm available to test (Horus X10s).
Thanks.

**Comment by CrazyDude1994** [comment]
Just found out the same issue. It would be great if this could be fixed
