### ISSUE TITLE
Horus x10 model wizard 2.2.2 dont work.

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#6121]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by ghost** [comment]
When you create a new model it just stay frozen on that page plus it dont show plane just the glider set up but wont go to the next step.

**Comment by 3djc** [comment]
Then you likely do not have thge right SD card content....

![image](https://user-images.githubusercontent.com/5167938/44533466-e1c85100-a6f5-11e8-8591-d86ef35856fe.png)

![image](https://user-images.githubusercontent.com/5167938/44533492-ed1b7c80-a6f5-11e8-8928-58c00e052142.png)

**Comment by ghost** [comment]
were do i get the right content? i just downloaded 2.2.2

**Comment by ghost** [comment]
it just the glider wizard but I just can get it to work

**Comment by 3djc** [comment]
Sorry but this is not a support site, please go to  community sites like rcforums or openrcforum for end user support
