### ISSUE TITLE
It is possible to change UI page while range check is ON

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#6123]
On all radios

**Comment by Allerhopp** [comment]
To be able to change page during range check was often useful for me, for example to watch the sensor screen in range check mode. It is more a feature than a bug, at least for me.

**Comment by kilrah** [comment]
What do you want to see on the sensor screen during range check that is useful to said range check?

**Comment by Allerhopp** [comment]
I am used to fly my rangetests/antennatests with a RTH quad and i watch distance, altitude, speed, heaading, RSSI, lost frames ....

**Comment by kilrah** [comment]
OK...
But then think of the normal plane pilot who has the radio muted or volume set a bit low and does not notice he is still in range check mode after exiting back to the main screen.

It was thought until now that it was not possible and EXIT was the only way out to the main menu and home screen, thereby disabling range check. But it turns out you can change page, and when there you can exit and get back to the main menu with no indication of being in range check. 

The reason for this is that it has happened and been reported.

**Comment by Allerhopp** [comment]
To be honest, i was surprised when i realised the first time it is possible at all. Safety first, i will work with the logfile in the future. lBtw. long page would also be helpful to be able to switch to telemetry screen/LUA telemetry screen, any chance to keep the long page function alive?

**Comment by kilrah** [comment]
Huh? Long page is how you get to the telemetry screen from the home page. In the menus it is "previous page". No change there.

**Comment by Allerhopp** [comment]
You are right of course, i had to press page, exit and long page.

**Comment by mpaperno** [comment]
Perhaps adding a special screen (with big "RANGE" title) and a non-editable telem. sensors list would be nice.

The little chirpy warning sound is easily missed.

**Comment by mpaperno** [comment]
Ooops, I was reading "range" and thinking "bind".  It is also possible to switch pages during bind though... not sure if that ends binding mode (the chirps stop), but seems like an oversight.

**Comment by kilrah** [comment]
Well that is much less of a problem since you can't fly while in binding mode...

**Comment by mpjf01** [comment]
I reckon the "no change" position should apply to bind mode as well. For consistency and because we have all been present when someone has launched a model without checking first that he had control.  You will never stop that happening of course but it would be better to reduce the possible excuses.

**Comment by kilrah** [comment]
If you had clicked on the linked PR you'd have seen the proposed change affects ALL edits.
