### ISSUE TITLE
R9M / R9Lite Flex Firmware support

### ISSUE THREAD

**Issue by fzilic** [opentx/opentx#6133]
Is there plan to support new Flex firmware for FrSky R9 system in upcoming OpenTX Release.

FrSky had released information about R9 Flex firmware, and released firmware for R9M/R9Lite modules as well for receivers in their recent news release https://www.frsky-rc.com/frsky-r9-series-new-products/

I have looked at commits, open tickets, but there is no mention for Flex firmware support anywhere.

FrSky is suggesting note that OpenTX 2.2.3 should support this feature, and I have even tried to contact them, but no hint of support for new firmware anywhere.

**Comment by kilrah** [comment]
#6118.
