### ISSUE TITLE
RBS and RBCS (sensors of RB20) not available for use in logical switches setup

### ISSUE THREAD

**Issue by franz4949** [opentx/opentx#6136]
Tx configuration:
Taranis X9e with OTx 2.2.2 (actual version) and FrSky RB20 with latest (not yet released to public) firmware.

The sensor search provides from RB20 among others RBS and RBCS with respective values. These sensors also can be setup to be shown on a telemetry page. I wished to use these sensors in logical switch setups for evaluation purpose, but none of both are offered there for selection.

RBS and RBCS should be made selectable same as also other sensors are.

**Comment by kilrah** [comment]
These "values" are bitfields and there is no way to test them in logical switches. 
You'll have to use a lua script to extract data from them. 

This might help: https://github.com/RealTadango/FrSky/tree/master/RBSMIX
