### ISSUE TITLE
Feature request: X-lite External Antenna startup warning

### ISSUE THREAD

**Issue by FearCapone** [opentx/opentx#6141]
At first, sorry for my bad english.

I own a xlite and there is a Detail that can be better:
If i Change from internal Antenna to External, the Transmitter friendly ask If i'm sure.
After reboot the xlite,there is no warning and the external Antenna output active if i choose this before powering off.
Is it possible to add here a warning Like "External Antenna active" and let the HF Modul deactivated until i press enter/Long press enter ?
I think that's a nice safety feature that prevent blown internal modules.
I'm not forgetful but we all know the bad day's, wrong prop direction, goggles at home etc.

Greets

**Comment by 3djc** [comment]
You can setup a checklist that will be displayed before module is turn on, that will display exactly what you want
