### ISSUE TITLE
Global variable pop-up issue with the Companion running Horus profile

### ISSUE THREAD

**Issue by Oldgibber** [opentx/opentx#6143]
It is not possible to enable the pop-up when programming global variables on the Horus transmitter itself. However, this feature is still enabled on the Companion. When enabled via the Companion it still does not work on the transmitter, so I presume this feature is not actually available for the Horus. Is it needed anyway?

If this is correct, then the pop-up option should be removed on the Companion when a Horus transmitter is selected.

**Comment by kilrah** [comment]
The feature makes no sense on Horus since you can use widgets to display them at any time.

**Comment by Oldgibber** [comment]
You've missed the point. If the pop-up option does not apply to the Horus, then it needs disabling in Companion.

**Comment by 3djc** [comment]
Which is what he just changed into companion, as referenced just above

**Comment by Oldgibber** [comment]
Sorry guys!

**Comment by StefanKellerAC** [comment]
in Companion 2.3.7 and X10 it is still selectable.
