### ISSUE TITLE
One German wav incorrect in SD content 0018

### ISSUE THREAD

**Issue by kreidler** [opentx/opentx#6152]
Sorry, but I am not able to rebuild the SD content. Therefore please correct 
in generated file "SOUNDS/SYSTEM/de-DE-taranis.csv" the line 180 from

SOUNDS/de/SYSTEM;sensorko.wav;Sensor veloren
to
SOUNDS/de/SYSTEM;sensorko.wav;Sensor verloren

Thanks

**Comment by 3djc** [comment]
The sdcard files has been regenerated with this change, you can find it with same number here : https://downloads.open-tx.org/2.2/nightlies/sdcard/

**Comment by kreidler** [comment]
@3djc :  Downloaded nightly sdcard content dated 2018-09-05. Issue still existing.

**Comment by 3djc** [comment]
Yes, I think I know why (it is fixed, but that fix did not reach the server generating the sounds when I regenerated those sounds. Will post here tomorrow when redone

**Comment by 3djc** [comment]
@kreidler , it should be ok now, sorry for this.

**Comment by kreidler** [comment]
@3djc : Thanks, it is ok now. Do not apologise that's software delevelopment
