### ISSUE TITLE
Setting Trainer Conditions

### ISSUE THREAD

**Issue by geekerator** [opentx/opentx#6156]
It does not seem to be possible to set:

Radio Setup > Trainer > Ail (or Ele, Thr, Rud) mode(s) to: OFF, :=, or += with a special function in 2.2.1 or 2.2.2

This is a problem for me when using a head tracker (with pan/tilt on channels 5/6) via the trainer port (which requires the "OFF" mode for each flight control) followed by using the trainer port for a buddy box (which normally requires the := mode for each flight control - channels 5/6 being unused).

It would be good if it were possible to set these modes with a special function (triggered by a switch movement), rather than having to enter the X9E's menu system and change each one of the 4 manually each time the role of the X9E changed.

**Comment by kilrah** [comment]
For your head tracker you should not be using the Trainer function at all. If it's on CH5 and 6 then you're using TR5 and TR6 in the mixer and not using the Trainer function.

**Comment by geekerator** [comment]
Thanks Kilrah, I am now on the correct road to managing my situation (without your guidance, I would be blundering around for days)...
