### ISSUE TITLE
POT for set HORUS(s) backlight, Please...

### ISSUE THREAD

**Issue by CcLaFleche** [opentx/opentx#6163]
With S2 Like as Volume with S1

**Comment by Amenotepia** [comment]
This would be great for Nirvana as well. :)

**Comment by Luznatural** [comment]
And also for the rest of the Horus community....
Is there any way to move this issue a little bit forward? This is the single issue for 2.4 already proposed.
It shouldn't be so difficult as already Frsky has shown us how to implement it in FrOs.
Thanks in advance

**Comment by CcLaFleche** [comment]
It's going well ?

**Comment by Luznatural** [comment]
Thanks for moving this issue up in priority.

**Comment by markran** [comment]
I would also like this.

**Comment by bsongis** [comment]
Still valid @bot
