### ISSUE TITLE
updating taranis firmware from 1.9 to 2.0 on MAC

### ISSUE THREAD

**Issue by drewster1965** [opentx/opentx#6164]
I have read all the info on openTX about flashing the taranis X9D from ver. 1.9 to ver. 2.2 and understand that I am now no longer able to do so independently and that a special file will have to be produced in order for me to be able to do that.
Please advise best way to go about this. Very frustrated that the download feature no longer works on companion 9!!!

**Comment by kilrah** [comment]
This place is for development matters, not user support. 

You can flash 2.0 to your taranis on mac, no issues. Make sure to install dfu-util which is linked at the bottom of the Downloads page.
