### ISSUE TITLE
Let model image widget also show name in small zones (like top bar)

### ISSUE THREAD

**Issue by offer-shmuely** [opentx/opentx#6165]
I like to request enhancement for the top bar on X10
I like to be able to choose “model name” (same as “model picture”) to be displayed

I know there is an option to put text, and write again the model name manually,
But I do copy models and change the name often for testing, and the name change is not reflected on the screen on that case

 

OpenTx 2.2.2 
X10s
Enhancement

**Comment by 3djc** [comment]
Someone (not necesseraly  us) need to write a tiny LUA widget (I would think it is less than 10 lines) to do that then (model.getInfo() returns the name)

**Comment by lshems** [comment]
Send a request at www.justfly.solutions and I'll make you this widget.

**Comment by offer-shmuely** [comment]
I feel that displaying the model name is basic feature for all.
Not just me.
Every other transmitter software present the (real model name) on the screen.

**Comment by kilrah** [comment]
It is also there by default, just not in the top bar.

**Comment by offer-shmuely** [comment]
Was it a technical problem to add it to the toolbar?

**Comment by kilrah** [comment]
No, just a choice. Full default widget displays both name and image, was decided the topbar size widget would show image only becasue the dimensions fit better. A long name would come in tiny characters in a single line in the top bar or overflow.

![screenshot_x12s_18-09-10_14-37-39](https://user-images.githubusercontent.com/6065069/45297949-4a416b80-b507-11e8-8073-9d2fafaa0b7a.png)

But anyway that's exactly why the Horus UI was made to be fully customizable, so that everyone can do whatever they want.

**Comment by offer-shmuely** [comment]
I believe that good approach should be:
Make the common things easy, and the hard things possible.

**Comment by kilrah** [comment]
Define common. You're the first to ask for that in 2+ years OpenTX for Horus has existed.

**Comment by mpaperno** [comment]
Here you go:
https://github.com/mpaperno/OTX-Lua/tree/master/WIDGETS

![screenshot_x12s_18-09-10_19-12-03](https://user-images.githubusercontent.com/1366615/45329250-707a0200-b52d-11e8-8222-d06f7881d2b1.png)

The model image widget can probably be modified to do the same thing (as an option)... But this one you can use now. In the screenshot, the image widget is first in the top bar, then the name widget. Text size/color is adjustable.

**Comment by offer-shmuely** [comment]
suggest to close this issue, and accept the pull request that add widget "ModelName"
see: https://github.com/opentx/opentx/pull/6411
