### ISSUE TITLE
Taranis x9d plus don't boot after upgrade to nightly build 2.2.3N677

### ISSUE THREAD

**Issue by fl0zan0** [opentx/opentx#6170]
taranis don't boot after upgrade to that firmware 2.2.3N677. 
I have to remove the battery and reflash with a old firmware.

**General information**
 - OpenTX version (e.g. 2.2.3N677 nightly)
 - Hardware (e.g. Frsky X9D+ )
 - OpenTX Companion (e.g. 2.2.3 osx nightly)

**Comment by 3djc** [comment]
Options ?

**Comment by fl0zan0** [comment]
lua, lua script, noheli, R9 flex

**Comment by kilrah** [comment]
Just downloaded and flashed `opentx-x9d+-noheli-lua-luac-flexr9m-en-2.2.3N677.bin`, no issues. So either you just had a glitch, or download failed/got corrupted.

**Comment by fl0zan0** [comment]
ok thanks
