### ISSUE TITLE
X9D+ Changing display backlight color via Switch (model) or KNOB (GVar)

### ISSUE THREAD

**Issue by mixMugz** [opentx/opentx#6171]
Hello. I wish to a new feature.
I want to set up in global vars (or in model) knob or switch for changing display color in X9D+.
We have two color by default blue and white. After small mod i have Red and Green color. I want option to change color via knob or different model different color.

If possible.

**Comment by Mattybperth** [comment]
hey what is the mod you did to change the colour is it easy please explain if possible

**Comment by kilrah** [comment]
Take the radio apart and replace the LEDs...
