### ISSUE TITLE
Simulator vs flexr9m flag

### ISSUE THREAD

**Issue by fape** [opentx/opentx#6175]
I create a x7s model with flexr9m flag check in companion-windows-2.2.3N678.
 ![flexr9m](https://i.imgur.com/rty5u3P.png)
And there is no flex options in simulator.
![simulator](https://i.imgur.com/vflGXkx.png)
Bot on companion everything looks good if I change flexr9m flag.
![with flex](https://i.imgur.com/9j6ZPAr.png)
![without flex](https://i.imgur.com/ceDW43d.png)
Is there any way I can test flex settings in simulator?

**Comment by 3djc** [comment]
No, simulator are built with standard options, not the one you choose in your download profile.
