### ISSUE TITLE
Hardware and Calibration tabs don't refresh after loading settings from profile

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#6178]
Before doing the following steps, a "calibration and hardware settings" must have been stored in the profile.

**Steps to reproduce the behavior**
1. Ctrl-N
2. Click on 'Edit Radio Settings'
3. Choose the 'Hardware' or 'Calibration' tab.
4. Click on 'Retrieve calib. and hw settings from profile'.

The radio settings tabs are **not** updated.
Closed the window and click again on 'Edit Radio Settings', the tabs are now up-to-date.

**General information**
 - OpenTX Companion 2.2.2 on Win10

**Comment by mpaperno** [comment]
This is somewhat a duplicate of (the rather old) #1705 (see last comment).  Also related: #4583.

Unfortunately this is yet another example of this feature being quite broken and unmaintained.  Personally I do not think it is worth fixing in its present form, and instead should be replaced with a different system as discussed (sort-of) in #4583.

**Comment by LapinFou** [comment]
Thanks for the explanations.
Sorry for the duplicate. 😞 😉 
Since, this is already known, I'm closing this ticket.
