### ISSUE TITLE
X-Lite sounds list bug 

### ISSUE THREAD

**Issue by FlyerFpv** [opentx/opentx#6182]
Hello everyone.

Just received my Xlite and when Im trying choose the music from list, the list just appear with bugs and invisible.
I can select the sounds with joystick but I cant see what Im selecting. 
Anyone with the same issue?
Best regards
![42186202_2341662095862287_2873966044584607744_o](https://user-images.githubusercontent.com/20193680/45849099-b2bef280-bd28-11e8-9f72-8dcdc437f963.jpg)

**Comment by kilrah** [comment]
Have you updated to latest OpenTX?

**Comment by FlyerFpv** [comment]
> 
> 
> Have you updated to latest OpenTX?

I have 2.2.2 218

**Comment by kilrah** [comment]
I mean have you updated to OUR latest distribution. We do not support what comes stock from FrSky since it never matches any of releases even when they show the same version number.

**Comment by FlyerFpv** [comment]
> 
> 
> I mean have you updated to OUR latest distribution. We do not support what comes stock from FrSky since it never matches any of releases even when they show the same version number.

Solved, already working.
The problem was the different time.
Now I have OpenTX 2.2.2 variant 218 with different time and its working!
Thanks
