### ISSUE TITLE
Problem loading openTX on the X12s horus

### ISSUE THREAD

**Issue by antgeebee** [opentx/opentx#6187]
This is the info i get when trying to load OpenTX on my Horus X12S:
Filter on vendor = 0x0483 product = 0xdf11
Opening DFU capable USB device... Cannot open device
please can you advise, many thanks
Antgeebee

**Comment by 3djc** [comment]
Sorry, but this place is only for tracking bugs. For support, please go to community places like rcgroups or openrcforum

**Comment by antgeebee** [comment]
appologies will do
