### ISSUE TITLE
Horus X10 crashes if LUA scripts draws text offscreen

### ISSUE THREAD

**Issue by azaz44** [opentx/opentx#6188]
**Describe the bug**
Using `lcd.drawText` in LUA will crash the radio if text goes off screen.
The radio crashes by going into *emergency mode*.

**To Reproduce**
Run the following one-time script:
```
local function init()
end

local function run(event)
  lcd.clear()
  lcd.drawText(50, LCD_H - 5, "Crashing for you", SMLSIZE)

  return 0
end

return { init=init, run=run }
```

**General information**
 - OpenTX version: opentx-x10-2.2.2
 - Horus X10s EU

**Comment by 3djc** [comment]
Yes, it is a known thing; Testing each pixel for offscreen is possible, but is the performance hit worth it ?

**Comment by azaz44** [comment]
Well, if anything, it should rather crash the script and not the whole radio. I believe it should not be possible to crash the radio with a script.

And as for drawing off screen:
- exceeding LCD_H is what I needed to have custom drawn screens with scrolling. You basically start drawing at the top, draw content until it exceeds the screen and allow user to scroll all of this. Something at the bottom goes off screen and is rendered partially. But I can imagine some workarounds (actually I have to it seems)
- exceeding LCD_W - I didn't check if this one crashes. But if it does, this is a bigger problem. Imagine you draw a model name on the screen somewhere (or any string not dependent on you). You have no idea how long is the text after drawing, there is no "measureText" function. So you always risk that text goes off screen. How do you prevent your script from crashing in this case?
