### ISSUE TITLE
It's not possible to include mps in prefligh checks

### ISSUE THREAD

**Issue by pmarkiewicz** [opentx/opentx#6189]
Taranis 9xd
If one of pots was replaced by mps preflight checks are incorrect.
1. Still show all pots
2. Don't let to set mps value in preflight checks.

**Comment by kilrah** [comment]
Should work even then when using the pot's settings.

**Comment by pmarkiewicz** [comment]
OK, let me check, but I don't want to stay on neutral value.

**Comment by 3djc** [comment]
Pot check does not only check for neutral value. It can check for last position or any specific position too

**Comment by pmarkiewicz** [comment]
OK, so this should be feature request.

**Comment by 3djc** [comment]
In what way ? It should work right know (assuring you know how to setup pot checks)
