### ISSUE TITLE
It's not possbile to replace LS/RS with MPS

### ISSUE THREAD

**Issue by pmarkiewicz** [opentx/opentx#6190]
Taranis 9xd
While it's possible to replace S1/S2 with MPS, it's not possible to replace LS/RS.

**Comment by MrLAtt** [comment]
I also planned to do this, instead had to do lots of wiring to wire the other 2 pots to the ls and rs inputs, and then the multipos switches to the inputs for the other 2 pots

**Comment by pmarkiewicz** [comment]
But looks like no one cares.
