### ISSUE TITLE
Companion not Detecting Taranis X9D+ with version 2.2.2

### ISSUE THREAD

**Issue by Luznatural** [opentx/opentx#6193]
**Describe the bug**
I flashed my Taranis X9D+ to firmware 2.2.2 with Companion 2.2.2. The radio worked fine, and the models were there. I tested several planes without problems.
Several days later, I tried to backup models from the radio. and found that Companion 2.2.2 does not detect Taranis X9D+. So, you cannot backup or load models, nor make backups of the whole radio.
I tried to backup my models from radio with Companion 2.2.1, but the radio is also not detected, so I assume the bug is on the firmware of the radio that somehow has interrupted the USB connection.

**To Reproduce**
To reproduce the behavior:
1. Start Taranis (OTX 2.2.2) with both trims to the center, as always. Computer (with Zadig driver installed) detects the radio in USB connections, as always.
2. Start Companion 2.2.2. Click on the icon to load models and settings from radio
3. Companion tells you that the radio is not detected

**Expected behavior**
To work as previous versions of firmware

**General information**
 - OpenTX version (2.2.2)
 - Hardware (Frsky X9D+ with OpenTX 2.2.2)
 - OpenTX Companion 2.2.2 (Windows 10)

**Comment by 3djc** [comment]
Given the number of 2.2.2 installs, we would know already if such an issue existed in either firmware or companion, but this is not the case. 

The error is most likely on your side,  please go to community support areas like rcgroups or openrcforum for end user support.

**Comment by Luznatural** [comment]
I have invested further. The issue could be related with the version on Zadig driver used. The computer with the problem had the newest version of it. I tried in a computer with the prior version and worked perfectly.
So I agree that the problem was in my side.
My apologies for raising the issue without investigating a little more..
Thank you @3djc

**Comment by 3djc** [comment]
Glad you found this issue, now you can enjoy your radio again

**Comment by kilrah** [comment]
It's not a zadig version thing, it's that you replaced driver wit the radio on in bootloader mode, when that must ONLY be done when powered off.
