### ISSUE TITLE
Model ID in use message in D8 mode

### ISSUE THREAD

**Issue by kreidler** [opentx/opentx#6194]
OTX 2.2.2 x9d+

Message "model id already in use" (sorry for bad translation using german version) appears after successful bind of a D8 receiver.

- Copy a model with D16 mode
- Switch mode to D8 and bind
- After bind messagebox with "model id already in use" appears but there is no possibility to change or remove the receiver number.
- Also reproducible after powercycle of TX and rebind.

**Comment by ParkerEde** [comment]
yes. it's the same OTX 2.2.2 Horus X10S

**Comment by Squirlier** [comment]
if i remember correct a workaround for this is:
select d16 mode. then a field called "id" od similar comes up which is not shown in d8.
simply change the id to next higer number and switch back to d8.
it would be easy if the id field is shown in d8 mode also.
i am not sure if this works. maybe you have to leave model after changing the id and before you change back to d8 mode. (for saving)

**Comment by kreidler** [comment]
The better workaround is ignoring because it works ;)
I do have around 25 models saved on this Tx mostly with D16 at the moment. So for me the "use a higher number" workaround would be practicable for a certain time only.
In any case the messeage is a minor "bug" which should be corrected.

**Comment by 3djc** [comment]
Done, will be in 2.3
