### ISSUE TITLE
X7 won't boot with 2.2.2

### ISSUE THREAD

**Issue by skorokithakis** [opentx/opentx#6206]
I flashed OpenTX 2.2.2 on my Q X7, it loaded fine, worked fine. I turned off the radio, tried to turn on again, the power button just flashes green and nothing happens. If I turn the radio on to the bootloader and then press "exit", the firmware loads and works fine. It just doesn't work when booting normally.

Downgrading back to 2.2.0 works fine.

**General information**
 - OpenTX version: 2.2.2
 - Hardware: Taranis Q X7
 - OpenTX Companion: 2.2.2 on Ubuntu 18.04

**Comment by 3djc** [comment]
Are you maintaining the power button pushed ?

**Comment by skorokithakis** [comment]
Sorry, I was not :( Is this new in 2.2.2, or did I just forget how the radio turns on?

**Comment by 3djc** [comment]
It is new, a feature that was added to prevent the radio turning on by itself during transport in a backpack for example

**Comment by skorokithakis** [comment]
Ah, so I'm not crazy, thank you. It would be nice if this were more advertised, as it's a pretty big change for a minor version...
