### ISSUE TITLE
No Trainer on X-lite

### ISSUE THREAD

**Issue by g19i85g** [opentx/opentx#6207]
I will use the SBus Trainer mode on the Taranis X-Lite but i can not find the menu on the model settings.
Tested with OpenTX 2.2.2.

**Comment by kilrah** [comment]
There is currently no trainer functionality on X-lite. We have work in progress for CPPM in but not SBUS (the hardware is capable though).

**Comment by noXi89** [comment]
There is a trainer function with the bluetooth module installed.
Close?

**Comment by g19i85g** [comment]
Can we make a feature request out of it?

**Comment by Protonus** [comment]
Anyone find a solution for this?  Looking to slave my X-Lite to DJI Occusync Air.  Just needs a trainer port.

**Comment by matthewthorp** [comment]
Trainer option in the model menu missing from opentx. I've recently bought a Bluetooth module to add to it as in this video.
https://www.youtube.com/watch?v=fyT6XohZIsY&t=478s

Gone through version history and seems to be showing last in v2.2.2

General information
 - OpenTX version 2.3.7
 - Hardware Frsky x-lite
 - OpenTX Companion 2.3.7 on windows

**Comment by DieHertz** [comment]
Was this somehow solved? I see X-lite has a 3.5mm input, but there's no Trainer setting in Model setup

**Comment by 3djc** [comment]
Xlite does have a 3.5mm headset out, no input

**Comment by DieHertz** [comment]
Bummer. Will try to DIY it by adding some wires manually then

**Comment by DieHertz** [comment]
So it turned out to be a quite simple mod, a matter of removing two capacitors and jumping two wires, as well as some PCBXLITE(S) amendments. Maybe I'll add speaker/trainer switch circuitry later on as well.

**Comment by kvng1** [comment]
> So it turned out to be a quite simple mod, a matter of removing two capacitors and jumping two wires, as well as some PCBXLITE(S) amendments. Maybe I'll add speaker/trainer switch circuitry later on as well.

Hello, was you able to get the trainer port working on x-lite? Can you please share some direction?

**Comment by DieHertz** [comment]
It required both hardware and software modification, I removed two capacitors which are used to drive left and right headphone channels, and added jumper wires from specific MCU pins to jack connector. This removes the possibility to use headphone plug for headphones unless you also add some switch circuitry, but I don't use headphones so I didn't bother.

I could share more details a bit later if that sounds like a mod you're willing to make.

**Comment by kvng1** [comment]
Yeah, that sounds doable, I also don't need headphone. Are you using the x-lite s firmware or have to build a custom?

**Comment by DieHertz** [comment]
A custom one, using Xlite S firmware would be cool but it requires more more, e.g. backlight control needs to be rerouted because FrSky swapped some pins around.
I'll share all changes necessary

**Comment by DieHertz** [comment]
![xlite-rev0 2-headphone-trainer-mod](https://user-images.githubusercontent.com/1427681/145718553-82a72ee2-211d-46a9-8ff9-0bbf8e9e192e.jpg)
Here's basically what I did, PD12&PD13 are both unused in original firmware, I shorted them just to make soldering easier, you only need one or potentially none, as jack plug event auto-detect does not work reliably with original wiring anyway.
Will share code tomorrow from my work laptop.

**Comment by kvng1** [comment]
Thank you, so pc13 for trainer input and pd12&13 for jack plus detection. Is there any unused pin on the female jack that I can jump the pc13? In this case, I need an adapter but headphone is still functional.

**Comment by DieHertz** [comment]
They hardwired the only potential jack pin to ground, so it's not possible without unsoldering connector and doing some heavy-duty modding I think

**Comment by DieHertz** [comment]
https://github.com/DieHertz/opentx/tree/hertz-xlite-trainer-jack-support-2.3

**Comment by kvng1** [comment]
Thank you for sharing it. I'm comfortable with hardware mod but building custom firmware hold me back a bit, look like you have to build a new one whenever a new version is introduced. I'm reading some build guide now but it'd take a while.

**Comment by DieHertz** [comment]
That's a necessary evil I'm afraid, I can build it for you if you want.
I personally update my radio firmware very rarely.

**Comment by Dragony** [comment]
@DieHertz I'm looking to support SBUS Trainer support on my X-Lite S. From what I can see in the code, I can use the same hardware mod you posted above. Can you confirm?

**Comment by DieHertz** [comment]
No idea, I don't have S, only original X-Lite

**Comment by jereitor** [comment]
> Eso es un mal necesario, me temo, puedo construirlo para ti si quieres. Personalmente, actualizo el firmware de mi radio muy raramente.

Could you build it for me? Thank you

**Comment by Maze1982** [comment]
@DieHertz I have tried but i just not have what it takes to build it for myself.
Could you help med also? 

/Maze

**Comment by DieHertz** [comment]
Hi, could you remind me what exactly we're taking about here? You did the mod and need a patched firmware?

**Comment by Maze1982** [comment]
Hello :-)

Thats correct, but i actually think i managed to fix it.

It seems that its working correctly.
I really appriciate you answering and the fix.

/Maze

Skickat från min iPhone

10 sep. 2023 kl. 11:04 skrev Andrey Mironov ***@***.***>:

﻿

Hi, could you remind me what exactly we're taking about here? You did the mod and need a patched firmware?

**Comment by DieHertz** [comment]
No problem, feel free to ask me if you need further help.

Sorry @jereitor I could not answer you, it's been a busy year

**Comment by ligteltelecom** [comment]
Hi i have frsky xlite (old version) and need add trainer port. Is this your mode is compatible with it? PC13 and PD12& 13

**Comment by DieHertz** [comment]
My X-lite was the latest pre-production version, I guess it should work, but I can't check anything as I no longer have access to any hardware

**Comment by ligteltelecom** [comment]
> My X-lite was the latest pre-production version, I guess it should work, but I can't check anything as I no longer have access to any hardware

Hello, which files do I need to download from your github? The hardware part, I have no doubts, is very clear to me. but I didn't find any information about what I should change in the software.

**Comment by DieHertz** [comment]
You have to manually build the firmware from the branch mentioned in this message:
https://github.com/opentx/opentx/issues/6207#issuecomment-993362949

**Comment by ligteltelecom** [comment]
> You have to manually build the firmware from the branch mentioned in this message: [#6207 (comment)](https://github.com/opentx/opentx/issues/6207#issuecomment-993362949)

Hello, do you have any instructions on how to build the firmware with your files?

**Comment by DieHertz** [comment]
> > You have to manually build the firmware from the branch mentioned in this message: [#6207 (comment)](https://github.com/opentx/opentx/issues/6207#issuecomment-993362949)
> 
> Hello, do you have any instructions on how to build the firmware with your files?

It's no different from building OpenTX in general, which is not that straightforward.
I would follow this commend and recommend the Docker way as it has fixed and isolated dependencies:
https://github.com/opentx/opentx/issues/8528#issuecomment-855251520
