### ISSUE TITLE
Add information about output power level for Frsky R9M module while in 1W dynamic mode.

### ISSUE THREAD

**Issue by ExaflopS** [opentx/opentx#6210]
*Before suggesting a new feature here, please search the open issue if there is already a request for the feature*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 3djc** [comment]
There is currently no information given back by the module on its status.

When module protocol get upgraded by FrSky, it will be implemented
