### ISSUE TITLE
XLite allow dpad to be used as momentary switches

### ISSUE THREAD

**Issue by rodgerramjet** [opentx/opentx#6214]
Wondering if this is possible- I’m a miniquad / fpv pilot and we have zero use for manual trim adjustment. 

Is it possible to make this a configurable option to give me 4 more buttons, if I don’t need the trims.

Each direction should be its own button/ channel.

I know you can do this with some special settings but that’s pretty clunky to do and doesn’t give all features we’d need

**Comment by kilrah** [comment]
They already are, trim keys is available in the list of switches, There are several tutorials around for this.

**Comment by expipiplus1** [comment]
@kilrah, would you be able to post a link to one of these tutorials, please?

**Comment by expipiplus1** [comment]
One way I've found to do this is to:

- Disable the trim in the flight mode(s) you will be using
- Create two special functions for `<trim symbol><trim number>u` and `<trim symbol><trim number>d` which override a channel to the desired values for trim up and trim down
- Be careful not to override any channel you are using elsewhere
