### ISSUE TITLE
X9D: selection Source not possible for calculated Telemetry Values (OTX 2.2.2)

### ISSUE THREAD

**Issue by r41065** [opentx/opentx#6215]
Building a new model on my Taranis X9D ( no Plus, OpenTX 2.2.2 ) 
i want to set new telemetry values for each cell of my FLVSS sensor:
- Discover new sensor: Cels is found.
- Then add new calculated sensor for each cell:
Selection menu for source shows only ---, not the discovered sensors..

As a workaround i set the source to single cell values in Companion and transfer it back to the transmitter but editing the source at X9D is not possible. ( even not for models which are converted from OTX 2.2.1 )

**Comment by kilrah** [comment]
Where are you trying to select that source? Have you given names to your calculated sensors?

**Comment by r41065** [comment]
Yes, done in same way as i've done it with Versions before directly on X9D 
( was working for about 42 models with FLVSS and MLVSS sensors, so i wonder why not...)


add new sensor
  give name ( Z1)
    select calculated
      try to select source: selection menu shows only ----
select Cell Value ( first, second, lowest ....) and check marks for logging etc. is possible again...

Selection this new calculated Value on telemetry screens is also possible ( but value is only blinking 0.00)

**Comment by 3djc** [comment]
Could you be more specific ? I'm trying to follow your sequence and I have the sources

![image](https://user-images.githubusercontent.com/5167938/46728128-69582800-cc82-11e8-88f4-271b193d2feb.png)

**Comment by r41065** [comment]
First picture: Working sensors edited from Companion:
![screenshot_x9d_18-10-10_11-50-26](https://user-images.githubusercontent.com/15220072/46728427-1fbc0d00-cc83-11e8-81a6-8a58be4ce3d0.png)

Trying to set 3rd Cell
![screenshot_x9d_18-10-10_11-51-47](https://user-images.githubusercontent.com/15220072/46728521-52fe9c00-cc83-11e8-8732-21d0121ac295.png)

Select Source  "Cels" ist not possible...  looks like it is only not possible to formula CELL, i didn't try the others before....

**Comment by kilrah** [comment]
Try to delete and rediscover your Cels sensor.

**Comment by r41065** [comment]
OK I Try when im home again ( maybe next Weekend...)
If it was to the converted Models i agree with you but this was a new designed Model and it was the first time i had discovered the FLVSS...
