### ISSUE TITLE
Graph in INPUT screen goes haywire when you change the source

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6218]
2.2.3N680

When an input is edited we get a graph that represents the curve.
If that input is one of several inputs and the edited one is not enabled (through switch or flight mode), I'm getting the graph of the active one.
I wouldn't expect that and maybe that's the bug already.
I would expect a graph of the input I'm editing at the moment. I can't remember seeing that before, but most of the time those graphs look similar in the same input.
I noticed it when I was editing the flight modes and then the graph suddenly changed because I deselected the FM I was currently in.

Maybe it is intended that one should see the graph of the active input and not the one that's being edited. I hope that's not the case.

But even if that's so there are still some bugs with the graph.
When I change, for instance, the source the graph then suddenly changes into something that's not meaningful. It is for certain not the graph of the active input, but it's also not the one I'm editing.

I have this example and SA is down:
```
Inputs
I1:Ail
    Ail Weight(+20%) Switch(SA↑)
    Ail Weight(+100%) Expo(50%)
```

![image](https://user-images.githubusercontent.com/39838998/46827634-67cd5380-cd99-11e8-8413-23ca8b789a3b.png)

![image](https://user-images.githubusercontent.com/39838998/46827865-08bc0e80-cd9a-11e8-92cb-4d1effcc8fdd.png)

**Comment by kilrah** [comment]
> Maybe it is intended that one should see the graph of the active input and not the one that's being edited. I hope that's not the case.

It is the case, it's how several other radios work so is something people are used to. Has the benefit of allowing to easily compare curves by flipping the switch too.

**Comment by notlebowski** [comment]
OK
But what about what happens if you change the source?

**Comment by kilrah** [comment]
Seems there's an issue with that indeed. And it must not be something people look at often because it's been there forever aka >4 years.

**Comment by notlebowski** [comment]
Normally I wouldn't go there, but I started fiddling with it to make sure it was indeed intended behaviour that the active graph was shown.

The intended behaviour is alright by me.
As long as you know, it's alright. I now know....  ;)

**Comment by hhjcz** [comment]
I myself found this feature of showing active curve very useful and had no problems with it when learning OpenTX for the first time. Though I understand it can be a little misleading for someone.

**Comment by notlebowski** [comment]
You may have been misled by the title of the ticket, but there was indeed something wrong with the graph of the input screen and I wouldn't have made this ticket if it was only its behaviour that it didn't represent the current input at hand.
I added that as I wanted to make sure it was intended behaviour. 
What happens after changing the source was not intended behavior.
