### ISSUE TITLE
X-Lite and R9M flex (power not adjustable)

### ISSUE THREAD

**Issue by skaman82** [opentx/opentx#6223]
I am not sure if this is a bug, but I've just installed the newest nightly available for my x-lite on the Companion and flashed my R9 mini module with the latest flex firmware from frsky. I can change the frequency but not the power output or s.port setting. The power output is always "(100mw)" 
How I can toggle between 25 and 100mw?
![img_20181017_173846_resized_20181017_054631384](https://user-images.githubusercontent.com/11768024/47098988-a8631c00-d234-11e8-9dfa-bb852fcd1d75.jpg)

**Comment by kilrah** [comment]
Power is not adjustable on the Lite module with Flex FW.
https://www.frsky-rc.com/frsky-r9-series-new-products/

**Comment by skaman82** [comment]
Ok, thanks @kilrah. But why it is (100mw) and not 100mw. Does it means something? How can I check if the flex firmware is actually working?

**Comment by 3djc** [comment]
( ) is actually to show it is information only, and not a value that can be changed. Since the module does not report its working status, you cannot have information from the radio (beside rssi)

**Comment by skaman82** [comment]
Then s.port ON value should be (ON) too, because it is also not changeble, right?

**Comment by 3djc** [comment]
Unlike RF power that cannot be changed, telemetry value can change depending on internal module status
