### ISSUE TITLE
FlexR9M build option missing from none FrSky ARM radios

### ISSUE THREAD

**Issue by th9xer** [opentx/opentx#6224]
If using nightly V2.2.3N682 the build option for FlexR9M is missing for all none FrSky ARM radios, Sky9X, AR9X 9XR-PRO, etc.

Guessing this is an oversight ?

**Comment by kilrah** [comment]
You mean the selection is missing in comnpanion? Yeah most likely.

**Comment by th9xer** [comment]
Yes exactly.
