### ISSUE TITLE
FrSky drivers not compatible with USB3.0

### ISSUE THREAD

**Issue by WynandRedelinghuys** [opentx/opentx#6225]
There seem to be a problem with the Companion2.2.2 device driver files. It initiates and runs without a problem with USB2. As soon as the Intel(R) USB 3.0 eXtensible Host Controller is loaded the drivers stops working. By Using the MicroSoft mass storage rather than the Taranis mass storage driver the drive is open up correctly. 

 FrSky_Taranis_Mass_Storage and Taranis Create Device Drivers initiates the USB3.0 port but does not show the Taranis QX7 radio or the SdCard as drives.

**Comment by kilrah** [comment]
There are no drivers that you're supposed to use for mass storage but the original microsoft ones.
The only way you'd have other drivers loaded is... when you use Zadig without following the instructions that say "power off only".

**Comment by WynandRedelinghuys** [comment]
Open-Tx 2.2.2 comes with its own device drivers for the Taranis x7 radio and is automatically installed when installing Companion2.2.

Is is easy enough to replace the - FrSky mass-storage  driver for the SDCard - with that of MicroSoft. 

The problem arises with the - FrSky driver for the radio's EEPROM. It doesn't have a problem with USB(2.0) but does not work with USB(3.0). 

It will be much appreciated if someone can help. I had a look at some of the other posts and it seems to be a regular topic. "No Radio Found." The USB driver (3.0) initiates as a device, but the radio's EEPROM is not available as a drive. No data can thus be copied to the directories in the radio's EEPROM and Companion2.2 does not see the radio.

There is no problem up and down loading the firmware using DFU-UTIL.

**Comment by schwabe** [comment]
It does not come with driver as @kilrah said. OpenTX on the device emulates a regular mass storage device.

**Comment by WynandRedelinghuys** [comment]
Now you have completely lost me. None of the drivers below was on my computer before I installed OpenTX

 ![open-tx](https://user-images.githubusercontent.com/43576924/47302499-f6579580-d621-11e8-8f6b-dd11e45688ba.JPG) 

Do you perhaps know who is the driver provider for libwdi with a generator code of USB\VID_0483&PID_5720 (libwdi autogenerated) is? 

![stm32bootloader](https://user-images.githubusercontent.com/43576924/47302093-eb503580-d620-11e8-94ed-8fc21bf17c64.JPG) ![frsky taranis mass storage](https://user-images.githubusercontent.com/43576924/47302129-fefb9c00-d620-11e8-9fd0-d7908b6947aa.JPG)

Your support will be highly appreciated. Companion2.2 will not allow me to simulate or upload the radio on the computer through USB(3.0) - "No Radio Found."

**Comment by kilrah** [comment]
As mentioned the libwdi drivers were likely installed by you using zadig incorrectly, no such thing is done automatically. With the radio on click uninstall device and check remove driver.

**Comment by WynandRedelinghuys** [comment]
Andre I am now completely lost. I have uninstalled and deleted all STM32 Bootloader and Frsky Taranis Mass storage devices and files from my computer. 

When the radio is switched off and I plug it into the USB port the STM32 Bootloader is loaded as a driver.

If the radio is switched on and I plug it into the USB port the options - USB Joystick (HID) and - USB Storage (SD) appear on the radio. By selecting the USB Joystick the Taranis radio appears as a FrSky joystick under the devices. By selecting USB Storage the FrSky Taranis mass storage driver is installed.

The installation of these drivers must be initiated from the Taranis radio. I did a search afterwards on the computer but could not find any of the drivers. I also was disconnected from the internet. There is no change in Companion. Still don't see the radio as a virtual drive and with  the -Taranis mass storage driver- installed the virtual SD card also disappeared. The radio needs a driver to communicate with the USB. Don't you think there is a bug in the USB Descriptor file file. It runs perfectly under USB(2.0) but crashes when using USB3.0

**Comment by kilrah** [comment]
Did you check the "remove driver" checkbox when uninstalling as requested? If you didn't then the wrong driver isn't removed, stays on your system and will be reused next time you plug.
Neither the radio nor OpenTX installs any driver on its own, and there is no specific issue with USB3 in general, I use 4 different machines with only USB3 ports daily with FrSky radios. 

Could be your specific USB3 controller though, some early ones are known to break in certain conditions, but regardless you having a libwdi driver for mass storage is wrong.

**Comment by WynandRedelinghuys** [comment]
![uninstall frsky taranis bootloader](https://user-images.githubusercontent.com/43576924/47335534-e1afe780-d68b-11e8-8a5c-78c8467d7f82.JPG)

Uninstalled and deleted all the Taranis device drivers. No access to the radio. Re-installed Companion. No access to the radio - cannot up/download firmware. Replaced libwdi (default installation) with USB mass storage - SDCard virtual drive is up and running.

Thank you for the help.
