### ISSUE TITLE
Reset Trim and knob settings with double click

### ISSUE THREAD

**Issue by Roitellet** [opentx/opentx#6228]
In Simulation in opentx:  it would be helpful to reset the trim sliders and rotating knobs to their zero center position with a double click of the left mouse button. Gas trim and rudder trim are sometimes used in an other function (e.g., gas to elevator mixing ratio, aileron differential). Setting the trim level to zero is easier with a double click than finding the zero position manually.
This would be applicable to the 4 trim sliders, the rotating knobs and the left and right sliders.

**Comment by mpaperno** [comment]
Already possible. Double-click with the _right_ mouse button to center them.  This info is also in the tooltips for each control.
