### ISSUE TITLE
Telemetry select in Redundancy mode

### ISSUE THREAD

**Issue by nox007** [opentx/opentx#6234]
Need to add Telemetry select in Redundancy mode. 
For example: i use as slave X8R and master R9mini, s.port getting from R9mini. Bind X8R without telemetry, and try to bind R9mini with telemetry. But it unavailable.
If i firs bind x8r without telemetry, turn off int module, than bind r9mini with telemetry. But when i turn on int module, in menu opposite s.port line for ex module i see a "Disable int".
I need to select myself, from whare i need a telemetry.
Thank you!

**Comment by 3djc** [comment]
I cannot be done currently since module have no commands to turn off telemetry out
