### ISSUE TITLE
Receiver number not working as intended?

### ISSUE THREAD

**Issue by skorzo** [opentx/opentx#6236]
Opentx 2.2.2 on Frsky Taranis X9D

Model 1 got receiver number 1 when setting it up

Model 2 got receiver number 2
Model 3 and 4 were copied from model 2 so they got receiver 2 too.

So:

Model 2 Receiver 2
Model 3 Receiver 2
Model 4 Receiver 2

But, apart from getting warnings or not the fact is that I have bound 3 different RX , one per slot, and all of them are working OK even when are sharing the same receiver number.

Model 2 receiver number 2 , RX1
Model 3 receiver number 2 , RX2
Model 4 receiver number 2 , RX3

Why is this working? I thought this is the behavior of model match on receiver number 0, sharing rxs in the same number, but don't know why I am sharing number 2 for  3 working rxs

**Comment by mpjf01** [comment]
When a new model is created it gets the model number as the receiver number as a default. It's just a convenience thing, OpenTx allows you to set any receiver number you like (within range) for any model number. It's up to the user to make sure that the receiver numbers used for any model matches whatever the user requirements are for that case. If you want the model number and receiver number to match for any (or all) your models, change the number and re-bind.

**Comment by skorzo** [comment]
So receiver numbers are model dependent?

I mean.. receiver number 2 is not the same for model 2, 3 4?   My 3 models and rx are working so the keys stored must be different, isn't it? But in that case, Why am I getting warnings about overwriting across models when binding?

**Comment by mpjf01** [comment]
As I wrote above, OpenTx allows you to set any receiver number you like for any model. 

The warning that a selected receiver number is already in use is purely advisory.

**Comment by kilrah** [comment]
If you want them different then change them after making a copy.

**Comment by 3djc** [comment]
If you set the receiver number the same in several models (it is YOUR choice), then all those radio models control those receivers. It is usefull for complex crafts for example, where you have a stable model you use to fly, and another radio model where you experiment things, both controling the same device.

If you want 1:1 match between radio models and craft, just choose appropriately your model ID, the warnings are here to help that (but ultimately, it is your choice)
