### ISSUE TITLE
X9+ 2.2.2 Cels voltage reading wrong

### ISSUE THREAD

**Issue by alberthorn** [opentx/opentx#6237]
I did setup a MLVSS sensor, it runs great but if I setup Play Value it doesn't say the 2 decimals, only sometimes one decimal, if so it is wrong value with about 0,5 volts offset.

**Comment by 3djc** [comment]
By design, audio uses only prec1, so one digit only

**Comment by alberthorn** [comment]
OK, but why the offset??

**Comment by 3djc** [comment]
You need to be providing more details about what you are seing

**Comment by alberthorn** [comment]
OK, so normally I read the correct voltage of the cells, let's say 12,41 Volts, but if I try to Play value it "says" 12,9 . Sometimes only 12....

**Comment by kilrah** [comment]
Then the sound set you have on your sd card is not the right one for the OpenTX version you're running on the radio.

**Comment by 3djc** [comment]
For 12.41v, Open Tx says 12.4 volts
