### ISSUE TITLE
XLite's Use of Internal + External Modules Prevents Telemetry

### ISSUE THREAD

**Issue by blauver** [opentx/opentx#6247]
Telemetry works fine until the internal module on the Xlite is powered on. It does not even need to be bound to the receiver for this to occur.

On the quad, an R9 mini (tele enabled) is the primary receiver and an R-XSR (tele disabled) is the secondary.

**Comment by 3djc** [comment]
Indeed but it is something imposed by frsky as the internal module telemetry cannot be disabled. If/when frsky changes that, we will happily update OpenTx accordingly

**Comment by blauver** [comment]
That's a bummer, but I appreciate the fast response!

**Comment by kilrah** [comment]
Same on all their radios.
