### ISSUE TITLE
Unable to create new models 

### ISSUE THREAD

**Issue by DonaldHillNZ** [opentx/opentx#6253]
The issue tracker here is for devlopment of OpenTX. This is not a
support site, only a bug tracking system. Please use support groups
like [rcgroups](https://rcgroups.com/) or
[openrcforum](https://www.openrcforums.com/forum/). See also our
[manual](https://opentx.gitbooks.io/manual-for-opentx-2-2/).

For quick questions you can also join our general chat.

Issues that fall into the category of asking for help, will be
generally closed as invalid without an answer.

**Comment by DonaldHillNZ** [comment]
Hi Its been a while since I tried to create a new model using the wizard and actually when I first received the 9Xr plus I didn't even have a screen for the creation of new models which seemed to resolve itself with a firmware upgrade however now I'm getting "Script syntax error plane.lua:537 unexpected symbol near char(136)

**Comment by kilrah** [comment]
As you just posted above by mistake this is not a help site. 

But make sure to have correct SD card contents for your firmware version.
