### ISSUE TITLE
Special Function Lua not starting OpenTX 2.2.2

### ISSUE THREAD

**Issue by TheSchey** [opentx/opentx#6254]
I wanted to start the BF LUA by using Special Functions. Therefor I copied it into the Functions Folder of the SD Card. The LUA is working if I execute it over the menu. By using a special function it will not start.

I'm using a Taranis X9D with the latest version of Open TX (2.2.2), SD-Card Contant (V0018) and BF LUA (V1.1.0) inclusing the LUAC setup on the radio.

It is probably rather a user issue than a software issue, however I do not get it solved.

**Comment by 3djc** [comment]
https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/function_scripts.html

Function scripts do not have access to LCD

Please this place is a bug tracking place, not en end user support forum. For usage question, please go to places like rcgroups or openrc forums
