### ISSUE TITLE
Allow to change module (FrSky R9) output power from a switch 

### ISSUE THREAD

**Issue by Nandox7** [opentx/opentx#6255]
Hi,

Adding a suggestion here so that in OpenTX it would be possible to adjust/change the RF Power from a module, in this case the R9 Series from FrSky using a a switch or combination ot swtiches.

This behavior is present in module such as the EzUHF from ImmersionRC where is possible to assign a channel or use the built-in switch in the module to transition between Low/High power modes.

The goal is t allow to use a lower power mode for normal flying and have a backup/failsafe option to change to a higher RF power mode if required. This is quite useful specially if you doing long range flights.

I have searched in github and overall the web and I don't see as an option at the moment so creating it 
here so see how viable it is.
At the moment from what I can see it is not possible to control any of the model/radio settings using a switch or input from the radio.

Thanks!

**Comment by kilrah** [comment]
R9M when set to its highest power will already automatically scale its output power as required.

**Comment by Nandox7** [comment]
Indeed. Still even if I'd force myself to believe i could trust it I'd rather be the one controlling it.
Also because I'd like to avoid it going up to 1W just because there was a drop in RSSI or I'm too far to get telemetry back.
