### ISSUE TITLE
Can't Download OpenTx 2.2.2

### ISSUE THREAD

**Issue by KJBB** [opentx/opentx#6258]
1 Dec 2018:
All roads lead to this Rome - http://www.open-tx.org/downloads.html
Nowhere can I find an active download link at this location, or when I select the OpenTx 2,2,2 link, or any link below this.
Temporary hiccup?

**Comment by 3djc** [comment]
What exactly is your issue ? It downloads fine here

**Comment by KJBB** [comment]
I see what I've done. I was searching for firmware for the transmitter, and have landed up with a download for Companion.
Apologies.
