### ISSUE TITLE
Model.getcurve() and model.setcurve() use different indexing on points

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#6259]
Model.getcurve() returns parameter y indexed from 0 up, the model.setcurve() wants them indexed from 1 up.

Please fix now or fix never. You can program around, but please not version dependant.

**Comment by schwabe** [comment]
@lshems index start at 1 in lua so setcurve is right. So fixing getcurve would be the right thing to do but getcurve has been there a lot longer.

**Comment by lshems** [comment]
Sorry, but almost everything is zero start indexed. So best to adapt new setcurve.

**Comment by notlebowski** [comment]
Or better even...
Make a new function model.curve
You would have the compatibility part solved and it is apparent that they can be used for getting and setting the curve.
When I created my first script [https://www.justfly.solutions/index.php/full-repository?view=product&layout=plugin&format=raw&field_id=69&id=28] I found out that the output of getCurve could not be used for setCurve   ?????

**Comment by lshems** [comment]
I suggested multiple times to get rid of the set and get. One function is enough.

Local C={}

Loop something
   C=model.curve(1,C)
   Modify C ....
End loop

Would simplify a lot of scripts where the modify would depend on some userinteraction.

**Comment by schwabe** [comment]
Nice idea but does not work well with the way lua is designed.

**Comment by lshems** [comment]
Please explain?

I created a library with exactly this way of using curve(), using the getcurve and setcurve, but for all unnecessary duplicate pairs with get and set.

Makes my code much easier to read and maintain.

So what within Lua doesn't work here?

**Comment by 3djc** [comment]
Great, so you have it working the way you like, no point in asking again and again to convert the world to your personal preference then. The initial point of the issue had however merits, but no easy solution since we probably do not want to break existing, working scripts

**Comment by lshems** [comment]
Just fix the stupid bug, or decide to leave it there forever now. It's you guys that keep breaking scripts.

I never asked, only suggested.

But hey, I'll work around again.

**Comment by 3djc** [comment]
We could change to model.setCurve(curve, params, startIndex), with startIndex been optional defaulting to 1 to allow earlier version compatibility and allow to set it  to 0 ?

**Comment by notlebowski** [comment]
It may have been just my "luck" that the first time I tried LUA I was immediately confronted with a 2 pair-function that was in fact not exactly paired.
Is it really the only function in the whole LUA-library that isn't properly paired???
I wouldn't know as it immediately put me off using LUA further.

The whole idea of objects is that you read and write them as objects.

I have no idea how that imbalance started, but I do know that an imbalance wouldn't have been created if it was 1 function that would be able to both set and get as it is then even more obvious that the 2 should stay balanced.

As you don't want to break compatibility a new function could be created. You could start with 1 that could do both get as set. It's not that lshems invented that.

**Comment by lshems** [comment]
Please FIX the BUG, instead of trying to keep compatibility for the BUG.

bad practice.

Or do nothing, just promise to never fix it.

**Comment by notlebowski** [comment]
Can this be reopened or at least a remark from a dev if something is done about it or not?
The indexing is not the only thing that's wrong with this pair.
They take/give completely different parameters.

**Comment by lshems** [comment]
I don't care anymore, seen the type of communication.

See https://www.rcgroups.com/forums/showthread.php?3176435-Bugs-in-openTX-lua-API-s

**Comment by schwabe** [comment]
@notlebowski lshem closed the bug. Also @lshems your attitude and now with public shaming makes dev like me less and less likely to care about your problem. 

setCurve was developed for using it in the setup wizard and there reading/store was not the goal, so I choose to use something that was a good fit for lua programming.

I think adding a getCurve_ex/getCurve_new or something similar or a API breaking change is a good thing to do. Unfortunately,  at the moment I have little time for OpenTX, so the best I can do is review a pull request if someone here proposes a change for the better.

@lshems maybe you can focus your energy into doing productive changes and makeing a pull request for this one instead using that energy for complaining.

**Comment by lshems** [comment]
You are playing the victim here.

I just posted a bug, with a suggestion on how to improve things, in the context of the bug.

Then you developers choose to post objections, that after inquiry and argumentation from my side, are never made substantial.

I don't want you to do anything, apart from being respectful.

I don't start a thread on my blog to put you on public shame. You are doing that yourselves constantly, no need for me.

I just open a thread to keep track of all the inconsistencies and bugs, for others not to loose precious time stumbling over them. I don't need any of them fixed, so when you start putting words in my mouth and clearly show you are not happy with my requests, well, I close them.

Do as you wish, but stop playing the victim. You're only a victim of your own behaviour.

**Comment by lshems** [comment]
Better open a new one perhaps? Because I do not want my request fulfilled anymore. It was a genuine mistake to post a bug, trying to point you at it before it becomes legacy.

I'll never do it again.

**Comment by schwabe** [comment]
@lshems please stop being destructive

**Comment by lshems** [comment]
Please log a new one. I don't want to be associated with any further things on your actions, or lack thereof.

I'll close again if I feel like it, just like you do on requests from others.
