### ISSUE TITLE
Allow R9 Telemetry While Using Internal RF Module For Redundancy

### ISSUE THREAD

**Issue by MrLAtt** [opentx/opentx#6261]
I'm trying to setup my r9 slim+ with an xm+ for redundancy, but when I enable the internal module for the xm+ I'm no longer able to receive telemetry from the r9 Slim+. (open tx 2.2.2 with latest eu (non-Flex) firmware

Can we instead have the option to decide weather we want telemetry from the internal module or the r9m module, or is there some reason why that can't work?

Its very frustrating since the xm+ does not have telemetry, and even if it did, the telemetry would not have enough range

**Comment by 3djc** [comment]
Thé is no option to turn off the internal module telemetry, and given the two share the same wire, it can only be one or the other

**Comment by MrLAtt** [comment]
From what I understand, cant we have both active through the same wire, just like you would with s-port on the receiver with multiple telemetry modules, as long as there is not too much info being sent at one time. Which, if using a non-telemetry capable receiver with the internal module there should be no problem?

**Comment by kilrah** [comment]
No, amount is irrelevant. Modules are bus masters and poll the bus every 12ms regardless of whether something responds or not. There simply can't be 2 of them.

**Comment by MrLAtt** [comment]
Would this same situation work if the s-port line of the internal module was phisically disconected, since it looks like quite a simple hardware hack to either just cut the trace to the pin on the xjt riser or route it through a switch, or would there be some other software problem stopping it. 

Because the only other solution to this I can think of for my situation (where I need frequency redundancy and telemetry from the 900mhz system) is to have a second transmitter connected to my x9d through the trainer port, and then use that as the transmitter for the 2.4ghz system.

Is there any other solution?

**Comment by 3djc** [comment]
There are upcomming changes that will further prevent concurent use of iXJT and R9M, so there is no point in going down that path

**Comment by kilrah** [comment]
It would work but you'll have to do the required code changes to remove the logic that prevents selection of normally incompatible combinations.

**Comment by kilrah** [comment]
To be clear this would work now with current gear. Probably won't be possible with future receiver models and module/radio firmware anymore, so if you do that you have to be aware that this setup won't be able to evolve.

**Comment by MrLAtt** [comment]
ok, thanks for the help
