### ISSUE TITLE
Taranis Qx7 cannot be BIND

### ISSUE THREAD

**Issue by Kwlim84** [opentx/opentx#6263]
Hi, i'm a new person here!

I was bought aTaranis QX7 two month ago, when i bought that time version is 2.2.0 but i accidently updated to version 2.2.2, end up i realize it cannot bind with my receiver! First i thought is my receiver got problem, at  the same time my friend also bought a set of Taranis, i use his backup firmware to flash back from version 2.2.2 to version 2.2.0, it's work, but still facing same issue which is cannot bind !  Anyone may help me on the above matter or sending me a clear video teaching me actually how to do it? Please advise..

Thank you!

**Comment by 3djc** [comment]
Sorry but this place is only to track bugs, not for training/basic support. Please got to places like RCGroups or openrcforum
