### ISSUE TITLE
Bind on powerup

### ISSUE THREAD

**Issue by BadRaven** [opentx/opentx#6264]
Test Setup - Horus X12S running Open TX with iRange Multi-Module in Serial.  Model - Eachine E011.

There may be other protocols that do similar but with BAYANG as per the E011 and the multi module it is required to power down and up again after a model battery change as this (at least) protocol randomly chooses a new model ID each time, so on re-power the model no longer matches the Tx.

Obviously power cycling the Tx on every brief battery use is not a good idea and time wasting! The E010 method of cycling Channel 12 does not work, nor any other channel I have tested.

I have found that if the "Bind on powerup" state is toggled over once, the model will re-bind instantly. It matters not if its toggled on to off or off to on. I'm therefore when using these models leaving the Tx on the Model screen and pressing the rotary knob once each time after a battery change.

I have not found a way to set this up via a switch. Can this be achieved please?

**Comment by 3djc** [comment]
I'm sorry, but this place is only for bug tracking. I usualy would recommend to go to rcgroups or openrcforum, but in our case, you probably need to a multiprotocol related forum
