### ISSUE TITLE
replace Orginal Frsky by Multiprotocol 

### ISSUE THREAD

**Issue by jonathan2018** [opentx/opentx#6265]
hi Deverloper 
I have problem with Orginal FRSKY  x9 , it short range and now i want to replace by Multiprotocol with Frsky protocol . 
I can not use  space on X9 for modul multiprotocol because i used it for R9M. 
i want to connect direct Multi to orginal Frsky to replace . It can compatible ? or any solution better ?

**Comment by kilrah** [comment]
No, multiprotocol is not supported on the internal port.

**Comment by jonathan2018** [comment]
> No, multiprotocol is not supported on the internal port.

even do not need telemetry. Internal port use PPM input ? 
i want to replace Frsky .So i need ainput PPM control and a Smarport ( if Internal supported )  .Do not need serial to choose protocol same EXtarnal Port Multiprotocol 
Internal port is a XJT  right ? Xjt support ppm and pxx input ? right ?

**Comment by kilrah** [comment]
Smart port is common to internal and external. 
We only send PXX to internal and nothing else (actually there can be PPM if you select the "internalppm" option. But multi serial is not available, there is no code written for it to be output by the internal module timer.

**Comment by jonathan2018** [comment]
Ohh. i do not see internalPPM in option Companion 2.2.2 ???
but 2.2.1 had interppm . Mean all version in future will remove internal PPM ?? 
Oh no, i can  not stay old version

**Comment by kilrah** [comment]
I have it here. Order is different.

**Comment by jonathan2018** [comment]
> I have it here. Order is different.

x9+ have but x7 have no ???
![image](https://user-images.githubusercontent.com/35451398/50055157-79f2b600-017d-11e9-8cf4-5cfeca7ef90d.png)
![image](https://user-images.githubusercontent.com/35451398/50055180-d524a880-017d-11e9-86fb-74602c4345dc.png)

**Comment by kilrah** [comment]
It's only for X9. X7 hardware is different.

**Comment by schwabe** [comment]
Multi on internal module is possible but so far, no one has made a modification to his/her hardware and coded and submitted changes. As long as this does not change, multi in internal module is not supported.

**Comment by jonathan2018** [comment]
> Multi on internal module is possible but so far, no one has made a modification to his/her hardware and coded and submitted changes. As long as this does not change, multi in internal module is not supported.

Even change PID  by modul Multiprotocol a long time nobody fix. maybe it not important with Opentx

**Comment by schwabe** [comment]
@jonathan2018 I am not even sure what PID by modul is...

**Comment by jonathan2018** [comment]
> @ jonathan2018 Tôi thậm chí không chắc chắn PID của modul là gì ...

sorry for my idiom .A issues from Github multiprotocol that you attended https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/136

**Comment by schwabe** [comment]
@jonathan2018 yeah but have you also read my analysis? This as also a HW problem. And the motivation to fix this for the OpenTX platform seem to be relatively low as most people will use the internal module for D16 protocol anyway. On the OpenTX side everything should be fine.

**Comment by jonathan2018** [comment]
> @jonathan2018 yeah but have you also read my analysis? This as also a HW problem. And the motivation to fix this for the OpenTX platform seem to be relatively low as most people will use the internal module for D16 protocol anyway. On the OpenTX side everything should be fine.

that is old story. i think everyone will like a multiprotocol now /
Pascan said problem from Opentx . and you said problem from hardware Multi but it worked with Er9xsky ???

**Comment by kilrah** [comment]
We don't know what you're talking about. Do you mean PID configuratiojn scripts?

**Comment by jonathan2018** [comment]
> We don't know what you're talking about. Do you mean PID configuratiojn scripts?

Kilah  
Sorry , instead create a new issue, i ask it in this topic . relate to multiprotocol PID configuratiojn scripts

**Comment by schwabe** [comment]
@jonathan2018 OpenTX does not implement the soft serial for uninverted serial. For inverted serial I am not aware of any new developments.

**Comment by jonathan2018** [comment]
@schwabe 
i create a new issues on your branch Multi.   If you have time , talk more there. thanks

**Comment by jack113113** [comment]
i saw a report Script display on Qx7 work here https://github.com/midelic/Ersky9x-Tx-bas-scripts/issues/1#issuecomment-464300436
but he used firmware from ersky9x
schwabe said problem from hardware smartport ????? 
ersky9x work and Opentx can not ?
