### ISSUE TITLE
Companion can't find sound files.

### ISSUE THREAD

**Issue by Smedly101** [opentx/opentx#6268]
Opentx Companion V 2.2.2
SDcard V X7-2.2V0018 with Amber sound pack
Windows 10
In X7 profile, on the special functions page with play track selected, no drop down list of sounds appears and cannot play sound with play arrow. "Unable to find or open sound file" error message appears. Sounds are normal in simulation mode and in X9D profile. Triple checked SDcard folder location and permissions, tried different locations and drives, also tried 2 other computers with fresh install, Windows and Linux...all the same result.
[FirmwareDebug_18-12-15_19-48-32.log](https://github.com/opentx/opentx/files/2683249/FirmwareDebug_18-12-15_19-48-32.log)

**Comment by 3djc** [comment]
I do not seem to be able to replacate (W10, x7 profile)

![image](https://user-images.githubusercontent.com/5167938/50051187-f352c000-010d-11e9-94de-2b7927fd3770.png)

**Comment by Smedly101** [comment]
Thanks for the response, the clip that you sent me prompted me to try a new document1.otx and this worked fine, the sounds were available. Previously I was working with an eprom.bin from the X7 transmitter and that still has the issue. I will try to reprogram my models into a fresh document1.otx hopefully that will work.

**Comment by Smedly101** [comment]
OK, problem solved, must have been a corrupted EPROM, just needed to transfer models to new document1.otx. Thanks for the help.
