### ISSUE TITLE
"One" can only be chosen in "Special Functions". It's not available in "Logical Switches"

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6274]
I can choose for "One" in Special functions, but not in logical switches.
Now it can only be used directly there. In switches you can add a duration and combine it with another switch.
It can tell the setup the model has just been selected for the first time.
A workaround could be using a non persisten Timer based on ON and test for that, but that would waste a timer.

**Comment by kilrah** [comment]
Make any "always true" combination e.g. OR SA- !SA- and give it a duration.

**Comment by notlebowski** [comment]
Thanks for the tip.
Not as elegant, but will do.
