### ISSUE TITLE
possibility of inserting pwm values instead of curving for multi-position keys

### ISSUE THREAD

**Issue by manotroll** [opentx/opentx#6275]
there is possibility of instead making a curve to try to hit the values allow fixed numbers
such as when using the 6-way switch for flight modes in px4 the program does not allow changing the values

http://ardupilot.org/copter/docs/common-rc-transmitter-flight-mode-configuration.html
or there is a way to do it and I do not know how to do it

**Comment by 3djc** [comment]
Whats wrong with curve ? You can do a LUA that setup your curve the way you want it at model creation

You can also use mix lines, overides, plenty of ways

**Comment by lshems** [comment]
I'll make you a script to set it up in one click. Check my profile on rcgroups and pm.

**Comment by manotroll** [comment]
> 
> 
> Whats wrong with curve ? You can do a LUA that setup your curve the way you want it at model creation
> 
> You can also use mix lines, overides, plenty of ways

But how do I do this?
because by editing the points in the curve comes an hour that one point changes the other
could you give me links that show you how to use the available methods

**Comment by kilrah** [comment]
Don't use a curve, use mixer lines with the proper values on the desired channel. 

-100% MAX Switch(6P1)
-80%   MAX Switch(6P2) 

etc...

**Comment by 3djc** [comment]
Closing this, as this is a training issue rather then an opentx bug

**Comment by manotroll** [comment]
> 
> 
> Don't use a curve, use mixer lines with the proper values on the desired channel.
> 
> -100% MAX Switch(6P1)
> -80% MAX Switch(6P2)
> 
> etc...

How do I do this?

**Comment by kilrah** [comment]
![screenshot_xlite_18-12-24_16-16-43](https://user-images.githubusercontent.com/6065069/50402493-68219c00-0797-11e9-99e1-84e16395df9f.png)
etc...

![screenshot_xlite_18-12-24_16-17-14](https://user-images.githubusercontent.com/6065069/50402497-6a83f600-0797-11e9-94e5-0ecd4fd96dda.png)

**Comment by manotroll** [comment]
but I'd like to use a single key
because I am using the mod of the rotary switch of 6 possibilities
Could you show me some video showing

**Comment by kilrah** [comment]
S11, S12. S13 etc are the positions of the rotary switch.

**Comment by manotroll** [comment]
I do not understand
I can not figure out how to get this result
