### ISSUE TITLE
special functions S3 key not detected taranis 9 plus

### ISSUE THREAD

**Issue by manotroll** [opentx/opentx#6276]
the S3 key is not detected when turning in the special functions menu and does not appear in the list
Is it possible to make her appear on this list?

**Comment by kilrah** [comment]
You must enable it in the hardware settings.

This place is a development tracker, not a user support platform. Please use forums for usage questions.

**Comment by manotroll** [comment]
but this enabled
https://www.youtube.com/watch?v=yVZbGX0lHTM&feature=youtu.be

**Comment by kilrah** [comment]
Recalibrated after enabling?

**Comment by manotroll** [comment]
https://www.youtube.com/watch?v=EqG6Rs58JFk&feature=youtu.be
yes same result

**Comment by kilrah** [comment]
Really wonder what the S35,S34 etc at 10 seconds could be...

**Comment by manotroll** [comment]
are the keys on the radio
in Companion appears normally but did not know that to leave in bootloader mode did not load via USB is now loading
