### ISSUE TITLE
Date and time resets when shutting off X9D ver 2.2.2

### ISSUE THREAD

**Issue by Bernroth** [opentx/opentx#6277]
After setting date and time to correct values in the RADIO SETUP page, date and time resets to 1970-01-01 resp. 00:00:00 after the radio was shut down. As long as the radio is on they remain correct.

**General information**
 - OpenTX version 2.2.2 (a5de713b)
 - Hardware Frsky X9D
 - OpenTX Companion 2.2.2 on Win7-64

**Comment by 3djc** [comment]
This likely meams the rtc battery is either empty or defective (ie hardware defect, not opentx issue)
