### ISSUE TITLE
New release schedule?

### ISSUE THREAD

**Issue by Sm1thson** [opentx/opentx#6279]
Is there a schedule for when the next release might be? I fully appreciate that you guys are working on this for nothing and its no easy task (Im an electronics hardware dev and work along side other embedded devs etc).

I, like many others, am using the R9 system. I am in EU which is more problematic as the EU firmware has more issues than the FCC, the answer from FrSky is to move to their Flex Firmware. However, the Flex firmware needs open TX 2.2.3, many people are running the nightly and it looks like I may have to take this route.

My suggestion would be to make a release of 2.2.3 to suit those on the R9 system, and then release a version with all the other 'bells and whistles' later

(and yes I feel FrSky should be working to help develop open TX to make this happen and am disappointed they are not)

**Comment by 3djc** [comment]
While we understand the question, this bug tracker is not the place for this.

We where hopping to be able to release much much faster, and that could not happen. We realise it is not great, but we are trying our best to handle ressources constrains and upcoming changes. That said, we do not commit to release dates
