### ISSUE TITLE
OpenTX 2.2.2 download problem

### ISSUE THREAD

**Issue by Cattlebaron** [opentx/opentx#6281]
I can not download OpenTX 2.2.2, when I click on the link I am taken back to the opening page. I can download the sdcard-taranis-x9-2.2V0018.zip

**Comment by 3djc** [comment]
You do not mention what platfrom, but it seems ok from here.

**Comment by Cattlebaron** [comment]
Thank you for the reply. I use an Apple Mac running the lates operating
system. When i click on the download link it return me to the opening
screen. See the two attachments.

**Comment by kilrah** [comment]
You cannot post attachments by mail, need to use the web interface.

We don't know whether you're trying to download companion or firmware, what radio and options if the former, what link you're using if companion...

Still looks all fine here.

**Comment by Cattlebaron** [comment]
Thanks again,

I am trying to download the firmware version 2.2.2  I have openTXCompanion
2.2 loaded on my computer and have been using for the best part of the last
6 months.I have a Taranis X9D which I have owned for about the last 4
years; the serial number X9D003895C01 may give you a guide of it age. the
download link I am using is https://www.open-tx.org/downloads (I have
attempted the download a number of times for the last 4 days)

Thanks

**Comment by kilrah** [comment]
Firmware is downloaded from within companion, not from the website.

**Comment by Cattlebaron** [comment]
Thanks Andre,

I will now have to find out how to do this as previously I would download
the file from the web and then with openTX flash the firmware using the
file I had on my mac, but I will learn and succeed.

Cheers

**Comment by kilrah** [comment]
We have never distributed firmware files on the website, so you're probably confusing with something else....
