### ISSUE TITLE
Horus timer widget:display only timer name if defined.

### ISSUE THREAD

**Issue by Oldgibber** [opentx/opentx#6284]
See closed issue #5684 
This bug was corrected for the transmitter software and the Companion simulator but not for the stand-alone simulator. 
![image](https://user-images.githubusercontent.com/9936596/50610242-247f0e80-0eca-11e9-8988-c764e7f48648.png)

**Comment by kilrah** [comment]
The same code is used everywhere, there is no fixing one but not the other. You must not be using the correct version.

**Comment by Oldgibber** [comment]
You are right, as always. I needed to update the sim. However, could you add a **Help** or **About** tab to the stand-alone sim to enable one to check the version number, or perhaps add this to the bottom of the Help menu. The only way I could find out was to download again.

**Comment by kilrah** [comment]
Navigate to the version screen in the simulated radio. Standalone simulator is installed together with companion so should always be the same version unelss you do weird stuff with multiple installs...
