### ISSUE TITLE
Download Failed 

### ISSUE THREAD

**Issue by smokeintheeye** [opentx/opentx#6292]
hi can someone help me please. i need to update my qx7 but openTX keeps giving me a server error?
![annotation 2019-01-09 142335](https://user-images.githubusercontent.com/13908744/50905393-a3200280-141a-11e9-8af3-7d29abc78b92.jpg)

**Comment by 3djc** [comment]
Beside the fact that you could be running 2.2.3 instead of a similar nightly, there was an issue with nightly downloads that has just been fixed. Could you try again ?

**Comment by kilrah** [comment]
You are using and trying to download a nightly. You probably don't want that but the stable release instead.

**Comment by smokeintheeye** [comment]
worked thanks. was using nightly for the R9M didnt know the nightly was 2.2.4 and full was now 2.2.3. all working now tho thanks

**Comment by smokeintheeye** [comment]
> You are using and trying to download a nightly. You probably don't want that but the stable release instead.

Dose stable release now have support for the flex drivers for the R9M?

**Comment by 3djc** [comment]
Maybe reading the release notes would answer that question, and possibly others : 
https://www.open-tx.org/2019/01/06/opentx-2.2.3
