### ISSUE TITLE
Make it possible to multiply with a constant in the telemetry's calculated field

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6293]
When measuring the voltage of the battery pack with A2 I'm using a trick to get the average cell voltage.
I copy the A2-line which gives me the full voltage and use that copy with a different ratio.

When giving voltage warnings, I prefer to hear typical LiPo values like 3.7V instead of 11.5V which I have to divide in my head while flying.
That's working.

I can't however use this trick with the VFAS-sensor and the FrESC32_80A
I then thought I could use a calculated field and use a multiply by 0.25 (for a 4S), but I then found out I can only multiply 2 sensor values. No gvars or constants.

It would be nice if it could do that so I can get average cell voltage with those sensors as well.

It will then also make it possible to create a setup with a voltage warning that detects if I'm using a 4S or a 3S battery and always give the proper average voltage.
A GVAR would make that more elegant.

A2 is renamed to 3S
Cell is the same sensor with a different ratio
![image](https://user-images.githubusercontent.com/39838998/50945144-b28f6200-1493-11e9-8037-83fff7cce9f8.png)

Here I can't use the "ratio trick" and hoped to use a calculated field with multiply to reach similar results.
![image](https://user-images.githubusercontent.com/39838998/50945054-444a9f80-1493-11e9-9d31-d1e07796735f.png)

**Comment by ahmad-kassem** [comment]
notlebowski Did you find a solution for this?

**Comment by Woita2095** [comment]
I would like to re-open it, such feature would be very useful.
Thanks!
