### ISSUE TITLE
if (type(gpsLatLon) == "table") always returns TRUE with OTX 2.2.2

### ISSUE THREAD

**Issue by BalsaBasher** [opentx/opentx#6294]
On OTX 2.1.9 the following LUA code (taken from OpenTx LUA reference guide) returns FALSE until the GPS sensor is ready, but on OTX 2.2.2 it returns TRUE with zero values in the table until the GPS sensor is ready. Is this intentional or a bug ?

local function background()
  gpsLatLon = getValue(gpsId)
  if (type(gpsLatLon) == "table") then
    gpsValue = rnd(gpsLatLon["lat"],4) .. ", " .. rnd(gpsLatLon["lon"],4)
  else
    gpsValue = "not currently available"
  end
end

The build is opentx-x9e-shutdownconfirm-eu-noheli-lua-luac-sqt5font-en

**Comment by 3djc** [comment]
As per 2.2 LUA  documentation on getValue ;

value current source value (number). Zero is returned for:
non-existing sources
for all telemetry source when the telemetry stream is not received

**Comment by BalsaBasher** [comment]
If that is the way it is going to be in 2.2.2 then so be it, but it is a change form the way it worked in 2.1.9 and the new behaviour does not match the example LUA code in the 2.2.2 LUA guide.

**Comment by 3djc** [comment]
Help is more than welcome, feel free to PR better/more up to date exemples to the doc !
