### ISSUE TITLE
Extract: Error writing to file companion.exe

### ISSUE THREAD

**Issue by m-lotze** [opentx/opentx#6298]
I tried to install the update to 2.2.3 (also tried 2.2.2) and i am getting this error during the setup process on windows 10:

```
Extract: Error writing to file companion.exe
```

Uninstalled the previous version 2.2.1 from my pc and still getting this error. `C:\..\OpenTx\Companion2.2` has a 0 byte `companion.exe` when i cancel the setup process.

Can anybody help with this?

**Comment by 3djc** [comment]
Sorry but this place is not for support, but only a bug tracker. For support, please go to community forums like rcgroup or openrcforum
