### ISSUE TITLE
Synchronize SD Options

### ISSUE THREAD

**Issue by amantegazzi** [opentx/opentx#6299]
Make "Local Folder" option radio profile dependant.

Use Case:
1. I have two different radios (X9D+ and X7, e.g.)
2. I start companion and synch data from the computer to radio SD folder using X9D+ profile.
3. I change profile to X7
4. The value in the Local Folder field still points to the X9D+ folder on my computer instead of the X7.

Tested on Companion 2.2.3.

**Comment by kilrah** [comment]
Already the case, make sure to set it right, you probably made a profile copy.
