### ISSUE TITLE
Telemetry units for Gas Suite

### ISSUE THREAD

**Issue by pstasek** [opentx/opentx#6303]
I appreciate the correct detection of Gas Suite sensors in the 2.2.3 version, but it would also be great if we're able to choose the right units for the flow sensor, the "ml/min" instead of ml. It's just a cosmetic issue, but still...

**Comment by 3djc** [comment]
This unit does not currently exist and requires and eeprom change. It will not be available before 2.3

**Comment by pstasek** [comment]
Fair enough, not a big issue anyway. Thanks for the comment ;-)

**Comment by 3djc** [comment]
We agree so much that there is a comment about it in the code :) https://github.com/opentx/opentx/blob/2.2/radio/src/telemetry/frsky_sport.cpp#L77

**Comment by 3djc** [comment]
Done, will be in 2.3
