### ISSUE TITLE
Fail to boot 2.2.3 on x-Lite

### ISSUE THREAD

**Issue by njdro** [opentx/opentx#6304]
**Describe the bug**
Power-On (Boot) fail after using companion 2.2.3 to install latest firmware (2.2.3) to FrSky X-Lite.  It would just "click" speaker sounds, but would not show the 4 boot squares.

**To Reproduce**
Use companion 2.2.3 to update x-Lite

**Expected behavior**
Normal operation

**Screenshots**
n/a

**General information**
 - OpenTX version: 2.2.3
 - Hardware: FrSky x-Lite
 - OpenTX Companion: 2.2.3 64 bit .deb on Ubuntu

Repaired by downloading and applying the FrSky version from https://www.frsky-rc.com/taranis-x-lite/

**Comment by 3djc** [comment]
It is rather unlikely, but just in case, please give the exact options you used

**Comment by kilrah** [comment]
What version were you on before? Are you holding power long enough? What method used for upgrading? Updating while in bootloader in mass storage mode can fail on linux.

**Comment by SchonRichtig** [comment]
I`ve used Windows 10 to update to 2.2.3 without any problems on my X-Lite

**Comment by njdro** [comment]
@3djc resultant file:`opentx-xlite-noheli-lua-luac-en.bin`, 2.2.3 (ae5ac05b) variant 218 2019-01-07 10:27:23 OFF with hardware compat check

@kilrah prior was `opentx-xlite-noheli-luac-en.bin` 2.2.2 (a5de713b) variant 218 2018-07-31 13:45:40 OFF -- i see it did not have basic `lua`.  i will try again. during the weekend.

**Comment by 3djc** [comment]
Somebody reported an issue on mint (an Ubuntu variant) when they activated check hardware compatibility. Could you try unchecking it ?

**Comment by njdro** [comment]
i tried without "check hardware compatibility" and it **_worked_**.  did not do extensive testing.

**Comment by 3djc** [comment]
Ok, so we have an issue with recent Ubuntu. Will try to have a look

**Comment by 3djc** [comment]
@mpaperno if you are arround, could you get in touch, this one could use your skills :)

**Comment by bsongis** [comment]
Please reopen an issue if the problem is still there in 2.3
