### ISSUE TITLE
No Flex implementation in 9XR Pro 2.2.3

### ISSUE THREAD

**Issue by L4ky** [opentx/opentx#6305]
Hi, 
i just flashed my 9XR Pro with 2.2.3.
I selected the option "Flex" then i downloaded firmware.
Firmware name contains "r9mflex".
I flash successfully the firmware.

When i edit my model to apply Flex options i can't see flex option, instead i see old official values.
Options are "FCC" and "EU" instead of "900 MHz" or "868 MHz".
For example, EU 200mW has only "TELEM OFF".

I tried to create a new model, no success.

EDIT: Sha-1 hash calculated in "stock" and "flexr9m" option enabled are the same.

**Comment by kilrah** [comment]
Try to redownload firmware now?

**Comment by L4ky** [comment]
I tried multiple times applying "battgraph" too.
No success.

**Comment by kilrah** [comment]
If I tell you to do so it's because I changed something...

**Comment by L4ky** [comment]
Sorry, i missed "now".

I tried now, redownloading firmware and still no success.
Options enable: battgraph, flexr9m

**Comment by kilrah** [comment]
Argh stupid me, retry now...

**Comment by L4ky** [comment]
Great, it works! SHA-1 changed, flashed and i see 868 and 915 MHz with their binding options.
Thank you so much!

**Comment by PhlJns99** [comment]
Is this in the nightly builds for 2.2.3? If I select "flex" as an option before downloading, the latest version I get is 2.2.2RC5?

**Comment by L4ky** [comment]
No, this issue was in official release 2.2.3.
Try that instead of Release Candidates

**Comment by 3djc** [comment]
For 9xr pro (and only this one) you need 2.2.4 nightly

**Comment by kilrah** [comment]
No, no need, 2.2.3 release is OK. 

You just need to set companion to use releases and not RCs.
