### ISSUE TITLE
Add gps radar on X12S like as frOs

### ISSUE THREAD

**Issue by CcLaFleche** [opentx/opentx#6306]
Very usefull when the quad is very far and plugged.

**Comment by 3djc** [comment]
I believe all the pieces required to make one in lua have been there for some time, no sure if someone did make one or not

**Comment by CcLaFleche** [comment]
please....

**Comment by kilrah** [comment]
Yes, someone did make one already.

**Comment by CcLaFleche** [comment]
Where? i Don't find...
Or it's just for display GPS coordinates. I have already this with telemetry.
But more like this, a map  :
![IMG_20190327_184640](https://user-images.githubusercontent.com/41867802/55100149-75656400-50c1-11e9-9d39-2739112ef2af.jpg)

**Comment by Luznatural** [comment]
I continue interested on this feature

**Comment by lshems** [comment]
PM me on www.justfly.solutions or rcgroups.

Busy with a waypoint flying app, radar should not be difficult to add.

see also https://www.youtube.com/watch?v=ldkvXOGcMv4

**Comment by Luznatural** [comment]
I continue interested in this

**Comment by kilrah** [comment]
https://github.com/yaapu/HorusMappingWidget
