### ISSUE TITLE
Q X7 Firmware update problem when "check compatibility hardware" is on

### ISSUE THREAD

**Issue by mipel85** [opentx/opentx#6310]
Hello,

I have done several times the update of my X7 in version 2.2.3 to test the options of compilation (tests performed under linux Mint 19.1). I'm using a X7 profile and everything happens normally unless I check the check box "Check Hardware Compatibility" before starting the transfer. In this case, the screen displays random pixels or the radio turns on and off continuously. This looks like issue #4821 which describes the same anomaly. The only solution is to disconnect the battery and restart the flashing without checking the box. Why keep this option that seems to generate a major malfunction?
Michel
![hardware_compatibility](https://user-images.githubusercontent.com/18450008/51607213-5eb15e00-1f14-11e9-9952-f2300f0a1fb6.png)

**Comment by kilrah** [comment]
Could be something causing issues when 2 operations are done through dfu-util in a row? Might want to try older dfu-util versions.

**Comment by 3djc** [comment]
Clearly not happening here under debian, I'll install a Mint workstation to see if I can reproduce
