### ISSUE TITLE
opentx v2.2.4N960 (21f63383) on a qx7s.. asking for sd contents 2.2 v0020??

### ISSUE THREAD

**Issue by tnap1979** [opentx/opentx#6313]
cannot locate the v0020 SD card contents.. ANYWHERE..
so the simple solution to stop my radio from nagging me everytime i turn it on??
plug radio into usb, go into the main SD card folder...
open this file in notepad " opentx.sdcard.version " and change the v00xx to v0020 and it nags me no more 👯‍♂️ so i hope the REAL proper contents come soon, so we dont have to do this bypass to stop the nag screen....
OR give us an option to turn off the sd card contents nagging like we can with the switches and such...
also the ability to turn off the nightly warning as well would just be a bonus...
cuz really all i wanna do is turn my radio on and fly... not have to bypass and click past a bunch of screens to get to my radio and use my craft

**Comment by kilrah** [comment]
We'll fix the automated pack generation, seems it broke.
But why are you using a nightly build in the first place? That's for testing and not for flight use.

**Comment by tnap1979** [comment]
not trying to be mean or rude or anything, but isnt that the purpose of nightlies is to be tested ??
well.. i test them, if they continue to operate how i expect i keep using them, i like to be on the edge of updates... thats not a problem is it???
if so then maybe they should not be made to be available to the general public then
also the options to turn off the warnings for people like me/us who like to tinker and test the newest of the new... would be nice... but not critical, just trying to help is all.... :(

**Comment by kilrah** [comment]
No it's your choice, but so is ours to warn about that not being recommended.
If you want to be so deeply involved in testing then you might want to join the dev chat, set up a build environment, and then you can build your own firmware with the parameters you like including removing the nightly warning.

Anyway if you looked at the commit log you'd see the reason for the version change is about Italian sounds which you likely don't care about, so just editing the version file solves your issue.
