### ISSUE TITLE
OPen TX 2.2.3 Compilation error

### ISSUE THREAD

**Issue by cbeith** [opentx/opentx#6314]
Hi there,

I am trying to upgrade my Taranis X9D to latest Firmware. On open in the Companion 2.2 I get an error as follows 
![image](https://user-images.githubusercontent.com/4945133/51886720-b8b29780-23dc-11e9-88d4-cfdd8ca58726.png)
on selecting yes that I do want to download it I get the following message

![image](https://user-images.githubusercontent.com/4945133/51886879-44c4bf00-23dd-11e9-8db5-fe2f949e6f8f.png)
My current taranis Bootloader is 2.0.8

Any help would be greatly appreciated

Regards
Chris

**Comment by 3djc** [comment]
You have not setup your radio profile in companion
