### ISSUE TITLE
Firmware upgrade Fails

### ISSUE THREAD

**Issue by cbeith** [opentx/opentx#6316]
Hi there am trying to upgrade to the latest firmware have not done this for about 18 Months. On start of Open TX  asks me if I want to download firmware completes successfully but on trying to install get the following message 
![image](https://user-images.githubusercontent.com/4945133/51951619-0aacf900-2481-11e9-84d0-6bf57b0cce1e.png)

Not sure where I am going wrong any help would be appreciated.

Regards
Chris

**Comment by kilrah** [comment]
This place is for development matters and not for user questions, please use forums for support.

Check you really have the right FWfor your radio, and if you do disable "check hardware compatibility". You need that if you come from FrSky firmware.

**Comment by bschatz-zebra** [comment]
Sorry to bother you, but since I have experiencing the same issue trying to upgrade my X9D (not plus) from 2.2.2 (a5de713b) to 2.2.3, what forum would you recommend?

**Comment by cbeith** [comment]
Hi there , 

 

Solution to my issue was to setup the Radio profile in companion. The OpenTX forums have always been helpful.

 

Regards

Chris
