### ISSUE TITLE
increase maximum number of mixers

### ISSUE THREAD

**Issue by Tiefflieger68** [opentx/opentx#6318]
Please increase maximum number of mixers. At the moment it is possible to create max 64 mixers.
In some configurations at multi function models I ran against the limit of maximum mixers.
The Horus Radios should have the ressources to handle more mixers. Hopefully the it will work with the Taranis Radios too.

**Comment by kilrah** [comment]
Are you using Inputs correctly? A lot of stuff is typically made there and frees mixer lines.

**Comment by Tiefflieger68** [comment]
of cause in some cases one input could replace one mixer. But the inputs are limited too. At the moment I use this option as workaround. My idea is that the new radios should have the ressouces to handle more mixes.

**Comment by Tiefflieger68** [comment]
I own a DIY switch module. Each module has 8 switched outputs, by using only one channel, connected via SBUS. But I need one mixer for each output. Thats the reason why I ran to the limits

**Comment by Tiefflieger68** [comment]
one more reason why more mixers is a MUST:
there is an announcement of AndreaHuang in RC-Groups:
https://www.rcgroups.com/forums/showpost.php?p=41065931&postcount=9

> _Together with the new functions that I mentioned above,....., it will support more channels,....._

and more channels cause a need for more mixers

**Comment by kilrah** [comment]
Given that both we and the radios we support already allow for 32 channels and almost nobody uses that many it is not really an argument.
