### ISSUE TITLE
(minus)GV's with x.x precision returns 10 times bigger value in mixer

### ISSUE THREAD

**Issue by prikrylm** [opentx/opentx#6320]
(OpenTX 2.2.3)
Example:
add mixer to CH1 as MAX and weight of -GV1, where GV1 has set x.x precision and value 10 and (for example) conditioned by SA^.
By swiching SA to ^ channel value becomes -100% (not -10%)
(The same example with +GV1 works fine.)

Bug can be found in Companion simulator X9D+, Horus, and bug is on real X9D+ too.

**Comment by prikrylm** [comment]
Example:
add mixer to CH1 as MAX and weight of **-GV1**, where GV1 has set **x.x** precision and value 10 and (for example) conditioned by SA^. 
By swiching SA to ^ channel value becomes -100% (not -10%)
(The same example with +GV1 works fine.)

Bug can be found in Companion simulator X9D+, Horus, and bug is on real X9D+ too.

**Comment by prikrylm** [comment]
Oh, sorry for first comment. I left orig text there...

**Comment by raphaelcoeffic** [comment]
@prikrylm @elecpower since this issue seems to have been fixed #6321, I guess this issue should be closed, right?

**Comment by prikrylm** [comment]
I think yes..
