### ISSUE TITLE
TBS Crossfire Luascript problem

### ISSUE THREAD

**Issue by haukasa** [opentx/opentx#6322]
Hi. I am the happy owner of a TBS Crossfire Full TX module, and a Crossfire Nano Rx. My radio is the Taranis X9D+ with the latest OpenTx 2.2.2 firmware, and the latest luascript installed on the sdcard. 
My problem is that the luascript page in my radio don't show any digital values, and also says no telemetry. TX and Rx are off course binded. Telemetry is enabled, and the receiver test in the BetaFlight Configurator is working. l have discovered the sensors in the telemetry page, and l also have the vbat value on my radio screen. 
I have of course updated the TX module with the latest firmware, and updated the receiver over the air. 
[However Im able to run the luascript and tune pids and rates and vtx when l am using a quad with a FrsKy layout]
Is the answer that l do have to use the latest Nano receiver wish has telemetry?

**Comment by 3djc** [comment]
Sorry, but this is a bug report system, not for support issues. Please go to forums like rcgroups or openrcforums for support.

As far as we understand it, the scripts have been confirmed working several times here.
