### ISSUE TITLE
X Lite allow shift button as mix input

### ISSUE THREAD

**Issue by gutland** [opentx/opentx#6325]
**Is your feature request related to a problem? Please describe.**
There are no momentary switches on Taranis X-Lite. I would like to use the shift button as trigger for a readout of a timer. 

**Describe the solution you'd like**
Add the state of the shift button as mix input or lua export (readable by getValue())

**Describe alternatives you've considered**
If a telemetry script could read the keyEvent in the background-function, a workaround lua script with the functionality could be written.

**Comment by kilrah** [comment]
It's already available to Lua. 
It's not going to be made a source for obvious reasons of it being required for certain UI operations.
