### ISSUE TITLE
Curves - 3 char limit

### ISSUE THREAD

**Issue by jj-uk** [opentx/opentx#6327]
Can we please have more characters for curve names? 3 is just not enough in a helicopter setup to remember what the curves are used for.

5 was ok, really wish this wasn't changed to 3.

**Comment by urkadurka** [comment]
Hello, I agree with the request, names like Thr Norm, Pit Norm, Pit Hold are clear, today on helicopter I need to use TNr PNr PHl that are less readable.

**Comment by jj-uk** [comment]
stale-bot bump.

**Comment by Eldenroot** [comment]
Why it was changed to 3?

**Comment by notlebowski** [comment]
Memory..
Other features like the 64 logical switches (was 32) take extra memory that has to carefully sourced from other places. I'm not a dev, but I appreciate how they are able to extend it each time, but they are at the limit.

I'm surprised this ticket wasn't manually closed at the time

**Comment by jj-uk** [comment]
Can you please not close my issue. The limit of 3 chars is a problem for heli pilots.

Who really needs 64 logical switches?

**Comment by kilrah** [comment]
>Who really needs 64 logical switches?

Well, who needs more than 3 chars? ;)

Makes no sense to keep it open on its own, nothing will change until the whole storage is overhauled and everything will be reconsidered at that point.
