### ISSUE TITLE
Mix Outputs in Radio Outputs of Simulator do not follow Direction selected in Outputs

### ISSUE THREAD

**Issue by sande005** [opentx/opentx#6333]
Companion 2.2.3, Jan 7, 2019  X9D+

Open new file.
Create new basic model by double clicking on first slot.
Go to Mixes, duplicate Ail channel on Ch 5.
Select Simulator, select View, Radio Outputs, Mix Outputs.
Verify that both Ail channels move in the same direction as would be expected.
Close view and simulator
Go to Outputs tab, under direction for Ch 5, select "INV".
Go back to Simulator, Mix Outputs and note that bars still move in the same direction for both channels.
Note that the Channels Monitor of the Radio view does correctly show the opposite movement for the respective channels.

**Comment by kilrah** [comment]
That's perfectly normal, Mix outputs is just that, taken BEFORE anything on the outputs page is applied. Then this creates Channel outputs.
