### ISSUE TITLE
Channel outputs do not show correctly for a mix

### ISSUE THREAD

**Issue by packocrayons** [opentx/opentx#6337]
**Describe the bug**
A mix can be set up in the mixer using a combination of two switches that are additive for a 5 position setup (-100, -50, 0, 0, 50, 100). It shows moving correctly in the mixer, and moves a servo correctly, however in the channel output screen (pressing page from the main screen) it does not show correctly

**To Reproduce**
Create two inputs from two switches, say SB (3-pos) and SF(2-pos).
SB travel = 50, offset = -50 (so it goes -100, -50, 0 on its own).
SF travel = 50, offset = 0
Create a mix that has SB + SF, in the mixer screen with SF ^, SB gives -100, -50, 0, SF down gives 0,50,100. In the channel screen (pressing page off the main screen), flipping SF ^ locks the channel to -100 and moving SB does not change the display.
Connect a servo and observe the channel moving correctly.

**Expected behavior**
Channel should be changing from -100, -50, 0 with SF up.

**General information**
- 2.2.4, fresh off of git last week
- Taranis X9D
- Flashed from bootloader (loaded onto SD card)

**Comment by 3djc** [comment]
Please post your otx file and a photo of what you are looking at
