### ISSUE TITLE
Start one-time LUA script on startup/after reset flight for better preflight checklist

### ISSUE THREAD

**Issue by prikrylm** [opentx/opentx#6339]
Similar functionality as "display checklist", but run one-time LUA script.
User could create own preflight checklist with some interactions, images :)..., there could be some warnings based on persistent timers (i.e. check motor bearings, lube, etc...) and so on.

**Comment by notlebowski** [comment]
Wouldn't a run script SF do based on the trigger "one"?

**Comment by prikrylm** [comment]
Special functions can start "function scripts" which has not access to screen (non visual). So, trigger "one" is not the solution.

**Comment by kilrah** [comment]
No, function scripts do not have LCD access.

**Comment by lshems** [comment]
Make an autorun telemetry startup routine.

If there is an Auto.lua defined in the first telemetry screen as Lua script, after exiting the notes, switch to telemetry screen one and execute it.

This solves sope other requests as well.

**Comment by prikrylm** [comment]
If I had to switch to telemetry screen, I could run one-time script as well. And switching back to main screen is needed too.

**Comment by scott-adamson1975** [comment]
external antenna would be enabled by this point i believe, main requirement of "checklist" for me is to remind me to connect external antenna, would be even better if i could script it to disable for this session if i choose an option.

or the an option for the firmware to always prompt "are you sure you want to  enable external antenna?" if external antenna is enabled for the model (on change and switch on) and based on the response activate or deactivate for this session.

effectively add a mode to treat the external antenna option like a "90% of the time i will have it connected, but when at home setting up and making adjustments i probably wont" without having to deactivate it in model settings.

even a build flag like "i have early onset Alzheimers and will surely forget to connect my antenna"

**Comment by 3djc** [comment]
There is not such thing like disactivate for a session. If your radio where to go emergency mode, you would be back to external which you don't have, here goes a dead craft. It surely sounds like a great idea, much less so when you dig into the details

**Comment by scott-adamson1975** [comment]
question regarding emergency mode, and possibly needs explaining in wiki/documentation

when emergency mode activates is there a brief period of time without control while the system shifts to emergency mode?

**Comment by kilrah** [comment]
Emergency mode is what the radio gets in after it has crashed/rebooted unexpectedly. So obviously it implies it was non-functional for a short while.

**Comment by kilrah** [comment]
#5156 takes care of this
