### ISSUE TITLE
Companion model edit special functions changing function Adjust GV# mode not reset

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#6342]
Changing the adjusted GV# which had a mode other than Value leaves the old mode unchanged but the parameter is a value. eg Adjust GV1 mode Source param SC after modifying to Adjust GV2 mode Source param 0 which is an invalid combination.

![sf adjust gv bug](https://user-images.githubusercontent.com/15316949/53489362-1bcf4100-3ae5-11e9-8940-ee178913aa33.JPG)

**General information**
 - OpenTX version 2.2.3
 - Hardware Frsky X9D+
 - OpenTX Companion 2.2.3 on Ubuntu 16.04 and Win 10

**Comment by raphaelcoeffic** [comment]
seems this wasn't in 2.3 yet (added to #6626)
