### ISSUE TITLE
Add FrSky telemetry ID form the number of active GPS satellite

### ISSUE THREAD

**Issue by iczfirz** [opentx/opentx#6345]
Please add telemetry ID for total number of active GPS satellite.
#define GPS_SAT_NUM_FIRST_ID        0x0860
#define GPS_SAT_NUM_LAST_ID         0x086f

**Comment by 3djc** [comment]
Those telem ID are decided by FrSky, not us. There is a DIY range from 0x5100 to 0x52ff

**Comment by iczfirz** [comment]
Thx 3djc. Does FrSky provide the telemetry ID table? Or radio/src/telemetry/frsky.h is a complete list already?

**Comment by 3djc** [comment]
FrSky does change this list when they want to, and they do usualy when they introduce new types of sensor for exemple. We update the list in frsky.h  when they do change it
