### ISSUE TITLE
how do I get more than 3 flightmodes? 

### ISSUE THREAD

**Issue by jensdk** [opentx/opentx#6346]
The issue tracker here is for devlopment of OpenTX. This is not a
support site, only a bug tracking system. Please use support groups
like [rcgroups](https://rcgroups.com/) or
[openrcforum](https://www.openrcforums.com/forum/). See also our
[manual](https://opentx.gitbooks.io/manual-for-opentx-2-2/).

For quick questions you can also join our general chat.

Issues that fall into the category of asking for help, will be
generally closed as invalid without an answer.

**Comment by jensdk** [comment]
In OTX above 2.2 it seems that it's only possible using 3 flightmodes the "easy" ...  on a 3pos switch, when I want to activate the  4.  mode, nothing happens.. 
i fly f3K planes  need 3 modes for camber and 1 for elevatorpreset when launching..  I have the 3 modes on SA and want the 4 on SF ..
using the "old" method doesn't seem to work.

**Comment by 3djc** [comment]
I'm sorry but this is a bug tracker, not a user support site. Please go to community places like rcgroups or openrcforums for usage type questions.

**Comment by jensdk** [comment]
IT's a kind of bug if you read it correctly.. 
Flightmodes has been limited, since earlier version.... ?

**Comment by 3djc** [comment]
No, you have exactly the same number of flighmodes

**Comment by jensdk** [comment]
Did you test it ?? 
I can get 3 modes, but when I want to activate the next "overule"  nothing happens.... 
Has the setup of modes been  changed since OTX 2.1 ?

**Comment by kilrah** [comment]
No. You're just misunderstanding the priority order of modes.

**Comment by mpjf01** [comment]
He seems to be claiming that something that used to work with a previous firmware now does not.  It might help him to understand why if he could be advised what was changed in the firmware that might have caused this issue for him.  It would help to see his .otx file for the model he is concerned about.

**Comment by kilrah** [comment]
He got answers to his question on forums as expected.
