### ISSUE TITLE
File system in "Special Functions" not working

### ISSUE THREAD

**Issue by exocode** [opentx/opentx#6348]
**Describe the bug**
The file listing is not working in special functions. In Special Functions, when I try to select a file while "Play Track" is selected, I don't get a list of files.

**To Reproduce**
1. Go to 'Special functions'
2. create  a new entry
3. select "Play track"
4. try to select a file
5. See error (attached picture)

(BTW: I can select the files correctly from within OpenTX Companion.)

**Expected behavior**
In step 4 of "To Reproduce" a list of files should appear
**Screenshots**
![img_1135](https://user-images.githubusercontent.com/1597621/53634263-0c9ddf80-3c1a-11e9-8b38-ab897ad71f8c.JPG)
![img_1134](https://user-images.githubusercontent.com/1597621/53634264-0c9ddf80-3c1a-11e9-9fc2-82b3c4cac454.JPG)
![img_1133](https://user-images.githubusercontent.com/1597621/53634267-0c9ddf80-3c1a-11e9-8ee3-490ff1ef39e4.JPG)

**General information**
 - OpenTX version (2.2.3 aee5ac05b)
 - Hardware (Frsky Taranis Q X7)
 - OpenTX Companion (Version 2.2.3, Jan 7 2019 on MacOS)

**Comment by kilrah** [comment]
Do you actually have the proper files at the right place, and the correct sound language selected?

**Comment by exocode** [comment]
Hi, 
I am working in "english" (en) folder.
Simply dropped the OpenTX card content on it. added Amber sound pack, that's it..

**Comment by exocode** [comment]
Could it be, that I am using Disk Content Version 2.2.2 and using OpenTX 2.2.3? (I didn't find any 2.2.3 Disk content)

**Comment by 3djc** [comment]
I cannot reproduce, works fine here. Have you checked there is not file (possibly hidden) with forbiden/strange name ?

**Comment by exocode** [comment]
Thank you for your time!

I got it working:
- Erased EVERYTHING on the disk
- downloaded 2.2.3 Files again https://downloads.open-tx.org/2.2/release/sdcard/opentx-x7/
- uploaded it: Worked

Sorry for waisting time :-|
