### ISSUE TITLE
X7q

### ISSUE THREAD

**Issue by homey65** [opentx/opentx#6357]
After using companion to update my new x7q. Know it won't come on regular or boot mode. In boot mode just a blank white screen. Was updating from in with USB cable mode from 2.2.0 to 2.2.3. I downloaded the most recent update and made sure the book "check for comparability" was checked. I'm new to the hobby and this is so fustrating. Thanks in advance

**Comment by 3djc** [comment]
I’m sorry to add to the frustration, but this place is not for usage support, but only to track identified bugs. Please go to community places like rcgroups or openrcforum for support.

**Comment by homey65** [comment]
Thank you
