### ISSUE TITLE
Flashing Frsky Horus X10s to non Eu firmware

### ISSUE THREAD

**Issue by theonlygk** [opentx/opentx#6358]
I've recently purchased a 2nd hand Horus already flashed to open tx but unfortunately its on EU firmware and I have lots of Frsky receivers all non EU as my taranis was pre 2015.

My question is how do I change this to non EU firmware please

**Comment by 3djc** [comment]
This place is only for bug tracking, not usage support. Please go to community places like rcgroups or openrcforums for usage type questions
