### ISSUE TITLE
altitude displayed with FAI mode

### ISSUE THREAD

**Issue by MartinSunal** [opentx/opentx#6363]
**Describe the bug**
I've flashed x9d+ to firmware 2.2.3 which includes FAI mode and it supposed to disable telemetry from vario but I still see altitude displaying on Top Bar.
I found this thread where FAI mode should be fixed:
opentx/opentx#3443
I see value 0 for Alti and Alt in the telemetry menu so I guess the fix in opentx works there but does not work with Top Bar.

**To Reproduce**
1. create and flash firmware 2.2.3 with faimode
2. set Top Bar -> Altitude 
3. connect TX and RX with vario
4. see main screen displaying altitude

**Expected behavior**
Altitude in top bar will be 0 or will disappear
 
**General information**
 - OpenTX version 2.2.3
 - Hardware: Frsky X9D+
 - OpenTX Companion 2.2

**Comment by 3djc** [comment]
Fixed in https://github.com/opentx/opentx/commit/b4f91b2f3e10268b9ee7b0e111e62fe651b8a1ea
