### ISSUE TITLE
Port to DIY ESP32 based boards.

### ISSUE THREAD

**Issue by tmrttmrt** [opentx/opentx#6373]
As my winter hobby project I work on port of OpenTX to ESP32. At the moment I have a basic working version of the radio firmware. I still need to figure out how to integrate it to Companion.  The branch is at: https://github.com/tmrttmrt/opentx/tree/esp32/ if anyone is interested.

Maybe it should be pulled into the upstream tree as a separate branch so others can test whether it breaks compilation for ARM. I wonder whether there would be enough interest and DIY enthusiasts to support the version.

**Comment by kilrah** [comment]
Interesting, the ESP32 has low I/O count, so how are you dealing with all the inputs? External processor? What are you using the ESP32's unique features for?

**Comment by tmrttmrt** [comment]
The pin count is indeed low. Two MCP23017 - i2c 16 input/output port expanders are a simple solution.

The main advantage of ESP32 for DIY is that is easy accessible and cheap with well established development environment.

My plan is to use the built-in WiFi for connection to Companion as well as non-latency-critical RC links eliminating the need for external modules. There are already some projects for this that could be incorporated.  LoRa ESP32 boards are another possibility for a compact RC link.

**Comment by renebohne** [comment]
I just had a look into your code. Great job, thanks! I tried to get low level access to the radio of the esp32 some time ago because I hoped that it can be used for general 2.4Ghz transmission. But no luck so far. If it was possible, there would be no need for an external nRF24L01 if somebody wants to do Bayang, MJX, or SymaX... 
I will get a ST7565P display and try your code soon. Did not look too deep, but are there the SPI pins that you use for the display? 
#define PIN_NUM_MOSI GPIO_NUM_12
#define PIN_NUM_CLK  GPIO_NUM_14
#define PIN_NUM_CS   GPIO_NUM_13

**Comment by tmrttmrt** [comment]
I doubt that the radio part is completely software defined and emulating any protocol is possible.  There exists, however, the esp32 long range WiFi mode that might be useful for RC.

The SPI pins in esp32 are quite flexible. At the moment my code uses all the pins so one can only swap pins to avoid any collision.  You also need at least two additional auxiliary pins to drive LCD:

#define PIN_NUM_DC   GPIO_NUM_27 // This pin selects the LCD command or data registers.
#define PIN_NUM_RST  GPIO_NUM_0 // Reset, it might be done by an external circuit on power on

**Comment by spectrenoir06** [comment]
I need to try this on my esp32 radio http://antoine.doussaud.org/esp32_radio
what is working right know ?

**Comment by kilrah** [comment]
This is very nice! Lack of switches is a little disturbing though!

**Comment by spectrenoir06** [comment]
Yeah it's was hard decision but the radio have to triggers buttons ( enough for arm + mode )
but the radio have a MCP3008 with 8 ADC input available

**Comment by tmrttmrt** [comment]
> I need to try this on my esp32 radio http://antoine.doussaud.org/esp32_radio
> what is working right know ?

I had noticed your radio before I started. Nice work!

Please see https://github.com/tmrttmrt/opentx/blob/esp32/radio/src/targets/common/esp32/Readme.md for the current status. Only PPM output is implemented now.  I am about to start some field tests. Before I do  I would like to implement SD card removal/insertion handling.

**Comment by powermik** [comment]
Would be awesome to support esp32 modules with integrated oled

**Comment by powermik** [comment]
can you post a quick schematic on how to connect the pots/switches?

**Comment by tmrttmrt** [comment]
https://github.com/tmrttmrt/opentx/blob/esp32/doc/esp-wroom-32/esp-wroom-32.pdf

**Comment by tmrttmrt** [comment]
The code has been pushed to 2.3 version by removing the MEGA2650 parts and basing everything on  the SKY9X-board code.

The ESP32 board was also included in Companion.

**Comment by tmrttmrt** [comment]
ESP-NOW protocol implemented as an internal module. Briefly tested with ESP8266 as a receiver on a micro quad.

The receiver code is at https://github.com/tmrttmrt/opentx-espnow-rx.

**Comment by tmrttmrt** [comment]
Ported to a board with an SSD1306 OLED display.

**Comment by Zebble** [comment]
For the life of me I can't seem to get this to build.  I'm using the 4.0 release of esp-idf on Windows, installed with the esp-idf tool and installed mingw32 stuff.  Cmake seems to work but no "flash" option gets added to the makefile so the flash command doesn't work...  Any pointers on creating a build environment on Windows that I might have missed?

**Comment by tmrttmrt** [comment]
Nothing special to do. I am using esp-idf 4.0-dev snapshot. I start mingw as this:
```
set IDF_PATH=/some-path/esp-idf 
T:\win64app\msys64\msys2_shell.cmd -here -mingw32
```

Do esp-idf examples compile and flash as expected?

**Comment by Zebble** [comment]
It looks like esp-idf release 4.0 (or higher) no longer use Msys2.  It all runs from a standard windows command prompt.
The examples compile and flash perfectly.  Just need to figure out how to use idf.py to do the compile and flash.  Not having much luck so far.

**Comment by tmrttmrt** [comment]
I updated the build files to post v4.0 IDF (branch esp32-idf-4.0). See readme.md under [...]/esp32 dir for info how to build. 
The binary is significantly larger with the new IDF version.

**Comment by naorunaoru** [comment]
So I tried to build it on macOS and failed. `esp32-2.3` branch fails to build because of MingW dependency:

```
/Users/naoru/Code/opentx/radio/src/targets/common/esp32/esp-idf/build/otxcore/build
CMake Error: Could not create named generator MinGW Makefiles
```

`esp32-idf-4.0` fails because it couldn't find partition table:
```
-- Checking Python dependencies...
Python requirements from /Users/naoru/Code/esp-idf/requirements.txt are satisfied.
Loading defaults file /Users/naoru/Code/opentx/radio/src/targets/common/esp32/esp-idf/../../../esp-wroom-32/esp-idf/sdkconfig.defaults...
CMake Warning at /Users/naoru/Code/esp-idf/components/partition_table/project_include.cmake:13 (message):
  Partition table CSV file partitions.csv not found.  Change custom partition
  CSV path in menuconfig.
Call Stack (most recent call first):
  /Users/naoru/Code/esp-idf/tools/cmake/build.cmake:306 (include)
  /Users/naoru/Code/esp-idf/tools/cmake/build.cmake:451 (__build_process_project_includes)
  CMakeLists.txt:13 (idf_build_process)
```

`esp-idf` version on my machine is 4.1, maybe that's not helping too.

My C skills are kinda crap so I'll try again on my Windows machine in a couple days.

Thank you for this project though, ESP32 is a fun little thing and I'd definitely choose it over AVR even if it requires using external port expanders.

**Comment by Zebble** [comment]
Had the same issues as you @naorunaoru.  I got a bit further but could never get the bin to compile so I gave up.  The instructions (and updated instructions) point to still using msys tools to compile, which esp-idf 4.0+ don't officially support anymore.  Any attempt I've made to get things working through Windows or Linux have ended up with the same issue...

I gave up for now.

**Comment by naorunaoru** [comment]
Sad news. @tmrttmrt please help with debugging these issues.

**Comment by naorunaoru** [comment]
Installed fresh mingw, added latest xtensa-esp32-elf toolchain, shuffled partitions.csv around a lot.

Now I'm here. No idf.includes generated indeed.

```
Scanning dependencies of target firmware
[ 37%] Building CXX object radio/src/CMakeFiles/firmware.dir/debug.cpp.obj
xtensa-esp32-elf-g++.exe: error: C:/MinGW/msys/1.0/home/naoru/opentx/build/idf.includes: No such file or directory
```

**Comment by tmrttmrt** [comment]
> So I tried to build it on macOS and failed. `esp32-2.3` branch fails to build because of MingW dependency:
> 

esp32-2.3 branch is outdated. Use the esp32 branch with esp-idf 4.0-dev git snapshot.

**Comment by naorunaoru** [comment]
> > So I tried to build it on macOS and failed. `esp32-2.3` branch fails to build because of MingW dependency:
> 
> esp32-2.3 branch is outdated. Use the esp32 branch with esp-idf 4.0-dev git snapshot.

Forgot to mention, I used esp-idf 4.0-rc on Windows last time I tried with esp32-idf-4.0 branch of your fork. I'll try to use 4.0-dev later.

**Comment by tmrttmrt** [comment]
Something got broken during upstream merging after tag 2.3.4-esp32 and a clean build does not work. Please try this tag with  esp-idf v4.0-dev.  I can perform clean build on Windows with this combination.

**Comment by tmrttmrt** [comment]
The tip of esp32-idf-4.0 branch compiles with esp-idf commit 39f090a4f1dee4e325f8109d880bf3627034d839 (I do not know how have I got this one checked out?) On my machine it is marked as origin/4.0 in SourceTree, but I cannot find it on GitHub. Sorry for 
confusion.

**Comment by Zebble** [comment]
Thanks @tmrttmrt.

I'm still confused.  Are you saying we need to download a specific commit of esp-idf and/or this repo?  Are you still preferring the legacy esp-idf install (gnu make/msys2/mingw) over the newer esp-idf tools installed (cmake/Windows console)?

**Comment by Zebble** [comment]
> Installed fresh mingw, added latest xtensa-esp32-elf toolchain, shuffled partitions.csv around a lot.
> 
> Now I'm here. No idf.includes generated indeed.
> 
> ```
> Scanning dependencies of target firmware
> [ 37%] Building CXX object radio/src/CMakeFiles/firmware.dir/debug.cpp.obj
> xtensa-esp32-elf-g++.exe: error: C:/MinGW/msys/1.0/home/naoru/opentx/build/idf.includes: No such file or directory
> ```

I'm in exactly the same spot now, so there's that...   :)

**Comment by tmrttmrt** [comment]
I tried to build on Ubuntu 16.04 and another Windows box and realized that the idf build process is much less robust than I assumed. Currently it builds only on my particular windows box with certain version of tools. I will now try to find how to reproduce the working build system on Windows and then start to work on compilation in the esp-idf v4.1 release.

**Comment by Zebble** [comment]
That's a good way to describe it tmrttmrt.  Definitely not very robust and things drastically change/break between releases.  Seems to be getting better with 4.x though...
Looking forward to see how you create your build system.

**Comment by naorunaoru** [comment]
`[100%] Built target flash`

I did it.

xtensa-esp32-elf toolchain version 5.2.0
tmrttmrt/opentx HEAD at d2b2754fa
esp-idf HEAD at tag v3.3.1 (what, why) with all submodules reinited

I don't have any peripherals connected to ESP32, even display, so I can't verify if it compiled successfully, but that's something.

**Comment by tmrttmrt** [comment]
> I tried to build on Ubuntu 16.04 and another Windows box and realized that the idf build process is much less robust than I assumed. 

I had broken esp-idf installation on the Ubuntu box. Following the instruction for esp-idf v3.3.1 to setup the tool-chain it builds straight out of the box as noted by naorunaoru.

In Windows it builds as well under MSYS2 MINGW32 shell provided together with esp-idf v3.3.1 toolchain. The MSYS2 environment, however, needs some tweaking:
Cmake for windows must be installed separately and included into the MSYS2 path.
``` 
pacman -S  mingw-w64-x86_64-make
pacman -S mingw-w64-i686-python2-pillow
export PATH=/mingw64/bin:$PATH
```
mingw32-make is needed to handle the opentx makefiles in Windows and I have no clue how to avoid it. Updating the  MSYS2 environment seems to break things so avoid it.

**Comment by naorunaoru** [comment]
> Updating the MSYS2 environment seems to break things so avoid it.

I've got the latest MingW with MSYS2. The only thing I did a bit differently is that I added `-DCMAKE_SH="CMAKE_SH-NOTFOUND"` to `cmake` because I use MSYS2 shell instead of cmd/powershell.

**Comment by tmrttmrt** [comment]
I  fixed esp32-idf-4.0 branch to compile with esp-idf v4.1 in Windows and Linux. 
In Windows MSYS2 environment is still required, but I had to use the native Windows python and cmake. 

I also had to significantly modify the PPM driver since RMT library was changed in v4.1. There might be issues due to this.

**Comment by naorunaoru** [comment]
I can confirm that it now builds on macOS. Super happy to use my usual development machine. 
Still waiting for the multiprotocol module to arrive. Already tested on a breadboard with gimbals, switches and buttons — it required a bit of specific tweaking here and there, but it works!

@tmrttmrt beware, if this port will ever be merged to upstream there will be tons and tons of inexpensive RC controllers with ESP32 and OpenTX. :)

**Comment by naorunaoru** [comment]
@tmrttmrt please advise on pullup resistors for buttons. I sometimes get weird misclicks on buttons connected to the MCPs.

**Comment by tmrttmrt** [comment]
Please look at the schematics. 100 nF capacitors parallel to the inputs and 100-200 Ohm resistors in series to the switches should do. Put both close to the inputs to filter out also any RF picked up by wires.

**Comment by Zebble** [comment]
@naorunaoru here's the link to the PDF schematic in case you can't find it:
[https://github.com/tmrttmrt/opentx/blob/esp32-idf-4.0/doc/esp-wroom-32/esp32-wroom-32.pdf](url)

I still can't get a build environment to work.  If anyone has the energy to create a build-doc for one it would be greatly appreciated.  Windows or Linux, I don't care.

**Comment by tmrttmrt** [comment]
On linux shuld be quite straigthforward. Install the he esp-idf as specified at https://docs.espressif.com/projects/esp-idf/en/latest/get-started/ . 

```
. ~/[path-to-esp-idf]/export.sh
python -m pip install Pillow
cd [src-path]
git clone -b esp32-idf-4.0 https://github.com/tmrttmrt/opentx.git
mkdir build
cd build
cmake  ../opentx/radio/src/targets/common/esp32/esp-idf  -DPCB=ESP_WROOM_32  -DCMAKE_TOOLCHAIN_FILE=$IDF_PATH/tools/cmake/toolchain-esp32.cmake
make flash ESPPORT=/dev/[tty-connected-to-esp32-board]
```

**Comment by Zebble** [comment]
Well, that worked!  Probably was obviously in my cmake line.  Now to build up a circuit!
Thanks @tmrttmrt

**Comment by Zebble** [comment]
> Ported to a board with an SSD1306 OLED display.

Any pointers on how to build for SSD1306 support?

**Comment by tmrttmrt** [comment]
-DPCB=ESP_HELTEC_32 configures for the Heltec  SSD1306 OLED board (https://heltec.org/project/wifi-kit-32/).  This configuration uses only one MCP23017 limiting the number of switches.

The pin definitions are in [opentx-src-folder]\radio\src\targets\\[board]\board.h:

```
#define I2C_DISPLAY_SCL_GPIO          GPIO_NUM_15
#define I2C_DISPLAY_SDA_GPIO          GPIO_NUM_4
#define I2C_DISPLAY_RESET_GPIO        GPIO_NUM_16
```

When porting to other boards one should also take a look at CONFIG_ESP32_XTAL_FREQ in   [opentx-src-folder]\radio\src\targets\\[board]\esp-idf\sdkconfig.defaults to select proper xtal frequency for the particular board.

**Comment by alexandrecnunes** [comment]
Is there another link to the schematic? Because this is not ok.
https://github.com/tmrttmrt/opentx/blob/esp32-idf-4.0/doc/esp-wroom-32/esp32-wroom-32.pdf

**Comment by tmrttmrt** [comment]
Please be more specific about what is not OK?

**Comment by alexandrecnunes** [comment]
excuse me,
when I try to access the link, it does not lead to a correct page. 
But now,I got it
Thank you

**Comment by gbraad** [comment]
@tmrttmrt Has there been any development/enhancements in recent time?
@spectrenoir06 interesting project, and exactly what I am trying to achieve. the size is great as that is perfect for small hands (like kids), unfortunately I wasn't able to find any schenmatics or design files.

I have some ESP32 modules that were sent to me by mistake (wrong part) and think this is ideal for a small transmitter that can even operate without a display (configured over bluetooth by a phone or webbrowser). At the moment more interested in getting it to work with the nRF24 from the MPM, but adding the serial protocol would certainly be great.

**Comment by tmrttmrt** [comment]
> Has there been any development/enhancements in recent time?

Unfortunately not.

**Comment by FractalEngineer** [comment]
@tmrttmrt Hey mate awesome work with this

I'd love to experiment with it making a modular TX; what's the current status on it; I saw in the schematics that PPM and power management is not yet implemented; is it still the case?

Does that mean that it can't yet work with external TX modules?

**Comment by tmrttmrt** [comment]
The git version is the last version. 
It can work with external modules that accept the PPM input since the PPM output is active. The software-controlled power hold and external PPM signal routing are not implemented.

**Comment by pierreh** [comment]
@tmrttmrt thanks for the great work!
I've managed to build this and flash it to a base ESP32-S, which is like the ESP32-WROVER.
I have to disable the `per10msTask` because it fails to communicate over I2C.
I don't need a lot of switches and no trims so I would like to use it without the IO expander and I want to implement the serial driver for an external module.
Can you give some pointers as to how to do those two tasks?

**Comment by tmrttmrt** [comment]
per10msTask should not be disabled since it performs quite a few important things in OpenTX.  Look into "keys_driver.cpp" for disabling I2C reads. 
For the serial driver I cannot help.

**Comment by pierreh** [comment]
Got it working without IO expander, with an oled display and sd card. Really cool! I've got some IO expanders on the way though, because I can only get 3 switch positions now. Just a few pins short ;-)
Enabling SPORT for an external module looks doable to me, but it may take a while to figure out all the details.
I've tried to get Lua support to build, but I'm running in to issues with the IDF cmake.
Have you tried to build Lua support?

**Comment by tmrttmrt** [comment]
Nice to have it working. I have not tried to build Lua. Unfortunately I cannot help much with cmake since my knowledge of cmake is on the level of guessing.

I have noticed however, that when building with  esp-idf versions above v4.0 the sound output and SD card are in some kind of conflict and either the sound output or SD card do not work.

**Comment by bangdc90** [comment]
@tmrttmrt 
Thank you for amazing project.
I am trying to bootup GLCD ST7565 with your sour code, but I am facing a problem that after mainGui show, it disappear immediatly. I tried many config for sequence of ST7565 but still fail.
Do you know any reason cause that issue?

**Comment by bangdc90** [comment]
I made it work after comment initAudio(); in board.cpp
And also need to disable reading/writing I2C in key_driver.cpp because i dont use external expand chip

**Comment by tmrttmrt** [comment]
Great! I have not touched the project for a while and I am currently too busy with my regular job to be able to help you. The absence of external chips would definitely hang the program.  initAudio() should, however, not interfere with the display.

**Comment by royyandzakiy** [comment]
Hi, I think I'm a little bit late, but I just stumbled upon this really great project. I've seen that this has the option to use PPM to connect to external modules. But is it able to connect using the CRSF protocol, so that I could connect a ELRS module using the TX pins? I have concerns of the latency that PPM might bring if I use it to connect with a Crossfire module or such alike

Thanks in advance!

**Comment by tmrttmrt** [comment]
Unfortunately not.

**Comment by geofrancis** [comment]
have you seen espnow? it might be a viable way of doing a long range rc link with these. 
https://discuss.ardupilot.org/t/simple-esp-telemetry-serial-bridges/75536

**Comment by tmrttmrt** [comment]
I have already implemented it, so one does not need any external module.  The receiver part (https://github.com/tmrttmrt/opentx-espnow-rx) is still quite rudimentary.

**Comment by royyandzakiy** [comment]
Alright, thanks for the response!

**Comment by micahvdm** [comment]
@tmrttmrt any chance that you have binaries for this? I have tried everything, but it just won't compile. I'm trying to compile the SSD1306 version. That doesn't work and neither does the WROOM version...I have even tried going back to esp-idf 4.0, but no success...

**Comment by tmrttmrt** [comment]
Building is tricky because esp32 libraries are not very stable. On Windows is even more tricky because esp32-idf moved away from Msys2 environment that is needed by  OpenTx so one needs to tweak tools manually to make it work and a simple update of Msys2 breaks things. I would suggest to compile it (commit  9735fb7aac08a5b4b25b4bfb2f60334425f7e087) in Linux using esp32-idf-v4.0 first. 

I only have some old binaries for Heltec board, not sure which commit: https://drive.google.com/file/d/1lqR29uIMZuHNjBhmJLxvR0s28OvPGfJ3/view?usp=sharing

**Comment by micahvdm** [comment]
@tmrttmrt this is great, managed to get it to compile on debian! Got everything working except ppm out. It doesn't seem to be sending anything out...am I missing something?

**Comment by tmrttmrt** [comment]
Have you set it up in the OpenTX menues? There could also be the that the esp32-idf version does not fit the particular commit. At some point PPM was broken due to an esp32-idf libraries change (see  f8700172b7627197ac7d7d761ec37a5890e11ea6).

**Comment by bangdc90** [comment]
![Screenshot 2021-12-12 130622](https://user-images.githubusercontent.com/65581036/145702462-38e111e7-6fc9-49a0-8c78-04647ac12e86.png)
Hi @tmrttmrt 
I integrated your source code to use RF module A7105 like TX flysky, but if keep your source code to use ESP wifi as internal RF, Did you test the range with  https://github.com/tmrttmrt/opentx-espnow-rx. ?
Can it  work with 150-200m?

**Comment by tmrttmrt** [comment]
Great to see it working! I have not checked the range, just flying a small drone indoors.
![IMG_20211212_084946165_HDR](https://user-images.githubusercontent.com/13926769/145704804-daf368b7-1bd4-4d90-a846-096d2a7f98b7.jpg)

**Comment by relaxibus** [comment]
Great job! I'm looking for an ESP32 coder for the USB2RC box project. A sort of very very simple ESP32 OpenTX for USBHID simulation devices, such as HOTAS, Joysticks, etc. The USB2RC box is composed by a USB HID board that sends out a SERaero serial stream to the ESP32. The ESP32 than act as the RC middleware sending out either PPM, serial (CRSF) or CAN. Hope to gain some interest.

**Comment by Dom-Tursini** [comment]
This is such an awesome project, I did see that there was a post asking to get OpenTX working on a Pi Pico, it was shot down quite quickly due to lack of GPIO pins, but having a 16ch expander is pretty simple, is there any way to get the ESP32 version ported to a Pi Pico W or am I missing something obvious? (I probably am)

**Comment by JunOllyLi** [comment]
@tmrttmrt , just wondering, have you figured out how to use the WiFi on the ESP32 to connect to the companion?

I gave up on building your code due to the variation of esp-idf. And I took a different route that uses the Arduino build environment as the low level BSP. That way I may get to switch other Arduino supported board later.

But I am very interested to see if you can connect to companion with WiFi.
Thanks!

**Comment by tmrttmrt** [comment]
It was working, but I have not touched it for a long time and have forgotten most of the details. Setting up environment to build Companion was quite tricky. For compilation I have to disabled firmware building within the Qt Creator to build just Companion.
