### ISSUE TITLE
Taranis E voltage indicator bar

### ISSUE THREAD

**Issue by frobert0** [opentx/opentx#6374]
With my FrSky Taranis E it comes to a false display when Spannugsanzeige bars in the upper display which manifests itself as follows.

The second green bar is always there even if the first yellow or less bar is no longer displayed.

Is someone familiar with this mistake and where does it come from?

Photo
https://www.dropbox.com/s/hft9n4kkla3tx3c/20190323_103829.jpg?dl=0

Robert

**Comment by kilrah** [comment]
Never seen that before, probably a faulty segment.

Or maybe the fact that the operation timer has far exceeded max capacity, maybe reset it.

**Comment by frobert0** [comment]
> Never seen that before, probably a faulty segment.
> 
> Or maybe the fact that the operation timer has far exceeded max capacity, maybe reset it.

Reset operating timer has helped.
Thank you

**Comment by kilrah** [comment]
I believe the timer capacity was increased at some point, so you're probably on an old OpenTX version.

**Comment by frobert0** [comment]
OpenTX version is 2.2.3

**Comment by frobert0** [comment]
> I believe the timer capacity was increased at some point, so you're probably on an old OpenTX version.

OpenTX version is 2.2.3

**Comment by 3djc** [comment]
A fix has been pushed to futures 2.2.4 / 2.3 to prevent this in the future
