### ISSUE TITLE
Lua Documentation for OpenTX 2.2.3

### ISSUE THREAD

**Issue by JohniUYS** [opentx/opentx#6376]
Hello, i tried coding some Telemetry scripts for my Taranis but i encountered errors getting the value from one of the Switches, i tried several methods eg. getValue("MIXSRC_SF") or getValue(97) but neither of thoose give me the required output

**Comment by 3djc** [comment]
https://opentx.gitbooks.io/opentx-2-2-lua-reference-guide/content/general/getValue.html

Source are linked
