### ISSUE TITLE
Lua Error, getValue doesnt work (OpenTX 2.2.3)

### ISSUE THREAD

**Issue by JohniUYS** [opentx/opentx#6377]
Hello i have now looked at the linked sources in the lua documentation, but i still cant get my script to work.
i have tried the following getValue combinations
getValue("MIXSRC_SF")
getValue(97)
getValue("sf")

But the script still doesnt work here is my code, i hope someone can help me https://hastebin.com/ojoviyudos.bash

**Comment by 3djc** [comment]
This place is not for support, just for tracking opentx bugs and enhancements request. What you need is community support like you can find in rcgroups or openercforums.

**Comment by lshems** [comment]
Check my blog on rcgroups, or send me a PM there.

I'll try to help you from there.
