### ISSUE TITLE
OpenTX 2.2.3 SD Card Files are not accepted by Taranis X9D

### ISSUE THREAD

**Issue by Oberlurch3000** [opentx/opentx#6385]
I updated my Taranis to OpenTx 2.2.3 (also the bootloader). I checked that both are really at version 2.2.3 now.
I copied the SD card files from the companion app to the SD card (2.2V0018).
First everything was fine... but since a few days my taranis is showing me the message "Expected version: 2.2V0018". That is the version I've installed. The readme file also says 2.2V0018.
The SD card does not show up in the menu at this point. But if I pull out the card while the X9D is still turned on and the push it back in it gets detected.
I've no idea whats going on there.

**Comment by 3djc** [comment]
Likely a hardware issue. Try changing sdcard. Closing this as this is not an OpenTx bug
