### ISSUE TITLE
Mega 2560 invalid board

### ISSUE THREAD

**Issue by KiddKhaos** [opentx/opentx#6390]
Tried to download firmware for Mega 2560 and get an "invalid board" message. I have tried it on my windows 8 and 10 pro machines with different iterations of companion and I always get the same error message. I can download firmware for other Tx's without issue. I have tried different combinations of build options and that doesn't change anything.

**Comment by kilrah** [comment]
Version? 
Last version with AVR radio support is 2.1.9.

http://www.open-tx.org/2018/02/26/avr-pull

**Comment by KiddKhaos** [comment]
That was it! I was watching a video where a guy downloads 2.2.1. I tried 2.1.9 and no issues thanks! Now on to run into new barriers haha.
