### ISSUE TITLE
Channel latches with input using MAX and LS

### ISSUE THREAD

**Issue by lthole** [opentx/opentx#6391]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by lthole** [comment]
If an Input with MAX as source and an LS as switch is mixed to a channel, the channel will latch high.

Example:
LS01 
AND SA↓ SB↓

IP05
Source = MAX
Switch = LS01

CH05
Source = IP05

When both SA and SB are down, CH05 will go to 100%. When either or both switches are switched up, CH05 stays at 100%.

Hardware: X10S with OpenTX 2.2.3
Also happens with Companion.

**Comment by kilrah** [comment]
Perfectly normal. An input with no active line maintains its value.
