### ISSUE TITLE
Jumper T16 companion

### ISSUE THREAD

**Issue by gian1312** [opentx/opentx#6398]
Hi,

It seems as the Jumper T16 is a nice remote with a lot of interesting features. 
Thus, using companion would be a big benefit. Are there any plans to add the jumper models to the companion or is there an easy workaround?

Best,
Gian

**Comment by 3djc** [comment]
You should ask jumper, as those radio are not running OpenTx, but JumperTx

**Comment by iFly4rotors** [comment]
Consider: JumperTX is a fork of OpenTX...while there may be additional extensions, the base is still OpenTX. In my research, it seems that the Jumper T16 is pretty close to the Taranis Horus transmitter in terms of electronical compatibility.
