### ISSUE TITLE
Display Stick and uSec position on Curve graph

### ISSUE THREAD

**Issue by Jetrell** [opentx/opentx#6399]
Currently, there seems to be no way to overlay the stick and micro second position on the curve graph.

![20190420_102202](https://user-images.githubusercontent.com/47995726/56448878-77d07c00-6356-11e9-99da-7c8e06f0be8d.jpg)

Even my old Spektrum and JR radio's can do this.  

DX6 display
![20190420_101826](https://user-images.githubusercontent.com/47995726/56448883-828b1100-6356-11e9-992d-8b7ea139cd41.jpg)

Its very helpful when setting up a throttle curve, if you can see exactly were about's the stick is positioned with the Input and Output uSec values. So the curve can be plotted more precisely and quickly.

The Inputs page has a similar feature. but it doesn't relate to the Curves page.

![20190420_095918](https://user-images.githubusercontent.com/47995726/56448906-d8f84f80-6356-11e9-965c-dc097cd4205c.jpg)

It makes it very tedious when trying to fine tune any curve. If we have to keep jumping back and forth between the Curve and Channel monitor screens.

**Comment by lshems** [comment]
For info: is fixed by me and others using Lua.

**Comment by Eldenroot** [comment]
Good idea nad I miss this from Spektrum radios

**Comment by ripper-911** [comment]
Glad I found this as I was just about to submit it as a feature request. Would be the bomb for matching servos using the curve functions.

**Comment by Eldenroot** [comment]
PR is ready :)
