### ISSUE TITLE
NEG/POS in Inputs unexpected behaviour

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#6402]
OpenTX 2.2.3 X9D and Companion

Using POS and NEG in Inputs leaves a random result, if the stick is in the opposite half. Using curves instead POS/NEG gives the expected result.

OTX File attached
[Neg_Pos.zip](https://github.com/opentx/opentx/files/3124101/Neg_Pos.zip)

**Comment by kilrah** [comment]
POS deactivates the line whenever the source is negative and vice versa.
An input without an active line keeps its last value.

Your job to do things right to get what you need given the above definitions. It is usually recommended to keep a default line at the bottom of each input should all others get deactivated unless you're sure you understand how it works, common advice given on forums.

**Comment by Allerhopp** [comment]
I expected the source to become zero before it turns negative. But i will contact forums for advice.
