### ISSUE TITLE
X-Lite Pro se and sf not working with Lua getFieldInfo(  ).id

### ISSUE THREAD

**Issue by agibson2** [opentx/opentx#6405]
**Describe the bug**
Using the factory software on the X-Lite Pro, If you try and get the .id using getFieldInfo for the X-Lite Pro's momentary buttons 'se' and 'sf' in a telemetry script, LUA gives an error.  This prevents us from using them for lua scripts.  I am trying to get the DLG script working on the X-Lite Pro but I need to use the new Pro version momentary buttons on the top.
https://www.rcgroups.com/forums/showthread.php?2298914-F3K-training-script-for-the-Taranis-Q-and-Horus

*A clear and concise description of what the bug is.*

Create a lua script that calls the below functions.  Using sa, sb, sc, or sd work but se and sf don't.

getFieldInfo ( 'se' ).id
or
getFieldInfo ( 'sf' ).id

Script syntax error
..../custom.lua 7
attempt to index a nil value

**To Reproduce**
1. Create the lua script that calls the functions
2. Run the telemetry script
3. The error causes the script to give an error

**Expected behavior**

The getFieldInfo('se').id should return not fail so that we can use it in Telemetry scripts.

**General information**
 - OpenTX factory installed opentx-xlites 2.3.0 (05f0057b) from FrSky (2019-04-19 13:23:35 EEPR:219
 - Hardware X-Lite Pro

**Comment by 3djc** [comment]
Fixed in upcoming 2.3
