### ISSUE TITLE
Telemetry sensor logging doesn't log strings

### ISSUE THREAD

**Issue by teckel12** [opentx/opentx#6413]
**Describe the bug**
It seems that OpenTX is only logging telemetry values that are integers or floating point values.  Alphanumeric string sensor values are logged as `0`.

**To Reproduce**
1. Use Crossfire telemetry
2. Enable logging of telemetry sensors, specifically `FM` (flight mode)
3. Set custom function to log telemetry
4. Review telemetry log and `FM` sensor values which are all zeros

**Expected behavior**
As Crossfire telemetry uses the `FM` sensor to show the flight mode, values should be: `!ERR`, `ACRO`, `WAIT`, `ANGL`, etc.

**Screenshots**

**General information**
 - OpenTX version 2.2.3
 - Hardware Frsky X10S & Q7X
 - OpenTX Companion 2.2.4N689

**Comment by kilrah** [comment]
We'll have to at some point add expand the sensor class to have a getLogString function or something to be able to handle things better here and cleanup a lot of formatting mess in the logging itself.
