### ISSUE TITLE
Xlite Pro : cannot read models and settings from companion

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#6425]
Cannot read models and settings for companion N3

**Comment by agibson2** [comment]
I have setup my DLG sailplanes from scratch in X-Lite Pro on the Radio before companion and upgraded companion and the firmware to N3 and now N4.  When I read the settings from radio on any of the nightlies, I get a message 'Can't extract RADIO/radio.bin.'.  If there is something you need from me, like the EPROM backup, let me know.

I am running Windows and using the firmware... 'opentx-xlites-faichoice-lua-multimodule-en-N4.bin'.  I put the N4 in the name to keep track of firmward downloads.  I am not using multimodule yet or configured that in the radio just as an FYI.

**Comment by 3djc** [comment]
Closed in N5
