### ISSUE TITLE
Companion (X-Lite Pro) loses SpecialFunction switch selections on load of .otx

### ISSUE THREAD

**Issue by agibson2** [opentx/opentx#6427]
**Describe the bug**
Loading a saved .otx that was created for the X-Lite Pro causes a lot of Special Function switch selections in the drop down box to disappear.  I have only tested X-Lite Pro so far (N5)

Only SF is shown out of SA, SB, SC, SD, SE, and SF for example.  The previously configured 'switches' that you configured appear as just blank.  You can't go in and fix it because the selections are not in the dropdown list anymore. 

**To Reproduce**
1. Create a .otx file for X-Lite Pro and create switch functions using SA, SB, SC, SD, SE, and SF.
2. Load the .otx file again
3. Go to the SPecial Functions screeen and see that some of the switches you chose are now blank and you cannot find them in the dropdown list to choose them again.
4. See screenshot.

**General information**
 - OpenTX version (e.g. 2.3.0 N5)
 - Hardware (X-Lite Pro)
 - OpenTX Companion (2.3.0 N5 on Windows)

Ignore in the screenshot that I didn't select any wav files for playing.  I didn't have them in the SD directory to select yet.  I was just preparing the Special Functions.

![2019-05-18](https://user-images.githubusercontent.com/6733850/57965478-bd12aa00-7912-11e9-9009-e3d560a53462.png)

**Comment by 3djc** [comment]
Fixed in N7
