### ISSUE TITLE
Companion 2.3: Splash screen blurred/corrupt

### ISSUE THREAD

**Issue by MikeNH** [opentx/opentx#6436]
![CompanionSplashScreen](https://user-images.githubusercontent.com/16496376/58037942-a4fe7e80-7afc-11e9-97f0-daa00fa1b968.jpg)

**Describe the bug**
Companion 2.3 Startup/Splash screen displays incorrectly (See attached). This is a Windows 10 system. Companion 2.2 displays correctly.

**To Reproduce**
Starting Companion generates corrupted image.

**Screenshots**
Screenshot attached

**General information**
 - OpenTX version 2.3.0N9 May 20, 2019
 - Windows 10

**Comment by bsongis** [comment]
We need an artist :)

**Comment by mhotar** [comment]
![splash23_1](https://user-images.githubusercontent.com/6114100/58239557-8ccf6f00-7d49-11e9-8b9b-efc08324dc17.png)
Here we go. Now I have to set the git to be able to contribute to opentx repo again :)

**Comment by 3djc** [comment]
😍

**Comment by mhotar** [comment]
![splash23_3](https://user-images.githubusercontent.com/6114100/58242361-fa31ce80-7d4e-11e9-943f-4d2181c4ff56.png)

**Comment by 3djc** [comment]
Commited !
