### ISSUE TITLE
X-VERT won't arm

### ISSUE THREAD

**Issue by fulltimer123** [opentx/opentx#6453]
I updated my IrangeX 4-in-1 module and now my AC will not arm.  No other changes made.

It worked perfectly before.

Taranis Plus running latest release of OpenTX.

Can't find anything on the DIY module github page

**Comment by kilrah** [comment]
Nothing to do with us.

The module at some point changed scaling for DSM, could be that depending on what version you had before.
Might want to check the multimodule thread on rcgroups.

**Comment by OpenUAS** [comment]
Maybe this will still help someone stumbling over this issue:
* https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/issues/227
* https://www.youtube.com/watch?v=SDCpQijk9Is
* https://www.multi-module.org/using-the-module/protocol-details/dsm
* https://www.deviationtx.com/forum/model-configs/7234-horizon-hobby-x-vert-vtol#63430

Note that to  bind the TH_KILL has to be in killed position value at bind... else no bind possible
