### ISSUE TITLE
SBEC_POWER sensor not processed

### ISSUE THREAD

**Issue by dgatf** [opentx/opentx#6457]
Hi,

Using opentx 2.2.3 (ae5ac05b) in Taranis X7

Sensor SBEC_POWER (0x0e50 to 0x0e5f) is not processed correctly. It appears as sensor 0E50 and value is RAW. Expected two sensors SbecV (bytes 1, 2) and SbecA (bytes 3, 4), similar as ESC_POWER

Cheers,
Daniel

**Comment by 3djc** [comment]
Yes, the fix is done already, and this will be part of 2.2.4 and 2.3. It is also in current 2.2.4 nightlies
