### ISSUE TITLE
A maintenance mode like ErskyTX

### ISSUE THREAD

**Issue by fulltimer123** [opentx/opentx#6471]
I don't know if such a feature exists and I've not found it or what.....

But being able to flash bootloaders, MultiModule firmware, etc, etc from an  OpenTX based Xmitter (like Taranis for example) would be wonderful.

If this already be done, please ignore my noob'ness and point me in the right direction.

Thanks

**Comment by kilrah** [comment]
Bootloader, module firmware etc are flashed form the SD card browser.
Flashing multimodule isn't supported at this point.
