### ISSUE TITLE
2.3 Lua missing popupInput

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#6472]
Got put aside and needs to be readded

**Comment by raphaelcoeffic** [comment]
@3djc any news here? What was the reason why it was removed / deactivated?

**Comment by 3djc** [comment]
@bsongis removed it because popups have been completely redesigned. It needs to be rewritten to support the new popups

**Comment by raphaelcoeffic** [comment]
@bsongis @3djc I had a look at where it is used, and it seems that internally, it is only used with the curve presets. In LUA, I cannot imagine someone using it, as it is really not nice for entering a parameter. So probably everyone made it differently.

Bottom line: what about just obsoleting that function?

**Comment by 3djc** [comment]
I opened it because I got informed that some fairly well known script was using it and failed with 2.3. And of course, I cannot remember which one :(

**Comment by 3djc** [comment]
Exemple is JFrickmann's DLG timing script

**Comment by bsongis** [comment]
please would you share the script so that we can think of a good solution?

**Comment by raphaelcoeffic** [comment]
@jfrickmann Jesper? Could you please jump in so we can find a good solution for your script?

**Comment by jfrickmann** [comment]
Thanks for the heads up, I was not aware that it is being removed. I can easily modify my scripts to not using it anymore.  I will put that on my to do list.

**Comment by jfrickmann** [comment]
You can find my programs and scripts here: https://github.com/jfrickmann/SoarOTX

**Comment by raphaelcoeffic** [comment]
@jfrickmann thx!

**Comment by lshems** [comment]
You can write a lua version of the popup input. Wasn't it used in the wizard? must be some code to be reused there than.

**Comment by jfrickmann** [comment]
I plan to do it the same way I have done the J programs - no problem!

————————
Jesper Frickmann

**Comment by sande005** [comment]
I'd suggest this be reopened.  I was using it on a telemetry script that tracked flight time and battery usage.  Used the popupInput to allow entry for however many mah were used for recharge during a day of flying.  X9d running 2.3.7

**Comment by sande005** [comment]
OK, so it turned out not to be very hard to replicate the function.  So while it was nice, I can see that it is something that isn't really needed.
