### ISSUE TITLE
No longer able to flash receiver using the S.PORT upgrade port on QX7/QX7S

### ISSUE THREAD

**Issue by ghden** [opentx/opentx#6473]
I have two remotes QX7 and QX7S and was able to flash all my sport receivers correctly using the S.PORT upgrade port and after upgrading to 2.2.2 release and later 2.2.3 versions no longer working, is not providing power probably not signal either, instead I was able to flash using the bottom 3 of the 5 pins in the back... I think this is an easy and important bug to fix. The error I receive is the same as when there is no receiver connected to that port "FW update error Bottom pin no resp"

**Comment by 3djc** [comment]
There are two versions of x7 boards. The very first ones did not have the 3 pins soldered at the bottom, and require using the bay to flash receivers. Very quickly, a new revision was made that had the pins and those can only use the bottom pins to flash. There is a hardware revision check in OpenTX for that.

If yours did come with bottom connected installed, then they should be  from the current revision, and that seems to be what OpenTX is detetecting, so I'm unsure why you have this issue
