### ISSUE TITLE
"Firmware update check failed, New version information not found or invalid."

### ISSUE THREAD

**Issue by itsmerandy** [opentx/opentx#6477]
Hello, Purchased a new Taranis X-Lite and went through process of upgrading the firmware and had issues with OpenTx giving me error messages everytime I open it with controller connected. nIt doesn't matter if controller is in Bootloader mode or turned off or on I still get this message.
"Firmware update check failed, New version information not found or invalid."
Also I get an SDcard error on x-lite when I turn it on "Expected version: 2.2V0016" The Sdcard has a newer SDCard version 2.3V0019 on it, why is it expecting an older SDcard ver?
Sorry, I'm really new to all of this. Thanks

**Comment by 3djc** [comment]
Sorry but this place is only for bug tracking, not usage question. Please go to community support forums like rcgroups or openrc forum
