### ISSUE TITLE
MPM on X-light-pro Fails to go online. Status light turns Red. Will not Bind.

### ISSUE THREAD

**Issue by fabioeh** [opentx/opentx#6487]
**Describe the bug**

MPM Vantech module Fails to go online. Status light turns Red. Will not Bind.
Setting External RF to off and reselecting MULTI brings the MPM module online and the Status light turns green. Turning radio off and on will not bring MPM online. Using DSM x22 protocol.

**To Reproduce**

1. Power up
2. Select Model with MPM MULT DSM X22ms
3. MPM turns on Lights will blink but turn red.
4. Setting External RF to off
5. Reselecting MULTI brings the MPM module online and the Status light turns green

**General information**

X-Light-Pro MPM ver 1.2.1.51,  Opentx N23, Radio Firmware 190605

**Comment by 3djc** [comment]
Duplicate #6481
