### ISSUE TITLE
Add Lua access to 'include trims' on model.getInput() and model.insertInput()

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#6491]
Currently, one of the settings missing in the LUA functions to read and modify inputs is the 'include trims'.

Would be nice to be able to access it.

I cannot assign myself. Would like to try and solve this one myself, so please assign me to this issue for 2.3. Thanks

**Comment by lshems** [comment]
Created a pull request.

**Comment by bsongis** [comment]
Will fix issue #6491
