### ISSUE TITLE
Crossfire in Xlite Pro with Open TX 2.3, It is already working perfectly, for the moment it is only to make this modification and the Telemetry and the Scrip Lua are working 

### ISSUE THREAD

**Issue by alexestevezfpv** [opentx/opentx#6496]
Crossfire in Xlite Pro with Open TX 2.3, It is already working perfectly, for the moment it is only to make this modification and the Telemetry and the Scrip Lua are working
https://youtu.be/Jf1DSeO-VEI

**Comment by kilrah** [comment]
Not an issue
