### ISSUE TITLE
R9M full size on X-Lite Pro

### ISSUE THREAD

**Issue by playlet** [opentx/opentx#6499]
Hi, guys!

I just tried R9M full size module on X-Lite Pro (EU mode), on latest N24 nightly.
It binds and works ok but there are some issues, described below.

Latest FLEX firmware on 868 has the following power levels: 10mw, 100, 500, adaptive.
Nightly for X-Lite Pro has 25 8ch, 25 16ch, 200, and 500. Do these power levels correspond to the above mentioned for flex: 10, 100, 500, 1W (adaptive)?

Next, on nightly, 200 and 500 options don't have the option to turn the telemetry on while binding (only 1-8 off and 9-16 off). So if I bind on 200 or 500mw, there is no telemetry.
Latest flex firmware enables telemetry on all power levels so it should work.
Workaround: bind on 25mw with telemetry on and then switch to higher power levels. It works.

Third problem (might not be a problem but only a fluke).
After binding, when I was trying different power levels, somehow 200mw was buzzing louder on my X9D Plus speaker nearby than 500mw.
Now, after each new try, it seems ok and 500mw is louder than 200mw. Strange, can't reproduce it anymore.

Just wanted to share stuff I noticed.

Thanks for your support.

Kind regards,

Ivan

**Comment by 3djc** [comment]
Not sure what you tried !

![image](https://user-images.githubusercontent.com/5167938/59508854-a2026e00-8eaf-11e9-8423-358bd11eb6f8.png)

![image](https://user-images.githubusercontent.com/5167938/59508983-07eef580-8eb0-11e9-8dea-6da5d4a7c128.png)

**Comment by playlet** [comment]
Hi!

I downloaded N024 latest nightly companion form here: https://downloads.open-tx.org/2.3/nightlies/companion/windows/

Have it setup like this:
![image](https://user-images.githubusercontent.com/24281976/59529093-5ae0a100-8ee0-11e9-90cd-c86ad981243d.png)
![image](https://user-images.githubusercontent.com/24281976/59529126-6af88080-8ee0-11e9-8035-d2161e507cb6.png)

Downloaded nightly N024:
![image](https://user-images.githubusercontent.com/24281976/59529216-b743c080-8ee0-11e9-8814-21a3fe24c335.png)

Installed:
![20190614_201502](https://user-images.githubusercontent.com/24281976/59529752-2d94f280-8ee2-11e9-8c0c-d55bf0ed44ed.jpg)
![20190614_201514](https://user-images.githubusercontent.com/24281976/59529767-3ab1e180-8ee2-11e9-8e9c-da5b6000fb8a.jpg)

Setup new model, and this is what I get in the menu:
![20190614_201827](https://user-images.githubusercontent.com/24281976/59529813-50bfa200-8ee2-11e9-96e6-f14d6ab08d00.jpg)
![20190614_201835](https://user-images.githubusercontent.com/24281976/59529831-5a490a00-8ee2-11e9-88cf-17e60d72c4d9.jpg)
![20190614_201841](https://user-images.githubusercontent.com/24281976/59529846-6634cc00-8ee2-11e9-98cb-c54faed6773d.jpg)
![20190614_201847](https://user-images.githubusercontent.com/24281976/59529863-7351bb00-8ee2-11e9-8145-9c4be71db715.jpg)

Did I miss anything?

Kind regards,

Ivan

**Comment by 3djc** [comment]
What was the full name of the downloaded firmware ? Also, this is EU settings, not FLEX, Flex show frequency

**Comment by playlet** [comment]
opentx-xlites-flexr9m-lua-luac-noheli-en-2.3.0N24

There is no other option, only FCC or EU with R9M.

**Comment by 3djc** [comment]
There seems to be something really strange happening on the compilation server, will investigate tomorow

**Comment by playlet** [comment]
Thanks for the support, I am at your disposal for any further tests from my side.

**Comment by 3djc** [comment]
Yes, you can try N25 tomorow, I have pushed a fix

**Comment by 3djc** [comment]
Tested this morning, now ok :)

**Comment by playlet** [comment]
Confirmed, it's ok. Thanks!
