### ISSUE TITLE
Horus X10 Gimbal Switches CON11 CON12

### ISSUE THREAD

**Issue by mottobug** [opentx/opentx#6508]
Hello,

i'm trying to use gimbal switches in my X10s. I found the connectors CON11 and CON12 from i assume there are supposed to use with gimbal switches. I found a piece of circuit diagram here:

https://static.rcgroups.net/forums/attachments/2/1/4/3/5/t10691873-51-thumb-Pin%20Belegung%20Hauptplatine_Kn%C3%BCppelsticks.png?d=1517319706

Is there a way to use this in OpenTX?

I've searched the code and found definitions for gimbal switches in hal.h (HARDWARE_SWITCH_GMBL, HARDWARE_SWITCH_GMBR). But i can't figure out how to use them in software.

Any hint is greatly appreciated,
Thomas

**Comment by 3djc** [comment]
Will be available in 2.3
