### ISSUE TITLE
Lua scripts, menu button on Taranis X7 does not work running OpenTX 2.3

### ISSUE THREAD

**Issue by vkolotov** [opentx/opentx#6509]
I know that 2.3 is not released yet, but this might help you anyway.

I'm testing OpenTX 2.3 and Betaflight lua scripts (latest release - 1.3.0). I can switch to a display with lua script and I can see my PIDs, however I cannot switch to other screens or save changes. Effectively "menu" button does not work, when I push it (either long or short) nothing happens.

* Taranis X7
* OpenTX 2.3 (8c56a131ede013104bc89f6cf2a82063faeb5061)
CMAKE OPTIONS: -DDISABLE_COMPANION=YES -DLUA_COMPILER=NO -DLUA=YES -DSUPPORT_D16_EU_ONLY=NO -DTRANSLATIONS=EN -DTARANIS_INTERNAL_PPM=NO -DGVARS=YES -DSHUTDOWN_CONFIRMATION=NO -DMULTIMODULE=NO -DRAS=YES -DOVERRIDE_CHANNEL_FUNCTION=YES -DPCB=X7 -DPPM_UNIT=PERCENT_PREC1 -DHELI=NO
* Betaflight lua scripts (1.3.0)

**Comment by vkolotov** [comment]
Could it be something to do with this?
https://github.com/opentx/opentx/pull/6502

**Comment by 3djc** [comment]
Could you test again after pulling ? (I don't have any quad :D)

**Comment by vkolotov** [comment]
Yep, it is working now. Thanks ;)

**Comment by 3djc** [comment]
Thx for reporting and testing !
