### ISSUE TITLE
Enable use of extended characters in input names.

### ISSUE THREAD

**Issue by Dvogonen** [opentx/opentx#651]
The automatic conversion creates Inputs using the names of the original mixer sources.
This is logical. What is less logical is that it is not possible to use extended characters in input names. This is kind of a big deal for my specific language. åäö are very common letters and the name for Elevator (Höjdroder) is  Höj.

As a result the input name for my old elevator mixes are given the nonsensical name H7j on my Taranis. In the emulator I think I saw the name H j (might be wrong there).

We had a discussion a while back about extended characters in model names and came to the conclusion that they would have to go, since they would cause havoc if the user switched language. A model name is just a name so it will be understandable in another language context. Having extended chars in a model name is a nuisance. 

That  reasoning does not apply to input names. These names need to be descriptive and become part of the interface. To keep them descriptive the user will have to translate them himself if he chooses to switch language. There is no way around this. So using extended characters in input names does not make the situation any worse.

**Comment by kilrah** [comment]
Related but less detailed than #2432
