### ISSUE TITLE
Lua scripts, up/down buttons on X LIte Pro not work running N30 FW

### ISSUE THREAD

**Issue by meccup** [opentx/opentx#6523]
Hey @3djc, I'm testing now X Lite Pro. Looks like there might be a bug similar to this one: https://github.com/opentx/opentx/issues/6509

Effectively I cannot move cursor. I can switch pages with left/right stick movements, but up/down stick input does not work, cursor stays on the same field.

**Comment by 3djc** [comment]
What script are you testing with ? I think I’ll do a specific script to test those things

**Comment by meccup** [comment]
That was Betaflight scripts.

I've tried wizard script, looks like up button is working, but down is not.

In Betaflight lua, neither up now down works.

**Comment by 3djc** [comment]
Found the issue for down, will push a fix. The BF scripts might need to be updated however

**Comment by 3djc** [comment]
What action are up/down supposed to perform in BF scripts ?

**Comment by meccup** [comment]
Yep, I can confirm N31 fixes the issue. I can now move cursor in the BF lua script. Thank you.

Up/Down keys are moving cursor from one field (betaflight config, PID, VTX etc) to another.

One thing I cannot figure out how to do in X Lite Pro is display switching. I set up two display for a model, one for BF lua, another one for telemetry. I can launch BF lua by long press down (little stick), but then whatever I do, it does not switch to my second display which is telemetry display.

**Comment by meccup** [comment]
Haha, just found this: https://www.youtube.com/watch?v=lXCcg2S3_RE

You need to hold right button and use joystick to switch telemetry screens/displays.

**Comment by 3djc** [comment]
shift + long left/right
