### ISSUE TITLE
Multiprotocol FlySky

### ISSUE THREAD

**Issue by BergshamraFraggel** [opentx/opentx#6526]
OpenTX 2.2.3 Taranis X9D
FlySky 9X9 protocols are 8 channel protocols but OpenTX seems to send 16 channels and the parameter cannot be changed.
The signal "spill over" between the channels of the receiver, while the control channel 5 reacts Channel 4 in certain situations.
It looks like all protocols except DSM are locked to 16 channels, even the FrSky D16 8ch.
![screenshot_x9d_19-06-27_15-14-54](https://user-images.githubusercontent.com/17248147/60277929-d1c56300-98fe-11e9-8385-c4f88cecf576.png)
![screenshot_x9d_19-06-27_15-17-44](https://user-images.githubusercontent.com/17248147/60277930-d1c56300-98fe-11e9-9e0f-956e638187ae.png)
![screenshot_x9d_19-06-27_15-18-43](https://user-images.githubusercontent.com/17248147/60277933-d1c56300-98fe-11e9-8726-a8fe29756676.png)
![screenshot_x9d_19-06-27_15-19-47](https://user-images.githubusercontent.com/17248147/60277934-d1c56300-98fe-11e9-9ccf-90a12a07dbd6.png)

**Comment by kilrah** [comment]
AFAIK the Multiprotocol module is supposed to do the job of sending out over RF what's appropriate for each protocol, like it does remapping and special functions. The data frame to the multi always contains 16 channels, so even if we "were not sending them" they would still be passed, just as neutrals.

**Comment by BergshamraFraggel** [comment]
Okey....
Why does the same module work with that receiver if I turn the module knob to position 1 and set the radio to PPM ch 1 - 8 ??

**Comment by kilrah** [comment]
No idea, would have to look at the module code. But in PPM things are completely different, there if 8 channels are sent from the radio the module only gets 8. Serial is always 16.

On some protocols the "option" can tell the module how many channels to send, you could try playing with that in "Custom" mode to see if it's the case there.

**Comment by BergshamraFraggel** [comment]
If I had the opportunity to change the settings to ch 1-8 in the same way as for DSM, it would probably solve the problem too!
But it is perhaps easier for you to explain how I set the parameters to use customs settings ??
What are the values of FlySky 9X9 ??

**Comment by kilrah** [comment]
No, most likely not.

Values for Custom are in the multiprotocol documentation.
