### ISSUE TITLE
companion V2.30 N35 missing Symbols

### ISSUE THREAD

**Issue by hrenz** [opentx/opentx#6531]
Companion V2.3.0 N35   SDCard V0019  Win 7 Prof 32bit

Missing Symbols, its works, but have no symbols
![2019-06-29_153158](https://user-images.githubusercontent.com/6217896/60385101-eda74100-9a85-11e9-8982-ae94dfe20190.jpg)

![2019-06-29_165300](https://user-images.githubusercontent.com/6217896/60385865-978acb80-9a8e-11e9-8833-b5bb9e4d6492.jpg)

Tested
Companion V2.30 new installed, uninstalled, installed again
allways the same

Companion V2.2.3 is installed too and its ok,

**Comment by 3djc** [comment]
Fix didn't work as planed in N36
