### ISSUE TITLE
2.3.0N35 Switches SC and up not working on XLITE Pro in companion

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#6533]
Create a new model, select any place where you can choose a physical switch as source (I tested on flightmodes and inputs). SA and SB get 'autoselected' on moving. Switch SC and up not.

If selecting manually or by companion, the switch doesn't have any effect on the function it is used on on the radio (through the sim).

**Comment by lshems** [comment]
Checked hardware definition, is ok. 

Don't know where to find the raw input ADC values, page seem to be gone, so can't check there.

**Comment by lshems** [comment]
I can't confirm radio side issues but they could well be there. If so I think it is important to label radio as well on this bug.

If it is on the radio as well, this is going to crash planes, as people are using the nightlies as there is nothing else.

**Comment by 3djc** [comment]
If I added companion, it is because I checked on the radio

**Comment by pmackenzie** [comment]
Might be related, but I found that SD↑ does not work in logical switches in Companion, but !SD↓ does. See attached image.  It does work correctly on the radio (X9 lite)
SD down position is processed correctly by the same logical switches ( First on, last two off when SD is down)

**Comment by pmackenzie** [comment]
Couldn't upload the file, here is a link to the image on RCG

https://static.rcgroups.net/forums/attachments/1/4/1/9/9/a12251445-90-sd%20problem.jpg
