### ISSUE TITLE
X Lite pro external Modul Crossfire

### ISSUE THREAD

**Issue by Piu1992** [opentx/opentx#6534]
Hello 
On the releas OpenTX at FrSky for the x lite pro is Crossfire not there but in the last nightly version it should be there that you can use Crossfire? The Nightly SD Card content contains Crossfire but after the update to nightly I am missing the choice of the external modules Crossfire ... is this a mistake? Will it officially be possible to use Crossfire even with a real opentx version? 
best regards

**Comment by 3djc** [comment]
This place is to track OpenTX bugs,,  not sure you are mentionning one. OpenTX nightly do support corssfire if you select that option in companion, however whether your radio PMU allows the module to run must be asked to FrSky, nothing to do with OpenTX
