### ISSUE TITLE
GVAR won't Increment/Decrement in steps smaller than MIN value

### ISSUE THREAD

**Issue by xoedusk** [opentx/opentx#6535]
**Describe the bug**
The Special Function "Adjust GVx > Increment" does not allow me to input an INCREMENT value that is lower than the manually-set minimum value of the Global Variable. Example, if I set up a Global Variable with a minimum of 40 and maximum of 150, the lowest increment value I can enter is 40. I want small steps, even negative steps, but I cannot do it.

**To Reproduce**
1. Create a Global Variable with min 40 and max 150
2. Create a Special Function using any switch, select Adjust GV# (newly created G.V.), then select Increment.
3. Try to enter an increment value less than 40, such as 2. It will revert back to the minimum value of 40.

**Expected behavior**
I should be able to enter any increment number I want, even negative, so long as its absolute value doesn't exceed some reasonable "range"

**Screenshots**

Defining the GVAR:

![Screen Shot 2019-06-30 at 1 08 53 PM](https://user-images.githubusercontent.com/2566738/60401634-7f23bb00-9b39-11e9-8bfb-6b11085257af.png)

Selecting Increment:

![Screen Shot 2019-06-30 at 1 13 41 PM](https://user-images.githubusercontent.com/2566738/60401641-88148c80-9b39-11e9-83ce-e34a18a8d522.png)

About to click out of the textbox to set an increment of 30:

![Screen Shot 2019-06-30 at 1 18 28 PM](https://user-images.githubusercontent.com/2566738/60401654-b1351d00-9b39-11e9-8939-113cde975f63.png)

But it reverts back to 40:

![Screen Shot 2019-06-30 at 1 18 35 PM](https://user-images.githubusercontent.com/2566738/60401657-b98d5800-9b39-11e9-86bc-725e66cd7634.png)

**General information**
 - OpenTX version 2.2.3
 - Hardware X10S
 - OpenTX Companion 2.2.3 on MacOS

**Comment by elecpower** [comment]
Fixed in 2.2.4 and 2.3

**Comment by 3djc** [comment]
👍
