### ISSUE TITLE
companion 2.3.0N38 x9d+ firmware download error

### ISSUE THREAD

**Issue by IllusionFpv** [opentx/opentx#6543]
Isn't x9d+ ready for opentx 2.3 nightlies? When I try to download the radio firmware I get this error:
![Screenshot 2019-07-04 19 31 52](https://user-images.githubusercontent.com/25136267/60687085-9e5d7800-9eac-11e9-8191-070ae5395e77.png)

**Comment by kilrah** [comment]
2.3 nightlies are currently only available for radios with 128x64px screens.
