### ISSUE TITLE
Companion/radio 2.3.0N35 view textfile crashes radio

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#6544]
couldn't test on 38.

opening a text file for view through SDcard file browser (scripts/telemetry/readme.txt for example) will trigger an uptrim switch event, causing trim on elevator to go full up and hang the GUI.

**Comment by 3djc** [comment]
More details please ? Tested on companion simu and T12 radio, seems to be ok

**Comment by lshems** [comment]
Sorry, didn't mention radio: XLite pro
