### ISSUE TITLE
SD Sync: Which is Source? Which is Destination?

### ISSUE THREAD

**Issue by MikeNH** [opentx/opentx#6545]
*Before submitting,  search the open issue if there is already a report of the bug*
Didn't find existing bug report.

**Describe the bug**
I am attempting to sync from the radio to Companion. I didn't want to overwrite files by making the wrong choice. The dialog is unclear which is Source and which is Dialog.

**To Reproduce**
1 - Open OpenTX Companion
2 - Menu File >>Synchronize SD
3 - In the "Sync. Direction" drop down list, try to guess which choice is Source and which is Destination.

**Expected behavior**
Change labels from "Local Folder" to "Source Folder" or the appropriate identification.

**Screenshots**
![SyncDialog](https://user-images.githubusercontent.com/16496376/60693164-280a4700-9ea7-11e9-9df0-5e8281c4426f.jpg)

**General information**
 - OpenTX version 2.3.0N37
 - Hardware (e.g. Frsky X-Lite  Pro)
 - OpenTX Companion 2.3.0N37 on Windows 10

**Comment by 3djc** [comment]
Duplicate #6490
