### ISSUE TITLE
attempt to index field '?' Error in new model creation

### ISSUE THREAD

**Issue by hursto75** [opentx/opentx#6549]
I have seen More than one person with this problem.

When creating a glider with the wizard if you select NO motor, when trying to create the model you get  "attempt to index field '?' (a nil value)"

**General information**
 - OpenTX 2.2.3
 - Hardware X12s
![20190705_225518 (1)](https://user-images.githubusercontent.com/3580226/60750880-adabf680-9f7c-11e9-8bb7-66f70fbc012f.jpg)

**Comment by 3djc** [comment]
This was fixed on Jan 8th for 2.2.4. People who need that fix earlier can replace the lua wizard file from either the git server, or a nightly, like 2.2V0020 (only take the wizard file if you do not want to have a version warning)
