### ISSUE TITLE
Nightly Warning Removal (opion)

### ISSUE THREAD

**Issue by robthomson** [opentx/opentx#6553]
When using 'nightly' version of the firmware... on startup you get a prompt to 'warn' you that the firmware is not safe.

I totally get the reason why this is the case - but it can also be rather annoying in certain scenario.

e.g.  I would like to use the 2.2 branch with vario support via csrf

This means I have to use a nightly.

It would be good to have an option to turn this off at own risk.

Either via a 'companion' check box.. or an option on the radio - maybe buried away in the system menu somewhere.

**Comment by kilrah** [comment]
We have discussed it and decided not to implement, the warning is there for a reason, and skipping it is not the end of the world..

**Comment by shamufpv** [comment]
The latest nightly did not give me a warning screen. Everything seems to be working though. Should I be concerned?

**Comment by 3djc** [comment]
You probably have an RC that does not trugger the warniing. please check your exact version in radio/version screen
