### ISSUE TITLE
2.3N40 companion S1 pot not selectable as volume input in special function X9-Lite

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#6554]
Title says it all.

**Comment by kilrah** [comment]
Can't reproduce. Check your S1 is actually enabled in hardware settings.

![Clipboard01](https://user-images.githubusercontent.com/6065069/60828325-66a74680-a1b2-11e9-8929-3168985f00ec.jpg)

**Comment by lshems** [comment]
Ah, really stupid from my side. I had it on S2, so after conversion it got missing. I was looking for the first item on the line to be selectable as S1, and not the third.

My bad.
