### ISSUE TITLE
Support of more 3 position switch on 9XR Pro

### ISSUE THREAD

**Issue by dadantsou** [opentx/opentx#6560]
Hi all,

@kilrah already mentionned in this [issue ](https://github.com/opentx/opentx/issues/6282) that "A rework of the switch handling is planned that will make this possible, but we have no ETA for it."

But is there any update about this? 'cause I like so much using OpenTx rather than erskyTx on my old 9XR Pro.

Thanks for your reply and your great work.

Cheers!

**Comment by 3djc** [comment]
Probably for 2.4
