### ISSUE TITLE
sportTelemetryPop() unpredictable result when value is bigger than 67108860

### ISSUE THREAD

**Issue by dgatf** [opentx/opentx#6565]
Using opentx 2.2.3, X7 - Lua scripts

sportTelemetryPop() packets with values bigger than 67108860 produces unpredictable results. The highest byte of the packet is unusable

**Comment by bsongis** [comment]
ah oui t'as raison, bizarre, j'espère qu'on n'a pas quelque chose sur 24 bits

**Comment by kilrah** [comment]
More data needed. What are you using as source? 
There are scripts like ardupilot data displays that transfer non-numeric data over all bytes and work just fine...

**Comment by raphaelcoeffic** [comment]
@dgatf we need more input, and something to reproduce, as it works for others.

**Comment by dgatf** [comment]
Sorry for taking a while to answer

I've tested on opentx 2.3 an I can't reproduce it. It must has been an error on my side. There is no issue for any value

FYI is for this project [https://github.com/dgatf/msrc](url)

Thanks
