### ISSUE TITLE
Less ram available for LUA scripts on X9D than for X7

### ISSUE THREAD

**Issue by m-rik-prog** [opentx/opentx#6568]
I have an application that I've managed to reduce to a minimum and compress so that the same precompiled application (.luac) can work not only on the Horus X12 & X10 but also on the Taranis X7 (even more than once since after the first run it was no longer working the second time because it obviously leaves some areas of RAM occupied and does not free them all and I had to compress further giving up some functions).

However, on the Taranis X9D it doesn't run even on the first run and the message of insufficient memory appears. Note: it runs perfectly with the emulator that uses the ram of the PC.

Is there a possibility to free up some RAM by modifying the system configuration in order to deactivate some function that occupies more RAM on the Taranis X9D than on the Taranis X7?
(unfortunately more than that I can't compress the application that has 14 pages to modify more than 300 parameters).

**Comment by 3djc** [comment]
x7 has more ram because the screen resolution is smaller, and yes, ram is an issue on taranis,  there is some gain that can be made using luac, but overall, everything that can be done has been done already

There are way, like making the scripts modular and load only when needed that can help with it

**Comment by m-rik-prog** [comment]
Sidenote: X7 also lacks some code. For example, when an insufficient memory error is generated by running a too big LUA script, the message "Not enough memory" that appears on the X9D does not appear on the X7 screen, which simply does not run the lua/luac code, but don't give to the user any info about the cause/problem. But I don't think this can affects the RAM space but only the ROM space.

**Comment by bsongis** [comment]
> because it obviously leaves some areas of RAM occupied and does not free them all

are you sure, isn't it only RAM fragmentation?

**Comment by lshems** [comment]
@m-rik-prog

Check my blog on rcgroups. It might give some ideas
