### ISSUE TITLE
Function to save a screenshot using a transmitter switch (X12S).

### ISSUE THREAD

**Issue by m-rik-prog** [opentx/opentx#6569]
In order to generate complete instructions / documentation for a Lua application, I am using the screenshots of the emulator. But with the emulator it is not possible to display the values received by the LUA application from the Smart Port.
It would be useful to implement a global function to save the screen image by using a dedicated switch for this purpose. Almost all transmitters on the market already have this function. Instead, even with the latest version 2.2.4 of OpenTX for the flagship X12S this function does not seem to have been implemented and working yet.
Will it be implemented in the future? When? Or is there a method I haven't discovered yet?
Thanks.

**Comment by 3djc** [comment]
Not currently available.

Duplicate ##3393
