### ISSUE TITLE
sportTelemetryPop() always returns nil

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#6572]
FW: opentx-x7
VERS: 2.2.3 (ae5ac05b)
TX: Taranis QX7
RX: X8R
Sensor: custom sensor sending data IDs 0x5200 and 0x5201 with frame ID 0x10

I can see the sensor data (IDs 0x5200 and 0x5201) being constantly updated on Taranis telemetry page in menu. However, when I want to use sportTelemetryPop() in a LUA script, I always receive nil for the 4 outputs of the function. Here is a very simple script that I am running:

 _local function run(e)
  -- Prepare to extract SPort data
  -- if not open, open the file for packets storage
  lcd.clear()
  -- get packets from queue
  local sensorID,frameID,dataID,value = sportTelemetryPop()
  lcd.drawText(0,0,"Sniffer:",SMLSIZE)
  lcd.drawText(10,10,tostring(dataID)..";"..tostring(value),SMLSIZE)
end
return{run=run}_

at the lua telemetry screen, I always get: nil;nil
Please help.

**Comment by kilrah** [comment]
sportTelemetryPop() is not for use with normal sensors, only with the IDs that bypass the whole sensor system and go straight to Lua (0x5000-0x50FF).
