### ISSUE TITLE
Flex auto power range limited to 100mW-1W

### ISSUE THREAD

**Issue by laurentopia** [opentx/opentx#6575]
**Describe the bug**
When you set the power to 1W, power is switched automatically to maintain quality signal. The range of a flex R9 is 10mW-1W but the current flex autoswitch is 100mW-1W

**To Reproduce**
flash R9 with flex
set openTX to flex
set power to 1W
power switches lowest is 100mW

**Expected behavior**
power switches from as low as 10mW

**General information**
 - OpenTX version 2.2
 - Hardware : R9m on qx7
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by 3djc** [comment]
OpenTX does not control at all the power changes that are fully decided by the module itself. Please contact FrSky if you believe their firmware does have an issue
