### ISSUE TITLE
External module powered while loading on X-Lite Pro 

### ISSUE THREAD

**Issue by Tim2309** [opentx/opentx#6576]
I hope this is a OpenTX related problem.
My full Crossfire TX is powered if I plug in USB for loading. Is it a bug or a hardware problem?
After loading finished the module is still powered and I think (not sure) the module will discharge the x-lite pro until I remove the cable.

**Comment by kilrah** [comment]
That is not OpenTX-related, this is due to a(nother) issue with the "PMU" FrSky has added to these radios.

**Comment by Talha909** [comment]
I have the same issue and write down the email to frysky.  They sent the update file of PMU.  I have installed the update and after that this issue resolve.

**Comment by Tim2309** [comment]
Last week they send me this in an email:
„There is an issue of the radios powering modules when the USB or charge circuit is live. I do not believe there is a fix just yet. Please remove modules when charging the radio. I know it is inconvenient at the moment, and hopefully will be addressed soon.“

Can you share the file with us?

**Comment by Talha909** [comment]
Sure. I will share the file. I have the same issue . But after update this issue resolve. Please give me your email address. I will send you the file.

**Comment by Tim2309** [comment]
Please send it to tim(at)phaea.de
Thank you

**Comment by Talha909** [comment]
I have attached the file over here. Please check. file name is autoupdate.zip. I have zip file and upload it.
https://www.rcgroups.com/forums/showthread.php?3080337-FrSky-New-Taranis-X-Lite-S-and-Pro-X9-Lite-R9M-Lite-and-Pro-MPM-Lite/page194
[autoupdate.zip](https://github.com/opentx/opentx/files/3426716/autoupdate.zip)

**Comment by Tim2309** [comment]
Thank you for sharing, now it works :)
