### ISSUE TITLE
Betaflight LUA - no telemetry

### ISSUE THREAD

**Issue by Tim2309** [opentx/opentx#6580]
I use the X-Lite Pro with the full crossfire module and opentx 2.3 nightly, telemetry works well, but the BF LUA doesn't show values and says no telemetry.

With my X10S on opened 2.2 all was fine and the LUA worked with the same quad.

**Comment by 3djc** [comment]
Well, we have reports suggesting BF scripts do run fine  with 2.3N and Xlite Pro, so that looks linked to XFire. We have asked for XFire gear, but we don't have that yet, so it may be some time before we can effectively help

**Comment by Tim2309** [comment]
ok no problem, btw the crossfire lua work without problems

**Comment by 3djc** [comment]
Even stranger !

**Comment by Tim2309** [comment]
anything I can do for testing?

**Comment by kilrah** [comment]
Is your XF up to date? Believe they released an update recently.

**Comment by Tim2309** [comment]
It’s on 3.00

**Comment by dmanzevel** [comment]
Hello , having the same issue with X9 Lite  (I guess the X-Lite pro , in the same development stage), on latest nightly today, N55
tested with crsf and with D16, the crsf sends telemetry but the BF lua script is not working
the D16(XSR) , not telemetry, and no lua script, verified that the BF lua and telemetry is working on this quad with X9D 2.2.3

is the telemetry and lua working on other radios on nightly ?
is there any way I can help? test something?

**Comment by 3djc** [comment]
Not sure I understand. The crsf part I understand.

The D16 as me confused, Are you saying that in D16 mode, your X9 Lite has no telemetry at all and that the LUA scripts do not work ?

**Comment by dmanzevel** [comment]
yes, on X9 Lite with D16 mode there is no sensors on telemetry screen, and the BF LUA script is not working

**Comment by Hawxxer** [comment]
Same Problem X-Lite Pro + 2.3.0N58. What is xfire? The Kiss Lua Script is working fine, but Betaflight lua script is not.
Sidenote:
Updating the crossfire transmitter is not working in 2.3.0N55 dont know about the newest nightly. When I press binding, the Script shows if the Transmitter should be updated, but when pressing Enter nothing happens.

**Comment by 3djc** [comment]
Issue replicated here, will  be working on it this week
