### ISSUE TITLE
X-Lite Pro with OTX 2.3.0N50. S1 and S2 Pot no response.

### ISSUE THREAD

**Issue by LOVECHEN** [opentx/opentx#6585]
Describe the bug
X-Lite Pro with OTX 2.3.0N50. S1 and S2 Pot no response.

To Reproduce

Power up X-Lite Pro.
Move S1 and S2 pot watching status bar same time.

General information

OpenTX version 2.3.0N50
Hardware X-Lite Pro
OpenTX Companion 2.3

**Comment by bsongis** [comment]
Strange I just flashed it, and it works. Next nightly will come in 2 hours, please confirm if there is still an issue

**Comment by kilrah** [comment]
Make sure they are not set to "None" in the Radio setup hardware page, and have been calibrated properly.

**Comment by drewzh** [comment]
Fresh install of OpenTx on my X-Lite Pro also gives me non working S1 and S2. The only hardware config option that results in movement is 'multipos'. Is this correct or should they be 'pot'?

**Comment by 3djc** [comment]
Set then as pot and redo calibration (they need to be moved during calibration too)

**Comment by drewzh** [comment]
Thanks @3djc, that solved my issues. First time flashing my X-Lite 👍

**Comment by LOVECHEN** [comment]
Thanks @bsongis @3djc ,problem solved.
