### ISSUE TITLE
Spectrum Analyzer and Power for Fr Sky Taranis X9Plus

### ISSUE THREAD

**Issue by ThePhantom05** [opentx/opentx#6587]
Please add the function Spectrum Analyzer and Power Meter in AK Sky Taranis x9D Plus. I as a user and really need this feature.

**Comment by 3djc** [comment]
This feature is supported by FrSky only on new ACCESS hardware (and spectrum not even on all new radios). There is nothing that can be done on OpenTx side to add that

**Comment by ThePhantom05** [comment]
Спасибо) За информацию. Значит придется делать своими руками.
