### ISSUE TITLE
X-Lite conversion from 2.2.4N706 to 2.3.0N54 changed setup

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6590]
FYI

Yesterday I tested an upgrade from 2.2.4N706 to the 2.3.0N54.
Upon startup the X-Lite started to convert the setup.
I then noticed that of at least my default model the setup has changed.

The flight modes were assigned totally different switches than on the original model.
I have not investigated other changes yet.

Please close this ticket if conversion errors should be expected at this stage of development.
I will close this ticket if there is no further interest.

I have an otx of before and after the conversion.
I can post those upon request.

![2 2 4N706](https://user-images.githubusercontent.com/39838998/62003523-92b24980-b118-11e9-9e99-04164f044856.JPG)
![2 3 0N54](https://user-images.githubusercontent.com/39838998/62003526-980f9400-b118-11e9-985c-f4968f19ae9d.JPG)

**Comment by 3djc** [comment]
Yes please share your 'before' otx, this should not happen at this stage

**Comment by notlebowski** [comment]
[OTX.zip](https://github.com/opentx/opentx/files/3438928/OTX.zip)

**Comment by notlebowski** [comment]
During upgrading the X-Lite was close to unreadable.
I quickly took this picture in case it could be useful.

![2019-07-27 20 23 17](https://user-images.githubusercontent.com/39838998/62003742-d2c6fb80-b11b-11e9-94ee-9a9619430d85.jpg)

This afternoon I will downgrade my X-Lite, reload last week's setup and migrate again.

I forgot to mention I am also running Mike Blandford's Ersky9x's bootloader.
AFAIK this could have no bearing on this issue, but I'm not sure of that either.
If the outcome of the corrupted setup will be the same this afternoon I will also do a cold flash of the 2.2.4, load the model and upgrade to 2.3

**Comment by 3djc** [comment]
Reproduced (but not the display issue)

![image](https://user-images.githubusercontent.com/5167938/62004902-9ef3d200-b12b-11e9-8095-644cd8e8e089.png)

**Comment by kilrah** [comment]
So is the conversion error only in companion or did you also have it on the radio?

The screen isue is normal, during conversion your custom contrast setting isn't available so a default is used, and that defaut will be either good of bad depending on the radio.

**Comment by 3djc** [comment]
Confirmed doing the conversion on radio (rel 2.2.4 to 2.3N54)

**Comment by notlebowski** [comment]
I only did the conversion on the radio....

I wanted to reproduce it now, but now it has been confirmed by 3djc there's no need, I guess.
I'm assured you will find the culprit soon.

**Comment by notlebowski** [comment]
My 2.2.4 setup was from last week, so I needed to reconstruct my 2.2.4 setup, so they now had the same subtrims and curves.
After that I did a "setup compare" and I noticed some more differences which may not be reflected in the new upgrade.

The RSSI-critical value (which I never touch) has suddenly changed from 33 to 42
The Top Bar settings were lost

![telemetry-changed-RSSI](https://user-images.githubusercontent.com/39838998/62010066-40981500-b166-11e9-9b43-150cd9cbad34.JPG)

The instances changed in sensors.
![sensors](https://user-images.githubusercontent.com/39838998/62010086-63c2c480-b166-11e9-8cd4-9e76a6bf401a.JPG)

I named my SC-switch "Act" (for Action).
The "Ac" and "t" were then assigned to SB-switch and SC-switch
![radio-setting-original](https://user-images.githubusercontent.com/39838998/62010104-a6849c80-b166-11e9-9dfa-9fd1917cfd43.JPG)

![radio-setting-converted](https://user-images.githubusercontent.com/39838998/62010105-ab495080-b166-11e9-99e5-97062d27b5ab.JPG)

**Comment by 3djc** [comment]
The RSSI critical in your otx is set to 33 for 2.2.4, and I have 33 on 2.3.0 radio, but 42 in companion, so companion issue

The Act seems to be a companion issue too, will follow up, as the radio is ok

![image](https://user-images.githubusercontent.com/5167938/62010874-d6d13880-b170-11e9-9875-8159adfffc1f.png)

**Comment by notlebowski** [comment]
Ah, ok.
I did not check that. It was terrible weather today for flying, but it was great for watching the GP F1 in Hockenheim.
