### ISSUE TITLE
Companion 2.3 issues

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#6592]
EEprom (xlite):

[eeprom-2000-01-30-085816.zip](https://github.com/opentx/opentx/files/3439423/eeprom-2000-01-30-085816.zip)

Issues : RSSI critical display 42 instead of 33
Hardware switch name for SC split in 2 (Ac and t)
RSSI source need to be chhecked too

**Comment by lucifergeo** [comment]
This also applies for the X9-Lite.
both RSSI warning level are reset when importing/exporting Modells between companion and TX

**Comment by notlebowski** [comment]
When I read models now, with radio upgraded to N61 I have a lot of empty lines in SF and probably much more is wrong

X-Lite classic

**Comment by raphaelcoeffic** [comment]
@3djc with the changes in #6625, your eeprom works for me properly (tried with simu / companion).

**Comment by raphaelcoeffic** [comment]
seems the special functions are still messed up:
<img width="714" alt="Screen Shot 2019-08-14 at 10 40 03" src="https://user-images.githubusercontent.com/1050031/63006944-fca05200-be7f-11e9-80a3-a557dd8ae2be.png">

**Comment by raphaelcoeffic** [comment]
@3djc seems all the switches were affected. Xlite uses a number of switches in the storage different from what it has in reality (probably because of compatibility with X-lite S/Pro?).

**Comment by 3djc** [comment]
yes, most radio do that in 2.3, there is a NUM_SWITCHES and STORAGE_NUM_SWITCHES

**Comment by notlebowski** [comment]
I just tested 2.3N62
The setup is still messed up if I read the radio with Companion.
The radio is still running N61 though.

Are these changes not yet in there or could it still be wrong?
It's a classic X-Lite

**Comment by kilrah** [comment]
N62 is from the 13th, this was merged in on the 14th.
Seems the build hasn't run.
