### ISSUE TITLE
horus 12s and horus 10---8.3 filename in special functions 

### ISSUE THREAD

**Issue by tj51** [opentx/opentx#6598]
if you go to System and find a mp3 with long filename, right click and play, it plays, go to model, special functions try to play track, go to the sound field and list the sounds, the long filename is missing out of the list, this function is in 8.3 mode not in ling file name mode, this is a problem, it works correctly on my tranis transmitter, but broken in Horus, I own a 12s, my friend owns a 10 and the same on both  horus's

**Comment by 3djc** [comment]
This is working as intended, the storage for filenames is limited, and is different on Horus because Horus allows several extensions

**Comment by tj51** [comment]
in the system, sound the are about 25 characters in the file name, in the special functions the are only 8, this has nothing to do the the file extension to the right of the file name like .mp3 .wav, please expand the special function characters to match the system sound characters

**Comment by kilrah** [comment]
System sounds are hardcoded in the firmware, so they can be any length without implication. 
User sounds must have their names stored in model memory.

**Comment by 3djc** [comment]
And also, for the sake of precision, it is not 8, it is 6
