### ISSUE TITLE
Cosmetic minor glitches in Companion's compare

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6602]
Only after creating the screenshots and preparing this ticket I noticed that the glitches would disappear after resizing the window.
I decided to post them anyhow and leave it up to you.

![companion-compare1](https://user-images.githubusercontent.com/39838998/62421600-d242dd80-b6a4-11e9-984c-5c061b053124.JPG)

![companion-compare2](https://user-images.githubusercontent.com/39838998/62421601-d7079180-b6a4-11e9-8a42-2e6c3a08c877.JPG)

BTW I needed to create this ticket with Firefox as the Github site failes when I do the same with Chrome. I normally have no problem to drag/drop images in a Github-ticket.

**Comment by elecpower** [comment]
Wrapping bugs are in the currently supported 5.7 version of QT libraries. Resizing the form fixes/causes the observed results. Not much can be done in Companion to fix without likely causing other side effects. Need to keep open and retest when supported QT version is updated.
