### ISSUE TITLE
XLite Pro Bars telemetry screen broken

### ISSUE THREAD

**Issue by MikeNH** [opentx/opentx#6603]
**Describe the bug**
Taranis Xlite Pro and Companion cannot get more than 1 custom telemetry screen to present itself. This the same behavior for XLite Pro and OpenTX Companion Simulator. 

I've seen this behavior for many nightly releases and am surprised that I haven''t seen this on RC Groups or as an open issue.

**To Reproduce**
1. Using Companion (but also is seen on the radio), create a new multicopter model and accept all defaults.
2. Open new model and go to Telemetry tab.
3. Scroll down to the bottom and on Telemetry screen 1, for Custom Screen Type drop-down, choose Numbers. From dropdown, choose Batt.
4. Telemetry screen 2, for Custom Screen Type drop-down, choose Bars. From dropdown, choose Batt.
5. Click Simulate
6. On Simulator, long-press the page down button to display 1st custom screen. 
7. On Simulator, hold down the "s" (shift) key and at the same time, click the left or right page button.
At various times the screen will flicker both on the radio and on Companion indicating an attempt to display screen 2 but the next configured never displays.

**Expected behavior**
Custom telemetry screens 2,3 and 4 should display if configured.

**Screenshots**

**General information**
 - OpenTX version2.3.0N58
 - Hardware XLite Pro
 - OpenTX Companion Windows 10

**Comment by kilrah** [comment]
Wrong issue description, it's not that you can't change screen, it's that the "Bars" screens are broken. If your 2nd screen is Nums it switches fine, and if you select only one screen that is Bars you et "no telemetry screens".

**Comment by kilrah** [comment]
Scratch that, it's all working correctly. Looks like you forgot to set the min and max values for the bar.

**Comment by MikeNH** [comment]
Sorry but the problem exists as an example when screen 1 & 2 are set for numbers and both use the "thr" parameter. Only the first screen appears and correctly reflects the throttle setting. No min/max settings required.

The title of this bug has been changed to "Bars" when, in fact, the problem exists in all cases; numbers, bars and scripts (but the scripts that I have may need attention).

**Comment by kilrah** [comment]
Works just fine here. You do know the left/right press is a long press, right?
