### ISSUE TITLE
X9 lite, internal module not saving settings when switching between modes.

### ISSUE THREAD

**Issue by P-I-Engineer** [opentx/opentx#6604]
2 issues in setup page

D16 failsafe setting not retained.
when set to D16 mode and f/s is set to something other than "not set". If mode is changed to Access and then back to D16 it will revert to failsafe "not set"

Access bind and f/s not retained.
register then bind rx in access mode. If mode changed to D16 and then back to Access bind is lost and you must rebind. Same issue as D16 for failsafe

**Expected behavior**
settings should be retained

**General information**
 - OpenTX version 2.3 N58
 - Hardware X9 lite
 - OpenTX Companion 2.3.0N58

**Comment by kilrah** [comment]
That is normal, changing mode resets everything and starts fresh. You don't switch back and forth between modes within a given model, so it makes no sense to waste memory storing both.
