### ISSUE TITLE
Companion 2.3.0N58 - Open .otx from 2.2.4 Horus X10s to convert in a new in X-Lite S Profie chrash

### ISSUE THREAD

**Issue by SnappyFPV** [opentx/opentx#6605]
I did save this Model Config .otx in 2.2.4 from my X10S to convert a model to my X-Lite S in 2.3.0N58  after the Message Box confirm the Companion App chrash and close.

[Test.zip](https://github.com/opentx/opentx/files/3474001/Test.zip)
![message1](https://user-images.githubusercontent.com/6499781/62573968-9de34300-b897-11e9-8d94-e99e4512e9a6.jpg)

 - OpenTX Companion 2.3.0N58

**Comment by 3djc** [comment]
While xlite are supported, Horus aren’t currently supported in 2.3

**Comment by SnappyFPV** [comment]
So no chance to convert model at the moment?

**Comment by kilrah** [comment]
Not for Horus. There is nothing you could do with it anyway since Horus 2.3 is far from being usable in the first place and will just crash on you.

**Comment by SnappyFPV** [comment]
Thanks - will do it from hand

**Comment by 3djc** [comment]
Only between currently supported models

**Comment by kilrah** [comment]
What you do from hand is not guaranteed to work without restarting from scratch once we start providing builds, and again **you should not use 2.3 for Horus for anything at this point**.
