### ISSUE TITLE
Upgrading from OpenTx 1.1.02 to 2.2

### ISSUE THREAD

**Issue by MachuFrey** [opentx/opentx#6609]
I'm having issues updating my Taranis to the latest version of OpenTX. The unit had been unused for several years (had a baby). Would like to upgrade but since it's the oldest version, it won't go into bootloader via the receiver and when I try to push it through the companion software I get errors about firmware being out of date.

**Comment by kilrah** [comment]
This is a bug tracker, not a support platform.

You will need to dig the old instructions for flashing via dfu/zadig if on Windows and upgrade step by step if you care about your model setups (still not guaranteed they won't get mangled through 6 years of changes so you might want to start fresh).
