### ISSUE TITLE
Invalid Logfile: X9Lite ( 2.3.0N61)

### ISSUE THREAD

**Issue by r41065** [opentx/opentx#6612]
Trying to open logfiles with Companion internal LogView 
i get always an Error message:
" The selected Logfile contains xxxx invalid lines out of xxxxtotal lines "

![11-08-2019](https://user-images.githubusercontent.com/15220072/62837385-14ed5280-bc6f-11e9-9067-5442d216b535.JPG)

openingthe .csv file for example with libre office it looks OK at the first view.

opening with a textbrowser i found out that the headline doesn't match to the number of Colums:
extract from Headline:
RxBt(V),Rud,Ele,Thr,Ail,S1,SA,SB,**SC,SE,SF**,LSW,TxBat(V)
extract from example Line:
4.8,-3,-1,-1024,1,-2,0,-1,**-1,-1**,0xFFFFFFFF00000000,7.2

in Headline is missing switch SD:
 there are listed 3 switches SC, SE, SF:

in example line only listed the values of 2 switches ( i didn't find out which ones till now...) at same Position, Values from SA, SB and LSW seemed to be OK

The X9Lite doesnt have switch SF, so if i delete the text " SF, " in headline, will be able to open the Logfile without warning...

Ralf

ps. cant open Logfiles from X9Lite since the Frsky Version my TX was delivered with...

**Comment by r41065** [comment]
complete corrupted logfile:
[1RK_ACCESS-2019-08-11.zip](https://github.com/opentx/opentx/files/3490278/1RK_ACCESS-2019-08-11.zip)

**Comment by 3djc** [comment]
The fix for this is ready in PR #6611.
