### ISSUE TITLE
Custom RSSI settings seem to be forgotten when loaded from radio to Companion

### ISSUE THREAD

**Issue by petegee** [opentx/opentx#6615]
This for my XLite Pro.  I set a custom (eg not the default) RSSI warning and critical value (say 40 & 38 respectively) within the radio. Load them into 2.3 companion. Open that model, and the values reported have reverted to their default values (45 and 42 is it??). When saving back to radio, the are reverted in the radio too - the defaults are saved back.

I think this also happens for the RSSI Source on the telem screen.??

**Comment by 3djc** [comment]
Duplicate #6592

**Comment by lucifergeo** [comment]
This also applies for the X9-Lite.
both RSSI warning level are reset when importing/exporting Modells between companion and TX
