### ISSUE TITLE
Sensor calibration precision

### ISSUE THREAD

**Issue by sybu0** [opentx/opentx#6639]
Dear all, 
I have noticed a slight difference in the reading of Intensity ESCa  (NEURON 80)  and my measurement with a decent multimeter, and I wanted to add 4% to the measured value but I could only put a ratio of 1.1 because there is only one figure possible after the point.
Is it possible to have at least 2 figures after the point for the ratio value? it should be very helpful when a slight adjustment for sensor calibration is required.
Kind regards

**Comment by 3djc** [comment]
Not a bad idea, but it will require an eeprom change, so not before 2.4. To be noted, you can achieve that with a lua based sensor.
