### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by craigywsm** [opentx/opentx#6643]
This is not an issue but more of a feature request.
Would it be possible to when binding for the transmitter to show on the screen a successful bind showing the receiver model it bound to?

**Comment by 3djc** [comment]
receivers are bound to the radio (not models) using their rxnum. Any model using same rxnum will be bound to that receiver too (and rxnum duplicates are already shown), unless I'm misunderstanding your issue ?

**Comment by craigywsm** [comment]
Hi, thanks for the quick reply 3djc. Sorry i come from a non open tx background. 
Most receivers that get bound on other platforms will show on the radio once bound.
![Capture](https://user-images.githubusercontent.com/40343747/63250960-b0c92080-c264-11e9-91d6-bbb98408266d.PNG)
 ie does not show on the radio the receiver bound  at the point of the bind process.
hope this make sence

**Comment by 3djc** [comment]
Something like that exist for ACCESS receiver, but not for ACCST. Not sure how it would be managed tho, since you can rebind a receievr to another rxnum at any time, there is no way to know when that happens

**Comment by kilrah** [comment]
This is a feature of the unknown system you're using that allows the radio to know the receiver type. There is no such thing in whatever unknown RF system you're now using with OpenTX, so of course we can't show anything. 

FrSky ACCESS has something like that and sure enough you can see your receiver there.
