### ISSUE TITLE
Simulator Momentary switches always down on x-lite-pro. 

### ISSUE THREAD

**Issue by fabioeh** [opentx/opentx#6650]
**Describe the bug**
Mac Simulator Momentary switches always down on x-lite-pro.
SE and SF report down and do not go to the UP state.
Special Functions using the SE and SF trigger stuck on the down action.

**To Reproduce**
1. Setup a Special Functions to trigger a sound wave file on SE or SF down repeat every 5s..
2. Run the simulator.

**Expected behavior**
Play sound only when switch is down.

**Bug behavior**

Plays sound when switch SE and SF is in the up position.

**General information**
 - OpenTX version (2.3 or N66)
 - Hardware (Frsky X-Lite-Pro)
 - OpenTX Companion (2.3 or N66)

**Comment by bsongis** [comment]
@3djc would you mind checking on linux or windows? no reason it's different on MacOS

**Comment by fabioeh** [comment]
Same problem on Mac and PC

**Comment by raphaelcoeffic** [comment]
The issue was actually showing up on **any** momentary switch on **any** TX simulation.
