### ISSUE TITLE
Cant read models and settings

### ISSUE THREAD

**Issue by kaindub** [opentx/opentx#6654]
Radio Taranis X9 plus
Boot loader 2.2.3
Companion version 2.2.4
Windows 10

When I try to read models and settings i get this screen
![image](https://user-images.githubusercontent.com/54387636/63485427-b7ff6100-c4e6-11e9-92d7-ad8887f141fe.png)

When I revert to Companion 2.2.3 I am able to read models and settings

**Comment by 3djc** [comment]
Not sure I understand, you put a 2.2.3 screen with 9xr pro selected and you say your issue is 2.2.4 with x9d+ ?

**Comment by kaindub** [comment]
My radion is a Taranis X9d plus. It has Bootlaoder 2.2.3 loaded on it
The Open TX Companion that I have a problem with is version 2.2.4, which I was requested to download by Open Companion 
version 2.2.3 of Open companion has no issues for me

**Comment by 3djc** [comment]
You still haven't given any details as to what your problem is !

**Comment by kaindub** [comment]
When I try to read models and settings i get this screen
![image](https://user-images.githubusercontent.com/54387636/63489770-57782000-c4f6-11e9-91fe-31931916d088.png)

The models and settings do not load to the PC and the screen above  just stays

**Comment by 3djc** [comment]
But that screen doesn't come from 2.2.4 ! Could you take a screenshot of what actually happens using 2.2.4 ?

**Comment by kaindub** [comment]
Alright its not the screen from 2.2.4
But i dont know how to take a screen shot. But I can assure you that despite this being a screenshot from 2.2.3, This is what comes up for me except it says 2.2.4 on the title bar

**Comment by raphaelcoeffic** [comment]
@kaindub as it seems, the wrong radio profile is selected. Please select the right one (X9D+) and try again.

**Comment by 3djc** [comment]
Given he doesn't know how to take screenshots, we can't even assume this screenshot comes from his pc

**Comment by kaindub** [comment]
Ok pardon my ignorance. I have never had to select the radio  profile when I have updated Open Companion version.
How do i do that?

**Comment by raphaelcoeffic** [comment]
@kaindub Use the marked Icon ;-) The Tooltips are very helpful as well, use them! The one for that icon reads "Radio profile".

![IMG_7620](https://user-images.githubusercontent.com/1050031/63491234-f1b87380-c4b6-11e9-9c1d-0dea165bd6fb.jpg)
