### ISSUE TITLE
x7 : 2.2.4 -> 2.3 won't turn on

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#6667]
Starting eeprom:

[eeprom-x7-2.2.4.bin.zip](https://github.com/opentx/opentx/files/3544729/eeprom-x7-2.2.4.bin.zip)

Flash 2.3N69 (tested with opentx-x7-lua-en.bin)

Turn off radio

Try to turn on : you get shutdown animation and it power off

**Comment by raphaelcoeffic** [comment]
@bsongis I think that when loading the settings so early to have `pwrOnSpeed` & `pwrOffSpeed`, we should prevent any conversions and use default values (0) in case a conversion would be needed. Then, later, load the settings as we would have done before the "fast boot/shutdown" change.

**Comment by bsongis** [comment]
of course yes!

**Comment by raphaelcoeffic** [comment]
And on top of that, `eeConvert()` tries to raise a warning screen (and probably waits for confirmation....).

**Comment by raphaelcoeffic** [comment]
How naive I was for not thinking about that!!! Sorry guys!
