### ISSUE TITLE
X9D 2.3N69 SensorID shows 3 digits on the radio / cosmetic

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#6670]
![SensorID](https://user-images.githubusercontent.com/23188713/63775568-e662af00-c8df-11e9-98e7-486716871b45.jpg)

**Comment by raphaelcoeffic** [comment]
@Allerhopp this is absolutely normal. The instance ID now includes the module and (in case of ACCESS) the receiver concerned. The upper 3 bits of the ID might get updated based on the received telemetry packages.

You can convince yourself by checking that the sensor values are still updated when your model is powered.

**Comment by Allerhopp** [comment]
OK, thanks. An explanation for the new feature is welcome. I have only one module active and no ACCESS radio but nevertheless 3 different numbers in the 3rd digit.

**Comment by raphaelcoeffic** [comment]
It's not about digits, it's about bits (unfortunately). So basically the first 5 bits are the instance ID, as it used to be (well, -1, as it now corresponds to what is really received), then 2 bits for the receiver ID and 1 bit for the module (0 internal, 1 external).

During the conversion to 2.3 on the radio, the upper 3 bits are all set, but it does not matter, just ignore them. We might actually hide them from the display (@bsongis wouldn't that be better?).

So, using  251 as an example, this is 27 if you remove the upper 3 bits.

**Comment by Allerhopp** [comment]
OK, thanks again. From user view I would prefer module and RX information in the telemetry summary screen (see hardcopy) and additionally instance and ID in the sensor edit screen.

Btw. good to see, there is no more offset in instance ID.

**Comment by Allerhopp** [comment]
Sorry, forgot there is another thing confusing users. It would be more clear, if instance ID/sub ID is named sensor ID. FrSky uses sensor ID or Physical ID.
And what is named ID in companion better name it data ID.
