### ISSUE TITLE
OTX 2.3N69 on X9D+ SE shows jitter in RC

### ISSUE THREAD

**Issue by netzwergracer** [opentx/opentx#6673]
**Describe the bug**
Jitter on the RC side on OpenTX 2.3N69 on X9D+ SE. Every 180ms a frame of 18ms is received.
Receiver is R9MM with R9M module. Both on latest firmware. FPort Flex.

**To Reproduce**
1. install OpenTX 2.3N69 on radio
2. Bind R9M module and R9MM receiver
3. set debug_mode = rc_smoothing_rate

**Expected behavior**
Smooth jitter-free RC input with ~6.69ms frame length
**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/28099853/63809668-37e05d80-c923-11e9-8c3b-28d19fcd40eb.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/28099853/63809723-59d9e000-c923-11e9-88d4-24304afc7188.PNG)

**General information**
 - OpenTX version (2.3 N69)
 - Hardware (Frsky X9D+ SE, R9MM receiver, R9M module, Fport Flex firmware)

For comparison:
Same R9M module in FrSky Q7 remote on OpenTX 2.3 N69 showing very smooth RX refresh rate:

![Unbenannt](https://user-images.githubusercontent.com/28099853/63810678-9c042100-c925-11e9-99fa-1ad388782118.PNG)

**Comment by 3djc** [comment]
Have you configured failsafe the same way ?

**Comment by bsongis** [comment]
Are you using FPort? Would you please double check that the same module / same receiver / same everything doesn't have the same issue on X7? I just checked with FrSky the issue should be in the module, every 200ms (not 180ms). Would you please confirm to be sure we are on the right track?

**Comment by bsongis** [comment]
I close this issue, if everything above is true, it's not related to opentx
