### ISSUE TITLE
Betaflight LUA not supported on 2019 X9D+SE

### ISSUE THREAD

**Issue by twidgit** [opentx/opentx#6674]
Betaflight LUA does not execute. 

![63818431-d9e95100-c8f5-11e9-8f2c-1e5e1ee449b0](https://user-images.githubusercontent.com/36611506/63825436-aca99c80-c90f-11e9-8e40-fdcbec9b6016.jpg)

Steps to reproduce the problem:
Execute betaflight LUA

**General information**
 - OpenTX version (e.g. 2.3N69)
 - Hardware Frsky X9D+SE2019

**Comment by 3djc** [comment]
This is not related to OpenTX, but BF scripts

**Comment by twidgit** [comment]
Thought so.  I opened a ticket on the Betaflight LUA page and Mikeller sent me here.

**Comment by 3djc** [comment]
I'll talk to Mike :)
