### ISSUE TITLE
2.3 : need lua path tools for TOOLS 

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#6679]
We need to be able to create a ‘launcher’ that can chdir to a subdirectory and then launch a specific lua among several

**Comment by raphaelcoeffic** [comment]
I had the scripts moved to the TOOLS directory and it worked ok.

**Comment by bsongis** [comment]
Yes but some scripts come with a lot of subscripts, if we exported a sort of `chdir` function it would be nice

**Comment by lshems** [comment]
Al boils down to the script needing to know where to find subscripts.

I just create a Lua variable containing the root path. I would never use the chdir, as for me it would complicate things.

**Comment by bsongis** [comment]
How do you know the root path?

**Comment by 3djc** [comment]
Well, the intend is to be able to use scripts as they are (of course, with scripts rewrite, you can manage it).

**Comment by bsongis** [comment]
Yes, for me a chdir with a relative dir would be perfect, right?

**Comment by 3djc** [comment]
yes, so we can have a XfireLaunch.lua in /SCRIPTS/TOOLS that will perform a chdir to CROSSFIRE and then launch crossfire.lua (as an example)

**Comment by lshems** [comment]
Ok, relocating existing scripts is another use case. Makes sense there.

Sorry for not noticing that intend.
