### ISSUE TITLE
X Lite Pro calibration problem after factory reset.

### ISSUE THREAD

**Issue by Talha909** [opentx/opentx#6690]
**Describe the bug**
I have installed the N73 in my Xlite Pro.  I did the factory reset.  Calibration screen appears after that.  I move sticks and there is nothing happening in my calibration screen. both sticks show calibration on right side but stick are in middle. 

**To Reproduce**
1. Factory Reset.
2. Calibration screen
3. Move sticks but nothing happened 

**Screenshots**
screen shot add.

**General information**
 - OpenTX version (N73)
 - Hardware (Frsky xlite Pro)
 - OpenTX Companion ( 2.3. N73 on windows 10
![dbc87ceb-d032-43bf-843f-f7adf2110f9b](https://user-images.githubusercontent.com/29024390/64068710-31205600-cc55-11e9-879b-21bd27a390aa.jpg)

**Comment by kilrah** [comment]
Continue the process as you're told to.
