### ISSUE TITLE
Executable D;/sam-ba.exe not found

### ISSUE THREAD

**Issue by Diffy91** [opentx/opentx#6692]
Hi! I am new to the hobby, so sorry if I seem slow on the uptake! I was given a 9xr Pro and am looking to use it it with a r9m receiver and transmitter pair. I tried to install opentx today on 9xr Pro after installing the latest version of OpenTX Companion. However, when ever I try to write firmware to my 9xr Pro, it gives me this error code.

Executable D;/New folder/Companion 2.2/sam-ba.exe not found

I've looked on several forums and haven't found anything to be helpful with this error! Can anybody help me see what I'm doing wrong? Thank you!

**Comment by bsongis** [comment]
You can download sam-ba (+ config files) in the downloads section of open-tx.org
