### ISSUE TITLE
Companion 2.3 give "Can't extract Radio/Bin" whenever I try to open a 2.2.4 nightly OTX

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6699]
The attached otx-files can't be opened.

![cantextract](https://user-images.githubusercontent.com/39838998/64117533-b3b02f00-cd95-11e9-9b3e-476c7b40eb77.PNG)
[OTX.zip](https://github.com/opentx/opentx/files/3566184/OTX.zip)

**Comment by bsongis** [comment]
Please check after next nightly build, I have fixed an issue, and I am now able to open an eeprom generated with companion 2.2

**Comment by notlebowski** [comment]
OK, I will test that tomorrow...
If it works I will check my models for differences.
Beside 3 active models there should be no difference between what's on the radio now.

If there is, I will revert my radio to 2.2.4N705, load the setup from then and then perform a new radio conversion and check for differences.

**Comment by 3djc** [comment]
I have just lauched a nightly creation, should be up in 90minutes or so
