### ISSUE TITLE
x9 lite 2.3 n73, cannot bind 9-16 with telem on

### ISSUE THREAD

**Issue by P-I-Engineer** [opentx/opentx#6701]
choose bind 9-16 telem on

result: no telemetry

hardware/firmware:
x9 lite
opent tx 2.3 n73
d16 mode

**Comment by 3djc** [comment]
Receiver ?

**Comment by P-I-Engineer** [comment]
r-x6r

**Comment by P-I-Engineer** [comment]
i'll be trying jumper 1&2 and 3&4 and 1-8 telem on, to see if it follows the rx8r binding method.

**Comment by kilrah** [comment]
Recent receivers don't support the jumper method.

**Comment by P-I-Engineer** [comment]
ok, i'll wait then, thanks

**Comment by P-I-Engineer** [comment]
rf module is on 190605 firmware

**Comment by P-I-Engineer** [comment]
updated internal module to isrm 1.1.3 and now working.
i'll close this. opentx is fine, it was the internal modules issue.
