### ISSUE TITLE
QX7S Bluetooth Telemetry with FreeLink App

### ISSUE THREAD

**Issue by MovingBush** [opentx/opentx#6704]
Hello, I was wondering how to enable the Bluetooth option on the QX7S. Also, is the QX7 version of OpenTX 2.2.4 compatible for the QX7s? If not, could you please post a link to it? Thanks!!

**Comment by 3djc** [comment]
I'm sorry but this place is not one for questions and user support, but for bug tracking. Please go places like rcgroups or openrcforums for this types of demand.

Also, as you can see for yourself, the radio setup mentions both x7 and x7s
![image](https://user-images.githubusercontent.com/5167938/64155418-05f35d80-ce33-11e9-9c12-6c10c9db1203.png)
