### ISSUE TITLE
x9e (emergency-mode and bootloder) self-initiated reboot fails

### ISSUE THREAD

**Issue by 0815Creeper** [opentx/opentx#6707]
**Describe the bug**
The transmitter does not turn back on again after watchdog reset or after pressing exit in the bootloader. First batches do not seem to be affected. 

**To Reproduce**
Press exit from bootloder menue an check if transmitter turns on again or stays off.

**Expected behavior**
Transmitter turns on again normally (After bootloader-exit) or turns on again in emergencymode (after watchdog reset)

**Observed behavior**
- Transmitter turns off and stays off after bootloader-exit
- Transmitter turns off and stays off due to watchdog-reset (presumably). After pressing the pwr-btn, the transmitter turns on in ermergency-mode (! Symbol, no sd, no splashscreen)

**General information**
 - OpenTX version 2.2.3 (bootloader 2.2.3)
 - Hardware x9e

https://www.youtube.com/watch?v=8k9ilSo-q2M

**Comment by 3djc** [comment]
We have finaly found an X9E that does have the issue too, we are working on it

**Comment by bsongis** [comment]
yes ... mine :)

**Comment by bsongis** [comment]
I fixed 2.3 and I see the same issue is there in 2.2

**Comment by 0815Creeper** [comment]
great, thanks!
