### ISSUE TITLE
Horus X10 not forwarding Crossfire telemetry to the internal BT module

### ISSUE THREAD

**Issue by putimir** [opentx/opentx#6712]
With (my) Horus X10S/w TBS Crossfire Micro TX module, when enabling the internal BT module, the telemetry data is not forwarded to/transmitted from the internal BT module. The feature however works fine, when using internal radio, receiving s.port telemetry data. 

1. Use Frsky Horus X10(S) transmitter with TBS Crossfire Micro TX module 
2. Have a working connection with a model, receiving (through XF link) and displaying telemetry data 
3. Enable internal BT module and set it to "telemetry"
4. Connect with a BLE tool of choice and listen to the data stream; there is no data transmitted, when using external XF module, but it works when using internal radio and s.port as telemetry.

I would like to request, that the Crossfire telemetry is being forwarded to the BT module, either in native format or  translate it to s.port 'format' or other, whichever is more simple and faster to accomplish.

**General information**
 - OpenTX version: "opentx-x10-2.2.4"
 - Hardware: Frsky Horus X10S
 - TBS Crossfire Micro TX, version 2.41

**Comment by davwys** [comment]
To add to this:
I have successfully tested FrSky's own TX modules such as the XJT or the R9M to work in this manner with the Horus and found that they forward telemetry via the Horus' built-in BT module - so this problem is most likely exclusive to third-party modules like the Crossfire.

**Comment by putimir** [comment]
Thank you for rapid collaboration, @davwys, thanks for additional data, I don't own other Frsky modules; to add: I'd be using this to feed the data to the u360gts tracker: https://github.com/raul-ortega/u360gts/tree/master/wiki

**Comment by kilrah** [comment]
The telemetry output from OpenTX will be straight Crossfire which that project doesn't support, so work will be needed there too.

**Comment by 3djc** [comment]
I will do that change, but as serial, we will output data in Crossfire native format (as we do output FrSky telem in their native format)

**Comment by davwys** [comment]
The project's author is currently working on CRSF telemetry implementation (and has already uploaded videos of it working), I'm assuming it will work soon - so that shouldn't be an issue.

**Comment by putimir** [comment]
@kilrah: just as davwys said: the implementation of the XF for that project is in beta stage, so, this solution will be most certainly beneficial!

https://www.facebook.com/groups/u360gts/permalink/2818315331572720/

**Comment by 3djc** [comment]
xfire telem comes at a really fast rate, it will be interesting to see if a BT ble link can cope with it

**Comment by 3djc** [comment]
Will be in tomorows 2.3 nightly

**Comment by putimir** [comment]
Regarding bandwidth: good point; it is already suggested (https://github.com/raul-ortega/u360gts/issues/47#issuecomment-522525250) that the internal baud rate is limited to 115200; but I'm more than happy to test all the scenarios!

**Comment by putimir** [comment]
YESS! Getting data! I'm using 115200 baud on the XF module. Will try later with 400000 baud. Here is the captured data, in case someone cares to take look if it is sane and usable...
[btlog.log](https://github.com/opentx/opentx/files/3582390/btlog.log)

Thank you @3djc!

**Comment by putimir** [comment]
Hello, @3djc: is this included in the todays RC1?

From release notes: "Add Crossfire telemetry mirror on bluetooth"?

Thanks

**Comment by 3djc** [comment]
well, I think you answered the question yourself

**Comment by putimir** [comment]
:D :D

Sorry, wasn't sure if it was Horus related.... Thanks again for the intervention!

Regards!

**Comment by putimir** [comment]
Hey sorry to bother you, with one more thing: I have installed now the RC1 companion over the N80 version, but now it gives me the "compilation error" when I try to download the FW, for the Horus X10...

I have the profile set-up and selected. I does not give me error, if I switch to the X7 profile and download the FW...

**Comment by 3djc** [comment]
What exact options are you using ?

**Comment by putimir** [comment]
just noheli and lua

**Comment by putimir** [comment]
![image](https://user-images.githubusercontent.com/33059362/64726228-773bac00-d4d6-11e9-8609-6a545ec1795c.png)

**Comment by 3djc** [comment]
I just downloaded it ok

**Comment by putimir** [comment]
What do you recommend? Make a new profile perhaps?

**Comment by putimir** [comment]
Yup, that fixed it...

**Comment by putimir** [comment]
Can just add this: I'm having no problem now, with RC1, getting telemetry through BT even if I set the module baud rate @400000... :D

**Comment by putimir** [comment]
One thing, I noticed, regarding telemetry display, changed in this version:

With the XF transmitter modules, you get some of the sensors from TX module in, even if not connected to a receiver, for example, TPWR and RQly. In previous OpenTX, these were getting in nicely and the telemetry display, as well as all the logical switches and functions were working as intended...

Now these sensors come in intermittently, the displays are blinking, the LS are firing multiple times....

When the TX connects with an RX, these symptoms are gone, all the sensors, both from RX and TX are stable...

https://www.youtube.com/watch?v=6f6MHlQQJQY

**Comment by 3djc** [comment]
please open separate issues, it is impossible to track things like that, thanks

**Comment by putimir** [comment]
Ok, sorry, I posted here, because I thought perhaps it's related to the BT mirror...
