### ISSUE TITLE
[2.3N81] Telemetry not working (ISRM ACCST D16)  

### ISSUE THREAD

**Issue by uragano47812** [opentx/opentx#6717]
**Describe the bug**
Telemetry is not working (using ACCST D16 with last 1.1.3 firmware module). The radio doesn't see the sensors and can't find any new sensors with the discover function. Only RSSI is reported and even not the RXbat showing. I tried with different sensor like Frsky 150A sensor and Unisens-E sensor. 

**I tested with N79 and it was working** 

**To Reproduce**
1. Go to 'Telemetry setup'
2. Click on 'discover new sensors'
3. See error: no new sensors will appear and RSSI is showing "default"

**Expected behavior**
See the sensors list with their usual ID.

**General information**
 - OpenTX version 2.3N81
 - Hardware  Frsky X9D+ SE 2019 with ISRM 1.1.3 module firmware
 - OpenTX Companion 2.3N81

**Comment by Talha909** [comment]
same issue faced by me.

**Comment by 3djc** [comment]
This should now be working in N82
