### ISSUE TITLE
TH9x with AR9x Board  "hangs" at startup logo.

### ISSUE THREAD

**Issue by OldGazer** [opentx/opentx#6724]
Radio works fine running Er9x and latest OpenTx 2.2.4.  Flashed with latest 2.3.0N80 nightlie, radio hangs at startup.  I have tested this with an SD card and without an SD card.  I have done a full chip erase and flashed  2.3 using SAM-BA, and the radio does not boot or display the startup logo.

Oddly enough I can put the AR9X into bootloader mode and I can flash with 2.2.4 from an SD card and the radio works.

**Comment by Steini63** [comment]
I can confirm the issue. I's exactly the same with my Turnigy TGY-9x with AR9X board. Older versions and Er9x running fine.

**Comment by sreichholf** [comment]
Same for me, AR9X doesn't boot with 2.3.x here

**Comment by OldGazer** [comment]
At this point its obvious to me that this is most likely caused by a code change that the Dev team could not test due to  a lack of hardware.

**Comment by 3djc** [comment]
> At this point its obvious to me that this is most likely caused by a code change that the Dev team could not test due to a lack of hardware.

Indeed

**Comment by sreichholf** [comment]
I'll see if I can find some time (asap) to bisect it.
It would be a major boost if anyone cloud point at the "closest" two versions he knows about it "working" and "being broken".
(if it's 2.2.x vs 2.3.0N80 than that's where i'll start).

**Comment by sreichholf** [comment]
This should be fixed with 0ebf9dbb1e020b24b93d2e3e8c6437999b1bc02f

**Comment by OldGazer** [comment]
This is totally AWESOME!!!

What is the ETA for this to it the 2.3.3 nightlies?

**Comment by OldGazer** [comment]
I just flashed my Th9x with 2.2.3N49 and IT'S ALIVE!!!

Thanks so much for getting this resolved.  You guys ROCK!!!
