### ISSUE TITLE
2.3N83:- Emergency mode when any reset option is selected on X10S Express

### ISSUE THREAD

**Issue by aussiepage** [opentx/opentx#6727]
X10S Express enters Emergency Mode when any of the reset options are selected (Reset Flight, Reset timer 1 etc)

Issue can be reproduced by

1. Long press of menu key to bring up menu
2. Select Reset...
3. Select any reset option.

The issue also occurs when

1. Long press of menu key to bring up menu
2. Select Reset...
3. Press RTN to exit reset menu

**Expected behavior**
Model reset option occurs

**General information**
 - OpenTX version (e.g. 2.3N83)
 - FrSky Horus X10s Express

Issue repeatable on my radio - only have one default model programmed but have created some new categories with no models programmed in these new categories.

**Comment by bsongis** [comment]
Reproduced
