### ISSUE TITLE
X10 Express enters emergency mode when telemetry filter is selected in Logical Switches Page

### ISSUE THREAD

**Issue by Quadpilotman** [opentx/opentx#6730]
X10 Express enters emergency mode when telemetry filter is selected in Logical Switches Page

To Reproduce
Select MDL menu 
Single click to Logical Switches page
Select a line to configure and scroll through to First variable column.
Long Press to get filters selection
Scroll down to Telemetry.
Two things cause the entry into emergency mode
1. Scroll back up
2 Select the Telemetry option with a single click.

OpenTX version 2.3.0N83
Hardware FrSky X10S Express

**Comment by bsongis** [comment]
Reproduced

**Comment by br34k0r** [comment]
Is this an issue in general with scrolling up in lists? Also happens on model picture selection or .wav file selection
