### ISSUE TITLE
binding t16 to hitec receiver

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#6736]
The issue tracker here is for devlopment of OpenTX. This is not a
support site, only a bug tracking system. Please use support groups
like [rcgroups](https://rcgroups.com/) or
[openrcforum](https://www.openrcforums.com/forum/). See also our
[manual](https://opentx.gitbooks.io/manual-for-opentx-2-2/).

For quick questions you can also join our general chat.

Issues that fall into the category of asking for help, will be
generally closed as invalid without an answer.

hi.  i cant bing correctly to my hitec optima receiver...  i did try to change firmware in receiver and try almost all model in t16..  nothing work.  can someone help me please..

**Comment by 3djc** [comment]
This place is for OpenTX bug tracking, T16 doesn't run OpenTX, and multiprotocol (if that's even what you are trying with) support is not done here. As mentionned in your own post : please use support groups like rcgroups or openrcforum
