### ISSUE TITLE
No R9M Access option on X9D+ SE (Old model) with R9M (old module) 

### ISSUE THREAD

**Issue by CIXFPV** [opentx/opentx#6737]
Hello guys,

Using last OTX 2.3 N84 we can't select the R9M access option on the X9D+ SE (old model).

Bug has been confirmed on 2 radio.

Thanks :)

**Comment by 3djc** [comment]
When you say old module, I guess you mean 'non 2019' R9 module. Those are not access compatible I believe, only the R9M 2019 are (and lite), so you can't do access with those anyway.

As for radio support, currently only X10 Express and X9D+ 2019 support R9M 2019 in ACCESS mode, we will assess if the other radio ahave the hardware capabilities to support it

**Comment by bsongis** [comment]
The X9D+ doesn't have a hardware serial port and the R9M ACCESS need to go to 450kHz
Only X9D+ 2019 and X10 Express are compatible with R9M ACCESS (full size) today

**Comment by RRAlex** [comment]
Just to get this straight as I think a lot of people are confused since FrSky promised things it might not deliver, but will regular ACCESS still be possible with the internal module on "old" X9D+SE?
(without spectrum analyzers or fancy features, but just core control...)

**Comment by kilrah** [comment]
Nobody knows but FrSky, and they have never answered that question. So assume no.

**Comment by 3djc** [comment]
That is not currently the case, and we have no information suggesting it will change (or not). Only FrSky would know
