### ISSUE TITLE
Vario and Atimeter have stopped working.

### ISSUE THREAD

**Issue by CliffEvans** [opentx/opentx#6738]
After updating to 2.2.4 I am not getting any data from the vario or altimeter on any of my models.  Alt just reads "0" all the time.

**Comment by 3djc** [comment]
Well, no detail on radio used, no detail on where you where comming from, thats gonna be real hard to investigate. Please post your otx so we can have a look, but that's the first time someone reports something like that in over 40k 2.2.4 downloads

**Comment by CliffEvans** [comment]
So sorry!  Horus X10s   otx is in the zip file.  The model I was flying when I noticed this is the SG38  As stated all was fine until I updated!  but, has affected all models.

[Cliff.zip](https://github.com/opentx/opentx/files/3599785/Cliff.zip)

**Comment by 3djc** [comment]
Any specific reason to have your instance to 27 on that sensor ? Also, what version where you comming from ?

**Comment by CliffEvans** [comment]
No, I don't really understand what that means, or how to change it.  I have never changed anything but the firmware.

**Comment by CliffEvans** [comment]
I have just fired up the T21 model, Alt just stays on 0 all the time.
![20190911_094002](https://user-images.githubusercontent.com/18718856/64682366-424d3c00-d479-11e9-9507-3fbbb44f0f15.jpg)

**Comment by CliffEvans** [comment]
![20190911_095043](https://user-images.githubusercontent.com/18718856/64682706-d7e8cb80-d479-11e9-8883-e97c7372406e.jpg)

**Comment by 3djc** [comment]
In your OTX, those sensor have an instance of 17, which is rather unusal, could you try to either rediscover sensors or changing their instance to 1 ?

**Comment by CliffEvans** [comment]
Have done all of that. two or three times now!

**Comment by CliffEvans** [comment]
Have just changed from 27 to 1, will just go out and try it.

**Comment by CliffEvans** [comment]
![20190911_100407](https://user-images.githubusercontent.com/18718856/64683761-cd2f3600-d47b-11e9-9742-5825896aebef.jpg)  instance set to "1"

**Comment by CliffEvans** [comment]
![20190911_100437](https://user-images.githubusercontent.com/18718856/64683828-ea640480-d47b-11e9-9036-6586060debc1.jpg)
After rediscovering.

**Comment by 3djc** [comment]
Strange that they are on 27, but there are here and working since you have the *

**Comment by CliffEvans** [comment]
I am totally clueless!!!

**Comment by CliffEvans** [comment]
I have just downloaded and installed the firmware again, all is now working!!!

**Comment by kilrah** [comment]
You likely had the "faimode" option enabled in the previous one you downloaded.

**Comment by CliffEvans** [comment]
I don't know!  As far as I am aware, I have never changed anything but, easily done I suppose.
Thanks to all for the help.
