### ISSUE TITLE
Swedish as a menu language does not work

### ISSUE THREAD

**Issue by eral00** [opentx/opentx#6747]
Junk characters on display, when I use Menu language Swedish

**Screenshots**
![image](https://user-images.githubusercontent.com/55209799/64728869-43fc1b80-d4dc-11e9-9770-eb6d130a3d2a.png)

Testing on ,Horus X10s Express
 - OpenTX version  2.3.0.N85
- Firmware version 2.3.0.N85

**Comment by 3djc** [comment]
We will fix this, but you need to be aware we haven't had updates  to swedish translation for a looonnng time

**Comment by 3djc** [comment]
OK, looks like a font issue. Could you check those screen to see if the right characters seem to be used ?

![image](https://user-images.githubusercontent.com/5167938/64757606-dc24ef80-d532-11e9-84d3-00b94a8a8f4a.png)

![image](https://user-images.githubusercontent.com/5167938/64757617-eb0ba200-d532-11e9-8f93-87b7756f13a2.png)
