### ISSUE TITLE
ISRM Access Gives Wrong Menu - EU Version

### ISSUE THREAD

**Issue by Bill-Edwards99** [opentx/opentx#6749]
Horus X10S Express

OpenTX 2.3.0RC1 (EU Build)

Select Model, Select ISRM, Select Access gives the following menu
![aaa1](https://user-images.githubusercontent.com/55228524/64760652-2659a100-d532-11e9-80fe-f2e1c2cabd07.jpg)

Select ISRM and Off gives the correct menu
![aaa2](https://user-images.githubusercontent.com/55228524/64760684-3b363480-d532-11e9-9d10-7c7e7dad2729.jpg)

**Comment by Bill-Edwards99** [comment]
Sincere apologies, I was sure I was in the correct place to post this, but it appears I wasn't :(

**Comment by 3djc** [comment]
Fixed in https://github.com/opentx/opentx/commit/43e5f0c50240e8ff7fad7807ba9cd85c9ee71106

**Comment by 3djc** [comment]
Fixed in tomorows nightly and in upcomiing RC2

**Comment by kilrah** [comment]
> Sincere apologies, I was sure I was in the correct place to post this, but it appears I wasn't :(

It is, it was just already taken care of.
