### ISSUE TITLE
Jumper T12 companion export shift in switches

### ISSUE THREAD

**Issue by PasiRuo** [opentx/opentx#6762]
L01=true does not change flightmode if switch=L01

Problem with JumperT12 and otx2.3rc1 is that logic condition does not change flightmode.

**Comment by 3djc** [comment]
Can you post your otx ? I just tested here, it works fines

**Comment by PasiRuo** [comment]
[document12.zip](https://github.com/opentx/opentx/files/3609179/document12.zip)
posted this before to chat.opentx and got confirmation and request to post this report here.

**Comment by kilrah** [comment]
Nothing to do with flight modes specifically, just export of switches for T12 has shifts

![Clipboard01](https://user-images.githubusercontent.com/6065069/64850357-88d79d80-d615-11e9-9533-e7849f6f469c.png)
![Clipboard02](https://user-images.githubusercontent.com/6065069/64850365-8aa16100-d615-11e9-99a2-2feb710be8ff.png)

**Comment by kilrah** [comment]
Also sources, GV1 comes as CH31

**Comment by redeyejoe** [comment]
I was trying to flash opentx to t12 today and file it imports wont open after install. also get error that file doesnt match current version. I had to flash back to the jumpertx firmware. Controller wont boot, just vibrates. It tried to open when I went back into bootloader mode.
