### ISSUE TITLE
Throttle trim for aileron diff setting.

### ISSUE THREAD

**Issue by tomekmgr** [opentx/opentx#6763]
I use my radio to fly gliders mainly. 
For those kind of aircraft it's very important to have differential aileron setting. (more up than down).
It's usually done by setting global variable, and assign it in diff field in mixer setting.
This value need to be adjusted, during first setup, or even sometimes during the flight.

The most convenient way to do that is to use throttle trim and add special functions to increase and decrease global variable.

I would like to be able to:
* Add option to remove trim from screen (when used to control something else it make no sense)
* Change sounds - when control global variable 'trim center ' is when GV is 0.
* There is no trim max nor trim min or if we provide a way to define global variable range, then it should point to it.
* Change pushing algorithm, when trim is pushed it increased GV by 1, but when hold, radio increases trim value, but not spawn special functions. (When press and hold the trim, GV is increased only by one)

**Comment by kilrah** [comment]
The first 3 are taken care of by setting the throttle trim to "Disabled" in flight modes.

4 can probably be overcome with a Timer LS.
