### ISSUE TITLE
Fry Sky Taranis x9D+

### ISSUE THREAD

**Issue by ThePhantom05** [opentx/opentx#6772]
Tell me, will firmware 2.3 on Fr sky Taranis x9D Plus be? And then I download copyman 2.3 (OpenTX 2.3.0RC2 (2019-09-13)) and there is no firmware for my Fr Sky Taranis X9D Plus ....

**Comment by kilrah** [comment]
This is not a support site but a bug tracker, please put your usage questions on forums.

Yes 2.3 supports the X9D+.

**Comment by ThePhantom05** [comment]
Sorry, I figured out the companion needed to set the firmware - realese channels - realese candidates (testing). 
But now at the moment there is no multi tab, you will have to wait until it appears....

**Comment by ThePhantom05** [comment]
Зачем закрыл?

**Comment by 3djc** [comment]
Multi is now always part of any 2.3 firmware

**Comment by ThePhantom05** [comment]
> Это не сайт поддержки, а багтрекер, пожалуйста, задавайте вопросы по использованию на форумах.
> 
> Да, 2.3 поддерживает X9D +.

Зачем закрыл? А?

**Comment by 3djc** [comment]
English only please

**Comment by ThePhantom05** [comment]
Wow, thanks) For the answer)) So you can upgrade)))?

**Comment by ThePhantom05** [comment]
The multi has a lot of useful features !!!

**Comment by ThePhantom05** [comment]
> Это не сайт поддержки, а багтрекер, пожалуйста, задавайте вопросы по использованию на форумах.
> 
> Да, 2.3 поддерживает X9D +.


Why did you close it ??? BUT

**Comment by 3djc** [comment]
Can you READ ????? MULTI is IN ALL 2.3 FIRMWARES
