### ISSUE TITLE
[2.3.0 RC3 - Horus X12S] - RAS always remains at 0

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#6775]
On my X12S the visualization of the RAS in the statistics is always of value 0, even changing antenna (INT or INT+EXT).
I'm sorry but this is a particular situation, that is I installed the IXJT+ RF module of the X10S (triple antenna), so I can't say it's a bug because maybe the firmware doesn't correctly interpret what comes from the module because it expects to find an IXJT and not a IXJT+.
It would still be welcome if he could intercept it anyway.
In this condition with OpenTX V2.2.4 the RAS is displayed only with INT+EXT antennas, it remains at 0 on the INT setting, but on the outside it reports it.
Surely with the original IXJT (X12S) the RAS was correctly reported on OpenTX V2.2.4 and in both situations (INT and INT+EXT antennas), I remember it well.

![20190914_124116](https://user-images.githubusercontent.com/3864712/64906967-1508c400-d6ed-11e9-8f97-8cc8701d7375.jpg)
![20190914_124135](https://user-images.githubusercontent.com/3864712/64906968-1a660e80-d6ed-11e9-9e5c-2a68406a1927.jpg)

**Comment by robustini** [comment]
@raphaelcoeffic @kilrah The problem is not so much that the RAS is not displayed, but that if an antenna has a problem the RF module continues to transmit, compromising its functioning.
I tried now to remove the external antenna for a moment after enabling it and OpenTX didn't notice.
Tested with RC5.

**Comment by kilrah** [comment]
>  if an antenna has a problem the RF module continues to transmit, compromising its functioning.

That is always the case anyway.

**Comment by robustini** [comment]
> That is always the case anyway.

With OpenTX V2.2.4 if the external antenna is badly fixed the RAS goes to the stars and the radio warns me.
With 2.3 it does not, being always at 0 with the XJT+ module on X12S, i hope with IXJT work fine.
With OpenTX 2.2.4 and the IXJT+ rf module work only the RAS when i select "INT+EXT", with the original IXJT module work in both condition.

**Comment by kilrah** [comment]
Sure, but your post suggested it would stop transmitting automatically which has never been the case.

We will likely need some clarification from FrSky about when it can be used/displayed at this point.

Unfortunately we can't just always display it since there are module hardware/software versions and/or antenna selection settings that lead to incorrect/invalid RAS to be sent that we have to ignore, something likely got broken in that logic but we don't know what exactly it's supposed to be.

**Comment by robustini** [comment]
> Sure, but your post suggested it would stop transmitting automatically which has never been the case.

I'm sorry Andre, i've explained myself wrongly, I do not mean absolutely that it has to stop transmitting, but simply warn as in 2.2.4, If the user is warned he can do something, if he is not warned he risks compromising the module.
