### ISSUE TITLE
[2.3.0 RC3 - X9D+ SE 2019] Crossfire scripts very slow

### ISSUE THREAD

**Issue by Target0815** [opentx/opentx#6778]
**Describe the bug**
With current Crossfire version (2.93) the LUA scripts for Crossfire are very slow. With Crossfire version 2.41 this was still ok.

Looks to me like the Crossfire scripts still need to be updated.

**To Reproduce**
Update Crossfire to lastest release version (2.93).

**Comment by 3djc** [comment]
To be sure I understand, is it RC3 releated, or Crossfire version related ?

**Comment by 3djc** [comment]
OK, tried on x7:
- 2.2.4 with 2.2 scripts and 2.41 : fast
- 2.2.4 with 2.2 scripts and 2.93 : slow
- 2.3.0RC3 with 2.2 scripts and 2.41 : fast
- 2.3.0RC3 with 2.3 scripts and 2.41 : fast
- 2.3.0RC3 with 2.2 scripts and 2.93 : slow
- 2.3.0RC3 with 2.3 scripts and 2.93 : slow

So it is definitively  a change in 2.93. Will contact TBS

**Comment by Target0815** [comment]
Thank you. I posted it here because the Crossfire scripts are also "delivered" with OTX.

**Comment by 3djc** [comment]
Had a discussion with TBS on the subject. On the newer version, a LOT more data are exchanged between TX and RX, specialy when entering this screen.  It's not doing "nothing', on the contrary. They are looking at ways this could be improved, but that's not the scripts or OpenTX, just XFire doing more and more things version after version
