### ISSUE TITLE
Auto-offset for Altitude seems to be not working anymore

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6780]
On my DLG's I will reset the altitude to 0 whenever ABS(alt) > 1m
Upon binding the system will reset the altitude to 0 and my graphs always looked good.

This weekend I'm seeing this in between flights.
Upon binding it gets a large negative height which spoils my graphs.
It never did this before. Not on <2.2.4 and not on the nightlies.

Today I flew with 2.3.0RC2

![alt](https://user-images.githubusercontent.com/39838998/64912248-ba8f5800-d72c-11e9-8c30-69d5deec3c1a.JPG)

**Comment by fritzster** [comment]
I have the same issue since going to 2.3RC1, Didn't have it with the nightlies. Reset telemetry shows 0 altitude for 1 second and then it jumps to 291m. Have deleted and re discovered sensors. The altitude is working but with the 291 offset. Have added -291 to the offset for an interim fix.

**Comment by 3djc** [comment]
What do you use, we don(t seem to be able to replicate,  but we don't have to rebind every flight either.

**Comment by notlebowski** [comment]
The word "binding" is used as in "establishing the link".
We don't rebind every flight neither...

Enabling/Disabling logging of my BAMF DLG is a bit complex, so I prefer to take my ELF as an example. I flew it on August 31st and on September 14th with the same setup.

On September 14th I flew it with RC2 and on August 31st I flew it with a 2.3.0 Nightly.

My BAMF and Elf showed the exact same behaviour on RC2.
Both have a different GRX6 receiver.

Logging is controlled by this:

L18 Telemetry AND ---- Delay(10s)
L19 !Telemetry AND ---- Delay(10s)
L20 Sticky(L18, L19)

SF1 L20 - SD Logs (0.3s)

Altitude gets set to 0 meters whenever I set the Elf into prelaunch.
On the first graph you will see no big change.
The small drift of -3.4m gets eliminated.

On September 14th the reset needed to reset the initial -148.6m.
I can put a duration of 0.1 second on L18 and give a reset of the altitude there, but auto-offset should have done that like it always did since its introduction.


You can see the Altitude was reset, but it drifted to -3.4m before it started logging.

Date,Time,VSpd(m/s),Alt(m)
2019-08-31,14:21:47.640,-0.2,-3.4
2019-08-31,14:21:47.850,-0.4,-3.5
2019-08-31,14:21:48.150,-0.2,-3.6
2019-08-31,14:21:48.450,-0.1,-3.6
2019-08-31,14:21:48.750,-0.2,-3.6
2019-08-31,14:21:49.050,0.0,-3.6
2019-08-31,14:21:49.350,0.1,-3.5
2019-08-31,14:21:49.650,0.0,-3.5

![Elf 31-08](https://user-images.githubusercontent.com/39838998/65050862-61ac0380-d968-11e9-873c-fa8006626314.JPG)




This is the exact same setup 2 weeks later

Date,Time,VSpd(m/s),Alt(m)
2019-09-14,14:17:03.150,0.0,-148.6
2019-09-14,14:17:03.160,0.0,-148.6
2019-09-14,14:17:03.540,-0.1,-148.8
2019-09-14,14:17:03.840,-0.1,-148.7
2019-09-14,14:17:04.150,0.0,-148.7
2019-09-14,14:17:04.450,-0.1,-148.8
2019-09-14,14:17:04.750,-0.1,-148.9
2019-09-14,14:17:05.050,0.0,-148.8
2019-09-14,14:17:05.350,0.0,-148.7
2019-09-14,14:17:05.650,0.0,-148.8
2019-09-14,14:17:05.950,0.0,-148.9
2019-09-14,14:17:06.250,-0.2,-149.0
2019-09-14,14:17:06.550,-0.1,-149.0

![Elf](https://user-images.githubusercontent.com/39838998/65050661-0c6ff200-d968-11e9-96fb-a5e22484e9a4.JPG)

**Comment by notlebowski** [comment]
@fritzster 
Upcoming Friday evening is the first time I can test this again.
Can you check if you can reproduce this with current RC?

**Comment by fritzster** [comment]
The offset altitude issue I had was while running ACCESS on my g-rx6 and 2.3RC1 on my 2019 X9D SE it did not happen on the 2.3 nightlies. I’ve since downgraded the RX to ACCST due to sensor loss issues and also upgraded to 2.3RC3 and I no longer have either of the issues. My offset problems had nothing to do with binding but occurred every time I powered up the RX or reset telemetry.

**Comment by notlebowski** [comment]
I had this issue last Saturday with both of my models. It happened during normal operation with 2 different receivers running ACCST that were without issue before. The word "binding" was not used properly by me when I opened the ticket.

I have been daily updating my radio during the holidays and flying a few of my models. Now these holidays are over and I only have access to them during the weekends. Hopefully it was some fluke in RC2. Upcoming Friday evening I will test the radio again. I hope there is no final release before that, but I think there is.

**Comment by notlebowski** [comment]
Last Sunday I flashed RC3 on my X-Lite, but never tested it. Just now I tested it with that version and it seems the issue was exclusive to version RC2

**Comment by 3djc** [comment]
So this is not an issue anymore ?

**Comment by notlebowski** [comment]
No... 
At the the time there was some work on RSSI-
It may have been some side-effect of a tried solution (or not) ;)

**Comment by notlebowski** [comment]
BTW
I now control the logs this way on my DLG's
Not because I need to, but just to get cleaner graphs.

L18 Telemetry AND Duration(0.1s) Delay(10s)
L19 !Telemetry AND ---- Delay(10s)
L20 Sticky(L18, L19)

SF1 L18 - Reset Alt
SF2 L20 - SD Logs (0.3s)
