### ISSUE TITLE
Companion RxNum does not differentiate between d8/d16

### ISSUE THREAD

**Issue by notlebowski** [opentx/opentx#6786]
Please reopen:

I have this in RC3

These models have RxNum #1 

#3  Kinetic  D16
#12 Me109 Multiprotocol
#15 Corsair D8

#15 and #3 are false positives. The Kinetic uses a D16 protocol and the #15 Corsair uses D8
The #12 (Me 109) is indeed not flagged anymore as a duplicate because it's another module
![rxnum](https://user-images.githubusercontent.com/39838998/64911174-92006180-d71e-11e9-8ed1-f2514e9c0828.JPG)

**Comment by raphaelcoeffic** [comment]
No need for a new issue, I have it already covered in #6781

**Comment by notlebowski** [comment]
If I add things to a closed ticket it stays unclear if they are addressed.
I have also added several comments to the X12S conversion ticket, but nothing is done with it. 

Radio conversion of my setup is not done perfectly. 
This worries me as the very minor glitch on my setup could be a major one on other's. 

Although I understand it somewhat, I think that tickets are closed too fast without giving the OP a chance to confirm it.

**Comment by 3djc** [comment]
Closing ticket with commits a is basic git mechanism. If after a fix you are still having an issue, open a new one

**Comment by notlebowski** [comment]
But is it fixed as in that it doesn't occur anymore?
Or you've decided to not differentiate between protocols?

I would fully understand that in case of the MPM, but I think an exception could be made for the native Frsky protocols.

**Comment by kilrah** [comment]
A match will only be reported if same number with same protocol on same module.

**Comment by notlebowski** [comment]
OK
Full fix. Even better!

**Comment by raphaelcoeffic** [comment]
@Kilrah with the latest patch, it is with the same protocol on ANY module.

**Comment by kilrah** [comment]
Then it's wrong becasue the very fact the modules are different excludes a clash...

**Comment by raphaelcoeffic** [comment]
Why? Let’s say I have a model on internal XJT/D16/5 and a model on external XJT/D16/5. Wouldn’t they clash? Or is it prevented by the module internal ID?
If this is the case, we can compare module # as well, no problem, but it works this way. Will just exclude a bit more (said case previously).

**Comment by raphaelcoeffic** [comment]
Apart from that, comparing just the module is really wrong, as you could exchange modules. Many people switch between MPM and crossfire for instance.

**Comment by 3djc** [comment]
No they would not clash, the bind is unique to a module. If you bind a receiver as '10' on your internal XJT, and another as '10' on external XJT module, they do not clash

**Comment by raphaelcoeffic** [comment]
Ok, so let’s have module AND protocol and finally be done...

**Comment by kilrah** [comment]
Why? Let’s say I have a model on internal XJT/D16/5 and a model on external XJT/D16/5. Wouldn’t they clash? Or is it prevented by the module internal ID?

Yep, module ID being different makes that fine.

> Apart from that, comparing just the module is really wrong, as you could exchange modules. Many people switch between MPM and crossfire for instance.

Precisely, if it's a different module you are allowed to have the same RX number without risk of clashing.
The one exception is someone using 2 multis and defining the same forced ID for both, but then it's their problem (and they likely did it do "deactivate" the whole purpose of having a model number in the first place anyway)

**Comment by raphaelcoeffic** [comment]
Protocol and module matching has been implemented and merged, will be in RC4.
