### ISSUE TITLE
RC3 opentx-x10-lua-noheli-en compilation error

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#6787]

**Comment by kilrah** [comment]
Hmm server/build hiccup again..

![Clipboard01](https://user-images.githubusercontent.com/6065069/64917867-16da9200-d796-11e9-8522-904507c9c350.png)

opentx-x10-lua-noheli-en apparently failed for no reason at some point, strangely there is a opentx-x10-noheli-lua-en that got called/built which should be the same thing, and when I removed the .err opentx-x10-lua-noheli-en built fine again.

**Comment by 3djc** [comment]
Fixed
