### ISSUE TITLE
Horus X10 iXJT upgrade not working

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#6790]
Hi folks,

Following the great tutoriel [Extracting Horus internal RF firmware](https://github.com/raphaelcoeffic/horus_frk) of @raphaelcoeffic I generated the attached .frk firmware for a friend (he is running the ACCST LBT)  → [X10-X10S_LBT_1.3.04.zip](https://github.com/opentx/opentx/files/3616202/X10-X10S_LBT_1.3.04.zip)

Unfortunately he is always getting an error message just after the black screen with **"Device Reset"** information.
Same issue with the FCC version → [X10-X10S_FCC_1.3.04.zip](https://github.com/opentx/opentx/files/3616200/X10-X10S_FCC_1.3.04.zip)

I don't know if it is a radio bug on the Horus X10 or something else.

I tried the same procedure on a LBT and a FCC Horus X12S and it did work perfectly.

**Comment by 3djc** [comment]
Reproduced

**Comment by LapinFou** [comment]
Good!
Thanks. 👍
