### ISSUE TITLE
[SD Card] Adding a LUA script or built-in menu to switch ACCST mode on EXPRESS radios

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#6796]
Hi folks,

The new FrSky radio with an ISRM RF module have got the ACCESS and the ACCST D16 protocols.
The FrSky RF firmware doesn't make a difference between the ACCST D14 FCC and the LBT mode.
The only way to switch from one norme to another one is through a LUA script provided by FrSky.
I know it is working for the X-Lite Pro/S ans the X9-Lite. I don't know for the new Horus EXPRESS and the X9DP+ 2019.

It would be very handy to have this script included in the official SD card pack. Or, even better, a built-in menu in the OpenTX.

Here is the LUA script provided by FrSky:
**DELETED**

**Comment by 3djc** [comment]
Since this script is completely illegal, this script is not publicly provided by frsky, or us

**Comment by LapinFou** [comment]
??? Looks like Frsky send by email this script to one member of the French Taranis forum.
So, I don't see any legal issue.
Despite the origin of the script, how can we switch the ACCST norm on a ISRM RF module ?

**Comment by raphaelcoeffic** [comment]
@LapinFou normally you're not supposed to. In the email your friend received, it was probably written that he must not forward it to anyone, just like in the email I received as I asked for it ;-) I think this is a RF regulations issue.

**Comment by LapinFou** [comment]
OK, indeed he didn't tell me. 😄 
I deleted the script.
So, does it mean if you buy a FCC ISRM radio, there is no legal way to switch it in LBT? 😨

**Comment by raphaelcoeffic** [comment]
The support will help you if you make them clear that you did it "by mistake" and you want to go legal by reprogramming your module to match your region.

**Comment by LapinFou** [comment]
Thanks! 👍 
Good to know, specially for European people buying staff directly in China...

**Comment by kilrah** [comment]
Normally the dealers have been giving the script to people who are in an FCC region but got the EU version by mistake (especially since... an update mistakenly switched FCC radios to EU) but not the opposite. If you're in EU, buy an EU version and support your "local" dealers.

**Comment by lshems** [comment]
As I understood there is no FCC certification yet for this module, so perhaps the retailers should be adviced not to sell it at all to FCC users?
