### ISSUE TITLE
Taranis Q X7 double entries with mixers

### ISSUE THREAD

**Issue by SjDost** [opentx/opentx#6803]
I noticed when reading models from the Taranis Q X7 (rel X7-2.2.4) that double entries are created in the Mixers. It looks that this happens only with Mixers above Ch20.
Companion used is OpenTX 2.2.4 Jul 11, 2019.
Attached are the OTX file and the corresponding ODT and PDF files. The issue is above CH20.
Regards SjDost

[Double mixer lines.zip](https://github.com/opentx/opentx/files/3625785/Double.mixer.lines.zip)

**Comment by 3djc** [comment]
Could you add you eeprom file ?

**Comment by SjDost** [comment]
Sorry but what do you need exactly? The Eeprom file on the SD card is empty
apart from the readme file.
Do you need de firmware files I can download in Companion?
Regards SjDost

**Comment by 3djc** [comment]
You need to go to that screen ON THE RADIO and LONG ENT to create an EEprom backup that you will then find in the EEPROM folder of your SD

![image](https://user-images.githubusercontent.com/5167938/65142027-19e1b680-da12-11e9-82a6-a74551dec07f.png)

**Comment by SjDost** [comment]
Added the requested Eeprom Bin file. 
[EEPROM.zip](https://github.com/opentx/opentx/files/3625995/EEPROM.zip)

**Comment by SjDost** [comment]
Now the correct EEPROM file requested. Sorry or the confusion on my part..
[eeprom-2019-09-18-125438.zip](https://github.com/opentx/opentx/files/3626028/eeprom-2019-09-18-125438.zip)
