### ISSUE TITLE
RSSI telemetry not manageable.  9XR (2.2.4)  OrangeRX(DSMX11) Jumper JP4in1 Multi-Protocol Module

### ISSUE THREAD

**Issue by gweep** [opentx/opentx#6806]
RSSI telemetry not manageable.  
Turnigy 9XR (2.2.4)
OrangeRX R620v2(DSMX11) [Also R720v2]
Jumper JP4in1 Multi-Protocol Module

With telemetry setup, the RSSI displays on the main screen as "signal bars" above the box for the left stick.  It also is displayed in in small type as a number in the footer of every telemetry screen setup to display bar charts.  

However RSSI does not show up in the Model Setup/Telemetry screen as a manageable data selection.  A full page of data from the receiver is available in the Model Setup/Telemetry screen for the user to manage and display in the Model Setup/Display screens.  RSSI is not included.  

Clearly RSSI is available from the receiver and is processed by OpenTX.   Perhaps Spectrum elected to omit the data but the OrangeRX receiver sends it anyway?

It would be nice to be able to display RSSI in big numbers on the telemetry screens and write logs.  

I also note that the Model Setup/Display screen offers to show 4 lines of data (Numbers) but only 3 lines are visible in the display.   The display does show all 4 lines in Bar format.

**Comment by raphaelcoeffic** [comment]
Silly question: have you done the sensor discovery on the model setup -> telemetry page?

**Comment by gweep** [comment]
Yes.  I even deleted them all and started over.

I also note that the Display screen offers to show 4 lines of data (numbers and bars) but only 3 lines are visible in the display.

**Comment by kilrah** [comment]
Spektrum gear does not give an RSSI. You might have a TSSI in your sensors, which is the strength of the received telemetry.

**Comment by gweep** [comment]
Yes TRSS show up and is manageable.   

Getting back to RSSI; even though it is not expected... RSSI is received from the OrangeRX receiver and is displayed by openTX.   Hence it could be made available to manage and display.

**Comment by kilrah** [comment]
What you see displayed is the TRSS that is fed to the RSSI mechanism since that's the closest thing that's available. You just have to know its limitations.

**Comment by gweep** [comment]
I have doubts about the TRSS value being displayed as RSSI.   The TRSS values and the RSSI values differ by over 30 to 40 dB.    I can't imagine that the TRSS values are being bumped internally before being displayed.    I don't believe that the difference is constant.  

I will take picture of the TX screen this weekend.  It displays both numbers.

**Comment by kilrah** [comment]
Sorry it's not TRSS, it's based on Frame Loss A.

https://github.com/opentx/opentx/blob/2.3/radio/src/telemetry/spektrum.cpp#L321

**Comment by kilrah** [comment]
See the code here, depending on the receiver "RSSI" is either fed by TRSS * 3 or Frame Loss A if it's a clone receiver that transmits this.

https://github.com/opentx/opentx/blob/2.3/radio/src/telemetry/spektrum.cpp#L321

**Comment by gweep** [comment]
Thanks!  That clears it up.   It also explains why my RSSI does not change when I switch to low power for a range check.

Thanks

**Comment by 3djc** [comment]
Just as a side comment, low power has been disabled in recent multi builds, so unless you are compiling yourself and have re enable low power, it might not be available
