### ISSUE TITLE
Toggle switches do not work an connectors P20 and P32

### ISSUE THREAD

**Issue by kaeuferrot** [opentx/opentx#6809]
I installed OpenTx RC4 on my Horus X12S because I read that additional switches are supported with 2.3. On my sticks, I have to additional toggle switches which were connected to P20 and P32 on motherboard. In the hardware menu I can see the switches SI and SJ and I configured them as toggle. The servo monitor shows me bars. But when toggling, nothing happens. Also the way of testing "There is a simple way to test if they work : go to SPECIAL FUNCTIONS screen, select an empty one, enter first column and enter, your cursor should blink. Move your switch, if it appears here, it is working correctly " 3djc described in the 2.3 discussion thread was not successful.

**Comment by 3djc** [comment]
Please test tomorrow’s nightly, some changes have been done to try to fix this.

**Comment by kaeuferrot** [comment]
Unfortunately I am not able to download the nightly even I reinstalled the N94-companion. The BIN file I get is only RC4. It was installed when I opened the issue.

**Comment by 3djc** [comment]
You need to have companion set to download nigthlies (which should be possible with N94 companion)

**Comment by kaeuferrot** [comment]
Great! It works now! Many thanks!

**Comment by 3djc** [comment]
👍 thanks for the test !

**Comment by kaeuferrot** [comment]
I can see the switches toggling and they are recognized when moving them. Servo monitor also shows moves. I tried to implement a special function, when pressing the key, that some values were played. But nothing happens there. With SH as a switch it works. Normally the switch name is bolded when active. Here this does not happen.

**Comment by 3djc** [comment]
What type of switch did you connect and how did you declare it ?

**Comment by kaeuferrot** [comment]
It is a toggle stick switch from RC-Technik. I declared it as toggle!

**Comment by kaeuferrot** [comment]
Acting as a channel works!

**Comment by 3djc** [comment]
Please test in RC5

**Comment by kaeuferrot** [comment]
Thank you, it works now!
