### ISSUE TITLE
18ms on 16ch?

### ISSUE THREAD

**Issue by asizon** [opentx/opentx#6813]
![img_20190921_105704](https://user-images.githubusercontent.com/43983086/65373358-ce7f1080-dc7c-11e9-88ee-900062d23c2b.jpg)

**Describe the bug**
Showing 18ms,does 9ms on 16ch now?? 
 
**General information**
 - OpenTX version 2.3.0 RC4
 - Hardware  Frsky X9D+

**Comment by asizon** [comment]
Confused with this parameter,  Does XJT latency fixes affect to this?

**Comment by 3djc** [comment]
This places is to track OpenTX bugs, which this is not, so closing this. Please use places like rcgroups or opentrc forums for this type of questions

**Comment by asizon** [comment]
Sorry @3djc , I thought it was a mistake of the opentx UI, not showing 9ms as it should.
