### ISSUE TITLE
2.3 RC4 minus button in LUA triggers twice

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#6814]
On taranis (didn't check others) the minus button triggers the LUA event twice. The plus functions correctly.

**Comment by 3djc** [comment]
What event are you monitoring ?

**Comment by lshems** [comment]
The 'old' ones.

**Comment by lshems** [comment]
The 'old' ones. I just run my scripts and get double response on minus button. So something has changed.

**Comment by kilrah** [comment]
Haven't been able to reproduce, so if it's still an issue in RC5 we'll need more detail and affected code.

**Comment by lshems** [comment]
Ok. I'll try and make a demo script. Something has changed between RC1 and the RC4

**Comment by ExaflopS** [comment]
I have found that now in release version 2.3.0, minus button makes one - and one + step by pressing once.  If I click -, the value remains same, only way is to hold - button to go to lower values and then use + button to go to desired value. however it is impossible to get value 0, because it always jump to 1.

**Comment by 3djc** [comment]
I'm not seing that here at all. Here you can find scripts to test and new and old events : https://github.com/opentx/opentx/tree/2.3/radio/util/lua

Plus and minus seem to be working ok here

**Comment by ExaflopS** [comment]
I Have tested Yours test scripts. + and minus worked good, but only lua_old_event_check.lua worked in full. In lua_event_test.lua only next and previous are working , enter, menu, next rept, previous rept, next page and previous page are not responding.

**Comment by 3djc** [comment]
Yes a fix for new events has been done this afternoon and will be available in tomorows nightly

**Comment by lshems** [comment]
For one reason or another, in the Taranis there is now a EVT_DOWN_BREAK event triggered after the release of the minus. this wasn't the case on 2.2.4.

The EVT_DOWN_BREAK should only be triggered for Xlite type radios.

**Comment by lshems** [comment]
I'll close this as the root cause is a clear bug. This is just the effect in my scripts.
