### ISSUE TITLE
Unable to remove telemetry screens

### ISSUE THREAD

**Issue by BladeScraper-Designs** [opentx/opentx#6816]
I looked around in the list of issues and didn't see anyone describing the issue I'm having.  

**Describe the bug**
If I try to remove a telemetry screen on the radio, the radio soft freezes, and scrolling the wheel or pressing the buttons on the left side don't do anything.  The only thing that un-freezes it is pressing the RTN button.  Once unfrozen, the screen is not removed.  This happens on the radio itself and also in the simulator.

**To Reproduce**
1. Go to TELE menu
2. Go to a telemetry screen you want to remove (create a new one if necessary)
3. Scroll down to remove screen
4. Press enter.  

Nothing happens.

**Expected behavior**
The screen to be removed.

**General information**
OpenTX 2.2.4
FrSky Horus X10S

**Comment by kilrah** [comment]
You need a long press on "remove screen".
