### ISSUE TITLE
Companion 2.2.4 can't extract RADIO/radio.bin

### ISSUE THREAD

**Issue by adrienbarde** [opentx/opentx#6823]
Hello everyone,

i just recieved my new stock X-lite pro and i can't read or save models from it.

1- I configured companion to "X-lite radio"
2- I booted my radio in bootloader mode
3- connected via USB
4- but, when i try to get models from the radio a get the following error "Can't extract RADIO/radio.bin"

I copied all files to the SD card 2.3v0019 (from frsky site)

**Screenshots**
![image](https://user-images.githubusercontent.com/5081583/65512968-9543dc00-deda-11e9-92ad-08d7c354b359.png)

**General information**
 - SD Card  2.3v0019
 - Hardware (X-lite Pro EU)
 - OpenTX Companion (2.2.4)
- Windows 10 64bits

**Comment by kilrah** [comment]
X-Lite pro isn't supported in 2.2, need 2.3.

**Comment by adrienbarde** [comment]
OK thank you for your help!
