### ISSUE TITLE
Disable "Hold to Turn on" on QX7 

### ISSUE THREAD

**Issue by mroldskool90** [opentx/opentx#6825]
In the earlier versions of OpenTX I could easily turn on the radio by just pushing the ON/OFF Button. Since I updated to V2.2.2 I always have to hold down the Button for turning the radio on or off.
Please! Please, make an option to turn this feature of. 
I see no sense for turn on prevention...
Preventing accidentally turn offs is understandable, but even this shoud be configable. 
Everyone with telemetry already has an extra safety net by getting the message "reciever is still connected".

"Hold to Turn on" and "Hold to Turn off" could be checkboxes in the radio settings and could be on by default.

Thanks for OpenTX in general!!

**Comment by 3djc** [comment]
You see no sense, it doesn't mean that there isn't. Anyhow configurable in 2.3
