### ISSUE TITLE
Compile 2.3 using QT Creator-Windows full "install" does not install needed Qt*.dll files

### ISSUE THREAD

**Issue by MRC3742** [opentx/opentx#6831]
**Describe the bug**
Compiling using Qt Creator 5.7.1 and MinGW 5.3.0 on Win7 32bit will compile correctly but doing a full windows install will not install any of the Qt*.dll's to the same directory. This causes Companion unable to start because of the missing files. This "install" build worked properly compiling in 2.2 but since I started building 2.3 a few months ago it has not worked properly.

**To Reproduce**
1. Compile 2.3 using Qt Creator with Build Steps "Build: cmake.exe --build . --target install"
2. After successful build only 12 files will be located in install directory with no Qt*.dll's
3. Companion will not run without these dependent files.
4. Screenshot of Compile Output below.

**Thoughts**
The problem seems to be in "/2.3/companion/src/CMakeLists.txt" at lines 409 - 430 " # Qt dlls (using windeployqt)" as this section has changed from version 2.2. Please review.
Possible Win7 32 bit issue? or different needed dependencies?

**Screenshots**
![Install_Error](https://user-images.githubusercontent.com/26642502/65624649-52483e00-df98-11e9-86d4-b9783c05315c.jpg)

**General information**
 - Building on Windows 7 32bit
 - OpenTX version 2.3.0RC5
 - Compile build for PCB X9D+ Rev 2014

**Comment by KingKnecht** [comment]
Had the same issue. I was told, that the "install" target is for Linux only. I have used "all" and it worked for me.
