### ISSUE TITLE
OpenTX 2.3.0RC5 X9D 2019 not booting

### ISSUE THREAD

**Issue by Hillgoonfpv** [opentx/opentx#6834]
**General information**
 - OpenTX version 2.3.0RC5
 - Hardware Frsky X9D+ 2019

After flashing firmware, radio will not boot. While holding the power button the splash screen shows but disappears when you let go but it never has a backlight.

**Comment by 3djc** [comment]
Looks like you are flashing a wrong firmware. What is the exact name of the firmware file ?

**Comment by bsongis** [comment]
Please reopen if needed
