### ISSUE TITLE
Menu navigation

### ISSUE THREAD

**Issue by RookFPV** [opentx/opentx#6840]
Bf.lua - When in the menu e.g. VTX I want to change e.g. channel, I can't slide down, I can only navigate only up

Crossfire.lua - Navigation up or down is reversed ... when I move the cursor up the menu goes down

**General information**
Betaflight Script 1.3.0
 - OpenTX version (2.3.0)
 - Hardware Frsky X9D+
 - OpenTX Companion 2.3.0 windows

**Comment by 3djc** [comment]
Yeah, for some reason the script expect a + event to increment value, but a - to go to next field, which got me confused. Will fix the script tomorrow

**Comment by kilrah** [comment]
That's becasue on X9D it is intuitive to press the DOWN button to go DOWN in the fields, but the DOWN button is -.

**Comment by 3djc** [comment]
Then we need to add another virtual event to distinguish inc/dec and previous/next
