### ISSUE TITLE
Sensor ID with 2.3.0 Horus 12S

### ISSUE THREAD

**Issue by aviat40** [opentx/opentx#6848]
Hello,

With new 2.3.0 version, the sensors Id on a Horus 12S are displayed with 3 numbers.
Example RSSI and RXbt are displayed as 245.. instead of 25.

BUG ?
Thks

**Comment by 3djc** [comment]
Not necessarely, Sensors in 2.3 can have different sources (internal, external, several receievrs in ACCESS), all that information is 'added" to the sensor ID

**Comment by aviat40** [comment]
Morning,
OK, but where to find this ID description ? just for my info .
Thks
