### ISSUE TITLE
ACT switch setting not recognized in companion

### ISSUE THREAD

**Issue by Tygrys-1** [opentx/opentx#6851]
When ACT is set as a switch option in the simmulator or on the radio (i.e. on the mixer), the companion editor changes it to --- after loading the settings. Also, there is no ACT setting in the companion editor.

**To Reproduce**
Set ACT as an switch option in the radio or simmulator, save the settings and open them in the companion.

**Expected behavior**
Companion should have the ACT setting added to the switch options and stay consistent with the radio. An explanation to this option should be added to the documentation.

**General information**
 - OpenTX version (2.3.0)
 - Hardware (Frsky X9 Lite Pro)
 - OpenTX Companion (2.3.0 on Win64)

**Comment by 3djc** [comment]
What exactly do you call ACT ? Not sure we understand what you mean

**Comment by Tygrys-1** [comment]
It is the one of the switch options to choose, like SA-, ON or TELE. I think it is new to 2.3.
For what I gather it is acting like momentary pulse of "true", when the rule or the condition is activated.
Just like ON is true all the time, ACT is true for a moment.
At least I have this setting on the radio as a "Switch" to choose ;-)

**Comment by Tygrys-1** [comment]
![obraz](https://user-images.githubusercontent.com/38982807/65832612-5ccf4400-e2c6-11e9-9884-b139af5d3b49.png)

**Comment by notlebowski** [comment]
@Kilrah
What does Act do?

**Comment by 3djc** [comment]
Any action on the radio triggering inacctivity timer to reset do also triggers Act to be true for a short period of time

**Comment by notlebowski** [comment]
Hey.   I requested that years ago
I had some ideas for that

**Comment by notlebowski** [comment]
I just looked at that request and now I remember...
I wanted to use it to enable a throttle safety, but I can't do it the way it is implemented now because "delay" can't be more than 25 seconds...

Otherwise I could use this trigger to invoke throttle safety

AND  !Act delay(180s)

At the time I was looking for a trigger that would become true if the inactivity becomes true.
I may still be able to use this trigger for that using the timer function...

BTW...    Why is delay limited to 25s and is it hard to make that longer?

**Comment by kilrah** [comment]
One 8-byte value available with 0.1s increments.

**Comment by notlebowski** [comment]
@kilrah 
I'm considering to use timer3 and set that to 3 minutes and let ACT reset that each time.
Whenever timer3 = 0 I can use that as a logical switch and that could invoke throttle safety

I think it's a bit ugly to use a timer for that. Do you have a tip for a more elegant solution to get a non-activity trigger that acts like:

L6 ( Thr < -95 ) AND !Act↓ Delay(180s)

It's an extra safety measure that will invoke a throttle safety after 3 minutes of inactivity if you forget the radio and want to avoid that someone bumps the throttle stick.

**Comment by kilrah** [comment]
You can stack 2 LSs and declare that 50sec is enough...

**Comment by notlebowski** [comment]
@kilrah Yes, I think I will do that. 50s is a long time to have both inactivity and no throttle.
