### ISSUE TITLE
X9D Systemmenue/Hardware: serial port function can not be accessed

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#6856]
X9D 2013
Highlighting and accessing serial port function is not possible in the radio system menue. It is blocked like RTC voltage above, where it makes sense.

Changing the setting with companion works.

**Comment by kilrah** [comment]
The 2 debug "buttons" can't be selected either

**Comment by kilrah** [comment]
X9D only, X9D+ is OK
