### ISSUE TITLE
From Mike: Shift in X9D/X9D+/X-lite sources

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#6860]
Telemetry Display Values X9D Plus - 2.3.0.
“Time” displays TX battery value
“GPS” displays TX time. Not sure where "GPS" is coming from because there is no "GPS" sensor showing on the Telemetry page. 
Not sure if there are other examples.

**Comment by RipperDrone** [comment]
confirmed today on X9DP 2013, GPS displays time.

**Comment by RipperDrone** [comment]
@kilrah Still not ok, tested with 2.3.1 N2 Nightly and matching firmware. GPS still displaying time...

Found that there were Travis errors in the PR. How's the procedure: PRs are merged even though Travis checks fail? Would just like to understand the sequence, so I start testing at the correct point in time... :-)

**Comment by kilrah** [comment]
Obviously since N2 was made 8 hours before this was merged.

**Comment by RipperDrone** [comment]
Good point, I haven't checked time details. Still curious: Commits can be merged ok even though Travis checks are failing? So whenever build date of a Nightly is later than Pull Request X, then it will be included? Like this one which did not pass Travis...
![image](https://user-images.githubusercontent.com/12601105/66000308-6b248800-e49f-11e9-8354-4120b5a59e51.png)

![image](https://user-images.githubusercontent.com/12601105/66000338-8099b200-e49f-11e9-9a92-9b00586a439c.png)

**Comment by kilrah** [comment]
If you look in #6857 you will see "2 checks passed", which means the changes introduced by that PR would build correctly. It's more prominent with a lot of green above the merge button while it's still pending.
It just so happens that something else had broken the commit tests on the 2.3.1 branch in the meantime, so anything done on that branch after it would fail automatically.

Tests are very helpful, but you have to dig into the details to understand the reason for failure which can be completely unrelated to what you're interested in.
And yes when something is merged it will be in the next nightly. Most of the currently active devs are in Europe, so nightlies are set to run at around 4AM CET while they're (usually) sleeping and not commiting.

The one you refer to - it was trivial so we didn't wait to merge it, but the tests had been written for an expectation that was no more in line with the new behavior so they failed. The PR was good, but the test needed to be changed whch was done shortly after.

**Comment by RipperDrone** [comment]
looks good on X9DP now (2.3.1N5).
