### ISSUE TITLE
Companion 2.3 missing external module protocols

### ISSUE THREAD

**Issue by kilrah** [opentx/opentx#6863]
For XLite:
R9M
R9M Access
R9M Lite ACCESS
R9M Lite Pro ACCESS
XJT Lite

Not checked others

**Comment by kilrah** [comment]
And "R9M Mini" instead of Lite is a string hack that actually sets R9M...

Whole list needs reworking

**Comment by Maceyee** [comment]
Is this why my r9 module won't respond to bind command

**Comment by kilrah** [comment]
If you set the proper module type on the radio then no.

**Comment by Maceyee** [comment]
how do i contact you via e-mail i would really appreciate some help here
