### ISSUE TITLE
2.3.0 RAS Issues

### ISSUE THREAD

**Issue by MIKE-DAILEY** [opentx/opentx#6866]
There might be something not right with 2.3.0 RAS:

RAS display ---/---on systems using Hardware Menu
It is 0/--- on the X9D Plus 2019 
It is 0/--- on the X-Lite - Pro RAS working with external antenna selected and RAS script works. 
It is ---/0 on the X9D Plus – RAS number works, but not RAS script.  Should the RAS number be on the right or left?  

RAS on Statistics /Analogs 
X12S Developer – RAS not working stays at 0.

**Comment by robustini** [comment]
Already reported...

https://github.com/opentx/opentx/issues/6775

**Comment by kilrah** [comment]
Indeed, duplicate

**Comment by MIKE-DAILEY** [comment]
That does not cover this part:

RAS display ---/---on systems using Hardware Menu
It is 0/--- on the X9D Plus 2019
It is 0/--- on the X-Lite - Pro RAS working with external antenna selected and RAS script works.
It is ---/0 on the X9D Plus – RAS number works, but not RAS script. Should the RAS number be on the right or left?

**Comment by kilrah** [comment]
It's supposed to be Internal/External
The other issue encompasses revising RAS on all platforms.

**Comment by MIKE-DAILEY** [comment]
All three systems were using the external antenna?

**Comment by kilrah** [comment]
Internal/External **module**.

**Comment by MIKE-DAILEY** [comment]
All three were on the internal module.  So the X9D Plus should be 0/--- not ---/0?

**Comment by kilrah** [comment]
Yeah, as I said everything needs reviewing.

**Comment by parm0** [comment]
Any update on this yet? My x9d+ is still showing - - - /0 on the latest firmware. The 0  does work for the internal module though, if I shield antenna it goes up to 16.

**Comment by MIKE-DAILEY** [comment]
Working correctly now in the latest 2.3.8 nightly.
