### ISSUE TITLE
No SI/SJ support on X7

### ISSUE THREAD

**Issue by twistedwings** [opentx/opentx#6867]
according to #5330 "X7/X10/X12: Support for additional switch inputs"
they should be there in 2.3 but they are not, neither in companion nor the radio.

Taranis X7
OpenTX 2.3.0

**Comment by 3djc** [comment]
Have you declared them in RADIO/HARDWARE on your radio ?

**Comment by twistedwings** [comment]
now I have and it does work.
Thank you!
