### ISSUE TITLE
Retrieve settings from profile - error message in companion

### ISSUE THREAD

**Issue by ParkerEde** [opentx/opentx#6868]
after updating to 2.3.0 (companion and horus X10S)
1. Button click: read models and settings from radio
2. Button click: Edit Radio settings
3. Button click: Store calib. and hw settings in selected profile
4. Button click: Retrieve calib. and hw settings from profile
Error message: Wrong data in profile, hw related parameters were not retrieved

**Comment by ParkerEde** [comment]
![otx hardware profile](https://user-images.githubusercontent.com/15068446/65890127-b147f180-e3a2-11e9-86ff-95ca6d5cfd2c.jpg)

**Comment by ParkerEde** [comment]
unstale...

**Comment by elecpower** [comment]
Does not occur from 2.3.8 onwards. Not sure what PR fixed.
