### ISSUE TITLE
Taranis qx7: Switches SI / SJ

### ISSUE THREAD

**Issue by QuaxBruchpilot** [opentx/opentx#6872]
These Switches are not supported (EEPROM 219). Testscreen: SI is , but SJ is not displayed

**Comment by 3djc** [comment]
Duplicate #6867 ?

**Comment by QuaxBruchpilot** [comment]
I think not. I declared the switches SI/SJ as push bottons. On the test-screen the SI is the last line but without testfunction. SJ is not displayed on the test-screen. It is not possible to scroll further.
