### ISSUE TITLE
SD Card Contents Link for X10 Express in Companion- Wrong URL

### ISSUE THREAD

**Issue by eovnu87435ds** [opentx/opentx#6874]
If you open the download window, and try to download the SD Card contents for the X10 Express, Companion TX brings you to https://downloads.open-tx.org/2.3/release/sdcard/opentx-x10express/ when it should actually bring you to https://downloads.open-tx.org/2.3/release/sdcard/opentx-x10-express/

**Comment by 3djc** [comment]
Fixed, thanks for the report
