### ISSUE TITLE
[2.3.0] - ISRM D16, missing antenna selection?

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#6876]
I don't know if it's a bug, coming from the X12S where it was possible to select the antenna (INT or INT+EXT) I don't see this option in the ISRM module set in D16 on Horus X10S Express ACCESS.
At present it would be useful to understand if use all three antennas or only the two internal ones, in the first case removing the external one could damage the module without any warning since currently the RAS is not working.

**General information**
 - OpenTX: V2.3.0
 - Hardware: Horus X10S Express ACCESS
 - OpenTX Companion. irrilevant

![isrm_ant](https://user-images.githubusercontent.com/3864712/65950391-3fbd8100-e43e-11e9-9ef1-12eb8918ee59.jpg)

**Comment by ParkerEde** [comment]
Hi, since 2.3.0 it's possible to set the antenna configuration in hardwaresettings . You can choose between "internal", "external" "ask" and "per model".
If you want to set it in the modelconfiguration, please choose "per model". X10 can only use internal or external antenna. Not both at the same time.

Regards

**Comment by robustini** [comment]
I don't see this option inside "HARDWARE" on my X10S Express with 2.3.0.

**Comment by kilrah** [comment]
For ACCESS modules the antenna gets selected in the "Options" page.

**Comment by robustini** [comment]
The antenna selection is available only by selecting ACCESS protocol, it does not seem very correct, if i use D16 should be visible already in the model menu.
I don't look very elegant where to go in ACCESS if the protocol I want to use is D16.

**Comment by kilrah** [comment]
It's not related to the protocol, it's related to the module type. You're not "going in access", you're going where an ISRM needs you to go.

**Comment by robustini** [comment]
When i've ISRM (the module) on the screen and D16 (the protocol) there's no option to select the antenna, this i mean.
"Option" appears only when the ACCESS protocol is set! :)

**Comment by kilrah** [comment]
You have it in your capture above...

![65950391-3fbd8100-e43e-11e9-9ef1-12eb8918ee59](https://user-images.githubusercontent.com/6065069/65972984-e7e93f00-e46a-11e9-922e-9985c7787a8f.jpg)

**Comment by robustini** [comment]
Damn, you're absolutely right, I've seen it now, I'm sorry! :P

**Comment by pandjarov** [comment]
When the checkbox is placed does the external antenna work with the two internals or they get switched off?

**Comment by robustini** [comment]
> switched off

Switched off.

**Comment by brainbubblersbest** [comment]
no i dont think so. are you shure?
ixjt worked with both antennas. (one in and one extern)
isrm has two intern and one extern.
isnt it that only one internal antenna switches off and the external antenna is used with the other internal antenna?

in that case. extern is vertical mounted
the intern antenna thats been not switched off is horizontal mounted?

**Comment by robustini** [comment]
ISRM does not make diversity between external and internal.

**Comment by brainbubblersbest** [comment]
So whats the purpose of a single 2,4ghz dipole compared to
two 2,4ghz pcb antennas? Have you compared the rssi/range?

I believe you but thats a bit weird, because the ixjt used both.

**Comment by robustini** [comment]
> So whats the purpose of a single 2,4ghz dipole compared to two 2,4ghz pcb antennas? Have you compared the rssi/range?
> 
> I believe you but thats a bit weird, because the ixjt used both.

I haven't noticed many differences between internal and external.

**Comment by Hlaalu11** [comment]
>  in the first case removing the external one could damage the module without any warning since currently the RAS is not working
> 

Forgive my ignorance, but how does removing the external antenna cause harm to the module, if RAS is not active?
