### ISSUE TITLE
Where is the "baudrate" setting in 2.3.0?

### ISSUE THREAD

**Issue by ps915** [opentx/opentx#6884]
I noticed, that the baudrate setting on the "hardware" page is gone!
Where can i find it? On which baudrates does 2.3.0 run now?

**Comment by kilrah** [comment]
What radio, what context, what feature are you looking at,...

**Comment by ps915** [comment]
I am looking at the "baudrate setting" of the Taranis QX7 which was on the "hardware" page. I want to lower the baudrate to 115200 to use the Crossfire TX Module without telemetry warnings.

**Comment by 3djc** [comment]
Then same place as before 

![image](https://user-images.githubusercontent.com/5167938/66133138-70481b00-e5f6-11e9-9c34-633f10bde5be.png)

**Comment by ps915** [comment]
Ok, my bad! Thanks

**Comment by Raziel1989** [comment]
Hello! In my opinion it's not in the same place before. It's missing and I can't find it ahywhere :( 
Open TX 2.3.15

**Comment by 3djc** [comment]
@Raziel1989 what radio? And what 2.3.15, you mean nightly?

**Comment by Raziel1989** [comment]
@3djc Taranis QX7 Access. I'm trying to configure Crossfire module and I get the syntax error. In some other topic I found that changing tha max bauds will fix the syntax error problem.

Yes, Nightly build 2.3.15. Schould I try official one ?

**Comment by 3djc** [comment]
I'll have a look at that model tomorow

**Comment by 3djc** [comment]
@Raziel1989 X7 ACCESS does not display the option, and never has apparently. I'll add it, and you can check tomorows nightly (549) to see if it helps your issue

**Comment by Raziel1989** [comment]
@3djc Meanwhile I fixed my problem so maybe no update is needed.
This article helped me: https://fpvfrenzy.com/tbs-crossfire-setup/ 
In the middle of article there is sentence:
"f that still doesn’t do the trick, download these scripts by GitHub user OhmEye and replace the existing scripts in the Crossfire folder with these. Run the script again and it should now work."
And it worked for me. Totally don't know what is the difference between this files and original ones but it works. No more syntax error showing while I'm trying to configure crossfire RX or TX. Today I'll do my first test flight so we wille se if there are any telemetry warnings.

**Comment by alec-bip** [comment]
Hi everyone,
I have a problem on my Taranis QX7 when it comes to adding the TBS CROSSFIRE MICRO TX II. First of all I have soldered the little piece according to videos and forums I saw and then I should be able to change : external RF —> CRSF. However, this option does not appear when I turn the right wheel. Therefore, some forums and videos I saw told me to change “max bauds” from 400000 to 115200. However, the “max bauds” does not appear in the hardware page (6/7). I have the version 2.3.0. 
Please help me I am desperate

**Comment by kilrah** [comment]
You likely have FrSky's factory firmware, that has CRSF taken out. Flash regular OpenTX.

**Comment by kort0175** [comment]
I am having the same problem with my X9D plus. Flashed 2.3.14 and it says that version on the last tab but I have no max baud line in the hardware tab.

**Comment by 3djc** [comment]
> I am having the same problem with my X9D plus. Flashed 2.3.14 and it says that version on the last tab but I have no max baud line in the hardware tab.

Nor should you, as far as we know all x9d+ are capable of 400k, hence the reduced speed at 115k is not offered

**Comment by kort0175** [comment]
The problem is when I try to use the Lua script for my ELRS module it hangs

**Comment by 3djc** [comment]
Well the issue was never reported for any crossfire module that use the same protocol, so it could be your module ?

**Comment by kort0175** [comment]
Maybe. I will remove and check pins tonight.

**Comment by 3djc** [comment]
I think it was added to all radio in nightlies because of similar complains, so you migh want to try a nightly (they are currently extremely stable)

**Comment by kort0175** [comment]
Will do. Thank you.

**Comment by kort0175** [comment]
Ok, tuns out it wasnt any of those things. I pulled it out and flashed it by the USB to UART method (which is how it was pinned, go figure) and am now able to get the LUA script to run. I tested it on both 400k and 115k. Both worked. Now I just need to go back to a stable release. Thank you for your help. It got me pointed in the right direction!

**Comment by poppel23** [comment]
> Ok, tuns out it wasnt any of those things. I pulled it out and flashed it by the USB to UART method (which is how it was pinned, go figure) and am now able to get the LUA script to run. I tested it on both 400k and 115k. Both worked. Now I just need to go back to a stable release. Thank you for your help. It got me pointed in the right direction!

Dear kort,
facing the same problem. running otx 2.3.14 on an x9d+ and trying to flash elrs 2.2 using the transmitter. As a result im getting a firmware update error "NoSync". The newest LUA is stuck in "Loading". Could you explain what u meant with flashing via "USB to UART"? 

I would have contacted you directly about the issue, but it seems impossible here to write a pm?!

**Comment by kort0175** [comment]
I had to plug the USB into the ELRS module board and flash it that way.

**Comment by Stekkereend** [comment]
running otx 2.3.14 on an jumper t lite and trying to flash elrs using the transmitter. As a result im getting the newest LUA is stuck in "Loading". 
baudrate option is not in the hardware tab . Also when trying to run ELRS onder tools nothing happens. When I run the lua from the scripts folder it hangs on loading

**Comment by 3djc** [comment]
You cannot flash an elrs module with OpenTX (unless you want to flash an R9M Lite to ELRS ?). As for baudrate, it will use 400k on tlite external

**Comment by Stekkereend** [comment]
Sorry , not trying to flash Elrs via the TX but only having it recognized by the t lite. As the lua script won’t run a cannot activate the bind or the wifi update of the receiver

**Comment by 3djc** [comment]
Working fine
![image](https://user-images.githubusercontent.com/5167938/154811311-20c088f5-06d9-472f-950c-e237161b79a0.png)

Are you using wrong script ?

**Comment by Stekkereend** [comment]
Need to do factory reset off the t lite I think. When  selecting the ExpressLRS line from page 1/7 nothing happens. Also have 2 identical entries there , both not doing anything

**Comment by Stekkereend** [comment]
![Uploading BD52E394-2826-4FCD-8158-938B615F0290.jpeg…]()

**Comment by Stekkereend** [comment]
![887FBD78-B8C8-46DD-A68A-3623D5954D17](https://user-images.githubusercontent.com/98787719/154813028-b6cf0f63-5a5c-402b-ba1f-205766528598.jpeg)

**Comment by Stekkereend** [comment]
![B03057B7-CB0C-4299-8215-6CB1918D1000](https://user-images.githubusercontent.com/98787719/154813066-7620470b-5cd3-4ab2-bdbd-60a3704b0ef9.jpeg)

**Comment by kilrah** [comment]
Have you set the external module type to CRSF/ELRS? Won't work until that's done.

**Comment by Stekkereend** [comment]
Flashed the module to v1.2.1 and now it’s has contact with the transmitter. Also both tx and rx are now visible over WiFi . Issues are only on V2.2.0 .

**Comment by kilrah** [comment]
2.x uses a different set of scripts so you probably just need to load and use the correct one.
