### ISSUE TITLE
ACCESS RX re-mapping channels menu not working correctly

### ISSUE THREAD

**Issue by uragano47812** [opentx/opentx#6895]
**Describe the bug**
I have the RX6R receiver binded with ISRM module of my X9D+ SE 2019 in 1-8CH mode , if i go to RX option menù and go to re-mapping channels i can't correctly scroll all the options. I can scroll from top menù to CH3 and then the cursor return to top. If i scroll the other way i can go to CH8 to CH5.
Basically i can't select CH4. You can't go above with the scroll line to select it. 

**General information**
 - OpenTX version 2.3.0
 - Hardware Frsky X9D+ SE 2019
 - OpenTX Companion 2.3.0

**Comment by kilrah** [comment]
Was fixed a while ago, works correctly in nightly
