### ISSUE TITLE
X9D - OTX 2.3.0 - Analog Inputs screen cannot be activated

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#6898]
Running X9D, OTX 2.3.0 build 2019-09-27. 
The Analog Inputs option appears as expected in the HARDWARE menu, but cannot be selected or activated (the cursor skips over it).
Applies to tx and Companion.
![screenshot_x9d_19-10-05_00-09-34](https://user-images.githubusercontent.com/6317479/66245370-52b5a700-e705-11e9-8a59-831f8fe742be.png)

**Comment by 3djc** [comment]
Navigation on this screen was broken in 2.3.0. Please try last nightly or 2.3.1 when available
