### ISSUE TITLE
X9D+ Plus 2019 doesn't bind with D16 

### ISSUE THREAD

**Issue by wascheck** [opentx/opentx#6899]
I have a problem with the new X9D+ plus 2019.
It doesn't bind with Crazybee F4 V2.1 with D16, but, this FC bind with my QX7 with D16 and works very good.
both radios are updated with Opentx V2.3
How explain that?
Any suggestion?

**Comment by 3djc** [comment]
If your quad isn't using a genuine FrSky receiver then it probably explains it. Try binding a genuine receiver and reopen if it does not work

**Comment by wascheck** [comment]
Yes, It isn't genuine as the FC has the rx. Thanks!

Em sáb, 5 de out de 2019 03:19, 3djc <notifications@github.com> escreveu:
