### ISSUE TITLE
Companion Shift+Trim not working correctly 

### ISSUE THREAD

**Issue by MikeNH** [opentx/opentx#6900]
*Before submitting,  search the open issue if there is already a report of the bug*

**Describe the bug**
I tried to reopen the original issue but it's not obvious to me how to do that. This is the original issue with updated information:
[github.com/opentx/opentx/issues/6582](url)  (I'm not sure why the link is not working but the screen print is attached.
![Trim](https://user-images.githubusercontent.com/16496376/66249253-44b05800-e6fe-11e9-9c8e-86e1933aa45e.JPG)

**General information**
 - OpenTX version 23.0
 - Hardware X-Lite Pro
 - OpenTX Companion Windows 10

**Comment by kilrah** [comment]
You cannot reopen, but we would have if there was a need after your comment. 
But it's working fine in 2.3.0 and 2.3.1, so we won't...

**Comment by MikeNH** [comment]
Thanks for the prompt response. This problem must be unique to my laptop. Feature works fine on the radio. Using the trims as switches allows for 12 channels to be in use on my quad.

Again, thanks.
