### ISSUE TITLE
[X7 2.3.1] SD card contents not available

### ISSUE THREAD

**Issue by 0crap** [opentx/opentx#6901]
I just updated my X7 from 2.3.0 to 2.3.1 and it expects 2.3V0022 SD card contents.
For other models it can be downloaded, however for the X7 it's not there.

https://downloads.open-tx.org/2.3/release/sdcard/opentx-x7/

**Comment by notlebowski** [comment]
None of the small screens have a 2.3V0022 SD-Card.
On my computer I have a 2.3V0021 version of 9/11. On https://downloads.open-tx.org/2.3/release/sdcard/opentx-x7/ It's a version of last April.

**Comment by kilrah** [comment]
Fixed

**Comment by 0crap** [comment]
Awesome!
Thx for the quick fix.

**Comment by notlebowski** [comment]
Ditto
