### ISSUE TITLE
2.3.0 / X9D - Lua script parameters incorrect after migration from 2.2.3

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#6904]
Using X9D, migrating from 2.2.3 to 2.3.0 in situ (on transmitter). 

My setup uses a mixer script. It has two parameters bound to CH24 and CH25. 
After migrating from to 2.3.0, the inputs are incorrectly bound to CH23 and CH24.

![screenshot_x9d_19-10-05_19-22-20](https://user-images.githubusercontent.com/6317479/66259209-230aab80-e7a6-11e9-8ba6-9cb596e729bd.png)

**Comment by RC-SOAR** [comment]
I've verified that It also fails when migrating to 2.3.1. It would great if this could be fixed in 2.3.2, as several users of my F3F template are using this script.

**Comment by 3djc** [comment]
Even when fixed, the fix will not apply to those who have installed 2.3.0 or 2.3.1

**Comment by RC-SOAR** [comment]
Yes, understood, and thanks for fixing.

In the meantime, I'm advising users of the script to hold off migrating their 2.2 setups until the next version.

**Comment by lshems** [comment]
You are all aware that different versions have different 'magic numbers'. Are all conversions covered? between different radio type's and different opentx versions?

perhaps some more elegant solution is possible??

**Comment by lshems** [comment]
I know, I shouldn't suggest improvements I can't create myself. Sorry for that.

**Comment by kilrah** [comment]
These are source lists, same as everywhere else in the radio, so same conversion applies. Unrelated.

**Comment by 3djc** [comment]
@RC-SOAR we have an issue with this. We have ne way to differentiate if the value represent a numeric value or a 'source index' (as in your case), as this is determined by the script itself, which we do not have access to. So it is impossible for us to do that migration.

**Comment by RC-SOAR** [comment]
So I take it the source lists have changed in 2.3? Would it be safer to pass channel numbers to scripts rather than channel values, then use getValue()? I'd prefer to avoid that, but it might be an option if it prevents migration issues with future updates.

**Comment by lshems** [comment]
Now that's a more elegant solution on the lua script side.
:)

**Comment by 3djc** [comment]
Yes source lists are usualy changing on major versions. in this case, a shift of 1 on x9d, 2 on x7, 4 on horus to allow new switches to be installed.. Closing this as there is nothing we can do on our side
