### ISSUE TITLE
Companion simulator - telemetry does not work

### ISSUE THREAD

**Issue by offer-shmuely** [opentx/opentx#6906]
telemetry does not work on simulator

**To Reproduce**
1. download a models with telemetry from the transmitter
2. run simulator on this model
3. enable telemetry
4. set the values in telemetry screen
5. check telemetry screen if it receive the information

**Expected behavior**
telemetry can be seen live in the telemetry secreen (the "*" andvaules should apear)

**General information**
 - OpenTX version 2.30
 - Hardware X10s
 - OpenTX Companion 2.3.0 & 2.3.1 on windows 10

![image](https://user-images.githubusercontent.com/7026911/66264973-4d488180-e817-11e9-902c-78735c18c928.png)

Note that the ID is looking strange

![image](https://user-images.githubusercontent.com/7026911/66265019-f7c0a480-e817-11e9-9277-cad1912b6d06.png)

**Comment by kilrah** [comment]
Duplicate #6862

**Comment by offer-shmuely** [comment]
Thank
Sorry for the duplication.

I think it better to label all this type of issues with “companion” label, 
I did check for same issue before i posted, but i filtered by “companion”
