### ISSUE TITLE
Para bluetooth upgrade not working

### ISSUE THREAD

**Issue by mortehoe** [opentx/opentx#6910]
I have installed ISRM upgrade module with para bluetooth module on my Frsky X10s
When I try to connect via bluetooth to my x-lite pro (also para module)I cannot connect as it seems there is no address field showing under hardware bluetooth trainer in opentx 2.3.1 (which is showing on x-lite pro opentx 2.3
I installed opentx 2.3.1 with internalaccess enabled.
When I try to discover under model setup/trainer/mode/master bluetooth the discover button does not activate and discover anything (x-lite pro set to slave/bluetooth in setup
![discover not working](https://user-images.githubusercontent.com/3820551/66316557-c925f500-e90f-11e9-8c90-6ca146fd34b1.JPG)
![X10S](https://user-images.githubusercontent.com/3820551/66316559-c925f500-e90f-11e9-962b-6f48a63b8355.jpg)
![x-lite pro](https://user-images.githubusercontent.com/3820551/66316561-c9be8b80-e90f-11e9-9c6c-62d9d65b1f13.JPG)
 *Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by robustini** [comment]
Welcome to the club! :-)

**Comment by robustini** [comment]
There's another issue in the assigned name of the bluetooth device.
In my Jumper T16, which mounts the X12S bluetooth module, the name change takes it, and everything is detected in lowercase even if i write everything in uppercase.
In the X10S Express instead it always remains "Hello" whatever i write, so it is OpenTX that perhaps does not send the correct instructions to the module regarding the change of the name, I cannot think that FrSky has the wrong firmware in the "PARA Wireless BT".

![bt](https://user-images.githubusercontent.com/3864712/66373835-dbed0800-e9a9-11e9-8c35-a04af0628dc0.jpg)

**Comment by robustini** [comment]
@bsongis , I'm trying to compile with your fix for local tests but it gives me a lot of errors referred to "AUX_SERIAL_USART", Is it an incomplete fix or I'm doing something wrong?

![immagine](https://user-images.githubusercontent.com/3864712/66567416-6d55a900-eb67-11e9-9645-2b8d99e5fd13.png)

**Comment by kilrah** [comment]
Always include your cmake config for build errors.

**Comment by robustini** [comment]
cmake -DTRANSLATIONS=IT -DPCB=X10 -DPCBREV=EXPRESS -DGVARS=YES -DDEBUG=YES ../

The problem shows up with debug enabled, should be fixed...

 if(DEBUG)
    set(BOOTLOADER_SRC
      ${BOOTLOADER_SRC}
      ../../../../../${STM32LIB_DIR}/STM32F4xx_StdPeriph_Driver/src/stm32f4xx_usart.c
      ../../../../../serial.cpp
      ../aux_serial_driver.cpp
      )
  endif()

**Comment by robustini** [comment]
I can confirm that from my bench tests it works perfectly, even between different bluetooth modules (X12S and X10S Express).
Thanks a lot @bsongis !!!

**Comment by bsongis** [comment]
you are right about that, aux_serial_driver should be removed, at least on EXPRESS

**Comment by robustini** [comment]
@bsongis please can you merge this fix in the 2.3 branch?

**Comment by 3djc** [comment]
Did you even try again before posting that ?

**Comment by robustini** [comment]
Yes, I tried a lot and it is very stable.
From what I found the new bluetooth modules (aka "PARA wireless") act as master to the old ones (type X12S), but not the other way around, but it's not a problem.

**Comment by robustini** [comment]
Not public video...

https://youtu.be/wlJPcbhSeXA

**Comment by 3djc** [comment]
> Yes, I tried a lot and it is very stable.
> From what I found the new bluetooth modules (aka "PARA wireless") act as master to the old ones (type X12S), but not the other way around, but it's not a problem.

I meant compile with debug. I pushed a fix hours ago

**Comment by robustini** [comment]
If you mean 2.3 branch I compile it without problems.
But there is still no bluetooth fix on 2.3.

**Comment by mortehoe** [comment]
Will this be in the 2.3.2 release.I cannot see this under issues, pull request or closed.will this work for the X10S para upgraded module

**Comment by robustini** [comment]
> 
> 
> Will this be in the 2.3.2 release.I cannot see this under issues, pull request or closed.will this work for the X10S para upgraded module

I've tried it locally with your own tx and now it works, obviously it's the developers who decide when to merge that fix, and if it will be integrated into 2.3.2.

**Comment by mortehoe** [comment]
Okay thank you.

**Comment by 3djc** [comment]
It has been merged this morning, and will be available in 2.3.2
