### ISSUE TITLE
Para bluetooth module for X10S

### ISSUE THREAD

**Issue by mortehoe** [opentx/opentx#6911]
I have installed the upgrade ISRM module kit and Para bluetooth module on Frsky X10S.
Unfortunately the  Bluetooth setup does not show an address field (as shown in my x-lite pro)
When I try to connect "discover" from bluetooth/master X10 to bluetooth/slave x-lite pro it does nothing when clicked.
If I enable telemetry then I can see the bluetooth module on my phone so it is transmitting something.
![discover not working](https://user-images.githubusercontent.com/3820551/66328230-25930f80-e924-11e9-84d3-6d73c8569d40.JPG)
![X10S](https://user-images.githubusercontent.com/3820551/66328231-25930f80-e924-11e9-93c3-c20fce546064.jpg)
![x-lite pro](https://user-images.githubusercontent.com/3820551/66328232-262ba600-e924-11e9-81e7-9fc4ac9a9e23.JPG)

**Comment by kilrah** [comment]
Duplicate #6910

**Comment by robustini** [comment]
Welcome to the club!
