### ISSUE TITLE
Under X9D-2.3.1 in companion, models with XJTD8 in .otx becomes XJTD16

### ISSUE THREAD

**Issue by dev-fred** [opentx/opentx#6912]
**Describe the bug**
In 2.3.1  after a transfer of .otx file in a X9D, all models using a XJTD8  internal are converted to XJTD16

**To Reproduce**
1-From companion open a model with internal RF XJTD8
2. run the simu you will see D16 

![D8-D16](https://user-images.githubusercontent.com/12371235/66387224-d3a1c680-e9c3-11e9-8b35-2b2fe9f680b8.PNG)

**Comment by dev-fred** [comment]
the problem is in companion

**Comment by dev-fred** [comment]
In fact the problem can be reproduced directly in companion and it's not linked to the firmware or the simulator.
To reproduce: 
1- create a model with XJT D8 internal
2- save it
3-close the otx windows
4- open the otx file
5- the HF internal is now in XJT D16

**Comment by dev-fred** [comment]
It's really an issue, sorry

**Comment by dev-fred** [comment]
Idem on X9D+, X10 so it's not only X9D

**Comment by notlebowski** [comment]
Indeed... when did that happen?
I don't think it was in the 2.3.0 nightlies...

**Comment by 3djc** [comment]
At least 2 monthes ago, according to git blame
