### ISSUE TITLE
Bricked Taranis?

### ISSUE THREAD

**Issue by YoureHotToo** [opentx/opentx#6915]
After a failure to get the Taranis to work on sims again, I came across a few forum posts saying to update the Taranis, giving back the ability to work. I performed the update, bringing both the firmware and bootloader to version 2.3.1 and despite backing up the model data, none of it was compatible with the update. This is fine, I can reprogram them. I go to program in the new sim, and the option I need wasn't on the radio; it needs to be added in with the firmware.
I reconnected into bootloader mode, clicked the Simulation box, and click update firmware. After waiting until the firmware flasher was finished, I closed the window and disconnected the Taranis. I clicked exit, and it just shut down. I can't get it to turn on, even in bootloader. What can I do to fix this?

**Comment by 3djc** [comment]
While we understand your issue, this place is  for tracking OpenTX bugs, which your issue isn't. Please use community support like RCgroups or  Open-RC forums for this type of requests
