### ISSUE TITLE
Companion 2.3.1 / X9D: LS and RS not simulated correctly.

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#6929]
**Companion ver 2.3.1, Oct 5 2019, with X9D profile**

I define two channels with LS and RS as sources. 
In the simulator, 
- moving RS affects the wrong channel. 
- moving LS has no effect.

![screenshot_x9d_19-10-10_22-52-29](https://user-images.githubusercontent.com/6317479/66609719-b3cff580-ebb1-11e9-9510-4d76c71f83c3.png)

**Comment by 3djc** [comment]
Yes, this affect x9d only (not x9d+ or x9d 2019) . This has been fixed already and will be available in 2.3.2
