### ISSUE TITLE
LS/RS source controls are missing X9D+ in input item

### ISSUE THREAD

**Issue by vitas** [opentx/opentx#6932]
Looks like a regression issue.
left and right sliders are not presented in the list of available source when editing input control item for Frsky X9D+ Radio

**Expected behavior**
Expect to select left or right slider as "source" in input control item

**General information**
 - OpenTX version (e.g. 3.2.1)
 - Hardware (Frsky X9D+)
 - OpenTX Companion (3.21)

**Comment by 3djc** [comment]
Duplicate #6929
