### ISSUE TITLE
Widgets using source decrease by 2 

### ISSUE THREAD

**Issue by MRC3742** [opentx/opentx#6935]
**Describe the bug**
Upgrading Jumper T16 2.2.3 to 2.3.2 built from current 2.3 branch causes a widget that uses "Source" to decrease by 2 options. This happens to top bar Widgets or any screen page Widget.
A widget originally set up to use RSSI as Source now shows Timer 2
Batt  becomes GV8
VFAS becomes RxBt-

**To Reproduce**
1. Jumper T16 running v2.2.3 setup with widget using any source value
2. Save models to file in Companion
3. Update Radio firmware to current build 2.3.2
4. Reopen model file in Companion 2.3.2 and save to Radio

5. This can also be reproduced using the T16 simulator in Companion 

**General information**
 - OpenTX version: 2.3.2 Oct 11, 2019
 - Hardware:  Jumper T16 Plus
 - OpenTX Companion (v 2.3.2 Oct 11, 2019)

**Comment by kilrah** [comment]
Going to 2.3.2 from any JumperTX version will not be supported and disabled.

**Comment by MRC3742** [comment]
I knew that OTX was supporting T16 on newer 2.3 versions and thought that you would be looking for feedback on upgrading. I didn't realize that JumperTX 2.2.3 was being considered an unsupported version but fully understand your position. Thanks for all your work on this project.
Rich
