### ISSUE TITLE
R9M 2019 Access is missing on Horus x10s with ISRM upgrade

### ISSUE THREAD

**Issue by Nico9n** [opentx/opentx#6938]
I flashed my Horus x10s with internal acceess upgrade. I think now it should be possible to use the external R9M 2019 access modul. The modul is missing in configuration on the transmitter. In Companion it is selectable. When I save the configuration to the transmitter, the external module is off.
Tested OpenTx Version 2.3.0 and 2.3.1

**Comment by 3djc** [comment]
No, it doens't work like that. In order to have R9M 2019 ACCESS working, you need an high speed link to this module, which only exist in the new radio that natively support ACCESS.

Changing your internal module hasn't changed the link to the external module. R9M 2019 in ACCESS mode cannot work on X10 non express, wheter or not you have an upgraded internal module.

It as nothing to do with OpenTX software, purely FrSky hardware

**Comment by Nico9n** [comment]
I have asked Frsky about that 2 Months ago. They said R9M 2019 should should work with access in the old Horus.

**Comment by kilrah** [comment]
They have recently been telling people the opposite, so maybe they changed plans.

**Comment by Nico9n** [comment]
I asked Frsky again. It should work.

**Comment by 3djc** [comment]
Could you paste the question and their response please ?

**Comment by Nico9n** [comment]
From Frsky:
> Hello sir, in order to have the R9M 2019 work with ACCESS firmware with older Horus X10S, you need to purchase an upgrade internal Tx module to replace the original one. Here is the purchase link from our dealer: https://www.horusrc.com/en/frsky-horus-x10-isrm-rf-module.html

I can send you a screenshot If you want.

**Comment by 3djc** [comment]
Yes please, we will double check with them, because changing internal module does not change the hardware link to external module, incapable of doing the required 450kbps needed by R9M 2019 ACCESS

**Comment by Nico9n** [comment]
https://1drv.ms/u/s!AiziGjacV8eZgtMmWU7iJt7SqsAwYQ here it is
![image](https://user-images.githubusercontent.com/29341260/66732279-8dcd7e00-ee5b-11e9-96d3-f122021b7423.png)

**Comment by raphaelcoeffic** [comment]
@Nico9n well, if they explain us how this is supposed to work, why not! But for now, we know only about the serial interface, and there is no way we can do software serial with that speed....

**Comment by bsongis** [comment]
Confirmed, it won't work

**Comment by Rogero-** [comment]
if ACCESS doesn't work with the upgrade module they are selling, the question is, why the upgrade module was called: "FrSky ACCESS Upgrade ISRM RF Module for Horus X10/X10S" and what does it upgrade exactly if ACCESS still won't work, arghhh FRsky what a mess.....

**Comment by raphaelcoeffic** [comment]
Well, you get ACCESS on the internal module on 2.4Ghz. Just not on 900Mhz with the external module, which, by the way, has no synchronisation and thus, quite some sampling aliasing on the receiver side. Ask the BF guys for it, they will tell you some stuff about it ;-)

**Comment by Rogero-** [comment]
thanks raphaelcoeffic for clearing that up... i'm glad i ordered a Jumper T16 Pro and not another Frsky radio.
