### ISSUE TITLE
Persistent timer data displays incorrectly on QX7 after upgrade to 2.3.1

### ISSUE THREAD

**Issue by VancouverUmbrella** [opentx/opentx#6945]
After updating my QX7 from OTX 2.2.4 to 2.3.1, the persisted timer data for each of my models displays incorrectly on the screen of the radio. 

For example, instead of 64:46:46 (correct value), the radio displays 3886:4. 

The problem also occurs in the Companion simulator. However, in the Companion editor interface, the data displays correctly.

Edit UI. See persistent value at far right of screenshot.
![image](https://user-images.githubusercontent.com/56514835/66718921-21407980-ed9e-11e9-86c2-8c2176be4638.png)

Simulator UI. The same occurs on the actual radio screen.
![image](https://user-images.githubusercontent.com/56514835/66718937-4e8d2780-ed9e-11e9-83a7-823903802356.png)

Radio: QX7
OS: macOS Catalina 10.15

**Comment by VancouverUmbrella** [comment]
Is the problem that, on the radio, both the display and edit interfaces no longer have an hours field and are restricted to minutes and seconds i.e. MMMM.SS not HHH.MM.SS.

8504 minutes = 141.73 hours.

**Comment by 3djc** [comment]
That, and the new TIMEHOUR format is HH.MM.SS, which cannot fit on the 128x64 screen, so we would need to restrict to HH:MM, but then some will complain because if they use a more traditional timer, they want MM:SS. But anyway in your case, 141h44 would not fit on screen either

**Comment by VancouverUmbrella** [comment]
Hey 3djc, thanks for the quick response!

Perhaps the time format could automatically adjust to optimize the data as MM:SS or HHH:MM or simply HHH.H (as a decimal) as required? In the current implementation, which renders as MMMM:S[S] for all my models, the last second digit is always occluded. 

Plus, anything over 60 minutes is pretty hard to digest without a calculator -- for me anyway. BTW I never noticed a problem with the display before. Perhaps the last digit was cut off? I don't recall. :-)

As a glider pilot, I tend to put a lot of time on all my models. However, I expect it'll be years before I exceed 999:59 hours on a single model.

Love your good work. Otx and Companion are excellent.

All the best,
Andrew

**Comment by 3djc** [comment]
Given the space on screen, the limit would be 99h59mins. if you pass that we could do HHHHh, I do not think HHH.H would be valid, would 100,5h be 100h30min ? 100h50mins ? very confusing

**Comment by VancouverUmbrella** [comment]
Your suggestion makes sense to me i.e. MM:SS -> HH:MM -> HHHH as required.

FWIW in the old scheme things weren't bad. One or perhaps two numbers could get partially or fully cut off, but I had no trouble understanding a log time of HHH:MM e.g. 141:33.

Thanks for considering this.
