### ISSUE TITLE
Companion simu crashing

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#6947]
Lauching simu with the X12s model file bellow crashes the simu. Renaming category to something smaller seem to bypass the issue.

[Modèles travail Pascal V5 2019 08 12.zip](https://github.com/opentx/opentx/files/3723085/Modeles.travail.Pascal.V5.2019.08.12.zip)

**Comment by Blackforrestpilot** [comment]
same topic as #program collabs when modellname has maximum signs (#6485)

**Comment by 3djc** [comment]
Fixed by 74db396
