### ISSUE TITLE
Mode D8 for taranis Xlite Pro

### ISSUE THREAD

**Issue by soko79** [opentx/opentx#6949]
**Describe the bug**

on my TARANIS xlite pro, I no can see menu for blind D8 protocol receiver with internal module.

**General information**

OpenTX version (2.3.1)
Hardware (Taranis XLite Pro)

**Comment by 3djc** [comment]
Xlite Pro has an ACCESS internal module. Those module do not support D8, there is nothing OpenTX can do about that. Your only options are external multimodule or external xjt

**Comment by soko79** [comment]
Ok, thanks.
