### ISSUE TITLE
Pre-Built nightly companions don't include the T16

### ISSUE THREAD

**Issue by tenten8401** [opentx/opentx#6953]
Downloading a fresh 2.3 companion nightly from the website doesn't seem to be built with Jumper T16 support enabled.

I'm downloading this:
https://downloads.open-tx.org/2.3/nightlies/companion/linux/companion23_2.3.1N17_amd64.deb

When I run it I'm not seeing an option for the T16 at all under my radio profile:
![image](https://user-images.githubusercontent.com/6174343/66773275-a609c100-ee8c-11e9-8aa2-ab42a470d39e.png)

I'm not sure if it's a missing build flag on the server making the nightlies or if it's something I'm doing wrong, but building it myself on a local server using the docker image does have the "T16 / T16+" option in there:
![image](https://user-images.githubusercontent.com/6174343/66774041-94c1b400-ee8e-11e9-9941-400ea14f9402.png)

Maybe they aren't being build from the 2.3 branch or something?

**Comment by 3djc** [comment]
When we start 2.3.2 nightlies, it will be available

**Comment by tenten8401** [comment]
Ahh that makes sense.
