### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by romigr** [opentx/opentx#6955]
Any plans for a 64-bit version of Companion compatible with macOS Catalina?

**Comment by 3djc** [comment]
This issue : https://github.com/opentx/opentx/issues/6945  seem to suggest that it is running fine on Catalina. @VancouverUmbrella  could you comment on that ?

**Comment by VancouverUmbrella** [comment]
Companion runs fine on my MacBook Pro, Catalina 10.15, Intel Core i5 processor (which is 64-bit, if I'm not mistaken).

I've used it with my QX7 and X10S.

**Comment by 3djc** [comment]
Thanks for clarifying that @VancouverUmbrella  !

**Comment by romigr** [comment]
Thanks! I'll give it a shot.
