### ISSUE TITLE
Lua Display Functions: Behaviour of Text Attributes has changed since 2.3

### ISSUE THREAD

**Issue by Matze-Jung** [opentx/opentx#6957]
The code ..
```
function test(value, format)
    lcd.clear()

    lcd.drawText(10, 1, value, format)
    lcd.drawText(lcd.getLastPos(), 1, "V", format)

    lcd.drawNumber(10, 15, value, format)
    lcd.drawText(lcd.getLastPos(), 15, "V", format)
end

return {
    run=function()
        test(80, MIDSIZE+PREC1)
    end
}

```
.. outputs:

opentx-companion-2.2.4-lua-eu_X7
![opentx-companion-2 2 4-lua-eu_X7](https://user-images.githubusercontent.com/52033553/66862936-41d12500-ef92-11e9-8f0d-e01293df3694.png)

opentx-companion-2.3.1-lua-eu_X7
![opentx-companion-2 3 1-lua-eu_X7](https://user-images.githubusercontent.com/52033553/66862955-4a296000-ef92-11e9-84ef-db062b9e419b.png)

Is there a solution I do not see, and is the current behavior of text attributes intended?
Thanks

**Comment by bsongis** [comment]
PREC1 cannot be passed to drawText!

**Comment by Matze-Jung** [comment]
@bsongis It was possible and totally fine on OpenTX < 2.3.x and the new behavior is not satisfactory at all. It seems to mess up with the _lcd.getLastPos()_ function. May have a look at a real use case here: [opentx-lua-widgets](https://github.com/Matze-Jung/opentx-lua-widgets/blob/master/src/SCRIPTS/WIDGETS/value.lua).

**Comment by bsongis** [comment]
again PREC1 is not compatible with drawText (unpredictable behavior)
it should only be used with drawNumber

**Comment by Matze-Jung** [comment]
Ok thx, I'll deal with it. But it's a pain.

**Comment by bsongis** [comment]
you have to understand that we added new flags such as `CENTERED` in 2.3 and we don't have enough space to have different flags values for text and numbers.

you can use a bitwise operator to avoid passing PREC1 to drawText function, something like `(flags & (~PREC1))`

**Comment by Matze-Jung** [comment]
That seems to be the hint I was looking for 👍
