### ISSUE TITLE
Cosmetic change for "X9-Lite" simulator skin

### ISSUE THREAD

**Issue by Ceeb182** [opentx/opentx#6961]
Thank you for using the skin of the X9-Lite. 
Martin Hotar's skins are much better made. So feel free to use his version if he offers one.

There is a cosmetic change to be made.
The simulator screen is not quite vertically centered, there is a one-pixel shift. 
![X9-Lite Image for Companion](https://zupimages.net/up/19/40/p39y.png "X9-Lite with one pixel offset")

**Comment by 3djc** [comment]
QT is a real mess to get right between platforms. We have something pretty good, not sure we want to break it to try to gain that pixel. If someone finds better at ui values that work across all 3 platforms, we will happily take those

**Comment by Ceeb182** [comment]
Ok, I understand.
