### ISSUE TITLE
Skin of the `X9D+ 2019` Companion simulator

### ISSUE THREAD

**Issue by Ceeb182** [opentx/opentx#6962]
Currently the skin of the `X9D+ 2019` Companion simulator is the same as the one of the `X9D+`. 
I propose a new skin designed for the `X9D+ 2019` simulator.
![X9D+ 2019 Image for Companion](https://zupimages.net/up/19/42/69t5.png "X9D+ 2019")

I'm going to create a branch `ceeb182/simuimages` with all the image files on my local OpenTx repository and to do a `pull request`.

**Comment by bsongis** [comment]
I don't like too much this blue :)

**Comment by Ceeb182** [comment]
Ok, the color is not pleasing.
What texture or color would you like ?

**Comment by Ceeb182** [comment]
Here is a new proposal :
![X9D+ 2019 Blue version image for Companion](https://zupimages.net/up/19/42/bwzk.png "X9D+ 2019 - Blue version")
What do you think about this version ?

**Comment by Eldenroot** [comment]
Cool!

**Comment by 3djc** [comment]
Incorporated

**Comment by Ceeb182** [comment]
The choice of the skin is done. :-)
For more information, see #6963 and #7054.
