### ISSUE TITLE
PREC1 and PREC2 in drawnumber lua function with CUSTOM_COLOR

### ISSUE THREAD

**Issue by aviat40** [opentx/opentx#6967]
Open TX 2.3.1 with Horus 12S

If you add PREC1 or PREC2 in the LCD.drawNumber function with a CUSTOM_COLOR,
the color is not considered.. it is always Black.

Without PRECx, it works fine.

Thank you

**Comment by aviat40** [comment]
Hello,

Forget it, it was a mistake in the code. Found the solution

Sorry for this

**Comment by 3djc** [comment]
Thanks a lot for looking deeper into that and finding the root of the issue, it is GREAT  behavior and helpiing a lot ! 👍
