### ISSUE TITLE
2.3.2N22 T16 highlighted (bold) display items not visible

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#6969]
Hi,
little display issue with T16. If items should be displayed in bold letters (highlighted) they are not visible. In this case values from FM2.
![T16highlight](https://user-images.githubusercontent.com/23188713/67143402-60be0880-f26b-11e9-84dc-dbb6d7d3c44b.jpg)

**Comment by 3djc** [comment]
Not seing that here:

![image](https://user-images.githubusercontent.com/5167938/67143801-7cc3a900-f26f-11e9-9a66-6713d3938929.png)

or you need to be more specific on what your issue is

**Comment by Allerhopp** [comment]
If you activate a FM, the according values appear bold. Attached picture is from companion with X10. If you do this with T16, the values become invisible on the radio display. 
[T16_2019_10_19.zip](https://github.com/opentx/opentx/files/3746582/T16_2019_10_19.zip)
![Highlight](https://user-images.githubusercontent.com/23188713/67143951-60c10700-f271-11e9-9d13-afbebf8cb8b3.jpg)
Attached is a model with flightmodes to verify.

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/67144101-6ae40500-f273-11e9-9b60-4d8873390b81.png)

Taken using your own model on real radio, no issue. Maybe try to reflash + check SDcard
