### ISSUE TITLE
Radio Special Function Screenshot for colour display missing in Companion 

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#6970]
I was surprised to find a working screenshot function in T16 with 2.3.2N22. Imo it existed only for monochrome radios. Companion does not know about this SF too. Is this a new feature?
![Screen_Radio](https://user-images.githubusercontent.com/23188713/67144174-2b69e880-f274-11e9-996c-e2978acdff1f.jpg)
![Screenshot](https://user-images.githubusercontent.com/23188713/67144175-2f960600-f274-11e9-8966-b9c3d20a52af.jpg)

**Comment by 3djc** [comment]
Yes, new feature. Will have a look at companion

**Comment by 3djc** [comment]
Fixed
