### ISSUE TITLE
TRAINER PORT IS NOT READ TARANIS X9D+

### ISSUE THREAD

**Issue by afdofdez** [opentx/opentx#6971]
When in companion 2.3.1 on windows 10 the characteristics of a model are read from a file (otx or bin) or from a radio (Taranis X9D +), the TRAINER PORT variable is not read correctly always presenting the MASTER / JACK value.

To reproduce the problem:
1) In the physical radio (X9D+) put the value "MASTER / CPPM Module" in the TRAINER PORT variable of a specific model.
2) Connect the radio to Companion 2.3.1 through USB.
3) Read radio models and settings
4) Check that the specific model shows the value "MASTER / JACK" in the TRAINER PORT variable instead of "MASTER / CPPM Module".

In the version of Companion 2.2 it works correctly.

**Comment by kilrah** [comment]
Already fixed in https://github.com/opentx/opentx/issues/6940
