### ISSUE TITLE
OpenTX2.3.1 on 9XR PRO has bugs at model settings screen 2/11

### ISSUE THREAD

**Issue by joefernwright** [opentx/opentx#6973]
After changing from OpenTX 2.2.4 to 2.3.1 I noticed that screen 2/11 of a model (no matter if restored or newly created) has some lines empty (for example between "Ch.Range CH1-16)" and "Output OpenDrain"). You can scroll down but only through some "invisible" lines. It"s like third part of the settings known from OpenTX 2.2.4 have been replaced to space characters.

When MULTI (multi-protocol module) is chosen with for example sub settings to FrSky D16, models do not bind (but they bind under OpenTX2.2.4 with multi 1.2.1.85). There is even no option to bind like I know it from 2.2.4.

Multi-protocol module is tested with firmware 1.2.1.76, 1.2.1.84, 1.2.1.85 - all of them work fine with OpenTX 2.2.4, version of multi protocol firmware is shown for instance. All these multi protocol firmware versions do not work on OpenTX 2.3.1.

I am forced to roll back to 2.2.4.

**Comment by 3djc** [comment]
broken indeed
