### ISSUE TITLE
[2.3.1] - Custom failsafe not saved when used R9M external module

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#6975]
On FrSky Taranis X9D+ with OpenTX V2.3.1 I installed an external R9M 2019 module with Flex firmware.
I'm noticing that the custom failsafe on the external module are neither written nor respected, it seems that even when entering to set them up it takes those of the internal module.

**To Reproduce**
1: on XJT internal module in D16 mode set a custom failsafe value in all the 16 channel
2: disable the internal module
3: enable the external module R9M, try to set a custom failsafe value, and exit
4: return to the custom failsafe value, they will not be the ones you wrote, sometimes it even reads the values of the internal

**General information**
 - OpenTX: V2.3.1 (same problem with 2.2.4) with "LUA - FLEXR9M" options enabled
 - Hardware: Frsky X9D+
 - OpenTX Companion: V2.3.1

**Comment by 3djc** [comment]
There is also an inconsistency I think between radio and companion data models for this

**Comment by robustini** [comment]
> 
> 
> There is also an inconsistency I think between radio and companion data models for this

The absurd thing is that in the Companion simulator it seems to work instead, i mean the failsafe custom settings.

**Comment by 3djc** [comment]
We probably have not done a great job (and yes, that is an understatement) in communicating a crucial change in 2.3. We are working on that

**Comment by kilrah** [comment]
There is only one failsafe value per channel, because there is no reason you would send the same channel out to 2 modules but wanting different failsafe positions for each. So on the radio both failsafe settings pages show the same thing.
Seems companion has an issue indeed.

**Comment by robustini** [comment]
> 
> 
> There is only one failsafe value per channel, because there is no reason you would send the same channel out to 2 modules but wanting different failsafe positions for each. So on the radio both failsafe settings pages show the same thing.
> Seems companion has an issue indeed.

Absolutely correct, the custom failsafe must be distinguished in both.

**Comment by kilrah** [comment]
No, companion also has to use the same shared values.

**Comment by robustini** [comment]
Not good imho.

**Comment by 3djc** [comment]
If you think that, you will need to elaborate more on use case where that would be needed

**Comment by robustini** [comment]
In the view that both modules act on the same system while flying I agree with you.

**Comment by kilrah** [comment]
No other option. And having one set of failsafes was a deliberate decision based on what I mentioned in my previous post.

**Comment by robustini** [comment]
But one module could for example pilot a drone, and the other a second rx connected to a gimbal.
In that state the custom failsafe should be distinguished from each other.

**Comment by kilrah** [comment]
No! You'll be using different channels, so it's already ok.

**Comment by robustini** [comment]
Ok, i agree about that.
But the problem written above remains, please check.

**Comment by 3djc** [comment]
I cannot reproduce you issue. No matter how modules are setup, I always have the right commun failsafe values.

**Comment by robustini** [comment]
> 
> 
> I cannot reproduce you issue. No matter how modules are setup, I always have the right commun failsafe values.

Leaving the internal module disabled, try to change a custom value on the external, exit and go back inside, here it remains as before.
I use 16 CH on both the module, but the internal is disabled.

**Comment by 3djc** [comment]
Yes, still can't reproduce :s

**Comment by robustini** [comment]
This does not happen in the simulator.

**Comment by 3djc** [comment]
Don't have a x9d(+) closes I have is X9E, and can't reproduce with it either

**Comment by robustini** [comment]
Perhaps in the X9D it does the same thing, if you want to try this it is the otx, model "GAIA DN".
Just to understand if I'm doing something wrong or if indeed there is this problem.
Tested in two X9D+, but with the same settings (cloned)... thanks!

[da.zip](https://github.com/opentx/opentx/files/3747696/da.zip)

**Comment by 3djc** [comment]
Dont have either an X9D or X9D+, so if it not the case on simu, somebody else will  have to take it

**Comment by robustini** [comment]
Question: when the rx is turned on and i try to set a costom value, when i enter inside "SET" the tx read this value from the rx turned on?
I ask this because now I am trying with the rx off and on the TX it keeps them.

**Comment by 3djc** [comment]
No, not in ACCST

**Comment by robustini** [comment]
Ok, i use R9M 2019 in FLEX here.

**Comment by 3djc** [comment]
So ACCST, so no, we can't read data from ACCST receivers

**Comment by robustini** [comment]
Nice, then the problem it seems is with the R9M in FLEX (R9 rx).
We have tried now to turn on the rx and in fact it does not keep the ones I set, but use always the one of the internal.

**Comment by 3djc** [comment]
Trying to recap.
X9D, internal module disabled, r9m flex enabled, rx off : you can change custom failsafe and values are saved

Same setup with rx on, it does not. Is that what you are saying ?

**Comment by robustini** [comment]
> 
> 
> Trying to recap.
> X9D, internal module disabled, r9m flex enabled, rx off : you can change custom failsafe and values are saved
> 
> Same setup with rx on, it does not. Is that what you are saying ?

Correct! If the rx is turned on does not save them.
I try to make a video that proves it.

**Comment by robustini** [comment]
I have no words, now he does so with the rx on, I close, thank you.
