### ISSUE TITLE
Companion 2.3.1 Simulater

### ISSUE THREAD

**Issue by BrianBlogg** [opentx/opentx#6980]
Tx voltage showing 7.3V on simulator LCD screen the actual transmitter screen shows 9.8V please attached screenshot. This is trigering a transmitter battery low warning every time I use the simulato?
![Companian_sim_Txbat_v](https://user-images.githubusercontent.com/48951790/67167261-9a882f80-f38f-11e9-8229-237aeecb3da6.png)

**Comment by 3djc** [comment]
Closed, replaced by new feature request : #7019
