### ISSUE TITLE
External RF Channel range is resetting everytime RF Power is changed on R9M 2019

### ISSUE THREAD

**Issue by Jackjan4** [opentx/opentx#6983]
**Describe the bug**
Whenever I change the output RF Power on my R9M 2019 module the channel range is resetting to the default 1-16, however I want it to stay at the setting I set it to. So for example I set the channel range to CH1-8 and now I want to up the output power for whatever reason. When I set the output power, the channel range jumps back to CH1-16.

**To Reproduce**
1. Create a Model with External RF - R9M FCC
2. Set channel range to 1-8
3. Change RF Power

**Expected behavior**
Channel range not changing when changing RF Power.

**General information**
 - OpenTX version 2.3.1
 - Hardware: Q X7 with R9M 2019 Module (Flashed with newest FCC firmware)
 - OpenTX Companion 2.3.1

**Comment by 3djc** [comment]
Reproduced
