### ISSUE TITLE
horus x10s express mit opentx head tracking

### ISSUE THREAD

**Issue by tompichler** [opentx/opentx#6992]
hy with my horus the head tracking works fine with fr os but since i use crossfire i am flying with opentx but there is no head tracking.  normally that would only be a software error or right?  maybe I would know what dun I can before I change to the taranis x7.  mfg Thomas

**Comment by Gaz-B** [comment]
I also need Head tracking to work on my X10S on OpenTX Pretty Please. Could you at least confirm if this is being worked on ?
