### ISSUE TITLE
[2.3.2 DEV] - Spektrum analyzer issue (ISRM)

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7004]
@3djc I'm experiencing a strange behavior with the spektrum analyzer on Horus X10S Express ACCESS (ISRM), I'm attaching a video to ask you if this very slow scroll is normal.
The comparison with the Multiprotocol is tangible (external in my case).

https://youtu.be/ZDNMAWAdU5s

**General information**
 - OpenTX: V2.3.2 DEV (commit 1b35f2bd)
 - Hardware: Horus X10S Express ACCESS + Multiprotocol external module

**Comment by 3djc** [comment]
Unfortunately, I do not have the radio gear that can help diagnose that. There seem to be 2 issues here, the value seems wrong, and the slow refresh. We will need to find somebody with the right gear and skills to investigate

**Comment by robustini** [comment]
I honestly think I'll never use it, it was just to know, thanks!

**Comment by robustini** [comment]
If you take a good look at the video there is also a graphic problem when INT is selected, the peak of the bars goes to cover the line with the frequencies, with the EXT it does not.

![immagine](https://user-images.githubusercontent.com/3864712/67550780-9d747e80-f707-11e9-8dd5-9959e6d9c48a.png)

**Comment by kilrah** [comment]
Yup we know, saw that yesterday

**Comment by raphaelcoeffic** [comment]
It’s the same at my place, I will probably take over

**Comment by Eldenroot** [comment]
Is that fixable?

**Comment by robustini** [comment]
> 
> 
> Is that fixable?

I hope! :p

**Comment by bsongis** [comment]
aie aie aie

**Comment by robustini** [comment]
@bsongis sure it's okay?
I tried now and it got worse because now it does the same thing with the MPM too.
The refresh is about 2 Hz, both INT and EXT, therefore the problem has not remained in the INT one, now it does so also with EXT.

**Comment by bsongis** [comment]
I tested on the internal module on X10 Express. There were a lot of issues. Do you confirm it's OK there?

**Comment by 3djc** [comment]
@robustini  Bertrand fixed the display glitches, not the refresh rate. As for external MPM refresh rate, what is your module version ?

**Comment by 3djc** [comment]
@robustini tested on T16 EXT, I had 1.3.0.33 installed and that was slow. Tried 1.3.0.22 and 1.2.1.85, both work ok here

**Comment by robustini** [comment]
> 
> 
> @robustini tested on T16 EXT, I had 1.3.0.33 installed and that was slow. Tried 1.3.0.22 and 1.2.1.85, both work ok here

Ok, has been fixed only the glitches.
Tested with MPM 1.3.0.40.

**Comment by 3djc** [comment]
Could you try with 1.2.1.85 and confirm speed is ok ?

**Comment by robustini** [comment]
Tested, i can confirm.
But the problem of refreshing on the ISRM remains.
This issue has been opened for this thing.

**Comment by bsongis** [comment]
On ISRM is there a version which has been better?

**Comment by robustini** [comment]
> 
> 
> On ISRM is there a version which has been better?

No, he always did this thing.
