### ISSUE TITLE
Jumper T16 betaflight-tx-lua-scripts not working

### ISSUE THREAD

**Issue by tiaanv** [opentx/opentx#7005]
The betaflight TX lua script not working as expected.

- Jumper T16 Pro
- BF script 1.4.1
- OpenTX 2.3.2N27 nightly build
- Multiprotocol module updated to latest with bootloader (FWIW)

The BF.lua script runs fine... 
Can also page through various settings... but nothing has values.
Telemetry works fine as can be seen below:
![image](https://user-images.githubusercontent.com/4703398/67575265-771d0600-f73c-11e9-8325-20403089fc4a.png)

BF script on my Taranis X7 with exact same quad worked fine...
Logged issue on betaflight-tx-lua-scripts Github also
https://github.com/betaflight/betaflight-tx-lua-scripts/issues/272

**Comment by 3djc** [comment]
No need to log them at beta flight. It is a known multi/OpenTX issue. Fix is planned.

https://youtu.be/eCnxs3d4VKg

**Comment by tiaanv** [comment]
> No need to log them at beta flight. It is a known multi/OpenTX issue. Fix is planned.
> 
> https://youtu.be/eCnxs3d4VKg

Awesome. Thx.

**Comment by Harrykd33** [comment]
Having a similar issue with brain2 integration, im not getting any values from the Brain unit.
Lua file can be found here under frsky integration. https://www.msh-electronics.com/downloads/

**Comment by bsongis** [comment]
@Harrykd33 not at all the same issue, here is discussed an issue with MULTI (polling not available)

**Comment by Harrykd33** [comment]
Yes correct that's the exact issue I'm having on my jumper T16pro with the internal multi module. It's not pulling bidirectional telemetry. Without bi telemetry my lua script does not work.

**Comment by kilrah** [comment]
Yes it's known that no uplink works with multi at that point, you have to wait until it's implemented.

**Comment by 3djc** [comment]
Fixed in N45

**Comment by tiaanv** [comment]
I've just updated to N46.  I still have no joy.  No BF values in BF.lua
Notes:
* Under the Model Setup - the Module Status says "Module Upgrade Required".
  I'm currently on 1.2.1.85.

Do I really have to take apart my TX again to flash the multiprotocol module with an fdti adapter again? I thought that after the initial re-flash it should have the bootloader on now to flash form TX..... 

If this post is no longer relevant here, someone can direct me where I can perhaps get some help.

**Comment by 3djc** [comment]
Yes, if you have installed the bootloader on your multi, you should be able to flash it from the radio. You need inv if you are using external, noinv for internal. Put the multi firmware on your sd, run the sd navigator, long enter, and choose flash multi

Tested successfully, and others have confirmed it working (the BF scripts)
You should be able to get help here : https://www.rcgroups.com/forums/showthread.php?3243685-Jumper-T16-2-4G-16CH-OpenTX-Multi-protocol-Radio

**Comment by tiaanv** [comment]
Thx @3djc. I was being impatient, and quite new to the T16.  It can't believe it was as simple as navigating to the BIN file on the SD and selecting "Flash Internal Multi".

I can confirm it is working as Expected!!! Yah!!!
