### ISSUE TITLE
Companion 2.3: Isssue import model adapter 2.2 to 2.3 for Taranis X9D+?

### ISSUE THREAD

**Issue by afdofdez** [opentx/opentx#7007]
In windows 10, the simulator 2.3.1 with models imported from version 2.2 continuously gives the error "low transmitter battery", with models created in version 2.3.1 works correctly.

**Comment by 3djc** [comment]
What are your battery alarm values in both cases ?

**Comment by afdofdez** [comment]
In model 2.2 battery warning 11,1 v (battery range 10,5 – 12,6)
In model 2.3 battery warning 6,6 v (battery range 6,0 – 8,0)

**Comment by 3djc** [comment]
The stock battery for X9D+ is a Ni-MH 7.2V 2000mAh battery, If you have those value in 2.2, they are not default values and you probably did some mod on your radio for a 3S lipo (guessing here), and adjusted radio setting accordingly

**Comment by afdofdez** [comment]
Conclusion if a different battery voltage than standard is set in version 2.3, the radio simulator gives transmitter battery error.  It is still an error because if the battery and the warning level are configurable, it should not fail to configure values ​​other than the standard.

**Comment by 3djc** [comment]
Well no, 2.2 and 2.3 set the same standard 6,6 v (battery range 6,0 – 8,0). You say your model have 11,1 v (battery range 10,5 – 12,6), but that's no standard value

**Comment by 3djc** [comment]
2.2 default:
![image](https://user-images.githubusercontent.com/5167938/67619022-cb84bc00-f7f6-11e9-9c85-570274d6f69a.png)

2.3 default:
![image](https://user-images.githubusercontent.com/5167938/67619043-f1aa5c00-f7f6-11e9-88cb-40e243121fd2.png)

**Comment by 3djc** [comment]
Closed, replaced by new feature request : #7019
