### ISSUE TITLE
T16 / X10 - unable to select custom wav files as background music

### ISSUE THREAD

**Issue by jeffhendrix** [opentx/opentx#7008]
On a T16 radio and in companion for T16 and X10, running release 2.3.2N27.
Unable to select custom wav files for background music.
These files work fine on my X9D.
Trying to select them on a T16 radio, they don't show up in the drop down.
Same things happens in companion for both T16 and X10.
Setting companion to X9D profile, the files show up in the drop down.
Selecting the wav files from the SD browser, will play them correctly, both on the radio and in the simulator.

**Comment by 3djc** [comment]
Is your wav files 6chars or less and located at the right place ?

**Comment by kilrah** [comment]
Did you configure the SD card path for your new T16 profile?

**Comment by jeffhendrix** [comment]
That problem was the file length. Making them 6 characters or less fixed the problem.
So why can I use longer file names on my X9D, but the T16 is limited to 6?

**Comment by notlebowski** [comment]
https://github.com/opentx/opentx/issues/6198

**Comment by notlebowski** [comment]
I think it's confusing to allow more than 6-chars on the X9D whilst other models have that limit.

it's also not documented at all. on the contrary. documentation even explicitly says it's firmware version dependent
