### ISSUE TITLE
Sending TX data to sensors connected to a RX using SPORT 

### ISSUE THREAD

**Issue by mstrens** [opentx/opentx#701]
SPORT protocol allows to communicate in both way between Tx and RX (and so to sensor connected to RX).
Currently some sensor read a ppm chanel on RX to get parameter they can internally react on. E.g. OpenXSensor read a ppm signal to adjust the sensitivity of the vario.
Another similar project uses up to 3 parameters to adapt internally.
Using each time a separate ppm chanel is not the best solution (no enough ppm chanel, conversion digital - analogic - digital with loose of resolution).
It would be great if Opentx would allow to transmit data over Sport from TX to RX.

I was thinking at a custom function like the current "play value" where you can select a TX field from a drop list and let the TX pronounce the value and eventually repeat it every x seconds. Here, instead of pronouncing it, the TX would send it over the SPORT.
For sure they should be some agreement on the device_ID and the field_ID to be used.
Perhaps is it possible to just use a generic device_ID for this and it should be the sensor that should take care if it is interested by the field_ID or not.

Thanks in advance.

**Comment by schwabe** [comment]
Sending data over Sport (via lua) is implemented in 2.2. The S6r.lua and betaflight script already use  it. If you are missing features in the current implementation, please open a new issue.
