### ISSUE TITLE
Telemetry mirror and bluetooh for Jumper T16

### ISSUE THREAD

**Issue by Guillesan** [opentx/opentx#7010]
I am following the development for Jumper T16. My request is if you can have "mirror telemetry", either by physical port, or by a bluetooh module. Right now I have a bluetooh module installed for Horus 10 on my Jumper T16, the visibility of the bluetooh works, it is even possible to change the name but the telemetry does not come out. Greetings

**Comment by 3djc** [comment]
Are you using self compiled binaries ?

**Comment by Guillesan** [comment]
I tested with the Jumper T16 2.3 firmware and with the latest night version

**Comment by 3djc** [comment]
Then they do not support BT at all

**Comment by Guillesan** [comment]
That is a problem, it could be overcome. In my other Taranis 9XE station I have a Wi-Fi module installed in the physical serial port, it works very well, I would like to do the same in my Jumper T16

**Comment by robustini** [comment]
Bluetooth on T16 works really well, I use that of the X12S (the most economic, $9), but the automatically compiled firmware does not provide it, so at the moment you have to use a self compiled binaries with the BLUETOOTH option.
So since the Bluetooth works you can theoretically do everything you do on an X12S / X10, I currently only tested the TRAINER function.
You can see it installed...

![t16_bt_liion_charge](https://user-images.githubusercontent.com/3864712/67623104-b5402580-f821-11e9-81a2-942b357effbc.jpg)

**Comment by redjacketKR** [comment]
> I am following the development for Jumper T16. My request is if you can have "mirror telemetry", either by physical port, or by a bluetooh module. Right now I have a bluetooh module installed for Horus 10 on my Jumper T16, the visibility of the bluetooh works, it is even possible to change the name but the telemetry does not come out. Greetings

I totally agree that. I don't know all that inversion / noinversion telemetry stuff yet but

1) people are using extra s.port of battery bay from 'taranis x9d' using a little inversion hardware
    T16 supposedly has one unused uart so it's possible to pull out gps info via UART or internal BT module, theoretically (for those who use Micro XF)

2) Or you can also use that as trainer with spektrum or taranis etc..

**Comment by 3djc** [comment]
1)  support for that will come in time, we are just very busy on a lot of things right now

2) there is a much better option on T16 with multi trainer, very very sweet

**Comment by Guillesan** [comment]
Hello everyone. As I am told, a special compilation is needed, I am not in a position to do so that I surpassed today. 3djc you tell me that from now on it will be possible to be implemented, I will wait, I am very interested in it, telemetry in my case be prepared from its normal screen use of the Jumper T16 in my case I would also use it in our tracker antenna project www.u360gts.com

**Comment by nelsong** [comment]
> Bluetooth on T16 works really well, I use that of the X12S (the most economic, $9), but the automatically compiled firmware does not provide it, so at the moment you have to use a self compiled binaries with the BLUETOOTH option.



Can you share the flags you used to compile it? I compiled mine with:
```shell
docker run -v /root/opentx:/opentx -e "OPENTX_VERSION_SUFFIX=2.3"  -w /opentx/build-t16 opentx cmake -DPCB=X10 -DGVARS=YES -DLUA=YES -DLUA_COMPILER=YES -DHELI=NO -DDEBUG=NO -DCMAKE_BUILD_TYPE=Release ../
docker run -v /root/opentx:/opentx -e "OPENTX_VERSION_SUFFIX=2.3" -w /opentx/build-t16 opentx make BLUETOOTH=yes firmware
```

**Comment by redjacketKR** [comment]
Better yet maybe you could share the compiled firmware temporarily.

**Comment by robustini** [comment]
> 
> 
> Better yet maybe you could share the compiled firmware temporarily.

There's PR by @3djc about this, we await the merge, then we can choose the BT option from Companion.

**Comment by SeanTheITGuy** [comment]
> Bluetooth on T16 works really well, I use that of the X12S (the most economic, $9), but the automatically compiled firmware does not provide it, so at the moment you have to use a self compiled binaries with the BLUETOOTH option.

Would there be a way to use this functionality to piggyback a "follow me" type app's output from a phone over the transmitter's link to be used in GCS Nav mode via MSP on a quad?  Trying to find the least obtrusive way of getting this functionality, and right now it seems like building the iforce2d followme tag and controller seems like it, especially given the work he's put in to the various follow modes, like circling a target, etc.

**Comment by DIY420** [comment]
Question to S.Port mode: Is is sufficient to listen to the existing S.Port stream from transmitters main board to the RF module, just inverting this stream and lead it to u360gts-RxD? Or do I have to use both data directions, u360gts-TxD for telemetry request and u360-RxD for telemetry receive (its clear that in this case I have to use the bluetooth interface usart and activate the bluetooth module in my Jumper T16, which is luckily available in opentx_T16 in the meantime).

**Comment by fabi9163** [comment]
> Bluetooth on T16 works really well, I use that of the X12S (the most economic, $9), but the automatically compiled firmware does not provide it, so at the moment you have to use a self compiled binaries with the BLUETOOTH option. So since the Bluetooth works you can theoretically do everything you do on an X12S / X10, I currently only tested the TRAINER function. You can see it installed...
> 
> ![t16_bt_liion_charge](https://user-images.githubusercontent.com/3864712/67623104-b5402580-f821-11e9-81a2-942b357effbc.jpg)

Any news? Which bluetooth-Module exactly did you use? I'm searching for a build in way to export telemetry from my T16 Pro v2 via bluetooth to my smartphone. solder bluetooth-module, enable bluetooth-flag in companion-app and go for it?

**Comment by rotorman** [comment]
> Which bluetooth-Module exactly did you use?

This one is a solder-in module with antenna and appropriate firmware pre-loaded: https://de.aliexpress.com/item/4001192317700.html
