### ISSUE TITLE
How does heartbeat work?/possible to support with CRSF protocol?

### ISSUE THREAD

**Issue by AlessandroAU** [opentx/opentx#7017]
Hi all,

I am the developer of ExpressLRS (https://github.com/AlessandroAU/ExpressLRS) I'm using the CRSF protocol to receive frames from openTX at 250hz, which I then asynchronously send over the air at 200Hz.

I've been doing some latency measurements and notice quite a lot of spread, best case is around 6ms and worse case 12ms or more. Obviously, part of this is due to the fact I am running my on air rates asynchronously from the input packet rate of CRSF. 

My question is, how does openTX work behind the scenes? Does each CRSF frame represent fresh data? Or will it be stale in some cases?

I know heartbeat was implemented for ACCESS, hypothetically, could this also be used for my application?  I'd like work towards minimizing the variation in system latency. 

Regards,
Alessandro

**Comment by 3djc** [comment]
We have in plan to implement CRSF synchronisation

**Comment by raphaelcoeffic** [comment]
@AlessandroAU it would be easier if you would contact me on the OpenTx chat so I can explain you what we’re doing and how it works / will work.

**Comment by raphaelcoeffic** [comment]
See MR #7050
