### ISSUE TITLE
OTX 2.2.4 Companion - Radio Simulator Not Yet Available

### ISSUE THREAD

**Issue by kneesaknocken** [opentx/opentx#7024]
I updated the Companion, now the Radio Simulation will not function.

**Comment by raphaelcoeffic** [comment]
Which radio?

**Comment by kneesaknocken** [comment]
QX7

**Comment by 3djc** [comment]
What OS ? (windows ? linux ? macosx ?)

**Comment by kneesaknocken** [comment]
Sorry, Windows 10

**Comment by 3djc** [comment]
Then thats not the case, just tested it, x7 simu is there. Have you configured your radio profile to x7 ?

**Comment by kneesaknocken** [comment]
Yikes, so what buttons do I need to push?

**Comment by kneesaknocken** [comment]
Downloaded again, now it works, IDK...

**Comment by 3djc** [comment]
Ok, closing then :)
