### ISSUE TITLE
2.3.2N32@X9D radio reboots if Trainer Mode Master/Serial is selected

### ISSUE THREAD

**Issue by Allerhopp** [opentx/opentx#7027]
MPM FrSky RX works perfect in Jumper T16. When I tried it with X9D the radio reboots, as soon as  Trainer Mode Master/Serial is selected. No chance to select Master/Multi. No matter if internal or external RF or none of both is activated.

**Comment by 3djc** [comment]
Well, We will look into that, but multi trainer cannot work on X9D because sport line is shared on this radio

**Comment by Allerhopp** [comment]
Understood. Isn't there a chance to let the XJT poll the SPort and MPM sends channel values as SPort data?

**Comment by 3djc** [comment]
You want minimum lag on your trainer, you cannot wait the XJT to poll, and the telemetry from the model is also spamming here as well

**Comment by raphaelcoeffic** [comment]
@Allerhopp The other reason why this would not work is the internal XJT module is driving the SPORT bus in the role of a bus master. It is not foreseen to allow bus slaves to place packets on this line whenever they please.

**Comment by Allerhopp** [comment]
Correct. That's why MPM would have to wait for XJT polls. 3djc has latency concerns, but it would be possible in priciple.

**Comment by kilrah** [comment]
Slow. A poll only gets you 4 bytes through and you might only get a few per second.
