### ISSUE TITLE
OpenTx 2.3.1 Taranis X9D+ 2019 - Intermittently bad telemetry data (on both ACCESS & ACCST) #7012

### ISSUE THREAD

**Issue by NickMilton** [opentx/opentx#7028]
No one has contacted from from FRSky as indicated...This problem is real and persists. I believe it is an OpenTx 2.3.1 issue. Please advise regarding original request #7012

**Comment by kilrah** [comment]
Please don't open duplicates, other one will be reopened if applicable.
