### ISSUE TITLE
On Horus 2.3, EVT_EXIT_BREAK event missing

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#7033]
I thought the virtual events where an extra, but perhaps I'm missing some understanding here.

The EVT_EXIT_BREAK const doesn't exist anymore for Horus 12. An event is thrown with value 615.

??

**Comment by lshems** [comment]
Please consider fixing, as some magic number workaround is needed for scripters currently.

Thanks.

**Comment by azaz44** [comment]
Same problem on Horus 10. Please fix, this makes a great deal of scripts not work properly, for example all scripts of Spirit Flybarless system.

**Comment by xoedusk** [comment]
I’d also like this fixed. Flying X10S.
