### ISSUE TITLE
MAX not available in 2.3.1

### ISSUE THREAD

**Issue by dposea** [opentx/opentx#7036]
Taranis QX7, MAX is not selectable as an Input Source option. I can copy an existing input with MAX already selected and it works.

**Comment by kilrah** [comment]
You can long press and select max, but yes there's something wrong, it doesn't appear when scrolling the list.

**Comment by bsongis** [comment]
MAX is missing
TR10-TR16 are displayed TR0-TR6
CH10-CH32 are displayed CH0-CH2
