### ISSUE TITLE
on 2.3.2, X10 extra pots ex1 and ex2 not adressable by getFieldInfo() in LUA

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#7040]
getFieldInfo("ex1") yields nil.

I checked hardware config, set to pot but still nil.

P.S.
This is yet another example why we should be able to get the name if a source ID.

**Comment by 3djc** [comment]
Have you tried ext1 ?

**Comment by lshems** [comment]
I'm not clearsighted. :).

the shorthand in companion on the radio is ex1 and ex2.

I'll try

**Comment by lshems** [comment]
Ok, seems to work. Thanks.

But It's not nice, and is asking for confusing.

Just my cup of tea
