### ISSUE TITLE
SD Card download mixup 2.3.1

### ISSUE THREAD

**Issue by ridilen** [opentx/opentx#7051]
It appears that the SD CARD downloads for OPENTX 2.3.1 are mixed up.  The directory under 2.3.1 for x9d+ as well as several other directories show sdcard-212x64-2.3V0022.zip.

**Comment by 3djc** [comment]
Yes. All packs are the same for radios of the same size. So clicking x9d+ will bring you to 212x64-2.3V0022.zip, which is exactly what you need
