### ISSUE TITLE
Crossfire setup OpenTX

### ISSUE THREAD

**Issue by DonMcFLY** [opentx/opentx#7065]
The issue tracker here is for devlopment of OpenTX. This is not a
support site, only a bug tracking system. Please use support groups
like [rcgroups](https://rcgroups.com/) or
[openrcforum](https://www.openrcforums.com/forum/). See also our
[manual](https://opentx.gitbooks.io/manual-for-opentx-2-2/).

For quick questions you can also join our general chat.

Issues that fall into the category of asking for help, will be
generally closed as invalid without an answer.

-->Hello

I have a xlite pro trasnmitter but it has not a CRSF option in the RF EXTERNAL.

I want to flash firmware, but when I try to download differents versions of OpenTX software including nightlies (since 2N29 to 2N36), unfortunately when I push setting configurator, then in the profile tab it is not appear CROSSFIRE option firmware to tick.

Could anybody help me to resolve it?

**Comment by 3djc** [comment]
OpenTX 2.3 all include Crossfire, and do not require anymore ticking anything. If your radio is running 2.3 and you do not have a CRSF option, then you are running a firmware supplied by FrSky and you need to reflash it with a firmware comming from Companion
