### ISSUE TITLE
HARDWARE menu switch error

### ISSUE THREAD

**Issue by kniuk** [opentx/opentx#7068]
- OpenTX opentx-t16-2.3.2N36
 - OpenTX Companion 2.3.2N36

Jumper T16. After changing via transmitter's HARDWARE menu Switch SF to 2POS i lost option to make it 3POS again. After that i opened config in Companion and same behaviour - not 3POS option on that switch.

**Comment by 3djc** [comment]
SF cannot be a 3POS on T16, hardware wise

**Comment by kniuk** [comment]
You are right. How stupid of me.
I broke switch lever  the other day and went to hardware menu to disable it temporary for safety reasons, until I fix it. Not having a switch functional I presumed it was 3 POS as all the rest :)

**Comment by 3djc** [comment]
Thx for your update !
