### ISSUE TITLE
[2.3.2 DEV] - Graphic problem on the TOOLS page with Horus TX

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7069]
With the N37 and over nine TOOLS in the relevant page there is an overlap at the bottom, the graphic bar below is not respected, it is overlapped.

 - OpenTX version 2.3.2 N37
 - Hardware Horus X10S Express

![tools](https://user-images.githubusercontent.com/3864712/68526026-d69c1980-02d7-11ea-978f-699fabb1bb13.jpg)

**Comment by bsongis** [comment]
+ SEGFAULT on scroll
