### ISSUE TITLE
Unchecked automatically search for companion and firmware updates on companion and now the radio wont connect back to companion.

### ISSUE THREAD

**Issue by ZFreyman47** [opentx/opentx#7074]
I unchecked automatically search for companion and firmware updates on companion and now the radio won't connect back to companion. I need to figure this out because I now have no way of accessing my radio on Opentx and it also won't show up in my PC's folder application so I can't directly edit and replace files. Please Help!

**Comment by 3djc** [comment]
This is unrelated, and this place is for bug reporting, and your report does not seem to point at an OpenTX issue. Please use community support site like rcgroups or open RC forum for this kind of support
