### ISSUE TITLE
X9L Trainer/SBUS + Ext bay ppm - restart radio

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#7078]
X9L OTX 2.3.1
No connection in external bay

Setting model page2 

Internal and external module off 
set Trainer/SBUS
set external bay from off to PPM 
Radio restart by WDT

**Comment by bsongis** [comment]
I take it

**Comment by bsongis** [comment]
Reproduced

**Comment by raphaelcoeffic** [comment]
"set Trainer/SBUS" disables heartbeat....

**Comment by bsongis** [comment]
@raphaelcoeffic it should NOT

On those 2 radios, SBUS / CPPM Trainer are done on RX Pin, not HB!

**Comment by kilrah** [comment]
HB and RX are the same pin also on the Lite connector AFAIK...

**Comment by bsongis** [comment]
no, HB is Pin 4 while RX is Pin 6

**Comment by janekx** [comment]
PXX in pin 6 works for SBUS in trainer function
https://frsky-forum.cz/download/file.php?id=251&mode=view
