### ISSUE TITLE
Companion 2.3: X9D Profile in Companion shows S3 pot which is not physically present

### ISSUE THREAD

**Issue by dingrgh** [opentx/opentx#7079]
In the X9D hardware profile in Companion 2.3, there appears a pot labelled S3 which is not on the actual radio.

Even when setting S3 to 'None' in the Radio Settings>Hardware tab, that error cause problems in the Simulator. In the Simulator, when LS is moved, the simulator thinks RS is moving. When RS is moved, nothing happens.

<img width="783" alt="Radio settings" src="https://user-images.githubusercontent.com/6561640/68711268-4d027b00-0567-11ea-981a-38b05083a9e3.png">

<img width="693" alt="Simulator" src="https://user-images.githubusercontent.com/6561640/68711273-4ffd6b80-0567-11ea-9f6c-dc01edb3e6d0.png">

**Comment by 3djc** [comment]
Already fixed in 2.3.2 nightly if you want to test it
