### ISSUE TITLE
X10 Express difficult to edit Reg ID and Rx Name fields in Registration popup

### ISSUE THREAD

**Issue by lthole** [opentx/opentx#7080]
Version: opentx-x10express-2.3.1 

After clicking on 'Register', and going into edit on the Reg ID field, you cannot continue after editing the Reg ID. Pressing RTN aborts the registration.
Similarly, if you go into edit on the Rx Name field, pressing RTN aborts the registration. However, if you keep editing until you get to the last character position, scrolling right causes the cursor to move to the [Enter] button. You can then complete the Registration.

This is a friend's radio I have on loan, so I don't want to upgrade it to the latest nightly to check.

This all works fine on my X9D+ 2019 version opentx-x9d+2019 2.3.2N32.

**Comment by bsongis** [comment]
Confirmed. I will take it. It will be needed to wait for 2.3.2
