### ISSUE TITLE
Model change on shutdown

### ISSUE THREAD

**Issue by Alhazred81** [opentx/opentx#7083]
Hello all,

is there a possibility on Taranis to change the current model on shutdown? I have a long range module with higher output power, and I always remove the antenna after turning off the TX. I'm afraid of roasting the module, when I turn on the transmitter, and forget to mount the antenna previously.

Thank you for the answer.
Regards,
Alhazred81

**Comment by 3djc** [comment]
No, but you can put a text warning on this/those model that will be displayed before module is turned on, and you have a accept before module will turn on

**Comment by Alhazred81** [comment]
Great, thank you.
