### ISSUE TITLE
[Companion 2.3.2N40] - Models conversion issue from X10S Express to X12S (not respected LS/RS pots)

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7084]
As shown in the attached image the LS and RS pots during conversion from "X10S Express" to "X12S" are not respected, they switch into S3 and S4 when they should remain as they originally were.
From X10S to Jumper T16 there's no issue.

![immagine](https://user-images.githubusercontent.com/3864712/68765989-4edb4580-061e-11ea-8a44-182275f3a338.png)

**General information**
 - OpenTX Companion V2.3.2 N40

**Comment by robustini** [comment]
@3djc can you fix it? Thanks!

**Comment by 3djc** [comment]
Probably not. We do not have mapping tables, that would be a dauting task to create all the best maps between all radio combinations

**Comment by robustini** [comment]
Unfortunately the X12S, unlike all the other OpenTX radio compatible, has S3 and S4 pots, so I think we can fix this.
It is the only tx to have these two additional pots, so if perform a conversion to this tx it would be enough not to contemplate in any case these two pots, but only LS, RS, S1 and S2.
In my example above LS must be mapped to LS since in X12S exists, and RS to RS.
If there is a scale in the conversion order, just change it as a priority: S1/S2/LS/RS/S3/S4 and not S1/S2/S3/S4/LS/RS.
