### ISSUE TITLE
Trim for Nick-Down stucks on X9D plus 2019

### ISSUE THREAD

**Issue by sh-hedge** [opentx/opentx#7087]
My nick trim automatically goes down minimum and in debug mode I can see that it stucks.

I measured on the pins. Hardware is ok.
I have 3.2volts on the trim up pin, and only 1.6volts on the trim down pin.

Could somebody check the code that the pullups are configured correctly?

**Comment by bsongis** [comment]
wow you are right

**Comment by bsongis** [comment]
Would you be able to test the nightly builds? I am commiting a fix, but my radio doesn't have this issue

**Comment by sh-hedge** [comment]
Yes sure, I'll test it. 
But I need some help to compile the firmware file. I do not have the software on my computer...
Or is it possible to use the companion SW for this?

**Comment by bsongis** [comment]
Please send me an email, and tell me which options you like in Companion, I will send a firmware so that we can have a test as quickly as possible. Thanks
