### ISSUE TITLE
Companion 2.3.3N47 'not enough flash' error on multiple targets

### ISSUE THREAD

**Issue by lthole** [opentx/opentx#7097]
OpenTX Companion 2.3.3N47 on MacOS Mojave.
Multiple targets: 
Horus X10/X10S (crossfire, faichoice, noheli, multimodule, lua, luac)
X10 Express (crossfire, faichoice, multimode, lua, luac)
X9D+ 2019 (crossfire, faichoice, multimode, lua, luac)

When trying to download new firmware, it takes quite a while before eventually reporting an error 'Not enough flash available on this board for all the selected options'. If I repeat the download request, it immediately downloads the firmware.

**Comment by 3djc** [comment]
Are you trying to download firmware (ie getting it from our servers) or trying to flash ? I ask because you mention crossfire and multimode which are not choices anymore and as such do not appear.

Looking on the server, I can see opentx-x9d+2019-faichoice-lua-en, but no  x10 firmware asked today (after about 04:00 CET)

And I just downloaded successfully : opentx-x10-faichoice-lua-noheli-en-2.3.3N47

**Comment by lthole** [comment]
I updated Companion, and then for each target checked for updates, downloaded the firmware and flashed the radios. The error was only experienced on X9D+ 2019 today. The X10's downloaded fine today, but also experienced these errors in the last days.

The options I listed in the issue were taken from the Version screens after successful flashing.
In Companion the only choices selected are:
Horus X10/X10S (faichoice, lua)
X10 Express (faichoice, noheli, lua)
X9D+ 2019 (faichoice, lua)
so the others are there now by default?

**Comment by 3djc** [comment]
For the options, yes, crossfire, multi and luac are there by default.

And sorry, I still do not understand WHERE/WHEN your error exactly is. Is that when you are trying to download the firmware (file/download/download firmware) ?

**Comment by lthole** [comment]
Sorry, after the check for updates, I selected to download the firmware. At this point the progress bar pops up, and if the error is going to occur the progress bar stays at 100% for quite some time, and then the error pops up. 
Normally the progress bar goes to 100% and then resets to 0 before showing progress during the download.

**Comment by 3djc** [comment]
I'm again very sorry, but I have a very hard time understanding your issue

When you download a firmware that has not yet been compiled, you have the progress bars that 'cycles' while it is compiling

![image](https://user-images.githubusercontent.com/5167938/69124169-7a898000-0aa3-11ea-8f72-822c79a8ec4a.png)

Then when it is done, the firmware is downloaded to the PC, and that goes with a normal bar, but takes a fraction of a second

Any way you can do a video of your issue ?

**Comment by lthole** [comment]
On MacOS, I don't get the 'cycling' progress bar during compilation, I only have a red bar at 100%. Then during download the progress bar resets to 0 and progresses normally for the download, but that can take 5-10s.

When the next update is available, I will make a video.

I also have Parallels installed, so I will use Windows Companion for the one of the updates.

**Comment by 3djc** [comment]
Great. If you can also record the exact time of failure, we can then try to  find traces of it in the server logs

**Comment by kilrah** [comment]
You don't need to wait for an update to try again, just use the Download menu entry.

**Comment by lthole** [comment]
Ok, I wasn't sure if the server does any buffering.

**Comment by 3djc** [comment]
Yes it does. When you ask for a firmware that has never been compiled yes, it will trigger a compilation, assuming enough ressources exist on the serveur. After says  3 minutes, firmware should be ready and download start. if firmware had been compiled, you get it imediately

**Comment by lthole** [comment]
I have tried on both X10 targets, and it took close to 4 minutes. I may not have waited long enough in the past, on the assumption that it would eventually compile and buffer, and download more quickly next time. Re-trying before the server was ready may have caused the issue.
However, after each error message, it definitely downloaded immediately and successfully.
I accept that I probably caused problems at your end by not just waiting long enough.

**Comment by 3djc** [comment]
We still need to investigate why you did not get server busy as you should have. And yes, Horus firmwares are longer to compile

**Comment by lthole** [comment]
Would you like me to ‘abuse’ the server by aborting and retrying too quickly?

**Comment by 3djc** [comment]
You can give  it a shot, I think I fixed it

**Comment by lthole** [comment]
Bingo! I tried it with a standard X9D+ target, not downloaded recently. I let it run for about 60s, then cancelled, and re-tried immediately. After the error, it downloaded fine. 
Time here is 8:32pm Australian Central Daylight Time.
Couldn't attach .mov video file. Can I email it to you?

**Comment by 3djc** [comment]
What error did you get ? You should be getting server busy (that's what I get here on windows)

**Comment by lthole** [comment]
Same as before 'Not enough flash available on this board for all the selected options'.

**Comment by 3djc** [comment]
OK, now we need to understand why the mac companion doesn't report the right error !

**Comment by 3djc** [comment]
Linux works has it should too

![image](https://user-images.githubusercontent.com/5167938/69143783-1a5a0480-0aca-11ea-9d84-7ee00f3753ed.png)

**Comment by 3djc** [comment]
We can' t reproduce, we have the same screen on mac here

**Comment by lthole** [comment]
I can send you the .mov video via wetransfer if you give me an email address. Otherwise I can paste in a screenshot.

**Comment by kilrah** [comment]
Upload to youtube, vimeo or equivalent and post the link.

**Comment by lthole** [comment]
Here is a screenshot.

![Screen Shot 2019-11-20 at 11 53 36 am](https://user-images.githubusercontent.com/26259987/69201591-b2212680-0b8e-11ea-8be0-4ec9680b6e2b.jpg)

**Comment by kilrah** [comment]
Yeah we know how that looks, unfortunately without context that doesn't help.
Issue is probably with one of your settings, so be sure to show companion configuration and profile settings.

**Comment by lthole** [comment]
X10 Express settings below. I get the same error with Horus X10/X10S, X9D+2019, X9D+. Let me know if you want more detail.

![Screen Shot 2019-11-20 at 5 06 52 pm](https://user-images.githubusercontent.com/26259987/69215032-79964280-0bb8-11ea-8852-23be6c07e4d9.jpg)
![Screen Shot 2019-11-20 at 5 07 10 pm](https://user-images.githubusercontent.com/26259987/69215043-84e96e00-0bb8-11ea-9f60-03bda05a4bea.jpg)
![Screen Shot 2019-11-20 at 5 07 34 pm](https://user-images.githubusercontent.com/26259987/69215062-8e72d600-0bb8-11ea-832c-dff2a1c44186.jpg)

**Comment by kilrah** [comment]
Still can't reproduce or see anything that would cause this... :\

**Comment by lthole** [comment]
I will ask a friend who also has a Macbook Pro (but newer) to try to reproduce the problem.

**Comment by 3djc** [comment]
We fixed it a couple of days ago
