### ISSUE TITLE
the function of the flash multi module does not exist

### ISSUE THREAD

**Issue by zyren** [opentx/opentx#7111]
Since the 2.3.3N50 version, the function of the flash multi module does not exist. When I select the multimodule firmware file from the SD card, the pop-up menu only has copy, rename, and delete.

**Comment by 3djc** [comment]
Reproduced. I think someone broke it while adding bootloader flash ...

**Comment by 3djc** [comment]
Will be fixed in tomorows nightly

**Comment by zyren** [comment]
It’s so fast to modify this issue.
Thank you very much.
