### ISSUE TITLE
[Sky9x] ppm2 port not active

### ISSUE THREAD

**Issue by FXDUTRUCROSSET** [opentx/opentx#7112]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by FXDUTRUCROSSET** [comment]
PPM2 port and TXRX2 seems not no be active on last revision 2.3 N44

**Comment by blairfancy** [comment]
Hi i confirm PPM2 porrt (EXTRA-MODULE) is totaly broken. I ll try to fix that but looks complicated.

**Comment by kilrah** [comment]
Duplicate 6324
