### ISSUE TITLE
2.3.3N52 MULTI flashing "Upgrade Required"

### ISSUE THREAD

**Issue by RubberDuck00** [opentx/opentx#7113]
Jumper T16 Pro w/Hall and FCC; came with internal MULTI module.
 
 OpenTX Companion 2.3.3N52 on Win10 Pro 64 bit
 Settings:  noheli, loa, internalmulti
 Release channel:  nightly builds
 SDcard: sdcard-jumper-t16-2.3v0024.zip

 VERSION: opentx-t16-2.3.3N52 (b9c9e3d9)
 EEPR: 219
 
 MODEL SETUP / MULTI, FrSky, D16 8ch
 v1.2.1.85 [flashing: Upgrade Required]
 
What version should the module be on?
Is this an issue?

**Comment by raphaelcoeffic** [comment]
No, it's not an issue. It's just the multimodule telling you that you should update it to take full advantage of all the features on OpenTx.
