### ISSUE TITLE
[OpenTX V2.3.3N54] - Jumper T16 does not go into OpenTX bootloader

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7115]
Unfortunately flashing the firmware for Jumper T16 from Companion (transmitter OFF) the tx does not access the OpenTX bootloader with the trim T1-T4.
I tried to compile the firmware locally and the same thing happens.

 - OpenTX version V2.3.3N54
 - Hardware Jumper T16
 - OpenTX Companion V2.3.3N54

**Comment by 3djc** [comment]
Known issue, affects X10/12 too, workaround, while we fix it, turn radio on, off, then enter bootloader right away

**Comment by robustini** [comment]
At the moment I stay with the HORUS bootloader, thanks anyway for the trick.

**Comment by 3djc** [comment]
Fixed by 3fe96bc6dd98c4da6947669bc4db1c1cf1b4aadf

**Comment by robustini** [comment]
> 
> 
> Fixed by [3fe96bc](https://github.com/opentx/opentx/commit/3fe96bc6dd98c4da6947669bc4db1c1cf1b4aadf)

Not 100% fixed, on my T16 if it has been off for some time at the first power-up it does not enter in the bootloader, I've to turn it off and on again.
It seems precisely that the problem occurs when the tx has been switched off for some time.

**Comment by 3djc** [comment]
Have you reflashed the bootloader or just upgraded OpenTX to RC ?

**Comment by robustini** [comment]
I compiled the latest code and flashed the whole firmware from Companion.

**Comment by 3djc** [comment]
Radio turned off or in bootloader ?

**Comment by robustini** [comment]
Turned off or the bootloader obviously would not be written.

**Comment by robustini** [comment]
https://youtu.be/MXZ6Nz0WSfA

**Comment by 3djc** [comment]
Would you try downbloading an RC1 from us (any option), and flashing the bootloader from OTX sdcard browser with that rather than your self made version ?

**Comment by robustini** [comment]
Yes, writing the bootloader this way now works.
