### ISSUE TITLE
Bluetooth Trainer on T16 works as slave but not master

### ISSUE THREAD

**Issue by SilentZen** [opentx/opentx#7117]
When pairing T16 with X-Lite Pro and setting X-Lite Pro to master bluetooth trainer works but when setting T16 to master it does not.

**Comment by 3djc** [comment]
Please detail what doesn't work, it is a bit vague. I have it as master connected to an x7s as slave, all seems to work ok

**Comment by SilentZen** [comment]
Once connected and configured as master/bt (t16) and discovered slave (xlite) I the zeros next to cal on trainer menu stay zero when moving stick on xlite.

**Comment by 3djc** [comment]
Not having that here at all. 

What version are you running on both ?
Do both radio say connected and display the other bt adress ?
What happens when you turn xlite off ?

**Comment by kilrah** [comment]
What BT module do you have in the T16? The X-Lite Pro has a new module and if you have the older Horus one in the T16 this combo isn't compatible and only works one way.

**Comment by SilentZen** [comment]
I have the X10 Bluetooth module and not the X12. So this would definitely be the issue. Thanks for your help.

**Comment by kilrah** [comment]
To be clear what you would need is the new "para" module used in the X10 Express, not the one of the X12S.
