### ISSUE TITLE
[Companion N54] No Internal Module available T16 using Standalone Sim or from Companion

### ISSUE THREAD

**Issue by MRC3742** [opentx/opentx#7118]
The Internal Module option is not available using the current v2.3.3N54. 
This problem is in both the Standalone Simulator or when using the Simulator from within Companion.
Also I have checked my settings options and internalmulti is selected.

**Screenshots**
![NoInternal](https://user-images.githubusercontent.com/26642502/69565473-0fe4b280-0f83-11ea-9ec3-fb8ff97c2fb6.jpg)

**General information**
 - Hardware Jumper T16
 - OpenTX Companion 2.3.3N54 on Windows7

**Comment by 3djc** [comment]
Yes, simulators are built with a default config, which in T16 case does not include internalmulti
