### ISSUE TITLE
Can't extract RADIO/radio.bin

### ISSUE THREAD

**Issue by Ferfly** [opentx/opentx#7119]
When I try to open the FIRMWARE file from my radio this message appears **Can't extract RADIO/radio.bin** and I don't know what to do
 
**General information**
 - OpenTX version 2.2.4
 - FrSKY Horus X12S
 - OpenTX Companion 2.2.4

**Comment by kilrah** [comment]
Becasue you don't "open" a firmware file...

**Comment by Ferfly** [comment]
What? If I double click it it is opened by OpenTX...

**Comment by Ferfly** [comment]
> Becasue you don't "open" a firmware file...

What? If I double click it it is opened by OpenTX...

**Comment by kilrah** [comment]
Opentx registers itself for .bin files because the eeprom files for some OpenTX radios are saved as .bin. 

Those can be opened and edited, but for firmware it's irrelevant as well as double-clicking.
