### ISSUE TITLE
backup radio /write backup to radio not implemented?

### ISSUE THREAD

**Issue by Tekniqueman** [opentx/opentx#7125]
backup radio not yet implemented and write backup to radio not yet implemented is the errors you get when trying to use the menus "Write backup to radio" and "Backup radio to file"

**To Reproduce**
1. Go to 'Read/Write'
2. Click on 'Write backup to radio' or 'Backup radio to file'
3. and the error 'not yet implemented' shows up

**Expected behavior**
being able to save radio.

**General information**
 - OpenTX version  2.3.3N55
 - Hardware Jumper T16
 - OpenTX Companion 2.3.3N55
![Udklip](https://user-images.githubusercontent.com/26787182/69813778-2ee97b80-11f3-11ea-8765-280435d47750.JPG)

**Comment by 3djc** [comment]
You can save your radio as an otx file, that’s how it should be done now.

You can also backup your sdcard, which also is a backup of your radio

**Comment by Tekniqueman** [comment]
Okay and that is not only for the Jumper T16? So both radio and models is saved in one file now?


Venlig hilsen
Villy Feltmann

[cid:93C05FAB-C27F-4C0F-B204-FE72EA6DA2F9]

Tlf. +45 26 13 72 52
Gentoftegade 54, 2.th.
2820 Gentofte

Tænk på miljøet, før du printer denne e-mail.
Think about the environment before printing this email.
I forbindelse med persondataloven af 25/5 2018 gør jeg opmærksom på, at Din Digitale Vicevært opbevarer følgende oplysninger om vores kunder/leverandører:

  *   Navn
  *   Adresse
  *   E-mail
  *   Telefonnummer
  *   CVR-nummer
  *   Relevante betalingsoplysninger
Hvis du som kunde fortsat ønsker, at modtage dine faktura via mail, skal du ikke foretage dig noget, og du giver os herved samtykke til, at opbevare ovenstående oplysninger
Ønsker du, at blive slettet fra vores kundekartotek, skal du venligst gøre opmærksom på dette via mail. Denne rettighed kan du til enhver tid benytte dig af.

Fra: 3djc <notifications@github.com>
Sendt: 28. november 2019 15:31
Til: opentx/opentx <opentx@noreply.github.com>
Cc: Villy Feltmann <vif@ddv.nu>; Author <author@noreply.github.com>
Emne: Re: [opentx/opentx] backup radio /write backup to radio not implemented? (#7125)


You can save your radio as an otx file, that’s how it should be done now

**Comment by kilrah** [comment]
Backup Radio To file and the reciprocal are only used for the radios that use an EEPROM, not those that use the SD card.

**Comment by Tekniqueman** [comment]
Ah, that make sense. Thanks for the explanation.
Venlig hilsen
Villy Feltmann

Tlf. +45 26 13 72 52
Gentoftegade 54, 2.th.
2820 Gentofte

Tænk på miljøet, før du printer denne e-mail.
Think about the environment before printing this email.
________________________________
Fra: Andre Bernet <notifications@github.com>
Sendt: Thursday, November 28, 2019 4:12:35 PM
Til: opentx/opentx <opentx@noreply.github.com>
Cc: Villy Feltmann <vif@ddv.nu>; Author <author@noreply.github.com>
Emne: Re: [opentx/opentx] backup radio /write backup to radio not implemented? (#7125)


Backup Radio To file and the reciprocal are only used for the radios that use an EEPROM, not those that use the SD card.
