### ISSUE TITLE
Restarting the Fr Sky Taranis X9D Plus transmitter when changing the mode on the external module

### ISSUE THREAD

**Issue by ThePhantom05** [opentx/opentx#7126]
Hello) Fr Sky Taranis X9D Plus transmitter overload when selecting the external module XJT - PPM mode (the transmitter is also selected to restart, in the upper right corner of the screen there is an exclamation mark. Turn off, turn on the exclamation point.
At the same time, XJT is as it was in the module setup. It can be said that the mode of the external module Fr Sky module is not selected.
**General information**
 - OpenTX version (2.3.3 or N54)
 - Hardware (Frsky X9D+ )
 - OpenTX Companion (2.3.3)
P.S. Обновился до 2.3.3  N55 Also the most

**Comment by FS4000** [comment]
Hello, something similar on my X9E 2.3.7 with Multimodule 1.3.0.87.
I make a new model on the transmitter, both modules are off.
Selection of any internal module mode crashes this screen and brings
it back to the first screen. There is also an exclamation mark on the upper
right corner. No internal module selection is possible with the transmitter!
The only way to select this mode is through Companion.
