### ISSUE TITLE
X9E V2.2.4 Wrong Alert -Model still powered 

### ISSUE THREAD

**Issue by Pix4hawk** [opentx/opentx#7129]
After Update to 2.2.4 and SD-Card flashing to 2.2V0021, I get the wrong Alert when I shut down the X9E.
Regards
Mike

**Comment by kilrah** [comment]
Which wrong alert? Can you clarify?

**Comment by 3djc** [comment]
Well,  model still powered alert means you are still receiving telemetry from your model when you try to turn off the radio.

**Comment by Pix4hawk** [comment]
@3djc I know the message and it is helpful if you forget to switch off the model first. 
Since the update get this message even if the model was first turned off

**Comment by 3djc** [comment]
Could you detail your module and settings then ? I'm flying with X9E too and I do not have that issue

**Comment by Pix4hawk** [comment]
Model (TinyHawk-S) D8 CH1-8 is selected. I'll try it later with another Model on my X9E.

**Comment by Pix4hawk** [comment]
same issue with other Models

**Comment by lepicfoto** [comment]
He he I also fly x9E and it does it all the time. Even when I got the receiver in hand and the function is off the menu, it's actually pretty annoying and it gives some giggle in the club "his gear is FUBAR" is a recurring thing right now, really funny not :-(

**Comment by 3djc** [comment]
Have you tried 2.3.x ?

**Comment by kilrah** [comment]
You probably have selected the "shutdownconfirm" option.

**Comment by Pix4hawk** [comment]
The shutdownconfirm is not the same Alert !
This message comes when the power button (no switch) is pressed longer to prevent accidental shutdown.
Both alarms have worked before V2.2.2 => Issue #6068

**Comment by 3djc** [comment]
Yes, there is an inconsistency. I guess we will make it so that shutdown confirm option disables completely RSSI check (including the setting), but that won't happen in 2.2 branch, maybe not even in time for 2.3.3

**Comment by 3djc** [comment]
Scrap that, I found a nice way to integrate both, preparing a PR for 2.3 branch

**Comment by kilrah** [comment]
I would personally remove the shutdownconfirm option entirely.

RSSI check provides what it was initially meant for, and it makes no sense to have it only for x9e when there are now a dozen radios with push power button...

**Comment by 3djc** [comment]
A fix has been merged into 2.3.3 for next release
