### ISSUE TITLE
idea or doability for a memory of frequency fine tuning once for all for each brand of receiver

### ISSUE THREAD

**Issue by FXDUTRUCROSSET** [opentx/opentx#7130]
would it be possible when using multiprotocol with opentx t create a sub menu or meory to store once for all the receivers of a brand 
or once the first model of a protocol, creating a memory or the fine frequency setting so next receivers bound or created in the next future should already be affected with this setting and would be bound correctly?
thx

**Comment by kilrah** [comment]
Once you have found them you should hardcode them in the multi firmware, there's a facility for that.

**Comment by FXDUTRUCROSSET** [comment]
André, i know you're right but it's far less user-friendly than an option for each user in companion, that would remain once set up regardless updates of new versions in preferences menu for instance
