### ISSUE TITLE
Simulator - cant open Mix Lua script

### ISSUE THREAD

**Issue by darvin** [opentx/opentx#7138]
Open firmware simulator

SD Card path set correctly

Choosing data source - SD Card

in SD Card path /SCRIPTS/MIXES/throttle.lua

in simulator - open Model settings/custom scripts

trying to create new - throttle.lua is not there, nothing is there.

Horus 12s simulator

**Comment by kilrah** [comment]
Wildcard issue it seems

```
convertToSimuPath(): /SCRIPTS/MIXES/.lua -> C:/Users/me/Documents/OpenTX/sdcard-480x272-2.3V0022/SCRIPTS/MIXES/.lua
findTrueFileName(C:/Users/me/Documents/OpenTX/sdcard-480x272-2.3V0022/SCRIPTS/MIXES/.lua)
	not found```

**Comment by darvin** [comment]
@kilrah whats workaround?

**Comment by kilrah** [comment]
Use the radio?

**Comment by 3djc** [comment]
throttle is 8 chars, when only 6 are allowed, reduce name lenght to 6 and it works
