### ISSUE TITLE
Horus X10S goes to safe mode while changing model

### ISSUE THREAD

**Issue by flyingdockp** [opentx/opentx#7142]
I have a FrSky Horus X10S (and the X10S Express) running OpenTx 2.3.1
I have made several model categories, each containing several models.
When I change too fast or I walk through too many categories, the software hangs and the receiver reboots in safe mode.

ALso, as pointed out in another issue, which is now marked as milestone, the Horus does not remember which model I used before the restart. 

Total number of categories: 
[Horus 10XS 2.3 modellenlijst nov 2019.zip](https://github.com/opentx/opentx/files/3908672/Horus.10XS.2.3.modellenlijst.nov.2019.zip)

**Comment by 3djc** [comment]
Have you tried with another sd card ?

**Comment by flyingdockp** [comment]
Yes, two transmitters (Horus x10s and Horus x10s express), 2 sd cards same problem

**Comment by robustini** [comment]
Have you tried with the nightbuilds?
