### ISSUE TITLE
Internal multi module without TXRSSI and TXLQI.

### ISSUE THREAD

**Issue by zyren** [opentx/opentx#7149]
- OpenTX version (2.3.3N60)
 - Hardware (Jumper T16)
 - Protocol (Frsky D16)

The TXRSSI and TXLQI of the external multi module are great!
But the internal multi module does not have this new feature.

**Comment by 3djc** [comment]
Already fixed, please try in next nightly

**Comment by zyren** [comment]
OK, Thanks!

**Comment by 3djc** [comment]
@zyren the RC1 work took a bit longer than expected, so it has not been merged yet. You'll should informed by github when this gets merged
