### ISSUE TITLE
Direct telemetry through port uart3 in Jumper T16

### ISSUE THREAD

**Issue by Guillesan** [opentx/opentx#7150]
It would be extraordinary if you could use the uart3 of the Jumper T16 board. Although this already works by bluetooh, as you know the connection by bluetooh is quite short distance, I wish I could use this port to connect for example a wifi module like the one I am using in my Taranis 9XE. I enclose photos of what I try to explain.
![70147281-f5ae8100-16b4-11ea-8a83-7d8111dc9a90](https://user-images.githubusercontent.com/12551237/70158686-f09f0100-16b7-11ea-86de-ddf153123e78.jpg)

**Comment by 3djc** [comment]
Since we never heard of wifi for any OpenTX transmiter, really hard to tell. Any link to what you have on your X9E ?

**Comment by Guillesan** [comment]
Hi, the explanation of using wifi is a bit long but I will try to summarize it. Together with several colleagues we started a project called www.u360gts.com, its purpose is to mount a multi-platform tracker antenna (telemetry), this is very advanced, you can see complete information in that direction. Initially telemetry is forwarded to the tracker antenna through the bluetooh modules of the Taranis 9xd, 9Xe, Horus 10 and now thanks to 3djc in the Jumper T16. But the bluetooh connection is weak in terms of distance, so we looked for a solution and it was to use Wi-Fi modules https://www.banggood.com/Geekcreit-DT-06-Wireless-WiFi-Serial-Port-Transparent- Transmission-Module-TTL-To-WiFi-Compatible-With-Bluetooth-HC-06-Interface-ESP-M2-p-1141047.html? Rmmds = myorder & cur_warehouse = CN
These modules behave the same as the hc-05/06 creating a transparent serial connection normally at 115200 and connecting the Taranis x with the tracker or pc antenna (Mission Planner) more robustly and greatly extending the connection distance. For use they connect to the serial port on the motherboards of the taranis, attached photo of my connection in my Taranis 9xe. Knowing that the Jumper T16 has the call uart3 on board would be interested could also be used to extract the telemetry received by that port and connect it to the outside by the wifi modules described above. I do not know if it is possible but I create a series of great interest for the users of this station. Sorry for the extension of this answer, I am available to answer any questions. a greeting
![Sin título](https://user-images.githubusercontent.com/12551237/70228829-5e4d3a80-1755-11ea-842e-70e52f68650d.jpg)
This is the modification in the Taranis 9XE, you can see the wifi module connected to the output of the uart.
![thumbnail_IMG_0988](https://user-images.githubusercontent.com/12551237/70229919-732acd80-1757-11ea-974c-e320c06c28a8.jpg)

![thumbnail_0A920472-78A2-4390-9479-262A50353ED9](https://user-images.githubusercontent.com/12551237/70229045-bb48f080-1755-11ea-8dcc-11d5efb9a4e0.jpg)
The brown plate is a telemetry inverter because it is inverted and can be used normally
A photo of the tracker antenna receiving its own CRSF telemetry from TBS Crossfire directly extracted
![thumbnail_C5036D89-46A7-417F-9EA0-F2BD29F4D56E](https://user-images.githubusercontent.com/12551237/70229192-fb0fd800-1755-11ea-8bed-2671d5059107.jpg)
![thumbnail_5D2E9DBC-0730-420B-858B-DC6C0FD0D1F9](https://user-images.githubusercontent.com/12551237/70229204-02cf7c80-1756-11ea-8c67-de7a04f0b025.jpg)
Thank you for your attention, Regards

**Comment by 3djc** [comment]
There is not free uart on T16, the best you could do is try to reuse BT uart which is uart6

**Comment by Guillesan** [comment]
Thanks for your quick reply. A pity is not free uart. I had thought the same usart the rx-tx input of the interior bluetooh module in the Jumper T16. I will test and inform if it is of interest.

**Comment by redjacketKR** [comment]
So how was the result going on Guillesan?

**Comment by brainbubblersbest** [comment]
#8073
