### ISSUE TITLE
Companion 2.3 RC1

### ISSUE THREAD

**Issue by Gaylian** [opentx/opentx#7152]
Companion 2,3RC1 Can not set internal Radio System when using Jumper T16 Pro.
Just get Off and no protocol.
External Radio seems to work.
![Fault](https://user-images.githubusercontent.com/58540542/70202041-72e8fd00-176c-11ea-9f91-301ec8739e05.png)

**Comment by kilrah** [comment]
You haven't ticked the internalmulti option.

**Comment by Gaylian** [comment]
Thanks for that
