### ISSUE TITLE
T16 Pro RC1 DSM sub protocol missing on internal module.

### ISSUE THREAD

**Issue by fabioeh** [opentx/opentx#7153]
**Describe the bug**
T16 Pro RC1 DSM sub protocol missing on internal module.

**To Reproduce**
1. select internal multi dsm

**Expected behavior**
Sub protocol missing

**Screenshots**
I[screen-2019-12-05-035107.bmp.pdf](https://github.com/opentx/opentx/files/3926691/screen-2019-12-05-035107.bmp.pdf)

**General information**
 - OpenTX version 2.3.3 rc1
 - Hardware (t16 pro

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/70234048-0cf67880-1760-11ea-9e94-80bf8668ecec.png)

Working correctly. Make sure your module version is recent enough

**Comment by fabioeh** [comment]
check my screen shot

**Comment by 3djc** [comment]
Please post your otx, definitively not happening here

**Comment by fabioeh** [comment]
are you on .47

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/70234636-5e533780-1761-11ea-8713-ad2ce02eadbf.png)

Same, working here

**Comment by fabioeh** [comment]
[Fabio-T16.otx.zip](https://github.com/opentx/opentx/files/3926766/Fabio-T16.otx.zip)

**Comment by fabioeh** [comment]
only happens on the internal the external works.

**Comment by 3djc** [comment]
only when external is set as RX actually

**Comment by fabioeh** [comment]
Looks like you were able to reproduce the problem.
Thanks for looking in to it.

**Comment by 3djc** [comment]
The fix should be in tomorows nightly

**Comment by 3djc** [comment]
Will have to wait one more nightly, sorry

**Comment by fabioeh** [comment]
Thank you, Just tested n63 and the problem is resolved.
