### ISSUE TITLE
2.3.3RC1 firmware download error

### ISSUE THREAD

**Issue by 0crap** [opentx/opentx#7155]
For two days now I'm trying to download 2.3.3RC1 but it errors out.
Can this be fixed please?

**Comment by 0crap** [comment]
![Download](https://user-images.githubusercontent.com/31951195/70250262-e8a99480-177d-11ea-80c1-2ad251dd7acd.jpg)
![Download_error](https://user-images.githubusercontent.com/31951195/70250268-ea735800-177d-11ea-9336-8bf0c83c3616.jpg)

**Comment by 3djc** [comment]
Please retry

**Comment by 0crap** [comment]
Yep, now working!
What did you do?

**Comment by 3djc** [comment]
Magic on the server side :)

**Comment by 0crap** [comment]
Thx for the quick fix!
