### ISSUE TITLE
Some Jumper T16 Switch / Pot Warning are not available in 2.3.3RC1

### ISSUE THREAD

**Issue by mrduncan626** [opentx/opentx#7162]
Installed the Multiprotocol v1.3.0.47 firmware.
Installed OpenTX Companion 2.3.3RC1 and upgrade radio to 2.3.3RC1.

SE and SF are the only options for switch warning
EX2 is the only option for pot warning.

UPDATE:  Please delete this issue as the problem with the missing sticks, switches, and pots are associated with using Companion.

**Comment by kilrah** [comment]
Working correctly including transfer to/from companion here.
