### ISSUE TITLE
[OpenTX V2.3.3] - Flash bootloader from SYS folder causes crash on Horus X10S Express

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7171]
Flashing the last bootloader from the SYS folder menu sends the Horus X10S Express in "Emergency Mode", even if the bootloader writes it regularly.

 - OpenTX 2.3.3 (self compiled, but with RC1 is the same)
 - Hardware Horus X10S Express

**Comment by 3djc** [comment]
Do you mean the last line of directory ? or bootloader of RC1 ?

**Comment by robustini** [comment]
I mean flashing the bootloader from the file menu of the tx.

**Comment by 3djc** [comment]
Is it specific to x10 express ? I have tried x10 and t16, but cannot reproduce

**Comment by robustini** [comment]
Specific (i think) with X10S Express, see the video, i've no issue with my T16:

https://youtu.be/un3RZAajP2Q

**Comment by 3djc** [comment]
Then I can't help, will try to find someone who can

**Comment by bsongis** [comment]
Reproduced and fixed
