### ISSUE TITLE
OpenTX V2.3.3RC1 Mac OS SD Card Warning QX7S

### ISSUE THREAD

**Issue by BigDogdgs22** [opentx/opentx#7177]
After firmware update & successful instal, l flashed Bootloader. On restart you get "SD Card Warning" Version expected Ver 3V0022

**Comment by 3djc** [comment]
- what is the exact issue ?
- if you have 2.3.3RC1, it should ask for 2.3v0024, not the one you mention

**Comment by BigDogdgs22** [comment]
That’s my EXACT point, it is  not asking for that so how do we fix it? Because that would mean the boot loader flash from the firmware is not updating to 2.3V0024

**Comment by 3djc** [comment]
You are mixing things. Please go to forums like rcgroups or open-rc forums for support, as this does not  look like an opentx bug
