### ISSUE TITLE
Momentary Switch SH slow to respond - Horus X10s 2.3.3RC1

### ISSUE THREAD

**Issue by aussiepage** [opentx/opentx#7179]
Switch SH slow to respond - only happens on Horus

To reproduce:-
1. Setup an unused mix to with source SH
2. View channels using monitors page.
3. Toggle momentary switch several times.

Can take several seconds to respond to switch change.

**General information**
 - OpenTX version 2.3.3 RC1
 - Hardware Horus X10S

**Comment by 3djc** [comment]
I cannot think about anything else but a hardware fault. Have you tried putting back 2.3.2 ? Also, there could be reasons like slow or delays that could affect channel response. Horus in 2.3.3 have a switch diagnostic page (RADIO/HARDWARE, last line (debug), click on switches)

**Comment by aussiepage** [comment]
Hi - issue was repeated on a friends Horus running same version of
software.

**Comment by 3djc** [comment]
Just tried here and I cannot replicate. Have you tried in switch test screen as suggested?

**Comment by aussiepage** [comment]
Thanks for help. I investigated further and found that I also had SH mapped
to Screenshot in global functions. Removing this mapping fixed issue.

Probably not an issue that would affect many as screenshot function not
used often.

Thanks

**Comment by bsongis** [comment]
would you please post your setup? what is linked to SH?

**Comment by kilrah** [comment]
It's just the UI being frozen during the screenshot and the channel monitor thus not showing the change, a servo connected to the channel would actually move

**Comment by bsongis** [comment]
ok, normal then
