### ISSUE TITLE
[OpenTX V2.3.3 RC1] - Missing "Multi-Trainer" option!

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7181]
Ii noticed the "Multi-Trainer" option is now missing in OpenTX V2.3.3 RC1, also not selectable in Companion, please check.

 - OpenTX: version 2.3.3 RC1
 - Hardware: Horus X10S Express ACCESS Module and Multiprotocol Module

**Comment by robustini** [comment]
I don't understand, in Companion the Multi-Trainer now is available with T16, but not on Horus target like X10S and X12S... what are you doing?

**Comment by kilrah** [comment]
Mult trainer can't be used on those since the smart port is used by the internal module.

**Comment by robustini** [comment]
How can i not use it?
I've been using it for a month!

**Comment by kilrah** [comment]
What's your config exactly?

**Comment by robustini** [comment]
Horus X10S Express ACCESS and Multiprotocol module.
With ISRM the smart port pin is not used by the internal module if it removes a pin from the module.
@raphaelcoeffic did all this work unnecessarily?
I don't understand why you removed this option, I've been using it for months without a issue.

**Comment by kilrah** [comment]
Yes, ACCESS AND hardware mod it works, but people who do that will be counted on one hand's fingers.

We have to decide what we do with this kind of stuff, and it's not easy. If the choice is available without the proper hardware configuration people will try to use it and complain it doesn't work. If it's not there at all then people who do specific mods are missing choices. But we can't have options for every single possible modification to selectively enable choices either.

**Comment by robustini** [comment]
This is understandable, but removing the possibility seems to me quite "dictatorial".
We worked on it for months, it was inserted after countless tests in branch 2.3, then approved, and now it is taken off?
It does not seem ethically correct.
At least leave the possibility to enable it by compiling the firmware with a cmake option, eliminating it seems incorrect.
I ask you, @bsongis and the other lead developers to reconsider.
I'm collaborating with your code, making continuous adjustments in the Italian language because in 50% of my use the Multi-Trainer is fundamental, not having it for me is deleterious.
My two cents... Marco

**Comment by robustini** [comment]
I saw where it was deactivated, I recompile it on my fork as it was before, thanks anyway.

**Comment by kilrah** [comment]
> We worked on it for months, it was inserted after countless tests in branch 2.3, then approved, and now it is taken off?

It was always developed with the T16 as the target, the whole effort was precisely triggered by the discovery that it had independent connections and that it would thus allow for this...

**Comment by robustini** [comment]
No problem, I've already created a batch here that automatically enables it in the code before compiling it.

**Comment by bsongis** [comment]
I reopen until we find a suitable solution.

**Comment by robustini** [comment]
Thanks @bsongis , I really appreciate it!
But I also understand what @kilrah writes, I understand it and I agree with it, unfortunately the average user sees this option that can be activated, he tries to enable it and use it, nothing that it doesn't work and he starts to open issue here or to write posts on the forums asking why, it would be deleterious.
Given that it is something that requires a hardware modification on the ISRM module or the pcb that houses the module, even if very simple, this thing should be well explained and it is not easy to make it public, and many will ask for explanations of the non-functioning.
I think the best solution is to leave it enabled only for those who know how to compile the code, so if it is doing so it means that it is also aware of the hardware modification.
The problem is that Companion should also be compiled, and it becomes quite boring.
I honestly don't know what the solution could be.
In case of ISRM:

![isrm_pin](https://user-images.githubusercontent.com/3864712/70601218-de5e1f00-1bf1-11ea-8577-4b3f013080e8.jpg)

**Comment by robustini** [comment]
The only possible solution maybe in my opinion could be to insert "multi-trainer" in the options that can be selected in Companion, and in the relative popup write that if not used with Jumper T16 requires ISRM with a hardware modification, with IXJT it wouldn't work anyway.

**Comment by 3djc** [comment]
- People don't read
- Companion option are a **major** source of issues and we are trying our best to decrease their number

**Comment by robustini** [comment]
@3djc you are absolutely right, but we have included "internalaccess" for the X10 and X12S in Companion, and that does not require a hardware modification? :-)
If there is that there may also be this.
There is also bluetooth for the T16 that can be enabled, and requires the module to be installed, which is by no means trivial, not for everyone.
So it seems absurd to me that many things that require a complex hardware modifications are there, and one that requires unsoldering a single pin no.
Then we also remove "internalaccess" and "bluetooth for T16", both require much more complex hardware changes... no?!
Obviously a joke, don't take them off, LOL, but it is to make you understand that the excuse of the hardware modification does not hold.
My two cents...

**Comment by robustini** [comment]
However, something different between X10S Express ACCESS and X12S with ISRM is there regarding the multi-trainer.
As you can see from the video (listen to the audio) the sport telemetry of the ISRM module stops working when I enter the MODEL menu and work again when exit, something that never happened to me with the X10S Express and the modification of the module I posted above.
In the same way I'm not able to flash the multiprotocol module, I'm forced to disable both ISRM and himself to do it.
The thing is strange because the X12S with the ISRM and the hardware modification should behave theoretically like the X10S Express with the same mod.
For this thing I ask for an answer from @raphaelcoeffic or in any case to those who know why, honestly I don't understand where the difference is, since the ISRM does not use the sport pin for telemetry, yet something when entering the MODEL menu is blocked, there is something different or I could flash the multiprotocol module without having to disable everything.
Apart from this anomaly the multi-trainer works, as does the telemetry on ISRM.

https://youtu.be/oGhtD3iEZd4

**Comment by robustini** [comment]
Could it be that with "internalacces" enabled there is something that is still used by ISRM sport pin, maybe something want disabled in case of "internalaccess" enabled?
I mean something in the code that erroneously remained active, as if there were the IXJT module instead of an ISRM.

**Comment by robustini** [comment]
I found a problem, in the internal module selection IXJT also appears, but if I chose the "internalaccess" option for ISRM in the firmware this option "IXJT" should not be selectable.
Imho this is to be fixed in the code, moreover if you select the ISRM you can not even have on board the IXJT, or one or the other.

**Comment by fabioeh** [comment]
If cutting a pin let’s me use Master/multi on my x10 with access upgrade. Please add it to OpenTX

Thanks

**Comment by robustini** [comment]
> 
> 
> If cutting a pin let’s me use Master/multi on my x10 with access upgrade. Please add it to OpenTX
> 
> Thanks

Absolutely yes!
It should however be remembered that this hardware modification invalidates the module warranty.
However I didn't cut the pin, I unsoldered it.

**Comment by fabioeh** [comment]
You could always replace it with one that has the pin for whatever reason you need it.

**Comment by robustini** [comment]
There is no reason for this pin to exist on ISRM, it only serves to block the possibility of using both modules at the same time, this apparently was annoying FrSky, perhaps because the average user could make disasters with link losses due RF interference or other thing.
This is not possible with IXJT because instead uses this pin.
So those who make this hardware mod must know what they are doing and why.

**Comment by 3djc** [comment]
It is even more complicated than you think. R9M or external XJT module do work at same time as ACCESS internal despite that pin, so it seems selective in what it is blocking

**Comment by fabioeh** [comment]
If there is no reason for it just let OpenTX users remove the pin and enjoy helping someone at the field by connect there transmitter to the X10 multi and enjoy their day.

**Comment by robustini** [comment]
> 
> 
> It is even more complicated than you think. R9M or external XJT module do work at same time as ACCESS internal despite that pin, so it seems selective in what it is blocking

And it is no coincidence, R9M is made by FrSky! :-)
Who knows why with Crossfiere it is not so, for a pure case of fate? :p

**Comment by fabioeh** [comment]
Looks like it’s a win for the completion 2.3.3 released with this feature disabled on the x10
More power to that other radio.

**Comment by gretel** [comment]
got `x9lite` and a multimodule compatible with https://github.com/pascallanger/DIY-Multiprotocol-TX-Module - can i make a hardware hack on this combo to be able to use `ALLOW_TRAINER_MULTI` ? regards
