### ISSUE TITLE
slowed down mixer output not respected while using two MAXes in multiplex REPLACE mode

### ISSUE THREAD

**Issue by kniuk** [opentx/opentx#7183]
Jumper T16, 2.3.3 RC1

Behaviour as described in subject. When I replace multiplex behaviour to ADD it works fine. I guess it is a bug not a feature.

**Comment by kilrah** [comment]
Normal, Slow works on changes in the source value, not the activation/deactivation of a line. You also should not use more than one line with Slow on a channel.
