### ISSUE TITLE
Add "SxR Calibrate" to TOOLS 

### ISSUE THREAD

**Issue by offer-shmuely** [opentx/opentx#7187]
Most of the tools script moved to TOOLS directory (great!)
one script was forgoten

Can we move the "SxR Calibrate" script ?
from: /SxR Calibrate
to: /SCRIPT/TOOLS/FrSky SxR Calibrate

**Comment by 3djc** [comment]
Not forgotten. This tool should be used once in a receiver life. You do it when you receive it, and then no more, so the idea is that we should not use valuable tools space for something almost never used.

If you want it there, you can easily add an entry like it is done for crossfire

**Comment by offer-shmuely** [comment]
Thanks
