### ISSUE TITLE
Open TX 2.4 NV14 compliation error regarding watchdog 

### ISSUE THREAD

**Issue by steady1337** [opentx/opentx#7201]
Trying to compile a .bin for the NV14 but get a few problems regarding the watchdog and bootloader. 

This is the error regarding the wdg:

In file included from /home/exilaz/lala/opentx-2.4/radio/src/debounce.h:24:0,
                 from /home/exilaz/lala/opentx-2.4/radio/src/opentx.h:31,
                 from /home/exilaz/lala/opentx-2.4/radio/src/opentx.cpp:21:
/home/exilaz/lala/opentx-2.4/radio/src/opentx.cpp: In function 'void opentxInit()':
/home/exilaz/lala/opentx-2.4/radio/src/opentx.cpp:2049:14: error: 'WDG_DURATION' was not declared in this scope
   WDG_ENABLE(WDG_DURATION);
              ^
/home/exilaz/lala/opentx-2.4/radio/src/targets/nv14/board.h:265:62: note: in definition of macro 'WDG_ENABLE'
     #define WDG_ENABLE(x)                       watchdogInit(x)
 
This is one of the errors regarding the bootloader:
 
Cannot find source file:
    ../../../../../thirdparty/STM32F4xx_DSP_StdPeriph_Lib_V1.4.0/Libraries/CMSIS/Device/ST/STM32F2xx/Source/Templates/gcc_ride7/startup_stm32f2xx.s 

Thank you for your work and help guys !

**Comment by 3djc** [comment]
2.4 is nowhere near any useful state.Please do not try to compile it
