### ISSUE TITLE
Invalid Board - Downloading Firmware

### ISSUE THREAD

**Issue by Holidays1** [opentx/opentx#7208]
Hi All, 

I'm trying to download OpenTX to my Jumper T16 Pro. When I select the firmware to download I get an error saying, invalid board. 

Any help is appreciated.

**Comment by 3djc** [comment]
https://www.open-tx.org/2019/12/13/opentx-2.3.3RC2

You will need to reset your companion release type to Release candidate to get RC firmware (Companion/Settings/settings/Application Settings/Release channel)
