### ISSUE TITLE
Firmware upgade for X9D Plus SE - 2019

### ISSUE THREAD

**Issue by Cattlebaron** [opentx/opentx#7214]
My TX is loaded with openTX version 2.3.0 and I can't get the Bootloader to work using the 3 finger method, I assume because of the new on/off switch. I also can't update with OpenTx Companion as I get a file write error.

**Comment by 3djc** [comment]
Please go to community support places like rcgroups or openrc forum for advice on how to flash and troubleshooting potential drivers issues preventing you to flash with radio turned off.
