### ISSUE TITLE
Companion OpenTX 2.3.4 Still not fixed

### ISSUE THREAD

**Issue by Gaylian** [opentx/opentx#7219]
No indication that "Write Models and Settings to Radio" is working or finished. (It does write back as when you read models back they have changed).
My Radio is a Jumper T16 Pro

**Comment by OpenUAS** [comment]
Dear @Gaylian could you change the issue _title_ to a bit more descriptive one please. Also the _Body_ of your issue could use some TLC in the text to describe your issue a bit better. 

All this will help developers to know what if at all needs to be fixed and in turn more chance that if something is not working will be fixed. TIA

**Comment by 3djc** [comment]
There is one in your left bottom bar. It display quickly, but is there nontheless

**Comment by kilrah** [comment]
Clicking OK everytime on a "written successfully" would be a pain. You get a message if there's an error, if nothing pops up it means it's OK.
