### ISSUE TITLE
Won't go into boot loading mode after updating to 2.3.3

### ISSUE THREAD

**Issue by mccartysr** [opentx/opentx#7220]
After I updated the bootloader to 2.3.3 it won't go in the bootloader anymore.had go back to bootloader 2.3 to get it to work .

**Comment by 3djc** [comment]
Sorry but i had to lend my Cristal ball to Santa Claus so he could better prepare Christmas, so I have nothing left to guess what radio you are using...

**Comment by mccartysr** [comment]
Sorry 2019 x9d +se

**Comment by kilrah** [comment]
Working fine here

**Comment by mccartysr** [comment]
An i was wrong it is bootloader 2.3.1works if i update the bootloader to 2.3.3 it won't go it to bootloader on my 2019 x9d+ se

**Comment by mccartysr** [comment]
I have both bootloaders on my SD card.would that make 2.3.3 not work?

**Comment by 3djc** [comment]
No, the sd card is not even needed or used to enter bootloader

**Comment by mccartysr** [comment]
Sorry to waste your time. I put the wrong profile in .i had a bootloader x9d not the 2019 x9d.

**Comment by bsongis** [comment]
Yes. I just checked, everything works perfectly
