### ISSUE TITLE
Companion - Impossible to re-dimension the Simulation window

### ISSUE THREAD

**Issue by Cliffweb** [opentx/opentx#7225]
**Describe the bug**
The telemetry simulation window is too small to display all options. 
It's impossible to resize the telemetry simulation window.
There is no 'anchor' visible at the 4 corners of this window in order to resize the window.
The Console windows is also not resizable.

**To Reproduce**
Companion 2.3.3 @ 2.3.4
Click on 'simulation' button at the bottom of the model window.
Open telemetry simulation function 

**Expected behavior**
Resize the telemetry simulation window in order to see all the choices in one time. ( as usual ) 
Ability to re-dimension the simulation window.

**General information**
 - OpenTX version 2.3.3 ( 2.3V0025 ) & OpenTX version 2.3.4
 - Hardware X7s
 - OpenTX Companion 2.3.3 ( 2.3V0025 ) &  OpenTX Companion 2.3.4
- Fr version
- MacOS Catalina 10.15.2

![Capture d’écran](https://user-images.githubusercontent.com/58845771/71306548-01eb4b80-23e2-11ea-9848-a07aae7b29a4.jpg)
![Capture d’écran](https://user-images.githubusercontent.com/58845771/71368373-14af7d00-25a8-11ea-887a-68465c096b6f.jpg)

NB : There is no problems with another profile ( X10s ) , only with this profile : X7s

**Comment by knutigro** [comment]
I also have this problem on my MacBook and OpeenTX 2.3.9 but after testing with version 2.4 this issue seemes to allready be fixed.
