### ISSUE TITLE
Companion 2.1 does not download FW

### ISSUE THREAD

**Issue by muelli01** [opentx/opentx#7230]
When trying to download firmware
(e.g. opentx-9x-frsky-nofp-nocurves-battgraph-pgbar-novario-en-2.1.9.hex) the companion just shows
"Unknown server failure, try later".
A file is however created with content "ERROR:125".

Tried bothe the win32 and Linux64 versions.

**Comment by 3djc** [comment]
Could you try again please ?

**Comment by muelli01** [comment]
Still the same error....

**Comment by 3djc** [comment]
Yes, I need to find a source for those version old compilers

**Comment by muelli01** [comment]
I am not quite sure which version is installed right now, I selected the build options as good as i remember......Is there a way to find the exact version?
It could as well be "opentx-9x-frsky-nofp-nocurves-rotenc-battgraph-pgbar-novario-en-2.1.9.hex" which I need.... Sadly I cannot find any version info in the remote itself.

Thanks!

**Comment by kilrah** [comment]
Nothing to do with you, our servers just do not have what's needed to build AVR stuff anymore, need to figure out how to restore that capability from files that are so old the known source doesn't exist anymore.

**Comment by muelli01** [comment]
OK, understood..... thanks for trying to figure this old stuff out :)

I just discovered the old hex file I was using (opentx-9x-frsky-heli-nofp-nocurves-ppmca-ppmus-symlimits-autoswitch-battgraph-pgbar-novario-nogps-en-r2940.hex) so options are clear. If upgrade to 2.1 is not possible because "old stuff gone away", then it is just bad luck :)

**Comment by 3djc** [comment]
Could you give it another try ?

**Comment by muelli01** [comment]
It downloaded sth, will try to flash asap

**Comment by muelli01** [comment]
OK, had a little trouble flashing, but after fixating to 32kHz i could flash the FW and it is working.
Thanks alot, appreciate your help!

**Comment by 3djc** [comment]
Great ! Our appologies for the lost time, have great flying !
