### ISSUE TITLE
Servo jerking when FS not set 

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#7231]
X12S, X9D+, X7 OpenTX 2,3,3
TX X7 170317FW 
S6R 
Flash OpenTX 2,3,3 
Bind RX and set Failsafe to not set
we can see small jerks every 10-15sec of the servo 1-3 degree
If set FS it doesnt happend. 
Looks like issue with FS transmission setting. 

https://photos.app.goo.gl/VweKthxPESYucEGC8

**Comment by bsongis** [comment]
Fixed
