### ISSUE TITLE
Bootloader not accessible with new X9D Plus SE - 2019

### ISSUE THREAD

**Issue by Cattlebaron** [opentx/opentx#7234]
With the new on/off switch on the TX one can not enter the bootloader mode to update the the Firmware. At present the TX is running on OpenTX Version 2.3.0

**Comment by 3djc** [comment]
We have many report that it is working fine. Maybe you can download a 2.3.3 firmware, put it on the sdcard, navigate to this file from OpenTX click on it and select flash bootloader. That should  rewrite it in case your is defective for some weird reason

**Comment by Cattlebaron** [comment]
Thank you for the information and advice but alas it did not work on my TX with Bootloader mode. I also followed the OpenTX (I assume OpenTX Companion) procedure suggested and get a file write error.
![Error msg for fail update X9DP](https://user-images.githubusercontent.com/33048669/71393715-a0351680-2659-11ea-9caa-ea3d2ed6e194.png)

**Comment by MRC3742** [comment]
Seems from your picture you have the wrong radio selected in the "Edit Settings"
You have Radio: Taranis X9D+ and it should be set to Taranis X9D+ 2019

If you downloaded firmware under this Radio Type then it is not correct for your 2019 Radio.
Change and Redownload firmware and then try to update.

If that doesn't work for you then.....
You can just update the bootloader from within OpenTX on the Radio as 3djc described above using the new firmware file.

Rich

**Comment by driedeker** [comment]
both trims and press the on off twice in sucsesion seam to work for me

**Comment by Cattlebaron** [comment]
Thanks a million times for the advice. I will work through the issue over the next day or two, I had reached a blank wall as far as I could see. I hope it will help others who may have experienced or are yet to experience the issue.

**Comment by Cattlebaron** [comment]
To add to the above post, thanks to driedeker I had the best Christmas present this year. I works like a charm, how did you find that method out?  I posted requests on RCGroups, intoFPV and openrcfotums without any useful replies before I asked here so thanks again.

Hank

**Comment by kilrah** [comment]
Still is an issue since it's not how it's supposed to be

**Comment by driedeker** [comment]
> 
> 
> To add to the above post, thanks to driedeker I had the best Christmas present this year. I works like a charm, how did you find that method out? I posted requests on RCGroups, intoFPV and openrcfotums without any useful replies before I asked here so thanks again.
> 
> Hank

I was lucky as I found it by trying all else.
Yes its not how it should work,but a work around.

**Comment by Cattlebaron** [comment]
Just officially document the "work around" and it will then be the default method of access to the bootloader.
