### ISSUE TITLE
No sub-protocol for DSM for internal module in 2.3.4

### ISSUE THREAD

**Issue by Ukulele-guy** [opentx/opentx#7238]
There is no sub-protocol for DSM in version 2.3.4 for the internal module. There is for the external module.

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/71399637-9a710e00-2624-11ea-93cb-926915aa85a9.png)

**Comment by nicolas-van** [comment]
I can confirm the same issue with opentx 2.3.5 on a Jumper T12.

**Comment by 3djc** [comment]
Module version ?

**Comment by nicolas-van** [comment]
1.2.1.25 . Also this is an external module.

**Comment by 3djc** [comment]
Please update module :)

**Comment by nicolas-van** [comment]
I flashed it in 1.3.0.53 and yes, now I have the option.

Thanks a lot @3djc for your time and your, insanely quick, response time :-)

**Comment by 3djc** [comment]
Thanks for the confirmation :)
