### ISSUE TITLE
There is no sub-protocol for FRSKY 2A in version 2.3.4 for the internal module.

### ISSUE THREAD

**Issue by PhATL1** [opentx/opentx#7239]
There is no sub-protocol for FRSKY 2A in version 2.3.4 for the internal module.
![IMG_5130](https://user-images.githubusercontent.com/59200574/71412755-b2409600-2614-11ea-96bb-cc5b61eb238d.jpg)
![IMG_5131](https://user-images.githubusercontent.com/59200574/71412761-b79de080-2614-11ea-8d16-269d2fdc9451.jpg)

**Comment by 3djc** [comment]
Could you do the recommended module update?

![image](https://user-images.githubusercontent.com/5167938/71412900-f8671b00-264f-11ea-9350-12eab9528e5f.png)

**Comment by PhATL1** [comment]
I tried using the Jumper firmware from their site, but got no change and then I realized that I may have made a mistake and should have used an update from you guys instead. I'm just totally confused
Eddee HorseyOwner, DesignerHorsePower Studios817.525.5875
 

    On Tuesday, December 24, 2019, 06:16:26 AM CST, 3djc <notifications@github.com> wrote:  
 
 
Could you do the recommended module update?

**Comment by 3djc** [comment]
I'm talking of the multimodule upgrade, as asked by the radio on your screenshot

**Comment by PhATL1** [comment]
me too

**Comment by 3djc** [comment]
You need to get a multi module firmware from https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/releases and flash it on your module. How you do that depends of the actual version of  your module

**Comment by PhATL1** [comment]
thanks I'll try that and let you know. You guys freaking rock

**Comment by 3djc** [comment]
I'm closing this as it is not an OpenTX bug by the look of it. You can find help here : https://www.rcgroups.com/forums/showthread.php?3243685-Jumper-T16-2-4G-16CH-OpenTX-Multi-protocol-Radio
