### ISSUE TITLE
Select Input missing in SF Adjust GV

### ISSUE THREAD

**Issue by ChristiaanVis** [opentx/opentx#7240]
Minor issue I think:

Running OTX 2.3.4 on a FrSky Horus 10S (with ISRM module) it seems not to be possible to select inputs or controls from the list as a source to adjust a GV in special functions. This is possible in Companion.

Companion:
<img width="899" alt="Screenshot 2019-12-24 at 12 03 54" src="https://user-images.githubusercontent.com/34834436/71419196-80f4b400-266e-11ea-8c43-d99f83dfcf2c.png">

Horus X10 running OpenTX 2.3.4
![screen-2019-12-24-121150](https://user-images.githubusercontent.com/34834436/71419251-cdd88a80-266e-11ea-9aae-39bb9a66e3bf.jpg)

Also noticed the '???' in Companion listed as controls. On the tx it seems that these entries are listed as not used pots named EX1 and EX2?
![screen-2019-12-24-170605](https://user-images.githubusercontent.com/34834436/71419515-18a6d200-2670-11ea-998e-5d5ca5901ed3.jpg)

**Comment by kilrah** [comment]
You're already in Source mode, the popup is to switch to another....

**Comment by ChristiaanVis** [comment]
Ai, you are right of course. Sorry for the spam.
