### ISSUE TITLE
Companion 2.3.3 - 'Owner Registration ID' value is now showing up in the Hardware tab

### ISSUE THREAD

**Issue by gdenton61** [opentx/opentx#7241]
Frsky X9-Lite
After updating to Companion 2.3.3 Release I now see the 'Owner Registration ID' value is now empty (was 'greg') and is now showing up in the Hardware tab, everything appears correctly on the TX itself.

![Companion 2 3 3 error](https://user-images.githubusercontent.com/6624651/71451145-849f3e00-2735-11ea-8fd8-4539f9a5a226.png)

**Comment by bsongis** [comment]
Fixed
