### ISSUE TITLE
X9 Lite S companion warning about documentX.otx from radio

### ISSUE THREAD

**Issue by johnelliott** [opentx/opentx#7244]
**Describe the bug**
Companion gives a warning that an x9 lite s document read from a radio is from an x9 lite. This seems erroneous. Found after testing results of #7215.

**To Reproduce**
1. Reset X9LITES to factory defaults with OpenTX 2.3.4
2. Open companion of 2.3.4 release
3. Click read models and settings from radio
4. See error dialog box

**Screenshots**
![image](https://user-images.githubusercontent.com/5633265/71551810-d954ea00-29bd-11ea-84bf-5e68f6446385.png)

**Expected behavior**
No error dialog box

**General information**
 - OpenTX version 2.3.4 from releases page
 - Hardware Frsky X9LITES
 - OpenTX Companion version 2.3.4 from releases page

**Comment by kilrah** [comment]
![Annotation 2019-12-29 071816](https://user-images.githubusercontent.com/6065069/71553215-7722d600-2a0b-11ea-82c8-84c1cc44adf9.png)

They are considered as different radios, configure for the right one.

**Comment by johnelliott** [comment]
Thanks Bertrand. I had trouble getting my builds set up but perhaps I can help out with things like this in the future.

**Comment by MrMagniv** [comment]
Just got a new x9-lite-s and had the same problem, is there a way to fix this?

**Comment by kilrah** [comment]
Update both companion and firmware to latest.

**Comment by MrMagniv** [comment]
I'm using companion 2.3.10, is this good?
also, how do I check what firmware I have?

**Comment by MrMagniv** [comment]
the fw I have is opentx-x9lites
and the vers is FrSky (d39cc6fa)

**Comment by kilrah** [comment]
The frsky stock build probably doesn't have the fixes done here so you should update with our 2.3.10.
