### ISSUE TITLE
curve graph not updated in inputs edit when switch not active

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#7246]
Taranis companion sim, 2.2.4.

perhaps wanted behaviour, but seems confusing.

when editing an input line that has a switch assigned, when the switch is not valid the graph of expo doesn't get updated when changing expo.

Removing the switch makes it OK again.

**Comment by kilrah** [comment]
That's intended, the graph shows the active curve.

**Comment by lshems** [comment]
OK, thanks for clarifying.
