### ISSUE TITLE
Trim 5 Trim 6 issues across Flight Modes

### ISSUE THREAD

**Issue by Stuntman2** [opentx/opentx#7247]
Companion 2.2.4 Horus x12s
Value of Trim 5 is not remembered in FM1 thro FM8
Value of Trim 6 is not remembered in FM1 thro FM8
When you have transferred the model to the radio you can go into Flight Modes and manually change the trim setting for Trims 5 & 6 and the transmitter will then function properly until the next time you write Models and Settings to Radio.

**Comment by kilrah** [comment]
Are you really using 2.2.4? It isn't supported anymore.

**Comment by Stuntman2** [comment]
I have upgraded to 2.3.4 and the issue is still there.

**Comment by Stuntman2** [comment]
I have upgraded to 2.3.4 and the issue remains

**Comment by 3djc** [comment]
Could you give more details ?  I have programmed this :

![image](https://user-images.githubusercontent.com/5167938/71619481-dbd56080-2bc4-11ea-8746-b5ae5c66a2d3.png)

Using 2.3.4, if I read radio and settings, and write back, this is still unchanged. Am I misunderstanding your issue ?

**Comment by afdofdez** [comment]
Horus X10S with OpenTx 2.3.4. 
When writing a model on the radio or turning on the radio, I don't know at what time, change the existing value of GV9 in FM0 to the value 1. 
In the two models that happened to me, GV9 could be modified by T6.

**Comment by Stuntman2** [comment]
[GitHub.zip](https://github.com/opentx/opentx/files/4018831/GitHub.zip)

**Comment by Stuntman2** [comment]
Sorry for the late reply @3djc @afdofdez, I have attached both an otx and a word document which I hope will explain the problem in more detail.

**Comment by 3djc** [comment]
Simulator does not store anything, so if you change value there, they will not be changed when sent to radio
