### ISSUE TITLE
Taranis 9xd crsf mirror telemetry

### ISSUE THREAD

**Issue by Guillesan** [opentx/opentx#7248]
In a Taranis 9XD recently updated to 2.3.4 I try to remove the CRSF telemetry from my Crossfire TX using the serial test in the battery bay, going through a signal inverter to forward it to my antenna tracker u360gts that decodes crsf without any problem for other users specifically a partner using Taranis 9XE, in the station all the data is discovered including the position lat, long, height and number of satellites without problem. But inexplicably it does not work fully, curiously only the number of satellites is received the rest does not, or it does not come out or send it in conditions. I would like to know if there is a problem (bug) already discovered or by contrast I am the first to find this problem. Thank you all

**Comment by 3djc** [comment]
Very strange. There has not been similar report. The fact that you get some data seems to indicate the 'piping' it set correctly. I would suggest to investigate what is happening around the inverter, and trace signal, because there is no reason for it not to work
