### ISSUE TITLE
TX/RX data from Taranis-receiver

### ISSUE THREAD

**Issue by villamany** [opentx/opentx#7253]
Hi, is there any way for sending data from the Taranis serial port to receiver?
I got a bluetooth module and inverter installed on my x9D+ and im receiving the SPORT telemetry from my iNav plane into my phone, but i would like also to send data to the plane from the phone. I don`t now if this is possible by SPORT or MSP yet but i dind´t found any extended info about taranis UART (battery slot pins). I see only "TELEM.MIRROR", "TELEM IN", "SBUS TRAINER", and "LUA" on the Serial port screen configuration but not sure if any of these options works like bidirectional port.

Thanks

**Comment by 3djc** [comment]
Well there are many steps needed for something like that to work. Currently there is no way to enter data into BT, you would then need to way  to encode so it gets transmited using telemetry, then you will need somekind of decoding protocol on the receiver end. Also you need to be aware that throughtput would be extremely extremely low

**Comment by villamany** [comment]
is no way to do this though bidirectional SPORT?

**Comment by kilrah** [comment]
Yes but then it would be independent from OpenTX.

**Comment by brainbubblersbest** [comment]
This will be in need anyway, if access functions are full Integrated. 
![IMG_20200423_190505](https://user-images.githubusercontent.com/48190425/80947102-b87b2600-8def-11ea-8a10-a715bb0c89bd.jpg)

I expect Serial telemetry link like the one in crossfire. This can be used for Mav Link. Or direct connencted GPS. Or any Other Serial Feature. 
But crossfire uses it's Own BT Module for that. 
Anyway. With HM-10 Module paired with internal x12s BTLE, crossfire lite AND Telemetry Mirror. This is working too.
