### ISSUE TITLE
Companion 2.3.3 2.3.4 X7access firmware download error

### ISSUE THREAD

**Issue by mStrangers** [opentx/opentx#7256]
Hi 
i can't download firmware for x7access ( every compilation option) with companion 2.3.3 or 2.3.4.
i had always a invalid board error and error:6 when i use this URl directly : https://downloads.open-tx.org/2.3/release/firmware/getfw.php?fw=opentx-x7access-en.bin

**Comment by 3djc** [comment]
Looks like FrSky forgot to add that to compile options

**Comment by mStrangers** [comment]
This didn't work completely , i can compile the firmware , upload it to the radio , it work on it.
but there's no access or accst protocol selection for the internal module only XJT , i've check the compilation option and didn't find where is the one for enabling access protocol.

**Comment by kilrah** [comment]
This fix is only for the server, the code was always OK.

**Comment by mStrangers** [comment]
Ok so can you give me the Gmake option for activating ACCESS , when i'm build it there no ACCESS protocol for the internal module.
Compilation option USED : -DPCB=X7 -DPCBREV=ACCESS

**Comment by kilrah** [comment]
Should work like that, make sure you cleared your build directory before launching cmake

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/71717560-be98d000-2e18-11ea-9be2-eaa8f3784999.png)

We do not have any x7 access radio, but it should work

**Comment by mStrangers** [comment]
hi , re clone the git , and this work thanks a lot guys
