### ISSUE TITLE
Timer - vibrate and voice together

### ISSUE THREAD

**Issue by Eldenroot** [opentx/opentx#7260]
I used Spektrum for a decade, it was a good radio but I switched to Frsky... one of the feature what I missing is better vibrates/sound notifications for timers.

Spektrum had an option on read the timer every minute, vibrate every minute over the set time etc. Is possible to get something like this (I can get a list of options from Spektrum DX9), or am I missing something in the OpenTX and this is already possible?

Thank you!

**Comment by kilrah** [comment]
![capture_x9lites_20-01-02_21-49-55](https://user-images.githubusercontent.com/6065069/71692317-d2f1b400-2da9-11ea-82e8-ccc0b918d870.png)

**Comment by Eldenroot** [comment]
@kilrah - OK, I understand... anyway in Spektrum I can set vibrate+voices together, is that possible in OpenTX?

**Comment by kilrah** [comment]
When on voice it will vibrate as well, try things...

**Comment by Eldenroot** [comment]
Then it should be Vibe/Voice not just Voice :)

Thank you anyway :)
