### ISSUE TITLE
Timer 3 does not start sometimes

### ISSUE THREAD

**Issue by afdofdez** [opentx/opentx#7261]
Horus X10S OpenTx 2.3.4

I have the timer3 set to know how much time I am in each model, with persistence and manual reset. 
TIMER3 = ON in companion 
TIMER3= ABS in the horus, is it the same? Should it be the same? 

ERROR:  Sometimes when selecting the model on the radio the TIMER3 is OFF. 

ERROR: In the fourth position (to the right of the whole) of the top bar of the main screen, next to the volume and battery icons, you can't put a Timer widget (it gets on but can't be seen). To be able to put it on, you have to put another widget before, I can name it and then I could put the timer widget. This happens on the radio.

**Comment by 3djc** [comment]
Cannot replicate any of this

![screen-2020-01-04-102239](https://user-images.githubusercontent.com/5167938/71763429-26641f00-2edc-11ea-8203-2434d5549127.png)
