### ISSUE TITLE
No reset for gas suite.  One can't reset the gas suite with telemetry reset.  The only way i have figured how to reset it is with a power off.  I have planes with big gas tanks and would like to set it not to reset with power off, but I need to reset it when I fill the tank.

### ISSUE THREAD

**Issue by williajgr** [opentx/opentx#7262]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by 3djc** [comment]
Gas Suite operation are defined by FrSky, we have no control over that
