### ISSUE TITLE
Radio Taranis Plus accst, não Bind com Versao 2.3.4

### ISSUE THREAD

**Issue by Larangeira** [opentx/opentx#7282]
Boa tarde

Estou com um sério problema praticamente a 1 mês, fui atualizar meu radio Taranis Plus accst, para a versão mais nova e não consigo mais fazer o bind com meus receptores.
O que vi de diferente é que na versão anterior onde faz bind não tinha a opção do modulo interno XJT, 

O que pode ser .

**Comment by 3djc** [comment]
English only please

**Comment by Larangeira** [comment]
Good afternoon

I have a serious problem for almost 1 month, I have been upgrading my access to the Taranis Plus radio to a newer version and can no longer bind to my receivers.
What I saw differently is that in the previous version, where bind didn't have the XJT internal module option,

What can it be .

**Comment by Larangeira** [comment]
Version 2.3.4 , I use the R9M module

**Comment by kilrah** [comment]
You are probably using the wrong firmware, you must NOT take the "2019" version if you have an ACCST Taranis Plus.

Also this place is for reporting bugs, not for user questions.
