### ISSUE TITLE
Rssi alarm "low signal reception" on Horus x10s 

### ISSUE THREAD

**Issue by fmartinezo** [opentx/opentx#7284]
Radio Horus X10s, r9 external module, r9mini receiver, flex firmware on 815 and Opentx 2.3.4

Flying at 500 meters i have an rssi around 70db and the radio start to sing "low signal reception" and vibrate. I have telemetry by smart port, configured in a channel (-100/200) and selected that channel on Inav . On the telemetry screen of my Horus, as on the inav lua telemetry screen,  as on the goggles osd and on Inav I have the same rssi value. What is wrong? I have on osd inav activated default alarms, on my horus x10 all alarms by default too. I enclose photo of my horus telemetry screen
![telemetry](https://user-images.githubusercontent.com/38476783/72062178-880afb80-32d7-11ea-9092-4f47805de4f2.jpg)

**Comment by kilrah** [comment]
It would mean that your link occasionally drops down and goes back up. 

Please note this issue tracker is not for usage questions.
