### ISSUE TITLE
X9-lite companion simulator logic switches error

### ISSUE THREAD

**Issue by prikrylm** [opentx/opentx#7285]
There is an error on the X9-Lite simulator in Companion v2.3.4. 
Set ie a>x  for CH1 ..
on simulator I can see CH3
![obrazek](https://user-images.githubusercontent.com/26926725/72063584-53e50a00-32da-11ea-9abb-b2474544b0cd.png)

**Comment by 3djc** [comment]
Likely a duplicate of https://github.com/opentx/opentx/issues/7273

Please test latest nighly

**Comment by prikrylm** [comment]
sorry, I was unable to find similar error.
