### ISSUE TITLE
Filename in OpenTX 2.3.4

### ISSUE THREAD

**Issue by BergshamraFraggel** [opentx/opentx#7289]
The file names in OTX 2.3.4 for audio / BGMusic have been reduced to 6 + 3 characters.
If using the OTX SD Explorer, it reads 8 + 3 characters of file names and sounds can be played.
In special functions only 6 + 3 characters are accepted and files with longer names are not displayed.

8 + 3 characters in file names work without problems in OpenTX 2.2.4 with Frsky Tarani's X9D.

OpenTX 2.3.4
Jumper T16 upgraded with hall effect gimbal.

**Comment by 3djc** [comment]
By design. We **may** review this at some point, but not before next major version as new eeprom version is required

**Comment by BergshamraFraggel** [comment]
I don't buy that statement.
What is the difference between pictures and audio files?
If I put an image on the SD card that is 8 + 3 characters, it is no problem to use it as a model image.

![Audio](https://user-images.githubusercontent.com/17248147/72609946-786a6300-3926-11ea-9c8e-eb2091063523.JPG)

![SD_Browser2](https://user-images.githubusercontent.com/17248147/72609989-933cd780-3926-11ea-8f87-b90c58a88628.JPG)

![SD_Browser1](https://user-images.githubusercontent.com/17248147/72609991-933cd780-3926-11ea-91c3-5173e43a7201.JPG)

![Image](https://user-images.githubusercontent.com/17248147/72609975-8b7d3300-3926-11ea-99a6-03913fa0e62b.JPG)

**Comment by kilrah** [comment]
It has to do with what is stored where. Audio files may be referenced to in special functions, allowing more characters would mean making the data structure for special functions bigger, which are instanciated 64 times, which means significantly more RAM and model storage usage.
Not a problem on Horus, but on Taranis things are tight already. Since the code is currently common it's how it is.

**Comment by BergshamraFraggel** [comment]
I know they share codebase, but since both Horus and Jumper have their own branch of firmware, it shouldn't be a general limitation.
It is annoying and cumbersome when you switch to a newer radio (X9D -> Jumper T16) and have worse conditions to handle the new features.

**Comment by kilrah** [comment]
Yep, but it's how it is for now until the entire data storage system is reworked.
