### ISSUE TITLE
[OpenTX V2.3.5] - Compilation issue, how fix it?

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7298]
I need some help, i've this error when compiling 2.3.5:

Scanning dependencies of target datacopy
[  6%] Generating datacopy.cpp
  File "/home/marco/opentx/radio/util/generate_datacopy.py", line 50
    print("Warning more than one union member (%s) in anynomous union inside struct %s, consider NOBACKUP statements" % (uc.spelling, cursor.spelling), file=sys.stderr)
                                                                                                                                                            ^
SyntaxError: invalid syntax
radio/src/CMakeFiles/datacopy.dir/build.make:61: recipe for target 'radio/src/datacopy.cpp' failed
make[3]: *** [radio/src/datacopy.cpp] Error 1
make[3]: *** Deleting file 'radio/src/datacopy.cpp'
CMakeFiles/Makefile2:239: recipe for target 'radio/src/CMakeFiles/datacopy.dir/all' failed
make[2]: *** [radio/src/CMakeFiles/datacopy.dir/all] Error 2
CMakeFiles/Makefile2:314: recipe for target 'radio/src/CMakeFiles/firmware.dir/rule' failed
make[1]: *** [radio/src/CMakeFiles/firmware.dir/rule] Error 2
Makefile:264: recipe for target 'firmware' failed
make: *** [firmware] Error 2

**Comment by robustini** [comment]
CMake Deprecation Warning at companion/src/CMakeLists.txt:358 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

**Comment by bsongis** [comment]
Are you using python2?

**Comment by robustini** [comment]
Yes, V2.7.17.

**Comment by bsongis** [comment]
python3 is needed, not python2

**Comment by robustini** [comment]
@bsongis please could you put me in the right direction?

python --version
Python 3.6.9

But:

![immagine](https://user-images.githubusercontent.com/3864712/72509494-fad02580-3847-11ea-9975-914a64d8f1eb.png)

Can't you make sure that the code is still forced to use version 3 in case of multiple versions installed?
I use version 2.7 for other things and can't remove it.
I forced the use of 3.6.9 as default in bashrc via alias.

**Comment by bsongis** [comment]
update-alternative?

**Comment by robustini** [comment]
Yes, I have omitted this step, I try, thanks.

**Comment by robustini** [comment]
Now:

-- Found Git: /usr/bin/git (found version "2.17.1") 
-- OpenTX 2.3.6 @cc298988
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.9") 
-- Python found, version: 3.6.9
-- Qt Version: 5.9.5

But:

  File "/home/marco/opentx/radio/util/generate_datacopy.py", line 4, in <module>
    import clang.cindex
ModuleNotFoundError: No module named 'clang'
radio/src/CMakeFiles/datacopy.dir/build.make:61: recipe for target 'radio/src/datacopy.cpp' failed
make[3]: *** [radio/src/datacopy.cpp] Error 1
make[3]: *** Eliminazione del file "radio/src/datacopy.cpp"
CMakeFiles/Makefile2:239: recipe for target 'radio/src/CMakeFiles/datacopy.dir/all' failed
make[2]: *** [radio/src/CMakeFiles/datacopy.dir/all] Error 2
CMakeFiles/Makefile2:314: recipe for target 'radio/src/CMakeFiles/firmware.dir/rule' failed
make[1]: *** [radio/src/CMakeFiles/firmware.dir/rule] Error 2
Makefile:264: recipe for target 'firmware' failed
make: *** [firmware] Error 2


Where am I wrong?

**Comment by robustini** [comment]
update-alternatives --list python

/usr/bin/python2.7
/usr/bin/python3.6

python --version

Python 3.6.9

**Comment by robustini** [comment]
I removed the alternative for version 2.7, now there is only 3.6, but I have the same error when I compile.

update-alternatives --list python

There is only one alternative in the python group (which provides / usr / bin / python): /usr/bin/python3.6
Nothing to configure.

**Comment by bsongis** [comment]
pip install clang ?

**Comment by robustini** [comment]
Yes, missing clang for Python 3, thanks!

**Comment by bsongis** [comment]
would you update our wiki page?

**Comment by robustini** [comment]
It would be better if someone who perfectly knows the English language did it, this is not my case.
But i agree, actually would like updated.

**Comment by robustini** [comment]
I'm sorry @bsongis if I still bother you in a closed issue but for a few days I can't compile in WLS anymore (updated Ubuntu 18), I've this error:

![immagine](https://user-images.githubusercontent.com/3864712/94986293-d810a900-055d-11eb-8028-0b917b888b24.png)

**Comment by 3djc** [comment]
thats the wrong compiler version

**Comment by robustini** [comment]
> 
> 
> thats the wrong compiler version

Ok, what should I do?
Install new gcc-arm-none-eabi?

**Comment by kilrah** [comment]
As mentioned in the wiki compiling for radio requires an old version, 4.7.
No idea how to install that on WSL.

**Comment by robustini** [comment]
> 
> 
> As mentioned in the wiki compiling for radio requires an old version, 4.7.
> No idea how to install that on WSL.

The problem is that until a few days ago I was compiling without issue, and I haven't updated anything.

![immagine](https://user-images.githubusercontent.com/3864712/94986924-e1e8db00-0562-11eb-953f-162172b0d8bf.png)

![immagine](https://user-images.githubusercontent.com/3864712/94986946-165c9700-0563-11eb-9c6a-87c472b96543.png)

**Comment by kilrah** [comment]
This is code that was written a week ago, and apparently it doesn't make that compiler version happy...

**Comment by robustini** [comment]
Same issue with g++4.8, damn!

![immagine](https://user-images.githubusercontent.com/3864712/94987594-b87e7e00-0567-11eb-9316-91c237157e57.png)

**Comment by robustini** [comment]
The problem is that I can't find g++4.7 arm64 for Ubuntu 18, starts from version 4.8 which still gives that problem.
Wouldn't it be better to check and fix the code?

**Comment by 3djc** [comment]
No, compiling with any other version than the tested compiler is really not something anyone should be doing

**Comment by kilrah** [comment]
Can you pull and try again?

**Comment by robustini** [comment]
> 
> 
> Can you pull and try again?

Fixed, thanks!!!
