### ISSUE TITLE
OpenTx 2.3.5 doesnt run X10S express

### ISSUE THREAD

**Issue by i3dm** [opentx/opentx#7299]
X10S Express, after upgrading to 2.3.5 got "Wrong PCB Deteced".
tried 2 different compliation versions - same results.
thank you.

**Comment by bsongis** [comment]
Confirmed

**Comment by bsongis** [comment]
2.3.4 was OK? I am comparing changes ...

**Comment by i3dm** [comment]
Yes.

**Comment by i3dm** [comment]
can you compile 2.3.4 for me and send it over temporarily so my radio isnt bricked? :)

**Comment by 3djc** [comment]
2.3.4 should not be used on horus and t16 anymore

**Comment by i3dm** [comment]
im aware of that, was there an issue with using internal module ONLY?

**Comment by bsongis** [comment]
I see the issue.

**Comment by i3dm** [comment]
is 2.3.6 coming?

**Comment by i3dm** [comment]
how do i get the fix?

**Comment by bsongis** [comment]
wait one hour, we will patch the server directly to avoid an extra delay

**Comment by i3dm** [comment]
do you rewrite 2.3.5 or is that 2.3.6?

**Comment by 3djc** [comment]
2.3.5

**Comment by i3dm** [comment]
thanks guys. how do i tell when this version will be online?

**Comment by dev-fred** [comment]
👍

**Comment by bsongis** [comment]
it's online now

**Comment by Ghost-B3** [comment]
It´s not working for me too. I´m running EU LBT version.
I´m still getting "wrong PCB Detected" message after flashing my radio with 2.3.5 version.
