### ISSUE TITLE
2.3.5 on Horus X10S Express ACCESS - Wrong PCB Detected

### ISSUE THREAD

**Issue by brian-sumpter** [opentx/opentx#7301]
When trying to upgrade firmware on my Horus X10S Express ACCESS model, radio boots after successful flash to black screen with "Wrong PCB Detected" text. Holding power lets the radio power down, but that is all that can be done. 

I was able to revert to 2.3.4 and radio is working again, so this appears specific to 2.3.5 version.

**Comment by i3dm** [comment]
issue already opened and fixed.

**Comment by 3djc** [comment]
Duplicate #7299
