### ISSUE TITLE
crossfireTelemetryPush function cause emergency mode on T16

### ISSUE THREAD

**Issue by lichtl** [opentx/opentx#7310]
**Describe the bug**
crossfireTelemetryPush function cause to crash openTX 2.3.5 (T16 will go into emergency mode / X9D will not properly execute function) when send 23 byte.

**To Reproduce**
1. Add/setup model with external Crossfire (no module required)
2. Add following lua on the SD card

```
local function run(event)
    lcd.clear()
	if event == EVT_ENTER_LONG then
        lcd.drawText(10, 20, "23 byte - PID change", 0)
        local result = crossfireTelemetryPush(0x78, {234,200,67,18,11,184,0,35,39,16,11,184,0,35,39,16,31,64,0,50,19,136,135})
        lcd.drawText(10, 35, "done", 0)
    end
	return 0
end

return { run=run }
```
3. Launch lua and hold ENTER key to trigger (T16 will go into emergency mode / X9D will not send out command) - https://youtu.be/ImHcW7YLh1A

**Expected behavior**
Command should be executed and send to Crossfire module

**General information**
 - OpenTX version (2.3.4 and 2.3.5 tested)
 - Hardware (Frsky X9D+, Jumper T16 both tested.)

**Comment by 3djc** [comment]
Anything above 16 (the size of the buffer) will get you into trouble I think. Will double check with TBS, and add a safety mechanism

**Comment by fedorcomander** [comment]
TBS packet is up to 64 bytes. It was ok on OTX 2.2.

**Comment by 3djc** [comment]
If you where sending 64 bytes in 2.2, you where probably massively exceeding buffer size (#define TELEMETRY_OUTPUT_FIFO_SIZE 16)

**Comment by fedorcomander** [comment]
Great… Well… There are specs for crossfire protocol, and buffer must be extended to 64 bytes. Sorry.

**Comment by 3djc** [comment]
Not sure we have the memory available for that, we will have a look, not commiting to that

**Comment by fedorcomander** [comment]
Well, telemetry receiving buffer is 256 bytes if i am not mistaken. which is quite a lot. can be smaller? ;)

**Comment by kilrah** [comment]
We can't control when we receive stuff, but we can control when we send stuff. Normal to have RX bigger.

**Comment by fedorcomander** [comment]
Yes, thats true. But specs are specs. 

Meanwhile, i patched device.lua so it will work with float numbers that kiss uses a lot. That DOESNT let you guys off the hook with buffer size ;)

**Comment by syrekszymon** [comment]
> ...Meanwhile, i patched device.lua ...

Where can i find it?

**Comment by AngusCox** [comment]
> > ...Meanwhile, i patched device.lua ...
> 
> Where can i find it?

Here, https://www.patreon.com/posts/33299763

**Comment by 3djc** [comment]
We will extend the buffer to 64 and put safeguards

**Comment by fedorcomander** [comment]
perfect! thank you from all kiss users.
