### ISSUE TITLE
opentx 2.3.5 unable to discover Telemetry A2 using FRsky v2.0.1 IXJT module

### ISSUE THREAD

**Issue by Hennyvt** [opentx/opentx#7317]
I have upgraded to Opentx 2.3.5 on my X10s IXJT to RFsky v2.0.1 as well as my X9D+ using RX6R also at v2.0.1 receiver and can no longer discover Telemetry sensor A2. This worked fine on the previous version.

**To Reproduce**
1. Go to '..Telemetry page.'
2. Click on '..Discover sensors..'
3. Scroll down to '...A2 not found.' RSSI and RxTx are found and working normally.

**Expected behavior**
A clear and concise description of what you expected to happen. A2 was discovered on the previous version 2.3.4

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by kilrah** [comment]
That would be a problem with the RF firmware, this is not the right place to report issues with it as we have no control over that.
Try here: https://www.rcgroups.com/forums/showthread.php?3507071-Important-Firmware-Update-%C2%96-ACCST-D16-2-0-0
