### ISSUE TITLE
Binding issue after updating to latest Rx firmware

### ISSUE THREAD

**Issue by Nadman1** [opentx/opentx#7318]
After updating the firmware on my two RX8R Pro and two M+ to the latest on the Frsky web page I was unable to bind them to my X10. My X10 firmware is version 2.3.5. 
After changing the Rxs FW back to the older version, I could bind them again.

**Comment by 3djc** [comment]
Nothing to do with OpenTX. You also need to update your x10 module firmware

**Comment by Nadman1** [comment]
Thank you for your reply.
Didn't know that. will update the X10 firmware.
