### ISSUE TITLE
Play Value Plays Starting Value Instead Of Ending Value

### ISSUE THREAD

**Issue by geekerator** [opentx/opentx#7321]
Please refer to the attachment. With openTX 2.3.4 on a Taranis X9E, I get what appears to be incorrect values when trying to play the value of CH9 (controlled by F1 and the curve CV1) when it changes by more than 5. The value played by SF12 is the value BEFORE F1 was moved. Since |d(CH9)| > 5 cannot be be detected until F1+CV1 has caused CH9 to change by more than 5 (and hence L10 to be raised), shouldn't the ending value be played? As a side note, the same behavior occurs in Companion's simulator if F1 is ROTATED SMOOTHLY. However, ENDING values are played if I CLICK ON RANDOM POINTS around the circumference of F1. Any help would be appreciated. Thank you...

[PlayValueIssue.pdf](https://github.com/opentx/opentx/files/4095109/PlayValueIssue.pdf)

**Comment by kilrah** [comment]
Please supply an otx, not a print.

**Comment by geekerator** [comment]
Posting an .otx here was rejected. I attached it to my reply to Andre's direct email (reply sent to: Andre Bernet <notifications@github.com>). If that is not correct, please let me know what to do and I will comply...Jeff

**Comment by geekerator** [comment]
Posting an .otx file here was rejected. I attached the .otx to my reply to Andre's direct email (reply sent to: Andre Bernet <notifications@github.com>). If this is not correct, please let me know and I will comply...Jeff

**Comment by kilrah** [comment]
Upload it somewhere and post the link, e.g. https://www.filehosting.org/

**Comment by geekerator** [comment]
Here is the link:

https://drive.google.com/open?id=1M57S3DyEvbUV4E7qWuuQ0RlCZf7682ft

I also renamed a copy of ChaserC1.otx to ChaserC1.zip and attached it to this post:

[ChaserC1.zip](https://github.com/opentx/opentx/files/4112163/ChaserC1.zip)

**Comment by geekerator** [comment]
[](url)

**Comment by geekerator** [comment]
Accidently closed.....

**Comment by geekerator** [comment]
An additional clue: if the ("play value" of CH9) special function is initiated by an actual switch, the current value of CH9 is played. If the ("play value" of CH9) is initiated by a logical switch, it plays the starting value.

**Comment by kilrah** [comment]
It's not the value before, it's the next value that is more than 5 off. Since LSs are evaluated >100 times per second even if you move the pot say +9%, during your move it will at some point be 5% and the play will be triggered there. Then since you're still moving, by the time the function gets executed it'll probably have moved a bit more so what gets played is maybe when you're at +7%.
