### ISSUE TITLE
setTelemetryValue(id    , subID, instance, value, unit , precision, name  ) doesn't allow to set SCALE for voltage sensors

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#7324]
The lua setTelemetryValue(id    , subID, instance, value, unit , precision, name  ) doesn't allow the scale to be set for voltage sensors, rendering the function practically useless for those sensors.

It would be very nice if that could be added as option.

getTelemetrySensor() would also be not bad as a function to manage the sensors better

**Comment by 3djc** [comment]
It is not meant to create sensors, but to simulate a flow of sensor data from lua data. If you want to scale the data, do it on lua side

**Comment by lshems** [comment]
The docs says differently.

It would be nice to have the default scale 13.2 added at least when adding a voltage sensor.

**Comment by lshems** [comment]
You cant prescale data when the scale on the sensor is autoset to zero without possibility to adapt from lua.

**Comment by kilrah** [comment]
The 13.2 ratio is irrelevant to anything other than the legacy Ax sensors. Use other IDs which don't have the limitation of being an 8-bit value...

**Comment by lshems** [comment]
No, rxbatt also.

Better would be if we would have real access to sensor definitions, but this could be a quick fix.
