### ISSUE TITLE
Companion: <total duration> computation in Telemetry logs window is wrong

### ISSUE THREAD

**Issue by MarkusPfaff** [opentx/opentx#7332]
One picture says more than a thousand words:
![image](https://user-images.githubusercontent.com/15657258/73098590-fe1f7d00-3ee9-11ea-9f1a-2727dc9cb307.png)

Best Regard
Markus

**Comment by 3djc** [comment]
What’s wrong ? The 4:06 covers the period from 13:51 to 17:57, which is right, so not sure what is wrong there ? Maybe ’time span’ would be a better choice of words

**Comment by MarkusPfaff** [comment]
Yes, this is about the wording and what we want to get from the data.

A "total" is a sum: total duration is the total of all durations thus the sum of all durations:
05:14 + 1:14:10 + 00:34 = 1:19:58
i.e. more or less the "flight time" you had this day (when taken in an optimistic way).

The time span the sessions are spread over is the time from the start of the first session to the end of the last session including all pauses in between. But this is not the total of the durations of all the sessions.
from 13:51:49 to 17:57:20+00:34 = 4:06:05

This is the time span the transmitter was first switched on until it was finally switched off. In many cases this will include a test at home before you put everything in the car to drive to the flying site and (like in the example above) a short test at home, because something needed adjustment. This may be more interesting for your family than you yourself, because they have proof that you are wasting too much time on your hobby.
