### ISSUE TITLE
Jumper T16 MDL button on OpenTX 2.3.5

### ISSUE THREAD

**Issue by FPVxfun** [opentx/opentx#7333]
Dear all, on the last OpenTX version, MDL button does not allow to enter Model Menu settings by short press. It only allows to enter display layout configuration. I hope you can fix It soon because in this condition the T16 could not be used. Thanks in advance

**Comment by 3djc** [comment]
You have likely a flat cable issue. Please go to RADIO/HARDWARE/Keys (at the bottom) and watch what happens when you push MDL

**Comment by FPVxfun** [comment]
Dear friend, all was working well up to 2.3.4 version. MDL Key Is correctly working with long press

**Comment by kilrah** [comment]
Entering model setup menu has always required a long press by design. Display layout config is accessed with TELE, so if that activates with the MDL key you indeed have a hardware issue with your ribbons, which is very common.

**Comment by FPVxfun** [comment]
Dear kilrah, you got the reason! T16 has BIG problems of soldering residual on PCB. When I got It for the First Time the scrolling was not working, now a push button. The problem Is the same. In order to solve all of them, I had to unmount/clean/reinstall ALL the PCB on the radio!!!! Honestly I think that Jumper has big quality problems on its best-seller T16!!!!
