### ISSUE TITLE
+/- changes the telemetry screen on Taranis X9D

### ISSUE THREAD

**Issue by jfrickmann** [opentx/opentx#7335]
Pressing the +/- buttons changes telemetry screens on X9D and plus, in addition to the PAGE button. This completely screws up Lua scripts that use these buttons, e.g. my SoarOTX programs.
https://github.com/jfrickmann/SoarOTX/wiki
Please remove that "feature" immediately!!!

Sincerely,
Jesper Frickmann

**Comment by r41065** [comment]
same as # 7309 ?

**Comment by jfrickmann** [comment]
Yes I think so
