### ISSUE TITLE
Support of Devo Telemetry

### ISSUE THREAD

**Issue by richardclli** [opentx/opentx#7340]
I checked the documents and settings, but cannot found any supports about the telemetry function of the Devo protocol.  It is not supported yet?  The version that I have tested is 2.3.5.

**Comment by richardclli** [comment]
I can see if I can contribute if this is not yet supported.

**Comment by 3djc** [comment]
Isn't that more a Multi request ?

**Comment by richardclli** [comment]
Just figured out that this is the multi module's function, and checked that it is not supported yet.  I will follow up this issue and try to develop a fix for this in the multi module project.

**Comment by richardclli** [comment]
Seems this is not only a multi request.  The telemetry decoding logic is in OpenTX source code and not only in the Multi source code.  I think I can solve this anyway ^.^

**Comment by 3djc** [comment]
yes, but those are usualy added to OpenTX by multi team, as it requires detailled knowledge of those protocol that we usualy do not have

**Comment by richardclli** [comment]
One thing I think it is not good is the telemetry receiving code and the telemetry decoding code splits into both the open-tx and the multi-protocol module code.  I think it will be better to have a unified telemetry protocol that bridges the module and opentx without the need to split the coding into 2 parts for different protocols implemented.

**Comment by richardclli** [comment]
I have added telemetry support for Devo in multi module using Frsky Hub, therefore only battery voltage is supported, mainly for microheli voltage feedback.
