### ISSUE TITLE
Cannot simulate model on OPEN TX Companion anymore.

### ISSUE THREAD

**Issue by fickjr** [opentx/opentx#7349]
I get a message now saying "Simulator for this firmware is not yet available."   It has been working on Windows 7 up until a few days ago.   Open TX 2.2.4 Companion,   I was going to try to uninstall the program and reinstall it but OPEN TX does not show up on my Program List.

**Comment by 3djc** [comment]
Sorry but this is a bug tracker site, not a support site. Please go to community support sites like rcgroups or open RC forums for support
