### ISSUE TITLE
LUA Script Menu - exit key closes the whole script

### ISSUE THREAD

**Issue by FrieKi** [opentx/opentx#7351]
252/5000
OpenTX 2.3.5
Taranis X9D +
yaapu / FrskyTelemetryScript

The script works great, but if I want to exit the Lua menu with the Exit button, it always closes the whole script.
  In OpenTX 2.3.1 everything is still in order (schort an long press exit).
Is this a bug in opentx?

**Comment by jfrickmann** [comment]
Yes, this is also the case with #7335. I made a pull request that will also fix this issue.
