### ISSUE TITLE
Screenshots viewer

### ISSUE THREAD

**Issue by kristjanbjarni** [opentx/opentx#7359]
It would be a great feature to be able to view your screenshots on the transmitter. For example if you want to mark your current location while flying, you can use a momentary switch take a screenshot of the telemetry screen including GPS coordinates, but the problem is you can't view this screenshot on the transmitter in the field without hooking it to a computer.

The way I see this work would be that you could go into the screenshots folder with the file manager and then just click on the bmp file and it would display on the screen, or long click and select "view image" similar like you can with text files.

**Comment by prodzprodz** [comment]
So is it possible to add option for displaying BMP files directly on the radio fullscreen when scrolling trough SCRENSHOT folder?
