### ISSUE TITLE
[Suggestion] Add ability to check if specific telemetry field is receiving data or not.

### ISSUE THREAD

**Issue by xoedusk** [opentx/opentx#7361]
**Request:** 
I would like the ability in both Lua scripting and in regular Logic Switches to check whether a specific telemetry channel (e.g., RPM, voltage, etc.) is actively receiving data or not.

**Reason:**
When flying and I lose a telemetry signal then I get the "sensor loss" announcement, but I do not know which sensor was loss. Having the ability to check if a specific sensor's telemetry data is or isn't being sent can be useful for me to make custom announcements, such as every 1 minute saying "no voltage data" or something to that effect.

**Comment by kilrah** [comment]
Already there, telemetry sensors appear as switches and those are true when data is received.
