### ISSUE TITLE
Crossfire tools crashed when using with QX7 and TBS micro TX / open tx 2.3.5

### ISSUE THREAD

**Issue by hervememain** [opentx/opentx#7362]
I have several error message when I try to change the settings for the crossfire (micro tx nano rx)

go to Tools / Crossfire Config

two lines appear : XF Micro TX and XF nano RX

when i select nano rx the screen become completely white, and if i press the scroll wheel I have the message : "Script Killed CPU limit". I can't modify the settings of the nano RX

when i select XF Micro TX it is the same : blank screen and the same message "Script Killed CPU limit" when i turn the scroll wheel

if on the blank screen, rather than using the scroll wheel I press the enter button I have an error message : 

Syntax error script
?:0 
attempt to index a nil val...

I don't see the end of the message because the line passes on the side of the screen

The binding between the RX and the TX seems to be good because the led on the nano rx goes from red to green when i turn on the RC

Moreover, when I go betaflight the RC is not recognized

**General information**
 - OpenTX version 2.3.5
 - Hardware : taranis QX7
 - OpenTX Companion 2.3.5
- SD card files : 2.3V0025

**Comment by hervememain** [comment]
![IMG_20200205_230540](https://user-images.githubusercontent.com/47895328/73887846-b6dfa780-486c-11ea-9fcd-a99e4722e1fa.jpg)
![IMG_20200205_230618](https://user-images.githubusercontent.com/47895328/73887857-bba45b80-486c-11ea-8cff-ac4d5694b9eb.jpg)

**Comment by 3djc** [comment]
Have you set your interface to 115 ? (Screen hardware, Max bauds to 115k)

**Comment by hervememain** [comment]
Thank you, fixing the baud rate to 115k works.
I also added the inverted mod on the QX7 and it works fine at 400000 bauds

Thank you

**Comment by jasc76** [comment]
What can it be if this message comes on a qx7s with hardware mod ?
TBS Crsfshot OpenTX Build.

**Comment by 3djc** [comment]
It means the communication is not working as it should, so hard to say
