### ISSUE TITLE
OpenTX 2.3.5 on Horus X10S

### ISSUE THREAD

**Issue by lennynpeter** [opentx/opentx#7365]
Hello,
I'm running the latest OpenTX firmware on my Horus X10S and all works very well. I can even flash the firmware through companion via USB and have according the manual the drivers installed with Zadig.
If I try to synchronize the SD card or use any of the options under the 'Read/Write' menu section I get the error 'No radio or SD card detected or 'Unable to find SD card'. I could find any hint to resolve the problem. Would very much appreciate any help on the subject. Thanks a lot!
Peter

**Comment by kilrah** [comment]
Radio needs to be on in bootloader mode for those.
Please note that this place is for issue tracking, not user support.
