### ISSUE TITLE
✱LES ICONES DU SIM ONT DISPARU ✱

### ISSUE THREAD

**Issue by andika207** [opentx/opentx#7367]
<a href='https://postimg.cc/zL2ytqHh' target='_blank'><img src='https://i.postimg.cc/zL2ytqHh/screenshot-3.png' border='0' alt='screenshot-3'/></a>

**Comment by 3djc** [comment]
English only please

**Comment by andika207** [comment]
@3djc c'est quoi la solution alors ?
