### ISSUE TITLE
Jumper T16 FlySky telemetry not working (FSky 2A)

### ISSUE THREAD

**Issue by Johnnysod** [opentx/opentx#7369]
Hi
I'm new to this and I'm using a EChine Trashcan FlySky version with a Jumper T16 running OpenTx-t16-2.3.5 (db7d2413). 2020-01-15

When I was using JumperTx  I had to bind using a AFHDS2A setting (from memory) and I was able to see telemetry like battery voltage, Under  OpenTx I now bind using FSky 2A but I can't discover any sensors in telemetry.
Any Ideas on what I'm doing wrong, or do you think the setting for FSky 2A has an bug compared to the JumperTx version?

John

**Comment by 3djc** [comment]
No known issues, on the contrary a lot of improvement have been made to FlySky telemetry . Are you running a recent multi module version ?

**Comment by Johnnysod** [comment]
Err I've not updated the module. I'll give that a go and see if it helps. I'll google what to do!

Incidentally I went to Opentx because my Crossfire module for my Cinecan didn't work, but it turned out the pins hadn't  lined up. I has to end then slightly to get it to connect. 
Anyway I think OpenTx is the future so I'm sticking with it

**Comment by Johnnysod** [comment]
Good call. I updated the module. 
Thank you I have telemetry again.
Although, a strange [ problem occurred, I am using RETA so I downloaded that multi firmware version, but it screwed up my channel order. The AETR version works fine even though I'm still on RETA?

**Comment by 3djc** [comment]
Closing this Check your model channel order, not the radio one

**Comment by Johnnysod** [comment]
Thanks again.
The channel order is RETA on everything but the firmware for the module is AETR. Strange but it all works!
When I used the RETA firmware the Yaw (R) and Roll (A) swapped. 
I don't understand why the Tx module needs to know the order, surely it just passes the value data on.
Unless it's for failsafe?!

**Comment by kilrah** [comment]
It's becasue the module is meant to be usable on radios where you can't select order, and so that you can always use the same order in your setups but the module reorganises them according to the specific protocol used.
