### ISSUE TITLE
Rescue Mode Horus X12S Bluetooth telemetry OTX 2.3.5

### ISSUE THREAD

**Issue by Bendau** [opentx/opentx#7375]
On openTX 2.3.5 in Horus X12S when the telemtetry of the Crossfire is redirect to the internal Bluetooth, the radio reboot in Rescue Mode.

**Comment by Bendau** [comment]
Test with 2.3.6 and 2.3.7 and same problem. Last test with 2.4 TBS nightly (CRSFshot) and no problem with the rescue mode.

**Comment by Bendau** [comment]
Oh Thank you ! If you need more test or what i can make to help you i'm in ;)

**Comment by Bendau** [comment]
[https://www.youtube.com/watch?v=tH-KONv9hjs](url)

**Comment by brainbubblersbest** [comment]
Do you use full speed crossfire with 400.000baud?
Would be interesting if that occours with Para BT Module too. 
Are you trying lower that telemetry speed? 
I dont know if thats an issue when send/mirror telemetry to a bt module running at 119200baud.
Maybe some one here can enlighten me?

**Comment by 3djc** [comment]
the telemetry is only a portion of those 400k, mainly used for channels
