### ISSUE TITLE
Default servo travel setting

### ISSUE THREAD

**Issue by jj-uk** [opentx/opentx#7378]
*Before suggesting a new feature here, please search the open issue if there is already a request for the feature*

**Is your feature request related to a problem? Please describe.**
The default servo travel is +-100%. Many of my models require a different travel, e.g. +-77.8%, +-82%(1100-1900) or +- 97.7% (1000-2000).

**Describe the solution you'd like**
Add a "default servo travel" setting as a per-model setting so that the servo travel is set to this value when "resetting" the servo travel value via the popup menu. Add a new menu item to the servo screen "reset all servos", which applies the default travel value, e.g. +-82%

**Describe alternatives you've considered**
Manually setting required channels to +-82%.....

**Additional context**

**Comment by loetefix** [comment]
I wish that function too.
Or an Entry in the Servo Menu with COPY LIMITS TO ALL Channels.
So you can Change all Ranges quickly.

**Comment by jj-uk** [comment]
+1 for copy limits to all channels.  
So to set all, the user would set the 1st row to the required limits, then use the menu to copy those limits to all the servo outputs.

I think this would be the easiest method for the devs to implement.

**Comment by loetefix** [comment]
I try to make it.Seems not to be that hard.If its ready i start a pull request.maybe they implement it.
