### ISSUE TITLE
2.3.5: Para Bluetooth not working for X10 express

### ISSUE THREAD

**Issue by patman13** [opentx/opentx#7381]
Still not working for me. 
X10 Ex as Master, X-Lite S as Slave —> not working
Other way round is working. 

Same as described in #7094

**Comment by dev-fred** [comment]
After investigating on my bluetooth, I am sure it's not working at all, a friend loan me a X-Lite pro.
When I select Bluetooth = Telemetry in Hardware page -> PIN Code  000000 and Local addr = 806FB01B6FC6
If I do the same choice in my X10 express -> PIN Code  000000 and Local add = ---

**Comment by afdofdez** [comment]
**Horus X10S Express EU   OpenTx 2.3.7**

After investigating on my bluetooth, I am sure it's not working at all, a friend loan me a Horus X10S.
When I select Bluetooth = Telemetry in Hardware page -> PIN Code 000000 and Local addr = 806FB0FE883A
If I do the same choice in my X10 express -> PIN Code 000000 and Local add = ---

in the bluetooth the my Samsung S8 it appears as "Hello" if I try to link it tells me that it has not been able to link and it shows me the remote address I suppose of my samsung S8.
![photo_2020-03-30_23-42-00](https://user-images.githubusercontent.com/56766487/77965881-4ab87780-72e2-11ea-8119-771626815840.jpg)

**Comment by dev-fred** [comment]
After changing my bluetooth module, it works like a charm, my problem was purely hardware
