### ISSUE TITLE
condition in logical switch not respected in GV

### ISSUE THREAD

**Issue by guillaumevaret** [opentx/opentx#7384]
Hi, 
Horus X10 Accst / 2.3.5 opentx-x10-lua-noheli-fr / 2.3.6N110

I have a condition in logical switch that doesn't work when it came from a global variable (here L12 : GV7 = 70), but work with a direct value (L13 x= 35). Doesn't work on companion either on the X10.

![opentx](https://user-images.githubusercontent.com/48926221/74442326-98cc0580-4e71-11ea-8882-22f7a08c9ad4.jpg)

**Comment by 3djc** [comment]
The value in the current sensor is in fact 700, it is displayed as 70.0 because your sensor is set with 0.0 precision. So in you case, set your GV to 700; or change sensor precision to 0.-

**Comment by guillaumevaret** [comment]
Thanks a lot, it works better than my "fix". 
I was using a momentary fix adding a mix line, switching the GV and the CH.
ch32 : max ratio(+vg7)
