### ISSUE TITLE
External & Internal module with CRSF protocol

### ISSUE THREAD

**Issue by jace26** [opentx/opentx#7385]
Version: 2.3.5 stable
Equipment: FrSky Horus x10s Express, R-XSR, TBS Crossfire Micro Tx, TBS Crossfire 8ch Diversity RX

I want to have dual band outputs with the internal FrSky 2.4 RF module and the External crossfire Micro Tx module. Currently, I can do this, but only if the external module is set to PPM, which means I cannot configure the module or the connected RX through the Lua script. 

I can in fact turn on the external module in CRSF with the internal module on, but there is no output on the RX until you switch to PPM or turn off the internal module.

Is there some hardware constraint that prohibits the desired behavior?

**Comment by kilrah** [comment]
Yes. CRSF communicates on the SPORT line, which is common with the internal module. When the internal module is on it forces that line low and corrupts the CRSF stream.

Some have cut the SPORT line on the internal module since it isn't used for anything.

**Comment by jace26** [comment]
@kilrah They cut the line to the internal module which allows the external module to talk on it? Sounds great, Where can I find that line? google didn't find anything, but I'm open to my fu being weak.

**Comment by jace26** [comment]
nm, found it.
https://www.rcgroups.com/forums/showthread.php?2922046-FrSky-Horus-X10-and-X10S-and-New-Express/page872#post42904121

may throw a switch in there so when frsky updates it to require the s.port I can fix easily
