### ISSUE TITLE
trainer/multi wrong trottle channel output

### ISSUE THREAD

**Issue by DarkSoulRL** [opentx/opentx#7387]
Jumper T16 PRO, internal multimodule + R9 
Taranis QX7 as as a student. OpenTX 2.3.5
Master / Multi Trainer Mode Set
SE switch assigned to enable trainer mode "Trainer Stiks"
All stick channels work correctly except trottle channel.
The trottle channel operates in the range of 0-200%. As a result, when the trainer mode is turned on, the model immediately receives 50% trottle.

**Comment by 3djc** [comment]
Just tested it, nothing like that. Please check your values in HARDWARE/TRAINER screen

**Comment by DarkSoulRL** [comment]
I do not know why:
Cal 0.0 0.0 100.0 0.0
