### ISSUE TITLE
SBUS generation corrupted when different refresh rate selected

### ISSUE THREAD

**Issue by krzysztofkuczek** [opentx/opentx#7388]
There is a problem with SBUS signal generated by Taranis x9D+ f.v 2.3.5. Channing refresh rate cause problems with generated signal. Applying values abowe aprox. 36ms cause that interval bw frames are set below 10ms. Except of that idle line is changed from high to low...

**To Reproduce**
1. Go to model setup menu
2. Click on sbus refresh rate for external module,  change to 38ms
4. observe sbus signal
5. change to different values like 20ms, 40ms, 36ms, go to point 4.

**Expected behavior**
- frequency of generated sbus frame should be adjusted according user's settings
- sbus line idle state should be low (according to inverted uart standard)

**Screenshots**
see the screenshots' all taken after signal inversion.
13ms
![13ms](https://user-images.githubusercontent.com/1246883/74593835-dd050480-502f-11ea-8d04-55e40a955d76.PNG)

36ms (please note idle line state)
![36ms](https://user-images.githubusercontent.com/1246883/74593836-dd9d9b00-502f-11ea-9ac5-bb1465d10806.PNG)

38ms
![38ms](https://user-images.githubusercontent.com/1246883/74593837-de363180-502f-11ea-9884-ee1939716408.PNG)

40ms
![40ms](https://user-images.githubusercontent.com/1246883/74593838-de363180-502f-11ea-90b1-2d07e1c0884b.PNG)

**General information**
 - OpenTX version 2.3.5
 - Hardware Frsky X9D+

**Comment by kilrah** [comment]
Polarity is selectable.
It makes no sense to go as high as 36ms refresh (the setting is meant to be able to replicate values between the standard 14ms and the FrSky 9ms), so if anything a limit just needs to be added.

**Comment by 3djc** [comment]
20 ms max ?

**Comment by krzysztofkuczek** [comment]
> 20 ms max ?

No. Plese keep 40ms. The problem with polarity is that during line idle state is changing every 2nd frame. See 2nd screen shot. 
PS. 
It would be greate to have also possibility to choose serial port speed to change it from default "standard" 100000bps 😁

**Comment by 3djc** [comment]
Why ? There is little point in having insanely slow  refresh rate

**Comment by krzysztofkuczek** [comment]
> 
> 
> Why ? There is little point in having insanely slow refresh rate

For LRS solutions...., there is enough to have 25Hz refresh rate, and SBUS frame can be easy use to "clock" air frame sending. Just DMA transfer ending after every SBUS frame can trigger sending air frame...
When user have possibility to adjust this timing, it's limits delays... 
Regarding serial port speed, it also would be useful, cause 100 000pbs are not supported by bt modules, etc....
Kris
