### ISSUE TITLE
Horus x12s hangs up in channel view

### ISSUE THREAD

**Issue by andreasstamm** [opentx/opentx#7390]
Hi OpenTx Team. 
I had a Bug yesterday with my x12s
After the landing, I was going to the channel. Monitor wo check ch9, to see what the actual value on the output is for the Gyro gain. 
As a went to model mdl key. Then when I pressed it the channel monitor again and then the page down to see ch9, the display and knobs for pageup/down and Rotary and display hangs up. Sticks switches and speech output was working.

After holding 10s the on butten and a restart every thing was working fine. 
I was not able to reproduce it. 

Versions of my x12s
2.3.5
HF 2.0.1LBT

Greetings Andreas

**Comment by 3djc** [comment]
Thats a known issue that we have never been able to reproduce.In 2.4, this will be fully rewritten, so hopefully this will fix it
