### ISSUE TITLE
Receiver ID on external 4 in 1 OTX 2.3.5

### ISSUE THREAD

**Issue by BergshamraFraggel** [opentx/opentx#7393]
new models are assigned receiver ID 0
Have tested Frsky D16 which previously automatically got unique ID for each new model.
Also, the warning when two models have the same receiver ID for D16 is gone.

Jumper T16
OTX 2.3.5

Best regards
Jonas Walther

**Comment by 3djc** [comment]
Just tried, same ID is reported correctly if module is the same and ID not 0, so working as intended. As for the new model ID, once you selected your protocol, go to model number and push ENTER LONG
