### ISSUE TITLE
Two errors detected in ES language. Both detected in the system folder

### ISSUE THREAD

**Issue by fmartinezo** [opentx/opentx#7398]
Two errors detected in ES language. Both detected in the system folder
There is no welcome wav file Hello.wav
The modelpwr.wav file is in English
These would be your Spanish translations:
For Helo.wav -----> Bienvenido a opentx (Bienvenido a open t equis)
For modelpwr.wav ----> El receptor esta conectado
I attach the two files already generated by me

[modelpwr.zip](https://github.com/opentx/opentx/files/4221574/modelpwr.zip)
[hello.zip](https://github.com/opentx/opentx/files/4221575/hello.zip)

**Comment by 3djc** [comment]
Giving us wav file will not help, they  are computer genrated each time a new pack is released.

This is the file that is used to generate the spanish pack : https://github.com/opentx/opentx/blob/2.3/radio/util/tts_es.py

I will put the changes you suggested into it, if there are more correction to be done, let us know
