### ISSUE TITLE
Cannot increase values in Crossfire / Kiss FC script

### ISSUE THREAD

**Issue by AuxPlumes** [opentx/opentx#7401]
Hello,

When entering into the Crossfire script, I have options to go into the NanoRx / MicroTX / and Kiss FC.
When I enter the Kiss FC, I can see all the values I need, but, I cannot increase any values, only decrease. This is the only issue I have with it, it saves when I change the value, but I cannot increase anything : PIDs, rates, etc ...
I have this issue with the QX7 / X9D+2019 and now the Tango 2. I'm assuming this is because of the scroll wheel type of input that messes with how it was coded, but it's a wild guess.
Can someone teach me how I can increment values in these settings ? I would really appreciate it !

**Comment by 3djc** [comment]
Tango 2 is not running OpenTX, so we can't help with that. For the other radios please try the scripts in https://downloads.open-tx.org/2.3/nightlies/sdcard/
