### ISSUE TITLE
I heard from domestic players that opentx will support Chinese language, right? Thank you.

### ISSUE THREAD

**Issue by Zhuwenpeng055** [opentx/opentx#7404]
If so, when can we use the Chinese version of Opened? We like Opentx very much, thank you

**Comment by 3djc** [comment]
Not before 2.4 at the earliest

**Comment by Zhuwenpeng055** [comment]
That means Chinese won't be included in version 2.3, right?

**Comment by kilrah** [comment]
Correct

**Comment by bsongis** [comment]
Yes it's there in 2.4 already. Japanese and Korean will be supported as well, the code is ready. We will need help for translating all the strings, as noone speaks Chinese (nor Korean and Japanese) in the team.

**Comment by iakuf** [comment]
maybe I can help for translating, What i can do ?

**Comment by iakuf** [comment]
I modify and create opentx/radio/src/translations/cn.h.txt ?

**Comment by 3djc** [comment]
Radiomaster is working on Chinese language translation for 2.4, maybe you can review those when they are done @iakuf ?

**Comment by RadioMasterRC** [comment]
Thanks 3djc, we are working on this now and will keep everyone posted.
