### ISSUE TITLE
No Logging of sensor data with Jumper T16 pro Internal module. When I look at the Sensor edit screen it is showing External module and cannot be edited.

### ISSUE THREAD

**Issue by rbayer62** [opentx/opentx#7408]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by 3djc** [comment]
It is indeed showing external, but that is for info only. Logging works

![image](https://user-images.githubusercontent.com/5167938/75115387-5cad5780-565e-11ea-9882-bc885c86cb74.png)

**Comment by rbayer62** [comment]
I hadn't set up logging in a long while. I had forgotten to enable in
Special functions. Thanks for the comment that jogged my brain cell.
