### ISSUE TITLE
 Reduce screen consumption in bootloader mode

### ISSUE THREAD

**Issue by mric3412** [opentx/opentx#7410]
When connected to a PC in bootloader mode, color LCD screen (e.g. T16) is all white : the battery is unnecessarily consumed.
![tmp](https://user-images.githubusercontent.com/6010627/75161491-3221d400-571c-11ea-9a57-da5059f44507.jpg)

It would be great to invert colors of the 2 bootloader screens ("WriteFirmware/Exit" option and "USB connected" message) in order to display allmost dark pixels and reduce the consumption.

Alternatively, having the option of simply turning off the screen (all pixels displaying in black) would be good for saving energy

This proposal concerns radios with large color screen (Horus, T16 etc.)

**Comment by 3djc** [comment]
It is not oled, so black pixels do not consume less...

**Comment by mric3412** [comment]
Ah! Sorry, it's not very intuitive... if it's an LCD backlight, it may even consume more when displaying black !? ... I guess there is no software way to stop powering the screen ?

**Comment by 3djc** [comment]
Consumption is extremely similar, mostly happening in backlight, not the lcd panel itself. All black screen can generate a little more heat, but that is not relevant in this case

**Comment by mric3412** [comment]
OK, thanks, I learned something ! It only remains for me to close this proposal...
