### ISSUE TITLE
Unable to Download 2.3.4 Firmware in Companion

### ISSUE THREAD

**Issue by DroneMang** [opentx/opentx#7419]
Hi,

On a clean install of 2.3.4 OpenTX Companion, there seems to be no way to get any firmware other than the newest 2.3.5 to download.  I do not have any prior firmwares saved.  I require the 2.3.4 firmware, to run the Yaapu Telemetry Script (https://github.com/yaapu/FrskyTelemetryScript) as it does not work with 2.3.5 yet.  I am able to download the source code from https://github.com/opentx/opentx/releases/tag/release%2F2.3.4 but then I would have to build it, which seems unnecessary.  On the 2.3.4 page http://www.open-tx.org/2019/12/23/opentx-2.3.4 I can download Companion in V2.3.4 and the SD card contents, but not the firmware.  Is there some way I can download just the .bin firmware file?  Thanks!

-DroneMang

**Comment by 3djc** [comment]
Working as intended, you cannot get any other 2.3.x than 2.3.5
