### ISSUE TITLE
Internal Antenna D8 doesn't appear - X-Lite S/PRO

### ISSUE THREAD

**Issue by Madsens** [opentx/opentx#7424]
After, 
1. installing the latest update to OpenTX Companion
2. selecting the Radio Type "FrSky Taranius X-Lite S/PRO", and then
3. updating the firmware with the "eu" checkmark,
the radio still doesn't display D8 in the internal antenna mode options.

Options are as before only "ACCESS" and "ACCST D16".

But as far as i understand from the latest release notes, the X-Lite S/PRO should be supported.

**Comment by 3djc** [comment]
Xlite S/Pro are access radio that do not support d8. It is a choice made by FrSky, not us
