### ISSUE TITLE
override function not returned in lua model.getCustomFunction

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#7427]
If you have an overrride function set on a custum (special) function, lua willl return a 0 for the function identifier in the model.getCustomFunction().

The model.setCustumFunction() is propably impacted as well.
 

**General information**
 - OpenTX version 2.3.5
 - Hardware any
 - OpenTX Companion also

**Comment by kilrah** [comment]
0 IS the correct value for override.

**Comment by lshems** [comment]
OK, Thanks.

Then I really don't get where I messed up :) creating the logging scripts.

I'll see if I overlooked something. 

Does this mean the channel value is stored in some other parameter?

**Comment by kilrah** [comment]
Channel value is stored in value...

XY problem? What are you actually trying to do?

**Comment by lshems** [comment]
No, No XY problem.

Since the dropdown on Companion is listing the override fucntions in the functionlist, I assumed every overridechX had it's own function ID.

The dropdown on the radio itself actually splits it nicely. function list and channel parameter.

Issue solved (lathough companion is not seperating the entries where the radio does)
