### ISSUE TITLE
LUA model.getGlobalVariable() crashes when optional FM is not given

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#7428]
bad argument #2 to 'getGlobalVariable' (number expected, got nil)

option 2 is flightmode, and is optional according to documentation.

Opentx 2.3.5

**Comment by 3djc** [comment]
Code exemple ?

**Comment by kilrah** [comment]
Doc is incorrect, argument isn't optional

**Comment by 3djc** [comment]
We do realise that the published doc is largely outdated, so for now, best is to look at the source code

**Comment by 3djc** [comment]
Which just got fixed by Kilrah : https://opentx.gitbooks.io/opentx-2-3-lua-reference-guide/content/

**Comment by kilrah** [comment]
Well no, the content is still unchanged

**Comment by lshems** [comment]
OK,

It would be nice to get the doc up. Thanks.

Would you mind if it got set to optional?

In lua you just put a getFlightMode() on the second parameter, but it is not that nice.
Could try to make a pull request some time.

**Comment by 3djc** [comment]
No reason for that’ even more if you assume current is the default, where I would have assumed 0, so keeping it mandatory is probably sensible.

And updated doc is up

**Comment by lshems** [comment]
Ok, I'll not bother to try create a pull request to default the flightmode to the current flightmode, and keep the parameter optional according to original documentation.

getFlightMode(mode) works with an optional mode parameter, but the doc is not mentioning optional, where it is. Defaults to current flight mode (which makes perfect sense to me).

So I don't understand why you would ever think 0 is the default flightmode for the optional 'mode' in the getGlobalVariable??

ticket is closed, retorical question.
