### ISSUE TITLE
[Taranis X9D+ 2019] Missing Serial Port in Hardware menu

### ISSUE THREAD

**Issue by zosko** [opentx/opentx#7429]
**Describe the bug**
I want to forward Smart Port telemetry from my Taranis X9D+ 2019 to my computer. But in my 2019 Taranis battery bay is different from this
https://github.com/opentx/opentx/wiki/Taranis-IO-ports
Also i notice that missing Serial Port Mirror in Hardware menu. 

In battery bay i have 3 pins on right side, S.Port , VCC and GND, but seems not working. Maybe they are not activated ? I mean is not working because VCC and GND there is no power.

Is it baud 57600 on S.port ?
Is it always inverted that signal ?

**To Reproduce**
1. Go to 'Hardware' menu
2. Scroll down to bottom and Serial Port missing

**Expected behavior**
Should see same menu like in old taranis ?

**Screenshots**
old taranis picture
https://www.imsb.ch/_Media/taranisconfig_med.png

**General information**
 - OpenTX version 2.3.3
 - Hardware Frsky X9D+ 2019

**Comment by kilrah** [comment]
2019 doesn't have a serial port anymore. The 3-pin connector is just a sport connection, and the internal module doesn't use it anymore so there's no data on it like before.
