### ISSUE TITLE
9XRPRO 2.3 switch mappings

### ISSUE THREAD

**Issue by solomondg1** [opentx/opentx#7433]
When I try to setup switches they seem to be named incorrectly. This is happening in companion as well. Ex:  3POS says Ail slider, RUD says THR, ELE says RUD.

**Comment by ElectroGloop** [comment]
I also have a 9XR Pro and can confirm I am having the exact same issue. Running OpenTX 2.3.7

**Comment by ikarus23** [comment]
Same here!

**Comment by JoshuaShaw** [comment]
Same here too

**Comment by pfeerick** [comment]
Same here. Just updated to 2.3.7 from 2.2.4 (mainly for the USB joystick mode) and 3POS (AUX3) and AIL D/R are wrong - 3POS comes up as ... is it alieron stick? ... and AIL D/R as ELE. ELE D/R comes up as RUD. RUD D/R comes up as THR. GEAR comes up as AIL. TRN comes up as GEAR. THR. CUT comes up as 3POS.
