### ISSUE TITLE
Jumper T16 auto off

### ISSUE THREAD

**Issue by ronbon172** [opentx/opentx#7438]
I recently left my radio on for a couple of hours and burnt out the internal module. Is there a way to auto shut off the radio or internal module to prevent burning it out accidentally?

**Comment by 3djc** [comment]
You have audio warning when not in use, and there is no reason that this would damage your module either

**Comment by ronbon172** [comment]
Unfortunately I left the room and forgot about it until later that evening. after that I keep getting "emergency" mode when power cycling radio. Grayson Hobby confirmed with me that the module is burnt out.

**Comment by 3djc** [comment]
I have a lot of respect for Grayson Hobby, but a burned module would not trigger emergency unless something very very strange has happened. Have you tried a new sd card ?

**Comment by ronbon172** [comment]
no

**Comment by 3djc** [comment]
That should be your first step, start with a blank, new, sd card, install sdcard pack (and only that), start the radio as new

**Comment by ronbon172** [comment]
thanks
