### ISSUE TITLE
Not enough flash available on this board for all teh selected options

### ISSUE THREAD

**Issue by PedroCortinas** [opentx/opentx#7439]
Hi, Im havinga a prblem with the firmware download for a Taranis X7: (opentx-x7-lua-luac-es-2.2.4.bin) i hvae the "Not enough flash available on this board for all teh selected options" message...
can you help me?

**Comment by Target0815** [comment]
Same for Taranis X9D (without plus). Selected options: noheli, nogvar, lua. Also no luck without this options.

@3djc, @kilrah

**Comment by Imperativ** [comment]
same here.
Firmware on Taranis D9X: opentx-taranis-noheli-nogvars-lua-en-2.1.9
Companion 2.2.4 stops downloading after short time with the error message:
**Not enough flash available on this board for all the selected options**

Happens, no matter wich hardware or option combination is selected
![Companion Error Msg](https://user-images.githubusercontent.com/7411921/76678694-2d916280-65da-11ea-8c72-51ced2581429.jpg)

**Comment by 3djc** [comment]
Yes @bsongis has been made aware of this issue, I'm sure he will fix it asap

**Comment by 3djc** [comment]
Could you try again ?

**Comment by Target0815** [comment]
It's fixed, I guess.  Thank you.

**Comment by PedroCortinas** [comment]
OK, perfect, thanks very much... all all right now...
