### ISSUE TITLE
Rx Channel Order not working in 2.3.6 for X Lite Pro

### ISSUE THREAD

**Issue by tdhouser1964** [opentx/opentx#7440]
Recently completely re set all firmware for my X Lite Pro due to an issue I was having. Spoke with FrSky rep in regards to proper firmware for X Lite Pro  using Crossfire protocol and was told to flash current OpenTx Companion version. Flashed 2.3.6 EEPR 219. Radio was set for Rx Channel Order TAER Mode 2. Betaflight Receiver Configuration also set for TAER to match Radio. Controls are mixed up and not correct.

**Comment by 3djc** [comment]
Channel order is a default configuration and only applys to newly created models (after settings is changed). Please use community places like RCGroups and openrcforums for end user support, not this bug tracker.
