### ISSUE TITLE
Horus X10S Express EU version Wrong PCB

### ISSUE THREAD

**Issue by Ghost-B3** [opentx/opentx#7441]
After OpenTX 2.3.5 flash into my new Horus X10S Express, I´ve got error message "Wrong PCB".

I´ve got EU LBT, mod 2 Horus X10S Express, so I´ve chosen "lua" and "eu", but it didn´t work either.
It uploads to the radio, but after turning it on, it says the error message "Wrong PCB".

I´ve searched for this issue, tried everything to make it work, but nothing helped.

Running 2.3.5 version of OpenTX.

**Comment by 3djc** [comment]
What is the exact name of the firmware you flashed ? (or what is the type of radio you selected in companion ?)

**Comment by Ghost-B3** [comment]
I’ve selected FrSky Horus X10 Express / X10S Express.

>What is the exact name of the firmware you flashed ? (or what is the type of radio you selected in companion ?)

@3djc

**Comment by 3djc** [comment]
Thanks We had a major issue that required us to qucikly change our firmware distribution servers. This caused a wrong 2.3.6 version to be available for a couple of hours, and also probably the issue here. I'm trying to contact the person in charge of this. Will keep this thread updated

**Comment by Ghost-B3** [comment]
>Thanks We had a major issue that required us to qucikly change our firmware distribution servers. This caused a wrong 2.3.6 version to be available for a couple of hours, and also probably the issue here. I'm trying to contact the person in charge of this. Will keep this thread updated

@3djc Is it repaired, or should we wait with flashing ?

**Comment by 3djc** [comment]
Repaired. You will need to redownload and reflash with newly downloaded firmware

**Comment by 3djc** [comment]
If you could also confirm the fix did work, it would be nice

**Comment by Ghost-B3** [comment]
It's working.
Updated without any issue.

Thanks for fast answer and fix. :)

**Comment by 3djc** [comment]
Thanks for letting us know. Closing this then
