### ISSUE TITLE
OTA not working - X10s express - 2.3.5 

### ISSUE THREAD

**Issue by nicoalas38** [opentx/opentx#7446]
On OpenTX 2.3.5 , horus x10s , the OTA firmware update is not working . 

Firmware uploaded in SD card (R9Stab_flex.frsk). 

ENTER - 
select "Flash receiver OTA firmware"
ENTER
however, nothing happen , there is no message "waiting for receiver"

**Comment by bsongis** [comment]
Please check in 2.3.6, it was not implemented in 2.3.5
