### ISSUE TITLE
input expo function set to diff when setting value to 0 in companion

### ISSUE THREAD

**Issue by lshems** [opentx/opentx#7451]
when setting the value of the expo to zero on any input, and saving the model, it will reset to diff as function type on next load.

**General information**
 - OpenTX version (e.g. 2.3.5)
 - Hardware (e.g. Frsky X9D+)
 - OpenTX Companion (e.g. 2.3.5)

**Comment by kilrah** [comment]
That looks intentional for eeprom savings.

**Comment by lshems** [comment]
It is annoying though if you really want expo on an input, and use a script to set it on a different value than zero.

Now you have to set it to expo as well for the script to work.

Close it if you like, but it seems a drastic measure to save a bit.

**Comment by kilrah** [comment]
This dates back from way before anyone would have dreamt of scripting, but is still valid...

**Comment by lshems** [comment]
Closing is fine with me.
