### ISSUE TITLE
2.3.5 failsafe not set after switch off and on the internal XJT module

### ISSUE THREAD

**Issue by janekx** [opentx/opentx#7452]
OpenTX 2.3.5 X9E 

Have switch ON the XJT internal module and set filesafe custom and set channels. 
Go to model and switch internal module XJT OFF.
Switch XJT internal module ON. 
FS is not set. 

Internal module FS setting is lost when switch OFF and ON module. 

As users wanted to switch off modules to prevent radiation doring long time model setup, is FS setting lost annoying when must set FS again.

**Comment by 3djc** [comment]
The same applies to all module data, not just failsafe (start, stop channel, rf protocol (d16/d8/lr12))

**Comment by kilrah** [comment]
To clarify the actual custom set values are kept since they are not in the module settings, but the global type selection is.
