### ISSUE TITLE
Seperate rssi indicators for internal and external modules

### ISSUE THREAD

**Issue by joedunnaway** [opentx/opentx#7455]
When using the internal module as the primary and the R9M external module transmitting to a 900 mhz redundant receiver, RSSI values do not seem to corralate with anything when doing a range test.  It is unknown whether you are seeing values from the main receiver or the redundant receiver.
   RSSI Values for 2.4 ghz and 900 mhz would tell you the reliability of both links.

**Comment by kilrah** [comment]
What radio? Most do not have separate telemetry lines that would allow this. External module needs to have telemetry set to disabled if the internal one is active.

**Comment by joedunnaway** [comment]
Radio is the Horus x10s express.  Receivers are the rx8r with Accst and the r9mm with Access.  R9mm was set to "no telemetry".  There is no option to disable telemetry on the external module.  An rssi value is displayed no matter which receiver is active. Joe DunnawaySent from my T-Mobile 4G LTE Device
-------- Original message --------From: Andre Bernet <notifications@github.com> Date: 3/24/20  2:31 AM  (GMT-06:00) To: opentx/opentx <opentx@noreply.github.com> Cc: joedunnaway <dunnaway@hbcomm.net>, Author <author@noreply.github.com> Subject: Re: [opentx/opentx] Seperate rssi indicators for internal and
  external modules (#7455) 
What radio? Most do not have separate telemetry lines that would allow this. External module needs to have telemetry set to disabled if the internal one is active.
