### ISSUE TITLE
X9 Lite not finding SD contents.

### ISSUE THREAD

**Issue by k0bae** [opentx/opentx#7464]
(OpenTX2.3.5) Open booting the radio an error message appears saying that it expects sd card contents *xxxxx*, which I have already installed the exact version on the SD card. I get no audio callouts, however can enter the SD card files from the radio settings. If I manually try to play an audio file an error message appears stating that the "path is too long" (amber back for 2.2, the original 2.3.5 sound pack did not work either).

**Comment by 3djc** [comment]
You probably did not install correctly your pack, but this site is not for end user suppor,t only for bug tracking. Please go to community sites like rcgroups or openrtx forums for user assistance.
