### ISSUE TITLE
OpenTX 2.3.4 and SD error

### ISSUE THREAD

**Issue by bonoboxita** [opentx/opentx#7465]
I've installed 2.3.4 and changed my SD card contents but i receive the splash screen regardi SD mismatch and it is looking for V2.2V0021 SD card

any suggestion?

**Comment by 3djc** [comment]
This site is for bug tracking only, not for end user support. Please go to community site like rcgroups or openrcforum for end user support. If your radio is asking V2.2V0021, then it is not running 2.3.4
