### ISSUE TITLE
Timer with 2 constraints

### ISSUE THREAD

**Issue by Quantumx3** [opentx/opentx#7466]
Hello,
I´ve been using OpenTx for around 6 years now and have alway wondered if it´s possible to create a timer with 2 constraints. I´ll give an example to explain:
1. I am using Throttle% as my Timer Input and have set a Throttle cut off. If I now raise the throttle, the timer starts counting, but the Engine on the model is not spinning up. With a second constraint like "If switch SG is in the upper position, then Throttle% as timer Input" 
That may seem like a very small issue, but there are some scenarios where this would make an huge difference and would make OpenTx even better:
1. If you are a Heli-Pilot and you fly with a Throttle curve, you may use Th% as input. But if you check the pitch, the timer will start counting. That may be easy to fix by resetting the timer, but the next scenerio is not:
2. I often fly sailplanes and want to know, how much capacity is left in the battery and how much time I am flying without motor-usage. The problem is, that if the motor is cut off, I steer the speadbreaks with my Throttle stick with full throttle being speadbrakes retracted. Because of that, I cant use any Throttle-related Input for my Capacity-timer, but have to use the switch for switching the flightmodes, which is far from ideal. As far as I know, there is now way to tackle this problem.

So to conclude:
I suggest implementing a second constraint for Timers in Open Tx, like
Flightmode1; Throttle%; 3 Minutes or
Switch C in middle Position; potentiometer 2; 5 Minutes
I hope I could convey my idea and hope it can and will be implemented in the Transmitter-software of choice.

I apologize for potential bad English, I am German

**Comment by 3djc** [comment]
Just set your Throttle source in model settings to wathever channel you want to use (instead of throttle stick)
