### ISSUE TITLE
Bootloader 2.3.6 ?

### ISSUE THREAD

**Issue by RookFPV** [opentx/opentx#7468]
Hello, I'm not sure but after updating OTX 2.3.6 and trying to flash the bootloader, the loading bar comes to an end everything is ok. However, the display reveals that it is still 2.3.5

Hardware X9D+SE
Frmware OTX 2.3.6

**Comment by kilrah** [comment]
The bootloader is still 2.3.5, but firmware will be 2.3.6, see that in the radio menus. 
Please note that this is not a support platform but a bug tracker.

**Comment by RookFPV** [comment]
Thanks You now work perfect

sob., 28 mar 2020, 09:34 użytkownik Andre Bernet <notifications@github.com>
napisał:
