### ISSUE TITLE
In SYS->CONFIGURATION ->USB  does not present the selected value

### ISSUE THREAD

**Issue by afdofdez** [opentx/opentx#7474]
![photo_2020-03-30_23-42-00](https://user-images.githubusercontent.com/56766487/77964877-2cea1300-72e0-11ea-9116-ccc913581181.jpg)
In SYS->CONFIGURATION ->USB it does not show the selected value, however it does change it. If you select SD it works fine when connected to the PC, but it still does not show it, if you select joystick it works when you connect it to> PC well but it still does not show it, but if you choose (sd / joystick) it does not ask and the PC does not recognize it.

Horus X10S   Opentx 2.3.7  windows 10

**Comment by 3djc** [comment]
This is an issue with Spanish translation, will have a look

**Comment by 3djc** [comment]
This will be fixed in next nightly and next release
