### ISSUE TITLE
Can't download firmware

### ISSUE THREAD

**Issue by flabrosse** [opentx/opentx#7476]
I'm new to OpenTX.  I recently received a Jumper T16 and have started using companion.  Version 2.3.5 and as of yesterday 2.3.7.

Every time I start Companion it wants me to download the firmware.  I say yes and this results in "Unknown server failure, try later".

The latest I tried was opentx-t16-&internalmulti-&lua-en but I have tried a variety of options, since 2.3.5, and now 2.3.7.

Pressing on the Release Notes button leads to a 404 error.

I have googled and searched through the issues here for the error message and only found one mention to old firmware versions, nothing to the current ones.

**Comment by kilrah** [comment]
Check that companion is set to the release channel.
Also is that the exact finlename with the "&"s in the name? This is incorrect, should be "opentx-t16-internalmulti-lua-en"

**Comment by flabrosse** [comment]
Thanks for the quick answer!

This is the name given in the window.  The URL I get in the console is [https://downloads.open-tx.org/2.3/release/firmware/getfw.php?fw=opentx-t16-%26internalmulti-%26lua-en.bin](https://downloads.open-tx.org/2.3/release/firmware/getfw.php?fw=opentx-t16-%26internalmulti-%26lua-en.bin). If I go to that URL I get an error 127.  If I remove the '&' (%26), then it does download something.  Using wget removing the %26 also gets me something that could be the firmware (binary file). 

Companion is set to the release channel.

**Comment by 3djc** [comment]
What OS are you using ?

**Comment by flabrosse** [comment]
Ubuntu 18.04.

The name it puts in the save box is `opentx-t16-&internalmulti-&lua-en-2.3.7.bin`.

**Comment by 3djc** [comment]
Are you compiling yourself ?

**Comment by flabrosse** [comment]
No, downloaded from the OpenTX [site](http://downloads.open-tx.org/2.3/release/companion/linux/companion23_2.3.7_amd64.deb).

**Comment by 3djc** [comment]
Just tested debian, looks fine, installing ubuntu

**Comment by kilrah** [comment]
Try deleting the radio profile and creating another and reconfiguring it

**Comment by flabrosse** [comment]
In fact, sorry, kubuntu 18.04.  Don't think it makes any difference though.

**Comment by flabrosse** [comment]
Just created a new profile (without deleting the previous one, does it make a difference?) and the same happens.

**Comment by flabrosse** [comment]
If I unselect all build options (which by the way happens every time I get into settings, I need to report that), then the '&' are not added.  It's only when build options are selected that the '&' are added.

And the download succeeds then.

**Comment by 3djc** [comment]
Just installed fresh Ubuntu 18.04, works fine

**Comment by flabrosse** [comment]
Even when selecting build options?

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/78025561-8e4ec800-735a-11ea-9579-9bc8c780fbd0.png)

**Comment by flabrosse** [comment]
With the same options:

![image](https://user-images.githubusercontent.com/16017784/78025815-8be87000-7352-11ea-8796-972f5c284e6a.png)

**Comment by 3djc** [comment]
There must be something wrong somewhere in your setup, working fine here right after default install

![image](https://user-images.githubusercontent.com/5167938/78025972-32d10a00-735b-11ea-9e5d-a714f9a0e631.png)

**Comment by flabrosse** [comment]
Given that it works without build options but not with build options, that points to a bug in the software, probably relating to my setup.  Closing seems a bit excessive.  Believe me I appreciate what you do for the community!  I do write software so will have a look when I have time, but please don't close it.  Others will have the same issue.

**Comment by kilrah** [comment]
Works fine here with ubuntu 19.10 too, and we never had a similar report even though this is years old. I looked at the code and don't see where something could be wrong, so it's likely some pretty unique interaction with QT and whatever you're using as desktop enviromnent. 
It's unlikely it's something we can investigate...
If you want seriously want to tackle it then we can reopen and assign you.

**Comment by flabrosse** [comment]
I'm downloading it and will compile from sources to see if this still happens.  If it does, then I'll have a look.  This will obviously take time as I don't have much time (even these days!) and I don't know the code at all.

**Comment by flabrosse** [comment]
"Good" news.  The self compiled version has the same behaviour as the pre-compiled one.  I'll work on it, but it will take time.

**Comment by flabrosse** [comment]
Quick investigation revealed that if I manually remove the '&' from the paths in the config file then all is fine.

If I create a new radio profile then the '&' are there.

Can someone reopen the issue please and I'll find a solution.

**Comment by bsongis** [comment]
@flabrosse thanks for your proposal!

**Comment by flabrosse** [comment]
I found the problem (but not the solution yet).  The name is made by concatenating a base name with a language and build option names, all separated by dashes '-'.  The build option names are obtained by getting the names of the corresponding QCheckBoxes.  The name contains an '&' as a shortcut, which is returned by the function text().

I found a couple of references to that, using PyQT, but apparently C++ suffers in the same way.  This seems to be due to a recent QT update (maybe a bug).  This is not documented in the QT docs.

I can see two solutions and would love to have some input from developers of the project:

Option 1: just parse the string and remove the '&'.  Simple and local, no global change required.

Option 2: not use the names of the QCheckBoxes.  Advantage is that they could use a more explanatory description.  The downside is that a lot of code (I guess) will need to be modified where the QCheckBoxes are created and used.

What do people think?

**Comment by flabrosse** [comment]
Fixing as Option 1 also fixes the bug where the build options appeared not be saved, obviously.

Because of that extra bit that I had not thought about, Option 2 is even less appealing.

Suggestions?

**Comment by kilrah** [comment]
The question is why does the name return an & on some systems and not others when it's the same code?

**Comment by flabrosse** [comment]
Good question.  The one discussion I saw online mentions a recent update of QT.

The most relevant package I think is:

```
Package: libqt5gui5
Version: 5.9.5+dfsg-0ubuntu2.5
```

Is that what others have?

**Comment by flabrosse** [comment]
I am ready to make a pull request with my option 1.  If people are happy for me to do it I'll do it.

**Comment by kilrah** [comment]
Do you have links to that discussion? It looks like a QT bug then, and it's rather there that it should need fixing.

**Comment by flabrosse** [comment]
Apparently that appeared in QT 5.4: [https://riverbankcomputing.com/pipermail/pyqt/2015-October/036499.html](https://riverbankcomputing.com/pipermail/pyqt/2015-October/036499.html)

My Ubuntu is up to date LTS, so not supporting that up to date version ot QT could limit a lot.  Also, the fix is trivial so not having it makes not much sense, IMHO.

**Comment by kilrah** [comment]
Can't just be that then, would have been an issue for years. 
Back to something weird with your environment. What exactly are you using as desktop environment and theme? In the past there was already an issue once where it was the user's UI theme that was broken.

**Comment by flabrosse** [comment]
I'm also not convinced it's a bug.  If you say button.setText("&lua"), you would expect that button.text() returns "&lua".

My Option 2 has the advantage that the software would be closer to an MVC model, while at the moment the UI is the data, with very tight integration.  But it would be a big change and probably way beyond that simple bug that consists of adding `.remove(QChar('&'))` at the end of a line.

**Comment by kilrah** [comment]
> I'm also not convinced it's a bug. If you say button.setText("&lua"), you would expect that button.text() returns "&lua".

Except that we don't put any &s in there.

**Comment by flabrosse** [comment]
I'm on kubuntu, with a standard KDE theme (Breeze Dark).

**Comment by flabrosse** [comment]
> > I'm also not convinced it's a bug. If you say button.setText("&lua"), you would expect that button.text() returns "&lua".
> 
> Except that we don't put any &s in there.

Interesting!  My companion definitely has shortcuts on almost everything on the Settings dialog.

I read somewhere that shortcuts could be automatically created to the first letter if not already set as a shortcut.  Some on the dialog are not the first letter.  I can't find that at the moment.  I'll investigate further.

**Comment by flabrosse** [comment]
It's a feature!  And other [projects](https://github.com/GoldenCheetah/GoldenCheetah/wiki/Working-around-KDE-shortcut-injection) have the same problem.

Given that it's a feature of some environments and that the fix is easy, should we just do it?

**Comment by 3djc** [comment]
Then fix should be on your environment:

add

[Development]
AutoCheckAccelerators=false

to ~/.config/kdeglobals

**Comment by flabrosse** [comment]
But it's not a bug in the environment, it's a feature!  Why not supporting it when it's so trivial to do it?  Other people will have the same problem (I'm not the only KDE user around!).

PS I don't use the feature, I never noticed it.

**Comment by flabrosse** [comment]
A lot of people are complaining about that feature (eg [link](https://bugs.kde.org/show_bug.cgi?id=337491) and a fix was introduced in 2019 for applications that don't explicitly link with KXmlGui.  Presumably companion uses xml gui.

I'm happy either way, but if nothing is done to make the code work, this should be documented somewhere, IMHO.

**Comment by kilrah** [comment]
So it's a bug in KDE that was fixed more than one year ago... no reason we'd have to add special handling for that.
This issue will be there to point people to should someone else have the problem.
