### ISSUE TITLE
no checkmark for Disable Telemetry on x9 lite italian on RX OPTION

### ISSUE THREAD

**Issue by alexdibi** [opentx/opentx#7490]
no checkmark for Disable Telemetry on x9 lite italian on RX OPTION

**To Reproduce**
1. Go to model page
2. Click on receiver and select RX option
3. See error on disable Telemetry option

![screen-2020-04-02-183044](https://user-images.githubusercontent.com/52356568/78281642-43c87980-751b-11ea-90eb-5250b884b003.jpg)

**General information**
 - OpenTX version: 2.3.7
 - Hardware: Frsky X9 Lite
 - OpenTX Companion (e.g. 2.3.7 on Windows 10)

**Comment by kilrah** [comment]
Can you provide what you think is a good label that is short enough to fit?

**Comment by alexdibi** [comment]
Telem. Off

**Comment by kilrah** [comment]
And current one is good for wider displays?

**Comment by alexdibi** [comment]
I have not tried

**Comment by kilrah** [comment]
No I mean is it good to keep that sentence, is the wording good?

**Comment by alexdibi** [comment]
yes, it can be fine, otherwise "Telemetria OFF" it should also be good for small displays and it would be good for both

**Comment by robustini** [comment]
My fault, thanks for the fix.

**Comment by robustini** [comment]
@3djc , check the fix, there's a doble "" before Telem. disabilitata

![immagine](https://user-images.githubusercontent.com/3864712/79743450-e303b400-8304-11ea-9486-860f704df234.png)

**Comment by 3djc** [comment]
fixed
