### ISSUE TITLE
Companion doesn't show the latest multiprotocol module Radio Protocols on Jumper T16

### ISSUE THREAD

**Issue by Gaylian** [opentx/opentx#7492]
Companion 2.3.7 doesn't show all the multi radio protocols on the internal radio system window.
It shows them on the Jumper T16 but when I import them into companion they are not there. I'm using Multiprotocol v1.3.0.79 to get the Frsky D16 version 2.01 protocol.

**Comment by kilrah** [comment]
Use a nightly build.

**Comment by 3djc** [comment]
Also, it is expected that not all the latest multi protocol are always included in Companion, the module can now tell the radio about the new protocol, but that does not include companion
