### ISSUE TITLE
OTX Companion Jumper T16 6P switch not changing icon

### ISSUE THREAD

**Issue by myozone** [opentx/opentx#7494]
I just discovered in Companion version 2.3.7 the 6 mode switch (6P) doesn't change the icon on the simulator screen - it stays at 1. This could be me not doing the right thing of course.

**Comment by 3djc** [comment]
Did you calibrate it ?

**Comment by myozone** [comment]
This is entirely in OpenTX companion (I'm not sure you can calibrate it within companion), I don't even own a T16 yet. I was just getting to the software first before I eventually get one.

**Comment by 3djc** [comment]
You can calibrate without companion simu as you would on a regular radio

**Comment by myozone** [comment]
> You can calibrate without companion

Eah?, I'm using companion - I don't own a radio

**Comment by 3djc** [comment]
Sorry mistyped : You can calibrate withIN companion simu.. I'm having a look at a possible callibration issue in the simu

**Comment by myozone** [comment]
Ah ok, I'll have a play - still learning

**Comment by myozone** [comment]
I get it to work once but it stopped again, also the '1' is greyed out a bit. It was lighter when it worked.
'Calibrated' a few times and re-selected  Mutlipos Switch for 6P within Hardware.

**Comment by kilrah** [comment]
The number staying at 1 is a known issue but the rest should work, even without calibration

**Comment by myozone** [comment]
Good to know, basically then the 6P mode switch in the simulator doesn't work. Everything else works apart from that.

**Comment by 3djc** [comment]
It mostly work, but as on the radio, it requires calibration. The calibration on the simu as some issues, but if getting a profile from a real radio, it works fine

**Comment by myozone** [comment]
Ok, I'll wait till I get a real radio - unless you have a real radio profile ?
