### ISSUE TITLE
SF PlayTrack: scrolling thru the audio files list is slow

### ISSUE THREAD

**Issue by kniuk** [opentx/opentx#7504]
Jumper t16 v.2.3.7

Conditions:
  SPECIAL FUNCTIONS menu:
    PlayTrack: scrolling thru the audio files list is slow. It takes ages to pick right file

Suggestion:
  Please change scroll speed dependent on wheel scrolling speed (same as in changing numeric values, or choosing switches/trims/logical switches/etc)

Also: While scrolling thru the list files could be played automatically.

Cheers!

**Comment by 3djc** [comment]
Dupliacte #6558
