### ISSUE TITLE
Windows size companion 2.2.x and 2.3.x under Linux

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#7509]
I think a see an issue here with oTx 2.2,.4 and 2.3.7 on my Thinkpad T450s running DEBIAN Testing.
Max. screen resolution is set to 1366x768

Full screen starting 2.3.7
![Bildschirmfoto_2020-04-09_14-14-21](https://user-images.githubusercontent.com/17964433/78894647-baaac880-7a6d-11ea-9c06-a9bf1d67def1.png)

and this is a 'full' screen with model setting opened
![Bildschirmfoto_2020-04-09_14-11-06](https://user-images.githubusercontent.com/17964433/78894764-fa71b000-7a6d-11ea-9512-8e1e3a457441.png)

The screen size of that window can not be reduced. Reduce window size is grayed out.

Not usable ...

br KH

**Comment by jtaylor2** [comment]
Clicking on a window edge or corner and dragging the window smaller doesn't work?

**Comment by ghost** [comment]
No.
I am running a VM on that T450s with WIN 10. (1366x768)
Here the fullscreen, which is ok.
![Unbenannt](https://user-images.githubusercontent.com/17964433/78899869-504a5600-7a76-11ea-8fc8-22192ed3ad0e.PNG)
 And here my desktop PC (DEBIAN Buster 1680x1050) with min size for that window.
Can reduce height to that min, but you are seeing min width. No further reduction possible.
![Bildschirmfoto_2020-04-09_15-28-34](https://user-images.githubusercontent.com/17964433/78900203-cc449e00-7a76-11ea-8003-dc157a3919ad.png)

br KH

**Comment by ghost** [comment]
Seems to be a DEBIAN issue.
Installed Linux Mint 19.3 Xfce on the T450s.

There it looks ok.

![Bildschirmfoto_2020-04-10_14-18-39](https://user-images.githubusercontent.com/17964433/78990493-dcbc4d80-7b36-11ea-8bf1-802f3045be43.png)

I am going to discuss that in DEBIAN forum.

Sorry and br - KH

**Comment by jtaylor2** [comment]
I tried yesterday to duplicate your problem in my self compiled openSUSE Leap 15.1 and Windows10 systems and could not duplicate it at any of my available screen resolutions.

For what it's worth I loaded Debian 10 in a virtual machine and tested the .deb at a screen size of 1360x768 and saw no problem.
![Screenshot_20200410_082816](https://user-images.githubusercontent.com/6879281/78991530-242ae580-7b07-11ea-8722-797d969e032a.png)

**Comment by ghost** [comment]
Thank you for trying, Jim. The T450s is on Testing, I guess, with Buster (DEBIAN 10) it could be ok.

I also asked in the Xfce forum and got this answer. 

https://forum.xfce.org/viewtopic.php?id=13894

So seems to be NOT an oTx and NOT a Xfce issue, it is pointing in the DEBIAN Testing direction.

Best regards and have a nice day - KH
