### ISSUE TITLE
SD Manager crash on X9E

### ISSUE THREAD

**Issue by ServError** [opentx/opentx#7513]
Looks like this might be similar to the Horus SD Manager crash.

1. Go to SD Manager page
2. Firmware immediately kicks back to main screen with error

**Expected behavior**
SD Manager opens

**General information**
 - OpenTX version 2.3.7 219
 - X9E with Horussticks

**Comment by 3djc** [comment]
Has been fixed on 01/04. Please use a recent nighty to fix this issue until next 2.3.8

**Comment by ServError** [comment]
Verified, sorry, I thought I was already on the nightly.
