### ISSUE TITLE
Companion - optional selection for Radio Profile on startup

### ISSUE THREAD

**Issue by sande005** [opentx/opentx#7514]
Add a "pop up" selection box on startup that prompts user to select a saved radio profile to be active.

For those of use with multiple radio types (X9D+, 10S, etc., etc.)  it is common to start companion and forget to choose the correct saved profile, resulting in starting over when the error found, possible wrong radio information (calibrations, etc.) saved to the radio, or errors due to wrong type.

Whether this feature to be active can be enabled/disabled via a checkbox under "Application Settings".

**Comment by 3djc** [comment]
This is a nice idea, but I doubt any of us will have the time for it, it would be a very good contained work for a volunteer with QT knowledge !
