### ISSUE TITLE
Owner Registration ID in companion does not allow numerical characters

### ISSUE THREAD

**Issue by plogibear** [opentx/opentx#7522]
Hi,

I found a bug in OpenTX companion V2.3.7 its connected to an FrSKY Xlite Pro.
Under Radio Settings >> Owner Registration ID (Owner Registration ID in companion does not allow numerical characters).

However on the FrSKY Xlite Pro you are able to change your Owner Registration ID it accepts both alphanumerical characters.

![Screenshot](https://user-images.githubusercontent.com/17494278/79301946-714ef300-7f1d-11ea-86ed-5f557dbb3320.png)

**Comment by pr-newman** [comment]
Issue also applies to FrSky Taranis X9D+ 2019 with v2.3.7.  Same details as for FrSKY Xlite Pro.

**Comment by 3djc** [comment]
It has been fixed already, please get a nightly companion

**Comment by pr-newman** [comment]
Thanks - I twigged it was Companion not Firmware after I commented! 8-)  Cheers --Pete
