### ISSUE TITLE
OPCIÓN MULTI MÓDULO EN VERSIONES POSTERIORES A 2.2.4

### ISSUE THREAD

**Issue by lauchablanca** [opentx/opentx#7526]
Hola gente Mi QX7 tenía la versión 2.3.0, pero no tenía la opción MULTI Módulo en esa versión, tampoco en la descarga de COMPANION más actual.
Tuve que hacer un DOWNGRADE, a la versión 2.2.4, para poder elegir la opción MULTIMÓDULO en el Companion.
¿Por qué desapareció esa opción desde la versión 2.2.4 en adelante?
No se puede agregar a versiones posteriores a 2.3.0?
Para poder usar mi Módulo externo IRX4 tengo que utilizar una versión vieja de OPENTX.

**Comment by kilrah** [comment]
Multimodule is always included since 2.3.0.

**Comment by lauchablanca** [comment]
![image](https://user-images.githubusercontent.com/63833418/79570780-71bbcb00-8090-11ea-9069-c1d096ddb258.png)

**Comment by lauchablanca** [comment]
Where is the multimodule option?

**Comment by 3djc** [comment]
Please read above ....

**Comment by lauchablanca** [comment]
> Por favor lea arriba ...

Friend, I read, but  I download the OpenTX Companion more recent that 2.2.4, and not have the multimodule option. Do you see my shared picture?

**Comment by 3djc** [comment]
READ THE ABOVE POST BY KILRAH !

**Comment by lauchablanca** [comment]
> ¡LEA EL ANTES POSTAL DE KILRAH!

Ahh, ok ok. I will read now. Thanks

**Comment by lauchablanca** [comment]
Friend, I don't want to bother or be pushy. Does the multi-module option appear with another name? They just tell me "it's always included since 2.3.0", but I installed at least 5 or 6 Comanion yesterday and none had it.

**Comment by 3djc** [comment]
....

ANY 2.3.x firmware DOES include it, whithout the need to tick any option. Download a firrmware, flash it, and it will be there

**Comment by lauchablanca** [comment]
Ahh, oK. Thanks. I will try now. Thanks again
