### ISSUE TITLE
MAVLINK extension broken

### ISSUE THREAD

**Issue by avrgandy** [opentx/opentx#754]
Issue replication:
- Upgraded 9XR to latest OpenTX using latest Companion9X with MAVLINK extension ticked only. OK.
- Upgraded the APM 2.5 to latest version of Arduplane (2.78b), set BAUD to 57600. OK.
- Using OpenLRSng (Gitsly branch) connected to PC via FTDI cable at BAUD 57600. OK.
- PC (Mission Planner) gets and displays all data correctly, BAUD set to 57600. OK
- On 9XR set baudrate to 57600 in radio settings, however MAVLINK params do not display. FAIL

Problem: Serial passthrough works fine but no data gets displayed on 9XR MAVLINK screens ("INV. MAV TY" shown as current mode). I suspect the MAVLINK defs in OpenTX do not match latest APM/MissionPlanner defs?

**Comment by EvgMe** [comment]
Problem not fixed. Display shows Mavlink data only at 19200 bitrate. Pleace, fix it.
