### ISSUE TITLE
What is the taranis rf backboard transmitter I.C. name/number?

### ISSUE THREAD

**Issue by mstram** [opentx/opentx#7540]
I'm looking for info on the Taranis RF I.C.,specifically to see how opentx is "talking" to it.

What is the taranis rf backboard transmitter I.C. name/number?

Is there a datasheet application note(s) ?

Any supported transmitter info is welcome.

If the Taranis x9 lite is supported, info on that transmitter is appreciated.

Mike

** p.s.*

Which source file is doing the low-level "talking"  to the  rf board ?

I've found some "dma setup" info in extmodule_driver.cpp,  but I haven't found  where the "DMA is connected" to the rf module

**Comment by 3djc** [comment]
We are sorry but this is a bug tracking system, not a support site
