### ISSUE TITLE
set Internal/External RF Module ON or OFF in LUA scripts

### ISSUE THREAD

**Issue by nik012003** [opentx/opentx#7541]
I need to turn on and off the External RF Module with a LUA script. 
`    model.setModule(1, {subType = -1} )
` only works with the XJT Module (and it doesn't even seem to be working: in the Simulator running 2.3.7 running this code it sets the mode to "ACCE" not "OFF" like it used to do on 2.2)
How can this be achieved?

**Comment by rzzuozuo** [comment]
subType  is onlyRead value
