### ISSUE TITLE
Horus X12S (ACCESS upgrade) doesn't handle "frsk" firmwares

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#7543]
Hi folks,

Horus X12S owners who upgraded the internal module from iXJT to ISRM need to upgrade some RX from ACCST D16 to ACCCESS.
Unfortunately the X12S can not handle **.frsk** extension (OpenTX 2.3.7).
Only the extension **.frk** is currently supported.
I guess it is the same thing for non-ACCESS X10/X10S

**Comment by kilrah** [comment]
Should work in nightly
