### ISSUE TITLE
jumper t16 very few wav files

### ISSUE THREAD

**Issue by capposteve** [opentx/opentx#7544]
there seems to be hardly any wav files in the latest sd card download, for instance there is no "armed" or "disarmed" in the list, where there used to be

**Comment by 3djc** [comment]
Default sound pack come with basic voice file needed for basic OpenTX operations and come in 8 languages. There are other user made packs, in various languages, that include more sounds tailored to specific activities. As for Armed/Disarmed, they have never been in our packs, but I will had it, as it is probably widely used those days
