### ISSUE TITLE
Jumper T16 Pro Hall

### ISSUE THREAD

**Issue by Joshenriquei** [opentx/opentx#7546]
I bought a new Jumper T16 Pro Hall, direct from China, in Ali express site. This was in December 2019. I received the radio on February 2020, about first week. After using the transmitter for two weeks without problem, I get an issue, the button page stops to scroll over the top menu. I get the beep, but the cursor do not move on menu. Then, was impossible to program the model.
Then I change to OpenTX. Just now I am using OpenTX 2,3.7 and sdcard-480x272-2.3V0026.zip. But, without any menu on screen.
Is there some procedure to solve this problem?
The transmitter continue to work, the SD Card is OK, I can create a new model, bind the receiver, but nothing about programming.
I know about the fight between OpenTX and JumperTX , and I am with OpenTX.
 Some help?

**Comment by kilrah** [comment]
Problems with the controls are due to the ribbon cables inside the radio, remove/clean/reseat them

**Comment by Joshenriquei** [comment]
Sorry Mr, but the problem is not control. The issue is in program. I already disconnected the flat cable between SDCard support and main board, clean it and connect again.  The issue continue. Someone have a new suggestion?

**Comment by 3djc** [comment]
Maybe do a video ? Really hard to understand what you are talking about

**Comment by kilrah** [comment]
The ones you need to reseat are those that go to the buttons and the wheel.

**Comment by Joshenriquei** [comment]
![WIN_20200423_15_46_29_Pro_LI](https://user-images.githubusercontent.com/16443845/80139550-020c7b00-857d-11ea-9402-d7ab3fd4db3e.jpg)
This is the problem.

**Comment by 3djc** [comment]
Your sdcard content is wrong

**Comment by Joshenriquei** [comment]
![image](https://user-images.githubusercontent.com/16443845/80140184-fec5bf00-857d-11ea-8ed4-feac7cad5d88.png)
This is my SDCard contend.

**Comment by 3djc** [comment]
Very wrong indeed. You need to bring up he content of the sdcard folder to sd card root

**Comment by kilrah** [comment]
You should not have the "sdcard-xxx" folder in there, the contents of it must be at the root.

**Comment by Joshenriquei** [comment]
![image](https://user-images.githubusercontent.com/16443845/80140767-d2f70900-857e-11ea-8ba7-63ad20128379.png)
Like this?

**Comment by 3djc** [comment]
No, here you should see RADIO MODELS SOUNDS IMAGES SCRIPTS...

**Comment by Joshenriquei** [comment]
Sorry, I don't know how to do this. Could you help me?
![image](https://user-images.githubusercontent.com/16443845/80141308-bc9d7d00-857f-11ea-8085-98b26c91ea59.png)
For instance, like this?

**Comment by 3djc** [comment]
You need to move all this up in the root directory

**Comment by Joshenriquei** [comment]
Solved! many,many thanks.

**Comment by Joshenriquei** [comment]
![WIN_20200423_16_41_13_Pro](https://user-images.githubusercontent.com/16443845/80143399-210e0b80-8583-11ea-9a11-706111064ce2.jpg)
Now I have programming Menu. Thanks
