### ISSUE TITLE
external multi-modul: Protocol settings garbled

### ISSUE THREAD

**Issue by twistedwings** [opentx/opentx#7548]
Protocol settings of the external multi-modul are garbled after reading into companion.

Settings in X7 (protocol 62, XK):

![image](https://user-images.githubusercontent.com/562809/80197347-cb873c80-861e-11ea-8b36-2008f986bd8e.png)

After reading models into companion:

![image](https://user-images.githubusercontent.com/562809/80196707-09379580-861e-11ea-9bbf-4dcdc6dc7534.png)

Taranis X7
iRangeX IRX4 FW v1.3.0.86
OpenTX 2.3.7
Companion 2.3.7

**Comment by 3djc** [comment]
Perfectly normal to not display newer protocols in companion. We probably need to alter number displayed (59 is what opentx uses to match multi 62), but we probably need to restrict the display to just protocol and subtype for unknow protocols

**Comment by twistedwings** [comment]
I understand that unknown protocols are displayed by number instead of text.
I do not understand why protocol 62 is changed to 59.
If I write the model back to the Tx, the protocol changes from 62 to 59 in the Tx also.

![image](https://user-images.githubusercontent.com/562809/80212611-12356080-8638-11ea-9be9-1a4a3992fd9d.png)

**Comment by 3djc** [comment]
Thats an issue. if you look on the tx , all frsky protocol are presented as one, you select frsky, and you have a choice of d8, x , v all in one. This ugly hack (like both Pascal and myself call it) create a progressive negative slide in protocol number (3 for protocols after 25, two from 15,..) Really ugly, but historical and cannot be changed before 2.4. Still I'll work on fixing the issue you esxperience comming from this

**Comment by twistedwings** [comment]
I understand, that is really ugly.
Shall I close the issue or leave it open ?

**Comment by 3djc** [comment]
No no, I need to fix the fact it gets displayed wrong

**Comment by 3djc** [comment]
Fixed at the same time as #7575 I believe
