### ISSUE TITLE
macOS 10.15.4  Compiling OpenTx Error info = fatal error: 'Availability.h' file not found

### ISSUE THREAD

**Issue by 1371030** [opentx/opentx#7549]
macOS:10.15.4
Xcode:11.4.1

gcc -v
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

cd build
cmake -DPCB=X10 -DPCBREV=T16 -DHELI=YES -DDEBUG=NO -DPYTHON_EXECUTABLE=/usr/local/cellar/python/3.7.7/bin/python3 -DCMAKE_BUILD_TYPE=Release ..
make firmware

-- OpenTX 2.3.7 @8b080683
-- Python found, version: 3.7.7
-- Qt Version: 5.14.1
-- Foxlib found at /usr/local/lib/libFOX-1.6.dylib
-- Found SDL: /usr/local/lib/libSDL.dylib;-framework Cocoa (found version "1.2.15") 
-- SDL Lib: /usr/local/lib/libSDL.dylib;-framework Cocoa; Headers: /usr/local/include/SDL; Version: 1.2.15
TARGET simu/libsimulator: cpp compiler /Library/Developer/CommandLineTools/usr/bin/c++ v11.0.3
-- Added optional gtests target
-- The ASM compiler identification is Clang
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
TARGET bootloader: cpp compiler arm-none-eabi-g++ v4.9.3
TARGET firmware: cpp compiler arm-none-eabi-g++ v4.9.3
TARGET companion: cpp compiler /Library/Developer/CommandLineTools/usr/bin/c++ v11.0.3
-- Added optional gtests-companion target

Compiling Error info:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:44:15: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:44:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include/stddef.h:102:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include/stddef.h:102:
  /usr/local/Cellar/gcc-arm-none-eabi-49/20150925/bin/../lib/gcc/arm-none-eabi/4.9.3/include/stddef.h:425:3: note: previous definition is here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:427:10: fatal error: 'Availability.h' file not found
  datastructs.h:531:10: note: in file included from datastructs.h:531:
  ./gui/480x272/layout.h:24:10: note: in file included from ./gui/480x272/layout.h:24:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:182:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:182:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:659:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:659:
make[3]: *** [radio/src/datacopy.cpp] Error 255
make[3]: *** Deleting file `radio/src/datacopy.cpp'
make[2]: *** [radio/src/CMakeFiles/datacopy.dir/all] Error 2
make[1]: *** [radio/src/CMakeFiles/firmware.dir/rule] Error 2

**Comment by kilrah** [comment]
https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15

**Comment by 1371030** [comment]
@kilrah Thanks,

But,

macOS 10.14.6
Xcode 11.0

make firmware
[  0%] Built target lua_export_t16
[  3%] Generating datacopy.cpp
/usr/local/Cellar/gcc-arm-none-eabi-49/20150925/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/include/sys/cdefs.h:371:9: warning: '__nonnull' macro redefined [-Wmacro-redefined]
  datastructs.h:25:10: note: in file included from datastructs.h:25:
  targets/horus/board.h:26:10: note: in file included from targets/horus/board.h:26:
  targets/common/arm/stm32/board_common.h:103:10: note: in file included from targets/common/arm/stm32/board_common.h:103:
  targets/horus/../simu/simpgmspace.h:32:10: note: in file included from targets/horus/../simu/simpgmspace.h:32:
  /usr/local/Cellar/gcc-arm-none-eabi-49/20150925/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/include/unistd.h:4:11: note: in file included from /usr/local/Cellar/gcc-arm-none-eabi-49/20150925/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/include/unistd.h:4:
  /usr/local/Cellar/gcc-arm-none-eabi-49/20150925/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/include/sys/unistd.h:11:10: note: in file included from /usr/local/Cellar/gcc-arm-none-eabi-49/20150925/bin/../lib/gcc/arm-none-eabi/4.9.3/../../../../arm-none-eabi/include/sys/unistd.h:11:
  note: previous definition is here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/__stddef_max_align_t.h:32:21: error: typedef redefinition with different types ('long double' vs 'struct max_align_t')
  datastructs.h:531:10: note: in file included from datastructs.h:531:
  ./gui/480x272/layout.h:24:10: note: in file included from ./gui/480x272/layout.h:24:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:183:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:183:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:653:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:653:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:406:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:406:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:45:15: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:45:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/stddef.h:118:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/stddef.h:118:
  /usr/local/Cellar/gcc-arm-none-eabi-49/20150925/bin/../lib/gcc/arm-none-eabi/4.9.3/include/stddef.h:425:3: note: previous definition is here
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:423:10: fatal error: 'Availability.h' file not found
  datastructs.h:531:10: note: in file included from datastructs.h:531:
  ./gui/480x272/layout.h:24:10: note: in file included from ./gui/480x272/layout.h:24:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:183:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/list:183:
  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:660:10: note: in file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:660:
make[3]: *** [radio/src/datacopy.cpp] Error 255
make[3]: *** Deleting file `radio/src/datacopy.cpp'
make[2]: *** [radio/src/CMakeFiles/datacopy.dir/all] Error 2
make[1]: *** [radio/src/CMakeFiles/firmware.dir/rule] Error 2
make: *** [firmware] Error 2

**Comment by 1371030** [comment]
generate_datacopy.py run error

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/__stddef_max_align_t.h:32:21: error: typedef redefinition with different types ('long double' vs 'struct max_align_t')

brew install llvm6

/usr/local/Cellar/llvm@6/6.0.1_3/lib/libclang.dylib
/usr/local/Cellar/llvm@6/6.0.1_3/lib/clang/6.0.1/include/__stddef_max_align_t.h:32:21: error: typedef redefinition with different types ('long double' vs 'struct max_align_t')
