### ISSUE TITLE
Menu jumping to system monitor. 

### ISSUE THREAD

**Issue by Oldgibber** [opentx/opentx#7554]
Not sure whether this is a bug or a deliberate system feature. 

On the Horus, when you enter the model menu and press the MDL button again, it jumps to the channel monitor. Does the same on both the tx and the Companion simulator.  Does not appear to happen with other transmitters.

**Comment by kilrah** [comment]
Intended, so you can quickly go see what the result of your change was. It is on other radios, eg. with MENU on X9D.
