### ISSUE TITLE
Logical switch always True if variable (V1) as Timer1  (V2) as  (any setting time)

### ISSUE THREAD

**Issue by njozsef** [opentx/opentx#7563]
**Describe the bug**
Timer1 countdown not triggering available: (9xrpro)

     Function   V1            V2
L01  a<x           Timer1     0:04:10 [h:mm:ss]

**To Reproduce**
1. setting on remote ctrl (9xrpro)
2. set model menu countdown as Timer1 04:00
3. set L01 a<x Timer1 00:00:10 (10 seconds before end)
4. L01 always on any time.

**Screenshots**
-

**General information**
 - OpenTX version (2.3.7)
 - Hardware (9Xr Pro)
 - OpenTX Companion (e.g. 2.3.7 on W10)

Thank you.

**Comment by 3djc** [comment]
Maybe a 9xr pro issue, because it works fine here on several other radios

**Comment by 3djc** [comment]
Set at 0:00:10 as mentionned 

![image](https://user-images.githubusercontent.com/5167938/80788992-05aa8e00-8b8b-11ea-8ce9-e1be6ebac2ee.png)

![image](https://user-images.githubusercontent.com/5167938/80789018-165b0400-8b8b-11ea-9dee-9a31d953d943.png)

![image](https://user-images.githubusercontent.com/5167938/80789082-3be80d80-8b8b-11ea-8f1c-85bdc04c9765.png)
