### ISSUE TITLE
Logical switch batt. variable is clock format 

### ISSUE THREAD

**Issue by njozsef** [opentx/opentx#7564]
**Describe the bug**
Logical sw. Batt. is time format.  9.8V unavailable,  9.59 continued 10:00, not 9.6

**To Reproduce**
1. power on 9xr pro radio
2. set any logical sw v1=batt
3. try set v2 9.8V   (v2 not number, v2 is time format.)

**General information**
 - OpenTX version (2.3.7)
 - Hardware (9Xr Pro)
 - OpenTX Companion (2.3.7 on w10)

thank you

**Comment by 3djc** [comment]
9XR specific
