### ISSUE TITLE
as there are some sensors only show as an ID instead of a name, so where I can find a list of all the sensors with all the name and unit etc. 

### ISSUE THREAD

**Issue by xixijoe** [opentx/opentx#7571]
The issue tracker here is for devlopment of OpenTX. This is not a
support site, only a bug tracking system. Please use support groups
like [rcgroups](https://rcgroups.com/) or
[openrcforum](https://www.openrcforums.com/forum/). See also our
[manual](https://opentx.gitbooks.io/manual-for-opentx-2-2/).

For quick questions you can also join our general chat.

Issues that fall into the category of asking for help, will be
generally closed as invalid without an answer.

**Comment by kilrah** [comment]
Sensors with no ID are non-standard, so you should refer to that sensor's documentation.
