### ISSUE TITLE
test if effective bind

### ISSUE THREAD

**Issue by vmath54** [opentx/opentx#7576]
It would be interesting to have a variable which indicates whether the bind is effective or not.
Example of use : in a logical switch, so as not to trigger a 'Bind On Channel' if the RX is already in bind.

**Comment by 3djc** [comment]
If you have telemetry, you are bind. If your receiver does not support telemetry, then there is no way to know

**Comment by vmath54** [comment]
OK. Thanks for the explanation

**Comment by 3djc** [comment]
And just in case you haven’t noticed, telem is a available ‘switch’

**Comment by vmath54** [comment]
no, I didn't notice it.
I will see on which models it is possible.
Thanks
