### ISSUE TITLE
T16-OpenTx2.3.7 Possible Tmr3 bug...

### ISSUE THREAD

**Issue by Key0nee** [opentx/opentx#7583]
**Describe the bug**

if using more than one telemetry screen and a Lua scripts that requires a fullscreen layout ie. (Inav Telemetry widget or Yapuu Mapping Widget) Timer 3 resets from 00:00 to 01:00:00 and the "1" cannot be reset. 

**Possibly Related but not sure how to reproduce**
 Switch SF (left side 2 pos switch) disappears from the available sources list.  I was trying to assign Tmr3 as a persistent manual reset timer, triggered by !^SF when I discovered it. upon highlighting the "trigger" selection for the timer and toggling switch SF it will select, however !^SF is never displayed.

**To Reproduce**
Create a second and or third telemetry screen, set to full screen with no trims or top bar and enable one of the telemetry widgets listed above.  the error seems to happen on page switching and or power cycle. 

**Expected behavior**
I would expect that Tmr3 like tmr 1 and 2 to be able to reset to 00:00 like the others. and also be able to use !^SF...

**Screenshots**

![IMG_0103](https://user-images.githubusercontent.com/29189979/81009643-dfdeec80-8e09-11ea-8392-11baeda2c13a.jpg)

**General information**
 - OpenTX version 2.3.7
 - Hardware Jumper T16proV2, Multiprotocol V 1.3.0.91 AETR
 - OpenTX Companion MacOS 2.3.7

**Comment by 3djc** [comment]
known issue with third party widget
