### ISSUE TITLE
Separat model handling feature request

### ISSUE THREAD

**Issue by jonasbjurel** [opentx/opentx#7585]
First I want to thank you all for a super good project. The openess, features and stability is just amazing!!!

This is not really an issue, but rather a companion feature request.
I have plenty of models for which evolves over time - both from HW capability-, as well as from TX/Telemetry programing/logic perspective.
These model projects/improvements don't go hand in hand timewise. Sometimes I'm working on my See-Cub, sometimes on my J29 turbine…., and sometimes on multiple projects at the same time.
To my point here - I would like to version control all of my models separately and not as a bundle of models.

Does the idea of separate model handling (download/upload/save) make sense to you. And would it make sense to have these fragments handled in some kind of source format (.xml, .yaml, ...). In that way every model could be version controlled separately - and in my case I would version control them using git, or even github.

Best regards/Jonas Bjurel

**Comment by kilrah** [comment]
We already have work in progress for replacing the current storage with YAML, but it's kind of a long term project. Current structure is how it is becasue of the way the older radios store data.
