### ISSUE TITLE
Jumper T16 Pro V2 Internal Radio off

### ISSUE THREAD

**Issue by Jannovik** [opentx/opentx#7586]
Hello,
I updated the Jumper T16 Pro Hall V2 (2020 Model) to firmware 2.3.7 and I can't turn on the internal radio. The option is not available in the radio. In the OpenTX Companion I see the internal radio options, but I click to turn it on and only off shows up in the drop down menu. I flashed to firmware 2.3.5 and it works again.
**General information**
 - OpenTX version 2.3.7
 - Hardware T16 Pro Hall V2
 - OpenTX Companion 2.3.7 macOS 10.15.4

**Comment by 3djc** [comment]
You forgot to enable internalmulti before downloading the firmware

**Comment by Jannovik** [comment]
How do I do that?

**Comment by HyperProxy** [comment]
Hello @Jannovik, How did you get back to 2.3.5 after you upgraded to 2.3.7? I have upgraded and I have had some problems and would like to go back, but cannot get a 2.3.5 firmware file.

**Comment by Jannovik** [comment]
What problems are you having? I made a backup of the firmware before upgrading. I had many problems, but they ended up being hardware related. I ended up emailing Jumper RC and they helped me fix it.

**Comment by HyperProxy** [comment]
I was having “key stuck” and it wasn’t taking any input. I worked with people in the Discord server. I ended up swapping the ribbons for the scroll wheel and right button set. That fixed it up nicely. Thank you though. I should really start making backups of my models and versions.

**Comment by Jannovik** [comment]
I had a similar problem. The SH switch would trigger 2 other switches. I also swapped the ribbons and that fixed it. Good luck and happy flying.

**Comment by HyperProxy** [comment]
Thanks, you too!
