### ISSUE TITLE
Too many analog lines in calibration for X10 in companion

### ISSUE THREAD

**Issue by 04fxdwgi** [opentx/opentx#7593]
Radio: Taranis X10S
OpenTX rev: opentx-x10-lua-ppmus-en-2.3.7
OpenTX Companion rev: 2.3.7
Issues:
1. Edit Radio Settings / hardware tab: Shows two components EX1 and EX2. Unknown what these 2 are
2. Edit Radio Settings / Calibrations tab: Shows calibration numbers for EX1 and EX2
3. Edit Radio Settings / Calibrations tab: Shows calibration numbers for components ??? and ??? on last two lines. Unknown what ??? and ??? are.

![X10S Odd radio Hardware settings](https://user-images.githubusercontent.com/65063010/81467115-7a418600-91a4-11ea-92b8-e9bec4cdf0fc.jpg)
![X10S Odd radio Calibration settings](https://user-images.githubusercontent.com/65063010/81467117-7ada1c80-91a4-11ea-82fe-405713be0a6f.jpg)

**Comment by kilrah** [comment]
EX1/EX2 are additional pots that can be connected to free connectors on the radio board.
Please note that this is not a place for user questions.

**Comment by 04fxdwgi** [comment]
Andrea, 

Thank you for the rapid response.

Please excuse my ignorance, as this is first time on GitHub. My train of thought was that it went hand in hand with the Hardware Calibration for the two slots labeled ???

Are the two calibrations labeled ??? a mislabel? I was unaware X10S had available inputs (EX1 and EX2) for unused POTs.

Thank you again

Regards

Bill Curtis

**Comment by kilrah** [comment]
The ??? are nothing, likely we just display too many lines.

**Comment by 04fxdwgi** [comment]
Thanx again
