### ISSUE TITLE
Add "power smart port" option for powering receivers outside the quad (for binding)

### ISSUE THREAD

**Issue by jag-88** [opentx/opentx#7595]
It's sometimes frustrating binding a receiver after installing it in the quad.

I would like the ability to power a receiver off the smart port pins outside of the flashing process. This could be very useful for binding/registering receivers outside of the quad without needing to purchase a laboratory power supply.

The smart port already powers the receiver during the flashing process so the ability to get power from the smart port pins is already there, I propose adding a selection under radio setup to turn on the power to the smart port pins so that you can bind the receiver using that power source.

**Comment by 3djc** [comment]
Already existing

**Comment by jag-88** [comment]
@3djc The feature exists or the feature request already exists? If the feature exists could you tell me where it is in the menu? I would like to try it out :)

**Comment by 3djc** [comment]
Exist since March 10, in Radio/hardware menu, almost at the end

**Comment by jag-88** [comment]
Found it! Thank you so much! :)
