### ISSUE TITLE
Bootloader Update alternatives

### ISSUE THREAD

**Issue by raznzsnasna** [opentx/opentx#7597]
Hello developers,
my X9d plus get a new update, the last was from 2016.
Now i want to update the bootloader, but the long klick of enter the taranis break down.
backlight flash, vibration for 0.1second and nothing else.
same problem if i switch to page 3 of modell settings. Flash, vibrate, back to main screen.
with long page i can go beck thrue the modell settings. But from page 4 to 3 the same problem.

Is there an alternative to update the bootloader without longpress?

Sry for english :)

**Comment by 3djc** [comment]
Sorry but this is a OpenTX bug tracking system, not designed for end user support. Please use forums like RCGroups or OpenRCForums for end user support. Updating the bootlaoder can be done from companion and flashing the radio turned off
