### ISSUE TITLE
Selection of any internal module mode on X9E transmitter crashes the screen

### ISSUE THREAD

**Issue by FS4000** [opentx/opentx#7600]
Describe the bug
Selection of any internal module mode on transmitter crashes the screen

To Reproduce

1. Make a new model (MODELL44), with or without wizard on X9E
![screen-2020-05-12-142554](https://user-images.githubusercontent.com/41964852/81694950-43989380-9462-11ea-9577-07b0c69c670c.jpg)
2. Click on Menu and select on the second screen INTERNAL HF- MODULE > MODE
![screen-2020-05-12-142614](https://user-images.githubusercontent.com/41964852/81695000-53b07300-9462-11ea-93ae-cca587093552.jpg)
3. Selection of any internal module mode crashes this screen and brings
    it back to the first screen. Its not possible to choose the internal module.
    On the first screen an exclamation mark appears on the upper right corner.
![screen-2020-05-12-142627](https://user-images.githubusercontent.com/41964852/81695160-89edf280-9462-11ea-9b41-5d3d5505b03d.jpg)
4. Selection of another model (MODELL43) can not bring the transmitter back to normal function.
    Only a restart is the solution.
![screen-2020-05-12-143448](https://user-images.githubusercontent.com/41964852/81695346-c6b9e980-9462-11ea-9ff0-d5f9e6bd2a7a.jpg)
5. On Companion, i can choose the internal module and it is active on the transmitter.
    I found two Issues with similarly problems: #7126 and #7594
    The same configuration on my Taranis QX7 works as it should, no problems!
 
Expected behavior
This reaction maybe dangerous and should not happen when running the system on the field.

General information
 - OpenTX version (2.3.7)
 - Hardware (Frsky X9E XJT ACCST with IRangeX Multiprotocol Module, Firmware v1.3.0.95) 
 - OpenTX Companion (2.3 on Windows 10)
 
Thank you for your work, i like OpenTX!

Kind regards, Uwe

**Comment by 3djc** [comment]
Could you include you OTX file ? It is clearly not happening here, most likely, you have set using companion a forbiden configuration.

**Comment by FS4000** [comment]
Here my otx- testfile (scroll down to MODELL43). I made the models not in companion, they were created on the transmitter first! On my older configurations it also works, but i can't tell when the error occurred for the first time.
[X9E_Test.otx.txt](https://github.com/opentx/opentx/files/4617701/X9E_Test.otx.txt)

**Comment by Rivelino911** [comment]
Same for me on Taranis X9D+ (non 2019) when i select internal module. For external no problem.
After i write 2.3.7 also removed SD and made a factory defaults. No go.

**Comment by 3djc** [comment]
> Here my otx- testfile (scroll down to MODELL43). I made the models not in companion, they were created on the transmitter first! On my older configurations it also works, but i can't tell when the error occurred for the first time.
> [X9E_Test.otx.txt](https://github.com/opentx/opentx/files/4617701/X9E_Test.otx.txt)

This file is empty

**Comment by FS4000** [comment]
Hello 3djc,
please rename the file (delete .txt) and then in Companion scroll down to MODELL43.

**Comment by 3djc** [comment]
Cannot duplicate the issue, please give us an eeprom backup instead

**Comment by FS4000** [comment]
Here the Eeprom file:
[eeprom-2020-05-14-175520.bin.txt](https://github.com/opentx/opentx/files/4629532/eeprom-2020-05-14-175520.bin.txt)

**Comment by FS4000** [comment]
If the screen crashes, as a result of the module selection,
the voltage display shows zero volts for a short moment.
Maybe this will help.
Regards, Uwe

**Comment by bsongis** [comment]
Did you all select the "internalppm" option in Companion? If yes the bug is fixed (and the option removed as it shouldn't be used here!)
