### ISSUE TITLE
[Horus] Power on is not possible via shortpress of power button

### ISSUE THREAD

**Issue by F-Po** [opentx/opentx#7605]
On OpenTX 2.3.7 the option "Pwr On delay" is missing. The delay seems to be hardcoded to 2s. I don't like to push the button over a long time to power it on. Please add this option or restore the old behavior.

![screen-2020-05-15-070629](https://user-images.githubusercontent.com/64350741/82014593-39061600-967d-11ea-8bb0-c1955bfcdc39.jpg)

**Comment by 3djc** [comment]
What radio/version are you comparing with ?

**Comment by F-Po** [comment]
Sorry, I forgot: Horus X12S compared with X-lite and QX7

**Comment by 3djc** [comment]
Ok, I understand then. There is not delay added on horus, thats just how the hardware is built, and there is nothing that can be done about that I'm affraid

**Comment by F-Po** [comment]
That could be not correct. The behavior was seen by me first in 2.3.5. Until 2.3.2 there was no power on delay.

**Comment by 3djc** [comment]
Well, I'm running 2.2.4 and I'm need to push 2secs for the radio to turn on, so I must not be looking at what you mean. Could you do a video with 2.3.3 and 2.3.7 showing the difference ?

**Comment by F-Po** [comment]
Yes, but it takes a while.

**Comment by F-Po** [comment]
Correction: My version before was the 2.3.2.

Here the videos:

OTX 2.3.2: https://youtu.be/X4oUTuV9OvU
OTX 2.3.7: https://youtu.be/6YpfdBtywCw

**Comment by maru-sama** [comment]
I just had a quick look at the code, and apparently both Power On Delay and Power Off Delay are defined. But Power ON is neither showing up in companion nor the simulator or the device itself.

**Comment by 3djc** [comment]
because it is not used by Horus ...

**Comment by 3djc** [comment]
If another dev wants to have a look, my x10 in 2.3.2 does not behave at all like in the video, so not sure if it is x12 specific, or if my proto has an issue

**Comment by F-Po** [comment]
Could someone please check if one of these commits should be the reason for this issue: 

https://github.com/opentx/opentx/pull/7212
     - The taranis has the power on delay option
     - If currently the same code is used could it be possible that the default/initialisation value of 2s is used also on the Horus?

https://github.com/opentx/opentx/pull/7096
    - Is it possible that currently the Horus always ends in unexpected shutdown and the restore at the next boot will take some time?

**Comment by 3djc** [comment]
yes : no and no

**Comment by kilrah** [comment]
- Horus can't easily have configurable power on delay becasue the data is stored on SD card, and the settings aren't read until a few of seconds into power up which is obviously too late

- X12S was the first of the radios using SD card. No delay was put initially as it had a switch cover.

- Now there are many radios using SD card and no other has a switch cover, so a delay was introduced, and it's there for everything, no interest in maintaining a special case just for X12S

**Comment by F-Po** [comment]
Just for clarification: The configurable value is secondary for me - I don't need that.

But the issue that I must longpress the power button is primary. Don't sure if there is a critical bug behind this new behavior. But longpress to power it on is crab at the X12S. So I hope the old behavior can be restored.

I changed the title to avoid missunderstandings.


THX

**Comment by F-Po** [comment]
pls fix!

**Comment by F-Po** [comment]
Is this the way OpenTX-gods work? Kill basic functionalities / create bugs with ass in front and ignore the issues to close! Such a case of arrogance!

If you go this way straight, your quality / stability will decrease rapidly in the near future. Today there are simple handling issues like a button that have another behavior, not loaded backgound pics, ... But when this ignorance will reach critical functionality, OpenTX will die rapidly!

Developing new features is always more fun. But fixing bugs is the main doing of a sw developer. So fix your f***ing bugs!

**Comment by F-Po** [comment]
Oh, inconveniant comments are deleted. I have another one: If you go this way straight, your quality / stability will decrease rapidly in the near future. Today there are simple handling issues like a button that have another behavior, not loaded backgound pics, ... But when this ignorance will reach critical functionality, OpenTX will die rapidly!

Developing new features is always more fun! But fixing issues is essentially **the** main thing in sw development. So fix you f***ing bugs!

**Comment by kilrah** [comment]
It's not a bug, it's an intentional change as explained before. 

OpenTX is going to die rapidly becasue you can't be bothered to hold a button for one second, really?

**Comment by lshems** [comment]
I do understand his grievance. It's more about how than what. 

But you know me. So ignore.
