### ISSUE TITLE
Companion sensor units incorrect in some instances

### ISSUE THREAD

**Issue by elecpower** [opentx/opentx#7608]
eg Cels unit should be V

![Screenshot from 2020-05-16 07-01-36](https://user-images.githubusercontent.com/15316949/82096203-d9bf0900-9743-11ea-891c-c888eb522da6.png)

Suspect PR #7529 is the culprit

**General information**
 - OpenTX Companion 2.3.8 Ns on Ubuntu 16.04

**Comment by kilrah** [comment]
How did Cels get into the list?
Only discovering it will set the correct unit. 
It's known that sometimes a major version upgrade hasn't kept the units right though.

**Comment by elecpower** [comment]
Cels was discovered pre 2.3.
The PR was only merged in the last month and added a new unit before volts in Companion. The result a description shuffle of those units below the new unit.

**Comment by 3djc** [comment]
m/l min is not before volt as far as I can remember, it was last, before hours, but after all "units"

**Comment by kilrah** [comment]
It is after volt but before the virtual units, which Cels is one of.

But the linked PR is correct, it's before that that it was wrong and would be unrelated, issue happens while upgrading in eeprom structure handling. 
Did you do the 2.2 to 2.3 upgrade on the radio or on companion?

**Comment by elecpower** [comment]
I cannot be certain but more than likely used Companion. Probably would have read radio settings into Companion.
I'll see if I have a backup 2.2 radio eeprom and/or Companion files and try some conversions to see if I can replicate.

**Comment by elecpower** [comment]
Investigation so far. Looks like the otx I was using was corrupted by too many tests however reading models and settings from a X9D+ 2.3.7 the unit is blank in Companion logical switches but correctly V on the radio and Companion simulator.

![lsblankunit](https://user-images.githubusercontent.com/15316949/82711058-b9ed8f00-9cc7-11ea-86be-4be6c54169d1.jpg)

![lssim](https://user-images.githubusercontent.com/15316949/82711247-28325180-9cc8-11ea-84c9-8ae36ae03a0f.jpg)

Still working thru the source code but it appears Companion was not updated to reflect the EEPROM version 219 change for 2.3 that added spare sensor units (commit # dcc803c5). PR 7529 added the new unit only.
