### ISSUE TITLE
X-Lite and OpenTX 2.3.7 - Can't read/write models & I can't read SD card via PC

### ISSUE THREAD

**Issue by imfatant** [opentx/opentx#7609]
This may be the same issue as described in https://github.com/opentx/opentx/issues/6425, in that I too have an X-Lite, and receive the same error message when trying to read models in Companion. However, I'm using OpenTX 2.3.7.

I have copied the accompanying SD card contents onto the SD card separately - i.e. using my PC with a SD card dongle. To sum up, I am now faced by what I believe is a single problem with two symptoms:

1) I can't access the SD card by plugging the X-Lite into my PC (after attaching the USB cable, I power the X-Lite on by first holding down the cross-shaped button and then pressing the power button). When I do, two new drives are detected. One, called 'Taranis', contains EEPROM.BIN, FIRWARE.BIN and FIRMWARE.TXT files. The other, called 'USB Drive (F:)' cannot be opened. I just get 'Please insert a disc into USB Drive (F:).'

2) I can't read or save models in OpenTX.

I *can* access the SD card contents from the radio itself.

**Comment by kilrah** [comment]
No known issue around that, using it myself. Must be a problem with your setup. Try other USB cables for example.
