### ISSUE TITLE
2.3.7 Jumper T12 Pro - GPS sensor not showing valid coordinates

### ISSUE THREAD

**Issue by peteoz** [opentx/opentx#7621]
On my Jumper T12 Pro display screen I only get a 6 digit number where the value of GPS coordinates is supposed to show up (the "GPS" sensor)

on Telemetry page under sensor "GPS" I also get the same 6-digit number followed by 3 letters "low"

I don't understand how is this of any use or how is one supposed to convert this to useable GPS coordinate format to locate a lost drone, this is not a valid GPS format (not even the new single string Google Plus Code)

is this a bug ?

**Comment by 3djc** [comment]
What gps sensor ? What type of receiver and telemetry ?

**Comment by peteoz** [comment]
> What gps sensor ? What type of receiver and telemetry ?

I'm using HGLRC Ublox M8N GPS, TBS Crossfire Rx and running Betaflight 4.1.5

on my Betaflight OSD coordinates show correctly as 2 separate values (longitude and latitude).
also when running exactly same setup on Taranis radio everything works as expected and the GPS sensor displays 2 separate values (Lon + Lat)

only on Jumper T12 Pro I get this 6-digit number followed by "low".

My concern is that the Googles DVR not always records, I found occasions (mostly during crashes) that the Fatshark Goggles DVR fails to record and I can only rely on my radio.

**Comment by peteoz** [comment]
here are few photos of what I'm getting on the screens and on Telemetry page.
(in my "Radio Setup" for "GPS Coords" settings it doesn't matter whether I choose "DMS" or "NMEA" format, the result is same)

![IMG_3813](https://user-images.githubusercontent.com/1837801/82703206-baf4d100-9c73-11ea-9c84-b2c872d921b7.JPG)

![IMG_3812](https://user-images.githubusercontent.com/1837801/82703226-c7792980-9c73-11ea-96a8-92ee6ba21b63.JPG)

![IMG_3811](https://user-images.githubusercontent.com/1837801/82703245-cea03780-9c73-11ea-9cc8-007ce727c6a0.JPG)

**Comment by kilrah** [comment]
Delete and rediscover the sensor

**Comment by peteoz** [comment]
that worked. thanks !
