### ISSUE TITLE
Companion V2.3.8 - Edit the assignment of values directly in the conversion window

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7624]
In Companion it would be absolutely useful to be able to edit the assignment of values directly in the conversion window.
Converting from X10S Express to X12S the values of LS and RS are misinterpreted, being able to edit them directly in the window that opens would be much more convenient, rather than accessing all the models and doing it one at a time.
Alternatively, it would be useful if the conversion was correct, since LS and RS exist in the X12S, and are not L1 and L2.

![companion](https://user-images.githubusercontent.com/3864712/82725611-5d499e80-9cde-11ea-9ddd-e4d2514c6e00.png)

**Comment by kilrah** [comment]
Would need a deep reengineering so unlikely, but the right thing is fixing the conversion yes.
