### ISSUE TITLE
Error Crossfire Outmap

### ISSUE THREAD

**Issue by toper74** [opentx/opentx#7625]
Hi,
i just update my Qx7 to Otx 2.3.7 and when i go to Tools > Crossfire config > Nano RX, i can scroll to the first 7 options (General, Mode, Telemetry, Rf profile, Failsafe mode, RC by Mavlink and Factory reset), but when i try to go to "Outmaps", i have this error message: "Error syntax script bad argument #3 to 'draw'......'
Can't see the full message.
I have this issue on all of my setups (drone)

**Comment by 3djc** [comment]
No issue here : 
![image](https://user-images.githubusercontent.com/5167938/82734106-d36af700-9d18-11ea-8f91-71fc4a3cdadc.png)

You many need to try an older crsf version, some run out of memory. This was shot on 3.28

**Comment by toper74** [comment]
An older CRSF version, and so an older versopn of OTX ?

**Comment by 3djc** [comment]
This was shot with 2.3.7 as you mentionned that version, with CRSF 3.28, works fine here

**Comment by toper74** [comment]
Thanks for testing. So i have a memory issue on my Qx7 ?

**Comment by 3djc** [comment]
No probably not.
You need to make sure that:
- crsf speed is set to 115k in radio/hardware
- you have the right SD content, especialy that you do not have some old scripts.

**Comment by toper74** [comment]
Sorry but can't find crsf speed option...
Is it on the crossfire config menu or Taranis menu ?

**Comment by 3djc** [comment]
Taranis, Radio, then hardware (6/7), then line called max bauds

**Comment by toper74** [comment]
Found. But same issue...
Do i have tu use the "Crossfire config" menu (page 1/7), or the "crossfire.lua" from SD-HC card menu (2/7) ?
Same error on both...arggh

**Comment by 3djc** [comment]
Please make sure you only have the content of our pack on your sd (at least for testing)

**Comment by toper74** [comment]
After upgrading, i format SD Card and put the "sdcard-128x64-2.3V0026.zip " from here https://downloads.open-tx.org/2.3/release/sdcard/opentx-x7/

**Comment by 3djc** [comment]
Yes I’m doing exactly that

**Comment by toper74** [comment]
And that's what I did... So?...

**Comment by toper74** [comment]
Oh my god, i'm so dumb..... was trying without antenna on Qx7....
I'm so sorry !...
Thanks for helping !!

**Comment by 3djc** [comment]
You are going to fry your crossfire doing that ..

**Comment by kubinets-ru** [comment]
I have the same problem, I have checked and updated everything, all antennas are connected but nothing helps. Could you help anybody help me?
![image](https://user-images.githubusercontent.com/104590416/165819607-02dc9008-38b9-4340-9ac0-6352ef228b38.png)
