### ISSUE TITLE
Taranis x9d + 2019 wont turn on after flashing under some options

### ISSUE THREAD

**Issue by suhast222** [opentx/opentx#7629]
Hello I have a problem with my taranis, whenever I try to upgrade opentx firmware (I have tried 2.37 and 2.38) the radio wont boot under some complation options.
For example It happens if I don’t check ppmus and nogvars. If I uncheck that options the radio works fine.

**Comment by 3djc** [comment]
What is the full name of the non working firmware?

**Comment by suhast222** [comment]
A lot of them won´t work for them. For example:
opentx-x9d+2019-lua-noheli-sqt5font-en-2.3.7.bin does not boot

This one is one of the few that works fine:
opentx-x9d+2019-faichoice-flexr9m-lua-nogvars-noheli-nooverridech-ppmus-sqt5font-en-2.3.7.bin

Maybe if I could have a previous version to try? the radio is new.

**Comment by 3djc** [comment]
Have you put a firmware on the sd card , start in bootloader and flash from there ?

**Comment by suhast222** [comment]
Bingo! That did the trick.
What is the problem then? The companion or my PC? I have tried in my desktop and my laptop, both windows 10 with the same results.

**Comment by 3djc** [comment]
Most likely your usb cable
