### ISSUE TITLE
Volt1.wav file is missed in the SOUND SD card directory for  the Italian language

### ISSUE THREAD

**Issue by fdapport** [opentx/opentx#7636]
Hardware: Taranis X9d+
Firmware: 2.3.7
SD card file:  sdcard-212x64-2.3V0026

The file volt1.wav is missed  in the Italian SOUND/SYSTEM dirs. No unit of measure is play when the radio play the voltage value.

How to fix:
Make a copy of volt0.wav to volt1.wav but I hope it will be include also in the others languages in the new SD versions.. The languages RU en EN are OK.

**Comment by 3djc** [comment]
Is the plural of volt also volt in Italian ?

**Comment by fdapport** [comment]
Yes, no plural of volt in Italian

**Comment by fdapport** [comment]
same of Watt, fps, mph, mps, mWatt, Percent, rpm, amp... No plural in Italian
