### ISSUE TITLE
Issue with the "Trim idle only" behavior

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#7638]
Hi folks,

For some reasons, I need to extract the "trim idle only" in order to use it somewhere else.
I did this config:

**General**
- Throttle → Source: **CH3**, Trim idle only: Yes, Warning: Yes, Reversed: No

**Inputs**
- I3:Gaz Thr Weight(+100%)

**Mixers**
- CH3:
     I3:Gaz Weight(+100%)
+= I3:Gaz Weight(-100%) NoTrim

The expected result would be to see a constant trim value.
However, if the throttle gimbal is moving from -100% to +100%, the trim is decreasing down to 0%!
I don't understand why, since the CH3 is not changing and the CH3 is designated as the throttle source?!?

I don't know if there is or not an hidden bug, but nevertheless I don't understand this behavior.
If a dev could kindly explain me what I'm doing wrong, it would be great. 😃 👍 

Here is the full setup:
[TrimIssue.pdf](https://github.com/opentx/opentx/files/4682833/TrimIssue.pdf)

**Comment by kilrah** [comment]
Trims work on the sticks, not the channel. Works exactly as expected.

**Comment by LapinFou** [comment]
Thanks. What the "throttle source" is for, then? :confused:

**Comment by kilrah** [comment]
Timers, throttle graph

**Comment by LapinFou** [comment]
Ah! 😱
I completely misunderstood the usage of this setting. I always thought it was for "Trim idle only" behavior. Now, all make perfectly sense. 😄 
Thanks @kilrah for yours explanations.
