### ISSUE TITLE
Provide description field for Logical Switches and Special Functions

### ISSUE THREAD

**Issue by bigtwin** [opentx/opentx#7645]
It would be helpfull to have a description or let say comment field for a logical switch or a special function. Only in Companion, an optional field which allows me to describe whatfor I have made this line and what was the intenion/idea behind.

Everytime I want to change a model config after I havent touched it for a while, I have difficulties to decrypt my thoughts on LS and SF. Would be great if I can label them somehow.

**Comment by 3djc** [comment]
Duplicate  #7633 ?

**Comment by bigtwin** [comment]
No! Not at all a dublicate!
This is about a comment field for Logial Switches and Special Functions, while the other issue is about the Simulator GUI and some labels to the switches and output bars.

I kindly ask to reopen this issue or add this topic to the still open issue

**Comment by kilrah** [comment]
Neither are possible without a complete redesign of the storage system and we've already got that use case in mind for whenever that happens one day, it's been asked many times over the years.

**Comment by bigtwin** [comment]
Thx for the statement and considering it someday!
But just in order to prevent any misunderstanding again - I am talking only about Companion and NOT the OpenTX itself.

**Comment by kilrah** [comment]
Yes but currently any data visible in one must be in both, so any comments for companion would have to be stored in the radio on which it would be a waste of the small amount of memory available.

**Comment by ridietz** [comment]
I would find this very helpful also.  I have been putting a blank line between Logic Switches and Special Functions so I can make comments on hard copies for future reference.

**Comment by ridietz** [comment]
For the majority of users, the small amount of memory in the radio would not be a problem if comments could be used in logical switches and special functions.  Other users could avoid these comments when memory capacity was a problem.  Thanks for your consideration 😷

**Comment by bigtwin** [comment]
I also want to point out again, that such a comment or description feature would not have to be assigned to the actuall program or configuration code. Even an additional tabulator side in _Companion_ for the model would  be a big improvement. If I would be able to store some additional comments along to each model - just and only in companion, not in OTX and just as free text and nothing special, it would be a big and great help.
I am thinking of just another tab, may after _Special Functions_ and _Telemetry_ - would do the job.

Thx again for considering to reopen the issue.

**Comment by lshems** [comment]
Anybody interested in this feature, please contact me on RC groups, pm l Shems.

I'll try to figure out a lua workaround based on some spec gathering.

**Comment by ridietz** [comment]
Thanks, I am interested.  I do not know how to contact you at RCGroups.  I am ridietz on RCGroups.

Dick Dietz, 317-560-0219
