### ISSUE TITLE
9XR PRO switch names incorrectly mapped

### ISSUE THREAD

**Issue by IanBurwell** [opentx/opentx#7647]
Hello,

I have just flashed my 9Xr Pro with the latest OpenTX build for the first time, and while control of my aircraft is working fine, the switches seem to be incorrectly mapped. For example, if I want to use the 3POS switch as an input I have to select the Aleron Trim switch as the source, or instead of using GEA for my gear switch it is mapped to AIL.

 - OpenTX version 2.3.7
 - Hardware: Turnigy 9XR Pro

**Comment by dgatf** [comment]
This is fixed in 2.3.8 #7639
