### ISSUE TITLE
Trainer page should adapt to 'Channels' vs 'Sticks' Trainer modes

### ISSUE THREAD

**Issue by lthole** [opentx/opentx#7650]
With reference to the new feature introduced in OpenTX 2.3.3 'Trainer function can now replace the channels values instead of the sticks positions':

The Trainer page is now misleading if the 'Channels' mode has been selected in the Trainer SF.

The left hand column always shows the master's side with stick symbols, which is fine when using the 'Sticks' mode. However, when 'Channels' mode is selected, the master's side should change to CH1 - CH4.

**Comment by 3djc** [comment]
This could become very complex as you can set a SF that does stick, another channel ... and watching with neither actived

**Comment by lthole** [comment]
Or maybe make the screen more generic by not having a stick symbol?

**Comment by kilrah** [comment]
Trainer Channels bypasses the ENTIRE master radio, so the page is irrelevant as well as everything else.
It just takes the slave's signal and puts it out straight to RF.
