### ISSUE TITLE
Horus X10 with option INTERNALACCESS Simulator works with wrong Telemetry SubIDs

### ISSUE THREAD

**Issue by ParkerEde** [opentx/opentx#7667]
OTX 2.3.7:
The old X10 with old iXJT works with 3 digit SubIDs for telemtriesensors. OTX is okay so far.
The old X10 with ISRM Upgrademodule (with INTERNALLACCESS) works with 1 or 2 digits SubIDs. OTX is not okay, because it still works with 3 digits of ID's

In relation of Telemtriesimulation the X10 with INTERNALACCESS must work like the X10 EXPRESS.

Kind regards
Ralf

**Comment by ParkerEde** [comment]
cool, it's working for ISRM D16 since 2.3.8N239
For ISRM ACCESS the Telemetriesensors are still 3 Digits.
Thank you
Ralf

**Comment by kilrah** [comment]
What does that mean? in simulator only?

**Comment by ParkerEde** [comment]
yes. In the physically radio is all fine. The issue is only in Companion radio simulator.

**Comment by bsongis** [comment]
Please check the latest nightlies, this issue should be fixed (I tested just now). Feel free to reopen if I am wrong.

**Comment by ParkerEde** [comment]
i've checked nightly 2.3.8N241. If a model is selected with ISRM D16, Telemetrie Simulator now is fine. If I choose a model with ISRM ACCEESS, only RSSI and RxBT works in Simulator. All other Sensors are still with 3 digits IDs and did not work.
One thing I've detected now in Simulator too. If you starts the Simulator and choose the "MDL" first Programmpage, and have a look to the Used RF Moduls. You can see, there is shown "OFF" for Internal RF, even though it was received from Horus as ISRM D16 or ISRM ACCESS.
![RF-issue](https://user-images.githubusercontent.com/15068446/84253992-e2bbb400-ab10-11ea-98f8-d8ac8c3f5ce6.jpg)

**Comment by bsongis** [comment]
![image](https://user-images.githubusercontent.com/5603504/84255848-77bfac80-ab13-11ea-80c4-a3b204fdd804.png)

![image](https://user-images.githubusercontent.com/5603504/84255890-827a4180-ab13-11ea-9e99-5c1617beb13e.png)

![image](https://user-images.githubusercontent.com/5603504/84255904-88702280-ab13-11ea-8383-b45c0c5f96a2.png)

**Comment by bsongis** [comment]
![image](https://user-images.githubusercontent.com/5603504/84256072-c3725600-ab13-11ea-983c-d8ed76cbcd1e.png)

![image](https://user-images.githubusercontent.com/5603504/84256090-c8cfa080-ab13-11ea-82dc-3f32486b4552.png)

**Comment by ParkerEde** [comment]
Did you use in Profile a Horus X10 (old) with "internalaccess"?

**Comment by 3djc** [comment]
Simulators DO NOT take into account options. So you have a plain x10 simu, which cannot handle ISRM

**Comment by bsongis** [comment]
Yes I did:
![image](https://user-images.githubusercontent.com/5603504/84256659-8064b280-ab14-11ea-8830-420b51f4e838.png)

**Comment by bsongis** [comment]
Ah yes we should include some other simulators, options are taken into account, but not all simulators with all options can be added to the installer bundle!

**Comment by bsongis** [comment]
Will be solved once we have something to build on-demand simulators (like your firmware), but that's another story!

**Comment by ParkerEde** [comment]
I found out, if I start simulator from Main WIndow with a default Model with ISRM D16 and switch inside the simulator to model with ISRM ACCESS then the Telemetrie will not work as it should. If I start the simulator from the Model editing window with a model uses ISRM ACCESS then it works like to see in your screenshots. It's okay for me but not perfect.
Many Thanks
Ralf
