### ISSUE TITLE
Open the .csv telemetry logfiles in the Log Viewer by double click

### ISSUE THREAD

**Issue by git2323** [opentx/opentx#7669]
It would be nice to be able to associate the .csv telemetry log files with the companion executable.
In this way we could open the telemetry log files (.csv File) by double clicking on them in the Windows Explorer.
Currently we have to start the companion, then open the log viewer, then Open Logfile, switch to the right path, select the file and click on 'Open'

Thanks

**Comment by 3djc** [comment]
Thats a configuation you can do for yourself in windows

**Comment by 3djc** [comment]
Ok, so probably what he would like is once you manually associate .csv to Companion, that companion can open log viewer with that file instead of main windows

**Comment by git2323** [comment]
Would still be nice to have it ;-)
