### ISSUE TITLE
Companion 2.3.8N229 - Error when importing a log

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7675]
I discovered now that I cannot open the logs generated with the current firmware compiled by the "2.3" branch, generated by Horus X10S Express.
The error is the one shown in the image.

[Epsilon_XL3-2020-06-05.zip](https://github.com/opentx/opentx/files/4735736/Epsilon_XL3-2020-06-05.zip)

![immagine](https://user-images.githubusercontent.com/3864712/83871004-87b04880-a72f-11ea-88a5-57eac4a5dcf2.png)

**General information**
 - OpenTX version V2.3.8 (self compiled yestarday from 2.3 branch)
 - Hardware Horus X10S Express
 - OpenTX Companion V2.3.8N229

**Comment by 3djc** [comment]
Did you add/remove sensors ?

**Comment by robustini** [comment]
No, but among the sensors there were none active, that yes.

**Comment by robustini** [comment]
The same log works perfectly in the sim.

**Comment by 3djc** [comment]
You added data to the log between 10:12:13 and 10:35:51, and you can't do that (a data of value 10.8)

**Comment by robustini** [comment]
> 
> 
> You added data to the log between 10:12:13 and 10:35:51, and you can't do that

That is, did I add sensors while the log was being written?
This is possible, and if this is the problem it really isn't, just know it! :-)

**Comment by 3djc** [comment]
Yes, it is a know limitation, you cannot change sensors been logged in a single log (day)
