### ISSUE TITLE
Companion 2.3.7: Second level of X-Lite trimms with SHIFT button doesn't work 

### ISSUE THREAD

**Issue by Gerd-St** [opentx/opentx#7685]
Within the simulator I can only operate the left stick trims, not the right ones. Even pressing the Shift button on the radio image has no effect.

I would expect either a second set of trim rulers for the right stick, same as there is for the left stick, or a workaround by using the Shift button as works for the real X-Lite.

![Bildschirmfoto von 2020-06-06 09-14-34](https://user-images.githubusercontent.com/56171110/83938606-314a1500-a7d6-11ea-91d2-d1dd6b0f9e23.png)

**General information**
 - OpenTX version 2.3.7
 - Hardware X-Lite radio profile
 - OpenTX Companion 2.3.7 on Ubuntu 18.04)

**Comment by kilrah** [comment]
Duplicate https://github.com/opentx/opentx/issues/6582
