### ISSUE TITLE
OTX 2.3.8 - X12S with ISRM: shows wrong selection (internal + external antenna)

### ISSUE THREAD

**Issue by robustini** [opentx/opentx#7689]
With the "internalaccess" enabled it should not show "internal + external antenna" but only "external", as it should be in case of IXJT module.

**General information**
 - OpenTX version 2.3.8 N231
 - Hardware Horus X12S with ISRM

![immagine](https://user-images.githubusercontent.com/3864712/83949931-2370b000-a827-11ea-979c-257ea4c747ef.png)

**Comment by MIKE-DAILEY** [comment]
The antenna line item does not exist in OpenTX-x12s-2.3.8N231 ( f 6 c e 4 0 e 7 ) 

It is a X12S internalaccess English.

**Comment by kilrah** [comment]
The setting does not apply to ACCESS

**Comment by MIKE-DAILEY** [comment]
Right and it is apparently OK with X12S internalaccess English

**Comment by 3djc** [comment]
This is because he is building himself and forget to have  INTERNAL_MODULE_PXX1 set to off

**Comment by robustini** [comment]
> 
> 
> This is because he is building himself and forget to have INTERNAL_MODULE_PXX1 set to off

That's right, I added the option now, thanks!

**Comment by robustini** [comment]
Sure, but I can show you a TMX5 that Horus X10S Express and Jumper T16 both flash perfectly, but X12S does not.
