### ISSUE TITLE
Horus X10S theme build?

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#7691]
Good evening everyone,
I have OpenTX 2.3.x flashed to my "Horus X10S" and love it but I am not really into the only 2 "themes" that are available (Darkblue & default). So I would like to be able to change the picture "back drop" as well as the color schemes. I was hoping that someone or somebody has any advice, how too change picture and or colors? 

I already have my model pictures done, splash screen changed, sound pack/voices done.
Any help would be Awesome!!

Thank you for your time

**Comment by 3djc** [comment]
Hello. This place is only a tracker for OpenTX issues, not a community support place. Please go to places like rcgroups or openrcforum for this type of question.
