### ISSUE TITLE
Can't change widget colors

### ISSUE THREAD

**Issue by michifpv** [opentx/opentx#7692]
When i change the color of my telemetry widget to red the color stays the same (blue). Only for one value i can change it to red. All other colors are set to red but stays blue. Any fix for this?

Radio: Radiomaster TX16s with stock Firmware.
![20200606_200300](https://user-images.githubusercontent.com/46536891/83952428-22e11500-a839-11ea-829d-1c6d9c192fb2.jpg)

**Comment by 3djc** [comment]
Hello. This place is only a tracker for OpenTX issues, not a community support place. Please go to places like rcgroups or openrcforum for this type of question.

**Comment by Marsellus19** [comment]
I have the same issue. The colour of the text can be changed for any displayed value, but not for telemetry data. I looks like either an openTX issue or the default Value widgets issue.

**Comment by kilrah** [comment]
The color you choose will be used whenever you're actually receiving telemetry. When there's no data it's always blue.
