### ISSUE TITLE
OTA Issue

### ISSUE THREAD

**Issue by bsongis** [opentx/opentx#7694]
I just checked N231 on my X12S OTA with an Archer GR8 and N231 still has the issue with the “waiting” screen.  You select the GR8 file to flash OTA, select flash OTA and the “waiting” screen pops up.  You power up the GR8.  When the X12S detects the Gr8 the “waiting” screen should go away and display the GR8 to be flashed.  The “waiting” screen does not go away when the GR8 is detected, it stays displayed unit you press RET. I would think you would want this to work like it does on the non-color screen systems.

**Comment by bsongis** [comment]
I have a X10 Express and a ARCHER GR8. I can try it myself

**Comment by 3djc** [comment]
Possibly related : #7684

**Comment by MIKE-DAILEY** [comment]
Thanks for posting my note @bsongis.  If you need help testing I would be happy to help. Other than needing to use RET to clear the "waiting" screen so the GR8 can be selected everything else works OK.
