### ISSUE TITLE
qx7 accst bind problem 

### ISSUE THREAD

**Issue by w2fly** [opentx/opentx#7701]
Update firmware on my Taranis Q X7 ACCST from 2.2.1 to 2.3 7 and transmitter stopped connecting to my quads (XM+, XSR receivers and internal D8 receiver on Mobula-6 whoop).
Rollback to version 2.2.4 but problem still exists.
How i can solve it
Quad with r9mm receiver and r9m on transmitter connected good.

**Comment by 3djc** [comment]
OpenTX does not affect binding. Please use community sites like rcgrousp or openrcforum for community support
