### ISSUE TITLE
Horus X12S internal GPS signal indicator does not work

### ISSUE THREAD

**Issue by Zadrob** [opentx/opentx#7710]
Hello, 
I have noticed (OPenTX 2.3.7), that internal GPS signal strength
 indicator (beside signal strength indicator, above battery indicator) does not work. 
Even when I have good internal GPS lock (visible via statistics)

**Comment by 3djc** [comment]
You mean the speaker sound volume indicator? There is no indicator for gps signal

**Comment by Zadrob** [comment]
Hello, I feel really stupid... Sorry :) 
Speaker symbol looks like satellite dish to me :)
Karel
