### ISSUE TITLE
9XR-Pro no MAX as mixer source

### ISSUE THREAD

**Issue by ewingate** [opentx/opentx#7711]
I've loaded OpenTX 2.3.7 (opentx-9xrpro-autosource-autoswitch-en-2.3.7) onto my radio and in the mixer I can't select MAX as a source (on the radio).  With the companion it's an option, and I can upload it, but it doesn't work.

**Comment by kilrah** [comment]
Use nightly builds, there have been fixes for that radio recently.

**Comment by JoshuaShaw** [comment]
Where am i find nightly builds?

**Comment by kilrah** [comment]
On the website but no need anymore, 2.3.9 has been released. Just update to that.

**Comment by JoshuaShaw** [comment]
But 2.3.9 has some other errors.  #7772

**Comment by kilrah** [comment]
Maybe but that's unrelated.

**Comment by JoshuaShaw** [comment]
That's unrelated, but I can not use 2.3.9 because #7772
