### ISSUE TITLE
9XR PRO global variable mapping problem

### ISSUE THREAD

**Issue by Berriss71** [opentx/opentx#7714]
Hello, 
In the new version 2.3.7 there was a problem in mapping global variables.

**Example:**
if I increase the GP2 values ​​in Special features thus GP2 increases in the simulator
but if I refer to GP2 in logic switches then here is GP2 = GP1

**Special features**  = **Logic switches:**
GP1                     =                  ?
GP2                     =                  GP1
GP3                     =                  GP2
GP4                     =                  GP3
atc..                                      ......

OpenTX version 2.3.7
Hardware: Turnigy 9XR Pro
opentx-9xrpro-autosource-autoswitch-battgraph-gvars-potscroll-ppmus-cz-2.

**Comment by kilrah** [comment]
There was a shift that has been fixed, should be OK in nightlies.
