### ISSUE TITLE
Name of model not always showing when selecting model on Jumper T16 

### ISSUE THREAD

**Issue by Gaylian** [opentx/opentx#7717]

**Comment by kilrah** [comment]
Screenshot? Example? OTX file?

**Comment by Gaylian** [comment]
![20200611_191742 (Medium)](https://user-images.githubusercontent.com/58540542/84371244-aecdb500-ac1c-11ea-87ba-035d880358da.jpg)
![20200611_191439 (Medium)](https://user-images.githubusercontent.com/58540542/84371251-b0977880-ac1c-11ea-9f3f-44aa3fbcad84.jpg)
![20200611_191636 (Medium)](https://user-images.githubusercontent.com/58540542/84371261-b2f9d280-ac1c-11ea-9db1-e6981a2b4957.jpg)
![20200611_191652 (Medium)](https://user-images.githubusercontent.com/58540542/84371264-b42aff80-ac1c-11ea-85a2-a0fefa964cf6.jpg)



Andre

Screens shots of missing ( most Times) names.

 

Adrian

**Comment by 3djc** [comment]
No screenshot was supplied,  but are you using supplied sd card ?

**Comment by kilrah** [comment]
You did not say what firmware you are running. Try to reflash OpenTX 2.3.7.
Also please note this is not an OpenTX issue and this place is not for user support.

**Comment by Gaylian** [comment]
I did send the screen shots but they didn’t appear on web site. I have add them via the web page.

I’m using the files for the SD card that are on the openTX web site. Version 2.3V0029.

I’m using OpenTX 2.3.8 (nightlies). This problem was also on version 2.3.7

**Comment by Gaylian** [comment]
Why is it closed. This looks a lot like a opentx problem. Flashing 2.3.7 does not fix the problem.

**Comment by 3djc** [comment]
It is a script that does that, can't remember if it is iNav or Yaapu, but it is not an OpenTX issue
