### ISSUE TITLE
Horus X10 Curve messed up

### ISSUE THREAD

**Issue by widl84** [opentx/opentx#7718]
Hello, my name is Michael and I have a problem with my new Horus X10S Express.

Firmware 2.3.7 is installed.
Companion is 2.3.7
On Windows 10 Home

I want to balance my elevator's servos, but my curve`s are messed up. if one is changed, the other also changes.
Even if the Horus is switched on again, something changes on the curves.

I have read the entry # 6853 but can not confirm that it does not come with slow rotation.
I also made a video of it.

**Comment by kilrah** [comment]
Post the video then?

**Comment by bsongis** [comment]
Would you try the nightlies, just to check that the issue is gone? Then you return to official 2.3.7, datamodel is compatible anyhow. We are near the 2.3.8 release.

**Comment by widl84** [comment]
[Untitled.zip](https://github.com/opentx/opentx/files/4769603/Untitled.zip)

**Comment by widl84** [comment]
Hello I can not generate the error in 2.3.8N again.
can I go flying with the "N" version?
the last version was 2.2.4 but Access doesn't work there and my receivers are already flashed.

**Comment by 3djc** [comment]
Wait a couple of hours ...
