### ISSUE TITLE
[Companion 2.3 Simu] Trim value spontaneously resets when switching between flight modes

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#7722]
**Problem**
Simple setup with two flight modes:
- FM0 has TrmT as 'disabled'
- FM1 has TrmT as 'own trim', value=+100. 

When switching between the two flight modes, the 'own trim' value spontaneously resets to zero, sometimes immediately, other times after a couple of cycles.

So far I can only reproduce this in Companion.

**To Reproduce**
1. Start Companion 2.3.7, with X9D profile
2. Open [this .OTX file](https://www.dropbox.com/s/vy02biivyakev9o/TrimBug_For_OTX_237_Simu.otx?dl=0)
3. Open the simulator
4. Keep an eye on the TrmT graphic (or CH1, which uses TrmT as source)
5. Switch rapidly between between flight modes using SH.

**Expected**: TrmT should alternate between +100 and zero
**Actual**: after a couple of cycles, TrmT shows zero for both FMs.

**General information**
 - Companion 2.3.7 (but also occurs in 2.2.x)
 - Frsky X9D profile
 - Windows 10 X64

**Comment by bsongis** [comment]
@dgatf @elecpower would you have time to fix this one?

**Comment by dgatf** [comment]
Sure
