### ISSUE TITLE
Add raw telemetry forwarding from internal module to external pins

### ISSUE THREAD

**Issue by annoyinganime** [opentx/opentx#7723]
Add a function that will grab all telemetry coming from internal multiprotocol module, an forward it to SPort pin in a module bay. This will be very useful for example when using external antenna tracker, or, in my case, to use XN297Dump feature for protocol analysis.

**Comment by ragelancer** [comment]
Yes, this is a very useful feature. I used s-port mirror on x9d, but on the t16, there is no way to output the telemetery. Please add this feature.

**Comment by brainbubblersbest** [comment]
#8073
