### ISSUE TITLE
SD card contents not refreshed in special functions: play track

### ISSUE THREAD

**Issue by DanielOBenson** [opentx/opentx#7725]
Using opentx-tx16s-Radiomaster (7ee5b1df0).
To reproduce problem.
Create a NEW sound using sound companion.  Name this reverse.wav as an example.
Put this on the SD card under the sounds:en directory  (used a new, formatted sd card).
Insert the card into the radiomaster sd card slot.
Confirm that the new file (reverse.wav) in on the sd card using sys. browse to SD-HC card=>en
confirm that the sound file can be played.  So far all is fine.
NOW to reproduce the problem!
Under model setup tab to special functions.
create a new special function and chose Play track.
now browse the sound files to play.  AND THE FILE IS NOT THERE!  The list of the files to play does not include the newly created reverse.wav file.
Thank you for your help.
Dan Benson

**Comment by 3djc** [comment]
Sound files are limited to 6 chars
