### ISSUE TITLE
Opentx

### ISSUE THREAD

**Issue by Gamertim** [opentx/opentx#7727]
Moin Leute ich möchte euch einmal fragen was man tun kann wenn bei OpenTX Companion 2.3.6                           

 No firmware release candidates are currently being served for this version, please switch release channel.

Steht.         ich freue mich auf Antwort.

LG

**Comment by 3djc** [comment]
Hello, this tools is English only, and is not for user support. Please gp to places like rcgroups or openrc forums for end user support. (or maybe https://fpv-community.de/ in german)
