### ISSUE TITLE
TX16S新固件2.3.8有問題

### ISSUE THREAD

**Issue by E120103016** [opentx/opentx#7728]
你好:  
今天有TX16S新固件2.3.8有問題.下載版本:otx(05411772).變體219日期:2020.06.13:19:02
燒錄遙控器後出現與當前固件不兼容(bug).一直嘗試都沒有辦法.麻煩告知如何處理謝謝!

**Comment by 3djc** [comment]
Please:
-English only
- No duplicates
- Try to be as descriptive as possible of your actual issue
