### ISSUE TITLE
Horus X10S 2.3.8 firmware not compatible

### ISSUE THREAD

**Issue by robertw2a** [opentx/opentx#7731]
Trying to update Horus X10S with 2.3.8 from 2.3.7 OpenTX Companion says file not compatible with existing firmware. Downloaded with R9flex and lua options
![failed](https://user-images.githubusercontent.com/54487202/84573852-db3a1c00-ad57-11ea-8c30-382811d50781.png)
![options](https://user-images.githubusercontent.com/54487202/84573853-dbd2b280-ad57-11ea-9cb3-8c08ddf5b8f0.png)

**Comment by 3djc** [comment]
Yes this is due to a change that was introduced in this release, please uncheck “check hardware compatibility” for this flash

**Comment by robertw2a** [comment]
OK will try, just did not want to corrupt or damage the radio

**Comment by robertw2a** [comment]
Thanks, that worked afterwards it will  flash with "check hardware compatibility” checked
