### ISSUE TITLE
2.3.8 "new firmware not compatible with one currently installed" for Horus X10

### ISSUE THREAD

**Issue by mbalun** [opentx/opentx#7736]
I only have one Transmitter and one setup settings in companion. 
When I download the 2.3.8 and go to update the firmware to the transmitter, I get "new firmware not compatible with one currently installed"  

I Had a 2.3.7 installed - "2.3.7 (8b080683)", variant 219, fw autoname "opentx-x10-eu-lua-en-2.3.7"
failed update - "otx (17db3dff)", variant 219, fw autoname "opentx-x10-eu-lua-noheli-en-2.3.8-otx"

**Comment by kilrah** [comment]
Yes that's becasue of the new -otx suffix, disable hardware compatibility check.

**Comment by 3djc** [comment]
Please disable check hardware compatibility for this flash as per release notes
