### ISSUE TITLE
Companion : issue in SF set failsafe

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#7737]
Companion does offer "set failsafe internal" and "set failsafe external" when only one should be proposed

![image](https://user-images.githubusercontent.com/5167938/84599902-be940600-ae75-11ea-9f1c-c11158f463cf.png)

Exists in 2.3.9 and has probably be present for some time

**Comment by elecpower** [comment]
So does Companion simulator and X9D+ radio even if an internal and/or external module is not configured.

**Comment by kilrah** [comment]
Thing is we used to have separate failsafes for internal and external and it's not the case anymore.

**Comment by bsongis** [comment]
@elecpower it should be possible to configure the failsafe even if there is no module configured

**Comment by bsongis** [comment]
@dgatf @elecpower this one for you? let me know!

**Comment by elecpower** [comment]
@bsongis @dgatf  I'll take it
