### ISSUE TITLE
Model Wizard does not work in Horus X12S

### ISSUE THREAD

**Issue by Luznatural** [opentx/opentx#7738]
Description:
With Open TX version 2.3.9, when you try to create a new model in Horus X12S, the screen where the model wizard should allow you to select plane, glider, or drone, appears just empty. So, you cannot make the wizzard

**To Reproduce**
1. select MDL. when the list of models appear, 
2. press and hold the enter wheel
3. Select create a new model
4. the screen goes empty with no option to select

**General information**
 - OpenTX version 2.3.9 Windows 10
 - Hardware Frsky X12S
 - OpenTX Companion 2.3.9 Windows

**Comment by 3djc** [comment]
You have not installed the sdcard pack correctly I’m afraid

**Comment by Luznatural** [comment]
It was the first thing I checked. I did check twice. I have in the script folder of the SD the wizard folder, and in the wizard folder I have both folders: glider and plane

**Comment by Luznatural** [comment]
both folders appear to have the correct files on them

**Comment by Luznatural** [comment]
I checked on my second radio, a Frsky X9D+, and works correctly with the same version 2.3.9
