### ISSUE TITLE
Presentation error in Spanish

### ISSUE THREAD

**Issue by afdofdez** [opentx/opentx#7743]
Horus X10s Express  OpenTx 2.3.9

In the radio's special functions screen, for the RESET action it erroneously presents the parameter values.

It has the following parameters:

Timer 1
imer 2
mer3
or
metria

the rest of the parameters present them correctly.

**Comment by 3djc** [comment]
After timers, there is a "flight" reset in english, and Todo is displayed in spanish, should it be vuelo ?

**Comment by afdofdez** [comment]
Yes

**Comment by 3djc** [comment]
Please test next nighly, shouold be fixed
