### ISSUE TITLE
Hott Telemetry Value BCpT fault scaling

### ISSUE THREAD

**Issue by Ziege-One** [opentx/opentx#7744]
I use the Hott System with the Radiomaster TX16s and an GAM Sensor on the Receiver side. The 
The value used mAh (BCpT) shows 0.01mAh, but in real it is 10mAh.

Here in opentx/radio/src/telemetry/hott.cpp you see the right scaling "battery capacity in 10mAh steps"

`          // packet[11] uint8_t batt_cap_L;     //#11 battery capacity in 10mAh steps
          // packet[12] uint8_t batt_cap_H;     //#12
          value = packet[11] + (packet[12] << 8);
          sensor = getHottSensor(HOTT_ID_BCAPA);`

Update I found  in opentx/radio/src/telemetry/hott.cpp
  {HOTT_ID_BCAPA,        ZSTR_SMART_BAT_CAPACITY, UNIT_MAH,               2},  // Batt Capa

means the 2 at the End. 2 decimal points ?

If yes it have to be 0 and the value have to be "value = (packet[11] + (packet[12] << 8)) * 10;"

Thank you for great Job on OpenTX

**General information**
 - OpenTX version (2.3.9-otx)
 - Hardware (Radiomaster TX16s)
 - OpenTX Companion (2.3.9 on Windows)

**Comment by 3djc** [comment]
@Ziege-One I have pushed a fix that will be in next nightly (247), please test and let us know how it worked :)

**Comment by Ziege-One** [comment]
@3djc Thank you
you have forgotten one line at 614.

3 Sensors have the used mAh ESC, GAM and EAM.
I will test it

**Comment by Ziege-One** [comment]
@3djc 
Hi,
nightly (247) install and tested. It works very well. I will check the other Values and will report.
Thank you form "Speedy" Update 👍
