### ISSUE TITLE
add persistent option for ESC-consumption Sensors

### ISSUE THREAD

**Issue by strgaltdel** [opentx/opentx#7746]
please add the **persistent** option for "consumption" telemetry sensors like "EscC".

This option is implemented in the corresponding calculated value (consumption) & works fine.
Unfortunately most ESCs doesn't store their consumption value into flash mem, so a new session / restart without changing the battery leads to a start by zero, although a discharge has already taken place.

Using the calculated value (based on the drive-current sensor) is far away from optimal, because ESCs, in addition, take the consumption caused by the BEC into account which can be relevant (i.e. F5j)

thanks & regards
Udo

![persist](https://user-images.githubusercontent.com/20392683/84876858-05594a00-b088-11ea-8f37-652b51ecf4e0.png)

**Comment by kilrah** [comment]
Nothing we can do about that, if the sensor sends 0 it's 0.
