### ISSUE TITLE
Wrong Italian wav file for km/h and low battery.

### ISSUE THREAD

**Issue by fdapport** [opentx/opentx#7748]
Hardware: Taranix XD9+
Firmware: 2.3.9
SD Card Files: sdcard-212x64-2.3V0029.zip
Under: SOUNDS/IT/SYSTEM
Files: kph0.wav,  kph1.wav and lowbatt.wav are wrong pronunciation.

The correct one are stored in SD Card files: sdcard-212x64-2.3V0026.zip
Under: \SOUNDS\it\SYSTEM

We could have other files with wrong Italian pronunciation, I didn’t check all.
Franco

**Comment by 3djc** [comment]
The only difference between 26 and 29 as far as Italian is concerned are here : https://github.com/opentx/opentx/commit/f0a1c65d952a7d7df32ca075dfba8d0251163a1d#diff-11b76c79cb42fd865dcb3825dc1c3c72

The one you mentioned haven’t been changed apparently, so it might well be some changes in the online generation tool we use

**Comment by fdapport** [comment]
On the radio and as well on the PC the wav file say "take kilometri orari" instead of "kilometri orari".
You can try by yourself, you could find that are different.

Also the files have different proprieties:

![kph0_OK](https://user-images.githubusercontent.com/42831968/84933773-b090f000-b0d6-11ea-9540-8c39132daad1.jpg)
![kph0_wrong](https://user-images.githubusercontent.com/42831968/84933790-b5ee3a80-b0d6-11ea-9022-782905df27e7.jpg)

Thanks,
Franco
