### ISSUE TITLE
TX16S UART power issue

### ISSUE THREAD

**Issue by xkriton** [opentx/opentx#7751]
Radiomaster TX16S OpenTX 2.3.8 stable (noheli, lua, flexr9m)
Both bottom UART outputs lose power after selecting Telemetry Mirror option.

Behavior when selecting options:
OFF (no power) -> Telem Mirror (no) -> Telemetry In (no) -> SBUS Trainer (no) -> LUA (powered!)
when going back:
LUA (powered) -> SBUS (powered) ->Tele In (powered) -> Telem Mirror (lost power) -> OFF (no power)

**Comment by 3djc** [comment]
ok, great time to review which of those more should have power. Should they all be powered but OFF ?

**Comment by xkriton** [comment]
Well, hard to tell. Just finished testing with stock FW from Radiomaster and there it keeps power even with "OFF" selected.
In my case I am focusing on "taranis style" BT Telemetry Mirror, which requires power for hooked up BT module. Honestly I did not even investigated possibilities of Tele In/SBUS/LUA options yet :-)

**Comment by xkriton** [comment]
After quick test with custom compiled FW (AUX_SERIAL_POWER_ON) there is everything OK with power for UARTs and I have telemetry mirror working over attached BT module.

**Comment by skaman82** [comment]
@xkriton any chance you can send me this firmware where the uart is powered on telemetry mirror (using crossfire)?

ideally with this options selected:
<img width="830" alt="Bildschirmfoto 2020-06-27 um 13 06 00" src="https://user-images.githubusercontent.com/11768024/85920795-0a33b000-b877-11ea-8490-8eae094b932c.png">

**Comment by 3djc** [comment]
Nightly

**Comment by skaman82** [comment]
@3djc thanks - how does this work exactly? - I can only enable release candidates in companion (there are none)

**Comment by 3djc** [comment]
You need nightly companion : https://downloads.open-tx.org/2.3/nightlies/companion/windows/
Set to nightly after install

**Comment by skaman82** [comment]
thank you very much

**Comment by al21883** [comment]
Radiomaster TX16S OpenTX 2.3.9

On all UART options except OFF I have the left UART powered and the right UART without power. It's supposed to work that way?

Thanks!
