### ISSUE TITLE
New telemetry screen layout for 480x272

### ISSUE THREAD

**Issue by KissmanCZ** [opentx/opentx#7757]
Hello, I would like to propose a new layout for telemetry screen. My idea is 4+2 or 2+4 layout. It is difficult to add all wanted values to one screen especially when some telemetry sensors cant be used with small cell (GPS for example). 2 pages is not always way to go.

![ngng](https://user-images.githubusercontent.com/13331823/85200576-f3caa900-b2f8-11ea-90ef-9ff80ae306a0.png)

**Comment by robustini** [comment]
I agree, good idea.

**Comment by KissmanCZ** [comment]
I am just thinking... what about this way:

![85200576-f3caa900-b2f8-11ea-90ef-9ff80ae306a0](https://user-images.githubusercontent.com/13331823/85208188-ad903c80-b32e-11ea-882f-24c2306a38f7.png)
So two new layouts (4+2 & 4+3) and **add option** to rotate layout horizontaly or vertically? Just two checkboxes below... So user will be able to select from 4 different styles for 2 layouts. Can work also for other layouts (2+1).

**Comment by robustini** [comment]
It would be very useful, I hope it will be taken into consideration.

**Comment by mhfalken** [comment]
Yes, more layouts would be nice, but also more layouts without the trim/sliders as they take up a lot of real estate and are never used on drones. I know they can be disabled, but that doesn't give more space to the widget, so extra widgets with larger boxes, so more of the screen can be used.

**Comment by PD5DJ** [comment]
I have not seen this request but similar to mine: https://github.com/opentx/opentx/issues/7921

Pleas devs add more type of layouts :-)

**Comment by PD5DJ** [comment]
I have created my own layouts:

https://github.com/Hobby4life/opentx/tree/2.3/radio/src/gui/480x272/layouts

https://www.youtube.com/watch?v=NJXQOz2F65A
