### ISSUE TITLE
Speak a desired number

### ISSUE THREAD

**Issue by xoedusk** [opentx/opentx#7758]
I’d like the ability in Special Functions to “Play Number” and then I could inertia scroll to any number I wanted, or whatever the limit is. 

This can be done in Lua scripting I know but it’d be more convenient to have it built in. 

An example use case is that I have a switch on my TX for different battery mAh values. I want it to tell me which battery I have selected by telling me the mAh.

**Comment by bigtwin** [comment]
Why dont create all your desired numbers on your own and save them as *.wav files?
I have created myself some wav-files containg e.g. "3,2 Volts" to represent certain LiPo cell voltages.
 In this manner you could even "speak" comma values and the unit.
