### ISSUE TITLE
Haptic mode not avalable on Taranis X9D+ 2019 

### ISSUE THREAD

**Issue by papapout** [opentx/opentx#7759]
Hi,
on radio parameter configuration screen haptic mode and power are greyed for Frsky Taranis X9D+ 2019 but X9D+2019 has haptic hardware available. Can you activate haptic mode please ?

**Comment by 3djc** [comment]
On the radio itself or Companion ? Seems ok on both here

**Comment by kilrah** [comment]
Seems you're talking of companion, this was fixed in 2.3.8.

https://github.com/opentx/opentx/issues/7570
