### ISSUE TITLE
Binding OpenTX (Jumper T16) als Lehrer/Schüler unter dem HOTT Protokoll (Graupner)

### ISSUE THREAD

**Issue by kleinerf** [opentx/opentx#7761]
Hallo zusammen,
wie kann ich mit einer Jumper T16 unter OpenTX diesen Sender als Schüler/Lehrer Sender unter dem HOTT Protokoll binden? Habe diesebezüglich keine Lösung gefunden. Wer kann mir weiterhelfen. 
Vielen Dank 
Frank

**Comment by 3djc** [comment]
English only please. Also,  this tools is for tracking OpenTX bugs, not for usage questions. Please got o community places like rcgroups or openrcforums for user assistance
