### ISSUE TITLE
Download older firmware using Companion

### ISSUE THREAD

**Issue by habbiebabbie** [opentx/opentx#7763]
Hi !

I recently thought I had a problem with 2.3.9 and wanted to download the 2.3.7 firmware version using Companion. I did not find an option to specify which firmware version I'd like to download. It always points to the most recent version.
Am I missing something ?

Regards,
René

**Comment by 3djc** [comment]
It is not possible to download an old version by design. Firmware are compiled on demand, and you always get the lastest one in the branch (2.3.x, 2.2.x)

**Comment by Hobbypilots** [comment]
> It is not possible to download an old version by design. Firmware are compiled on demand, and you always get the lastest one in the branch (2.3.x, 2.2.x)
agree that opentx down does not allow users to download the previous version, but is there any way of doing it.

**Comment by bigtwin** [comment]
You can consult your favorit support forum and simply ask if somebody still has your desired version with your wanted features.

**Comment by gratefulfrog** [comment]
Is this still the case?  The latest versions of opentTX do not work properly with the multimodule, the last working version is 1.3.13. I would really like to be able to configure it myself and not depend on other's versions..

**Comment by 3djc** [comment]
So untrue,what issue are there with multi on latest version ? Most of the supported radio are now actually multi based ...

**Comment by gratefulfrog** [comment]
see this https://www.rcgroups.com/forums/showpost.php?p=48240461&postcount=23142
the SF switch somehow cuts off communication,
but actually is is 2.3.11 that works, not 2.3.13

see this issue: https://github.com/opentx/opentx/issues/8786
