### ISSUE TITLE
Jumper T16, can't assign certain PNG images to models

### ISSUE THREAD

**Issue by fiechr** [opentx/opentx#7764]
I'm running OpenTX 2.3.9 on my Jumper T16 and I had a similar issue before, but it somehow did go away by itself, this time it doesn't...

I've downloaded all these pictures for my models from https://www.air-rc.com/

The problem basically is, that the images don't show up in the drop down menu where I can select the image by name. This doesn't work on the transmitter or the companion software. I've restarted the transmitter and copied the files again, but that didn't change anything.

I can see the images though, on the file system view of the global settings menu. But if I open the context menu, I don't get the "Assign bitmap" function, while on other, working images, this menu entry shows up.

All the PNG images have the same resolution and have also similar file sizes.

I've attached four images, two that work fine and two that don't:

These two do work fine and are assigned to a model each:
![dragon](https://user-images.githubusercontent.com/12040376/85405344-933da500-b560-11ea-9deb-bae865a6897c.png)
![umbrella](https://user-images.githubusercontent.com/12040376/85405345-933da500-b560-11ea-8e0e-a2df5e4fd5f7.png)

These two are the ones I can't see and/or assign:
![thfreestyle](https://user-images.githubusercontent.com/12040376/85405339-920c7800-b560-11ea-9969-921708b25f39.png)
![easyglider4](https://user-images.githubusercontent.com/12040376/85405342-92a50e80-b560-11ea-8a7f-2f2f553711c1.png)

**Comment by 3djc** [comment]
Name too long ?

**Comment by 3djc** [comment]
Tested here ok when named t16.png

**Comment by fiechr** [comment]
Yeah, indeed, name was more than 8(?) characters.

To be honest, this is pretty confusing, since there is no warning or information (like in the readme.txt in the folder), that there is a filename length limit. Especially since I can copy files with long names over without errors and even look at them (in case of images) in the global file menu. I'm sure I had this issue before, but didn't realized it then.
