### ISSUE TITLE
Internal Bluetooth disconnecting after several seconds

### ISSUE THREAD

**Issue by skaman82** [opentx/opentx#7766]
**Describe the bug**
I am using the para BT module in my X-Lite and Full CRSF TX. I set BT to "telemetry" and I can connect to it normally using Android Telemetry Viewer App or connect to it with an HM-10. BT is paired and pin is also entered. At first I am getting data normally but after several seconds (sometimes 5 - sometimes 60) the connection is lost. 

The Android App must be reconnected manually until it loses connection again after max 1minute or so and the HM-10 just reconnects by itself but this is also happening frequently.

Because this is happening with the App and the HM-10, I think this hast something to do with the para module or OpenTX.

**To Reproduce**
Enable Telemetry under Hardware > Bluetooth
Connect with Telemetry Viewer or a HM-10
INAV telemetry downlink at 10Hz

**Expected behavior**
A stable BT connection until I disconnect it by myself

**General information**
 - OpenTX version 2.3.9
 - Hardware: Frsky X-Lite and Full Crossfire Module
 - Telemetry Viewer Android App: https://github.com/CrazyDude1994/android-taranis-smartport-telemetry
 - HM-10 bound to x-lite and set to 115200 baud

**Comment by skaman82** [comment]
closing this for now as I stumbled on the cause probably. have to check first

**Comment by skaman82** [comment]
Okay, this issue is only happening if the hardware telemetry is set to "Max baud 400000". If it is set to "max baud 115200" the BT connection is stable. But I would like to use my CRSF on full speed of course, so I am reopening this

**Comment by 3djc** [comment]
Isn't that exceeding BT bandwidth ?

**Comment by skaman82** [comment]
I thought opentx somehow handles the conversion between CRSF native baud rate and BT output baud rate as the BT is of course not capable of transmitting at native CRSF baud rate of 420k

**Comment by 3djc** [comment]
We adapt rate, but if there is too much data, well, there is not much we can do about that

**Comment by skaman82** [comment]
Hm, any chance to filter some data out without restarting the connection again and again?

**Comment by 3djc** [comment]
Not sure how we could decide what shoud go or not go

**Comment by skaman82** [comment]
maybe selectable setting to do A. all sensors or B. just battery and data relevant for navigation only (Alt, GPS, SATS)?

**Comment by skaman82** [comment]
Same could be also handy on the "Telemetry Mirror on serial port" feature on radios like X9D, Radiomaster etc. As far I know there is no option to change internal telemetry rate on X9D like on the x-lite. And in case of CRSF the telemetry is send also at 115200 baud out of the serial port (inverted in this case)

**Comment by kilrah** [comment]
We don't exactly want to start adding custom processing and filtering for specific protocols.
Can't you reduce the sending rate of whatever sensors you're using? Or use the BT in the CRSF module...

**Comment by skaman82** [comment]
@kilrah About "sending rate of whatever sensors": I was not aware of this option in openTX, maybe sensor based sending rate would be a good solution. Where i can find it? (or do you mean on CRSF side?) The BT in the CRSF does only Mavlink and is too slow (max 2HZ on Mavlink vs. 10Hz native telemetry). 

You don't need to do filtering for specific protocols. Maybe adding custom update/forward rate to every telemetry sensor would be a good solution like: "native, 0.1 / 0.2 / 0.5 / 1.0s

**Comment by skaman82** [comment]
Access modules (like R9) have most likely the same issue as they are working on a very fast baud rate as well (PXX2 is 450k I think). I am not sure about the telemetry update rate tho, but think it is way slower than 10Hz

**Comment by kilrah** [comment]
> About "sending rate of whatever sensors": I was not aware of this option in openTX,

OpenTX can't do anything about it, but it might be configurable in your sensor, or whatever the onboard device sending telemetry data is. 

> You don't need to do filtering for specific protocols. Maybe adding custom update/forward rate to every telemetry sensor would be a good solution like: "native, 0.1 / 0.2 / 0.5 / 1.0s

Still requires us to buffer incoming messages, compare them to a list of different behaviors to act accordingly, make some kind of UI to configure it... the current system is "byte comes in, byte is pushed out". 

> Access modules (like R9) have most likely the same issue as they are working on a very fast baud rate as well (PXX2 is 450k I think). 

They don't, link baudrate between radio and module is irrelevant, it's the quantity of data that can go over the telemetry link, and it's lower on all other systems.

**Comment by skaman82** [comment]
@kilrah okay, I understand, thank you. I noticed if I set the max telemetry baud rate of my x-lite to 115200 the BT stability improves significantly - any chance we could have at least this "max bauds" seting on other radios as well (like jumper and radiomaster) to improve things?

**Comment by arf-it** [comment]
> > About "sending rate of whatever sensors": I was not aware of this option in openTX,
> 
> OpenTX can't do anything about it, but it might be configurable in your sensor, or whatever the onboard device sending telemetry data is.
> 
> > You don't need to do filtering for specific protocols. Maybe adding custom update/forward rate to every telemetry sensor would be a good solution like: "native, 0.1 / 0.2 / 0.5 / 1.0s
> 
> Still requires us to buffer incoming messages, compare them to a list of different behaviors to act accordingly, make some kind of UI to configure it... the current system is "byte comes in, byte is pushed out".
> 
> > Access modules (like R9) have most likely the same issue as they are working on a very fast baud rate as well (PXX2 is 450k I think).
> 
> They don't, link baudrate between radio and module is irrelevant, it's the quantity of data that can go over the telemetry link, and it's lower on all other systems.

@kilrah this sounds really logic. I could be wrong but looking at the code the BT module speed is set at 115k (it looks hard coded to me but I could be wrong) despite the telemetry mirror speed set in the hardware menu.
When I'm using the crossfire I set the speed at 400k in the menu. With this configuration  I'm pretty sure that the phisical sport of my Taranis is running at the same speed (400K) while Bluetooth is at 115K and I'm experiencing the same issues reported by @skaman82.
It could be that the BT UART its just overflowed?

**Comment by 3djc** [comment]
Yes BT is clearly is overflow by CRSF telemetry rate, is CRSF is running at 400k.
Things we can do short term:
- allow users to reduce sport max baurate even on radio that always allow 400k (and therefore are not showing the option)
- allow faster mirroring on devices with external HW uarts (TX16S)  (it does 115k there as well I think, need to check)

**Comment by arf-it** [comment]
@3djc  I agree in principle with the first option for my Taranis (that, by the way, need the inverter mod to run at 400K..). I personally don't see the need to have telemetry running at 400K: I guess that data coming down from the flight controller is not faster than 2~5 Hz but I think that the same port is used by the CRSF module to exchange data with the Taranis and reducing to 115K probably will affect performance somehow.
I can already use that option (I see 115K in the hardware menu) and in this case, I'm experiencing a "sensor lost" warning time to time (this will never happen with speed at 400K). This is just to say that approaching this way probably will create lot of troubles to people not using the telemetry mirror.

Long term I think could be great to "decouple" the telemetry mirror feature from the main communication speed. How to do it: no idea but I saw a project running LTM telemetry on serial via LUA script could be a good idea to give access to Bluetooth to LUA in order to mirror telemetry via LUA (there is already an issue opened on this topic) and maybe buildup LUA libraries that mirror telemetry.

**Comment by brainbubblersbest** [comment]
#8073
