### ISSUE TITLE
Missing sounds for "Timer X elapsed" in spanish sound files

### ISSUE THREAD

**Issue by ignaciobfp** [opentx/opentx#7770]
Sorry to make this a bug report, but I was unable to find where I can submit new sounds for the SDCard.

AFAIK there is a sound speaker/recorder, but I am not familiar with this project and I have no idea if this is related to this. In short, sound files for timer elapsed are missing in spanish, so only a beep sounds.

Path for this files would be as follows
SD_ROOT\SOUNDS\es\SYSTEM\timovr1.wav
SD_ROOT\SOUNDS\es\SYSTEM\timovr2.wav
SD_ROOT\SOUNDS\es\SYSTEM\timovr3.wav

It was a bit annoying for me so I prepared some valid wav files for my own usage, but I have no idea on how/where I can submit them to be included in future sdcard content releases. Am I missing something?

HW: Horus X12s, SW: OpenTX 2.3.9

**Comment by kilrah** [comment]
SD card contents are autogenerated by a script based on this code: https://github.com/opentx/opentx/blob/2.3/radio/util/tts_es.py

If you tell us the words it should say we can add them.

**Comment by ignaciobfp** [comment]
> 
> 
> SD card contents are autogenerated by a script based on this code: https://github.com/opentx/opentx/blob/2.3/radio/util/tts_es.py
> 
> If you tell us the words it should say we can add them.

Thank you for pointing me in the right direction and for providing the information, I will try to add a pull request myself to add the missing sounds.
