### ISSUE TITLE
FrSky Taranis X9D Plus SE 2019 gimbal issue

### ISSUE THREAD

**Issue by HFATL** [opentx/opentx#7771]
Recently I've received a new radio: the FrSky Taranis X9D Plus SE 2019. However I'm having an issue in CH3 and CH4 (mode 2) with my radio. It is running the latest OpenTX 2.3.9. CH1 and CH2 works as expected but CH3 and CH4 show an erratic behavior: with a small touch in the gimbals the output changes a lot and then there is a large deadband near the endpoints of the sticks.

Please see the video below with the problem: https://drive.google.com/file/d/1epbQSXde0XhVos4iGfZMMAyMfDvxyK34/view?usp=sharing

Any help please?

Thank you and best regards

**Comment by kilrah** [comment]
Do a stick/pot calibration.
