### ISSUE TITLE
I can not flash firmware to rx from 9xr pro

### ISSUE THREAD

**Issue by JoshuaShaw** [opentx/opentx#7773]
there are no the option of flash firmware to rx in sd-card menu.
[Gif of the bug](https://easyexcelif.com/images/bug.03.gif)

**Comment by dgatf** [comment]
You must flash the firmware in bootloader mode (trims inwards while powering up the tx)

**Comment by kilrah** [comment]
He says flash a receiver.  Was never supported on 9XR-Pro et al.

**Comment by JoshuaShaw** [comment]
Is there any plan to support it?

**Comment by lucajon** [comment]
hi, i got the same problem, turnigy 9xrpro opentx 2.2.3. no option to flash firmware of the receiver(xm+) and xjt module. i remember that i have done it before (2017) with this radio. 
I don't remember which version I used... have you find the fix?

**Comment by lucajon** [comment]
'normaly' with the file .frk in the firmware folder, when you select the file you should have the flash rx menu option! but nothing!?!
