### ISSUE TITLE
Strange issue

### ISSUE THREAD

**Issue by Ziov1** [opentx/opentx#7776]
Updated my taranis x9d plus to the latest version of opentx but getting issues with file corruption and unable to transfer the bmp images files from sd card contents to the sd card. I'm also unable to load r9 firmware for the R9 modual. 

In the sd card contents new entries keep being created and can't delete them. Link to video. [Youtube](https://youtu.be/CuonTRpEC1E)

**Comment by kilrah** [comment]
Format/replace SD
