### ISSUE TITLE
Taranis x9d plus se 2019 RAS 0/--

### ISSUE THREAD

**Issue by RookFPV** [opentx/opentx#7778]
Hardware Taranis x9d plus se 2019
Firmware OTX v2.3.9
ISRM v2.1.0

Internal module display RAS 0/-- Why ?

Old Taranis X9d Plus SE It displays RAS well

**Comment by 3djc** [comment]
This site is not for end user support, but for OpenTX bug tracking. Please go to community site like rcgroups or openrcforum for support. In addition 0/--- is a perfectly valid display meaning 0 ras on internal module, no measure on external
