### ISSUE TITLE
Theme Settings: custom colors

### ISSUE THREAD

**Issue by skaman82** [opentx/opentx#7780]
I can only set custom background and main color on the default theme. 
If I select any other theme (blue/tbs) there are no options to change the colors anymore. 

I am trying to achieve this: white text (like in the blue theme) and colored background (icons in the top bar same color as background). Not possible with the default theme.
I am not sure if this is a bug or just missing functionality.

Other solution would be to change the text color in the default theme. 

Tested on TX16S, OpenTX ver 2.3.10N257

**Comment by kilrah** [comment]
Flexi theme was added in the meantime.
