### ISSUE TITLE
Add ability to reorder LUA scripts in Tools menu

### ISSUE THREAD

**Issue by jyunte** [opentx/opentx#7782]
I searched for this feature request and couldn't find it.

When adding or updating a LUA script, Opentx places the new script at the bottom of the list in the Tools menu (long-press Menu).

I'd like to be able to reorder the scripts using the same method as reordering models... Long-press enter to open a menu to Move, Copy, Delete.

**Comment by kreidler** [comment]
Same here.
Just updated the BF Luas to actual version. Have had this script as a telemetry screen. Now changed to the bottom of the TOOLS menu. Even if you delete all luas in tools dir, do a power cycle and copy the file back the sorting order is different but without any sense. 
I am not sure if "copy" and "delete" will be helpful. A single option to reorder the single entries would be sufficient.

**Comment by JimB40** [comment]
Adding same request. It seems now TOOLS folder files are sorted by file's modification date. So we have to scroll to most used scripts.
Simple sorting by file name or toolName inside lua (toolName = "TNS|name|TNE") will do the trick.

**Comment by ichiemo** [comment]
I would also find this incredibly useful, another way to implement sorting could be renaming/adding a numeric value to the beginning of the lua script file or adding a folder for each lua script to be placed in with a numeric value to order them in the menu.

**Comment by JimB40** [comment]
@pfeerick I thinlk we haven't implemented alphabethic sorting. Re-open or we leave it close as in new UI there will be new App section?

**Comment by pfeerick** [comment]
ROBERT! You need more coffee! ;) 

1) Why would I re-open something on a project I'm not a member of?
2) Look again, "we" did, and it's been like that since 2.6, so only been alphabetically sorted for the last five months! 😆

**Comment by JimB40** [comment]
Well for years working with devs I learned that when they say "It's done" it means coding without testing :)

EdgeTX 2.7

![screenshot_x9d+2019_22-04-24_06-44-52](https://user-images.githubusercontent.com/46420768/164957101-74cc4bc3-38eb-451e-a356-4f38fa751334.png)
![Screenshot 2022-04-24 at 06 42 48](https://user-images.githubusercontent.com/46420768/164957102-324adfab-1e9c-4a42-9af4-4a6078f62255.png)

**Comment by pfeerick** [comment]
No, that means it was implemented in colorlcd - you didn't ask *where* it was implemented ;) This is still the wrong project to be commenting on anyway ;) edit: Happy now? https://github.com/EdgeTX/edgetx/issues/1886 😝

**Comment by JimB40** [comment]
Buahaha. I love devs
My most loved quote is "I know it doesn't work but look how wonderful algorithm is"
Ups just spotted I'm commentin in OTX ;) Sorry morning coffee not strong enough
