### ISSUE TITLE
2.3.9 Jumper T18 / Display is rotated 180° 

### ISSUE THREAD

**Issue by steve-1000** [opentx/opentx#7788]
With flashing the new firmware V2.3.9 of open TX the display is rotated 180°.
Its a bug or a wrong setting somewher else? I'm new in open tx..

TX: Jumper T18pro with image for Jumper [T16..](url
![2 3 9_JumperT18_Display 180 turned](https://user-images.githubusercontent.com/67792321/86476408-c47b5980-bd46-11ea-813f-e28c5da00dcd.jpg)
)

**Comment by 3djc** [comment]
T18 is NOT supported on 2.3.9. Please download a 2.3.10 nightly FOR T18 (NOT T16)  and reflash
