### ISSUE TITLE
2.3.9 - Simulator does not work in Companion on Mac for QX7 ACCESS radio

### ISSUE THREAD

**Issue by VancouverUmbrella** [opentx/opentx#7789]
OpenTx 2.3.9
Radio profile: QX7 ACCESS

Error message: "The simulator for this firmware is not yet available."

![Screen Shot 2020-07-03 at 8 10 06 AM](https://user-images.githubusercontent.com/56514835/86481570-22874d00-bd05-11ea-89be-d77ba670538c.png)

**Comment by VancouverUmbrella** [comment]
That was fast! 🥇

**Comment by 3djc** [comment]
Available now in 2.3.10 nighlies and will be in 2.3.10 release

**Comment by VancouverUmbrella** [comment]
Nice.
