### ISSUE TITLE
Add ability to map all 16 channels in Companion/Radio Settings/Trianer

### ISSUE THREAD

**Issue by dwheel** [opentx/opentx#7791]
When using an MPM as a receiver for wireless training purposes, all 16 channels from the student transmitter can be utilized in the instructor transmitter. However, Companion only allows the first 4 channels to be mapped. Please add the ability to use all 16 channels in Companion.

**Comment by kilrah** [comment]
You use the TR1 to TR16 sources in the mixer.

**Comment by dwheel** [comment]
Yes, I know. But the control sticks in the companion trainer simulator are always mapped to channels 1 thru 4. They can not be used for simulation if someone wants to use any of the other channels of the student transmitter for A,E,T,R. 

![trainer simulator](https://user-images.githubusercontent.com/6865267/86512738-482a5a00-bdca-11ea-92aa-e60d2e454762.jpg)

**Comment by kilrah** [comment]
Ah, completely different thing.
