### ISSUE TITLE
2.3.9 - Incorrect transmitter options appear in Companion simulator for X9D+ 2019, QX7 ACCESS

### ISSUE THREAD

**Issue by VancouverUmbrella** [opentx/opentx#7793]
**Conditions**
Companion 2.3.9 simulator 
X9D+ 2019 or QX7 ACCESS
Windows

**Case 1 - X9D+ 2019**
Under transmitter options, for the internal module set to _ACCESS_, _Ext. antenna_ and _Power_ appear as options.
https://www.rcgroups.com/forums/showpost.php?p=44918831&postcount=62

**Case 2 - QX7 ACCESS**
As above for case 1.
And, for the external module set to _R9M ACCESS_, _Ext. antenna_ appears as an option.

**Comment by kilrah** [comment]
Options availability depends on the module telling the radio what it's capable of. No module in the simulator so those pages are simply irrelevant.
