### ISSUE TITLE
sbec lua not working

### ISSUE THREAD

**Issue by P-I-Engineer** [opentx/opentx#7796]
sbec tool is not working

**To Reproduce**
plug in battery
-discover sensors
-go to tools, sbec
-syntax error - no sbec in this model
or syntax error attempt to call a nill value.

**Screenshots**

**General information**
 - OpenTX version 2.3.9 and 2.3.10nightly
 - Hardware X9D, X9 lite
 - OpenTX Companion 2.3.9
 -FrSky FrESC32 BL_Heli32 80A 3-6s ESC
-x4r receiver

**Comment by 3djc** [comment]
Are you certain this model is supported by the scripts ? Went throught the product user manual, and no mention of scripts support on this product.

**Comment by P-I-Engineer** [comment]
Just googled and dawned on me as well, no adjustable Bec.

It's either 5v or 12v

Sorry for confusion, thanks for time
