### ISSUE TITLE
Compiling 2.4

### ISSUE THREAD

**Issue by wimalopaan** [opentx/opentx#7805]
I tried to compile 2.4 as I do for 2.3. But I get an cmake error regarding libopenui (not present in the thirdparty directory).

This is the cmake command:

cmake -DUSB_SERIAL=ON -DHELI=OFF -DTRANSLATIONS=DE -DPCB=X10 -DPCBREV=TX16S -DINTERNAL_MODULE_MULTI=YES -DGVARS=YES -DLUA=YES -DALLOW_TRAINER_MULTI=ON -DCROSSFIRE=OFF -DDSM2=PPM -DINTERNAL_MODULE_PXX1=OFF -DPXX1=Off  -DXJT=OFF -DRADIOMASTER_RELEASE=YES -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..

This ist the cmake output (with error regarding libopenui):

CMake Deprecation Warning at CMakeLists.txt:14 (cmake_policy):
The OLD behavior for policy CMP0023 will be removed from a future version
of CMake.

The cmake-policies(7) manual explains that the OLD behaviors of all
policies are deprecated and that a policy should be set to OLD only under
specific short-term circumstances.  Projects should be ported to the NEW
behavior and not rely on setting a policy to OLD.

-- OpenTX 2.4.0 @ 6a5aa60a
-- Python found, version: 3.8.3
-- Qt Version: 5.15.0
CMake Warning (dev) at /usr/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
The package name passed to `find_package_handle_standard_args` (FOX) does
not match the name of the calling package (Fox).  This can lead to problems
in calling code that expects `find_package` result variables (e.g.,
`_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
cmake/FindFox.cmake:59 (find_package_handle_standard_args)
CMakeLists.txt:154 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Foxlib found at /usr/lib/libFOX-1.6.so
-- SDL Lib: /usr/lib/libSDL.so;-lpthread; Headers: /usr/include/SDL; Version: 1.2.15
CMake Error at radio/src/gui/colorlcd/CMakeLists.txt:93 (include):
include could not find load file:

/home/lmeier/Projekte/opentx/opentx2/radio/src/thirdparty/libopenui/src/CMakeLists.txt
Call Stack (most recent call first):
radio/src/gui/CMakeLists.txt:1 (include)
radio/src/CMakeLists.txt:141 (include)

TARGET simu/libsimulator: cpp compiler /usr/bin/g++ v10.1.0
-- Added optional gtests target
TARGET bootloader: cpp compiler arm-none-eabi-g++ v4.7.4
TARGET firmware: cpp compiler arm-none-eabi-g++ v4.7.4
-- Simulators library search path: /usr/local/lib/companion24
TARGET companion24: cpp compiler /usr/bin/g++ v10.1.0
-- Added optional gtests-companion target
CMake Deprecation Warning at companion/src/CMakeLists.txt:363 (cmake_policy):
The OLD behavior for policy CMP0026 will be removed from a future version
of CMake.

The cmake-policies(7) manual explains that the OLD behaviors of all
policies are deprecated and that a policy should be set to OLD only under
specific short-term circumstances.  Projects should be ported to the NEW
behavior and not rely on setting a policy to OLD.

-- install /home/lmeier/Projekte/opentx/opentx2/build_rmtx16s to /usr/local/bin
-- Configuring incomplete, errors occurred!
See also "/home/lmeier/Projekte/opentx/opentx2/build_rmtx16s/CMakeFiles/CMakeOutput.log".
See also "/home/lmeier/Projekte/opentx/opentx2/build_rmtx16s/CMakeFiles/CMakeError.log".

**Comment by 3djc** [comment]
2.4 is simply far from been  ready
