### ISSUE TITLE
Just Create the model- wizard problem

### ISSUE THREAD

**Issue by alexdibi** [opentx/opentx#7807]
- OpenTX version 2.3.9
 - Hardware x9 lite
 - OpenTX Companion 2.3.9, Jun 14 [2020](url)

On companion i've selected "Just Create the model" without wizard...
but once opentx is updated the wizard is there....
for security I downloaded the file again, but the problem persists

![opentx](https://user-images.githubusercontent.com/52356568/87048920-9ee5c880-c1fc-11ea-9003-4841606ed112.jpg)
![IMG_20200709_154616](https://user-images.githubusercontent.com/52356568/87048938-a4dba980-c1fc-11ea-83c6-73c9b4e14adb.jpg)

**Comment by kilrah** [comment]
This only concerns the wizard when creating a model **in companion**.

![image](https://user-images.githubusercontent.com/6065069/87049420-3d722980-c1fd-11ea-91e8-21be058494e6.png)
