### ISSUE TITLE
Settings for pots,sticks,switches to trigger backlight on

### ISSUE THREAD

**Issue by frizzle101101** [opentx/opentx#7809]
Can we further the backlight off and on capibility ides by adding a setting to remove the sticks from the backlight trigger as well as pots and switches...there shld be 3 settings, stick backlight trigger, switch backlight trigger and pot backlight trigger...the hole idea comes from flying at night and moving the sticks turns on my backlight where id like that to only happen really when im scrolling and clicking in menus and such, i just dont like how the sticks turn on the back light when moved but i still want the push of buttons to turn it on.

**Comment by kilrah** [comment]
As you've been answered in the other thread you commented in, the "Keys" choice has been there just for that for ever.
