### ISSUE TITLE
Radiomaster TX16S HID button and SD Card button mixed up

### ISSUE THREAD

**Issue by GotskGK** [opentx/opentx#7812]
Hi so it looks like this is quite and easy fix. It's just that when I select HID device it goes into mass storage and vice versa. I've attached a video. This is on the latest 2.3.9 I found on opentx which I flashed today, 11/07/2020.

Thanks for your continued hard work on opentx 
[IMG_1765.MOV.zip](https://github.com/opentx/opentx/files/4906832/IMG_1765.MOV.zip)
and getting the radiomaster supported this early.

**Comment by 3djc** [comment]
Absolutely not. As anywhere on the radio, the darker element is selected
