### ISSUE TITLE
Taranis Q7 battery loose contact

### ISSUE THREAD

**Issue by flyinggerda** [opentx/opentx#7816]
1. power on Taranis Q7 and Transmitter works
2. loose contact of battery causes disruption of power supply --> q7 is off
3. no restart of the transmitter if battery is connected again
4. --> plane crashes

Q7 should remember if power was on or off before loosing contact of battery
old Taranis XD9 does (mechanical switch remembers)

Murphy is everywhere - here too

**Comment by kilrah** [comment]
Nothing we can do about that.
