### ISSUE TITLE
Radiomaster TX16S will not save date and time

### ISSUE THREAD

**Issue by uavpilotjoe1981** [opentx/opentx#7823]
I noticed after installing the latest firmware that the TX16S is refusing to save my Date and Time. Could this be a software issue or is it the Backup battery in the radio? Thanks for the help.

**Comment by 3djc** [comment]
What does RTC bat report ? (RADIO/Hardware screen toward bottom)

**Comment by uavpilotjoe1981** [comment]
.58v That must be the issue. Sad that Radiomaster sends these out with dead RTC batteries

**Comment by 3djc** [comment]
Contact RM support, they will fix it for you. They usualy answers very quickly and are very helpfull
