### ISSUE TITLE
Implenent Trainer Tab in Menu into each Model

### ISSUE THREAD

**Issue by Mucki** [opentx/opentx#7824]
Hello,
in my Model club i have a bunch of kids, whom i teach Flying via a Buddy Box System. Everone of them has his own plane, which is bound to my transmitter. But as some of them fly different modes, have some servo reverses, dont want to control the motor yet or want to fly with less percent of servo movement, i always have to change the settings in the Trainer Tab in the menu. 

Is there a way to save the setttings in the Trainer Tab for each model?
Maybe you could make it so you dont have to change it the trainer tab it the menu but in the model pages.

You would have to move the trainer tab from the general transmitter setup to the model setup, so to speak.

I hope you understand what i mean.

Best regards.

**Comment by kilrah** [comment]
You can completely ignore the trainer tab and do model-specific setups using the trainer channels (TR1-16) directly in the mixer.
