### ISSUE TITLE
X10S Express - Registration ID is not displayed on Model Setup screen

### ISSUE THREAD

**Issue by Alex00101** [opentx/opentx#7825]
OpenTX2.3.9 on X10S Express
**Steps to reproduce the behavior:**
1. Select the model (set for  ISRM ACCESS) and go to Model Set Up screen
2. Scroll down to the Internal RF section.
3. Reg.ID field is not visible
4. Click 'Register' - Reg.ID is visible in the registration dialog but even after registration not shown on the Model Set Up screen.

**Expected behavior**
This may be by design, however on my X10S radio upgraded with ISRM Upgrade module (also OpenTX2.3.9) Reg.ID is always on even if model is set to ISRM D16.  Perhaps the expected behavior is to not show it for D16 and always show it for ACCESS?

![Pic2](https://user-images.githubusercontent.com/27343158/87764542-ece07900-c859-11ea-8313-9dba13278624.jpg)

**Comment by 3djc** [comment]
Could you avoid opening an issue with two issues inside ? That completely breaks github autoclosing feature ...

**Comment by Alex00101** [comment]
Apologies.  Would you like me to go back and try to split it?

Sorry

**Comment by 3djc** [comment]
There are even 3 apparently, soo confusing. Yes please open one per issue

**Comment by Alex00101** [comment]
Done

**Comment by 3djc** [comment]
The registration ID is shown only of different from Ownerid, and I believe behaves the same way in both radio.
