### ISSUE TITLE
X10S Express - "Select RX..." appears on Model Selection Dialog

### ISSUE THREAD

**Issue by Alex00101** [opentx/opentx#7826]
OpenTX2.3.9 on X10S Express
**Steps to reproduce the behavior:**
1. Select the model (set for  ISRM ACCESS) and go to Model Set Up screen
2. Scroll down to the Internal RF section and perform Register/Bind sequence for ACCESS.
3. Exit Model Set Up screen and long press right button for model selection dialog. 
4. "Select RX..." appears on Model Selection Dialog and goes away after radio restart.

**Expected behavior**
I think this is an unwanted remnant of the ACCESS Bind dialog.

![Pic1](https://user-images.githubusercontent.com/27343158/87768728-ece37780-c85f-11ea-83c7-9b486db5195d.jpg)

**Comment by 3djc** [comment]
Fixe by https://github.com/opentx/opentx/commit/5e4c301e78aaf7a0d028f06eed0faf1d4040f74f
