### ISSUE TITLE
 X10S Express - RX ID check behavior inconsistent between ACCESS and D16

### ISSUE THREAD

**Issue by Alex00101** [opentx/opentx#7827]
OpenTX2.3.9 on X10S Express.
**Steps to reproduce the behavior:**
1. Select the model (set for  ISRM ACCESS) and go to Model Set Up screen
2. Scroll down to the Internal RF section and try to set Receiver No to the value used in other model:
2a. If the model is set to ACCESS changing value in Receveier No field does not produce warning, however the warning is produced if I select Mode ISRM field and press right button (Enter) 2 times.
2b. If the model is set to D16 changing value in Receveier No field produces the warning (as expected). The same seems to be the case on X10S radio upgraded with ISRM Upgrade module (also OpenTX2.3.9). 

**Expected behavior**
I think it should be as described in 2b. (D16)

**Comment by kilrah** [comment]
Do you actually have another model using the same receiver no and using ACCESS?

The system is supposed to allow duplicate numbers if the protocol is different since that naturally prevents a conflict on its own.

**Comment by Alex00101** [comment]
Retested. X10 Express with OpenTX2.3.9 and latest ISRM firmware.
**Setup**
Model 1 - D16            RX# 1
Model 2 - ACCCESS    RX# 2
Model 3 - D16            RX# 3
Model 2 - ACCCESS    RX# 4
Test Model ---
No other models set.

**Test 1. Test Model set to ISRM D16** 
RX# set to 1 - "RX# is used warning" (further referred as Warning)  produced as expected. On RX# field value cofirmation (ENT).
RX# set to 2 - No warning - as expected.
RX# set to 3 - Warning produced - as expected.  On RX# field value confirmation (ENT).
RX# set to 3 - No warning - as expected.

**Test 2. Test Model set to ISRM ACCESS** 
RX# set to 1 - no warning is produced on On RX# field value confirmation (ENT). However if 'ISRM' field (Mode) is double clicked, the Warning is produced (referring to Model 1 - D16).
RX# set to 2 - no warning is produced on On RX# field value confirmation (ENT). However if 'ISRM' field (Mode) is double clicked, the Warning is produced (referring to Model 2 - ACCESS).
RX# set to 3 - no warning is produced on On RX# field value confirmation (ENT). However if 'ISRM' field (Mode) is double clicked, the Warning is produced (referring to Model 3 - D16).
RX# set to 4 - no warning is produced on On RX# field value confirmation (ENT). However if 'ISRM' field (Mode) is double clicked, the Warning is produced (referring to Model 4 - ACCESS).

**Interpretation***
D16 works as expected, ACCESS looks inconsistent. In other words, unless I'm changing the protocol/mode duplicate RX# may be unnoticed**
