### ISSUE TITLE
Transfer channels 17-32 as time-multiplex  

### ISSUE THREAD

**Issue by wimalopaan** [opentx/opentx#7828]
For shipmodels or other "slower" rc models it could be very interesting to get more than 16 channels transferred to the receiver. Clearly, most receivers aren't capable of decoding nor ist the 4-in1-module capable of encoding all 32 channels. 
Recently there was an update to the MPM-Module for AFHDS2A to transfer also channel 15/16 and 17/18 (!).

This triggered my longstanding idea to encode the additional channels 17-32 as a time-multiplex sin two other (unused channels to gain in total 14 channels more, with a reduced update rate.

It could be implemented as follows:

- we use twi channels in the range of 1-16 (18 for AFHDS2A) to transfer the channel-# and value of one of the channels 17-32.

- every time the payload is transferred to the MPM, a different channel-value is transferred

- after all of the channels 17-32 are transferred, the transfer begins again with channel 17 (cyclic).

With this scheme, we get all additional channels 17-32 encode with a reduced update rate as a time-multiplex in the current sbus frame.

Clearly, on the receivers side the must be an SBus/IBus-to-PWM decoder to decode the additional channels. But this should be doable for most hobbyists - I would like to share my implementation.

Do you see any chance to get this FR to be implemented?

If not, please provide me with the neccessary information to do so. 

Thanks!!!

**Comment by hrenz** [comment]
its a Nautic-Funktion at Graupner or Robbe
