### ISSUE TITLE
Telemetry 2.3.9 with 2.1.0 firmware on X12S - RPM 

### ISSUE THREAD

**Issue by Joetrin** [opentx/opentx#7829]
*Before submitting,  search the open issue if there is already a report of the bug*
Hardware: X12S
OS: OpenTX 2.3.9
Firmware: 2.1.0

OpenXsensor using Arduino on RPM, became unstable after installing 2.3.9 and 2.1.0, unfortunately I can not tell if it's a module firmware issue or an OpenTX issue.

The other issue is logging RPM:  Even though RPM is unstable and fluctuates, the log reader and logs that are being saved are multiplying the log output of the RPM by 2.  6000 rpm shows as 12000 rpm.

I'll upload the logs later today.

**Comment by 3djc** [comment]
Well you are going to have to test with a v1.0 firmware, that should allow to find out if it is 2.3.9 or 2.1.0 related
