### ISSUE TITLE
Widget value convert to text

### ISSUE THREAD

**Issue by asterix4you** [opentx/opentx#7830]
InfoBar. OpenTx 2.3.9 TX16S
Hi, in the upper bar I inserted two widgets (Switch SE and SG with three positions). Upon their activation, the values ​​0% - 50% - 100% are shown. I would like them to show for Switch SE> Normal (0%); Attidude (50%); GPS (100%) and for Switch SG> Normal (0%); HL (50%); CL (100%). What can I do?

**Comment by 3djc** [comment]
Write your own wiget in lua. Please remember that this site is to be used only to track OpenTX bugs. For support, please go to community sites like rcgroups or openrcforum
