### ISSUE TITLE
Models reset after reboot and Can't read models in Companion - Radiomaster TX16S

### ISSUE THREAD

**Issue by Addzy21** [opentx/opentx#7832]
Hello

After updating to the latest firmware 2.3.9 and card contents when i create a model it resets after i reboot the radio also Companion cannot read the models, it errors saying "Can't extract model1.bin" (screenshot attached) I've set up the new radio profile as per Painless Video. https://www.youtube.com/watch?v=HGLX0l299so&list=PLYsWjANuAm4pGrFcykUq-lATEOwvxWEmh&index=8

I was able to create models before i upgraded but not able to save models in Companion
I have even rolled back with the card backup 

Can you suggest some help

Cheers
Adam
![Screen Shot 2020-07-19 at 5 17 43 pm](https://user-images.githubusercontent.com/68494895/87870142-c9980400-c9e8-11ea-9b34-190e6b5458bd.png)

**Comment by 3djc** [comment]
We are sorry but this site is only for bug tracking. For end user support, please go to community sites like rcgroups or openrcforum.
