### ISSUE TITLE
Switchs not working 

### ISSUE THREAD

**Issue by Ziov1** [opentx/opentx#7834]
I have my x9d+ updated with all latest firmwares but my switchs are not working. S1 / 2, side roll switchs and trims work but all other switchs don't work. 

Do these need to be enabled? Or is there a software issue? Switchs don't register when set manually and don't register when trying to set them in setting up mode, inav does not detect them either. 

Help please.

**Comment by 3djc** [comment]
We are sorry but this site is only for OTX bug tracking. For usage support please go to community sites like rcgroups or openrc forums
