### ISSUE TITLE
'Value' Widget won't change colour Radiomaster TX16s

### ISSUE THREAD

**Issue by GotskGK** [opentx/opentx#7836]
Hi,

Setup: Radiomaster TX16S, Opentx 2.3.9

When setting up widgets, in the widget settings, regardless of what colour I set it seems that the text colour for the 'value' widget is always dark blue?

**Comment by 3djc** [comment]
Please this place is for bug tracking. For usage question, please go to community places like rcgroups or openrx forums

**Comment by GotskGK** [comment]
Surely if it won't change colour that is a bug? I mean I can adjust the R, G and B of the colour I want for the value widget but it doesn't actually carry this out. Maybe I'm wrong.

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/88073262-473d4a80-cb76-11ea-9633-f25084ea38f8.png)

![image](https://user-images.githubusercontent.com/5167938/88073318-5623fd00-cb76-11ea-92eb-25ada200cb06.png)

**Comment by GotskGK** [comment]
[Archive.zip](https://github.com/opentx/opentx/files/4954824/Archive.zip)
Hmmmm that's weird... this is what I get.

**Comment by GotskGK** [comment]
To confirm, the same also seems to happen when using the dark theme.

**Comment by kilrah** [comment]
The value always shows in blue if no data is received, when there is your color is used

**Comment by loetefix** [comment]
That the value shows allways in blue if no data is still a bug because it should appear in the system "ALARM_COLOR_INDEX".
In default theme it should appear in RED and in the darkblue theme in a grey.

in the file opentx/radio/src/gui/480x272/widgets.cpp there are two lines with:

      lcdSetColor(ALARM_COLOR_INDEX);

i changed to:
    
     lcdSetColor(lcdColorTable[ALARM_COLOR_INDEX]);

and now the value appears in the right color if no data isreceived

**Comment by JustinTimeToo** [comment]
> The value always shows in blue if no data is received, when there is your color is used

My top bar widgets show the text in blue **_when there is_** a value and they show the white text when there is no value.

I came here by searching how to change this and found your answer. How do I change this?
