### ISSUE TITLE
Inverse hardware

### ISSUE THREAD

**Issue by frizzle101101** [opentx/opentx#7837]
Hi so i just updated some gimbals in my opentx transmitter and did the calibration but cant see any way to inverse the hardware, i culd go to the mixxer on each model but that would be super annoying to have to inverse all my controls on all my models, im hoping theres a way to inverse the hardware so mixers dont need to be changed

**Comment by 3djc** [comment]
Unless you fork and modify the code accordingly, you cannot do that I'm affraid. The only supported inversion is installing Hall gimbal in an X9E

**Comment by frizzle101101** [comment]
Thats silly why isnt that a feature request them?

**Comment by 3djc** [comment]
If it makes you feel better reopening it, but since that cannot be done at least before next major release it won’t help you

**Comment by frizzle101101** [comment]
But it culd be in a maintenance release of the next major update...i will
sill do the modification and make a pull request i guess then

**Comment by frizzle101101** [comment]
Havent had a chance to do a big implementation on this so i was wondering how i could enable the "horussticks" options on somthing like the t16 or any other target other than x9e
