### ISSUE TITLE
I want to help for translating chinese, What i can do ?

### ISSUE THREAD

**Issue by iakuf** [opentx/opentx#7839]
maybe I can help for translating, What i can do ?

I modify and create opentx/radio/src/translations/cn.h.txt ?

**Comment by PD5DJ** [comment]
I gues that is very hard to do because of the limitations of the Font set?

**Comment by iakuf** [comment]
I don`t know what can i do . 
if someone can introduce me, maybe i can translate from en to cn.

**Comment by kilrah** [comment]
Chinese fonts are planned for 2.4 I believe. For now nothing to do.
