### ISSUE TITLE
[Opentx] check box not visible for Italian language in HARDWARE menu

### ISSUE THREAD

**Issue by OpenMik** [opentx/opentx#7842]
OpenTX 2.3.9
Radio X9E Italian language
In HARDWARE menù check box for "Check RTC voltage" is not visible because the italian text is too long
("Controllo voltaggio RTC")
Text may be only
"Controllo RTC"

**Comment by 3djc** [comment]
Or "voltaggio RTC" ?

**Comment by 3djc** [comment]
"Controllo RTC batt" or something ? Check RTC is really a bit ambiguous no ?

**Comment by 3djc** [comment]
I guess actually the best option is to push the items a bit on the right, no reasons to squeeze those

**Comment by OpenMik** [comment]
may be a solution push the items a bit on the right
but for this in debug option is necessary to move the [Switches] text under the [Analog ] text
there is no more space on the right 
in Italian the text "Interruttori" Is not completely visible

please check also the bluetooth option
first show "---" 
second show "Enabled" (In italian "Attivo")
third show blank space (in italian "Non in mo")
