### ISSUE TITLE
[2.3.9] SH switch not in model logfile

### ISSUE THREAD

**Issue by 0crap** [opentx/opentx#7844]
The SH switch which I use as a (dis)arm switch is never logged in my model logfile on the Taranis QX7S.
The value is always -1.
(For trouble shooting it is nice to see if I used the disarm switch mid flight for example.)

Other switches I use are logged into the model logfile by default.
Is this a bug or am I misunderstandig something? (Could very well be the case.)

![SH switch](https://user-images.githubusercontent.com/31951195/88456458-42321100-ce7e-11ea-8e4c-c6feb84069ce.jpg)

**General information**
 - OpenTX version: 2.3.9
 - Hardware: Frsky Taranis QX7S
 - OpenTX Companion: 2.3.9 Windows

**Comment by 3djc** [comment]
SH is a toggle, so when you activate, it might be ON for a very short period, and therefore not appear in logs as ON

**Comment by 0crap** [comment]
That would be a bad decision, to have a toggle switch to disarm. :-)
So that is not the case. Might be I swapped it in the past.

![SH switch](https://user-images.githubusercontent.com/31951195/89888925-1084ae00-dbd1-11ea-8af0-83f5b16f5863.jpg)

**Comment by 3djc** [comment]
Cannot replicate

![image](https://user-images.githubusercontent.com/5167938/89889950-d3212000-dbd2-11ea-8337-53b540ee7d43.png)

![image](https://user-images.githubusercontent.com/5167938/89889988-dddbb500-dbd2-11ea-9026-52627fa5ef01.png)

Both are properly logged. Do you happen to enable logging on your arm switch too ?

**Comment by 0crap** [comment]
Hmmm, I'm only aware I could enable/disable logging on found telemetry sensors.
Where can I enable/disable this on switches?

**Comment by 3djc** [comment]
What i meant is logging is not by default, it needs to be enabled by a sd logs special function. This special function is triggered by a switch. Is it SH or a related LS ?

**Comment by 0crap** [comment]
OK, I understand.
Yes, it is triggered by my arm switch. 🥇 
Guess that's why.
Sorry for wasting your time.

I played with delay but that only seems to interact when starting logging.
Any smart thing to do, to keep logging a second after disarm? (Not having to use a separate switch.)

**Comment by 3djc** [comment]
You need to create a LS for that

**Comment by 0crap** [comment]
@3djc I tried, using the Delay parameter would be the most logical choice to use.
However Delay is only active on activation. Deactivation happens immediately. (Maybe that is a bug?)

Can you give an example how to keep logging active for a few seconds after disarming?

**Comment by kilrah** [comment]
Set the source to be the opposite of what you want, then select the !LS to start logging.

**Comment by 0crap** [comment]
@kilrah Thx for stepping in.
What you are effectively creating with that is having the Delay function during deactivation.
So yes, that works if you're only starting and stopping logging with the arm switch.
I have more logic depending on the arm switch, so now that doesn't work as intended.

To me it seems a bug that the Delay parameter is only active on activation.
If Delay is also active on deactivation (what you would expect it to do in the first place) would make for a clean solution.

Is Delay only working on activation intended behaviour?

**Comment by kilrah** [comment]
Whether intentional or not it's how it's been for many years so it's not like it could be changed on a whim. But nothing prevents you from making separate LSes for both functions.
