### ISSUE TITLE
5v line disabled on telem mirror for Radiomaster TX16S

### ISSUE THREAD

**Issue by wx4cb** [opentx/opentx#7845]
question about the 5v line on the uarts on the bottom of the case.

![image](https://user-images.githubusercontent.com/1495297/88459210-a4c8e400-ce61-11ea-8524-e6357febdafd.png)

When I have the left uart set to telemetry mirror, i get 5V at startup on the uart port, but then it turns off. 

however, if i set it to LUA in the hardware page of openTX, then the 5v turns back on. 

as soon as i switch itback to telemetry mirror, the 5v line turns off.

**Comment by 3djc** [comment]
Fixed in nightlies

**Comment by wx4cb** [comment]
> Fixed in nightlies

official nightlies i'm assuming ?

**Comment by NuclearManD** [comment]
@3djc Where were the code changes?  What commit?
