### ISSUE TITLE
Taranis 2019+ SE SBUS Trainer Master not working

### ISSUE THREAD

**Issue by HippoDan** [opentx/opentx#7849]
XM Receiver bound to my X9D+, installed in the 2019 (On 2.3.9).  Nothing shows up on the 2019 as trainer input.  Works in the other direction with the XM installed in the Older Radio.

Can trainer SBUS input from the module bay on the 2019 be made to work?

**Comment by bsongis** [comment]
we have an open PR for this one, it cannot be closed
