### ISSUE TITLE
Real, real ugly voice

### ISSUE THREAD

**Issue by bigtwin** [opentx/opentx#7850]
The new voice "Welcome to OpenTX" in Open TX 2.3.9 is unbelievable ugly.
It was fine with 2.3.7 and I really wonder why this has been changed.

I am pretty sure that most of the users dont like the new voice and therefor I would like to ask for a rollback.

**Comment by 3djc** [comment]
Since nothing has changed on our side, it means this is a change on Google side

**Comment by bigtwin** [comment]
@3djc - would be fine if you can quick explain what role goolge plays at this point ...(?)

**Comment by 3djc** [comment]
The voice are generated from strings using google tts
