### ISSUE TITLE
Jumper t12 with openTX 2.3.9  + FrSky xsr

### ISSUE THREAD

**Issue by FOBOSTECH** [opentx/opentx#7852]
Jumper t12 (version openTX 2.3.9)   with Multi-Protocol  jp4in1-se (version multi-stm-opentx-taer-noinv-v1.3.1.36) does not connect with FrSky xsr (version FW-XSR-v2.1.0)

**Comment by 3djc** [comment]
You need to select FrSkyX2 protocol (https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md)

**Comment by FOBOSTECH** [comment]
Not connecting, green and red lamp is on
