### ISSUE TITLE
Value widget in wrong color if no data

### ISSUE THREAD

**Issue by loetefix** [opentx/opentx#7858]
That the value shows allways in blue if no data is a bug because it should appear in the system "ALARM_COLOR_INDEX".
In default theme it should appear in RED and in the darkblue theme in a grey.

in the file opentx/radio/src/gui/480x272/widgets.cpp there are two lines with:

  lcdSetColor(ALARM_COLOR_INDEX);
i changed to:

 lcdSetColor(lcdColorTable[ALARM_COLOR_INDEX]);
and now the value appears in the right color if no data isreceived

**Comment by 3djc** [comment]
Not sure it should be alarm colour, need to give it some thoughts

**Comment by loetefix** [comment]
Alarm colour is what it was , so i chose it. Alternatively it is possible to make this colour configurable.
