### ISSUE TITLE
2.3.9 Special Functions options in Companion do not match transmitter

### ISSUE THREAD

**Issue by dwheel** [opentx/opentx#7859]
**Describe the bug**
When programming Trainer functions in Companion I can not access Parameter options that are available when programming on transmitter.

**To Reproduce**
1. Go to Special Functions in Companion
2. Click on Any function and select Trainer
3. Cannot scroll to Parameter
4. See Picture

**Expected behavior**
On transmitter, I can scroll over to Functions and select Sticks. Option not available in Companion.

**Screenshots**
See attached picture

**General information**
 - OpenTX version 2.3.9
 - Hardware Radiomaster TX16S and matching Companion
 - OpenTX Companion 2.3.9 Windows 10
![companion239](https://user-images.githubusercontent.com/6865267/89237958-38b15300-d5ba-11ea-8b82-83d9dfcd5a59.jpg)

**Comment by kilrah** [comment]
![image](https://user-images.githubusercontent.com/6065069/89257919-67194780-d627-11ea-8a6c-8ad6e9e4d7de.png)

They're just different choices on the main list instead of a separate list.

**Comment by 3djc** [comment]
Maybe we should just update companion 'Trainer' to 'Trainer Sticks' for better matching with the radio ?

**Comment by kilrah** [comment]
Yep that's a good start... and maybe do the same split as on the radio if we feel like.
