### ISSUE TITLE
Channel Monitor pops up during X-Lite S_Pro value edit

### ISSUE THREAD

**Issue by lthole** [opentx/opentx#7865]
No existing issue found.
 
**Description of bug**
The Channel Monitor popup should be disabled when in value edit mode.

**To Reproduce**
When in edit mode on (for example) a Weight value, and:
a) if I try to use the shift + up/down/left/right to give the value edit shortcuts by pressing shift first, the shift button also brings up the Channels Monitor because it sees it as shift_long before I can operate the joystick. 
b) if I press up/down/left/right first, it starts counting up or down, and if I then press shift I can get it to jump to -100, +100, 0 or invert, etc. Again, if I press shift for too long it brings up the Channel Monitor. The invert is tricky because it is counting up until I press shift. By then the inverted value is not the starting value I wanted to invert.

**Expected behavior**
While in value edit mode you should be able to press shift followed by joystick up/down/left/right to invoke the value edit shortcuts without the Channel Monitor popping up.

**General information**
 - OpenTX version 2.3.9
 - Hardware: X-Lite Pro
 - Also refer to rcgroups ' Frsky X-Lite and other Taranis (X9 Lite, X-Lite S, X-Lite Pro)' thread from #4876.

**Comment by kilrah** [comment]
Can move the channel monitor to shift-enter maybe?
