### ISSUE TITLE
Taranis X9D (original one). Cant get into bootloader.

### ISSUE THREAD

**Issue by abreimeris** [opentx/opentx#7866]
Hello.
I purchased my Taranis back when they very first came out (2012 or 2013?)
Due to reasons of changing lifestyle, I never really got to play with it at the time.
Now I'm getting back into RC and I need to upgrade the firmware. Its still 1.1.02
However, I cant get the Taranis to go into bootloader mode.
I tried turning it on with the Horizontal trim buttons both pushed to the center. No change. Just boots up normally.
Was there a different way of getting into the bootloader on the early Taranis?
Failing that, is there a way of loading the new firmware via the SD Card?

Thanks in Advance.

**Comment by kilrah** [comment]
Firmware is so old it predates the bootloader. Need to flash via dfu with power off.

Please note this place is for tracking development matters, not for user questions.
