### ISSUE TITLE
BMP Screenshot preview

### ISSUE THREAD

**Issue by prodzprodz** [opentx/opentx#7868]
Hi,

Is it possible to display BMP files directly on the radio fullscreen when scrolling trough SCRENSHOT folder?
Only option is copy, rename and dellete. Prewiev on right side is totaly messed up.

Greetings from Croatia,
Igor

![pic  (1)](https://user-images.githubusercontent.com/69361176/89670111-ed13e780-d8e0-11ea-8ca4-fb2a2357afef.jpg)
![pic  (2)](https://user-images.githubusercontent.com/69361176/89670118-f0a76e80-d8e0-11ea-97e5-2ee8c1ee9502.jpg)

**Comment by 3djc** [comment]
Duplicate #7359
