### ISSUE TITLE
Theme Text colors cannot be adjusted

### ISSUE THREAD

**Issue by robertmehrer** [opentx/opentx#7877]
When Setting the default  theme background you cannot set the Theme text colors. The text is default black so any image other than white, gray, blue, you cannot read any of the widget borders or text within them. When setting  to the blue theme the text inverts to white but you cannot set a background image. This seems a little odd, is there a location where the text color can be set or is this a bug?

**Comment by kilrah** [comment]
The built in themes were just never meant for that level of customization and were basically examples hoping people would contribute more.

But https://github.com/opentx/opentx/pull/7841 will be in 2.3.10.

**Comment by robertmehrer** [comment]
thank you !!
