### ISSUE TITLE
Companion : ??? in sources instead of EX1/EX2

### ISSUE THREAD

**Issue by 3djc** [opentx/opentx#7879]
2.3.9 and current nightlies

![image](https://user-images.githubusercontent.com/5167938/90217132-ba964d00-de00-11ea-8cc8-fe639a41935e.png)

**Comment by elecpower** [comment]
Initial investigations reveal that EX1 and EX2 are set to type None in Radio Settings - Hardware for a new TX16S profile and therefore do not show in the list however when they do appear in the list the two ??? entries still display.

**Comment by 3djc** [comment]
Just as a reference, it is not TX16S specific, it is the same for x10 for exemple

**Comment by elecpower** [comment]
@3djc yes, as I have been working through the code I noticed they share the same logic which is expected. 
Should these radios have JSx and JSy in the sources list? If so then I believe I have the fix.

**Comment by 3djc** [comment]
No not quiten JSx and JSy are only for X12S where those two slots are used for the "joystick", on other 'horus', it is a spare 'analog) port, like there is SI/Sj for switches

**Comment by elecpower** [comment]
If I am understanding you, these two ??? entries should just be dropped from the list.

**Comment by 3djc** [comment]
When not defined (set to none in radio hardware) then yes they should not be there, howerver if defined, then they should with either custom name or ex1/ex2 name

**Comment by kilrah** [comment]
To have the indexes right in other places we normally always show them, but grey out if not applicable

**Comment by 3djc** [comment]
yes, with ex1 / ex2 name (or custom name)

**Comment by elecpower** [comment]
ex1 and ex2 work as they should. Need to prevent 'horus' radios other than 12S displaying ??? in the joystick reserved positions

**Comment by 3djc** [comment]
Just display ex1 ex2 instead of ??? (since ex1 for x10 is on the same slot as JSx for x12). In other words, always show for horus but ex1/2 when !x12s, JSx/y if x12s
