### ISSUE TITLE
No EU Option for X9d+ 2019

### ISSUE THREAD

**Issue by Jullibach** [opentx/opentx#7880]
Hello,
i have the X9d + 2019SE and i since the Version 2.3.9 i dont have the Option to flash to non EU.

![Unbenannt](https://user-images.githubusercontent.com/69680881/90252536-f8669600-de3f-11ea-9874-d0bac869fab8.JPG)

**Comment by 3djc** [comment]
Eu was just hidding d8. This radio does not do d8, so there is no need to hide it

**Comment by Jullibach** [comment]
Why the X9d+ supports D8 and the 2019 model not? (;

**Comment by 3djc** [comment]
This is a choice made by FrSky, please ask them, nothing to do with OpenTX
