### ISSUE TITLE
Companion 2.3 crashes when attempting to access global functions context menu

### ISSUE THREAD

**Issue by bigtwin** [opentx/opentx#7883]
This is about _Edit Radio Settings_ in Companion 2.3.9. 
When I am doing a right click on a row in "Global Functions", Companion crashes immediatly. This is reproducable anytime. I have only tested with MAX OSX 10.12.6.

**Comment by elecpower** [comment]
Confirmed issue also on Win 10 and Ubuntu 16.04

**Comment by 3djc** [comment]
yeah windows too, :) At least it is consistent :D Thanks for grabbing this one @elecpower 👍

**Comment by elecpower** [comment]
@3djc I broke it so I should fix
