### ISSUE TITLE
X12S with OpenTx 2.3.9 cannot flash Rx ACCESS firmware (extension .frsk)

### ISSUE THREAD

**Issue by bbc25185** [opentx/opentx#7891]
Today I mounted the ACCESS module on the X12S.
Installed correctly, OpenTx version 2.3.9 flashed with "internalAccess" tick.
I copy on the SD the files for updating the ISRM module and those for the RX6R and RXSR receivers (all with the .frsk extension).

I launch the update of the internal radio module and everything happens without problems, but when I try to update the Rx (using the usual method with the cable attached to the pins of the JR module), selecting the file NO flash option appears, only the items COPY, RENAME and DELETE. (same behavior also in the simulator)

The strangest thing is that by renaming the file extension with .frk, everything seems to work (it starts the RX update and, in the end, it says that it was done correctly) but when I try to test the ACCESS protocol, it does NOT bind **WHILE** binds correctly **IF I SET THE MODULE IN ACCST MODE** ??????

Radio: Frsky X12S
Firmware: OpenTx 2.3.9 with "InternalAccess"
Tx Module firmware: ACCESS 2.1.0 EU

**Comment by 3djc** [comment]
Has been fixed recently, please try a nightly. Renaming won’t work
