### ISSUE TITLE
External Radio Module Receiver Number Field

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#7893]
In the upcoming future, external radio module protocol at least for the Crossfire protocol will have a Receiver No. I'd like to request that field be available/mapped when editing a model.
It might makes sense to also make sure the Model summary page, column RX # also displays Receiver No. for external modules like it does now for internal radio system.

![7D47C97E-51F9-4DC3-846C-BC00C184BEA9](https://user-images.githubusercontent.com/13228659/90725700-6d3d3400-e275-11ea-8e2f-20501cf60cf6.JPG)
<img width="1212" alt="Screen Shot 2020-08-19 at 11 38 13 PM" src="https://user-images.githubusercontent.com/13228659/90725570-3cf59580-e275-11ea-80ac-3a2a5536e4ef.png">
<img width="752" alt="Screen Shot 2020-08-19 at 11 38 20 PM" src="https://user-images.githubusercontent.com/13228659/90725580-40891c80-e275-11ea-8fbb-dbf9163560f5.png">

**Comment by 3djc** [comment]
The first part is within the crsf modelid PR.

On the last screen however, it poses a lot of issues since both internal and external can have their own number, so which one do you display, it raises a lot of issues

**Comment by ghost** [comment]
label and delimit? Acceptable values could be `01-internal` or `02-external;01-internal`.

**Comment by elecpower** [comment]
What about separate columns "Int.RX #" and "Ext.RX #"? This would also make identifying and colour coding duplicates simpler.
Update: checked the code and external modules that support RX# should be displayed in the models list though there is no label to identify if the RX# is for an internal or external module.

**Comment by 3djc** [comment]
sure
