### ISSUE TITLE
Mixers getting invisible in HorusX12S after moving channels in companion

### ISSUE THREAD

**Issue by Gewe99** [opentx/opentx#7908]
It is possible to move channels via "Move Up" and Move Down" 
This is great because all corresponding mixer lines are automatically moved with the channel.

![grafik](https://user-images.githubusercontent.com/27633575/91653440-39e27c80-eaa1-11ea-8df9-d6d47757b99e.png)

Before moving Channels everything works fine...
![grafik](https://user-images.githubusercontent.com/27633575/91653487-b2e1d400-eaa1-11ea-87d1-4096009b55cc.png)

When I move channel 2 with "Move up" to Channel 1 nearly all other Mixers get invisible.
![grafik](https://user-images.githubusercontent.com/27633575/91653511-f0466180-eaa1-11ea-8f41-e4bb3ba68e7b.png)

The mixers work as they should, but they are invisible an can not be edited.
![grafik](https://user-images.githubusercontent.com/27633575/91653536-1f5cd300-eaa2-11ea-9f3f-461a07a1ce6d.png)

You can reproduce it in a real radio and in the simulator.

When you download the Model from the radio, the mixers are visible in companion.

Here my test template
[ChannelFinder.zip](https://github.com/opentx/opentx/files/5146447/ChannelFinder.zip)

Regards Dirk

**Comment by elecpower** [comment]
Confirmed lines are hidden also for X9D+ in the Simulator. Not a refresh issue as tested saving settings and reloaded model.
