### ISSUE TITLE
 TX16S switch SB has no position↓ problem

### ISSUE THREAD

**Issue by zyren** [opentx/opentx#7912]
OpenTX version: 2.3.10N310
Radio: Radiomaster TX16S

The switch SB only has ↑ and -. When the switch SB is placed in the position of ↓, it does not work. Occasionally there will be a success, and then it will not work. Then after waiting for about a few minutes, ↓ will appear. Toggle switch SB, the same problem occurred again.

**Comment by 3djc** [comment]
It was fixed on Jul 28th, and only affects some firmware combination (it is actually a compiler issue). Current nighlies do not have this issue
