### ISSUE TITLE
Tele2 Recvr Bat Voltage Ratio Fluctuates

### ISSUE THREAD

**Issue by CaptLeMay** [opentx/opentx#7925]
Radiomaster TX16S setup per the Users Manual.
Firmware:  opentx-tx16s-bluetooth-faichoice-flexr9m-lua-ppmus-                   en-2.3.9-otx.bin
                 multi-stm-opentx-taer-noinv-v1.3.1.49.bin
FrySky D8R XP Receiver
3S GensAce Lipo Flight battery

Tele A2 Flt Bat Voltage Ratio varies each time the receiver is powered up.  It usually starts around 24 to display proper voltage, but drifts down to about 8.6 as time goes on.

![Firmware](https://user-images.githubusercontent.com/70938150/92457594-960a7680-f1ee-11ea-9f22-c483829a22ff.png)
![Telemetry](https://user-images.githubusercontent.com/70938150/92457598-97d43a00-f1ee-11ea-8d4f-73094dadc33e.png)

**Comment by 3djc** [comment]
Telemetry is displayed untouched, so it is an issue on your receiver side imho

**Comment by kilrah** [comment]
Did you actually connect a sensor to the A2 input? The receiver doesn't magically guess the pack voltage.

**Comment by CaptLeMay** [comment]
Andre, Thanks for your reply.Attached is the instruction sheet for the receiver.As you can see on the instruction sheet, there is an internal sensor for the battery voltage with a 4:1 ratio. 
 Wow!  It must be Magic!!  I call it firmware.I did not attach an external sensor since the receiver has an internal sensor.
I will get an external sensor and see if that works without fluctuations.If it still fluctuates, would you say this may a software issue?  Admittedly, it may be a problem with the receiver. I have 2 D8R II receivers and the fluctuations occur on both.
Thanks for your time.Ross
 
 
-----Original Message-----

**Comment by kilrah** [comment]
The internal sensor gives you the voltage the receiver is supplied with, either as RxBt or A1.

A2 is an external input for a sensor, and if you want to measure pack voltage you need to use that. The receiver doesn't have access to the pack voltage without one.

**Comment by CaptLeMay** [comment]
OK,I'll put an external sensor on.
 
 
-----Original Message-----
