### ISSUE TITLE
Tele A2 Flt Bat Ratio Fluctuates

### ISSUE THREAD

**Issue by CaptLeMay** [opentx/opentx#7926]
Radiomaster TX16S setup per the Users Manual.
Firmware:  opentx-tx16s-bluetooth-faichoice-flexr9m-lua-ppmus-                   en-2.3.9-otx.bin
                 multi-stm-opentx-taer-noinv-v1.3.1.49.bin
FrySky D8R XP Receiver
3S GensAce Lipo Flight battery

Tele A2 Flt Bat Voltage Ratio varies each time the receiver is powered up.  It usually starts around 24 to display proper voltage, but drifts down to about 8.6 as time goes on.

![Firmware](https://user-images.githubusercontent.com/70938150/92457594-960a7680-f1ee-11ea-9f22-c483829a22ff.png)
![Telemetry](https://user-images.githubusercontent.com/70938150/92457598-97d43a00-f1ee-11ea-8d4f-73094dadc33e.png)

**Comment by kilrah** [comment]
Duplicate #7295
