### ISSUE TITLE
"Slow" functions slows input channel, not the Mix.  ei: aileron slow, not flap

### ISSUE THREAD

**Issue by CaptLeMay** [opentx/opentx#7927]
Radiomaster TX16S setup per the Users Manual.
Firmware:  opentx-tx16s-bluetooth-faichoice-flexr9m-lua-ppmus-                   en-2.3.9-otx.bin
                 multi-stm-opentx-taer-noinv-v1.3.1.49.bin
FrySky D8R XP Receiver

Mixing flaps with Ailerons, the "Slow Up/Down" function does not slow the flaps, but it does slow the aileron movement.  Also, must use the "Replace" function to prevent an opposite direction movement of the ailerons prior to the correct direction movement.  IE:  Moving the aileron up first causes a down movement followed by the proper direction up movement.

![Input](https://user-images.githubusercontent.com/70938150/92460265-f6e77e00-f1f1-11ea-9485-871241d8bd88.png)
![Logical Swithes](https://user-images.githubusercontent.com/70938150/92460268-f818ab00-f1f1-11ea-8542-36a7b17d1edf.png)
![Output](https://user-images.githubusercontent.com/70938150/92460271-f8b14180-f1f1-11ea-9411-4ee14633aa9f.png)
![Setup](https://user-images.githubusercontent.com/70938150/92460276-f949d800-f1f1-11ea-929c-b282d29aea98.png)
![Mixes](https://user-images.githubusercontent.com/70938150/92460418-28604980-f1f2-11ea-8d97-389599f7d122.png)
![Special Functions](https://user-images.githubusercontent.com/70938150/92460456-31511b00-f1f2-11ea-8186-b42855cd64f8.png)

**Comment by 3djc** [comment]
This place is not for end user support. Your programming is wrong in many ways, but this is not the right place for discussing it. Please go to community sites like rcgrousp or openrc forums for community support

**Comment by CaptLeMay** [comment]
Thank you for your reply.
Sorry to have posted on the wrong site for assistance.
As I obviously need help in the programming,would you please direct me to a specific site or sites where I can get it. 
 I have read through most of the openTX university documents, and watched multiple YouTube videos to try to learn.  I have found nothing relating to the problems I am experiencing with the slow; dif, and travel adjustments.

 
 
-----Original Message-----
