### ISSUE TITLE
"Dif" function does not funtion on "Input 6" on duel aileron or elevon mix setup.

### ISSUE THREAD

**Issue by CaptLeMay** [opentx/opentx#7928]
Radiomaster TX16S setup per the Users Manual.
Firmware:  opentx-tx16s-bluetooth-faichoice-flexr9m-lua-ppmus-taer-en-2.3.9-otx.bin
                 multi-stm-opentx-taer-noinv-v1.3.1.49.bin
FrySky D8R XP Receiver
Input 2 is right aileron, Input 6 is left aileron
Servos are centered and linkages are 90 degrees to servo arms but up/down travel is not equal.

On my previous radio setup, the JR 9X II, the Exponential top/bottom endpoints could be adjusted to get equal up/down movement on up to 3 rates/flight modes.  That function is not available on the TX16s.  So....

For "High Rates" , setting the "Rate" to the desired throw on the side of the lowest movement,  I then adjust the "Dif" of the "Input" to give me equal travel on the side of the most movement.  "Low Rates" are  not equal, and I can not find a way to adjust them seperately.  "Offset" is then used to re-center the servo on Lower Rates.

The "Dif" function on "Input 6" (the left aileron) has no affect on the movement of the servo.

I have setup two planes.  One with a flying tail/Delta wing (elevons) configuration, and this one with the conventional configuration.  I have the same problem on both of them.

I am new to Open TX, so please excuse me if I am doing this all wrong.  
Is there any way to adjust for equal travel left/right, or up/down, of the servo in multiple flight modes/ rates?
Thank you
CaptLeMay

![Input](https://user-images.githubusercontent.com/70938150/92460265-f6e77e00-f1f1-11ea-9485-871241d8bd88.png)
![Logical Swithes](https://user-images.githubusercontent.com/70938150/92460268-f818ab00-f1f1-11ea-8542-36a7b17d1edf.png)
![Output](https://user-images.githubusercontent.com/70938150/92460271-f8b14180-f1f1-11ea-9411-4ee14633aa9f.png)
![Setup](https://user-images.githubusercontent.com/70938150/92460276-f949d800-f1f1-11ea-929c-b282d29aea98.png)
![Mixes](https://user-images.githubusercontent.com/70938150/92460418-28604980-f1f2-11ea-8d97-389599f7d122.png)
![Special Functions](https://user-images.githubusercontent.com/70938150/92460456-31511b00-f1f2-11ea-8186-b42855cd64f8.png)

**Comment by 3djc** [comment]
This place is not for end user support. Please go to community sites like rcgrousp or openrc forums for community support
