### ISSUE TITLE
No Frsky X option on 2.3.9 TX16S

### ISSUE THREAD

**Issue by Daviot52** [opentx/opentx#7934]
2.3.9 Open TX 
Radiomaster TX16S
No option for Frsky X only X2

**Comment by kilrah** [comment]
Might need to update module.

**Comment by Daviot52** [comment]
Module just updated yestarday. Reflased rx to fcc v1 tried option Frsky D16 and it bound ok. Issue seems to be change in OpenTX as option for X8R is now Frsky D16.  Option Frsky X no longer available.

**Comment by 3djc** [comment]
FrSky X never was in OpenTX, we rename it

**Comment by Daviot52** [comment]
So difference in multiprotocol module naming and open tx naming ?

**Comment by 3djc** [comment]
X, D and V are regrouped under FrSky label, and you select them as subtypes. X2 is not included tho

**Comment by Daviot52** [comment]
Thanks for the explanation. I was more than a little confused due to the
similarities with the multimodule but not seeing the same structure in open
tx. Is this listed somewhere ? I had done several searches but not come
accross this information. I also had some older X8Rs that did not seem to
bind with any protocol which helped increase the frustation reflashed them
now all is ok.
Thanks.

**Comment by kilrah** [comment]
It's in the MPM doc.
https://www.multi-module.org/using-the-module/protocol-details/frsky-d
