### ISSUE TITLE
RADIOMASTER TX16S & FrSKY X8R

### ISSUE THREAD

**Issue by RSRCTRUCK** [opentx/opentx#7943]
I have a TX16S, the X8R bind to radio, have green led on X8R, Channel 5-8 work, BUT CHANNEL 1-4, DON'T WORK FROM STICKS.

**Comment by 3djc** [comment]
Sorry but this site is to be used only to report OpenTX bug, which yours is not. Please use community sites like rcgroup or openrc forums for community support
