### ISSUE TITLE
% indications blank on mix screen

### ISSUE THREAD

**Issue by coulsonrobert** [opentx/opentx#7945]
When scrolling through the mixes the % indication shows blank on some lines. Best shown by video, link below:

[Youtube link](https://youtu.be/flycGqvamo0) 

Version shown here.

![E7F4075C-0A8D-4769-B632-596D964D1EB5](https://user-images.githubusercontent.com/71485194/93562641-57a75100-f97e-11ea-8fab-ee172dbf64cb.jpeg)

**Comment by 3djc** [comment]
It is your bold numbers that are not displaying, not sure why. Please reflash firmware and ensure SD content is correct. Also are you using iNav script ?

**Comment by 3djc** [comment]
Duplicate #6969

INav issue as mentionned here : https://github.com/opentx/opentx/issues/7095#issuecomment-555471746
