### ISSUE TITLE
Audio file select list fast scroll

### ISSUE THREAD

**Issue by RMFPV** [opentx/opentx#7946]
**Is your feature request related to a problem? Please describe.**
Scrolling through Audio files list takes VERY long time with a roller.

**Describe the solution you'd like**
Using stick for fast scroll. 

**Describe alternatives you've considered**
Page button to scroll many items at a time. Or jump to next first letter files set.

**Comment by bigtwin** [comment]
This would be fine :-) Its a mess to locate the desired sound file using the transmitter. However, since it is not very comfortable to check whether "this" file contains actually "that" sound, I usually do stuff like that in Companion.
