### ISSUE TITLE
Ideas-- calculated sensors to tell the bearing from start point (or xmitter) to current position of model, as well as direction model is currently travelling, and glide angle from current position to start point

### ISSUE THREAD

**Issue by aeronaut999** [opentx/opentx#7952]
Ideas-- calculated sensors to tell the bearing from start point (or xmitter location if GPS-enabled) to current position of model, as well as the GPS-track-derived direction model is currently travelling.  Also glide angle from current position to start point (or to xmitter location if GPS-enabled.)  I would really enjoy having this information readily available as calculated sensors.

**Comment by 3djc** [comment]
Easy to do with LUA, also already transmitted by INav for exemple

**Comment by PD5DJ** [comment]
Using OpenXsensor GPS already gives you de "Hdg" output.. Bearing of plane.

**Comment by aeronaut999** [comment]
Good to know, but I don't fly w/ that hardware; FrSky GPS sensor does not give "Hdg" output.

**Comment by PD5DJ** [comment]
> Good to know, but I don't fly w/ that hardware; FrSky GPS sensor does not give "Hdg" output.

I can say, start using them.. they perform far more better then the original GPS'ses :-)

Faster fix due availability of Better performing GPS'ses like Ublox Neo8> chipsets.
Faster Position updates Frsky = 1x /sec, Ublox = 10x /sec (handy for ground speed measurement)
GPS Altitude very accurate, due the fact Ublox uses Multiple Sattellite platforms for calculation.
Gives status output, Sats in view, Hdop etc..
Costs a lot less :-)

**Comment by bigtwin** [comment]
Eventhough I would also love to have this feature, I dont think this is something which can be done in a transmitter in a sensefull manner. I know from other GPS sensors that they are providing those values. Just as OpenXSensor. Its a "problem" of the FrSky Sensor and I dont think this can be addressed within OTX.

**Comment by lshems** [comment]
Of course it could. But Lua is probably where the Devs will point.

No reason why it would not be possible.
