### ISSUE TITLE
Only one "Serial port (TTL)" Displayed on Hardware menu.

### ISSUE THREAD

**Issue by al21883** [opentx/opentx#7958]
On the Hardware screen (System menu) there's only one "Serial port (TTL)" available.
It's a brand new radio, and i haven't done any HW modification. I have reflashed the firmware to the latest (Stable) available, and the problem persist.

Thanks in advance for your help!

 - OpenTX version: 2.3.9-otx (Crossfire, faichoice, flexr9m, internalmulti, multimodule, lua, luac, ppmus)
 - Radiomaster TX16S
 - OpenTX Companion 2.3

**Comment by 3djc** [comment]
Clearly not here

![image](https://user-images.githubusercontent.com/5167938/93905270-0f2fc080-fcfb-11ea-8e2b-e52439dd5304.png)

![image](https://user-images.githubusercontent.com/5167938/93905374-325a7000-fcfb-11ea-98e0-ac4a3a935839.png)

**Comment by al21883** [comment]
I don't understand. Same version, same Hardware:

![IMG_20200922_180202](https://user-images.githubusercontent.com/33052244/93907645-e5c46400-fcfd-11ea-9d60-3ac1c153e582.jpg)
![IMG_20200922_180148](https://user-images.githubusercontent.com/33052244/93907651-e8bf5480-fcfd-11ea-88a0-c20d906d7dc7.jpg)

**Comment by 3djc** [comment]
You have BT option

**Comment by al21883** [comment]
Thanks!
