### ISSUE TITLE
Reverbed Audio X12S

### ISSUE THREAD

**Issue by PD5DJ** [opentx/opentx#7965]
**Describe the bug**
Occasionally Reverbed audio on X12S, I dont know if this is caused by OpenTx.

**To Reproduce**
Occasionally there is Reverbed audio on my X12S, directly from turning on the radio, switching it back off and on again and Audio is normal non reverbed.

**Expected behavior**
Normal audio :-) no Reverbed although it is not disturbing

**Screenshots**
https://youtu.be/p-ALz_kaiJo

**General information**
 - OpenTX version (e.g. 2.3.9)
 - Hardware: Frsky Horus X12S Access upgrade
 - OpenTX Companion v2.3.9

**Comment by kilrah** [comment]
Official sound pack or 3rd party?

**Comment by PD5DJ** [comment]
Good point, I am now using TTSautomated files.

I will try official soundpack, and let you know

Although I never hear(d) it on my X10S (Express) and Xlite Pro,

All use the same Soundpacks.


https://www.dropbox.com/sh/oxalciz0lsszh1m/AAA-UBCaxaO3siYLakZ-k-8Na?dl=0
