### ISSUE TITLE
Channel monitor graphical/display glitches

### ISSUE THREAD

**Issue by xnoreq** [opentx/opentx#7967]
**Describe the bug**
The channel monitor has weird graphical/display glitches where certain columns have a different color/contrast.

See photo:
![channelmonitor](https://user-images.githubusercontent.com/4028859/94287026-169ed600-ff56-11ea-8e1e-a6aa963bdf6b.jpg)

**General information**
OpenTX 2.3.9 on X9-Lite S

**Comment by 3djc** [comment]
Fixed already

**Comment by xnoreq** [comment]
With which commit/version?

**Comment by xnoreq** [comment]
Still the case in 2.3.10N330 with sdcard-128x64-2.3V0032.

**Comment by 3djc** [comment]
Do you still have the empty rectangle or just a bar ?

**Comment by 3djc** [comment]
Ok i get it, I was assuming x7 has it is a known x7 issue, so x9lite also has the crappy screen, will do like x7

**Comment by 3djc** [comment]
You should be able to test with tomorow 's nightly

**Comment by xnoreq** [comment]
Thanks. https://github.com/opentx/opentx/commit/3715669b9155ec8abac703252c90f1b8644b87c2
