### ISSUE TITLE
Taranis X9D Plus SE 2019 getting bricked eveytime trying to flash 2.3.9 through companion

### ISSUE THREAD

**Issue by venom-code** [opentx/opentx#7969]
I was trying to update the Taranis X9D PLUS SE 2019 from 2.3.5 (which worked without any issue) to 2.3.9 and encountered this issue that after the update was completed in companion and you exit companion disconnect usb and choose exit on the tx instead of it going to the welcome screen the tx just shuts down but the power button still shows a dim blue light which usually is bright when functioning normally, tried taking out the battery and rebooting the tx but nothing works, the only thing that is possible is to go into bootloader mode, after checking for various things, like formatting and checking for corrupt sd card or wrong fw etc everything seemed okay, removed amber sound pack and custom sounds but still the problem persisted, then i tried the method of flashing the fw through the tx by copying the downloaded 2.3.9 onto the the FIRMWARE folder of the sd card and that finally took it out of its bricked state, so had nothing to do with custom sound files etc, the problem that i face now is that i cannot use custom splash when flashing through the sd card method and 2ndly and more important is that the models are still present but all their settings have been reset which is a huge headache, so for now no splash screen other than the default opentx one and all settings for individual models will need to be done i cannot figure out what is causing this and what is the proper solution to this issue if any of the experienced members can find a solution would be great otherwise updating next time would be a bad experience specially to do all the settings for different models again.

**Comment by 3djc** [comment]
Duplicate #7742 

Copy firmware on SD and flash from bootloader
