### ISSUE TITLE
Special Function : No "Override chanel" available 

### ISSUE THREAD

**Issue by lalibe-m** [opentx/opentx#7972]
Hi there,

I've recently updated my OpenTX version to 2.3.9,

I've been surprised to see that the "Override Chanel" option is no more available,

Is that an issue? or a choice?

If so, what's the option I can use in order to get it right?

Kind regards,

**Comment by 3djc** [comment]
It is a choice, your choice actually, when you selected nooveridech option ...

**Comment by lalibe-m** [comment]
Yeah I just saw that... Sorry for taht, have a nice day!
