### ISSUE TITLE
Sounds drop down menu issue Taranis X9D+SE 2019

### ISSUE THREAD

**Issue by Martivip** [opentx/opentx#7975]
Hello 

**Describe the bug**
When in SOUND/en folder I will merge audio files from latest Amber sound pack and with the BetaFlight sounds from latest Lua Script pack then sounds list on dropdown menu is not properly displayed

![IMG_2580](https://user-images.githubusercontent.com/72009313/94407360-a79ec880-0173-11eb-920a-1e4ceb820e90.jpg)
![IMG_2582](https://user-images.githubusercontent.com/72009313/94423300-b6dc4100-0188-11eb-9f64-95a8306409a7.jpg)

**To Reproduce**
Steps to reproduce the behaviour:
1. Download the latest Amber Sound Pack to SD card
2. Download the latest BetaFlight Lua Script pack 
3. Merge both packs (BF Lua pack contains 4 more audio files) on SD card 
4. Go to Special Functions
5. Click on SF1
6. Choose Play Track
7. Choose sound file - and right now you will see that dropdown menu with list of the files is corrupted

When I delete this 4 more additional audio files that comes from BF Lua Script pack in SOUNDS/en folder everything comes back to normal.

**Expected behaviour**

![IMG_2584](https://user-images.githubusercontent.com/72009313/94423578-22261300-0189-11eb-98b9-917eaff31d0b.jpg)

**General information**
 - OpenTX version 2.3.9 (60e1edc1)
 - Hardware Taranis X9D+ SE 2019
 - FW Version OpenTX-x9d+2019
 - OpenTX Companion 2.3.9

**Comment by 3djc** [comment]
How was your SD card formated ? Would be interesting to try with it formated as FAT32 (NOT exFAT)

**Comment by Martivip** [comment]
my SD card is formatted to FAT32
<img width="361" alt="Zrzut ekranu 2020-09-28 o 11 40 15" src="https://user-images.githubusercontent.com/72009313/94417814-d8d1c580-0180-11eb-91ed-d356909d0281.png">

**Comment by Martivip** [comment]
does anyone is able to confirm this problem ?

**Comment by Martivip** [comment]
after OpenTX update to 2.3.10 the issue still exists

**Comment by mhon44** [comment]
I had the same problem on my X-Lite, OTX 2.3.9, also on 2.3.10. It seems like the LUA Script was not updated recently. 

Solved it simply by deleting corrupted .waw files

**Comment by Martivip** [comment]
> I had the same problem on my X-Lite, OTX 2.3.9, also on 2.3.10. It seems like the LUA Script was not updated recently.
> 
> Solved it simply by deleting corrupted .waw files

I don't think that issue is related to corrupted .wav files, please do this exercise :
when you delete this BF .wav files, please replace them by 5 different ones and the issue will come back :(

**Comment by mhon44** [comment]
Actually that is true, but I am OK with deleting few files - there are hundreds of tracks I would never use.

Looks like there is a limited number of .waw files in a folder that OTX can show with no issue
