### ISSUE TITLE
LuaC taranis x9d+ 2019 - yaapu

### ISSUE THREAD

**Issue by babolcs** [opentx/opentx#7978]
I installed the yaapu script on my taranis x9d+2019. On the telemetry screen i can see the sensors, but on the yaapu screen i can see no telemetry data. 

At firmware installation for this model there is no luac option just lua. Can it be the problem?

**Comment by 3djc** [comment]
This site is only for OpenTX bug tracking, that your issue really isn't. Please go to community sites like RCgroups or openrxforums for community support

**Comment by babolcs** [comment]
Thanks a lot for your help. 
Yes i was skeptic  to post it here, but didnt know where to. 

Sent from Yahoo Mail for iPhone


On kedd, szeptember 29, 2020, 10:43 de., 3djc <notifications@github.com> wrote:




This site is only for OpenTX bug tracking, that your issue really isn't. Please go to community sites like RCgroups or openrxforums for community support

**Comment by 3djc** [comment]
Yaapu does have a specific thread on rgc : https://www.rcgroups.com/forums/showthread.php?3020527-An-Ardupilot-frsky-telemetry-LUA-script-for-the-Horus-X10-X12-and-Taranis-X9D-E-QX7

**Comment by babolcs** [comment]
Sorry one question.
Is it normal that there is no luac option for taranis x9d+ 2019?
Thx

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 3djc** [comment]
Yes, luac has been defaulted in all build for a little bit over a year

**Comment by babolcs** [comment]
Really thanks a lot for your help. Have a good day. Szabolcs


Sent from Yahoo Mail for iPhone


On kedd, szeptember 29, 2020, 12:12 du., 3djc <notifications@github.com> wrote:




Yes, luac has been defaulted in all build for a little bit over a year
