### ISSUE TITLE
X9D+2019 R9M-2019 ACCESS V1.3 It's not responding

### ISSUE THREAD

**Issue by mimicookie** [opentx/opentx#7983]
"OpenTX 2.3.10-N355" farm cannot set the output power of the R9M-2019 (ACCESS V1.3) module.

The information screen of the module does not appear.

It works properly in OpenTx2.3.9.

 - OpenTX 2.3.10-N355
 - Hardware X9D+2019SE + R9M-2019(V1.3 Flex)
![n355](https://user-images.githubusercontent.com/72244263/94892286-36d31580-04bf-11eb-873e-b2e678b64914.jpg)

**Comment by 3djc** [comment]
Thaks for reporting it. I'll prepare 2 or 3 binaries for you to test to try to narrow down when this issue appeared

**Comment by mimicookie** [comment]
Thank you for your help.

**Comment by 3djc** [comment]
Could you try this one. Just install from SD, just got to module version and just check if showing or not
[firmware-test1.zip](https://github.com/opentx/opentx/files/5316342/firmware-test1.zip)

**Comment by mimicookie** [comment]
Nothing has been improved.
The module version is not shown either.

**Comment by kilrah** [comment]
You did not say if control works properly or not.

**Comment by 3djc** [comment]
OK, right now just trying to narrow down when it broke, making you another test version

**Comment by 3djc** [comment]
Could you try this
[firmware_test2.zip](https://github.com/opentx/opentx/files/5321392/firmware_test2.zip)

**Comment by mimicookie** [comment]
Same as "test1". The module version is not shown. The module version is not displayed, and the transmission power cannot be set.

**Comment by 3djc** [comment]
Could you try this one ?
[firmware_test3.zip](https://github.com/opentx/opentx/files/5321409/firmware_test3.zip)

**Comment by mimicookie** [comment]
"test3" works fine.
It also displays the module version. RF output can be set up by option.
It's perfect.

**Comment by 3djc** [comment]
Tahnks a lot, it confirms that current issue is linked to FRM302 PR, we now need to find the issue there then

**Comment by mimicookie** [comment]
Thanks for the effort.

**Comment by 3djc** [comment]
Could you test this ?
[firmware_testfix1.zip](https://github.com/opentx/opentx/files/5321625/firmware_testfix1.zip)

**Comment by mimicookie** [comment]
"firmware_testfix1" works perfectly.
No problem.

**Comment by 3djc** [comment]
GREAT NEWS !
