### ISSUE TITLE
Switch SA, SB, SC, SD can't on 3 position

### ISSUE THREAD

**Issue by mirkoaero** [opentx/opentx#7990]
I have a problem with the SA, SB, SC, SD switches Cannot be 3 positions, even though the hardware settings have been calibrated to 3 positions, currently all switches can only be 2 positions, please help if there are colleagues here who experience it, I using the jumper t16 firmware open tx 2.3.9

**Comment by 3djc** [comment]
Sorry but this site is for bug tracking, not user support. For assistance, please go to community sites like RCGroups or OpenRC forums
