### ISSUE TITLE
FlySky FRM302 support in 2.310-otx

### ISSUE THREAD

**Issue by vandusinae** [opentx/opentx#7995]
I upgraded to 2.310-otx to get serial support for the FRM302, but I can't find any entry. GHOST, SBUS, R9, MULTI, CRSF, DSM2, XJT and PPM are there.

From the release note:
```
Miscelaneous

Add support for FlySky FRM302 external module
Add support for ImmersionRC Ghost external module
```

Cheers

**Comment by 3djc** [comment]
Is your internal module off ? Radio type?

**Comment by vandusinae** [comment]
x9D+, if it were off, I wouldn't see the other serial protocols ;)

**Comment by 3djc** [comment]
Do you see the option in version screen?

**Comment by vandusinae** [comment]
no, only: Firmware options: crossfire, ghost, noheli, multimodule, lua, luac

**Comment by vandusinae** [comment]
Thank you very much!!!! I found the option in the option in Companion!!

**Comment by 3djc** [comment]
Was about to write that :)

**Comment by vandusinae** [comment]
Thanks again!!
