### ISSUE TITLE
Flysky FRM302 serial module status: not ready - OpenTX 2.3.10-OTX, x9d+, PPM works 

### ISSUE THREAD

**Issue by vandusinae** [opentx/opentx#7996]
I have an issue with the AFHDS3 serial mode with Opentx 2.3.10-OTX on a x9d+ and X-Lite S (with bay adapter).
The module powers up, but can't be controlled via serial mode.

Status: not ready
Power src: unknown

If I select PPM mode everything works. I can bind the receiver and control the quad. When I switch back to serial mode, the transmitter and receiver loses connection. The blue LED on the back of the Flysky tx module flashes slowly.

**Comment by 3djc** [comment]
I think the module requires a specific firmware to work with OpenTX. @qba667 ?

**Comment by vandusinae** [comment]
Thanks for tip! I'll try that. Cheers

**Comment by qba667** [comment]
Fixed by updating TX module firmware. @vandusinae  already confirmed it is working.
