### ISSUE TITLE
Horus takes longer to turn on backlight at boot on 2.3.10

### ISSUE THREAD

**Issue by nmaggioni** [opentx/opentx#7998]
**Describe the bug**
Given that the active model has the [Hobby4life/GPSMap](https://github.com/Hobby4life/GPSMap) widget enabled on any page, my Horus X10S radio takes ~8s to boot (from pressing the power button to hearing the startup sound) after having updated to OTX 2.3.10; reflashing 2.3.9 brings back the shorter boot time of ~4s using the same widgets.

I have found no other widgets that cause this behavior and removing this one from the current model (or booting after having selected a model without such a widget enabled) makes the problem disappear. I'm creating an issue here since this behavior seems to be OTX-dependant rather than widget-dependant.

**To Reproduce**
1. Flash OTX 2.3.9 on an Horus X10 (or presumably an equivalent radio).
2. Configure the widget linked above on any page of the currently active model.
3. Power down the radio.
4. Power up the radio, notice usual boot time.
5. Flash OTX 2.3.10.
6. Upgrade SD contents as needed.
7. Power up the radio, notice longer boot time.

**Expected behavior**
Equivalent boot times between OTX 2.3.9 and 2.3.10.

**General information**
 - OpenTX version: 2.3.10 (_opentx-x10-flexr9m-lua-noheli-en-2.3.10-otx_)
 - Hardware: FrSky X10S
 - OpenTX Companion: 2.3.10 on Manjaro Linux

**Comment by 3djc** [comment]
There is absolutely no changes to the boot process, so what you are saying is really strange. Please include your OTX and full  SD content

**Comment by PD5DJ** [comment]
I have noticed booting time takes indeed up to almost 5 seconds longer since v2.3.10.

**Comment by 3djc** [comment]
It does not without your widget, so might be worth looking at what happens on your side

**Comment by PD5DJ** [comment]
I have to add, I have cleared the radio, and used a fresh SD download. (X10S) no widgets, everything blank.

**Comment by robustini** [comment]
I think it's quite normal, even with Yaapu it does the same thing.

**Comment by 3djc** [comment]
My total boot time with 2.3.10 on x10s is 3 seconds

**Comment by robustini** [comment]
Tested now, after turning on the tx I've the widget screen in exactly 7 seconds, with Yaapu the same.
The time of the splash image must obviously be considered.

**Comment by 3djc** [comment]
@robustini  'the same', you mean your boot time is the same between 2.3.9 and 2.3.10 ?

**Comment by nmaggioni** [comment]
@3djc I can reproduce the issue with the stock SD contents, the only change being having added @Hobby4life's widget files in the SD and having enabled it on a separate page for the current model. Having seen some changes related to LUA in the changelog, I would suppose that the prolonged boot time is a consequence of something else.

I will try to bisect the latest version's commmits in the next few days, that could help pinpoint the source of the problem.

**Comment by robustini** [comment]
> 
> 
> @robustini 'the same', you mean your boot time is the same between 2.3.9 and 2.3.10 ?

Yes!

**Comment by 3djc** [comment]
Ok so given yapuu is quite big, looks like something specific to GPSMap

**Comment by PD5DJ** [comment]
As I said, I have cleared my X10S, insert a fresh SD with the latest SD contents.
There is a significant longer boot time, then v2.3.9
I have noticed it too in the nightlies, but thought it was due testing version.

**Comment by 3djc** [comment]
That contradicts what everyone else says in this thread

**Comment by PD5DJ** [comment]
I know boot time is longer due bitmap loading of my widget.. but was never that "longer" as it is now.

Funny thing is, I dont use GPSMap myself on any of my TX at all at the moment.

**Comment by robustini** [comment]
Regardless of whether the boot is longer than a few seconds I think this is not a problem, simply an observation.
3 to 7 seconds doesn't change my life.
A fast boot could be useful only in case of "emergency mode", but it depends on which aircraft you are using, automatic with failsafe or manual management.
Another thing: watch out for the speed of the MicroSDs you use.
The ones that come with FrSky are tremendously slow, also in reading.

**Comment by 3djc** [comment]
Emergency mode is a very fast boot mode without ui, without lua , without sounds,...

**Comment by robustini** [comment]
> 
> 
> Emergency mode is a very fast boot mode without ui, without lua , without sounds,...

Exactly, problem solved.

**Comment by PD5DJ** [comment]
I myself have no problems with it, but I assume that the developers would really like to know what it can be. possibility is that it may cause problems in the future. who knows?

That it happened is now clear to me after only changing firmware. there was just a slight extra delay at startup.

Could it have to do with increasing the stack size? just a thought.

**Comment by 3djc** [comment]
Clearly, that’s why it is still opened. @nmaggioni offered to try to narrow down the issue, let’s see where it leads to.

**Comment by PD5DJ** [comment]
Let me know if testing is needed,, I have some spare horusses lying arround just for testing.

**Comment by nmaggioni** [comment]
035cc6c seems to be the curlprit: the radio indeed doesn't take longer to boot, the backlight just doesn't turn on anymore until eveything else is loaded.

Before:
1. Turn on the radio.
2. The backlight turns on in ~4s and the splash screen is shown.
3. After another ~4s the startup sound is played.
4. The radio is now useable.

After:
1. Turn on the radio.
2. The backlight stays off for ~8s. If carefully looked at, the screen shows the splash screen in the meantime.
3. The backlight turns on and the startup sound is immediately played.
4. The radio is now useable.

There is no difference between overall boot times (intended from radio off to useable).

**Comment by 3djc** [comment]
Ok, thanks a lot for your investigation @nmaggioni ! Closing it then

**Comment by nmaggioni** [comment]
@3djc Please keep this open, I'll look into reverting to the old behavior without breaking the backlight function.

**Comment by 3djc** [comment]
It is done already, try with a nightly

**Comment by nmaggioni** [comment]
Excellent, I didn't check them since opening this issue! Thanks a lot.

**Comment by PD5DJ** [comment]
I have just tested it with the latest nightly download, but I dont see any "improvent" in a faster boot time.. still the same "longer" boot time.

Also pulled and compiled just 15mins from now.. same result.
