### ISSUE TITLE
No Power Meter on X9D Plus 2019 SE - ACCESS

### ISSUE THREAD

**Issue by Jullibach** [opentx/opentx#8000]
Hello, I only got the Spectrum Analyser on my Radio, and it works fine, but I don't get a Tool for the Power Meter.
But all pages I was looking to, show a Power Meter option in the Tools menu of ACCESS Hardware.

Radio: Taranis X9D Plus 2019SE
Internal ISRM Module Version : 2.1.0 FCC 
Protokol: ACCESS

**Comment by 3djc** [comment]
I do not believe your radio does have this capability. @bsongis ?

**Comment by kilrah** [comment]
Power meter is a feature of only the X-Lite Pro, not of all ACCESS hardware
