### ISSUE TITLE
OpenTx Companion Update Problem

### ISSUE THREAD

**Issue by ahmad-kassem** [opentx/opentx#8004]
Dear All

I am trying to update my TX16S firmware using OpenTx Companion but I am unable to download the new firmware, each time I click Download and then Download firmware i get a popup message saying: Firmware update check failed.

I uninstalled and installed again companion 2.3.10 also I tried with another computer but still facing the same problem.

I attached a screenshot of the error.

thanks in advance.

![error screen](https://user-images.githubusercontent.com/71368418/95544341-8192e700-0a03-11eb-83fb-61ba15287d79.png)

**Comment by 3djc** [comment]
There is an issue withour SSL certificate renewal, will be fixed shortly

**Comment by 3djc** [comment]
Fixed, thanks for the report
