### ISSUE TITLE
Protocol V765 (Volantex)

### ISSUE THREAD

**Issue by Fean1** [opentx/opentx#8006]
Hi,

I am having rc planes from different brands, so I recently purchased the TX16s.

The Volantex rc planes are having annoyingly two protocols V761 which works fine with 400mm warbirds. But they also sell planes with the V765 protocol which is not supported by Radiomaster yet. There are loads of people out there who are having these Volantex V765 protocol planes. We already have these discussions on the Facebook usergroup, Volantex planes are selling planes in bulk and are extremely popular.

https://www.monkeyhobby.com/volantex-rc-ear403-5ch-receiver-with-gyro-for-rc-plane-76502-76801-76702-74701-74706-75706-75704/

How does a request work, is that been done here or should I go to Radiomaster, OpenTx or Volantex?

Thanks!

**Comment by 3djc** [comment]
Thats for multimodule (https://github.com/pascallanger/DIY-Multiprotocol-TX-Module)
