### ISSUE TITLE
TX16S Trainer problem

### ISSUE THREAD

**Issue by ahmad-kassem** [opentx/opentx#8009]
Dear All

After updating my TX16S to OpenTx 2.3.10, the trainer mode: Master/Serial has disappeared, any idea Why??

**Comment by 3djc** [comment]
You probably have no AUX port set to trainer

**Comment by ahmad-kassem** [comment]
how to solve this?

**Comment by 3djc** [comment]
like : set an AUX port to trainer ?

![image](https://user-images.githubusercontent.com/5167938/95588218-6cd64380-0a43-11eb-9ed9-c1a5314974cb.png)

**Comment by ahmad-kassem** [comment]
i found it, whey i set the serial port to sbus trainer, the option Mater/serial appears again.

**Comment by 3djc** [comment]
You can't set it to trainer if none of your port are set to trainer, quite logical IMHO

**Comment by ahmad-kassem** [comment]
another question, now in this mode the UART is set as an SBUS signal input, Right?

**Comment by 3djc** [comment]
Yes, but be carefull that this is TTL level (so non inverted, 3.3v)

**Comment by ahmad-kassem** [comment]
5V is not OK?

**Comment by 3djc** [comment]
yes, that port is 5v tolerant, but depending on your signal source, the inversion might be an issue

**Comment by ahmad-kassem** [comment]
I will be using an Jumper R1+ receiver, i will weld an non-inverted sbus output from the receiver pcb and i will use it as sbus input to the UART, and i will power the receiver from the UART 5V supply, will this work?

**Comment by 3djc** [comment]
yes

**Comment by ahmad-kassem** [comment]
very good, thanks a lot

**Comment by ahmad-kassem** [comment]
another question, on the Taranis x9d the external module pins can be used as an sbus input when the trainer is set to master/sbus, is this possible in TX16S?

**Comment by 3djc** [comment]
no

**Comment by ahmad-kassem** [comment]
ok thanks

**Comment by dakhnod** [comment]
@ahmad-kassem ok, so about the tx16s:
Can I just connect some sbus receiver to one of the serial ports, set Master/Serial and opentx will read the sbus input and convert that to trainer inputs?
Also, why is it not possible to use the pins on the back as sbus input?

**Comment by dakhnod** [comment]
sorry, meant to mention @3djc
