### ISSUE TITLE
Radiomaster TX16S brightness control on S2

### ISSUE THREAD

**Issue by SVEH88** [opentx/opentx#8011]
Is there a way to assign display brightness to S2 knob similarly to how I have Volume assigned to S1 knob?

**Comment by 3djc** [comment]
This site is to be used only to track OpenTX bug and new features. For usage support, please go to community sites like RCGroups or OpenRCforums

Yes in 2.3.10
![image](https://user-images.githubusercontent.com/5167938/95647471-01868300-0ad0-11eb-9ab5-3d10764e0eae.png)
