### ISSUE TITLE
Jumper T18 "No SD card" error after flashing 2.3.10

### ISSUE THREAD

**Issue by HannoKranzhoff** [opentx/opentx#8016]
When I flash my Jumper T18 with version 2.3.10 and write the SD card content 
the TX afterwards fails to boot and just displays "No SD card" (white text on black screen).

After reverting to the original firmware the TX works as expected again.

**To Reproduce**

- flash 2.3.10 on Jumper T18
- write SD content for T18 on SD card
- reboot

**General information**
- opentx-t18-lua-noheli-en version 2.3.10
- Hardware Jumper T18
- OpenTX Companion 2.3.10 stable, Oct. 6, 2020

**Comment by 3djc** [comment]
This is a know hardware defect of Jumper T18, hidden by factory installed firmware. Please contact your radio dealer, they should have received instructions from Jumper on how to fix this

**Comment by HannoKranzhoff** [comment]
Ok, thanks a bunch. Didn't know that.

**Comment by HannoKranzhoff** [comment]
Just got a reply from Jumper:
"You can download firmware here https://www.jumper-rc.com/download/t18-series/
Please update firmware to the one on our website."

The version available for download on their website is 2.3.8. :(

Does this mean I will always have to wait for Jumper to release new firmware versions?
What kind of hardware issue causes this issue?

**Comment by kilrah** [comment]
Bad soldering on the SD card holder. They were sending replacement motherboards to people with the issue initially but I guess they got tired of the expense caused by their poor QC... try your dealer instead.
