### ISSUE TITLE
Spektrum Telemetry

### ISSUE THREAD

**Issue by whasianben** [opentx/opentx#8026]
I have a Radiomaster TX16S that I have bound to a Spektrum 4649T receiver. I have tried to set up telemetry on it so I can get a voltage and current draw reading, but when I went to discover new sensors there were a ton of vague and misleading sensors. I was only able to use the voltage reading accurately but everything else for the most part was useless. Would it be at all possible to better adapt OpenTX to support Spektrum telemetry in this manner? It would also be nice to be able to use the telemetry on this radio to change Betaflight settings like VTX channel and PIDs.

**Comment by Dosh22** [comment]
I have the same problem with Spektrum 4650 receiver.

**Comment by 2pacsawyer** [comment]
Im also having the same issue with a Spektrum 4650. All I really care about is RSSI.

**Comment by 3djc** [comment]
Telemetry is handled by multimodule, and as far as I know, it forward most (all) sensors. Anyhow, this is more for multimodule than otx
