### ISSUE TITLE
Lua scripts (Yaapu, iNav,..) don't work in companion simulator on Mac.

### ISSUE THREAD

**Issue by TomGun87** [opentx/opentx#8038]
Dear OpenTx Team,

On MacOs Catalina and running latest versions of both companion as OpenTx 2.3.10,
the simulators for the TX's with color screens don't work with Lua scripts like Yaapu and iNav.
When any of these scripts is on the virtual "SD card", the simulator at first display's all folders when entering system page, then few seconds later all but 2 disappear (Spectrum (INT) & Spectrum (EXT) remain).
When trying to add a new Telemetry page and selecting any of the widgets, the Yaapu and iNav don't show.

After restarting the simulator the radio shows "STORAGE WARNING, Bad radio data". 

This bug only affects companion versions on MacOs, on Windows they work as expected.

Kind regards.

**Comment by gbine** [comment]
I can confrm that this behviour also exists in 2.3.11 on MacOS Mojave 10.14.6

**Comment by lshems** [comment]
Because of a different lua compiler in the Mac build?

**Comment by 3djc** [comment]
You can try the current nightly that are built in a very different way (https://github.com/opentx/opentx/releases/tag/nightly), but it looks to me like file access issues, but since none of us does have a mac...
