### ISSUE TITLE
X9D+ 2019SE OTX2.3.10 FrSky Tools SBEC Lua Error

### ISSUE THREAD

**Issue by pau33** [opentx/opentx#8046]
If I want to start Tools:SBEC, I get an Lua NiL comparison error.

You can see it in the TX but also in the Simulator.
A fix should not be too complicated.

All other toots at least start normally.

**Comment by PD5DJ** [comment]
When running the Frsky SBEC script, I get a warning message on line 266.

![screenshot_x9d+2019_20-10-20_11-02-28](https://user-images.githubusercontent.com/55426642/96564674-c51f0800-12c3-11eb-8af2-3f7c4e550674.png)

Please make a screenshot of your error.

More info is needed.

**Comment by pau33** [comment]
I get this message:
![image](https://user-images.githubusercontent.com/19154380/96634188-70f34280-131a-11eb-9749-c912cb45bf8c.png)

although the new neuron80 is connected (single SBEC the same):
![image](https://user-images.githubusercontent.com/19154380/96634321-9e3ff080-131a-11eb-9c6e-6f289ff0baab.png)

I addressed this also in the Frsky firmware forum, as it might  be an Frsky problem (I hope it is not related to the X9D).

It seems to be this line:
![image](https://user-images.githubusercontent.com/19154380/96634709-2faf6280-131b-11eb-842f-025b300a95d9.png)

**Comment by kreidler** [comment]
@pau33 Have you ever tried to delete the sensors and started a new search? Afterwards try LUA script again.

**Comment by pau33** [comment]
Thank You for the tip.
It work's. With a completely new model the  lua script for the neuron works.
With the exiting model it doesn't. Although all values form the neuron are visible in the telemetry and it's id seams not to interfere.
