### ISSUE TITLE
Companion: no "SP Power" flag for QX7 

### ISSUE THREAD

**Issue by Tiefflieger68** [opentx/opentx#8047]
in Companion there is no flag for "SP Power".
In the System Settings of the Radio it is available and works well.

**Comment by Tiefflieger68** [comment]
depends to QX7 Radios

**Comment by kilrah** [comment]
What radios have it in companion? I don't see it for any of them.

**Comment by Tiefflieger68** [comment]
no Radio have this funktion in Companion.
This feature is imho only available for Radios with external S.Port Connector. 
You are right, it is also not available in Companion for X10 Radio.

So this issue depends to all Radios with external S.Port Connector.

If I transfer the config of my QX7 to Conmpanion and back to the Radio, the Flag for "SP Power" is set to default (Auto).
So it would be great to have this funktion in Companion too.
