### ISSUE TITLE
MacOS Companion 2.3.10 - Curve labels missing

### ISSUE THREAD

**Issue by lthole** [opentx/opentx#8053]
**Describe the bug**
In MacOS Companion 2.3.10, the Curve number labels are missing. The coloured blocks are there, but no text labels 'Curve 1', 'Curve 2', etc.

**To Reproduce**
1. Go to Companion 2.3 in MacOS
2. Go to the Curves tab, and look for the curve identification labels

**Expected behavior**
Was expecting to see curve identification labels.

**Screenshots**
See below

**General information**
 - OpenTX version: 2.3.10
 - Hardware: n/a
 - OpenTX Companion (2.3.10 on MacOS Catalina on MacBook Pro 15"
<img width="954" alt="Screen Shot 2020-10-22 at 10 02 00 am" src="https://user-images.githubusercontent.com/26259987/96802727-f6c5d980-1451-11eb-946e-9d531e61c4e4.png">

![Screenshot 2020-10-22 102524](https://user-images.githubusercontent.com/26259987/96802852-44424680-1452-11eb-8ab1-b38a13b769b7.png)

)

**Comment by lthole** [comment]
The curve name labels are actually there, but they are the same colour as the background tiles. I found this by clicking on the Curves tab, and then changing the focus by clicking on the model in the .otx window.

**Comment by bigtwin** [comment]
I can confirm - this is still the same in 2.3.11 (on MacOS Mojave).
Text and background are simply the same color.
