### ISSUE TITLE
6p_x switch does not work with special functions

### ISSUE THREAD

**Issue by twistedwings** [opentx/opentx#8055]
6p_x switch assigned to a special function does nothing.

![image](https://user-images.githubusercontent.com/562809/97039826-5238ba00-156d-11eb-9c55-44d479dae04e.png)

Radiomaster TX16S
OpenTX 2.3.10

**Comment by 3djc** [comment]
Please, this site is only for otx bug reports. For community user support, please go to sites like rcgroups or openrcforum. You likely haven’t calibrated your 6p

**Comment by twistedwings** [comment]
I have calibrated my 6p.
It doesn't work on the radio nor in companion simulator.
