### ISSUE TITLE
Idle Trim Only and new trim switch selection (ver 2.3.10)

### ISSUE THREAD

**Issue by sande005** [opentx/opentx#8061]
A gotcha when using the new capability for "idle trim only" and cross trims in ver 2.3.10
If you define an alternate trim in Setup, but forget to also define the same alternative switch in Inputs, not only will the intended cross trim switch not work for throttle (obviously), but the conventional idle trim will now be reversed - it only affects the high end, not the idle side of output.

Or, if you define an alternative trim in Inputs, but don't also define it the same in Setup, you get reversed functionality out of whatever is defined in Inputs.

Setup and Inputs have to agree on what trim switch to use for "Idle Trim Only".

May be primarily an issue for users that want to use "idle trim only" who then inadvertently change the "Throttle trim switch" selection on the Setup page.

Tested in Companion only.

**Comment by 3djc** [comment]
To be added to the issue https://www.rcgroups.com/forums/showpost.php?p=45747595&postcount=3741
