### ISSUE TITLE
RadioMaster TX16S: There is no multirotor profile when creating a new model

### ISSUE THREAD

**Issue by IgorS102** [opentx/opentx#8067]
When adding/creating a new model, there is no profile for multirotor (quadrocopters) models, there is only a glider and an airplane to choose from, regardless of whether the noheli option is enabled or disabled when building the firmware in OpenTX Companion.

**General information**
 - OpenTX version: 2.3.9 and 2.3.10
 - Hardware: RadioMaster TX16S
 - OpenTX Companion 2.3.10 on Windows 10
![New model](https://user-images.githubusercontent.com/73647885/97576139-9580a600-1a0f-11eb-903e-f163bd3d6f10.jpg)

**Comment by 3djc** [comment]
Wizard are left to the community to create, seems like no one has seemed to bother, maybe because no two quad are the same, and most can be setup like planes

**Comment by IgorS102** [comment]
Did you decide to close because "most" are not concerned about it? This is called professional deformity. When an experienced person does not see the problems of an ordinary consumer. I'm new to this hobby and the lack of a pre-configured profile personally upsets me. A quadrocopter is not an airplane or a glider.

**Comment by IgorS102** [comment]
Did you decide to close because "most" are not concerned about it? This is called professional deformity. When an experienced person does not see the problems of an ordinary consumer. I'm new to this hobby and the lack of a pre-configured profile personally upsets me. A quadrocopter is not an airplane or a glider.

**Comment by kilrah** [comment]
Every multirotor flight controller software needs different settings, and said settings depend on what's been set up on the FC itself. 
There's nothing a wizard can reliably automate.
