### ISSUE TITLE
TBS Nano RX telemetry - only 10 sensors

### ISSUE THREAD

**Issue by Pavelnew1** [opentx/opentx#8078]
I am using OpenTX 2.3.10  on Radiomaster TX16S. Crossfire mini TX is plugged and bound with Nano RX, both have latest stable firmware installed. I am doing Discover new sensors in Model setup -> Telemetry, and only 10 sensors are discovered. I've contacted TBS support, checked every possible setting with them, switched to another Nano RX - nothing helped and only 10 sensors are discovered. Can this be a bug in OpenTX? What other information is required from my side?
Many thanks in advance.

**Comment by 3djc** [comment]
Are those by any chance the crsf own sensors and you are missing the fc ones ? Anyhow, OpenTX does not restrict any sensors, just a total limit of 40

**Comment by Pavelnew1** [comment]
I have checked multiple set up instructions and manuals - even when connecting just TBS mini TX and Nano RX the number of sensors discovered should be at least 14. I have for sure connected FC as well (Matek F411), but still the number of sensors is 10 only. Tried various firmware on TBS (downgrading, upgrading again) - same result. That is the reason for my message here - trying to see whether OpenTX can cut sensor discovery somehow...  Otherwise, not even sure what to check...

**Comment by 3djc** [comment]
Well not quite. A CRSF receiver connecter to nothing brings 9 sensors. Could you put a picture of your discovered sensors ?

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/98443143-bb8e0080-2109-11eb-8d91-9b694e3dfa64.png)

**Comment by Pavelnew1** [comment]
![image](https://user-images.githubusercontent.com/74102190/98443356-d4071680-211b-11eb-878a-add39c3f9fe6.png)

**Comment by Pavelnew1** [comment]
I do have the same (+ one more ANT)

**Comment by Pavelnew1** [comment]
However here is the link with 14 sensors: https://www.youtube.com/watch?v=0pihx42GtIs&ab_channel=RCVideoReviews

**Comment by 3djc** [comment]
Then there is no issue on our side, you have an issue with your FC telemetry connection, nothing OpenTX can help with I’m afraid

**Comment by Pavelnew1** [comment]
And the problem, that when I solder Nano RX to FC, I get the same number of sensors (after I do "Discover new sensors"

**Comment by 3djc** [comment]
Look at the video, he has capa and more, that coming from fc

**Comment by Pavelnew1** [comment]
OK, understood, thank you for your answers.
