### ISSUE TITLE
Voz femenina OpexTX 2.3.10

### ISSUE THREAD

**Issue by Vidorlp** [opentx/opentx#8079]
Hola, ¿seria posible descargar la voz femenina que viene para la version 2.3.10? hay muchas traducciones que estan mal y me gustaria corregirlas para despues compartirlas.

Gracias.

**Comment by 3djc** [comment]
English only please

**Comment by Vidorlp** [comment]
Hei, would it be possible to download the female voice in Spanish that comes for version 2.3.10? There are many translations that are wrong and I would like to correct them for later sharing.

Thank you.

**Comment by 3djc** [comment]
Have a look here : https://github.com/opentx/opentx/blob/2.3/radio/util/tts_es.py

Some guidance here : https://github.com/opentx/opentx/wiki/Flow-for-the-Translators

It is computer generated out of this. Closing this as this is not an issue, but you can keep posting if you need our help
