### ISSUE TITLE
Taranis QX7 Radio Setup

### ISSUE THREAD

**Issue by jinxster64** [opentx/opentx#8081]
I have updated my taranis qx7 with the right firmware and everything works right except for when i try to access the radio setup function by pressing and holding the page button. When i first turned on the Tx the first time i was able to access the radio setup but i made some changes in the setup and now i am unable to access the radio setup. I tried to reinstall the firmware and that did not work. is there another way to access the radio setup function besides pressing the page button and holding it for a couple seconds? I am at my wits end trying to figure this out and need help. Any suggestions will be greatly appreciated.
.

**Comment by 3djc** [comment]
There is nothing you can change in the settings that can prevent buttons to work. The only thing I can think of is a hardware issue on the switch that does not allow it to be maintained long enough

**Comment by jinxster64** [comment]
So how would i fix that issue?

**Comment by kilrah** [comment]
> except for when i try to access the radio setup function by pressing and holding the page button

Maybe becasue that is accessed by long MENU, not long PAGE?
