### ISSUE TITLE
RadioMaster TX16S Inputs Panel Curves Display Glitch Since 2.3.10

### ISSUE THREAD

**Issue by lm410700** [opentx/opentx#8084]
**Describe the bug**
On new and established models, on "inputs" screen, "live" crosshairs on graph showing control input always "trace" CV1 regardless of selected curve/func. Affects all (AETR) inputs. This DOES NOT affect radio channel output... just visual.. The outputs correctly follow black curve.

**To Reproduce**
1. Create a basic AETR new model (Plane, Yes, Next, One Aileron, Next, No Flaps, Next, One Elev, One Rud, Next, Create.)
2. Go to Model Edit.
3. Go to 'Curve' tab.
4. Click on 'CV1', edit and create a simple 5-point sawtooth (100-0-100-0-100) curve. (This step helps make issue obvious, although problem exists regardless)
5. Go to inputs tab, select edit on any Input (AETR) and move control. Observe the live crosshair trace follow CV1 just created instead of the black defined curve.
6. If you select other custom curves, then hold select on the curve name to enter curve "quick edit", then return, they will "take" and the "live trace" will follow them, but if you restart radio, the live trace will revert to follow CV1 again.

I have switched back and forth between 2.3.9 and 2.3.10 and the problems disappears, reappears respectively and repeatedly.

I have noticed that under 2.3.9 there are no live traces under the curve "quick edit" screen, but under 2.3.10 there are. Could the change be related to the glitch?

FYI, I have just started using OpenTX over the past two months so can't comment on any past behaviour.
This is my first Github bug report, so be nice if I'm doing anything wrong.

I can create a video showing problem if more explanation needed.

**Comment by kilrah** [comment]
Fixed in nightlies. https://github.com/opentx/opentx/pull/8057
