### ISSUE TITLE
FRSKY HORUS X10S XPRESS ACCESS (COMPLETELY BLACK SCREEN AFTER A MISTAKE INTRODUCING INCORRECT FILES...

### ISSUE THREAD

**Issue by Danielsvf** [opentx/opentx#8087]

**Comment by 3djc** [comment]
We are very sorry to hear what is happening to you, but this site on only to handle OpenTX bugs, which your situation obviously isn't. You should contact FrSky support or alternatively try on community supports sites like rcgroup or openrcforums

**Comment by Danielsvf** [comment]
Ok, thanks
