### ISSUE TITLE
Read potmeter's value before initalization

### ISSUE THREAD

**Issue by klmn-roland** [opentx/opentx#8088]
I have a potentiometer set to volume control in the global functions, but when I turn on the radio, the volume won't change to the potmeter's value until I move it. 
So for example the hello.wav will play on default volume until I move the potmeter (S2 in my case). 

I have the latest versions.
FrSky Taranis Q X7 Access

**Comment by kilrah** [comment]
hello.wav always plays at system set volume since it's launched before settings are loaded and evaluation of anything is started.

**Comment by klmn-roland** [comment]
Thanks for the answer. I guess you won't change this, maybe I'll make it myself.
