### ISSUE TITLE
curve editor bug (at uncommon curves)

### ISSUE THREAD

**Issue by FranzDurst** [opentx/opentx#8096]
When trying to create this curve
6 point (also with other nr of point), custom x
X: -100, +49, +50, +59, +60, +100          (Y doesn't matter)
or some other values of x, these values can not be set.
The problem seems to happen when some x values should be shifted quit a distance.
For example the original -60 x point can not be set above -20.
Defining this type of curve on Transmitter works.

**Comment by 3djc** [comment]
Please state version and enviroment used. Is it companion ? 2.3.10 ?

**Comment by kilrah** [comment]
Will be fixed in next nightly, in the meantime you can drag the points instead of typing values for X, that works.

**Comment by FranzDurst** [comment]
Companion 2.3.10 on Windows 10
Wow, that was fast!
Thx Developers
