### ISSUE TITLE
[Horus] S.Port output only outputs polling frames

### ISSUE THREAD

**Issue by lukas-hosek** [opentx/opentx#8105]
I have a setup connected like this:

S.Port on the R9M module (or on the Horus itself, doesn't matter) -> inverter -> PC serial in

![Horus](https://user-images.githubusercontent.com/47420264/99528230-48ed1280-299e-11eb-8e6f-779b83147646.jpg)

I'm only seeing polling frames (7E xx). I would expect full telemetry mirror.

Horus X10 Express running OpenTX 2.3.10
R9M 2019 module, 1.3.0 FLEX firmware

**Comment by 3djc** [comment]
Telemetry for ACCESS stuff is not using sport line, but is embedded in PXX2 lines. Not an OpenTX choice, thats how this hardware works

**Comment by brainbubblersbest** [comment]
This should be possible somehow with #8073 
The telemetry Sensors discovered in telemetry setup can be send out to the Serial? 
Can the (mode telemetry) send out old frsky d telemetry, even s.port Telemetry is in Use and send out by Mode (telemetry mirror) ?
