### ISSUE TITLE
Problem flashing reciver with .frsk firmware

### ISSUE THREAD

**Issue by Baggeman** [opentx/opentx#8111]
Hey!

I have an jumper t12 and am trying to flash new firmware to my R9mm OTA reciver as i cant get it to bind to the radio. The new firmware is .frsk but as i understand it, it should be .frk. Everytime i try to flash it via the module bay i just get an error.. anyone that knows what i can do?

Sorry for my bad english...

**Comment by kilrah** [comment]
This place is not for usage questions. Frsk is correct for the new receivers and should work on current OpenTX version.
