### ISSUE TITLE
Hissing noise on Jumper T18 speaker when lowered the screen brightness 

### ISSUE THREAD

**Issue by Altastaire** [opentx/opentx#8116]
Whenever on-screen brightness is lowered, there are hissing noise coming from the Jumper T18 speaker. 
If the brightest is high (>70%) the hissing noise is gone.

**Comment by 3djc** [comment]
Hardware related, nothing we can do software wise about that

**Comment by sfjuocekr** [comment]
Are you sure this is hardware related?

I noticed this behavior after flashing T18 builds to my TX18S, this does not happen with the stock RadioKing firmware.

I've been trying to contact them to release their sources, but all I'm getting from them is "we set this through to our tech blablabla".
