### ISSUE TITLE
Issues at SBUS output in external module bay with long output periods

### ISSUE THREAD

**Issue by Tiefflieger68** [opentx/opentx#8120]
find attached PDF doc with screenshots

[SBUS Issue.pdf](https://github.com/opentx/opentx/files/5592287/SBUS.Issue.pdf)

let me know if I should do any further tests

**Comment by 3djc** [comment]
Some seem to disagree with reducing max value : https://github.com/opentx/opentx/issues/7388

**Comment by Tiefflieger68** [comment]
#7388 describes the same problem.
But issue is closed. This is why I didn't found it in open issues before I've logged the new issue.

For my understanding it makes no sense to keep this "flip mode" alive. 
It's always danger to use a bug as feature......

**Comment by kilrah** [comment]
A limit needs to be added indeed.
