### ISSUE TITLE
Telemetry views not appearing on Jumper T12 Pro

### ISSUE THREAD

**Issue by jlindrud** [opentx/opentx#8131]
According to OpenTX docs, long pressing the "Page" button from any of the main views should bring up the telemetry views. This does not happen on my Jumper T12 Pro. I have configured telemetry and the radio is receiving valid telemetry data from my receiver (Frsky R-XSR), which I know because the telemetry values are being logged to the SD card. However I cannot get any telemetry views to come up.

When I long-press the Page button, rather than displaying the telemetry view, it switches to the model selection screen.

Same thing happens in the OpenTX Companion simulator as well.

I have updated firmware to latest (2.3.10), but it hasn't made a difference.

**Comment by 3djc** [comment]
T12 uses a 9x navigation, as such, telemtry view are accessible using long down. Also please be aware that this site is for bug tracking only. For usage questions, please go to community support area like rcgroups or openrcforum
