### ISSUE TITLE
[2.3.11 N385, RM TX12] - Cannot page between multiple telemetry screens

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#8133]
Cannot page between multiple telemetry screens on RadioMaster TX12

1. Go to Telemetry menu
2. Define screen 1 [I]Ail as num
3. Define screen 2 [I]Ail as bars
4. Exit, then press 'telemetry' button to display first telemetry screen.
5. Attempt to access second screen with **Page>** or **Page<**

Should show screen 2, but stays on screen 1.

Running:
 - OpenTX 2.3.11 N385 (also fails with factory provided firmware).
 - RadioMaster TX12

**Comment by 3djc** [comment]
Good catch. Fixed in tomorow nighlies

**Comment by RC-SOAR** [comment]
Working in N386 - many thanks :)
