### ISSUE TITLE
FrSky XM+ receiver unable to bind

### ISSUE THREAD

**Issue by oskarosa** [opentx/opentx#8134]
Original firmware as purchased: v.2.1.X , I was able to bind under internal: MULTI   FrSkyX2   D16. Green LED flickering and never turned steady-solid. Flickering dependent on TX16S antenna distance and position. Different angle on TX16S=loss of signal.
Successfully flashed to newest firmware v.2.1.2 and since then, unable to bind. Did a FrSky brick the receiver with the new firmware on purpose unable to be used across different TX manufacturers? Or is it a bug?
 - OpenTX version:  2.3.10 otx
 - Hardware: opentx-tx16s 
 - OpenTX Companion win10 2.3.10
multi -stm-serial-aetr-v1.3.1.77

**Comment by 3djc** [comment]
This place is for OpenTX bugs tracking, which your issues isn't. You might want to read about multi tuning : https://www.multi-module.org/using-the-module/frequency-tuning. Also there is a thread on RCG covering multi issues : https://www.rcgroups.com/forums/showthread.php?2165676-DIY-Multiprotocol-TX-Module/page1381
