### ISSUE TITLE
Vario "silent" broken

### ISSUE THREAD

**Issue by SHezinger** [opentx/opentx#8135]
I tried to set the center range (-0.5 to 0.5 m/s) of the Vario to silent which didn't work.
The plane is on the ground (VSpd 0.0m/s) and the Vario is still beeping.
The TX is receiving telemetry data from the RX (G-RX8) and all other function of the Vario are working fine.

Hardware 
 - OpenTX 2.3.10
 - Hardware X12s

**Comment by 3djc** [comment]
Can we have a video showing the telemetry setup screen ? Cannot replicate here

**Comment by SHezinger** [comment]
Sure, will post it when I am back home

**Comment by SHezinger** [comment]
I deleted all sensors. Searched again for new sensors and the problem was gone.
