### ISSUE TITLE
display problem on the input tab horus X10

### ISSUE THREAD

**Issue by janko813** [opentx/opentx#8139]
see the two screenshots. The problem is visible on the radio as well as on the companion simulator.
On version 2.3.09 the display is normal and on version 2.3.10 the reticle does not follow the curve.
![Version 2_3_10_c](https://user-images.githubusercontent.com/75564901/101277600-de1d4300-37b5-11eb-9cf7-d37528b7dab7.png)
![Version 2_3_09_c](https://user-images.githubusercontent.com/75564901/101277602-e2e1f700-37b5-11eb-8388-ea53f7fb611c.png)

**General information**
 - OpenTX version (e.g. 2.3.10)
 - Hardware (horus X10)
 - OpenTX Companion (e.g. 2.3.10)
![Version 2_3_09](https://user-images.githubusercontent.com/75564901/101277723-9b0f9f80-37b6-11eb-991d-531678e54840.png)
![version2_3_10](https://user-images.githubusercontent.com/75564901/101277724-9cd96300-37b6-11eb-85d1-4a49d0d2726c.png)

**Comment by 3djc** [comment]
Already fixed
