### ISSUE TITLE
Curves Reset/Delete Option 

### ISSUE THREAD

**Issue by Githubbachelor** [opentx/opentx#8140]
Hallo People
Is it possible to make an option for RESETTING builded Curves with an easy setting option? I mean easy delete CURVE?

**Comment by 3djc** [comment]
Like long enter then reset ???

**Comment by Githubbachelor** [comment]
Yes thats what I mean -Thank You

 

Von: 3djc <notifications@github.com> 
Gesendet: Montag, 7. Dezember 2020 08:35
An: opentx/opentx <opentx@noreply.github.com>
Cc: Githubbachelor <rcbachelor@t-online.de>; Author <author@noreply.github.com>
Betreff: Re: [opentx/opentx] Curves Reset/Delete Option (#8140)

 

Like long enter then reset ???
