### ISSUE TITLE
Timer and monitor not visible

### ISSUE THREAD

**Issue by jeanbatfr** [opentx/opentx#8157]
Hello, I have a problem on my brand new tx16s and no one on the internet seem to have the same problem : 

All the software firmwares ... are up to date

On the simulation AND on the radio I don't have the timer and the little monitor : 
![image](https://user-images.githubusercontent.com/23725373/101838131-626a2000-3b40-11eb-9bf8-809247262cc5.png)
Please someone can help me?

**Comment by kilrah** [comment]
You don't have SD card contents loaded.
