### ISSUE TITLE
X9D+ (before 2019) crashes when selecting trainermode "Master/Serial"

### ISSUE THREAD

**Issue by Tiefflieger68** [opentx/opentx#8159]
openTX 2.3.10 @ X9D+

if  "SBUS Trainer" is activated for serial port in hardware settings and selecting trainermode "Master/Serial" in model setup, the radio crashes and reboots in emergency mode.
Found the same description in issue #7027.
No matter if MPM is activated or not or if MPM is pluged or not.

**Comment by Tiefflieger68** [comment]
is it fixed in die latest Nighties ?
The issue is still present in 2.3.11N400

**Comment by 3djc** [comment]
@Tiefflieger68 please test tomorow

**Comment by Tiefflieger68** [comment]
will do tomorrow later the evening

**Comment by 3djc** [comment]
Thanks, please let us known both if it works or not 👍

**Comment by Tiefflieger68** [comment]
my Test Equipment

Radio X9D+ @ openTX 2.3.11N405
Receiver XM (connected to serial port in battery bay)

Settings:
"SBUS Trainer" selected at Radio Settings

Tests:
1:
select "Master/Serial" (Lehrer/Serial in my radio cause of German language pack)
CHECK - no reboot of radio

2:
unplug/plug receiver from/to serial port
CHECK - lost and recovery of trainer signal detected

3:
SBUS signal is correctly decoded?
Defined a mixer with source "TR1"
CHECK - Stick moves of slave radio is visable in Mixer Monitor

Everything seems working well !

**Comment by 3djc** [comment]
Cool ! Thanks for checking that :) Will be in 2.3.11 that should be released in the coming few days
