### ISSUE TITLE
Model Select Category Pagination Delay and Model Select Delay

### ISSUE THREAD

**Issue by jmxp69** [opentx/opentx#8163]
OpenTx 2.3.10
TX16s
9 Model Categories. 35 Models.
Occurs with stock sd card, class 4 and class 10. Current card is 8gb class 10 with 7.6gb free.

After boot
Press model select.
First 5 model categories are displayed on left.
Press page right to move down the list and when the category pagination is reached there is frequently (but not always) a substantial delay before the category list updates to show first non-displayed category.

Similar problem

After boot, long press jog dial.
Menu pops up immediately.
Press model select and there is frequently (but not always) a substantial delay before model select screen shows up.

**Comment by kilrah** [comment]
That's normal, takes time to load the model images. Make sure they're no bigger than necessary since that will make it a lot worse. Or if it bothers you that much, don't use any.
