### ISSUE TITLE
2.3.10 - Simulator does not work in Companion 

### ISSUE THREAD

**Issue by jsreimer** [opentx/opentx#8174]
Opentx 2.3.10 
Radio Jumper T16

Ever since I did the update to 2.3.10 the simulator doesn't work in Companion, just comes up with the warning "simulator for this  firmware is not yet available" . 

Thanks
Jeff

**Comment by 3djc** [comment]
Either your radio profile is wrong, or your firmware channel is. Please use community sites like rcgroups or openrcforum for support
