### ISSUE TITLE
Bluetooth name not changing when using telemetry 

### ISSUE THREAD

**Issue by craigywsm** [opentx/opentx#8175]
**Describe the bug**
Using x9d 2019 When using the Bluetooth feature and setting the name, does not change the broadcast name. When telemetry is selected

**To Reproduce**
1. Go to Hardware
2. Click on bluetooth and set as telemetry 
3. Scroll down to name
4. When searching bluetooth shows up as hello

**Expected behavior**
Bluetooth should show as set name

**Screenshots**
![20201221_194442](https://user-images.githubusercontent.com/40343747/102815976-28610f80-43c5-11eb-8892-73d7638bab1a.jpg)
![Screenshot_20201221-194505_Telemetry viewer](https://user-images.githubusercontent.com/40343747/102815995-3020b400-43c5-11eb-9ef7-9b97bd576874.jpg)

Actual behaviour 
Bluetooth name shows as hello
**General information**
 - OpenTX version (2.3.10)
 - Hardware (Frsky X9D+ 2019 )

**Comment by kilrah** [comment]
BT module issue, out of our control

**Comment by craigywsm** [comment]
@kilrah please can you elaborate?

**Comment by kilrah** [comment]
The firmware of the BT module isn't taking the name correctly.

**Comment by craigywsm** [comment]
@kilrah Thanks, is this that OpenTX do not know the proper AT Command to set the name or the AT command is being ignored?
Either way how do we link this issue awaiting for a response from Frsky ?

**Comment by kilrah** [comment]
They've known about it for a year but never addressed it.
