### ISSUE TITLE
INAV LUA menu no change the settings and leave it with Radiomaster TX16S

### ISSUE THREAD

**Issue by ollifisch** [opentx/opentx#8177]
I can do that with the Radiomaster TX16S
Call up INAV LUA menu with the left stick and scroll up and down within this munu by moving the right stick. Unfortunately it does not work with the right stick to change the values ​​and to leave the menu again. This is not a problem with the transmitter Jumper T16 and it is possible to change the settings in the INAV LUA menu with the right stick and to exit the menu again.
I tested it with the current openTX-version also with the last nightly version.

**Comment by 3djc** [comment]
Please contact the scripts author so they diagnose and determine if their script has issues or if we have an LUA issue. And then they can logon the issue with more details
