### ISSUE TITLE
No internalmulti

### ISSUE THREAD

**Issue by French6man4** [opentx/opentx#8179]
Download Opentx companion for Jumper T18.  don't see internalmulti check box?
as you aee it was on Jumper T16 program settings. Jumper T18 only have external multi settings.  I do something wrong?. I did try but no internal on Jumper T18 radio protocal  settings. Thank you for your time.

**Comment by 3djc** [comment]
T18 always comes with internal multi, so there is no need for a choice, it is always included in t18 otx
