### ISSUE TITLE
CH3 versus throttle input error

### ISSUE THREAD

**Issue by ccaputo001** [opentx/opentx#8185]
Within logical switches window when I choose an a>x function with a=CH3 and x=-99, my horus X10D does not follow the proper logic.  It appears to confuse the CH3 output with the throttle input/mixer and renders the logical switch TRUE when it fact the CH3 output is -100 (as a result of a special function designed to lock the throttle) and it should be FALSE.

**Comment by 3djc** [comment]
If your ch3 is brought to -100 as a result of using an override channel function, then it is to be expected. If you want your cut to actually affect channel mix valu, then it needs to be done at mixer level
