### ISSUE TITLE
INPUT edit screen with faulty movable cursor

### ISSUE THREAD

**Issue by ccaputo001** [opentx/opentx#8186]
I am using the latest opentx 2.3.10

When I am in the INPUT screen and choose to edit an input such as AILERON the white curve displayed on the right hand side is correct (shows proper end points, expo, etc), but the movable cursor ALWAYS follows path from (-100,0) to (100,100) without any attention to the actual curve.

**Comment by 3djc** [comment]
Already fixed in nightlies
