### ISSUE TITLE
Insert Logical switch in Companion causes incorrect SF

### ISSUE THREAD

**Issue by kreidler** [opentx/opentx#8187]
When inserting a logical switch often the switch condition of the Special Functions is affected. Insert function is available in Companion only.

**To Reproduce**
1. Add at least 2 LS
2. Add 2 SF with switch condition depending on the LS

3a, Insert new LS line between LS1 and LS2. So that LS2 is now LS3.
-> Switch condition in SF2 will be moved to FM0
Expected behavior: SF2 switch condition should be LS3

3b. Insert new LS line before LS1. So that LS1 is now LS2 and LS2 will be LS3.
-> Switch condition in SF1 will be moved to LS2 correctly. SF2 stuck on LS2
Expected behavior: SF2 switch condition should be LS3 also

Edit: Nearly same behavior when deleting lines.

- OpenTX Companion 2.3.10 with Radio Profile X9D+ 2019

**Comment by elecpower** [comment]
Confirmed it is an interface refresh bug. Closing and reopening the model will show the updated SFs.
