### ISSUE TITLE
Unknown Error when Flashing Taranis x9 Lite

### ISSUE THREAD

**Issue by SojournerrB** [opentx/opentx#8193]
When attempting to flash the FrSky 2.3.10 firmware onto my radio, I receive an error reading "Cannot write G://FIRMWARE.BIN (reason: Unknown error)"

Not sure if this is my issue, I am quite new to these kinds of things, or an issue with my software or hardware. Any ideas?

**Comment by kilrah** [comment]
This place is for bug reports, not user support.

Your radio probably isn't in bootloader mode.
