### ISSUE TITLE
Bars screen

### ISSUE THREAD

**Issue by RookFPV** [opentx/opentx#8199]
Taranis x9d+se
OTX 2.3.11

When I set the bars screen, the inscriptions are displayed badly in the top bar (they overlap)

**Comment by 3djc** [comment]
Can you be more specific ? looks ok here

![image](https://user-images.githubusercontent.com/5167938/104044261-5cb63780-51dd-11eb-88d3-301000090048.png)

**Comment by RookFPV** [comment]
This strange subtitle overlapped when I installed the firmware but as soon as I restarted the radio everything is ok. I'm sorry for the trouble

**Comment by 3djc** [comment]
Ok please reopen if it reappears
