### ISSUE TITLE
Range Check can be select when in RX mode of the Multimodule

### ISSUE THREAD

**Issue by wucke13** [opentx/opentx#8204]
**Describe the bug**
Using the internal Multimodule of a Radiomaster TX16S, in the Model setup, I can select the menu item for Range Check for the `FrSkyRX` mode. The menu item is not visible, but selectable. Pressing enter on it starts the `RSSI:` Screen.  

**To Reproduce**
1. Go to  `Model Setup`
2. Set `Mode` to `MULTI  FrSkyRX  RX`
3. Select `Bind`
4. Scroll down one click

**Expected behavior**
The selection moves from Bind to `RF Freq. fine tune` (without invisible `Range Check` menu item in between).

**Screenshots**
Between all of the screenshots I just scrolled down one element. Observe how no visibile menu item is selected in the second screenshot.

![screen-2021-01-10-132840](https://user-images.githubusercontent.com/20400405/104122929-5f816b80-5348-11eb-9ab5-6958df989928.png)
![screen-2021-01-10-132844](https://user-images.githubusercontent.com/20400405/104122930-601a0200-5348-11eb-920c-d51c703c9ea3.png)
![screen-2021-01-10-132847](https://user-images.githubusercontent.com/20400405/104122931-601a0200-5348-11eb-9aae-8d02b538fd11.png)

**General information**
 - OpenTX version 2.1.10-otx (7ac1ecb6)
 - Hardware Radiomaster TX16S Hall

**Comment by 3djc** [comment]
You  mean there is a hidden step ?

**Comment by 3djc** [comment]
ok, I can reproduce

**Comment by wucke13** [comment]
Perfect, thanks!
