### ISSUE TITLE
Binding beep keeps going in MULTI RX mode

### ISSUE THREAD

**Issue by wucke13** [opentx/opentx#8205]
**Describe the bug**
When I select the `MULTI  FrSkyRX  RX` protocol on internal multimodule, the bind sound does not stop after bind mode is deactivated again

**To Reproduce**
1. Open `MODEL SETUP`
2. Select `MULTI  FrSkyRX  RX`
3. Activate `Bind` mode, the bind mode is announced through repeating "beep-beep-beep" sounds
4. Deactivate `Bind` mode by pressing enter again on the menu item
5. The "beep-beep-beep" sound keeps going

**Expected behavior**
The "beep-beep-beep" stops after bind mode is deactivated

**General information**
 - OpenTX version 2.1.10-otx (7ac1ecb)
 - Hardware Radiomaster TX16S

**Comment by 3djc** [comment]
We are working with @pascallanger on this. Stay tuned

**Comment by 3djc** [comment]
Fixed in upcoming multi v1.3.1.98
