### ISSUE TITLE
Global persistent timer

### ISSUE THREAD

**Issue by dmmanson** [opentx/opentx#8207]
In release 2.3.11 the "statistics" page (previously available in 2.3.10) seems to be missing (or I can no longer find it). That page contained a value for a "global persistent timer." This information could be used to keep track of the total Tx "ON" time since the last battery charge. This feature was mentioned in Issue 4950.

**Comment by 3djc** [comment]
Radio type ?

**Comment by dmmanson** [comment]
FrSky X10S

**Comment by 3djc** [comment]
This hasn't changed. Long enter then statistics

**Comment by dmmanson** [comment]
Hmm.  Press "SYS" > PgUp/Dn to Info .  No cursor, no "Statistics"
Page name is
 "VERSION" with lines for FW, VERS, DATE, TIME, EEPR, OPTS

![20210110_154745 1](https://user-images.githubusercontent.com/77246115/104135219-bee97680-535c-11eb-96dc-9734df036f43.jpg)

**Comment by 3djc** [comment]
Where did I talk about SYS ???

**Comment by dmmanson** [comment]
You didn't talk about SYS.  My bad.  Let's leave it at that.
