### ISSUE TITLE
lcd.resetBacklightTimeout() do not work in function scripts if menu screen is aktiv

### ISSUE THREAD

**Issue by Storchy1** [opentx/opentx#8215]
i have tried to use lcd.resetBacklightTimeout() in an function script.
I want to reset the timeout if the Menu is entered with long press MDL or SYS Button.
Function script is called as Special function or global function.
i have a KeepAlive to a gvar variable, which is set by a widget script
The function script polls the KeepAlive, if it is dead call lcd.resetBacklightTimeout()
I think the  lcd.resetBacklightTimeout() is not called if any menu screen is active.
Is this circumstance possible to change, so that the lcd.resetBacklightTimeout() has functionality if menu screen is active

**General information**
 - OpenTX version 2.3.11
 - Hardware Horus X12s
 - OpenTX Companion  2.3

**Comment by kilrah** [comment]
Duplicate
