### ISSUE TITLE
Why is there no flysky protocol in my multi option(RadioMaster TX12 )

### ISSUE THREAD

**Issue by hahafather007** [opentx/opentx#8222]
My device is RadioMaster TX12(CC2500), I thought the problem was the firmware version, but I seemed to find the problem
![image](https://user-images.githubusercontent.com/23414420/104809245-be7d2f80-57e3-11eb-9b2e-3d8d56975ad0.png)

**Comment by 3djc** [comment]
AFHDS3 is included by defaut, and is NOT for multi, but for flysky AFHDS3  module
