### ISSUE TITLE
FrSky X (D16) Cloned_8 not showing up in multimodule (TX16S)

### ISSUE THREAD

**Issue by Fumes74** [opentx/opentx#8224]
I can't see "FrSky X (D16) - Cloned_8" on Radiomaster TX16S.
The option is not there but i can see "Cloned" and it works.
Running OpenTX 2.3.11 and Multimodule 1.3.1.92.

**Comment by Fumes74** [comment]
Any thoughts on this?
Asked Pascal from multi-module.org and he suggest the eventual bug is on the opentx side.

**Comment by 3djc** [comment]
Fixing it would require a complete rewrite of the multi handling and a incompatibility with existing setup, so this cannot be fixed before 2.4

**Comment by Fumes74** [comment]
Ah, alright.
Thank you for noticing it anyway, much appreciated.
