### ISSUE TITLE
Add telemetry screen widget to allow 480x272 jpg for use as "INFO / HELP" screens

### ISSUE THREAD

**Issue by jerryhprado** [opentx/opentx#8233]
This feature will allow the user to display 480x272 screens at the model level. Such a feature will provide useful static displays such as switch assignments, model specs, checklists etc. Please see attached. I use the modelbmp feature now although the limited resolution makes it difficult to read, it is still very valuable. 
![horus1](https://user-images.githubusercontent.com/895924/105053112-d2b46d00-5a2d-11eb-9f39-a12d96c74546.jpg)

**Comment by ds7060** [comment]
Yes, something to display things like this:


![iNav_Stick](https://user-images.githubusercontent.com/48708611/114449595-35547980-9bd5-11eb-9d5d-79c782ffae4d.png)

or 

![apakpcfbgfabmpem](https://user-images.githubusercontent.com/48708611/114449627-4309ff00-9bd5-11eb-967d-82608578d584.png)

Thank you
