### ISSUE TITLE
Jumper T18 doesn't connect to simulator

### ISSUE THREAD

**Issue by chucktilbury** [opentx/opentx#8240]
I updated to version 2.3.11 and the transmitter no longer connects to the simulator. The simulator can "see" the controller, but there are no stick inputs. The transmitter can still bind and send signal. This is 100% repeatable and the problem does not exist in version 2.3.10. 

Build options: ppmus, fairchoice, noheli, lua, flexr9rm

Simulator is Steam/LiftOff running under a fully updated MX Linux:
NAME="MX"
VERSION="19 (patito feo)"
ID="mx"
VERSION_ID="19"
PRETTY_NAME="MX 19 (patito feo)"
ANSI_COLOR="0;34"
HOME_URL="https://mxlinux.org"
BUG_REPORT_URL="https://mxlinux.org"
PRETTY_NAME="MX 19.3 patito feo"
DISTRIB_ID=MX
DISTRIB_RELEASE=19.3 
DISTRIB_CODENAME="patito feo"
DISTRIB_DESCRIPTION="MX 19.3 patito feo"
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Linux mx 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

**Comment by 3djc** [comment]
We made a change based on simulator manufacturer demand in 2.3.11 affecting USB vid/pid. No other change was done in that area. I guess you should contact liftoff tech support on the right process under linux/liftoff for the T18 to be re-added as a joystick
