### ISSUE TITLE
tx12 usb connection fail

### ISSUE THREAD

**Issue by askerix** [opentx/opentx#8242]
hi all, i bought a tx12 rc and my computers don't react when i connect it via usb.
  I've read about others who had to update their drivers but, to me, it doesn't even show up in device manager.
 It's like you don't connect it. Yet the tx12, just connected via usb, asks me whether to use it as a joystick or sdcard.
I've done dozens of combinations.
Can someone help me if I have to do some particular setting?
Thanks

**Comment by kilrah** [comment]
You're probably using a charge-only cable, try others.

**Comment by askerix** [comment]
Yuo were right and I not so smart.
Thanks a lot!

Il Dom 24 Gen 2021, 00:59 Andre Bernet <notifications@github.com> ha
scritto:
