### ISSUE TITLE
Change defauls position of switchs /allarm on the start up of the radio

### ISSUE THREAD

**Issue by fdapport** [opentx/opentx#8244]
**General information**
 - OpenTX version 2.3.10
 - Hardware Taranis Frsky X9D+

When I try to change the defaults switch alarm on the initial switch alarm setting I cannot change it on the Radio menu but only if I use companions software  on the PC.

How to reproduce the bug:
Go in the first screen of a model.
Try to change the setting on the Switch, in the pictures Switch A... Only 2 options are able to set,, switch on position arrow point high or NO check. Not sure if it is a bug but or I am not able to set it.

Second scenario:
When I try to do the same for the Sliders (LS, RS, S2, S1, motor stick) I am not able to set the position that I like to check in the initial switch/slider alarm check… 
How to reproduce the bug:
In a glider I have set a Butterfly on the Motor stick, when I switch on the radio I like to receive a Alarm if the stick is NOT in top position, same thinks If I have set others functionality (camber, flight mode) on LS or RS.

Please let me know if you need additional information
Franco

![20210124_101930](https://user-images.githubusercontent.com/42831968/105721107-8208ac80-5f24-11eb-9b18-f4c7870418d2.jpg)
![20210124_101917](https://user-images.githubusercontent.com/42831968/105721122-86cd6080-5f24-11eb-9333-9a11d19bd073.jpg)

**Comment by kilrah** [comment]
Long press enter when the entire line is selected will read how all switches should be.
