### ISSUE TITLE
Make the lua reference guide available as PDF

### ISSUE THREAD

**Issue by drtrigon** [opentx/opentx#8248]
Please make the lua reference guide [1] available as pdf for download. According to [2] this should be fairly simple.

[1] https://opentx.gitbooks.io/opentx-2-3-lua-reference-guide/content/
[2] https://docs.gitbook.com/features/pdf-export

**Comment by kilrah** [comment]
Was already on, but we are still on legacy gitbook which has apparently been deactivated now. Will have to see how to migrate.
