### ISSUE TITLE
Start on default model

### ISSUE THREAD

**Issue by sten1860** [opentx/opentx#8249]
It would be great for openTX to start on the default model selected rather than the last model which was selected. 

By doing this, we can turn the radio on to a default model, and not bind or power any external modules, then select the model we wish to use. 

We have model match, but to same external modules blasting out 1mW it would be best to start on a default (non bound) model. 

Thanks.

**Comment by bigtwin** [comment]
Actually ... I like it as it is. It's more often that I like to start with the model I had the last time, than to start with some other.
