### ISSUE TITLE
Companion overwrites timer setting.

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#8252]
In the Model Setup menu on the transmitter, there is a setting for the start of voice/beep countdown. However, this is missing in Companion (see screenshots). 

Also, if models and settings are saved using Companion, then written back to the transmitter, the setting is overwritten with a default value of 10. Steps to reproduce:

1. On the transmitter, create a new model
2. In the model setup menu, set a timer with beep, and start of countdown = 20
3. Using Companion, read all settings from radio, then write back to radio. The start of countdown is 10 instead of 20.

Setup
- OpenTX 2.3.11
- Horus X12S (also applies to other tx's)

![screenshot_x12s_21-01-26_10-37-43](https://user-images.githubusercontent.com/6317479/105834943-0d387f80-5fc3-11eb-9661-f6db31de88ae.png)

![2021-01-26_104055](https://user-images.githubusercontent.com/6317479/105835092-4375ff00-5fc3-11eb-9a76-caea040fe8d7.png)

**Comment by kilrah** [comment]
I wonder if anyone has ever used that feature since it's been like this since 2016, and the option has been missing on 128px radios since then as well...

**Comment by RC-SOAR** [comment]
It's a useful configuration option for sailplane flyers. The alternative is to read out timer values via special functions, but each value is accompanied by 'seconds' and it doesn't work well.  At the very least, it would be good if Companion didn't overwrite the tx setting.

**Comment by 3djc** [comment]
We agree, we where just shocked that this didn't get noticed earlier. Complete fix is on its way

**Comment by RC-SOAR** [comment]
Great - much appreciated as always :-)
