### ISSUE TITLE
Raspberry pi Pico?

### ISSUE THREAD

**Issue by Dracks** [opentx/opentx#8256]
hi, since arduino DIY support was dropped on 2.2 and the recent appearance of the raspberry pi pico, I was asking myself if it can be possible to port openTX to raspberry pi Pico. 

https://www.raspberrypi.org/documentation/pico/getting-started/

Thanks, 
Jaume.

**Comment by kilrah** [comment]
It's a pretty low end microcontroller and lacks too many things that are needed (only has 3 analog inputs for example). 
Makes no sense even trying to use that compared to existing devboards.
