### ISSUE TITLE
IRX4 won't boot unless model switched

### ISSUE THREAD

**Issue by cru774** [opentx/opentx#8263]
Created a new model in TX that uses external IRX4 module. Turn off TX, Turn on TX, module will not boot up. Select a different model, switch / select back - module boots up.

**Expected behavior**
Module boots up every time the TX is turned on.

**Screenshots**
![IMG_5967](https://user-images.githubusercontent.com/78266595/106359269-e30ff600-6311-11eb-9492-56144ad675af.jpg)

**General information**
IRX4 Lite firmware v1.3.2.12
OpenTX v2.3.11

**Comment by cru774** [comment]
By coincidence I narrowed the issue down. What you see in the video here - https://youtu.be/A7X70Z92Wy4 - is that by quickly clicking away the warnings (which I usually do), you can prevent the module from coming online entirely. If you select another model, switch back, the module comes online. Interestingly, if you wait a few seconds before clicking away the warnings, the module comes online on first try.

Not sure if someone is following this? Did I miss to provide required information?

Thanks a lot
Christian

**Comment by benlye** [comment]
This is a known problem with the original bootloader on the IRX Lite module.

Have you updated the bootloader?

**Comment by cru774** [comment]
Hi benlye, thank you for your reply. Honest answer: Yes, but I am unsure if it was successful. I am able to flash the module from the transmitter. I did flash with flash-multi, and the device shows up as DFU-device ever since. Is there a definitive way to tell, wether or not the boot-loader has been flashed?

I also followed all instructions on https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Compiling_STM32.md#download-the-multiprotocol-source-and-open-the-project with an FTDI adapter. That also did not succeed, as when uploading from Arduino IDE, the log stated that no module was found in Boot0 mode on COM6 (which was the port the adapter was connected to). 

So I not sure how to verify...

**Comment by benlye** [comment]
You can use Flash Multi to update the bootloader:
https://github.com/benlye/flash-multi#upgrade-module-bootloader

You need to write the firmware again after flashing the bootloader updater.

**Comment by cru774** [comment]
I did try flash-multi a few days ago, also attempting to flash the boot-loader. This is what is happening and where I am stuck:

![1](https://user-images.githubusercontent.com/78266595/107131210-c1e07400-68d4-11eb-8af7-f9c0fde62b5b.JPG)
![2](https://user-images.githubusercontent.com/78266595/107131211-c1e07400-68d4-11eb-9e0a-2e064e37e7aa.jpg)
![3](https://user-images.githubusercontent.com/78266595/107131213-c2790a80-68d4-11eb-8fd0-d46a4522e837.jpg)
![4](https://user-images.githubusercontent.com/78266595/107131214-c2790a80-68d4-11eb-8ad2-344fe619f773.JPG)
![5](https://user-images.githubusercontent.com/78266595/107131215-c311a100-68d4-11eb-8771-41f9e6c17b01.JPG)
![6](https://user-images.githubusercontent.com/78266595/107131252-09670000-68d5-11eb-8750-c96bcd407585.JPG)

**Comment by cru774** [comment]
Installing the USB-drivers from the flash-multi menu also fails...
![7](https://user-images.githubusercontent.com/78266595/107131268-2e5b7300-68d5-11eb-8cfa-0d3a0bb7a639.JPG)

**Comment by benlye** [comment]
Possibly the module's firmware is too new (does not have USB support) so the app is struggling because the matching bootloader is not installed.

Can you use your radio to downgrade the module firmware to v1.3.1.59, then try to update the bootloader (using Flash Multi) again?

The driver installation is a puzzle - what does the verbose output show?  Sometime the installer files get quarantined by antivirus software.  You may need to get that working, but first try without and see if the devices show up correctly when running the older firmware..

**Comment by benlye** [comment]
Also, if flashing / reading continues to fail please post the verbose logs.  

And lastly, make sure you have extracted *all* the file from the zip file, including the folder structure.  I'm wondering if the app can't find the tools where it expects them.

**Comment by cru774** [comment]
Thanks for your help, really appreciated. 

I did uninstall all drivers for this device, and ran flash-multi as admin. Installation of drivers succeeded, and I am now able to run "Flash Module Bootloader" from the menu. It succeeded, and I followed the instructions from the dialogue:

![8](https://user-images.githubusercontent.com/78266595/107132433-636cc300-68df-11eb-99c4-4ac488d05ef5.JPG)

I went ahead and downgraded to 1.3.1.59 successfully via transmitter. "Read Module" now works:
Reading MULTI-Module via native USB
Reading flash memory ... done

Multi Firmware Version:   1.3.1.59 (STM32F1)
Firmware Target:          STM32F103CB (128KB)
Expected Channel Order:   TAER
Telemetry Type:           OpenTX or erSkyTx (MULTI_TELEMETRY)
Invert Telemetry Enabled: True
Flash from Radio Enabled: True
Bootloader Enabled:       True
USB Serial Support:       True
Serial Debug Enabled:     False

EEPROM Global ID:         0x667A9B13

MULTI-Module read successfully


Verbose Output:

.\tools\dfu-util-multi.exe -a 2 -d 1EAF:0003 -U "C:\Users\cru\AppData\Local\Temp\tmp3E3.tmp" -v

dfu-util-multi 0.7

Copyright 2005-2008 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2012 Tormod Volden and Stefan Schmidt
Copyright 2020 Ben Lye
This program is Free Software and has ABSOLUTELY NO WARRANTY

This version of dfu-util has been modified for flashing an STM32 MULTI-Module. It is intended for use with Flash Multi.
Please report bugs to https://github.com/benlye/dfu-util-multi

Filter on vendor = 0x1eaf product = 0x0003
Opening DFU capable USB device... ID 1eaf:0003
Run-time device DFU version 0110
Found DFU: [1eaf:0003] devnum=0, cfg=1, intf=0, alt=2, name="STM32duino bootloader v1.0  Upload to Flash 0x8002000"
Claiming USB DFU Interface...
Setting Alternate Setting #2 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0110
Device returned transfer size 1024
bytes_per_hash=1024
Copying data from DFU device to PC
Starting upload: [########################################################################################################################] finished!
Received a total of 122880 bytes

**Comment by benlye** [comment]
OK, so now you have the latest bootloader installed you can update to the latest module firmware again and see if your original issue has gone away or remains...

**Comment by cru774** [comment]
So I did, and the process succeeded. However, the issue form my 2nd post still persists.

![10](https://user-images.githubusercontent.com/78266595/107132533-23f2a680-68e0-11eb-8178-b442f0848248.JPG)

**Comment by benlye** [comment]
> So I did, and the process succeeded. However, the issue form my 2nd post still persists.

Well that's unfortunate.  At least now we know that the problem isn't the old broken bootloader (which really does cause this issue on these modules).

**Comment by cru774** [comment]
Just to reiterate: The remaining issue is, that if I click away the throttle warning / switch warning too early, the module does not boot entirely, and goes offline. See the video.

If I am waiting a few seconds, then click it away, the module completes the boot-up. 

This is some weird race condition in conjunction with speech output or user dialogue handling in OpenTx, if I would have to make a very uneducated guess ;)

**Comment by cru774** [comment]
Even with the module booted up (green and red LED on constantly), I get no info in the Tx about it
![11](https://user-images.githubusercontent.com/78266595/107132722-be071e80-68e1-11eb-8510-8cb3c37cd41c.JPG)
