### ISSUE TITLE
Error al actualizar

### ISSUE THREAD

**Issue by Taes59** [opentx/opentx#8268]
Buenas tardes, soy nuevo en RC, compre Radio Master TX16S, y no puedo actualizarla.

![image](https://user-images.githubusercontent.com/78378202/106504963-f06ee100-64c7-11eb-8856-1d297c6c291a.png)

**Comment by 3djc** [comment]
English only please. Also this place is not for user support, but the track OpenTX bugs. For support, please go to community sites like rcgroups or openrcforum

**Comment by Taes59** [comment]
Gracias
