### ISSUE TITLE
Support PLAY_BACKGROUND flag in the LUA API "playFile(name)"

### ISSUE THREAD

**Issue by witon** [opentx/opentx#8269]
The LUA API "playFile(name)" or "playNumber(value, unit [, attributes])" can play only one sound in the same time.  A sound can't be played until the sound is finished which is played before.  But in some competition or training situations, the sound of important event notifications must be played at an accurate time, and some sounds such as flight time are played at the same time.

I have read the LUA API source of the radio,  the function "static int luaPlayFile(lua_State * L)" always passes the second parameter with 0 to "audioQueue.playFile((f), (flags), (id))". Is it possible to add a parameter to the LUA API "playFile(name)" to select the sound play at the background or foreground? It will enhance the LUA script's capability.

**Comment by Miami-Mike** [comment]
I would love to see that! It would greatly enhance my [Shepard Tone Vario](https://www.rcgroups.com/forums/showthread.php?3396569-The-Shepard-Tone-Vario), which is presently compromised by voice announcements.
