### ISSUE TITLE
Cannot bind R-XSR with QX7

### ISSUE THREAD

**Issue by Sebitalugano** [opentx/opentx#8270]
My taranis qx7 worked with an R-xsr receiver but after updating the internal module and the receiver I couldn't bind it anymore.
I returned the firmware to the previous versions and the only thing I get is that the red led blinks at the moment of binding and when turning on again the green that confirms the link is not fixed.
I took it to a technician but he says that everything is ok, it must be a software issue but he does not know the issue.
Has anyone had this problem and could solve it? I went through all of Youtube and found nothing.

This is my own video:
https://youtu.be/MQPIrBOQ7gs

**Comment by kilrah** [comment]
Binding and RF transmission issues with FrSky stuff are unrelated to OpenTX, they're pretty much always mismatches of RF module and RX firmware versions and variants.

**Comment by Sebitalugano** [comment]
Ok, can you send me the files please?

I try all posibilities downloaded from official pages, and don't have results.

Taranis QX7 & R-XSR

Hope you can help me, thank You

Cheers

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
