### ISSUE TITLE
Opentx 2.3.9

### ISSUE THREAD

**Issue by Eg681** [opentx/opentx#8287]
I'm trying to get into the yaapu sensors cfg page so I can add telemetry to yaapu maps, following github directions creating model_sensors_maps.lua in yaapu cfg page no joy, have tried many times I just get a page with no sensors, back on telemetry page I can see inav lua sensors. Is there a work around? This seems like a opentx issue, I get some information on yaapu maps time,RSS and gps coordinates. What could be going on here.

**Comment by kilrah** [comment]
We can't support 3rd party scripts, but you should start by updating OpenTX to current.

**Comment by Eg681** [comment]
Ok thanks
