### ISSUE TITLE
read and import losing channel output max

### ISSUE THREAD

**Issue by guillaumevaret** [opentx/opentx#8302]
only on companion 2.3.11, windows
I don't have the problem on previous version (2.3.9) 

When I read a model from the radio X10S express or from  a file, with a channel output max VG, its losing the VG info, converting it in 150%. The VG info on min is not lost.

**Comment by elecpower** [comment]
Unable to replicate using Companion only - On Windows 10 and Ubuntu 20 tested with Companion 2.3.11 a new X10S Express profile and new model. Changed sub-trim, min and max to different GVs. Closed and saved model file, reopened file and model, displayed GVs as saved.

**Comment by 3djc** [comment]
@guillaumevaret maybe you could provide said file ?

**Comment by guillaumevaret** [comment]
yes. And with a screen view of the difference before saving the file / after opening the file
![Sans-titre-2](https://user-images.githubusercontent.com/48926221/108592408-102e5200-736e-11eb-87fe-e11a089fb042.jpg)

[pb vg 11.zip](https://github.com/opentx/opentx/files/6014598/pb.vg.11.zip)

**Comment by elecpower** [comment]
Bug confirmed. Triggered by extended limits being selected in model setup.
Setting Min to a neg GV also triggers issue.
