### ISSUE TITLE
Mac: OpenTX Companion wants permission to listen for keystrokes from ALL applications

### ISSUE THREAD

**Issue by DavidJJ** [opentx/opentx#8304]
**Describe the bug**
MacOS Catalina and Big Sur

On first launch, OpenTX Companion requests permission to listen for keystrokes from all and any applications. 

**To Reproduce**
1. Go to OpenTX Companion Downloads
2. Click on Download latest version
3. Open application.
4. See permissions request dialog.

**Expected behavior**
I see no reason why the OpenTX companion software should need or want to listen to keystrokes meant for other applications.  Even if innocuous, this is something a keylogger would do.    

Denying the request does not seem to affect the application so the permission is not needed. 

**Screenshots**
![Keystroke_Receiving_and_OpenTX_Companion_2_3_12N440_-_Radio__Jumper_T-Lite_-_Profile__T-Lite](https://user-images.githubusercontent.com/911399/108083500-bf9aba00-7038-11eb-9bf8-7af49058d63e.png)

**General information**
 - OpenTX version (N440)
 - Hardware (e.g.Jumper T-Lite)
 - OpenTX Companion (e.g. 2.3.12 on MacOS)

**Comment by 3djc** [comment]
Clearly not a macOS expert by I seem to recall it is required for some of the simulator inputs

**Comment by kilrah** [comment]
It's required by the simulator for it to respond to keypresses without any text entry field and whether its window is in focus or not.

**Comment by DavidJJ** [comment]
Explanation given for behavior is enough to close the issue.
