### ISSUE TITLE
OpenTx Companion - Simulator for this firmware is not available

### ISSUE THREAD

**Issue by Hotfly100** [opentx/opentx#8308]
OpenTx Companion 2.3.11 Win10
QX7 radio with version 2.3.11 date: 2021-01-08

I get a 'Simulator for this firmware is not available' message when I select Simulate

Justin

**Comment by kilrah** [comment]
All good here, maybe reinstall companion, or you're running the wrong version.

**Comment by Hotfly100** [comment]
OK - will do - thanks for checking - Justin

Sent from Yahoo Mail on Android 
 
  On Thu, 18 Feb 2021 at 9:07, Andre Bernet<notifications@github.com> wrote:   


Closed #8308.
