### ISSUE TITLE
Wrong telemetry warning values in companion

### ISSUE THREAD

**Issue by drtrigon** [opentx/opentx#8310]
**Describe the bug**
The telemetry low and critical values of a model on the TX are not handeled correctly by companion. When reading the models with companion and going to the telemetry page I see just the default values of 45 and 42.

**To Reproduce**
1. On the TX on the telemetry page change the low and/or critical values to something other than (45 or 42)
2. Connect the TX to a PC and use companion to read the setting
3. Open the models telemetry page on companion

**Expected behavior**
Companion should use the values given in the model (by the TX).

**Screenshots**
(n/a)

**General information**
- OpenTX version: 2.3.9 (the one it came installed with)
- Hardware TX16S
- OpenTX Companion: 2.3.11

**Comment by elecpower** [comment]
Unable to replicate - Tested on Windows 10 with my TX16S with 2.3.11 firmware and Companion. Companion shows the RX adjusted values. Also tested changing values in Companion, saving model and re-opening and changed values shown.

**Comment by 3djc** [comment]
Cannot replicate either.

**Comment by drtrigon** [comment]
I use companion in linux, Kubuntu 20.04.

Tested again, I set low to 20 and critical to 15. When I look at the telemetry page I see 20 in both fields. So I have to correct the bug report, it does show one of the two values...

**Comment by elecpower** [comment]
Confirmed Companion ranges do not match radio.

**Comment by drtrigon** [comment]
Thanks a lot!
