### ISSUE TITLE
missing switch

### ISSUE THREAD

**Issue by hangarkat** [opentx/opentx#8316]
after updating taranis x9d+se 2019 to otx 2.3.11 switch SI is not available in inputs screen or under switches in flight modes screen

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/108602950-5357e780-73a5-11eb-868b-2a4e5bf0a2f7.png)

Is it defined ?

**Comment by hangarkat** [comment]
Thanks for your quick reply. That fixed the problem though i don't understand what happened; with previous updates this switch didn't disappear and i didn't seem to lose any other hardware???

Anyway, thank you!
