### ISSUE TITLE
Improve SD-card synchronisation texts. 

### ISSUE THREAD

**Issue by mrpraline** [opentx/opentx#8319]
Hello, 

Thanks for the great work on Opentx! 

I have noticed some of my fellow RC-modelers getting confused by the dialog that comes up when synchronizing the SD and like to propose an improvement in Companion.

Its says 'Local folder' and 'Radio folder' in the folder selections. This is fine. Maybe 'Companion' instead of 'Local' would be even better, but that's just a matter of opinion.
But then in the 'Sync direction' drop down it talks about: 'Source folder' and 'Destination folder'. This is confusing, it is not obvious what device is the destination and what is the source. The terms in this drop-down should correspond to names of the selection boxes directly above it.  So something like 'Both directions, Local to Radio folder first' and "Only from Local folder to Radio folder.

Keep up the good work!

OS: Linux, Windows.
Companion version 2.3.11.

**Comment by bigtwin** [comment]
Just to have this complete - its the same on MAC.
