### ISSUE TITLE
How can I change Channel Range

### ISSUE THREAD

**Issue by MartyHugh** [opentx/opentx#8322]
Once upon a time it was possible to reduce Channel Range from 1-16 to 1-8 to halve the latency.

This does not appear to work the same way now.  Only the starting channel can be selected and changed, and the end channel remains +16 channels away.

What am I missing ?

Thanks for reading,

**Comment by kilrah** [comment]
It completely depends on what module/protocol is used so you should say which of the many supported ones you're referring to.

**Comment by MartyHugh** [comment]
Yeah good point :-)

I am using FrSky X and FrSky X2, mainly in LBT 8 channel mode.

**Comment by 3djc** [comment]
So you are only sending 8ch, since thats the way multi works. 16 chan are sent to the multi module, but it sends over the air only 8 if you selected an 8ch mode

**Comment by MartyHugh** [comment]
Thanks for the explanation.

**Comment by 3djc** [comment]
If you want to reduce latency on a multi, you should investigate redpine protocol
