### ISSUE TITLE
Is it possible that OpenTX can have problems accessing External module

### ISSUE THREAD

**Issue by MartyHugh** [opentx/opentx#8330]
I am running two radiomaster TX16S each with a TBS Crossfire Micro.
They have identical models loaded, a mix of CrossFire and Frsky (internal LBT 8) loaded.
One model has all the Frsky models cloned from the other.
So to all intents and purposes they are identical.

I am seeing an intermittent fault with both, the chances of this being hardware are limited in that both radios behave in a similar way.

The fault is when I have a Crossfire (External RF) model loaded sometimes I get the "Waiting for Crossfire" warning in the LUA script, flashing indefinitely and the external module cannot be found.  The external module is powered up OK and binds straight away to the Crossfire Receiver, But the radio cannot communicate with it.

As I say, the fault is intermittent it works most of the time,  But when it does fail, the only thing which snaps it out of this failure mode is to switch the radio to a FrSky (i.e. internal RF) model, and then switch back to the Crossfire (External RF) module. Then the LUA script can see the External module.

This problem is not specific to the LUA script because it also happens with TBS Agent Lite, i.e. when the fault is present it cannot find any devices.

The fact that this reset works every time makes me wonder whether this is a software logic issue.

I would be grateful for any insights on what the cause might be, or whether there are any known or suspected problems switching between Internal and External modes.

I am running OpenTX 2.3.11 on both radios, although I do remember seeing this with an earlier version.
One of the radios is brand new, the other only 6 months old.

Thanks for reading.

**Comment by 3djc** [comment]
Could you try nigthlies ? Think we fixed it already

**Comment by MartyHugh** [comment]
Thanks 3djc - will do.

Can you explain the cause of the problem so I can verify it fits my symptoms.

Thanks

**Comment by MartyHugh** [comment]
Slightly awkward.... I have installed 2.3.12N448 companion.  How do I install firmware later than 2.3.11?  That is the latest the companion will download.  Is there a nightly option within companion somewhere ?

Thanks

**Comment by 3djc** [comment]
You need to set your channel to nightlies in settings/settings/application settings (because we allow you to test nightly companion with release radio firmware if you so whish)

**Comment by MartyHugh** [comment]
Thanks. Doh!

**Comment by MartyHugh** [comment]
Ok I have one radio with 2.3.12N448 and one with 2.3.11.

Can not induce the problem so far.  As the problem is intermittent though, it is a bit difficult to prove conclusively that it is no longer a problem in the nightly build.

From the fix(es) that were done in this area, can you give me some idea of how I can induce the fault on 2.3.11 so I can then do the same on the nightly to show the fault is no longer present.

Thanks
