### ISSUE TITLE
Bootloader issue on MacBook

### ISSUE THREAD

**Issue by Gadget99** [opentx/opentx#8332]
I can not get the bootloader to work on my MacBook. There is a link to Zadig for a new usb driver (windows version) but not for the Mac. Does anyone know if one is available for the Mac or a work around to be able to use companion TX?

I am running the latest 2.3.11. I have also updated to the latest firmware but neither have resolved the bootloader issue. It still just boots normally.

My TX is a Radiomaster TX16s. Firmware OpenTX-t16. Version 2.3.11-otx (4328055e)

**Comment by 3djc** [comment]
> My TX is a Radiomaster **TX16s.** Firmware OpenTX-**t16**. Version 2.3.11-otx ([4328055]

**Comment by Gadget99** [comment]
Why was this closed?
