### ISSUE TITLE
No option in menu for failsafe 

### ISSUE THREAD

**Issue by Gadget99** [opentx/opentx#8340]
I am setting up my first model on a TX16s. I’m using a cheap and cheerful model that uses internal RF Multi V761. Under the menu there is no option for failsafe shown. Is this due to the RF I’m using or have I missed a setting out to show it?
I’m using 2.3.11.

![79449908-8A64-4ED3-8F09-EC7B85C0B855](https://user-images.githubusercontent.com/79744698/110202781-d62b7880-7e62-11eb-909f-c9fde02aaad6.jpeg)
![BB9AE72E-6B09-4CFB-94C2-7741C69E71CA](https://user-images.githubusercontent.com/79744698/110202786-d7f53c00-7e62-11eb-9dbe-93d05320f447.jpeg)

**Comment by 3djc** [comment]
Not all protocol allow failsafe settings on the radio. The information if supported or not comes from the multi directly, nothing we can do

**Comment by Gadget99** [comment]
Ok thanks for the confirmation
