### ISSUE TITLE
Feature request: Use MTP instead of USB mass storage for file transfers.

### ISSUE THREAD

**Issue by ThisIsMyNameBecauseEverythingIsTaken** [opentx/opentx#8342]
The problem:
USB mass storage requires exclusive access to the radio sd card.
When USB is plugged in the radio becomes effectively unusable.

The solution:
Switching to using MTP would allow shared access between the radio and the PC. In the future this would allow for further improvements like making a change in the companion software and instantly seeing the update in the radio.
It would also remove the need for "safe removal" and no risk of corrupting the sd card if the cable is accidentally unplugged during a write.

Why MTP and not some other file transfer protocol?
MTP is used by Android for file transfers and all major operating systems already support it, meaning no custom drivers would be needed.

**Comment by kilrah** [comment]
MTP is actually hot garbage and has very poor cross compatibility...

MSD isn't that great but MTP would certainly be worse...
