### ISSUE TITLE
[BUG?] Incorrect decoding of Gas Suite temps, residual percent and flow data?

### ISSUE THREAD

**Issue by pawelsky** [opentx/opentx#8343]
**Describe the bug**
According to FrSky S.Port protocol specification (version 3.4.7) following values are encoded on bits 0-15 only:
- Temperature1
- Temperature2
- Residual percent
- Flow
- Max flow
- Average flow

however OpenTx treats them as 32 bit values. This will cause displaying incorrect values if bits 16-31 are set to anything else than zeros for positive values or anything else than ones for negative values (e.g. for temperature). Is that a bug in OpenTx or FrSky spec? Has this been verified with an actual Gas Suite sensor sending negative temperature values?

**To Reproduce**
To reproduce the issue one needs to send temperature, residual percentage or flow data with e.g. 0x5555 in bits 16-31.

**Expected behavior**
Assuming FrSky spec is right data should be displayed correctly regardless of value of bits 16-31

**Screenshots**
Attached screenshot shows Temperature1 displayed as 65526 instead of -10 when 0x0000FFF6 is sent
![screenshot_1](https://user-images.githubusercontent.com/7121220/110250259-ae2f3880-7f7a-11eb-9df0-694c09c6cac2.png)

**General information**
 - OpenTX 2.3.10
 - Taranis X9D

**Comment by pawelsky** [comment]
Are there maybe any GasSuite owners here that could verify the displayed value for negative temperatures?

**Comment by pawelsky** [comment]
I was able to confirm that FrSky **does not** follow their own spec and GasSuite sends the mentioned values as 32 bits rather then 16 as specified. Here is an example logged communication with GasSuite (see the negative temp values):
```
7E 16 10 00 0D F4 FF FF FF ED 
7E 16 10 10 0D F7 FF FF FF DA 
7E 16 10 20 0D 00 00 00 00 C2 
7E 16 10 30 0D F8 02 00 00 B7 
7E 16 10 40 0D 4C 00 00 00 56 
7E 16 10 50 0D 00 00 00 00 92 
7E 16 10 60 0D 21 01 00 00 60 
7E 16 10 70 0D 54 00 00 00 1E 
```
This means that the OpenTX implementation will show correct values and this issue can be closed - at least until FrSky decides to start following own specifications ;)

**Comment by 3djc** [comment]
Thanks for your thoughrough checks !
