### ISSUE TITLE
When "Sensor Lost", SD Card log immediately changes schema, perhaps twice.

### ISSUE THREAD

**Issue by marked23** [opentx/opentx#8345]
FW    : opentx-x9d+2019
VERS : 2.3.7 (8b080683)
DATE : 2020-03-28 10:52:48
EEPR : 219

Internal Module
ISRM-S-X9
1.1.0/2.1.0FCC

Receiver
RX4R - ACCESS firmware v2.1.0

Receiving telemetry data from IKON2 (aka. BRAIN2) flight controller, over F.Port.  
CH-3 is a signaling port on the IKON2 that can talk F.Port (for telemetry) and S-Bus (for control) at the same time.
![RX4R_to_IKON2_FPort](https://user-images.githubusercontent.com/732793/110263981-10813c80-7f6d-11eb-9d63-64e3d12ee2a9.PNG)

**Description:**
An interruption in sensor telemetry data causes the log file to change schema.
Some on-board sensors (local to the RX) reset, causing a second schema change in the log file. 

**Repro steps:**
Establish a setup where:
1. The transmitter is set to log telemetry to the SD card (0.5s)
the RX4R is receiving sensor telemetry from an external device over F.Port
the RX4R is sending S-Bus commands to the external device over the same F.Port  
(In my case, this is the IKON2)
1. Do something to interrupt or invalidate the F.Port signal until the TX cries "Sensor Lost"
1. Restore whatever interruption, so that F.Port might resume sensor telemetry
Let this state continue for a minute, to give you a chance to repro the second schema change 
1. Power everything down
1. Review the logs on the SD card

**Observed:**
* When sensor data disappears, the related columns also disappear from the logs
in my case: Tmp1, FLR, A2, RSSI, RxBt, Tmp2, RPM, RB1C, RB2C, VFAS, Curr
* Some of those columns come back
RSSI, RxBt (and maybe RB2C, but I'm not sure)

_header line added for context_
![LogExample](https://user-images.githubusercontent.com/732793/110270319-6d372400-7f7a-11eb-886a-c85cc4b556e7.png)

**Expected:**
* When sensor telemetry data disappears, the log schema remains unchanged.
_(Some non-value serves as a placeholder for no-data csv columns)_
* When sensor telemetry data re-appears, the log schema remains unchanged.
* When new sensors are discovered, the log schema remains unchanged until the TX is power-cycled.
* When the TX is power-cycled, the available sensors are compared to the existing log file schema... 
* If there is a mismatch, a new log file is started with the new schema.

**Comment by kilrah** [comment]
First step would be to load current version and check the problem is still present, 2.3.7 is a year old.

**Comment by mpjf01** [comment]
Seems to be possibly related to #7752
