### ISSUE TITLE
Companion: DSM RX # 0 doesn't show its number on the models list. 

### ISSUE THREAD

**Issue by ManoDaSilva** [opentx/opentx#8348]
**Describe the bug**
This is a very minor, cosmetic bug: when opening my models, my first model using RX# 0 doesn't display its number on the list. All the others # are fine, but this one just doesn't show.

**To Reproduce**
1. Click on "add model", go through all the queries in the Wizard (doesn't matter what you specify).
2. Double click on your "New Model"
3. Specify "Internal" or "External" Radio Module, any protocol. 
4. Specify Receiver No 0.
2. The issue is (in)visible in the RX # column. Specifying any other number than 0 will show something.

**Expected behavior**
The ID number 0 should be visible in the RX# column.

**Screenshots**
Here's a screenshot of the situation:
![image](https://user-images.githubusercontent.com/13788521/110374772-5e6f7080-8051-11eb-8792-ae73cf59306a.png)

**General information**
 - OpenTX version 2.3.11
 - Jumper T16 Pro Hall V2
 - OpenTX Companion (2.3.11 Windows 10 1809)

Thank you for your work!

**Comment by 3djc** [comment]
Then many users will see plenty of 0, as it is default value. If I recall correctly we decided not to display 0 for that reason
