### ISSUE TITLE
Timer display collides with model picture when exceeding 99:99

### ISSUE THREAD

**Issue by AchimSto** [opentx/opentx#8350]
The display of a flight timer and a total flight timer together with the model picture works very fine until the total flight timer exceeds 99:99. Then it continues with 100:00 and the last digit is covered partially by the model picture.
I would expect that (every?) timer would change its (configurable) behaviour in this situation from mmm:ss to hh:mm.
Is this already implemented? I couldn't find any settings for this.

![20210309_092938](https://user-images.githubusercontent.com/42888187/110444023-db83ff80-80bc-11eb-88ed-9e274d1ed3f4.jpg)

**General information**
 - OpenTX version 2.3.10-otx
 - Hardware FrSky X10s express

**Comment by 3djc** [comment]
Use timer widget ?

**Comment by AchimSto** [comment]
> Use timer widget ?

Yes. I use the timer widgets and unfortunately I cannot change any settings according format or so. Do I have to create a widget by myself?

**Comment by 3djc** [comment]
Thats not the timer widget

**Comment by AchimSto** [comment]
> Thats not the timer widget

Oh! When I press the TELE button I enter the Main view 1 layout site. Here I can select the layout and several widgets. In "setup widgets" I can choose a timer widget und change its source an colour. Here it would be great if I could choose the time format when time exceeds 99:99.

**Comment by kilrah** [comment]
This is the "timer2" widget. You can display a timer 2 other ways, with Timer and Value widgets according to your preference.
