### ISSUE TITLE
Companion Diff Feature 

### ISSUE THREAD

**Issue by MartyHugh** [opentx/opentx#8355]
What would be nice would be to see what changes you have made since your last good backup
a) in case any unusual settings (e.g. bad trim setting) or indeed any setting which has been accidentally changed.
b) so that where a backup/cloned radio is being maintained, so that any valid changes can be checked before updating and synchronising

A nice solution would be the ability for Companion to be able to select any two .otx settings files (or in memory loaded settings files) and produce a diff summary of the differences between them.

Further functionality would allow changes to selected one at a time to copy one way or the other.

**Comment by elecpower** [comment]
@MartyHugh Companion has a Compare Models feature that colour highlights differences though not as compact as a diff.

**Comment by MartyHugh** [comment]
@elecpower thank you for replying, that feature looks useful.  

However. What would be nice would be to compare complete files though.
