### ISSUE TITLE
Frsky telemetry fw-option  not working on companion 2.1.9

### ISSUE THREAD

**Issue by njozsef** [opentx/opentx#8359]
Hi developers!
I modded old 9xr with stock board  w. M128 and frsky telemetry mod.

Frsky telemetry fw-compile-option checked but not working on companion 2.1.9
I try 9xr and m128 stock board.

after flashed, missing telemetry menu and not working two switch (due to rx tx modified pins)

Frsky and no frsky Hex-file is same. (except compiled timestamp)
maybe something happened to the backed compiler server

Please help.
Thank you.
Jozsef

**Comment by bigtwin** [comment]
Would it be the same on a current Version?
