### ISSUE TITLE
Battery, Volume and RSSI display with dark background in Flexi theme not visible

### ISSUE THREAD

**Issue by Fridolin1981** [opentx/opentx#8375]
**Describe the bug**
If the flexi theme on a color display transmitter is chosen and a dark background color is set, the display of the battery remaining battery capacity, the volume and the RSSI is not readable. The reason why is because the "shadow" of these displays in the top bar are black and therefore if a dark background color is chosen there is no contrast.

**To Reproduce**
1. Go to 'TELE'
2. Push long  'PgUp/Dn'
3. Scroll down to 'Theme'
4. Push 'ENT'
5. Scroll down to 'Flexi Theme'
6. Push 2x 'RTN'
7. Scroll down to 'Background color'
8. Push 'ENT'
9. Set R: to '0', G: to '0' and B: to '0'
10. Push 2x 'RET'

**Expected behavior**
Even if the battery is "empty" and RSSI is "0" it looks if the battery is full and the RSSI is 100%
**Screenshots**
![screenshot_Battery_Display](https://user-images.githubusercontent.com/72024078/111271698-d9c4b980-8631-11eb-81cf-040f45e7d778.jpg)

**General information**
 - OpenTX version 2.3.11
 - Hardware FrSky Horus X01S Express
 - OpenTX Companion 2.3.11

**Comment by Grinderman77** [comment]
The bug is still present in 2.3.15.
