### ISSUE TITLE
Gets stuck in MULTI Assan under MODEL SETUP

### ISSUE THREAD

**Issue by c0debreaker** [opentx/opentx#8377]
**Describe the bug**
It happens when using MULTI settings in External RF section in MODEL SETUP of my Jumper T16. Once I switch to MULTI then start choosing FrSky, before I can get to select FrSky, ASSAN shows up and I am unable to scroll thru selection anymore. It gets stuck in ASSAN. I have to exit and change MULTI back to OFF or any settings then MULTI settings again. I'd do the same process but I have to be extremely fast and accurate to get to FrSky. If I am slow, ASSAN will show up.

**Expected behavior**
Should be able to scroll thru different protocols and not get stuck in Assan

**Screenshots**
https://imgur.com/a/Yr4AyuN

**General information**
 - OpenTX 2.3.11-tbs version 
 - Jumper T16

**Comment by kilrah** [comment]
Likely need to update multiprotocol module firmware.

**Comment by c0debreaker** [comment]
Thank you @kilrah How do I do that?

**Comment by c0debreaker** [comment]
I found this, I'll watch it - https://www.youtube.com/watch?v=8fwU220sVKc

Oh, I've watched this and also followed the instructions. Maybe I installed wrong firmware last month

**Comment by c0debreaker** [comment]
I just finished updating it and it said on screen "FLASH SUCCESSFUL". I tried the process above again, it is not fixed. The issue still remains. Let me know if I should share a video.

I'd like to add that even when this issue is present, once I set to FrSky D8, I'll be able to fly my drone. However, in few days, it will be hard to arm the quad again. I will have to turn off multi and set it back to FrSky again. It's been a pain. This behavior didn't happen with the original Jumper T16 firmware.

**Comment by kilrah** [comment]
Try our builds instead of the TBS one.

**Comment by c0debreaker** [comment]
Looking at my Downloads folder, the file I used back in January 27 is `opentx-t16-lua-noheli-en-2.3.11-otx.bin`.

Which one are you referring to?

**Comment by kilrah** [comment]
Your initial post says "OpenTX 2.3.11-tbs version" so you have the special TBS build, download our version from companion.

**Comment by c0debreaker** [comment]
Ah, I see it on my screenshot too. Will I have to reconfigure everything again?

**Comment by kilrah** [comment]
No.

**Comment by c0debreaker** [comment]
Thank you. Everything is good now. The bug that was present in the TBS version didn't exist in your version. It also connects to the frsky receiver really quick now. Companion is cool. I used the write config to radio. It worked but there was no message. I think a message window must pop up so that users can be informed that writing to the radio was successful. I only knew that it worked when I rebooted my Jumper T16.
It's all good! Thanks a lot! 💪

**Comment by c0debreaker** [comment]
Oh maybe the reason I used TBS firmware was because of crsf shot. I'll check it later since it's 3:40am. I'll hit the bed now.

**Comment by c0debreaker** [comment]
How do I get crsf shot added with native OpenTX version?

**Comment by kilrah** [comment]
You wait until it's included.

**Comment by c0debreaker** [comment]
Got it. Is there an existing pull request?

**Comment by c0debreaker** [comment]
Please disregard my question. I checked https://github.com/opentx/opentx/pulls and looks like there is no existing pull request for crsfshot. My guess it might take a long time before this feature support gets merged into native OpenTX.

**Comment by kilrah** [comment]
It is planned to be included in 2.4, but yes that may be far away.

**Comment by c0debreaker** [comment]
Thank you.

**Comment by c0debreaker** [comment]
I honestly thought I won't be able to fly without crsfshot. However, I flew it today and didn't have issues at all. My quad was still very responsive. I didn't notice any latency. 😊
