### ISSUE TITLE
6 Position Switch in Companion Simulator delivers odd values

### ISSUE THREAD

**Issue by Papa-Echo** [opentx/opentx#8378]
I am using OpenTX 2.3.11 on a FrSky Horus X10S Express.
I program everything in Companion. When I simulate my Horus and use the 6 position switch with my mouse I get odd values. Usually the 6 position switch should deliver something like -100, -60, -20, 20, 60, 100. The mouse delivers all numbers between -100 and 100 in the Mixer. Can this be fixed?

**Comment by Storchy1** [comment]
You get better values, if you use the PgUp and PgDn on your keyboard instead of using the mouse. Just select the 6Pos with the mouse, you see a little blue ring and then use the keyboard
