### ISSUE TITLE
Main Views Settings from the Simulator are not transferred to the Radio

### ISSUE THREAD

**Issue by Papa-Echo** [opentx/opentx#8379]
I am using OpenTX 2.3.11 on a FrSky Horus X10S Express.
I program everything in Companion. When I simulate my Horus I also change Main Views settings. I just changed a widget in the top bar, but when I write my models to the radio these settings are not transferred. I can only change the main views on the Horus, directly.

**Comment by kilrah** [comment]
When you run the simulator in companion no change done in it is saved back to the file, it's preview only.

**Comment by Papa-Echo** [comment]
Can this be added in a future version?

**Comment by 3djc** [comment]
This is by design

**Comment by kilrah** [comment]
You can use the standalone simulator, that will alter the selected source.
