### ISSUE TITLE
Add DSM Forward Programming support for Spektrum AR630

### ISSUE THREAD

**Issue by Schaezard** [opentx/opentx#8398]
**Is your feature request related to a problem? Please describe.**
When I try to use the latest DSM Forward Programming Script with my Spektrum AR630 receiver, the configuration for failsafe etc. works fine. However the AS3X first time setup shows no text in the menu. Pressing the 'Next' Button does not seem to actually do anything.

**Describe the solution you'd like**
It seems to me like the Script is simply missing the correct translations for the return codes, the receiver is sending. So adding those should allow me to interact with the AS3X setup properly.

**Additional context**

![screen-2021-03-26-123409](https://user-images.githubusercontent.com/23404767/112618839-db0e9700-8e26-11eb-8371-b1dc048ef88c.png)
![screen-2021-03-26-123415](https://user-images.githubusercontent.com/23404767/112618842-dba72d80-8e26-11eb-9bd6-e1f7a28a84d5.png)
![screen-2021-03-26-123443](https://user-images.githubusercontent.com/23404767/112618843-dc3fc400-8e26-11eb-9e60-eff38e0ba1ce.png)

**Comment by 3djc** [comment]
You should direct this to multimodule, as OpenTX does not deal with this itself

@pascallanger so that you know :)

**Comment by Schaezard** [comment]
> You should direct this to multimodule, as OpenTX does not deal with this itself

My bad, I planned to do that and accidentally ended on the wrong github tab it seems ^^
