### ISSUE TITLE
Companion conversion GUI Close

### ISSUE THREAD

**Issue by Ga1j1n** [opentx/opentx#8403]
Companion force closes the GUI when opening an .otx model file and converting, this worked on a previous nightly (e.g N460 and earlier) in this case from a Jumper T16 to a T-Lite

Hardware Jumper T-Lite
latest nightly 2.3.12
Windows 10

**Comment by elecpower** [comment]
Unable to replicate with Jumper T16 profile, a new otx with one model and converting to T-Lite.
Successfully converted an old X9D+ otx containing multiple models to Radiomaster T16S to Jumper T-Lite.

Tested on Ubuntu 20.04 Companion 2.3.12
