### ISSUE TITLE
Vario programming under Open-TX

### ISSUE THREAD

**Issue by Basti77** [opentx/opentx#8404]
Servus,
maybe someone can help me.
I am trying to set up the vario of the g-rx8 receiver in the transmitter (XLite, current openTX). 
I get it to announce altitude to me on/above a switch, but not the classic beep beep with the change in frequency to delta V.
The option about special function on a switch "Vario" generates only constant beep beep.

**https://www.youtube.com/watch?v=tgvnFrSuKg8**
I have only found this example video.
he has much more options on his taranis under telmetry.
the center and range options are missing for me.

**Comment by kilrah** [comment]
They are here and Source needs to be set to Vspd.

![screenshot_xlite_21-03-30_22-41-01](https://user-images.githubusercontent.com/6065069/113053859-130c3600-91a9-11eb-85a7-256299a05484.png)

**Comment by Basti77** [comment]
thank you very much. 
it works now.
I think I have not found the place because the numbering of the menus is not correct. 
So far I have not missed anything, but what can be missing with me so that with me 12 is 13.
![DSC_0448](https://user-images.githubusercontent.com/8112783/113302760-ac019500-9300-11eb-81e5-5caba4cf1feb.JPG)
