### ISSUE TITLE
script error 

### ISSUE THREAD

**Issue by kiwi41000** [opentx/opentx#8407]
operating a frsky taranis x9d+ 2019  opentx 2.3.11 While trying to use the frsky sbec function I'm getting Script syntax error attempt to compare number with nil. Dan

**Comment by elecpower** [comment]
@kiwi41000 I took the liberty to remove the template text from your issue.

**Comment by elecpower** [comment]
@kiwi41000 does the script crash almost immediately or does it display information or menu and crash after a selection?

**Comment by kiwi41000** [comment]
Upon opening of the program for the SBec voltage adjustment Lua script it fails immediately

**Comment by kilrah** [comment]
Make sure you get the current script version, there have been old broken ones around. Also I believe you need to have discovered sensors from the ESC before launching.

**Comment by kiwi41000** [comment]
This is with the Tranus 2019 in D 16 mode to an x receiver and I have re-loaded the software three or four times just to make sure it’s correct. Might it work if I were using access protocol receiver.

**Comment by 3djc** [comment]
what esc ?

**Comment by kiwi41000** [comment]
Neuron 80 to a s8r but it works great with the Taranis x9d

**Comment by kiwi41000** [comment]
I have also updated the firmware several times and no good

**Comment by kiwi41000** [comment]
﻿
﻿
﻿
﻿Neuron 80 to a s8r but works good with the Taranis x9d

**Comment by kiwi41000** [comment]
Neuron 80 but works fine with the Taranis x9d

**Comment by kiwi41000** [comment]
Sorry if you need anymore information Ive been having problems with my email curious if you’re making any progress
