### ISSUE TITLE
Radiomaster TX12: sbus as input for trainer/master in JR module bay not working

### ISSUE THREAD

**Issue by Riffer** [opentx/opentx#8409]
Using sbus receiver as input device for does not work

1. Connect an already bound (to another TX) standard SBus-Receiver into JR Bay (beginning with the second pin from the bottom, GND, VCC, SIGNAL)
2. Power up TX12
4. Select Master/SBus in model settings (power for RX turns on)
5. Map incoming channels TR1 to TR8 to input and mixer
6. Show channels in the front end on TX12

**Expected behavior**
While moving trainer sticks on X9D plus the TX12 channels should show corresponding movements. 

**General information**
 - OpenTX version 2.3.11 and N470
 - Hardware TX12 (and X9D plus as sending device)
 - I ensured that this szenario works the other way around, where I used my X9D Plus as master/sbus and the TX12 as a trainer device.

**Comment by Riffer** [comment]
Is my expectation that I can use SBus as input in the JR bay wrong?

**Comment by 3djc** [comment]
Investigating your issue I stumbled into another one, which is that synced pulse has broken SBUS trainer...

**Comment by 3djc** [comment]
Ok, it turns out there was a software issue affecting nightlies that is being fixed.  It also appears there is a hardware design flaw on TX12 that prevent SBUS trainer to work. I found a fairly simple hardware fix, I'm talking with RM so they confirm (or not) my findings

**Comment by 3djc** [comment]
Here is what needs to be done for those who really need trainer from ext bay working (cppm or sbus)

![image](https://user-images.githubusercontent.com/5167938/116386049-b6d51a00-a819-11eb-9f3d-ee39c206043d.png)

![image](https://user-images.githubusercontent.com/5167938/116386174-d0766180-a819-11eb-949e-8748444a673c.png)

**Comment by Riffer** [comment]
![IMG_20210502_112913](https://user-images.githubusercontent.com/851325/116809852-a4701e80-ab40-11eb-9921-0489760edee4.jpg)

I guess I have a new problem and I do not know whom to ask, but you: The mainboard of my TX12 has "TX12S" on it, and comparing it with your picture I fail. I am not experienced in SMD electronics but I guess that item on the left is a capacitor while the right one is a resistor. The right group looks like the same as yours but the item on the left is not only much bigger but also a little bit moved. 

I hoped the update alone could help, but I guess even with this 'newer' version of the board struggles with SBus - so I think I need to solder the wire. But where... ?

**Comment by 3djc** [comment]
I have asked Radiomaster to supply the information about the right points for this mainboard

**Comment by 3djc** [comment]
Not the best picture ever, but here you go !
![image_2021_05_06T01_23_54_127Z](https://user-images.githubusercontent.com/5167938/117244411-3de94a00-ae39-11eb-94f9-e8617ff0176f.png)

**Comment by georgweb** [comment]
![TX12s V1 2](https://user-images.githubusercontent.com/97058963/147973447-c83e8475-06c3-444e-b477-ce95ed6e1c4d.jpg)
Done that, still no trainer function. I'm measuring approx. 10kΩ both ways on that tiny element on the right end of the cable - so I'm confident that my soldering worked out OK. Been using trainer function via XM+ rx in module bay of QX7s so I am also confident that I have indeed triple checked everything else. TX12s is on otx2.3.13.

**Comment by Riffer** [comment]
I am sorry for my late response, but must agree, that mod didn't work for me either.

**Comment by leofelipelf** [comment]
> ![IMG_20210502_112913](https://user-images.githubusercontent.com/851325/116809852-a4701e80-ab40-11eb-9921-0489760edee4.jpg)
> 
> I guess I have a new problem and I do not know whom to ask, but you: The mainboard of my TX12 has "TX12S" on it, and comparing it with your picture I fail. I am not experienced in SMD electronics but I guess that item on the left is a capacitor while the right one is a resistor. The right group looks like the same as yours but the item on the left is not only much bigger but also a little bit moved.
> 
> I hoped the update alone could help, but I guess even with this 'newer' version of the board struggles with SBus - so I think I need to solder the wire. But where... ?

**Comment by leofelipelf** [comment]
> ![IMG_20210502_112913](https://user-images.githubusercontent.com/851325/116809852-a4701e80-ab40-11eb-9921-0489760edee4.jpg)
> 
> I guess I have a new problem and I do not know whom to ask, but you: The mainboard of my TX12 has "TX12S" on it, and comparing it with your picture I fail. I am not experienced in SMD electronics but I guess that item on the left is a capacitor while the right one is a resistor. The right group looks like the same as yours but the item on the left is not only much bigger but also a little bit moved.
> 
> I hoped the update alone could help, but I guess even with this 'newer' version of the board struggles with SBus - so I think I need to solder the wire. But where... ?

Hi, Riffer! Sorry comment in this post. But i really need help to identify a component. Could you help me please?
![Radiomaster tx12s 12 2](https://user-images.githubusercontent.com/8193622/230647953-dfc92fc4-38aa-4f8a-8576-0097bd90c4be.jpg)

**Comment by Riffer** [comment]
I am sorry, can't help.

Maybe @3djc ?

**Comment by leofelipelf** [comment]
> I am sorry, can't help.
> 
> Maybe @3djc ?

Thanks, Riffer!
It's a try. Hope i could recovery. I just connect in the wrong voltage.
Look at this 🤦🏻‍♂️
![20230407_141404](https://user-images.githubusercontent.com/8193622/230663979-0d8e51fe-c2c6-49bb-bbf9-93373a096c96.jpg)

**Comment by sadovenko** [comment]
> > ![IMG_20210502_112913](https://user-images.githubusercontent.com/851325/116809852-a4701e80-ab40-11eb-9921-0489760edee4.jpg)
> > I guess I have a new problem and I do not know whom to ask, but you: The mainboard of my TX12 has "TX12S" on it, and comparing it with your picture I fail. I am not experienced in SMD electronics but I guess that item on the left is a capacitor while the right one is a resistor. The right group looks like the same as yours but the item on the left is not only much bigger but also a little bit moved.
> > I hoped the update alone could help, but I guess even with this 'newer' version of the board struggles with SBus - so I think I need to solder the wire. But where... ?
> 
> Hi, Riffer! Sorry comment in this post. But i really need help to identify a component. Could you help me please? ![Radiomaster tx12s 12 2](https://user-images.githubusercontent.com/8193622/230647953-dfc92fc4-38aa-4f8a-8576-0097bd90c4be.jpg)

Hello
Did you have a chance to identify the component?

**Comment by leofelipelf** [comment]
Hey!! Yes, the part number is CS5090E. In my case, i replaced it and it worked, hope it works for you too.

**Comment by rotorman** [comment]
CS5090E is a 2-cell Li-Ion/Li-Po charge controller IC. Has only to do with charging the radio battery and is not connected to main radio microcontroller and cannot influence or be influenced by the firmware of the radio.

**Comment by sadovenko** [comment]
Thank you very much
