### ISSUE TITLE
Radiomaster TX12: not all system screens respect contrast an font settings

### ISSUE THREAD

**Issue by Riffer** [opentx/opentx#8410]
Some screens at TX12 do not obey the contrast settings (and maybe font as well)

**To Reproduce**
1. Start system screens
2. Page through them

**Expected behavior**
All contrast and font should stay the same

**Screenshots**
![IMG_20210402_112638](https://user-images.githubusercontent.com/851325/113404363-57b1f000-93a8-11eb-8337-dbb0e8fe5f01.jpg)
![IMG_20210402_112656_1](https://user-images.githubusercontent.com/851325/113404369-58e31d00-93a8-11eb-8b92-9028289860bc.jpg)
![IMG_20210402_112705](https://user-images.githubusercontent.com/851325/113404371-597bb380-93a8-11eb-9561-a9beb0e18929.jpg)

**General information**
 - OpenTX version 2.3.11 and N470 with option sqt5font (DE)
 - Hardware Radiomaster TX12

**Comment by 3djc** [comment]
Nothing we can do about, hardware behavior

**Comment by Riffer** [comment]
Maybe my initial explanation was not clear enough.

All other screens are okay and only 2 single ones are caused by hardware behaviour? Not plausible to me.

If it happened randomly I might understand your statement, but that is not the case here. Why should the light or contrast change at all, when you page through any information at all? There must be code that changes the brightness or contrast values of the display.

**Comment by Riffer** [comment]
To show it more detailed I turned up the overall contrast - in this GIF you can see, that screens 4 and 7 are totally over contrast. 

![20210403_135126](https://user-images.githubusercontent.com/851325/113477732-43432580-9484-11eb-8ff8-87d3694aecba.gif)

Here is a link to the original: https://photos.app.goo.gl/z8kLyKYA12tfaEyT8

@3djc

**Comment by kilrah** [comment]
The LCD just has overall contrast that depends on what content is displayed, nothing we can do about that.

**Comment by Riffer** [comment]
@kilrah Thank you for the detail - so - if there were more text at the display the contrast wouldn't freak out? I will give it a try...
