### ISSUE TITLE
Radioking tx18s opentx support

### ISSUE THREAD

**Issue by marcus202** [opentx/opentx#8413]
Hello, I am a bit confused. So I bought this radio (Radioking tx18s) thinking it had the same opentx experience as all of the other ones, but it turns out that I can't update it because there are no official updates for this radio. It uses a custom opentx version, sadly it wasn't marked anywhere or I missed it because I didn't know what I was supposed to be looking for. Okay I'm new to this, but e.g. I want to set the flexr9m to on but since there is no official firmware for it, is it even possible?

Thank you in advance for answers:)

**Comment by 3djc** [comment]
This radio is not a supported OpenTX radio (https://www.open-tx.org/radios)

**Comment by marcus202** [comment]
Yeah, I know that now, but that's why I'm asking. Is it even possible to enable flexr9m on it?

**Comment by kilrah** [comment]
Believe it's basically identical to the T18, firmware for that might work.

**Comment by marcus202** [comment]
Yeah, I tried it but for some reason, my sticks wouldn't move.

**Comment by kilrah** [comment]
Then you should probably try to see if someone in the community found something, or contact the seller/manufacturer.
They never talked to us so we have no idea about that thing.

**Comment by marcus202** [comment]
Yep i already asked them:)

**Comment by Nich2245** [comment]
I'm not sure if this is the right place to ask, but I have a radio King tx18s, I purchased the radio when it first came out, haven't tried everything I could to make it work, now I can't even give it to power on the red lights just flash across the radio and then it goes off it won't even power on I have done something to the firmware and I don't know what I've done please help I don't know where to ask I've tried so many times asking so many people and nobody knows I would appreciate it if someone could please help me or give me an idea where you go I was stuck with manufacturer in there no help. Could someone please help me to get it operational again or let me know I where I can contact someone who can I would really appreciate it it's been so much trouble to fine someone that can help me. I believe it has bricked if that's the time to use.

**Comment by rotorman** [comment]
@Nich2245 as RadioKing TX18S is not a supported radio (not by OpenTX, nor by EdgeTX), you are a bit in a pickle with your radio choice.
Anyhow, as the mainboard of TX18S should be the same, or mostly the same, as Jumper T18, you can try to flash Jumper T18 firmware to it in DFU mode.
For this, download latest OpenTX Companion and install it on your computer.
Open Companion and set up a profile for Jumper T18.
Power off your TX18S and hook it up via USB to the computer - this will connect the radio in DFU mode that is required to fully flash the firmware of the radio in one go (bootloader and the firmware part).
Now try to download and flash the firmware via OpenTX Companion.
The flashing via DFU mode takes significant time (numerous minutes) - be patient. After flashing finishes, remove the USB cable and put OpenTX 2.3.15 SD card content of t18 to the SD card (get it here: https://downloads.open-tx.org/2.3/release/sdcard/opentx-t18/sdcard-480x272-2.3V0039.zip )
If all went smoothly, and your radio hw is not faulty, you should be greeted with a running system again.

If you have further questions, GitHub is a wrong place for this kind of non-developmental support - Discord would be better.
