### ISSUE TITLE
2.4 fails building under Win with GNU ARM v6-2017q2, but builds without errors with v7-2017-q4 and with v10-2020-q4

### ISSUE THREAD

**Issue by rotorman** [opentx/opentx#8417]
By experimenting with OpenTX 2.4, I noticed in [.travis.yml](https://github.com/opentx/opentx/blob/a3a375efc81e60ccc2bd48824729df31e66da3d0/.travis.yml#L37) that for v2.4, I should use GNU ARM Embedded toolchain in version [6-2017q2](https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads) (instead of 4.7-2013-q3, as previously for building OpenTX v2.3).

Unfortunately building firmware with v6-2017q2 under Windows (presently) fails, with:
```
[ 59%] Building C object radio/src/CMakeFiles/firmware.dir/thirdparty/Lua/src/lzio.c.obj
C:\Users\x\AppData\Local\Temp\ccabJoqb.s: Assembler messages:
C:\Users\x\AppData\Local\Temp\ccabJoqb.s: Warning: end of file in comment; newline inserted
C:\Users\x\AppData\Local\Temp\ccabJoqb.s: Error: open CFI at the end of file; missing .cfi_endproc directive
mingw32-make[3]: *** [radio\src\CMakeFiles\firmware.dir\build.make:1485: radio/src/CMakeFiles/firmware.dir/thirdparty/Lua/src/lundump.c.obj] Error 1
mingw32-make[3]: *** Waiting for unfinished jobs....
mingw32-make[3]: Leaving directory 'C:/opentx/build-24'
mingw32-make[2]: *** [CMakeFiles\Makefile2:405: radio/src/CMakeFiles/firmware.dir/all] Error 2
mingw32-make[2]: Leaving directory 'C:/opentx/build-24'
mingw32-make[1]: *** [CMakeFiles\Makefile2:412: radio/src/CMakeFiles/firmware.dir/rule] Error 2
mingw32-make[1]: Leaving directory 'C:/opentx/build-24'
mingw32-make: *** [Makefile:175: firmware] Error 2
mingw32-make: Leaving directory 'C:/opentx/build-24'
```

On the other hand, it builds fine with GNU ARM Toolchain v7 2017-q4 (also tried with latest, v10 2020-q4).

I tested both built firmware.elf's with [Segger's Ozone](https://www.segger.com/products/development-tools/ozone-j-link-debugger/) running with [J-Link connected to RM TX16S SWD-header](https://www.rcgroups.com/forums/showthread.php?3840595-Blog-4-Exploring-and-debugging-OpenTX-with-Qt-Creator-IDE-under-64-bit-Windows-10). Both run on the physical hardware (not perfect yet, but this is expected due to early nature of v2.4 presently. E.g. cannot access SYSTEM nor MODEL menu after successful sticks&pots calibration).

Please check/re-consider, if GNU ARM Toolchain v6-2017q2 is the best choice to go with.

**Comment by raphaelcoeffic** [comment]
@rotorman you should join us on discord for these kind of things ;-)
