### ISSUE TITLE
Widget source error

### ISSUE THREAD

**Issue by minzukas** [opentx/opentx#8431]
OpenTx 2.4
Radio Radiomaster Tx16s

Unable to select source when trying to change topbar widgets through widget settings. Roller seems to work fine in other menus, though when selecting source, always jumps to SC switch. I can select subgroup, f.e. telemetry, but when scrolling with roller it jumps to SC again. SC seems to work also fine. Any thought how to put RxBt or something else?

**Comment by 3djc** [comment]
2.4 is not yet available
