### ISSUE TITLE
Add swedish sound files

### ISSUE THREAD

**Issue by fgaafgb** [opentx/opentx#8439]
Attached in file
[sv.zip](https://github.com/opentx/opentx/files/6287745/sv.zip)

**Comment by 3djc** [comment]
That’s not how it works, if you want Swedish sounds, then the relevant code needs to be added to the TTS sound generation

**Comment by PD5DJ** [comment]
> Attached in file
> [sv.zip](https://github.com/opentx/opentx/files/6287745/sv.zip)

Did you generate these with TTS automate? if so.. can you share the TTS Automate file?
