### ISSUE TITLE
Taranis QX7 won't start when connected to USB

### ISSUE THREAD

**Issue by Noahdecoco74** [opentx/opentx#8449]
I've searched a bit on the internet and the only related problem is to charge the battery through usb.

When I want to start my QX7 I have to connect the battery and disconnect the USB cable. The controller won't start with either only the USB or the USB and the battery pluged in. 
When the controller is off and I connect the USB cable, windows tells me "STM32  BOOTLOADER" is plugged in.

I would like to be able to start my controller without having to plug-in and unplug the battery every time.

My controller is a QX7 ACCST under openTX 2.3.11
![image](https://user-images.githubusercontent.com/82590532/114876338-84c9be00-9dfe-11eb-9665-f77ba48ae0dc.png)

**Comment by 3djc** [comment]
This is done in hardware, nothing that can be done in software

**Comment by kilrah** [comment]
The radio will not start with USB connected, that's normal based on how the hardware is designed.
