### ISSUE TITLE
S-Port-Mirror for Taranis X9D+ 19 is missing

### ISSUE THREAD

**Issue by RMFPV** [opentx/opentx#8451]
**Describe the bug**

https://github.com/opentx/opentx/wiki/Taranis-IO-ports

This section includes OpenTX serial port settings that has S-Port-Mirror option.
S-Port-Mirror is not available in Hardware menu and anywhere else in fact.
There is a mistake somewhere then. 

**General information**
 - OpenTX version 2.3.11
 - Hardware Frsky X9D+ 2019

**Comment by 3djc** [comment]
The documentation you are refering to is for X9D and X9D+, not X9D+ 2019. The 2019 does not offer this

**Comment by RMFPV** [comment]
There is no other documentation. The difference is not described anywhere.

**Comment by 3djc** [comment]
I edited the doc before replaying to you, please refresh the doc page. While we try to help the community, we are not responsible for hardfware design of radio, that is manufacturers responsibility

**Comment by RMFPV** [comment]
Great! Thanks!

Does it mean no external BT support for Taranis 19?
That's killing.
