### ISSUE TITLE
Unexpected Termination of Companion on Converting an OTX File

### ISSUE THREAD

**Issue by Hartinger** [opentx/opentx#8466]
I am using Companion 2.3.11 with several Radio profiles, i.e. Taranis X9D+ 2019, Taranis X7S ACCESS and Horus X10S Express. As I have a number of models that I fly with different Radios, I do regular conversions of the otx files for comparison, harmonisation, etc. In this context, I noticed the following erroneous behaviour.

If I work in the profile for the Taranis X7S ACCESS, and then open a Taranis X9D+ 2019 otx file and confirm the file conversion, Companion terminates withour any pre-warning and without saving anything. This problem does not occur if I open a Horus X10S Express otx file in the X7S profile.
For testing I have generated a Taranis X9D+ 2019 otx file with only one simple model in it, and the problem still occurs. So it does not seem to be related to any specific model setup.

**Comment by elecpower** [comment]
On Win 10, I have tested on my model file converting from TX16S to X9D+ 2019 to X7S Access and no crash.
Also tested a X9D+ 2019 new file and wizard created model then converted to X7S Access and no crash.

@Hartinger what operating system and version are you using? Can you upload your simple X9D+ 2019 otx file so I can try and reproduce.

**Comment by Hartinger** [comment]
I am using Win 10 pro, here is the simple otx file (you need to remove the .txt suffix).
[Test.otx.txt](https://github.com/opentx/opentx/files/6367782/Test.otx.txt)

**Comment by elecpower** [comment]
@Hartinger thanks I can reproduce with your test file

**Comment by elecpower** [comment]
@Hartinger  when I load your test file the conversion message only says **X9D+** not **X9D+ 2019**. Here is the message when opening your test file. Can you please confirm what format the test file is in.

![test file conversion msg](https://user-images.githubusercontent.com/15316949/115925802-18695180-a4c5-11eb-9e9f-0703ef689a08.jpg)

**Comment by elecpower** [comment]
@Hartinger I have updated my previous post. I misread the msg. They are the same no matter whether X9D+ or X9D+ 2019.

**Comment by elecpower** [comment]
Cause: The conversion process does not know the radio variants for all the sub types. In this case the 2019 has one extra switch and if it is used in a model config the conversion crashes.

**Comment by Hartinger** [comment]
So we were very lucky that the simple model I used for testing includes the additional button SI. :-)
Good to hear you could find the cause, thanks a lot.
