### ISSUE TITLE
Missing repetition option for global/special function "play music" on RadioMaster TX12 - opentx 2.3.11

### ISSUE THREAD

**Issue by GoHardt** [opentx/opentx#8467]
There is no option of choosing the amount of repetitions of the special or global function "play music" on the Radiomaster TX12. This leads to the situation that the choosen sound keeps playing on repeat if the choosen switch is active.

1. Click "Sys" button
2. Scroll with 'page' to Page 4/7 "global functions"
3. Create function "PlayTrack" for any button and any sound
4. See error of missing repetition option.

A clear and concise description of what you expected to happen.:

There should be the counter of repetitions as shown in screenshot 1 for the option play sound (=german: Spiel Töne)

**Screenshots**
Spiel Töne = Play Sound
Spiel Musik = Play Track

![Screenshots](https://user-images.githubusercontent.com/55238005/115845408-1b126b00-a421-11eb-9e32-839df111c496.jpg)

**General information**
 - OpenTX version 2.3.11
 - Hardware: Radiomaster TX12
 - OpenTX Companion 2.3.11

**Comment by 3djc** [comment]
Isn't that by definition the difference between play track and play music ?

**Comment by GoHardt** [comment]
The german "Start Musik" is the equivilant for the english "play track". There is no option as play music according to the manual

![grafik](https://user-images.githubusercontent.com/55238005/115848662-6417ee80-a424-11eb-8725-fcddb64fc026.png)

Page 45-46
https://manuals.plus/wp-content/plugins/pdfjs-viewer-shortcode/pdfjs/web/viewer.php?file=/wp-content/sideloads/radiomaster-tx12-manual-optimized.pdf&dButton=true&pButton=true&oButton=false&sButton=true#zoom=auto&pagemode=none

**Comment by 3djc** [comment]
ok, then it is likely a translation issue, because play track does have it. Ins't "Spiel Musik" BGMusic" or something like that ?

![image](https://user-images.githubusercontent.com/5167938/115849895-a1c94700-a425-11eb-9adb-1e714f1cf8b5.png)

**Comment by GoHardt** [comment]
ok well. So i guess i need to swap to the english version. i also figured i can apply that option in companion. thanks :)
