### ISSUE TITLE
QX7 crashes when creating a new model - no icons, lua error

### ISSUE THREAD

**Issue by redjetvark** [opentx/opentx#8475]
No model icons display when creating a new model, scroll right is a second blank box, scroll again and tx crashes and restarts.
![PXL_20210427_221215930](https://user-images.githubusercontent.com/83316067/116319933-3c6fb000-a7af-11eb-9916-d4e9d9af0682.jpg)
![PXL_20210427_214307540](https://user-images.githubusercontent.com/83316067/116319935-3e397380-a7af-11eb-81b4-d7798304b6b7.jpg)

**Comment by 3djc** [comment]
Wrong sd content

**Comment by redjetvark** [comment]
thanks. a pretty clear PEBCAK error. thanks.
