### ISSUE TITLE
X Lite Pro Trim to Subtrim

### ISSUE THREAD

**Issue by SoaringJim1951** [opentx/opentx#8478]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**
On X-Lite PRO running OTX 2.3.11 and Bootloader 2.3.11. On Tx Outputs screen when Copy Trims to Subtrims is highlighted all Max and Min values in all Outputs are also highlighted. On selecting to Copy trims Max and Min values from Output 1 Copy to all other Outputs, destroying all previous settings.

**To Reproduce**
1. Go to 'Outputs Screen'
2. Click on 'Copy trims to Sub trims.'
3. All Max and Min values on all outputs are highlighted
4. Values from Output 1 are copied to Outputs 2-60

**Expected behavior**
Expected any physical trim positions to adjust subtrims

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - No equivalent fucnction on Companion. Running 2.3.11

**Comment by SoaringJim1951** [comment]
![IMG_20210502_142138](https://user-images.githubusercontent.com/25616915/117341177-b7b12000-ae99-11eb-9d89-e719f25c607e.jpg)

**Comment by SoaringJim1951** [comment]
Screenshot now attached

**Comment by SoaringJim1951** [comment]
I did nit mean to close this issue. It still exists.

**Comment by 3djc** [comment]
Could you try with a nightly ? I cannot reproduce

**Comment by bigtwin** [comment]
@SoaringJim1951 
I cannot reproduce as well. I have a _Taranis QX7_ and also 2.3.11.
_Copy Trim to SubTrim_ work as expected for all Outputs as well as for a single output.

However, I am not sure whether I understood your bug description correctly. May you try to explain more in detail? Or even provide a step-by-step instruction? Just to prevent misunderstandings.

**Comment by SoaringJim1951** [comment]
Hello
I have only seen this fault on the x-lite Pro. If you select the "copy
trims to subtrim" function on the end of the outputs screen it highlights
every max and Min entry from outputs 1 to 60. When you click on the
function it copies the max and Min values from output 1 to outputs 2-59. As
a result you have to do all your servo calibrations again. My previous
screen shot shows the situation.
I have only witnessed this on one example of the x-lite pro. My basic
x-lite behaves normally. On my Taranis you can see how the function should
behave.

**Comment by 3djc** [comment]
I did test on Xlite pro and cannot replicate with current version (nightly)

**Comment by SoaringJim1951** [comment]
Ok.
The tx belongs to a friend who is new to OTX. I am helping him to get
started. I will see him at the weekend. We will try a nightly and report
back. Maybe his download of 2.3.11 is corrupted.
Thanks for your attention to this.
