### ISSUE TITLE
Feature Request - Adjustable telemetry/sensor timeout 

### ISSUE THREAD

**Issue by AlessandroAU** [opentx/opentx#8481]
OpenTX will throw a "telemetry lost" audio warning after a certain amount of time a sensor has not been updated, it would be nice to have per-protocol adjustable parameter that controlled how long this timeout was before the audio was played to the user. 

Currently some protocols intentionally repeat stale telemetry values to avoid unnecessarily triggering the event and alarming the user.

**Comment by raphaelcoeffic** [comment]
Would this be a setting which is hard coded for each protocol, or is that a user setting?
ATM, we don’t have system wide protocol settings. This is rather per model, in the internal/external module settings.
