### ISSUE TITLE
Serial communication between DIY MEG2560 and multi protocol module

### ISSUE THREAD

**Issue by Rpi112** [opentx/opentx#8483]
I am trying to use 4 in 1 multi protocol module with DIY Mega 2560 in serial mode (so that I can select the module & protocol in openTx software directly). 

In the multi protocol module, Pin 1 is PPM/TX and Pin 5 is RX(Telemetry). Can I connect Mega2560 pins Telemetry_TX (PE1) and Telemetry_RX (PE0) to RF module pins 1 and 5 respectively and leave PPM_Out unconnected for using serial communication?

Also since only OpenTx 2.1 version supports Mega2560 does 2.1.9 version also supports serial communication?

Multi Protocol Module pins:
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/Transmitters.md

Thanks in advance for the help..

**Comment by kilrah** [comment]
There is no multi code in 2.1, so you'd have to write everything that's needed yourself.
