### ISSUE TITLE
TX16S Welcome to OpenTX is not play smoothly during power on cycle

### ISSUE THREAD

**Issue by richardclli** [opentx/opentx#8484]
Happens in TX16S.  The opening theme sound cannot play smoothly during power on cycle.  The problem seems the same as X12, need to wait for the chip fully initialized before playing.  I will provide a fix later.

**Comment by richardclli** [comment]
Already created a pull request.

**Comment by raphaelcoeffic** [comment]
Thx, I'll test ASAP.
