### ISSUE TITLE
The model cannot be moved in the Model selection screen.

### ISSUE THREAD

**Issue by mimicookie** [opentx/opentx#8488]
Transmitter: QX7, X9LiteS
Version: 2.3.12 N490

**Comment by 3djc** [comment]
You need to give us more details to understand what the issue is :)

**Comment by mimicookie** [comment]
Select a model in the MODELSEL screen, and try to move the position of the model with Move model from the pop-up menu display.
The model to be moved will not be selected and a blank model will be selected. If you press Enter at the destination, you will get a menu that allows you to create a new model or restore it.
I cannot move a model in the model select screen.
It works fine with X9D, X9D+, T12, and T-Lite.
