### ISSUE TITLE
2.4ghz ELRS Support for Radiomaster TX16 Internal multi module

### ISSUE THREAD

**Issue by evildronepilot** [opentx/opentx#8495]
Is it possible to get support for the internal multi-protocol module built into TX16.. radio?
Having the option to select the 2.4 ELRS and bind with, for example, ghost RX... would be a mind-blowing/game-changing feature even if we only have a low power lever available.

**Comment by 3djc** [comment]
Not sure what you are exactly referring to, but ghost rx use a modulation type not available in any of the 4  MPM chip

**Comment by evildronepilot** [comment]
> Not sure what you are exactly referring to, but ghost rx use a modulation type not available in any of the 4  MPM chip

Well, the idea is: 

The express LRS firmware is available for Ghost RX's so I hopped if the support for Express LRS could be added to the internal TX module this would make it possible to bind.... People willing to use thins options would then need to flash Express LRS on to the receivers and problem solved... 

What we are ending up with is:
Internal module using/running 2.4ghz Express LRS + Ghost RX (or any other supported by ExpressLRS receiver on that matter) running Express LRS.

**Comment by 3djc** [comment]
You would need to talk to the elrs team, but I belive this is not possible hardware wise

**Comment by davifelix** [comment]
Good morning.  resuming this discussion...... would it be possible to have an internal 2.4ghz elrs module instead of the 4in1 module?  in order to have the free bay for the 900mhz module.

**Comment by rotorman** [comment]
RadioMaster TX16S mkII is being sold with internal Express LRS option.

**Comment by davifelix** [comment]
yes I know...... What I would like to know is if it is possible to modify the tx16 with the elrs module of MKII....... Could it work? Or are they just different?

**Comment by rotorman** [comment]
Cannot follow unfortunately what you are asking - please try to rephrase. And also for such questions, best turn to OpenTX or EdgeTX Discord, as Github here is more for software/firmware developmental issues.

**Comment by davifelix** [comment]
scrivo in italiano così evito due traduzioni. vorrei sapere se la scheda lrs 2.4 della tx16s MARKII può essere montata su una tx16s normale, eliminando la scheda 4in1. grazie

**Comment by rotorman** [comment]
What you are asking is if TX16S mkII internal ExpressLRS module can be used in 1st generation TX16S - the answer is yes, it can. The mounting and the RF module connector of the internal RF module are the same between 1st gen. and mkII versions of TX16S.

**Comment by davifelix** [comment]
esatto!! è quello che volevo sapere. grazie mille! non devo modificare il firmware della radio giusto? o devo caricare una versione per mkII?

**Comment by rotorman** [comment]
If your 1st gen. TX16S is running a firmware that is new enough that it supports internal Express LRS, then no update is required, otherwise you need to update in order to use internal ExpressLRS.
In general, there might be other reasons to update as well, thus my recommendation would be to update your TX16S to the latest release version anyhow. For all further questions, please turn to OpenTX or EdgeTX Discord.
