### ISSUE TITLE
R9M Flex support broken 2.3.12N495 ?

### ISSUE THREAD

**Issue by menignulle** [opentx/opentx#8500]
Radiomaster TX16S Hall
Frsky R9M 2019 - non access
Frsky R9slim+ rx

Unable to bind to R9Slim+ after upgrading to 2.3.12N495
Running ok on 2.3.11 (2.3.11-otx (4328055e))

Variant 219(according to companion)

R9M fw: FW-R9M-ACCST-20190117 (Flex)

Tried back and forth, always works on 2.3.11
Cleaned SD card and put newest SD-Card content for nightly on there.(sdcard-480x272-2.3V0037)

Any anyone verify same result or give me some pointers ? 

Reason for upgrade is needing the LUA serialport working.

**Comment by 3djc** [comment]
Broken indeed
