### ISSUE TITLE
OTX 2.3.9 Switch SB does not function after exiting Analog Test screen.

### ISSUE THREAD

**Issue by RC-SOAR** [opentx/opentx#8502]
On the TX16S, after exiting the Analog Test screen, switch SB does not function. Normal operation is restored after power cycling the tx.

Steps to reproduce:
1. Create a blank model, no widgets.
2. Set SB as the source of CH1.
2. Open the Analog Test screen. Move controls around, and flick SB up and down.
4. Exit Analog Test screen
5. Open mixers monitor.

**Expected behavior**
Output of CH1 should vary with position of SB

**Actual behaviour**
Output of CH1 is fixed

**Other info**
This was first mentioned in [this RCG post](https://www.rcgroups.com/forums/showpost.php?p=47113687&postcount=1691), and I was able to reproduce the issue. It only applies to switch SB.

**Environment**
 - OpenTX version 2.3.9
 - Radiomaster TX16S

**Comment by 3djc** [comment]
update to lastest version ....
