### ISSUE TITLE
Horus X12S + OpenTX 2.3.11 + iNav Lua = Text/graphics Colour Change

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#8508]
Ok found a bug on opentx 2.3.11 & the inav Lua on the X12S. 

On the flexi or default theme, if text colour is anything other than black on a first widget screen with trims & sliders enabled, flicking between the inav Lua & back to the first widget screen changes text colour from white (on default) or user selected (on Flexi) to black.

**To Reproduce**
1. select theme default or flexi, 
2. change Text colour on flexi to anything other than black confirm & exit to 1st widget screen with sliders & trims on
3. flick over screen to iNav Lua on second widget screen then back to 1st widget screen
4. See error of graphics & text colour change to black even though theme set colour is anything but.

**Expected behavior**
colour of text & slider/trim graphics not to change colour

**General information**
 - OpenTX version 2.3.11
 - Hardware FRSKY X12S ACCESS
 - inav Lua 1.7.4

![IMG_0641](https://user-images.githubusercontent.com/84204457/118324133-ee261500-b501-11eb-904b-bf9f8a6c12a7.JPG)
![IMG_0639](https://user-images.githubusercontent.com/84204457/118324194-fd0cc780-b501-11eb-871b-f53f48edfa9e.JPG)
![IMG_0642D](https://user-images.githubusercontent.com/84204457/118324220-085ff300-b502-11eb-8476-22bbfc40cabd.JPG)

**Comment by 3djc** [comment]
Widgets have the ability to change colors, if they do not use it always properly, it is not otx responsibility.
