### ISSUE TITLE
Horus X12S Emergency Mode with oversize model image & inav Lua

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#8509]
Crashes OpenTX! Emergency Mode! Changing theme & theme colours multiple times on a model with iNav Lua running & oversized model image

**To Reproduce**
1. Select slightly oversize (pixel) model image
2. install & inav Lua 1.7.4 on second widget screen, display first widget screen with trims sliders, model image large right, timer 1 top left, battcheck bottom left.
3. change to different themes & change colour of flexi theme multiple times
4. OpenTx crashes putting tx into emergency mode - intermittent error

**Expected behavior**
not to crash OpenTX

**General information**
 - OpenTX version 2.3.11
 - Hardware FRSKY X12S ACCESS
 - iNav Lua 1.7.4
 

![IMG_0633](https://user-images.githubusercontent.com/84204457/118325297-9092c800-b503-11eb-929b-1296034022e8.JPG)

**Comment by raphaelcoeffic** [comment]
opentx 2.3 is missing proper clipping. Most of the time, when you write off screen, you will crash the radio.

**Comment by ghost** [comment]
Ah ok that'll explain it no doubt, it seems to be running better with correctly sized images now, however the over pixel size images would still display correctly in the model image box on screen giving no indication they were the incorrect size.

**Comment by raphaelcoeffic** [comment]
That is because the model widget resizes image to the correct size. Not sure the function is available in LUS.
