### ISSUE TITLE
Can only select RSSI warning from one receiver in a redundancy system

### ISSUE THREAD

**Issue by mpjf01** [opentx/opentx#8515]
The OpenTx telemetry setup screen (2.3.11 X9DP 2019) allows the user to select the source of the RSSI telemetry alarms. In a situation where two receivers are connected via SBUS (and SPORT) there are going to be two RSSI sources - one from each receiver. Depending on the power up sequence (one of the options) the receiver shown in this field can be either of the two. There doesn't seem to be a secure way for the user to define which it is going to be. 

If the user manages to discover telemetry sensors from both of the receivers - this can be achieved by powering up each receiver separately (and by other means) at any given time only data from one of the two receivers is populated. As it can be either of the two, if the user displays fields for viewing or uses them for alerts or calculations the results will only be predictable and useful if the receiver that is meant to be delivering the data is doing so - and it may not be. 

Is this a matter that can be rectified in OpenTx or is the lack of a useful outcome due to information not being provided by the RF module or receiver firmware and thus FRSKY's responsibility?

**Comment by 3djc** [comment]
https://github.com/opentx/opentx/issues/8504
