### ISSUE TITLE
Taranis QX7 ACCESS - Owner ID different in Companion and radio

### ISSUE THREAD

**Issue by VancouverUmbrella** [opentx/opentx#8518]
**Describe the bug**
In Companion, the 'Owner Registration ID' is not the same as the 'Owner ID' shown in the Setup screen in the radio.

**To Reproduce**
1. On the radio, in the Setup screen, view the Owner ID. In my case it is shown as **z_z X**.
2. Read the model and settings into Companion.
3. Under Radio settings, view the Owner Registration ID. In my case it is shown as **zz X**. Note the lack of underscore.

**Expected behavior**
The ID in Companion would match the ID shown in the radio.

**Significance**
Perhaps this is a trivial problem without any serious consequences. It would be good to be sure. :-)

**Screenshots**

**General information**
 - OpenTX version 2.3.10
 - FrSky QX7 ACCESS transmitter
 - OpenTX Companion 2.3.10 on Mac OS 10.15.7
 
![QX7-owner-id-2021-05-19](https://user-images.githubusercontent.com/56514835/119040251-05ce2500-b96a-11eb-9b6b-967e07a5a5a5.png)
![Screen Shot 2021-05-19 at 10 52 46 AM](https://user-images.githubusercontent.com/56514835/119040255-0666bb80-b96a-11eb-8484-096e15974b87.png)

**Comment by 3djc** [comment]
Duplicate #8167
