### ISSUE TITLE
'Max. Throw' option for DSM protocol not available in Companion

### ISSUE THREAD

**Issue by gdenton61** [opentx/opentx#8527]
Companion Version 2.3.12N500, May 16 2021:
Under the 'External Radio Module' when I select the 'DSM' protocol, 'DSMX' Sub Type I don't see the 'Max. Throw' option available.

Thank you Devs for all of your time/effort!

**Comment by 3djc** [comment]
Companion cannot talk to the module, therefore only very basic configuration of multi is available. In the radio, the multi dialog with OpenTX and inform it of the available options
