### ISSUE TITLE
Radiomaster TX16S - 2.3.11 - Global Functions: Volume, Brightness, etc. not working.

### ISSUE THREAD

**Issue by domhan** [opentx/opentx#8529]
The Global Functions for Volume/Brightness etc. is not working on the Radiomaster TX16S - Version 2.3.11 and 2.3.10.

Configuration seems to be right - right?
![GF](https://user-images.githubusercontent.com/22370971/119777365-57286800-bec6-11eb-9a6c-3afac636e5d4.jpg)

I have also tried an toher knop/poti - same Problem.
In the main Tab I can see, that the knob/poti is working.

**Comment by 3djc** [comment]
Volume works fine (check you do not have a model function not doing the same thing ....)
Brightness needs 2.3.12 nightly to work best
