### ISSUE TITLE
Open TX 2.3.11 and Hours X12S

### ISSUE THREAD

**Issue by 505ray** [opentx/opentx#8551]
updated to OTX 2.3.11 
loaded on computer fine,
try to update Hours X12S .. it seems to try to do so
but I get an error message of ;
Cannot write to L;//FIRMWARE.BIN (reason Unknown error)
TX is currently at 2.3.10-otx
Don't know why... ??
thoughts ?

**Comment by 3djc** [comment]
Sorry but this place is only for tracking otx bugs, not usage issues. Please go to community place like rcgroups or openrcforum for community support

**Comment by 505ray** [comment]
Sorry,  can you please suggest a site to use  ??

**Comment by pfeerick** [comment]
You were given two suggestions above... [rcgroups](rcgroups.com/) and [openrcforums](https://openrcforums.com). However, you most likely tried to copy the file to the wrong drive - you should be copying it onto the SD card drive, not the internal memory.
