### ISSUE TITLE
Crossfire Tx not longer connect to receiver after updating OTX to 2.3.12

### ISSUE THREAD

**Issue by sylphio** [opentx/opentx#8554]
**Describe the bug**
After updating from opentx 2.3.9 to otx 2.3.12, my crossfire tx module is no longer able to connect to crossfire nano receiver (led on the receiver stay red,  normally once a connection is establish the led become green).

To confirm it is OTX related, I flashed back otx 2.3.9 on my transmitter and the issue disappear.

Just after the TX is powered, during 1sec the RX led become green but afterward the connection is lost again.
On the TX module lcd display, during the first second after powering the TX,  CRSF V2 is noted as the RC input but as soon it automatically switch to CRSFShot the connection is lost.

I tested with 2 crossfire transmitter, the big one and the micro tx v2. Both have the same issues.
I tested with 2 crossfire receiver,  one nano on a INAV build and one nano rx on betaflight both have the same issue.

Both transmitter have the multibind option enabled as they can share receiver. 

In all case, if i revert back to otx 2.3.9 everything work again.

**To Reproduce**
Just power previously binded a Crossfire TX and a receiver after updating otx to 2.3.12

**Expected behavior**
The led on the receiver should become green and a valid connection should be established.

**General information**
 OpenTX version 2.3.12 
 Crossfire version 4.11 TX & RX (latest)
 Radiomaster TX16S
 TBS CROSSFIRE TX (the big 2W one) : Multibind enabled
 TBS CROSSFIRE micro TX  v2
 2xTBS receiver nano

**Comment by 3djc** [comment]
It works fine here, I guess your issue must be related to crsf rxnum introduced in 2.3.10

**Comment by sylphio** [comment]
@3djc I was wondering if my issue was related to the tbs cloud/multibind who is enabled on both of my transmitter? It is not used by a lot of people.

Do you have a suggestion on how I can fix that?
Thank you

**Comment by sylphio** [comment]
Ha, I understand now., it can be the rxnum, I use non-zero number for both of them. I will do some test.
Thank
