### ISSUE TITLE
Jumper T-Lite Blackscreen after Update to otx 2.3.12

### ISSUE THREAD

**Issue by c3lsiusII** [opentx/opentx#8555]
Hi all

Yesterday I updated the firmware to 2.3.12 on my jumper t lite. 
Now, as I start the transmitter there comes a message "fatal (or throttle?) warning". 
After that the screen goes black (with a bit backlight...) and the LED becomes red. 
If you press the RTN-Button the LED becomes green but the screen stays black. 
What Ive already done: 
- Firmware Update with the following versions: 2.3.12 and factory-version from jumper itself
- Update over DFU and over Bootloader

I didn't touch the Firmware-Files stored in the transmitter. 
What can I do now? Do you have an idea? 

Thanks and regards

C3sius

**Comment by 3djc** [comment]
This site is not for usage question but to report OpenTX bugs which yours isn't. Please go to community sites like rcgroups or openrc forums for comminity support.

rcgroups tlite thread : https://www.rcgroups.com/forums/showthread.php?3754503-Jumper-T-Lite-another-Lite-radio/page77
