### ISSUE TITLE
Companion 2.3.12: When choosing a sensor to include in a "Calculated" sensor, the minus signs are missing.

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#8562]
In previous versions of Companion, when selecting a sensor to include in a "Calculated" sensor, each available sensor's name appeared in the top half of the list preceded by a minus (-) sign and again in the bottom half of the list without a preceding sign. Now the sensor's name still appears in both halves of the list but the minus sign is missing, making it unclear whether the value or its negative will be used in the calculation.

This is the issue that [sandet01 mentioned on RCGroups](https://www.rcgroups.com/forums/showthread.php?p=47330411&postcount=5536).

**Comment by 3djc** [comment]
Yeap, replicated. @elecpower could you have al look ?

**Comment by elecpower** [comment]
Yes. Without looking I know where the bug is but I'm away this week so will put in a PR next week.
