### ISSUE TITLE
Connecting USB on bootloader lock whole X9D+ radio 

### ISSUE THREAD

**Issue by prikrylm** [opentx/opentx#8566]
**Describe the bug**
Switch on X9D+ (pre 2019) on bootloader (v2.3.12) and connect USB cable lock whole radio.

**To Reproduce**
1. Switch on radio in bootloader mode
2. plug in USB cable (USB connected appears on the screen)
3. No disk on PC appears
4. unplug USB cable - no menu appears
5. try to switch off radio - nothing happened, the radio still powered on "USB connected" is still on the screen.
6. only way  to "switch off" is unplug main battery.

**General information**
 - OpenTX version 2.3.12 
 - Hardware Frsky X9D+ (pre 2019)

**Comment by kilrah** [comment]
Can't reproduce. Bad flash?

**Comment by 3djc** [comment]
Make sure you reflash your bootloader not from computer, but directly on the radio itself (using sd manager, click on firmware file, choose flash bootloader)

**Comment by prikrylm** [comment]
Bootloader is flashed from the radio. But there's probably something wrong with my radio. Bootloader 2.3.11 behaves the same.
