### ISSUE TITLE
No more sound with version 2.3.12

### ISSUE THREAD

**Issue by Cliffweb** [opentx/opentx#8567]
**Describe the bug**
No more sound or alerts with this version 2.3.12 of Companion 
**To Reproduce**
1. Go to every where you have defined sound or alert with special functions.
2. No sound...

I tested the previous version 2.3.11 with the same plane, and same SD card -> it's work well.
It's work well if you manually push the play button in special functions tab.

**Expected behavior**
Sounds like in previous version 2.3.11

**Screenshots**

**General information**
 - OpenTX version 2.3.12
 - X10s radio profile
 - OpenTX Companion 2.3.12 Mac OS 11.4

I have tested to play the same wav file on Mac and on Win10 : The debug window show more actions on Win than on Mac.
It's ok on Win10 not on Mac.

![OpenTx sur PC](https://user-images.githubusercontent.com/58845771/122942758-ba4ad480-d376-11eb-8230-72dc766a319c.png)
<img width="1314" alt="Capture d’écran 1" src="https://user-images.githubusercontent.com/58845771/122942820-c59e0000-d376-11eb-8a54-b3d6d03b2ba3.png">

Result of test on MacOs 11.4 and version 2.3.11 -> it's works

<img width="1651" alt="Capture d’écran 2" src="https://user-images.githubusercontent.com/58845771/122964638-c12e1300-d387-11eb-8ced-3edf0839bae5.png">

**Comment by Cliffweb** [comment]
I reopen this issue because it still not resolved, included in last night compilation.

**Comment by 3djc** [comment]
duplicate #8591
