### ISSUE TITLE
2.3.13 Firmware Release notes 404 error

### ISSUE THREAD

**Issue by timtuxworth** [opentx/opentx#8581]
When I open Companion with my profile set to Jumper T-Lite, I get a prompt to update my firmware. When I click on the Release Notes button on this dialog, the release notes window opens displaying a 404 Not Found error from nginx.

1. open Companion with my profile set to Jumper T-Lite
2. click Release Notes"
3. see OpenTx release notes window containing 404 Not Found error

**Expected behavior**
Jumper T-Lite release notes for the 2.3.13 firmware version should be displayed.

Screenshots attached.
![Screen Shot 2021-06-27 at 4 16 55 PM](https://user-images.githubusercontent.com/5266784/123562498-ee057000-d763-11eb-992a-4337f1b0d109.png)
![Screen Shot 2021-06-27 at 4 16 07 PM](https://user-images.githubusercontent.com/5266784/123562502-f198f700-d763-11eb-8021-f366652dad50.png)

Open-TX Companion 2.3.13 stable version on Mac-OS Big Sur 11.4

**Comment by elecpower** [comment]
Applies to all radios
