### ISSUE TITLE
LOST CONNECTION OF HORUS X10S EXPRESS AND RECEIVER

### ISSUE THREAD

**Issue by afdofdez** [opentx/opentx#8585]
I have a Horus X10S Express and both in versions 3.3.12 and 3.3.13 (much less) I have had problems of loss of connection with the plane, the Horus X10S said "loss of telemetry" and the servos stopped during one or two seconds, then the telemetry would recover and the servos would work again.
To produce the fault, he moved the right stick continuously, commanding ailerons and depth.

Both the Horus X10S Express transmitter with the receivers (Archer R6 and Rx6R) are updated to the latest versions of Frsky, namely 2.1.6 and 2.1.7. respectively.

I am back to version 3.3.11 and everything seems to work fine.

**Comment by 3djc** [comment]
ACCESS issue was know in 2.3.12, but we have several tester with very complex setup that said ACCESS was ok, but now in 2.3.13, it seem ACCST on ISRM is having issue. Are you saying you still have issues with ACCESS ?

**Comment by afdofdez** [comment]
Yes, my problem is with Access LBT (EU)

**Comment by 3djc** [comment]
Then it would be nice to have a otx of your setup where this appears the more clearly

**Comment by afdofdez** [comment]
![Perfil radio](https://user-images.githubusercontent.com/56766487/124016638-29af6c80-d9e6-11eb-8cd0-6a7b80bae7ef.jpg)

![Modelo extra](https://user-images.githubusercontent.com/56766487/124016237-b4439c00-d9e5-11eb-8917-534b5d69b965.jpg)
![Modelo Wisel](https://user-images.githubusercontent.com/56766487/124016240-b4dc3280-d9e5-11eb-9711-e2d0769cbfc7.jpg)

**Comment by afdofdez** [comment]
wisel and extra 300L models

[modelos.zip](https://github.com/opentx/opentx/files/6745904/modelos.zip)

**Comment by brainbubblersbest** [comment]
Update to 2.3.13. Youre on 2.3.12

**Comment by afdofdez** [comment]
I am now on 2.3.11
The problem occurred frequently in 2.3.12 and less frequently in 2.3.13, so I went back to 2.3.11.

**Comment by bigtwin** [comment]
You continue to type 3.3.x instead of 2.3.x. Any special reason for that? May some misunderstanding ...

**Comment by afdofdez** [comment]
just a typo.

**Comment by robustini** [comment]
@afdofdez could you try this firmware and give me feedback?
It is compiled to a specific [commit](https://github.com/opentx/opentx/commit/a167ded9b534f373904e4424e053187b90237b8a), let me know if there is the problem or not.
I compiled it for you for Spanish language.

[firmware.zip](https://github.com/opentx/opentx/files/6756107/firmware.zip)

**Comment by afdofdez** [comment]
The version 2.3.12 variant 219 that you have sent me works perfectly, it has only lost telemetry once with one of the planes when I have moved away from the plane with walls in the middle and the RSSI has dropped a lot over 50.

**Comment by robustini** [comment]
Thanks for the test!
@3djc  knows where to look...

**Comment by raphaelcoeffic** [comment]
> Thanks for the test!
> @3djc knows where to look...

@robustini we already know there is an issue with the new mixer trigger ;-) there is no point to prove here. It would be much more useful to find the issue itself.

and if you want to blame someone, it’s me, as this is my code. @3djc just adapted it and merged it into the 2.3 branch.

**Comment by robustini** [comment]
Hi Raphael! I absolutely don't want to blame anyone, I just want to point out where the problem lies.

**Comment by raphaelcoeffic** [comment]
> Hi Raphael! I absolutely don't want to blame anyone, I just want to point out where the problem lies.

Ok ok! Anyway, I’ll take care as soon as I can. I’m currently away in the mountains, which makes it hard to debug this ;-)

**Comment by robustini** [comment]
> 
> 
> > Hi Raphael! I absolutely don't want to blame anyone, I just want to point out where the problem lies.
> 
> Ok ok! Anyway, I’ll take care as soon as I can. I’m currently away in the mountains, which makes it hard to debug this ;-)

Have a nice holiday!

**Comment by 3djc** [comment]
Could you try those ?
[test-firmwares.zip](https://github.com/opentx/opentx/files/6774746/test-firmwares.zip)

**Comment by afdofdez** [comment]
Now I'm on vacation, this weekend I'll do the tests, ok?

**Comment by afdofdez** [comment]
The version 2.3.13 variant 219 from 2021-07-05 08:20:03 that you have sent me works perfectly in the two planes

**Comment by 3djc** [comment]
What are those version ? The one I posted yesterday (should be more like 2021-07-07) ? Anyhow, I hope we can merge the into nightlies today, so that you can test with all your prefered options

**Comment by afdofdez** [comment]
This is the version you posted yesterday.
But in Companion it says it's from 2021/7/5
![fecha](https://user-images.githubusercontent.com/56766487/124905081-f6706d00-dfe5-11eb-9936-091bed960659.jpg)

**Comment by 3djc** [comment]
Great then ! Thanks for the feedback, looks like we have a fix for this issue :)

**Comment by i3dm** [comment]
if there is a radio link connection issue shouldn't this be a critical bug and message to all users to upgrade fw?

**Comment by 3djc** [comment]
Since you cannot actually  start your craft, you'll notice quicky, and fix is in 2.3.14 which is flagged as a should do upgrade

**Comment by i3dm** [comment]
> Since you cannot actually start your craft, you'll notice quicky, and fix is in 2.3.14 which is flagged as a should do upgrade

why cant you start your craft?
