### ISSUE TITLE
Companion Curves page: Hovering your mouse cursor over a curve number pops up an empty window.

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#8603]
Companion 2.3.13 & Windows 10:

When hovering your mouse cursor over a curve number, an empty window pops up.
 
![curve](https://user-images.githubusercontent.com/22988476/124825766-10f10a80-df42-11eb-984d-d236dba63895.png)

Is the window supposed to show the name of the curve? If so, nothing shows in the popup window whether the curve has a name or not. Companion 2.2.4 behaves the same way and nothing pops up in version 2.1.9.

**Comment by bigtwin** [comment]
Checked on OSX - the little Windows tells "Popup menu available" for all curves. if they are named or not. So actually same gainful as the empty popup :-)
