### ISSUE TITLE
channel 3 ghost mixing on channel 2 after mix removal

### ISSUE THREAD

**Issue by nagordon** [opentx/opentx#8617]
I have been using my frsky x10e for about 1.5 years now with no issue. A few months ago I added a elevator mix to the throttle, such that when I add throttle, the elevator pitches down with a delay. A few days ago, I removed this mixing, and now, there is a undefined/ghost mix that is occurring only on channel 2. The elevator still moves the channel but now also the throttle mixes with the elevator as well, even when there is no mix defined. The worst part of this is that every single other model on my radio now have this ghost mix with the throttle adding to the elevator channel 2! I've tried recreating new models and it still has this issue.

here is the setup before I removed the mix
![image](https://user-images.githubusercontent.com/3792276/125386203-bc3dfd00-e350-11eb-908a-19818f8d8bbc.png)

![image](https://user-images.githubusercontent.com/3792276/125386225-c52ece80-e350-11eb-88ed-85667068270f.png)

here is the radio with a new model recreating the undesirable mixing that is occurring without there being any mixing in opentx. The video shows the inputs page with just 3 inputs
![image](https://user-images.githubusercontent.com/3792276/125388875-25277400-e355-11eb-8b21-a4904f9b046e.png)

For the Mixes I created 4 new mixes (with channel 4 repeating the use of input 2. CH1 and CH3 work fine, but CH2 has odd mixing from the elevator stick and throttle stick.

![opentx frsky x10e](https://user-images.githubusercontent.com/3792276/125388462-5f444600-e354-11eb-892a-4c1e41d0a1e6.gif)

I have recreated this issue on new models. I've tried updating to 2.3.13 but no change. 

**General information**
 - OpenTX version open tx 2.3.10 
 - horus x10 express

Thanks

**Comment by 3djc** [comment]
You do not specifiy at all what you do where. Are you editing your model with companion ? If yes then can you try doing the same on the radio and report ? Also please provide a step by step so we have a change to reproduce

**Comment by nagordon** [comment]
> You do not specifiy at all what you do where. Are you editing your model with companion ? If yes then can you try doing the same on the radio and report ? Also please provide a step by step so we have a change to reproduce

I have created new models with the wizard on the radio, and new models in companion. I am not editing the models at all, just creating new ones, and showing the elevator and throttle channel mixing when there is no mixing. I have removed all models from my radio. 

After performing the stick calibration on the fresh install, you can see the throttle and elevator mixing (see animation)
![20210713_204046_1](https://user-images.githubusercontent.com/3792276/125557964-db519ca2-88a3-495a-9266-bd3fd03c5e4c.gif)

I did try the companion simulator on the model that this issue first occurred, and the ghost mixing did not happen and the model behaved as expected. Is it possible it is some sort of hardware issue on my X10e?
the companion model is here
[zoho dart.odt](https://github.com/opentx/opentx/files/6813390/zoho.dart.odt)


frankly i don't know how to replicate it because I cannot get it to go away in the first place. The best I can describe how to replicate it is to create this model on a frsky X10e, and remove the throttle mixing(which had slow ups) on the elevons, that is when this issue appears. 

this discussion feels relevant to this problem, but I am baffled on how to test it since I only have 1 "infected" radio
https://www.openrcforums.com/forum/viewtopic.php?t=8648

**Comment by nagordon** [comment]
So I installed the ethos bootloader and firmware on the radio and the same exact thing is happening!!! I am convinced it is a hardware error and not an opentx bug.

**Comment by 3djc** [comment]
Ok, closing this then,Best of luck to get your radio repaired

**Comment by nagordon** [comment]
well, I don't think anyone will ever believe me, but when I unplugged and replugged both gimbals, everything works fine now. If anyone can explain how this happened I will buy you a beer.

**Comment by kilrah** [comment]
Bad contacts happen... probably not more than that.
Would really wiggle the wires and connector a bit while moving the sticks and check it's reliable, last thing you want is that a wire/solder point is broken and it reappears in flight after you move the sticks a bit.

**Comment by nagordon** [comment]
I am just curious how a hall effect sensor could "mix" the channels by missing a contact. Must be something on how they come together on the circuit board?

**Comment by kilrah** [comment]
When you have an ADC with multiple muxed inputs (like here) if one input is not connected it will read about the same as the previous one that was read.

**Comment by nagordon** [comment]
> When you have an ADC with multiple muxed inputs (like here) if one input is not connected it will read about the same as the previous one that was read.

ahh, ok. that's make a little more sense. hopefully this will serve other people with a similar issue. thanks
