### ISSUE TITLE
T-Lite Trainer external module does not work

### ISSUE THREAD

**Issue by 0815Creeper** [opentx/opentx#8618]
**Describe the bug**
T-Lite with sbus receiver hooked up to the external module bay does not receive a trainer signal. RX can be turned on and off selecting or deselecting the master/sbus setting as it should but trainer mix lines stay deactivated and trainer mode does not work. Same for ppm receivers and ppm setting

**To Reproduce**
1. Plug sbus receiver into heartbeat of external bay
2. Set trainer mode in active model to master/sbus, the RX turns on (green light if slave radio is transmitting.
3. Check otx trainer page for moving numbers, they don't.

**Expected behavior**
Moving numbers on the trainer page if RX bound to sending slave transmitter and moving it's sticks.

**General information**
 - OpenTX version 2.3.13
 - Hardware T-lite

**Comment by 0815Creeper** [comment]
Possibly a HW defect but someone else would have to check that, I only have 1 t lite

**Comment by 3djc** [comment]
I just had a look at tlite schematics, and by the look of it, there is a reversed diod and missing vcc connection for this pin to actually work... Will contact Jumper in case my drawings I wrong ....

**Comment by 0815Creeper** [comment]
Damn, thanks. Any chance this can be HW moded to work? At least in ppm mode?

**Comment by 3djc** [comment]
ppm or sbus is the same issue, the pin goes trough an hardware inverter, and that circuit is all wrong. Sure it can be hardware modded, it requires D402 to be reversed, and a 3.3v brought between R430 and R429. Where are those ? Your guess is as good as mine !

**Comment by 0815Creeper** [comment]
I see, thanks. I am looking forward to Jumpers answer on this.

**Comment by brainbubblersbest** [comment]
Using a RXSR connected to it's uninverted SBUS pin wont make the Trick? As it is the way on the most F4 Flight Controllers Today.

**Comment by 3djc** [comment]
No, it’s not that the inverter doesn’t invert, it let’s no signal through

**Comment by brainbubblersbest** [comment]
Because of the reverted Diode it blocks + Potential?
But a low Signal can let + Potential through the Diode to drain it and pull it to GND.
Dont know the Schematic and have no t-lite. But that comes into my mind.
A Pic from the Region around R429 and R430 would be Nice. 😁

**Comment by brainbubblersbest** [comment]
Ive read Jumper dont Support frsky r9m lite for that Radio.
Maybe thats why they done this to make shure the weak supply Trace dont get overloaded. The tbs is only supported with 50mw tx power😕
Instead of 7 pin connection like on the x lite, that contain additional two Pins for two wire uart, 
here is only: sbus, blocked heartbeat, vbat, gnd, and s.port

Weird Design....

**Comment by 3djc** [comment]
Ok, I have tracked down the issues, yes, there are two:
1) a VCC pullup is missing. It can be fixed with a hardware patch like this
![image](https://user-images.githubusercontent.com/5167938/125762113-d14886fc-d251-4048-b0bd-c0022712cb0e.png)

2) the input pin on the external module 'thing' is not connected at all
![image](https://user-images.githubusercontent.com/5167938/125762132-d0086f5f-3887-47ce-ae9c-aa47ca9760fa.png)
This one is a mess to fix, so i did not do it

**Comment by 3djc** [comment]
It needs a hardware fix for a missing VCC pull up

![image](https://user-images.githubusercontent.com/5167938/125765034-24325646-9e84-48a8-a6a4-4047d035372d.png)

**Comment by kilrah** [comment]
> Ive read Jumper dont Support frsky r9m lite for that Radio.
> Maybe thats why they done this to make shure the weak supply Trace dont get overloaded. 

No it's because the R9M lite talks over 2 pins of a fast UART and Jumper haven't brought one there.

**Comment by 0815Creeper** [comment]
just to clarify before i start soldering: the only thing that needs to be done is soldering this wire as shown in the picture?
The necessary pin definitons are done in otx?
There is no reversed diod?

**Comment by 3djc** [comment]
No, diod was reversed in the schematic, but not in boards. All is needed is this wire

**Comment by 0815Creeper** [comment]
Works great with the mod. Thank you very much

**Comment by brainbubblersbest** [comment]
> > Ive read Jumper dont Support frsky r9m lite for that Radio.
> > Maybe thats why they done this to make shure the weak supply Trace dont get overloaded.
> 
> No it's because the R9M lite talks over 2 pins of a fast UART and Jumper haven't brought one there.

Yes, I know. But why they planned to use a xlite Bay then?
Only for multi and crsf nano? 
Heartbeat Pin is not really need here. Seems more they finally decide to change wiring before the release, so no one use a r9mlite at 500mW. Jumper advertised Crsf Support with more Output at the Release too. And corrected this a short time later.
Isnt the pxxrx pin bridged with the HB pin in that external pcb?
![Screenshot_20210715_202552_com android chrome](https://user-images.githubusercontent.com/48190425/125840410-c6a96dae-3aef-441f-916b-79b04bd776dc.jpg)
![Screenshot_20210715_202203_com android chrome](https://user-images.githubusercontent.com/48190425/125840420-c1784f92-09c1-49e6-b4f1-db4fe8ad3bf5.jpg)

**Comment by 0815Creeper** [comment]
> Heartbeat Pin is not really need here.

yes it is needed, as the SBUS or PPM RX for trainer operation is connected here. 

Please open a new issue if you think there is a problem with the r9m or any other module. This has nothing to do with modulebay-tranier functionalty

**Comment by brainbubblersbest** [comment]
The pxxrx is used for Trainer input on other Taranis Radios. its just a bit investigating what Happening here, leading you need to mod a T-Lite for SBUS input 😉 I would not say it has nothing to Do with that. But at least youre Happy with it.

**Comment by 0815Creeper** [comment]
Ok, enlighten me please: which radios? On all radios with a JR bay the RX is connected to heartbeat.
Aren't there only the xlite and x9lite remaining? Do you connect an sbus RX to their pxxrx instead of heartbeat?

**Comment by brainbubblersbest** [comment]
Deleted because, sorry i remembered a bit wrong. 
There Was a discussion about implementing it on the pxxrx long ago.
Too long 


#8362

https://github.com/opentx/opentx/pull/5518#issuecomment-539002200

Maybe it will finally Happen on edge since Raphael working on that fork. Sorry for that.

**Comment by derFrickler** [comment]
I use the module bay of my T-Lite for ELRS, but want to use the wireless trainer via the internal Multi-Module.
Is there a way to get this working? 

If i get it right, the normal FrSkyRX-Multi mode on the 4in1 is not working, as internal and external module share the same Telemetry line on most Transmitters (T-Lite seems to have the same schematics as the X7?)

The Multimodule can be run as RX with CPPM output on the STM32 USART1.TX pin (BOOT0 programming TX pin)
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/docs/CPPM_HW_Mod.md  

If if connect that pin to the tip of the trainer jack on the T-Lite, that should work right?

**Comment by 3djc** [comment]
No reason for it not to work with multi trainer

**Comment by derFrickler** [comment]
OK, you say Multi-Trainer should work on the T-Lite while using the external module as described here?
https://www.multi-module.org/using-the-module/wireless-trainer

**Comment by 3djc** [comment]
indeed

**Comment by derFrickler** [comment]
Great, works now, X7 as Student, T-Lite with FrSkyRX-Multi to the Student and ELRS to the Quad.
