### ISSUE TITLE
Loss of servo centre

### ISSUE THREAD

**Issue by driedeker** [opentx/opentx#8620]
I flashed to latest release of open tx. when i took out a model to fly ( this was maiden flight) so when I had elevator not centre i had a hell of a time to get it back to safetly on the ground.I think to myself dodgy servo  on channel 4.so order a replacement
this is on a xr8 in d16.
few days later take a electric glider for flight and again loss of servo centre on channel 4 this resulted in glider going into uncontroled looping or dive till it hit the ground. this was an archer gr8.
now both aircraft had non digital servos on channel 4
I see you now have 2.3.14 with pulse changes so is it fixed and is this mabe the cause on 2.3.13

Back on 2.3.12 and back working ok

**Describe the bug**
Servo not return to centre causing model to loose control.

**To Reproduce**

**Expected behavior**
not to loose control

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.3.13)
 - Hardware (e.g. Frsky X9D se 2019 - OpenTX Companion (e.g. 2.3.13 on windows archer gr8 ans xr8

**Comment by 3djc** [comment]
Use nighly, there is a know issue with your type of radio that is solved in nigthly / upcoming 2.3.14. Please test and reopen if you have an issue with current nightlies
