### ISSUE TITLE
Companion Simulator Bug: Switch padlock doesn't release function when clicked off.

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#8625]
Using OpenTX Companion 2.3.13, set up any function to be activated by SH↓, or by any other switch that's set up as a momentary switch. For example:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

SF1 | SH↓ - Play Sound (Beep 1) Repeat 1s
-- | --
</body></html> 

When you click the padlock icon for the momentary switch it drops to the bottom position and remains there, and the function (in this case a beep every second) becomes active. But when you click the icon again the switch returns to the top position yet the function remains active. At that point you have to pull the switch down again with your mouse and release it in order to deactivate the function.

Companion 2.2.4 does not have this bug.

**Comment by elecpower** [comment]
From memory the interface code had a major overhaul at 2.3 and looks like this one crept in then.
