### ISSUE TITLE
2.3.14 After update no splashscreen change, is only starting up in USB mode

### ISSUE THREAD

**Issue by Toogo** [opentx/opentx#8629]
Firmware update via Companion won't  let the radio startup again, you need to go in USB mode and write firmware from menu.
Own spalshscreen is not copied to te radio

Radi is: X9D+ 2019

Frank

**Comment by 3djc** [comment]
This happens sometimes. Soemtimes retrying fixes it sometimes not. It is clearly computer related, so the new recommended way to flash is to flash using bootloader as you did. COmpanion allows you to save a firmware with your own spalshscreen
