### ISSUE TITLE
GPS + BT

### ISSUE THREAD

**Issue by chemata** [opentx/opentx#8634]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by chemata** [comment]
For the Radiomaster TX16S OpenTX Companion it does not stop configuring with GPS and Bluetooth simultaneously.

**Comment by 3djc** [comment]
It does here

**Comment by 3djc** [comment]
https://user-images.githubusercontent.com/5167938/126875446-71f8d58e-b29c-4691-9fc2-db8a5558d813.MOV

**Comment by 3djc** [comment]
[IMG_0955.zip](https://github.com/opentx/opentx/files/6872777/IMG_0955.zip)

**Comment by chemata** [comment]
Very good.
Now activate both at the same time

**Comment by 3djc** [comment]
how exactly ? clicking on one desactivate the other

**Comment by chemata** [comment]
That is what happens. But the Radiomaster TX16S has 2 UART ports. BT + GPS can be put internally. But if the firmware doesn't support it ......

**Comment by 3djc** [comment]
> For the Radiomaster TX16S OpenTX Companion it does not stop configuring with GPS and Bluetooth simultaneously.

 Then why do you complain that Companion does NOT stop you configuring both when it does. 

BT only works with Horus BT module that required a specific port, so it need someone to develop further the internalgps option to be able to choose the UART port, but it starts to get messy

**Comment by chemata** [comment]
That's not true at all. There is a video from a Russian who puts GPS and BT HC-05.
From what you say, if I have BT FrSky for Horus in OpenTx companion I only have to add the internal GPS, and the BT detects it alone?

**Comment by 3djc** [comment]
BT option is for FrSky BT module ONLY. If you add a BT HC05 then it acts as a transparent UART and does not require an option

**Comment by chemata** [comment]
I don't think I can explain myself well.
I do have the BT on the corresponding site. The FrSykyBT module.
Now I want to put the internal GPS. From what I understand I have to configure the OpenTX with the internal GPS option. The BT is transparent and detects it by itself?

**Comment by 3djc** [comment]
No, you cannot do that, it would need modification to both OpenTX and Companion. GPS and HC-05 is however possible

**Comment by chemata** [comment]
I don't think we understand each other.
That's the problem.
OpenTX Companion does not allow to generate the Firmware of the radiomaster TX16S with internal GPS and internal BT module (FrSkyBT module).
I think OpenTX companion has to leave the 2 options simultaneously

**Comment by 3djc** [comment]
You CANNOT use Horus BT module and GPS at the same time without important otx and companion change. You can make a request for that change

**Comment by chemata** [comment]
Now we have understood each other. That is precisely what I am trying to do. Maybe I got the wrong place, but I don't know where to expose it.
But I sincerely thank you for the kind response and help from him.
I hope someone responsible has time to read this and can implement both options in the future

**Comment by AlksSAV** [comment]
> You CANNOT use Horus BT module and GPS at the same time without important otx and companion change. You can make a request for that change
I use BT and GPS, in TX16S.  In the firmware, I specified the GPS version, and BT via UART to the lower connector(mirror mode).  I recorded a video 
https://youtu.be/0UulXKpc6Kg

**Comment by 3djc** [comment]
That’s not an horus bt module like he has

**Comment by chemata** [comment]
Thank you Alexander for your intervention. I was talking about your video precisely. What happens is that your language (I think Russian) I do not understand, and there is no possibility of simultaneous translation.
I thought you made both BT + GPS work.
I hope that in future versions of OpenTX it can be used together.
No, it is not the same module, but it uses both uarts. Another thing is that you do not work both at the same time

**Comment by chemata** [comment]
Alexander,
I have tried joining your video with this one:
https://www.youtube.com/watch?v=a3wXHn0cokg
But this one doesn't work

**Comment by 3djc** [comment]
BT and gps at the same is not an issues, horus bt and gps is

**Comment by chemata** [comment]
How ?, if openTX Companion does not stop?

**Comment by chemata** [comment]
you configure GPS or configure BT. Both of us do not

**Comment by 3djc** [comment]
As I said earlier you only need the BT option for horus BT, not for hc 05, so if you use hc05 and gps, you only need gps option

**Comment by chemata** [comment]
You will forgive my ignorance.
I have installed the BT FrSkyBT for Horus on the site that the Radiomaster TX16S has for it.
I also have a GPS (BN-800) installed in one of the two UARTs. According to OpenTX Companion the two cannot be used together. You can't both get dizzy.
That alone is my problem. Comrade Alexander did it with another BT module, but I don't understand how. Not my problem.
But if Alexander makes it work, I'll ask him for advice. Or subtitles your video

**Comment by rotorman** [comment]
The protocol that talks to FrSky BT module is different than the protocol that talks with external HC-05.

For FrSky BT you need to activate in OpenTX the special build option "bluetooth", for HC-05 no such option is necessary - you just connect and use it via std. serial protocol (AUX1 or AUX2 of TX16S). With HC-05, you do not have any special "Bluetooth" menus in OpenTX - just serial ports. You need to parametrize the HC-05 externally, e.g. via FTDI adapter on a PC.

OpenTX code is hardwired to use for internalgps and for FrSky BT both the USART6 (that is also shared with TX16S AUX2 port). This is the reason why you currently can only choose internalgps or bluetooth, but not both at the same time.

What you want is to connect FrSky BT (internally to USART6 / AUX2) and connect GPS to USART3/AUX1. But the current code does not support GPS yet on USART3/AUX1.

I hope this clarifies the issue a bit.

**Comment by chemata** [comment]
Spectacular.
Very well explained.
It has become very clear. I hope that soon it can be done.
Thank you very much

**Comment by chemata** [comment]
I think the problem has been clarified.
A shame, but cleared up. I guess this question can be ended. What I do not know if I have to close it because I am the one who has started it or if an administrator has to close it.

**Comment by rotorman** [comment]
Glad to hear you understood the problem. The issue has already been closed, so no further action is necessary from your side!
