### ISSUE TITLE
LUA 2.3.14 broken on x9d 2019?

### ISSUE THREAD

**Issue by elrom** [opentx/opentx#8647]
**Describe the bug**
Flashing lua binary on x9d+ 2019 results in bricked radio

**To Reproduce**
Flash opentx-x9d+2019-lua-noheli-en-2.3.14-otx.bin or opentx-x9d+2019-lua-en-2.3.14-otx.bin to reproduce.

**General information**
opentx-x9d+2019-noheli-en-2.3.14-otx.bin and opentx-x9d+2019-en-2.3.14-otx.bin work fine.

**Comment by 3djc** [comment]
Put firwmware file on SD card in FIRMWARE directory and flash from bootloader
