### ISSUE TITLE
openTx v. 2.3.14 : language in italian when "French" is chosen

### ISSUE THREAD

**Issue by clapenard** [opentx/opentx#8651]
Hi,
After flashing my radiomaster TX16S to v. 2.3.14, the language is in "Italian" while "french" is chosen in the parameters.

This problem didn't exist on v. 2.3.13

Thank you for your fix

Bruno

**Comment by 3djc** [comment]
What parameter are you referring to ?

**Comment by clapenard** [comment]
I'm sorry, it was the voice language on system parameters.
But why all the menu is natively in italian and where may i change it ?

Thank you and sorry for my bad English

**Comment by 3djc** [comment]
Radio menu language is chosen in companion in your radio profile

Audio language is chosen on the radio

**Comment by clapenard** [comment]
ok, thanks
