### ISSUE TITLE
Download a firmware doesn't work

### ISSUE THREAD

**Issue by 0-Sacha** [opentx/opentx#8657]
OpenTX V2.3.14 on Windows 10 21H1

Hello, I got a bug on Windows I can't download a firmware. 

When I got to download then "Download firmware" it open a file explorer to select where to put it.
Then I select "Save" of the file explorer and I got a error because the file do not exist : 
![image](https://user-images.githubusercontent.com/69162022/128605969-2ab1dece-be43-4ed9-93f6-8e6fec4edf12.png)
And when I create a file with the name that it want, it will not change the data in it (I got a 0 bytes file)

I've tried on Pop OS 20.04 (which is a Ubuntu) and all works fine.

**Comment by kilrah** [comment]
Sounds like you're trying to save to a place with no write permissions.

**Comment by 0-Sacha** [comment]
Ok, you were right. The program didn't got the write permission on my folder.
Thanks.
