### ISSUE TITLE
Hi X-Lite, can not restore Models and Settings

### ISSUE THREAD

**Issue by blooddog70** [opentx/opentx#8669]
Hi, I have the next problem .... When I want to read in my models and settings via OpenTX Companion 2.3.14, I always get this error message,can't extract RADIO/radio.bin. Can anyone help me here too? Taranis X-Lite with newest OpenTX Firmware . 
Thank you!

**Comment by 3djc** [comment]
You haven’t configured your radio profile correctly in Companion

**Comment by blooddog70** [comment]
can't backup Models and settings over companion

**Comment by blooddog70** [comment]
i have configured correctlx, whats should i do incorrect??

**Comment by 3djc** [comment]
Your message means the selected profile is one of a color screen radio

**Comment by blooddog70** [comment]
Radio Type: FrSky Taranis X-Lite

**Comment by blooddog70** [comment]
What I have done wrong?
