### ISSUE TITLE
Flashing Horus X12S to 2.3.14 causes all internal XJT models to lose RF settings

### ISSUE THREAD

**Issue by adamkutell** [opentx/opentx#8673]
After using Companion to install version of 2.3.14 (from 2.3.10) causes every model that used internal XJT module for RF setting to lose the setting, and sets radio Internal RF Mode to OFF.  I do not use an external module at all. 

To diagnose, I attempted to switch the mode from OFF but it only shows "ISRM" as a choice. This radio model has an internal XJT and does not contain an internal ISRM module (except as a later upgrade).  Using Companion to flash an older .bin from 2.3.10 restores to previous settings and all models show correct internal RF modes and communication with all my models is restored.  I would be happy with 2.3.11 so I could purchase an R9M and put ExpressLRS on the external module, but cannot if I need to continue using OTX 2.3.10.

Is there a workaround to OTX 2.3.14 to prevent corruption of the internal module choices?

**Comment by 3djc** [comment]
You flashed the wrong firmware, if you do not have isrm, do NOT select internalaccess option
