### ISSUE TITLE
TBS module is not powering on in my Taranis Qx7

### ISSUE THREAD

**Issue by Elrokyfpv** [opentx/opentx#8682]
Everything was working correctly with my tbs module until suddenly it stopped turning on, the battery is new so I discard that option as the problem. What can I do?

**Comment by 3djc** [comment]
Sorry, but this place is for OpenTX bug tracking,  which your issue is obviously not. Please go to community sites like rcgroups or openrcforums for community assistance. In addition, you might ask in https://www.facebook.com/groups/BlackSheepLOUNGE

**Comment by Elrokyfpv** [comment]
I already contacted tbs previously.  We came to the conclusion that the
problem comes from my station so I thought it could be something related to
opentx, sorry.
