### ISSUE TITLE
no bind option

### ISSUE THREAD

**Issue by wakesolo** [opentx/opentx#8683]
Under internal RF I'm unable to select multi-protocol or highlight the word "off"
There's no receiver option or bind option.
I've been trying to factory reset reinstall firmware nothing seems to help.  
[1.zip](https://github.com/opentx/opentx/files/7069969/1.zip)

**Comment by 3djc** [comment]
Indeed, introduced by TBS merge

**Comment by 3djc** [comment]
Should be fixed in tomorows nightly
