### ISSUE TITLE
No support for Jumper T18 Pro?

### ISSUE THREAD

**Issue by SilentJello** [opentx/opentx#8687]
Cant seem to install 2.3.14 seems like the support for the t18 pro is gone.

**Comment by 3djc** [comment]
![image](https://user-images.githubusercontent.com/5167938/131241792-ec528d56-e88c-4a81-8c41-c6002f7a0a58.png)

Maybe supplying MUCH more details would help ?

**Comment by SilentJello** [comment]
That version dosnt include the internal module for 915mhz its only for the 2.4ghz T18S

**Comment by 3djc** [comment]
This has nothing to do with OpenTX then, this is driven by the multi module itself, that reports what protocol are available or not
