### ISSUE TITLE
Unable to bind to V761 protocol unless in 'Low Power Mode'

### ISSUE THREAD

**Issue by frankdoylezw** [opentx/opentx#8702]
I am using a Radiomaster TX16S running 2.3.14-otx(1e09791a) with internal module V1.3.2.86.

If I bind to a receiver running V761 module (https://www.multi-module.org/using-the-module/protocol-details/v761) when the TX is in normal, full power mode, binding occurs (flashing red light on receiver turns solid) but I have no control of the control surfaces. If I click on 'Range', I immediately gain control of the surfaces, but this is lost as soon as I exit the range screen.

If I power cycle the receiver, turn on 'Low power mode' and click bind again, binding occurs but I have full control of the surfaces.

Further info on RCGroups here: https://www.rcgroups.com/forums/showthread.php?2165676-DIY-Multiprotocol-TX-Module/page1513 (See 22685)

Potentially the RF module in the radio outputting too strong a signal?

Grateful for some help, here.

**Comment by 3djc** [comment]
Sorry but OpenTX does not deal with RF communication at all, it really only Pascal that an help you with such issues
