### ISSUE TITLE
Add option to select LUA script as default screen or 'homescreen'

### ISSUE THREAD

**Issue by julianschweizer** [opentx/opentx#8712]
I am heavily useing LUA scripts (e.g. INAV or Betaflight LUA). After selecting a model i have to switch manually to the LUA screen. It would be nice to have a option within opentx to select a LUA or another screen as  'homescreen'. The homescreen should be opened automatically after power on or model selection. 

I know, its not that much effort to navigate to a certain screen. But when making thing ready for flight, hands are full with other stuff (lipo, googles). Having the TX ready automarically could be very handy .... . 

Would be nice to have this added some day! Opinions?!

**Comment by rotorman** [comment]
Just put the LUA full screen widget to the first telemetry page, as this will be the one showed on startup.
