### ISSUE TITLE
Jumper t18 rf power

### ISSUE THREAD

**Issue by DimiDr0l** [opentx/opentx#8731]
Hi, i own jumper t18 pro, opentx 2.3.14 internal rf v1.3.3.0, why rf power max 50mw?
where the power is 300mw?

**Comment by doctormess** [comment]
I have same problem. Running most current OpenTX 2.3.14. Jumper T18 specs say 900mhz power should be up to 300mW. But range under the "RF Power" setting only goes from 1.6mW to 50mW.

In OpenTX I have the Internal RF selected, mode is MULTI FRSKYR9 915MHz. Module Status is the most current V1.3.3.7 AETR.

**Comment by 3djc** [comment]
That power is returned by the multimodule, nothing to do with OpenTX

**Comment by doctormess** [comment]
Just a bit more info.  I emailed Jumper and they said, "The multiprotocol module doesn't support power settings. Please ignore this function on the radio."

I also asked DIY-Multiprotocol-TX-Module here on github and they said," That power is returned by the multimodule, nothing to do with OpenTX."
