### ISSUE TITLE
Frsky redundancy via SBUS not working with complex models

### ISSUE THREAD

**Issue by dl3it** [opentx/opentx#8743]
radios used: Horus X12S (ISRM, w and w/o external XJT), Taranis X9DPlus (XJT)
all firmwares are up to date
openTX 2.3.14 and 2.3.15N584 tested
receivers: RX8R, XM+, RX6R

description:
when using a more or less complex model, the redundancy mode is not working properly. 2 rx are connected via SBUS-OUT and SBUS-IN (e.g. XM+ as slave, RX8R as master). Servos show a glitch every 5-20s, random. When starting RANGE test or when the rx field strength gets low, servos start to move randomly. When flying, telemetry lost and low signal alarms appear, failsafe gets activated.
The problem remains the same when using ACCST or ACCESS for both receivers or when using any combination of the receivers. No difference in X12S when using ISRM (internal) or XJT (external). 
Problems are not visible, when using empty/clean/new models without any complexity.
I attached my problematic model...

[problem.zip](https://github.com/opentx/opentx/files/7336383/problem.zip)

 Thanks :-)

**Comment by dl3it** [comment]
Problem identified:

SBUS seems to be limited to ~125%-130% ... This leads to jitter, when bigger values are used.

The problems while flying are most likely caused by the usage of an external module for the redundant rx and the internal modul for the main rx.

**Comment by Ceeb182** [comment]
Concerning the SBUS protocol (https://github.com/bolderflight/sbus):
- the position command is coded on 11bits, i.e. 2^11=2048 positions
- the position command cannot exceed ±150% (coded in SBUS by 0 for -150% and 2047 for 150%)
- for information -100% is coded by the value 172 and 100% is coded by the value 1811

Concerning OpenTx, even if the extended limits are activated, it is impossible to exceed ±150%.

So everything seems to be consistent in sending and receiving (at least from the theoretical point of view)

So I don't understand why the position command would be limited to ~125-130% ?

@dl3it : do you think it's a problem with the receiver firmware that would wrongly interpret values above ±130% ?

**Comment by dl3it** [comment]
@Ceeb182 
As I have learned today, Frsky receivers are limited to somewhat close to 130%, as Futaba originally intended to use the values only up to 130%, even though 150% would be generally possible. I can confirm that values >130% are clipped.
When having values >130%, the master rx outputs this value, but when using the value from the redundancy bus, it sees only max. 130%. This leads to servo jitter...

**Comment by Ceeb182** [comment]
Well understood, I thank you for this clarification.
