### ISSUE TITLE
Companion 2.3.14: Selecting "Toggle highlight" on the Mixes page produces a weird result.   

### ISSUE THREAD

**Issue by Miami-Mike** [opentx/opentx#8746]
In Companion 2.1.9, right-clicking a mix line and then left-clicking _Toggle_ _highlight_ changes the selected channel number and its associated label to bold type, and the function only allows one channel at a time to be highlighted. If you then switch tabs away from and back to the Mixes page the highlighted channel remains highlighted, but the highlighting is lost when the editing window is closed. Apparently this was the intended behavior of the _Toggle_ _highlight_ option, but as of version 2.2 it behaves very differently.   

Now, in versions 2.2.4, 2.3.14, and presumably all Companion versions in between, right-clicking any mix line and left-clicking _Toggle_ _highlight_ causes all of the channel numbers for channels with entries, and all of their associated labels, to disappear. Nothing remains in the left column of the Mixes page except the channel numbers and labels of mix channels with no entries, and those appear in gray.

And if you switch to a different tab and back again you'll find that the page has returned to normal, and if the channel you intended to highlight has one or more entries, the highlighting will be there.

You might decide to simply remove the _Toggle_ _highlight_ function since its usefulness seems questionable, or you might decide to fix it, but I don't think you'd want to leave it as it is.

**Comment by elecpower** [comment]
Confirmed and I also question usefulness. I've never used the feature. Maybe there is some hidden purpose. I'll check the code and if nothing other than bold/normal then I'd favour removal.

**Comment by pfeerick** [comment]
I noticed this also last week when setting up a model - was copying mixer lines so noticed the entry. If it highlighted a line properly (none of this bold nonsense, nice yellow highlighter hilite thanks!) I could see *some* potential use - i.e. being able to make a line stand out for comparision/reference, but as it stands, it is 1) useless and 2) bugged as it makes the channel names disappear and also makes it look like there are multi-input mixes (`+=`). I'd vote for removal also ;)

**Comment by elecpower** [comment]
The feature's purpose is to highlight all references to the highlighted channel in the mixes list.

![Screenshot from 2021-10-27 06-39-46](https://user-images.githubusercontent.com/15316949/138950115-3f348eb6-f234-4dc9-9d02-f34abf7c3a90.png)
