### ISSUE TITLE
TX16S external Access Registration fails

### ISSUE THREAD

**Issue by twistedwings** [opentx/opentx#8747]
I purchased a FrSky R9M 2019 and 2 R9MM-OTA.
Did the external Access Mod.
Flashed R9M with ACCESS firmware FW-R9M2019_ACCESS_V1.3.0.
Flashed the R9MMs with ACCESS firmware FW-R9MINI-R9MM-OTA_v1.3.1.

Registered the 1st R9MM successful.
![screen-2021-10-13-204537](https://user-images.githubusercontent.com/562809/137263526-dcb4948b-a749-4c1e-b3e1-b37d625d9304.jpg)

Registering the 2nd R9MM failed.
![screen-2021-10-13-204658](https://user-images.githubusercontent.com/562809/137263671-2ede7110-222c-451b-9d6e-f55392e5b0df.jpg)

Then I flashed R9M and R9MMs with ACCST firmware.
Both receivers can be bound and are working with ACCST so it's unlikely they are damaged.

Radiomaster TX16S
external Access Mod
OpenTX 2.3.14

**Comment by 3djc** [comment]
openTX does not handle those function per say. Most likely, your second receiver firmware was imcompatible wth module
