### ISSUE TITLE
TX16S external Access Registration fails

### ISSUE THREAD

**Issue by twistedwings** [opentx/opentx#8749]
I purchased a FrSky R9M 2019 and 2 R9MM-OTA.
Did the external Access Mod.
Flashed R9M with ACCESS firmware FW-R9M2019_ACCESS_V1.3.0.
Flashed the R9MMs with ACCESS firmware FW-R9MINI-R9MM-OTA_v1.3.1.

Registered the 1st R9MM successful.
![screen-2021-10-13-204537](https://user-images.githubusercontent.com/562809/137381606-63952c4f-f40a-4496-9c80-416f317fe0d3.jpg)

Registering the 2nd R9MM failed.

![screen-2021-10-13-204658](https://user-images.githubusercontent.com/562809/137381629-b541fbb6-651e-4e67-b046-e5e95ea02d32.jpg)

Then I flashed R9M and R9MMs with ACCST firmware.
Both receivers can be bound and are working with ACCST so it's unlikely they are damaged.

Radiomaster TX16S
external Access Mod
OpenTX 2.3.14

**Comment by brainbubblersbest** [comment]
Use Different id for a second receiver. (eg=rx1XY/rx2XY) 
That Name is to recognize wich receiver in your plane it is. 
And bind after register.
And first select register on your Radio. 
AFTER THAT supply your receiver with Presse Boot Button. 

The other (userID) needs to be the same on all your Radios.
(if you wanna use more then one Radio. Eg x10 but other day the xlite)

**Comment by twistedwings** [comment]
turned out that the 2nd receiver was damaged.
Registration worked with the new one.
