### ISSUE TITLE
HoTT telemetry / error in calculation of TX and RX RSSI values 

### ISSUE THREAD

**Issue by mha1** [opentx/opentx#8751]
General information
 - OpenTX version 2.3.14
 - Hardware Radiomaster TX16s 
 - OpenTX Companion e.g. 2.1.14 on Ubuntu 16.04
 - MPM in Graupner HoTT mode with Graupner GR-16 and GR-24 RX

Problem
RSSI values for either TX or RX RSSI have a lower boundary of -71dm, see screenshot 1

Expected behaviour
RSSI should reflect the true RSSI values as delivered by the CC2500 

Reason
The function _processHoTTdBm_ in _hott.cpp_ converting CC2500 values to RSSI values has two implementation problems.

1. The CC2500 value passed is a signed 8 bit value but processed as unsigned 8 bit value
2. The CC2500 data sheet ask for subtracting 256 from the CC2500 value if the CC2500 value is greater or equal to 128. Instead the CC2500 value is subtracted from 256 in this case

Solution
Replace function _int16_t processHoTTdBm(uint8_t value)_ with the follwing code. For results see screenshot 2.
```

// CC2500 data sheet:
// The RSSI value read from the RSSI status register is a 2’s complement number. The following
// procedure can be used to convert the RSSI reading to an absolute power level (RSSI_dBm).
// 1) Read the RSSI status register
// 2) Convert the reading from a hexadecimal number to a decimal number (RSSI_dec)
// 3) If RSSI_dec ≥ 128 then RSSI_dBm = (RSSI_dec - 256)/2 – RSSI_offset
// 4) Else if RSSI_dec < 128 then RSSI_dBm = (RSSI_dec)/2 – RSSI_offset

int16_t processHoTTdBm(int16_t value)
{
  if (value >= 128) {
    value -= 256;
  }
  return value/2 - 71;
}
```

Screenshot 1
![image](https://user-images.githubusercontent.com/5615068/137704435-c69aeec4-d7f7-4796-a968-8e3890a23fb8.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/5615068/137704876-316c2adc-ad68-43c0-b41b-ce5be7e51973.png)

**Comment by 3djc** [comment]
@pascallanger , you wrote this code,  let me know what you think

**Comment by pascallanger** [comment]
@3djc I'm thinking it's a typo in the code... value = 256 - value; instead of value = value - 256; or value -= 256;

**Comment by 3djc** [comment]
Thanks, will change it then

**Comment by mha1** [comment]
Hi,

Thanks, appreciate it.

Please don't just change the one line. I also changed the type of the argument 'value' from uint8_t to int16_t. 

value = value - 256 won't work with 'value' being a uint8_t. Changing the argument to int16_t doesn't have any side effects as the return type is a int16_t too.

I flight tested the code as proposed with a private build based on 2.3.14. No issues with RSSI  as expected down into the -80s at a distance slightly over 1000m. 

Regards,
Michael
