### ISSUE TITLE
Change trainer channel settings via trim inputs

### ISSUE THREAD

**Issue by dakhnod** [opentx/opentx#8754]
### Is your feature request related to a problem? Please describe.
No Problem. My proposal aims to simplify setting which channels a trainee/slave remote is able to control

### Describe the solution you'd like
My solution is to control the trainer setting for a channel via that channels trim button.
Lets imagine, the throttle channel is set to disable in trainer settings, e.g. the trainee cannot control the throttle.
By pressing throttle-trim up we enable the throttle channel for our trainee.
By pressing throttle-trim down we disable the throttle channel again.
This is only supposed to work if the trainer screen is open on the remote.

### Describe alternatives you've considered
The trainer screen is fine the way it is, I'm just proposing something that would make at least my life easier.

Some people may need the trim functions in the trainer screen, so my application would interfere with that.
Maybe a setting to control the trim button behaviour in the trainer screen would make sense?

If there is any interest in that feature I am willing to implement it myself.
I would just appreciate some feedback on whether it makes sense and how to satisfy those people
who need to really trim their model in the trainer settings.

**Comment by 3djc** [comment]
It can be done today with existing functions I think

**Comment by dakhnod** [comment]
That would also be great. I wasn't able to find a way to control what channels a trainee controls programmatically.

**Comment by kilrah** [comment]
You don't use the built-in Trainer function but use mixer lines with the trainer channels as source. These can be enabled/disabled with a switch, and a toggle switch can be created from the trims with Logical switches.
