### ISSUE TITLE
„Max Bauds“ missing on T-Lite (2.3.12)

### ISSUE THREAD

**Issue by ltwin8** [opentx/opentx#8762]
**Describe the bug**

Max bauds not available on t-lite running 2.3.12, use external ELRS Slim module can not get over 143Hz

**To Reproduce**
1. Flash 2.3.12 (2.3.13 also tested)
2. Go to HARDWARE (log press SYS, page to 6 of 7
3. Scroll down eher Max bauds should be
4. See error, no option

**Expected behavior**
Near the bottom of the page I expect max bauds with option to set 400k as in the x7 running 2.3.12

**Screenshots**
Picture attached

**General information**
 - OpenTX version 2.3.12
 - Hardware jumper t-lite
 - OpenTX Companion 2.3.12 on windows (2.3.13 also tried)

Thanks for any help

**Comment by 3djc** [comment]
Max baud isn't missing for T-Lite. It is present only for radio that are likely not to support 400k, T-Lite supports 400k, so it is set at 400k, no UI need for that.
