### ISSUE TITLE
Radioking TX18S - Bootloaderscreen

### ISSUE THREAD

**Issue by ruedig** [opentx/opentx#8763]
meine  Radioking TX18S hat im Auslieferungszustand die richtige Screenansicht für den Bootsloader und auch für die Modelleinstellungen gezeigt.
Nach dem UpLoad auf  OpenTX 2.3.14 wird die Ansicht des Bootloaderscreen um 180° gedreht angezeigt.

![image](https://user-images.githubusercontent.com/93605932/139905046-2e840992-369b-49dc-9cea-70d89c559a03.png)

Wie kann ich das ändern ??
Ein zurück flashen auf OpenTX 2.3.10  blieb ohne Erfolg.

Danke für die Hilfe
Rüdiger

**Comment by 3djc** [comment]
This site is English only, and tx18 is not a supported radio (https://www.open-tx.org/radios)
