### ISSUE TITLE
Companion update check failed, new version information not found

### ISSUE THREAD

**Issue by kicka911** [opentx/opentx#8766]
Getting this error when trying to update firmware on my QX7. I have tried on two different laptops with no success. Cleared browser cache and that didn't work.

**Comment by bigtwin** [comment]
Probably [this helps](https://github.com/opentx/opentx/issues/8723).

If not, plz provide the minimun required information which is needed to describe a bug. And dont forget to peform at least a little search to check whether your problem is already known.

**Comment by 3djc** [comment]
https://www.open-tx.org/2021/10/01/companion-downloads

**Comment by kicka911** [comment]
OK. I downloaded a fresh copy with Edge, installed it and all seems good now. Thanks for you help.

    On Wednesday, November 3, 2021, 02:05:49 AM CDT, 3djc ***@***.***> wrote:  
 
 


Closed #8766.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
