### ISSUE TITLE
Trainer Socket Detection on X7 AND X9 Lite

### ISSUE THREAD

**Issue by justtrashmaker** [opentx/opentx#8774]
Hallo,

same problem like here:

https://github.com/opentx/opentx/issues/8764

on the x9 lite. With version 2.3.9 no problems.

**Comment by ChrisOhara57** [comment]
Hello
it seems to be the same problem I had.  #8670
In my case it is a x9lite S.
I worked on 2.3.7 but did not on 2.3.14
I flashed 2.3.11 and it does work now.

**Comment by 3djc** [comment]
Duplicate #8764
