### ISSUE TITLE
Jumper T-Lite switch locations

### ISSUE THREAD

**Issue by FelixSchreiber** [opentx/opentx#8780]
In the radios Main View the switch locations are not ordered according to the real hardware switch locations.

On the radio, C and A are left to the antenna,  B and D are right to it; C is the leftmost and D the rightmost switch. C and D are located more to the back whereas A and B are located more to the front of the radio.
In the main view, A and B are left to the left stick, C and D are right to the right stick.
![T-Lite_switches](https://user-images.githubusercontent.com/94545140/142624999-0d75ff0e-1205-415e-99ed-8ac4009ac8da.png)
A more intuitive order would e.g be :
Left to the left stick: First Switch A and below switch C
Right to the right stick: First Switch B and below switch D

In Companion the switches are ordered A, B, C, D (from left to right)
![SimulatorSwitches](https://user-images.githubusercontent.com/94545140/142625052-dbc3e83d-9512-4572-8c91-dd38a590c57f.png)
A more intuitive order would be according to the real switch locations: C, A, B, D (from left to right)

Furthermore it would be very helpful if the other buttons in the radio image could be named (as long as you are not fully used to this radio and know it by heart).
![SimulatorGraphics](https://user-images.githubusercontent.com/94545140/142625080-0e490265-1de4-42c7-8cc2-e6bef8760b34.png)

**General information**
 - OpenTX version 2.3.14
 - Hardware Jumper T-Lite
 - OpenTX Companion .3.14

**Comment by 3djc** [comment]
Switch are alphabeticaly ordered by design

**Comment by FelixSchreiber** [comment]
sorry, but this answer is too simple and doesn't comply with reality (probably you are referring only to the Companion?).

In radio/src/gui/128x64/view_main.cpp there are for example many different arrangements for the switches defined.
Why not add something similar for this radio like

```
#elif defined(PCBXLITES)
        static const uint8_t x[NUM_SWITCHES] = {2*FW-2, 16*FW+1, 2*FW-2, 16*FW+1};
        static const uint8_t y[NUM_SWITCHES] = {4*FH+1, 4*FH+1, 6*FH+1, 6*FH+1};
        for (int i=0; i<NUM_SWITCHES; ++i) {
          if (SWITCH_EXISTS(i)) {
            getvalue_t val = getValue(MIXSRC_FIRST_SWITCH + i);
            getvalue_t sw = ((val < 0) ? 3 * i + 1 : ((val == 0) ? 3 * i + 2 : 3 * i + 3));
            drawSwitch(x[i], y[i], sw, 0, false);
          }
        }
```

**Comment by FelixSchreiber** [comment]
this solves at least my first point

![screenshot_tlite_21-11-19_17-59-06](https://user-images.githubusercontent.com/94545140/142662223-10cd7587-5a25-4ebe-883c-5561e55e9325.png)


```
diff --git a/radio/src/gui/128x64/view_main.cpp b/radio/src/gui/128x64/view_main.cpp
index b3cea8de7..4ea774651 100644
--- a/radio/src/gui/128x64/view_main.cpp
+++ b/radio/src/gui/128x64/view_main.cpp
@@ -520,6 +520,16 @@ void menuMainView(event_t event)
             drawSwitch(x[i], y[i], sw, 0, false);
           }
         }
+#elif defined(RADIO_TLITE)
+        static const uint8_t x[NUM_SWITCHES] = {2 * FW - 2, 16 * FW + 1, 2 * FW - 2, 16 * FW + 1};
+        static const uint8_t y[NUM_SWITCHES] = {4 * FH + 1, 4 * FH + 1, 5 * FH + 1, 5 * FH + 1};
+        for (int i = 0; i < NUM_SWITCHES; ++i) {
+          if (SWITCH_EXISTS(i)) {
+            getvalue_t val = getValue(MIXSRC_FIRST_SWITCH + i);
+            getvalue_t sw = ((val < 0) ? 3 * i + 1 : ((val == 0) ? 3 * i + 2 : 3 * i + 3));
+            drawSwitch(x[i], y[i], sw, 0, false);
+          }
+        }
 #elif defined(PCBTARANIS)
         uint8_t switches = min(NUM_SWITCHES, 6);
         for (int i = 0; i < switches; ++i) {

```
