### ISSUE TITLE
flashing of receiver unfortunately not possible

### ISSUE THREAD

**Issue by TheIsotopes** [opentx/opentx#8805]
Unfortunately i was only able to test fix 685657c a few days ago by changing the mode. This works now, but I was only able to test the flashing today and it unfortunately fails. The message `Firmware update error - Data refused` appears.

Sorry that i was only able to determine this today, please @3djc can you have a look at it again.

(this is an addendum to #8802)

**Comment by 3djc** [comment]
Simply try a second time, it seems to have been a issue for a long time

**Comment by 3djc** [comment]
Or not, more tricky than it sounds

**Comment by TheIsotopes** [comment]
I tested everything again (mode change / flashing receiver) with #8806 and it now works as expected.

thanks again @3djc 👍
