### ISSUE TITLE
QX7 and TBS nano TX II

### ISSUE THREAD

**Issue by alec-bip** [opentx/opentx#8810]
Hi everyone,
I have a problem on my Taranis QX7 when it comes to adding the TBS CROSSFIRE MICRO TX II. First of all I have soldered the little piece according to videos and forums I saw and then I should be able to change : external RF —> CRSF. However, this option does not appear when I turn the right wheel. Therefore, some forums and videos I saw told me to change “max bauds” from 400000 to 115200. However, the “max bauds” does not appear in the hardware page (6/7). I have the version 2.3.0.
Please help me I am desperate

**Comment by 3djc** [comment]
Please update to 2.3.14
