### ISSUE TITLE
TBS MAMBO flash external module not working (elrs always no sync)

### ISSUE THREAD

**Issue by Sekilsgs2** [opentx/opentx#8812]
Latest opentx installed to tbs mambo.
I'm trying flash elrs bootloader to r9m - getting always data refused error
I'm trying flash elrs firmware to r9m - getting always nosync error 
Probably telemetry driver have bug?

**Comment by 3djc** [comment]
Isn't tbs still using freedom tx ?

**Comment by Sekilsgs2** [comment]
> Isn't tbs still using freedom tx ?

I'm install opentx to mambo and tested it myself.
All working good besides flashing external modules..
Current freedomtx does not support flashing firmware of external modules such elrs or r9m..

**Comment by Sekilsgs2** [comment]
Oh.. i'm find that tbs telemetry driver loose this 
**sportWaitTransmissionComplete();**
in
**void telemetryPortSetDirectionInput()**
function - i'm think this reason..

**Comment by Sekilsgs2** [comment]
I'm add this to telemetry driver but now have another problem - while writing FW to module i'm getting  random errors and writing breaks at random state (5% or 70% and etc).
I'm try stopping crossfire task and this helps but not 100% (now i'm success flashing 2 time and 5 time have errors while writing)..

**Comment by Sekilsgs2** [comment]
Upd - adding **sportWaitTransmissionComplete();** fix this bug!

**Comment by 3djc** [comment]
you mean that : https://github.com/opentx/opentx/pull/8813 ?

**Comment by Sekilsgs2** [comment]
> you mean that : #8813 ?

Yes thank you!
