### ISSUE TITLE
Uppercase letters- where?

### ISSUE THREAD

**Issue by Sekilsgs2** [opentx/opentx#8814]
Cant put uppercase letters in any text edit.

For example - try change model name, where default name have first uppercase letter - after scrolling through uppercase letters to non-uppercase ones - you won't see any more uppercase letters - they disappear from the list.

 - OpenTX version (master)
 - Hardware (-)
 - OpenTX Companion (-)

**Comment by kilrah** [comment]
Long press enter.

**Comment by Sekilsgs2** [comment]
> Long press enter.

Oh, sorry.
Thanks.
