### ISSUE TITLE
TBS Mambo - no pots calibration menu

### ISSUE THREAD

**Issue by Sekilsgs2** [opentx/opentx#8815]
**Describe the bug**
TBS Mambo - need two calibrations - for sticks and for pots but - no pots calibration menu (button not active)

**To Reproduce**
1. Go to radio hardware page
2. Scroll down to calibration for pots
3. See that cursor skips calibration and go to S1 pot. 

see video
https://mega.nz/file/xSxElYja#xkdeHZqorKBFcjvxdTdk91OxL8BvUQdhKFLJH0YNzlM

 - OpenTX version (latest)
 - Hardware (tbs mambo)

**Comment by kilrah** [comment]
Sticks and pots calibrate at the same place, issue is likely the stray label

**Comment by 3djc** [comment]
Mambo calib do not work on simu and we don't have a mambo to try, can you confirm that calibration of pots occurs in main callib @Sekilsgs2  ? (code suggest it should)

**Comment by Sekilsgs2** [comment]
> Mambo calib do not work on simu and we don't have a mambo to try, can you confirm that calibration of pots occurs in main callib @Sekilsgs2 ? (code suggest it should)

No, tbs have separate calibration menu ( **void menuCommonCalibPots(event_t event)** )for pots in 
**https://github.com/opentx/opentx/blob/2.3/radio/src/gui/128x64/radio_calibration_hall.cpp**
Need separate button for this.
see video with the right behavior - 
https://mega.nz/file/ELIXGQbZ#9zVXHGEdpKjlsYcxCXt_Aha93lzSl_m58xOq3yAq_fY

Need to add a **POTS_CALIBRATION** menu to
**void menuRadioHardware(event_t event)**
But with latest commits need litle rework current defines for **POTS_ROWS**

**Comment by 3djc** [comment]
I disagree that this is the right behaviors, it should be trigered after sticks are calibrated, if not at same time. The code suggest it is done using page key : https://github.com/opentx/opentx/blob/2.3/radio/src/gui/128x64/radio_calibration_hall.cpp#L76, but htne again, can't try it

**Comment by Sekilsgs2** [comment]
> I disagree that this is the right behaviors, it should be trigered after sticks are calibrated, if not at same time. The code suggest it is done using page key : https://github.com/opentx/opentx/blob/2.3/radio/src/gui/128x64/radio_calibration_hall.cpp#L76

:-D
Yes page key list next pots calibration menu! I'm test and this working))
There is no information about this anywhere...
Thanks!

**Comment by 3djc** [comment]
Which means we need to remove that button, or make it working so leaving this issue opened

**Comment by Sekilsgs2** [comment]
> Which means we need to remove that button, or make it working so leaving this issue opened

Yes i'm want say this too,but thought it might for others :)

**Comment by 3djc** [comment]
Could you try this branch ? It should have the button working (in addition of PAGE) : https://github.com/opentx/opentx/compare/3djc/tbs-pots-calib

**Comment by Sekilsgs2** [comment]
> Could you try this branch ? It should have the button working (in addition of PAGE) : https://github.com/opentx/opentx/compare/3djc/tbs-pots-calib

Yes this works correctly!
Thanks.
