### ISSUE TITLE
Companion: Jumper T-Pro has jp4in1 but only FrSky is allowed

### ISSUE THREAD

**Issue by arkarkark** [opentx/opentx#8826]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

I have a Jumper T-Pro running the factory firmware and I'm using companion version 2.3.15N625 (Jan 13th 2022). I copied a model over from my Jumper T-Lite but it said some of the settings weren't compatible. Indeed the internal RF module was listed as off. when I went to turn it on (for Flysky) the only option was for 3 FrSky models not Multi which would allow me to select FlySky.

**To Reproduce**
1. configure radio to be a Jumper T-Pro
2. Go to add a new model
3. double click to configure it. try and select Multi from the internal RF options.
4. See only FrSky options and no MULTI option or FlySky

**Expected behavior**

**Screenshots**

here's how it looks
<img width="440" alt="Editing_model_2__Humbug____t-pro_otx_" src="https://user-images.githubusercontent.com/877895/149643953-e6335222-9b61-41ea-8535-84b8b4eeaea3.png">

here's how it should look
<img width="1039" alt="Editing_model_2__Humbug____t-lite_otx_" src="https://user-images.githubusercontent.com/877895/149644000-4ef3308c-5ce0-465b-b393-e1a505359328.png">

**General information**
 - OpenTX version: Factory (af6b37d3) Variant: 219 Date and time 2021-12-13 13:57:35 
 - Hardware Jumper T-Pro
 - OpenTX Companion Mac 2.3.15N625 (Jan 13th 2022)

**Comment by 3djc** [comment]
It will be fixed in tomorows nightly companion, but multi module edition should NOT be done in companion. Since 2.3, there is an advanced dialog happening in the radio between the module and OpenTX, allowing OpenTX to display the option asked by the module itself. This can obviously not happen in companion.
