### ISSUE TITLE
Jumper T-Pro and companion 2.3.14, cannot read models and settings from radio, error: 'Can't extract RADIO/radio.bin'

### ISSUE THREAD

**Issue by karmensarodjo** [opentx/opentx#8830]
Dear All,

I'm new to OpenTX. Just bought a Jumper T-PRO and did a few things, ran into this problem right away. I've been trying to find a solution for almost two days and haven't found it yet, ...did I miss something, should do or download a more appropriate version? Thanks in advance!

Background,
- Download and prepare the sdcard file sdcard-128x64-2.3V0038.zip on the micro SD Card and insert it into the radio. Now radio can talk.
- Download OpenTX Companion, install, and added profile settings as Jumper T-Lite, the rest are default
- No problem with PC and radio connection. The SD Card radio is read by Explorer complete with its folders and there is another drive with some bin files.
- Everything is still original 
- ...haven't flashed anything to radio, just insert SD card, create and name a model, set it as FUTABA (no further setup).

1. Power up the radio via bootloader
2. Connect USB C cable
3. Run Companion
4. Goto Read/Write>Read Models and Settings From Radio

Expected behavior:
The process should be seamless to read and copy models and radio settings

Screenshots:
Like other 'Can't extract RADIO/radio.bin' screenshots

General information:
 - OpenTX version... (how can i check firmware version of Jumper T-PRO?)
 - Hardware brand new Jumper T-PRO, brand new SD Card microSDHC 16GB
 - OpenTX Companion 2.3.14 on Windows 7

**Comment by unites** [comment]
Just pointing out this same thing is seen with EdgeTX.  I may open a similar issue over there.  I am guessing something needs to be added for the Jumper T Pro to both "companions".

FYI OP, if you hold down your menu button you are thrown into an Admin menu and the last page will give you info about your firmware.

EDIT: done... https://github.com/EdgeTX/edgetx/issues/1452

**Comment by 3djc** [comment]
I'll fix that tomorrow

**Comment by unites** [comment]
> I'll fix that tomorrow

Thanks!
@3djc 
I can create a separate issue for this but thought I would ask.  Do you or anyone here happen to have the Jumper T Pro firmware?  In the process of messing with this I accidently flashed the T-lite and am not able to find a version of the T-Pro firmware bin.

**Comment by 3djc** [comment]
You should be able to get a nightly

**Comment by 3djc** [comment]
Tested ok with 2.3.15N624, please ensure your current profile is a T-Pro

**Comment by unites** [comment]
> Tested ok with 2.3.15N624, please ensure your current profile is a T-Pro

@3djc  Thanks, however... I am getting an "Invalid board" error when attempting to download any T-Pro firmware using the Companion app on nightly 2.3.15N624 for mac, windows and debian.  Is there a URL/URI I could access to just pull the bin file for the T pro?

**Comment by 3djc** [comment]
Have you set your channel to nighties ?

**Comment by unites** [comment]
Ah, there is a channel drop down in the Companion app. I see it now on tab two of settings.  Apologies this is day 2 for me in this hobby, still learning my way around.  All set, new T-PRO firmware is now in place!  Thanks again!

**Comment by karmensarodjo** [comment]
Thank you, all! …will be tested after office

**Comment by monkfood** [comment]
Issue still exists in nightly 665
Steps:

- Downloaded and installed nightly build 665
- Created a model for T-PRO, downloaded the firmware (trom nightly channel)
- Connected T-PRO RC to Laptop USB: It says that USB cable is connected on he RC, 
-  Push firmware or model.

Error: 
No DFU Compatible device found in log and message "Can't extract RADIO/radio.bin"

Tested on OSX and Windows
