### ISSUE TITLE
Horus Access - receiver option displayed with "typo"/missing character

### ISSUE THREAD

**Issue by bigtwin** [opentx/opentx#8831]
When displaying the options for a ACCESS bound RXSR receiver it is written " rotocol" rather than "Protocol".
Please see attached pictures from 2 different RXSR. However, I dont know (yet) whether its an issue of RXSR or any other ACCESS receiver as well.

OpenTX 2.3.14 on Horus

![grafik](https://user-images.githubusercontent.com/55102433/149773318-9f31f096-45fc-4345-b1e1-4ef735d3f5eb.png)

![grafik](https://user-images.githubusercontent.com/55102433/149773358-d3ff006a-5981-4991-9a2e-5bd49a2e557b.png)

**Comment by bigtwin** [comment]
This typo does not occur with ETX. Closing the issue.

**Comment by bsongis** [comment]
Fixed
