### ISSUE TITLE
Companion: T-Pro Logical Switches & Special Functions, blank and wrong...

### ISSUE THREAD

**Issue by karmensarodjo** [opentx/opentx#8842]
Hi All,

To be honest, i'm not sure if this is a bug or I'm missing something...
I'm still exploring programming in OpenTX before using it for my rc heli. And the lines of logic I've written below, are what I expected and work fine on my Jumper T-Pro radio. But when I read it to Companion to do a backup, it doesn't read correctly like the screenshot below. 
Please check... thanks in advance!

1. ...read Models and Settings from Radio
1. edit the model
2. go to Logical Switches and Special Functions

Expected behavior:
The Companion should reflect of my radio settings

Screenshots:
Logical Switches:
![Logical Switches](https://user-images.githubusercontent.com/97834436/150676427-2067f25d-5ebc-434b-8a24-c303d942bafe.png)

Special Functions:
![Special Functions](https://user-images.githubusercontent.com/97834436/150676455-60a5b8fb-c7e9-42d6-8753-d752ff497659.png)

General information:
OpenTX version 2.3.15N633
OpenTX companion-windows-2.3.15N633 on Windows 7

**Comment by 3djc** [comment]
Please save your eeprom with radio (hardware page, bottom, will be saved in EEPROM ssd directory) and paste it here

**Comment by karmensarodjo** [comment]
@3djc,

plase find the attached file below...
[eeprom-2022-01-23-190634.zip](https://github.com/opentx/opentx/files/7920417/eeprom-2022-01-23-190634.zip)

thanks you!

**Comment by 3djc** [comment]
Fixed in 17af9c2328711fd34527f2c08e3697afd89fa0cf
