### ISSUE TITLE
Power on Delay Farb Radio

### ISSUE THREAD

**Issue by Devil-67** [opentx/opentx#8854]
Please add the option Power on Delay for colour radios as for black and white.
![X12](https://user-images.githubusercontent.com/31169133/152130490-e4bd04fa-ff42-4767-b885-1bd85ff227f8.PNG)
![X9D](https://user-images.githubusercontent.com/31169133/152130492-32f0511f-7163-4967-8d1c-d843c6d24c9f.PNG)

**Comment by 3djc** [comment]
Power on delay is dictated by the hardware loading time which are much longer on colorlcd radio

**Comment by Devil-67** [comment]
I'm only concerned with the time it takes to hold the power button, not the time it takes to start.

**Comment by 3djc** [comment]
Not sure I understand, it takes a 1sec push, but thats hardware, you want it longer ?

**Comment by Devil-67** [comment]
No I want it shorter, so just tap it.
The best way to adjust it is the way it is with X9D 2019.
I use 0 sec on the X9D

**Comment by 3djc** [comment]
Then that won't happen, since the only delay there is is hardware

**Comment by Devil-67** [comment]
hmm... 
ok, then you can close it

Thanks
