### ISSUE TITLE
Radiomaster Zorro Simulator on Linux Momentary switches missing

### ISSUE THREAD

**Issue by coaster007** [opentx/opentx#8860]
Edgetx companion/simulator on Linux: EdgeTx_Companion_2.7.0-44f12ba-x86_64.AppImage

Momentary switches SA/SD/SG not present in the Simulator, only the SH momentary switch
On Windows all momentary switches are available and visible.

![zorro](https://user-images.githubusercontent.com/34204590/152647631-04a9be02-6a93-4013-bdff-8c8898164ad8.png)

**Comment by rotorman** [comment]
If the issue is present solely in EdgeTX Companion, you might want to post the issue in EdgeTX GitHub instead: https://github.com/EdgeTX/edgetx/issues

**Comment by coaster007** [comment]
Hi risto,
This issue is in simulator27 on linux.
But now an update ist only present on converted files from tx16s. If no covertion (new file new model) then the switches are present in simulator.
Greetings
Graziano

**Comment by coaster007** [comment]
Sorry ! my fault posted in the wrong place !
sorry for the inconvenience, Graziano
