### ISSUE TITLE
Function Lua Script repeating after "running" check

### ISSUE THREAD

**Issue by callagga** [opentx/opentx#8872]
When triggering this Function Script from SH↓ switch (switch it down, and it comes up) the "playTone" triggers multiple times during the period when the switch is down, even though I've incorporated a "running" check?   Would be very interested in:

a) is opentx bug, or if now how then to "debounce" this?  
_b) is there a "log" function for debugging to log text/values out to the companion "Debug Output" window?
c) do you have to manually delete the compilted lua file each time or make a change when testing in companion to trigger seeing the effect of the the lua scripts changes one makes_

```
local running = false

local function init_func()
  playTone(264, 100, 0)
end

local function run_func()
  if not running then
    running = true
    playTone(528, 100, 0)
    running = false
  end
end

return { run=run_func, init=init_func }

```

**Comment by 3djc** [comment]
Script is going to be triggered as long as condition is true, not a bug, working as designed. As far as your logic goes, it will not wait for playTone to finish to set running to flase, but this is not the place to debug your lua code
