### ISSUE TITLE
Invert Scrollbar Direction Option Please!

### ISSUE THREAD

**Issue by shahmir-k** [opentx/opentx#8875]
Hello would it be possible to add an option in the OpenTX menu to invert the direction of the selection scroll bar? I have been using my radiomaster tx16s for a very long time and I have built up a lot of muscle memory in navigating the menus with it. 

Recently I purchased a Jumper T-Pro as a lightweight radio to keep in my backpack when going to my classes. Unfortunately the scroll wheel direction is inverted on that radio compared to the TX16s. 

I'd like to be able to make both radios have matching inputs so I can more easily navigate the menus. Currently I'm having a lot of trouble navigating the menus smoothly, and once I'm used the direction on the T-Pro... the same muscle memory problem affects me when I switch back to the radiomaster tx16s at home.

From what I understand the menu, return, and scroll bar buttons are non-configurable unlike all the other switches. I think adding a simple option in the menu to invert the scrollbar would be an easy way to greatly improve the user experience when switching between different radios in my kind of use case. 

Thank you for your consideration!

**Comment by 3djc** [comment]
Available in nightly and upcoming 2.3.15
