### ISSUE TITLE
Getting Assert on Companion23 and Simulator23 after commit a809e94759d436f0592defd689e88083c62c038f

### ISSUE THREAD

**Issue by jtaylor2** [opentx/opentx#8877]
I am getting an ASSERT when running my self built Companion23 or Simulator23 after this mornings commit a809e94759d436f0592defd689e88083c62c038f

ASSERT: "rd.maxSubtype + 1 == (unsigned int) rd.protocols.length()" in file /root/frsky/opentx/git/opentx/companion/src/firmwares/multiprotocols.h, line 65
Aborted (core dumped)

Latest 2.3 branch compiled on openSUSE 15.3

**Comment by 3djc** [comment]
@MRC3742 did you miss something, like Xerall that is not in all lists ?

**Comment by MRC3742** [comment]
@3djc Yes, I forgot to add the string in Companion for Xerall and MT99XX2.
Will add them in a new PR later today.

**Comment by 3djc** [comment]
Cool thanks

**Comment by MRC3742** [comment]
@3djc  @jtaylor2  #8878  should resolve this "Issue"

Rich

**Comment by jtaylor2** [comment]
I'm still the core dump and assert on both Companion and standalone simulator.
Where is the value of rd.maxSubtype set?  I can't find it?

**Comment by 3djc** [comment]
When exactly do you get those?

**Comment by jtaylor2** [comment]
As soon as I try to run them.  Are you able to run the current 2.3 branch?

ASUS-Linux:~/frsky/opentx/git/opentx/build-test # ./simulator23
ASSERT: "rd.maxSubtype + 1 == (unsigned int) rd.protocols.length()" in file /root/frsky/opentx/git/opentx/companion/src/firmwares/multiprotocols.h, line 65
Aborted (core dumped)

**Comment by 3djc** [comment]
Yes, I can run companion just fine, tried selecting a multi module, and select the new protocols, worked fine

**Comment by jtaylor2** [comment]
Must be something with my environment.  I build almost every day and was working fine until that commit.  Will try to see what's wrong with my build environment.

**Comment by 3djc** [comment]
Just pushed a consistency change, does it improve something for you ?

**Comment by jtaylor2** [comment]
Still doesn't work.  It works fine if i comment out that assert.  I don't understand the code enough to know where rd.maxSubtype gets set or what value it should hold.  Maybe something with my options.  I'll create a clean build directory and try with no options.

**Comment by 3djc** [comment]
maybe share what you exactly build so we can try to reproduce

**Comment by jtaylor2** [comment]
cmake -Wno-dev -DCMAKE_BUILD_TYPE=Debug -DPCB=X10 -DPCBREV=TX16S -DDEFAULT_MODE=2 -DEXT=FRSKY -DSDCARD=YES -DPPM_CENTER_ADJUSTABLE=YES -DFLIGHT_MODES=YES -DAUTOSWITCH=YES -DPPM_LIMITS_SYMETRICAL=YES -DAUTOSOURCE=YES -DDBLKEYS=YES -DHELI=YES  -DPPM_UNIT=PERCENT_PREC1 -DGVARS=YES -DFAI=NO -DUNITS=IMPERIAL -DTRANSLATIONS=EN -DHAPTIC=YES -DLUA=YES -DOVERRIDE_CHANNEL_FUNCTION=NO -DMIXERS_MONITOR=YES -DTIMERS=3 -DMULTIMODULE=YES -DALLOW_NIGHTLY_BUILDS=NO -DSIMU_AUDIO=YES ..

Trying now with just PCB=X10 and PCBREV=TX16S

**Comment by jtaylor2** [comment]
Build with just  PCB=X10 and PCBREV=TX16S works.  Something with my options.  I haven't changed them in years.  Will clean them up to just what I need now and if it still fails figure out which one does it.

**Comment by kilrah** [comment]
> cmake -Wno-dev -DCMAKE_BUILD_TYPE=Debug

Looks like the error only shows up on a Debug build, not on a Release one.

**Comment by 3djc** [comment]
Fixed I think, could you confirm ?*

**Comment by jtaylor2** [comment]
Missing coma.....guess that's why asserts are there.  Thanks works fine now.
