### ISSUE TITLE
Jumper t-Pro Boot Screen Contrast very low

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#8879]
The Contrast of the Bootscreen is very low on the Jumper t-pro

i am using 
opentx-tpro-lua-en-2.3.15N647

after bootup the adjusted contrast from the menue is loaded and used.

**Comment by 3djc** [comment]
Not seeing that on two T-Pro. What is your constrast value ?

**Comment by ghost** [comment]
It is at 25 on my tx Menue, but is is ignored at Bootloader and Bootscreen only after bootup it is ok
