### ISSUE TITLE
Jumper t-pro  both 3 pos Switches wrong way at menue

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#8880]
using:

opentx-tpro-lua-en-2.3.15N647

On a new model booth 3 pos switches are showed at the up position but i have to switch it to wards me to get the switch warning clear.
At Betaflight it is the same, switching it up on the Jumper t-Pro is setting it to -100 it should be +100. On all the other TXs the switches have to set down ( away from the Pilot ) to go to -100 on the T-Pro it is the other way.
Please turn it on the Firmware to match it

its Switch SA + SB

**Comment by 3djc** [comment]
While we agree with you, this cannot be changed once the product is on the market. Nor the reviewers nor Jumper themselves made any comment about that, it is therefore too late for that to be changed
