### ISSUE TITLE
Jumper t-Pro trim to subtrim not working

### ISSUE THREAD

**Issue by ghost** [opentx/opentx#8881]
on Version opentx-tpro-lua-en-2.3.15N647

On the T-Pro page 7 ( Outputs ) the " Copy Trim to Subtrim " is not working.
The Trim is not set to Center and the Value is not copyed to the Subtrim Number

the other " Copy to " are not working to

**Comment by 3djc** [comment]
Tested it, working fine here, I guess you are not using enter long enough to have the beep confirmation
