### ISSUE TITLE
STM32__BOOTLOADER driver install and Windows 10 fails consistantly

### ISSUE THREAD

**Issue by Flyswadder** [opentx/opentx#8897]
STM32 Bootloader driver consistanly fails Windows 10 install on multiple machines.

![Dm1](https://user-images.githubusercontent.com/102922050/161443335-0354614b-0aaf-477c-a7cd-bbdb56082e93.PNG)
![Dm2](https://user-images.githubusercontent.com/102922050/161443344-4b4618e8-4fff-4727-967d-2fbf3a0787b9.PNG)

**Comment by 3djc** [comment]
Sorry but what you experience is a local pc issue, not an OpenTX bug

**Comment by Flyswadder** [comment]
It's your driver that refuses to install on ANY windows 10 machine, multiple computers, always the same failure. How is that a "local" pc issues when it doesn't matter what Windows 10 machines, in multiple locations across the country?

**Comment by 3djc** [comment]
What you call our driver is stm32 bootloader, from st electronics, and has nothing to do with OpenTX. If I might add, it used by millions of devices worldwide

**Comment by rotorman** [comment]
@Flyswadder where did you get that driver? For the official ST DFU drivers, download STM32CubeProgrammer, that comes packaged with the original DFU drivers (you need to make a free account at ST to download it); https://www.st.com/en/development-tools/stm32cubeprog.html

**Comment by kilrah** [comment]
1) You shouldn't need dfu drivers in situations other than recovery from a "bricked" radio
2) You use Zadig to install them, those used with Companion are NOT the ST drivers mentioned by @rotorman.

**Comment by Flyswadder** [comment]
This is the source of that file Rotorman: https://www.open-tx.org/2013/07/18/taranis-windows-usb-driver-for-manual-installation.

I have since downloaded the cube file from ST Electronics and it installed, but I'm now not sure what to do with it. I managed to update my bootloader and firmware from an obsolete Win 7 machine that the above software installed properly on.
