### ISSUE TITLE
new firmware

### ISSUE THREAD

**Issue by garrathbond** [opentx/opentx#8908]
![Capture](https://user-images.githubusercontent.com/16117199/164743034-25b41ad7-7b6a-44d6-b3b2-fd9de21b21be.JPG)
I keep getting this am I doing something wrong  (it would also be helpfull if you could actually "copy" the link)

**Comment by 3djc** [comment]
2.3.15 is being released

**Comment by garrathbond** [comment]
what does that mean?

**Comment by garrathbond** [comment]
I can see its being released but I am getting an error is it your end or mine?

**Comment by 3djc** [comment]
literraly thousands of users wanting to download the new version, that all

**Comment by garrathbond** [comment]
Ok so I just need to wait

 

thanks
