### ISSUE TITLE
Deleted Firmware and EEPROM directory

### ISSUE THREAD

**Issue by tommyblue91** [opentx/opentx#8910]
Hello,
I accidently deleted the Taranis Q7's firmware directory and the EEPROM directory (genius).
Now my computer will not recognize the controller when i plug it in.

I've tried giving the controller a factory reset, but it still is not recognized. 

How can I restore these missing files!?

**Comment by 3djc** [comment]
Unrelated, you don't need those directories. Please go to community sites like rcgroups or openrcform for support
