### ISSUE TITLE
[LUA] How to use foreign fonts in LUA scripts?

### ISSUE THREAD

**Issue by LapinFou** [opentx/opentx#8912]
Sorry for the silly question, but I can't find any relevant information.
Look like the special foreign accents are available: [](https://doc.open-tx.org/opentx-2-3-lua-reference-guide/part_vii_-_appendix/fonts#french)
However I don't understand how to use it, for example, with `lcd.drawText` function.

**Comment by 3djc** [comment]
You cannot,it would require some kind of Unicode support, and that would require much more ressources

**Comment by LapinFou** [comment]
Ooh. I see.
So the available fonts here [**Fonts (French)**](https://doc.open-tx.org/opentx-2-3-lua-reference-guide/part_vii_-_appendix/fonts#french) are only use by the OpenTX OS. They cannot be use inside a LUA script.
Did I get it correctly?

I yes, so maybe this section should be removed from the LUA documentation... 😉😋

**Comment by kilrah** [comment]
You can use them with an escape sequence
`"T\128l\128commande:"`

**Comment by 3djc** [comment]
but that only works with matching firmware language (if using english firmware, you'll get garbage)

**Comment by LapinFou** [comment]
Thanks for your answers. To keep it simple, I will stick with the "no accent" solution.
