### ISSUE TITLE
Can't use a switch in setting up a Logical Switch

### ISSUE THREAD

**Issue by mpjf01** [opentx/opentx#8913]
OpenTx 2.3.15. Taranis X9D transmitter. 

Using Transmitter for changing model data. Switches do not appear in the list of parameters available to select from when setting up or modifying a logical switch. Toggling the switch does not make that switch appear in the parameter for selection. Companion functions as normal.

This function works as expected on my X9DP2019 transmitter, my X-Lite and my X9D Plus but not on my older X9D.

**Comment by kilrah** [comment]
Check that the switch types are correct in Hardware settings.

**Comment by mpjf01** [comment]
That was it, thanks. What happens when you buy a Tx from someone and don't check it carefully......
