### ISSUE TITLE
Binding error.

### ISSUE THREAD

**Issue by AlksSAV** [opentx/opentx#8933]
I can't binding my equipment to the FlySky receiver. When it is selected in the menu in the Status item, the message “Prot. invalid”

**Screenshots**
![image](https://user-images.githubusercontent.com/43313549/172834289-a73892c1-860d-438b-803c-7109c9cee980.jpeg)

**General information**
 - OpenTX version 2.3.15
 - Hardware Jumper T-Pro
            Internal RF CC2500

**Comment by 3djc** [comment]
https://github.com/pascallanger/DIY-Multiprotocol-TX-Module/blob/master/Protocols_Details.md#FLYSKY---1

As documented above, flysky protocol is not available with a cc2500 only module
