### ISSUE TITLE
firmware install

### ISSUE THREAD

**Issue by ydyjdwp** [opentx/opentx#8941]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by ydyjdwp** [comment]
Frsky Taranus qx7 running open tx 2.2.0, attempting to upgrade to 2.2.14, when I send to qx7 message is "this version is not compatible with present version on the radio.

**Comment by ydyjdwp** [comment]
I am a total newbe, I am attempting to upgrade my qx7 for use initially with a simulator, sorry if this is invalid, I really want to get this done, and learn something at the same time.  I was attempting the upload through companion. Any help will be greatly appreciated.

**Comment by 3djc** [comment]
You can seek help on community sites like rcgroups.com or openrcforums.com
