### ISSUE TITLE
Archer SR8pro - CH4 goes weird in stabilize mode

### ISSUE THREAD

**Issue by JeffG2022** [opentx/opentx#8960]
This is a problem report with the SR8PRO.  Not sure if this is the place to post.

What I have:
•             Taranis X9D+ SE 2019 with 2.3.15 and SDcard v0039.  I also loaded the latest lua (v2.03) for the SR8 configuration, with ACCESS D16
•             Archer SR8 Pro with 2.1.10 firmware
•             Airplane: E-Flite Turbo Timber Evolution 1.5 PNP.

What I did:
I configured the SR8PRO via the Taranis S.port.  I did a calibration first, then a stabilization setup with the FrSky SxR_R9S.lua script via the Taranis, over the air.

When I connect to the SR8PRO without stabilization, all is good.  Servos center properly, servo travel is good, servo direction is good, servi limits are good, etc  all to my liking.

The problem:
When I add stabilization (using the CH10 switch), the rudder stabilization (CH04) is in the wrong direction. It amplifies the yaw error instead of cancelling it.  So I have to reverse the rudder direction using the  FrSky SxR_R9S.lua script, by selecting Rud direction "inversed".  When I select this inversed, the rudder does reverse, but it also decenters itself badly, with all the travel on the right side and none on the left side.  If I try to readjust the servo centering with the OpenTx output screen, all that happens is that the servo travel become close to none on both sides.  At that point, there is no travel left, even with just operating the Tx stick normally.

If I turn off the stabilization with the CH10 switch (I assigned to SA), or completely off by “disabling” it in the lua script, then the rudder returns to normal, but of course without stabilization.

Other steps taken:
I did the Rx calibration on the desk several times, taking care of getting the right directions on the Rx and installing the Rx in the right position in the plane I tried the Receiver "label up, pins towards tail" and label on left side, pins towards tail", re stabilizing everything every change.  It does the same behavior.

I run self checks from the LUA script (since RX firmware 2.1.10 doesn’t support the fast CH12 switch flicking anymore) after every change to make sure the full travel of servos is properly recorded in the Rx.  I also tried via the PC Freelink app.  Same result.

I can see in the Taranis channel monitor that the rudder signal sent out is centered properly and has normal movement both sides.  It's seems to be the receiver that doesn't operate normally.

I tried reloading the SR8PRO with firmware version 2.19 and 2.1.10.  Same problem.

I tried reversing at the mixing level, at the output level, at the stabilization level.  It’s the last one that breaks it, but that’s the one needed to get the proper rudder direction to correct yaw properly.

Help! 
I do not know what else to try.  Maybe the SR8Pro is broken? Can you help?

I hope that you can provide some help.  

Attached files:
The pdf file is the OpenTX model configuration.
Pictures are captured screens of the stabilize script parameters.  
Also, the last picture (Tried to recenter) shows I have tried to center the rudder when it is experiencing the bug, but the result is almost no travel at all of the rudder. 

![IMG_5638](https://user-images.githubusercontent.com/112654960/187985153-7ba725ae-2583-47dc-a8c0-411e7e76a435.JPG)
![IMG_5639](https://user-images.githubusercontent.com/112654960/187985157-73303f02-fca2-4c74-804d-6f6aeea40ab1.JPG)
![IMG_5640](https://user-images.githubusercontent.com/112654960/187985158-a58d1940-5dfc-4c1a-9f5b-28a3a7dd11f4.JPG)
![IMG_5636](https://user-images.githubusercontent.com/112654960/187985159-dbf4eec0-5a4c-4fa5-bc80-6094d0d6e078.JPG)
![IMG_5637](https://user-images.githubusercontent.com/112654960/187985160-0f686e28-2723-4971-a308-8e8faf29b87f.JPG)
![Tried to recenter](https://user-images.githubusercontent.com/112654960/187985182-b94a27e5-1e55-436b-bf5f-6353014b18d8.JPG)
[Timber SR8pro bug 2022-09-01.pdf](https://github.com/opentx/opentx/files/9472339/Timber.SR8pro.bug.2022-09-01.pdf)

Thanks in advance!

**Comment by 3djc** [comment]
I'm afraid it is not OpenTX related. You should contact FrSky

**Comment by JeffG2022** [comment]
Ok thanks for fast reply
