### ISSUE TITLE
Radiomaster TX16S internal ELRS - add module for rc air/heli too?

### ISSUE THREAD

**Issue by SJurick** [opentx/opentx#8966]
I have a new TX16S with internal ELRS.  Is there a module I can get to add the ability to fly my other non-ELRS models like Specktrum / JR 2.4 protocols?

**Comment by geofrancis** [comment]
you should be able to add a 4 in 1 module in the rear bay.

**Comment by pfeerick** [comment]
Look for a 4IN1 multi-protocol module (MPM) such as the iRangeX IRX4 / iRangeX IRX4 Plus - that will connect to pretty much every other RC protocol available.
