### ISSUE TITLE
Companion update check failed

### ISSUE THREAD

**Issue by Vlady789** [opentx/opentx#8973]
When the companion 2.3.15 is started there is a OpenTX Companion message "Companion update check failed, new version information not found." and then message "Firmware update check failed, new version information not found or invalid. "

General information
 - - OpenTX Companion 2.3.15 on Windows 11
 - - Radio Radiomaster TX16S

**Comment by MacFlieger** [comment]
I have the same problem.
Also I can't download 2.3.15 firmware or SD-Card-content.
I think this is because the SSL-certificate of https://downloads.open-tx.org isn't actual. It ended 30.9.2022.

**Comment by 3djc** [comment]
The person in charge has been notified

**Comment by 3djc** [comment]
The certificate issue has been fixed, sorry for the inconvenience
