### ISSUE TITLE
Si switch in tranis 2019, missing pot and multi position selections, this woud be a great place for a 6 position switchrepalcing the unusful push button

### ISSUE THREAD

**Issue by tj51** [opentx/opentx#8975]
*Before submitting,  search the open issue if there is already a report of the bug*

Also often minor bugs are already fixed in nightly builds, often it is
a good idea to test (in a controlled environment like a bench setup)
with a nightly firmware to see if the bug still exists.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**General information**
 - OpenTX version (e.g. 2.1.23 or N123)
 - Hardware (e.g. Frsky X9D+ or 9X Pro)
 - OpenTX Companion (e.g. 2.1.23 on Ubuntu 16.04)

**Comment by 3djc** [comment]
Hardware wise, switches are connected logical inputs, not analog, cannot become pots (analog)

**Comment by tj51** [comment]
Thank you, I guess the only logical choice is s2, Tj
