### ISSUE TITLE
Download Link for all 2.2 Versions not working 

### ISSUE THREAD

**Issue by SpaceToaster2** [opentx/opentx#8976]
Hi Guys, 

it is not pissible to download any 2.2 Version. 

Link is not working "https://downloads.open-tx.org/2.2/" 

is there a reason? 

Best regards

**Comment by MlCHEL1234** [comment]
Hi,

at

https://downloads.open-tx.org/

you can see, what you can download...

**Comment by 3djc** [comment]
2.2 are i think not available anymore for downloads

**Comment by ghost** [comment]
> 2.2 are i think not available anymore for downloads

Nice, but 2.1 still is.

![Bildschirmfoto_2023-01-10_17-22-12](https://user-images.githubusercontent.com/17964433/211620014-5a9e1992-16b5-427a-867f-8451bef30694.png)

**Comment by 3djc** [comment]
Not firmware for 2.1, so mostly irrelevant

**Comment by ghost** [comment]
But irrelevant 2.1 companion can still be downloaded.

![Bildschirmfoto_2023-01-10_18-56-04](https://user-images.githubusercontent.com/17964433/211627022-ee45df64-5d5b-493d-98d6-f171b5e5f5fe.png)

People here are asking not for companion 2.1, but for 2.2, which for some here still seems to be relevant somehow.

In my case, I have two Taranis X9D here, happy on 2.2.4 and a new Linux Debian version is on the horizon.  So I am looking, what of my software is working on that new version. Therefore I was looking for the companion22_2.2.4_amd64.deb package. I just downloaded companion21_2.1.9_amd64.deb, but that is for sure not helpful.

And I think, I am not alone with that situation.

br KH

**Comment by 0815Creeper** [comment]
duplicate to #8962

developers do not seem to care...

**Comment by ghost** [comment]
I realize here, that I am not alone with my request, and i guess , that only around ~ 1 out of 10 OTX users affected will report here in github on that missing software issues.

br KH

**Comment by ghost** [comment]
2.2.4 is online again!

br KH
