### ISSUE TITLE
Windows 11 issues with OpenTX

### ISSUE THREAD

**Issue by Larryglenn** [opentx/opentx#8998]
Can't seem to connect my opentx transmitters to my computer.  I have a Jumper T16 and Frsky Horus 10s that won't connect to my Windows 11 desktop.  Did a long time ago with Win 10, but set the two computers aside when I got back into Spektrum transmitters.  Want to upgrade the Jumper and Horus with the latest OpenTX/EdgeeTX and start using them again. How do I fix this?

**Comment by 3djc** [comment]
This site is for bug reporting, not end user support. Please go to community sites like rcgroup or openrcforum.
