### ISSUE TITLE
Eachine E130 protocol OpenTX

### ISSUE THREAD

**Issue by pavelajakdal** [opentx/opentx#9008]
Hello, I have the same problem as other users, sometime between 2022 and 2023. I can't pair the Eachine E130 helicopter with the Eachine (Radiomaster) TX16S. The Futaba protocol mentioned in the manual is broken, the E130 protocol according to Youtube (video tutorial about one year old) is broken. The original transmitter is functional. The supplier of both Banggood products refused help or contact to the manufacturer. The manufacturer of the Eachine E130 helicopter must have secretly changed something. It would be nice if someone clever would create an OpenTX protocol that would work for this variant as well. The throttle right control on the original transmitter is unusable nonsense - have you seen anyone control the cyclic with both hands separately? I otherwise use throttle right. Thank you for your help, kind regards.

**Comment by 3djc** [comment]
That's for multi module, not OpenTX. See https://github.com/pascallanger/DIY-Multiprotocol-TX-Module
