### ISSUE TITLE
External RF "R9M Lite Pro" not working

### ISSUE THREAD

**Issue by vbond-app** [opentx/opentx#9009]
**Describe the bug**
I have Jumper T16 Pro with External RF R9M Lite Pro.
Jumper T16 Pro has been hardware modified for support R9M ACCESS.
But i cannot register external receivers.
Reciever FrSky R9 SX.

**To Reproduce**
1. go to radio settings -> external module -> select R9M  ACCESS -> press REGISTER;
2. Nothing happens during the register process; (Waiting ...)

Expected behavior
The expected behavior is a binding between receiver and radio module

**General information**
 - OpenTX version 2.1.15 Jumper T6 PRO  with Externalaccessmod Option
 - Hardware  R9M Lite Pro + FrSky R9 SX (latest firmware)

**Comment by 3djc** [comment]
R9M access is for the access version of 2019 full size. Not sure the lite pro choice is available for your radio. Also did you do the external access mod ?

**Comment by vbond-app** [comment]
Do the R9M Lite pro support?
In the menu section "Modules/RX Versions"  field External information  : "---------------"

**Comment by vbond-app** [comment]
I did everything possible
And checked all nearest smd components

**Comment by 3djc** [comment]
If your radio doesn't offer r9m lite pro choice, then it won't work

**Comment by vbond-app** [comment]
Could u say exactly - do opentx 2.3.15 support R9M lite pro?
The latest version had this comment about the changes: "   RADIOMASTER ZORRO
Support for ELRS and multi version (ELRS require choosing internalELRS in companion options)
Support for small size Access modules (R9M pro,…) "

**Comment by 3djc** [comment]
But you don't have a zorro there, or do I miss something?

**Comment by vbond-app** [comment]
I have Jumper t16 , I think that u soft should support rf module lite too ?
about protocol , look , the same : https://www.frsky-rc.com/product/r9m-lite-pro/


Lighting flashing blue - red  in ‘register ‘ process

**Comment by 3djc** [comment]
The dialog between the radio and the module is different between almost all r9 modules. From memory, we only support small modules on radio equipped with a small module. As said earlier, if you don't have a r9m lite pro, then we don't support it on your radio

**Comment by vbond-app** [comment]
I have r9m lite pro
I think , that u only support large modules 
Could u show me code/file with process of detect module in radio ?
i want change this

**Comment by vbond-app** [comment]
It is not solved yet

**Comment by 3djc** [comment]
We don't support the radio/module configuration, so it is not a bug
