### ISSUE TITLE
Display voltage rather than graphic of battery with bars.

### ISSUE THREAD

**Issue by LBC970** [opentx/opentx#9012]
Horus X10S Express

FW: opentx-x10express
VERS: 2.3.15-otx (1004ef7c)

I have been through the radio and companion, I'm not seeing an option for displaying radio voltage instead of just a graphic of a battery with bars. I have set the battery meter range, but we'd like to display voltage as a number. (7.0v for example.)

Am I just missing it? Is this even an option? If not, can it be? We have 150+ radios running OpenTX and this is one of the most requested changes in the display by our pilots. 

Thanks for your help.

**Comment by 3djc** [comment]
Simply put the numeric value in top bar ?

**Comment by LBC970** [comment]
I would love to do that. I'm not seeing an option for it. I found "BattCheck" but as I understand it that's populated by telemetry from the aircraft. Not the radio voltage.

**Comment by 3djc** [comment]
A simple value widget with vbat as source

**Comment by LBC970** [comment]
Ahhhhhhh, ok. I'll have to look into how to set that up. There's no VBAT option in the list of sources. Thanks for the guidance 3djc.

**Comment by 3djc** [comment]
The exact name in English is probably Batt
