### ISSUE TITLE
Gitbook links are broken

### ISSUE THREAD

**Issue by non-bin** [opentx/opentx#9013]
The links to the user manual, and lua reference guide on the main readme are broken, they take me here:
![image](https://user-images.githubusercontent.com/36313060/235790128-5740948a-acbc-4eae-8a24-19bccd6f8abe.png)

**Comment by pfeerick** [comment]
The user manual link is fine for me, but the lua guide one is broken. edit: Actually, I see the manual link was updated by this commit c3e9abca167a05ee56f234f9e649dc9d9dacb305 but not the lua guide link.
