### ISSUE TITLE
SRx receiver: pitch offset

### ISSUE THREAD

**Issue by Denis56-fr** [opentx/opentx#9043]
Hi, I use SRx for my motogliders. After initial climb, at motor cut-off, I automatically engage the Automatic Level mode for 5 second so the glider starts gliding without losing any altitude.  I would like to add to this feature another one: I would like to use the Automatic Level during the climb, which means: auto level setup 1 with plane pitch +35⁰ and auto level setup 2 with plane pitch 0⁰, switchable in flight. In SRx stable LUA, there is a pitch offset setting that would do the job, if it could be configured in flight. Maybe it is possible through a LUA script, maybe not. No useful answer from Frsky, already contacted. Any insight? Thanks!

Same under ETHOS, of course.

**Comment by 3djc** [comment]
Not possible
