### ISSUE TITLE
ilter on vendor = 0x0483 product = 0xdf11

### ISSUE THREAD

**Issue by shiron007** [opentx/opentx#9045]
Hello,
My name is Liron,
I have a RADIOMASTER TX16S device and I use OpenTX Companion v2.3.
I am trying to back up the Firmware, Settings and my Models,
I turn on my radio device in Bootloader v2.10.1 mode, connecting with the original USB cable that came with the device,
I enter the software in the correct profile and click on "Read Firmware from Radio" and get the following error:

C:/Program Files (x86)/OpenTX/Companion 2.3/dfu-util.exe -a 0 --dfuse-address 0x08000000:2097152 --device 0483:df11 -UG:/MyStorage//My_RadioMaster_TX16s/Companion profile/Backups/Companion backup folder/My_30-06-2024.bin

=================================================================================

dfu-util 0.7
Copyright 2005-2008 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2012 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to [dfu-util@lists.gnumonks.org](mailto:dfu-util@lists.gnumonks.org)
Filter on vendor = 0x0483 product = 0xdf11
No DFU capable USB device found
=================================================================================
I tried to change the USB cable and also put the remote in Normal and the same error was received.
Hope you can help me :-|

**Comment by 3djc** [comment]
Dfu is done with radio turned off

**Comment by gagarinlg** [comment]
And even more importantly, 2.10 is EdgeTX and the companion version must match the radio version to have things working correctly
