### ISSUE TITLE
fine/float adjustment for GVars

### ISSUE THREAD

**Issue by arronbates** [opentx/opentx#905]
This may be a 2.1 feature, but for what it's worth... now that the GVars work awesome for servo/input offsets (super nice feature), incrementing/decrementing a GVar by one changes the servo output by 5us. The subtrims are able to increment by 0.1 along with super fine trim adjustment, would also be cool if by choice (in the gvar screen of model menu maybe) if global variables could also get the option of fine adjustment.

I have a work-around by using an unused mixer line to get a fraction of a variable (assign gvar to offset, then weight that back into another mix)... but others may not find the work-around all that appealing.

**Comment by bsongis** [comment]
Refactoring explained in #3185
