### ISSUE TITLE
Add proper helicopter support to the Wizard

### ISSUE THREAD

**Issue by Dvogonen** [opentx/opentx#906]
Mixing for helicopters is complex. Having proper support for this in the model Wizard would be a great addition.

**Comment by richarddeweerd** [comment]
If you need some assistance with this, I'm a heli pilot and I'm trying to get my head around the open tx tool chain. So I can at least help with the basic setup for the Flybar and flybar-less setups.

**Comment by bsongis** [comment]
You don't need a toolchain for the Wizard, it's only plain text.

**Comment by richarddeweerd** [comment]
That is true, but currently there is no way to create a curve with LUA. So the other option is to add the wizard to the companion.

**Comment by bsongis** [comment]
Is it the next thing which is needed to continue? I would add it shortly then!

**Comment by richarddeweerd** [comment]
That would be great. For a heli with a fly-bar you also must be able to set the swash plate type and cyclic info. (Basically all info on the Heli page in companion)
For a Flybar-less heli the curves are enough. I'll start tonight with the script and I will create it

**Comment by kilrah** [comment]
#2120

**Comment by schwabe** [comment]
@richarddeweerd I have only a small flybar-less heli (Nano CPX), but I am willing to test and assist you with whatever you need to need to complete the wizard.

**Comment by richarddeweerd** [comment]
I can test most of it my self but it would be nice if someone else can help testing, sometimes as a developer you're blind for some obvious issues or usability errors.

I have a nano CPS myself, so if you need my EPEE file give me a email on richard at deweerd dot biz

**Comment by schwabe** [comment]
My problem as most OpenTX developer is just that I have no idea, how a "good" helicopter setup looks. What I have for my nano cp x work for me but it is probably far from what a real helicopter pilot would consider a good setup. Therefore as someone who is really inexperience with Helicopter setup but (albeit recent) OpenTX developer I am probably a good candidate for testing a Helicopter setup wizard. :)

**Comment by richarddeweerd** [comment]
This should be linked to this also:

https://github.com/opentx/opentx/issues/1647

**Comment by bazsound** [comment]
i wizard shouldnt be that difficult. helicopter setups are simple atleast from a standard setup point of view and thats all it has to be is a simple standard setup which has 2 or three flight modes.

flight mode 0 can be linear on throttle and on collective channel -20 -20 0 50 100
flight mode 1 throttel curve flat 80 collective linbear
flight mode 2 throttle curve flat 95 collective linear.

everything else is a simple mix when dealing with flybarless helis as theres no swash mixing. Surely a non helicopter pilot familair with open tx can easily make this kind of setup

**Comment by bazsound** [comment]
essentially all your doing is changing curves for 2 channe,ls

**Comment by Eldenroot** [comment]
+1, at least for flybarless units...

**Comment by kilrah** [comment]
Flybarless units don't need anything complex, and many need different stuff. You've got to figure it out yourself, pointless to try and make a wizard. 
It's for flybar that it's more "complicated" but more standard and a wizard can work.

**Comment by mbalun** [comment]
Finally joined a new openTX (had a tgy9x with one for long and now got a Horus X10) so can contribute. I would like to participate in the setup of the helli wizard but I dont have to much programming skills (not that I dont want to learn them, but I wouldn't trust them :) ). I could put out the logic which than somebody can easily follow in the programming. I fly Hellis :)

The "minimum" I would like to have is a helli Icon for the model instead of be forced to use a plane or quad :)
