### ISSUE TITLE
new feature: to view telemetry graphs on the taranis display

### ISSUE THREAD

**Issue by snawaratne** [opentx/opentx#960]
Just came to my mind, why not have the option use the logs generated via taranis directly on the Tx to display a particular graph.

the screen resolution could be an issue, but say just to inspect a particular graph on the field, say for example amps and volts. 

would be awesome!

**Comment by janekx** [comment]
+1

**Comment by Eldenroot** [comment]
+1

**Comment by lshems** [comment]
See repository.justfly.solutions for free versions of this feature.
